ESPResSo++: /home/espressopp/espressopp/src/main/_espressopp.cpp File Reference
_espressopp.cpp File Reference
#include "acconfig.hpp"
#include "espressopp_common.hpp"
#include "python.hpp"
Functions
static void finalize ()
BOOST_PYTHON_MODULE (_espressopp)
Function Documentation
BOOST_PYTHON_MODULE()
BOOST_PYTHON_MODULE (_espressopp)
Definition at line 33 of file _espressopp.cpp.
References finalize(), initMPIEnv(), and espressopp::registerPython().
finalize()
void finalize () static
Definition at line 43 of file _espressopp.cpp.
References finalizeMPIEnv().
Referenced by BOOST_PYTHON_MODULE().