ESPResSo++: espressopp::interaction::AngularHarmonic Class Reference
espressopp::interaction::AngularHarmonic Class Reference
This class provides methods to compute forces and energies of the AngularHarmonic angular potential.
#include <AngularHarmonic.hpp>
Public Member Functions
AngularHarmonic ()
AngularHarmonic (real _K, real _theta0)
void setK (real _K)
real getK () const
void setTheta0 (real _theta0)
real getTheta0 () const
real _computeEnergyRaw (real _theta) const
bool _computeForceRaw (Real3D &force12, Real3D &force32, const Real3D &dist12, const Real3D &dist32) const
real _computeForceRaw (const real theta) const
virtual real computeEnergy (const Particle &p1, const Particle &p2, const Particle &p3) const
virtual real computeEnergy (const Real3D &dist12, const Real3D &dist32) const
virtual real computeEnergy (const real theta) const
virtual void computeForce (Real3D &force12, Real3D &force32, const Particle &p1, const Particle &p2, const Particle &p3) const
virtual void computeForce (Real3D &force12, Real3D &force32, const Real3D &dist12, const Real3D &dist32) const
virtual real computeForce (real theta) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)
virtual shared_ptr< FixedPairList > getColVarBondList () const
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &fpl)
virtual shared_ptr< FixedTripleList > getColVarAngleList () const
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fpl)
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const
virtual void setColVar (const RealND &cv)
virtual void setColVar (const Real3D &dist12, const Real3D &dist32, const bc::BC &bc)
virtual RealND getColVar () const
virtual void computeColVarWeights (const Real3D &dist12, const Real3D &dist32, const bc::BC &bc)
real _computeEnergy (const Particle &p1, const Particle &p2, const Particle &p3) const
real _computeEnergy (const Real3D &dist12, const Real3D &dist32) const
real _computeEnergy (real theta) const
void _computeForce (Real3D &force12, Real3D &force32, const Particle &p1, const Particle &p2, const Particle &p3) const
bool _computeForce (Real3D &force12, Real3D &force32, const Real3D &dist12, const Real3D &dist32) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
AngularHarmonic * derived_this ()
const AngularHarmonic * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
shared_ptr< FixedPairList > colVarBondList
shared_ptr< FixedTripleList > colVarAngleList
shared_ptr< FixedQuadrupleList > colVarDihedList
RealND colVar
Private Attributes
real K
real theta0
Detailed Description
This class provides methods to compute forces and energies of the AngularHarmonic angular potential.
To create a new angular potential one only needs to write the setter/getters and the variable dU_dtheta.
Definition at line 37 of file AngularHarmonic.hpp.
Constructor & Destructor Documentation
AngularHarmonic() [1/2]
espressopp::interaction::AngularHarmonic::AngularHarmonic () inline
Definition at line 45 of file AngularHarmonic.hpp.
AngularHarmonic() [2/2]
espressopp::interaction::AngularHarmonic::AngularHarmonic (real _K, real _theta0) inline
Definition at line 46 of file AngularHarmonic.hpp.
Member Function Documentation
_computeEnergy() [1/3]
real espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::_computeEnergy (const Particle & p1, const Particle & p2, const Particle & p3) const inline inherited
Definition at line 290 of file AngularPotential.hpp.
_computeEnergy() [2/3]
real espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::_computeEnergy (const Real3D & dist12, const Real3D & dist32) const inline inherited
Definition at line 299 of file AngularPotential.hpp.
_computeEnergy() [3/3]
real espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::_computeEnergy (real theta) const inline inherited
Definition at line 314 of file AngularPotential.hpp.
_computeEnergyRaw()
real espressopp::interaction::AngularHarmonic::_computeEnergyRaw (real _theta) const inline
Definition at line 54 of file AngularHarmonic.hpp.
_computeForce() [1/2]
void espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::_computeForce (Real3D & force12, Real3D & force32, const Particle & p1, const Particle & p2, const Particle & p3) const inline inherited
Definition at line 343 of file AngularPotential.hpp.
_computeForce() [2/2]
bool espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::_computeForce (Real3D & force12, Real3D & force32, const Real3D & dist12, const Real3D & dist32) const inline inherited
Definition at line 354 of file AngularPotential.hpp.
_computeForceRaw() [1/2]
bool espressopp::interaction::AngularHarmonic::_computeForceRaw (Real3D & force12, Real3D & force32, const Real3D & dist12, const Real3D & dist32) const inline
Definition at line 83 of file AngularHarmonic.hpp.
References theta0.
_computeForceRaw() [2/2]
real espressopp::interaction::AngularHarmonic::_computeForceRaw (const real theta) const inline
Definition at line 117 of file AngularHarmonic.hpp.
References theta0.
computeColVarWeights()
void espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::computeColVarWeights (const Real3D & dist12, const Real3D & dist32, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 255 of file AngularPotential.hpp.
computeEnergy() [1/3]
real espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::computeEnergy (const Particle & p1, const Particle & p2, const Particle & p3) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 264 of file AngularPotential.hpp.
computeEnergy() [2/3]
real espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::computeEnergy (const Real3D & dist12, const Real3D & dist32) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 273 of file AngularPotential.hpp.
computeEnergy() [3/3]
real espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::computeEnergy (const real theta) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 283 of file AngularPotential.hpp.
computeForce() [1/3]
void espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::computeForce (Real3D & force12, Real3D & force32, const Particle & p1, const Particle & p2, const Particle & p3) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 322 of file AngularPotential.hpp.
computeForce() [2/3]
void espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::computeForce (Real3D & force12, Real3D & force32, const Real3D & dist12, const Real3D & dist32) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 333 of file AngularPotential.hpp.
computeForce() [3/3]
real espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::computeForce (real theta) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 366 of file AngularPotential.hpp.
derived_this() [1/2]
AngularHarmonic * espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::derived_this () inline protected inherited
Definition at line 154 of file AngularPotential.hpp.
derived_this() [2/2]
const AngularHarmonic * espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::derived_this () const inline protected inherited
Definition at line 158 of file AngularPotential.hpp.
getColVar()
RealND espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::getColVar () const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 249 of file AngularPotential.hpp.
getColVarAngleList()
shared_ptr< FixedTripleList > espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::getColVarAngleList () const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 212 of file AngularPotential.hpp.
getColVarBondList()
shared_ptr< FixedPairList > espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::getColVarBondList () const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 198 of file AngularPotential.hpp.
getColVarDihedList()
shared_ptr< FixedQuadrupleList > espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::getColVarDihedList () const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 226 of file AngularPotential.hpp.
getCutoff()
real espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 184 of file AngularPotential.hpp.
getK()
real espressopp::interaction::AngularHarmonic::getK () const inline
Definition at line 49 of file AngularHarmonic.hpp.
References K.
Referenced by registerPython().
getTheta0()
real espressopp::interaction::AngularHarmonic::getTheta0 () const inline
Definition at line 52 of file AngularHarmonic.hpp.
References theta0.
Referenced by registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::AngularPotential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
registerPython()
void espressopp::interaction::AngularHarmonic::registerPython () static
Definition at line 33 of file AngularHarmonic.cpp.
References getK(), getTheta0(), setK(), and setTheta0().
Referenced by espressopp::interaction::registerPython().
setColVar() [1/2]
void espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::setColVar (const RealND & cv) inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 233 of file AngularPotential.hpp.
setColVar() [2/2]
void espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::setColVar (const Real3D & dist12, const Real3D & dist32, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 240 of file AngularPotential.hpp.
setColVarAngleList()
void espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::setColVarAngleList (const shared_ptr< FixedTripleList > & fpl) inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 205 of file AngularPotential.hpp.
setColVarBondList()
void espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::setColVarBondList (const shared_ptr< FixedPairList > & fpl) inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 191 of file AngularPotential.hpp.
setColVarDihedList()
void espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fpl) inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 219 of file AngularPotential.hpp.
setCutoff()
void espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 176 of file AngularPotential.hpp.
setK()
void espressopp::interaction::AngularHarmonic::setK (real _K) inline
Definition at line 48 of file AngularHarmonic.hpp.
Referenced by registerPython().
setTheta0()
void espressopp::interaction::AngularHarmonic::setTheta0 (real _theta0) inline
Definition at line 51 of file AngularHarmonic.hpp.
Referenced by registerPython().
Member Data Documentation
colVar
RealND espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::colVar protected inherited
Definition at line 152 of file AngularPotential.hpp.
colVarAngleList
shared_ptr<FixedTripleList> espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::colVarAngleList protected inherited
Definition at line 148 of file AngularPotential.hpp.
colVarBondList
shared_ptr<FixedPairList> espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::colVarBondList protected inherited
Definition at line 146 of file AngularPotential.hpp.
colVarDihedList
shared_ptr<FixedQuadrupleList> espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::colVarDihedList protected inherited
Definition at line 150 of file AngularPotential.hpp.
cutoff
real espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::cutoff protected inherited
Definition at line 143 of file AngularPotential.hpp.
cutoffSqr
real espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >::cutoffSqr protected inherited
Definition at line 144 of file AngularPotential.hpp.
K
real espressopp::interaction::AngularHarmonic::K private
Definition at line 39 of file AngularHarmonic.hpp.
Referenced by getK().
theta0
real espressopp::interaction::AngularHarmonic::theta0 private
Definition at line 40 of file AngularHarmonic.hpp.
Referenced by _computeForceRaw(), and getTheta0().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/AngularHarmonic.hpp
/home/espressopp/espressopp/src/interaction/AngularHarmonic.cpp