ESPResSo++: espressopp::vectorization::interaction::VerletListLennardJones Class Reference
espressopp::vectorization::interaction::VerletListLennardJones Class Reference
#include <VerletListLennardJones.hpp>
Classes
struct LJCoefficients
Public Member Functions
VerletListLennardJones (shared_ptr< VerletList > _verletList)
virtual ~VerletListLennardJones ()
void setVerletList (shared_ptr< VerletList > _verletList)
shared_ptr< VerletList > getVerletList ()
void setPotential (int type1, int type2, const Potential &potential)
Potential & getPotential (int type1, int type2)
shared_ptr< Potential > getPotentialPtr (int type1, int type2)
void rebuildPotential ()
template<bool ONETYPE, bool VEC_MODE_AOS>
void addForces_impl ()
virtual void addForces ()
virtual real computeEnergy ()
virtual real computeEnergyDeriv ()
virtual real computeEnergyAA ()
virtual real computeEnergyCG ()
virtual real computeEnergyAA (int atomtype)
virtual real computeEnergyCG (int atomtype)
virtual void computeVirialX (std::vector< real > &p_xx_total, int bins)
virtual real computeVirial ()
virtual void computeVirialTensor (Tensor &w)
virtual void computeVirialTensor (Tensor &w, real z)
virtual void computeVirialTensor (Tensor *w, int n)
virtual real getMaxCutoff ()
This method returns the maximal cutoff defined for one type pair.
virtual int bondType ()
Static Public Member Functions
static void registerPython ()
Protected Types
typedef LennardJones _Potential
typedef _Potential Potential
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Protected Attributes
int ntypes
shared_ptr< VerletList > verletList
esutil::Array2D< Potential, esutil::enlarge > potentialArray
size_t np_types
size_t p_types
AlignedVector< LJCoefficients > ffs
AlignedVector< real > cutoffSqr
bool needRebuildPotential = true
Detailed Description
Definition at line 52 of file VerletListLennardJones.hpp.
Member Typedef Documentation
_Potential
typedef LennardJones espressopp::vectorization::interaction::VerletListLennardJones::_Potential protected
Definition at line 55 of file VerletListLennardJones.hpp.
Potential
typedef _Potential espressopp::vectorization::interaction::VerletListLennardJones::Potential protected
Definition at line 56 of file VerletListLennardJones.hpp.
Constructor & Destructor Documentation
VerletListLennardJones()
espressopp::vectorization::interaction::VerletListLennardJones::VerletListLennardJones (shared_ptr< VerletList > _verletList) inline
Definition at line 66 of file VerletListLennardJones.hpp.
References np_types, ntypes, p_types, and potentialArray.
~VerletListLennardJones()
virtual espressopp::vectorization::interaction::VerletListLennardJones::~VerletListLennardJones () inline virtual
Definition at line 75 of file VerletListLennardJones.hpp.
Member Function Documentation
addForces()
void espressopp::vectorization::interaction::VerletListLennardJones::addForces () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 157 of file VerletListLennardJones.hpp.
References addForces_impl(), getPotential(), LOG4ESPP_DEBUG, needRebuildPotential, np_types, p_types, rebuildPotential(), and verletList.
Referenced by rebuildPotential().
addForces_impl()
template<bool ONETYPE, bool VEC_MODE_AOS> void espressopp::vectorization::interaction::VerletListLennardJones::addForces_impl () inline
Definition at line 182 of file VerletListLennardJones.hpp.
References computeEnergy(), cutoffSqr, ffs, np_types, espressopp::vectorization::Real3DInt::t, verletList, espressopp::vectorization::Real3DInt::x, espressopp::vectorization::Real4D::x, espressopp::vectorization::Real3DInt::y, and espressopp::vectorization::Real3DInt::z.
Referenced by addForces(), and rebuildPotential().
bondType()
virtual int espressopp::vectorization::interaction::VerletListLennardJones::bondType () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 138 of file VerletListLennardJones.hpp.
References espressopp::interaction::Nonbonded.
computeEnergy()
real espressopp::vectorization::interaction::VerletListLennardJones::computeEnergy () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 336 of file VerletListLennardJones.hpp.
References espressopp::interaction::PotentialTemplate< Derived >::_computeEnergy(), computeEnergyDeriv(), getPotential(), getVerletList(), espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_DEBUG, LOG4ESPP_TRACE, espressopp::Particle::type(), and verletList.
Referenced by addForces_impl(), and rebuildPotential().
computeEnergyAA() [1/2]
real espressopp::vectorization::interaction::VerletListLennardJones::computeEnergyAA () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 369 of file VerletListLennardJones.hpp.
References LOG4ESPP_WARN.
Referenced by computeEnergyDeriv(), and rebuildPotential().
computeEnergyAA() [2/2]
real espressopp::vectorization::interaction::VerletListLennardJones::computeEnergyAA (int atomtype) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 376 of file VerletListLennardJones.hpp.
References computeEnergyCG(), and LOG4ESPP_WARN.
computeEnergyCG() [1/2]
real espressopp::vectorization::interaction::VerletListLennardJones::computeEnergyCG () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 383 of file VerletListLennardJones.hpp.
References LOG4ESPP_WARN.
Referenced by computeEnergyAA(), and rebuildPotential().
computeEnergyCG() [2/2]
real espressopp::vectorization::interaction::VerletListLennardJones::computeEnergyCG (int atomtype) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 390 of file VerletListLennardJones.hpp.
References computeVirialX(), and LOG4ESPP_WARN.
computeEnergyDeriv()
real espressopp::vectorization::interaction::VerletListLennardJones::computeEnergyDeriv () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 362 of file VerletListLennardJones.hpp.
References computeEnergyAA(), and LOG4ESPP_WARN.
Referenced by computeEnergy(), and rebuildPotential().
computeVirial()
real espressopp::vectorization::interaction::VerletListLennardJones::computeVirial () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 403 of file VerletListLennardJones.hpp.
References espressopp::interaction::PotentialTemplate< Derived >::_computeForce(), computeVirialTensor(), getPotential(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_DEBUG, mpiWorld, espressopp::Particle::position(), espressopp::Particle::type(), and verletList.
Referenced by computeVirialX(), and rebuildPotential().
computeVirialTensor() [1/3]
void espressopp::vectorization::interaction::VerletListLennardJones::computeVirialTensor (Tensor & w) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 432 of file VerletListLennardJones.hpp.
References espressopp::interaction::PotentialTemplate< Derived >::_computeForce(), getPotential(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_DEBUG, mpiWorld, espressopp::Particle::position(), espressopp::Particle::type(), and verletList.
Referenced by computeVirial(), computeVirialTensor(), and rebuildPotential().
computeVirialTensor() [2/3]
void espressopp::vectorization::interaction::VerletListLennardJones::computeVirialTensor (Tensor & w, real z) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 462 of file VerletListLennardJones.hpp.
References espressopp::interaction::PotentialTemplate< Derived >::_computeForce(), espressopp::System::bc, computeVirialTensor(), getPotential(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_DEBUG, mpiWorld, espressopp::Particle::position(), espressopp::Particle::type(), and verletList.
computeVirialTensor() [3/3]
void espressopp::vectorization::interaction::VerletListLennardJones::computeVirialTensor (Tensor * w, int n) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 519 of file VerletListLennardJones.hpp.
References espressopp::interaction::PotentialTemplate< Derived >::_computeForce(), espressopp::System::bc, getMaxCutoff(), getPotential(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_DEBUG, mpiWorld, espressopp::Particle::position(), espressopp::Particle::type(), and verletList.
computeVirialX()
void espressopp::vectorization::interaction::VerletListLennardJones::computeVirialX (std::vector< real > & p_xx_total, int bins) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 397 of file VerletListLennardJones.hpp.
References computeVirial(), and LOG4ESPP_WARN.
Referenced by computeEnergyCG(), and rebuildPotential().
getMaxCutoff()
real espressopp::vectorization::interaction::VerletListLennardJones::getMaxCutoff () inline virtual
This method returns the maximal cutoff defined for one type pair.
Implements espressopp::interaction::Interaction.
Definition at line 592 of file VerletListLennardJones.hpp.
References getPotential(), and ntypes.
Referenced by computeVirialTensor(), and rebuildPotential().
getPotential()
Potential& espressopp::vectorization::interaction::VerletListLennardJones::getPotential (int type1, int type2) inline
Definition at line 100 of file VerletListLennardJones.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), needRebuildPotential, potentialArray, espressopp::esutil::Array2D< T, outlier_mode >::size_m(), and espressopp::esutil::Array2D< T, outlier_mode >::size_n().
Referenced by addForces(), computeEnergy(), computeVirial(), computeVirialTensor(), and getMaxCutoff().
getPotentialPtr()
shared_ptr<Potential> espressopp::vectorization::interaction::VerletListLennardJones::getPotentialPtr (int type1, int type2) inline
Definition at line 106 of file VerletListLennardJones.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), and potentialArray.
Referenced by espressopp::vectorization::interaction::LennardJones::registerPython().
getVerletList()
shared_ptr<VerletList> espressopp::vectorization::interaction::VerletListLennardJones::getVerletList () inline
Definition at line 82 of file VerletListLennardJones.hpp.
References verletList.
Referenced by computeEnergy(), and espressopp::vectorization::interaction::LennardJones::registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Interaction::LOG4ESPP_DECL_LOGGER (theLogger) static protected inherited
Logger.
Referenced by espressopp::interaction::Interaction::~Interaction().
rebuildPotential()
void espressopp::vectorization::interaction::VerletListLennardJones::rebuildPotential () inline
Definition at line 110 of file VerletListLennardJones.hpp.
References addForces(), addForces_impl(), computeEnergy(), computeEnergyAA(), computeEnergyCG(), computeEnergyDeriv(), computeVirial(), computeVirialTensor(), computeVirialX(), cutoffSqr, ffs, getMaxCutoff(), espressopp::vectorization::interaction::VerletListLennardJones::LJCoefficients::LJCoefficients(), needRebuildPotential, np_types, p_types, potentialArray, espressopp::esutil::Array2D< T, outlier_mode >::size_m(), and espressopp::esutil::Array2D< T, outlier_mode >::size_n().
Referenced by addForces(), and setPotential().
registerPython()
void espressopp::interaction::Interaction::registerPython () static inherited
Definition at line 36 of file Interaction.cpp.
References espressopp::interaction::Interaction::bondType(), espressopp::interaction::Interaction::computeEnergy(), espressopp::interaction::Interaction::computeEnergyAA(), espressopp::interaction::Interaction::computeEnergyCG(), espressopp::interaction::Interaction::computeEnergyDeriv(), and espressopp::interaction::Interaction::computeVirial().
Referenced by espressopp::interaction::registerPython(), and espressopp::interaction::Interaction::~Interaction().
setPotential()
void espressopp::vectorization::interaction::VerletListLennardJones::setPotential (int type1, int type2, const Potential & potential) inline
Definition at line 87 of file VerletListLennardJones.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), LOG4ESPP_INFO, ntypes, potentialArray, and rebuildPotential().
Referenced by espressopp::vectorization::interaction::LennardJones::registerPython().
setVerletList()
void espressopp::vectorization::interaction::VerletListLennardJones::setVerletList (shared_ptr< VerletList > _verletList) inline
Definition at line 78 of file VerletListLennardJones.hpp.
References verletList.
Member Data Documentation
cutoffSqr
AlignedVector<real> espressopp::vectorization::interaction::VerletListLennardJones::cutoffSqr protected
Definition at line 148 of file VerletListLennardJones.hpp.
Referenced by addForces_impl(), and rebuildPotential().
ffs
AlignedVector<LJCoefficients> espressopp::vectorization::interaction::VerletListLennardJones::ffs protected
Definition at line 147 of file VerletListLennardJones.hpp.
Referenced by addForces_impl(), and rebuildPotential().
needRebuildPotential
bool espressopp::vectorization::interaction::VerletListLennardJones::needRebuildPotential = true protected
Definition at line 149 of file VerletListLennardJones.hpp.
Referenced by addForces(), getPotential(), and rebuildPotential().
np_types
size_t espressopp::vectorization::interaction::VerletListLennardJones::np_types protected
Definition at line 146 of file VerletListLennardJones.hpp.
Referenced by addForces(), addForces_impl(), rebuildPotential(), and VerletListLennardJones().
ntypes
int espressopp::vectorization::interaction::VerletListLennardJones::ntypes protected
Definition at line 141 of file VerletListLennardJones.hpp.
Referenced by getMaxCutoff(), setPotential(), and VerletListLennardJones().
p_types
size_t espressopp::vectorization::interaction::VerletListLennardJones::p_types protected
Definition at line 146 of file VerletListLennardJones.hpp.
Referenced by addForces(), rebuildPotential(), and VerletListLennardJones().
potentialArray
esutil::Array2D<Potential, esutil::enlarge> espressopp::vectorization::interaction::VerletListLennardJones::potentialArray protected
Definition at line 143 of file VerletListLennardJones.hpp.
Referenced by getPotential(), getPotentialPtr(), rebuildPotential(), setPotential(), and VerletListLennardJones().
verletList
shared_ptr<VerletList> espressopp::vectorization::interaction::VerletListLennardJones::verletList protected
Definition at line 142 of file VerletListLennardJones.hpp.
Referenced by addForces(), addForces_impl(), computeEnergy(), computeVirial(), computeVirialTensor(), getVerletList(), and setVerletList().
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/vectorization/interaction/VerletListLennardJones.hpp