ESPResSo++: espressopp::integrator::LBInitPopUniform Class Reference
espressopp::integrator::LBInitPopUniform Class Reference
#include <LBInitPopUniform.hpp>
Public Member Functions
LBInitPopUniform (shared_ptr< System > _system, shared_ptr< LatticeBoltzmann > _latticeboltzmann)
void createDenVel (real _rho0, Real3D _u0)
void setForce (Real3D _force)
void addForce (Real3D _force)
Static Public Member Functions
static void registerPython ()
Protected Attributes
shared_ptr< LatticeBoltzmann > latticeboltzmann
real rho0
Real3D u0
Detailed Description
Definition at line 30 of file LBInitPopUniform.hpp.
Constructor & Destructor Documentation
espressopp::integrator::LBInitPopUniform::LBInitPopUniform (shared_ptr< System > _system, shared_ptr< LatticeBoltzmann > _latticeboltzmann)
Definition at line 29 of file LBInitPopUniform.cpp.
Member Function Documentation
void espressopp::integrator::LBInitPopUniform::addForce (Real3D _force) [virtual]
Implements espressopp::integrator::LBInit.
Definition at line 78 of file LBInitPopUniform.cpp.
void espressopp::integrator::LBInitPopUniform::createDenVel (real _rho0, Real3D _u0) [virtual]
Implements espressopp::integrator::LBInit.
Definition at line 34 of file LBInitPopUniform.cpp.
References espressopp::Int3D::getItem(), espressopp::Real3D::getItem(), espressopp::integrator::LBInit::latticeboltzmann, and mpiWorld.
Referenced by registerPython().
void espressopp::integrator::LBInitPopUniform::registerPython () [static]
Reimplemented from espressopp::integrator::LBInit.
Definition at line 80 of file LBInitPopUniform.cpp.
References createDenVel().
Referenced by espressopp::integrator::registerPython().
void espressopp::integrator::LBInitPopUniform::setForce (Real3D _force) [virtual]
Implements espressopp::integrator::LBInit.
Definition at line 77 of file LBInitPopUniform.cpp.
Member Data Documentation
shared_ptr<LatticeBoltzmann> espressopp::integrator::LBInit::latticeboltzmann [protected, inherited]
Definition at line 52 of file LBInit.hpp.
Referenced by espressopp::integrator::LBInitConstForce::addForce(), espressopp::integrator::LBInitPeriodicForce::addForce(), createDenVel(), espressopp::integrator::LBInitPopWave::createDenVel(), espressopp::integrator::LBInit::LBInit(), espressopp::integrator::LBInitConstForce::setForce(), and espressopp::integrator::LBInitPeriodicForce::setForce().
real espressopp::integrator::LBInit::rho0 [protected, inherited]
Definition at line 53 of file LBInit.hpp.
Real3D espressopp::integrator::LBInit::u0 [protected, inherited]
Definition at line 54 of file LBInit.hpp.
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/integrator/LBInitPopUniform.hpp
/home/travis/build/espressopp/espressopp/src/integrator/LBInitPopUniform.cpp