ESPResSo++: espressopp::interaction::PotentialVSpherePair Class Reference
espressopp::interaction::PotentialVSpherePair Class Reference abstract
#include <PotentialVSpherePair.hpp>
Public Member Functions
virtual ~PotentialVSpherePair ()
virtual real computeEnergy (const Particle &p1, const Particle &p2) const =0
virtual real computeEnergy (const Real3D &dist, real &sigmaij) const =0
virtual real computeEnergy (real dist, real sigmaij) const =0
virtual real computeEnergySqr (real distSqr, real sigmaij) const =0
virtual python::list computeForce (const Particle &p1, const Particle &p2) const =0
virtual python::list computeForce (const Real3D &dist, const real &sigmai, const real &sigmaj) const =0
virtual void setCutoff (real _cutoff)=0
virtual real getCutoff () const =0
virtual void setShift (real _shift)=0
virtual real getShift () const =0
virtual real setAutoShift ()=0
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Detailed Description
Definition at line 34 of file PotentialVSpherePair.hpp.
Constructor & Destructor Documentation
~PotentialVSpherePair()
virtual espressopp::interaction::PotentialVSpherePair::~PotentialVSpherePair () inline virtual
Definition at line 36 of file PotentialVSpherePair.hpp.
References computeEnergy(), computeEnergySqr(), computeForce(), getCutoff(), getShift(), LOG4ESPP_DECL_LOGGER(), registerPython(), setAutoShift(), setCutoff(), and setShift().
Member Function Documentation
computeEnergy() [1/3]
virtual real espressopp::interaction::PotentialVSpherePair::computeEnergy (const Particle & p1, const Particle & p2) const pure virtual
Implemented in espressopp::interaction::PotentialVSpherePairTemplate< Derived >, and espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >.
Referenced by registerPython(), ~PotentialVSpherePair(), and espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::~PotentialVSpherePairTemplate().
computeEnergy() [2/3]
virtual real espressopp::interaction::PotentialVSpherePair::computeEnergy (const Real3D & dist, real & sigmaij) const pure virtual
Implemented in espressopp::interaction::PotentialVSpherePairTemplate< Derived >, and espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >.
computeEnergy() [3/3]
virtual real espressopp::interaction::PotentialVSpherePair::computeEnergy (real dist, real sigmaij) const pure virtual
Implemented in espressopp::interaction::PotentialVSpherePairTemplate< Derived >, and espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >.
computeEnergySqr()
virtual real espressopp::interaction::PotentialVSpherePair::computeEnergySqr (real distSqr, real sigmaij) const pure virtual
Implemented in espressopp::interaction::PotentialVSpherePairTemplate< Derived >, and espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >.
Referenced by ~PotentialVSpherePair(), and espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::~PotentialVSpherePairTemplate().
computeForce() [1/2]
virtual python::list espressopp::interaction::PotentialVSpherePair::computeForce (const Particle & p1, const Particle & p2) const pure virtual
Implemented in espressopp::interaction::PotentialVSpherePairTemplate< Derived >, and espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >.
Referenced by registerPython(), ~PotentialVSpherePair(), and espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::~PotentialVSpherePairTemplate().
computeForce() [2/2]
virtual python::list espressopp::interaction::PotentialVSpherePair::computeForce (const Real3D & dist, const real & sigmai, const real & sigmaj) const pure virtual
Implemented in espressopp::interaction::PotentialVSpherePairTemplate< Derived >, and espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >.
getCutoff()
virtual real espressopp::interaction::PotentialVSpherePair::getCutoff () const pure virtual
Implemented in espressopp::interaction::PotentialVSpherePairTemplate< Derived >, and espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >.
Referenced by registerPython(), ~PotentialVSpherePair(), and espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::~PotentialVSpherePairTemplate().
getShift()
virtual real espressopp::interaction::PotentialVSpherePair::getShift () const pure virtual
Implemented in espressopp::interaction::PotentialVSpherePairTemplate< Derived >, and espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >.
Referenced by registerPython(), ~PotentialVSpherePair(), and espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::~PotentialVSpherePairTemplate().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::PotentialVSpherePair::LOG4ESPP_DECL_LOGGER (theLogger) static
Referenced by ~PotentialVSpherePair().
registerPython()
void espressopp::interaction::PotentialVSpherePair::registerPython () static
Definition at line 35 of file PotentialVSpherePair.cpp.
References computeEnergy(), computeForce(), getCutoff(), getShift(), setAutoShift(), setCutoff(), and setShift().
Referenced by espressopp::interaction::registerPython(), and ~PotentialVSpherePair().
setAutoShift()
virtual real espressopp::interaction::PotentialVSpherePair::setAutoShift () pure virtual
Implemented in espressopp::interaction::PotentialVSpherePairTemplate< Derived >, and espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >.
Referenced by registerPython(), ~PotentialVSpherePair(), and espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::~PotentialVSpherePairTemplate().
setCutoff()
virtual void espressopp::interaction::PotentialVSpherePair::setCutoff (real _cutoff) pure virtual
Implemented in espressopp::interaction::PotentialVSpherePairTemplate< Derived >, and espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >.
Referenced by registerPython(), ~PotentialVSpherePair(), and espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::~PotentialVSpherePairTemplate().
setShift()
virtual void espressopp::interaction::PotentialVSpherePair::setShift (real _shift) pure virtual
Implemented in espressopp::interaction::PotentialVSpherePairTemplate< Derived >, and espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >.
Referenced by registerPython(), ~PotentialVSpherePair(), and espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::~PotentialVSpherePairTemplate().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/PotentialVSpherePair.hpp
/home/espressopp/espressopp/src/interaction/PotentialVSpherePair.cpp