ESPResSo++: espressopp::FixedSingleList Class Reference
espressopp::FixedSingleList Class Reference
#include <FixedSingleList.hpp>
Public Types
typedef std::set< longint > GlobalSingles
typedef ESPPIterator
< std::vector< ParticleSingle > > Iterator
Public Member Functions
FixedSingleList (shared_ptr< storage::Storage > _storage)
virtual ~FixedSingleList ()
virtual bool add (longint pid1)
Add the given particle to the list on this processor if the particle belongs to this processor.
virtual void beforeSendParticles (ParticleList &pl, class OutBuffer &buf)
void afterRecvParticles (ParticleList &pl, class InBuffer &buf)
virtual void onParticlesChanged ()
python::list getSingles ()
GlobalSingles * getGlobalSingles ()
int size ()
Get the number of particles in the GlobalSingle list.
void add (Particle *p)
void add (Particle &p)
void add (std::vector< Particle * > particles)
Static Public Member Functions
static void registerPython ()
Protected Types
typedef std::vector
< ParticleSingle > Super
Protected Attributes
boost::signals2::connection con1
boost::signals2::connection con2
boost::signals2::connection con3
shared_ptr< storage::Storage > storage
GlobalSingles globalSingles
Static Private Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Detailed Description
Definition at line 37 of file FixedSingleList.hpp.
Member Typedef Documentation
typedef std::set<longint> espressopp::FixedSingleList::GlobalSingles
Definition at line 39 of file FixedSingleList.hpp.
typedef ESPPIterator<std::vector< ParticleSingle > > espressopp::esutil::ESPPContainer< std::vector< ParticleSingle > >::Iterator [inherited]
Definition at line 66 of file ESPPIterator.hpp.
typedef std::vector< ParticleSingle > espressopp::esutil::ESPPContainer< std::vector< ParticleSingle > >::Super [protected, inherited]
Definition at line 64 of file ESPPIterator.hpp.
Constructor & Destructor Documentation
espressopp::FixedSingleList::FixedSingleList (shared_ptr< storage::Storage > _storage)
Definition at line 39 of file FixedSingleList.cpp.
References afterRecvParticles(), beforeSendParticles(), con1, con2, con3, LOG4ESPP_INFO, onParticlesChanged(), and storage.
espressopp::FixedSingleList::~FixedSingleList () [virtual]
Definition at line 52 of file FixedSingleList.cpp.
References con1, con2, con3, and LOG4ESPP_INFO.
Member Function Documentation
bool espressopp::FixedSingleList::add (longint pid1) [virtual]
Add the given particle to the list on this processor if the particle belongs to this processor.
Note that this routine does not check whether the particle is inserted on another processor as well.
Returns:
whether the particle was inserted on this processor.
Definition at line 62 of file FixedSingleList.cpp.
References espressopp::System::comm, globalSingles, LOG4ESPP_INFO, and storage.
Referenced by onParticlesChanged(), and registerPython().
void espressopp::SingleList::add (Particle * p) [inline, inherited]
Definition at line 365 of file Particle.hpp.
Referenced by espressopp::SingleList::add().
void espressopp::SingleList::add (Particle & p) [inline, inherited]
Definition at line 369 of file Particle.hpp.
References espressopp::SingleList::add().
void espressopp::SingleList::add (std::vector< Particle * > particles) [inline, inherited]
Definition at line 373 of file Particle.hpp.
References espressopp::SingleList::add().
void espressopp::FixedSingleList::afterRecvParticles (ParticleList & pl, class InBuffer & buf)
Definition at line 115 of file FixedSingleList.cpp.
References globalSingles, LOG4ESPP_INFO, espressopp::InBuffer::read(), and size().
Referenced by FixedSingleList().
void espressopp::FixedSingleList::beforeSendParticles (ParticleList & pl, class OutBuffer & buf) [virtual]
Definition at line 101 of file FixedSingleList.cpp.
References globalSingles, espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_DEBUG, LOG4ESPP_INFO, and espressopp::OutBuffer::write().
Referenced by FixedSingleList().
GlobalSingles* espressopp::FixedSingleList::getGlobalSingles () [inline]
Definition at line 63 of file FixedSingleList.hpp.
References globalSingles.
python::list espressopp::FixedSingleList::getSingles ()
Definition at line 89 of file FixedSingleList.cpp.
References globalSingles.
Referenced by registerPython().
static espressopp::FixedSingleList::LOG4ESPP_DECL_LOGGER (theLogger) [static, private]
void espressopp::FixedSingleList::onParticlesChanged () [virtual]
Definition at line 126 of file FixedSingleList.cpp.
References add(), espressopp::esutil::Error::checkException(), espressopp::System::comm, globalSingles, LOG4ESPP_INFO, espressopp::esutil::Error::setException(), and storage.
Referenced by FixedSingleList().
void espressopp::FixedSingleList::registerPython () [static]
Definition at line 150 of file FixedSingleList.cpp.
References add(), getSingles(), and size().
Referenced by espressopp::registerPython().
int espressopp::FixedSingleList::size () [inline]
Get the number of particles in the GlobalSingle list.
Definition at line 66 of file FixedSingleList.hpp.
References globalSingles.
Referenced by afterRecvParticles(), and registerPython().
Member Data Documentation
boost::signals2::connection espressopp::FixedSingleList::con1 [protected]
Definition at line 42 of file FixedSingleList.hpp.
Referenced by FixedSingleList(), and ~FixedSingleList().
boost::signals2::connection espressopp::FixedSingleList::con2 [protected]
Definition at line 42 of file FixedSingleList.hpp.
Referenced by FixedSingleList(), and ~FixedSingleList().
boost::signals2::connection espressopp::FixedSingleList::con3 [protected]
Definition at line 42 of file FixedSingleList.hpp.
Referenced by FixedSingleList(), and ~FixedSingleList().
GlobalSingles espressopp::FixedSingleList::globalSingles [protected]
Definition at line 44 of file FixedSingleList.hpp.
Referenced by add(), afterRecvParticles(), beforeSendParticles(), getGlobalSingles(), getSingles(), onParticlesChanged(), and size().
shared_ptr<storage::Storage> espressopp::FixedSingleList::storage [protected]
Definition at line 43 of file FixedSingleList.hpp.
Referenced by add(), FixedSingleList(), and onParticlesChanged().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/FixedSingleList.hpp
/home/travis/build/espressopp/espressopp/src/FixedSingleList.cpp