ESPResSo++: espressopp::interaction::TabulatedSubEnsDihedral Class Reference
espressopp::interaction::TabulatedSubEnsDihedral Class Reference
#include <TabulatedSubEnsDihedral.hpp>
Public Member Functions
TabulatedSubEnsDihedral ()
void addInteraction (int itype, boost::python::str fname, const RealND &_cvref)
void setDimension (int _dim)
int getDimension () const
void setInterpolationType (int itype)
Setter for the interpolation type.
int getInterpolationType () const
Getter for the interpolation type.
RealND getTargetProb () const
void setTargetProb (int index, real _r)
RealND getColVarSds () const
void setColVarSd (int index, real _r)
RealND getColVarRef (int i) const
RealNDs getColVarRefs () const
void setColVarRef (const RealNDs &cvRefs)
void setColVarRefs (const RealNDs &c)
boost::python::list getFilenames () const
boost::python::list getFilename (int index) const
void setFilename (int index, boost::python::list _f)
void setFilenames (int dim, int itype, boost::python::list _filenames)
RealND getWeights () const
void setWeights (const RealND &r)
real getWeight (int index) const
void setWeight (int index, real _w)
real getAlpha () const
void setAlpha (real _r)
void computeColVarWeights (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43, const bc::BC &bc)
void setColVar (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43, const bc::BC &bc)
real _computeEnergyRaw (real phi) const
real d (int i, int j) const
Real3D prod (Real3D a, Real3D b) const
Compute dot product of two vectors.
void _computeForceRaw (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &r21, const Real3D &r32, const Real3D &r43) const
real _computeForceRaw (real phi) const
virtual real computeEnergy (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
virtual real computeEnergy (real phi) const
virtual void computeForce (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
virtual real computeForce (real phi) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)
virtual shared_ptr< FixedPairList > getColVarBondList () const
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &ftl)
virtual shared_ptr< FixedTripleList > getColVarAngleList () const
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fql)
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const
virtual void setColVar (const RealND &cv)
virtual RealND getColVar () const
real _computeEnergy (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
real _computeEnergy (real phi) const
void _computeForce (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
Static Public Member Functions
static void registerPython ()
static real computePhi (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43)
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
TabulatedSubEnsDihedral * derived_this ()
const TabulatedSubEnsDihedral * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
shared_ptr< FixedPairList > colVarBondList
shared_ptr< FixedTripleList > colVarAngleList
shared_ptr< FixedQuadrupleList > colVarDihedList
RealND colVar
Private Attributes
int numInteractions
std::vector< std::string > filenames
std::vector< shared_ptr< Interpolation > > tables
int interpolationType
RealNDs colVarRef
RealND weights
RealND targetProb
RealND weightSum
int weightCounts
RealND colVarSd
real alpha
int colVarBondListSize
int colVarAngleListSize
int colVarDihedListSize
Detailed Description
Definition at line 33 of file TabulatedSubEnsDihedral.hpp.
Constructor & Destructor Documentation
TabulatedSubEnsDihedral()
espressopp::interaction::TabulatedSubEnsDihedral::TabulatedSubEnsDihedral () inline
Definition at line 61 of file TabulatedSubEnsDihedral.hpp.
References addInteraction(), espressopp::infinity, espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::setCutoff(), espressopp::RealND::setDimension(), and espressopp::RealNDs::setDimension().
Member Function Documentation
_computeEnergy() [1/2]
real espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::_computeEnergy (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline inherited
Definition at line 285 of file DihedralPotential.hpp.
_computeEnergy() [2/2]
real espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::_computeEnergy (real phi) const inline inherited
Definition at line 295 of file DihedralPotential.hpp.
_computeEnergyRaw()
real espressopp::interaction::TabulatedSubEnsDihedral::_computeEnergyRaw (real phi) const inline
Definition at line 152 of file TabulatedSubEnsDihedral.hpp.
References numInteractions.
_computeForce()
void espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::_computeForce (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline inherited
Definition at line 317 of file DihedralPotential.hpp.
_computeForceRaw() [1/2]
void espressopp::interaction::TabulatedSubEnsDihedral::_computeForceRaw (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & r21, const Real3D & r32, const Real3D & r43) const inline
Definition at line 178 of file TabulatedSubEnsDihedral.hpp.
References espressopp::Real3D::cross(), d(), M_PI, numInteractions, prod(), and espressopp::Real3D::sqr().
_computeForceRaw() [2/2]
real espressopp::interaction::TabulatedSubEnsDihedral::_computeForceRaw (real phi) const inline
Definition at line 261 of file TabulatedSubEnsDihedral.hpp.
References numInteractions.
addInteraction()
void espressopp::interaction::TabulatedSubEnsDihedral::addInteraction (int itype, boost::python::str fname, const RealND & _cvref)
Definition at line 59 of file TabulatedSubEnsDihedral.cpp.
References colVarRef, filenames, numInteractions, espressopp::RealND::push_back(), espressopp::RealNDs::setDimension(), tables, targetProb, weights, and weightSum.
Referenced by registerPython(), and TabulatedSubEnsDihedral().
computeColVarWeights()
void espressopp::interaction::TabulatedSubEnsDihedral::computeColVarWeights (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43, const bc::BC & bc) virtual
Reimplemented from espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >.
Definition at line 95 of file TabulatedSubEnsDihedral.cpp.
References alpha, espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::colVar, colVarBondListSize, colVarDihedListSize, colVarRef, colVarSd, espressopp::RealND::getDimension(), M_PI, numInteractions, setColVar(), targetProb, weightCounts, weights, and weightSum.
Referenced by setAlpha().
computeEnergy() [1/2]
real espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::computeEnergy (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 265 of file DihedralPotential.hpp.
computeEnergy() [2/2]
real espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::computeEnergy (real phi) const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 278 of file DihedralPotential.hpp.
computeForce() [1/2]
void espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::computeForce (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 303 of file DihedralPotential.hpp.
computeForce() [2/2]
real espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::computeForce (real phi) const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 331 of file DihedralPotential.hpp.
computePhi()
real espressopp::interaction::DihedralPotential::computePhi (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) static inherited
Definition at line 31 of file DihedralPotential.cpp.
References espressopp::Real3D::abs(), espressopp::Real3D::cross(), and espressopp::interaction::LOG4ESPP_LOGGER().
Referenced by espressopp::interaction::DihedralPotential::registerPython(), setColVar(), espressopp::interaction::TabulatedSubEnsAngular::setColVar(), and espressopp::interaction::TabulatedSubEns::setColVar().
d()
real espressopp::interaction::TabulatedSubEnsDihedral::d (int i, int j) const inline
Definition at line 160 of file TabulatedSubEnsDihedral.hpp.
Referenced by _computeForceRaw(), and prod().
derived_this() [1/2]
TabulatedSubEnsDihedral * espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::derived_this () inline protected inherited
Definition at line 154 of file DihedralPotential.hpp.
derived_this() [2/2]
const TabulatedSubEnsDihedral * espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::derived_this () const inline protected inherited
Definition at line 158 of file DihedralPotential.hpp.
getAlpha()
real espressopp::interaction::TabulatedSubEnsDihedral::getAlpha () const inline
Definition at line 142 of file TabulatedSubEnsDihedral.hpp.
References alpha.
Referenced by espressopp::interaction::TabulatedSubEnsDihedral_pickle::getinitargs(), and registerPython().
getColVar()
RealND espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::getColVar () const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 250 of file DihedralPotential.hpp.
getColVarAngleList()
shared_ptr< FixedTripleList > espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::getColVarAngleList () const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 213 of file DihedralPotential.hpp.
getColVarBondList()
shared_ptr< FixedPairList > espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::getColVarBondList () const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 199 of file DihedralPotential.hpp.
getColVarDihedList()
shared_ptr< FixedQuadrupleList > espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::getColVarDihedList () const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 227 of file DihedralPotential.hpp.
getColVarRef()
RealND espressopp::interaction::TabulatedSubEnsDihedral::getColVarRef (int i) const inline
Definition at line 109 of file TabulatedSubEnsDihedral.hpp.
Referenced by registerPython().
getColVarRefs()
RealNDs espressopp::interaction::TabulatedSubEnsDihedral::getColVarRefs () const inline
Definition at line 111 of file TabulatedSubEnsDihedral.hpp.
References colVarRef, and setColVarRef().
Referenced by espressopp::interaction::TabulatedSubEnsDihedral_pickle::getinitargs(), and registerPython().
getColVarSds()
RealND espressopp::interaction::TabulatedSubEnsDihedral::getColVarSds () const inline
Definition at line 103 of file TabulatedSubEnsDihedral.hpp.
References colVarSd.
Referenced by espressopp::interaction::TabulatedSubEnsDihedral_pickle::getinitargs(), and registerPython().
getCutoff()
real espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 185 of file DihedralPotential.hpp.
getDimension()
int espressopp::interaction::TabulatedSubEnsDihedral::getDimension () const inline
Definition at line 89 of file TabulatedSubEnsDihedral.hpp.
References numInteractions.
Referenced by espressopp::interaction::TabulatedSubEnsDihedral_pickle::getinitargs(), and registerPython().
getFilename()
boost::python::list espressopp::interaction::TabulatedSubEnsDihedral::getFilename (int index) const inline
Definition at line 120 of file TabulatedSubEnsDihedral.hpp.
Referenced by registerPython().
getFilenames()
boost::python::list espressopp::interaction::TabulatedSubEnsDihedral::getFilenames () const inline
Definition at line 117 of file TabulatedSubEnsDihedral.hpp.
Referenced by espressopp::interaction::TabulatedSubEnsDihedral_pickle::getinitargs(), and registerPython().
getInterpolationType()
int espressopp::interaction::TabulatedSubEnsDihedral::getInterpolationType () const inline
Getter for the interpolation type.
Definition at line 95 of file TabulatedSubEnsDihedral.hpp.
References interpolationType.
Referenced by espressopp::interaction::TabulatedSubEnsDihedral_pickle::getinitargs().
getTargetProb()
RealND espressopp::interaction::TabulatedSubEnsDihedral::getTargetProb () const inline
Definition at line 97 of file TabulatedSubEnsDihedral.hpp.
References targetProb.
Referenced by registerPython().
getWeight()
real espressopp::interaction::TabulatedSubEnsDihedral::getWeight (int index) const inline
Definition at line 134 of file TabulatedSubEnsDihedral.hpp.
References espressopp::RealND::getItem().
getWeights()
RealND espressopp::interaction::TabulatedSubEnsDihedral::getWeights () const inline
Definition at line 130 of file TabulatedSubEnsDihedral.hpp.
References weights.
Referenced by registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::DihedralPotential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
prod()
Real3D espressopp::interaction::TabulatedSubEnsDihedral::prod (Real3D a, Real3D b) const inline
Compute dot product of two vectors.
Definition at line 168 of file TabulatedSubEnsDihedral.hpp.
References d().
Referenced by _computeForceRaw().
registerPython()
void espressopp::interaction::TabulatedSubEnsDihedral::registerPython () static
Definition at line 240 of file TabulatedSubEnsDihedral.cpp.
References addInteraction(), getAlpha(), getColVarRef(), getColVarRefs(), getColVarSds(), getDimension(), getFilename(), getFilenames(), getTargetProb(), getWeights(), setAlpha(), setColVarSd(), setFilename(), setTargetProb(), and setWeight().
Referenced by espressopp::interaction::registerPython().
setAlpha()
void espressopp::interaction::TabulatedSubEnsDihedral::setAlpha (real _r) inline
Definition at line 144 of file TabulatedSubEnsDihedral.hpp.
References computeColVarWeights(), and setColVar().
Referenced by registerPython().
setColVar() [1/2]
void espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::setColVar (const RealND & cv) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 234 of file DihedralPotential.hpp.
setColVar() [2/2]
void espressopp::interaction::TabulatedSubEnsDihedral::setColVar (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43, const bc::BC & bc) virtual
Reimplemented from espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >.
Definition at line 173 of file TabulatedSubEnsDihedral.cpp.
References espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::colVar, espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::colVarAngleList, colVarAngleListSize, espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::colVarBondList, colVarBondListSize, espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::colVarDihedList, colVarDihedListSize, espressopp::interaction::DihedralPotential::computePhi(), espressopp::bc::BC::getMinimumImageVectorBox(), espressopp::Particle::position(), and espressopp::RealND::setDimension().
Referenced by computeColVarWeights(), and setAlpha().
setColVarAngleList()
void espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::setColVarAngleList (const shared_ptr< FixedTripleList > & ftl) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 206 of file DihedralPotential.hpp.
setColVarBondList()
void espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::setColVarBondList (const shared_ptr< FixedPairList > & fpl) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 192 of file DihedralPotential.hpp.
setColVarDihedList()
void espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fql) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 220 of file DihedralPotential.hpp.
setColVarRef()
void espressopp::interaction::TabulatedSubEnsDihedral::setColVarRef (const RealNDs & cvRefs)
Definition at line 87 of file TabulatedSubEnsDihedral.cpp.
References colVarRef, and numInteractions.
Referenced by getColVarRefs().
setColVarRefs()
void espressopp::interaction::TabulatedSubEnsDihedral::setColVarRefs (const RealNDs & c) inline
Definition at line 115 of file TabulatedSubEnsDihedral.hpp.
setColVarSd()
void espressopp::interaction::TabulatedSubEnsDihedral::setColVarSd (int index, real _r) inline
Definition at line 105 of file TabulatedSubEnsDihedral.hpp.
References espressopp::RealND::setItem().
Referenced by registerPython().
setCutoff()
void espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 177 of file DihedralPotential.hpp.
Referenced by TabulatedSubEnsDihedral().
setDimension()
void espressopp::interaction::TabulatedSubEnsDihedral::setDimension (int _dim) inline
Definition at line 79 of file TabulatedSubEnsDihedral.hpp.
References espressopp::RealND::setDimension(), and espressopp::RealNDs::setDimension().
setFilename()
void espressopp::interaction::TabulatedSubEnsDihedral::setFilename (int index, boost::python::list _f) inline
Definition at line 124 of file TabulatedSubEnsDihedral.hpp.
References setFilenames().
Referenced by registerPython().
setFilenames()
void espressopp::interaction::TabulatedSubEnsDihedral::setFilenames (int dim, int itype, boost::python::list _filenames)
Definition at line 33 of file TabulatedSubEnsDihedral.cpp.
References colVarRef, filenames, numInteractions, espressopp::RealNDs::setDimension(), and tables.
Referenced by setFilename().
setInterpolationType()
void espressopp::interaction::TabulatedSubEnsDihedral::setInterpolationType (int itype) inline
Setter for the interpolation type.
Definition at line 92 of file TabulatedSubEnsDihedral.hpp.
setTargetProb()
void espressopp::interaction::TabulatedSubEnsDihedral::setTargetProb (int index, real _r) inline
Definition at line 99 of file TabulatedSubEnsDihedral.hpp.
References espressopp::RealND::setItem().
Referenced by registerPython().
setWeight()
void espressopp::interaction::TabulatedSubEnsDihedral::setWeight (int index, real _w) inline
Definition at line 138 of file TabulatedSubEnsDihedral.hpp.
References espressopp::RealND::setItem().
Referenced by registerPython().
setWeights()
void espressopp::interaction::TabulatedSubEnsDihedral::setWeights (const RealND & r) inline
Definition at line 132 of file TabulatedSubEnsDihedral.hpp.
Member Data Documentation
alpha
real espressopp::interaction::TabulatedSubEnsDihedral::alpha private
Definition at line 52 of file TabulatedSubEnsDihedral.hpp.
Referenced by computeColVarWeights(), and getAlpha().
colVar
RealND espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::colVar protected inherited
Definition at line 152 of file DihedralPotential.hpp.
Referenced by computeColVarWeights(), and setColVar().
colVarAngleList
shared_ptr<FixedTripleList> espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::colVarAngleList protected inherited
Definition at line 148 of file DihedralPotential.hpp.
Referenced by setColVar().
colVarAngleListSize
int espressopp::interaction::TabulatedSubEnsDihedral::colVarAngleListSize private
Definition at line 55 of file TabulatedSubEnsDihedral.hpp.
Referenced by setColVar().
colVarBondList
shared_ptr<FixedPairList> espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::colVarBondList protected inherited
Definition at line 146 of file DihedralPotential.hpp.
Referenced by setColVar().
colVarBondListSize
int espressopp::interaction::TabulatedSubEnsDihedral::colVarBondListSize private
Definition at line 54 of file TabulatedSubEnsDihedral.hpp.
Referenced by computeColVarWeights(), and setColVar().
colVarDihedList
shared_ptr<FixedQuadrupleList> espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::colVarDihedList protected inherited
Definition at line 150 of file DihedralPotential.hpp.
Referenced by setColVar().
colVarDihedListSize
int espressopp::interaction::TabulatedSubEnsDihedral::colVarDihedListSize private
Definition at line 56 of file TabulatedSubEnsDihedral.hpp.
Referenced by computeColVarWeights(), and setColVar().
colVarRef
RealNDs espressopp::interaction::TabulatedSubEnsDihedral::colVarRef private
Definition at line 41 of file TabulatedSubEnsDihedral.hpp.
Referenced by addInteraction(), computeColVarWeights(), getColVarRefs(), setColVarRef(), and setFilenames().
colVarSd
RealND espressopp::interaction::TabulatedSubEnsDihedral::colVarSd private
Definition at line 50 of file TabulatedSubEnsDihedral.hpp.
Referenced by computeColVarWeights(), and getColVarSds().
cutoff
real espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::cutoff protected inherited
Definition at line 143 of file DihedralPotential.hpp.
cutoffSqr
real espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >::cutoffSqr protected inherited
Definition at line 144 of file DihedralPotential.hpp.
filenames
std::vector<std::string> espressopp::interaction::TabulatedSubEnsDihedral::filenames private
Definition at line 37 of file TabulatedSubEnsDihedral.hpp.
Referenced by addInteraction(), and setFilenames().
interpolationType
int espressopp::interaction::TabulatedSubEnsDihedral::interpolationType private
Definition at line 39 of file TabulatedSubEnsDihedral.hpp.
Referenced by getInterpolationType().
numInteractions
int espressopp::interaction::TabulatedSubEnsDihedral::numInteractions private
Definition at line 36 of file TabulatedSubEnsDihedral.hpp.
Referenced by _computeEnergyRaw(), _computeForceRaw(), addInteraction(), computeColVarWeights(), getDimension(), setColVarRef(), and setFilenames().
tables
std::vector<shared_ptr <Interpolation> > espressopp::interaction::TabulatedSubEnsDihedral::tables private
Definition at line 38 of file TabulatedSubEnsDihedral.hpp.
Referenced by addInteraction(), and setFilenames().
targetProb
RealND espressopp::interaction::TabulatedSubEnsDihedral::targetProb private
Definition at line 45 of file TabulatedSubEnsDihedral.hpp.
Referenced by addInteraction(), computeColVarWeights(), and getTargetProb().
weightCounts
int espressopp::interaction::TabulatedSubEnsDihedral::weightCounts private
Definition at line 48 of file TabulatedSubEnsDihedral.hpp.
Referenced by computeColVarWeights().
weights
RealND espressopp::interaction::TabulatedSubEnsDihedral::weights private
Definition at line 43 of file TabulatedSubEnsDihedral.hpp.
Referenced by addInteraction(), computeColVarWeights(), and getWeights().
weightSum
RealND espressopp::interaction::TabulatedSubEnsDihedral::weightSum private
Definition at line 47 of file TabulatedSubEnsDihedral.hpp.
Referenced by addInteraction(), and computeColVarWeights().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/TabulatedSubEnsDihedral.hpp
/home/espressopp/espressopp/src/interaction/TabulatedSubEnsDihedral.cpp