ESPResSo++: espressopp::RealND Class Reference
espressopp::RealND Class Reference
#include <RealND.hpp>
Public Types
typedef real * iterator
Public Member Functions
void setDimension (int _dim)
int getDimension () const
RealND ()
RealND (int d)
RealND (int d, real v)
RealND (const RealND &v)
RealND (const int _dim, const std::vector< real > &v)
RealND (const boost::python::list &l)
RealND & operator= (const RealND &v)
real & operator[] (int i)
const real & operator[] (int i) const
real & at (int i)
const real & at (int i) const
void setItem (int i, real v)
real getItem (int i) const
RealND & operator+= (const RealND &v)
RealND & operator-= (const RealND &v)
RealND & operator*= (const real v)
RealND & operator/= (const real v)
bool operator== (const RealND &v) const
bool operator!= (const RealND &v) const
RealND operator+ (const RealND &v) const
RealND operator- (const RealND &v) const
RealND operator* (real v) const
RealND operator/ (real v) const
real operator* (const RealND &v) const
real sqr () const
real abs () const
iterator begin ()
iterator end ()
const real * get () const
real * get ()
void push_back (real r)
Static Public Member Functions
static void registerPython ()
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::vector< real > data
int dimension
Friends
class boost::serialization::access
Detailed Description
Definition at line 35 of file RealND.hpp.
Member Typedef Documentation
iterator
typedef real* espressopp::RealND::iterator
Definition at line 57 of file RealND.hpp.
Constructor & Destructor Documentation
RealND() [1/6]
espressopp::RealND::RealND () inline
Definition at line 161 of file RealND.hpp.
References setDimension().
Referenced by operator*(), espressopp::operator*(), operator+(), operator-(), and operator/().
RealND() [2/6]
espressopp::RealND::RealND (int d) inline
Definition at line 162 of file RealND.hpp.
References setDimension().
RealND() [3/6]
espressopp::RealND::RealND (int d, real v) inline
Definition at line 164 of file RealND.hpp.
References data, and setDimension().
RealND() [4/6]
espressopp::RealND::RealND (const RealND & v) inline
Definition at line 170 of file RealND.hpp.
References data, getDimension(), and setDimension().
RealND() [5/6]
espressopp::RealND::RealND (const int _dim, const std::vector< real > & v) inline
Definition at line 176 of file RealND.hpp.
References data, and setDimension().
RealND() [6/6]
espressopp::RealND::RealND (const boost::python::list & l) inline
Definition at line 188 of file RealND.hpp.
References data, and setDimension().
Member Function Documentation
abs()
real espressopp::RealND::abs () const inline
Definition at line 314 of file RealND.hpp.
References sqr().
Referenced by registerPython().
at() [1/2]
real & espressopp::RealND::at (int i) inline
Definition at line 210 of file RealND.hpp.
References getDimension().
Referenced by espressopp::RealNDs::getDimension(), getItem(), and setItem().
at() [2/2]
const real & espressopp::RealND::at (int i) const inline
Definition at line 216 of file RealND.hpp.
References getDimension().
begin()
RealND::iterator espressopp::RealND::begin () inline
Definition at line 317 of file RealND.hpp.
References data.
Referenced by espressopp::io::DumpGROAdress::dump(), and espressopp::io::DumpGRO::dump().
end()
RealND::iterator espressopp::RealND::end () inline
Definition at line 318 of file RealND.hpp.
References data, and dimension.
get() [1/2]
const real* espressopp::RealND::get () const inline
Definition at line 106 of file RealND.hpp.
get() [2/2]
real* espressopp::RealND::get () inline
Definition at line 107 of file RealND.hpp.
References push_back(), and registerPython().
getDimension()
int espressopp::RealND::getDimension () const inline
Definition at line 55 of file RealND.hpp.
References dimension.
Referenced by at(), espressopp::interaction::TabulatedSubEnsDihedral::computeColVarWeights(), espressopp::interaction::TabulatedSubEnsAngular::computeColVarWeights(), espressopp::interaction::TabulatedSubEns::computeColVarWeights(), espressopp::io::DumpXTCAdress::dump(), espressopp::io::DumpXTC::dump(), espressopp::realND_pickle_suite::getinitargs(), operator*(), operator+=(), operator-=(), espressopp::operator<<(), operator=(), operator==(), push_back(), RealND(), registerPython(), and espressopp::analysis::ConfigurationExt::set().
getItem()
real espressopp::RealND::getItem (int i) const inline
Definition at line 225 of file RealND.hpp.
References at().
Referenced by espressopp::RealNDs::getDimension(), espressopp::interaction::TabulatedSubEnsDihedral::getWeight(), espressopp::interaction::TabulatedSubEnsAngular::getWeight(), espressopp::interaction::TabulatedSubEns::getWeight(), and registerPython().
operator!=()
bool espressopp::RealND::operator!= (const RealND & v) const inline
Definition at line 275 of file RealND.hpp.
operator*() [1/2]
RealND espressopp::RealND::operator* (real v) const inline
Definition at line 285 of file RealND.hpp.
References RealND().
Referenced by espressopp::RealNDs::getDimension().
operator*() [2/2]
real espressopp::RealND::operator* (const RealND & v) const inline
Definition at line 292 of file RealND.hpp.
References data, dimension, and getDimension().
operator*=()
RealND & espressopp::RealND::operator*= (const real v) inline
Definition at line 249 of file RealND.hpp.
References data, and dimension.
operator+()
RealND espressopp::RealND::operator+ (const RealND & v) const inline
Definition at line 279 of file RealND.hpp.
References RealND().
operator+=()
RealND & espressopp::RealND::operator+= (const RealND & v) inline
Definition at line 229 of file RealND.hpp.
References data, dimension, and getDimension().
operator-()
RealND espressopp::RealND::operator- (const RealND & v) const inline
Definition at line 282 of file RealND.hpp.
References RealND().
operator-=()
RealND & espressopp::RealND::operator-= (const RealND & v) inline
Definition at line 239 of file RealND.hpp.
References data, dimension, and getDimension().
operator/()
RealND espressopp::RealND::operator/ (real v) const inline
Definition at line 288 of file RealND.hpp.
References RealND().
operator/=()
RealND & espressopp::RealND::operator/= (const real v) inline
Definition at line 252 of file RealND.hpp.
References data, and dimension.
operator=()
RealND & espressopp::RealND::operator= (const RealND & v) inline
Definition at line 194 of file RealND.hpp.
References data, dimension, getDimension(), and setDimension().
Referenced by espressopp::RealNDs::getDimension().
operator==()
bool espressopp::RealND::operator== (const RealND & v) const inline
Definition at line 260 of file RealND.hpp.
References data, dimension, and getDimension().
operator[]() [1/2]
real & espressopp::RealND::operator[] (int i) inline
Definition at line 204 of file RealND.hpp.
References data.
Referenced by espressopp::RealNDs::getDimension().
operator[]() [2/2]
const real & espressopp::RealND::operator[] (int i) const inline
Definition at line 207 of file RealND.hpp.
References data.
push_back()
void espressopp::RealND::push_back (real r) inline
Definition at line 320 of file RealND.hpp.
References data, getDimension(), and setDimension().
Referenced by espressopp::interaction::TabulatedSubEnsDihedral::addInteraction(), espressopp::interaction::TabulatedSubEnsAngular::addInteraction(), espressopp::interaction::TabulatedSubEns::addInteraction(), get(), and espressopp::RealNDs::getDimension().
registerPython()
void espressopp::RealND::registerPython () static
Definition at line 39 of file RealND.cpp.
References abs(), getDimension(), getItem(), setDimension(), setItem(), and sqr().
Referenced by get(), espressopp::RealNDs::getDimension(), and espressopp::registerPython().
serialize()
template<class Archive > void espressopp::RealND::serialize (Archive & ar, const unsigned int version) inline private
Definition at line 43 of file RealND.hpp.
setDimension()
void espressopp::RealND::setDimension (int _dim) inline
Definition at line 51 of file RealND.hpp.
Referenced by espressopp::io::DumpXTCAdress::dump(), espressopp::io::DumpXTC::dump(), operator=(), push_back(), RealND(), registerPython(), espressopp::interaction::TabulatedSubEnsDihedral::setColVar(), espressopp::interaction::TabulatedSubEnsAngular::setColVar(), espressopp::interaction::TabulatedSubEns::setColVar(), espressopp::interaction::TabulatedSubEnsDihedral::setDimension(), espressopp::interaction::TabulatedSubEnsAngular::setDimension(), espressopp::interaction::TabulatedSubEns::setDimension(), espressopp::interaction::TabulatedSubEns::TabulatedSubEns(), espressopp::interaction::TabulatedSubEnsAngular::TabulatedSubEnsAngular(), and espressopp::interaction::TabulatedSubEnsDihedral::TabulatedSubEnsDihedral().
setItem()
void espressopp::RealND::setItem (int i, real v) inline
Definition at line 222 of file RealND.hpp.
References at().
Referenced by espressopp::analysis::ConfigurationsExtAdress::gather(), espressopp::analysis::ConfigurationsExt::gather(), espressopp::RealNDs::getDimension(), registerPython(), espressopp::interaction::TabulatedSubEnsDihedral::setColVarSd(), espressopp::interaction::TabulatedSubEnsAngular::setColVarSd(), espressopp::interaction::TabulatedSubEns::setColVarSd(), espressopp::interaction::TabulatedSubEnsDihedral::setTargetProb(), espressopp::interaction::TabulatedSubEnsAngular::setTargetProb(), espressopp::interaction::TabulatedSubEns::setTargetProb(), espressopp::interaction::TabulatedSubEnsDihedral::setWeight(), espressopp::interaction::TabulatedSubEnsAngular::setWeight(), and espressopp::interaction::TabulatedSubEns::setWeight().
sqr()
real espressopp::RealND::sqr () const inline
Definition at line 307 of file RealND.hpp.
References data, and dimension.
Referenced by abs(), and registerPython().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Definition at line 41 of file RealND.hpp.
Member Data Documentation
data
std::vector<real> espressopp::RealND::data private
Definition at line 38 of file RealND.hpp.
Referenced by begin(), end(), operator*(), operator*=(), operator+=(), operator-=(), operator/=(), operator=(), operator==(), operator[](), push_back(), RealND(), and sqr().
dimension
int espressopp::RealND::dimension private
Definition at line 47 of file RealND.hpp.
Referenced by end(), getDimension(), espressopp::RealNDs::getDimension(), operator*(), operator*=(), operator+=(), operator-=(), operator/=(), operator=(), operator==(), and sqr().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/RealND.hpp
/home/espressopp/espressopp/src/RealND.cpp