ESPResSo++: espressopp::esutil::Array3D< T, outlier_mode > Class Template Reference
espressopp::esutil::Array3D< T, outlier_mode > Class Template Reference
A three-dimensional array (i.e.
#include <Array3D.hpp>
Public Types
typedef T value_type
The type of object, T, stored in the Array1D.
typedef T & reference
Reference to to a T object.
typedef const T & const_reference
Const reference to to a T object.
typedef Super::size_type size_type
An unsigned integer type.
typedef Super::iterator iterator
Iterator used to iterate through an Array1D.
typedef Super::const_iterator const_iterator
Const-iterator used to iterate through an Array1D.
Public Member Functions
Array3D ()
Default constructor.
Array3D (size_type n, size_type m, size_type l, const T &t=T())
Creates a 3-dimensional n x m x l array, initialising the values with copies of t.
void clear ()
Erases all elements.
void init (size_type n, size_type m, size_type l, const T &t=T())
Creates a 3-dimensional n x m x l array, initialising the values with copies of t.
void resize (size_type n, size_type m, size_type l, const T &t=T())
Changes the size of the Array3D so that the size becomes n x m x l.
size_type size_n () const
Returns the n -size of the array.
size_type size_x () const
Returns the n -size of the array.
size_type size_m () const
Returns the m -size of the array.
size_type size_y () const
Returns the m -size of the array.
size_type size_l () const
Returns the m -size of the array.
size_type size_z () const
Returns the m -size of the array.
bool empty () const
true if the Array3D's size is 0 x 0 x 0.
reference operator() (size_type i, size_type j, size_type k)
Returns the element at position i x j x k.
const_reference operator() (size_type i, size_type j, size_type k) const
Returns the element at position i x j x k.
template<class Vector >
reference operator() (const Vector &pos)
Returns the element at position pos.
template<class Vector >
const_reference operator() (const Vector &pos) const
Returns the element at position pos.
reference at (size_type i, size_type j, size_type k)
Returns the element at position i x j x k.
const_reference at (size_type i, size_type j, size_type k) const
Returns the element at position i x j x k.
template<class Vector >
reference at (const Vector &pos)
Returns the element at position pos.
template<class Vector >
const_reference at (const Vector &pos) const
Returns the element at position pos.
iterator begin ()
Returns an iterator pointing to the beginning of the Array3D.
const_iterator begin () const
Returns a const_iterator pointing to the beginning of the Array3D.
iterator end ()
Returns an iterator pointing to the end of the Array3D.
const_iterator end () const
Returns a const_iterator pointing to the end of the Array3D.
template<class T2 >
void operator= (const T2 &t2)
Assigns t2 to each of the elements.
template<class T2 >
void operator+= (const T2 &t2)
Adds t2 to each of the elements.
template<class T2 >
void operator-= (const T2 &t2)
Adds t2 to each of the elements.
template<class T2 >
void operator*= (const T2 &t2)
Multiplies each of the elements by t2.
template<class T2 >
void operator/= (const T2 &t2)
Divides each of the elements by t2.
void operator/= (const double &x)
bool operator== (const Array3D< T, exception > &a)
Equality operator.
bool operator!= (const Array3D< T, exception > &a)
Inequality operator.
Private Types
typedef Array3D< T > Self
typedef std::vector< T > Super
The super class of the array (i.e.
Private Attributes
size_type n
The n size of the n x m x l array.
size_type m
The m size of the n x m x l array.
size_type l
The l size of the n x m x l array.
Detailed Description
template<class T, OutlierMode outlier_mode = exception>
class espressopp::esutil::Array3D< T, outlier_mode >
A three-dimensional array (i.e.
a matrix). Prticulary we need it for 3-body potential tables
Parameters
T The type of the object stored in the array.
Example:
// create the 10x10 id matrix
Array3D< double > I(10, 10, ,10, 0.0);
for (int i = 0; i < 10; i++) I(i, i, i) = 1.0;
Definition at line 44 of file Array3D.hpp.
Member Typedef Documentation
const_iterator
template<class T, OutlierMode outlier_mode = exception> typedef Super::const_iterator espressopp::esutil::Array3D< T, outlier_mode >::const_iterator
Const-iterator used to iterate through an Array1D.
Definition at line 61 of file Array3D.hpp.
const_reference
template<class T, OutlierMode outlier_mode = exception> typedef const T& espressopp::esutil::Array3D< T, outlier_mode >::const_reference
Const reference to to a T object.
Definition at line 55 of file Array3D.hpp.
iterator
template<class T, OutlierMode outlier_mode = exception> typedef Super::iterator espressopp::esutil::Array3D< T, outlier_mode >::iterator
Iterator used to iterate through an Array1D.
Definition at line 59 of file Array3D.hpp.
reference
template<class T, OutlierMode outlier_mode = exception> typedef T& espressopp::esutil::Array3D< T, outlier_mode >::reference
Reference to to a T object.
Definition at line 53 of file Array3D.hpp.
Self
template<class T, OutlierMode outlier_mode = exception> typedef Array3D< T > espressopp::esutil::Array3D< T, outlier_mode >::Self private
Definition at line 45 of file Array3D.hpp.
size_type
template<class T, OutlierMode outlier_mode = exception> typedef Super::size_type espressopp::esutil::Array3D< T, outlier_mode >::size_type
An unsigned integer type.
Definition at line 57 of file Array3D.hpp.
Super
template<class T, OutlierMode outlier_mode = exception> typedef std::vector< T > espressopp::esutil::Array3D< T, outlier_mode >::Super private
The super class of the array (i.e.
vector<T>).
Definition at line 47 of file Array3D.hpp.
value_type
template<class T, OutlierMode outlier_mode = exception> typedef T espressopp::esutil::Array3D< T, outlier_mode >::value_type
The type of object, T, stored in the Array1D.
Definition at line 51 of file Array3D.hpp.
Constructor & Destructor Documentation
Array3D() [1/2]
template<class T, OutlierMode outlier_mode = exception> espressopp::esutil::Array3D< T, outlier_mode >::Array3D () inline
Default constructor.
Definition at line 64 of file Array3D.hpp.
Array3D() [2/2]
template<class T, OutlierMode outlier_mode = exception> espressopp::esutil::Array3D< T, outlier_mode >::Array3D (size_type n, size_type m, size_type l, const T & t = T()) inline
Creates a 3-dimensional n x m x l array, initialising the values with copies of t.
Definition at line 68 of file Array3D.hpp.
Member Function Documentation
at() [1/4]
template<class T, OutlierMode outlier_mode = exception> reference espressopp::esutil::Array3D< T, outlier_mode >::at (size_type i, size_type j, size_type k) inline
Returns the element at position i x j x k.
Exceptions
out_of_range i is out of range of the Array3D
Definition at line 151 of file Array3D.hpp.
Referenced by espressopp::esutil::Array3D< Potential, esutil::enlarge >::at(), espressopp::esutil::Array3D< T, enlarge >::at(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::getPotential(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::getPotential(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::getPotentialPtr(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::setPotential(), and espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::setPotential().
at() [2/4]
template<class T, OutlierMode outlier_mode = exception> const_reference espressopp::esutil::Array3D< T, outlier_mode >::at (size_type i, size_type j, size_type k) const inline
Returns the element at position i x j x k.
Exceptions
out_of_range i is out of range of the Array3D
Definition at line 160 of file Array3D.hpp.
at() [3/4]
template<class T, OutlierMode outlier_mode = exception> template<class Vector > reference espressopp::esutil::Array3D< T, outlier_mode >::at (const Vector & pos) inline
Returns the element at position pos.
pos must be a vector where the expressions pos[0], pos[1] and pos[2] return the first and second element.
\exception out_of_range \p i is out of range of the Array3D
Definition at line 174 of file Array3D.hpp.
at() [4/4]
template<class T, OutlierMode outlier_mode = exception> template<class Vector > const_reference espressopp::esutil::Array3D< T, outlier_mode >::at (const Vector & pos) const inline
Returns the element at position pos.
pos must be a vector where the expressions pos[0], pos[1] and pos[2] return the first and second element.
\exception out_of_range \p i is out of range of the Array3D
Definition at line 184 of file Array3D.hpp.
begin() [1/2]
template<class T, OutlierMode outlier_mode = exception> iterator espressopp::esutil::Array3D< T, outlier_mode >::begin () inline
Returns an iterator pointing to the beginning of the Array3D.
Definition at line 189 of file Array3D.hpp.
Referenced by espressopp::esutil::Array3D< Potential, esutil::enlarge >::operator*=(), espressopp::esutil::Array3D< Potential, esutil::enlarge >::operator+=(), espressopp::esutil::Array3D< Potential, esutil::enlarge >::operator-=(), espressopp::esutil::Array3D< Potential, esutil::enlarge >::operator/=(), and espressopp::esutil::Array3D< Potential, esutil::enlarge >::operator=().
begin() [2/2]
template<class T, OutlierMode outlier_mode = exception> const_iterator espressopp::esutil::Array3D< T, outlier_mode >::begin () const inline
Returns a const_iterator pointing to the beginning of the Array3D.
Definition at line 193 of file Array3D.hpp.
clear()
template<class T, OutlierMode outlier_mode = exception> void espressopp::esutil::Array3D< T, outlier_mode >::clear () inline
Erases all elements.
Definition at line 72 of file Array3D.hpp.
Referenced by espressopp::esutil::Array3D< Potential, esutil::enlarge >::Array3D().
empty()
template<class T, OutlierMode outlier_mode = exception> bool espressopp::esutil::Array3D< T, outlier_mode >::empty () const inline
true if the Array3D's size is 0 x 0 x 0.
Definition at line 119 of file Array3D.hpp.
end() [1/2]
template<class T, OutlierMode outlier_mode = exception> iterator espressopp::esutil::Array3D< T, outlier_mode >::end () inline
Returns an iterator pointing to the end of the Array3D.
Definition at line 197 of file Array3D.hpp.
Referenced by espressopp::esutil::Array3D< Potential, esutil::enlarge >::operator*=(), espressopp::esutil::Array3D< Potential, esutil::enlarge >::operator+=(), espressopp::esutil::Array3D< Potential, esutil::enlarge >::operator-=(), espressopp::esutil::Array3D< Potential, esutil::enlarge >::operator/=(), and espressopp::esutil::Array3D< Potential, esutil::enlarge >::operator=().
end() [2/2]
template<class T, OutlierMode outlier_mode = exception> const_iterator espressopp::esutil::Array3D< T, outlier_mode >::end () const inline
Returns a const_iterator pointing to the end of the Array3D.
Definition at line 201 of file Array3D.hpp.
init()
template<class T, OutlierMode outlier_mode = exception> void espressopp::esutil::Array3D< T, outlier_mode >::init (size_type n, size_type m, size_type l, const T & t = T()) inline
Creates a 3-dimensional n x m x l array, initialising the values with copies of t.
Definition at line 81 of file Array3D.hpp.
Referenced by espressopp::esutil::Array3D< Potential, esutil::enlarge >::Array3D(), and espressopp::esutil::Array3D< T, enlarge >::Array3D().
operator!=()
template<class T, OutlierMode outlier_mode = exception> bool espressopp::esutil::Array3D< T, outlier_mode >::operator!= (const Array3D< T, exception > & a) inline
Inequality operator.
Definition at line 243 of file Array3D.hpp.
operator()() [1/4]
template<class T, OutlierMode outlier_mode = exception> reference espressopp::esutil::Array3D< T, outlier_mode >::operator() (size_type i, size_type j, size_type k) inline
Returns the element at position i x j x k.
Attention
No range checking.
Definition at line 123 of file Array3D.hpp.
Referenced by espressopp::esutil::Array3D< Potential, esutil::enlarge >::at(), and espressopp::esutil::Array3D< Potential, esutil::enlarge >::operator()().
operator()() [2/4]
template<class T, OutlierMode outlier_mode = exception> const_reference espressopp::esutil::Array3D< T, outlier_mode >::operator() (size_type i, size_type j, size_type k) const inline
Returns the element at position i x j x k.
Attention
No range checking.
Definition at line 128 of file Array3D.hpp.
operator()() [3/4]
template<class T, OutlierMode outlier_mode = exception> template<class Vector > reference espressopp::esutil::Array3D< T, outlier_mode >::operator() (const Vector & pos) inline
Returns the element at position pos.
pos must be a vector where the expressions pos[0], pos[1] and pos[2] return the indices.
Attention
No range checking.
Definition at line 137 of file Array3D.hpp.
operator()() [4/4]
template<class T, OutlierMode outlier_mode = exception> template<class Vector > const_reference espressopp::esutil::Array3D< T, outlier_mode >::operator() (const Vector & pos) const inline
Returns the element at position pos.
pos must be a vector where the expressions pos[0], pos[1] and pos[2] return the indices.
Attention
No range checking.
Definition at line 146 of file Array3D.hpp.
operator*=()
template<class T, OutlierMode outlier_mode = exception> template<class T2 > void espressopp::esutil::Array3D< T, outlier_mode >::operator*= (const T2 & t2) inline
Multiplies each of the elements by t2.
Definition at line 223 of file Array3D.hpp.
operator+=()
template<class T, OutlierMode outlier_mode = exception> template<class T2 > void espressopp::esutil::Array3D< T, outlier_mode >::operator+= (const T2 & t2) inline
Adds t2 to each of the elements.
Definition at line 211 of file Array3D.hpp.
operator-=()
template<class T, OutlierMode outlier_mode = exception> template<class T2 > void espressopp::esutil::Array3D< T, outlier_mode >::operator-= (const T2 & t2) inline
Adds t2 to each of the elements.
Definition at line 217 of file Array3D.hpp.
operator/=() [1/2]
template<class T, OutlierMode outlier_mode = exception> template<class T2 > void espressopp::esutil::Array3D< T, outlier_mode >::operator/= (const T2 & t2) inline
Divides each of the elements by t2.
Definition at line 228 of file Array3D.hpp.
operator/=() [2/2]
template<class T, OutlierMode outlier_mode = exception> void espressopp::esutil::Array3D< T, outlier_mode >::operator/= (const double & x) inline
Definition at line 231 of file Array3D.hpp.
operator=()
template<class T, OutlierMode outlier_mode = exception> template<class T2 > void espressopp::esutil::Array3D< T, outlier_mode >::operator= (const T2 & t2) inline
Assigns t2 to each of the elements.
Definition at line 205 of file Array3D.hpp.
operator==()
template<class T, OutlierMode outlier_mode = exception> bool espressopp::esutil::Array3D< T, outlier_mode >::operator== (const Array3D< T, exception > & a) inline
Equality operator.
Definition at line 237 of file Array3D.hpp.
resize()
template<class T, OutlierMode outlier_mode = exception> void espressopp::esutil::Array3D< T, outlier_mode >::resize (size_type n, size_type m, size_type l, const T & t = T()) inline
Changes the size of the Array3D so that the size becomes n x m x l.
Attention
The elements of the Array3D are not initialised consistently, so the values are undefined. The t parameter exists only for the purpose to provide a default T value when new elements are created and needs to be specified only when T has no default constructor.
Definition at line 96 of file Array3D.hpp.
Referenced by espressopp::esutil::Array3D< Potential, esutil::enlarge >::init().
size_l()
template<class T, OutlierMode outlier_mode = exception> size_type espressopp::esutil::Array3D< T, outlier_mode >::size_l () const inline
Returns the m -size of the array.
Definition at line 114 of file Array3D.hpp.
Referenced by espressopp::esutil::Array3D< T, enlarge >::at().
size_m()
template<class T, OutlierMode outlier_mode = exception> size_type espressopp::esutil::Array3D< T, outlier_mode >::size_m () const inline
Returns the m -size of the array.
Definition at line 109 of file Array3D.hpp.
Referenced by espressopp::esutil::Array3D< T, enlarge >::at().
size_n()
template<class T, OutlierMode outlier_mode = exception> size_type espressopp::esutil::Array3D< T, outlier_mode >::size_n () const inline
Returns the n -size of the array.
Definition at line 104 of file Array3D.hpp.
Referenced by espressopp::esutil::Array3D< T, enlarge >::at().
size_x()
template<class T, OutlierMode outlier_mode = exception> size_type espressopp::esutil::Array3D< T, outlier_mode >::size_x () const inline
Returns the n -size of the array.
Definition at line 106 of file Array3D.hpp.
size_y()
template<class T, OutlierMode outlier_mode = exception> size_type espressopp::esutil::Array3D< T, outlier_mode >::size_y () const inline
Returns the m -size of the array.
Definition at line 111 of file Array3D.hpp.
size_z()
template<class T, OutlierMode outlier_mode = exception> size_type espressopp::esutil::Array3D< T, outlier_mode >::size_z () const inline
Returns the m -size of the array.
Definition at line 116 of file Array3D.hpp.
Member Data Documentation
l
template<class T, OutlierMode outlier_mode = exception> size_type espressopp::esutil::Array3D< T, outlier_mode >::l private
The l size of the n x m x l array.
Definition at line 254 of file Array3D.hpp.
Referenced by espressopp::esutil::Array3D< Potential, esutil::enlarge >::resize(), espressopp::esutil::Array3D< Potential, esutil::enlarge >::size_l(), and espressopp::esutil::Array3D< Potential, esutil::enlarge >::size_z().
m
template<class T, OutlierMode outlier_mode = exception> size_type espressopp::esutil::Array3D< T, outlier_mode >::m private
The m size of the n x m x l array.
Definition at line 252 of file Array3D.hpp.
Referenced by espressopp::esutil::Array3D< Potential, esutil::enlarge >::resize(), espressopp::esutil::Array3D< Potential, esutil::enlarge >::size_m(), and espressopp::esutil::Array3D< Potential, esutil::enlarge >::size_y().
n
template<class T, OutlierMode outlier_mode = exception> size_type espressopp::esutil::Array3D< T, outlier_mode >::n private
The n size of the n x m x l array.
Definition at line 250 of file Array3D.hpp.
Referenced by espressopp::esutil::Array3D< Potential, esutil::enlarge >::resize(), espressopp::esutil::Array3D< Potential, esutil::enlarge >::size_n(), and espressopp::esutil::Array3D< Potential, esutil::enlarge >::size_x().
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/esutil/Array3D.hpp