ESPResSo++: espressopp::MultiSystemAccess Class Reference
espressopp::MultiSystemAccess Class Reference
Common base class for all classes that need access to multiple systems.
#include <MultiSystemAccess.hpp>
Public Member Functions
MultiSystemAccess (shared_ptr< System > system1, shared_ptr< System > system2)
Constructor.
shared_ptr< System > getSystem1 () const
Get shared pointers to the systems.
shared_ptr< System > getSystem2 () const
System & getSystemRef1 () const
Get system references.
System & getSystemRef2 () const
Private Attributes
weak_ptr< System > mySystem1
Weak pointer to the system guarantees that system will be freed.
weak_ptr< System > mySystem2
Detailed Description
Common base class for all classes that need access to multiple systems.
This class encapsulates the access to a system via weak pointers and takes care of error handling (NULL system, system expired)
Definition at line 38 of file MultiSystemAccess.hpp.
Constructor & Destructor Documentation
MultiSystemAccess()
espressopp::MultiSystemAccess::MultiSystemAccess (shared_ptr< System > system1, shared_ptr< System > system2) inline
Constructor.
Definition at line 69 of file MultiSystemAccess.hpp.
Member Function Documentation
getSystem1()
shared_ptr< System > espressopp::MultiSystemAccess::getSystem1 () const inline
Get shared pointers to the systems.
Definition at line 89 of file MultiSystemAccess.hpp.
References mySystem1.
Referenced by getSystemRef1().
getSystem2()
shared_ptr< System > espressopp::MultiSystemAccess::getSystem2 () const inline
Definition at line 98 of file MultiSystemAccess.hpp.
References mySystem2.
Referenced by getSystemRef2().
getSystemRef1()
System& espressopp::MultiSystemAccess::getSystemRef1 () const inline
Get system references.
Definition at line 53 of file MultiSystemAccess.hpp.
References getSystem1().
getSystemRef2()
System& espressopp::MultiSystemAccess::getSystemRef2 () const inline
Definition at line 54 of file MultiSystemAccess.hpp.
References getSystem2().
Member Data Documentation
mySystem1
weak_ptr< System > espressopp::MultiSystemAccess::mySystem1 private
Weak pointer to the system guarantees that system will be freed.
Definition at line 60 of file MultiSystemAccess.hpp.
Referenced by getSystem1().
mySystem2
weak_ptr< System > espressopp::MultiSystemAccess::mySystem2 private
Definition at line 61 of file MultiSystemAccess.hpp.
Referenced by getSystem2().
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/MultiSystemAccess.hpp