ESPResSo++: espressopp::interaction::DihedralUniquePotentialTemplate< Derived > Class Template Reference
espressopp::interaction::DihedralUniquePotentialTemplate< Derived > Class Template Reference
#include <DihedralUniquePotential.hpp>
Public Member Functions
DihedralUniquePotentialTemplate ()
virtual real computeEnergy (const Real3D &r21, const Real3D &r32, const Real3D &r43, const real phi0) const
virtual real computeEnergy (real phi, real phi0) const
virtual void computeForce (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &r21, const Real3D &r32, const Real3D &r43, const real phi0) const
virtual real computeForce (real phi, real phi0) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
real _computeEnergy (const Real3D &r21, const Real3D &r32, const Real3D &r43, const real phi0) const
real _computeEnergy (real phi, real phi0) const
void _computeForce (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &r21, const Real3D &r32, const Real3D &r43, const real phi0) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
Derived * derived_this ()
const Derived * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
Detailed Description
template<class Derived>
class espressopp::interaction::DihedralUniquePotentialTemplate< Derived >
Definition at line 61 of file DihedralUniquePotential.hpp.
Constructor & Destructor Documentation
DihedralUniquePotentialTemplate()
template<class Derived > espressopp::interaction::DihedralUniquePotentialTemplate< Derived >::DihedralUniquePotentialTemplate () inline
Definition at line 122 of file DihedralUniquePotential.hpp.
Referenced by espressopp::interaction::DihedralUniquePotentialTemplate< DihedralHarmonicUniqueCos >::derived_this().
Member Function Documentation
_computeEnergy() [1/2]
template<class Derived > real espressopp::interaction::DihedralUniquePotentialTemplate< Derived >::_computeEnergy (const Real3D & r21, const Real3D & r32, const Real3D & r43, const real phi0) const inline
Definition at line 165 of file DihedralUniquePotential.hpp.
_computeEnergy() [2/2]
template<class Derived > real espressopp::interaction::DihedralUniquePotentialTemplate< Derived >::_computeEnergy (real phi, real phi0) const inline
Definition at line 194 of file DihedralUniquePotential.hpp.
_computeForce()
template<class Derived > void espressopp::interaction::DihedralUniquePotentialTemplate< Derived >::_computeForce (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & r21, const Real3D & r32, const Real3D & r43, const real phi0) const inline
Definition at line 216 of file DihedralUniquePotential.hpp.
computeEnergy() [1/2]
template<class Derived > real espressopp::interaction::DihedralUniquePotentialTemplate< Derived >::computeEnergy (const Real3D & r21, const Real3D & r32, const Real3D & r43, const real phi0) const inline virtual
Implements espressopp::interaction::DihedralUniquePotential.
Definition at line 145 of file DihedralUniquePotential.hpp.
computeEnergy() [2/2]
template<class Derived > real espressopp::interaction::DihedralUniquePotentialTemplate< Derived >::computeEnergy (real phi, real phi0) const inline virtual
Implements espressopp::interaction::DihedralUniquePotential.
Definition at line 158 of file DihedralUniquePotential.hpp.
computeForce() [1/2]
template<class Derived > void espressopp::interaction::DihedralUniquePotentialTemplate< Derived >::computeForce (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & r21, const Real3D & r32, const Real3D & r43, const real phi0) const inline virtual
Implements espressopp::interaction::DihedralUniquePotential.
Definition at line 202 of file DihedralUniquePotential.hpp.
computeForce() [2/2]
template<class Derived > real espressopp::interaction::DihedralUniquePotentialTemplate< Derived >::computeForce (real phi, real phi0) const inline virtual
Implements espressopp::interaction::DihedralUniquePotential.
Definition at line 230 of file DihedralUniquePotential.hpp.
derived_this() [1/2]
template<class Derived> Derived* espressopp::interaction::DihedralUniquePotentialTemplate< Derived >::derived_this () inline protected
Definition at line 107 of file DihedralUniquePotential.hpp.
derived_this() [2/2]
template<class Derived> const Derived* espressopp::interaction::DihedralUniquePotentialTemplate< Derived >::derived_this () const inline protected
Definition at line 111 of file DihedralUniquePotential.hpp.
getCutoff()
template<class Derived > real espressopp::interaction::DihedralUniquePotentialTemplate< Derived >::getCutoff () const inline virtual
Implements espressopp::interaction::DihedralUniquePotential.
Definition at line 138 of file DihedralUniquePotential.hpp.
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::DihedralUniquePotential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
registerPython()
void espressopp::interaction::DihedralUniquePotential::registerPython () static inherited
Definition at line 36 of file DihedralUniquePotential.cpp.
References espressopp::interaction::DihedralUniquePotential::computeEnergy(), espressopp::interaction::DihedralUniquePotential::computeForce(), espressopp::interaction::DihedralUniquePotential::getCutoff(), and espressopp::interaction::DihedralUniquePotential::setCutoff().
Referenced by espressopp::interaction::registerPython().
setCutoff()
template<class Derived > void espressopp::interaction::DihedralUniquePotentialTemplate< Derived >::setCutoff (real _cutoff) inline virtual
Implements espressopp::interaction::DihedralUniquePotential.
Definition at line 130 of file DihedralUniquePotential.hpp.
Member Data Documentation
cutoff
template<class Derived> real espressopp::interaction::DihedralUniquePotentialTemplate< Derived >::cutoff protected
Definition at line 104 of file DihedralUniquePotential.hpp.
cutoffSqr
template<class Derived> real espressopp::interaction::DihedralUniquePotentialTemplate< Derived >::cutoffSqr protected
Definition at line 105 of file DihedralUniquePotential.hpp.
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/interaction/DihedralUniquePotential.hpp