ESPResSo++: espressopp::esutil::RNG Class Reference
espressopp::esutil::RNG Class Reference
#include <RNG.hpp>
Public Member Functions
RNG (long _seed=12345)
Init the RNG, use the given seed.
void seed (long _seed)
Seed the RNG.
long get_seed ()
Gets RNG seed.
real operator() ()
returns a uniformly distributed random number between 0 and
int operator() (int N)
returns a uniformly distributed integer random number in the interval [0, N-1].
real normal ()
returns a normal distributed random number, with mean of 0.0 and sigma of 1.0.
real gamma (unsigned int alpha=1)
returns a gamma distributed random number with shape parameter and scale parameter 1.
real gammaOf1 ()
Real3D uniformOnSphere ()
returns a random 3D vector that is uniformly distributed on a sphere.
shared_ptr< RNGType > getBoostRNG ()
void saveState (int)
void loadState (const char *)
Static Public Member Functions
static void registerPython ()
Private Types
typedef variate_generator< RNGType &, normal_distribution< real > > NormalVariate
typedef variate_generator< RNGType &, uniform_on_sphere< real, Real3D > > UniformOnSphereVariate
Private Attributes
long seed_
shared_ptr< RNGType > boostRNG
NormalVariate normalVariate
UniformOnSphereVariate uniformOnSphereVariate
Detailed Description
Definition at line 40 of file RNG.hpp.
Member Typedef Documentation
NormalVariate
typedef variate_generator< RNGType&, normal_distribution< real > > espressopp::esutil::RNG::NormalVariate private
Definition at line 87 of file RNG.hpp.
UniformOnSphereVariate
typedef variate_generator< RNGType&, uniform_on_sphere< real, Real3D > > espressopp::esutil::RNG::UniformOnSphereVariate private
Definition at line 95 of file RNG.hpp.
Constructor & Destructor Documentation
RNG()
espressopp::esutil::RNG::RNG (long _seed = 12345)
Init the RNG, use the given seed.
Definition at line 38 of file RNG.cpp.
Member Function Documentation
gamma()
real espressopp::esutil::RNG::gamma (unsigned int alpha = 1)
returns a gamma distributed random number with shape parameter and scale parameter 1.
Definition at line 70 of file RNG.cpp.
References boostRNG.
Referenced by registerPython().
gammaOf1()
real espressopp::esutil::RNG::gammaOf1 () inline
Definition at line 69 of file RNG.hpp.
References espressopp::esutil::registerPython().
Referenced by registerPython().
get_seed()
long espressopp::esutil::RNG::get_seed ()
Gets RNG seed.
Definition at line 51 of file RNG.cpp.
References seed_.
Referenced by registerPython().
getBoostRNG()
shared_ptr< RNGType > espressopp::esutil::RNG::getBoostRNG ()
Definition at line 81 of file RNG.cpp.
References boostRNG.
loadState()
void espressopp::esutil::RNG::loadState (const char * fname)
Definition at line 104 of file RNG.cpp.
References boostRNG, and mpiWorld.
Referenced by registerPython().
normal()
real espressopp::esutil::RNG::normal ()
returns a normal distributed random number, with mean of 0.0 and sigma of 1.0.
If you need to generate many normal idstributed random numbers with different mean or sigma, use createNormalVariate() to create a variate generator object.
Definition at line 66 of file RNG.cpp.
References normalVariate.
Referenced by registerPython().
operator()() [1/2]
real espressopp::esutil::RNG::operator() ()
returns a uniformly distributed random number between 0 and
Definition at line 55 of file RNG.cpp.
References boostRNG.
operator()() [2/2]
int espressopp::esutil::RNG::operator() (int N)
returns a uniformly distributed integer random number in the interval [0, N-1].
Definition at line 60 of file RNG.cpp.
References boostRNG.
registerPython()
void espressopp::esutil::RNG::registerPython () static
Definition at line 127 of file RNG.cpp.
References gamma(), gammaOf1(), get_seed(), loadState(), normal(), saveState(), seed(), and uniformOnSphere().
Referenced by espressopp::esutil::registerPython().
saveState()
void espressopp::esutil::RNG::saveState (int step)
Definition at line 85 of file RNG.cpp.
References boostRNG, and mpiWorld.
Referenced by registerPython().
seed()
void espressopp::esutil::RNG::seed (long _seed)
Seed the RNG.
Definition at line 45 of file RNG.cpp.
References boostRNG, mpiWorld, and seed_.
Referenced by registerPython().
uniformOnSphere()
Real3D espressopp::esutil::RNG::uniformOnSphere ()
returns a random 3D vector that is uniformly distributed on a sphere.
Definition at line 77 of file RNG.cpp.
References uniformOnSphereVariate.
Referenced by registerPython().
Member Data Documentation
boostRNG
shared_ptr< RNGType > espressopp::esutil::RNG::boostRNG private
Definition at line 97 of file RNG.hpp.
Referenced by gamma(), getBoostRNG(), loadState(), operator()(), saveState(), and seed().
normalVariate
NormalVariate espressopp::esutil::RNG::normalVariate private
Definition at line 99 of file RNG.hpp.
Referenced by normal().
seed_
long espressopp::esutil::RNG::seed_ private
Definition at line 83 of file RNG.hpp.
Referenced by get_seed(), and seed().
uniformOnSphereVariate
UniformOnSphereVariate espressopp::esutil::RNG::uniformOnSphereVariate private
Definition at line 103 of file RNG.hpp.
Referenced by uniformOnSphere().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/esutil/RNG.hpp
/home/espressopp/espressopp/src/esutil/RNG.cpp