ESPResSo++: espressopp::interaction::StillingerWeberPairTermCapped Class Reference
espressopp::interaction::StillingerWeberPairTermCapped Class Reference abstract
This class provides methods to compute forces and energies of 2 body term of Stillinger-Weber potential.
#include <StillingerWeberPairTermCapped.hpp>
Public Member Functions
StillingerWeberPairTermCapped ()
StillingerWeberPairTermCapped (real _A, real _B, real _p, real _q, real _epsilon, real _sigma, real _cutoff, real _caprad)
virtual ~StillingerWeberPairTermCapped ()
void setA (real _A)
real getA () const
void setB (real _B)
real getB () const
void setP (real _p)
real getP () const
void setQ (real _q)
real getQ () const
void setEpsilon (real _epsilon)
real getEpsilon () const
void setSigma (real _sigma)
real getSigma () const
void setCaprad (real _caprad)
real getCaprad () const
void preset ()
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &r12, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual real getCutoff () const =0
virtual void setShift (real _shift)
virtual real getShift () const
virtual real getShift () const =0
virtual real setAutoShift ()
void updateAutoShift ()
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)
virtual shared_ptr< FixedPairList > getColVarBondList () const
virtual shared_ptr< FixedPairList > getColVarBondList () const =0
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &fpl)
virtual shared_ptr< FixedTripleList > getColVarAngleList () const
virtual shared_ptr< FixedTripleList > getColVarAngleList () const =0
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fpl)
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const =0
virtual void setColVar (const RealND &cv)
virtual void setColVar (const Real3D &dist, const bc::BC &bc)
virtual RealND getColVar () const
virtual RealND getColVar () const =0
virtual void computeColVarWeights (const Real3D &dist, const bc::BC &bc)
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
real _computeEnergyDeriv (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
StillingerWeberPairTermCapped * derived_this ()
const StillingerWeberPairTermCapped * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
shared_ptr< FixedPairList > colVarBondList
shared_ptr< FixedTripleList > colVarAngleList
shared_ptr< FixedQuadrupleList > colVarDihedList
RealND colVar
Private Attributes
real A
real B
real p
real q
real epsilon
real sigma
real caprad
Detailed Description
This class provides methods to compute forces and energies of 2 body term of Stillinger-Weber potential.
Definition at line 42 of file StillingerWeberPairTermCapped.hpp.
Constructor & Destructor Documentation
StillingerWeberPairTermCapped() [1/2]
espressopp::interaction::StillingerWeberPairTermCapped::StillingerWeberPairTermCapped () inline
Definition at line 53 of file StillingerWeberPairTermCapped.hpp.
References espressopp::infinity, preset(), espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::setCutoff(), and espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::setShift().
StillingerWeberPairTermCapped() [2/2]
espressopp::interaction::StillingerWeberPairTermCapped::StillingerWeberPairTermCapped (real _A, real _B, real _p, real _q, real _epsilon, real _sigma, real _cutoff, real _caprad) inline
Definition at line 59 of file StillingerWeberPairTermCapped.hpp.
References preset(), espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::setCutoff(), and espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::setShift().
~StillingerWeberPairTermCapped()
virtual espressopp::interaction::StillingerWeberPairTermCapped::~StillingerWeberPairTermCapped () inline virtual
Definition at line 67 of file StillingerWeberPairTermCapped.hpp.
Member Function Documentation
_computeEnergy() [1/4]
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::_computeEnergy (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 352 of file Potential.hpp.
_computeEnergy() [2/4]
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 360 of file Potential.hpp.
_computeEnergy() [3/4]
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::_computeEnergy (const Real3D & dist) const inline inherited
Definition at line 367 of file Potential.hpp.
_computeEnergy() [4/4]
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::_computeEnergy (real dist) const inline inherited
Definition at line 374 of file Potential.hpp.
_computeEnergyDeriv()
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::_computeEnergyDeriv (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 395 of file Potential.hpp.
_computeEnergySqr()
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::_computeEnergySqr (real distSqr) const inline inherited
Definition at line 381 of file Potential.hpp.
_computeEnergySqrRaw()
real espressopp::interaction::StillingerWeberPairTermCapped::_computeEnergySqrRaw (real distSqr) const inline
Definition at line 104 of file StillingerWeberPairTermCapped.hpp.
References A, B, getCaprad(), espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::getCutoff(), p, and q.
_computeForce() [1/3]
bool espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const inline inherited
Definition at line 423 of file Potential.hpp.
_computeForce() [2/3]
bool espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 431 of file Potential.hpp.
_computeForce() [3/3]
bool espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::_computeForce (Real3D & force, const Real3D & dist) const inline inherited
Definition at line 438 of file Potential.hpp.
_computeForceRaw()
bool espressopp::interaction::StillingerWeberPairTermCapped::_computeForceRaw (Real3D & force, const Real3D & r12, real distSqr) const inline
Definition at line 115 of file StillingerWeberPairTermCapped.hpp.
References A, B, getCaprad(), espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::getCutoff(), p, and q.
computeColVarWeights()
void espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::computeColVarWeights (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 315 of file Potential.hpp.
computeEnergy() [1/3]
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::computeEnergy (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 323 of file Potential.hpp.
computeEnergy() [2/3]
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::computeEnergy (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 331 of file Potential.hpp.
computeEnergy() [3/3]
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::computeEnergy (real dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 338 of file Potential.hpp.
computeEnergySqr()
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::computeEnergySqr (real distsqr) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 345 of file Potential.hpp.
computeForce() [1/2]
Real3D espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::computeForce (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 405 of file Potential.hpp.
computeForce() [2/2]
Real3D espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::computeForce (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 413 of file Potential.hpp.
derived_this() [1/2]
StillingerWeberPairTermCapped * espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::derived_this inline protected inherited
Definition at line 161 of file Potential.hpp.
derived_this() [2/2]
const StillingerWeberPairTermCapped * espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::derived_this inline protected inherited
Definition at line 165 of file Potential.hpp.
getA()
real espressopp::interaction::StillingerWeberPairTermCapped::getA () const inline
Definition at line 70 of file StillingerWeberPairTermCapped.hpp.
References A.
Referenced by registerPython().
getB()
real espressopp::interaction::StillingerWeberPairTermCapped::getB () const inline
Definition at line 73 of file StillingerWeberPairTermCapped.hpp.
References B.
Referenced by registerPython().
getCaprad()
real espressopp::interaction::StillingerWeberPairTermCapped::getCaprad () const inline
Definition at line 98 of file StillingerWeberPairTermCapped.hpp.
References caprad.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), and registerPython().
getColVar() [1/2]
RealND espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::getColVar inline virtual inherited
Definition at line 309 of file Potential.hpp.
getColVar() [2/2]
virtual RealND espressopp::interaction::Potential::getColVar () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getColVarAngleList() [1/2]
shared_ptr< FixedTripleList > espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::getColVarAngleList inline virtual inherited
Definition at line 273 of file Potential.hpp.
getColVarAngleList() [2/2]
virtual shared_ptr<FixedTripleList> espressopp::interaction::Potential::getColVarAngleList () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getColVarBondList() [1/2]
shared_ptr< FixedPairList > espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::getColVarBondList inline virtual inherited
Definition at line 259 of file Potential.hpp.
getColVarBondList() [2/2]
virtual shared_ptr<FixedPairList> espressopp::interaction::Potential::getColVarBondList () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getColVarDihedList() [1/2]
shared_ptr< FixedQuadrupleList > espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::getColVarDihedList inline virtual inherited
Definition at line 287 of file Potential.hpp.
getColVarDihedList() [2/2]
virtual shared_ptr<FixedQuadrupleList> espressopp::interaction::Potential::getColVarDihedList () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getCutoff() [1/2]
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::getCutoff inline virtual inherited
Definition at line 210 of file Potential.hpp.
getCutoff() [2/2]
virtual real espressopp::interaction::Potential::getCutoff () const pure virtual inherited
Implemented in espressopp::interaction::CoulombKSpaceP3M, and espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getEpsilon()
real espressopp::interaction::StillingerWeberPairTermCapped::getEpsilon () const inline
Definition at line 86 of file StillingerWeberPairTermCapped.hpp.
References epsilon.
Referenced by registerPython().
getP()
real espressopp::interaction::StillingerWeberPairTermCapped::getP () const inline
Definition at line 76 of file StillingerWeberPairTermCapped.hpp.
References p.
Referenced by registerPython().
getQ()
real espressopp::interaction::StillingerWeberPairTermCapped::getQ () const inline
Definition at line 79 of file StillingerWeberPairTermCapped.hpp.
References q.
Referenced by registerPython().
getShift() [1/2]
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::getShift inline virtual inherited
Definition at line 225 of file Potential.hpp.
getShift() [2/2]
virtual real espressopp::interaction::Potential::getShift () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getSigma()
real espressopp::interaction::StillingerWeberPairTermCapped::getSigma () const inline
Definition at line 92 of file StillingerWeberPairTermCapped.hpp.
References sigma.
Referenced by registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
preset()
void espressopp::interaction::StillingerWeberPairTermCapped::preset () inline
Definition at line 101 of file StillingerWeberPairTermCapped.hpp.
Referenced by setCaprad(), setEpsilon(), setSigma(), and StillingerWeberPairTermCapped().
registerPython()
void espressopp::interaction::StillingerWeberPairTermCapped::registerPython () static
Definition at line 45 of file StillingerWeberPairTermCapped.cpp.
References getA(), getB(), getCaprad(), getEpsilon(), getP(), getQ(), getSigma(), setA(), setB(), setCaprad(), setEpsilon(), setP(), setQ(), and setSigma().
Referenced by espressopp::interaction::registerPython().
setA()
void espressopp::interaction::StillingerWeberPairTermCapped::setA (real _A) inline
Definition at line 69 of file StillingerWeberPairTermCapped.hpp.
References A.
Referenced by registerPython().
setAutoShift()
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::setAutoShift inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 231 of file Potential.hpp.
setB()
void espressopp::interaction::StillingerWeberPairTermCapped::setB (real _B) inline
Definition at line 72 of file StillingerWeberPairTermCapped.hpp.
References B.
Referenced by registerPython().
setCaprad()
void espressopp::interaction::StillingerWeberPairTermCapped::setCaprad (real _caprad) inline
Definition at line 94 of file StillingerWeberPairTermCapped.hpp.
References caprad, and preset().
Referenced by registerPython().
setColVar() [1/2]
void espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::setColVar (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 301 of file Potential.hpp.
setColVar() [2/2]
void espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::setColVar (const RealND & cv) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 294 of file Potential.hpp.
setColVarAngleList()
void espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::setColVarAngleList (const shared_ptr< FixedTripleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 266 of file Potential.hpp.
setColVarBondList()
void espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::setColVarBondList (const shared_ptr< FixedPairList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 252 of file Potential.hpp.
setColVarDihedList()
void espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 280 of file Potential.hpp.
setCutoff()
void espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 201 of file Potential.hpp.
setEpsilon()
void espressopp::interaction::StillingerWeberPairTermCapped::setEpsilon (real _epsilon) inline
Definition at line 82 of file StillingerWeberPairTermCapped.hpp.
References epsilon, and preset().
Referenced by registerPython().
setP()
void espressopp::interaction::StillingerWeberPairTermCapped::setP (real _p) inline
Definition at line 75 of file StillingerWeberPairTermCapped.hpp.
References p.
Referenced by registerPython().
setQ()
void espressopp::interaction::StillingerWeberPairTermCapped::setQ (real _q) inline
Definition at line 78 of file StillingerWeberPairTermCapped.hpp.
References q.
Referenced by registerPython().
setShift()
void espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::setShift (real _shift) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 216 of file Potential.hpp.
setSigma()
void espressopp::interaction::StillingerWeberPairTermCapped::setSigma (real _sigma) inline
Definition at line 88 of file StillingerWeberPairTermCapped.hpp.
References preset(), and sigma.
Referenced by registerPython().
updateAutoShift()
void espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::updateAutoShift inline inherited
Definition at line 244 of file Potential.hpp.
Member Data Documentation
A
real espressopp::interaction::StillingerWeberPairTermCapped::A private
Definition at line 45 of file StillingerWeberPairTermCapped.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), getA(), and setA().
autoShift
bool espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::autoShift protected inherited
Definition at line 151 of file Potential.hpp.
B
real espressopp::interaction::StillingerWeberPairTermCapped::B private
Definition at line 45 of file StillingerWeberPairTermCapped.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), getB(), and setB().
caprad
real espressopp::interaction::StillingerWeberPairTermCapped::caprad private
Definition at line 49 of file StillingerWeberPairTermCapped.hpp.
Referenced by getCaprad(), and setCaprad().
colVar
RealND espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::colVar protected inherited
Definition at line 159 of file Potential.hpp.
colVarAngleList
shared_ptr<FixedTripleList> espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::colVarAngleList protected inherited
Definition at line 155 of file Potential.hpp.
colVarBondList
shared_ptr<FixedPairList> espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::colVarBondList protected inherited
Definition at line 153 of file Potential.hpp.
colVarDihedList
shared_ptr<FixedQuadrupleList> espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::colVarDihedList protected inherited
Definition at line 157 of file Potential.hpp.
cutoff
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::cutoff protected inherited
Definition at line 148 of file Potential.hpp.
cutoffSqr
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::cutoffSqr protected inherited
Definition at line 149 of file Potential.hpp.
epsilon
real espressopp::interaction::StillingerWeberPairTermCapped::epsilon private
Definition at line 46 of file StillingerWeberPairTermCapped.hpp.
Referenced by getEpsilon(), and setEpsilon().
p
real espressopp::interaction::StillingerWeberPairTermCapped::p private
Definition at line 45 of file StillingerWeberPairTermCapped.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), getP(), and setP().
q
real espressopp::interaction::StillingerWeberPairTermCapped::q private
Definition at line 45 of file StillingerWeberPairTermCapped.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), getQ(), and setQ().
shift
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >::shift protected inherited
Definition at line 150 of file Potential.hpp.
sigma
real espressopp::interaction::StillingerWeberPairTermCapped::sigma private
Definition at line 47 of file StillingerWeberPairTermCapped.hpp.
Referenced by getSigma(), and setSigma().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/StillingerWeberPairTermCapped.hpp
/home/espressopp/espressopp/src/interaction/StillingerWeberPairTermCapped.cpp