ESPResSo++: espressopp::analysis::VelocityAutocorrelation Class Reference
espressopp::analysis::VelocityAutocorrelation Class Reference
#include <VelocityAutocorrelation.hpp>
Public Member Functions
VelocityAutocorrelation (shared_ptr< System > system)
~VelocityAutocorrelation ()
virtual python::list compute () const
void setPrint_progress (bool _print_progress)
bool getPrint_progress ()
int getListSize () const
void gather ()
void gatherFromFile (string filename)
ConfigurationPtr getConf (int position) const
ConfigurationList all () const
void clear ()
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (logger)
Protected Attributes
int num_of_part
int chainlength
int start_pid
map< size_t, int > idToCpu
map< size_t, int > cidToCpu
map< size_t, int > idToCid
string key
Private Member Functions
void pushConfig (ConfigurationPtr config)
Private Attributes
bool print_progress
ConfigurationList configurations
weak_ptr< System > mySystem
Weak pointer to the system guarantees that system will be freed.
weak_ptr< System > mySystem1
weak_ptr< System > mySystem2
Detailed Description
Definition at line 35 of file VelocityAutocorrelation.hpp.
Constructor & Destructor Documentation
VelocityAutocorrelation()
espressopp::analysis::VelocityAutocorrelation::VelocityAutocorrelation (shared_ptr< System > system) inline
Definition at line 39 of file VelocityAutocorrelation.hpp.
References espressopp::analysis::ConfigsParticleDecomp::key, and setPrint_progress().
~VelocityAutocorrelation()
espressopp::analysis::VelocityAutocorrelation::~VelocityAutocorrelation () inline
Definition at line 45 of file VelocityAutocorrelation.hpp.
Member Function Documentation
all()
ConfigurationList espressopp::analysis::ConfigsParticleDecomp::all () const inherited
Definition at line 46 of file ConfigsParticleDecomp.cpp.
clear()
void espressopp::analysis::ConfigsParticleDecomp::clear () inline inherited
Definition at line 272 of file ConfigsParticleDecomp.hpp.
compute()
python::list espressopp::analysis::VelocityAutocorrelation::compute () const virtual
Implements espressopp::analysis::ConfigsParticleDecomp.
Definition at line 34 of file VelocityAutocorrelation.cpp.
References espressopp::System::comm.
gather()
void espressopp::analysis::ConfigsParticleDecomp::gather () inherited
Definition at line 69 of file ConfigsParticleDecomp.cpp.
References espressopp::System::bc, espressopp::System::comm, espressopp::iterator::CellListIterator::isDone(), espressopp::esutil::Error::setException(), and espressopp::System::storage.
gatherFromFile()
void espressopp::analysis::ConfigsParticleDecomp::gatherFromFile (string filename) inherited
Definition at line 133 of file ConfigsParticleDecomp.cpp.
References espressopp::System::comm, espressopp::esutil::Error::setException(), and espressopp::System::storage.
getConf()
ConfigurationPtr espressopp::analysis::ConfigsParticleDecomp::getConf (int position) const inherited
Definition at line 50 of file ConfigsParticleDecomp.cpp.
References espressopp::System::comm, and espressopp::esutil::Error::setException().
getListSize()
int espressopp::analysis::ConfigsParticleDecomp::getListSize () const inherited
Definition at line 42 of file ConfigsParticleDecomp.cpp.
getPrint_progress()
bool espressopp::analysis::VelocityAutocorrelation::getPrint_progress () inline
Definition at line 52 of file VelocityAutocorrelation.hpp.
References print_progress.
getSystem()
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::VerletList::_rebuildUsingBuffers(), espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::LatticeBoltzmann::assignMyLattice(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::vectorization::Vectorization::befCalcForces(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::vectorization::Vectorization::connect(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::vectorization::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpXTCAdress::dump(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::io::DumpXYZ::DumpXYZ(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::vectorization::VerletList::rebuild(), espressopp::vectorization::VerletList::rebuild_p_nc_pack_stencil(), espressopp::vectorization::VerletList::rebuildPairs(), espressopp::VerletListTriple::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::VerletList::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::vectorization::VerletList::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::vectorization::Vectorization::resetCells(), espressopp::vectorization::Vectorization::resetParticles(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::vectorization::Vectorization::updateForces(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
getSystem1()
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
getSystem2()
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
getSystemRef()
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerletRESPA::calcForces(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeCOM(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::FixedLocalTupleComListInteractionTemplate(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::VelocityVerletRESPA::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::VelocityVerletRESPA::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::VelocityVerletRESPA::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::Adress::integrateSlow(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::vectorization::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::VelocityVerletRESPA::run(), espressopp::integrator::PIAdressIntegrator::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::MinimizeEnergy::run(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::Rattle::saveOldPos(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostatOnGroup::thermalize(), espressopp::integrator::LangevinThermostatOnRadius::thermalize(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::vectorization::VerletList::totalSize(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::io::DumpH5MD::update(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::VelocityVerletRESPA::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
getSystemRef1()
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
getSystemRef2()
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
LOG4ESPP_DECL_LOGGER()
static espressopp::analysis::ConfigsParticleDecomp::LOG4ESPP_DECL_LOGGER (logger) static protected inherited
pushConfig()
void espressopp::analysis::ConfigsParticleDecomp::pushConfig (ConfigurationPtr config) private inherited
Definition at line 65 of file ConfigsParticleDecomp.cpp.
registerPython()
void espressopp::analysis::VelocityAutocorrelation::registerPython () static
Definition at line 104 of file VelocityAutocorrelation.cpp.
Referenced by espressopp::analysis::registerPython().
setPrint_progress()
void espressopp::analysis::VelocityAutocorrelation::setPrint_progress (bool _print_progress) inline
Definition at line 49 of file VelocityAutocorrelation.hpp.
References print_progress.
Referenced by VelocityAutocorrelation().
Member Data Documentation
chainlength
int espressopp::analysis::ConfigsParticleDecomp::chainlength protected inherited
Definition at line 286 of file ConfigsParticleDecomp.hpp.
cidToCpu
map< size_t, int > espressopp::analysis::ConfigsParticleDecomp::cidToCpu protected inherited
Definition at line 289 of file ConfigsParticleDecomp.hpp.
configurations
ConfigurationList espressopp::analysis::ConfigsParticleDecomp::configurations private inherited
Definition at line 299 of file ConfigsParticleDecomp.hpp.
idToCid
map< size_t, int > espressopp::analysis::ConfigsParticleDecomp::idToCid protected inherited
Definition at line 290 of file ConfigsParticleDecomp.hpp.
idToCpu
map< size_t, int > espressopp::analysis::ConfigsParticleDecomp::idToCpu protected inherited
Definition at line 288 of file ConfigsParticleDecomp.hpp.
key
string espressopp::analysis::ConfigsParticleDecomp::key protected inherited
Definition at line 292 of file ConfigsParticleDecomp.hpp.
Referenced by espressopp::analysis::MeanSquareDispl::MeanSquareDispl(), espressopp::analysis::MeanSquareInternalDist::MeanSquareInternalDist(), and VelocityAutocorrelation().
mySystem
weak_ptr< System > espressopp::SystemAccess::mySystem private inherited
Weak pointer to the system guarantees that system will be freed.
Definition at line 54 of file SystemAccess.hpp.
Referenced by espressopp::SystemAccess::getSystem(), and espressopp::SystemAccess::SystemAccess().
mySystem1
weak_ptr< System > espressopp::SystemAccess::mySystem1 private inherited
Definition at line 55 of file SystemAccess.hpp.
Referenced by espressopp::SystemAccess::getSystem1(), and espressopp::SystemAccess::SystemAccess().
mySystem2
weak_ptr< System > espressopp::SystemAccess::mySystem2 private inherited
Definition at line 56 of file SystemAccess.hpp.
Referenced by espressopp::SystemAccess::getSystem2(), and espressopp::SystemAccess::SystemAccess().
num_of_part
int espressopp::analysis::ConfigsParticleDecomp::num_of_part protected inherited
Definition at line 285 of file ConfigsParticleDecomp.hpp.
print_progress
bool espressopp::analysis::VelocityAutocorrelation::print_progress private
Definition at line 56 of file VelocityAutocorrelation.hpp.
Referenced by getPrint_progress(), and setPrint_progress().
start_pid
int espressopp::analysis::ConfigsParticleDecomp::start_pid protected inherited
Definition at line 287 of file ConfigsParticleDecomp.hpp.
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/analysis/VelocityAutocorrelation.hpp
/home/espressopp/espressopp/src/analysis/VelocityAutocorrelation.cpp