ESPResSo++: espressopp::bc::BC Class Reference
espressopp::bc::BC Class Reference abstract
Abstract base class for boundary conditions.
#include <BC.hpp>
Public Member Functions
BC (shared_ptr< esutil::RNG > _rng)
virtual ~BC ()
Virtual destructor for boundary conditions.
virtual Real3D getBoxL () const =0
Getter for box dimensions.
virtual void scaleVolume (real s)=0
virtual void scaleVolume (Real3D s)=0
virtual shared_ptr< esutil::RNG > getRng ()
Getter for the RNG.
virtual void setRng (shared_ptr< esutil::RNG > _rng)
Setter for RNG.
virtual void getMinimumImageVector (Real3D &dist, const Real3D &pos1, const Real3D &pos2) const =0
Computes the minimum image distance vector between two positions.
virtual void getMinimumImageVectorBox (Real3D &dist, const Real3D &pos1, const Real3D &pos2) const =0
Computes the minimum image distance vector between two positions where both positions are in the box.
virtual void getMinimumImageVectorX (real dist[3], const real pos1[3], const real pos2[3]) const =0
virtual Real3D getMinimumImageVector (const Real3D &pos1, const Real3D &pos2) const
virtual void getMinimumDistance (Real3D &dist) const =0
Compute the minimum image distance where the distance is given by two positions in the box.
virtual void foldCoordinate (Real3D &pos, Int3D &imageBox, int dir) const =0
fold a coordinate to the primary simulation box.
virtual void unfoldCoordinate (Real3D &pos, Int3D &imageBox, int dir) const =0
virtual void foldPosition (Real3D &pos, Int3D &imageBox) const
Fold the coordinates to the primary simulation box.
virtual void foldPosition (Real3D &pos) const
virtual boost::python::tuple getFoldedPosition (const Real3D &pos, const Int3D &imageBox) const
Get the folded position as a Python tuple.
virtual boost::python::tuple getFoldedPosition (const Real3D &pos) const
virtual void unfoldPosition (Real3D &pos, Int3D &imageBox) const
unfold coordinates to physical position.
virtual Real3D getUnfoldedPosition (const Real3D &pos, const Int3D &imageBox) const
virtual void getRandomPos (Real3D &res) const =0
Get a random position within the central simulation box.
virtual Real3D getRandomPos () const
Static Public Member Functions
static void registerPython ()
Public Attributes
boost::signals2::signal< void()> onBoxDimensionsChanged
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (logger)
Protected Attributes
shared_ptr< esutil::RNG > rng
Detailed Description
Abstract base class for boundary conditions.
Definition at line 38 of file BC.hpp.
Constructor & Destructor Documentation
BC()
espressopp::bc::BC::BC (shared_ptr< esutil::RNG > _rng) inline
Definition at line 40 of file BC.hpp.
~BC()
virtual espressopp::bc::BC::~BC () inline virtual
Virtual destructor for boundary conditions.
Definition at line 43 of file BC.hpp.
References getBoxL(), and scaleVolume().
Member Function Documentation
foldCoordinate()
virtual void espressopp::bc::BC::foldCoordinate (Real3D & pos, Int3D & imageBox, int dir) const pure virtual
fold a coordinate to the primary simulation box.
Parameters
pos the position
imageBox and the box
dir the coordinate to fold: dir = 0,1,2 for x, y and z coordinate.
Both pos and image_box are I/O, i. e. a previously folded position will be folded correctly.
Implemented in espressopp::bc::SlabBC, and espressopp::bc::OrthorhombicBC.
Referenced by foldPosition(), and setRng().
foldPosition() [1/2]
void espressopp::bc::BC::foldPosition (Real3D & pos, Int3D & imageBox) const virtual
Fold the coordinates to the primary simulation box.
Parameters
pos the position...
imageBox and the box
Both pos and image_box are I/O, i. e. a previously folded position will be folded correctly.
Definition at line 52 of file BC.cpp.
References foldCoordinate().
Referenced by foldPosition(), getFoldedPosition(), and setRng().
foldPosition() [2/2]
void espressopp::bc::BC::foldPosition (Real3D & pos) const virtual
Definition at line 58 of file BC.cpp.
References foldPosition().
getBoxL()
virtual Real3D espressopp::bc::BC::getBoxL () const pure virtual
Getter for box dimensions.
Implemented in espressopp::bc::SlabBC, and espressopp::bc::OrthorhombicBC.
Referenced by espressopp::interaction::LennardJones93Wall::_computeEnergyRaw(), espressopp::interaction::LennardJones93Wall::_computeForceRaw(), espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirialTensor(), registerPython(), and ~BC().
getFoldedPosition() [1/2]
boost::python::tuple espressopp::bc::BC::getFoldedPosition (const Real3D & pos, const Int3D & imageBox) const virtual
Get the folded position as a Python tuple.
Definition at line 70 of file BC.cpp.
References foldPosition().
Referenced by registerPython(), and setRng().
getFoldedPosition() [2/2]
boost::python::tuple espressopp::bc::BC::getFoldedPosition (const Real3D & pos) const virtual
Definition at line 79 of file BC.cpp.
References foldPosition().
getMinimumDistance()
virtual void espressopp::bc::BC::getMinimumDistance (Real3D & dist) const pure virtual
Compute the minimum image distance where the distance is given by two positions in the box.
Implemented in espressopp::bc::SlabBC, and espressopp::bc::OrthorhombicBC.
Referenced by setRng().
getMinimumImageVector() [1/2]
virtual void espressopp::bc::BC::getMinimumImageVector (Real3D & dist, const Real3D & pos1, const Real3D & pos2) const pure virtual
Computes the minimum image distance vector between two positions.
Parameters
dist is the distance vector (pos2 - pos1)
pos1,pos2 are the particle positions
Implemented in espressopp::bc::SlabBC, and espressopp::bc::OrthorhombicBC.
Referenced by espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeEnergy(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeEnergy(), getMinimumImageVector(), registerPython(), and setRng().
getMinimumImageVector() [2/2]
Real3D espressopp::bc::BC::getMinimumImageVector (const Real3D & pos1, const Real3D & pos2) const virtual
Definition at line 37 of file BC.cpp.
References getMinimumImageVector().
getMinimumImageVectorBox()
virtual void espressopp::bc::BC::getMinimumImageVectorBox (Real3D & dist, const Real3D & pos1, const Real3D & pos2) const pure virtual
Computes the minimum image distance vector between two positions where both positions are in the box.
Parameters
dist is the distance vector (pos2 - pos1)
pos1,pos2 are the particle positions
Be careful: this routine is faster than getMinimumImageVector but will only deliver corrrect result if the absolute distance in each dimension is less than the box size.
Implemented in espressopp::bc::SlabBC, and espressopp::bc::OrthorhombicBC.
Referenced by espressopp::interaction::HarmonicTrap::_computeEnergyRaw(), espressopp::interaction::HarmonicTrap::_computeForceRaw(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::addForces(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::addForces(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::analysis::AdressDensity::computeArray(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeCOM(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::VerletListAdress::rebuild(), setRng(), espressopp::integrator::Settle::settlep(), and espressopp::integrator::Settle::settlev().
getMinimumImageVectorX()
virtual void espressopp::bc::BC::getMinimumImageVectorX (real dist[3], const real pos1[3], const real pos2[3]) const pure virtual
Implemented in espressopp::bc::SlabBC, and espressopp::bc::OrthorhombicBC.
Referenced by setRng().
getRandomPos() [1/2]
virtual void espressopp::bc::BC::getRandomPos (Real3D & res) const pure virtual
Get a random position within the central simulation box.
The positions are assigned with each coordinate on [0, boxL].
Implemented in espressopp::bc::SlabBC, and espressopp::bc::OrthorhombicBC.
getRandomPos() [2/2]
Real3D espressopp::bc::BC::getRandomPos () const virtual
Definition at line 45 of file BC.cpp.
Referenced by espressopp::bc::OrthorhombicBC::getBoxL(), espressopp::bc::SlabBC::getBoxL(), registerPython(), setRng(), espressopp::bc::OrthorhombicBC::unfoldCoordinate(), and espressopp::bc::SlabBC::unfoldCoordinate().
getRng()
virtual shared_ptr< esutil::RNG > espressopp::bc::BC::getRng () inline virtual
Getter for the RNG.
Definition at line 50 of file BC.hpp.
References rng.
Referenced by registerPython().
getUnfoldedPosition()
Real3D espressopp::bc::BC::getUnfoldedPosition (const Real3D & pos, const Int3D & imageBox) const virtual
Definition at line 87 of file BC.cpp.
References unfoldPosition().
Referenced by registerPython(), and setRng().
LOG4ESPP_DECL_LOGGER()
static espressopp::bc::BC::LOG4ESPP_DECL_LOGGER (logger) static protected
registerPython()
void espressopp::bc::BC::registerPython () static
Definition at line 99 of file BC.cpp.
References getBoxL(), getFoldedPosition(), getMinimumImageVector(), getRandomPos(), getRng(), getUnfoldedPosition(), and setRng().
Referenced by espressopp::bc::registerPython().
scaleVolume() [1/2]
virtual void espressopp::bc::BC::scaleVolume (real s) pure virtual
Implemented in espressopp::bc::SlabBC, and espressopp::bc::OrthorhombicBC.
Referenced by ~BC().
scaleVolume() [2/2]
virtual void espressopp::bc::BC::scaleVolume (Real3D s) pure virtual
Implemented in espressopp::bc::SlabBC, and espressopp::bc::OrthorhombicBC.
setRng()
virtual void espressopp::bc::BC::setRng (shared_ptr< esutil::RNG > _rng) inline virtual
Setter for RNG.
Definition at line 52 of file BC.hpp.
References foldCoordinate(), foldPosition(), getFoldedPosition(), getMinimumDistance(), getMinimumImageVector(), getMinimumImageVectorBox(), getMinimumImageVectorX(), getRandomPos(), getUnfoldedPosition(), rng, unfoldCoordinate(), and unfoldPosition().
Referenced by registerPython().
unfoldCoordinate()
virtual void espressopp::bc::BC::unfoldCoordinate (Real3D & pos, Int3D & imageBox, int dir) const pure virtual
Implemented in espressopp::bc::SlabBC, and espressopp::bc::OrthorhombicBC.
Referenced by setRng(), and unfoldPosition().
unfoldPosition()
void espressopp::bc::BC::unfoldPosition (Real3D & pos, Int3D & imageBox) const virtual
unfold coordinates to physical position.
Parameters
pos the position...
imageBox and the box
Both pos and image_box are I/O, i.e. image_box will be (0,0,0) afterwards.
Definition at line 64 of file BC.cpp.
References unfoldCoordinate().
Referenced by getUnfoldedPosition(), and setRng().
Member Data Documentation
onBoxDimensionsChanged
boost::signals2::signal<void ()> espressopp::bc::BC::onBoxDimensionsChanged
Definition at line 152 of file BC.hpp.
Referenced by espressopp::bc::OrthorhombicBC::scaleVolume(), espressopp::bc::SlabBC::scaleVolume(), espressopp::bc::OrthorhombicBC::setBoxL(), and espressopp::bc::SlabBC::setBoxL().
rng
shared_ptr< esutil::RNG > espressopp::bc::BC::rng protected
Definition at line 157 of file BC.hpp.
Referenced by getRng(), and setRng().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/bc/BC.hpp
/home/espressopp/espressopp/src/bc/BC.cpp