ESPResSo++: espressopp::FixedTripleListAdress Class Reference
espressopp::FixedTripleListAdress Class Reference
This is a subclass of FixedTripleList.
#include <FixedTripleListAdress.hpp>
Public Types
typedef ESPPIterator
< std::vector< ParticleTriple > > Iterator
Public Member Functions
FixedTripleListAdress (shared_ptr< storage::Storage > _storage, shared_ptr< FixedTupleListAdress > _fixedtupleList)
~FixedTripleListAdress ()
bool add (longint pid1, longint pid2, longint pid3)
Add the given particle triple to the list on this processor if the particle with the lower id belongs to this processor.
void beforeSendParticles (ParticleList &pl, class OutBuffer &buf)
void beforeSendATParticles (std::vector< longint > &atpl, class OutBuffer &buf)
void onParticlesChanged ()
void add (Particle *p1, Particle *p2, Particle *p3)
void add (Particle &p1, Particle &p2, Particle &p3)
void add (std::vector< Particle * > particles)
void afterRecvParticles (ParticleList &pl, class InBuffer &buf)
python::list getTriples ()
int size ()
Get the number of triples in the GlobalTriples list.
Static Public Member Functions
static void registerPython ()
Protected Types
typedef
boost::unordered_multimap
< longint, std::pair< longint,
longint > > GlobalTriples
typedef std::vector
< ParticleTriple > Super
Protected Attributes
boost::signals2::connection sigBeforeSendAT
boost::signals2::connection sigAfterRecvAT
boost::signals2::connection sigAfterRecv
boost::signals2::connection sigOnParticleChanged
boost::signals2::connection sigBeforeSend
shared_ptr< storage::Storage > storage
GlobalTriples globalTriples
Static Private Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Private Attributes
shared_ptr< FixedTupleListAdress > fixedtupleList
Detailed Description
This is a subclass of FixedTripleList.
It should be used for AdResS fixed triples. It overrides some parent functions, to use AT particles.
Definition at line 45 of file FixedTripleListAdress.hpp.
Member Typedef Documentation
typedef boost::unordered_multimap<longint,std::pair <longint, longint> > espressopp::FixedTripleList::GlobalTriples [protected, inherited]
Definition at line 41 of file FixedTripleList.hpp.
typedef ESPPIterator<std::vector< ParticleTriple > > espressopp::esutil::ESPPContainer< std::vector< ParticleTriple > >::Iterator [inherited]
Definition at line 66 of file ESPPIterator.hpp.
typedef std::vector< ParticleTriple > espressopp::esutil::ESPPContainer< std::vector< ParticleTriple > >::Super [protected, inherited]
Definition at line 64 of file ESPPIterator.hpp.
Constructor & Destructor Documentation
espressopp::FixedTripleListAdress::FixedTripleListAdress (shared_ptr< storage::Storage > _storage, shared_ptr< FixedTupleListAdress > _fixedtupleList)
Definition at line 42 of file FixedTripleListAdress.cpp.
References espressopp::FixedTripleList::afterRecvParticles(), beforeSendATParticles(), fixedtupleList, LOG4ESPP_INFO, espressopp::FixedTripleList::sigAfterRecv, sigAfterRecvAT, espressopp::FixedTripleList::sigBeforeSend, and sigBeforeSendAT.
espressopp::FixedTripleListAdress::~FixedTripleListAdress ()
Definition at line 58 of file FixedTripleListAdress.cpp.
References LOG4ESPP_INFO, sigAfterRecvAT, and sigBeforeSendAT.
Member Function Documentation
bool espressopp::FixedTripleListAdress::add (longint pid1, longint pid2, longint pid3) [virtual]
Add the given particle triple to the list on this processor if the particle with the lower id belongs to this processor.
Note that this routine does not check whether the pair is inserted on another processor as well.
Returns:
whether the particle was inserted on this processor.
Reimplemented from espressopp::FixedTripleList.
Definition at line 67 of file FixedTripleListAdress.cpp.
References espressopp::esutil::Error::checkException(), espressopp::System::comm, espressopp::FixedTripleList::globalTriples, LOG4ESPP_INFO, espressopp::esutil::Error::setException(), and espressopp::FixedTripleList::storage.
Referenced by onParticlesChanged(), and registerPython().
void espressopp::TripleList::add (Particle * p1, Particle * p2, Particle * p3) [inline, inherited]
Definition at line 424 of file Particle.hpp.
Referenced by espressopp::FixedListComm::add(), espressopp::TripleList::add(), and espressopp::VerletListTriple::checkTriple().
void espressopp::TripleList::add (Particle & p1, Particle & p2, Particle & p3) [inline, inherited]
Definition at line 428 of file Particle.hpp.
References espressopp::TripleList::add().
Referenced by espressopp::TripleList::add().
void espressopp::TripleList::add (std::vector< Particle * > particles) [inline, inherited]
Definition at line 431 of file Particle.hpp.
References espressopp::TripleList::add().
void espressopp::FixedTripleList::afterRecvParticles (ParticleList & pl, class InBuffer & buf) [inherited]
Definition at line 213 of file FixedTripleList.cpp.
References espressopp::FixedTripleList::globalTriples, LOG4ESPP_INFO, espressopp::InBuffer::read(), and espressopp::FixedTripleList::size().
Referenced by espressopp::FixedTripleList::FixedTripleList(), and FixedTripleListAdress().
void espressopp::FixedTripleListAdress::beforeSendATParticles (std::vector< longint > & atpl, class OutBuffer & buf)
Definition at line 132 of file FixedTripleListAdress.cpp.
References espressopp::FixedTripleList::globalTriples, LOG4ESPP_DEBUG, LOG4ESPP_INFO, and espressopp::OutBuffer::write().
Referenced by FixedTripleListAdress().
void espressopp::FixedTripleListAdress::beforeSendParticles (ParticleList & pl, class OutBuffer & buf) [virtual]
Reimplemented from espressopp::FixedTripleList.
Definition at line 178 of file FixedTripleListAdress.cpp.
python::list espressopp::FixedTripleList::getTriples () [inherited]
Definition at line 157 of file FixedTripleList.cpp.
References espressopp::FixedTripleList::globalTriples.
Referenced by espressopp::FixedTripleList::registerPython().
static espressopp::FixedTripleListAdress::LOG4ESPP_DECL_LOGGER (theLogger) [static, private]
Reimplemented from espressopp::FixedTripleList.
void espressopp::FixedTripleListAdress::onParticlesChanged () [virtual]
Reimplemented from espressopp::FixedTripleList.
Definition at line 185 of file FixedTripleListAdress.cpp.
References add(), espressopp::esutil::Error::checkException(), espressopp::System::comm, espressopp::FixedTripleList::globalTriples, LOG4ESPP_INFO, espressopp::esutil::Error::setException(), and espressopp::FixedTripleList::storage.
void espressopp::FixedTripleListAdress::registerPython () [static]
Reimplemented from espressopp::FixedTripleList.
Definition at line 235 of file FixedTripleListAdress.cpp.
References add().
Referenced by espressopp::registerPython().
int espressopp::FixedTripleList::size () [inline, inherited]
Get the number of triples in the GlobalTriples list.
Definition at line 65 of file FixedTripleList.hpp.
References espressopp::FixedTripleList::globalTriples.
Referenced by espressopp::FixedTripleList::afterRecvParticles(), and espressopp::FixedTripleList::registerPython().
Member Data Documentation
shared_ptr<FixedTupleListAdress> espressopp::FixedTripleListAdress::fixedtupleList [private]
Definition at line 69 of file FixedTripleListAdress.hpp.
Referenced by FixedTripleListAdress().
GlobalTriples espressopp::FixedTripleList::globalTriples [protected, inherited]
Definition at line 42 of file FixedTripleList.hpp.
Referenced by espressopp::FixedTripleList::add(), add(), espressopp::FixedTripleList::afterRecvParticles(), beforeSendATParticles(), espressopp::FixedTripleList::beforeSendParticles(), espressopp::FixedTripleList::getTriples(), espressopp::FixedTripleList::onParticlesChanged(), onParticlesChanged(), and espressopp::FixedTripleList::size().
boost::signals2::connection espressopp::FixedTripleList::sigAfterRecv [protected, inherited]
Definition at line 39 of file FixedTripleList.hpp.
Referenced by espressopp::FixedTripleList::FixedTripleList(), FixedTripleListAdress(), and espressopp::FixedTripleList::~FixedTripleList().
boost::signals2::connection espressopp::FixedTripleListAdress::sigAfterRecvAT [protected]
Definition at line 66 of file FixedTripleListAdress.hpp.
Referenced by FixedTripleListAdress(), and ~FixedTripleListAdress().
boost::signals2::connection espressopp::FixedTripleList::sigBeforeSend [protected, inherited]
Definition at line 39 of file FixedTripleList.hpp.
Referenced by espressopp::FixedTripleList::FixedTripleList(), FixedTripleListAdress(), and espressopp::FixedTripleList::~FixedTripleList().
boost::signals2::connection espressopp::FixedTripleListAdress::sigBeforeSendAT [protected]
Definition at line 66 of file FixedTripleListAdress.hpp.
Referenced by FixedTripleListAdress(), and ~FixedTripleListAdress().
boost::signals2::connection espressopp::FixedTripleList::sigOnParticleChanged [protected, inherited]
Definition at line 39 of file FixedTripleList.hpp.
Referenced by espressopp::FixedTripleList::FixedTripleList(), and espressopp::FixedTripleList::~FixedTripleList().
shared_ptr<storage::Storage> espressopp::FixedTripleList::storage [protected, inherited]
Definition at line 40 of file FixedTripleList.hpp.
Referenced by espressopp::FixedTripleList::add(), add(), espressopp::FixedTripleList::FixedTripleList(), espressopp::FixedTripleList::onParticlesChanged(), and onParticlesChanged().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/FixedTripleListAdress.hpp
/home/travis/build/espressopp/espressopp/src/FixedTripleListAdress.cpp