ESPResSo++: espressopp::integrator::VelocityVerletOnRadius Class Reference
espressopp::integrator::VelocityVerletOnRadius Class Reference
#include <VelocityVerletOnRadius.hpp>
Public Types
enum ExtensionType {
all =0, Thermostat =1, Barostat =2, Constraint =3,
Adress =4, FreeEnergyCompensation =5, ExtForce =6, ExtAnalysis =7,
Reaction =8
}
Public Member Functions
VelocityVerletOnRadius (shared_ptr< System > _system, real _radialDampingMass)
virtual ~VelocityVerletOnRadius ()
void setRadialDampingMass (real _radialDampingMass)
real getRadialDampingMass ()
ExtensionType getType ()
void setType (ExtensionType k)
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
Register this class so it can be used from Python.
Public Attributes
ExtensionType type
Protected Member Functions
void setIntegrator (shared_ptr< MDIntegrator > _integrator)
Protected Attributes
shared_ptr< MDIntegrator > integrator
Private Member Functions
void connect ()
void disconnect ()
void integrate1 ()
void integrate2 ()
void initForces ()
Static Private Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Private Attributes
boost::signals2::connection _aftIntP
boost::signals2::connection _aftIntV
boost::signals2::connection _aftInitF
real radialDampingMass
weak_ptr< System > mySystem
Weak pointer to the system guarantees that system will be freed.
weak_ptr< System > mySystem1
weak_ptr< System > mySystem2
Detailed Description
Definition at line 37 of file VelocityVerletOnRadius.hpp.
Member Enumeration Documentation
ExtensionType
enum espressopp::integrator::Extension::ExtensionType inherited
Enumerator
all
Thermostat
Barostat
Constraint
Adress
FreeEnergyCompensation
ExtForce
ExtAnalysis
Reaction
Definition at line 48 of file Extension.hpp.
Constructor & Destructor Documentation
VelocityVerletOnRadius()
espressopp::integrator::VelocityVerletOnRadius::VelocityVerletOnRadius (shared_ptr< System > _system, real _radialDampingMass)
Definition at line 39 of file VelocityVerletOnRadius.cpp.
References LOG4ESPP_INFO.
~VelocityVerletOnRadius()
virtual espressopp::integrator::VelocityVerletOnRadius::~VelocityVerletOnRadius () inline virtual
Definition at line 40 of file VelocityVerletOnRadius.hpp.
Member Function Documentation
connect()
void espressopp::integrator::VelocityVerletOnRadius::connect () private virtual
Implements espressopp::integrator::Extension.
Definition at line 51 of file VelocityVerletOnRadius.cpp.
References _aftInitF, _aftIntP, _aftIntV, initForces(), integrate1(), integrate2(), and espressopp::integrator::Extension::integrator.
Referenced by registerPython().
disconnect()
void espressopp::integrator::VelocityVerletOnRadius::disconnect () private virtual
Implements espressopp::integrator::Extension.
Definition at line 45 of file VelocityVerletOnRadius.cpp.
References _aftInitF, _aftIntP, and _aftIntV.
Referenced by registerPython().
getRadialDampingMass()
real espressopp::integrator::VelocityVerletOnRadius::getRadialDampingMass () inline
Definition at line 46 of file VelocityVerletOnRadius.hpp.
References radialDampingMass.
Referenced by registerPython().
getSystem()
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::VerletList::_rebuildUsingBuffers(), espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::LatticeBoltzmann::assignMyLattice(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::vectorization::Vectorization::befCalcForces(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::vectorization::Vectorization::connect(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::vectorization::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpXTCAdress::dump(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::io::DumpXYZ::DumpXYZ(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::vectorization::VerletList::rebuild(), espressopp::vectorization::VerletList::rebuild_p_nc_pack_stencil(), espressopp::vectorization::VerletList::rebuildPairs(), espressopp::VerletListTriple::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::VerletList::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::vectorization::VerletList::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::vectorization::Vectorization::resetCells(), espressopp::vectorization::Vectorization::resetParticles(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::vectorization::Vectorization::updateForces(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
getSystem1()
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
getSystem2()
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
getSystemRef()
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerletRESPA::calcForces(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeCOM(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::FixedLocalTupleComListInteractionTemplate(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), initForces(), espressopp::integrator::VelocityVerletRESPA::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), integrate1(), espressopp::integrator::VelocityVerletRESPA::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::Adress::integrate1(), integrate2(), espressopp::integrator::VelocityVerletRESPA::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::Adress::integrateSlow(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::vectorization::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::VelocityVerletRESPA::run(), espressopp::integrator::PIAdressIntegrator::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::MinimizeEnergy::run(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::Rattle::saveOldPos(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostatOnGroup::thermalize(), espressopp::integrator::LangevinThermostatOnRadius::thermalize(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::vectorization::VerletList::totalSize(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::io::DumpH5MD::update(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::VelocityVerletRESPA::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
getSystemRef1()
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
getSystemRef2()
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
getType()
ExtensionType espressopp::integrator::Extension::getType () inline inherited
Definition at line 67 of file Extension.hpp.
References espressopp::integrator::Extension::type.
Referenced by espressopp::integrator::Extension::registerPython().
initForces()
void espressopp::integrator::VelocityVerletOnRadius::initForces () private
Definition at line 91 of file VelocityVerletOnRadius.cpp.
References espressopp::SystemAccess::getSystemRef(), espressopp::iterator::CellListIterator::isDone(), LOG4ESPP_INFO, and espressopp::System::storage.
Referenced by connect().
integrate1()
void espressopp::integrator::VelocityVerletOnRadius::integrate1 () private
Definition at line 58 of file VelocityVerletOnRadius.cpp.
References espressopp::SystemAccess::getSystemRef(), espressopp::integrator::Extension::integrator, espressopp::iterator::CellListIterator::isDone(), LOG4ESPP_DEBUG, radialDampingMass, and espressopp::System::storage.
Referenced by connect().
integrate2()
void espressopp::integrator::VelocityVerletOnRadius::integrate2 () private
Definition at line 78 of file VelocityVerletOnRadius.cpp.
References espressopp::SystemAccess::getSystemRef(), espressopp::integrator::Extension::integrator, espressopp::iterator::CellListIterator::isDone(), radialDampingMass, and espressopp::System::storage.
Referenced by connect().
LOG4ESPP_DECL_LOGGER()
static espressopp::integrator::VelocityVerletOnRadius::LOG4ESPP_DECL_LOGGER (theLogger) static private
Logger.
registerPython()
void espressopp::integrator::VelocityVerletOnRadius::registerPython () static
Register this class so it can be used from Python.
Definition at line 106 of file VelocityVerletOnRadius.cpp.
References connect(), disconnect(), getRadialDampingMass(), and setRadialDampingMass().
Referenced by espressopp::integrator::registerPython().
setIntegrator()
void espressopp::integrator::Extension::setIntegrator (shared_ptr< MDIntegrator > _integrator) protected inherited
Definition at line 49 of file Extension.cpp.
References espressopp::integrator::Extension::integrator.
Referenced by espressopp::integrator::Extension::registerPython().
setRadialDampingMass()
void espressopp::integrator::VelocityVerletOnRadius::setRadialDampingMass (real _radialDampingMass) inline
Definition at line 42 of file VelocityVerletOnRadius.hpp.
References radialDampingMass.
Referenced by registerPython().
setType()
void espressopp::integrator::Extension::setType (ExtensionType k) inline inherited
Definition at line 68 of file Extension.hpp.
References espressopp::integrator::Extension::type.
Referenced by espressopp::integrator::Extension::registerPython().
Member Data Documentation
_aftInitF
boost::signals2::connection espressopp::integrator::VelocityVerletOnRadius::_aftInitF private
Definition at line 53 of file VelocityVerletOnRadius.hpp.
Referenced by connect(), and disconnect().
_aftIntP
boost::signals2::connection espressopp::integrator::VelocityVerletOnRadius::_aftIntP private
Definition at line 53 of file VelocityVerletOnRadius.hpp.
Referenced by connect(), and disconnect().
_aftIntV
boost::signals2::connection espressopp::integrator::VelocityVerletOnRadius::_aftIntV private
Definition at line 53 of file VelocityVerletOnRadius.hpp.
Referenced by connect(), and disconnect().
integrator
shared_ptr<MDIntegrator> espressopp::integrator::Extension::integrator protected inherited
Definition at line 72 of file Extension.hpp.
Referenced by espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::LatticeBoltzmann::calcRandForce(), espressopp::integrator::ExtAnalyze::connect(), espressopp::integrator::Rattle::connect(), connect(), espressopp::integrator::BerendsenBarostatAnisotropic::connect(), espressopp::integrator::BerendsenBarostat::connect(), espressopp::integrator::FixPositions::connect(), espressopp::integrator::Isokinetic::connect(), espressopp::integrator::ExtForce::connect(), espressopp::integrator::FreeEnergyCompensation::connect(), espressopp::integrator::BerendsenThermostat::connect(), espressopp::integrator::TDforce::connect(), espressopp::integrator::Settle::connect(), espressopp::integrator::LangevinThermostatOnGroup::connect(), espressopp::integrator::Adress::connect(), espressopp::integrator::CapForce::connect(), espressopp::integrator::LangevinThermostatOnRadius::connect(), espressopp::integrator::OnTheFlyFEC::connect(), espressopp::integrator::DPDThermostat::connect(), espressopp::integrator::GeneralizedLangevinThermostat::connect(), espressopp::integrator::LangevinThermostat1D::connect(), espressopp::integrator::LangevinThermostatHybrid::connect(), espressopp::integrator::LangevinBarostat::connect(), espressopp::integrator::LangevinThermostat::connect(), espressopp::integrator::AssociationReaction::connect(), espressopp::integrator::StochasticVelocityRescaling::connect(), espressopp::integrator::LatticeBoltzmann::connect(), espressopp::integrator::LatticeBoltzmann::convTimeMDtoLB(), espressopp::integrator::LangevinThermostatOnGroup::initialize(), espressopp::integrator::LangevinThermostatOnRadius::initialize(), espressopp::integrator::LangevinThermostat::initialize(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinThermostat1D::initialize(), espressopp::integrator::BerendsenThermostat::initialize(), espressopp::integrator::LangevinThermostatHybrid::initialize(), espressopp::integrator::BerendsenBarostatAnisotropic::initialize(), espressopp::integrator::BerendsenBarostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), integrate1(), espressopp::integrator::Adress::integrate1(), integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::Adress::integrateSlow(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::Extension::setIntegrator(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
mySystem
weak_ptr< System > espressopp::SystemAccess::mySystem private inherited
Weak pointer to the system guarantees that system will be freed.
Definition at line 54 of file SystemAccess.hpp.
Referenced by espressopp::SystemAccess::getSystem(), and espressopp::SystemAccess::SystemAccess().
mySystem1
weak_ptr< System > espressopp::SystemAccess::mySystem1 private inherited
Definition at line 55 of file SystemAccess.hpp.
Referenced by espressopp::SystemAccess::getSystem1(), and espressopp::SystemAccess::SystemAccess().
mySystem2
weak_ptr< System > espressopp::SystemAccess::mySystem2 private inherited
Definition at line 56 of file SystemAccess.hpp.
Referenced by espressopp::SystemAccess::getSystem2(), and espressopp::SystemAccess::SystemAccess().
radialDampingMass
real espressopp::integrator::VelocityVerletOnRadius::radialDampingMass private
Definition at line 59 of file VelocityVerletOnRadius.hpp.
Referenced by getRadialDampingMass(), integrate1(), integrate2(), and setRadialDampingMass().
type
ExtensionType espressopp::integrator::Extension::type inherited
Definition at line 62 of file Extension.hpp.
Referenced by espressopp::integrator::GeneralizedLangevinThermostat::addCoeffs(), espressopp::integrator::FreeEnergyCompensation::addForce(), espressopp::integrator::TDforce::addForce(), espressopp::integrator::Adress::Adress(), espressopp::integrator::AssociationReaction::AssociationReaction(), espressopp::integrator::BerendsenBarostat::BerendsenBarostat(), espressopp::integrator::BerendsenBarostatAnisotropic::BerendsenBarostatAnisotropic(), espressopp::integrator::BerendsenThermostat::BerendsenThermostat(), espressopp::integrator::DPDThermostat::DPDThermostat(), espressopp::integrator::ExtAnalyze::ExtAnalyze(), espressopp::integrator::FreeEnergyCompensation::FreeEnergyCompensation(), espressopp::integrator::GeneralizedLangevinThermostat::GeneralizedLangevinThermostat(), espressopp::integrator::Extension::getType(), espressopp::integrator::LangevinBarostat::LangevinBarostat(), espressopp::integrator::LangevinThermostat::LangevinThermostat(), espressopp::integrator::LangevinThermostat1D::LangevinThermostat1D(), espressopp::integrator::LangevinThermostatHybrid::LangevinThermostatHybrid(), espressopp::integrator::LangevinThermostatOnGroup::LangevinThermostatOnGroup(), espressopp::integrator::LangevinThermostatOnRadius::LangevinThermostatOnRadius(), espressopp::integrator::OnTheFlyFEC::OnTheFlyFEC(), espressopp::integrator::TDforce::registerPython(), espressopp::integrator::Extension::setType(), espressopp::integrator::StochasticVelocityRescaling::StochasticVelocityRescaling(), and espressopp::integrator::TDforce::TDforce().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/integrator/VelocityVerletOnRadius.hpp
/home/espressopp/espressopp/src/integrator/VelocityVerletOnRadius.cpp