ESPResSo++: espressopp::interaction::PotentialTemplate< Derived > Class Template Reference
espressopp::interaction::PotentialTemplate< Derived > Class Template Reference
Provides a template for the simple implementation of a shifted, absolute distance dependent potential with cutoff.
#include <Potential.hpp>
Public Member Functions
PotentialTemplate ()
virtual ~PotentialTemplate ()
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)
virtual shared_ptr< FixedPairList > getColVarBondList () const
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &fpl)
virtual shared_ptr< FixedTripleList > getColVarAngleList () const
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fpl)
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const
virtual void setColVar (const RealND &cv)
virtual void setColVar (const Real3D &dist, const bc::BC &bc)
virtual RealND getColVar () const
virtual void computeColVarWeights (const Real3D &dist, const bc::BC &bc)
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
real _computeEnergyDeriv (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
Derived * derived_this ()
const Derived * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
shared_ptr< FixedPairList > colVarBondList
shared_ptr< FixedTripleList > colVarAngleList
shared_ptr< FixedQuadrupleList > colVarDihedList
RealND colVar
Detailed Description
template<class Derived>
class espressopp::interaction::PotentialTemplate< Derived >
Provides a template for the simple implementation of a shifted, absolute distance dependent potential with cutoff.
Definition at line 85 of file Potential.hpp.
Constructor & Destructor Documentation
PotentialTemplate()
template<class Derived > espressopp::interaction::PotentialTemplate< Derived >::PotentialTemplate () inline
Definition at line 194 of file Potential.hpp.
~PotentialTemplate()
template<class Derived> virtual espressopp::interaction::PotentialTemplate< Derived >::~PotentialTemplate () inline virtual
Definition at line 88 of file Potential.hpp.
Member Function Documentation
_computeEnergy() [1/4]
template<class Derived > real espressopp::interaction::PotentialTemplate< Derived >::_computeEnergy (const Particle & p1, const Particle & p2) const inline
Definition at line 352 of file Potential.hpp.
_computeEnergy() [2/4]
template<class Derived > real espressopp::interaction::PotentialTemplate< Derived >::_computeEnergy (const Real3D & dist) const inline
Definition at line 367 of file Potential.hpp.
_computeEnergy() [3/4]
template<class Derived > real espressopp::interaction::PotentialTemplate< Derived >::_computeEnergy (real dist) const inline
Definition at line 374 of file Potential.hpp.
_computeEnergy() [4/4]
template<class Derived > real espressopp::interaction::PotentialTemplate< Derived >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const inline
Definition at line 360 of file Potential.hpp.
_computeEnergyDeriv()
template<class Derived > real espressopp::interaction::PotentialTemplate< Derived >::_computeEnergyDeriv (const Particle & p1, const Particle & p2) const inline
Definition at line 395 of file Potential.hpp.
_computeEnergySqr()
template<class Derived > real espressopp::interaction::PotentialTemplate< Derived >::_computeEnergySqr (real distSqr) const inline
Definition at line 381 of file Potential.hpp.
_computeForce() [1/3]
template<class Derived > bool espressopp::interaction::PotentialTemplate< Derived >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const inline
Definition at line 423 of file Potential.hpp.
_computeForce() [2/3]
template<class Derived > bool espressopp::interaction::PotentialTemplate< Derived >::_computeForce (Real3D & force, const Real3D & dist) const inline
Definition at line 438 of file Potential.hpp.
_computeForce() [3/3]
template<class Derived > bool espressopp::interaction::PotentialTemplate< Derived >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const inline
Definition at line 431 of file Potential.hpp.
computeColVarWeights()
template<class Derived > void espressopp::interaction::PotentialTemplate< Derived >::computeColVarWeights (const Real3D & dist, const bc::BC & bc) inline virtual
Implements espressopp::interaction::Potential.
Reimplemented in espressopp::interaction::TabulatedSubEns.
Definition at line 315 of file Potential.hpp.
computeEnergy() [1/3]
template<class Derived > real espressopp::interaction::PotentialTemplate< Derived >::computeEnergy (const Particle & p1, const Particle & p2) const inline virtual
Implements espressopp::interaction::Potential.
Reimplemented in espressopp::interaction::LennardJonesAutoBonds.
Definition at line 323 of file Potential.hpp.
computeEnergy() [2/3]
template<class Derived > real espressopp::interaction::PotentialTemplate< Derived >::computeEnergy (const Real3D & dist) const inline virtual
Implements espressopp::interaction::Potential.
Reimplemented in espressopp::interaction::LennardJonesAutoBonds.
Definition at line 331 of file Potential.hpp.
computeEnergy() [3/3]
template<class Derived > real espressopp::interaction::PotentialTemplate< Derived >::computeEnergy (real dist) const inline virtual
Implements espressopp::interaction::Potential.
Reimplemented in espressopp::interaction::LennardJonesAutoBonds.
Definition at line 338 of file Potential.hpp.
computeEnergySqr()
template<class Derived > real espressopp::interaction::PotentialTemplate< Derived >::computeEnergySqr (real distsqr) const inline virtual
Implements espressopp::interaction::Potential.
Reimplemented in espressopp::interaction::LennardJonesAutoBonds.
Definition at line 345 of file Potential.hpp.
computeForce() [1/2]
template<class Derived > Real3D espressopp::interaction::PotentialTemplate< Derived >::computeForce (const Particle & p1, const Particle & p2) const inline virtual
Implements espressopp::interaction::Potential.
Reimplemented in espressopp::interaction::LennardJonesAutoBonds.
Definition at line 405 of file Potential.hpp.
computeForce() [2/2]
template<class Derived > Real3D espressopp::interaction::PotentialTemplate< Derived >::computeForce (const Real3D & dist) const inline virtual
Implements espressopp::interaction::Potential.
Reimplemented in espressopp::interaction::LennardJonesAutoBonds.
Definition at line 413 of file Potential.hpp.
derived_this() [1/2]
template<class Derived> Derived* espressopp::interaction::PotentialTemplate< Derived >::derived_this () inline protected
Definition at line 161 of file Potential.hpp.
derived_this() [2/2]
template<class Derived> const Derived* espressopp::interaction::PotentialTemplate< Derived >::derived_this () const inline protected
Definition at line 165 of file Potential.hpp.
getColVar()
template<class Derived > RealND espressopp::interaction::PotentialTemplate< Derived >::getColVar () const inline virtual
Implements espressopp::interaction::Potential.
Definition at line 309 of file Potential.hpp.
getColVarAngleList()
template<class Derived > shared_ptr< FixedTripleList > espressopp::interaction::PotentialTemplate< Derived >::getColVarAngleList () const inline virtual
Implements espressopp::interaction::Potential.
Definition at line 273 of file Potential.hpp.
getColVarBondList()
template<class Derived > shared_ptr< FixedPairList > espressopp::interaction::PotentialTemplate< Derived >::getColVarBondList () const inline virtual
Implements espressopp::interaction::Potential.
Definition at line 259 of file Potential.hpp.
getColVarDihedList()
template<class Derived > shared_ptr< FixedQuadrupleList > espressopp::interaction::PotentialTemplate< Derived >::getColVarDihedList () const inline virtual
Implements espressopp::interaction::Potential.
Definition at line 287 of file Potential.hpp.
getCutoff()
template<class Derived > real espressopp::interaction::PotentialTemplate< Derived >::getCutoff () const inline virtual
Implements espressopp::interaction::Potential.
Reimplemented in espressopp::interaction::CoulombKSpaceP3M.
Definition at line 210 of file Potential.hpp.
Referenced by espressopp::interaction::CoulombTruncatedUniqueCharge_pickle::getinitargs(), espressopp::interaction::SoftCosine_pickle::getinitargs(), espressopp::interaction::LennardJonesExpand_pickle::getinitargs(), espressopp::interaction::Tabulated_pickle::getinitargs(), espressopp::interaction::LennardJonesGeneric_pickle::getinitargs(), espressopp::interaction::LennardJonesEnergyCapped_pickle::getinitargs(), espressopp::interaction::LennardJonesCapped_pickle::getinitargs(), espressopp::interaction::LennardJones_pickle::getinitargs(), espressopp::interaction::TabulatedSubEns_pickle::getinitargs(), espressopp::interaction::LennardJonesGromacs_pickle::getinitargs(), espressopp::interaction::ReactionFieldGeneralizedTI_pickle::getinitargs(), and espressopp::interaction::ReactionFieldGeneralized_pickle::getinitargs().
getShift()
template<class Derived > real espressopp::interaction::PotentialTemplate< Derived >::getShift () const inline virtual
Implements espressopp::interaction::Potential.
Definition at line 225 of file Potential.hpp.
Referenced by espressopp::interaction::CoulombTruncatedUniqueCharge_pickle::getinitargs(), espressopp::interaction::SoftCosine_pickle::getinitargs(), espressopp::interaction::LennardJonesExpand_pickle::getinitargs(), espressopp::interaction::LennardJonesGeneric_pickle::getinitargs(), espressopp::interaction::LennardJonesEnergyCapped_pickle::getinitargs(), espressopp::interaction::LennardJonesCapped_pickle::getinitargs(), espressopp::interaction::LennardJones_pickle::getinitargs(), espressopp::interaction::LennardJonesGromacs_pickle::getinitargs(), and espressopp::interaction::ReactionFieldGeneralized_pickle::getinitargs().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
Referenced by espressopp::interaction::Potential::~Potential().
registerPython()
void espressopp::interaction::Potential::registerPython () static inherited
Definition at line 35 of file Potential.cpp.
References espressopp::interaction::Potential::computeEnergy(), espressopp::interaction::Potential::computeForce(), espressopp::interaction::Potential::getColVar(), espressopp::interaction::Potential::getColVarAngleList(), espressopp::interaction::Potential::getColVarBondList(), espressopp::interaction::Potential::getColVarDihedList(), espressopp::interaction::Potential::getCutoff(), espressopp::interaction::Potential::getShift(), espressopp::interaction::Potential::setAutoShift(), espressopp::interaction::Potential::setColVarAngleList(), espressopp::interaction::Potential::setColVarBondList(), espressopp::interaction::Potential::setColVarDihedList(), espressopp::interaction::Potential::setCutoff(), and espressopp::interaction::Potential::setShift().
Referenced by espressopp::interaction::registerPython(), and espressopp::interaction::Potential::~Potential().
setAutoShift()
template<class Derived > real espressopp::interaction::PotentialTemplate< Derived >::setAutoShift () inline virtual
Implements espressopp::interaction::Potential.
Reimplemented in espressopp::interaction::LennardJonesAutoBonds.
Definition at line 231 of file Potential.hpp.
setColVar() [1/2]
template<class Derived > void espressopp::interaction::PotentialTemplate< Derived >::setColVar (const RealND & cv) inline virtual
Implements espressopp::interaction::Potential.
Definition at line 294 of file Potential.hpp.
setColVar() [2/2]
template<class Derived > void espressopp::interaction::PotentialTemplate< Derived >::setColVar (const Real3D & dist, const bc::BC & bc) inline virtual
Implements espressopp::interaction::Potential.
Reimplemented in espressopp::interaction::TabulatedSubEns.
Definition at line 301 of file Potential.hpp.
setColVarAngleList()
template<class Derived > void espressopp::interaction::PotentialTemplate< Derived >::setColVarAngleList (const shared_ptr< FixedTripleList > & fpl) inline virtual
Implements espressopp::interaction::Potential.
Definition at line 266 of file Potential.hpp.
setColVarBondList()
template<class Derived > void espressopp::interaction::PotentialTemplate< Derived >::setColVarBondList (const shared_ptr< FixedPairList > & fpl) inline virtual
Implements espressopp::interaction::Potential.
Definition at line 252 of file Potential.hpp.
setColVarDihedList()
template<class Derived > void espressopp::interaction::PotentialTemplate< Derived >::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fpl) inline virtual
Implements espressopp::interaction::Potential.
Definition at line 280 of file Potential.hpp.
setCutoff()
template<class Derived > void espressopp::interaction::PotentialTemplate< Derived >::setCutoff (real _cutoff) inline virtual
Implements espressopp::interaction::Potential.
Reimplemented in espressopp::interaction::CoulombKSpaceP3M, espressopp::interaction::ReactionFieldGeneralized, espressopp::interaction::LennardJonesAutoBonds, and espressopp::interaction::ReactionFieldGeneralizedTI.
Definition at line 201 of file Potential.hpp.
setShift()
template<class Derived > void espressopp::interaction::PotentialTemplate< Derived >::setShift (real _shift) inline virtual
Implements espressopp::interaction::Potential.
Definition at line 216 of file Potential.hpp.
updateAutoShift()
template<class Derived > void espressopp::interaction::PotentialTemplate< Derived >::updateAutoShift () inline
Definition at line 244 of file Potential.hpp.
Member Data Documentation
autoShift
template<class Derived> bool espressopp::interaction::PotentialTemplate< Derived >::autoShift protected
Definition at line 151 of file Potential.hpp.
colVar
template<class Derived> RealND espressopp::interaction::PotentialTemplate< Derived >::colVar protected
Definition at line 159 of file Potential.hpp.
colVarAngleList
template<class Derived> shared_ptr<FixedTripleList> espressopp::interaction::PotentialTemplate< Derived >::colVarAngleList protected
Definition at line 155 of file Potential.hpp.
colVarBondList
template<class Derived> shared_ptr<FixedPairList> espressopp::interaction::PotentialTemplate< Derived >::colVarBondList protected
Definition at line 153 of file Potential.hpp.
colVarDihedList
template<class Derived> shared_ptr<FixedQuadrupleList> espressopp::interaction::PotentialTemplate< Derived >::colVarDihedList protected
Definition at line 157 of file Potential.hpp.
cutoff
template<class Derived> real espressopp::interaction::PotentialTemplate< Derived >::cutoff protected
Definition at line 148 of file Potential.hpp.
cutoffSqr
template<class Derived> real espressopp::interaction::PotentialTemplate< Derived >::cutoffSqr protected
Definition at line 149 of file Potential.hpp.
shift
template<class Derived> real espressopp::interaction::PotentialTemplate< Derived >::shift protected
Definition at line 150 of file Potential.hpp.
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/interaction/Potential.hpp