ESPResSo++: espressopp::interaction::HarmonicUnique Class Reference
espressopp::interaction::HarmonicUnique Class Reference
#include <HarmonicUnique.hpp>
Public Member Functions
HarmonicUnique ()
HarmonicUnique (real _K)
void setK (real _K)
real getK () const
real _computeEnergySqrRaw (real distSqr, real curDist) const
bool _computeForceRaw (Real3D &force, const Real3D &r21, real distSqr, real curDist) const
virtual real computeEnergy (const Particle &p1, const Particle &p2, const real curDist) const
virtual real computeEnergy (const Real3D &r21, const real curDist) const
virtual real computeEnergy (real dist, real curDist) const
virtual real computeEnergySqr (real distsqr, real curDist) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2, const real curDist) const
virtual Real3D computeForce (const Real3D &r21, const real curDist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
real _computeEnergy (const Particle &p1, const Particle &p2, const real curDist) const
real _computeEnergy (const Real3D &r21, const real curDist) const
real _computeEnergy (real dist, real curDist) const
real _computeEnergySqr (real distSqr, real curDist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const real curDist) const
bool _computeForce (Real3D &force, const Real3D &dist, const real curDist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
HarmonicUnique * derived_this ()
const HarmonicUnique * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
Private Attributes
real K
Detailed Description
Definition at line 36 of file HarmonicUnique.hpp.
Constructor & Destructor Documentation
espressopp::interaction::HarmonicUnique::HarmonicUnique () [inline]
Definition at line 43 of file HarmonicUnique.hpp.
espressopp::interaction::HarmonicUnique::HarmonicUnique (real _K) [inline]
Definition at line 46 of file HarmonicUnique.hpp.
Member Function Documentation
real espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::_computeEnergy (const Particle & p1, const Particle & p2, const real curDist) const [inherited]
real espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::_computeEnergy (const Real3D & r21, const real curDist) const [inherited]
real espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::_computeEnergy (real dist, real curDist) const [inherited]
real espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::_computeEnergySqr (real distSqr, real curDist) const [inherited]
real espressopp::interaction::HarmonicUnique::_computeEnergySqrRaw (real distSqr, real curDist) const [inline]
Definition at line 56 of file HarmonicUnique.hpp.
References K.
bool espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const real curDist) const [inherited]
bool espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::_computeForce (Real3D & force, const Real3D & dist, const real curDist) const [inherited]
bool espressopp::interaction::HarmonicUnique::_computeForceRaw (Real3D & force, const Real3D & r21, real distSqr, real curDist) const [inline]
Definition at line 61 of file HarmonicUnique.hpp.
References K.
virtual real espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::computeEnergy (const Particle & p1, const Particle & p2, const real curDist) const [virtual, inherited]
Implements espressopp::interaction::PotentialUniqueDist.
virtual real espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::computeEnergy (const Real3D & r21, const real curDist) const [virtual, inherited]
Implements espressopp::interaction::PotentialUniqueDist.
virtual real espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::computeEnergy (real dist, real curDist) const [virtual, inherited]
Implements espressopp::interaction::PotentialUniqueDist.
virtual real espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::computeEnergySqr (real distsqr, real curDist) const [virtual, inherited]
Implements espressopp::interaction::PotentialUniqueDist.
virtual Real3D espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::computeForce (const Particle & p1, const Particle & p2, const real curDist) const [virtual, inherited]
Implements espressopp::interaction::PotentialUniqueDist.
virtual Real3D espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::computeForce (const Real3D & r21, const real curDist) const [virtual, inherited]
Implements espressopp::interaction::PotentialUniqueDist.
HarmonicUnique * espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::derived_this () [inline, protected, inherited]
Definition at line 105 of file PotentialUniqueDist.hpp.
const HarmonicUnique * espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::derived_this () const [inline, protected, inherited]
Definition at line 109 of file PotentialUniqueDist.hpp.
virtual real espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::getCutoff () const [virtual, inherited]
Implements espressopp::interaction::PotentialUniqueDist.
real espressopp::interaction::HarmonicUnique::getK () const [inline]
Definition at line 53 of file HarmonicUnique.hpp.
References K.
Referenced by registerPython().
virtual real espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::getShift () const [virtual, inherited]
Implements espressopp::interaction::PotentialUniqueDist.
static espressopp::interaction::PotentialUniqueDist::LOG4ESPP_DECL_LOGGER (theLogger) [static, inherited]
void espressopp::interaction::HarmonicUnique::registerPython () [static]
Reimplemented from espressopp::interaction::PotentialUniqueDist.
Definition at line 33 of file HarmonicUnique.cpp.
References getK(), and setK().
Referenced by espressopp::interaction::registerPython().
virtual real espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::setAutoShift () [virtual, inherited]
Implements espressopp::interaction::PotentialUniqueDist.
virtual void espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::setCutoff (real _cutoff) [virtual, inherited]
Implements espressopp::interaction::PotentialUniqueDist.
void espressopp::interaction::HarmonicUnique::setK (real _K) [inline]
Definition at line 50 of file HarmonicUnique.hpp.
References K.
Referenced by registerPython().
virtual void espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::setShift (real _shift) [virtual, inherited]
Implements espressopp::interaction::PotentialUniqueDist.
void espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::updateAutoShift () [inherited]
Member Data Documentation
bool espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::autoShift [protected, inherited]
Definition at line 103 of file PotentialUniqueDist.hpp.
real espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::cutoff [protected, inherited]
Definition at line 100 of file PotentialUniqueDist.hpp.
real espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::cutoffSqr [protected, inherited]
Definition at line 101 of file PotentialUniqueDist.hpp.
real espressopp::interaction::HarmonicUnique::K [private]
Definition at line 38 of file HarmonicUnique.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), getK(), and setK().
real espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::shift [protected, inherited]
Definition at line 102 of file PotentialUniqueDist.hpp.
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/interaction/HarmonicUnique.hpp
/home/travis/build/espressopp/espressopp/src/interaction/HarmonicUnique.cpp