ESPResSo++: espressopp::interaction::InterpolationLinear Class Reference
espressopp::interaction::InterpolationLinear Class Reference
#include <InterpolationLinear.hpp>
Public Member Functions
InterpolationLinear ()
~InterpolationLinear ()
void readRaw (mpi::communicator comm, const char *file)
real getEnergyRaw (real r) const
real getForceRaw (real r) const
virtual real getEnergy (real r) const
virtual real getForce (real r) const
virtual void read (mpi::communicator comm, const char *file)
Protected Member Functions
InterpolationLinear * derived_this ()
const InterpolationLinear * derived_this () const
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Private Member Functions
InterpolationLinear (const InterpolationLinear &)
int readFile (const char *file, bool dummy)
void spline (const real *x, const real *y, int N, real *a, real *b)
real splineInterpolation (real r, const real *a, const real *b) const
Private Attributes
int N
real inner
real outer
real delta
real invdelta
real * radius
real * energy
real * force
real * ae
real * be
real * af
real * bf
Detailed Description
Definition at line 33 of file InterpolationLinear.hpp.
Constructor & Destructor Documentation
InterpolationLinear() [1/2]
espressopp::interaction::InterpolationLinear::InterpolationLinear ()
Definition at line 32 of file InterpolationLinear.cpp.
References energy, force, and radius.
~InterpolationLinear()
espressopp::interaction::InterpolationLinear::~InterpolationLinear ()
Definition at line 39 of file InterpolationLinear.cpp.
References LOG4ESPP_INFO.
InterpolationLinear() [2/2]
espressopp::interaction::InterpolationLinear::InterpolationLinear (const InterpolationLinear &) inline private
Definition at line 46 of file InterpolationLinear.hpp.
References N, readFile(), spline(), and splineInterpolation().
Member Function Documentation
derived_this() [1/2]
InterpolationLinear * espressopp::interaction::InterpolationTemplate< InterpolationLinear >::derived_this () inline protected inherited
Definition at line 52 of file Interpolation.hpp.
derived_this() [2/2]
const InterpolationLinear * espressopp::interaction::InterpolationTemplate< InterpolationLinear >::derived_this () const inline protected inherited
Definition at line 55 of file Interpolation.hpp.
getEnergy()
real espressopp::interaction::InterpolationTemplate< InterpolationLinear >::getEnergy (real r) const inline virtual inherited
Implements espressopp::interaction::Interpolation.
Definition at line 72 of file Interpolation.hpp.
References espressopp::interaction::Interpolation::getForce().
getEnergyRaw()
real espressopp::interaction::InterpolationLinear::getEnergyRaw (real r) const inline
Definition at line 74 of file InterpolationLinear.hpp.
References ae, be, and splineInterpolation().
getForce()
real espressopp::interaction::InterpolationTemplate< InterpolationLinear >::getForce (real r) const inline virtual inherited
Implements espressopp::interaction::Interpolation.
Definition at line 79 of file Interpolation.hpp.
References espressopp::interaction::Interpolation::read().
getForceRaw()
real espressopp::interaction::InterpolationLinear::getForceRaw (real r) const inline
Definition at line 78 of file InterpolationLinear.hpp.
References af, bf, and splineInterpolation().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::InterpolationLinear::LOG4ESPP_DECL_LOGGER (theLogger) static protected
read()
void espressopp::interaction::InterpolationTemplate< InterpolationLinear >::read (mpi::communicator comm, const char * file) inline virtual inherited
Implements espressopp::interaction::Interpolation.
Definition at line 86 of file Interpolation.hpp.
readFile()
int espressopp::interaction::InterpolationLinear::readFile (const char * file, bool dummy) private
Definition at line 97 of file InterpolationLinear.cpp.
References energy, force, LOG4ESPP_ERROR, LOG4ESPP_INFO, MAXLINE, N, and radius.
Referenced by InterpolationLinear(), and readRaw().
readRaw()
void espressopp::interaction::InterpolationLinear::readRaw (mpi::communicator comm, const char * file)
Definition at line 48 of file InterpolationLinear.cpp.
References ae, af, be, bf, delta, energy, force, inner, invdelta, LOG4ESPP_ERROR, LOG4ESPP_INFO, N, outer, radius, readFile(), and spline().
spline()
void espressopp::interaction::InterpolationLinear::spline (const real * x, const real * y, int N, real * a, real * b) private
Definition at line 133 of file InterpolationLinear.cpp.
Referenced by InterpolationLinear(), and readRaw().
splineInterpolation()
real espressopp::interaction::InterpolationLinear::splineInterpolation (real r, const real * a, const real * b) const inline private
Definition at line 82 of file InterpolationLinear.hpp.
References delta, inner, invdelta, LOG4ESPP_ERROR, and N.
Referenced by getEnergyRaw(), getForceRaw(), and InterpolationLinear().
Member Data Documentation
ae
real* espressopp::interaction::InterpolationLinear::ae private
Definition at line 68 of file InterpolationLinear.hpp.
Referenced by getEnergyRaw(), and readRaw().
af
real* espressopp::interaction::InterpolationLinear::af private
Definition at line 69 of file InterpolationLinear.hpp.
Referenced by getForceRaw(), and readRaw().
be
real * espressopp::interaction::InterpolationLinear::be private
Definition at line 68 of file InterpolationLinear.hpp.
Referenced by getEnergyRaw(), and readRaw().
bf
real * espressopp::interaction::InterpolationLinear::bf private
Definition at line 69 of file InterpolationLinear.hpp.
Referenced by getForceRaw(), and readRaw().
delta
real espressopp::interaction::InterpolationLinear::delta private
Definition at line 63 of file InterpolationLinear.hpp.
Referenced by readRaw(), and splineInterpolation().
energy
real * espressopp::interaction::InterpolationLinear::energy private
Definition at line 66 of file InterpolationLinear.hpp.
Referenced by InterpolationLinear(), readFile(), and readRaw().
force
real * espressopp::interaction::InterpolationLinear::force private
Definition at line 66 of file InterpolationLinear.hpp.
Referenced by InterpolationLinear(), readFile(), and readRaw().
inner
real espressopp::interaction::InterpolationLinear::inner private
Definition at line 61 of file InterpolationLinear.hpp.
Referenced by readRaw(), and splineInterpolation().
invdelta
real espressopp::interaction::InterpolationLinear::invdelta private
Definition at line 64 of file InterpolationLinear.hpp.
Referenced by readRaw(), and splineInterpolation().
N
int espressopp::interaction::InterpolationLinear::N private
Definition at line 59 of file InterpolationLinear.hpp.
Referenced by InterpolationLinear(), readFile(), readRaw(), and splineInterpolation().
outer
real espressopp::interaction::InterpolationLinear::outer private
Definition at line 62 of file InterpolationLinear.hpp.
Referenced by readRaw().
radius
real* espressopp::interaction::InterpolationLinear::radius private
Definition at line 66 of file InterpolationLinear.hpp.
Referenced by InterpolationLinear(), readFile(), and readRaw().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/InterpolationLinear.hpp
/home/espressopp/espressopp/src/interaction/InterpolationLinear.cpp