ESPResSo++: espressopp::esutil::WallTimer Class Reference
espressopp::esutil::WallTimer Class Reference
timer measuring the wall time.
#include <Timer.hpp>
Public Member Functions
void reset ()
reset the starting time
float getElapsedTime () const
get the time that elapsed since the last reset
Protected Attributes
float currentTime
Private Member Functions
virtual float getCurrentTime () const
Private Attributes
boost::mpi::timer timer
Detailed Description
timer measuring the wall time.
Definition at line 65 of file Timer.hpp.
Member Function Documentation
getCurrentTime()
float espressopp::esutil::WallTimer::getCurrentTime () const private virtual
Implements espressopp::esutil::Timer.
Definition at line 45 of file Timer.cpp.
getElapsedTime()
float espressopp::esutil::Timer::getElapsedTime () const inline inherited
get the time that elapsed since the last reset
Definition at line 48 of file Timer.hpp.
References espressopp::esutil::Timer::currentTime, and espressopp::esutil::Timer::getCurrentTime().
Referenced by espressopp::integrator::VelocityVerlet::calcForces(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::LatticeBoltzmann::collideStream(), espressopp::esutil::operator<<(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletList::rebuild(), espressopp::vectorization::VerletList::rebuild(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::VelocityVerlet::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), and espressopp::analysis::LBOutputScreen::writeOutput().
reset()
void espressopp::esutil::Timer::reset () inline inherited
reset the starting time
Definition at line 46 of file Timer.hpp.
References espressopp::esutil::Timer::getCurrentTime().
Referenced by espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletList::rebuild(), espressopp::vectorization::VerletList::rebuild(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::esutil::UserTimer::UserTimer(), and espressopp::analysis::LBOutputScreen::writeOutput().
Member Data Documentation
currentTime
float espressopp::esutil::Timer::currentTime protected inherited
Definition at line 41 of file Timer.hpp.
Referenced by espressopp::esutil::Timer::getElapsedTime().
timer
boost::mpi::timer espressopp::esutil::WallTimer::timer private
Definition at line 66 of file Timer.hpp.
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/esutil/Timer.hpp
/home/espressopp/espressopp/src/esutil/Timer.cpp