ESPResSo++: espressopp::interaction::DihedralPotential Class Reference
espressopp::interaction::DihedralPotential Class Reference abstract
#include <DihedralPotential.hpp>
Public Member Functions
virtual real computeEnergy (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const =0
virtual real computeEnergy (real phi) const =0
virtual void computeForce (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const =0
virtual real computeForce (real phi) const =0
virtual void setCutoff (real _cutoff)=0
virtual real getCutoff () const =0
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)=0
virtual shared_ptr< FixedPairList > getColVarBondList () const =0
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &ftl)=0
virtual shared_ptr< FixedTripleList > getColVarAngleList () const =0
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fql)=0
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const =0
virtual void setColVar (const RealND &cv)=0
virtual void setColVar (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43, const bc::BC &bc)=0
virtual RealND getColVar () const =0
virtual void computeColVarWeights (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43, const bc::BC &bc)=0
Static Public Member Functions
static real computePhi (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43)
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Detailed Description
Definition at line 39 of file DihedralPotential.hpp.
Member Function Documentation
computeColVarWeights()
virtual void espressopp::interaction::DihedralPotential::computeColVarWeights (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43, const bc::BC & bc) pure virtual
Implemented in espressopp::interaction::TabulatedSubEnsDihedral, espressopp::interaction::DihedralPotentialTemplate< Derived >, espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >, espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >, espressopp::interaction::DihedralPotentialTemplate< DihedralRB >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >, and espressopp::interaction::DihedralPotentialTemplate< OPLS >.
computeEnergy() [1/2]
virtual real espressopp::interaction::DihedralPotential::computeEnergy (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const pure virtual
Implemented in espressopp::interaction::DihedralPotentialTemplate< Derived >, espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >, espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >, espressopp::interaction::DihedralPotentialTemplate< DihedralRB >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >, and espressopp::interaction::DihedralPotentialTemplate< OPLS >.
Referenced by registerPython().
computeEnergy() [2/2]
virtual real espressopp::interaction::DihedralPotential::computeEnergy (real phi) const pure virtual
Implemented in espressopp::interaction::DihedralPotentialTemplate< Derived >, espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >, espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >, espressopp::interaction::DihedralPotentialTemplate< DihedralRB >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >, and espressopp::interaction::DihedralPotentialTemplate< OPLS >.
computeForce() [1/2]
virtual void espressopp::interaction::DihedralPotential::computeForce (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const pure virtual
Implemented in espressopp::interaction::DihedralPotentialTemplate< Derived >, espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >, espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >, espressopp::interaction::DihedralPotentialTemplate< DihedralRB >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >, and espressopp::interaction::DihedralPotentialTemplate< OPLS >.
Referenced by registerPython().
computeForce() [2/2]
virtual real espressopp::interaction::DihedralPotential::computeForce (real phi) const pure virtual
Implemented in espressopp::interaction::DihedralPotentialTemplate< Derived >, espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >, espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >, espressopp::interaction::DihedralPotentialTemplate< DihedralRB >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >, and espressopp::interaction::DihedralPotentialTemplate< OPLS >.
computePhi()
real espressopp::interaction::DihedralPotential::computePhi (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) static
Definition at line 31 of file DihedralPotential.cpp.
References espressopp::Real3D::abs(), espressopp::Real3D::cross(), and espressopp::interaction::LOG4ESPP_LOGGER().
Referenced by registerPython(), espressopp::interaction::TabulatedSubEnsDihedral::setColVar(), espressopp::interaction::TabulatedSubEnsAngular::setColVar(), and espressopp::interaction::TabulatedSubEns::setColVar().
getColVar()
virtual RealND espressopp::interaction::DihedralPotential::getColVar () const pure virtual
Implemented in espressopp::interaction::DihedralPotentialTemplate< Derived >, espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >, espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >, espressopp::interaction::DihedralPotentialTemplate< DihedralRB >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >, and espressopp::interaction::DihedralPotentialTemplate< OPLS >.
Referenced by registerPython().
getColVarAngleList()
virtual shared_ptr<FixedTripleList> espressopp::interaction::DihedralPotential::getColVarAngleList () const pure virtual
Implemented in espressopp::interaction::DihedralPotentialTemplate< Derived >, espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >, espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >, espressopp::interaction::DihedralPotentialTemplate< DihedralRB >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >, and espressopp::interaction::DihedralPotentialTemplate< OPLS >.
Referenced by registerPython().
getColVarBondList()
virtual shared_ptr<FixedPairList> espressopp::interaction::DihedralPotential::getColVarBondList () const pure virtual
Implemented in espressopp::interaction::DihedralPotentialTemplate< Derived >, espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >, espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >, espressopp::interaction::DihedralPotentialTemplate< DihedralRB >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >, and espressopp::interaction::DihedralPotentialTemplate< OPLS >.
Referenced by registerPython().
getColVarDihedList()
virtual shared_ptr<FixedQuadrupleList> espressopp::interaction::DihedralPotential::getColVarDihedList () const pure virtual
Implemented in espressopp::interaction::DihedralPotentialTemplate< Derived >, espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >, espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >, espressopp::interaction::DihedralPotentialTemplate< DihedralRB >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >, and espressopp::interaction::DihedralPotentialTemplate< OPLS >.
getCutoff()
virtual real espressopp::interaction::DihedralPotential::getCutoff () const pure virtual
Implemented in espressopp::interaction::DihedralPotentialTemplate< Derived >, espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >, espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >, espressopp::interaction::DihedralPotentialTemplate< DihedralRB >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >, and espressopp::interaction::DihedralPotentialTemplate< OPLS >.
Referenced by registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::DihedralPotential::LOG4ESPP_DECL_LOGGER (theLogger) static
registerPython()
void espressopp::interaction::DihedralPotential::registerPython () static
Definition at line 64 of file DihedralPotential.cpp.
References computeEnergy(), computeForce(), computePhi(), getColVar(), getColVarAngleList(), getColVarBondList(), getCutoff(), setColVarAngleList(), setColVarBondList(), and setCutoff().
Referenced by espressopp::interaction::registerPython().
setColVar() [1/2]
virtual void espressopp::interaction::DihedralPotential::setColVar (const RealND & cv) pure virtual
Implemented in espressopp::interaction::DihedralPotentialTemplate< Derived >, espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >, espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >, espressopp::interaction::DihedralPotentialTemplate< DihedralRB >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >, and espressopp::interaction::DihedralPotentialTemplate< OPLS >.
setColVar() [2/2]
virtual void espressopp::interaction::DihedralPotential::setColVar (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43, const bc::BC & bc) pure virtual
Implemented in espressopp::interaction::TabulatedSubEnsDihedral, espressopp::interaction::DihedralPotentialTemplate< Derived >, espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >, espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >, espressopp::interaction::DihedralPotentialTemplate< DihedralRB >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >, and espressopp::interaction::DihedralPotentialTemplate< OPLS >.
setColVarAngleList()
virtual void espressopp::interaction::DihedralPotential::setColVarAngleList (const shared_ptr< FixedTripleList > & ftl) pure virtual
Implemented in espressopp::interaction::DihedralPotentialTemplate< Derived >, espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >, espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >, espressopp::interaction::DihedralPotentialTemplate< DihedralRB >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >, and espressopp::interaction::DihedralPotentialTemplate< OPLS >.
Referenced by registerPython().
setColVarBondList()
virtual void espressopp::interaction::DihedralPotential::setColVarBondList (const shared_ptr< FixedPairList > & fpl) pure virtual
Implemented in espressopp::interaction::DihedralPotentialTemplate< Derived >, espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >, espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >, espressopp::interaction::DihedralPotentialTemplate< DihedralRB >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >, and espressopp::interaction::DihedralPotentialTemplate< OPLS >.
Referenced by registerPython().
setColVarDihedList()
virtual void espressopp::interaction::DihedralPotential::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fql) pure virtual
Implemented in espressopp::interaction::DihedralPotentialTemplate< Derived >, espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >, espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >, espressopp::interaction::DihedralPotentialTemplate< DihedralRB >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >, and espressopp::interaction::DihedralPotentialTemplate< OPLS >.
setCutoff()
virtual void espressopp::interaction::DihedralPotential::setCutoff (real _cutoff) pure virtual
Implemented in espressopp::interaction::DihedralPotentialTemplate< Derived >, espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >, espressopp::interaction::DihedralPotentialTemplate< TabulatedSubEnsDihedral >, espressopp::interaction::DihedralPotentialTemplate< DihedralRB >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >, espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >, and espressopp::interaction::DihedralPotentialTemplate< OPLS >.
Referenced by registerPython().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/DihedralPotential.hpp
/home/espressopp/espressopp/src/interaction/DihedralPotential.cpp