ESPResSo++: espressopp::analysis::RDFatomistic Class Reference
espressopp::analysis::RDFatomistic Class Reference
Class to compute the radial distribution function of the system.
#include <RDFatomistic.hpp>
Classes
class data
Public Types
enum result_types {
old_format =-1, none =0, real_scalar =1, int_scalar =2,
real_vector =3, int_vector =4
}
Observable can be int, real, scalar or vector.
Public Member Functions
RDFatomistic (shared_ptr< System > system, int type1, int type2, bool _spanbased=true, real _span=1.0)
~RDFatomistic ()
virtual real compute () const
for compatibilty with old compute function only, will be deleted soon
virtual python::list computeArray (int) const
virtual real compute_real () const
returns observable of type real, used for Python and on C++ level
virtual int compute_int () const
returns observable of type int, used for Python and on C++ level
virtual void compute_real_vector ()
computes vector of real values (e.g.
virtual void compute_int_vector ()
computes vector of integer values, used on C++ level only
virtual python::list compute_real_vector_python ()
returns python list of real values (e.g.
virtual python::list compute_int_vector_python ()
returns python list of integer values, used on Python level
int getResultType ()
returns the result type of the observable
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
Public Attributes
int target1
int target2
real span
bool spanbased
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (logger)
Protected Attributes
result_types result_type
std::vector< real > result_real_vector
std::vector< int > result_int_vector
Detailed Description
Class to compute the radial distribution function of the system.
Definition at line 35 of file RDFatomistic.hpp.
Member Enumeration Documentation
enum espressopp::analysis::Observable::result_types inherited
Observable can be int, real, scalar or vector.
Enumerator
old_format
none
real_scalar
int_scalar
real_vector
int_vector
Definition at line 37 of file Observable.hpp.
Constructor & Destructor Documentation
espressopp::analysis::RDFatomistic::RDFatomistic (shared_ptr< System > system, int type1, int type2, bool _spanbased = true, real _span = 1.0) inline
Definition at line 37 of file RDFatomistic.hpp.
espressopp::analysis::RDFatomistic::~RDFatomistic () inline
Definition at line 38 of file RDFatomistic.hpp.
References compute(), computeArray(), and registerPython().
Member Function Documentation
real espressopp::analysis::RDFatomistic::compute () const virtual
for compatibilty with old compute function only, will be deleted soon
Reimplemented from espressopp::analysis::Observable.
Definition at line 201 of file RDFatomistic.cpp.
Referenced by ~RDFatomistic().
virtual int espressopp::analysis::Observable::compute_int () const inline virtual inherited
returns observable of type int, used for Python and on C++ level
Definition at line 47 of file Observable.hpp.
Referenced by espressopp::analysis::Observable::registerPython().
virtual void espressopp::analysis::Observable::compute_int_vector () inline virtual inherited
computes vector of integer values, used on C++ level only
Definition at line 51 of file Observable.hpp.
References espressopp::analysis::Observable::compute_int_vector_python(), and espressopp::analysis::Observable::compute_real_vector_python().
Referenced by espressopp::analysis::Observable::compute_int_vector_python().
python::list espressopp::analysis::Observable::compute_int_vector_python () virtual inherited
returns python list of integer values, used on Python level
Definition at line 39 of file Observable.cpp.
References espressopp::analysis::Observable::compute_int_vector(), and espressopp::analysis::Observable::result_int_vector.
Referenced by espressopp::analysis::Observable::compute_int_vector(), and espressopp::analysis::Observable::registerPython().
virtual real espressopp::analysis::Observable::compute_real () const inline virtual inherited
returns observable of type real, used for Python and on C++ level
Reimplemented in espressopp::analysis::PotentialEnergy, and espressopp::analysis::NPart.
Definition at line 45 of file Observable.hpp.
Referenced by espressopp::analysis::Observable::registerPython().
virtual void espressopp::analysis::Observable::compute_real_vector () inline virtual inherited
computes vector of real values (e.g.
pressure tensor, ...), used on C++ level only
Definition at line 49 of file Observable.hpp.
Referenced by espressopp::analysis::Observable::compute_real_vector_python().
python::list espressopp::analysis::Observable::compute_real_vector_python () virtual inherited
returns python list of real values (e.g.
pressure tensor, ...), used on Python level
Definition at line 32 of file Observable.cpp.
References espressopp::analysis::Observable::compute_real_vector(), and espressopp::analysis::Observable::result_real_vector.
Referenced by espressopp::analysis::Observable::compute_int_vector(), and espressopp::analysis::Observable::registerPython().
python::list espressopp::analysis::RDFatomistic::computeArray (int rdfN) const virtual
Definition at line 46 of file RDFatomistic.cpp.
References espressopp::Real3D::abs(), espressopp::System::bc, espressopp::System::comm, espressopp::Particle::id(), espressopp::iterator::CellListIterator::isDone(), espressopp::Particle::lambda(), M_PIl, espressopp::Particle::position(), espressopp::System::storage, and espressopp::Particle::type().
Referenced by registerPython(), and ~RDFatomistic().
int espressopp::analysis::Observable::getResultType () inline inherited
returns the result type of the observable
Definition at line 62 of file Observable.hpp.
References espressopp::analysis::Observable::registerPython(), and espressopp::analysis::Observable::result_type.
Referenced by espressopp::analysis::Observable::registerPython().
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::LatticeBoltzmann::assignMyLattice(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::io::DumpXYZ::DumpXYZ(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::VerletListTriple::registerPython(), espressopp::VerletList::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::addForces(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::addForces(), espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerlet::calcForces(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeCOM(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::FixedLocalTupleComListInteractionTemplate(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::VelocityVerlet::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::VelocityVerlet::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::VelocityVerlet::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::VelocityVerlet::printForces(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerlet::printPositions(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::MinimizeEnergy::run(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::Rattle::saveOldPos(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostatOnGroup::thermalize(), espressopp::integrator::LangevinThermostatOnRadius::thermalize(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::VelocityVerlet::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
static espressopp::analysis::Observable::LOG4ESPP_DECL_LOGGER (logger) static protected inherited
void espressopp::analysis::RDFatomistic::registerPython () static
Definition at line 205 of file RDFatomistic.cpp.
References computeArray().
Referenced by espressopp::analysis::registerPython(), and ~RDFatomistic().
Member Data Documentation
std::vector< int > espressopp::analysis::Observable::result_int_vector protected inherited
Definition at line 69 of file Observable.hpp.
Referenced by espressopp::analysis::Observable::compute_int_vector_python().
std::vector< real > espressopp::analysis::Observable::result_real_vector protected inherited
Definition at line 68 of file Observable.hpp.
Referenced by espressopp::analysis::Observable::compute_real_vector_python().
result_types espressopp::analysis::Observable::result_type protected inherited
Definition at line 67 of file Observable.hpp.
Referenced by espressopp::analysis::Observable::getResultType(), espressopp::analysis::NPart::NPart(), espressopp::analysis::Observable::Observable(), and espressopp::analysis::PotentialEnergy::PotentialEnergy().
real espressopp::analysis::RDFatomistic::span
Definition at line 61 of file RDFatomistic.hpp.
bool espressopp::analysis::RDFatomistic::spanbased
Definition at line 62 of file RDFatomistic.hpp.
int espressopp::analysis::RDFatomistic::target1
Definition at line 59 of file RDFatomistic.hpp.
int espressopp::analysis::RDFatomistic::target2
Definition at line 60 of file RDFatomistic.hpp.
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/analysis/RDFatomistic.hpp
/home/espressopp/espressopp/src/analysis/RDFatomistic.cpp