ESPResSo++: espressopp::analysis::PressureTensorLayer Class Reference
espressopp::analysis::PressureTensorLayer Class Reference
Class to compute the pressure tensor.
#include <PressureTensorLayer.hpp>
Public Member Functions
PressureTensorLayer (shared_ptr< System > system, real _z0, real _dz)
virtual ~PressureTensorLayer ()
Tensor computeRaw ()
python::list compute ()
python::list getAverageValue ()
void resetAverage ()
void updateAverage (Tensor res)
void setH0 (real _h0)
real getH0 ()
void setDH (real _dh)
real getDH ()
virtual void performMeasurement ()
virtual void reset ()
virtual int getNumberOfMeasurements ()
void perform_action ()
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (logger)
Protected Attributes
Tensor newAverage
Tensor lastAverage
Tensor newVariance
Tensor lastVariance
int nMeasurements
Private Attributes
real z0
real dz
int direction
Detailed Description
Class to compute the pressure tensor.
Definition at line 42 of file PressureTensorLayer.hpp.
Constructor & Destructor Documentation
espressopp::analysis::PressureTensorLayer::PressureTensorLayer (shared_ptr< System > system, real _z0, real _dz) [inline]
Definition at line 51 of file PressureTensorLayer.hpp.
virtual espressopp::analysis::PressureTensorLayer::~PressureTensorLayer () [inline, virtual]
Definition at line 52 of file PressureTensorLayer.hpp.
Member Function Documentation
python::list espressopp::analysis::PressureTensorLayer::compute () [inline, virtual]
Implements espressopp::analysis::AnalysisBaseTemplate< Tensor >.
Definition at line 120 of file PressureTensorLayer.hpp.
Tensor espressopp::analysis::PressureTensorLayer::computeRaw () [inline, virtual]
Implements espressopp::analysis::AnalysisBaseTemplate< Tensor >.
Definition at line 57 of file PressureTensorLayer.hpp.
References espressopp::System::bc, espressopp::iterator::CellListIterator::isDone(), mpiWorld, espressopp::System::shortRangeInteractions, and espressopp::System::storage.
python::list espressopp::analysis::PressureTensorLayer::getAverageValue () [inline, virtual]
Implements espressopp::analysis::AnalysisBaseTemplate< Tensor >.
Definition at line 129 of file PressureTensorLayer.hpp.
real espressopp::analysis::PressureTensorLayer::getDH () [inline]
Definition at line 172 of file PressureTensorLayer.hpp.
Referenced by registerPython().
real espressopp::analysis::PressureTensorLayer::getH0 () [inline]
Definition at line 169 of file PressureTensorLayer.hpp.
Referenced by registerPython().
virtual int espressopp::analysis::AnalysisBaseTemplate< Tensor >::getNumberOfMeasurements () [virtual, inherited]
return the number of measurements since the last reset
Implements espressopp::analysis::AnalysisBase.
shared_ptr< System > espressopp::SystemAccess::getSystem () const [inline, inherited]
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::LatticeBoltzmann::initGammas(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readCouplForces(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::VerletListTriple::registerPython(), espressopp::VerletList::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveCouplForces(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::analysis::LBOutputScreen::writeOutput(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const [inline, inherited]
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const [inline, inherited]
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
System& espressopp::SystemAccess::getSystemRef () const [inline, inherited]
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readCouplForces(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::LatticeBoltzmann::restoreLBForces(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::LatticeBoltzmann::saveCouplForces(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
System& espressopp::SystemAccess::getSystemRef1 () const [inline, inherited]
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
System& espressopp::SystemAccess::getSystemRef2 () const [inline, inherited]
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
static espressopp::analysis::AnalysisBase::LOG4ESPP_DECL_LOGGER (logger) [static, inherited]
void espressopp::analysis::AnalysisBase::perform_action () [inline, virtual, inherited]
Implements espressopp::ParticleAccess.
Definition at line 54 of file AnalysisBase.hpp.
References espressopp::analysis::AnalysisBase::performMeasurement().
virtual void espressopp::analysis::AnalysisBaseTemplate< Tensor >::performMeasurement () [virtual, inherited]
This method will measure the observable and can be called from within the integrator by using the ExtAnalyse extension.
It can also be called from python. It will also update the average value (typically also the variance) of the observable
Implements espressopp::analysis::AnalysisBase.
void espressopp::analysis::PressureTensorLayer::registerPython () [static]
Reimplemented from espressopp::analysis::AnalysisBase.
Definition at line 29 of file PressureTensorLayer.cpp.
References getDH(), getH0(), setDH(), and setH0().
Referenced by espressopp::analysis::registerPython().
virtual void espressopp::analysis::AnalysisBaseTemplate< Tensor >::reset () [virtual, inherited]
This method resets/initializes the measurement.
Implements espressopp::analysis::AnalysisBase.
void espressopp::analysis::PressureTensorLayer::resetAverage () [inline, virtual]
Implements espressopp::analysis::AnalysisBaseTemplate< Tensor >.
Definition at line 143 of file PressureTensorLayer.hpp.
void espressopp::analysis::PressureTensorLayer::setDH (real _dh) [inline]
Definition at line 171 of file PressureTensorLayer.hpp.
Referenced by registerPython().
void espressopp::analysis::PressureTensorLayer::setH0 (real _h0) [inline]
Definition at line 168 of file PressureTensorLayer.hpp.
Referenced by registerPython().
void espressopp::analysis::PressureTensorLayer::updateAverage (Tensor res) [inline, virtual]
Implements espressopp::analysis::AnalysisBaseTemplate< Tensor >.
Definition at line 150 of file PressureTensorLayer.hpp.
Member Data Documentation
int espressopp::analysis::PressureTensorLayer::direction [private]
Definition at line 46 of file PressureTensorLayer.hpp.
real espressopp::analysis::PressureTensorLayer::dz [private]
Definition at line 45 of file PressureTensorLayer.hpp.
Tensor espressopp::analysis::AnalysisBaseTemplate< Tensor >::lastAverage [protected, inherited]
Definition at line 79 of file AnalysisBase.hpp.
Tensor espressopp::analysis::AnalysisBaseTemplate< Tensor >::lastVariance [protected, inherited]
Definition at line 80 of file AnalysisBase.hpp.
Tensor espressopp::analysis::AnalysisBaseTemplate< Tensor >::newAverage [protected, inherited]
Definition at line 79 of file AnalysisBase.hpp.
Tensor espressopp::analysis::AnalysisBaseTemplate< Tensor >::newVariance [protected, inherited]
Definition at line 80 of file AnalysisBase.hpp.
int espressopp::analysis::AnalysisBaseTemplate< Tensor >::nMeasurements [protected, inherited]
Definition at line 81 of file AnalysisBase.hpp.
real espressopp::analysis::PressureTensorLayer::z0 [private]
Definition at line 44 of file PressureTensorLayer.hpp.
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/analysis/PressureTensorLayer.hpp
/home/travis/build/espressopp/espressopp/src/analysis/PressureTensorLayer.cpp