ESPResSo++: espressopp::integrator::LangevinThermostatHybrid Class Reference
espressopp::integrator::LangevinThermostatHybrid Class Reference
For use in AdResS simulations.
#include <LangevinThermostatHybrid.hpp>
Public Types
enum ExtensionType {
all =0, Thermostat =1, Barostat =2, Constraint =3,
Adress =4, FreeEnergyCompensation =5, ExtForce =6, ExtAnalysis =7,
Reaction =8
}
Public Member Functions
LangevinThermostatHybrid (shared_ptr< System > system, shared_ptr< FixedTupleListAdress > _fixedtupleList)
virtual ~LangevinThermostatHybrid ()
void setGamma (real gamma)
real getGamma ()
void setGammaHybrid (real gammahy)
real getGammaHybrid ()
void setGammaCG (real gammacg)
real getGammaCG ()
void setTemperature (real temperature)
real getTemperature ()
void initialize ()
void thermalizeAdr ()
update of forces to thermalize the system
void heatUp ()
very nasty: if we recalculate force when leaving/reentering the integrator, a(t) and a((t-dt)+dt) are NOT equal in the vv algorithm.
void coolDown ()
Opposite to heatUp.
ExtensionType getType ()
void setType (ExtensionType k)
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
Register this class so it can be used from Python.
Public Attributes
shared_ptr< FixedTupleListAdress > fixedtupleList
ExtensionType type
Protected Member Functions
void setIntegrator (shared_ptr< MDIntegrator > _integrator)
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Protected Attributes
shared_ptr< MDIntegrator > integrator
Private Member Functions
void frictionThermo (class Particle &, real)
void connect ()
void disconnect ()
Private Attributes
boost::signals2::connection _initialize
boost::signals2::connection _heatUp
boost::signals2::connection _coolDown
boost::signals2::connection _thermalizeAdr
real gamma
friction coefficient for aa region
real gammacg
friction coefficient for cg region
real gammahy
friction coefficient for hybrid region
real temperature
desired user temperature
real pref1
prefactor, reduces complexity of thermalize
real pref2
prefactor, reduces complexity of thermalize
real pref1hy
prefactor, reduces complexity of thermalize
real pref2hy
prefactor, reduces complexity of thermalize
real pref1cg
prefactor, reduces complexity of thermalize
real pref2cg
prefactor, reduces complexity of thermalize
real pref2buffer
temporary to save value between heatUp/coolDown
real pref2bufferhy
temporary to save value between heatUp/coolDown
real pref2buffercg
temporary to save value between heatUp/coolDown
shared_ptr< esutil::RNG > rng
random number generator used for friction term
Detailed Description
For use in AdResS simulations.
Langevin thermostat with three values of gamma, one for aa region, for cg region, and for hybrid region; uses value of lambda for each particle to decide which value of gamma to apply to that particle
Definition at line 47 of file LangevinThermostatHybrid.hpp.
Member Enumeration Documentation
ExtensionType
enum espressopp::integrator::Extension::ExtensionType inherited
Enumerator
all
Thermostat
Barostat
Constraint
Adress
FreeEnergyCompensation
ExtForce
ExtAnalysis
Reaction
Definition at line 48 of file Extension.hpp.
Constructor & Destructor Documentation
LangevinThermostatHybrid()
espressopp::integrator::LangevinThermostatHybrid::LangevinThermostatHybrid (shared_ptr< System > system, shared_ptr< FixedTupleListAdress > _fixedtupleList)
Definition at line 39 of file LangevinThermostatHybrid.cpp.
References gamma, gammacg, gammahy, LOG4ESPP_INFO, rng, temperature, espressopp::integrator::Extension::Thermostat, and espressopp::integrator::Extension::type.
~LangevinThermostatHybrid()
espressopp::integrator::LangevinThermostatHybrid::~LangevinThermostatHybrid () virtual
Definition at line 100 of file LangevinThermostatHybrid.cpp.
References disconnect().
Member Function Documentation
connect()
void espressopp::integrator::LangevinThermostatHybrid::connect () private virtual
Implements espressopp::integrator::Extension.
Definition at line 114 of file LangevinThermostatHybrid.cpp.
References _coolDown, _heatUp, _initialize, _thermalizeAdr, coolDown(), heatUp(), initialize(), espressopp::integrator::Extension::integrator, and thermalizeAdr().
Referenced by registerPython().
coolDown()
void espressopp::integrator::LangevinThermostatHybrid::coolDown ()
Opposite to heatUp.
Definition at line 232 of file LangevinThermostatHybrid.cpp.
References LOG4ESPP_INFO, pref2, pref2buffer, pref2buffercg, pref2bufferhy, pref2cg, and pref2hy.
Referenced by connect().
disconnect()
void espressopp::integrator::LangevinThermostatHybrid::disconnect () private virtual
Implements espressopp::integrator::Extension.
Definition at line 105 of file LangevinThermostatHybrid.cpp.
References _coolDown, _heatUp, _initialize, and _thermalizeAdr.
Referenced by registerPython(), and ~LangevinThermostatHybrid().
frictionThermo()
void espressopp::integrator::LangevinThermostatHybrid::frictionThermo (class Particle & p, real weight) private
Definition at line 166 of file LangevinThermostatHybrid.cpp.
References espressopp::Particle::force(), LOG4ESPP_TRACE, espressopp::Particle::mass(), pref1, pref1cg, pref1hy, pref2, pref2cg, pref2hy, rng, and espressopp::Particle::velocity().
Referenced by thermalizeAdr().
getGamma()
real espressopp::integrator::LangevinThermostatHybrid::getGamma ()
Definition at line 65 of file LangevinThermostatHybrid.cpp.
References gamma.
Referenced by registerPython().
getGammaCG()
real espressopp::integrator::LangevinThermostatHybrid::getGammaCG ()
Definition at line 85 of file LangevinThermostatHybrid.cpp.
References gammacg.
Referenced by registerPython().
getGammaHybrid()
real espressopp::integrator::LangevinThermostatHybrid::getGammaHybrid ()
Definition at line 75 of file LangevinThermostatHybrid.cpp.
References gammahy.
Referenced by registerPython().
getSystem()
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::LatticeBoltzmann::assignMyLattice(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::PIAdressIntegrator::computeKineticEnergy(), espressopp::integrator::PIAdressIntegrator::computeMomentumDrift(), espressopp::integrator::PIAdressIntegrator::computePositionDrift(), espressopp::integrator::PIAdressIntegrator::computeRingEnergy(), espressopp::integrator::PIAdressIntegrator::computeRingEnergyRaw(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpXTCAdress::dump(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::io::DumpXYZ::DumpXYZ(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::VerletListTriple::registerPython(), espressopp::VerletList::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
getSystem1()
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
getSystem2()
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
getSystemRef()
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::addForces(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::addForces(), espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerletRESPA::calcForces(), espressopp::integrator::VelocityVerlet::calcForces(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::PIAdressIntegrator::calcForcesF(), espressopp::integrator::PIAdressIntegrator::calcForcesM(), espressopp::integrator::PIAdressIntegrator::calcForcesS(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeCOM(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeEnergy(), espressopp::integrator::PIAdressIntegrator::computeKineticEnergy(), espressopp::integrator::PIAdressIntegrator::computeMomentumDrift(), espressopp::integrator::PIAdressIntegrator::computePositionDrift(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::integrator::PIAdressIntegrator::computeRingEnergy(), espressopp::integrator::PIAdressIntegrator::computeRingEnergyRaw(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::PIAdressIntegrator::distributeForces(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::FixedLocalTupleComListInteractionTemplate(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::VelocityVerletRESPA::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerlet::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::PIAdressIntegrator::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::PIAdressIntegrator::initializeSetup(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::VelocityVerletRESPA::integrate1(), espressopp::integrator::VelocityVerlet::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::VelocityVerletRESPA::integrate2(), espressopp::integrator::VelocityVerlet::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::PIAdressIntegrator::integrateModePos(), espressopp::integrator::Adress::integrateSlow(), espressopp::integrator::PIAdressIntegrator::integrateV1(), espressopp::integrator::PIAdressIntegrator::integrateV2(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::PIAdressIntegrator::OUintegrate(), espressopp::integrator::VelocityVerlet::printForces(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerlet::printPositions(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::VelocityVerletRESPA::run(), espressopp::integrator::PIAdressIntegrator::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::MinimizeEnergy::run(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::Rattle::saveOldPos(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::PIAdressIntegrator::setWeights(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostatOnGroup::thermalize(), espressopp::integrator::LangevinThermostatOnRadius::thermalize(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::integrator::PIAdressIntegrator::transForces(), espressopp::integrator::PIAdressIntegrator::transMom1(), espressopp::integrator::PIAdressIntegrator::transMom2(), espressopp::integrator::PIAdressIntegrator::transPos1(), espressopp::integrator::PIAdressIntegrator::transPos2(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::io::DumpH5MD::update(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::VelocityVerletRESPA::updateForces(), espressopp::integrator::VelocityVerlet::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::PIAdressIntegrator::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
getSystemRef1()
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
getSystemRef2()
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
getTemperature()
real espressopp::integrator::LangevinThermostatHybrid::getTemperature ()
Definition at line 95 of file LangevinThermostatHybrid.cpp.
References temperature.
Referenced by registerPython().
getType()
ExtensionType espressopp::integrator::Extension::getType () inline inherited
Definition at line 67 of file Extension.hpp.
References espressopp::integrator::Extension::type.
Referenced by espressopp::integrator::Extension::registerPython().
heatUp()
void espressopp::integrator::LangevinThermostatHybrid::heatUp ()
very nasty: if we recalculate force when leaving/reentering the integrator, a(t) and a((t-dt)+dt) are NOT equal in the vv algorithm.
The random numbers are drawn twice, resulting in a different variance of the random force. This is corrected by additional heat when restarting the integrator here. Currently only works for the Langevin thermostat, although probably also others are affected.
Definition at line 218 of file LangevinThermostatHybrid.cpp.
References LOG4ESPP_INFO, pref2, pref2buffer, pref2buffercg, pref2bufferhy, pref2cg, and pref2hy.
Referenced by connect().
initialize()
void espressopp::integrator::LangevinThermostatHybrid::initialize ()
Definition at line 188 of file LangevinThermostatHybrid.cpp.
References gamma, gammacg, gammahy, espressopp::integrator::Extension::integrator, LOG4ESPP_INFO, pref1, pref1cg, pref1hy, pref2, pref2cg, pref2hy, and temperature.
Referenced by connect().
LOG4ESPP_DECL_LOGGER()
static espressopp::integrator::Extension::LOG4ESPP_DECL_LOGGER (theLogger) static protected inherited
Logger.
registerPython()
void espressopp::integrator::LangevinThermostatHybrid::registerPython () static
Register this class so it can be used from Python.
Definition at line 246 of file LangevinThermostatHybrid.cpp.
References connect(), disconnect(), getGamma(), getGammaCG(), getGammaHybrid(), getTemperature(), setGamma(), setGammaCG(), setGammaHybrid(), and setTemperature().
Referenced by espressopp::integrator::registerPython().
setGamma()
void espressopp::integrator::LangevinThermostatHybrid::setGamma (real gamma)
Definition at line 60 of file LangevinThermostatHybrid.cpp.
References gamma.
Referenced by registerPython().
setGammaCG()
void espressopp::integrator::LangevinThermostatHybrid::setGammaCG (real gammacg)
Definition at line 80 of file LangevinThermostatHybrid.cpp.
References gammacg.
Referenced by registerPython().
setGammaHybrid()
void espressopp::integrator::LangevinThermostatHybrid::setGammaHybrid (real gammahy)
Definition at line 70 of file LangevinThermostatHybrid.cpp.
References gammahy.
Referenced by registerPython().
setIntegrator()
void espressopp::integrator::Extension::setIntegrator (shared_ptr< MDIntegrator > _integrator) protected inherited
Definition at line 49 of file Extension.cpp.
References espressopp::integrator::Extension::integrator.
Referenced by espressopp::integrator::Extension::registerPython().
setTemperature()
void espressopp::integrator::LangevinThermostatHybrid::setTemperature (real temperature)
Definition at line 90 of file LangevinThermostatHybrid.cpp.
References temperature.
Referenced by registerPython().
setType()
void espressopp::integrator::Extension::setType (ExtensionType k) inline inherited
Definition at line 68 of file Extension.hpp.
Referenced by espressopp::integrator::Extension::registerPython().
thermalizeAdr()
void espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr ()
update of forces to thermalize the system
Definition at line 130 of file LangevinThermostatHybrid.cpp.
References fixedtupleList, frictionThermo(), espressopp::SystemAccess::getSystemRef(), espressopp::iterator::CellListIterator::isDone(), espressopp::Particle::lambda(), LOG4ESPP_DEBUG, and espressopp::System::storage.
Referenced by connect().
Member Data Documentation
_coolDown
boost::signals2::connection espressopp::integrator::LangevinThermostatHybrid::_coolDown private
Definition at line 89 of file LangevinThermostatHybrid.hpp.
Referenced by connect(), and disconnect().
_heatUp
boost::signals2::connection espressopp::integrator::LangevinThermostatHybrid::_heatUp private
Definition at line 89 of file LangevinThermostatHybrid.hpp.
Referenced by connect(), and disconnect().
_initialize
boost::signals2::connection espressopp::integrator::LangevinThermostatHybrid::_initialize private
Definition at line 89 of file LangevinThermostatHybrid.hpp.
Referenced by connect(), and disconnect().
_thermalizeAdr
boost::signals2::connection espressopp::integrator::LangevinThermostatHybrid::_thermalizeAdr private
Definition at line 89 of file LangevinThermostatHybrid.hpp.
Referenced by connect(), and disconnect().
fixedtupleList
shared_ptr<FixedTupleListAdress> espressopp::integrator::LangevinThermostatHybrid::fixedtupleList
Definition at line 51 of file LangevinThermostatHybrid.hpp.
Referenced by thermalizeAdr().
gamma
real espressopp::integrator::LangevinThermostatHybrid::gamma private
friction coefficient for aa region
Definition at line 99 of file LangevinThermostatHybrid.hpp.
Referenced by getGamma(), initialize(), LangevinThermostatHybrid(), and setGamma().
gammacg
real espressopp::integrator::LangevinThermostatHybrid::gammacg private
friction coefficient for cg region
Definition at line 100 of file LangevinThermostatHybrid.hpp.
Referenced by getGammaCG(), initialize(), LangevinThermostatHybrid(), and setGammaCG().
gammahy
real espressopp::integrator::LangevinThermostatHybrid::gammahy private
friction coefficient for hybrid region
Definition at line 101 of file LangevinThermostatHybrid.hpp.
Referenced by getGammaHybrid(), initialize(), LangevinThermostatHybrid(), and setGammaHybrid().
integrator
shared_ptr<MDIntegrator> espressopp::integrator::Extension::integrator protected inherited
Definition at line 72 of file Extension.hpp.
Referenced by espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::LatticeBoltzmann::calcRandForce(), espressopp::integrator::ExtAnalyze::connect(), espressopp::integrator::Rattle::connect(), espressopp::integrator::VelocityVerletOnRadius::connect(), espressopp::integrator::BerendsenBarostatAnisotropic::connect(), espressopp::integrator::BerendsenBarostat::connect(), espressopp::integrator::FixPositions::connect(), espressopp::integrator::Isokinetic::connect(), espressopp::integrator::ExtForce::connect(), espressopp::integrator::FreeEnergyCompensation::connect(), espressopp::integrator::BerendsenThermostat::connect(), espressopp::integrator::TDforce::connect(), espressopp::integrator::Settle::connect(), espressopp::integrator::LangevinThermostatOnGroup::connect(), espressopp::integrator::Adress::connect(), espressopp::integrator::CapForce::connect(), espressopp::integrator::LangevinThermostatOnRadius::connect(), espressopp::integrator::OnTheFlyFEC::connect(), espressopp::integrator::DPDThermostat::connect(), espressopp::integrator::GeneralizedLangevinThermostat::connect(), espressopp::integrator::LangevinThermostat1D::connect(), connect(), espressopp::integrator::LangevinBarostat::connect(), espressopp::integrator::LangevinThermostat::connect(), espressopp::integrator::AssociationReaction::connect(), espressopp::integrator::StochasticVelocityRescaling::connect(), espressopp::integrator::LatticeBoltzmann::connect(), espressopp::integrator::LatticeBoltzmann::convTimeMDtoLB(), espressopp::integrator::LangevinThermostatOnGroup::initialize(), espressopp::integrator::LangevinThermostatOnRadius::initialize(), espressopp::integrator::LangevinThermostat::initialize(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinThermostat1D::initialize(), espressopp::integrator::BerendsenThermostat::initialize(), initialize(), espressopp::integrator::BerendsenBarostatAnisotropic::initialize(), espressopp::integrator::BerendsenBarostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::Adress::integrateSlow(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::Extension::setIntegrator(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
pref1
real espressopp::integrator::LangevinThermostatHybrid::pref1 private
prefactor, reduces complexity of thermalize
Definition at line 104 of file LangevinThermostatHybrid.hpp.
Referenced by frictionThermo(), and initialize().
pref1cg
real espressopp::integrator::LangevinThermostatHybrid::pref1cg private
prefactor, reduces complexity of thermalize
Definition at line 108 of file LangevinThermostatHybrid.hpp.
Referenced by frictionThermo(), and initialize().
pref1hy
real espressopp::integrator::LangevinThermostatHybrid::pref1hy private
prefactor, reduces complexity of thermalize
Definition at line 106 of file LangevinThermostatHybrid.hpp.
Referenced by frictionThermo(), and initialize().
pref2
real espressopp::integrator::LangevinThermostatHybrid::pref2 private
prefactor, reduces complexity of thermalize
Definition at line 105 of file LangevinThermostatHybrid.hpp.
Referenced by coolDown(), frictionThermo(), heatUp(), and initialize().
pref2buffer
real espressopp::integrator::LangevinThermostatHybrid::pref2buffer private
temporary to save value between heatUp/coolDown
Definition at line 111 of file LangevinThermostatHybrid.hpp.
Referenced by coolDown(), and heatUp().
pref2buffercg
real espressopp::integrator::LangevinThermostatHybrid::pref2buffercg private
temporary to save value between heatUp/coolDown
Definition at line 113 of file LangevinThermostatHybrid.hpp.
Referenced by coolDown(), and heatUp().
pref2bufferhy
real espressopp::integrator::LangevinThermostatHybrid::pref2bufferhy private
temporary to save value between heatUp/coolDown
Definition at line 112 of file LangevinThermostatHybrid.hpp.
Referenced by coolDown(), and heatUp().
pref2cg
real espressopp::integrator::LangevinThermostatHybrid::pref2cg private
prefactor, reduces complexity of thermalize
Definition at line 109 of file LangevinThermostatHybrid.hpp.
Referenced by coolDown(), frictionThermo(), heatUp(), and initialize().
pref2hy
real espressopp::integrator::LangevinThermostatHybrid::pref2hy private
prefactor, reduces complexity of thermalize
Definition at line 107 of file LangevinThermostatHybrid.hpp.
Referenced by coolDown(), frictionThermo(), heatUp(), and initialize().
rng
shared_ptr< esutil::RNG > espressopp::integrator::LangevinThermostatHybrid::rng private
random number generator used for friction term
Definition at line 115 of file LangevinThermostatHybrid.hpp.
Referenced by frictionThermo(), and LangevinThermostatHybrid().
temperature
real espressopp::integrator::LangevinThermostatHybrid::temperature private
desired user temperature
Definition at line 102 of file LangevinThermostatHybrid.hpp.
Referenced by getTemperature(), initialize(), LangevinThermostatHybrid(), and setTemperature().
type
ExtensionType espressopp::integrator::Extension::type inherited
Definition at line 62 of file Extension.hpp.
Referenced by espressopp::integrator::TDforce::addForce(), espressopp::integrator::Adress::Adress(), espressopp::integrator::AssociationReaction::AssociationReaction(), espressopp::integrator::BerendsenBarostat::BerendsenBarostat(), espressopp::integrator::BerendsenBarostatAnisotropic::BerendsenBarostatAnisotropic(), espressopp::integrator::BerendsenThermostat::BerendsenThermostat(), espressopp::integrator::DPDThermostat::DPDThermostat(), espressopp::integrator::ExtAnalyze::ExtAnalyze(), espressopp::integrator::FreeEnergyCompensation::FreeEnergyCompensation(), espressopp::integrator::GeneralizedLangevinThermostat::GeneralizedLangevinThermostat(), espressopp::integrator::Extension::getType(), espressopp::integrator::LangevinBarostat::LangevinBarostat(), espressopp::integrator::LangevinThermostat::LangevinThermostat(), espressopp::integrator::LangevinThermostat1D::LangevinThermostat1D(), LangevinThermostatHybrid(), espressopp::integrator::LangevinThermostatOnGroup::LangevinThermostatOnGroup(), espressopp::integrator::LangevinThermostatOnRadius::LangevinThermostatOnRadius(), espressopp::integrator::OnTheFlyFEC::OnTheFlyFEC(), espressopp::integrator::TDforce::registerPython(), espressopp::integrator::StochasticVelocityRescaling::StochasticVelocityRescaling(), and espressopp::integrator::TDforce::TDforce().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/integrator/LangevinThermostatHybrid.hpp
/home/espressopp/espressopp/src/integrator/LangevinThermostatHybrid.cpp