ESPResSo++: espressopp::RealNDs Class Reference
espressopp::RealNDs Class Reference
#include <RealND.hpp>
Public Member Functions
void setDimension (int _dim)
int getDimension () const
RealNDs ()
RealNDs & operator= (const RealNDs &v)
RealND & operator[] (int i)
const RealND & operator[] (int i) const
RealND & at (int i)
const RealND & at (int i) const
void setItem (int i, const RealND &v)
RealND getItem (int i) const
void push_back (const RealND &v)
Static Public Member Functions
static void registerPython ()
Private Attributes
std::vector< shared_ptr< RealND > > data
int dimension
Detailed Description
Definition at line 114 of file RealND.hpp.
Constructor & Destructor Documentation
RealNDs()
espressopp::RealNDs::RealNDs () inline
Definition at line 337 of file RealND.hpp.
Member Function Documentation
at() [1/2]
RealND & espressopp::RealNDs::at (int i) inline
Definition at line 352 of file RealND.hpp.
References getDimension().
Referenced by getItem(), and setItem().
at() [2/2]
const RealND & espressopp::RealNDs::at (int i) const inline
Definition at line 358 of file RealND.hpp.
References getDimension().
getDimension()
int espressopp::RealNDs::getDimension () const inline
Definition at line 125 of file RealND.hpp.
References espressopp::RealND::at(), espressopp::RealND::dimension, espressopp::RealND::getItem(), espressopp::RealND::operator*(), espressopp::operator<<(), espressopp::RealND::operator=(), espressopp::RealND::operator[](), espressopp::RealND::push_back(), espressopp::RealND::registerPython(), and espressopp::RealND::setItem().
Referenced by at(), espressopp::realNDs_pickle_suite::getinitargs(), espressopp::operator<<(), operator=(), push_back(), and registerPython().
getItem()
RealND espressopp::RealNDs::getItem (int i) const inline
Definition at line 367 of file RealND.hpp.
References at().
Referenced by registerPython().
operator=()
RealNDs & espressopp::RealNDs::operator= (const RealNDs & v) inline
Definition at line 339 of file RealND.hpp.
References data, getDimension(), and setDimension().
operator[]() [1/2]
RealND & espressopp::RealNDs::operator[] (int i) inline
Definition at line 346 of file RealND.hpp.
References data.
operator[]() [2/2]
const RealND & espressopp::RealNDs::operator[] (int i) const inline
Definition at line 349 of file RealND.hpp.
References data.
push_back()
void espressopp::RealNDs::push_back (const RealND & v) inline
Definition at line 370 of file RealND.hpp.
References getDimension(), setDimension(), and setItem().
registerPython()
void espressopp::RealNDs::registerPython () static
Definition at line 86 of file RealND.cpp.
References getDimension(), getItem(), setDimension(), and setItem().
Referenced by espressopp::registerPython().
setDimension()
void espressopp::RealNDs::setDimension (int _dim) inline
Definition at line 119 of file RealND.hpp.
Referenced by espressopp::interaction::TabulatedSubEnsDihedral::addInteraction(), espressopp::interaction::TabulatedSubEnsAngular::addInteraction(), espressopp::interaction::TabulatedSubEns::addInteraction(), operator=(), push_back(), registerPython(), espressopp::interaction::TabulatedSubEnsDihedral::setDimension(), espressopp::interaction::TabulatedSubEnsAngular::setDimension(), espressopp::interaction::TabulatedSubEns::setDimension(), espressopp::interaction::TabulatedSubEnsDihedral::setFilenames(), espressopp::interaction::TabulatedSubEnsAngular::setFilenames(), espressopp::interaction::TabulatedSubEns::setFilenames(), espressopp::interaction::TabulatedSubEns::TabulatedSubEns(), espressopp::interaction::TabulatedSubEnsAngular::TabulatedSubEnsAngular(), and espressopp::interaction::TabulatedSubEnsDihedral::TabulatedSubEnsDihedral().
setItem()
void espressopp::RealNDs::setItem (int i, const RealND & v) inline
Definition at line 364 of file RealND.hpp.
References at().
Referenced by push_back(), and registerPython().
Member Data Documentation
data
std::vector<shared_ptr <RealND> > espressopp::RealNDs::data private
Definition at line 115 of file RealND.hpp.
Referenced by operator=(), and operator[]().
dimension
int espressopp::RealNDs::dimension private
Definition at line 117 of file RealND.hpp.
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/RealND.hpp
/home/espressopp/espressopp/src/RealND.cpp