ESPResSo++: espressopp::integrator::ExtForce Class Reference
espressopp::integrator::ExtForce Class Reference
ExtForce.
#include <ExtForce.hpp>
Public Types
enum ExtensionType {
all = 0, Thermostat = 1, Barostat = 2, Constraint = 3,
Adress = 4, FreeEnergyCompensation = 5, ExtForce = 6, ExtAnalysis = 7,
Reaction = 8
}
Public Member Functions
ExtForce (shared_ptr< System > _system, const Real3D &_extForce)
ExtForce (shared_ptr< System > _system, const Real3D &_extForce, shared_ptr< ParticleGroup > _particleGroup)
void setExtForce (Real3D &_extForce)
Real3D & getExtForce ()
void setParticleGroup (shared_ptr< ParticleGroup > _particleGroup)
shared_ptr< ParticleGroup > getParticleGroup ()
void applyForceToGroup ()
void applyForceToAll ()
virtual ~ExtForce ()
ExtensionType getType ()
void setType (ExtensionType k)
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
Register this class so it can be used from Python.
Public Attributes
ExtensionType type
Protected Member Functions
void setIntegrator (shared_ptr< MDIntegrator > _integrator)
Protected Attributes
shared_ptr< MDIntegrator > integrator
Private Member Functions
void connect ()
void disconnect ()
Static Private Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Private Attributes
boost::signals2::connection _aftInitF
shared_ptr< ParticleGroup > particleGroup
bool allParticles
Real3D extForce
Detailed Description
ExtForce.
Definition at line 40 of file ExtForce.hpp.
Member Enumeration Documentation
enum espressopp::integrator::Extension::ExtensionType [inherited]
Enumerator:
all
Thermostat
Barostat
Constraint
Adress
FreeEnergyCompensation
ExtForce
ExtAnalysis
Reaction
Definition at line 48 of file Extension.hpp.
Constructor & Destructor Documentation
espressopp::integrator::ExtForce::ExtForce (shared_ptr< System > _system, const Real3D & _extForce)
Definition at line 39 of file ExtForce.cpp.
References allParticles, and LOG4ESPP_INFO.
espressopp::integrator::ExtForce::ExtForce (shared_ptr< System > _system, const Real3D & _extForce, shared_ptr< ParticleGroup > _particleGroup)
Definition at line 46 of file ExtForce.cpp.
References allParticles, and LOG4ESPP_INFO.
virtual espressopp::integrator::ExtForce::~ExtForce () [inline, virtual]
Definition at line 59 of file ExtForce.hpp.
Member Function Documentation
void espressopp::integrator::ExtForce::applyForceToAll ()
Definition at line 97 of file ExtForce.cpp.
References extForce, espressopp::SystemAccess::getSystemRef(), espressopp::iterator::CellListIterator::isDone(), and espressopp::System::storage.
Referenced by connect().
void espressopp::integrator::ExtForce::applyForceToGroup ()
Definition at line 89 of file ExtForce.cpp.
References extForce, LOG4ESPP_DEBUG, and particleGroup.
Referenced by connect().
void espressopp::integrator::ExtForce::connect () [private, virtual]
Implements espressopp::integrator::Extension.
Definition at line 57 of file ExtForce.cpp.
References _aftInitF, allParticles, applyForceToAll(), applyForceToGroup(), and espressopp::integrator::Extension::integrator.
Referenced by registerPython(), and setParticleGroup().
void espressopp::integrator::ExtForce::disconnect () [private, virtual]
Implements espressopp::integrator::Extension.
Definition at line 53 of file ExtForce.cpp.
References _aftInitF.
Referenced by registerPython(), and setParticleGroup().
Real3D & espressopp::integrator::ExtForce::getExtForce ()
Definition at line 70 of file ExtForce.cpp.
References extForce.
Referenced by registerPython().
shared_ptr< ParticleGroup > espressopp::integrator::ExtForce::getParticleGroup ()
Definition at line 83 of file ExtForce.cpp.
References particleGroup.
Referenced by registerPython().
shared_ptr< System > espressopp::SystemAccess::getSystem () const [inline, inherited]
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::LatticeBoltzmann::initGammas(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readCouplForces(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::VerletListTriple::registerPython(), espressopp::VerletList::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveCouplForces(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::analysis::LBOutputScreen::writeOutput(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const [inline, inherited]
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const [inline, inherited]
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
System& espressopp::SystemAccess::getSystemRef () const [inline, inherited]
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), applyForceToAll(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readCouplForces(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::LatticeBoltzmann::restoreLBForces(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::LatticeBoltzmann::saveCouplForces(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
System& espressopp::SystemAccess::getSystemRef1 () const [inline, inherited]
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
System& espressopp::SystemAccess::getSystemRef2 () const [inline, inherited]
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
ExtensionType espressopp::integrator::Extension::getType () [inline, inherited]
Definition at line 67 of file Extension.hpp.
References espressopp::integrator::Extension::type.
Referenced by espressopp::integrator::Extension::registerPython().
static espressopp::integrator::ExtForce::LOG4ESPP_DECL_LOGGER (theLogger) [static, private]
Logger.
Reimplemented from espressopp::integrator::Extension.
void espressopp::integrator::ExtForce::registerPython () [static]
Register this class so it can be used from Python.
Reimplemented from espressopp::integrator::Extension.
Definition at line 109 of file ExtForce.cpp.
References connect(), disconnect(), getExtForce(), getParticleGroup(), setExtForce(), and setParticleGroup().
Referenced by espressopp::integrator::registerPython().
void espressopp::integrator::ExtForce::setExtForce (Real3D & _extForce)
Definition at line 66 of file ExtForce.cpp.
References extForce.
Referenced by registerPython().
void espressopp::integrator::Extension::setIntegrator (shared_ptr< MDIntegrator > _integrator) [protected, inherited]
Definition at line 49 of file Extension.cpp.
References espressopp::integrator::Extension::integrator.
Referenced by espressopp::integrator::Extension::registerPython().
void espressopp::integrator::ExtForce::setParticleGroup (shared_ptr< ParticleGroup > _particleGroup)
Definition at line 74 of file ExtForce.cpp.
References allParticles, connect(), disconnect(), and particleGroup.
Referenced by registerPython().
void espressopp::integrator::Extension::setType (ExtensionType k) [inline, inherited]
Definition at line 68 of file Extension.hpp.
References espressopp::integrator::Extension::type.
Referenced by espressopp::integrator::Extension::registerPython().
Member Data Documentation
boost::signals2::connection espressopp::integrator::ExtForce::_aftInitF [private]
Definition at line 65 of file ExtForce.hpp.
Referenced by connect(), and disconnect().
bool espressopp::integrator::ExtForce::allParticles [private]
Definition at line 67 of file ExtForce.hpp.
Referenced by connect(), ExtForce(), and setParticleGroup().
Real3D espressopp::integrator::ExtForce::extForce [private]
Definition at line 68 of file ExtForce.hpp.
Referenced by applyForceToAll(), applyForceToGroup(), getExtForce(), and setExtForce().
shared_ptr<MDIntegrator> espressopp::integrator::Extension::integrator [protected, inherited]
Definition at line 72 of file Extension.hpp.
Referenced by espressopp::integrator::LatticeBoltzmann::calcRandForce(), espressopp::integrator::ExtAnalyze::connect(), espressopp::integrator::VelocityVerletOnRadius::connect(), espressopp::integrator::BerendsenBarostatAnisotropic::connect(), espressopp::integrator::BerendsenBarostat::connect(), espressopp::integrator::FreeEnergyCompensation::connect(), espressopp::integrator::FixPositions::connect(), espressopp::integrator::Isokinetic::connect(), connect(), espressopp::integrator::BerendsenThermostat::connect(), espressopp::integrator::TDforce::connect(), espressopp::integrator::Settle::connect(), espressopp::integrator::Adress::connect(), espressopp::integrator::CapForce::connect(), espressopp::integrator::OnTheFlyFEC::connect(), espressopp::integrator::DPDThermostat::connect(), espressopp::integrator::LangevinThermostat::connect(), espressopp::integrator::GeneralizedLangevinThermostat::connect(), espressopp::integrator::LangevinThermostat1D::connect(), espressopp::integrator::LangevinThermostatHybrid::connect(), espressopp::integrator::LangevinBarostat::connect(), espressopp::integrator::AssociationReaction::connect(), espressopp::integrator::StochasticVelocityRescaling::connect(), espressopp::integrator::LiquidGasLB::connect(), espressopp::integrator::LatticeBoltzmann::connect(), espressopp::integrator::LatticeBoltzmann::convTimeMDtoLB(), espressopp::integrator::LangevinThermostat::initialize(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinThermostat1D::initialize(), espressopp::integrator::BerendsenThermostat::initialize(), espressopp::integrator::LangevinThermostatHybrid::initialize(), espressopp::integrator::BerendsenBarostatAnisotropic::initialize(), espressopp::integrator::BerendsenBarostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::LiquidGasLB::makeLBStep(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::saveCouplForces(), espressopp::integrator::Extension::setIntegrator(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
shared_ptr< ParticleGroup > espressopp::integrator::ExtForce::particleGroup [private]
Definition at line 66 of file ExtForce.hpp.
Referenced by applyForceToGroup(), getParticleGroup(), and setParticleGroup().
ExtensionType espressopp::integrator::Extension::type [inherited]
Definition at line 62 of file Extension.hpp.
Referenced by espressopp::integrator::Adress::Adress(), espressopp::integrator::AssociationReaction::AssociationReaction(), espressopp::integrator::BerendsenBarostat::BerendsenBarostat(), espressopp::integrator::BerendsenBarostatAnisotropic::BerendsenBarostatAnisotropic(), espressopp::integrator::BerendsenThermostat::BerendsenThermostat(), espressopp::integrator::DPDThermostat::DPDThermostat(), espressopp::integrator::ExtAnalyze::ExtAnalyze(), espressopp::integrator::FreeEnergyCompensation::FreeEnergyCompensation(), espressopp::integrator::GeneralizedLangevinThermostat::GeneralizedLangevinThermostat(), espressopp::integrator::Extension::getType(), espressopp::integrator::LangevinBarostat::LangevinBarostat(), espressopp::integrator::LangevinThermostat::LangevinThermostat(), espressopp::integrator::LangevinThermostat1D::LangevinThermostat1D(), espressopp::integrator::LangevinThermostatHybrid::LangevinThermostatHybrid(), espressopp::integrator::OnTheFlyFEC::OnTheFlyFEC(), espressopp::integrator::TDforce::registerPython(), espressopp::integrator::Extension::setType(), espressopp::integrator::StochasticVelocityRescaling::StochasticVelocityRescaling(), and espressopp::integrator::TDforce::TDforce().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/integrator/ExtForce.hpp
/home/travis/build/espressopp/espressopp/src/integrator/ExtForce.cpp