ESPResSo++: espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG > Class Template Reference
espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG > Class Template Reference
#include <VerletListAdressInteractionTemplate.hpp>
Public Member Functions
VerletListAdressInteractionTemplate (shared_ptr< VerletListAdress > _verletList, shared_ptr< FixedTupleListAdress > _fixedtupleList)
void setVerletList (shared_ptr< VerletListAdress > _verletList)
shared_ptr< VerletListAdress > getVerletList ()
void setFixedTupleList (shared_ptr< FixedTupleListAdress > _fixedtupleList)
void setPotentialAT (int type1, int type2, const PotentialAT &potential)
void setPotentialCG (int type1, int type2, const PotentialCG &potential)
PotentialAT & getPotentialAT (int type1, int type2)
PotentialCG & getPotentialCG (int type1, int type2)
virtual void addForces ()
virtual real computeEnergy ()
virtual real computeEnergyDeriv ()
virtual real computeEnergyAA ()
virtual real computeEnergyCG ()
virtual void computeVirialX (std::vector< real > &p_xx_total, int bins)
virtual real computeVirial ()
virtual void computeVirialTensor (Tensor &w)
virtual void computeVirialTensor (Tensor &w, real z)
virtual void computeVirialTensor (Tensor *w, int n)
virtual real getMaxCutoff ()
This method returns the maximal cutoff defined for one type pair.
virtual int bondType ()
Static Public Member Functions
static void registerPython ()
Protected Types
typedef _PotentialAT PotentialAT
typedef _PotentialCG PotentialCG
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Protected Attributes
int ntypes
shared_ptr< VerletListAdress > verletList
shared_ptr< FixedTupleListAdress > fixedtupleList
esutil::Array2D< PotentialAT,
esutil::enlarge > potentialArrayAT
esutil::Array2D< PotentialCG,
esutil::enlarge > potentialArrayCG
real pidhy2
real dexdhy
real dexdhy2
real dex
real dhy
real dex2
Detailed Description
template<typename _PotentialAT, typename _PotentialCG>
class espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >
Definition at line 44 of file VerletListAdressInteractionTemplate.hpp.
Member Typedef Documentation
template<typename _PotentialAT , typename _PotentialCG > typedef _PotentialAT espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::PotentialAT protected
Definition at line 47 of file VerletListAdressInteractionTemplate.hpp.
template<typename _PotentialAT , typename _PotentialCG > typedef _PotentialCG espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::PotentialCG protected
Definition at line 48 of file VerletListAdressInteractionTemplate.hpp.
Constructor & Destructor Documentation
template<typename _PotentialAT , typename _PotentialCG > espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::VerletListAdressInteractionTemplate (shared_ptr< VerletListAdress > _verletList, shared_ptr< FixedTupleListAdress > _fixedtupleList) inline
Definition at line 52 of file VerletListAdressInteractionTemplate.hpp.
References espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::dex, espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::dex2, espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::dexdhy, espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::dexdhy2, espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::dhy, M_PI, espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::ntypes, espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::pidhy2, espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::potentialArrayAT, espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::potentialArrayCG, and espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::verletList.
Member Function Documentation
template<typename _PotentialAT , typename _PotentialCG > void espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::addForces () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 149 of file VerletListAdressInteractionTemplate.hpp.
References espressopp::Particle::force(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::Particle::lambda(), LOG4ESPP_INFO, espressopp::Particle::position(), espressopp::Particle::type(), and espressopp::Particle::velocity().
template<typename _PotentialAT , typename _PotentialCG > virtual int espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::bondType () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 124 of file VerletListAdressInteractionTemplate.hpp.
References espressopp::interaction::Nonbonded.
template<typename _PotentialAT , typename _PotentialCG > real espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeEnergy () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 509 of file VerletListAdressInteractionTemplate.hpp.
References espressopp::Real3D::begin(), espressopp::Particle::getMass(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::Particle::lambda(), LOG4ESPP_INFO, espressopp::Particle::mass(), espressopp::Particle::position(), espressopp::Real3D::sqr(), espressopp::Particle::type(), and espressopp::Particle::velocity().
template<typename _PotentialAT , typename _PotentialCG > real espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeEnergyAA () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 734 of file VerletListAdressInteractionTemplate.hpp.
template<typename _PotentialAT , typename _PotentialCG > real espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeEnergyCG () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 741 of file VerletListAdressInteractionTemplate.hpp.
template<typename _PotentialAT , typename _PotentialCG > real espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeEnergyDeriv () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 682 of file VerletListAdressInteractionTemplate.hpp.
References espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::Particle::lambda(), LOG4ESPP_INFO, and espressopp::Particle::type().
template<typename _PotentialAT , typename _PotentialCG > real espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirial () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 1041 of file VerletListAdressInteractionTemplate.hpp.
References espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_INFO, mpiWorld, espressopp::Particle::position(), and espressopp::Particle::type().
template<typename _PotentialAT , typename _PotentialCG > void espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialTensor (Tensor & w) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 1083 of file VerletListAdressInteractionTemplate.hpp.
References espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_INFO, mpiWorld, espressopp::Particle::position(), and espressopp::Particle::type().
template<typename _PotentialAT , typename _PotentialCG > void espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialTensor (Tensor & w, real z) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 1122 of file VerletListAdressInteractionTemplate.hpp.
References LOG4ESPP_INFO.
template<typename _PotentialAT , typename _PotentialCG > void espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialTensor (Tensor * w, int n) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 1185 of file VerletListAdressInteractionTemplate.hpp.
template<typename _PotentialAT , typename _PotentialCG > void espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialX (std::vector< real > & p_xx_total, int bins) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 749 of file VerletListAdressInteractionTemplate.hpp.
References espressopp::Real3D::at(), espressopp::System::bc, espressopp::Real3D::begin(), espressopp::Particle::getMass(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::Particle::lambda(), espressopp::Particle::mass(), mpiWorld, espressopp::Particle::position(), espressopp::Real3D::sqr(), espressopp::Particle::type(), and espressopp::Particle::velocity().
template<typename _PotentialAT , typename _PotentialCG > real espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::getMaxCutoff () inline virtual
This method returns the maximal cutoff defined for one type pair.
Implements espressopp::interaction::Interaction.
Definition at line 1192 of file VerletListAdressInteractionTemplate.hpp.
template<typename _PotentialAT , typename _PotentialCG > PotentialAT& espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::getPotentialAT (int type1, int type2) inline
Definition at line 105 of file VerletListAdressInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), and espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::potentialArrayAT.
template<typename _PotentialAT , typename _PotentialCG > PotentialCG& espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::getPotentialCG (int type1, int type2) inline
Definition at line 109 of file VerletListAdressInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), and espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::potentialArrayCG.
template<typename _PotentialAT , typename _PotentialCG > shared_ptr<VerletListAdress> espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::getVerletList () inline
Definition at line 74 of file VerletListAdressInteractionTemplate.hpp.
References espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::verletList.
static espressopp::interaction::Interaction::LOG4ESPP_DECL_LOGGER (theLogger) static protected inherited
Logger.
void espressopp::interaction::Interaction::registerPython () static inherited
Definition at line 36 of file Interaction.cpp.
References espressopp::interaction::Interaction::bondType(), espressopp::interaction::Interaction::computeEnergy(), espressopp::interaction::Interaction::computeEnergyAA(), espressopp::interaction::Interaction::computeEnergyCG(), espressopp::interaction::Interaction::computeEnergyDeriv(), and espressopp::interaction::Interaction::computeVirial().
Referenced by espressopp::interaction::registerPython().
template<typename _PotentialAT , typename _PotentialCG > void espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::setFixedTupleList (shared_ptr< FixedTupleListAdress > _fixedtupleList) inline
Definition at line 79 of file VerletListAdressInteractionTemplate.hpp.
References espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::fixedtupleList.
template<typename _PotentialAT , typename _PotentialCG > void espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::setPotentialAT (int type1, int type2, const PotentialAT & potential) inline
Definition at line 84 of file VerletListAdressInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::ntypes, and espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::potentialArrayAT.
template<typename _PotentialAT , typename _PotentialCG > void espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::setPotentialCG (int type1, int type2, const PotentialCG & potential) inline
Definition at line 95 of file VerletListAdressInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::ntypes, and espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::potentialArrayCG.
template<typename _PotentialAT , typename _PotentialCG > void espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::setVerletList (shared_ptr< VerletListAdress > _verletList) inline
Definition at line 70 of file VerletListAdressInteractionTemplate.hpp.
References espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::verletList.
Member Data Documentation
template<typename _PotentialAT , typename _PotentialCG > real espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::dex protected
Definition at line 137 of file VerletListAdressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::VerletListAdressInteractionTemplate().
template<typename _PotentialAT , typename _PotentialCG > real espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::dex2 protected
Definition at line 139 of file VerletListAdressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::VerletListAdressInteractionTemplate().
template<typename _PotentialAT , typename _PotentialCG > real espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::dexdhy protected
Definition at line 135 of file VerletListAdressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::VerletListAdressInteractionTemplate().
template<typename _PotentialAT , typename _PotentialCG > real espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::dexdhy2 protected
Definition at line 136 of file VerletListAdressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::VerletListAdressInteractionTemplate().
template<typename _PotentialAT , typename _PotentialCG > real espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::dhy protected
Definition at line 138 of file VerletListAdressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::VerletListAdressInteractionTemplate().
template<typename _PotentialAT , typename _PotentialCG > shared_ptr<FixedTupleListAdress> espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::fixedtupleList protected
Definition at line 129 of file VerletListAdressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::setFixedTupleList().
template<typename _PotentialAT , typename _PotentialCG > int espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::ntypes protected
Definition at line 127 of file VerletListAdressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::setPotentialAT(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::setPotentialCG(), and espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::VerletListAdressInteractionTemplate().
template<typename _PotentialAT , typename _PotentialCG > real espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::pidhy2 protected
Definition at line 134 of file VerletListAdressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::VerletListAdressInteractionTemplate().
template<typename _PotentialAT , typename _PotentialCG > esutil::Array2D<PotentialAT, esutil::enlarge> espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::potentialArrayAT protected
Definition at line 130 of file VerletListAdressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::getPotentialAT(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::setPotentialAT(), and espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::VerletListAdressInteractionTemplate().
template<typename _PotentialAT , typename _PotentialCG > esutil::Array2D<PotentialCG, esutil::enlarge> espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::potentialArrayCG protected
Definition at line 131 of file VerletListAdressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::getPotentialCG(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::setPotentialCG(), and espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::VerletListAdressInteractionTemplate().
template<typename _PotentialAT , typename _PotentialCG > shared_ptr<VerletListAdress> espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::verletList protected
Definition at line 128 of file VerletListAdressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::getVerletList(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::setVerletList(), and espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::VerletListAdressInteractionTemplate().
The documentation for this class was generated from the following file:
/home/travis/build/espressopp/espressopp/src/interaction/VerletListAdressInteractionTemplate.hpp