ESPResSo++: espressopp::analysis::ConfigurationsExtAdress Class Reference
espressopp::analysis::ConfigurationsExtAdress Class Reference
#include <ConfigurationsExtAdress.hpp>
Public Member Functions
ConfigurationsExtAdress (shared_ptr< System > system, shared_ptr< FixedTupleListAdress > _fixedTupleList)
Constructor, allow for unlimited snapshots.
void setCapacity (int max)
set number of maximal snapshots.
int getCapacity ()
get number of maximal snapshots.
int getSize ()
get number of available snapshots.
~ConfigurationsExtAdress ()
bool getUnfolded ()
void setUnfolded (bool v)
void gather ()
Gake a snapshot of all current particle positions.
ConfigurationExtPtr get (int stackpos)
Get a configuration from stack.
ConfigurationExtPtr back ()
ConfigurationExtList all ()
void clear ()
void setFixedTupleList (shared_ptr< FixedTupleListAdress > _fixedtupleList)
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (logger)
Protected Attributes
shared_ptr< FixedTupleListAdress > fixedTupleList
Private Member Functions
void pushConfig (ConfigurationExtPtr config)
Private Attributes
ConfigurationExtList configurationsExtAdress
int maxConfigs
bool unfolded
Detailed Description
Definition at line 43 of file ConfigurationsExtAdress.hpp.
Constructor & Destructor Documentation
espressopp::analysis::ConfigurationsExtAdress::ConfigurationsExtAdress (shared_ptr< System > system, shared_ptr< FixedTupleListAdress > _fixedTupleList) inline
Constructor, allow for unlimited snapshots.
Definition at line 49 of file ConfigurationsExtAdress.hpp.
References maxConfigs.
espressopp::analysis::ConfigurationsExtAdress::~ConfigurationsExtAdress () inline
Definition at line 64 of file ConfigurationsExtAdress.hpp.
Member Function Documentation
ConfigurationExtList espressopp::analysis::ConfigurationsExtAdress::all ()
Definition at line 81 of file ConfigurationsExtAdress.cpp.
Referenced by registerPython().
ConfigurationExtPtr espressopp::analysis::ConfigurationsExtAdress::back ()
Definition at line 99 of file ConfigurationsExtAdress.cpp.
Referenced by espressopp::io::DumpGROAdress::dump(), and registerPython().
void espressopp::analysis::ConfigurationsExtAdress::clear () inline
Definition at line 79 of file ConfigurationsExtAdress.hpp.
References configurationsExtAdress.
Referenced by registerPython().
void espressopp::analysis::ConfigurationsExtAdress::gather ()
Gake a snapshot of all current particle positions.
Definition at line 120 of file ConfigurationsExtAdress.cpp.
References espressopp::System::bc, espressopp::System::comm, DEFAULT_TAG, espressopp::Particle::id(), espressopp::Particle::image(), espressopp::iterator::CellListIterator::isDone(), LOG4ESPP_DEBUG, LOG4ESPP_ERROR, LOG4ESPP_INFO, espressopp::Particle::position(), espressopp::RealND::setItem(), espressopp::System::storage, and espressopp::Particle::velocity().
Referenced by espressopp::io::DumpGROAdress::dump(), and registerPython().
ConfigurationExtPtr espressopp::analysis::ConfigurationsExtAdress::get (int stackpos)
Get a configuration from stack.
Definition at line 88 of file ConfigurationsExtAdress.cpp.
References LOG4ESPP_ERROR.
Referenced by registerPython().
int espressopp::analysis::ConfigurationsExtAdress::getCapacity ()
get number of maximal snapshots.
Definition at line 70 of file ConfigurationsExtAdress.cpp.
Referenced by registerPython().
int espressopp::analysis::ConfigurationsExtAdress::getSize ()
get number of available snapshots.
Definition at line 75 of file ConfigurationsExtAdress.cpp.
Referenced by registerPython().
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::io::DumpXYZ::DumpXYZ(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::LatticeBoltzmann::initGammas(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readCouplForces(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::VerletListTriple::registerPython(), espressopp::VerletList::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveCouplForces(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::analysis::LBOutputScreen::writeOutput(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readCouplForces(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::LatticeBoltzmann::restoreLBForces(), espressopp::integrator::MinimizeEnergy::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::LatticeBoltzmann::saveCouplForces(), espressopp::integrator::Rattle::saveOldPos(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostatOnGroup::thermalize(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
bool espressopp::analysis::ConfigurationsExtAdress::getUnfolded () inline
Definition at line 66 of file ConfigurationsExtAdress.hpp.
References unfolded.
Referenced by registerPython().
static espressopp::analysis::ConfigurationsExtAdress::LOG4ESPP_DECL_LOGGER (logger) static protected
void espressopp::analysis::ConfigurationsExtAdress::pushConfig (ConfigurationExtPtr config) private
Definition at line 104 of file ConfigurationsExtAdress.cpp.
References LOG4ESPP_DEBUG.
void espressopp::analysis::ConfigurationsExtAdress::registerPython () static
Definition at line 331 of file ConfigurationsExtAdress.cpp.
References all(), back(), clear(), gather(), get(), getCapacity(), getSize(), getUnfolded(), setCapacity(), and setUnfolded().
Referenced by espressopp::analysis::registerPython().
void espressopp::analysis::ConfigurationsExtAdress::setCapacity (int max)
set number of maximal snapshots.
Definition at line 43 of file ConfigurationsExtAdress.cpp.
References LOG4ESPP_ERROR, and LOG4ESPP_INFO.
Referenced by registerPython().
void espressopp::analysis::ConfigurationsExtAdress::setFixedTupleList (shared_ptr< FixedTupleListAdress > _fixedtupleList) inline
Definition at line 82 of file ConfigurationsExtAdress.hpp.
References fixedTupleList.
void espressopp::analysis::ConfigurationsExtAdress::setUnfolded (bool v) inline
Definition at line 67 of file ConfigurationsExtAdress.hpp.
References unfolded.
Referenced by espressopp::io::DumpGROAdress::dump(), and registerPython().
Member Data Documentation
ConfigurationExtList espressopp::analysis::ConfigurationsExtAdress::configurationsExtAdress private
Definition at line 97 of file ConfigurationsExtAdress.hpp.
Referenced by clear().
shared_ptr<FixedTupleListAdress> espressopp::analysis::ConfigurationsExtAdress::fixedTupleList protected
Definition at line 91 of file ConfigurationsExtAdress.hpp.
Referenced by setFixedTupleList().
int espressopp::analysis::ConfigurationsExtAdress::maxConfigs private
Definition at line 99 of file ConfigurationsExtAdress.hpp.
Referenced by ConfigurationsExtAdress().
bool espressopp::analysis::ConfigurationsExtAdress::unfolded private
Definition at line 101 of file ConfigurationsExtAdress.hpp.
Referenced by getUnfolded(), and setUnfolded().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/analysis/ConfigurationsExtAdress.hpp
/home/travis/build/espressopp/espressopp/src/analysis/ConfigurationsExtAdress.cpp