ESPResSo++: espressopp::FixedTripleAngleList Class Reference
espressopp::FixedTripleAngleList Class Reference
#include <FixedTripleAngleList.hpp>
Public Types
typedef ESPPIterator< std::vector< ParticleTriple > > Iterator
Public Member Functions
FixedTripleAngleList (shared_ptr< storage::Storage > _storage)
virtual ~FixedTripleAngleList ()
virtual bool add (longint pid1, longint pid2, longint pid3)
Add the given particle triple to the list on this processor if the particle with the lower id belongs to this processor.
virtual void beforeSendParticles (ParticleList &pl, class OutBuffer &buf)
void afterRecvParticles (ParticleList &pl, class InBuffer &buf)
virtual void onParticlesChanged ()
python::list getTriples ()
python::list getTriplesAngles ()
real getAngle (int, int, int)
int size ()
Get the number of triples in the GlobalTriples list.
void add (Particle *p1, Particle *p2, Particle *p3)
void add (Particle &p1, Particle &p2, Particle &p3)
void add (std::vector< Particle *> particles)
Static Public Member Functions
static void registerPython ()
Protected Types
typedef multimap< longint, pair< pair< longint, longint >, real > > TriplesAngles
typedef std::vector< ParticleTriple > Super
Protected Attributes
boost::signals2::connection con1
boost::signals2::connection con2
boost::signals2::connection con3
shared_ptr< storage::Storage > storage
TriplesAngles triplesAngles
Static Private Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Detailed Description
Definition at line 47 of file FixedTripleAngleList.hpp.
Member Typedef Documentation
Iterator
typedef ESPPIterator<std::vector< ParticleTriple > > espressopp::esutil::ESPPContainer< std::vector< ParticleTriple > >::Iterator inherited
Definition at line 66 of file ESPPIterator.hpp.
Super
typedef std::vector< ParticleTriple > espressopp::esutil::ESPPContainer< std::vector< ParticleTriple > >::Super protected inherited
Definition at line 64 of file ESPPIterator.hpp.
TriplesAngles
typedef multimap<longint,pair<pair<longint, longint>, real> > espressopp::FixedTripleAngleList::TriplesAngles protected
Definition at line 50 of file FixedTripleAngleList.hpp.
Constructor & Destructor Documentation
FixedTripleAngleList()
espressopp::FixedTripleAngleList::FixedTripleAngleList (shared_ptr< storage::Storage > _storage)
Definition at line 38 of file FixedTripleAngleList.cpp.
References afterRecvParticles(), beforeSendParticles(), con1, con2, con3, LOG4ESPP_INFO, onParticlesChanged(), and storage.
~FixedTripleAngleList()
espressopp::FixedTripleAngleList::~FixedTripleAngleList () virtual
Definition at line 51 of file FixedTripleAngleList.cpp.
References add(), con1, con2, con3, and LOG4ESPP_INFO.
Member Function Documentation
add() [1/4]
bool espressopp::FixedTripleAngleList::add (longint pid1, longint pid2, longint pid3) virtual
Add the given particle triple to the list on this processor if the particle with the lower id belongs to this processor.
Note that this routine does not check whether the triple is inserted on another processor as well.
Returns
whether the triple was inserted on this processor.
Definition at line 61 of file FixedTripleAngleList.cpp.
References espressopp::Real3D::abs(), espressopp::System::bc, espressopp::esutil::Error::checkException(), espressopp::System::comm, LOG4ESPP_INFO, espressopp::Particle::position(), espressopp::esutil::Error::setException(), storage, and triplesAngles.
Referenced by onParticlesChanged(), registerPython(), and ~FixedTripleAngleList().
add() [2/4]
void espressopp::TripleList::add (Particle * p1, Particle * p2, Particle * p3) inline inherited
Definition at line 483 of file Particle.hpp.
Referenced by espressopp::FixedListComm::add(), espressopp::VerletListTriple::checkTriple(), and espressopp::FixedListComm::onParticlesChanged().
add() [3/4]
void espressopp::TripleList::add (Particle & p1, Particle & p2, Particle & p3) inline inherited
Definition at line 487 of file Particle.hpp.
add() [4/4]
void espressopp::TripleList::add (std::vector< Particle *> particles) inline inherited
Definition at line 490 of file Particle.hpp.
afterRecvParticles()
void espressopp::FixedTripleAngleList::afterRecvParticles (ParticleList & pl, class InBuffer & buf)
Definition at line 206 of file FixedTripleAngleList.cpp.
References LOG4ESPP_INFO, espressopp::InBuffer::read(), size(), and triplesAngles.
Referenced by FixedTripleAngleList().
beforeSendParticles()
void espressopp::FixedTripleAngleList::beforeSendParticles (ParticleList & pl, class OutBuffer & buf) virtual
Definition at line 169 of file FixedTripleAngleList.cpp.
References espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_INFO, triplesAngles, and espressopp::OutBuffer::write().
Referenced by FixedTripleAngleList().
getAngle()
real espressopp::FixedTripleAngleList::getAngle (int pid1, int pid2, int pid3)
Definition at line 143 of file FixedTripleAngleList.cpp.
References triplesAngles.
Referenced by registerPython().
getTriples()
python::list espressopp::FixedTripleAngleList::getTriples ()
Definition at line 119 of file FixedTripleAngleList.cpp.
References triplesAngles.
Referenced by registerPython().
getTriplesAngles()
python::list espressopp::FixedTripleAngleList::getTriplesAngles ()
Definition at line 131 of file FixedTripleAngleList.cpp.
References triplesAngles.
Referenced by registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::FixedTripleAngleList::LOG4ESPP_DECL_LOGGER (theLogger) static private
onParticlesChanged()
void espressopp::FixedTripleAngleList::onParticlesChanged () virtual
Definition at line 238 of file FixedTripleAngleList.cpp.
References add(), espressopp::esutil::Error::checkException(), espressopp::System::comm, LOG4ESPP_INFO, espressopp::esutil::Error::setException(), storage, and triplesAngles.
Referenced by FixedTripleAngleList().
registerPython()
void espressopp::FixedTripleAngleList::registerPython () static
Definition at line 282 of file FixedTripleAngleList.cpp.
References add(), getAngle(), getTriples(), getTriplesAngles(), and size().
Referenced by espressopp::registerPython().
size()
int espressopp::FixedTripleAngleList::size () inline
Get the number of triples in the GlobalTriples list.
Definition at line 78 of file FixedTripleAngleList.hpp.
References LOG4ESPP_DECL_LOGGER, and espressopp::analysis::registerPython().
Referenced by afterRecvParticles(), and registerPython().
Member Data Documentation
con1
boost::signals2::connection espressopp::FixedTripleAngleList::con1 protected
Definition at line 49 of file FixedTripleAngleList.hpp.
Referenced by FixedTripleAngleList(), and ~FixedTripleAngleList().
con2
boost::signals2::connection espressopp::FixedTripleAngleList::con2 protected
Definition at line 49 of file FixedTripleAngleList.hpp.
Referenced by FixedTripleAngleList(), and ~FixedTripleAngleList().
con3
boost::signals2::connection espressopp::FixedTripleAngleList::con3 protected
Definition at line 49 of file FixedTripleAngleList.hpp.
Referenced by FixedTripleAngleList(), and ~FixedTripleAngleList().
storage
shared_ptr<storage::Storage> espressopp::FixedTripleAngleList::storage protected
Definition at line 51 of file FixedTripleAngleList.hpp.
Referenced by add(), FixedTripleAngleList(), and onParticlesChanged().
triplesAngles
TriplesAngles espressopp::FixedTripleAngleList::triplesAngles protected
Definition at line 52 of file FixedTripleAngleList.hpp.
Referenced by add(), afterRecvParticles(), beforeSendParticles(), getAngle(), getTriples(), getTriplesAngles(), and onParticlesChanged().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/FixedTripleAngleList.hpp
/home/espressopp/espressopp/src/FixedTripleAngleList.cpp