ESPResSo++: espressopp::integrator::LBInitConstForce Class Reference
espressopp::integrator::LBInitConstForce Class Reference
#include <LBInitConstForce.hpp>
Public Member Functions
LBInitConstForce (shared_ptr< System > _system, shared_ptr< LatticeBoltzmann > _latticeboltzmann)
void createDenVel (real _rho0, Real3D _u0)
Destructor for output.
void setForce (Real3D _force)
void addForce (Real3D _force)
void printForce (Real3D _force, int _id)
void applyExtForce ()
Static Public Member Functions
static void registerPython ()
Protected Attributes
shared_ptr< LatticeBoltzmann > latticeboltzmann
real rho0
Real3D u0
Detailed Description
Definition at line 30 of file LBInitConstForce.hpp.
Constructor & Destructor Documentation
espressopp::integrator::LBInitConstForce::LBInitConstForce (shared_ptr< System > _system, shared_ptr< LatticeBoltzmann > _latticeboltzmann)
Definition at line 30 of file LBInitConstForce.cpp.
Member Function Documentation
void espressopp::integrator::LBInitConstForce::addForce (Real3D _force) virtual
Implements espressopp::integrator::LBInit.
Definition at line 65 of file LBInitConstForce.cpp.
References espressopp::Int3D::getItem(), espressopp::integrator::LBInit::latticeboltzmann, and printForce().
Referenced by registerPython().
void espressopp::integrator::LBInitConstForce::applyExtForce ()
void espressopp::integrator::LBInitConstForce::createDenVel (real _rho0, Real3D _u0) virtual
Destructor for output.
Implements espressopp::integrator::LBInit.
Definition at line 36 of file LBInitConstForce.cpp.
void espressopp::integrator::LBInitConstForce::printForce (Real3D _force, int _id)
Definition at line 93 of file LBInitConstForce.cpp.
References espressopp::Real3D::getItem(), and mpiWorld.
Referenced by addForce(), and setForce().
void espressopp::integrator::LBInitConstForce::registerPython () static
Definition at line 124 of file LBInitConstForce.cpp.
References addForce(), and setForce().
Referenced by espressopp::integrator::registerPython().
void espressopp::integrator::LBInitConstForce::setForce (Real3D _force) virtual
Implements espressopp::integrator::LBInit.
Definition at line 39 of file LBInitConstForce.cpp.
References espressopp::Int3D::getItem(), espressopp::integrator::LBInit::latticeboltzmann, and printForce().
Referenced by registerPython().
Member Data Documentation
shared_ptr<LatticeBoltzmann> espressopp::integrator::LBInit::latticeboltzmann protected inherited
Definition at line 52 of file LBInit.hpp.
Referenced by espressopp::integrator::LBInitPeriodicForce::addForce(), addForce(), espressopp::integrator::LBInitPopUniform::createDenVel(), espressopp::integrator::LBInitPopWave::createDenVel(), espressopp::integrator::LBInit::LBInit(), espressopp::integrator::LBInitPeriodicForce::setForce(), and setForce().
real espressopp::integrator::LBInit::rho0 protected inherited
Definition at line 53 of file LBInit.hpp.
Real3D espressopp::integrator::LBInit::u0 protected inherited
Definition at line 54 of file LBInit.hpp.
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/integrator/LBInitConstForce.hpp
/home/espressopp/espressopp/src/integrator/LBInitConstForce.cpp