ESPResSo++: espressopp::interaction::TabulatedAngular Class Reference
espressopp::interaction::TabulatedAngular Class Reference
#include <TabulatedAngular.hpp>
Public Member Functions
TabulatedAngular ()
TabulatedAngular (int itype, const char *filename)
TabulatedAngular (int itype, const char *filename, real cutoff)
void setInterpolationType (int itype)
Setter for the interpolation type.
int getInterpolationType () const
Getter for the interpolation type.
void setFilename (int itype, const char *_filename)
const char * getFilename () const
real _computeEnergyRaw (real theta) const
bool _computeForceRaw (Real3D &force12, Real3D &force32, const Real3D &dist12, const Real3D &dist32) const
real _computeForceRaw (real theta) const
virtual real computeEnergy (const Particle &p1, const Particle &p2, const Particle &p3) const
virtual real computeEnergy (const Real3D &dist12, const Real3D &dist32) const
virtual real computeEnergy (const real theta) const
virtual void computeForce (Real3D &force12, Real3D &force32, const Particle &p1, const Particle &p2, const Particle &p3) const
virtual void computeForce (Real3D &force12, Real3D &force32, const Real3D &dist12, const Real3D &dist32) const
virtual real computeForce (real theta) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
real _computeEnergy (const Particle &p1, const Particle &p2, const Particle &p3) const
real _computeEnergy (const Real3D &dist12, const Real3D &dist32) const
real _computeEnergy (real theta) const
void _computeForce (Real3D &force12, Real3D &force32, const Particle &p1, const Particle &p2, const Particle &p3) const
bool _computeForce (Real3D &force12, Real3D &force32, const Real3D &dist12, const Real3D &dist32) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
TabulatedAngular * derived_this ()
const TabulatedAngular * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
Private Attributes
std::string filename
shared_ptr< Interpolation > table
int interpolationType
Detailed Description
Definition at line 35 of file TabulatedAngular.hpp.
Constructor & Destructor Documentation
TabulatedAngular() [1/3]
espressopp::interaction::TabulatedAngular::TabulatedAngular () inline
Definition at line 45 of file TabulatedAngular.hpp.
TabulatedAngular() [2/3]
espressopp::interaction::TabulatedAngular::TabulatedAngular (int itype, const char * filename) inline
Definition at line 50 of file TabulatedAngular.hpp.
References setFilename(), and setInterpolationType().
TabulatedAngular() [3/3]
espressopp::interaction::TabulatedAngular::TabulatedAngular (int itype, const char * filename, real cutoff) inline
Definition at line 55 of file TabulatedAngular.hpp.
References espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >::setCutoff(), setFilename(), and setInterpolationType().
Member Function Documentation
_computeEnergy() [1/3]
real espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >::_computeEnergy (const Particle & p1, const Particle & p2, const Particle & p3) const inline inherited
Definition at line 175 of file AngularPotential.hpp.
_computeEnergy() [2/3]
real espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >::_computeEnergy (const Real3D & dist12, const Real3D & dist32) const inline inherited
Definition at line 184 of file AngularPotential.hpp.
_computeEnergy() [3/3]
real espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >::_computeEnergy (real theta) const inline inherited
Definition at line 199 of file AngularPotential.hpp.
_computeEnergyRaw()
real espressopp::interaction::TabulatedAngular::_computeEnergyRaw (real theta) const inline
Definition at line 73 of file TabulatedAngular.hpp.
References LOG4ESPP_DEBUG.
_computeForce() [1/2]
void espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >::_computeForce (Real3D & force12, Real3D & force32, const Particle & p1, const Particle & p2, const Particle & p3) const inline inherited
Definition at line 228 of file AngularPotential.hpp.
_computeForce() [2/2]
bool espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >::_computeForce (Real3D & force12, Real3D & force32, const Real3D & dist12, const Real3D & dist32) const inline inherited
Definition at line 239 of file AngularPotential.hpp.
_computeForceRaw() [1/2]
bool espressopp::interaction::TabulatedAngular::_computeForceRaw (Real3D & force12, Real3D & force32, const Real3D & dist12, const Real3D & dist32) const inline
Definition at line 82 of file TabulatedAngular.hpp.
References LOG4ESPP_DEBUG.
_computeForceRaw() [2/2]
real espressopp::interaction::TabulatedAngular::_computeForceRaw (real theta) const inline
Definition at line 108 of file TabulatedAngular.hpp.
computeEnergy() [1/3]
real espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >::computeEnergy (const Particle & p1, const Particle & p2, const Particle & p3) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 149 of file AngularPotential.hpp.
computeEnergy() [2/3]
real espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >::computeEnergy (const Real3D & dist12, const Real3D & dist32) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 158 of file AngularPotential.hpp.
computeEnergy() [3/3]
real espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >::computeEnergy (const real theta) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 168 of file AngularPotential.hpp.
computeForce() [1/3]
void espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >::computeForce (Real3D & force12, Real3D & force32, const Particle & p1, const Particle & p2, const Particle & p3) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 207 of file AngularPotential.hpp.
computeForce() [2/3]
void espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >::computeForce (Real3D & force12, Real3D & force32, const Real3D & dist12, const Real3D & dist32) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 218 of file AngularPotential.hpp.
computeForce() [3/3]
real espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >::computeForce (real theta) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 251 of file AngularPotential.hpp.
derived_this() [1/2]
TabulatedAngular * espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >::derived_this () inline protected inherited
Definition at line 111 of file AngularPotential.hpp.
derived_this() [2/2]
const TabulatedAngular * espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >::derived_this () const inline protected inherited
Definition at line 115 of file AngularPotential.hpp.
getCutoff()
real espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 142 of file AngularPotential.hpp.
getFilename()
const char* espressopp::interaction::TabulatedAngular::getFilename () const inline
Definition at line 69 of file TabulatedAngular.hpp.
Referenced by espressopp::interaction::TabulatedAngular_pickle::getinitargs(), and registerPython().
getInterpolationType()
int espressopp::interaction::TabulatedAngular::getInterpolationType () const inline
Getter for the interpolation type.
Definition at line 65 of file TabulatedAngular.hpp.
References interpolationType, and setFilename().
Referenced by espressopp::interaction::TabulatedAngular_pickle::getinitargs().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::AngularPotential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
registerPython()
void espressopp::interaction::TabulatedAngular::registerPython () static
Definition at line 64 of file TabulatedAngular.cpp.
References getFilename(), and setFilename().
Referenced by espressopp::interaction::registerPython().
setCutoff()
void espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 134 of file AngularPotential.hpp.
Referenced by TabulatedAngular().
setFilename()
void espressopp::interaction::TabulatedAngular::setFilename (int itype, const char * _filename)
Definition at line 36 of file TabulatedAngular.cpp.
References filename, and table.
Referenced by getInterpolationType(), registerPython(), and TabulatedAngular().
setInterpolationType()
void espressopp::interaction::TabulatedAngular::setInterpolationType (int itype) inline
Setter for the interpolation type.
Definition at line 62 of file TabulatedAngular.hpp.
Referenced by TabulatedAngular().
Member Data Documentation
cutoff
real espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >::cutoff protected inherited
Definition at line 108 of file AngularPotential.hpp.
cutoffSqr
real espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >::cutoffSqr protected inherited
Definition at line 109 of file AngularPotential.hpp.
filename
std::string espressopp::interaction::TabulatedAngular::filename private
Definition at line 38 of file TabulatedAngular.hpp.
Referenced by setFilename().
interpolationType
int espressopp::interaction::TabulatedAngular::interpolationType private
Definition at line 40 of file TabulatedAngular.hpp.
Referenced by getInterpolationType().
table
shared_ptr<Interpolation> espressopp::interaction::TabulatedAngular::table private
Definition at line 39 of file TabulatedAngular.hpp.
Referenced by setFilename().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/TabulatedAngular.hpp
/home/espressopp/espressopp/src/interaction/TabulatedAngular.cpp