ESPResSo++: espressopp::esutil::Array3D< T, enlarge > Class Template Reference
espressopp::esutil::Array3D< T, enlarge > Class Template Reference
#include <Array3D.hpp>
Public Types
typedef T value_type
The type of object, T, stored in the Array1D.
typedef T & reference
Reference to to a T object.
typedef Super::size_type size_type
An unsigned integer type.
typedef Super::iterator iterator
Iterator used to iterate through an Array1D.
typedef Super::const_iterator const_iterator
Const-iterator used to iterate through an Array1D.
Public Member Functions
Array3D (const T &prototype=T())
Default constructor.
Array3D (size_type n, size_type m, size_type l, const T &prototype=T())
Creates a one-dimensional array of size n with n copies of prototype.
void init (size_type n, size_type m, size_type l, const T &prototype=T())
Creates a one-dimensional array of size n with n copies of prototype.
void set_prototype (const T &prototype=T())
Sets the prototype used when the Array3D<T,enlarge> is automatically resized.
reference at (size_type i, size_type j, size_type k)
Returns the element at position i x j x k.
template<class Vector >
reference at (const Vector &pos)
Returns the element at position pos.
void clear ()
Erases all elements.
void resize (size_type n, size_type m, size_type l, const T &t=T())
Changes the size of the Array3D so that the size becomes n x m x l.
size_type size_n () const
Returns the n -size of the array.
size_type size_x () const
Returns the n -size of the array.
size_type size_m () const
Returns the m -size of the array.
size_type size_y () const
Returns the m -size of the array.
size_type size_l () const
Returns the m -size of the array.
size_type size_z () const
Returns the m -size of the array.
bool empty () const
true if the Array3D's size is 0 x 0 x 0.
reference operator() (size_type i, size_type j, size_type k)
Returns the element at position i x j x k.
const_reference operator() (size_type i, size_type j, size_type k) const
Returns the element at position i x j x k.
reference operator() (const Vector &pos)
Returns the element at position pos.
const_reference operator() (const Vector &pos) const
Returns the element at position pos.
const_reference at (size_type i, size_type j, size_type k) const
Returns the element at position i x j x k.
const_reference at (const Vector &pos) const
Returns the element at position pos.
iterator begin ()
Returns an iterator pointing to the beginning of the Array3D.
const_iterator begin () const
Returns a const_iterator pointing to the beginning of the Array3D.
iterator end ()
Returns an iterator pointing to the end of the Array3D.
const_iterator end () const
Returns a const_iterator pointing to the end of the Array3D.
void operator+= (const T2 &t2)
Adds t2 to each of the elements.
void operator-= (const T2 &t2)
Adds t2 to each of the elements.
void operator*= (const T2 &t2)
Multiplies each of the elements by t2.
void operator/= (const T2 &t2)
Divides each of the elements by t2.
void operator/= (const double &x)
bool operator== (const Array3D< T, exception > &a)
Equality operator.
bool operator!= (const Array3D< T, exception > &a)
Inequality operator.
Public Attributes
const typedef T & const_reference
Const reference to to a T object.
Private Types
typedef Array3D< T, exception > Super
The super class of the array (i.e.
typedef Array3D< T > Self
Private Attributes
value_type prototype
size_type n
The n size of the n x m x l array.
size_type m
The m size of the n x m x l array.
size_type l
The l size of the n x m x l array.
Detailed Description
template<class T>
class espressopp::esutil::Array3D< T, enlarge >
Definition at line 258 of file Array3D.hpp.
Member Typedef Documentation
const_iterator
template<class T > typedef Super::const_iterator espressopp::esutil::Array3D< T, enlarge >::const_iterator
Const-iterator used to iterate through an Array1D.
Definition at line 274 of file Array3D.hpp.
iterator
template<class T > typedef Super::iterator espressopp::esutil::Array3D< T, enlarge >::iterator
Iterator used to iterate through an Array1D.
Definition at line 272 of file Array3D.hpp.
reference
template<class T > typedef T& espressopp::esutil::Array3D< T, enlarge >::reference
Reference to to a T object.
Definition at line 266 of file Array3D.hpp.
Self
typedef Array3D< T > espressopp::esutil::Array3D< T, outlier_mode >::Self private inherited
Definition at line 45 of file Array3D.hpp.
size_type
template<class T > typedef Super::size_type espressopp::esutil::Array3D< T, enlarge >::size_type
An unsigned integer type.
Definition at line 270 of file Array3D.hpp.
Super
template<class T > typedef Array3D< T, exception > espressopp::esutil::Array3D< T, enlarge >::Super private
The super class of the array (i.e.
vector<T>).
Definition at line 260 of file Array3D.hpp.
value_type
template<class T > typedef T espressopp::esutil::Array3D< T, enlarge >::value_type
The type of object, T, stored in the Array1D.
Definition at line 264 of file Array3D.hpp.
Constructor & Destructor Documentation
Array3D() [1/2]
template<class T > espressopp::esutil::Array3D< T, enlarge >::Array3D (const T & prototype = T()) inline
Default constructor.
Definition at line 281 of file Array3D.hpp.
References espressopp::esutil::Array3D< T, outlier_mode >::init().
Array3D() [2/2]
template<class T > espressopp::esutil::Array3D< T, enlarge >::Array3D (size_type n, size_type m, size_type l, const T & prototype = T()) inline
Creates a one-dimensional array of size n with n copies of prototype.
Also sets the prototype.
Definition at line 286 of file Array3D.hpp.
References espressopp::esutil::Array3D< T, outlier_mode >::init(), espressopp::esutil::Array3D< T, outlier_mode >::l, espressopp::esutil::Array3D< T, outlier_mode >::m, and espressopp::esutil::Array3D< T, outlier_mode >::n.
Member Function Documentation
at() [1/4]
template<class T > template<class Vector > reference espressopp::esutil::Array3D< T, enlarge >::at (const Vector & pos) inline
Returns the element at position pos.
pos must be a vector where the expressions pos[0], pos[1] and pos[2] return the first and second element.
When the element doesn't exist, the Array3D is automatically
extended so that the element exists. The new elements are
initialised with copies of the prototype.
Definition at line 355 of file Array3D.hpp.
References espressopp::esutil::Array3D< T, outlier_mode >::at().
at() [2/4]
const_reference espressopp::esutil::Array3D< T, outlier_mode >::at (const Vector & pos) const inline inherited
Returns the element at position pos.
pos must be a vector where the expressions pos[0], pos[1] and pos[2] return the first and second element.
\exception out_of_range \p i is out of range of the Array3D
Definition at line 184 of file Array3D.hpp.
at() [3/4]
template<class T > reference espressopp::esutil::Array3D< T, enlarge >::at (size_type i, size_type j, size_type k) inline
Returns the element at position i x j x k.
When the element doesn't exist, the Array3D is automatically extended so that the element exists. The new elements are initialised with copies of the prototype.
Definition at line 308 of file Array3D.hpp.
References espressopp::esutil::Array3D< T, outlier_mode >::size_l(), espressopp::esutil::Array3D< T, outlier_mode >::size_m(), and espressopp::esutil::Array3D< T, outlier_mode >::size_n().
at() [4/4]
const_reference espressopp::esutil::Array3D< T, outlier_mode >::at (size_type i, size_type j, size_type k) const inline inherited
Returns the element at position i x j x k.
Exceptions
out_of_range i is out of range of the Array3D
Definition at line 160 of file Array3D.hpp.
begin() [1/2]
iterator espressopp::esutil::Array3D< T, outlier_mode >::begin inline inherited
Returns an iterator pointing to the beginning of the Array3D.
Definition at line 189 of file Array3D.hpp.
begin() [2/2]
const_iterator espressopp::esutil::Array3D< T, outlier_mode >::begin inline inherited
Returns a const_iterator pointing to the beginning of the Array3D.
Definition at line 193 of file Array3D.hpp.
clear()
void espressopp::esutil::Array3D< T, outlier_mode >::clear inline inherited
Erases all elements.
Definition at line 72 of file Array3D.hpp.
empty()
bool espressopp::esutil::Array3D< T, outlier_mode >::empty inline inherited
true if the Array3D's size is 0 x 0 x 0.
Definition at line 119 of file Array3D.hpp.
end() [1/2]
iterator espressopp::esutil::Array3D< T, outlier_mode >::end inline inherited
Returns an iterator pointing to the end of the Array3D.
Definition at line 197 of file Array3D.hpp.
end() [2/2]
const_iterator espressopp::esutil::Array3D< T, outlier_mode >::end inline inherited
Returns a const_iterator pointing to the end of the Array3D.
Definition at line 201 of file Array3D.hpp.
init()
template<class T > void espressopp::esutil::Array3D< T, enlarge >::init (size_type n, size_type m, size_type l, const T & prototype = T()) inline
Creates a one-dimensional array of size n with n copies of prototype.
Also sets the prototype.
Definition at line 292 of file Array3D.hpp.
References espressopp::esutil::Array3D< T, outlier_mode >::l, espressopp::esutil::Array3D< T, outlier_mode >::m, and espressopp::esutil::Array3D< T, outlier_mode >::n.
operator!=()
bool espressopp::esutil::Array3D< T, outlier_mode >::operator!= (const Array3D< T, exception > & a) inline inherited
Inequality operator.
Definition at line 243 of file Array3D.hpp.
operator()() [1/4]
reference espressopp::esutil::Array3D< T, outlier_mode >::operator() (const Vector & pos) inline inherited
Returns the element at position pos.
pos must be a vector where the expressions pos[0], pos[1] and pos[2] return the indices.
Attention
No range checking.
Definition at line 137 of file Array3D.hpp.
operator()() [2/4]
const_reference espressopp::esutil::Array3D< T, outlier_mode >::operator() (const Vector & pos) const inline inherited
Returns the element at position pos.
pos must be a vector where the expressions pos[0], pos[1] and pos[2] return the indices.
Attention
No range checking.
Definition at line 146 of file Array3D.hpp.
operator()() [3/4]
reference espressopp::esutil::Array3D< T, outlier_mode >::operator() (size_type i, size_type j, size_type k) inline inherited
Returns the element at position i x j x k.
Attention
No range checking.
Definition at line 123 of file Array3D.hpp.
operator()() [4/4]
const_reference espressopp::esutil::Array3D< T, outlier_mode >::operator() (size_type i, size_type j, size_type k) const inline inherited
Returns the element at position i x j x k.
Attention
No range checking.
Definition at line 128 of file Array3D.hpp.
operator*=()
void espressopp::esutil::Array3D< T, outlier_mode >::operator*= (const T2 & t2) inline inherited
Multiplies each of the elements by t2.
Definition at line 223 of file Array3D.hpp.
operator+=()
void espressopp::esutil::Array3D< T, outlier_mode >::operator+= (const T2 & t2) inline inherited
Adds t2 to each of the elements.
Definition at line 211 of file Array3D.hpp.
operator-=()
void espressopp::esutil::Array3D< T, outlier_mode >::operator-= (const T2 & t2) inline inherited
Adds t2 to each of the elements.
Definition at line 217 of file Array3D.hpp.
operator/=() [1/2]
void espressopp::esutil::Array3D< T, outlier_mode >::operator/= (const double & x) inline inherited
Definition at line 231 of file Array3D.hpp.
operator/=() [2/2]
void espressopp::esutil::Array3D< T, outlier_mode >::operator/= (const T2 & t2) inline inherited
Divides each of the elements by t2.
Definition at line 228 of file Array3D.hpp.
operator==()
bool espressopp::esutil::Array3D< T, outlier_mode >::operator== (const Array3D< T, exception > & a) inline inherited
Equality operator.
Definition at line 237 of file Array3D.hpp.
resize()
void espressopp::esutil::Array3D< T, outlier_mode >::resize (size_type n, size_type m, size_type l, const T & t = T()) inline inherited
Changes the size of the Array3D so that the size becomes n x m x l.
Attention
The elements of the Array3D are not initialised consistently, so the values are undefined. The t parameter exists only for the purpose to provide a default T value when new elements are created and needs to be specified only when T has no default constructor.
Definition at line 96 of file Array3D.hpp.
set_prototype()
template<class T > void espressopp::esutil::Array3D< T, enlarge >::set_prototype (const T & prototype = T()) inline
Sets the prototype used when the Array3D<T,enlarge> is automatically resized.
Definition at line 297 of file Array3D.hpp.
size_l()
size_type espressopp::esutil::Array3D< T, outlier_mode >::size_l inline inherited
Returns the m -size of the array.
Definition at line 114 of file Array3D.hpp.
size_m()
size_type espressopp::esutil::Array3D< T, outlier_mode >::size_m inline inherited
Returns the m -size of the array.
Definition at line 109 of file Array3D.hpp.
size_n()
size_type espressopp::esutil::Array3D< T, outlier_mode >::size_n inline inherited
Returns the n -size of the array.
Definition at line 104 of file Array3D.hpp.
size_x()
size_type espressopp::esutil::Array3D< T, outlier_mode >::size_x inline inherited
Returns the n -size of the array.
Definition at line 106 of file Array3D.hpp.
size_y()
size_type espressopp::esutil::Array3D< T, outlier_mode >::size_y inline inherited
Returns the m -size of the array.
Definition at line 111 of file Array3D.hpp.
size_z()
size_type espressopp::esutil::Array3D< T, outlier_mode >::size_z inline inherited
Returns the m -size of the array.
Definition at line 116 of file Array3D.hpp.
Member Data Documentation
const_reference
template<class T > const typedef T& espressopp::esutil::Array3D< T, enlarge >::const_reference
Const reference to to a T object.
Definition at line 268 of file Array3D.hpp.
l
size_type espressopp::esutil::Array3D< T, outlier_mode >::l private inherited
The l size of the n x m x l array.
Definition at line 254 of file Array3D.hpp.
m
size_type espressopp::esutil::Array3D< T, outlier_mode >::m private inherited
The m size of the n x m x l array.
Definition at line 252 of file Array3D.hpp.
n
size_type espressopp::esutil::Array3D< T, outlier_mode >::n private inherited
The n size of the n x m x l array.
Definition at line 250 of file Array3D.hpp.
prototype
template<class T > value_type espressopp::esutil::Array3D< T, enlarge >::prototype private
Definition at line 359 of file Array3D.hpp.
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/esutil/Array3D.hpp