ESPResSo++: espressopp::analysis::LBOutput Class Reference
espressopp::analysis::LBOutput Class Reference abstract
Abstract base class for arbitrary output from LB simulations.
#include <LBOutput.hpp>
Public Member Functions
LBOutput (shared_ptr< System > _system, shared_ptr< integrator::LatticeBoltzmann > _latticeboltzmann)
virtual ~LBOutput ()
real computeRaw ()
python::list compute ()
python::list getAverageValue ()
void resetAverage ()
void updateAverage (real res)
virtual void writeOutput ()=0
virtual void performMeasurement ()
This method will measure the observable and can be called from within the integrator by using the ExtAnalyse extension.
virtual void reset ()
This method resets/initializes the measurement.
virtual int getNumberOfMeasurements ()
return the number of measurements since the last reset
void perform_action ()
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (logger)
Protected Attributes
shared_ptr< integrator::LatticeBoltzmann > latticeboltzmann
real newAverage
real lastAverage
real newVariance
real lastVariance
int nMeasurements
Private Attributes
weak_ptr< System > mySystem
Weak pointer to the system guarantees that system will be freed.
weak_ptr< System > mySystem1
weak_ptr< System > mySystem2
Detailed Description
Abstract base class for arbitrary output from LB simulations.
Definition at line 33 of file LBOutput.hpp.
Constructor & Destructor Documentation
LBOutput()
espressopp::analysis::LBOutput::LBOutput (shared_ptr< System > _system, shared_ptr< integrator::LatticeBoltzmann > _latticeboltzmann) inline
Definition at line 36 of file LBOutput.hpp.
~LBOutput()
virtual espressopp::analysis::LBOutput::~LBOutput () inline virtual
Definition at line 42 of file LBOutput.hpp.
Member Function Documentation
compute()
python::list espressopp::analysis::LBOutput::compute () inline virtual
Implements espressopp::analysis::AnalysisBaseTemplate< real >.
Definition at line 50 of file LBOutput.hpp.
computeRaw()
real espressopp::analysis::LBOutput::computeRaw () inline virtual
Implements espressopp::analysis::AnalysisBaseTemplate< real >.
Definition at line 44 of file LBOutput.hpp.
getAverageValue()
python::list espressopp::analysis::LBOutput::getAverageValue () inline virtual
Implements espressopp::analysis::AnalysisBaseTemplate< real >.
Definition at line 57 of file LBOutput.hpp.
getNumberOfMeasurements()
int espressopp::analysis::AnalysisBaseTemplate< real >::getNumberOfMeasurements inline virtual inherited
return the number of measurements since the last reset
Implements espressopp::analysis::AnalysisBase.
Definition at line 106 of file AnalysisBase.hpp.
getSystem()
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::VerletList::_rebuildUsingBuffers(), espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::LatticeBoltzmann::assignMyLattice(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::vectorization::Vectorization::befCalcForces(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::vectorization::Vectorization::connect(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::vectorization::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpXTCAdress::dump(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::io::DumpXYZ::DumpXYZ(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::vectorization::VerletList::rebuild(), espressopp::vectorization::VerletList::rebuild_p_nc_pack_stencil(), espressopp::vectorization::VerletList::rebuildPairs(), espressopp::VerletListTriple::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::VerletList::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::vectorization::VerletList::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::vectorization::Vectorization::resetCells(), espressopp::vectorization::Vectorization::resetParticles(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::vectorization::Vectorization::updateForces(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
getSystem1()
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
getSystem2()
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
getSystemRef()
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerletRESPA::calcForces(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeCOM(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::FixedLocalTupleComListInteractionTemplate(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::VelocityVerletRESPA::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::VelocityVerletRESPA::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::VelocityVerletRESPA::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::Adress::integrateSlow(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::vectorization::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::VelocityVerletRESPA::run(), espressopp::integrator::PIAdressIntegrator::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::MinimizeEnergy::run(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::Rattle::saveOldPos(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostatOnGroup::thermalize(), espressopp::integrator::LangevinThermostatOnRadius::thermalize(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::vectorization::VerletList::totalSize(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::io::DumpH5MD::update(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::VelocityVerletRESPA::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
getSystemRef1()
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
getSystemRef2()
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
LOG4ESPP_DECL_LOGGER()
static espressopp::analysis::AnalysisBase::LOG4ESPP_DECL_LOGGER (logger) static inherited
perform_action()
void espressopp::analysis::AnalysisBase::perform_action () inline virtual inherited
Implements espressopp::ParticleAccess.
Reimplemented in espressopp::analysis::CMVelocity.
Definition at line 54 of file AnalysisBase.hpp.
References espressopp::analysis::AnalysisBase::performMeasurement().
performMeasurement()
void espressopp::analysis::AnalysisBaseTemplate< real >::performMeasurement inline virtual inherited
This method will measure the observable and can be called from within the integrator by using the ExtAnalyse extension.
It can also be called from python. It will also update the average value (typically also the variance) of the observable
Implements espressopp::analysis::AnalysisBase.
Definition at line 89 of file AnalysisBase.hpp.
registerPython()
void espressopp::analysis::LBOutput::registerPython () static
Definition at line 27 of file LBOutput.cpp.
References writeOutput().
Referenced by espressopp::analysis::registerPython().
reset()
void espressopp::analysis::AnalysisBaseTemplate< real >::reset inline virtual inherited
This method resets/initializes the measurement.
Implements espressopp::analysis::AnalysisBase.
Definition at line 98 of file AnalysisBase.hpp.
resetAverage()
void espressopp::analysis::LBOutput::resetAverage () inline virtual
Implements espressopp::analysis::AnalysisBaseTemplate< real >.
Definition at line 63 of file LBOutput.hpp.
updateAverage()
void espressopp::analysis::LBOutput::updateAverage (real res) inline virtual
Implements espressopp::analysis::AnalysisBaseTemplate< real >.
Definition at line 64 of file LBOutput.hpp.
writeOutput()
virtual void espressopp::analysis::LBOutput::writeOutput () pure virtual
Implemented in espressopp::analysis::LBOutputScreen, espressopp::analysis::LBOutputVzInTime, and espressopp::analysis::LBOutputVzOfX.
Referenced by registerPython().
Member Data Documentation
lastAverage
real espressopp::analysis::AnalysisBaseTemplate< real >::lastAverage protected inherited
Definition at line 79 of file AnalysisBase.hpp.
lastVariance
real espressopp::analysis::AnalysisBaseTemplate< real >::lastVariance protected inherited
Definition at line 80 of file AnalysisBase.hpp.
latticeboltzmann
shared_ptr<integrator::LatticeBoltzmann> espressopp::analysis::LBOutput::latticeboltzmann protected
Definition at line 71 of file LBOutput.hpp.
Referenced by espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::analysis::LBOutputVzOfX::writeOutput(), espressopp::analysis::LBOutputVzInTime::writeOutput(), and espressopp::analysis::LBOutputScreen::writeOutput().
mySystem
weak_ptr< System > espressopp::SystemAccess::mySystem private inherited
Weak pointer to the system guarantees that system will be freed.
Definition at line 54 of file SystemAccess.hpp.
Referenced by espressopp::SystemAccess::getSystem(), and espressopp::SystemAccess::SystemAccess().
mySystem1
weak_ptr< System > espressopp::SystemAccess::mySystem1 private inherited
Definition at line 55 of file SystemAccess.hpp.
Referenced by espressopp::SystemAccess::getSystem1(), and espressopp::SystemAccess::SystemAccess().
mySystem2
weak_ptr< System > espressopp::SystemAccess::mySystem2 private inherited
Definition at line 56 of file SystemAccess.hpp.
Referenced by espressopp::SystemAccess::getSystem2(), and espressopp::SystemAccess::SystemAccess().
newAverage
real espressopp::analysis::AnalysisBaseTemplate< real >::newAverage protected inherited
Definition at line 79 of file AnalysisBase.hpp.
newVariance
real espressopp::analysis::AnalysisBaseTemplate< real >::newVariance protected inherited
Definition at line 80 of file AnalysisBase.hpp.
nMeasurements
int espressopp::analysis::AnalysisBaseTemplate< real >::nMeasurements protected inherited
Definition at line 81 of file AnalysisBase.hpp.
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/analysis/LBOutput.hpp
/home/espressopp/espressopp/src/analysis/LBOutput.cpp