ESPResSo++: espressopp::interaction::Harmonic Class Reference
espressopp::interaction::Harmonic Class Reference
#include <Harmonic.hpp>
Public Member Functions
Harmonic ()
Harmonic (real _K, real _r0, real _cutoff, real _shift)
Harmonic (real _K, real _r0, real _cutoff)
void setK (real _K)
real getK () const
void setR0 (real _r0)
real getR0 () const
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &dist, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
real _computeEnergyDeriv (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
Harmonic * derived_this ()
const Harmonic * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
Private Attributes
real K
real r0
Detailed Description
Definition at line 37 of file Harmonic.hpp.
Constructor & Destructor Documentation
Harmonic() [1/3]
espressopp::interaction::Harmonic::Harmonic () inline
Definition at line 45 of file Harmonic.hpp.
References espressopp::infinity, espressopp::interaction::PotentialTemplate< Harmonic >::setCutoff(), and espressopp::interaction::PotentialTemplate< Harmonic >::setShift().
Harmonic() [2/3]
espressopp::interaction::Harmonic::Harmonic (real _K, real _r0, real _cutoff, real _shift) inline
Definition at line 50 of file Harmonic.hpp.
References espressopp::interaction::PotentialTemplate< Harmonic >::setCutoff(), and espressopp::interaction::PotentialTemplate< Harmonic >::setShift().
Harmonic() [3/3]
espressopp::interaction::Harmonic::Harmonic (real _K, real _r0, real _cutoff) inline
Definition at line 55 of file Harmonic.hpp.
References espressopp::interaction::PotentialTemplate< Harmonic >::autoShift, espressopp::interaction::PotentialTemplate< Harmonic >::setAutoShift(), and espressopp::interaction::PotentialTemplate< Harmonic >::setCutoff().
Member Function Documentation
_computeEnergy() [1/4]
real espressopp::interaction::PotentialTemplate< Harmonic >::_computeEnergy (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 242 of file Potential.hpp.
_computeEnergy() [2/4]
real espressopp::interaction::PotentialTemplate< Harmonic >::_computeEnergy (const Real3D & dist) const inline inherited
Definition at line 257 of file Potential.hpp.
_computeEnergy() [3/4]
real espressopp::interaction::PotentialTemplate< Harmonic >::_computeEnergy (real dist) const inline inherited
Definition at line 264 of file Potential.hpp.
_computeEnergy() [4/4]
real espressopp::interaction::PotentialTemplate< Harmonic >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 250 of file Potential.hpp.
_computeEnergyDeriv()
real espressopp::interaction::PotentialTemplate< Harmonic >::_computeEnergyDeriv (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 285 of file Potential.hpp.
_computeEnergySqr()
real espressopp::interaction::PotentialTemplate< Harmonic >::_computeEnergySqr (real distSqr) const inline inherited
Definition at line 271 of file Potential.hpp.
_computeEnergySqrRaw()
real espressopp::interaction::Harmonic::_computeEnergySqrRaw (real distSqr) const inline
Definition at line 76 of file Harmonic.hpp.
_computeForce() [1/3]
bool espressopp::interaction::PotentialTemplate< Harmonic >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const inline inherited
Definition at line 313 of file Potential.hpp.
_computeForce() [2/3]
bool espressopp::interaction::PotentialTemplate< Harmonic >::_computeForce (Real3D & force, const Real3D & dist) const inline inherited
Definition at line 328 of file Potential.hpp.
_computeForce() [3/3]
bool espressopp::interaction::PotentialTemplate< Harmonic >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 321 of file Potential.hpp.
_computeForceRaw()
bool espressopp::interaction::Harmonic::_computeForceRaw (Real3D & force, const Real3D & dist, real distSqr) const inline
Definition at line 81 of file Harmonic.hpp.
References r0.
computeEnergy() [1/3]
real espressopp::interaction::PotentialTemplate< Harmonic >::computeEnergy (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 213 of file Potential.hpp.
computeEnergy() [2/3]
real espressopp::interaction::PotentialTemplate< Harmonic >::computeEnergy (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 221 of file Potential.hpp.
computeEnergy() [3/3]
real espressopp::interaction::PotentialTemplate< Harmonic >::computeEnergy (real dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 228 of file Potential.hpp.
computeEnergySqr()
real espressopp::interaction::PotentialTemplate< Harmonic >::computeEnergySqr (real distsqr) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 235 of file Potential.hpp.
computeForce() [1/2]
Real3D espressopp::interaction::PotentialTemplate< Harmonic >::computeForce (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 295 of file Potential.hpp.
computeForce() [2/2]
Real3D espressopp::interaction::PotentialTemplate< Harmonic >::computeForce (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 303 of file Potential.hpp.
derived_this() [1/2]
Harmonic * espressopp::interaction::PotentialTemplate< Harmonic >::derived_this () inline protected inherited
Definition at line 123 of file Potential.hpp.
derived_this() [2/2]
const Harmonic * espressopp::interaction::PotentialTemplate< Harmonic >::derived_this () const inline protected inherited
Definition at line 127 of file Potential.hpp.
getCutoff()
real espressopp::interaction::PotentialTemplate< Harmonic >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 171 of file Potential.hpp.
getK()
real espressopp::interaction::Harmonic::getK () const inline
Definition at line 67 of file Harmonic.hpp.
References K.
Referenced by registerPython().
getR0()
real espressopp::interaction::Harmonic::getR0 () const inline
Definition at line 74 of file Harmonic.hpp.
References r0.
Referenced by registerPython().
getShift()
real espressopp::interaction::PotentialTemplate< Harmonic >::getShift () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 186 of file Potential.hpp.
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
Referenced by espressopp::interaction::Potential::~Potential().
registerPython()
void espressopp::interaction::Harmonic::registerPython () static
Definition at line 34 of file Harmonic.cpp.
References getK(), getR0(), setK(), and setR0().
Referenced by espressopp::interaction::registerPython().
setAutoShift()
real espressopp::interaction::PotentialTemplate< Harmonic >::setAutoShift () inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 192 of file Potential.hpp.
Referenced by Harmonic().
setCutoff()
void espressopp::interaction::PotentialTemplate< Harmonic >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 162 of file Potential.hpp.
Referenced by Harmonic().
setK()
void espressopp::interaction::Harmonic::setK (real _K) inline
Definition at line 62 of file Harmonic.hpp.
References espressopp::interaction::PotentialTemplate< Harmonic >::updateAutoShift().
Referenced by registerPython().
setR0()
void espressopp::interaction::Harmonic::setR0 (real _r0) inline
Definition at line 69 of file Harmonic.hpp.
References espressopp::interaction::PotentialTemplate< Harmonic >::updateAutoShift().
Referenced by registerPython().
setShift()
void espressopp::interaction::PotentialTemplate< Harmonic >::setShift (real _shift) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 177 of file Potential.hpp.
Referenced by Harmonic().
updateAutoShift()
void espressopp::interaction::PotentialTemplate< Harmonic >::updateAutoShift () inline inherited
Definition at line 205 of file Potential.hpp.
Referenced by setK(), and setR0().
Member Data Documentation
autoShift
bool espressopp::interaction::PotentialTemplate< Harmonic >::autoShift protected inherited
Definition at line 121 of file Potential.hpp.
Referenced by Harmonic().
cutoff
real espressopp::interaction::PotentialTemplate< Harmonic >::cutoff protected inherited
Definition at line 118 of file Potential.hpp.
cutoffSqr
real espressopp::interaction::PotentialTemplate< Harmonic >::cutoffSqr protected inherited
Definition at line 119 of file Potential.hpp.
K
real espressopp::interaction::Harmonic::K private
Definition at line 39 of file Harmonic.hpp.
Referenced by getK().
r0
real espressopp::interaction::Harmonic::r0 private
Definition at line 40 of file Harmonic.hpp.
Referenced by _computeForceRaw(), and getR0().
shift
real espressopp::interaction::PotentialTemplate< Harmonic >::shift protected inherited
Definition at line 120 of file Potential.hpp.
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/Harmonic.hpp
/home/espressopp/espressopp/src/interaction/Harmonic.cpp