ESPResSo++: espressopp::integrator::Adress Class Reference
espressopp::integrator::Adress Class Reference
#include <Adress.hpp>
Public Types
enum ExtensionType {
all =0, Thermostat =1, Barostat =2, Constraint =3,
Adress =4, FreeEnergyCompensation =5, ExtForce =6, ExtAnalysis =7,
Reaction =8
}
Public Member Functions
Adress (shared_ptr< System > _system, shared_ptr< VerletListAdress > _verletList, shared_ptr< FixedTupleListAdress > _fixedtupleList, bool _KTI=false, int _regionupdates=1, int _multistep=1)
~Adress ()
ExtensionType getType ()
void setType (ExtensionType k)
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
Register this class so it can be used from Python.
Public Attributes
shared_ptr< VerletListAdress > verletList
shared_ptr< FixedTupleListAdress > fixedtupleList
bool KTI
int regionupdates
int multistep
real dhy
real pidhy2
real dex
real dex2
real dexdhy
real dexdhy2
ExtensionType type
Protected Member Functions
void setIntegrator (shared_ptr< MDIntegrator > _integrator)
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Protected Attributes
shared_ptr< MDIntegrator > integrator
Private Member Functions
void integrate1 (real &)
void initForces ()
void SetPosVel ()
void integrate2 ()
void integrateSlow ()
void aftCalcF ()
void communicateAdrPositions ()
void connect ()
void disconnect ()
real weight (real)
real weightderivative (real)
Private Attributes
boost::signals2::connection _SetPosVel
boost::signals2::connection _initForces
boost::signals2::connection _integrate1
boost::signals2::connection _integrate2
boost::signals2::connection _integrateSlow
boost::signals2::connection _aftCalcSlow
boost::signals2::connection _recalc2
boost::signals2::connection _befIntV
int updatecount
Detailed Description
Definition at line 44 of file Adress.hpp.
Member Enumeration Documentation
ExtensionType
enum espressopp::integrator::Extension::ExtensionType inherited
Enumerator
all
Thermostat
Barostat
Constraint
Adress
FreeEnergyCompensation
ExtForce
ExtAnalysis
Reaction
Definition at line 48 of file Extension.hpp.
Constructor & Destructor Documentation
Adress()
espressopp::integrator::Adress::Adress (shared_ptr< System > _system, shared_ptr< VerletListAdress > _verletList, shared_ptr< FixedTupleListAdress > _fixedtupleList, bool _KTI = false, int _regionupdates = 1, int _multistep = 1)
Definition at line 44 of file Adress.cpp.
References espressopp::integrator::Extension::Adress, communicateAdrPositions(), dex, dex2, dexdhy, dexdhy2, dhy, LOG4ESPP_INFO, M_PI, pidhy2, espressopp::integrator::Extension::type, updatecount, and verletList.
~Adress()
espressopp::integrator::Adress::~Adress ()
Definition at line 62 of file Adress.cpp.
References disconnect(), and LOG4ESPP_INFO.
Member Function Documentation
aftCalcF()
void espressopp::integrator::Adress::aftCalcF () private
Definition at line 598 of file Adress.cpp.
References fixedtupleList, espressopp::Particle::force(), espressopp::Particle::getMass(), espressopp::SystemAccess::getSystemRef(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::iterator::CellListIterator::isDone(), espressopp::Particle::mass(), espressopp::Particle::position(), and espressopp::System::storage.
Referenced by connect().
communicateAdrPositions()
void espressopp::integrator::Adress::communicateAdrPositions () private
Definition at line 484 of file Adress.cpp.
References espressopp::System::comm, espressopp::SystemAccess::getSystem(), espressopp::SystemAccess::getSystemRef(), espressopp::iterator::CellListIterator::isValid(), regionupdates, updatecount, and verletList.
Referenced by Adress(), and integrate1().
connect()
void espressopp::integrator::Adress::connect () private virtual
Implements espressopp::integrator::Extension.
Definition at line 80 of file Adress.cpp.
References _aftCalcSlow, _befIntV, _initForces, _integrate1, _integrate2, _integrateSlow, _recalc2, _SetPosVel, aftCalcF(), initForces(), integrate1(), integrate2(), integrateSlow(), espressopp::integrator::Extension::integrator, and SetPosVel().
Referenced by registerPython().
disconnect()
void espressopp::integrator::Adress::disconnect () private virtual
Implements espressopp::integrator::Extension.
Definition at line 67 of file Adress.cpp.
References _aftCalcSlow, _befIntV, _initForces, _integrate1, _integrate2, _integrateSlow, _recalc2, and _SetPosVel.
Referenced by registerPython(), and ~Adress().
getSystem()
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::LatticeBoltzmann::assignMyLattice(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::PIAdressIntegrator::computeKineticEnergy(), espressopp::integrator::PIAdressIntegrator::computeMomentumDrift(), espressopp::integrator::PIAdressIntegrator::computePositionDrift(), espressopp::integrator::PIAdressIntegrator::computeRingEnergy(), espressopp::integrator::PIAdressIntegrator::computeRingEnergyRaw(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpXTCAdress::dump(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::io::DumpXYZ::DumpXYZ(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::VerletListTriple::registerPython(), espressopp::VerletList::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
getSystem1()
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
getSystem2()
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
getSystemRef()
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::addForces(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::addForces(), aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerletRESPA::calcForces(), espressopp::integrator::VelocityVerlet::calcForces(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::PIAdressIntegrator::calcForcesF(), espressopp::integrator::PIAdressIntegrator::calcForcesM(), espressopp::integrator::PIAdressIntegrator::calcForcesS(), communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeCOM(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeEnergy(), espressopp::integrator::PIAdressIntegrator::computeKineticEnergy(), espressopp::integrator::PIAdressIntegrator::computeMomentumDrift(), espressopp::integrator::PIAdressIntegrator::computePositionDrift(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::integrator::PIAdressIntegrator::computeRingEnergy(), espressopp::integrator::PIAdressIntegrator::computeRingEnergyRaw(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::PIAdressIntegrator::distributeForces(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::FixedLocalTupleComListInteractionTemplate(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::VelocityVerletRESPA::initForces(), espressopp::integrator::VelocityVerlet::initForces(), initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::PIAdressIntegrator::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::PIAdressIntegrator::initializeSetup(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::VelocityVerletRESPA::integrate1(), espressopp::integrator::VelocityVerlet::integrate1(), integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::VelocityVerletRESPA::integrate2(), espressopp::integrator::VelocityVerlet::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), integrate2(), espressopp::integrator::PIAdressIntegrator::integrateModePos(), integrateSlow(), espressopp::integrator::PIAdressIntegrator::integrateV1(), espressopp::integrator::PIAdressIntegrator::integrateV2(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::PIAdressIntegrator::OUintegrate(), espressopp::integrator::VelocityVerlet::printForces(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerlet::printPositions(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::VelocityVerletRESPA::run(), espressopp::integrator::PIAdressIntegrator::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::MinimizeEnergy::run(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::Rattle::saveOldPos(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::PIAdressIntegrator::setWeights(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostatOnGroup::thermalize(), espressopp::integrator::LangevinThermostatOnRadius::thermalize(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::integrator::PIAdressIntegrator::transForces(), espressopp::integrator::PIAdressIntegrator::transMom1(), espressopp::integrator::PIAdressIntegrator::transMom2(), espressopp::integrator::PIAdressIntegrator::transPos1(), espressopp::integrator::PIAdressIntegrator::transPos2(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::io::DumpH5MD::update(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::VelocityVerletRESPA::updateForces(), espressopp::integrator::VelocityVerlet::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::PIAdressIntegrator::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
getSystemRef1()
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
getSystemRef2()
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
getType()
ExtensionType espressopp::integrator::Extension::getType () inline inherited
Definition at line 67 of file Extension.hpp.
References espressopp::integrator::Extension::type.
Referenced by espressopp::integrator::Extension::registerPython().
initForces()
void espressopp::integrator::Adress::initForces () private
Definition at line 211 of file Adress.cpp.
References espressopp::SystemAccess::getSystemRef(), and espressopp::System::storage.
Referenced by connect().
integrate1()
void espressopp::integrator::Adress::integrate1 (real & maxSqDist) private
Definition at line 238 of file Adress.cpp.
References communicateAdrPositions(), fixedtupleList, espressopp::Particle::getMass(), espressopp::SystemAccess::getSystemRef(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::integrator::Extension::integrator, espressopp::iterator::CellListIterator::isDone(), KTI, espressopp::Particle::lambda(), espressopp::Particle::lambdaDeriv(), espressopp::Particle::mass(), espressopp::Particle::position(), espressopp::Real3D::sqr(), espressopp::System::storage, espressopp::Particle::velocity(), verletList, weight(), and weightderivative().
Referenced by connect().
integrate2()
void espressopp::integrator::Adress::integrate2 () private
Definition at line 375 of file Adress.cpp.
References fixedtupleList, espressopp::Particle::getMass(), espressopp::SystemAccess::getSystemRef(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::integrator::Extension::integrator, espressopp::iterator::CellListIterator::isDone(), espressopp::Particle::mass(), espressopp::Particle::position(), espressopp::System::storage, and espressopp::Particle::velocity().
Referenced by connect().
integrateSlow()
void espressopp::integrator::Adress::integrateSlow () private
Definition at line 430 of file Adress.cpp.
References fixedtupleList, espressopp::Particle::getMass(), espressopp::SystemAccess::getSystemRef(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::integrator::Extension::integrator, espressopp::iterator::CellListIterator::isDone(), espressopp::Particle::mass(), multistep, espressopp::Particle::position(), espressopp::System::storage, and espressopp::Particle::velocity().
Referenced by connect().
LOG4ESPP_DECL_LOGGER()
static espressopp::integrator::Extension::LOG4ESPP_DECL_LOGGER (theLogger) static protected inherited
Logger.
registerPython()
void espressopp::integrator::Adress::registerPython () static
Register this class so it can be used from Python.
Definition at line 638 of file Adress.cpp.
References connect(), and disconnect().
Referenced by espressopp::integrator::registerPython().
setIntegrator()
void espressopp::integrator::Extension::setIntegrator (shared_ptr< MDIntegrator > _integrator) protected inherited
Definition at line 49 of file Extension.cpp.
References espressopp::integrator::Extension::integrator.
Referenced by espressopp::integrator::Extension::registerPython().
SetPosVel()
void espressopp::integrator::Adress::SetPosVel () private
Definition at line 126 of file Adress.cpp.
References fixedtupleList, espressopp::Particle::getMass(), espressopp::SystemAccess::getSystemRef(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::iterator::CellListIterator::isDone(), KTI, espressopp::Particle::lambda(), espressopp::Particle::lambdaDeriv(), espressopp::Particle::mass(), espressopp::Particle::position(), espressopp::Real3D::sqr(), espressopp::System::storage, espressopp::Particle::velocity(), verletList, weight(), and weightderivative().
Referenced by connect().
setType()
void espressopp::integrator::Extension::setType (ExtensionType k) inline inherited
Definition at line 68 of file Extension.hpp.
Referenced by espressopp::integrator::Extension::registerPython().
weight()
real espressopp::integrator::Adress::weight (real distanceSqr) private
Definition at line 577 of file Adress.cpp.
References dex, dex2, dexdhy2, and pidhy2.
Referenced by integrate1(), and SetPosVel().
weightderivative()
real espressopp::integrator::Adress::weightderivative (real distanceSqr) private
Definition at line 586 of file Adress.cpp.
References dex, dex2, dexdhy2, and pidhy2.
Referenced by integrate1(), and SetPosVel().
Member Data Documentation
_aftCalcSlow
boost::signals2::connection espressopp::integrator::Adress::_aftCalcSlow private
Definition at line 69 of file Adress.hpp.
Referenced by connect(), and disconnect().
_befIntV
boost::signals2::connection espressopp::integrator::Adress::_befIntV private
Definition at line 69 of file Adress.hpp.
Referenced by connect(), and disconnect().
_initForces
boost::signals2::connection espressopp::integrator::Adress::_initForces private
Definition at line 69 of file Adress.hpp.
Referenced by connect(), and disconnect().
_integrate1
boost::signals2::connection espressopp::integrator::Adress::_integrate1 private
Definition at line 69 of file Adress.hpp.
Referenced by connect(), and disconnect().
_integrate2
boost::signals2::connection espressopp::integrator::Adress::_integrate2 private
Definition at line 69 of file Adress.hpp.
Referenced by connect(), and disconnect().
_integrateSlow
boost::signals2::connection espressopp::integrator::Adress::_integrateSlow private
Definition at line 69 of file Adress.hpp.
Referenced by connect(), and disconnect().
_recalc2
boost::signals2::connection espressopp::integrator::Adress::_recalc2 private
Definition at line 69 of file Adress.hpp.
Referenced by connect(), and disconnect().
_SetPosVel
boost::signals2::connection espressopp::integrator::Adress::_SetPosVel private
Definition at line 69 of file Adress.hpp.
Referenced by connect(), and disconnect().
dex
real espressopp::integrator::Adress::dex
Definition at line 55 of file Adress.hpp.
Referenced by Adress(), weight(), and weightderivative().
dex2
real espressopp::integrator::Adress::dex2
Definition at line 56 of file Adress.hpp.
Referenced by Adress(), weight(), and weightderivative().
dexdhy
real espressopp::integrator::Adress::dexdhy
Definition at line 57 of file Adress.hpp.
Referenced by Adress().
dexdhy2
real espressopp::integrator::Adress::dexdhy2
Definition at line 58 of file Adress.hpp.
Referenced by Adress(), weight(), and weightderivative().
dhy
real espressopp::integrator::Adress::dhy
Definition at line 53 of file Adress.hpp.
Referenced by Adress().
fixedtupleList
shared_ptr<FixedTupleListAdress> espressopp::integrator::Adress::fixedtupleList
Definition at line 48 of file Adress.hpp.
Referenced by aftCalcF(), integrate1(), integrate2(), integrateSlow(), and SetPosVel().
integrator
shared_ptr<MDIntegrator> espressopp::integrator::Extension::integrator protected inherited
Definition at line 72 of file Extension.hpp.
Referenced by espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::LatticeBoltzmann::calcRandForce(), espressopp::integrator::ExtAnalyze::connect(), espressopp::integrator::Rattle::connect(), espressopp::integrator::VelocityVerletOnRadius::connect(), espressopp::integrator::BerendsenBarostatAnisotropic::connect(), espressopp::integrator::BerendsenBarostat::connect(), espressopp::integrator::FixPositions::connect(), espressopp::integrator::Isokinetic::connect(), espressopp::integrator::ExtForce::connect(), espressopp::integrator::FreeEnergyCompensation::connect(), espressopp::integrator::BerendsenThermostat::connect(), espressopp::integrator::TDforce::connect(), espressopp::integrator::Settle::connect(), espressopp::integrator::LangevinThermostatOnGroup::connect(), connect(), espressopp::integrator::CapForce::connect(), espressopp::integrator::LangevinThermostatOnRadius::connect(), espressopp::integrator::OnTheFlyFEC::connect(), espressopp::integrator::DPDThermostat::connect(), espressopp::integrator::GeneralizedLangevinThermostat::connect(), espressopp::integrator::LangevinThermostat1D::connect(), espressopp::integrator::LangevinThermostatHybrid::connect(), espressopp::integrator::LangevinBarostat::connect(), espressopp::integrator::LangevinThermostat::connect(), espressopp::integrator::AssociationReaction::connect(), espressopp::integrator::StochasticVelocityRescaling::connect(), espressopp::integrator::LatticeBoltzmann::connect(), espressopp::integrator::LatticeBoltzmann::convTimeMDtoLB(), espressopp::integrator::LangevinThermostatOnGroup::initialize(), espressopp::integrator::LangevinThermostatOnRadius::initialize(), espressopp::integrator::LangevinThermostat::initialize(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinThermostat1D::initialize(), espressopp::integrator::BerendsenThermostat::initialize(), espressopp::integrator::LangevinThermostatHybrid::initialize(), espressopp::integrator::BerendsenBarostatAnisotropic::initialize(), espressopp::integrator::BerendsenBarostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), integrate2(), integrateSlow(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::Extension::setIntegrator(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
KTI
bool espressopp::integrator::Adress::KTI
Definition at line 49 of file Adress.hpp.
Referenced by integrate1(), and SetPosVel().
multistep
int espressopp::integrator::Adress::multistep
Definition at line 51 of file Adress.hpp.
Referenced by integrateSlow().
pidhy2
real espressopp::integrator::Adress::pidhy2
Definition at line 54 of file Adress.hpp.
Referenced by Adress(), weight(), and weightderivative().
regionupdates
int espressopp::integrator::Adress::regionupdates
Definition at line 50 of file Adress.hpp.
Referenced by communicateAdrPositions().
type
ExtensionType espressopp::integrator::Extension::type inherited
Definition at line 62 of file Extension.hpp.
Referenced by espressopp::integrator::TDforce::addForce(), Adress(), espressopp::integrator::AssociationReaction::AssociationReaction(), espressopp::integrator::BerendsenBarostat::BerendsenBarostat(), espressopp::integrator::BerendsenBarostatAnisotropic::BerendsenBarostatAnisotropic(), espressopp::integrator::BerendsenThermostat::BerendsenThermostat(), espressopp::integrator::DPDThermostat::DPDThermostat(), espressopp::integrator::ExtAnalyze::ExtAnalyze(), espressopp::integrator::FreeEnergyCompensation::FreeEnergyCompensation(), espressopp::integrator::GeneralizedLangevinThermostat::GeneralizedLangevinThermostat(), espressopp::integrator::Extension::getType(), espressopp::integrator::LangevinBarostat::LangevinBarostat(), espressopp::integrator::LangevinThermostat::LangevinThermostat(), espressopp::integrator::LangevinThermostat1D::LangevinThermostat1D(), espressopp::integrator::LangevinThermostatHybrid::LangevinThermostatHybrid(), espressopp::integrator::LangevinThermostatOnGroup::LangevinThermostatOnGroup(), espressopp::integrator::LangevinThermostatOnRadius::LangevinThermostatOnRadius(), espressopp::integrator::OnTheFlyFEC::OnTheFlyFEC(), espressopp::integrator::TDforce::registerPython(), espressopp::integrator::StochasticVelocityRescaling::StochasticVelocityRescaling(), and espressopp::integrator::TDforce::TDforce().
updatecount
int espressopp::integrator::Adress::updatecount private
Definition at line 84 of file Adress.hpp.
Referenced by Adress(), and communicateAdrPositions().
verletList
shared_ptr<VerletListAdress> espressopp::integrator::Adress::verletList
Definition at line 47 of file Adress.hpp.
Referenced by Adress(), communicateAdrPositions(), integrate1(), and SetPosVel().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/integrator/Adress.hpp
/home/espressopp/espressopp/src/integrator/Adress.cpp