ESPResSo++: espressopp::integrator::MDIntegrator Class Reference
espressopp::integrator::MDIntegrator Class Reference abstract
#include <MDIntegrator.hpp>
Public Member Functions
MDIntegrator (shared_ptr< System > system)
Constructor for an integrator.
virtual ~MDIntegrator ()
Destructor.
void setTimeStep (real dt)
Setter routine for the timestep.
real getTimeStep ()
Getter routine for the timestep.
void setStep (long long step_)
Getter routine for integration step.
long long getStep ()
Getter routine for integration step.
virtual void run (int nsteps)=0
This method runs the integration for a certain number of steps.
void addExtension (shared_ptr< integrator::Extension > extension)
shared_ptr< integrator::Extension > getExtension (int k)
int getNumberOfExtensions ()
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
Register this class so it can be used from Python.
Public Attributes
boost::signals2::signal< void()> runInit
boost::signals2::signal< void()> recalc1
boost::signals2::signal< void()> recalc2
boost::signals2::signal< void()> befIntP
boost::signals2::signal< void(real &)> inIntP
boost::signals2::signal< void()> aftIntP
boost::signals2::signal< void()> aftInitF
boost::signals2::signal< void()> aftCalcF
boost::signals2::signal< void()> befIntV
boost::signals2::signal< void()> aftIntV
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Protected Attributes
bool timeFlag
ExtensionList exList
long long step
Integration step.
real dt
Timestep used for integration.
Detailed Description
Definition at line 52 of file MDIntegrator.hpp.
Constructor & Destructor Documentation
espressopp::integrator::MDIntegrator::MDIntegrator (shared_ptr< System > system)
Constructor for an integrator.
Parameters
system is reference to the system. Note: This class will keep a weak reference to the system.
Definition at line 37 of file MDIntegrator.cpp.
References dt, LOG4ESPP_ERROR, LOG4ESPP_INFO, step, and timeFlag.
espressopp::integrator::MDIntegrator::~MDIntegrator () virtual
Destructor.
Definition at line 49 of file MDIntegrator.cpp.
References LOG4ESPP_INFO.
Member Function Documentation
void espressopp::integrator::MDIntegrator::addExtension (shared_ptr< integrator::Extension > extension)
Definition at line 68 of file MDIntegrator.cpp.
References exList.
Referenced by registerPython().
shared_ptr< integrator::Extension > espressopp::integrator::MDIntegrator::getExtension (int k)
Definition at line 92 of file MDIntegrator.cpp.
References exList.
Referenced by registerPython().
int espressopp::integrator::MDIntegrator::getNumberOfExtensions ()
Definition at line 88 of file MDIntegrator.cpp.
References exList.
Referenced by registerPython().
long long espressopp::integrator::MDIntegrator::getStep () inline
Getter routine for integration step.
Definition at line 73 of file MDIntegrator.hpp.
Referenced by registerPython().
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::LatticeBoltzmann::assignMyLattice(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::io::DumpXYZ::DumpXYZ(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::VerletListTriple::registerPython(), espressopp::VerletList::registerPython(), espressopp::VerletListAdress::registerPython(), registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::addForces(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::addForces(), espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerlet::calcForces(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeCOM(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::FixedLocalTupleComListInteractionTemplate(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::VelocityVerlet::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::VelocityVerlet::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::VelocityVerlet::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::VelocityVerlet::printForces(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerlet::printPositions(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::MinimizeEnergy::run(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::Rattle::saveOldPos(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostatOnGroup::thermalize(), espressopp::integrator::LangevinThermostatOnRadius::thermalize(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::VelocityVerlet::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
real espressopp::integrator::MDIntegrator::getTimeStep () inline
Getter routine for the timestep.
Definition at line 67 of file MDIntegrator.hpp.
Referenced by registerPython().
static espressopp::integrator::MDIntegrator::LOG4ESPP_DECL_LOGGER (theLogger) static protected
Logger.
void espressopp::integrator::MDIntegrator::registerPython () static
Register this class so it can be used from Python.
Definition at line 100 of file MDIntegrator.cpp.
References addExtension(), getExtension(), getNumberOfExtensions(), getStep(), espressopp::SystemAccess::getSystem(), getTimeStep(), run(), setStep(), and setTimeStep().
Referenced by espressopp::integrator::registerPython().
virtual void espressopp::integrator::MDIntegrator::run (int nsteps) pure virtual
This method runs the integration for a certain number of steps.
Implemented in espressopp::integrator::VelocityVerletOnGroup, and espressopp::integrator::VelocityVerlet.
Referenced by registerPython().
void espressopp::integrator::MDIntegrator::setStep (long long step_) inline
Getter routine for integration step.
Definition at line 70 of file MDIntegrator.hpp.
Referenced by registerPython().
void espressopp::integrator::MDIntegrator::setTimeStep (real dt)
Setter routine for the timestep.
Definition at line 54 of file MDIntegrator.cpp.
References espressopp::System::comm, dt, espressopp::SystemAccess::getSystemRef(), and espressopp::esutil::Error::setException().
Referenced by registerPython().
Member Data Documentation
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::aftCalcF
Definition at line 92 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerlet::updateForces().
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::aftInitF
Definition at line 91 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerlet::calcForces().
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::aftIntP
Definition at line 90 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerlet::run().
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::aftIntV
Definition at line 94 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerlet::run().
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::befIntP
Definition at line 88 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerlet::run().
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::befIntV
Definition at line 93 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerlet::run().
real espressopp::integrator::MDIntegrator::dt protected
Timestep used for integration.
Definition at line 110 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerlet::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerlet::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), MDIntegrator(), and setTimeStep().
ExtensionList espressopp::integrator::MDIntegrator::exList protected
Definition at line 104 of file MDIntegrator.hpp.
Referenced by addExtension(), getExtension(), and getNumberOfExtensions().
boost::signals2::signal<void (real&)> espressopp::integrator::MDIntegrator::inIntP
Definition at line 89 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerlet::integrate1().
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::recalc1
Definition at line 86 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerlet::run().
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::recalc2
Definition at line 87 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerlet::run().
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::runInit
Definition at line 85 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerlet::run().
long long espressopp::integrator::MDIntegrator::step protected
Integration step.
Definition at line 107 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerlet::integrate2(), and MDIntegrator().
bool espressopp::integrator::MDIntegrator::timeFlag protected
Definition at line 102 of file MDIntegrator.hpp.
Referenced by MDIntegrator().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/integrator/MDIntegrator.hpp
/home/espressopp/espressopp/src/integrator/MDIntegrator.cpp