ESPResSo++: espressopp::FixedTupleList Class Reference
espressopp::FixedTupleList Class Reference
#include <FixedTupleList.hpp>
Public Types
typedef ESPPIterator< std::map
< Particle *, std::vector
< Particle * > > > Iterator
Public Member Functions
FixedTupleList (shared_ptr< storage::Storage > _storage)
virtual ~FixedTupleList ()
virtual bool addTuple (boost::python::list &tuple)
virtual void beforeSendParticles (ParticleList &pl, class OutBuffer &buf)
void afterRecvParticles (ParticleList &pl, class InBuffer &buf)
virtual void onParticlesChanged ()
python::list getTuples ()
int size ()
Get the number of triples in the GlobalTriples list.
void add (Particle *p, std::vector< Particle * > particles)
Static Public Member Functions
static void registerPython ()
Protected Types
typedef std::vector< longint > tuple
typedef std::multimap< longint,
tuple > GlobalTuples
typedef std::map< Particle
*, std::vector< Particle * > > Super
Protected Attributes
boost::signals2::connection con1
boost::signals2::connection con2
boost::signals2::connection con3
shared_ptr< storage::Storage > storage
GlobalTuples globalTuples
Static Private Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Detailed Description
Definition at line 36 of file FixedTupleList.hpp.
Member Typedef Documentation
typedef std::multimap<longint,tuple > espressopp::FixedTupleList::GlobalTuples [protected]
Definition at line 41 of file FixedTupleList.hpp.
typedef ESPPIterator<std::map< Particle *, std::vector< Particle * > > > espressopp::esutil::ESPPContainer< std::map< Particle *, std::vector< Particle * > > >::Iterator [inherited]
Definition at line 66 of file ESPPIterator.hpp.
typedef std::map< Particle *, std::vector< Particle * > > espressopp::esutil::ESPPContainer< std::map< Particle *, std::vector< Particle * > > >::Super [protected, inherited]
Definition at line 64 of file ESPPIterator.hpp.
typedef std::vector<longint> espressopp::FixedTupleList::tuple [protected]
Definition at line 40 of file FixedTupleList.hpp.
Constructor & Destructor Documentation
espressopp::FixedTupleList::FixedTupleList (shared_ptr< storage::Storage > _storage)
Definition at line 41 of file FixedTupleList.cpp.
References afterRecvParticles(), beforeSendParticles(), con1, con2, con3, LOG4ESPP_INFO, onParticlesChanged(), and storage.
espressopp::FixedTupleList::~FixedTupleList () [virtual]
Definition at line 54 of file FixedTupleList.cpp.
References con1, con2, con3, and LOG4ESPP_INFO.
Member Function Documentation
void espressopp::TupleList::add (Particle * p, std::vector< Particle * > particles) [inline, inherited]
Definition at line 470 of file Particle.hpp.
Referenced by addTuple(), and onParticlesChanged().
bool espressopp::FixedTupleList::addTuple (boost::python::list & tuple) [virtual]
Definition at line 64 of file FixedTupleList.cpp.
References espressopp::TupleList::add(), espressopp::esutil::Error::checkException(), espressopp::System::comm, globalTuples, LOG4ESPP_INFO, espressopp::esutil::Error::setException(), and storage.
Referenced by registerPython().
void espressopp::FixedTupleList::afterRecvParticles (ParticleList & pl, class InBuffer & buf)
Definition at line 168 of file FixedTupleList.cpp.
References globalTuples, espressopp::Particle::id(), LOG4ESPP_DEBUG, and espressopp::InBuffer::read().
Referenced by FixedTupleList().
void espressopp::FixedTupleList::beforeSendParticles (ParticleList & pl, class OutBuffer & buf) [virtual]
Definition at line 133 of file FixedTupleList.cpp.
References globalTuples, espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_DEBUG, storage, and espressopp::OutBuffer::write().
Referenced by FixedTupleList().
python::list espressopp::FixedTupleList::getTuples ()
Definition at line 116 of file FixedTupleList.cpp.
References globalTuples.
Referenced by registerPython().
static espressopp::FixedTupleList::LOG4ESPP_DECL_LOGGER (theLogger) [static, private]
void espressopp::FixedTupleList::onParticlesChanged () [virtual]
Definition at line 191 of file FixedTupleList.cpp.
References espressopp::TupleList::add(), espressopp::System::comm, globalTuples, LOG4ESPP_INFO, espressopp::esutil::Error::setException(), and storage.
Referenced by FixedTupleList().
void espressopp::FixedTupleList::registerPython () [static]
Definition at line 231 of file FixedTupleList.cpp.
References addTuple(), getTuples(), and size().
Referenced by espressopp::registerPython().
int espressopp::FixedTupleList::size () [inline]
Get the number of triples in the GlobalTriples list.
Definition at line 58 of file FixedTupleList.hpp.
References globalTuples.
Referenced by registerPython().
Member Data Documentation
boost::signals2::connection espressopp::FixedTupleList::con1 [protected]
Definition at line 38 of file FixedTupleList.hpp.
Referenced by FixedTupleList(), and ~FixedTupleList().
boost::signals2::connection espressopp::FixedTupleList::con2 [protected]
Definition at line 38 of file FixedTupleList.hpp.
Referenced by FixedTupleList(), and ~FixedTupleList().
boost::signals2::connection espressopp::FixedTupleList::con3 [protected]
Definition at line 38 of file FixedTupleList.hpp.
Referenced by FixedTupleList(), and ~FixedTupleList().
GlobalTuples espressopp::FixedTupleList::globalTuples [protected]
Definition at line 42 of file FixedTupleList.hpp.
Referenced by addTuple(), afterRecvParticles(), beforeSendParticles(), getTuples(), onParticlesChanged(), and size().
shared_ptr<storage::Storage> espressopp::FixedTupleList::storage [protected]
Definition at line 39 of file FixedTupleList.hpp.
Referenced by addTuple(), beforeSendParticles(), FixedTupleList(), and onParticlesChanged().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/FixedTupleList.hpp
/home/travis/build/espressopp/espressopp/src/FixedTupleList.cpp