ESPResSo++: espressopp::FixedTripleList Class Reference
espressopp::FixedTripleList Class Reference
#include <FixedTripleList.hpp>
Public Types
typedef ESPPIterator
< std::vector< ParticleTriple > > Iterator
Public Member Functions
FixedTripleList (shared_ptr< storage::Storage > _storage)
virtual ~FixedTripleList ()
virtual bool add (longint pid1, longint pid2, longint pid3)
Add the given particle triple to the list on this processor if the
particle with the lower id belongs to this processor.
virtual void beforeSendParticles (ParticleList &pl, class OutBuffer &buf)
void afterRecvParticles (ParticleList &pl, class InBuffer &buf)
virtual void onParticlesChanged ()
python::list getTriples ()
int size ()
Get the number of triples in the GlobalTriples list.
void add (Particle *p1, Particle *p2, Particle *p3)
void add (Particle &p1, Particle &p2, Particle &p3)
void add (std::vector< Particle * > particles)
Static Public Member Functions
static void registerPython ()
Protected Types
typedef
boost::unordered_multimap
< longint, std::pair< longint,
longint > > GlobalTriples
typedef std::vector
< ParticleTriple > Super
Protected Attributes
boost::signals2::connection sigAfterRecv
boost::signals2::connection sigOnParticleChanged
boost::signals2::connection sigBeforeSend
shared_ptr< storage::Storage > storage
GlobalTriples globalTriples
Static Private Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Detailed Description
Definition at line 37 of file FixedTripleList.hpp.
Member Typedef Documentation
typedef boost::unordered_multimap<longint,std::pair <longint, longint> > espressopp::FixedTripleList::GlobalTriples protected
Definition at line 41 of file FixedTripleList.hpp.
typedef ESPPIterator<std::vector< ParticleTriple > > espressopp::esutil::ESPPContainer< std::vector< ParticleTriple > >::Iterator inherited
Definition at line 66 of file ESPPIterator.hpp.
typedef std::vector< ParticleTriple > espressopp::esutil::ESPPContainer< std::vector< ParticleTriple > >::Super protected inherited
Definition at line 64 of file ESPPIterator.hpp.
Constructor & Destructor Documentation
espressopp::FixedTripleList::FixedTripleList (shared_ptr< storage::Storage > _storage)
Definition at line 47 of file FixedTripleList.cpp.
References afterRecvParticles(), beforeSendParticles(), LOG4ESPP_INFO, onParticlesChanged(), sigAfterRecv, sigBeforeSend, sigOnParticleChanged, and storage.
espressopp::FixedTripleList::~FixedTripleList () virtual
Definition at line 60 of file FixedTripleList.cpp.
References LOG4ESPP_INFO, sigAfterRecv, sigBeforeSend, and sigOnParticleChanged.
Member Function Documentation
bool espressopp::FixedTripleList::add (longint pid1, longint pid2, longint pid3) virtual
Add the given particle triple to the list on this processor if the
particle with the lower id belongs to this processor.
Note that this routine does not check whether the triple is inserted on another processor as well.
Returns
whether the triple was inserted on this processor.
Reimplemented in espressopp::FixedTripleListAdress.
Definition at line 81 of file FixedTripleList.cpp.
References espressopp::esutil::Error::checkException(), espressopp::System::comm, globalTriples, LOG4ESPP_INFO, espressopp::esutil::Error::setException(), and storage.
Referenced by onParticlesChanged(), and registerPython().
void espressopp::TripleList::add (Particle * p1, Particle * p2, Particle * p3) inline inherited
Definition at line 424 of file Particle.hpp.
Referenced by espressopp::FixedListComm::add(), espressopp::TripleList::add(), espressopp::VerletListTriple::checkTriple(), and espressopp::FixedListComm::onParticlesChanged().
void espressopp::TripleList::add (Particle & p1, Particle & p2, Particle & p3) inline inherited
Definition at line 428 of file Particle.hpp.
References espressopp::TripleList::add().
Referenced by espressopp::TripleList::add().
void espressopp::TripleList::add (std::vector< Particle * > particles) inline inherited
Definition at line 431 of file Particle.hpp.
References espressopp::TripleList::add().
void espressopp::FixedTripleList::afterRecvParticles (ParticleList & pl, class InBuffer & buf)
Definition at line 213 of file FixedTripleList.cpp.
References globalTriples, LOG4ESPP_INFO, espressopp::InBuffer::read(), and size().
Referenced by FixedTripleList(), and espressopp::FixedTripleListAdress::FixedTripleListAdress().
void espressopp::FixedTripleList::beforeSendParticles (ParticleList & pl, class OutBuffer & buf) virtual
Reimplemented in espressopp::FixedTripleListAdress.
Definition at line 170 of file FixedTripleList.cpp.
References globalTriples, espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_INFO, and espressopp::OutBuffer::write().
Referenced by FixedTripleList().
python::list espressopp::FixedTripleList::getTriples ()
Definition at line 157 of file FixedTripleList.cpp.
References globalTriples.
Referenced by registerPython().
static espressopp::FixedTripleList::LOG4ESPP_DECL_LOGGER (theLogger) static private
void espressopp::FixedTripleList::onParticlesChanged () virtual
Reimplemented in espressopp::FixedTripleListAdress.
Definition at line 242 of file FixedTripleList.cpp.
References add(), espressopp::esutil::Error::checkException(), espressopp::System::comm, globalTriples, LOG4ESPP_INFO, espressopp::esutil::Error::setException(), and storage.
Referenced by FixedTripleList().
void espressopp::FixedTripleList::registerPython () static
Definition at line 289 of file FixedTripleList.cpp.
References add(), getTriples(), and size().
Referenced by espressopp::registerPython().
int espressopp::FixedTripleList::size () inline
Get the number of triples in the GlobalTriples list.
Definition at line 65 of file FixedTripleList.hpp.
References globalTriples.
Referenced by afterRecvParticles(), and registerPython().
Member Data Documentation
GlobalTriples espressopp::FixedTripleList::globalTriples protected
Definition at line 42 of file FixedTripleList.hpp.
Referenced by add(), espressopp::FixedTripleListAdress::add(), afterRecvParticles(), espressopp::FixedTripleListAdress::beforeSendATParticles(), beforeSendParticles(), getTriples(), espressopp::FixedTripleListAdress::onParticlesChanged(), onParticlesChanged(), and size().
boost::signals2::connection espressopp::FixedTripleList::sigAfterRecv protected
Definition at line 39 of file FixedTripleList.hpp.
Referenced by FixedTripleList(), espressopp::FixedTripleListAdress::FixedTripleListAdress(), and ~FixedTripleList().
boost::signals2::connection espressopp::FixedTripleList::sigBeforeSend protected
Definition at line 39 of file FixedTripleList.hpp.
Referenced by FixedTripleList(), espressopp::FixedTripleListAdress::FixedTripleListAdress(), and ~FixedTripleList().
boost::signals2::connection espressopp::FixedTripleList::sigOnParticleChanged protected
Definition at line 39 of file FixedTripleList.hpp.
Referenced by FixedTripleList(), and ~FixedTripleList().
shared_ptr<storage::Storage> espressopp::FixedTripleList::storage protected
Definition at line 40 of file FixedTripleList.hpp.
Referenced by add(), espressopp::FixedTripleListAdress::add(), FixedTripleList(), onParticlesChanged(), and espressopp::FixedTripleListAdress::onParticlesChanged().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/FixedTripleList.hpp
/home/travis/build/espressopp/espressopp/src/FixedTripleList.cpp