ESPResSo++: espressopp::interaction::ReactionFieldGeneralizedTI Class Reference
espressopp::interaction::ReactionFieldGeneralizedTI Class Reference abstract
#include <ReactionFieldGeneralizedTI.hpp>
Public Member Functions
ReactionFieldGeneralizedTI ()
ReactionFieldGeneralizedTI (real _prefactor, real _kappa, real _eps1, real _eps2, real _cutoff, real _lambdaTI, bool _annihilate)
real getKappa () const
real getEpsilon1 () const
real getEpsilon2 () const
real getLambdaTI () const
bool getAnnihilate () const
void setCutoff (real _cutoff)
void setPrefactor (real _prefactor)
real getPrefactor () const
void addPid (longint pid)
bool checkTIpair (size_t pid1, size_t pid2) const
real _computeEnergy (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
real _computeEnergyDeriv (const Particle &p1, const Particle &p2) const
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &dist, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual real getCutoff () const
virtual real getCutoff () const =0
virtual void setShift (real _shift)
virtual real getShift () const
virtual real getShift () const =0
virtual real setAutoShift ()
void updateAutoShift ()
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)
virtual shared_ptr< FixedPairList > getColVarBondList () const
virtual shared_ptr< FixedPairList > getColVarBondList () const =0
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &fpl)
virtual shared_ptr< FixedTripleList > getColVarAngleList () const
virtual shared_ptr< FixedTripleList > getColVarAngleList () const =0
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fpl)
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const =0
virtual void setColVar (const RealND &cv)
virtual void setColVar (const Real3D &dist, const bc::BC &bc)
virtual RealND getColVar () const
virtual RealND getColVar () const =0
virtual void computeColVarWeights (const Real3D &dist, const bc::BC &bc)
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
ReactionFieldGeneralizedTI * derived_this ()
const ReactionFieldGeneralizedTI * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
shared_ptr< FixedPairList > colVarBondList
shared_ptr< FixedTripleList > colVarAngleList
shared_ptr< FixedQuadrupleList > colVarDihedList
RealND colVar
Private Member Functions
void initialize ()
Private Attributes
real kappa
real epsilon1
real epsilon2
real rc
real rc3
real rc2
real B1
real B0
real B1_half
real prefactor
bool annihilate
real crf
real lambdaTI
real complLambdaTI
std::set< longint > pidsTI
Detailed Description
Definition at line 40 of file ReactionFieldGeneralizedTI.hpp.
Constructor & Destructor Documentation
ReactionFieldGeneralizedTI() [1/2]
espressopp::interaction::ReactionFieldGeneralizedTI::ReactionFieldGeneralizedTI () inline
Definition at line 75 of file ReactionFieldGeneralizedTI.hpp.
References espressopp::infinity.
ReactionFieldGeneralizedTI() [2/2]
espressopp::interaction::ReactionFieldGeneralizedTI::ReactionFieldGeneralizedTI (real _prefactor, real _kappa, real _eps1, real _eps2, real _cutoff, real _lambdaTI, bool _annihilate) inline
Definition at line 85 of file ReactionFieldGeneralizedTI.hpp.
Member Function Documentation
_computeEnergy() [1/4]
real espressopp::interaction::ReactionFieldGeneralizedTI::_computeEnergy (const Particle & p1, const Particle & p2) const inline
Definition at line 144 of file ReactionFieldGeneralizedTI.hpp.
References espressopp::Particle::id(), espressopp::Particle::position(), espressopp::Particle::q(), and espressopp::Real3D::sqr().
_computeEnergy() [2/4]
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 360 of file Potential.hpp.
_computeEnergy() [3/4]
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::_computeEnergy (const Real3D & dist) const inline inherited
Definition at line 367 of file Potential.hpp.
_computeEnergy() [4/4]
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::_computeEnergy (real dist) const inline inherited
Definition at line 374 of file Potential.hpp.
_computeEnergyDeriv()
real espressopp::interaction::ReactionFieldGeneralizedTI::_computeEnergyDeriv (const Particle & p1, const Particle & p2) const inline
Definition at line 177 of file ReactionFieldGeneralizedTI.hpp.
References espressopp::Particle::id(), espressopp::Particle::position(), espressopp::Particle::q(), and espressopp::Real3D::sqr().
_computeEnergySqr()
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::_computeEnergySqr (real distSqr) const inline inherited
Definition at line 381 of file Potential.hpp.
_computeEnergySqrRaw()
real espressopp::interaction::ReactionFieldGeneralizedTI::_computeEnergySqrRaw (real distSqr) const inline
Definition at line 190 of file ReactionFieldGeneralizedTI.hpp.
_computeForce() [1/3]
bool espressopp::interaction::ReactionFieldGeneralizedTI::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const inline
Definition at line 161 of file ReactionFieldGeneralizedTI.hpp.
References espressopp::Particle::id(), espressopp::Particle::position(), espressopp::Particle::q(), and espressopp::Real3D::sqr().
_computeForce() [2/3]
bool espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 431 of file Potential.hpp.
_computeForce() [3/3]
bool espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::_computeForce (Real3D & force, const Real3D & dist) const inline inherited
Definition at line 438 of file Potential.hpp.
_computeForceRaw()
bool espressopp::interaction::ReactionFieldGeneralizedTI::_computeForceRaw (Real3D & force, const Real3D & dist, real distSqr) const inline
Definition at line 195 of file ReactionFieldGeneralizedTI.hpp.
addPid()
void espressopp::interaction::ReactionFieldGeneralizedTI::addPid (longint pid) inline
Definition at line 122 of file ReactionFieldGeneralizedTI.hpp.
Referenced by registerPython().
checkTIpair()
bool espressopp::interaction::ReactionFieldGeneralizedTI::checkTIpair (size_t pid1, size_t pid2) const inline
Definition at line 126 of file ReactionFieldGeneralizedTI.hpp.
computeColVarWeights()
void espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::computeColVarWeights (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 315 of file Potential.hpp.
computeEnergy() [1/3]
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::computeEnergy (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 323 of file Potential.hpp.
computeEnergy() [2/3]
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::computeEnergy (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 331 of file Potential.hpp.
computeEnergy() [3/3]
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::computeEnergy (real dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 338 of file Potential.hpp.
computeEnergySqr()
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::computeEnergySqr (real distsqr) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 345 of file Potential.hpp.
computeForce() [1/2]
Real3D espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::computeForce (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 405 of file Potential.hpp.
computeForce() [2/2]
Real3D espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::computeForce (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 413 of file Potential.hpp.
derived_this() [1/2]
ReactionFieldGeneralizedTI * espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::derived_this inline protected inherited
Definition at line 161 of file Potential.hpp.
derived_this() [2/2]
const ReactionFieldGeneralizedTI * espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::derived_this inline protected inherited
Definition at line 165 of file Potential.hpp.
getAnnihilate()
bool espressopp::interaction::ReactionFieldGeneralizedTI::getAnnihilate () const inline
Definition at line 109 of file ReactionFieldGeneralizedTI.hpp.
Referenced by espressopp::interaction::ReactionFieldGeneralizedTI_pickle::getinitargs().
getColVar() [1/2]
RealND espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::getColVar inline virtual inherited
Definition at line 309 of file Potential.hpp.
getColVar() [2/2]
virtual RealND espressopp::interaction::Potential::getColVar () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getColVarAngleList() [1/2]
shared_ptr< FixedTripleList > espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::getColVarAngleList inline virtual inherited
Definition at line 273 of file Potential.hpp.
getColVarAngleList() [2/2]
virtual shared_ptr<FixedTripleList> espressopp::interaction::Potential::getColVarAngleList () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getColVarBondList() [1/2]
shared_ptr< FixedPairList > espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::getColVarBondList inline virtual inherited
Definition at line 259 of file Potential.hpp.
getColVarBondList() [2/2]
virtual shared_ptr<FixedPairList> espressopp::interaction::Potential::getColVarBondList () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getColVarDihedList() [1/2]
shared_ptr< FixedQuadrupleList > espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::getColVarDihedList inline virtual inherited
Definition at line 287 of file Potential.hpp.
getColVarDihedList() [2/2]
virtual shared_ptr<FixedQuadrupleList> espressopp::interaction::Potential::getColVarDihedList () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getCutoff() [1/2]
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::getCutoff inline virtual inherited
Definition at line 210 of file Potential.hpp.
getCutoff() [2/2]
virtual real espressopp::interaction::Potential::getCutoff () const pure virtual inherited
Implemented in espressopp::interaction::CoulombKSpaceP3M, and espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getEpsilon1()
real espressopp::interaction::ReactionFieldGeneralizedTI::getEpsilon1 () const inline
Definition at line 106 of file ReactionFieldGeneralizedTI.hpp.
Referenced by espressopp::interaction::ReactionFieldGeneralizedTI_pickle::getinitargs().
getEpsilon2()
real espressopp::interaction::ReactionFieldGeneralizedTI::getEpsilon2 () const inline
Definition at line 107 of file ReactionFieldGeneralizedTI.hpp.
Referenced by espressopp::interaction::ReactionFieldGeneralizedTI_pickle::getinitargs().
getKappa()
real espressopp::interaction::ReactionFieldGeneralizedTI::getKappa () const inline
Definition at line 105 of file ReactionFieldGeneralizedTI.hpp.
Referenced by espressopp::interaction::ReactionFieldGeneralizedTI_pickle::getinitargs().
getLambdaTI()
real espressopp::interaction::ReactionFieldGeneralizedTI::getLambdaTI () const inline
Definition at line 108 of file ReactionFieldGeneralizedTI.hpp.
Referenced by espressopp::interaction::ReactionFieldGeneralizedTI_pickle::getinitargs().
getPrefactor()
real espressopp::interaction::ReactionFieldGeneralizedTI::getPrefactor () const inline
Definition at line 120 of file ReactionFieldGeneralizedTI.hpp.
Referenced by espressopp::interaction::ReactionFieldGeneralizedTI_pickle::getinitargs(), and registerPython().
getShift() [1/2]
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::getShift inline virtual inherited
Definition at line 225 of file Potential.hpp.
getShift() [2/2]
virtual real espressopp::interaction::Potential::getShift () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
initialize()
void espressopp::interaction::ReactionFieldGeneralizedTI::initialize () inline private
Definition at line 56 of file ReactionFieldGeneralizedTI.hpp.
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
registerPython()
void espressopp::interaction::ReactionFieldGeneralizedTI::registerPython () static
Definition at line 45 of file ReactionFieldGeneralizedTI.cpp.
References addPid(), getPrefactor(), and setPrefactor().
Referenced by espressopp::interaction::registerPython().
setAutoShift()
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::setAutoShift inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 231 of file Potential.hpp.
setColVar() [1/2]
void espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::setColVar (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 301 of file Potential.hpp.
setColVar() [2/2]
void espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::setColVar (const RealND & cv) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 294 of file Potential.hpp.
setColVarAngleList()
void espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::setColVarAngleList (const shared_ptr< FixedTripleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 266 of file Potential.hpp.
setColVarBondList()
void espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::setColVarBondList (const shared_ptr< FixedPairList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 252 of file Potential.hpp.
setColVarDihedList()
void espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 280 of file Potential.hpp.
setCutoff()
void espressopp::interaction::ReactionFieldGeneralizedTI::setCutoff (real _cutoff) inline virtual
Reimplemented from espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >.
Definition at line 111 of file ReactionFieldGeneralizedTI.hpp.
setPrefactor()
void espressopp::interaction::ReactionFieldGeneralizedTI::setPrefactor (real _prefactor) inline
Definition at line 117 of file ReactionFieldGeneralizedTI.hpp.
Referenced by registerPython().
setShift()
void espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::setShift (real _shift) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 216 of file Potential.hpp.
updateAutoShift()
void espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::updateAutoShift inline inherited
Definition at line 244 of file Potential.hpp.
Member Data Documentation
annihilate
bool espressopp::interaction::ReactionFieldGeneralizedTI::annihilate private
Definition at line 49 of file ReactionFieldGeneralizedTI.hpp.
autoShift
bool espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::autoShift protected inherited
Definition at line 151 of file Potential.hpp.
B0
real espressopp::interaction::ReactionFieldGeneralizedTI::B0 private
Definition at line 47 of file ReactionFieldGeneralizedTI.hpp.
B1
real espressopp::interaction::ReactionFieldGeneralizedTI::B1 private
Definition at line 47 of file ReactionFieldGeneralizedTI.hpp.
B1_half
real espressopp::interaction::ReactionFieldGeneralizedTI::B1_half private
Definition at line 47 of file ReactionFieldGeneralizedTI.hpp.
colVar
RealND espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::colVar protected inherited
Definition at line 159 of file Potential.hpp.
colVarAngleList
shared_ptr<FixedTripleList> espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::colVarAngleList protected inherited
Definition at line 155 of file Potential.hpp.
colVarBondList
shared_ptr<FixedPairList> espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::colVarBondList protected inherited
Definition at line 153 of file Potential.hpp.
colVarDihedList
shared_ptr<FixedQuadrupleList> espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::colVarDihedList protected inherited
Definition at line 157 of file Potential.hpp.
complLambdaTI
real espressopp::interaction::ReactionFieldGeneralizedTI::complLambdaTI private
Definition at line 53 of file ReactionFieldGeneralizedTI.hpp.
crf
real espressopp::interaction::ReactionFieldGeneralizedTI::crf private
Definition at line 50 of file ReactionFieldGeneralizedTI.hpp.
cutoff
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::cutoff protected inherited
Definition at line 148 of file Potential.hpp.
cutoffSqr
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::cutoffSqr protected inherited
Definition at line 149 of file Potential.hpp.
epsilon1
real espressopp::interaction::ReactionFieldGeneralizedTI::epsilon1 private
Definition at line 44 of file ReactionFieldGeneralizedTI.hpp.
epsilon2
real espressopp::interaction::ReactionFieldGeneralizedTI::epsilon2 private
Definition at line 44 of file ReactionFieldGeneralizedTI.hpp.
kappa
real espressopp::interaction::ReactionFieldGeneralizedTI::kappa private
Definition at line 43 of file ReactionFieldGeneralizedTI.hpp.
lambdaTI
real espressopp::interaction::ReactionFieldGeneralizedTI::lambdaTI private
Definition at line 52 of file ReactionFieldGeneralizedTI.hpp.
pidsTI
std::set<longint> espressopp::interaction::ReactionFieldGeneralizedTI::pidsTI private
Definition at line 54 of file ReactionFieldGeneralizedTI.hpp.
prefactor
real espressopp::interaction::ReactionFieldGeneralizedTI::prefactor private
Definition at line 48 of file ReactionFieldGeneralizedTI.hpp.
rc
real espressopp::interaction::ReactionFieldGeneralizedTI::rc private
Definition at line 45 of file ReactionFieldGeneralizedTI.hpp.
rc2
real espressopp::interaction::ReactionFieldGeneralizedTI::rc2 private
Definition at line 46 of file ReactionFieldGeneralizedTI.hpp.
rc3
real espressopp::interaction::ReactionFieldGeneralizedTI::rc3 private
Definition at line 45 of file ReactionFieldGeneralizedTI.hpp.
shift
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >::shift protected inherited
Definition at line 150 of file Potential.hpp.
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/ReactionFieldGeneralizedTI.hpp
/home/espressopp/espressopp/src/interaction/ReactionFieldGeneralizedTI.cpp