ESPResSo++: espressopp::io::DumpH5MD Class Reference
espressopp::io::DumpH5MD Class Reference
Store particle data in Python buffers.
#include <DumpH5MD.hpp>
Public Member Functions
DumpH5MD (shared_ptr< System > system, bool is_adress)
~DumpH5MD ()
int get_NLocal ()
void set_store_position (bool _s)
bool get_store_position ()
void set_store_species (bool _s)
bool get_store_id ()
void set_store_id (bool _s)
bool get_store_species ()
void set_store_state (bool _s)
bool get_store_state ()
void set_store_velocity (bool _s)
bool get_store_velocity ()
void set_store_force (bool _s)
bool get_store_force ()
void set_store_charge (bool _s)
bool get_store_charge ()
void set_store_lambda (bool _s)
bool get_store_lambda ()
void set_store_res_id (bool _s)
bool get_store_res_id ()
void set_store_mass (bool _s)
bool get_store_mass ()
void clear_buffers ()
void update ()
PyObject * getPosition ()
PyObject * getId ()
PyObject * getImage ()
PyObject * getSpecies ()
PyObject * getState ()
PyObject * getVelocity ()
PyObject * getForce ()
PyObject * getMass ()
PyObject * getCharge ()
PyObject * getLambda ()
PyObject * getResId ()
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
Private Attributes
bool store_position
bool store_velocity
bool store_mass
bool store_id
bool store_force
bool store_species
bool store_state
bool store_charge
bool store_lambda
bool store_res_id
bool is_adress_
bool cleared
int NLocal
Py_buffer position
Py_buffer image
Py_buffer velocity
Py_buffer mass
Py_buffer id
Py_buffer force
Py_buffer species
Py_buffer state
Py_buffer charge
Py_buffer lambda
Py_buffer res_id
Detailed Description
Store particle data in Python buffers.
Definition at line 41 of file DumpH5MD.hpp.
Constructor & Destructor Documentation
DumpH5MD()
espressopp::io::DumpH5MD::DumpH5MD (shared_ptr< System > system, bool is_adress)
Definition at line 75 of file DumpH5MD.cpp.
References cleared, force, lambda, mass, NLocal, position, res_id, species, state, store_force, store_lambda, store_mass, store_position, store_res_id, store_species, store_state, store_velocity, and velocity.
~DumpH5MD()
espressopp::io::DumpH5MD::~DumpH5MD ()
Definition at line 96 of file DumpH5MD.cpp.
References clear_buffers().
Member Function Documentation
clear_buffers()
void espressopp::io::DumpH5MD::clear_buffers ()
Definition at line 100 of file DumpH5MD.cpp.
References charge, cleared, force, espressopp::io::free_pb(), image, lambda, mass, position, res_id, species, state, store_charge, store_force, store_lambda, store_mass, store_position, store_res_id, store_species, store_state, store_velocity, and velocity.
Referenced by get_store_mass(), registerPython(), update(), and ~DumpH5MD().
get_NLocal()
int espressopp::io::DumpH5MD::get_NLocal () inline
Definition at line 46 of file DumpH5MD.hpp.
References NLocal.
Referenced by registerPython().
get_store_charge()
bool espressopp::io::DumpH5MD::get_store_charge () inline
Definition at line 60 of file DumpH5MD.hpp.
References store_charge.
Referenced by registerPython().
get_store_force()
bool espressopp::io::DumpH5MD::get_store_force () inline
Definition at line 58 of file DumpH5MD.hpp.
References store_force.
Referenced by registerPython().
get_store_id()
bool espressopp::io::DumpH5MD::get_store_id () inline
Definition at line 50 of file DumpH5MD.hpp.
References store_id.
get_store_lambda()
bool espressopp::io::DumpH5MD::get_store_lambda () inline
Definition at line 62 of file DumpH5MD.hpp.
References store_lambda.
Referenced by registerPython().
get_store_mass()
bool espressopp::io::DumpH5MD::get_store_mass () inline
Definition at line 66 of file DumpH5MD.hpp.
References clear_buffers(), getCharge(), getForce(), getId(), getImage(), getLambda(), getMass(), getPosition(), getResId(), getSpecies(), getState(), getVelocity(), registerPython(), store_mass, and update().
Referenced by registerPython().
get_store_position()
bool espressopp::io::DumpH5MD::get_store_position () inline
Definition at line 48 of file DumpH5MD.hpp.
References store_position.
Referenced by registerPython().
get_store_res_id()
bool espressopp::io::DumpH5MD::get_store_res_id () inline
Definition at line 64 of file DumpH5MD.hpp.
References store_res_id.
Referenced by registerPython().
get_store_species()
bool espressopp::io::DumpH5MD::get_store_species () inline
Definition at line 52 of file DumpH5MD.hpp.
References store_species.
Referenced by registerPython().
get_store_state()
bool espressopp::io::DumpH5MD::get_store_state () inline
Definition at line 54 of file DumpH5MD.hpp.
References store_state.
Referenced by registerPython().
get_store_velocity()
bool espressopp::io::DumpH5MD::get_store_velocity () inline
Definition at line 56 of file DumpH5MD.hpp.
References store_velocity.
Referenced by registerPython().
getCharge()
PyObject * espressopp::io::DumpH5MD::getCharge ()
Definition at line 284 of file DumpH5MD.cpp.
References charge, and store_charge.
Referenced by get_store_mass(), and registerPython().
getForce()
PyObject * espressopp::io::DumpH5MD::getForce ()
Definition at line 270 of file DumpH5MD.cpp.
References force, and store_force.
Referenced by get_store_mass(), and registerPython().
getId()
PyObject * espressopp::io::DumpH5MD::getId ()
Definition at line 245 of file DumpH5MD.cpp.
Referenced by get_store_mass(), and registerPython().
getImage()
PyObject * espressopp::io::DumpH5MD::getImage ()
Definition at line 236 of file DumpH5MD.cpp.
References image, position, and store_position.
Referenced by get_store_mass(), and registerPython().
getLambda()
PyObject * espressopp::io::DumpH5MD::getLambda ()
Definition at line 291 of file DumpH5MD.cpp.
References lambda, and store_lambda.
Referenced by get_store_mass(), and registerPython().
getMass()
PyObject * espressopp::io::DumpH5MD::getMass ()
Definition at line 277 of file DumpH5MD.cpp.
References mass, and store_mass.
Referenced by get_store_mass(), and registerPython().
getPosition()
PyObject * espressopp::io::DumpH5MD::getPosition ()
Definition at line 230 of file DumpH5MD.cpp.
References position, and store_position.
Referenced by get_store_mass(), and registerPython().
getResId()
PyObject * espressopp::io::DumpH5MD::getResId ()
Definition at line 298 of file DumpH5MD.cpp.
References res_id, and store_res_id.
Referenced by get_store_mass(), and registerPython().
getSpecies()
PyObject * espressopp::io::DumpH5MD::getSpecies ()
Definition at line 251 of file DumpH5MD.cpp.
References species, and store_species.
Referenced by get_store_mass(), and registerPython().
getState()
PyObject * espressopp::io::DumpH5MD::getState ()
Definition at line 257 of file DumpH5MD.cpp.
References state, and store_state.
Referenced by get_store_mass(), and registerPython().
getSystem()
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::VerletList::_rebuildUsingBuffers(), espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::LatticeBoltzmann::assignMyLattice(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::PIAdressIntegrator::computeKineticEnergy(), espressopp::integrator::PIAdressIntegrator::computeMomentumDrift(), espressopp::integrator::PIAdressIntegrator::computePositionDrift(), espressopp::integrator::PIAdressIntegrator::computeRingEnergy(), espressopp::integrator::PIAdressIntegrator::computeRingEnergyRaw(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpXTCAdress::dump(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::io::DumpXYZ::DumpXYZ(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::VerletListTriple::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::VerletList::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
getSystem1()
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
getSystem2()
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
getSystemRef()
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::addForces(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::addForces(), espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerletRESPA::calcForces(), espressopp::integrator::VelocityVerlet::calcForces(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::PIAdressIntegrator::calcForcesF(), espressopp::integrator::PIAdressIntegrator::calcForcesM(), espressopp::integrator::PIAdressIntegrator::calcForcesS(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeCOM(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeEnergy(), espressopp::integrator::PIAdressIntegrator::computeKineticEnergy(), espressopp::integrator::PIAdressIntegrator::computeMomentumDrift(), espressopp::integrator::PIAdressIntegrator::computePositionDrift(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::integrator::PIAdressIntegrator::computeRingEnergy(), espressopp::integrator::PIAdressIntegrator::computeRingEnergyRaw(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::PIAdressIntegrator::distributeForces(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::FixedLocalTupleComListInteractionTemplate(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::VelocityVerletRESPA::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerlet::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::PIAdressIntegrator::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::PIAdressIntegrator::initializeSetup(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::VelocityVerletRESPA::integrate1(), espressopp::integrator::VelocityVerlet::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::VelocityVerletRESPA::integrate2(), espressopp::integrator::VelocityVerlet::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::PIAdressIntegrator::integrateModePos(), espressopp::integrator::Adress::integrateSlow(), espressopp::integrator::PIAdressIntegrator::integrateV1(), espressopp::integrator::PIAdressIntegrator::integrateV2(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::PIAdressIntegrator::OUintegrate(), espressopp::integrator::VelocityVerlet::printForces(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerlet::printPositions(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::VelocityVerletRESPA::run(), espressopp::integrator::PIAdressIntegrator::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::MinimizeEnergy::run(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::Rattle::saveOldPos(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::PIAdressIntegrator::setWeights(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostatOnGroup::thermalize(), espressopp::integrator::LangevinThermostatOnRadius::thermalize(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::integrator::PIAdressIntegrator::transForces(), espressopp::integrator::PIAdressIntegrator::transMom1(), espressopp::integrator::PIAdressIntegrator::transMom2(), espressopp::integrator::PIAdressIntegrator::transPos1(), espressopp::integrator::PIAdressIntegrator::transPos2(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), update(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::VelocityVerletRESPA::updateForces(), espressopp::integrator::VelocityVerlet::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::PIAdressIntegrator::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
getSystemRef1()
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
getSystemRef2()
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
getVelocity()
PyObject * espressopp::io::DumpH5MD::getVelocity ()
Definition at line 263 of file DumpH5MD.cpp.
References store_velocity, and velocity.
Referenced by get_store_mass(), and registerPython().
registerPython()
void espressopp::io::DumpH5MD::registerPython () static
Definition at line 305 of file DumpH5MD.cpp.
References clear_buffers(), get_NLocal(), get_store_charge(), get_store_force(), get_store_lambda(), get_store_mass(), get_store_position(), get_store_res_id(), get_store_species(), get_store_state(), get_store_velocity(), getCharge(), getForce(), getId(), getImage(), getLambda(), getMass(), getPosition(), getResId(), getSpecies(), getState(), getVelocity(), set_store_charge(), set_store_force(), set_store_lambda(), set_store_mass(), set_store_position(), set_store_res_id(), set_store_species(), set_store_state(), set_store_velocity(), and update().
Referenced by get_store_mass(), and espressopp::io::registerPython().
set_store_charge()
void espressopp::io::DumpH5MD::set_store_charge (bool _s) inline
Definition at line 59 of file DumpH5MD.hpp.
References store_charge.
Referenced by registerPython().
set_store_force()
void espressopp::io::DumpH5MD::set_store_force (bool _s) inline
Definition at line 57 of file DumpH5MD.hpp.
References store_force.
Referenced by registerPython().
set_store_id()
void espressopp::io::DumpH5MD::set_store_id (bool _s) inline
Definition at line 51 of file DumpH5MD.hpp.
References store_id.
set_store_lambda()
void espressopp::io::DumpH5MD::set_store_lambda (bool _s) inline
Definition at line 61 of file DumpH5MD.hpp.
References store_lambda.
Referenced by registerPython().
set_store_mass()
void espressopp::io::DumpH5MD::set_store_mass (bool _s) inline
Definition at line 65 of file DumpH5MD.hpp.
References store_mass.
Referenced by registerPython().
set_store_position()
void espressopp::io::DumpH5MD::set_store_position (bool _s) inline
Definition at line 47 of file DumpH5MD.hpp.
References store_position.
Referenced by registerPython().
set_store_res_id()
void espressopp::io::DumpH5MD::set_store_res_id (bool _s) inline
Definition at line 63 of file DumpH5MD.hpp.
References store_res_id.
Referenced by registerPython().
set_store_species()
void espressopp::io::DumpH5MD::set_store_species (bool _s) inline
Definition at line 49 of file DumpH5MD.hpp.
References store_species.
Referenced by registerPython().
set_store_state()
void espressopp::io::DumpH5MD::set_store_state (bool _s) inline
Definition at line 53 of file DumpH5MD.hpp.
References store_state.
Referenced by registerPython().
set_store_velocity()
void espressopp::io::DumpH5MD::set_store_velocity (bool _s) inline
Definition at line 55 of file DumpH5MD.hpp.
References store_velocity.
Referenced by registerPython().
update()
void espressopp::io::DumpH5MD::update ()
Definition at line 119 of file DumpH5MD.cpp.
References charge, clear_buffers(), cleared, force, espressopp::Particle::force(), espressopp::SystemAccess::getSystemRef(), id, espressopp::Particle::id(), image, espressopp::Particle::image(), is_adress_, espressopp::iterator::CellListIterator::isDone(), lambda, espressopp::Particle::lambda(), mass, espressopp::Particle::mass(), NLocal, position, espressopp::Particle::position(), espressopp::Particle::q(), res_id, espressopp::Particle::res_id(), species, state, espressopp::Particle::state(), espressopp::System::storage, store_charge, store_force, store_lambda, store_mass, store_position, store_res_id, store_species, store_state, store_velocity, espressopp::Particle::type(), velocity, and espressopp::Particle::velocity().
Referenced by get_store_mass(), and registerPython().
Member Data Documentation
charge
Py_buffer espressopp::io::DumpH5MD::charge private
Definition at line 101 of file DumpH5MD.hpp.
Referenced by clear_buffers(), getCharge(), and update().
cleared
bool espressopp::io::DumpH5MD::cleared private
Definition at line 91 of file DumpH5MD.hpp.
Referenced by clear_buffers(), DumpH5MD(), and update().
force
Py_buffer espressopp::io::DumpH5MD::force private
Definition at line 98 of file DumpH5MD.hpp.
Referenced by clear_buffers(), DumpH5MD(), getForce(), and update().
id
Py_buffer espressopp::io::DumpH5MD::id private
Definition at line 97 of file DumpH5MD.hpp.
Referenced by update().
image
Py_buffer espressopp::io::DumpH5MD::image private
Definition at line 94 of file DumpH5MD.hpp.
Referenced by clear_buffers(), getImage(), and update().
is_adress_
bool espressopp::io::DumpH5MD::is_adress_ private
Definition at line 90 of file DumpH5MD.hpp.
Referenced by update().
lambda
Py_buffer espressopp::io::DumpH5MD::lambda private
Definition at line 102 of file DumpH5MD.hpp.
Referenced by clear_buffers(), DumpH5MD(), getLambda(), and update().
mass
Py_buffer espressopp::io::DumpH5MD::mass private
Definition at line 96 of file DumpH5MD.hpp.
Referenced by clear_buffers(), DumpH5MD(), getMass(), and update().
NLocal
int espressopp::io::DumpH5MD::NLocal private
Definition at line 92 of file DumpH5MD.hpp.
Referenced by DumpH5MD(), get_NLocal(), and update().
position
Py_buffer espressopp::io::DumpH5MD::position private
Definition at line 93 of file DumpH5MD.hpp.
Referenced by clear_buffers(), DumpH5MD(), getImage(), getPosition(), and update().
res_id
Py_buffer espressopp::io::DumpH5MD::res_id private
Definition at line 103 of file DumpH5MD.hpp.
Referenced by clear_buffers(), DumpH5MD(), getResId(), and update().
species
Py_buffer espressopp::io::DumpH5MD::species private
Definition at line 99 of file DumpH5MD.hpp.
Referenced by clear_buffers(), DumpH5MD(), getSpecies(), and update().
state
Py_buffer espressopp::io::DumpH5MD::state private
Definition at line 100 of file DumpH5MD.hpp.
Referenced by clear_buffers(), DumpH5MD(), getState(), and update().
store_charge
bool espressopp::io::DumpH5MD::store_charge private
Definition at line 87 of file DumpH5MD.hpp.
Referenced by clear_buffers(), get_store_charge(), getCharge(), set_store_charge(), and update().
store_force
bool espressopp::io::DumpH5MD::store_force private
Definition at line 86 of file DumpH5MD.hpp.
Referenced by clear_buffers(), DumpH5MD(), get_store_force(), getForce(), set_store_force(), and update().
store_id
bool espressopp::io::DumpH5MD::store_id private
Definition at line 86 of file DumpH5MD.hpp.
Referenced by get_store_id(), and set_store_id().
store_lambda
bool espressopp::io::DumpH5MD::store_lambda private
Definition at line 87 of file DumpH5MD.hpp.
Referenced by clear_buffers(), DumpH5MD(), get_store_lambda(), getLambda(), set_store_lambda(), and update().
store_mass
bool espressopp::io::DumpH5MD::store_mass private
Definition at line 86 of file DumpH5MD.hpp.
Referenced by clear_buffers(), DumpH5MD(), get_store_mass(), getMass(), set_store_mass(), and update().
store_position
bool espressopp::io::DumpH5MD::store_position private
Definition at line 86 of file DumpH5MD.hpp.
Referenced by clear_buffers(), DumpH5MD(), get_store_position(), getImage(), getPosition(), set_store_position(), and update().
store_res_id
bool espressopp::io::DumpH5MD::store_res_id private
Definition at line 88 of file DumpH5MD.hpp.
Referenced by clear_buffers(), DumpH5MD(), get_store_res_id(), getResId(), set_store_res_id(), and update().
store_species
bool espressopp::io::DumpH5MD::store_species private
Definition at line 87 of file DumpH5MD.hpp.
Referenced by clear_buffers(), DumpH5MD(), get_store_species(), getSpecies(), set_store_species(), and update().
store_state
bool espressopp::io::DumpH5MD::store_state private
Definition at line 87 of file DumpH5MD.hpp.
Referenced by clear_buffers(), DumpH5MD(), get_store_state(), getState(), set_store_state(), and update().
store_velocity
bool espressopp::io::DumpH5MD::store_velocity private
Definition at line 86 of file DumpH5MD.hpp.
Referenced by clear_buffers(), DumpH5MD(), get_store_velocity(), getVelocity(), set_store_velocity(), and update().
velocity
Py_buffer espressopp::io::DumpH5MD::velocity private
Definition at line 95 of file DumpH5MD.hpp.
Referenced by clear_buffers(), DumpH5MD(), getVelocity(), and update().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/io/DumpH5MD.hpp
/home/espressopp/espressopp/src/io/DumpH5MD.cpp