ESPResSo++: espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential > Class Template Reference
espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential > Class Template Reference
#include <VerletListPIadressNoDriftInteractionTemplate.hpp>
Public Member Functions
VerletListPIadressNoDriftInteractionTemplate (shared_ptr< VerletListAdress > _verletList, shared_ptr< FixedTupleListAdress > _fixedtupleList, int _ntrotter, bool _speedup)
void setVerletList (shared_ptr< VerletListAdress > _verletList)
shared_ptr< VerletListAdress > getVerletList ()
void setFixedTupleList (shared_ptr< FixedTupleListAdress > _fixedtupleList)
shared_ptr< FixedTupleListAdress > getFixedTupleList ()
void setNTrotter (int _ntrotter)
int getNTrotter ()
void setSpeedup (bool _speedup)
bool getSpeedup ()
void setPotential (int type1, int type2, const Potential &potential)
Potential & getPotential (int type1, int type2)
virtual void addForces ()
virtual real computeEnergy ()
virtual real computeEnergyDeriv ()
virtual real computeEnergyAA ()
virtual real computeEnergyCG ()
virtual real computeEnergyAA (int atomtype)
virtual real computeEnergyCG (int atomtype)
virtual void computeVirialX (std::vector< real > &p_xx_total, int bins)
virtual real computeVirial ()
virtual void computeVirialTensor (Tensor &w)
virtual void computeVirialTensor (Tensor &w, real z)
virtual void computeVirialTensor (Tensor *w, int n)
virtual real getMaxCutoff ()
This method returns the maximal cutoff defined for one type pair.
virtual int bondType ()
Static Public Member Functions
static void registerPython ()
Protected Types
typedef _Potential Potential
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Protected Attributes
int ntypes
shared_ptr< VerletListAdress > verletList
shared_ptr< FixedTupleListAdress > fixedtupleList
esutil::Array2D< Potential, esutil::enlarge > potentialArray
int ntrotter
bool speedup
Detailed Description
template<typename _Potential>
class espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >
Definition at line 40 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
Member Typedef Documentation
Potential
template<typename _Potential > typedef _Potential espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::Potential protected
Definition at line 43 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
Constructor & Destructor Documentation
VerletListPIadressNoDriftInteractionTemplate()
template<typename _Potential > espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::VerletListPIadressNoDriftInteractionTemplate (shared_ptr< VerletListAdress > _verletList, shared_ptr< FixedTupleListAdress > _fixedtupleList, int _ntrotter, bool _speedup) inline
Definition at line 47 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::ntypes, and espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::potentialArray.
Member Function Documentation
addForces()
template<typename _Potential > void espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::addForces () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 137 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::fixedtupleList, espressopp::Particle::force(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getPotential(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::ntrotter, espressopp::Particle::pib(), espressopp::Particle::position(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::speedup, espressopp::Particle::type(), and espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::verletList.
Referenced by espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getPotential().
bondType()
template<typename _Potential > virtual int espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::bondType () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 118 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
References espressopp::interaction::Nonbonded.
computeEnergy()
template<typename _Potential > real espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergy () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 280 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergyDeriv(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::fixedtupleList, espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getPotential(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getVerletList(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::ntrotter, espressopp::Particle::pib(), espressopp::Particle::position(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::speedup, espressopp::Particle::type(), and espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::verletList.
Referenced by espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::addForces(), and espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getPotential().
computeEnergyAA() [1/2]
template<typename _Potential > real espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergyAA () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 421 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::fixedtupleList, espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getPotential(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getVerletList(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::ntrotter, espressopp::Particle::pib(), espressopp::Particle::position(), espressopp::Particle::type(), and espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::verletList.
Referenced by espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergyDeriv(), and espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getPotential().
computeEnergyAA() [2/2]
template<typename _Potential > real espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergyAA (int atomtype) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 547 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergyCG(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::fixedtupleList, espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getPotential(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getVerletList(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::ntrotter, espressopp::Particle::pib(), espressopp::Particle::position(), espressopp::Particle::type(), and espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::verletList.
computeEnergyCG() [1/2]
template<typename _Potential > real espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergyCG () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 693 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::fixedtupleList, espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getPotential(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getVerletList(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::ntrotter, espressopp::Particle::pib(), espressopp::Particle::position(), espressopp::Particle::type(), and espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::verletList.
Referenced by espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergyAA(), and espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getPotential().
computeEnergyCG() [2/2]
template<typename _Potential > real espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergyCG (int atomtype) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 819 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeVirialX(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::fixedtupleList, espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getPotential(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getVerletList(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::ntrotter, espressopp::Particle::pib(), espressopp::Particle::position(), espressopp::Particle::type(), and espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::verletList.
computeEnergyDeriv()
template<typename _Potential > real espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergyDeriv () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 412 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergyAA().
Referenced by espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergy(), and espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getPotential().
computeVirial()
template<typename _Potential > real espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeVirial () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 972 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::fixedtupleList, espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getPotential(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), mpiWorld, espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::ntrotter, espressopp::Particle::pib(), espressopp::Particle::position(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::speedup, espressopp::Particle::type(), and espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::verletList.
Referenced by espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeVirialX(), and espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getPotential().
computeVirialTensor() [1/3]
template<typename _Potential > void espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeVirialTensor (Tensor & w) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 1123 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeVirialTensor(), and espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getPotential().
computeVirialTensor() [2/3]
template<typename _Potential > void espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeVirialTensor (Tensor & w, real z) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 1130 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeVirialTensor().
computeVirialTensor() [3/3]
template<typename _Potential > void espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeVirialTensor (Tensor * w, int n) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 1137 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getMaxCutoff().
computeVirialX()
template<typename _Potential > void espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeVirialX (std::vector< real > & p_xx_total, int bins) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 964 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeVirial().
Referenced by espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergyCG(), and espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getPotential().
getFixedTupleList()
template<typename _Potential > shared_ptr< FixedTupleListAdress > espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getFixedTupleList () inline
Definition at line 68 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::fixedtupleList.
getMaxCutoff()
template<typename _Potential > real espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getMaxCutoff () inline virtual
This method returns the maximal cutoff defined for one type pair.
Implements espressopp::interaction::Interaction.
Definition at line 1145 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getPotential(), and espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::ntypes.
Referenced by espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeVirialTensor(), and espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getPotential().
getNTrotter()
template<typename _Potential > int espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getNTrotter () inline
Definition at line 77 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::ntrotter.
getPotential()
template<typename _Potential > Potential& espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getPotential (int type1, int type2) inline
Definition at line 101 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::addForces(), espressopp::esutil::Array2D< T, outlier_mode >::at(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergyAA(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergyCG(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergyDeriv(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeVirialX(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getMaxCutoff(), and espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::potentialArray.
Referenced by espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergyAA(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergyCG(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeVirial(), and espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getMaxCutoff().
getSpeedup()
template<typename _Potential > bool espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getSpeedup () inline
Definition at line 86 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::speedup.
getVerletList()
template<typename _Potential > shared_ptr<VerletListAdress> espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getVerletList () inline
Definition at line 59 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::verletList.
Referenced by espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergyAA(), and espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergyCG().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Interaction::LOG4ESPP_DECL_LOGGER (theLogger) static protected inherited
Logger.
Referenced by espressopp::interaction::Interaction::~Interaction().
registerPython()
void espressopp::interaction::Interaction::registerPython () static inherited
Definition at line 36 of file Interaction.cpp.
References espressopp::interaction::Interaction::bondType(), espressopp::interaction::Interaction::computeEnergy(), espressopp::interaction::Interaction::computeEnergyAA(), espressopp::interaction::Interaction::computeEnergyCG(), espressopp::interaction::Interaction::computeEnergyDeriv(), and espressopp::interaction::Interaction::computeVirial().
Referenced by espressopp::interaction::registerPython(), and espressopp::interaction::Interaction::~Interaction().
setFixedTupleList()
template<typename _Potential > void espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::setFixedTupleList (shared_ptr< FixedTupleListAdress > _fixedtupleList) inline
Definition at line 64 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::fixedtupleList.
setNTrotter()
template<typename _Potential > void espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::setNTrotter (int _ntrotter) inline
Definition at line 73 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::ntrotter.
setPotential()
template<typename _Potential > void espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::setPotential (int type1, int type2, const Potential & potential) inline
Definition at line 91 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::ntypes, and espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::potentialArray.
setSpeedup()
template<typename _Potential > void espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::setSpeedup (bool _speedup) inline
Definition at line 82 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::speedup.
setVerletList()
template<typename _Potential > void espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::setVerletList (shared_ptr< VerletListAdress > _verletList) inline
Definition at line 55 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::verletList.
Member Data Documentation
fixedtupleList
template<typename _Potential > shared_ptr<FixedTupleListAdress> espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::fixedtupleList protected
Definition at line 125 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergyAA(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergyCG(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getFixedTupleList(), and espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::setFixedTupleList().
ntrotter
template<typename _Potential > int espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::ntrotter protected
Definition at line 128 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergyAA(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergyCG(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getNTrotter(), and espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::setNTrotter().
ntypes
template<typename _Potential > int espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::ntypes protected
Definition at line 123 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getMaxCutoff(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::setPotential(), and espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::VerletListPIadressNoDriftInteractionTemplate().
potentialArray
template<typename _Potential > esutil::Array2D<Potential, esutil::enlarge> espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::potentialArray protected
Definition at line 126 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getPotential(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::setPotential(), and espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::VerletListPIadressNoDriftInteractionTemplate().
speedup
template<typename _Potential > bool espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::speedup protected
Definition at line 129 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getSpeedup(), and espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::setSpeedup().
verletList
template<typename _Potential > shared_ptr<VerletListAdress> espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::verletList protected
Definition at line 124 of file VerletListPIadressNoDriftInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergyAA(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergyCG(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getVerletList(), and espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::setVerletList().
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/interaction/VerletListPIadressNoDriftInteractionTemplate.hpp