ESPResSo++: espressopp::interaction::StillingerWeberPairTerm Class Reference
espressopp::interaction::StillingerWeberPairTerm Class Reference
This class provides methods to compute forces and energies of 2 body term of Stillinger-Weber potential.
#include <StillingerWeberPairTerm.hpp>
Public Member Functions
StillingerWeberPairTerm ()
StillingerWeberPairTerm (real _A, real _B, real _p, real _q, real _epsilon, real _sigma, real _cutoff)
virtual ~StillingerWeberPairTerm ()
void setA (real _A)
real getA () const
void setB (real _B)
real getB () const
void setP (real _p)
real getP () const
void setQ (real _q)
real getQ () const
void setEpsilon (real _epsilon)
real getEpsilon () const
void setSigma (real _sigma)
real getSigma () const
void preset ()
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &r12, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
real _computeEnergyDeriv (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
StillingerWeberPairTerm * derived_this ()
const StillingerWeberPairTerm * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
Private Attributes
real A
real B
real p
real q
real epsilon
real sigma
real epsilonA
Detailed Description
This class provides methods to compute forces and energies of 2 body term of Stillinger-Weber potential.
Definition at line 42 of file StillingerWeberPairTerm.hpp.
Constructor & Destructor Documentation
StillingerWeberPairTerm() [1/2]
espressopp::interaction::StillingerWeberPairTerm::StillingerWeberPairTerm () inline
Definition at line 53 of file StillingerWeberPairTerm.hpp.
References espressopp::infinity, preset(), espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::setCutoff(), and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::setShift().
StillingerWeberPairTerm() [2/2]
espressopp::interaction::StillingerWeberPairTerm::StillingerWeberPairTerm (real _A, real _B, real _p, real _q, real _epsilon, real _sigma, real _cutoff) inline
Definition at line 59 of file StillingerWeberPairTerm.hpp.
References preset(), espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::setCutoff(), and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::setShift().
~StillingerWeberPairTerm()
virtual espressopp::interaction::StillingerWeberPairTerm::~StillingerWeberPairTerm () inline virtual
Definition at line 67 of file StillingerWeberPairTerm.hpp.
Member Function Documentation
_computeEnergy() [1/4]
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::_computeEnergy (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 242 of file Potential.hpp.
References espressopp::Particle::position().
_computeEnergy() [2/4]
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::_computeEnergy (const Real3D & dist) const inline inherited
Definition at line 257 of file Potential.hpp.
References espressopp::Real3D::sqr().
_computeEnergy() [3/4]
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::_computeEnergy (real dist) const inline inherited
Definition at line 264 of file Potential.hpp.
_computeEnergy() [4/4]
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 250 of file Potential.hpp.
_computeEnergyDeriv()
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::_computeEnergyDeriv (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 285 of file Potential.hpp.
_computeEnergySqr()
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::_computeEnergySqr (real distSqr) const inline inherited
Definition at line 271 of file Potential.hpp.
References LOG4ESPP_TRACE.
_computeEnergySqrRaw()
real espressopp::interaction::StillingerWeberPairTerm::_computeEnergySqrRaw (real distSqr) const inline
Definition at line 103 of file StillingerWeberPairTerm.hpp.
References espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::getCutoff(), and sigma.
_computeForce() [1/3]
bool espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const inline inherited
Definition at line 313 of file Potential.hpp.
References espressopp::Particle::position().
_computeForce() [2/3]
bool espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::_computeForce (Real3D & force, const Real3D & dist) const inline inherited
Definition at line 328 of file Potential.hpp.
References espressopp::Real3D::sqr().
_computeForce() [3/3]
bool espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 321 of file Potential.hpp.
_computeForceRaw()
bool espressopp::interaction::StillingerWeberPairTerm::_computeForceRaw (Real3D & force, const Real3D & r12, real distSqr) const inline
Definition at line 111 of file StillingerWeberPairTerm.hpp.
References espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::getCutoff(), and sigma.
computeEnergy() [1/3]
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::computeEnergy (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 213 of file Potential.hpp.
References espressopp::Particle::position().
computeEnergy() [2/3]
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::computeEnergy (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 221 of file Potential.hpp.
References espressopp::Real3D::sqr().
computeEnergy() [3/3]
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::computeEnergy (real dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 228 of file Potential.hpp.
computeEnergySqr()
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::computeEnergySqr (real distsqr) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 235 of file Potential.hpp.
computeForce() [1/2]
Real3D espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::computeForce (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 295 of file Potential.hpp.
References espressopp::Particle::position().
computeForce() [2/2]
Real3D espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::computeForce (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 303 of file Potential.hpp.
derived_this() [1/2]
StillingerWeberPairTerm * espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::derived_this () inline protected inherited
Definition at line 123 of file Potential.hpp.
derived_this() [2/2]
const StillingerWeberPairTerm * espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::derived_this () const inline protected inherited
Definition at line 127 of file Potential.hpp.
getA()
real espressopp::interaction::StillingerWeberPairTerm::getA () const inline
Definition at line 73 of file StillingerWeberPairTerm.hpp.
References A.
Referenced by registerPython().
getB()
real espressopp::interaction::StillingerWeberPairTerm::getB () const inline
Definition at line 76 of file StillingerWeberPairTerm.hpp.
References B.
Referenced by registerPython().
getCutoff()
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 171 of file Potential.hpp.
Referenced by _computeEnergySqrRaw(), and _computeForceRaw().
getEpsilon()
real espressopp::interaction::StillingerWeberPairTerm::getEpsilon () const inline
Definition at line 90 of file StillingerWeberPairTerm.hpp.
References epsilon.
Referenced by registerPython().
getP()
real espressopp::interaction::StillingerWeberPairTerm::getP () const inline
Definition at line 79 of file StillingerWeberPairTerm.hpp.
References p.
Referenced by registerPython().
getQ()
real espressopp::interaction::StillingerWeberPairTerm::getQ () const inline
Definition at line 82 of file StillingerWeberPairTerm.hpp.
References q.
Referenced by registerPython().
getShift()
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::getShift () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 186 of file Potential.hpp.
getSigma()
real espressopp::interaction::StillingerWeberPairTerm::getSigma () const inline
Definition at line 96 of file StillingerWeberPairTerm.hpp.
References sigma.
Referenced by registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
Referenced by espressopp::interaction::Potential::~Potential().
preset()
void espressopp::interaction::StillingerWeberPairTerm::preset () inline
Definition at line 99 of file StillingerWeberPairTerm.hpp.
References A.
Referenced by setA(), setEpsilon(), setSigma(), and StillingerWeberPairTerm().
registerPython()
void espressopp::interaction::StillingerWeberPairTerm::registerPython () static
Definition at line 45 of file StillingerWeberPairTerm.cpp.
References getA(), getB(), getEpsilon(), getP(), getQ(), getSigma(), setA(), setB(), setEpsilon(), setP(), setQ(), and setSigma().
Referenced by espressopp::interaction::registerPython().
setA()
void espressopp::interaction::StillingerWeberPairTerm::setA (real _A) inline
Definition at line 69 of file StillingerWeberPairTerm.hpp.
References preset().
Referenced by registerPython().
setAutoShift()
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::setAutoShift () inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 192 of file Potential.hpp.
References espressopp::infinity, and LOG4ESPP_INFO.
setB()
void espressopp::interaction::StillingerWeberPairTerm::setB (real _B) inline
Definition at line 75 of file StillingerWeberPairTerm.hpp.
Referenced by registerPython().
setCutoff()
void espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 162 of file Potential.hpp.
References LOG4ESPP_INFO.
Referenced by StillingerWeberPairTerm().
setEpsilon()
void espressopp::interaction::StillingerWeberPairTerm::setEpsilon (real _epsilon) inline
Definition at line 85 of file StillingerWeberPairTerm.hpp.
References preset().
Referenced by registerPython().
setP()
void espressopp::interaction::StillingerWeberPairTerm::setP (real _p) inline
Definition at line 78 of file StillingerWeberPairTerm.hpp.
Referenced by registerPython().
setQ()
void espressopp::interaction::StillingerWeberPairTerm::setQ (real _q) inline
Definition at line 81 of file StillingerWeberPairTerm.hpp.
Referenced by registerPython().
setShift()
void espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::setShift (real _shift) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 177 of file Potential.hpp.
References LOG4ESPP_INFO.
Referenced by StillingerWeberPairTerm().
setSigma()
void espressopp::interaction::StillingerWeberPairTerm::setSigma (real _sigma) inline
Definition at line 92 of file StillingerWeberPairTerm.hpp.
References preset().
Referenced by registerPython().
updateAutoShift()
void espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::updateAutoShift () inline inherited
Definition at line 205 of file Potential.hpp.
Member Data Documentation
A
real espressopp::interaction::StillingerWeberPairTerm::A private
Definition at line 45 of file StillingerWeberPairTerm.hpp.
Referenced by getA(), and preset().
autoShift
bool espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::autoShift protected inherited
Definition at line 121 of file Potential.hpp.
B
real espressopp::interaction::StillingerWeberPairTerm::B private
Definition at line 45 of file StillingerWeberPairTerm.hpp.
Referenced by getB().
cutoff
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::cutoff protected inherited
Definition at line 118 of file Potential.hpp.
cutoffSqr
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::cutoffSqr protected inherited
Definition at line 119 of file Potential.hpp.
epsilon
real espressopp::interaction::StillingerWeberPairTerm::epsilon private
Definition at line 46 of file StillingerWeberPairTerm.hpp.
Referenced by getEpsilon().
epsilonA
real espressopp::interaction::StillingerWeberPairTerm::epsilonA private
Definition at line 49 of file StillingerWeberPairTerm.hpp.
p
real espressopp::interaction::StillingerWeberPairTerm::p private
Definition at line 45 of file StillingerWeberPairTerm.hpp.
Referenced by getP().
q
real espressopp::interaction::StillingerWeberPairTerm::q private
Definition at line 45 of file StillingerWeberPairTerm.hpp.
Referenced by getQ().
shift
real espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::shift protected inherited
Definition at line 120 of file Potential.hpp.
sigma
real espressopp::interaction::StillingerWeberPairTerm::sigma private
Definition at line 47 of file StillingerWeberPairTerm.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), and getSigma().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/StillingerWeberPairTerm.hpp
/home/espressopp/espressopp/src/interaction/StillingerWeberPairTerm.cpp