ESPResSo++: espressopp::interaction::LennardJonesGeneric Class Reference
espressopp::interaction::LennardJonesGeneric Class Reference
This class provides methods to compute forces and energies of the a generic Lennard Jones potential with arbitrary integers a and b.
#include <LennardJonesGeneric.hpp>
Public Member Functions
LennardJonesGeneric ()
LennardJonesGeneric (real _epsilon, real _sigma, int _a, int _b, real _cutoff)
LennardJonesGeneric (real _epsilon, real _sigma, int _a, int _b, real _cutoff, real _shift)
virtual ~LennardJonesGeneric ()
void preset ()
void setEpsilon (real _epsilon)
real getEpsilon () const
void setSigma (real _sigma)
real getSigma () const
void setA (int _a)
int getA () const
void setB (int _b)
int getB () const
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &dist, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
LennardJonesGeneric * derived_this ()
const LennardJonesGeneric * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
Private Attributes
real epsilon
real sigma
int a
int b
real ff1
real ff2
Detailed Description
This class provides methods to compute forces and energies of the a generic Lennard Jones potential with arbitrary integers a and b.
Definition at line 40 of file LennardJonesGeneric.hpp.
Constructor & Destructor Documentation
espressopp::interaction::LennardJonesGeneric::LennardJonesGeneric () [inline]
Definition at line 50 of file LennardJonesGeneric.hpp.
References espressopp::infinity, LOG4ESPP_INFO, preset(), espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::setCutoff(), and espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::setShift().
espressopp::interaction::LennardJonesGeneric::LennardJonesGeneric (real _epsilon, real _sigma, int _a, int _b, real _cutoff) [inline]
Definition at line 58 of file LennardJonesGeneric.hpp.
References espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::autoShift, LOG4ESPP_INFO, preset(), espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::setAutoShift(), and espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::setCutoff().
espressopp::interaction::LennardJonesGeneric::LennardJonesGeneric (real _epsilon, real _sigma, int _a, int _b, real _cutoff, real _shift) [inline]
Definition at line 68 of file LennardJonesGeneric.hpp.
References LOG4ESPP_INFO, preset(), espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::setCutoff(), and espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::setShift().
virtual espressopp::interaction::LennardJonesGeneric::~LennardJonesGeneric () [inline, virtual]
Definition at line 77 of file LennardJonesGeneric.hpp.
Member Function Documentation
real espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::_computeEnergy (const Particle & p1, const Particle & p2) const [inherited]
real espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::_computeEnergy (const Real3D & dist) const [inherited]
real espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::_computeEnergy (real dist) const [inherited]
real espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const [inherited]
real espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::_computeEnergySqr (real distSqr) const [inherited]
real espressopp::interaction::LennardJonesGeneric::_computeEnergySqrRaw (real distSqr) const [inline]
Definition at line 118 of file LennardJonesGeneric.hpp.
References a, b, epsilon, and sigma.
bool espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const [inherited]
bool espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::_computeForce (Real3D & force, const Real3D & dist) const [inherited]
bool espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const [inherited]
bool espressopp::interaction::LennardJonesGeneric::_computeForceRaw (Real3D & force, const Real3D & dist, real distSqr) const [inline]
Definition at line 127 of file LennardJonesGeneric.hpp.
References a, b, epsilon, ff1, and ff2.
virtual real espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::computeEnergy (const Particle & p1, const Particle & p2) const [virtual, inherited]
Implements espressopp::interaction::Potential.
virtual real espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::computeEnergy (const Real3D & dist) const [virtual, inherited]
Implements espressopp::interaction::Potential.
virtual real espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::computeEnergy (real dist) const [virtual, inherited]
Implements espressopp::interaction::Potential.
virtual real espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::computeEnergySqr (real distsqr) const [virtual, inherited]
Implements espressopp::interaction::Potential.
virtual Real3D espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::computeForce (const Particle & p1, const Particle & p2) const [virtual, inherited]
Implements espressopp::interaction::Potential.
virtual Real3D espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::computeForce (const Real3D & dist) const [virtual, inherited]
Implements espressopp::interaction::Potential.
LennardJonesGeneric * espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::derived_this () [inline, protected, inherited]
Definition at line 121 of file Potential.hpp.
const LennardJonesGeneric * espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::derived_this () const [inline, protected, inherited]
Definition at line 125 of file Potential.hpp.
int espressopp::interaction::LennardJonesGeneric::getA () const [inline]
Definition at line 108 of file LennardJonesGeneric.hpp.
References a.
Referenced by espressopp::interaction::LennardJonesGeneric_pickle::getinitargs(), and registerPython().
int espressopp::interaction::LennardJonesGeneric::getB () const [inline]
Definition at line 116 of file LennardJonesGeneric.hpp.
References b.
Referenced by espressopp::interaction::LennardJonesGeneric_pickle::getinitargs(), and registerPython().
virtual real espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::getCutoff () const [virtual, inherited]
Implements espressopp::interaction::Potential.
real espressopp::interaction::LennardJonesGeneric::getEpsilon () const [inline]
Definition at line 92 of file LennardJonesGeneric.hpp.
References epsilon.
Referenced by espressopp::interaction::LennardJonesGeneric_pickle::getinitargs(), and registerPython().
virtual real espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::getShift () const [virtual, inherited]
Implements espressopp::interaction::Potential.
real espressopp::interaction::LennardJonesGeneric::getSigma () const [inline]
Definition at line 100 of file LennardJonesGeneric.hpp.
References sigma.
Referenced by espressopp::interaction::LennardJonesGeneric_pickle::getinitargs(), and registerPython().
static espressopp::interaction::LennardJonesGeneric::LOG4ESPP_DECL_LOGGER (theLogger) [static]
Reimplemented from espressopp::interaction::Potential.
void espressopp::interaction::LennardJonesGeneric::preset () [inline]
Definition at line 79 of file LennardJonesGeneric.hpp.
References a, b, ff1, ff2, and sigma.
Referenced by LennardJonesGeneric(), setA(), setB(), setEpsilon(), and setSigma().
void espressopp::interaction::LennardJonesGeneric::registerPython () [static]
Reimplemented from espressopp::interaction::Potential.
Definition at line 54 of file LennardJonesGeneric.cpp.
References getA(), getB(), getEpsilon(), getSigma(), setA(), setB(), setEpsilon(), and setSigma().
Referenced by espressopp::interaction::registerPython().
void espressopp::interaction::LennardJonesGeneric::setA (int _a) [inline]
Definition at line 102 of file LennardJonesGeneric.hpp.
References a, LOG4ESPP_INFO, preset(), and espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::updateAutoShift().
Referenced by registerPython().
virtual real espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::setAutoShift () [virtual, inherited]
Implements espressopp::interaction::Potential.
Referenced by LennardJonesGeneric().
void espressopp::interaction::LennardJonesGeneric::setB (int _b) [inline]
Definition at line 110 of file LennardJonesGeneric.hpp.
References b, LOG4ESPP_INFO, preset(), and espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::updateAutoShift().
Referenced by registerPython().
virtual void espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::setCutoff (real _cutoff) [virtual, inherited]
Implements espressopp::interaction::Potential.
Referenced by LennardJonesGeneric().
void espressopp::interaction::LennardJonesGeneric::setEpsilon (real _epsilon) [inline]
Definition at line 85 of file LennardJonesGeneric.hpp.
References epsilon, LOG4ESPP_INFO, preset(), and espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::updateAutoShift().
Referenced by registerPython().
virtual void espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::setShift (real _shift) [virtual, inherited]
Implements espressopp::interaction::Potential.
Referenced by LennardJonesGeneric().
void espressopp::interaction::LennardJonesGeneric::setSigma (real _sigma) [inline]
Definition at line 94 of file LennardJonesGeneric.hpp.
References LOG4ESPP_INFO, preset(), sigma, and espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::updateAutoShift().
Referenced by registerPython().
void espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::updateAutoShift () [inherited]
Referenced by setA(), setB(), setEpsilon(), and setSigma().
Member Data Documentation
int espressopp::interaction::LennardJonesGeneric::a [private]
Definition at line 44 of file LennardJonesGeneric.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), getA(), preset(), and setA().
bool espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::autoShift [protected, inherited]
Definition at line 119 of file Potential.hpp.
Referenced by LennardJonesGeneric().
int espressopp::interaction::LennardJonesGeneric::b [private]
Definition at line 44 of file LennardJonesGeneric.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), getB(), preset(), and setB().
real espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::cutoff [protected, inherited]
Definition at line 116 of file Potential.hpp.
real espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::cutoffSqr [protected, inherited]
Definition at line 117 of file Potential.hpp.
real espressopp::interaction::LennardJonesGeneric::epsilon [private]
Definition at line 42 of file LennardJonesGeneric.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), getEpsilon(), and setEpsilon().
real espressopp::interaction::LennardJonesGeneric::ff1 [private]
Definition at line 45 of file LennardJonesGeneric.hpp.
Referenced by _computeForceRaw(), and preset().
real espressopp::interaction::LennardJonesGeneric::ff2 [private]
Definition at line 45 of file LennardJonesGeneric.hpp.
Referenced by _computeForceRaw(), and preset().
real espressopp::interaction::PotentialTemplate< LennardJonesGeneric >::shift [protected, inherited]
Definition at line 118 of file Potential.hpp.
real espressopp::interaction::LennardJonesGeneric::sigma [private]
Definition at line 43 of file LennardJonesGeneric.hpp.
Referenced by _computeEnergySqrRaw(), getSigma(), preset(), and setSigma().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/interaction/LennardJonesGeneric.hpp
/home/travis/build/espressopp/espressopp/src/interaction/LennardJonesGeneric.cpp