ESPResSo++: espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential > Class Template Reference
espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential > Class Template Reference
#include <CellListAllPairsInteractionTemplate.hpp>
Public Member Functions
CellListAllPairsInteractionTemplate (shared_ptr< storage::Storage > _storage)
void setPotential (int type1, int type2, const Potential &potential)
Potential & getPotential (int type1, int type2)
virtual void addForces ()
virtual real computeEnergy ()
virtual real computeEnergyDeriv ()
virtual real computeEnergyAA ()
virtual real computeEnergyCG ()
virtual void computeVirialX (std::vector< real > &p_xx_total, int bins)
virtual real computeVirial ()
virtual void computeVirialTensor (Tensor &wij)
virtual void computeVirialTensor (Tensor &w, real z)
virtual void computeVirialTensor (Tensor *w, int n)
virtual real getMaxCutoff ()
This method returns the maximal cutoff defined for one type pair.
virtual int bondType ()
Static Public Member Functions
static void registerPython ()
Protected Types
typedef _Potential Potential
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Protected Attributes
int ntypes
esutil::Array2D< Potential,
esutil::enlarge > potentialArray
shared_ptr< storage::Storage > storage
Detailed Description
template<typename _Potential>
class espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >
Definition at line 37 of file CellListAllPairsInteractionTemplate.hpp.
Member Typedef Documentation
template<typename _Potential > typedef _Potential espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::Potential protected
Definition at line 40 of file CellListAllPairsInteractionTemplate.hpp.
Constructor & Destructor Documentation
template<typename _Potential > espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::CellListAllPairsInteractionTemplate (shared_ptr< storage::Storage > _storage) inline
Definition at line 43 of file CellListAllPairsInteractionTemplate.hpp.
References espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::ntypes, and espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::potentialArray.
Member Function Documentation
template<typename _Potential > void espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::addForces () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 91 of file CellListAllPairsInteractionTemplate.hpp.
References espressopp::Particle::force(), espressopp::iterator::CellListAllPairsIterator::isValid(), LOG4ESPP_INFO, and espressopp::Particle::type().
template<typename _Potential > virtual int espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::bondType () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 78 of file CellListAllPairsInteractionTemplate.hpp.
References espressopp::interaction::Nonbonded.
template<typename _Potential > real espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::computeEnergy () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 109 of file CellListAllPairsInteractionTemplate.hpp.
References espressopp::iterator::CellListAllPairsIterator::isValid(), LOG4ESPP_INFO, mpiWorld, and espressopp::Particle::type().
template<typename _Potential > real espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::computeEnergyAA () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 135 of file CellListAllPairsInteractionTemplate.hpp.
template<typename _Potential > real espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::computeEnergyCG () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 142 of file CellListAllPairsInteractionTemplate.hpp.
template<typename _Potential > real espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::computeEnergyDeriv () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 128 of file CellListAllPairsInteractionTemplate.hpp.
template<typename _Potential > real espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::computeVirial () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 156 of file CellListAllPairsInteractionTemplate.hpp.
References espressopp::iterator::CellListAllPairsIterator::isValid(), LOG4ESPP_INFO, mpiWorld, espressopp::Particle::position(), and espressopp::Particle::type().
template<typename _Potential > void espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::computeVirialTensor (Tensor & wij) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 183 of file CellListAllPairsInteractionTemplate.hpp.
References espressopp::iterator::CellListAllPairsIterator::isValid(), LOG4ESPP_INFO, mpiWorld, espressopp::Particle::position(), and espressopp::Particle::type().
template<typename _Potential > void espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::computeVirialTensor (Tensor & w, real z) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 208 of file CellListAllPairsInteractionTemplate.hpp.
References espressopp::bc::BC::getMinimumImageVectorBox(), espressopp::iterator::CellListAllPairsIterator::isValid(), LOG4ESPP_INFO, mpiWorld, espressopp::Particle::position(), and espressopp::Particle::type().
template<typename _Potential > void espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::computeVirialTensor (Tensor * w, int n) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 242 of file CellListAllPairsInteractionTemplate.hpp.
References espressopp::bc::BC::getBoxL(), espressopp::bc::BC::getMinimumImageVectorBox(), espressopp::iterator::CellListAllPairsIterator::isValid(), LOG4ESPP_INFO, mpiWorld, espressopp::Particle::position(), and espressopp::Particle::type().
template<typename _Potential > void espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::computeVirialX (std::vector< real > & p_xx_total, int bins) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 150 of file CellListAllPairsInteractionTemplate.hpp.
template<typename _Potential > real espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::getMaxCutoff () inline virtual
This method returns the maximal cutoff defined for one type pair.
Implements espressopp::interaction::Interaction.
Definition at line 293 of file CellListAllPairsInteractionTemplate.hpp.
template<typename _Potential > Potential& espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::getPotential (int type1, int type2) inline
Definition at line 63 of file CellListAllPairsInteractionTemplate.hpp.
References espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::potentialArray.
static espressopp::interaction::Interaction::LOG4ESPP_DECL_LOGGER (theLogger) static protected inherited
Logger.
void espressopp::interaction::Interaction::registerPython () static inherited
Definition at line 36 of file Interaction.cpp.
References espressopp::interaction::Interaction::bondType(), espressopp::interaction::Interaction::computeEnergy(), espressopp::interaction::Interaction::computeEnergyAA(), espressopp::interaction::Interaction::computeEnergyCG(), espressopp::interaction::Interaction::computeEnergyDeriv(), and espressopp::interaction::Interaction::computeVirial().
Referenced by espressopp::interaction::registerPython().
template<typename _Potential > void espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::setPotential (int type1, int type2, const Potential & potential) inline
Definition at line 50 of file CellListAllPairsInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::ntypes, and espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::potentialArray.
Member Data Documentation
template<typename _Potential > int espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::ntypes protected
Definition at line 81 of file CellListAllPairsInteractionTemplate.hpp.
Referenced by espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::CellListAllPairsInteractionTemplate(), and espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::setPotential().
template<typename _Potential > esutil::Array2D< Potential, esutil::enlarge > espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::potentialArray protected
Definition at line 82 of file CellListAllPairsInteractionTemplate.hpp.
Referenced by espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::CellListAllPairsInteractionTemplate(), espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::getPotential(), and espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::setPotential().
template<typename _Potential > shared_ptr< storage::Storage > espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::storage protected
Definition at line 83 of file CellListAllPairsInteractionTemplate.hpp.
The documentation for this class was generated from the following file:
/home/travis/build/espressopp/espressopp/src/interaction/CellListAllPairsInteractionTemplate.hpp