ESPResSo++: espressopp::interaction::DihedralHarmonicNCos Class Reference
espressopp::interaction::DihedralHarmonicNCos Class Reference
This class provides methods to compute forces and energies of the DihedralHarmonicNCos dihedral potential.
#include <DihedralHarmonicNCos.hpp>
Public Member Functions
DihedralHarmonicNCos ()
DihedralHarmonicNCos (real _K, real _phi0, int _multiplicity)
void setK (real _K)
real getK () const
void setPhi0 (real _phi0)
real getPhi0 () const
void setMultiplicity (real _multiplicity)
int getMultiplicity () const
real d (int i, int j) const
Real3D prod (Real3D a, Real3D b) const
Compute dot product of two vectors.
real _computeEnergyRaw (real _phi) const
Calculate raw value of the energy.
void _computeForceRaw (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &r21, const Real3D &r32, const Real3D &r43) const
Compute the force.
real _computeForceRaw (real phi) const
virtual real computeEnergy (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
virtual real computeEnergy (real phi) const
virtual void computeForce (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
virtual real computeForce (real phi) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
real _computeEnergy (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
real _computeEnergy (real phi) const
void _computeForce (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
DihedralHarmonicNCos * derived_this ()
const DihedralHarmonicNCos * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
Private Attributes
real K
real phi0
int multiplicity
real cos_phi0
Detailed Description
This class provides methods to compute forces and energies of the DihedralHarmonicNCos dihedral potential.
The reference potential is as follow:
where the K is a constant. The angles and should be provided in radians.
The reference documentation: http://www.uark.edu/ua/fengwang/DLPOLY2/node49.html
Definition at line 50 of file DihedralHarmonicNCos.hpp.
Constructor & Destructor Documentation
DihedralHarmonicNCos() [1/2]
espressopp::interaction::DihedralHarmonicNCos::DihedralHarmonicNCos () inline
Definition at line 60 of file DihedralHarmonicNCos.hpp.
DihedralHarmonicNCos() [2/2]
espressopp::interaction::DihedralHarmonicNCos::DihedralHarmonicNCos (real _K, real _phi0, int _multiplicity) inline
Definition at line 61 of file DihedralHarmonicNCos.hpp.
Member Function Documentation
_computeEnergy() [1/2]
real espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >::_computeEnergy (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline inherited
Definition at line 165 of file DihedralPotential.hpp.
_computeEnergy() [2/2]
real espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >::_computeEnergy (real phi) const inline inherited
Definition at line 258 of file DihedralPotential.hpp.
_computeEnergyRaw()
real espressopp::interaction::DihedralHarmonicNCos::_computeEnergyRaw (real _phi) const inline
Calculate raw value of the energy.
Parameters
[in] _phi The phi value in radians.
Returns
The energy value.
Definition at line 109 of file DihedralHarmonicNCos.hpp.
_computeForce()
void espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >::_computeForce (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline inherited
Definition at line 280 of file DihedralPotential.hpp.
_computeForceRaw() [1/2]
void espressopp::interaction::DihedralHarmonicNCos::_computeForceRaw (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & r21, const Real3D & r32, const Real3D & r43) const inline
Compute the force.
Only the form of the potential derivative has to be changed. The rest remain the same as for the harmonic cosine potential
The part of the formula. 1/sin(phi) * d/dphi U(phi) where the The n is multiplicity.
The derivative of is
Definition at line 119 of file DihedralHarmonicNCos.hpp.
References espressopp::Real3D::cross(), d(), M_PI, prod(), and espressopp::Real3D::sqr().
_computeForceRaw() [2/2]
real espressopp::interaction::DihedralHarmonicNCos::_computeForceRaw (real phi) const inline
Definition at line 206 of file DihedralHarmonicNCos.hpp.
computeEnergy() [1/2]
real espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >::computeEnergy (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 145 of file DihedralPotential.hpp.
computeEnergy() [2/2]
real espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >::computeEnergy (real phi) const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 158 of file DihedralPotential.hpp.
computeForce() [1/2]
void espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >::computeForce (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 266 of file DihedralPotential.hpp.
computeForce() [2/2]
real espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >::computeForce (real phi) const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 294 of file DihedralPotential.hpp.
d()
real espressopp::interaction::DihedralHarmonicNCos::d (int i, int j) const inline
Definition at line 86 of file DihedralHarmonicNCos.hpp.
Referenced by _computeForceRaw(), and prod().
derived_this() [1/2]
DihedralHarmonicNCos * espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >::derived_this () inline protected inherited
Definition at line 107 of file DihedralPotential.hpp.
derived_this() [2/2]
const DihedralHarmonicNCos * espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >::derived_this () const inline protected inherited
Definition at line 111 of file DihedralPotential.hpp.
getCutoff()
real espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 138 of file DihedralPotential.hpp.
getK()
real espressopp::interaction::DihedralHarmonicNCos::getK () const inline
Definition at line 72 of file DihedralHarmonicNCos.hpp.
References K.
Referenced by registerPython().
getMultiplicity()
int espressopp::interaction::DihedralHarmonicNCos::getMultiplicity () const inline
Definition at line 83 of file DihedralHarmonicNCos.hpp.
References multiplicity.
Referenced by registerPython().
getPhi0()
real espressopp::interaction::DihedralHarmonicNCos::getPhi0 () const inline
Definition at line 80 of file DihedralHarmonicNCos.hpp.
References phi0.
Referenced by registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::DihedralPotential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
prod()
Real3D espressopp::interaction::DihedralHarmonicNCos::prod (Real3D a, Real3D b) const inline
Compute dot product of two vectors.
Definition at line 94 of file DihedralHarmonicNCos.hpp.
References d().
Referenced by _computeForceRaw().
registerPython()
void espressopp::interaction::DihedralHarmonicNCos::registerPython () static
Definition at line 36 of file DihedralHarmonicNCos.cpp.
References getK(), getMultiplicity(), getPhi0(), setK(), setMultiplicity(), and setPhi0().
Referenced by espressopp::interaction::registerPython().
setCutoff()
void espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 130 of file DihedralPotential.hpp.
setK()
void espressopp::interaction::DihedralHarmonicNCos::setK (real _K) inline
Definition at line 71 of file DihedralHarmonicNCos.hpp.
Referenced by registerPython().
setMultiplicity()
void espressopp::interaction::DihedralHarmonicNCos::setMultiplicity (real _multiplicity) inline
Definition at line 82 of file DihedralHarmonicNCos.hpp.
Referenced by registerPython().
setPhi0()
void espressopp::interaction::DihedralHarmonicNCos::setPhi0 (real _phi0) inline
Definition at line 74 of file DihedralHarmonicNCos.hpp.
Referenced by registerPython().
Member Data Documentation
cos_phi0
real espressopp::interaction::DihedralHarmonicNCos::cos_phi0 private
Definition at line 56 of file DihedralHarmonicNCos.hpp.
cutoff
real espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >::cutoff protected inherited
Definition at line 104 of file DihedralPotential.hpp.
cutoffSqr
real espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicNCos >::cutoffSqr protected inherited
Definition at line 105 of file DihedralPotential.hpp.
K
real espressopp::interaction::DihedralHarmonicNCos::K private
Definition at line 52 of file DihedralHarmonicNCos.hpp.
Referenced by getK().
multiplicity
int espressopp::interaction::DihedralHarmonicNCos::multiplicity private
Definition at line 54 of file DihedralHarmonicNCos.hpp.
Referenced by getMultiplicity().
phi0
real espressopp::interaction::DihedralHarmonicNCos::phi0 private
Definition at line 53 of file DihedralHarmonicNCos.hpp.
Referenced by getPhi0().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/DihedralHarmonicNCos.hpp
/home/espressopp/espressopp/src/interaction/DihedralHarmonicNCos.cpp