ESPResSo++: espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential > Class Template Reference
espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential > Class Template Reference
#include <VerletListHadressATInteractionTemplate.hpp>
Public Member Functions
VerletListHadressATInteractionTemplate (shared_ptr< VerletListAdress > _verletList, shared_ptr< FixedTupleListAdress > _fixedtupleList)
void setVerletList (shared_ptr< VerletListAdress > _verletList)
shared_ptr< VerletListAdress > getVerletList ()
void setFixedTupleList (shared_ptr< FixedTupleListAdress > _fixedtupleList)
void setPotential (int type1, int type2, const Potential &potential)
Potential & getPotential (int type1, int type2)
shared_ptr< Potential > getPotentialPtr (int type1, int type2)
virtual void addForces ()
virtual real computeEnergy ()
virtual real computeEnergyDeriv ()
virtual real computeEnergyAA ()
virtual real computeEnergyCG ()
virtual real computeEnergyAA (int atomtype)
virtual real computeEnergyCG (int atomtype)
virtual void computeVirialX (std::vector< real > &p_xx_total, int bins)
virtual real computeVirial ()
virtual void computeVirialTensor (Tensor &w)
virtual void computeVirialTensor (Tensor &w, real z)
virtual void computeVirialTensor (Tensor *w, int n)
virtual real getMaxCutoff ()
This method returns the maximal cutoff defined for one type pair.
virtual int bondType ()
Static Public Member Functions
static void registerPython ()
Protected Types
typedef _Potential Potential
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Protected Attributes
int ntypes
shared_ptr< VerletListAdress > verletList
shared_ptr< FixedTupleListAdress > fixedtupleList
esutil::Array2D< Potential, esutil::enlarge > potentialArray
real pidhy2
real dexdhy
real dexdhy2
real dex
real dhy
real dex2
boost::unordered_map< Particle *, real > energydiff
std::set< Particle * > adrZone
std::set< Particle * > cgZone
Detailed Description
template<typename _Potential>
class espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >
Definition at line 42 of file VerletListHadressATInteractionTemplate.hpp.
Member Typedef Documentation
Potential
template<typename _Potential > typedef _Potential espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::Potential protected
Definition at line 45 of file VerletListHadressATInteractionTemplate.hpp.
Constructor & Destructor Documentation
VerletListHadressATInteractionTemplate()
template<typename _Potential > espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::VerletListHadressATInteractionTemplate (shared_ptr< VerletListAdress > _verletList, shared_ptr< FixedTupleListAdress > _fixedtupleList) inline
Definition at line 49 of file VerletListHadressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::dex, espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::dex2, espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::dexdhy, espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::dexdhy2, espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::dhy, M_PI, espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::ntypes, espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::pidhy2, espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::potentialArray, and espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::verletList.
Member Function Documentation
addForces()
template<typename _Potential > void espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::addForces () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 139 of file VerletListHadressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::adrZone, espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::cgZone, espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeEnergy(), espressopp::Particle::drift(), espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::energydiff, espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::fixedtupleList, espressopp::Particle::force(), espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::getPotential(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::Particle::lambda(), espressopp::Particle::lambdaDeriv(), LOG4ESPP_INFO, espressopp::Particle::position(), espressopp::Real3D::sqr(), espressopp::Particle::type(), and espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::verletList.
Referenced by espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::getPotentialPtr().
bondType()
template<typename _Potential > virtual int espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::bondType () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 111 of file VerletListHadressATInteractionTemplate.hpp.
References espressopp::interaction::Nonbonded.
computeEnergy()
template<typename _Potential > real espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeEnergy () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 291 of file VerletListHadressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeEnergyDeriv(), espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::fixedtupleList, espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::getPotential(), espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::getVerletList(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::Particle::lambda(), LOG4ESPP_INFO, espressopp::Particle::type(), and espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::verletList.
Referenced by espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::addForces(), and espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::getPotentialPtr().
computeEnergyAA() [1/2]
template<typename _Potential > real espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeEnergyAA () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 346 of file VerletListHadressATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeEnergyDeriv(), and espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::getPotentialPtr().
computeEnergyAA() [2/2]
template<typename _Potential > real espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeEnergyAA (int atomtype) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 353 of file VerletListHadressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeEnergyCG().
computeEnergyCG() [1/2]
template<typename _Potential > real espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeEnergyCG () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 360 of file VerletListHadressATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeEnergyAA(), and espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::getPotentialPtr().
computeEnergyCG() [2/2]
template<typename _Potential > real espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeEnergyCG (int atomtype) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 367 of file VerletListHadressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeVirialX().
computeEnergyDeriv()
template<typename _Potential > real espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeEnergyDeriv () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 339 of file VerletListHadressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeEnergyAA().
Referenced by espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeEnergy(), and espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::getPotentialPtr().
computeVirial()
template<typename _Potential > real espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeVirial () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 380 of file VerletListHadressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeVirialTensor(), and LOG4ESPP_INFO.
Referenced by espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeVirialX(), and espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::getPotentialPtr().
computeVirialTensor() [1/3]
template<typename _Potential > void espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeVirialTensor (Tensor & w) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 388 of file VerletListHadressATInteractionTemplate.hpp.
References LOG4ESPP_INFO.
Referenced by espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeVirialTensor(), and espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::getPotentialPtr().
computeVirialTensor() [2/3]
template<typename _Potential > void espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeVirialTensor (Tensor & w, real z) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 395 of file VerletListHadressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeVirialTensor(), and LOG4ESPP_INFO.
computeVirialTensor() [3/3]
template<typename _Potential > void espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeVirialTensor (Tensor * w, int n) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 402 of file VerletListHadressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::getMaxCutoff().
computeVirialX()
template<typename _Potential > void espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeVirialX (std::vector< real > & p_xx_total, int bins) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 374 of file VerletListHadressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeVirial().
Referenced by espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeEnergyCG(), and espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::getPotentialPtr().
getMaxCutoff()
template<typename _Potential > real espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::getMaxCutoff () inline virtual
This method returns the maximal cutoff defined for one type pair.
Implements espressopp::interaction::Interaction.
Definition at line 409 of file VerletListHadressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::getPotential(), and espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::ntypes.
Referenced by espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeVirialTensor(), and espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::getPotentialPtr().
getPotential()
template<typename _Potential > Potential& espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::getPotential (int type1, int type2) inline
Definition at line 90 of file VerletListHadressATInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), and espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::potentialArray.
Referenced by espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeEnergy(), and espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::getMaxCutoff().
getPotentialPtr()
template<typename _Potential > shared_ptr<Potential> espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::getPotentialPtr (int type1, int type2) inline
Definition at line 94 of file VerletListHadressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::addForces(), espressopp::esutil::Array2D< T, outlier_mode >::at(), espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeEnergyAA(), espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeEnergyCG(), espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeEnergyDeriv(), espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeVirialX(), espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::getMaxCutoff(), and espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::potentialArray.
getVerletList()
template<typename _Potential > shared_ptr<VerletListAdress> espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::getVerletList () inline
Definition at line 70 of file VerletListHadressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::verletList.
Referenced by espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeEnergy().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Interaction::LOG4ESPP_DECL_LOGGER (theLogger) static protected inherited
Logger.
Referenced by espressopp::interaction::Interaction::~Interaction().
registerPython()
void espressopp::interaction::Interaction::registerPython () static inherited
Definition at line 36 of file Interaction.cpp.
References espressopp::interaction::Interaction::bondType(), espressopp::interaction::Interaction::computeEnergy(), espressopp::interaction::Interaction::computeEnergyAA(), espressopp::interaction::Interaction::computeEnergyCG(), espressopp::interaction::Interaction::computeEnergyDeriv(), and espressopp::interaction::Interaction::computeVirial().
Referenced by espressopp::interaction::registerPython(), and espressopp::interaction::Interaction::~Interaction().
setFixedTupleList()
template<typename _Potential > void espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::setFixedTupleList (shared_ptr< FixedTupleListAdress > _fixedtupleList) inline
Definition at line 75 of file VerletListHadressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::fixedtupleList.
setPotential()
template<typename _Potential > void espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::setPotential (int type1, int type2, const Potential & potential) inline
Definition at line 80 of file VerletListHadressATInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::ntypes, and espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::potentialArray.
setVerletList()
template<typename _Potential > void espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::setVerletList (shared_ptr< VerletListAdress > _verletList) inline
Definition at line 66 of file VerletListHadressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::verletList.
Member Data Documentation
adrZone
template<typename _Potential > std::set<Particle*> espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::adrZone protected
Definition at line 129 of file VerletListHadressATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::addForces().
cgZone
template<typename _Potential > std::set<Particle*> espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::cgZone protected
Definition at line 130 of file VerletListHadressATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::addForces().
dex
template<typename _Potential > real espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::dex protected
Definition at line 125 of file VerletListHadressATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::VerletListHadressATInteractionTemplate().
dex2
template<typename _Potential > real espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::dex2 protected
Definition at line 127 of file VerletListHadressATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::VerletListHadressATInteractionTemplate().
dexdhy
template<typename _Potential > real espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::dexdhy protected
Definition at line 123 of file VerletListHadressATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::VerletListHadressATInteractionTemplate().
dexdhy2
template<typename _Potential > real espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::dexdhy2 protected
Definition at line 124 of file VerletListHadressATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::VerletListHadressATInteractionTemplate().
dhy
template<typename _Potential > real espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::dhy protected
Definition at line 126 of file VerletListHadressATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::VerletListHadressATInteractionTemplate().
energydiff
template<typename _Potential > boost::unordered_map<Particle*, real> espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::energydiff protected
Definition at line 128 of file VerletListHadressATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::addForces().
fixedtupleList
template<typename _Potential > shared_ptr<FixedTupleListAdress> espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::fixedtupleList protected
Definition at line 118 of file VerletListHadressATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeEnergy(), and espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::setFixedTupleList().
ntypes
template<typename _Potential > int espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::ntypes protected
Definition at line 116 of file VerletListHadressATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::getMaxCutoff(), espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::setPotential(), and espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::VerletListHadressATInteractionTemplate().
pidhy2
template<typename _Potential > real espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::pidhy2 protected
Definition at line 122 of file VerletListHadressATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::VerletListHadressATInteractionTemplate().
potentialArray
template<typename _Potential > esutil::Array2D<Potential, esutil::enlarge> espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::potentialArray protected
Definition at line 119 of file VerletListHadressATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::getPotential(), espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::getPotentialPtr(), espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::setPotential(), and espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::VerletListHadressATInteractionTemplate().
verletList
template<typename _Potential > shared_ptr<VerletListAdress> espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::verletList protected
Definition at line 117 of file VerletListHadressATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::getVerletList(), espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::setVerletList(), and espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::VerletListHadressATInteractionTemplate().
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/interaction/VerletListHadressATInteractionTemplate.hpp