ESPResSo++: espressopp::interaction::TersoffTripleTerm Class Reference
espressopp::interaction::TersoffTripleTerm Class Reference
#include <TersoffTripleTerm.hpp>
Public Member Functions
TersoffTripleTerm ()
TersoffTripleTerm (real _B, real _lambda2, real _R, real _D, real _n, real _beta, real _m, real _lambda3, real _gamma, real _c, real _d, real _theta0, real _cutoff1, real _cutoff2)
virtual ~TersoffTripleTerm ()
void setB (real _B)
real getB () const
void setLambda2 (real _lambda2)
real getLambda2 () const
void setR (real _R)
real getR () const
void setD (real _D)
real getD () const
void setN (real _n)
real getN () const
void setBeta (real _beta)
real getBeta () const
void setM (real _m)
real getM () const
void setLambda3 (real _lambda3)
real getLambda3 () const
void setGamma (real _gamma)
real getGamma () const
void setC (real _c)
real getC () const
void setd (real _d)
real getd () const
void setTheta0 (real _theta0)
real getTheta0 () const
real getCutoff () const
void setCutoff1 (real _cutoff)
real getCutoff1 () const
void setCutoff2 (real _cutoff)
real getCutoff2 () const
void preset ()
real _computeEnergy (const Real3D &r12, const Real3D &r32) const
bool _computeForceRaw (Real3D &force12, Real3D &force32, const Real3D &r12, const Real3D &r32) const
real _computeEnergyRaw (real _theta) const
real _computeForceRaw (real theta) const
virtual real computeEnergy (const Particle &p1, const Particle &p2, const Particle &p3) const
virtual real computeEnergy (const Real3D &dist12, const Real3D &dist32) const
virtual real computeEnergy (const real theta) const
virtual void computeForce (Real3D &force12, Real3D &force32, const Particle &p1, const Particle &p2, const Particle &p3) const
virtual void computeForce (Real3D &force12, Real3D &force32, const Real3D &dist12, const Real3D &dist32) const
virtual real computeForce (real theta) const
virtual void setCutoff (real _cutoff)
real _computeEnergy (const Particle &p1, const Particle &p2, const Particle &p3) const
real _computeEnergy (real theta) const
void _computeForce (Real3D &force12, Real3D &force32, const Particle &p1, const Particle &p2, const Particle &p3) const
bool _computeForce (Real3D &force12, Real3D &force32, const Real3D &dist12, const Real3D &dist32) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
TersoffTripleTerm * derived_this ()
const TersoffTripleTerm * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
Private Attributes
real rc1
real gamma1, gamma2; real sigma1, rc1, sigma2, rc2;
real rc2
real R
real D
real B
real lambda2
real n
real beta
real m
real lambda3
real gamma
real c
real d
real theta0
real c2
real d2
real Pi_2D
real cosTheta0
Detailed Description
Definition at line 39 of file TersoffTripleTerm.hpp.
Constructor & Destructor Documentation
TersoffTripleTerm() [1/2]
espressopp::interaction::TersoffTripleTerm::TersoffTripleTerm () inline
Definition at line 65 of file TersoffTripleTerm.hpp.
References preset().
TersoffTripleTerm() [2/2]
espressopp::interaction::TersoffTripleTerm::TersoffTripleTerm (real _B, real _lambda2, real _R, real _D, real _n, real _beta, real _m, real _lambda3, real _gamma, real _c, real _d, real _theta0, real _cutoff1, real _cutoff2) inline
Definition at line 70 of file TersoffTripleTerm.hpp.
References preset().
~TersoffTripleTerm()
virtual espressopp::interaction::TersoffTripleTerm::~TersoffTripleTerm () inline virtual
Definition at line 81 of file TersoffTripleTerm.hpp.
Member Function Documentation
_computeEnergy() [1/3]
real espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >::_computeEnergy (const Particle & p1, const Particle & p2, const Particle & p3) const inline inherited
Definition at line 175 of file AngularPotential.hpp.
References espressopp::Particle::position().
_computeEnergy() [2/3]
real espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >::_computeEnergy (real theta) const inline inherited
Definition at line 199 of file AngularPotential.hpp.
_computeEnergy() [3/3]
real espressopp::interaction::TersoffTripleTerm::_computeEnergy (const Real3D & r12, const Real3D & r32) const inline
Definition at line 185 of file TersoffTripleTerm.hpp.
References espressopp::Real3D::abs(), cosTheta0, and R.
_computeEnergyRaw()
real espressopp::interaction::TersoffTripleTerm::_computeEnergyRaw (real _theta) const inline
Definition at line 308 of file TersoffTripleTerm.hpp.
_computeForce() [1/2]
void espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >::_computeForce (Real3D & force12, Real3D & force32, const Particle & p1, const Particle & p2, const Particle & p3) const inline inherited
Definition at line 228 of file AngularPotential.hpp.
References espressopp::Particle::position().
_computeForce() [2/2]
bool espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >::_computeForce (Real3D & force12, Real3D & force32, const Real3D & dist12, const Real3D & dist32) const inline inherited
Definition at line 239 of file AngularPotential.hpp.
_computeForceRaw() [1/2]
bool espressopp::interaction::TersoffTripleTerm::_computeForceRaw (Real3D & force12, Real3D & force32, const Real3D & r12, const Real3D & r32) const inline
Definition at line 226 of file TersoffTripleTerm.hpp.
References espressopp::Real3D::abs(), cosTheta0, and R.
_computeForceRaw() [2/2]
real espressopp::interaction::TersoffTripleTerm::_computeForceRaw (real theta) const inline
Definition at line 314 of file TersoffTripleTerm.hpp.
computeEnergy() [1/3]
real espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >::computeEnergy (const Particle & p1, const Particle & p2, const Particle & p3) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 149 of file AngularPotential.hpp.
References espressopp::Particle::position().
computeEnergy() [2/3]
real espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >::computeEnergy (const Real3D & dist12, const Real3D & dist32) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 158 of file AngularPotential.hpp.
computeEnergy() [3/3]
real espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >::computeEnergy (const real theta) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 168 of file AngularPotential.hpp.
computeForce() [1/3]
void espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >::computeForce (Real3D & force12, Real3D & force32, const Particle & p1, const Particle & p2, const Particle & p3) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 207 of file AngularPotential.hpp.
References espressopp::Particle::position().
computeForce() [2/3]
void espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >::computeForce (Real3D & force12, Real3D & force32, const Real3D & dist12, const Real3D & dist32) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 218 of file AngularPotential.hpp.
computeForce() [3/3]
real espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >::computeForce (real theta) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 251 of file AngularPotential.hpp.
derived_this() [1/2]
TersoffTripleTerm * espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >::derived_this () inline protected inherited
Definition at line 111 of file AngularPotential.hpp.
derived_this() [2/2]
const TersoffTripleTerm * espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >::derived_this () const inline protected inherited
Definition at line 115 of file AngularPotential.hpp.
References espressopp::interaction::AngularPotentialTemplate< Derived >::AngularPotentialTemplate().
getB()
real espressopp::interaction::TersoffTripleTerm::getB () const inline
Definition at line 86 of file TersoffTripleTerm.hpp.
References B.
Referenced by registerPython().
getBeta()
real espressopp::interaction::TersoffTripleTerm::getBeta () const inline
Definition at line 112 of file TersoffTripleTerm.hpp.
References beta.
Referenced by registerPython().
getC()
real espressopp::interaction::TersoffTripleTerm::getC () const inline
Definition at line 133 of file TersoffTripleTerm.hpp.
References c.
Referenced by registerPython().
getCutoff()
real espressopp::interaction::TersoffTripleTerm::getCutoff () const inline virtual
Reimplemented from espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >.
Definition at line 147 of file TersoffTripleTerm.hpp.
getCutoff1()
real espressopp::interaction::TersoffTripleTerm::getCutoff1 () const inline
Definition at line 154 of file TersoffTripleTerm.hpp.
References rc1.
Referenced by registerPython().
getCutoff2()
real espressopp::interaction::TersoffTripleTerm::getCutoff2 () const inline
Definition at line 161 of file TersoffTripleTerm.hpp.
References rc2.
Referenced by registerPython().
getD()
real espressopp::interaction::TersoffTripleTerm::getD () const inline
Definition at line 102 of file TersoffTripleTerm.hpp.
References D.
Referenced by registerPython().
getd()
real espressopp::interaction::TersoffTripleTerm::getd () const inline
Definition at line 139 of file TersoffTripleTerm.hpp.
References d.
Referenced by registerPython().
getGamma()
real espressopp::interaction::TersoffTripleTerm::getGamma () const inline
Definition at line 127 of file TersoffTripleTerm.hpp.
References gamma.
Referenced by registerPython().
getLambda2()
real espressopp::interaction::TersoffTripleTerm::getLambda2 () const inline
Definition at line 91 of file TersoffTripleTerm.hpp.
References lambda2.
Referenced by registerPython().
getLambda3()
real espressopp::interaction::TersoffTripleTerm::getLambda3 () const inline
Definition at line 122 of file TersoffTripleTerm.hpp.
References lambda3.
Referenced by registerPython().
getM()
real espressopp::interaction::TersoffTripleTerm::getM () const inline
Definition at line 117 of file TersoffTripleTerm.hpp.
References m.
Referenced by registerPython().
getN()
real espressopp::interaction::TersoffTripleTerm::getN () const inline
Definition at line 107 of file TersoffTripleTerm.hpp.
References n.
Referenced by registerPython().
getR()
real espressopp::interaction::TersoffTripleTerm::getR () const inline
Definition at line 96 of file TersoffTripleTerm.hpp.
References R.
Referenced by registerPython().
getTheta0()
real espressopp::interaction::TersoffTripleTerm::getTheta0 () const inline
Definition at line 145 of file TersoffTripleTerm.hpp.
References theta0.
Referenced by registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::AngularPotential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
preset()
void espressopp::interaction::TersoffTripleTerm::preset () inline
Definition at line 166 of file TersoffTripleTerm.hpp.
References c, D, d, and M_PIl.
Referenced by setC(), setCutoff1(), setCutoff2(), setD(), setd(), setTheta0(), and TersoffTripleTerm().
registerPython()
void espressopp::interaction::TersoffTripleTerm::registerPython () static
Definition at line 40 of file TersoffTripleTerm.cpp.
References getB(), getBeta(), getC(), getCutoff1(), getCutoff2(), getD(), getd(), getGamma(), getLambda2(), getLambda3(), getM(), getN(), getR(), getTheta0(), setB(), setBeta(), setC(), setCutoff1(), setCutoff2(), setD(), setd(), setGamma(), setLambda2(), setLambda3(), setM(), setN(), setR(), and setTheta0().
Referenced by espressopp::interaction::registerPython().
setB()
void espressopp::interaction::TersoffTripleTerm::setB (real _B) inline
Definition at line 83 of file TersoffTripleTerm.hpp.
Referenced by registerPython().
setBeta()
void espressopp::interaction::TersoffTripleTerm::setBeta (real _beta) inline
Definition at line 109 of file TersoffTripleTerm.hpp.
Referenced by registerPython().
setC()
void espressopp::interaction::TersoffTripleTerm::setC (real _c) inline
Definition at line 129 of file TersoffTripleTerm.hpp.
References preset().
Referenced by registerPython().
setCutoff()
void espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 134 of file AngularPotential.hpp.
setCutoff1()
void espressopp::interaction::TersoffTripleTerm::setCutoff1 (real _cutoff) inline
Definition at line 150 of file TersoffTripleTerm.hpp.
References preset().
Referenced by registerPython().
setCutoff2()
void espressopp::interaction::TersoffTripleTerm::setCutoff2 (real _cutoff) inline
Definition at line 157 of file TersoffTripleTerm.hpp.
References preset().
Referenced by registerPython().
setD()
void espressopp::interaction::TersoffTripleTerm::setD (real _D) inline
Definition at line 98 of file TersoffTripleTerm.hpp.
References preset().
Referenced by registerPython().
setd()
void espressopp::interaction::TersoffTripleTerm::setd (real _d) inline
Definition at line 135 of file TersoffTripleTerm.hpp.
References preset().
Referenced by registerPython().
setGamma()
void espressopp::interaction::TersoffTripleTerm::setGamma (real _gamma) inline
Definition at line 124 of file TersoffTripleTerm.hpp.
Referenced by registerPython().
setLambda2()
void espressopp::interaction::TersoffTripleTerm::setLambda2 (real _lambda2) inline
Definition at line 88 of file TersoffTripleTerm.hpp.
Referenced by registerPython().
setLambda3()
void espressopp::interaction::TersoffTripleTerm::setLambda3 (real _lambda3) inline
Definition at line 119 of file TersoffTripleTerm.hpp.
Referenced by registerPython().
setM()
void espressopp::interaction::TersoffTripleTerm::setM (real _m) inline
Definition at line 114 of file TersoffTripleTerm.hpp.
Referenced by registerPython().
setN()
void espressopp::interaction::TersoffTripleTerm::setN (real _n) inline
Definition at line 104 of file TersoffTripleTerm.hpp.
Referenced by registerPython().
setR()
void espressopp::interaction::TersoffTripleTerm::setR (real _R) inline
Definition at line 93 of file TersoffTripleTerm.hpp.
Referenced by registerPython().
setTheta0()
void espressopp::interaction::TersoffTripleTerm::setTheta0 (real _theta0) inline
Definition at line 141 of file TersoffTripleTerm.hpp.
References preset().
Referenced by registerPython().
Member Data Documentation
B
real espressopp::interaction::TersoffTripleTerm::B private
Definition at line 57 of file TersoffTripleTerm.hpp.
Referenced by getB().
beta
real espressopp::interaction::TersoffTripleTerm::beta private
Definition at line 58 of file TersoffTripleTerm.hpp.
Referenced by getBeta().
c
real espressopp::interaction::TersoffTripleTerm::c private
Definition at line 60 of file TersoffTripleTerm.hpp.
Referenced by getC(), and preset().
c2
real espressopp::interaction::TersoffTripleTerm::c2 private
Definition at line 61 of file TersoffTripleTerm.hpp.
cosTheta0
real espressopp::interaction::TersoffTripleTerm::cosTheta0 private
Definition at line 61 of file TersoffTripleTerm.hpp.
Referenced by _computeEnergy(), and _computeForceRaw().
cutoff
real espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >::cutoff protected inherited
Definition at line 108 of file AngularPotential.hpp.
cutoffSqr
real espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >::cutoffSqr protected inherited
Definition at line 109 of file AngularPotential.hpp.
D
real espressopp::interaction::TersoffTripleTerm::D private
Definition at line 56 of file TersoffTripleTerm.hpp.
Referenced by getD(), and preset().
d
real espressopp::interaction::TersoffTripleTerm::d private
Definition at line 60 of file TersoffTripleTerm.hpp.
Referenced by getd(), and preset().
d2
real espressopp::interaction::TersoffTripleTerm::d2 private
Definition at line 61 of file TersoffTripleTerm.hpp.
gamma
real espressopp::interaction::TersoffTripleTerm::gamma private
Definition at line 60 of file TersoffTripleTerm.hpp.
Referenced by getGamma().
lambda2
real espressopp::interaction::TersoffTripleTerm::lambda2 private
Definition at line 57 of file TersoffTripleTerm.hpp.
Referenced by getLambda2().
lambda3
real espressopp::interaction::TersoffTripleTerm::lambda3 private
Definition at line 59 of file TersoffTripleTerm.hpp.
Referenced by getLambda3().
m
real espressopp::interaction::TersoffTripleTerm::m private
Definition at line 59 of file TersoffTripleTerm.hpp.
Referenced by getM().
n
real espressopp::interaction::TersoffTripleTerm::n private
Definition at line 58 of file TersoffTripleTerm.hpp.
Referenced by getN().
Pi_2D
real espressopp::interaction::TersoffTripleTerm::Pi_2D private
Definition at line 61 of file TersoffTripleTerm.hpp.
R
real espressopp::interaction::TersoffTripleTerm::R private
Definition at line 56 of file TersoffTripleTerm.hpp.
Referenced by _computeEnergy(), _computeForceRaw(), and getR().
rc1
real espressopp::interaction::TersoffTripleTerm::rc1 private
real gamma1, gamma2; real sigma1, rc1, sigma2, rc2;
real theta0, lambda; real epsilon; real cosTheta0; real sigmaGamma1, sigmaGamma2; real sigmarc1, sigmarc2; real epsilonLambda;
Definition at line 54 of file TersoffTripleTerm.hpp.
Referenced by getCutoff1().
rc2
real espressopp::interaction::TersoffTripleTerm::rc2 private
Definition at line 54 of file TersoffTripleTerm.hpp.
Referenced by getCutoff2().
theta0
real espressopp::interaction::TersoffTripleTerm::theta0 private
Definition at line 60 of file TersoffTripleTerm.hpp.
Referenced by getTheta0().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/TersoffTripleTerm.hpp
/home/espressopp/espressopp/src/interaction/TersoffTripleTerm.cpp