ESPResSo++: espressopp::interaction::GravityTruncated Class Reference
espressopp::interaction::GravityTruncated Class Reference
#include <GravityTruncated.hpp>
Public Member Functions
GravityTruncated ()
GravityTruncated (real _prefactor, real _cutoff)
void preset ()
void setPrefactor (real _prefactor)
real getPrefactor () const
real _computeEnergy (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &dist, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
real _computeEnergyDeriv (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
GravityTruncated * derived_this ()
const GravityTruncated * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
Private Attributes
real prefactor
Detailed Description
Definition at line 37 of file GravityTruncated.hpp.
Constructor & Destructor Documentation
GravityTruncated() [1/2]
espressopp::interaction::GravityTruncated::GravityTruncated () inline
Definition at line 45 of file GravityTruncated.hpp.
References espressopp::infinity.
GravityTruncated() [2/2]
espressopp::interaction::GravityTruncated::GravityTruncated (real _prefactor, real _cutoff) inline
Definition at line 52 of file GravityTruncated.hpp.
Member Function Documentation
_computeEnergy() [1/4]
real espressopp::interaction::GravityTruncated::_computeEnergy (const Particle & p1, const Particle & p2) const inline
Definition at line 69 of file GravityTruncated.hpp.
References espressopp::Real3D::abs(), espressopp::Particle::mass(), and espressopp::Particle::position().
_computeEnergy() [2/4]
real espressopp::interaction::PotentialTemplate< GravityTruncated >::_computeEnergy (const Real3D & dist) const inline inherited
Definition at line 257 of file Potential.hpp.
_computeEnergy() [3/4]
real espressopp::interaction::PotentialTemplate< GravityTruncated >::_computeEnergy (real dist) const inline inherited
Definition at line 264 of file Potential.hpp.
_computeEnergy() [4/4]
real espressopp::interaction::PotentialTemplate< GravityTruncated >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 250 of file Potential.hpp.
_computeEnergyDeriv()
real espressopp::interaction::PotentialTemplate< GravityTruncated >::_computeEnergyDeriv (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 285 of file Potential.hpp.
_computeEnergySqr()
real espressopp::interaction::PotentialTemplate< GravityTruncated >::_computeEnergySqr (real distSqr) const inline inherited
Definition at line 271 of file Potential.hpp.
_computeEnergySqrRaw()
real espressopp::interaction::GravityTruncated::_computeEnergySqrRaw (real distSqr) const inline
Definition at line 85 of file GravityTruncated.hpp.
_computeForce() [1/3]
bool espressopp::interaction::GravityTruncated::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const inline
Definition at line 75 of file GravityTruncated.hpp.
References espressopp::Real3D::abs(), espressopp::Particle::mass(), espressopp::Particle::position(), and espressopp::Real3D::sqr().
_computeForce() [2/3]
bool espressopp::interaction::PotentialTemplate< GravityTruncated >::_computeForce (Real3D & force, const Real3D & dist) const inline inherited
Definition at line 328 of file Potential.hpp.
_computeForce() [3/3]
bool espressopp::interaction::PotentialTemplate< GravityTruncated >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 321 of file Potential.hpp.
_computeForceRaw()
bool espressopp::interaction::GravityTruncated::_computeForceRaw (Real3D & force, const Real3D & dist, real distSqr) const inline
Definition at line 90 of file GravityTruncated.hpp.
computeEnergy() [1/3]
real espressopp::interaction::PotentialTemplate< GravityTruncated >::computeEnergy (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 213 of file Potential.hpp.
computeEnergy() [2/3]
real espressopp::interaction::PotentialTemplate< GravityTruncated >::computeEnergy (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 221 of file Potential.hpp.
computeEnergy() [3/3]
real espressopp::interaction::PotentialTemplate< GravityTruncated >::computeEnergy (real dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 228 of file Potential.hpp.
computeEnergySqr()
real espressopp::interaction::PotentialTemplate< GravityTruncated >::computeEnergySqr (real distsqr) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 235 of file Potential.hpp.
computeForce() [1/2]
Real3D espressopp::interaction::PotentialTemplate< GravityTruncated >::computeForce (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 295 of file Potential.hpp.
computeForce() [2/2]
Real3D espressopp::interaction::PotentialTemplate< GravityTruncated >::computeForce (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 303 of file Potential.hpp.
derived_this() [1/2]
GravityTruncated * espressopp::interaction::PotentialTemplate< GravityTruncated >::derived_this () inline protected inherited
Definition at line 123 of file Potential.hpp.
derived_this() [2/2]
const GravityTruncated * espressopp::interaction::PotentialTemplate< GravityTruncated >::derived_this () const inline protected inherited
Definition at line 127 of file Potential.hpp.
getCutoff()
real espressopp::interaction::PotentialTemplate< GravityTruncated >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 171 of file Potential.hpp.
getPrefactor()
real espressopp::interaction::GravityTruncated::getPrefactor () const inline
Definition at line 67 of file GravityTruncated.hpp.
Referenced by registerPython().
getShift()
real espressopp::interaction::PotentialTemplate< GravityTruncated >::getShift () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 186 of file Potential.hpp.
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
Referenced by espressopp::interaction::Potential::~Potential().
preset()
void espressopp::interaction::GravityTruncated::preset () inline
Definition at line 58 of file GravityTruncated.hpp.
registerPython()
void espressopp::interaction::GravityTruncated::registerPython () static
Definition at line 35 of file GravityTruncated.cpp.
References getPrefactor(), and setPrefactor().
Referenced by espressopp::interaction::registerPython().
setAutoShift()
real espressopp::interaction::PotentialTemplate< GravityTruncated >::setAutoShift () inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 192 of file Potential.hpp.
setCutoff()
void espressopp::interaction::PotentialTemplate< GravityTruncated >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 162 of file Potential.hpp.
setPrefactor()
void espressopp::interaction::GravityTruncated::setPrefactor (real _prefactor) inline
Definition at line 63 of file GravityTruncated.hpp.
Referenced by registerPython().
setShift()
void espressopp::interaction::PotentialTemplate< GravityTruncated >::setShift (real _shift) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 177 of file Potential.hpp.
updateAutoShift()
void espressopp::interaction::PotentialTemplate< GravityTruncated >::updateAutoShift () inline inherited
Definition at line 205 of file Potential.hpp.
Member Data Documentation
autoShift
bool espressopp::interaction::PotentialTemplate< GravityTruncated >::autoShift protected inherited
Definition at line 121 of file Potential.hpp.
cutoff
real espressopp::interaction::PotentialTemplate< GravityTruncated >::cutoff protected inherited
Definition at line 118 of file Potential.hpp.
cutoffSqr
real espressopp::interaction::PotentialTemplate< GravityTruncated >::cutoffSqr protected inherited
Definition at line 119 of file Potential.hpp.
prefactor
real espressopp::interaction::GravityTruncated::prefactor private
Definition at line 39 of file GravityTruncated.hpp.
shift
real espressopp::interaction::PotentialTemplate< GravityTruncated >::shift protected inherited
Definition at line 120 of file Potential.hpp.
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/GravityTruncated.hpp
/home/espressopp/espressopp/src/interaction/GravityTruncated.cpp