ESPResSo++: espressopp::iterator::CellListIterator Class Reference
espressopp::iterator::CellListIterator Class Reference
Iterates all Particles in a list of cells.
#include <CellListIterator.hpp>
Public Member Functions
CellListIterator ()
CellListIterator (CellList &cl)
CellListIterator & operator++ ()
bool isValid () const
bool isDone () const
Particle & operator* () const
Particle * operator-> () const
Cell & getCurrentCell () const
Private Member Functions
void findNonemptyCell ()
Private Attributes
CellList::Iterator cit
ParticleList::Iterator pit
Detailed Description
Iterates all Particles in a list of cells.
This is a Python-like, self-contained iterator: isValid() tells whether there are more particles to come.
Definition at line 36 of file CellListIterator.hpp.
Constructor & Destructor Documentation
espressopp::iterator::CellListIterator::CellListIterator () inline
Definition at line 62 of file CellListIterator.hpp.
espressopp::iterator::CellListIterator::CellListIterator (CellList & cl) inline
Definition at line 67 of file CellListIterator.hpp.
References cit, findNonemptyCell(), and pit.
Member Function Documentation
void espressopp::iterator::CellListIterator::findNonemptyCell () inline private
Definition at line 108 of file CellListIterator.hpp.
References cit, espressopp::esutil::ESPPIterator< STLContainer >::isDone(), and pit.
Referenced by CellListIterator(), and operator++().
Cell & espressopp::iterator::CellListIterator::getCurrentCell () const inline
Definition at line 103 of file CellListIterator.hpp.
References cit.
bool espressopp::iterator::CellListIterator::isDone () const inline
Definition at line 88 of file CellListIterator.hpp.
References isValid().
Referenced by espressopp::interaction::CoulombKSpaceEwald::_computeForce(), espressopp::interaction::VSphereSelfInteractionTemplate< _Potential >::addForces(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::addForces(), espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::analysis::OrderParameter::biggest_cluster(), espressopp::analysis::Pressure::compute(), espressopp::analysis::MaxPID::compute(), espressopp::analysis::TotalVelocity::compute(), espressopp::analysis::AdressDensity::computeArray(), espressopp::analysis::RDFatomistic::computeArray(), espressopp::analysis::XDensity::computeArray(), espressopp::analysis::XPressure::computeArray(), espressopp::analysis::XTemperature::computeArray(), espressopp::analysis::RadialDistrF::computeArray(), espressopp::analysis::StaticStructF::computeArray(), espressopp::analysis::StaticStructF::computeArraySingleChain(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::interaction::VSphereSelfInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::computeEnergy(), espressopp::analysis::Temperature::computeRaw(), espressopp::analysis::PressureTensor::computeRaw(), espressopp::analysis::ParticleRadiusDistribution::computeRaw(), espressopp::analysis::PressureTensorLayer::computeRaw(), espressopp::analysis::PressureTensorMultiLayer::computeRaw(), espressopp::analysis::OrderParameter::computeRaw(), espressopp::analysis::NeighborFluctuation::computeValues(), espressopp::analysis::CenterOfMass::computeVector(), espressopp::analysis::ConfigsParticleDecomp::ConfigsParticleDecomp(), espressopp::integrator::Settle::correctVelocities(), espressopp::interaction::CoulombKSpaceEwald::count_charges(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::analysis::OrderParameter::define_solid(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::interaction::CoulombKSpaceEwald::exponentPrecalculation(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::analysis::Velocities::gather(), espressopp::analysis::ConfigurationsExtAdress::gather(), espressopp::analysis::ConfigurationsExt::gather(), espressopp::analysis::Configurations::gather(), espressopp::analysis::ConfigsParticleDecomp::gather(), espressopp::analysis::AllParticlePos::gatherAllPositions(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::storage::Storage::getRealParticleIDs(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::VelocityVerlet::initForces(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerlet::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::VelocityVerlet::integrate2(), espressopp::analysis::OrderParameter::local_cluster_search(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerlet::printForces(), espressopp::integrator::VelocityVerlet::printPositions(), espressopp::integrator::LatticeBoltzmann::readCouplForces(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::analysis::TotalVelocity::reset(), espressopp::integrator::LatticeBoltzmann::restoreLBForces(), espressopp::integrator::LatticeBoltzmann::saveCouplForces(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::scaleVolume(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
bool espressopp::iterator::CellListIterator::isValid () const inline
Definition at line 83 of file CellListIterator.hpp.
References cit.
Referenced by espressopp::interaction::CoulombKSpaceP3M::_computeForce(), espressopp::interaction::CoulombKSpaceP3M::common_part(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::interaction::CoulombKSpaceP3M::count_charges(), espressopp::storage::Storage::fetchParticles(), espressopp::storage::DomainDecompositionAdress::invalidateGhosts(), espressopp::storage::Storage::invalidateGhosts(), isDone(), and espressopp::VerletListAdress::rebuild().
Particle & espressopp::iterator::CellListIterator::operator* () const inline
Definition at line 93 of file CellListIterator.hpp.
References pit.
CellListIterator & espressopp::iterator::CellListIterator::operator++ () inline
Definition at line 75 of file CellListIterator.hpp.
References findNonemptyCell(), and pit.
Particle * espressopp::iterator::CellListIterator::operator-> () const inline
Definition at line 98 of file CellListIterator.hpp.
Member Data Documentation
CellList::Iterator espressopp::iterator::CellListIterator::cit private
Definition at line 53 of file CellListIterator.hpp.
Referenced by CellListIterator(), findNonemptyCell(), getCurrentCell(), and isValid().
ParticleList::Iterator espressopp::iterator::CellListIterator::pit private
Definition at line 54 of file CellListIterator.hpp.
Referenced by CellListIterator(), findNonemptyCell(), operator*(), and operator++().
The documentation for this class was generated from the following file:
/home/travis/build/espressopp/espressopp/src/iterator/CellListIterator.hpp