ESPResSo++: espressopp::FixedPairList Class Reference
espressopp::FixedPairList Class Reference
#include <FixedPairList.hpp>
Public Types
typedef boost::unordered_multimap< longint, longint > GlobalPairs
typedef ESPPIterator< std::vector< ParticlePair > > Iterator
Public Member Functions
FixedPairList (shared_ptr< storage::Storage > _storage)
virtual ~FixedPairList ()
real getLongtimeMaxBondSqr ()
void setLongtimeMaxBondSqr (real d)
void resetLongtimeMaxBondSqr ()
virtual bool add (longint pid1, longint pid2)
Add the given particle pair to the list on this processor if the particle with the lower id belongs to this processor.
virtual void beforeSendParticles (ParticleList &pl, class OutBuffer &buf)
void afterRecvParticles (ParticleList &pl, class InBuffer &buf)
virtual void onParticlesChanged ()
void remove ()
std::vector< longint > getPairList ()
python::list getBonds ()
python::list getAllBonds ()
GlobalPairs * getGlobalPairs ()
int size ()
Get the number of bonds in the GlobalPairs list.
int totalSize ()
void add (Particle *p1, Particle *p2)
void add (Particle &p1, Particle &p2)
void add (std::vector< Particle *> particles)
Static Public Member Functions
static void registerPython ()
Protected Types
typedef std::vector< ParticlePair > Super
Protected Attributes
boost::signals2::connection sigBeforeSend
boost::signals2::connection sigOnParticlesChanged
boost::signals2::connection sigAfterRecv
shared_ptr< storage::Storage > storage
GlobalPairs globalPairs
real longtimeMaxBondSqr
Static Private Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Detailed Description
Definition at line 40 of file FixedPairList.hpp.
Member Typedef Documentation
GlobalPairs
typedef boost::unordered_multimap<longint, longint> espressopp::FixedPairList::GlobalPairs
Definition at line 42 of file FixedPairList.hpp.
Iterator
typedef ESPPIterator<std::vector< ParticlePair > > espressopp::esutil::ESPPContainer< std::vector< ParticlePair > >::Iterator inherited
Definition at line 66 of file ESPPIterator.hpp.
Super
typedef std::vector< ParticlePair > espressopp::esutil::ESPPContainer< std::vector< ParticlePair > >::Super protected inherited
Definition at line 64 of file ESPPIterator.hpp.
Constructor & Destructor Documentation
FixedPairList()
espressopp::FixedPairList::FixedPairList (shared_ptr< storage::Storage > _storage)
Definition at line 54 of file FixedPairList.cpp.
References afterRecvParticles(), beforeSendParticles(), LOG4ESPP_INFO, onParticlesChanged(), sigAfterRecv, sigBeforeSend, sigOnParticlesChanged, and storage.
~FixedPairList()
espressopp::FixedPairList::~FixedPairList () virtual
Definition at line 67 of file FixedPairList.cpp.
References LOG4ESPP_INFO, sigAfterRecv, sigBeforeSend, and sigOnParticlesChanged.
Member Function Documentation
add() [1/4]
bool espressopp::FixedPairList::add (longint pid1, longint pid2) virtual
Add the given particle pair to the list on this processor if the particle with the lower id belongs to this processor.
Note that this routine does not check whether the pair is inserted on another processor as well.
Returns
whether the particle was inserted on this processor.
Reimplemented in espressopp::FixedPairListAdress.
Definition at line 98 of file FixedPairList.cpp.
References globalPairs, LOG4ESPP_DEBUG, LOG4ESPP_INFO, and storage.
Referenced by onParticlesChanged(), registerPython(), and resetLongtimeMaxBondSqr().
add() [2/4]
void espressopp::PairList::add (Particle * p1, Particle * p2) inline inherited
Definition at line 454 of file Particle.hpp.
Referenced by espressopp::FixedListComm::add(), espressopp::VerletList::checkPair(), espressopp::VerletListAdress::checkPair(), and espressopp::FixedListComm::onParticlesChanged().
add() [3/4]
void espressopp::PairList::add (Particle & p1, Particle & p2) inline inherited
Definition at line 458 of file Particle.hpp.
add() [4/4]
void espressopp::PairList::add (std::vector< Particle *> particles) inline inherited
Definition at line 461 of file Particle.hpp.
afterRecvParticles()
void espressopp::FixedPairList::afterRecvParticles (ParticleList & pl, class InBuffer & buf)
Definition at line 237 of file FixedPairList.cpp.
References globalPairs, LOG4ESPP_DEBUG, LOG4ESPP_ERROR, LOG4ESPP_INFO, espressopp::InBuffer::read(), and size().
Referenced by FixedPairList(), and espressopp::FixedPairListAdress::FixedPairListAdress().
beforeSendParticles()
void espressopp::FixedPairList::beforeSendParticles (ParticleList & pl, class OutBuffer & buf) virtual
Reimplemented in espressopp::FixedPairListAdress.
Definition at line 197 of file FixedPairList.cpp.
References globalPairs, espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_DEBUG, LOG4ESPP_INFO, and espressopp::OutBuffer::write().
Referenced by FixedPairList().
getAllBonds()
python::list espressopp::FixedPairList::getAllBonds ()
Definition at line 169 of file FixedPairList.cpp.
References espressopp::System::comm, globalPairs, and storage.
Referenced by registerPython().
getBonds()
python::list espressopp::FixedPairList::getBonds ()
Definition at line 148 of file FixedPairList.cpp.
References globalPairs.
Referenced by registerPython().
getGlobalPairs()
GlobalPairs* espressopp::FixedPairList::getGlobalPairs () inline
Definition at line 73 of file FixedPairList.hpp.
References globalPairs.
getLongtimeMaxBondSqr()
real espressopp::FixedPairList::getLongtimeMaxBondSqr ()
Definition at line 85 of file FixedPairList.cpp.
References longtimeMaxBondSqr.
Referenced by registerPython().
getPairList()
std::vector< longint > espressopp::FixedPairList::getPairList ()
Definition at line 160 of file FixedPairList.cpp.
References globalPairs.
LOG4ESPP_DECL_LOGGER()
static espressopp::FixedPairList::LOG4ESPP_DECL_LOGGER (theLogger) static private
Referenced by size().
onParticlesChanged()
void espressopp::FixedPairList::onParticlesChanged () virtual
Reimplemented in espressopp::FixedPairListAdress.
Definition at line 265 of file FixedPairList.cpp.
References add(), espressopp::esutil::Error::checkException(), espressopp::System::comm, globalPairs, LOG4ESPP_INFO, espressopp::esutil::Error::setException(), and storage.
Referenced by FixedPairList().
registerPython()
void espressopp::FixedPairList::registerPython () static
Definition at line 320 of file FixedPairList.cpp.
References add(), getAllBonds(), getBonds(), getLongtimeMaxBondSqr(), remove(), resetLongtimeMaxBondSqr(), size(), and totalSize().
Referenced by espressopp::registerPython(), and size().
remove()
void espressopp::FixedPairList::remove (void)
Definition at line 300 of file FixedPairList.cpp.
References globalPairs, sigAfterRecv, sigBeforeSend, and sigOnParticlesChanged.
Referenced by registerPython().
resetLongtimeMaxBondSqr()
void espressopp::FixedPairList::resetLongtimeMaxBondSqr ()
Definition at line 93 of file FixedPairList.cpp.
References add(), and longtimeMaxBondSqr.
Referenced by registerPython().
setLongtimeMaxBondSqr()
void espressopp::FixedPairList::setLongtimeMaxBondSqr (real d)
Definition at line 89 of file FixedPairList.cpp.
References longtimeMaxBondSqr.
size()
int espressopp::FixedPairList::size () inline
Get the number of bonds in the GlobalPairs list.
Definition at line 77 of file FixedPairList.hpp.
References LOG4ESPP_DECL_LOGGER(), registerPython(), and totalSize().
Referenced by afterRecvParticles(), and registerPython().
totalSize()
int espressopp::FixedPairList::totalSize ()
Definition at line 308 of file FixedPairList.cpp.
References espressopp::System::comm, globalPairs, and storage.
Referenced by registerPython(), and size().
Member Data Documentation
globalPairs
GlobalPairs espressopp::FixedPairList::globalPairs protected
Definition at line 47 of file FixedPairList.hpp.
Referenced by espressopp::FixedPairListAdress::add(), add(), afterRecvParticles(), espressopp::FixedPairListAdress::beforeSendATParticles(), beforeSendParticles(), getAllBonds(), espressopp::FixedPairListAdress::getBonds(), getBonds(), getGlobalPairs(), getPairList(), espressopp::FixedPairListAdress::onParticlesChanged(), onParticlesChanged(), espressopp::FixedPairListAdress::remove(), remove(), and totalSize().
longtimeMaxBondSqr
real espressopp::FixedPairList::longtimeMaxBondSqr protected
Definition at line 49 of file FixedPairList.hpp.
Referenced by getLongtimeMaxBondSqr(), resetLongtimeMaxBondSqr(), and setLongtimeMaxBondSqr().
sigAfterRecv
boost::signals2::connection espressopp::FixedPairList::sigAfterRecv protected
Definition at line 45 of file FixedPairList.hpp.
Referenced by FixedPairList(), espressopp::FixedPairListAdress::FixedPairListAdress(), espressopp::FixedPairListAdress::remove(), remove(), and ~FixedPairList().
sigBeforeSend
boost::signals2::connection espressopp::FixedPairList::sigBeforeSend protected
Definition at line 45 of file FixedPairList.hpp.
Referenced by FixedPairList(), espressopp::FixedPairListAdress::FixedPairListAdress(), espressopp::FixedPairListAdress::remove(), remove(), and ~FixedPairList().
sigOnParticlesChanged
boost::signals2::connection espressopp::FixedPairList::sigOnParticlesChanged protected
Definition at line 45 of file FixedPairList.hpp.
Referenced by FixedPairList(), espressopp::FixedPairListAdress::remove(), remove(), and ~FixedPairList().
storage
shared_ptr<storage::Storage> espressopp::FixedPairList::storage protected
Definition at line 46 of file FixedPairList.hpp.
Referenced by espressopp::FixedPairListAdress::add(), add(), FixedPairList(), getAllBonds(), espressopp::FixedPairListAdress::onParticlesChanged(), onParticlesChanged(), and totalSize().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/FixedPairList.hpp
/home/espressopp/espressopp/src/FixedPairList.cpp