ESPResSo++: espressopp::interaction::LennardJones Class Reference
espressopp::interaction::LennardJones Class Reference abstract
This class provides methods to compute forces and energies of the Lennard Jones potential.
#include <LennardJones.hpp>
Public Member Functions
LennardJones ()
LennardJones (real _epsilon, real _sigma, real _cutoff, real _shift)
LennardJones (real _epsilon, real _sigma, real _cutoff)
virtual ~LennardJones ()
void preset ()
void setEpsilon (real _epsilon)
real getEpsilon () const
void setSigma (real _sigma)
real getSigma () const
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &dist, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual real getCutoff () const =0
virtual void setShift (real _shift)
virtual real getShift () const
virtual real getShift () const =0
virtual real setAutoShift ()
void updateAutoShift ()
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)
virtual shared_ptr< FixedPairList > getColVarBondList () const
virtual shared_ptr< FixedPairList > getColVarBondList () const =0
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &fpl)
virtual shared_ptr< FixedTripleList > getColVarAngleList () const
virtual shared_ptr< FixedTripleList > getColVarAngleList () const =0
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fpl)
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const =0
virtual void setColVar (const RealND &cv)
virtual void setColVar (const Real3D &dist, const bc::BC &bc)
virtual RealND getColVar () const
virtual RealND getColVar () const =0
virtual void computeColVarWeights (const Real3D &dist, const bc::BC &bc)
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
real _computeEnergyDeriv (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
LennardJones * derived_this ()
const LennardJones * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
shared_ptr< FixedPairList > colVarBondList
shared_ptr< FixedTripleList > colVarAngleList
shared_ptr< FixedQuadrupleList > colVarDihedList
RealND colVar
Private Attributes
real epsilon
real sigma
real ff1
real ff2
real ef1
real ef2
Detailed Description
This class provides methods to compute forces and energies of the Lennard Jones potential.
Definition at line 41 of file LennardJones.hpp.
Constructor & Destructor Documentation
LennardJones() [1/3]
espressopp::interaction::LennardJones::LennardJones () inline
Definition at line 51 of file LennardJones.hpp.
References espressopp::infinity, preset(), espressopp::interaction::PotentialTemplate< LennardJones >::setCutoff(), and espressopp::interaction::PotentialTemplate< LennardJones >::setShift().
LennardJones() [2/3]
espressopp::interaction::LennardJones::LennardJones (real _epsilon, real _sigma, real _cutoff, real _shift) inline
Definition at line 58 of file LennardJones.hpp.
References preset(), espressopp::interaction::PotentialTemplate< LennardJones >::setCutoff(), and espressopp::interaction::PotentialTemplate< LennardJones >::setShift().
LennardJones() [3/3]
espressopp::interaction::LennardJones::LennardJones (real _epsilon, real _sigma, real _cutoff) inline
Definition at line 66 of file LennardJones.hpp.
References espressopp::interaction::PotentialTemplate< LennardJones >::autoShift, preset(), espressopp::interaction::PotentialTemplate< LennardJones >::setAutoShift(), and espressopp::interaction::PotentialTemplate< LennardJones >::setCutoff().
~LennardJones()
virtual espressopp::interaction::LennardJones::~LennardJones () inline virtual
Definition at line 75 of file LennardJones.hpp.
Member Function Documentation
_computeEnergy() [1/4]
real espressopp::interaction::PotentialTemplate< LennardJones >::_computeEnergy (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 352 of file Potential.hpp.
_computeEnergy() [2/4]
real espressopp::interaction::PotentialTemplate< LennardJones >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 360 of file Potential.hpp.
_computeEnergy() [3/4]
real espressopp::interaction::PotentialTemplate< LennardJones >::_computeEnergy (const Real3D & dist) const inline inherited
Definition at line 367 of file Potential.hpp.
_computeEnergy() [4/4]
real espressopp::interaction::PotentialTemplate< LennardJones >::_computeEnergy (real dist) const inline inherited
Definition at line 374 of file Potential.hpp.
_computeEnergyDeriv()
real espressopp::interaction::PotentialTemplate< LennardJones >::_computeEnergyDeriv (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 395 of file Potential.hpp.
_computeEnergySqr()
real espressopp::interaction::PotentialTemplate< LennardJones >::_computeEnergySqr (real distSqr) const inline inherited
Definition at line 381 of file Potential.hpp.
_computeEnergySqrRaw()
real espressopp::interaction::LennardJones::_computeEnergySqrRaw (real distSqr) const inline
Definition at line 104 of file LennardJones.hpp.
References epsilon, and sigma.
_computeForce() [1/3]
bool espressopp::interaction::PotentialTemplate< LennardJones >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const inline inherited
Definition at line 423 of file Potential.hpp.
_computeForce() [2/3]
bool espressopp::interaction::PotentialTemplate< LennardJones >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 431 of file Potential.hpp.
_computeForce() [3/3]
bool espressopp::interaction::PotentialTemplate< LennardJones >::_computeForce (Real3D & force, const Real3D & dist) const inline inherited
Definition at line 438 of file Potential.hpp.
_computeForceRaw()
bool espressopp::interaction::LennardJones::_computeForceRaw (Real3D & force, const Real3D & dist, real distSqr) const inline
Definition at line 132 of file LennardJones.hpp.
References ff1, and ff2.
computeColVarWeights()
void espressopp::interaction::PotentialTemplate< LennardJones >::computeColVarWeights (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 315 of file Potential.hpp.
computeEnergy() [1/3]
real espressopp::interaction::PotentialTemplate< LennardJones >::computeEnergy (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 323 of file Potential.hpp.
computeEnergy() [2/3]
real espressopp::interaction::PotentialTemplate< LennardJones >::computeEnergy (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 331 of file Potential.hpp.
computeEnergy() [3/3]
real espressopp::interaction::PotentialTemplate< LennardJones >::computeEnergy (real dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 338 of file Potential.hpp.
computeEnergySqr()
real espressopp::interaction::PotentialTemplate< LennardJones >::computeEnergySqr (real distsqr) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 345 of file Potential.hpp.
computeForce() [1/2]
Real3D espressopp::interaction::PotentialTemplate< LennardJones >::computeForce (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 405 of file Potential.hpp.
computeForce() [2/2]
Real3D espressopp::interaction::PotentialTemplate< LennardJones >::computeForce (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 413 of file Potential.hpp.
derived_this() [1/2]
LennardJones * espressopp::interaction::PotentialTemplate< LennardJones >::derived_this inline protected inherited
Definition at line 161 of file Potential.hpp.
derived_this() [2/2]
const LennardJones * espressopp::interaction::PotentialTemplate< LennardJones >::derived_this inline protected inherited
Definition at line 165 of file Potential.hpp.
getColVar() [1/2]
RealND espressopp::interaction::PotentialTemplate< LennardJones >::getColVar inline virtual inherited
Definition at line 309 of file Potential.hpp.
getColVar() [2/2]
virtual RealND espressopp::interaction::Potential::getColVar () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getColVarAngleList() [1/2]
shared_ptr< FixedTripleList > espressopp::interaction::PotentialTemplate< LennardJones >::getColVarAngleList inline virtual inherited
Definition at line 273 of file Potential.hpp.
getColVarAngleList() [2/2]
virtual shared_ptr<FixedTripleList> espressopp::interaction::Potential::getColVarAngleList () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getColVarBondList() [1/2]
shared_ptr< FixedPairList > espressopp::interaction::PotentialTemplate< LennardJones >::getColVarBondList inline virtual inherited
Definition at line 259 of file Potential.hpp.
getColVarBondList() [2/2]
virtual shared_ptr<FixedPairList> espressopp::interaction::Potential::getColVarBondList () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getColVarDihedList() [1/2]
shared_ptr< FixedQuadrupleList > espressopp::interaction::PotentialTemplate< LennardJones >::getColVarDihedList inline virtual inherited
Definition at line 287 of file Potential.hpp.
getColVarDihedList() [2/2]
virtual shared_ptr<FixedQuadrupleList> espressopp::interaction::Potential::getColVarDihedList () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getCutoff() [1/2]
real espressopp::interaction::PotentialTemplate< LennardJones >::getCutoff inline virtual inherited
Definition at line 210 of file Potential.hpp.
getCutoff() [2/2]
virtual real espressopp::interaction::Potential::getCutoff () const pure virtual inherited
Implemented in espressopp::interaction::CoulombKSpaceP3M, and espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getEpsilon()
real espressopp::interaction::LennardJones::getEpsilon () const inline
Definition at line 94 of file LennardJones.hpp.
References epsilon.
Referenced by espressopp::interaction::LennardJones_pickle::getinitargs(), and registerPython().
getShift() [1/2]
real espressopp::interaction::PotentialTemplate< LennardJones >::getShift inline virtual inherited
Definition at line 225 of file Potential.hpp.
getShift() [2/2]
virtual real espressopp::interaction::Potential::getShift () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getSigma()
real espressopp::interaction::LennardJones::getSigma () const inline
Definition at line 102 of file LennardJones.hpp.
References sigma.
Referenced by espressopp::interaction::LennardJones_pickle::getinitargs(), and registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::LennardJones::LOG4ESPP_DECL_LOGGER (theLogger) static
preset()
void espressopp::interaction::LennardJones::preset () inline
Definition at line 77 of file LennardJones.hpp.
References ef1, ef2, epsilon, ff1, ff2, and sigma.
Referenced by LennardJones(), setEpsilon(), and setSigma().
registerPython()
void espressopp::interaction::LennardJones::registerPython () static
Definition at line 93 of file LennardJones.cpp.
References getEpsilon(), getSigma(), setEpsilon(), and setSigma().
Referenced by espressopp::interaction::registerPython().
setAutoShift()
real espressopp::interaction::PotentialTemplate< LennardJones >::setAutoShift inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 231 of file Potential.hpp.
setColVar() [1/2]
void espressopp::interaction::PotentialTemplate< LennardJones >::setColVar (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 301 of file Potential.hpp.
setColVar() [2/2]
void espressopp::interaction::PotentialTemplate< LennardJones >::setColVar (const RealND & cv) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 294 of file Potential.hpp.
setColVarAngleList()
void espressopp::interaction::PotentialTemplate< LennardJones >::setColVarAngleList (const shared_ptr< FixedTripleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 266 of file Potential.hpp.
setColVarBondList()
void espressopp::interaction::PotentialTemplate< LennardJones >::setColVarBondList (const shared_ptr< FixedPairList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 252 of file Potential.hpp.
setColVarDihedList()
void espressopp::interaction::PotentialTemplate< LennardJones >::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 280 of file Potential.hpp.
setCutoff()
void espressopp::interaction::PotentialTemplate< LennardJones >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 201 of file Potential.hpp.
setEpsilon()
void espressopp::interaction::LennardJones::setEpsilon (real _epsilon) inline
Definition at line 87 of file LennardJones.hpp.
References epsilon, LOG4ESPP_INFO, preset(), and espressopp::interaction::PotentialTemplate< LennardJones >::updateAutoShift().
Referenced by registerPython().
setShift()
void espressopp::interaction::PotentialTemplate< LennardJones >::setShift (real _shift) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 216 of file Potential.hpp.
setSigma()
void espressopp::interaction::LennardJones::setSigma (real _sigma) inline
Definition at line 96 of file LennardJones.hpp.
References LOG4ESPP_INFO, preset(), sigma, and espressopp::interaction::PotentialTemplate< LennardJones >::updateAutoShift().
Referenced by registerPython().
updateAutoShift()
void espressopp::interaction::PotentialTemplate< LennardJones >::updateAutoShift inline inherited
Definition at line 244 of file Potential.hpp.
Member Data Documentation
autoShift
bool espressopp::interaction::PotentialTemplate< LennardJones >::autoShift protected inherited
Definition at line 151 of file Potential.hpp.
colVar
RealND espressopp::interaction::PotentialTemplate< LennardJones >::colVar protected inherited
Definition at line 159 of file Potential.hpp.
colVarAngleList
shared_ptr<FixedTripleList> espressopp::interaction::PotentialTemplate< LennardJones >::colVarAngleList protected inherited
Definition at line 155 of file Potential.hpp.
colVarBondList
shared_ptr<FixedPairList> espressopp::interaction::PotentialTemplate< LennardJones >::colVarBondList protected inherited
Definition at line 153 of file Potential.hpp.
colVarDihedList
shared_ptr<FixedQuadrupleList> espressopp::interaction::PotentialTemplate< LennardJones >::colVarDihedList protected inherited
Definition at line 157 of file Potential.hpp.
cutoff
real espressopp::interaction::PotentialTemplate< LennardJones >::cutoff protected inherited
Definition at line 148 of file Potential.hpp.
cutoffSqr
real espressopp::interaction::PotentialTemplate< LennardJones >::cutoffSqr protected inherited
Definition at line 149 of file Potential.hpp.
ef1
real espressopp::interaction::LennardJones::ef1 private
Definition at line 46 of file LennardJones.hpp.
Referenced by preset().
ef2
real espressopp::interaction::LennardJones::ef2 private
Definition at line 46 of file LennardJones.hpp.
Referenced by preset().
epsilon
real espressopp::interaction::LennardJones::epsilon private
Definition at line 43 of file LennardJones.hpp.
Referenced by _computeEnergySqrRaw(), getEpsilon(), preset(), and setEpsilon().
ff1
real espressopp::interaction::LennardJones::ff1 private
Definition at line 45 of file LennardJones.hpp.
Referenced by _computeForceRaw(), and preset().
ff2
real espressopp::interaction::LennardJones::ff2 private
Definition at line 45 of file LennardJones.hpp.
Referenced by _computeForceRaw(), and preset().
shift
real espressopp::interaction::PotentialTemplate< LennardJones >::shift protected inherited
Definition at line 150 of file Potential.hpp.
sigma
real espressopp::interaction::LennardJones::sigma private
Definition at line 44 of file LennardJones.hpp.
Referenced by _computeEnergySqrRaw(), getSigma(), preset(), and setSigma().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/LennardJones.hpp
/home/espressopp/espressopp/src/interaction/LennardJones.cpp