ESPResSo++: espressopp::integrator::PIAdressIntegrator Class Reference
espressopp::integrator::PIAdressIntegrator Class Reference
#include <PIAdressIntegrator.hpp>
Public Member Functions
PIAdressIntegrator (shared_ptr< class espressopp::System > system, shared_ptr< VerletListAdress > _verletList)
virtual ~PIAdressIntegrator ()
void run (int nsteps)
This method runs the integration for a certain number of steps.
void addEVcomponent (real val)
void addTransposedEigenVector ()
void addEigenValues (real val)
void transp ()
int getVerletlistBuilds ()
void setTimeStep (real _dt)
real getTimeStep ()
void setmStep (int _mStep)
int getmStep ()
void setsStep (int _sStep)
int getsStep ()
void setNtrotter (int _ntrotter)
int getNtrotter ()
void setTemperature (real _temperature)
real getTemperature ()
void setGamma (real _gamma)
real getGamma ()
void setCMDparameter (real _CMDparameter)
real getCMDparameter ()
void setPILElambda (real _PILElambda)
real getPILElambda ()
void setClmassmultiplier (real _clmassmultiplier)
real getClmassmultiplier ()
void setSpeedup (bool _speedup)
bool getSpeedup ()
void setKTI (bool _KTI)
bool getKTI ()
void setCentroidThermostat (bool _centroidthermostat)
bool getCentroidThermostat ()
void setPILE (bool _PILE)
bool getPILE ()
void setRealKinMass (bool _realkinmass)
bool getRealKinMass ()
void setConstKinMass (bool _constkinmass)
bool getConstKinMass ()
void setVerletList (shared_ptr< VerletListAdress > _verletList)
shared_ptr< VerletListAdress > getVerletList ()
real computeRingEnergy ()
real computeRingEnergyRaw ()
real computeKineticEnergy ()
real computePositionDrift (int parttype)
real computeMomentumDrift (int parttype)
void setStep (long long step_)
Getter routine for integration step.
long long getStep ()
Getter routine for integration step.
void addExtension (shared_ptr< integrator::Extension > extension)
shared_ptr< integrator::Extension > getExtension (int k)
int getNumberOfExtensions ()
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
Register this class so it can be used from Python.
Public Attributes
shared_ptr< VerletListAdress > verletList
boost::signals2::signal< void()> runInit
boost::signals2::signal< void()> recalc1
boost::signals2::signal< void()> aftCalcSlow
boost::signals2::signal< void()> recalc2
boost::signals2::signal< void()> befIntP
boost::signals2::signal< void(real &)> inIntP
boost::signals2::signal< void()> aftIntP
boost::signals2::signal< void()> aftInitF
boost::signals2::signal< void()> aftCalcF
boost::signals2::signal< void()> befIntV
boost::signals2::signal< void()> aftIntV
boost::signals2::signal< void()> aftIntSlow
Protected Member Functions
void integrateV1 (int t, bool doubletime)
void integrateV2 ()
void integrateModePos ()
void OUintegrate ()
void initForces (int f)
void updateForces (int f)
void distributeForces ()
void calcForcesF ()
void calcForcesM ()
void calcForcesS ()
void transForces ()
void transPos1 ()
void transPos2 ()
void transMom1 ()
void transMom2 ()
void initializeSetup ()
void setWeights ()
void setOmegaSquared ()
real weight (real distanceSqr)
real weightderivative (real distanceSqr)
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Protected Attributes
int sStep
int mStep
int ntrotter
int verletlistBuilds
bool resortFlag
bool speedup
bool KTI
bool constkinmass
bool realkinmass
bool centroidthermostat
bool PILE
real omega2
real clmassmultiplier
real CMDparameter
real PILElambda
real gamma
real temperature
real maxDist
real dt2
real dt3
real dhy
real pidhy2
real dex
real dex2
real dexdhy
real dexdhy2
std::vector< std::vector< real > > Eigenvectors
std::vector< std::vector< real > > Tvectors
std::vector< real > Eigenvalues
std::vector< real > tmpvals
shared_ptr< esutil::RNG > rng
bool timeFlag
ExtensionList exList
long long step
Integration step.
real dt
Timestep used for integration.
Detailed Description
Definition at line 32 of file PIAdressIntegrator.hpp.
Constructor & Destructor Documentation
PIAdressIntegrator()
espressopp::integrator::PIAdressIntegrator::PIAdressIntegrator (shared_ptr< class espressopp::System > system, shared_ptr< VerletListAdress > _verletList)
Definition at line 40 of file PIAdressIntegrator.cpp.
References centroidthermostat, clmassmultiplier, CMDparameter, constkinmass, dex, dex2, dexdhy, dexdhy2, dhy, espressopp::integrator::MDIntegrator::dt, dt2, dt3, gamma, KTI, M_PI, maxDist, mStep, ntrotter, pidhy2, PILE, PILElambda, realkinmass, resortFlag, rng, setOmegaSquared(), speedup, sStep, temperature, verletList, and verletlistBuilds.
~PIAdressIntegrator()
espressopp::integrator::PIAdressIntegrator::~PIAdressIntegrator () virtual
Definition at line 82 of file PIAdressIntegrator.cpp.
Member Function Documentation
addEigenValues()
void espressopp::integrator::PIAdressIntegrator::addEigenValues (real val) inline
Definition at line 45 of file PIAdressIntegrator.hpp.
References Eigenvalues, and transp().
Referenced by registerPython().
addEVcomponent()
void espressopp::integrator::PIAdressIntegrator::addEVcomponent (real val) inline
Definition at line 43 of file PIAdressIntegrator.hpp.
References tmpvals.
Referenced by registerPython().
addExtension()
void espressopp::integrator::MDIntegrator::addExtension (shared_ptr< integrator::Extension > extension) inherited
Definition at line 68 of file MDIntegrator.cpp.
References espressopp::integrator::MDIntegrator::exList.
Referenced by espressopp::integrator::MDIntegrator::registerPython().
addTransposedEigenVector()
void espressopp::integrator::PIAdressIntegrator::addTransposedEigenVector () inline
Definition at line 44 of file PIAdressIntegrator.hpp.
References tmpvals, and Tvectors.
Referenced by registerPython().
calcForcesF()
void espressopp::integrator::PIAdressIntegrator::calcForcesF () protected
Definition at line 1072 of file PIAdressIntegrator.cpp.
References clmassmultiplier, Eigenvalues, espressopp::Particle::forcem(), espressopp::SystemAccess::getSystemRef(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::iterator::CellListIterator::isDone(), espressopp::Particle::lambda(), espressopp::Particle::lambdaDeriv(), espressopp::Particle::mass(), espressopp::Particle::modepos(), ntrotter, omega2, espressopp::Particle::pib(), espressopp::Particle::position(), speedup, espressopp::Real3D::sqr(), espressopp::System::storage, espressopp::Particle::varmass(), and verletList.
Referenced by updateForces().
calcForcesM()
void espressopp::integrator::PIAdressIntegrator::calcForcesM () protected
Definition at line 1058 of file PIAdressIntegrator.cpp.
References espressopp::integrator::MDIntegrator::aftCalcF, espressopp::interaction::Angular, espressopp::SystemAccess::getSystemRef(), espressopp::interaction::Pair, and espressopp::System::shortRangeInteractions.
Referenced by updateForces().
calcForcesS()
void espressopp::integrator::PIAdressIntegrator::calcForcesS () protected
Definition at line 1047 of file PIAdressIntegrator.cpp.
References espressopp::SystemAccess::getSystemRef(), espressopp::interaction::Nonbonded, and espressopp::System::shortRangeInteractions.
Referenced by updateForces().
computeKineticEnergy()
real espressopp::integrator::PIAdressIntegrator::computeKineticEnergy ()
Definition at line 1354 of file PIAdressIntegrator.cpp.
References CMDparameter, constkinmass, Eigenvalues, espressopp::SystemAccess::getSystem(), espressopp::SystemAccess::getSystemRef(), getVerletList(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::iterator::CellListIterator::isDone(), espressopp::Particle::lambda(), espressopp::Particle::mass(), espressopp::Particle::modemom(), ntrotter, espressopp::Particle::pib(), espressopp::Particle::position(), realkinmass, speedup, espressopp::Real3D::sqr(), espressopp::System::storage, and espressopp::Particle::varmass().
Referenced by getVerletList(), and registerPython().
computeMomentumDrift()
real espressopp::integrator::PIAdressIntegrator::computeMomentumDrift (int parttype)
Definition at line 1497 of file PIAdressIntegrator.cpp.
References clmassmultiplier, CMDparameter, Eigenvalues, espressopp::SystemAccess::getSystem(), espressopp::SystemAccess::getSystemRef(), getVerletList(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::iterator::CellListIterator::isDone(), espressopp::Particle::mass(), espressopp::Particle::modemom(), ntrotter, espressopp::Particle::pib(), espressopp::Particle::position(), realkinmass, espressopp::Real3D::sqr(), espressopp::System::storage, espressopp::Particle::type(), and espressopp::Particle::varmass().
Referenced by getVerletList(), and registerPython().
computePositionDrift()
real espressopp::integrator::PIAdressIntegrator::computePositionDrift (int parttype)
Definition at line 1542 of file PIAdressIntegrator.cpp.
References clmassmultiplier, Eigenvalues, espressopp::SystemAccess::getSystem(), espressopp::SystemAccess::getSystemRef(), getVerletList(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::iterator::CellListIterator::isDone(), espressopp::Particle::mass(), espressopp::Particle::modepos(), ntrotter, omega2, espressopp::Particle::pib(), espressopp::Particle::position(), espressopp::Real3D::sqr(), espressopp::System::storage, and espressopp::Particle::type().
Referenced by getVerletList(), and registerPython().
computeRingEnergy()
real espressopp::integrator::PIAdressIntegrator::computeRingEnergy ()
Definition at line 1411 of file PIAdressIntegrator.cpp.
References Eigenvalues, espressopp::SystemAccess::getSystem(), espressopp::SystemAccess::getSystemRef(), getVerletList(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::iterator::CellListIterator::isDone(), espressopp::Particle::modepos(), ntrotter, omega2, espressopp::Particle::pib(), espressopp::Particle::position(), espressopp::Real3D::sqr(), espressopp::System::storage, and espressopp::Particle::varmass().
Referenced by getVerletList(), and registerPython().
computeRingEnergyRaw()
real espressopp::integrator::PIAdressIntegrator::computeRingEnergyRaw ()
Definition at line 1450 of file PIAdressIntegrator.cpp.
References espressopp::SystemAccess::getSystem(), espressopp::SystemAccess::getSystemRef(), getVerletList(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::iterator::CellListIterator::isDone(), ntrotter, omega2, espressopp::Particle::pib(), espressopp::Particle::position(), espressopp::System::storage, and espressopp::Particle::varmass().
Referenced by getVerletList(), and registerPython().
distributeForces()
void espressopp::integrator::PIAdressIntegrator::distributeForces () protected
Definition at line 1279 of file PIAdressIntegrator.cpp.
References espressopp::Particle::force(), espressopp::SystemAccess::getSystemRef(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::iterator::CellListIterator::isDone(), ntrotter, espressopp::Particle::position(), and espressopp::System::storage.
Referenced by updateForces().
getCentroidThermostat()
bool espressopp::integrator::PIAdressIntegrator::getCentroidThermostat () inline
Definition at line 84 of file PIAdressIntegrator.hpp.
References centroidthermostat, and setPILE().
Referenced by registerPython().
getClmassmultiplier()
real espressopp::integrator::PIAdressIntegrator::getClmassmultiplier () inline
Definition at line 75 of file PIAdressIntegrator.hpp.
References clmassmultiplier, and setSpeedup().
Referenced by registerPython().
getCMDparameter()
real espressopp::integrator::PIAdressIntegrator::getCMDparameter () inline
Definition at line 69 of file PIAdressIntegrator.hpp.
References CMDparameter, and setPILElambda().
Referenced by registerPython().
getConstKinMass()
bool espressopp::integrator::PIAdressIntegrator::getConstKinMass () inline
Definition at line 93 of file PIAdressIntegrator.hpp.
References constkinmass, and setVerletList().
Referenced by registerPython().
getExtension()
shared_ptr< integrator::Extension > espressopp::integrator::MDIntegrator::getExtension (int k) inherited
Definition at line 92 of file MDIntegrator.cpp.
References espressopp::integrator::MDIntegrator::exList.
Referenced by espressopp::integrator::MDIntegrator::registerPython().
getGamma()
real espressopp::integrator::PIAdressIntegrator::getGamma () inline
Definition at line 66 of file PIAdressIntegrator.hpp.
References gamma, and setCMDparameter().
Referenced by registerPython().
getKTI()
bool espressopp::integrator::PIAdressIntegrator::getKTI () inline
Definition at line 81 of file PIAdressIntegrator.hpp.
References KTI, and setCentroidThermostat().
Referenced by registerPython().
getmStep()
int espressopp::integrator::PIAdressIntegrator::getmStep () inline
Definition at line 54 of file PIAdressIntegrator.hpp.
References mStep, and setsStep().
Referenced by registerPython().
getNtrotter()
int espressopp::integrator::PIAdressIntegrator::getNtrotter () inline
Definition at line 60 of file PIAdressIntegrator.hpp.
References ntrotter, and setTemperature().
Referenced by registerPython().
getNumberOfExtensions()
int espressopp::integrator::MDIntegrator::getNumberOfExtensions () inherited
Definition at line 88 of file MDIntegrator.cpp.
References espressopp::integrator::MDIntegrator::exList.
Referenced by espressopp::integrator::MDIntegrator::registerPython().
getPILE()
bool espressopp::integrator::PIAdressIntegrator::getPILE () inline
Definition at line 87 of file PIAdressIntegrator.hpp.
References PILE, and setRealKinMass().
Referenced by registerPython().
getPILElambda()
real espressopp::integrator::PIAdressIntegrator::getPILElambda () inline
Definition at line 72 of file PIAdressIntegrator.hpp.
References PILElambda, and setClmassmultiplier().
Referenced by registerPython().
getRealKinMass()
bool espressopp::integrator::PIAdressIntegrator::getRealKinMass () inline
Definition at line 90 of file PIAdressIntegrator.hpp.
References realkinmass, and setConstKinMass().
Referenced by registerPython().
getSpeedup()
bool espressopp::integrator::PIAdressIntegrator::getSpeedup () inline
Definition at line 78 of file PIAdressIntegrator.hpp.
References setKTI(), and speedup.
Referenced by registerPython().
getsStep()
int espressopp::integrator::PIAdressIntegrator::getsStep () inline
Definition at line 57 of file PIAdressIntegrator.hpp.
References setNtrotter(), and sStep.
Referenced by registerPython().
getStep()
long long espressopp::integrator::MDIntegrator::getStep () inline inherited
Getter routine for integration step.
Definition at line 73 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::MDIntegrator::registerPython().
getSystem()
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::LatticeBoltzmann::assignMyLattice(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), computeKineticEnergy(), computeMomentumDrift(), computePositionDrift(), computeRingEnergy(), computeRingEnergyRaw(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpXTCAdress::dump(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::io::DumpXYZ::DumpXYZ(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::VerletListTriple::registerPython(), espressopp::VerletList::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
getSystem1()
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
getSystem2()
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
getSystemRef()
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::addForces(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::addForces(), espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerletRESPA::calcForces(), espressopp::integrator::VelocityVerlet::calcForces(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), calcForcesF(), calcForcesM(), calcForcesS(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeCOM(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeEnergy(), computeKineticEnergy(), computeMomentumDrift(), computePositionDrift(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), computeRingEnergy(), computeRingEnergyRaw(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), distributeForces(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::FixedLocalTupleComListInteractionTemplate(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::VelocityVerletRESPA::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerlet::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), initializeSetup(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::VelocityVerletRESPA::integrate1(), espressopp::integrator::VelocityVerlet::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::VelocityVerletRESPA::integrate2(), espressopp::integrator::VelocityVerlet::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::integrator::Adress::integrate2(), integrateModePos(), espressopp::integrator::Adress::integrateSlow(), integrateV1(), integrateV2(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), OUintegrate(), espressopp::integrator::VelocityVerlet::printForces(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerlet::printPositions(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), run(), espressopp::integrator::VelocityVerletRESPA::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::MinimizeEnergy::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::Rattle::saveOldPos(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), setWeights(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostatOnGroup::thermalize(), espressopp::integrator::LangevinThermostatOnRadius::thermalize(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), transForces(), transMom1(), transMom2(), transPos1(), transPos2(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::io::DumpH5MD::update(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::VelocityVerletRESPA::updateForces(), espressopp::integrator::VelocityVerlet::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
getSystemRef1()
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
getSystemRef2()
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
getTemperature()
real espressopp::integrator::PIAdressIntegrator::getTemperature () inline
Definition at line 63 of file PIAdressIntegrator.hpp.
References setGamma(), and temperature.
Referenced by registerPython().
getTimeStep()
real espressopp::integrator::PIAdressIntegrator::getTimeStep () inline
Definition at line 51 of file PIAdressIntegrator.hpp.
References espressopp::integrator::MDIntegrator::dt, and setmStep().
Referenced by registerPython().
getVerletList()
shared_ptr<VerletListAdress> espressopp::integrator::PIAdressIntegrator::getVerletList () inline
Definition at line 96 of file PIAdressIntegrator.hpp.
References computeKineticEnergy(), computeMomentumDrift(), computePositionDrift(), computeRingEnergy(), computeRingEnergyRaw(), registerPython(), and verletList.
Referenced by computeKineticEnergy(), computeMomentumDrift(), computePositionDrift(), computeRingEnergy(), computeRingEnergyRaw(), and registerPython().
getVerletlistBuilds()
int espressopp::integrator::PIAdressIntegrator::getVerletlistBuilds () inline
Definition at line 48 of file PIAdressIntegrator.hpp.
References setTimeStep(), and verletlistBuilds.
Referenced by registerPython().
initForces()
void espressopp::integrator::PIAdressIntegrator::initForces (int f) protected
Definition at line 1308 of file PIAdressIntegrator.cpp.
References espressopp::SystemAccess::getSystemRef(), espressopp::iterator::CellListIterator::isDone(), and espressopp::System::storage.
Referenced by updateForces().
initializeSetup()
void espressopp::integrator::PIAdressIntegrator::initializeSetup () protected
Definition at line 185 of file PIAdressIntegrator.cpp.
References clmassmultiplier, espressopp::SystemAccess::getSystemRef(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::iterator::CellListIterator::isDone(), KTI, espressopp::Particle::lambda(), espressopp::Particle::lambdaDeriv(), espressopp::Particle::mass(), ntrotter, espressopp::Particle::position(), espressopp::Real3D::sqr(), espressopp::System::storage, espressopp::Particle::varmass(), espressopp::Particle::velocity(), verletList, weight(), and weightderivative().
Referenced by run().
integrateModePos()
void espressopp::integrator::PIAdressIntegrator::integrateModePos () protected
!!!
Definition at line 476 of file PIAdressIntegrator.cpp.
References clmassmultiplier, CMDparameter, constkinmass, espressopp::integrator::MDIntegrator::dt, Eigenvalues, espressopp::SystemAccess::getSystemRef(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::iterator::CellListIterator::isDone(), KTI, espressopp::Particle::lambda(), espressopp::Particle::lambdaDeriv(), espressopp::Particle::mass(), espressopp::Particle::modemom(), espressopp::Particle::modepos(), ntrotter, espressopp::Particle::pib(), espressopp::Particle::position(), realkinmass, speedup, espressopp::Real3D::sqr(), espressopp::System::storage, espressopp::Particle::varmass(), verletList, weight(), and weightderivative().
Referenced by run().
integrateV1()
void espressopp::integrator::PIAdressIntegrator::integrateV1 (int t, bool doubletime) protected
Definition at line 258 of file PIAdressIntegrator.cpp.
References dt2, dt3, espressopp::Particle::forcem(), espressopp::SystemAccess::getSystemRef(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::iterator::CellListIterator::isDone(), espressopp::Particle::lambda(), espressopp::Particle::mass(), espressopp::Particle::modemom(), ntrotter, espressopp::Particle::pib(), espressopp::Particle::position(), speedup, espressopp::System::storage, and espressopp::Particle::velocity().
Referenced by run().
integrateV2()
void espressopp::integrator::PIAdressIntegrator::integrateV2 () protected
Definition at line 316 of file PIAdressIntegrator.cpp.
References clmassmultiplier, CMDparameter, constkinmass, espressopp::integrator::MDIntegrator::dt, Eigenvalues, espressopp::Particle::forcem(), espressopp::SystemAccess::getSystemRef(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::iterator::CellListIterator::isDone(), espressopp::Particle::lambda(), espressopp::Particle::lambdaDeriv(), espressopp::Particle::mass(), espressopp::Particle::modemom(), espressopp::Particle::modepos(), ntrotter, espressopp::Particle::pib(), espressopp::Particle::position(), realkinmass, speedup, espressopp::Real3D::sqr(), espressopp::System::storage, espressopp::Particle::varmass(), espressopp::Particle::velocity(), and verletList.
Referenced by run().
LOG4ESPP_DECL_LOGGER()
static espressopp::integrator::MDIntegrator::LOG4ESPP_DECL_LOGGER (theLogger) static protected inherited
Logger.
OUintegrate()
void espressopp::integrator::PIAdressIntegrator::OUintegrate () protected
Definition at line 690 of file PIAdressIntegrator.cpp.
References centroidthermostat, CMDparameter, constkinmass, espressopp::integrator::MDIntegrator::dt, Eigenvalues, gamma, espressopp::SystemAccess::getSystemRef(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::iterator::CellListIterator::isDone(), espressopp::Particle::lambda(), espressopp::Particle::mass(), espressopp::Particle::modemom(), ntrotter, omega2, espressopp::Particle::pib(), PILE, PILElambda, espressopp::Particle::position(), realkinmass, rng, speedup, espressopp::System::storage, temperature, espressopp::Particle::varmass(), and espressopp::Particle::velocity().
Referenced by run().
registerPython()
void espressopp::integrator::PIAdressIntegrator::registerPython () static
Register this class so it can be used from Python.
Definition at line 1772 of file PIAdressIntegrator.cpp.
References addEigenValues(), addEVcomponent(), addTransposedEigenVector(), computeKineticEnergy(), computeMomentumDrift(), computePositionDrift(), computeRingEnergy(), computeRingEnergyRaw(), getCentroidThermostat(), getClmassmultiplier(), getCMDparameter(), getConstKinMass(), getGamma(), getKTI(), getmStep(), getNtrotter(), getPILE(), getPILElambda(), getRealKinMass(), getSpeedup(), getsStep(), getTemperature(), getTimeStep(), getVerletList(), getVerletlistBuilds(), setCentroidThermostat(), setClmassmultiplier(), setCMDparameter(), setConstKinMass(), setGamma(), setKTI(), setmStep(), setNtrotter(), setPILE(), setPILElambda(), setRealKinMass(), setSpeedup(), setsStep(), setTemperature(), setTimeStep(), setVerletList(), and transp().
Referenced by getVerletList(), and espressopp::integrator::registerPython().
run()
void espressopp::integrator::PIAdressIntegrator::run (int nsteps) virtual
This method runs the integration for a certain number of steps.
Implements espressopp::integrator::MDIntegrator.
Definition at line 85 of file PIAdressIntegrator.cpp.
References espressopp::storage::Storage::decompose(), Eigenvalues, espressopp::System::getSkin(), espressopp::SystemAccess::getSystemRef(), initializeSetup(), integrateModePos(), integrateV1(), integrateV2(), maxDist, mStep, OUintegrate(), PILE, realkinmass, resortFlag, sStep, espressopp::integrator::MDIntegrator::step, espressopp::System::storage, transMom1(), transMom2(), transPos1(), transPos2(), updateForces(), and verletlistBuilds.
setCentroidThermostat()
void espressopp::integrator::PIAdressIntegrator::setCentroidThermostat (bool _centroidthermostat)
Definition at line 1699 of file PIAdressIntegrator.cpp.
References centroidthermostat.
Referenced by getKTI(), and registerPython().
setClmassmultiplier()
void espressopp::integrator::PIAdressIntegrator::setClmassmultiplier (real _clmassmultiplier)
Definition at line 1738 of file PIAdressIntegrator.cpp.
References clmassmultiplier.
Referenced by getPILElambda(), and registerPython().
setCMDparameter()
void espressopp::integrator::PIAdressIntegrator::setCMDparameter (real _CMDparameter)
Definition at line 1728 of file PIAdressIntegrator.cpp.
References CMDparameter.
Referenced by getGamma(), and registerPython().
setConstKinMass()
void espressopp::integrator::PIAdressIntegrator::setConstKinMass (bool _constkinmass)
Definition at line 1704 of file PIAdressIntegrator.cpp.
References constkinmass.
Referenced by getRealKinMass(), and registerPython().
setGamma()
void espressopp::integrator::PIAdressIntegrator::setGamma (real _gamma)
Definition at line 1723 of file PIAdressIntegrator.cpp.
References gamma.
Referenced by getTemperature(), and registerPython().
setKTI()
void espressopp::integrator::PIAdressIntegrator::setKTI (bool _KTI)
Definition at line 1684 of file PIAdressIntegrator.cpp.
References KTI.
Referenced by getSpeedup(), and registerPython().
setmStep()
void espressopp::integrator::PIAdressIntegrator::setmStep (int _mStep)
Definition at line 1660 of file PIAdressIntegrator.cpp.
References espressopp::integrator::MDIntegrator::dt, dt2, dt3, mStep, and sStep.
Referenced by getTimeStep(), and registerPython().
setNtrotter()
void espressopp::integrator::PIAdressIntegrator::setNtrotter (int _ntrotter)
Definition at line 1674 of file PIAdressIntegrator.cpp.
References ntrotter.
Referenced by getsStep(), and registerPython().
setOmegaSquared()
void espressopp::integrator::PIAdressIntegrator::setOmegaSquared () protected
Definition at line 1715 of file PIAdressIntegrator.cpp.
References ntrotter, omega2, and temperature.
Referenced by PIAdressIntegrator(), and setTemperature().
setPILE()
void espressopp::integrator::PIAdressIntegrator::setPILE (bool _PILE)
Definition at line 1689 of file PIAdressIntegrator.cpp.
References PILE.
Referenced by getCentroidThermostat(), and registerPython().
setPILElambda()
void espressopp::integrator::PIAdressIntegrator::setPILElambda (real _PILElambda)
Definition at line 1733 of file PIAdressIntegrator.cpp.
References PILElambda.
Referenced by getCMDparameter(), and registerPython().
setRealKinMass()
void espressopp::integrator::PIAdressIntegrator::setRealKinMass (bool _realkinmass)
Definition at line 1694 of file PIAdressIntegrator.cpp.
References realkinmass.
Referenced by getPILE(), and registerPython().
setSpeedup()
void espressopp::integrator::PIAdressIntegrator::setSpeedup (bool _speedup)
Definition at line 1679 of file PIAdressIntegrator.cpp.
References speedup.
Referenced by getClmassmultiplier(), and registerPython().
setsStep()
void espressopp::integrator::PIAdressIntegrator::setsStep (int _sStep)
Definition at line 1667 of file PIAdressIntegrator.cpp.
References espressopp::integrator::MDIntegrator::dt, dt2, dt3, mStep, and sStep.
Referenced by getmStep(), and registerPython().
setStep()
void espressopp::integrator::MDIntegrator::setStep (long long step_) inline inherited
Getter routine for integration step.
Definition at line 70 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::MDIntegrator::registerPython().
setTemperature()
void espressopp::integrator::PIAdressIntegrator::setTemperature (real _temperature)
Definition at line 1709 of file PIAdressIntegrator.cpp.
References setOmegaSquared(), and temperature.
Referenced by getNtrotter(), and registerPython().
setTimeStep()
void espressopp::integrator::PIAdressIntegrator::setTimeStep (real _dt)
Definition at line 1653 of file PIAdressIntegrator.cpp.
References espressopp::integrator::MDIntegrator::dt, dt2, dt3, mStep, and sStep.
Referenced by getVerletlistBuilds(), and registerPython().
setVerletList()
void espressopp::integrator::PIAdressIntegrator::setVerletList (shared_ptr< VerletListAdress > _verletList)
Definition at line 1743 of file PIAdressIntegrator.cpp.
References verletList.
Referenced by getConstKinMass(), and registerPython().
setWeights()
void espressopp::integrator::PIAdressIntegrator::setWeights () protected
Definition at line 1582 of file PIAdressIntegrator.cpp.
References clmassmultiplier, espressopp::SystemAccess::getSystemRef(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::iterator::CellListIterator::isDone(), espressopp::Particle::lambda(), espressopp::Particle::lambdaDeriv(), espressopp::Particle::mass(), espressopp::Particle::position(), espressopp::Real3D::sqr(), espressopp::System::storage, espressopp::Particle::varmass(), verletList, weight(), and weightderivative().
Referenced by updateForces().
transForces()
void espressopp::integrator::PIAdressIntegrator::transForces () protected
Definition at line 1005 of file PIAdressIntegrator.cpp.
References Eigenvectors, espressopp::Particle::force(), espressopp::Particle::forcem(), espressopp::SystemAccess::getSystemRef(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::iterator::CellListIterator::isDone(), ntrotter, espressopp::Particle::pib(), espressopp::Particle::position(), and espressopp::System::storage.
Referenced by updateForces().
transMom1()
void espressopp::integrator::PIAdressIntegrator::transMom1 () protected
Definition at line 866 of file PIAdressIntegrator.cpp.
References CMDparameter, espressopp::System::comm, constkinmass, Eigenvalues, espressopp::SystemAccess::getSystemRef(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::iterator::CellListIterator::isDone(), espressopp::Particle::mass(), maxDist, espressopp::Particle::modemom(), ntrotter, espressopp::Particle::pib(), espressopp::Particle::position(), realkinmass, espressopp::System::storage, Tvectors, espressopp::Particle::varmass(), and espressopp::Particle::velocity().
Referenced by run().
transMom2()
void espressopp::integrator::PIAdressIntegrator::transMom2 () protected
Definition at line 940 of file PIAdressIntegrator.cpp.
References CMDparameter, constkinmass, Eigenvalues, Eigenvectors, espressopp::SystemAccess::getSystemRef(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::iterator::CellListIterator::isDone(), espressopp::Particle::mass(), espressopp::Particle::modemom(), ntrotter, espressopp::Particle::pib(), espressopp::Particle::position(), realkinmass, espressopp::System::storage, espressopp::Particle::varmass(), and espressopp::Particle::velocity().
Referenced by run().
transp()
void espressopp::integrator::PIAdressIntegrator::transp ()
Definition at line 1751 of file PIAdressIntegrator.cpp.
References Eigenvectors, ntrotter, and Tvectors.
Referenced by addEigenValues(), and registerPython().
transPos1()
void espressopp::integrator::PIAdressIntegrator::transPos1 () protected
Definition at line 768 of file PIAdressIntegrator.cpp.
References espressopp::System::comm, espressopp::SystemAccess::getSystemRef(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::iterator::CellListIterator::isDone(), espressopp::Particle::mass(), maxDist, espressopp::Particle::modemom(), espressopp::Particle::modepos(), ntrotter, espressopp::Particle::pib(), espressopp::Particle::position(), espressopp::System::storage, Tvectors, and espressopp::Particle::velocity().
Referenced by run().
transPos2()
void espressopp::integrator::PIAdressIntegrator::transPos2 () protected
Definition at line 823 of file PIAdressIntegrator.cpp.
References Eigenvectors, espressopp::SystemAccess::getSystemRef(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::iterator::CellListIterator::isDone(), espressopp::Particle::modepos(), ntrotter, espressopp::Particle::pib(), espressopp::Particle::position(), and espressopp::System::storage.
Referenced by run().
updateForces()
void espressopp::integrator::PIAdressIntegrator::updateForces (int f) protected
Definition at line 1247 of file PIAdressIntegrator.cpp.
References calcForcesF(), calcForcesM(), calcForcesS(), espressopp::storage::Storage::collectGhostForces(), distributeForces(), espressopp::SystemAccess::getSystemRef(), initForces(), KTI, setWeights(), espressopp::System::storage, transForces(), and espressopp::storage::Storage::updateGhosts().
Referenced by run().
weight()
real espressopp::integrator::PIAdressIntegrator::weight (real distanceSqr) protected
Definition at line 1633 of file PIAdressIntegrator.cpp.
References dex, dex2, dexdhy2, and pidhy2.
Referenced by initializeSetup(), integrateModePos(), and setWeights().
weightderivative()
real espressopp::integrator::PIAdressIntegrator::weightderivative (real distanceSqr) protected
Definition at line 1643 of file PIAdressIntegrator.cpp.
References dex, dex2, dexdhy2, and pidhy2.
Referenced by initializeSetup(), integrateModePos(), and setWeights().
Member Data Documentation
aftCalcF
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::aftCalcF inherited
Definition at line 93 of file MDIntegrator.hpp.
Referenced by calcForcesM(), espressopp::integrator::VelocityVerletRESPA::updateForces(), and espressopp::integrator::VelocityVerlet::updateForces().
aftCalcSlow
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::aftCalcSlow inherited
Definition at line 87 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerletRESPA::run().
aftInitF
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::aftInitF inherited
Definition at line 92 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerletRESPA::calcForces(), and espressopp::integrator::VelocityVerlet::calcForces().
aftIntP
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::aftIntP inherited
Definition at line 91 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerletRESPA::run(), and espressopp::integrator::VelocityVerlet::run().
aftIntSlow
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::aftIntSlow inherited
Definition at line 96 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerletRESPA::run().
aftIntV
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::aftIntV inherited
Definition at line 95 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerletRESPA::run(), and espressopp::integrator::VelocityVerlet::run().
befIntP
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::befIntP inherited
Definition at line 89 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerletRESPA::run(), and espressopp::integrator::VelocityVerlet::run().
befIntV
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::befIntV inherited
Definition at line 94 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerletRESPA::run(), and espressopp::integrator::VelocityVerlet::run().
centroidthermostat
bool espressopp::integrator::PIAdressIntegrator::centroidthermostat protected
Definition at line 119 of file PIAdressIntegrator.hpp.
Referenced by getCentroidThermostat(), OUintegrate(), PIAdressIntegrator(), and setCentroidThermostat().
clmassmultiplier
real espressopp::integrator::PIAdressIntegrator::clmassmultiplier protected
Definition at line 123 of file PIAdressIntegrator.hpp.
Referenced by calcForcesF(), computeMomentumDrift(), computePositionDrift(), getClmassmultiplier(), initializeSetup(), integrateModePos(), integrateV2(), PIAdressIntegrator(), setClmassmultiplier(), and setWeights().
CMDparameter
real espressopp::integrator::PIAdressIntegrator::CMDparameter protected
Definition at line 125 of file PIAdressIntegrator.hpp.
Referenced by computeKineticEnergy(), computeMomentumDrift(), getCMDparameter(), integrateModePos(), integrateV2(), OUintegrate(), PIAdressIntegrator(), setCMDparameter(), transMom1(), and transMom2().
constkinmass
bool espressopp::integrator::PIAdressIntegrator::constkinmass protected
Definition at line 117 of file PIAdressIntegrator.hpp.
Referenced by computeKineticEnergy(), getConstKinMass(), integrateModePos(), integrateV2(), OUintegrate(), PIAdressIntegrator(), setConstKinMass(), transMom1(), and transMom2().
dex
real espressopp::integrator::PIAdressIntegrator::dex protected
Definition at line 137 of file PIAdressIntegrator.hpp.
Referenced by PIAdressIntegrator(), weight(), and weightderivative().
dex2
real espressopp::integrator::PIAdressIntegrator::dex2 protected
Definition at line 138 of file PIAdressIntegrator.hpp.
Referenced by PIAdressIntegrator(), weight(), and weightderivative().
dexdhy
real espressopp::integrator::PIAdressIntegrator::dexdhy protected
Definition at line 139 of file PIAdressIntegrator.hpp.
Referenced by PIAdressIntegrator().
dexdhy2
real espressopp::integrator::PIAdressIntegrator::dexdhy2 protected
Definition at line 140 of file PIAdressIntegrator.hpp.
Referenced by PIAdressIntegrator(), weight(), and weightderivative().
dhy
real espressopp::integrator::PIAdressIntegrator::dhy protected
Definition at line 135 of file PIAdressIntegrator.hpp.
Referenced by PIAdressIntegrator().
dt
real espressopp::integrator::MDIntegrator::dt protected inherited
Timestep used for integration.
Definition at line 112 of file MDIntegrator.hpp.
Referenced by getTimeStep(), espressopp::integrator::VelocityVerletRESPA::integrate1(), espressopp::integrator::VelocityVerlet::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerletRESPA::integrate2(), espressopp::integrator::VelocityVerlet::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), integrateModePos(), integrateV2(), espressopp::integrator::MDIntegrator::MDIntegrator(), OUintegrate(), PIAdressIntegrator(), espressopp::integrator::VelocityVerletRESPA::run(), setmStep(), espressopp::integrator::VelocityVerletRESPA::setmultistep(), setsStep(), setTimeStep(), espressopp::integrator::VelocityVerletRESPA::setTimeStep(), espressopp::integrator::MDIntegrator::setTimeStep(), and espressopp::integrator::VelocityVerletRESPA::VelocityVerletRESPA().
dt2
real espressopp::integrator::PIAdressIntegrator::dt2 protected
Definition at line 132 of file PIAdressIntegrator.hpp.
Referenced by integrateV1(), PIAdressIntegrator(), setmStep(), setsStep(), and setTimeStep().
dt3
real espressopp::integrator::PIAdressIntegrator::dt3 protected
Definition at line 133 of file PIAdressIntegrator.hpp.
Referenced by integrateV1(), PIAdressIntegrator(), setmStep(), setsStep(), and setTimeStep().
Eigenvalues
std::vector< real > espressopp::integrator::PIAdressIntegrator::Eigenvalues protected
Definition at line 144 of file PIAdressIntegrator.hpp.
Referenced by addEigenValues(), calcForcesF(), computeKineticEnergy(), computeMomentumDrift(), computePositionDrift(), computeRingEnergy(), integrateModePos(), integrateV2(), OUintegrate(), run(), transMom1(), and transMom2().
Eigenvectors
std::vector< std::vector<real> > espressopp::integrator::PIAdressIntegrator::Eigenvectors protected
Definition at line 142 of file PIAdressIntegrator.hpp.
Referenced by transForces(), transMom2(), transp(), and transPos2().
exList
ExtensionList espressopp::integrator::MDIntegrator::exList protected inherited
Definition at line 106 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::MDIntegrator::addExtension(), espressopp::integrator::MDIntegrator::getExtension(), and espressopp::integrator::MDIntegrator::getNumberOfExtensions().
gamma
real espressopp::integrator::PIAdressIntegrator::gamma protected
Definition at line 128 of file PIAdressIntegrator.hpp.
Referenced by getGamma(), OUintegrate(), PIAdressIntegrator(), and setGamma().
inIntP
boost::signals2::signal<void (real&)> espressopp::integrator::MDIntegrator::inIntP inherited
Definition at line 90 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerletRESPA::integrate1(), and espressopp::integrator::VelocityVerlet::integrate1().
KTI
bool espressopp::integrator::PIAdressIntegrator::KTI protected
Definition at line 116 of file PIAdressIntegrator.hpp.
Referenced by getKTI(), initializeSetup(), integrateModePos(), PIAdressIntegrator(), setKTI(), and updateForces().
maxDist
real espressopp::integrator::PIAdressIntegrator::maxDist protected
Definition at line 131 of file PIAdressIntegrator.hpp.
Referenced by PIAdressIntegrator(), run(), transMom1(), and transPos1().
mStep
int espressopp::integrator::PIAdressIntegrator::mStep protected
Definition at line 111 of file PIAdressIntegrator.hpp.
Referenced by getmStep(), PIAdressIntegrator(), run(), setmStep(), setsStep(), and setTimeStep().
ntrotter
int espressopp::integrator::PIAdressIntegrator::ntrotter protected
Definition at line 112 of file PIAdressIntegrator.hpp.
Referenced by calcForcesF(), computeKineticEnergy(), computeMomentumDrift(), computePositionDrift(), computeRingEnergy(), computeRingEnergyRaw(), distributeForces(), getNtrotter(), initializeSetup(), integrateModePos(), integrateV1(), integrateV2(), OUintegrate(), PIAdressIntegrator(), setNtrotter(), setOmegaSquared(), transForces(), transMom1(), transMom2(), transp(), transPos1(), and transPos2().
omega2
real espressopp::integrator::PIAdressIntegrator::omega2 protected
Definition at line 122 of file PIAdressIntegrator.hpp.
Referenced by calcForcesF(), computePositionDrift(), computeRingEnergy(), computeRingEnergyRaw(), OUintegrate(), and setOmegaSquared().
pidhy2
real espressopp::integrator::PIAdressIntegrator::pidhy2 protected
Definition at line 136 of file PIAdressIntegrator.hpp.
Referenced by PIAdressIntegrator(), weight(), and weightderivative().
PILE
bool espressopp::integrator::PIAdressIntegrator::PILE protected
Definition at line 120 of file PIAdressIntegrator.hpp.
Referenced by getPILE(), OUintegrate(), PIAdressIntegrator(), run(), and setPILE().
PILElambda
real espressopp::integrator::PIAdressIntegrator::PILElambda protected
Definition at line 126 of file PIAdressIntegrator.hpp.
Referenced by getPILElambda(), OUintegrate(), PIAdressIntegrator(), and setPILElambda().
realkinmass
bool espressopp::integrator::PIAdressIntegrator::realkinmass protected
Definition at line 118 of file PIAdressIntegrator.hpp.
Referenced by computeKineticEnergy(), computeMomentumDrift(), getRealKinMass(), integrateModePos(), integrateV2(), OUintegrate(), PIAdressIntegrator(), run(), setRealKinMass(), transMom1(), and transMom2().
recalc1
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::recalc1 inherited
Definition at line 86 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerletRESPA::run(), and espressopp::integrator::VelocityVerlet::run().
recalc2
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::recalc2 inherited
Definition at line 88 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerletRESPA::run(), and espressopp::integrator::VelocityVerlet::run().
resortFlag
bool espressopp::integrator::PIAdressIntegrator::resortFlag protected
Definition at line 114 of file PIAdressIntegrator.hpp.
Referenced by PIAdressIntegrator(), and run().
rng
shared_ptr< esutil::RNG > espressopp::integrator::PIAdressIntegrator::rng protected
Definition at line 147 of file PIAdressIntegrator.hpp.
Referenced by OUintegrate(), and PIAdressIntegrator().
runInit
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::runInit inherited
Definition at line 85 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerletRESPA::run(), and espressopp::integrator::VelocityVerlet::run().
speedup
bool espressopp::integrator::PIAdressIntegrator::speedup protected
Definition at line 115 of file PIAdressIntegrator.hpp.
Referenced by calcForcesF(), computeKineticEnergy(), getSpeedup(), integrateModePos(), integrateV1(), integrateV2(), OUintegrate(), PIAdressIntegrator(), and setSpeedup().
sStep
int espressopp::integrator::PIAdressIntegrator::sStep protected
Definition at line 110 of file PIAdressIntegrator.hpp.
Referenced by getsStep(), PIAdressIntegrator(), run(), setmStep(), setsStep(), and setTimeStep().
step
long long espressopp::integrator::MDIntegrator::step protected inherited
Integration step.
Definition at line 109 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerletRESPA::integrate2(), espressopp::integrator::VelocityVerlet::integrate2(), espressopp::integrator::MDIntegrator::MDIntegrator(), and run().
temperature
real espressopp::integrator::PIAdressIntegrator::temperature protected
Definition at line 129 of file PIAdressIntegrator.hpp.
Referenced by getTemperature(), OUintegrate(), PIAdressIntegrator(), setOmegaSquared(), and setTemperature().
timeFlag
bool espressopp::integrator::MDIntegrator::timeFlag protected inherited
Definition at line 104 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::MDIntegrator::MDIntegrator().
tmpvals
std::vector<real> espressopp::integrator::PIAdressIntegrator::tmpvals protected
Definition at line 145 of file PIAdressIntegrator.hpp.
Referenced by addEVcomponent(), and addTransposedEigenVector().
Tvectors
std::vector< std::vector<real> > espressopp::integrator::PIAdressIntegrator::Tvectors protected
Definition at line 143 of file PIAdressIntegrator.hpp.
Referenced by addTransposedEigenVector(), transMom1(), transp(), and transPos1().
verletList
shared_ptr<VerletListAdress> espressopp::integrator::PIAdressIntegrator::verletList
Definition at line 39 of file PIAdressIntegrator.hpp.
Referenced by calcForcesF(), getVerletList(), initializeSetup(), integrateModePos(), integrateV2(), PIAdressIntegrator(), setVerletList(), and setWeights().
verletlistBuilds
int espressopp::integrator::PIAdressIntegrator::verletlistBuilds protected
Definition at line 113 of file PIAdressIntegrator.hpp.
Referenced by getVerletlistBuilds(), PIAdressIntegrator(), and run().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/integrator/PIAdressIntegrator.hpp
/home/espressopp/espressopp/src/integrator/PIAdressIntegrator.cpp