ESPResSo++: espressopp::analysis::SystemMonitor Class Reference
espressopp::analysis::SystemMonitor Class Reference
#include <SystemMonitor.hpp>
Public Types
typedef std::vector< std::pair
< std::string, shared_ptr
< Observable > > > ObservableList
Public Member Functions
SystemMonitor (shared_ptr< System > system, shared_ptr< integrator::MDIntegrator > integrator, shared_ptr< SystemMonitorOutputCSV > output)
~SystemMonitor ()
void perform_action ()
void info ()
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
Private Member Functions
void computeObservables ()
void addObservable (std::string name, shared_ptr< Observable > obs, bool is_visible)
Private Attributes
int current_step_
bool header_written_
bool header_shown_
shared_ptr< std::vector< real > > values_
shared_ptr< std::vector
< std::string > > header_
std::vector< int > visible_observables_
shared_ptr< System > system_
shared_ptr
< integrator::MDIntegrator > integrator_
shared_ptr
< SystemMonitorOutputCSV > output_
ObservableList observables_
Detailed Description
Definition at line 68 of file SystemMonitor.hpp.
Member Typedef Documentation
typedef std::vector<std::pair<std::string, shared_ptr<Observable> > > espressopp::analysis::SystemMonitor::ObservableList
Definition at line 70 of file SystemMonitor.hpp.
Constructor & Destructor Documentation
espressopp::analysis::SystemMonitor::SystemMonitor (shared_ptr< System > system, shared_ptr< integrator::MDIntegrator > integrator, shared_ptr< SystemMonitorOutputCSV > output) inline
Definition at line 71 of file SystemMonitor.hpp.
References header_, header_shown_, output_, values_, and visible_observables_.
espressopp::analysis::SystemMonitor::~SystemMonitor () inline
Definition at line 94 of file SystemMonitor.hpp.
Member Function Documentation
void espressopp::analysis::SystemMonitor::addObservable (std::string name, shared_ptr< Observable > obs, bool is_visible) private
Definition at line 78 of file SystemMonitor.cpp.
References header_, observables_, and visible_observables_.
Referenced by registerPython().
void espressopp::analysis::SystemMonitor::computeObservables () private
Definition at line 43 of file SystemMonitor.cpp.
References observables_, and values_.
Referenced by perform_action().
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::io::DumpXYZ::DumpXYZ(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::LatticeBoltzmann::initGammas(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readCouplForces(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::VerletListTriple::registerPython(), espressopp::VerletList::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveCouplForces(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::analysis::LBOutputScreen::writeOutput(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readCouplForces(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::LatticeBoltzmann::restoreLBForces(), espressopp::integrator::MinimizeEnergy::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::LatticeBoltzmann::saveCouplForces(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
void espressopp::analysis::SystemMonitor::info ()
Definition at line 49 of file SystemMonitor.cpp.
References header_, header_shown_, system_, values_, and visible_observables_.
Referenced by registerPython().
void espressopp::analysis::SystemMonitor::perform_action () virtual
Implements espressopp::ParticleAccess.
Definition at line 31 of file SystemMonitor.cpp.
References computeObservables(), current_step_, integrator_, output_, system_, and values_.
Referenced by registerPython().
void espressopp::analysis::SystemMonitor::registerPython () static
Definition at line 88 of file SystemMonitor.cpp.
References addObservable(), info(), and perform_action().
Referenced by espressopp::analysis::registerPython().
Member Data Documentation
int espressopp::analysis::SystemMonitor::current_step_ private
Definition at line 106 of file SystemMonitor.hpp.
Referenced by perform_action().
shared_ptr<std::vector<std::string> > espressopp::analysis::SystemMonitor::header_ private
Definition at line 110 of file SystemMonitor.hpp.
Referenced by addObservable(), info(), and SystemMonitor().
bool espressopp::analysis::SystemMonitor::header_shown_ private
Definition at line 108 of file SystemMonitor.hpp.
Referenced by info(), and SystemMonitor().
bool espressopp::analysis::SystemMonitor::header_written_ private
Definition at line 107 of file SystemMonitor.hpp.
Referenced by espressopp::analysis::SystemMonitorOutputCSV::write().
shared_ptr<integrator::MDIntegrator> espressopp::analysis::SystemMonitor::integrator_ private
Definition at line 113 of file SystemMonitor.hpp.
Referenced by perform_action().
ObservableList espressopp::analysis::SystemMonitor::observables_ private
Definition at line 116 of file SystemMonitor.hpp.
Referenced by addObservable(), and computeObservables().
shared_ptr<SystemMonitorOutputCSV> espressopp::analysis::SystemMonitor::output_ private
Definition at line 115 of file SystemMonitor.hpp.
Referenced by perform_action(), and SystemMonitor().
shared_ptr<System> espressopp::analysis::SystemMonitor::system_ private
Definition at line 112 of file SystemMonitor.hpp.
Referenced by info(), perform_action(), and espressopp::analysis::SystemMonitorOutputCSV::write().
shared_ptr<std::vector<real> > espressopp::analysis::SystemMonitor::values_ private
Definition at line 109 of file SystemMonitor.hpp.
Referenced by computeObservables(), info(), perform_action(), SystemMonitor(), and espressopp::analysis::SystemMonitorOutputCSV::write().
std::vector<int> espressopp::analysis::SystemMonitor::visible_observables_ private
Definition at line 111 of file SystemMonitor.hpp.
Referenced by addObservable(), info(), and SystemMonitor().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/analysis/SystemMonitor.hpp
/home/travis/build/espressopp/espressopp/src/analysis/SystemMonitor.cpp