ESPResSo++: espressopp::interaction::DihedralHarmonic Class Reference
espressopp::interaction::DihedralHarmonic Class Reference
This class provides methods to compute forces and energies of the DihedralHarmonic dihedral potential.
#include <DihedralHarmonic.hpp>
Public Member Functions
DihedralHarmonic ()
DihedralHarmonic (real _K, real _phi0)
void setK (real _K)
real getK () const
void setPhi0 (real _phi0)
real getPhi0 () const
real d (int i, int j) const
Real3D prod (Real3D a, Real3D b) const
Compute dot product of two vectors.
real _computeEnergyRaw (real _phi) const
Calculate raw value of the energy.
void _computeForceRaw (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &r21, const Real3D &r32, const Real3D &r43) const
Compute the force.
real _computeForceRaw (real phi) const
virtual real computeEnergy (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
virtual real computeEnergy (real phi) const
virtual void computeForce (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
virtual real computeForce (real phi) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
real _computeEnergy (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
real _computeEnergy (real phi) const
void _computeForce (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
DihedralHarmonic * derived_this ()
const DihedralHarmonic * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
Private Attributes
real K
real phi0
Detailed Description
This class provides methods to compute forces and energies of the DihedralHarmonic dihedral potential.
The reference potential is as follow:
where the K is a constant. The angles and should be provided in radians.
The reference documentation: Gromacs Manual 4.6.1, section 4.2.11 (page 79-80), equation 4.60
Definition at line 46 of file DihedralHarmonic.hpp.
Constructor & Destructor Documentation
DihedralHarmonic() [1/2]
espressopp::interaction::DihedralHarmonic::DihedralHarmonic () inline
Definition at line 54 of file DihedralHarmonic.hpp.
DihedralHarmonic() [2/2]
espressopp::interaction::DihedralHarmonic::DihedralHarmonic (real _K, real _phi0) inline
Definition at line 55 of file DihedralHarmonic.hpp.
Member Function Documentation
_computeEnergy() [1/2]
real espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >::_computeEnergy (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline inherited
Definition at line 165 of file DihedralPotential.hpp.
_computeEnergy() [2/2]
real espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >::_computeEnergy (real phi) const inline inherited
Definition at line 258 of file DihedralPotential.hpp.
_computeEnergyRaw()
real espressopp::interaction::DihedralHarmonic::_computeEnergyRaw (real _phi) const inline
Calculate raw value of the energy.
Parameters
[in] _phi The phi value in radians.
Returns
The energy value.
Definition at line 94 of file DihedralHarmonic.hpp.
References M_PI, and phi0.
_computeForce()
void espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >::_computeForce (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline inherited
Definition at line 280 of file DihedralPotential.hpp.
_computeForceRaw() [1/2]
void espressopp::interaction::DihedralHarmonic::_computeForceRaw (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & r21, const Real3D & r32, const Real3D & r43) const inline
Compute the force.
Only the form of the potential derivative has to be changed. The rest remain the same as for the harmonic cosine potential
The part of the formula. 1/sin(phi) * d/dphi U(phi) where the
The derivative of is
Definition at line 107 of file DihedralHarmonic.hpp.
References espressopp::Real3D::cross(), d(), M_PI, phi0, prod(), and espressopp::Real3D::sqr().
_computeForceRaw() [2/2]
real espressopp::interaction::DihedralHarmonic::_computeForceRaw (real phi) const inline
Definition at line 204 of file DihedralHarmonic.hpp.
References M_PI, and phi0.
computeEnergy() [1/2]
real espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >::computeEnergy (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 145 of file DihedralPotential.hpp.
computeEnergy() [2/2]
real espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >::computeEnergy (real phi) const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 158 of file DihedralPotential.hpp.
computeForce() [1/2]
void espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >::computeForce (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 266 of file DihedralPotential.hpp.
computeForce() [2/2]
real espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >::computeForce (real phi) const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 294 of file DihedralPotential.hpp.
d()
real espressopp::interaction::DihedralHarmonic::d (int i, int j) const inline
Definition at line 71 of file DihedralHarmonic.hpp.
Referenced by _computeForceRaw(), and prod().
derived_this() [1/2]
DihedralHarmonic * espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >::derived_this () inline protected inherited
Definition at line 107 of file DihedralPotential.hpp.
derived_this() [2/2]
const DihedralHarmonic * espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >::derived_this () const inline protected inherited
Definition at line 111 of file DihedralPotential.hpp.
getCutoff()
real espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 138 of file DihedralPotential.hpp.
getK()
real espressopp::interaction::DihedralHarmonic::getK () const inline
Definition at line 60 of file DihedralHarmonic.hpp.
References K.
Referenced by registerPython().
getPhi0()
real espressopp::interaction::DihedralHarmonic::getPhi0 () const inline
Definition at line 68 of file DihedralHarmonic.hpp.
References phi0.
Referenced by registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::DihedralPotential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
prod()
Real3D espressopp::interaction::DihedralHarmonic::prod (Real3D a, Real3D b) const inline
Compute dot product of two vectors.
Definition at line 79 of file DihedralHarmonic.hpp.
References d().
Referenced by _computeForceRaw().
registerPython()
void espressopp::interaction::DihedralHarmonic::registerPython () static
Definition at line 36 of file DihedralHarmonic.cpp.
References getK(), getPhi0(), setK(), and setPhi0().
Referenced by espressopp::interaction::registerPython().
setCutoff()
void espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 130 of file DihedralPotential.hpp.
setK()
void espressopp::interaction::DihedralHarmonic::setK (real _K) inline
Definition at line 59 of file DihedralHarmonic.hpp.
Referenced by registerPython().
setPhi0()
void espressopp::interaction::DihedralHarmonic::setPhi0 (real _phi0) inline
Definition at line 62 of file DihedralHarmonic.hpp.
Referenced by registerPython().
Member Data Documentation
cutoff
real espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >::cutoff protected inherited
Definition at line 104 of file DihedralPotential.hpp.
cutoffSqr
real espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonic >::cutoffSqr protected inherited
Definition at line 105 of file DihedralPotential.hpp.
K
real espressopp::interaction::DihedralHarmonic::K private
Definition at line 48 of file DihedralHarmonic.hpp.
Referenced by getK().
phi0
real espressopp::interaction::DihedralHarmonic::phi0 private
Definition at line 49 of file DihedralHarmonic.hpp.
Referenced by _computeEnergyRaw(), _computeForceRaw(), and getPhi0().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/DihedralHarmonic.hpp
/home/espressopp/espressopp/src/interaction/DihedralHarmonic.cpp