ESPResSo++: espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential > Class Template Reference
espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential > Class Template Reference
#include <FixedTripleListTypesInteractionTemplate.hpp>
Public Member Functions
FixedTripleListTypesInteractionTemplate (shared_ptr< System > system, shared_ptr< FixedTripleList > _fixedtripleList)
virtual ~FixedTripleListTypesInteractionTemplate ()
void setFixedTripleList (shared_ptr< FixedTripleList > _fixedtripleList)
shared_ptr< FixedTripleList > getFixedTripleList ()
void setPotential (int type1, int type2, int type3, const Potential &potential)
Potential & getPotential (int type1, int type2, int type3)
shared_ptr< Potential > getPotentialPtr (int type1, int type2, int type3)
virtual void addForces ()
virtual real computeEnergy ()
virtual real computeEnergyDeriv ()
virtual real computeEnergyAA ()
virtual real computeEnergyCG ()
virtual void computeVirialX (std::vector< real > &p_xx_total, int bins)
virtual real computeVirial ()
virtual void computeVirialTensor (Tensor &w)
virtual void computeVirialTensor (Tensor &w, real z)
virtual void computeVirialTensor (Tensor *w, int n)
virtual real getMaxCutoff ()
This method returns the maximal cutoff defined for one type pair.
virtual int bondType ()
Static Public Member Functions
static void registerPython ()
Protected Types
typedef _Potential Potential
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Protected Attributes
int ntypes
shared_ptr< FixedTripleList > fixedtripleList
esutil::Array3D< Potential,
esutil::enlarge > potentialArray
Private Member Functions
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Detailed Description
template<typename _Potential>
class espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >
Definition at line 44 of file FixedTripleListTypesInteractionTemplate.hpp.
Member Typedef Documentation
template<typename _Potential > typedef _Potential espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::Potential protected
Definition at line 46 of file FixedTripleListTypesInteractionTemplate.hpp.
Constructor & Destructor Documentation
template<typename _Potential > espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::FixedTripleListTypesInteractionTemplate (shared_ptr< System > system, shared_ptr< FixedTripleList > _fixedtripleList) inline
Definition at line 50 of file FixedTripleListTypesInteractionTemplate.hpp.
References espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::ntypes, and espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::potentialArray.
template<typename _Potential > virtual espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::~FixedTripleListTypesInteractionTemplate () inline virtual
Definition at line 57 of file FixedTripleListTypesInteractionTemplate.hpp.
Member Function Documentation
template<typename _Potential > void espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::addForces () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 109 of file FixedTripleListTypesInteractionTemplate.hpp.
References espressopp::Particle::force(), espressopp::bc::BC::getMinimumImageVectorBox(), LOG4ESPP_INFO, espressopp::Particle::position(), and espressopp::Particle::type().
template<typename _Potential > virtual int espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::bondType () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 96 of file FixedTripleListTypesInteractionTemplate.hpp.
References espressopp::interaction::Angular.
template<typename _Potential > real espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeEnergy () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 136 of file FixedTripleListTypesInteractionTemplate.hpp.
References espressopp::bc::BC::getMinimumImageVector(), espressopp::Particle::id(), LOG4ESPP_INFO, LOG4ESPP_TRACE, mpiWorld, espressopp::Particle::position(), and espressopp::Particle::type().
template<typename _Potential > real espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeEnergyAA () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 174 of file FixedTripleListTypesInteractionTemplate.hpp.
template<typename _Potential > real espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeEnergyCG () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 180 of file FixedTripleListTypesInteractionTemplate.hpp.
template<typename _AngularPotential > real espressopp::interaction::FixedTripleListTypesInteractionTemplate< _AngularPotential >::computeEnergyDeriv () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 166 of file FixedTripleListTypesInteractionTemplate.hpp.
template<typename _Potential > real espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirial () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 192 of file FixedTripleListTypesInteractionTemplate.hpp.
References espressopp::bc::BC::getMinimumImageVectorBox(), LOG4ESPP_INFO, mpiWorld, espressopp::Particle::position(), and espressopp::Particle::type().
template<typename _Potential > void espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirialTensor (Tensor & w) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 222 of file FixedTripleListTypesInteractionTemplate.hpp.
References espressopp::bc::BC::getMinimumImageVectorBox(), LOG4ESPP_INFO, mpiWorld, espressopp::Particle::position(), and espressopp::Particle::type().
template<typename _Potential > void espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirialTensor (Tensor & w, real z) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 252 of file FixedTripleListTypesInteractionTemplate.hpp.
References LOG4ESPP_INFO.
template<typename _Potential > void espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirialTensor (Tensor * w, int n) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 259 of file FixedTripleListTypesInteractionTemplate.hpp.
References LOG4ESPP_INFO.
template<typename _Potential > void espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirialX (std::vector< real > & p_xx_total, int bins) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 186 of file FixedTripleListTypesInteractionTemplate.hpp.
template<typename _Potential > shared_ptr<FixedTripleList> espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::getFixedTripleList () inline
Definition at line 63 of file FixedTripleListTypesInteractionTemplate.hpp.
References espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::fixedtripleList.
template<typename _Potential > real espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::getMaxCutoff () inline virtual
This method returns the maximal cutoff defined for one type pair.
Implements espressopp::interaction::Interaction.
Definition at line 265 of file FixedTripleListTypesInteractionTemplate.hpp.
template<typename _Potential > Potential& espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::getPotential (int type1, int type2, int type3) inline
Definition at line 77 of file FixedTripleListTypesInteractionTemplate.hpp.
References espressopp::esutil::Array3D< T, outlier_mode >::at(), and espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::potentialArray.
template<typename _Potential > shared_ptr<Potential> espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::getPotentialPtr (int type1, int type2, int type3) inline
Definition at line 81 of file FixedTripleListTypesInteractionTemplate.hpp.
References espressopp::esutil::Array3D< T, outlier_mode >::at(), and espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::potentialArray.
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::LatticeBoltzmann::initGammas(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readCouplForces(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::VerletListTriple::registerPython(), espressopp::VerletList::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveCouplForces(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::analysis::LBOutputScreen::writeOutput(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readCouplForces(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::LatticeBoltzmann::restoreLBForces(), espressopp::integrator::MinimizeEnergy::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::LatticeBoltzmann::saveCouplForces(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
static espressopp::interaction::Interaction::LOG4ESPP_DECL_LOGGER (theLogger) static protected inherited
Logger.
void espressopp::interaction::Interaction::registerPython () static inherited
Definition at line 36 of file Interaction.cpp.
References espressopp::interaction::Interaction::bondType(), espressopp::interaction::Interaction::computeEnergy(), espressopp::interaction::Interaction::computeEnergyAA(), espressopp::interaction::Interaction::computeEnergyCG(), espressopp::interaction::Interaction::computeEnergyDeriv(), and espressopp::interaction::Interaction::computeVirial().
Referenced by espressopp::interaction::registerPython().
template<typename _Potential > void espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::setFixedTripleList (shared_ptr< FixedTripleList > _fixedtripleList) inline
Definition at line 59 of file FixedTripleListTypesInteractionTemplate.hpp.
References espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::fixedtripleList.
template<typename _Potential > void espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::setPotential (int type1, int type2, int type3, const Potential & potential) inline
Definition at line 67 of file FixedTripleListTypesInteractionTemplate.hpp.
References espressopp::esutil::Array3D< T, outlier_mode >::at(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::ntypes, and espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::potentialArray.
Member Data Documentation
template<typename _Potential > shared_ptr<FixedTripleList> espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::fixedtripleList protected
Definition at line 100 of file FixedTripleListTypesInteractionTemplate.hpp.
Referenced by espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::getFixedTripleList(), and espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::setFixedTripleList().
template<typename _Potential > int espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::ntypes protected
Definition at line 99 of file FixedTripleListTypesInteractionTemplate.hpp.
Referenced by espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::FixedTripleListTypesInteractionTemplate(), and espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::setPotential().
template<typename _Potential > esutil::Array3D<Potential, esutil::enlarge> espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::potentialArray protected
Definition at line 101 of file FixedTripleListTypesInteractionTemplate.hpp.
Referenced by espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::FixedTripleListTypesInteractionTemplate(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::getPotential(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::getPotentialPtr(), and espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::setPotential().
The documentation for this class was generated from the following file:
/home/travis/build/espressopp/espressopp/src/interaction/FixedTripleListTypesInteractionTemplate.hpp