ESPResSo++: espressopp::interaction::AngularCosineSquared Class Reference
espressopp::interaction::AngularCosineSquared Class Reference
This class provides methods to compute forces and energies of the AngularCosineSquared angular potential.
#include <AngularCosineSquared.hpp>
Public Member Functions
AngularCosineSquared ()
AngularCosineSquared (real _K, real _theta0)
void setK (real _K)
real getK () const
void setTheta0 (real _theta0)
real getTheta0 () const
real _computeEnergyRaw (real _theta) const
bool _computeForceRaw (Real3D &force12, Real3D &force32, const Real3D &dist12, const Real3D &dist32) const
real _computeForceRaw (real theta) const
virtual real computeEnergy (const Particle &p1, const Particle &p2, const Particle &p3) const
virtual real computeEnergy (const Real3D &dist12, const Real3D &dist32) const
virtual real computeEnergy (const real theta) const
virtual void computeForce (Real3D &force12, Real3D &force32, const Particle &p1, const Particle &p2, const Particle &p3) const
virtual void computeForce (Real3D &force12, Real3D &force32, const Real3D &dist12, const Real3D &dist32) const
virtual real computeForce (real theta) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
real _computeEnergy (const Particle &p1, const Particle &p2, const Particle &p3) const
real _computeEnergy (const Real3D &dist12, const Real3D &dist32) const
real _computeEnergy (real theta) const
void _computeForce (Real3D &force12, Real3D &force32, const Particle &p1, const Particle &p2, const Particle &p3) const
bool _computeForce (Real3D &force12, Real3D &force32, const Real3D &dist12, const Real3D &dist32) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
AngularCosineSquared * derived_this ()
const AngularCosineSquared * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
Private Attributes
real K
real theta0
real cos_theta0
Detailed Description
This class provides methods to compute forces and energies of the AngularCosineSquared angular potential.
To create a new angular potential one only needs to write the setter/getters and the variable dU_dtheta.
Definition at line 37 of file AngularCosineSquared.hpp.
Constructor & Destructor Documentation
espressopp::interaction::AngularCosineSquared::AngularCosineSquared () inline
Definition at line 46 of file AngularCosineSquared.hpp.
espressopp::interaction::AngularCosineSquared::AngularCosineSquared (real _K, real _theta0) inline
Definition at line 47 of file AngularCosineSquared.hpp.
References cos_theta0.
Member Function Documentation
real espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >::_computeEnergy (const Particle & p1, const Particle & p2, const Particle & p3) const inherited
real espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >::_computeEnergy (const Real3D & dist12, const Real3D & dist32) const inherited
real espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >::_computeEnergy (real theta) const inherited
real espressopp::interaction::AngularCosineSquared::_computeEnergyRaw (real _theta) const inline
Definition at line 60 of file AngularCosineSquared.hpp.
References cos_theta0, and K.
void espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >::_computeForce (Real3D & force12, Real3D & force32, const Particle & p1, const Particle & p2, const Particle & p3) const inherited
bool espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >::_computeForce (Real3D & force12, Real3D & force32, const Real3D & dist12, const Real3D & dist32) const inherited
bool espressopp::interaction::AngularCosineSquared::_computeForceRaw (Real3D & force12, Real3D & force32, const Real3D & dist12, const Real3D & dist32) const inline
Definition at line 93 of file AngularCosineSquared.hpp.
References cos_theta0, and K.
real espressopp::interaction::AngularCosineSquared::_computeForceRaw (real theta) const inline
Definition at line 122 of file AngularCosineSquared.hpp.
References cos_theta0, and K.
virtual real espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >::computeEnergy (const Particle & p1, const Particle & p2, const Particle & p3) const virtual inherited
Implements espressopp::interaction::AngularPotential.
virtual real espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >::computeEnergy (const Real3D & dist12, const Real3D & dist32) const virtual inherited
Implements espressopp::interaction::AngularPotential.
virtual real espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >::computeEnergy (const real theta) const virtual inherited
Implements espressopp::interaction::AngularPotential.
virtual void espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >::computeForce (Real3D & force12, Real3D & force32, const Particle & p1, const Particle & p2, const Particle & p3) const virtual inherited
Implements espressopp::interaction::AngularPotential.
virtual void espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >::computeForce (Real3D & force12, Real3D & force32, const Real3D & dist12, const Real3D & dist32) const virtual inherited
Implements espressopp::interaction::AngularPotential.
virtual real espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >::computeForce (real theta) const virtual inherited
Implements espressopp::interaction::AngularPotential.
AngularCosineSquared * espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >::derived_this () inline protected inherited
Definition at line 111 of file AngularPotential.hpp.
const AngularCosineSquared * espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >::derived_this () const inline protected inherited
Definition at line 115 of file AngularPotential.hpp.
virtual real espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >::getCutoff () const virtual inherited
Implements espressopp::interaction::AngularPotential.
real espressopp::interaction::AngularCosineSquared::getK () const inline
Definition at line 52 of file AngularCosineSquared.hpp.
References K.
Referenced by registerPython().
real espressopp::interaction::AngularCosineSquared::getTheta0 () const inline
Definition at line 58 of file AngularCosineSquared.hpp.
References theta0.
Referenced by registerPython().
static espressopp::interaction::AngularPotential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
void espressopp::interaction::AngularCosineSquared::registerPython () static
Definition at line 33 of file AngularCosineSquared.cpp.
References getK(), getTheta0(), setK(), and setTheta0().
Referenced by espressopp::interaction::registerPython().
virtual void espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >::setCutoff (real _cutoff) virtual inherited
Implements espressopp::interaction::AngularPotential.
void espressopp::interaction::AngularCosineSquared::setK (real _K) inline
Definition at line 51 of file AngularCosineSquared.hpp.
References K.
Referenced by registerPython().
void espressopp::interaction::AngularCosineSquared::setTheta0 (real _theta0) inline
Definition at line 54 of file AngularCosineSquared.hpp.
References cos_theta0, and theta0.
Referenced by registerPython().
Member Data Documentation
real espressopp::interaction::AngularCosineSquared::cos_theta0 private
Definition at line 41 of file AngularCosineSquared.hpp.
Referenced by _computeEnergyRaw(), _computeForceRaw(), AngularCosineSquared(), and setTheta0().
real espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >::cutoff protected inherited
Definition at line 108 of file AngularPotential.hpp.
real espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >::cutoffSqr protected inherited
Definition at line 109 of file AngularPotential.hpp.
real espressopp::interaction::AngularCosineSquared::K private
Definition at line 39 of file AngularCosineSquared.hpp.
Referenced by _computeEnergyRaw(), _computeForceRaw(), getK(), and setK().
real espressopp::interaction::AngularCosineSquared::theta0 private
Definition at line 40 of file AngularCosineSquared.hpp.
Referenced by getTheta0(), and setTheta0().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/interaction/AngularCosineSquared.hpp
/home/travis/build/espressopp/espressopp/src/interaction/AngularCosineSquared.cpp