ESPResSo++: espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential > Class Template Reference
espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential > Class Template Reference
#include <VerletListAdressATInteractionTemplate.hpp>
Public Member Functions
VerletListAdressATInteractionTemplate (shared_ptr< VerletListAdress > _verletList, shared_ptr< FixedTupleListAdress > _fixedtupleList)
void setVerletList (shared_ptr< VerletListAdress > _verletList)
shared_ptr< VerletListAdress > getVerletList ()
void setFixedTupleList (shared_ptr< FixedTupleListAdress > _fixedtupleList)
void setPotential (int type1, int type2, const Potential &potential)
Potential & getPotential (int type1, int type2)
shared_ptr< Potential > getPotentialPtr (int type1, int type2)
virtual void addForces ()
virtual real computeEnergy ()
virtual real computeEnergyDeriv ()
virtual real computeEnergyAA ()
virtual real computeEnergyCG ()
virtual real computeEnergyAA (int atomtype)
virtual real computeEnergyCG (int atomtype)
virtual void computeVirialX (std::vector< real > &p_xx_total, int bins)
virtual real computeVirial ()
virtual void computeVirialTensor (Tensor &w)
virtual void computeVirialTensor (Tensor &w, real z)
virtual void computeVirialTensor (Tensor *w, int n)
virtual real getMaxCutoff ()
This method returns the maximal cutoff defined for one type pair.
virtual int bondType ()
Static Public Member Functions
static void registerPython ()
Protected Types
typedef _Potential Potential
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Protected Attributes
int ntypes
shared_ptr< VerletListAdress > verletList
shared_ptr< FixedTupleListAdress > fixedtupleList
esutil::Array2D< Potential, esutil::enlarge > potentialArray
real pidhy2
real dexdhy
real dexdhy2
real dex
real dhy
real dex2
Detailed Description
template<typename _Potential>
class espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >
Definition at line 42 of file VerletListAdressATInteractionTemplate.hpp.
Member Typedef Documentation
Potential
template<typename _Potential > typedef _Potential espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::Potential protected
Definition at line 45 of file VerletListAdressATInteractionTemplate.hpp.
Constructor & Destructor Documentation
VerletListAdressATInteractionTemplate()
template<typename _Potential > espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::VerletListAdressATInteractionTemplate (shared_ptr< VerletListAdress > _verletList, shared_ptr< FixedTupleListAdress > _fixedtupleList) inline
Definition at line 49 of file VerletListAdressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::dex, espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::dex2, espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::dexdhy, espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::dexdhy2, espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::dhy, M_PI, espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::ntypes, espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::pidhy2, espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::potentialArray, and espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::verletList.
Member Function Documentation
addForces()
template<typename _Potential > void espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::addForces () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 137 of file VerletListAdressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::fixedtupleList, espressopp::Particle::force(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::getPotential(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::Particle::lambda(), LOG4ESPP_INFO, espressopp::Particle::position(), espressopp::Particle::type(), espressopp::Particle::velocity(), and espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::verletList.
Referenced by espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::getPotentialPtr().
bondType()
template<typename _Potential > virtual int espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::bondType () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 111 of file VerletListAdressATInteractionTemplate.hpp.
References espressopp::interaction::Nonbonded.
computeEnergy()
template<typename _Potential > real espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeEnergy () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 240 of file VerletListAdressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeEnergyDeriv(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::dex, espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::dex2, espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::dexdhy2, espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::fixedtupleList, espressopp::Particle::getMass(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::getPotential(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::getVerletList(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::Particle::lambda(), LOG4ESPP_INFO, espressopp::Particle::mass(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::pidhy2, espressopp::Particle::position(), espressopp::Real3D::sqr(), espressopp::Particle::type(), espressopp::Particle::velocity(), and espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::verletList.
Referenced by espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::addForces(), and espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::getPotentialPtr().
computeEnergyAA() [1/2]
template<typename _Potential > real espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeEnergyAA () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 377 of file VerletListAdressATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeEnergyDeriv(), and espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::getPotentialPtr().
computeEnergyAA() [2/2]
template<typename _Potential > real espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeEnergyAA (int atomtype) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 384 of file VerletListAdressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeEnergyCG().
computeEnergyCG() [1/2]
template<typename _Potential > real espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeEnergyCG () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 391 of file VerletListAdressATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeEnergyAA(), and espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::getPotentialPtr().
computeEnergyCG() [2/2]
template<typename _Potential > real espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeEnergyCG (int atomtype) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 398 of file VerletListAdressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeVirialX().
computeEnergyDeriv()
template<typename _Potential > real espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeEnergyDeriv () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 370 of file VerletListAdressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeEnergyAA().
Referenced by espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeEnergy(), and espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::getPotentialPtr().
computeVirial()
template<typename _Potential > real espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeVirial () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 411 of file VerletListAdressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeVirialTensor(), and LOG4ESPP_INFO.
Referenced by espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeVirialX(), and espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::getPotentialPtr().
computeVirialTensor() [1/3]
template<typename _Potential > void espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeVirialTensor (Tensor & w) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 419 of file VerletListAdressATInteractionTemplate.hpp.
References LOG4ESPP_INFO.
Referenced by espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeVirialTensor(), and espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::getPotentialPtr().
computeVirialTensor() [2/3]
template<typename _Potential > void espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeVirialTensor (Tensor & w, real z) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 426 of file VerletListAdressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeVirialTensor(), and LOG4ESPP_INFO.
computeVirialTensor() [3/3]
template<typename _Potential > void espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeVirialTensor (Tensor * w, int n) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 433 of file VerletListAdressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::getMaxCutoff().
computeVirialX()
template<typename _Potential > void espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeVirialX (std::vector< real > & p_xx_total, int bins) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 405 of file VerletListAdressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeVirial().
Referenced by espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeEnergyCG(), and espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::getPotentialPtr().
getMaxCutoff()
template<typename _Potential > real espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::getMaxCutoff () inline virtual
This method returns the maximal cutoff defined for one type pair.
Implements espressopp::interaction::Interaction.
Definition at line 440 of file VerletListAdressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::getPotential(), and espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::ntypes.
Referenced by espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeVirialTensor(), and espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::getPotentialPtr().
getPotential()
template<typename _Potential > Potential& espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::getPotential (int type1, int type2) inline
Definition at line 90 of file VerletListAdressATInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), and espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::potentialArray.
Referenced by espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeEnergy(), and espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::getMaxCutoff().
getPotentialPtr()
template<typename _Potential > shared_ptr<Potential> espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::getPotentialPtr (int type1, int type2) inline
Definition at line 94 of file VerletListAdressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::addForces(), espressopp::esutil::Array2D< T, outlier_mode >::at(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeEnergyAA(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeEnergyCG(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeEnergyDeriv(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeVirialX(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::getMaxCutoff(), and espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::potentialArray.
getVerletList()
template<typename _Potential > shared_ptr<VerletListAdress> espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::getVerletList () inline
Definition at line 70 of file VerletListAdressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::verletList.
Referenced by espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeEnergy().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Interaction::LOG4ESPP_DECL_LOGGER (theLogger) static protected inherited
Logger.
Referenced by espressopp::interaction::Interaction::~Interaction().
registerPython()
void espressopp::interaction::Interaction::registerPython () static inherited
Definition at line 36 of file Interaction.cpp.
References espressopp::interaction::Interaction::bondType(), espressopp::interaction::Interaction::computeEnergy(), espressopp::interaction::Interaction::computeEnergyAA(), espressopp::interaction::Interaction::computeEnergyCG(), espressopp::interaction::Interaction::computeEnergyDeriv(), and espressopp::interaction::Interaction::computeVirial().
Referenced by espressopp::interaction::registerPython(), and espressopp::interaction::Interaction::~Interaction().
setFixedTupleList()
template<typename _Potential > void espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::setFixedTupleList (shared_ptr< FixedTupleListAdress > _fixedtupleList) inline
Definition at line 75 of file VerletListAdressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::fixedtupleList.
setPotential()
template<typename _Potential > void espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::setPotential (int type1, int type2, const Potential & potential) inline
Definition at line 80 of file VerletListAdressATInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::ntypes, and espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::potentialArray.
setVerletList()
template<typename _Potential > void espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::setVerletList (shared_ptr< VerletListAdress > _verletList) inline
Definition at line 66 of file VerletListAdressATInteractionTemplate.hpp.
References espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::verletList.
Member Data Documentation
dex
template<typename _Potential > real espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::dex protected
Definition at line 125 of file VerletListAdressATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeEnergy(), and espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::VerletListAdressATInteractionTemplate().
dex2
template<typename _Potential > real espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::dex2 protected
Definition at line 127 of file VerletListAdressATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeEnergy(), and espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::VerletListAdressATInteractionTemplate().
dexdhy
template<typename _Potential > real espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::dexdhy protected
Definition at line 123 of file VerletListAdressATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::VerletListAdressATInteractionTemplate().
dexdhy2
template<typename _Potential > real espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::dexdhy2 protected
Definition at line 124 of file VerletListAdressATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeEnergy(), and espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::VerletListAdressATInteractionTemplate().
dhy
template<typename _Potential > real espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::dhy protected
Definition at line 126 of file VerletListAdressATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::VerletListAdressATInteractionTemplate().
fixedtupleList
template<typename _Potential > shared_ptr<FixedTupleListAdress> espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::fixedtupleList protected
Definition at line 118 of file VerletListAdressATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeEnergy(), and espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::setFixedTupleList().
ntypes
template<typename _Potential > int espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::ntypes protected
Definition at line 116 of file VerletListAdressATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::getMaxCutoff(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::setPotential(), and espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::VerletListAdressATInteractionTemplate().
pidhy2
template<typename _Potential > real espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::pidhy2 protected
Definition at line 122 of file VerletListAdressATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeEnergy(), and espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::VerletListAdressATInteractionTemplate().
potentialArray
template<typename _Potential > esutil::Array2D<Potential, esutil::enlarge> espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::potentialArray protected
Definition at line 119 of file VerletListAdressATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::getPotential(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::getPotentialPtr(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::setPotential(), and espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::VerletListAdressATInteractionTemplate().
verletList
template<typename _Potential > shared_ptr<VerletListAdress> espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::verletList protected
Definition at line 117 of file VerletListAdressATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::getVerletList(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::setVerletList(), and espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::VerletListAdressATInteractionTemplate().
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/interaction/VerletListAdressATInteractionTemplate.hpp