ESPResSo++: espressopp::analysis::OrderParameter Class Reference
espressopp::analysis::OrderParameter Class Reference
compute order parameter.
#include <OrderParameter.hpp>
Classes
struct communicate_label
Public Member Functions
OrderParameter (shared_ptr< System > system, real _cutoff, int _angular_momentum, bool _do_cl_an, bool _incl_surface, real _d_min, real _d_max)
virtual ~OrderParameter ()
dcomplex SphHarm (int l_, int m_, Real3D r_)
void setAngularMomentum (int v)
int getAngularMomentum ()
void setCutoff (real v)
real getCutoff ()
void setDo_cl_an (bool v)
bool getDo_cl_an ()
void setIncl_surface (bool v)
bool getIncl_surface ()
void setD_min (int v)
int getD_min ()
void setD_max (int v)
int getD_max ()
void setMax_Cl (int v)
int getMax_Cl ()
void setNum_of_Cl (int v)
int getNum_of_Cl ()
RealND computeRaw ()
void define_solid ()
void cluster_analysis ()
void global_cluster_analysis ()
void relab22 (int new_lab, int old_lab)
void local_cluster_search ()
void cluster_walk (int pid, int cur_lab, OrderParticleProps &opp)
void relab (int new_lab, int old_lab)
void relab11 (int new_lab, int old_lab)
int getCorrectLabel (int current_label)
void relabel_particles ()
void biggest_cluster ()
python::list compute ()
python::list getAverageValue ()
void resetAverage ()
void updateAverage (RealND res)
virtual void performMeasurement ()
This method will measure the observable and can be called from within the integrator by using the ExtAnalyse extension.
virtual void reset ()
This method resets/initializes the measurement.
virtual int getNumberOfMeasurements ()
return the number of measurements since the last reset
void perform_action ()
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (logger)
Public Attributes
unordered_map< int, int > wrong_label_local0
vector< communicate_label > outside_id
unordered_map< int, int > wrong_label_local
Protected Attributes
RealND newAverage
RealND lastAverage
RealND newVariance
RealND lastVariance
int nMeasurements
Private Attributes
real cutoff
real cutoff_sq
int angular_momentum
boost::unordered_multimap< int, OrderParticleProps > opp_map
boost::unordered_multimap< int, int > pairs
bool do_cl_an
bool incl_surface
real d_min
real d_max
int max_cluster
int number_of_clust
Detailed Description
compute order parameter.
Definition at line 196 of file OrderParameter.hpp.
Constructor & Destructor Documentation
espressopp::analysis::OrderParameter::OrderParameter (shared_ptr< System > system, real _cutoff, int _angular_momentum, bool _do_cl_an, bool _incl_surface, real _d_min, real _d_max) inline
Definition at line 229 of file OrderParameter.hpp.
virtual espressopp::analysis::OrderParameter::~OrderParameter () inline virtual
Definition at line 247 of file OrderParameter.hpp.
Member Function Documentation
void espressopp::analysis::OrderParameter::biggest_cluster () inline
Definition at line 840 of file OrderParameter.hpp.
References espressopp::analysis::OrderParticleProps::getLabel(), espressopp::analysis::OrderParticleProps::getPID(), espressopp::Particle::id(), and espressopp::iterator::CellListIterator::isDone().
void espressopp::analysis::OrderParameter::cluster_analysis () inline
Definition at line 541 of file OrderParameter.hpp.
void espressopp::analysis::OrderParameter::cluster_walk (int pid, int cur_lab, OrderParticleProps & opp) inline
Definition at line 743 of file OrderParameter.hpp.
References espressopp::analysis::OrderParameter::communicate_label::cpu, espressopp::analysis::OrderParticleProps::getLabel(), espressopp::analysis::OrderParticleProps::getNN(), espressopp::analysis::OrderParticleProps::getNumNN(), espressopp::analysis::OrderParticleProps::getSolid(), espressopp::analysis::OrderParticleProps::getSurface(), espressopp::analysis::OrderParameter::communicate_label::label, espressopp::analysis::OrderParameter::communicate_label::pid, and espressopp::analysis::OrderParticleProps::setLabel().
python::list espressopp::analysis::OrderParameter::compute () inline virtual
Implements espressopp::analysis::AnalysisBaseTemplate< RealND >.
Definition at line 931 of file OrderParameter.hpp.
RealND espressopp::analysis::OrderParameter::computeRaw () inline virtual
Implements espressopp::analysis::AnalysisBaseTemplate< RealND >.
Definition at line 279 of file OrderParameter.hpp.
References espressopp::analysis::OrderParticleProps::addQlmVector(), espressopp::analysis::OrderParticleProps::calculateSumQlm(), espressopp::analysis::OrderParticleProps::getD(), espressopp::analysis::OrderParticleProps::getNN(), espressopp::analysis::OrderParticleProps::getNumNN(), espressopp::analysis::OrderParticleProps::getPID(), espressopp::analysis::OrderParticleProps::getQlm(), espressopp::analysis::OrderParticleProps::getQlmVector(), espressopp::analysis::OrderParticleProps::getSumQlm(), espressopp::Particle::id(), espressopp::analysis::OrderParticleProps::insertNN(), espressopp::iterator::CellListIterator::isDone(), espressopp::iterator::CellListAllPairsIterator::isValid(), espressopp::analysis::OrderParticleProps::setD(), espressopp::analysis::OrderParticleProps::setQlm(), and espressopp::Real3D::sqr().
void espressopp::analysis::OrderParameter::define_solid () inline
Definition at line 478 of file OrderParameter.hpp.
References espressopp::analysis::OrderParticleProps::getD(), espressopp::analysis::OrderParticleProps::getNN(), espressopp::analysis::OrderParticleProps::getNumNN(), espressopp::analysis::OrderParticleProps::getPID(), espressopp::analysis::OrderParticleProps::getSolid(), espressopp::analysis::OrderParticleProps::getSurface(), espressopp::Particle::id(), espressopp::iterator::CellListIterator::isDone(), espressopp::analysis::OrderParticleProps::setSolid(), and espressopp::analysis::OrderParticleProps::setSurface().
int espressopp::analysis::OrderParameter::getAngularMomentum () inline
Definition at line 253 of file OrderParameter.hpp.
Referenced by registerPython().
python::list espressopp::analysis::OrderParameter::getAverageValue () inline virtual
Implements espressopp::analysis::AnalysisBaseTemplate< RealND >.
Definition at line 1003 of file OrderParameter.hpp.
int espressopp::analysis::OrderParameter::getCorrectLabel (int current_label) inline
Definition at line 813 of file OrderParameter.hpp.
real espressopp::analysis::OrderParameter::getCutoff () inline
Definition at line 258 of file OrderParameter.hpp.
Referenced by registerPython().
int espressopp::analysis::OrderParameter::getD_max () inline
Definition at line 270 of file OrderParameter.hpp.
int espressopp::analysis::OrderParameter::getD_min () inline
Definition at line 268 of file OrderParameter.hpp.
bool espressopp::analysis::OrderParameter::getDo_cl_an () inline
Definition at line 262 of file OrderParameter.hpp.
bool espressopp::analysis::OrderParameter::getIncl_surface () inline
Definition at line 265 of file OrderParameter.hpp.
int espressopp::analysis::OrderParameter::getMax_Cl () inline
Definition at line 273 of file OrderParameter.hpp.
int espressopp::analysis::OrderParameter::getNum_of_Cl () inline
Definition at line 275 of file OrderParameter.hpp.
virtual int espressopp::analysis::AnalysisBaseTemplate< RealND >::getNumberOfMeasurements () virtual inherited
return the number of measurements since the last reset
Implements espressopp::analysis::AnalysisBase.
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::LatticeBoltzmann::assignMyLattice(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::io::DumpXYZ::DumpXYZ(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::VerletListTriple::registerPython(), espressopp::VerletList::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::addForces(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::addForces(), espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerlet::calcForces(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::VelocityVerlet::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::VelocityVerlet::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::VelocityVerlet::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::VelocityVerlet::printForces(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerlet::printPositions(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::MinimizeEnergy::run(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::Rattle::saveOldPos(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostatOnGroup::thermalize(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::VelocityVerlet::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
void espressopp::analysis::OrderParameter::global_cluster_analysis () inline
Definition at line 565 of file OrderParameter.hpp.
References espressopp::analysis::OrderParameter::communicate_label::cpu, espressopp::analysis::OrderParticleProps::getLabel(), espressopp::analysis::OrderParticleProps::getSolid(), espressopp::analysis::OrderParticleProps::getSurface(), espressopp::analysis::OrderParameter::communicate_label::label, espressopp::analysis::OrderParameter::communicate_label::pid, and espressopp::analysis::OrderParticleProps::setLabel().
void espressopp::analysis::OrderParameter::local_cluster_search () inline
Definition at line 698 of file OrderParameter.hpp.
References espressopp::analysis::OrderParticleProps::getLabel(), espressopp::analysis::OrderParticleProps::getSolid(), espressopp::analysis::OrderParticleProps::getSurface(), espressopp::Particle::id(), and espressopp::iterator::CellListIterator::isDone().
static espressopp::analysis::AnalysisBase::LOG4ESPP_DECL_LOGGER (logger) static inherited
Referenced by espressopp::analysis::AnalysisBase::perform_action().
void espressopp::analysis::AnalysisBase::perform_action () inline virtual inherited
Implements espressopp::ParticleAccess.
Reimplemented in espressopp::analysis::CMVelocity.
Definition at line 54 of file AnalysisBase.hpp.
References espressopp::analysis::AnalysisBase::LOG4ESPP_DECL_LOGGER(), espressopp::analysis::AnalysisBase::performMeasurement(), and espressopp::analysis::AnalysisBase::registerPython().
virtual void espressopp::analysis::AnalysisBaseTemplate< RealND >::performMeasurement () virtual inherited
This method will measure the observable and can be called from within the integrator by using the ExtAnalyse extension.
It can also be called from python. It will also update the average value (typically also the variance) of the observable
Implements espressopp::analysis::AnalysisBase.
void espressopp::analysis::OrderParameter::registerPython () static
Definition at line 66 of file OrderParameter.cpp.
References getAngularMomentum(), getCutoff(), setAngularMomentum(), and setCutoff().
Referenced by espressopp::analysis::registerPython().
void espressopp::analysis::OrderParameter::relab (int new_lab, int old_lab) inline
Definition at line 790 of file OrderParameter.hpp.
References espressopp::analysis::OrderParticleProps::getLabel(), and espressopp::analysis::OrderParticleProps::setLabel().
void espressopp::analysis::OrderParameter::relab11 (int new_lab, int old_lab) inline
Definition at line 799 of file OrderParameter.hpp.
void espressopp::analysis::OrderParameter::relab22 (int new_lab, int old_lab) inline
Definition at line 683 of file OrderParameter.hpp.
void espressopp::analysis::OrderParameter::relabel_particles () inline
Definition at line 822 of file OrderParameter.hpp.
References espressopp::analysis::OrderParticleProps::getLabel(), espressopp::analysis::OrderParticleProps::getPID(), espressopp::analysis::OrderParticleProps::getSolid(), espressopp::analysis::OrderParticleProps::getSurface(), and espressopp::analysis::OrderParticleProps::setLabel().
virtual void espressopp::analysis::AnalysisBaseTemplate< RealND >::reset () virtual inherited
This method resets/initializes the measurement.
Implements espressopp::analysis::AnalysisBase.
void espressopp::analysis::OrderParameter::resetAverage () inline virtual
Implements espressopp::analysis::AnalysisBaseTemplate< RealND >.
Definition at line 1015 of file OrderParameter.hpp.
void espressopp::analysis::OrderParameter::setAngularMomentum (int v) inline
Definition at line 252 of file OrderParameter.hpp.
Referenced by registerPython().
void espressopp::analysis::OrderParameter::setCutoff (real v) inline
Definition at line 254 of file OrderParameter.hpp.
Referenced by registerPython().
void espressopp::analysis::OrderParameter::setD_max (int v) inline
Definition at line 269 of file OrderParameter.hpp.
void espressopp::analysis::OrderParameter::setD_min (int v) inline
Definition at line 267 of file OrderParameter.hpp.
void espressopp::analysis::OrderParameter::setDo_cl_an (bool v) inline
Definition at line 261 of file OrderParameter.hpp.
void espressopp::analysis::OrderParameter::setIncl_surface (bool v) inline
Definition at line 264 of file OrderParameter.hpp.
void espressopp::analysis::OrderParameter::setMax_Cl (int v) inline
Definition at line 272 of file OrderParameter.hpp.
void espressopp::analysis::OrderParameter::setNum_of_Cl (int v) inline
Definition at line 274 of file OrderParameter.hpp.
dcomplex espressopp::analysis::OrderParameter::SphHarm (int l_, int m_, Real3D r_)
Definition at line 32 of file OrderParameter.cpp.
References espressopp::Real3D::abs(), and M_PIl.
void espressopp::analysis::OrderParameter::updateAverage (RealND res) inline virtual
Implements espressopp::analysis::AnalysisBaseTemplate< RealND >.
Definition at line 1022 of file OrderParameter.hpp.
Member Data Documentation
int espressopp::analysis::OrderParameter::angular_momentum private
Definition at line 200 of file OrderParameter.hpp.
real espressopp::analysis::OrderParameter::cutoff private
Definition at line 198 of file OrderParameter.hpp.
real espressopp::analysis::OrderParameter::cutoff_sq private
Definition at line 199 of file OrderParameter.hpp.
real espressopp::analysis::OrderParameter::d_max private
Definition at line 222 of file OrderParameter.hpp.
real espressopp::analysis::OrderParameter::d_min private
Definition at line 222 of file OrderParameter.hpp.
bool espressopp::analysis::OrderParameter::do_cl_an private
Definition at line 210 of file OrderParameter.hpp.
bool espressopp::analysis::OrderParameter::incl_surface private
Definition at line 211 of file OrderParameter.hpp.
RealND espressopp::analysis::AnalysisBaseTemplate< RealND >::lastAverage protected inherited
Definition at line 79 of file AnalysisBase.hpp.
RealND espressopp::analysis::AnalysisBaseTemplate< RealND >::lastVariance protected inherited
Definition at line 80 of file AnalysisBase.hpp.
int espressopp::analysis::OrderParameter::max_cluster private
Definition at line 224 of file OrderParameter.hpp.
RealND espressopp::analysis::AnalysisBaseTemplate< RealND >::newAverage protected inherited
Definition at line 79 of file AnalysisBase.hpp.
RealND espressopp::analysis::AnalysisBaseTemplate< RealND >::newVariance protected inherited
Definition at line 80 of file AnalysisBase.hpp.
int espressopp::analysis::AnalysisBaseTemplate< RealND >::nMeasurements protected inherited
Definition at line 81 of file AnalysisBase.hpp.
int espressopp::analysis::OrderParameter::number_of_clust private
Definition at line 224 of file OrderParameter.hpp.
boost::unordered_multimap<int, OrderParticleProps> espressopp::analysis::OrderParameter::opp_map private
Definition at line 203 of file OrderParameter.hpp.
vector< communicate_label > espressopp::analysis::OrderParameter::outside_id
Definition at line 737 of file OrderParameter.hpp.
boost::unordered_multimap<int, int> espressopp::analysis::OrderParameter::pairs private
Definition at line 205 of file OrderParameter.hpp.
unordered_map< int, int > espressopp::analysis::OrderParameter::wrong_label_local
Definition at line 739 of file OrderParameter.hpp.
unordered_map< int, int > espressopp::analysis::OrderParameter::wrong_label_local0
Definition at line 681 of file OrderParameter.hpp.
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/analysis/OrderParameter.hpp
/home/espressopp/espressopp/src/analysis/OrderParameter.cpp