ESPResSo++: espressopp::interaction::AngularPotentialTemplate< Derived > Class Template Reference
espressopp::interaction::AngularPotentialTemplate< Derived > Class Template Reference
Provides a template for the simple implementation of a shifted, absolute distance dependent potential with cutoff.
#include <AngularPotential.hpp>
Public Member Functions
AngularPotentialTemplate ()
virtual real computeEnergy (const Particle &p1, const Particle &p2, const Particle &p3) const
virtual real computeEnergy (const Real3D &dist12, const Real3D &dist32) const
virtual real computeEnergy (const real theta) const
virtual void computeForce (Real3D &force12, Real3D &force32, const Particle &p1, const Particle &p2, const Particle &p3) const
virtual void computeForce (Real3D &force12, Real3D &force32, const Real3D &dist12, const Real3D &dist32) const
virtual real computeForce (real theta) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
real _computeEnergy (const Particle &p1, const Particle &p2, const Particle &p3) const
real _computeEnergy (const Real3D &dist12, const Real3D &dist32) const
real _computeEnergy (real theta) const
void _computeForce (Real3D &force12, Real3D &force32, const Particle &p1, const Particle &p2, const Particle &p3) const
bool _computeForce (Real3D &force12, Real3D &force32, const Real3D &dist12, const Real3D &dist32) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
Derived * derived_this ()
const Derived * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
Detailed Description
template<class Derived>
class espressopp::interaction::AngularPotentialTemplate< Derived >
Provides a template for the simple implementation of a shifted, absolute distance dependent potential with cutoff.
Definition at line 67 of file AngularPotential.hpp.
Constructor & Destructor Documentation
template<class Derived > espressopp::interaction::AngularPotentialTemplate< Derived >::AngularPotentialTemplate () [inline]
Definition at line 126 of file AngularPotential.hpp.
Member Function Documentation
template<class Derived > real espressopp::interaction::AngularPotentialTemplate< Derived >::_computeEnergy (const Particle & p1, const Particle & p2, const Particle & p3) const [inline]
Definition at line 175 of file AngularPotential.hpp.
References espressopp::Particle::position().
template<class Derived > real espressopp::interaction::AngularPotentialTemplate< Derived >::_computeEnergy (const Real3D & dist12, const Real3D & dist32) const [inline]
Reimplemented in espressopp::interaction::TersoffTripleTerm, and espressopp::interaction::StillingerWeberTripleTerm.
Definition at line 184 of file AngularPotential.hpp.
template<class Derived > real espressopp::interaction::AngularPotentialTemplate< Derived >::_computeEnergy (real theta) const [inline]
Definition at line 199 of file AngularPotential.hpp.
template<class Derived > void espressopp::interaction::AngularPotentialTemplate< Derived >::_computeForce (Real3D & force12, Real3D & force32, const Particle & p1, const Particle & p2, const Particle & p3) const [inline]
Definition at line 228 of file AngularPotential.hpp.
References espressopp::Particle::position().
template<class Derived > bool espressopp::interaction::AngularPotentialTemplate< Derived >::_computeForce (Real3D & force12, Real3D & force32, const Real3D & dist12, const Real3D & dist32) const [inline]
Definition at line 239 of file AngularPotential.hpp.
template<class Derived > real espressopp::interaction::AngularPotentialTemplate< Derived >::computeEnergy (const Particle & p1, const Particle & p2, const Particle & p3) const [inline, virtual]
Implements espressopp::interaction::AngularPotential.
Definition at line 149 of file AngularPotential.hpp.
References espressopp::Particle::position().
template<class Derived > real espressopp::interaction::AngularPotentialTemplate< Derived >::computeEnergy (const Real3D & dist12, const Real3D & dist32) const [inline, virtual]
Implements espressopp::interaction::AngularPotential.
Definition at line 158 of file AngularPotential.hpp.
template<class Derived > real espressopp::interaction::AngularPotentialTemplate< Derived >::computeEnergy (const real theta) const [inline, virtual]
Implements espressopp::interaction::AngularPotential.
Definition at line 168 of file AngularPotential.hpp.
template<class Derived > void espressopp::interaction::AngularPotentialTemplate< Derived >::computeForce (Real3D & force12, Real3D & force32, const Particle & p1, const Particle & p2, const Particle & p3) const [inline, virtual]
Implements espressopp::interaction::AngularPotential.
Definition at line 207 of file AngularPotential.hpp.
References espressopp::Particle::position().
template<class Derived > void espressopp::interaction::AngularPotentialTemplate< Derived >::computeForce (Real3D & force12, Real3D & force32, const Real3D & dist12, const Real3D & dist32) const [inline, virtual]
Implements espressopp::interaction::AngularPotential.
Definition at line 218 of file AngularPotential.hpp.
template<class Derived > real espressopp::interaction::AngularPotentialTemplate< Derived >::computeForce (real theta) const [inline, virtual]
Implements espressopp::interaction::AngularPotential.
Definition at line 251 of file AngularPotential.hpp.
template<class Derived> Derived* espressopp::interaction::AngularPotentialTemplate< Derived >::derived_this () [inline, protected]
Definition at line 111 of file AngularPotential.hpp.
template<class Derived> const Derived* espressopp::interaction::AngularPotentialTemplate< Derived >::derived_this () const [inline, protected]
Definition at line 115 of file AngularPotential.hpp.
template<class Derived > real espressopp::interaction::AngularPotentialTemplate< Derived >::getCutoff () const [inline, virtual]
Implements espressopp::interaction::AngularPotential.
Reimplemented in espressopp::interaction::TersoffTripleTerm, and espressopp::interaction::StillingerWeberTripleTerm.
Definition at line 142 of file AngularPotential.hpp.
static espressopp::interaction::AngularPotential::LOG4ESPP_DECL_LOGGER (theLogger) [static, inherited]
void espressopp::interaction::AngularPotential::registerPython () [static, inherited]
Reimplemented in espressopp::interaction::TersoffTripleTerm, espressopp::interaction::StillingerWeberTripleTerm, espressopp::interaction::AngularCosineSquared, espressopp::interaction::AngularHarmonic, espressopp::interaction::Cosine, and espressopp::interaction::TabulatedAngular.
Definition at line 35 of file AngularPotential.cpp.
References espressopp::interaction::AngularPotential::computeEnergy(), espressopp::interaction::AngularPotential::computeForce(), espressopp::interaction::AngularPotential::getCutoff(), and espressopp::interaction::AngularPotential::setCutoff().
Referenced by espressopp::interaction::registerPython().
template<class Derived > void espressopp::interaction::AngularPotentialTemplate< Derived >::setCutoff (real _cutoff) [inline, virtual]
Implements espressopp::interaction::AngularPotential.
Definition at line 134 of file AngularPotential.hpp.
Member Data Documentation
template<class Derived> real espressopp::interaction::AngularPotentialTemplate< Derived >::cutoff [protected]
Definition at line 108 of file AngularPotential.hpp.
template<class Derived> real espressopp::interaction::AngularPotentialTemplate< Derived >::cutoffSqr [protected]
Definition at line 109 of file AngularPotential.hpp.
The documentation for this class was generated from the following file:
/home/travis/build/espressopp/espressopp/src/interaction/AngularPotential.hpp