ESPResSo++: espressopp::interaction::PotentialVSpherePairTemplate< Derived > Class Template Reference
espressopp::interaction::PotentialVSpherePairTemplate< Derived > Class Template Reference
Provides a template for the simple implementation of a shifted, absolute distance dependent potential with cutoff.
#include <PotentialVSpherePair.hpp>
Public Member Functions
PotentialVSpherePairTemplate ()
virtual ~PotentialVSpherePairTemplate ()
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist, real &sigmaij) const
virtual real computeEnergy (real dist, real sigmaij) const
virtual real computeEnergySqr (real distsqr, real sigmaij) const
virtual python::list computeForce (const Particle &p1, const Particle &p2) const
virtual python::list computeForce (const Real3D &dist, const real &sigmai, const real &sigmaj) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Real3D &dist, real &sigmaij) const
real _computeEnergy (real dist, real sigmaij) const
real _computeEnergySqr (real distSqr, real sigmaij) const
bool _computeForce (Real3D &force, real &sigiforce, real &sigjforce, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, real &sigiforce, real &sigjforce, const Real3D &dist, const real &sigmai, const real &sigmaj) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
Derived * derived_this ()
const Derived * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
Detailed Description
template<class Derived>
class espressopp::interaction::PotentialVSpherePairTemplate< Derived >
Provides a template for the simple implementation of a shifted, absolute distance dependent potential with cutoff.
Definition at line 68 of file PotentialVSpherePair.hpp.
Constructor & Destructor Documentation
PotentialVSpherePairTemplate()
template<class Derived > espressopp::interaction::PotentialVSpherePairTemplate< Derived >::PotentialVSpherePairTemplate inline
Definition at line 151 of file PotentialVSpherePair.hpp.
~PotentialVSpherePairTemplate()
template<class Derived > virtual espressopp::interaction::PotentialVSpherePairTemplate< Derived >::~PotentialVSpherePairTemplate () inline virtual
Definition at line 71 of file PotentialVSpherePair.hpp.
Member Function Documentation
_computeEnergy() [1/3]
template<class Derived > real espressopp::interaction::PotentialVSpherePairTemplate< Derived >::_computeEnergy (const Particle & p1, const Particle & p2) const inline
Definition at line 240 of file PotentialVSpherePair.hpp.
_computeEnergy() [2/3]
template<class Derived > real espressopp::interaction::PotentialVSpherePairTemplate< Derived >::_computeEnergy (const Real3D & dist, real & sigmaij) const inline
Definition at line 251 of file PotentialVSpherePair.hpp.
_computeEnergy() [3/3]
template<class Derived > real espressopp::interaction::PotentialVSpherePairTemplate< Derived >::_computeEnergy (real dist, real sigmaij) const inline
Definition at line 258 of file PotentialVSpherePair.hpp.
_computeEnergySqr()
template<class Derived > real espressopp::interaction::PotentialVSpherePairTemplate< Derived >::_computeEnergySqr (real distSqr, real sigmaij) const inline
Definition at line 265 of file PotentialVSpherePair.hpp.
_computeForce() [1/2]
template<class Derived > bool espressopp::interaction::PotentialVSpherePairTemplate< Derived >::_computeForce (Real3D & force, real & sigiforce, real & sigjforce, const Particle & p1, const Particle & p2) const inline
Definition at line 317 of file PotentialVSpherePair.hpp.
_computeForce() [2/2]
template<class Derived > bool espressopp::interaction::PotentialVSpherePairTemplate< Derived >::_computeForce (Real3D & force, real & sigiforce, real & sigjforce, const Real3D & dist, const real & sigmai, const real & sigmaj) const inline
Definition at line 328 of file PotentialVSpherePair.hpp.
computeEnergy() [1/3]
template<class Derived > real espressopp::interaction::PotentialVSpherePairTemplate< Derived >::computeEnergy (const Particle & p1, const Particle & p2) const inline virtual
Implements espressopp::interaction::PotentialVSpherePair.
Definition at line 208 of file PotentialVSpherePair.hpp.
computeEnergy() [2/3]
template<class Derived > real espressopp::interaction::PotentialVSpherePairTemplate< Derived >::computeEnergy (const Real3D & dist, real & sigmaij) const inline virtual
Implements espressopp::interaction::PotentialVSpherePair.
Definition at line 219 of file PotentialVSpherePair.hpp.
computeEnergy() [3/3]
template<class Derived > real espressopp::interaction::PotentialVSpherePairTemplate< Derived >::computeEnergy (real dist, real sigmaij) const inline virtual
Implements espressopp::interaction::PotentialVSpherePair.
Definition at line 226 of file PotentialVSpherePair.hpp.
computeEnergySqr()
template<class Derived > real espressopp::interaction::PotentialVSpherePairTemplate< Derived >::computeEnergySqr (real distsqr, real sigmaij) const inline virtual
Implements espressopp::interaction::PotentialVSpherePair.
Definition at line 233 of file PotentialVSpherePair.hpp.
computeForce() [1/2]
template<class Derived > python::list espressopp::interaction::PotentialVSpherePairTemplate< Derived >::computeForce (const Particle & p1, const Particle & p2) const inline virtual
Implements espressopp::interaction::PotentialVSpherePair.
Definition at line 279 of file PotentialVSpherePair.hpp.
computeForce() [2/2]
template<class Derived > python::list espressopp::interaction::PotentialVSpherePairTemplate< Derived >::computeForce (const Real3D & dist, const real & sigmai, const real & sigmaj) const inline virtual
Implements espressopp::interaction::PotentialVSpherePair.
Definition at line 298 of file PotentialVSpherePair.hpp.
derived_this() [1/2]
template<class Derived > Derived* espressopp::interaction::PotentialVSpherePairTemplate< Derived >::derived_this () inline protected
Definition at line 118 of file PotentialVSpherePair.hpp.
derived_this() [2/2]
template<class Derived > const Derived* espressopp::interaction::PotentialVSpherePairTemplate< Derived >::derived_this () const inline protected
Definition at line 122 of file PotentialVSpherePair.hpp.
getCutoff()
template<class Derived > real espressopp::interaction::PotentialVSpherePairTemplate< Derived >::getCutoff inline virtual
Implements espressopp::interaction::PotentialVSpherePair.
Definition at line 165 of file PotentialVSpherePair.hpp.
Referenced by espressopp::interaction::VSpherePair_pickle::getinitargs().
getShift()
template<class Derived > real espressopp::interaction::PotentialVSpherePairTemplate< Derived >::getShift inline virtual
Implements espressopp::interaction::PotentialVSpherePair.
Definition at line 179 of file PotentialVSpherePair.hpp.
Referenced by espressopp::interaction::VSpherePair_pickle::getinitargs().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::PotentialVSpherePair::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
registerPython()
void espressopp::interaction::PotentialVSpherePair::registerPython () static inherited
Definition at line 35 of file PotentialVSpherePair.cpp.
References espressopp::interaction::PotentialVSpherePair::computeEnergy(), espressopp::interaction::PotentialVSpherePair::computeForce(), espressopp::interaction::PotentialVSpherePair::getCutoff(), espressopp::interaction::PotentialVSpherePair::getShift(), espressopp::interaction::PotentialVSpherePair::setAutoShift(), espressopp::interaction::PotentialVSpherePair::setCutoff(), and espressopp::interaction::PotentialVSpherePair::setShift().
Referenced by espressopp::interaction::registerPython().
setAutoShift()
template<class Derived > real espressopp::interaction::PotentialVSpherePairTemplate< Derived >::setAutoShift inline virtual
Implements espressopp::interaction::PotentialVSpherePair.
Definition at line 185 of file PotentialVSpherePair.hpp.
setCutoff()
template<class Derived > void espressopp::interaction::PotentialVSpherePairTemplate< Derived >::setCutoff (real _cutoff) inline virtual
Implements espressopp::interaction::PotentialVSpherePair.
Definition at line 157 of file PotentialVSpherePair.hpp.
setShift()
template<class Derived > void espressopp::interaction::PotentialVSpherePairTemplate< Derived >::setShift (real _shift) inline virtual
Implements espressopp::interaction::PotentialVSpherePair.
Definition at line 171 of file PotentialVSpherePair.hpp.
updateAutoShift()
template<class Derived > void espressopp::interaction::PotentialVSpherePairTemplate< Derived >::updateAutoShift inline
Definition at line 200 of file PotentialVSpherePair.hpp.
Member Data Documentation
autoShift
template<class Derived > bool espressopp::interaction::PotentialVSpherePairTemplate< Derived >::autoShift protected
Definition at line 116 of file PotentialVSpherePair.hpp.
cutoff
template<class Derived > real espressopp::interaction::PotentialVSpherePairTemplate< Derived >::cutoff protected
Definition at line 113 of file PotentialVSpherePair.hpp.
cutoffSqr
template<class Derived > real espressopp::interaction::PotentialVSpherePairTemplate< Derived >::cutoffSqr protected
Definition at line 114 of file PotentialVSpherePair.hpp.
shift
template<class Derived > real espressopp::interaction::PotentialVSpherePairTemplate< Derived >::shift protected
Definition at line 115 of file PotentialVSpherePair.hpp.
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/interaction/PotentialVSpherePair.hpp