ESPResSo++: espressopp::interaction::Morse Class Reference
espressopp::interaction::Morse Class Reference
This class provides methods to compute forces and energies of the Morse potential.
#include <Morse.hpp>
Public Member Functions
Morse ()
Morse (real _epsilon, real _alpha, real _rMin, real _cutoff, real _shift)
Morse (real _epsilon, real _alpha, real _rMin, real _cutoff)
void setEpsilon (real _epsilon)
real getEpsilon () const
void setAlpha (real _alpha)
real getAlpha () const
void setRMin (real _rMin)
real getRMin () const
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &dist, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
Morse * derived_this ()
const Morse * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
Private Attributes
real epsilon
real alpha
real rMin
Detailed Description
This class provides methods to compute forces and energies of the Morse potential.
Definition at line 37 of file Morse.hpp.
Constructor & Destructor Documentation
espressopp::interaction::Morse::Morse () [inline]
Definition at line 46 of file Morse.hpp.
References espressopp::infinity, espressopp::interaction::PotentialTemplate< Morse >::setCutoff(), and espressopp::interaction::PotentialTemplate< Morse >::setShift().
espressopp::interaction::Morse::Morse (real _epsilon, real _alpha, real _rMin, real _cutoff, real _shift) [inline]
Definition at line 52 of file Morse.hpp.
References espressopp::interaction::PotentialTemplate< Morse >::setCutoff(), and espressopp::interaction::PotentialTemplate< Morse >::setShift().
espressopp::interaction::Morse::Morse (real _epsilon, real _alpha, real _rMin, real _cutoff) [inline]
Definition at line 58 of file Morse.hpp.
References espressopp::interaction::PotentialTemplate< Morse >::autoShift, espressopp::interaction::PotentialTemplate< Morse >::setAutoShift(), and espressopp::interaction::PotentialTemplate< Morse >::setCutoff().
Member Function Documentation
real espressopp::interaction::PotentialTemplate< Morse >::_computeEnergy (const Particle & p1, const Particle & p2) const [inherited]
real espressopp::interaction::PotentialTemplate< Morse >::_computeEnergy (const Real3D & dist) const [inherited]
real espressopp::interaction::PotentialTemplate< Morse >::_computeEnergy (real dist) const [inherited]
real espressopp::interaction::PotentialTemplate< Morse >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const [inherited]
real espressopp::interaction::PotentialTemplate< Morse >::_computeEnergySqr (real distSqr) const [inherited]
real espressopp::interaction::Morse::_computeEnergySqrRaw (real distSqr) const [inline]
Definition at line 84 of file Morse.hpp.
References alpha, epsilon, and rMin.
bool espressopp::interaction::PotentialTemplate< Morse >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const [inherited]
bool espressopp::interaction::PotentialTemplate< Morse >::_computeForce (Real3D & force, const Real3D & dist) const [inherited]
bool espressopp::interaction::PotentialTemplate< Morse >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const [inherited]
bool espressopp::interaction::Morse::_computeForceRaw (Real3D & force, const Real3D & dist, real distSqr) const [inline]
Definition at line 91 of file Morse.hpp.
References alpha, epsilon, and rMin.
virtual real espressopp::interaction::PotentialTemplate< Morse >::computeEnergy (const Particle & p1, const Particle & p2) const [virtual, inherited]
Implements espressopp::interaction::Potential.
virtual real espressopp::interaction::PotentialTemplate< Morse >::computeEnergy (const Real3D & dist) const [virtual, inherited]
Implements espressopp::interaction::Potential.
virtual real espressopp::interaction::PotentialTemplate< Morse >::computeEnergy (real dist) const [virtual, inherited]
Implements espressopp::interaction::Potential.
virtual real espressopp::interaction::PotentialTemplate< Morse >::computeEnergySqr (real distsqr) const [virtual, inherited]
Implements espressopp::interaction::Potential.
virtual Real3D espressopp::interaction::PotentialTemplate< Morse >::computeForce (const Particle & p1, const Particle & p2) const [virtual, inherited]
Implements espressopp::interaction::Potential.
virtual Real3D espressopp::interaction::PotentialTemplate< Morse >::computeForce (const Real3D & dist) const [virtual, inherited]
Implements espressopp::interaction::Potential.
Morse * espressopp::interaction::PotentialTemplate< Morse >::derived_this () [inline, protected, inherited]
Definition at line 121 of file Potential.hpp.
const Morse * espressopp::interaction::PotentialTemplate< Morse >::derived_this () const [inline, protected, inherited]
Definition at line 125 of file Potential.hpp.
real espressopp::interaction::Morse::getAlpha () const [inline]
Definition at line 76 of file Morse.hpp.
References alpha.
Referenced by espressopp::interaction::Morse_pickle::getinitargs(), and registerPython().
virtual real espressopp::interaction::PotentialTemplate< Morse >::getCutoff () const [virtual, inherited]
Implements espressopp::interaction::Potential.
real espressopp::interaction::Morse::getEpsilon () const [inline]
Definition at line 70 of file Morse.hpp.
References epsilon.
Referenced by espressopp::interaction::Morse_pickle::getinitargs(), and registerPython().
real espressopp::interaction::Morse::getRMin () const [inline]
Definition at line 82 of file Morse.hpp.
References rMin.
Referenced by registerPython().
virtual real espressopp::interaction::PotentialTemplate< Morse >::getShift () const [virtual, inherited]
Implements espressopp::interaction::Potential.
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) [static, inherited]
Reimplemented in espressopp::interaction::LennardJones, espressopp::interaction::LennardJonesGeneric, and espressopp::interaction::FENE.
void espressopp::interaction::Morse::registerPython () [static]
Reimplemented from espressopp::interaction::Potential.
Definition at line 49 of file Morse.cpp.
References getAlpha(), getEpsilon(), getRMin(), setAlpha(), setEpsilon(), and setRMin().
Referenced by espressopp::interaction::registerPython().
void espressopp::interaction::Morse::setAlpha (real _alpha) [inline]
Definition at line 72 of file Morse.hpp.
References alpha, and espressopp::interaction::PotentialTemplate< Morse >::updateAutoShift().
Referenced by registerPython().
virtual real espressopp::interaction::PotentialTemplate< Morse >::setAutoShift () [virtual, inherited]
Implements espressopp::interaction::Potential.
Referenced by Morse().
virtual void espressopp::interaction::PotentialTemplate< Morse >::setCutoff (real _cutoff) [virtual, inherited]
Implements espressopp::interaction::Potential.
Referenced by Morse().
void espressopp::interaction::Morse::setEpsilon (real _epsilon) [inline]
Definition at line 66 of file Morse.hpp.
References epsilon, and espressopp::interaction::PotentialTemplate< Morse >::updateAutoShift().
Referenced by registerPython().
void espressopp::interaction::Morse::setRMin (real _rMin) [inline]
Definition at line 78 of file Morse.hpp.
References rMin, and espressopp::interaction::PotentialTemplate< Morse >::updateAutoShift().
Referenced by registerPython().
virtual void espressopp::interaction::PotentialTemplate< Morse >::setShift (real _shift) [virtual, inherited]
Implements espressopp::interaction::Potential.
Referenced by Morse().
void espressopp::interaction::PotentialTemplate< Morse >::updateAutoShift () [inherited]
Referenced by setAlpha(), setEpsilon(), and setRMin().
Member Data Documentation
real espressopp::interaction::Morse::alpha [private]
Definition at line 40 of file Morse.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), getAlpha(), and setAlpha().
bool espressopp::interaction::PotentialTemplate< Morse >::autoShift [protected, inherited]
Definition at line 119 of file Potential.hpp.
Referenced by Morse().
real espressopp::interaction::PotentialTemplate< Morse >::cutoff [protected, inherited]
Definition at line 116 of file Potential.hpp.
real espressopp::interaction::PotentialTemplate< Morse >::cutoffSqr [protected, inherited]
Definition at line 117 of file Potential.hpp.
real espressopp::interaction::Morse::epsilon [private]
Definition at line 39 of file Morse.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), getEpsilon(), and setEpsilon().
real espressopp::interaction::Morse::rMin [private]
Definition at line 41 of file Morse.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), getRMin(), and setRMin().
real espressopp::interaction::PotentialTemplate< Morse >::shift [protected, inherited]
Definition at line 118 of file Potential.hpp.
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/interaction/Morse.hpp
/home/travis/build/espressopp/espressopp/src/interaction/Morse.cpp