ESPResSo++: espressopp::interaction::Tabulated Class Reference
espressopp::interaction::Tabulated Class Reference abstract
This class provides methods to compute forces and energies of a tabulated potential.
#include <Tabulated.hpp>
Public Member Functions
Tabulated ()
Tabulated (int itype, const char *filename)
Tabulated (int itype, const char *filename, real cutoff)
void setInterpolationType (int itype)
Setter for the interpolation type.
int getInterpolationType () const
Getter for the interpolation type.
void setFilename (int itype, const char *_filename)
Setter for the filename will read in the table.
const char * getFilename () const
Getter for the filename.
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &dist, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual real getCutoff () const =0
virtual void setShift (real _shift)
virtual real getShift () const
virtual real getShift () const =0
virtual real setAutoShift ()
void updateAutoShift ()
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)
virtual shared_ptr< FixedPairList > getColVarBondList () const
virtual shared_ptr< FixedPairList > getColVarBondList () const =0
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &fpl)
virtual shared_ptr< FixedTripleList > getColVarAngleList () const
virtual shared_ptr< FixedTripleList > getColVarAngleList () const =0
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fpl)
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const =0
virtual void setColVar (const RealND &cv)
virtual void setColVar (const Real3D &dist, const bc::BC &bc)
virtual RealND getColVar () const
virtual RealND getColVar () const =0
virtual void computeColVarWeights (const Real3D &dist, const bc::BC &bc)
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
real _computeEnergyDeriv (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
Tabulated * derived_this ()
const Tabulated * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
shared_ptr< FixedPairList > colVarBondList
shared_ptr< FixedTripleList > colVarAngleList
shared_ptr< FixedQuadrupleList > colVarDihedList
RealND colVar
Private Attributes
std::string filename
shared_ptr< Interpolation > table
int interpolationType
Detailed Description
This class provides methods to compute forces and energies of a tabulated potential.
The potential and forces must be provided in a file.
Be careful: default and copy constructor of this class are used.
Definition at line 43 of file Tabulated.hpp.
Constructor & Destructor Documentation
Tabulated() [1/3]
espressopp::interaction::Tabulated::Tabulated () inline
Definition at line 53 of file Tabulated.hpp.
References espressopp::infinity, interpolationType, espressopp::interaction::PotentialTemplate< Tabulated >::setCutoff(), and espressopp::interaction::PotentialTemplate< Tabulated >::setShift().
Tabulated() [2/3]
espressopp::interaction::Tabulated::Tabulated (int itype, const char * filename) inline
Definition at line 61 of file Tabulated.hpp.
References filename, espressopp::infinity, espressopp::interaction::PotentialTemplate< Tabulated >::setCutoff(), setFilename(), setInterpolationType(), and espressopp::interaction::PotentialTemplate< Tabulated >::setShift().
Tabulated() [3/3]
espressopp::interaction::Tabulated::Tabulated (int itype, const char * filename, real cutoff) inline
Definition at line 69 of file Tabulated.hpp.
References espressopp::interaction::PotentialTemplate< Tabulated >::cutoff, filename, espressopp::interaction::PotentialTemplate< Tabulated >::setCutoff(), setFilename(), setInterpolationType(), and espressopp::interaction::PotentialTemplate< Tabulated >::setShift().
Member Function Documentation
_computeEnergy() [1/4]
real espressopp::interaction::PotentialTemplate< Tabulated >::_computeEnergy (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 352 of file Potential.hpp.
_computeEnergy() [2/4]
real espressopp::interaction::PotentialTemplate< Tabulated >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 360 of file Potential.hpp.
_computeEnergy() [3/4]
real espressopp::interaction::PotentialTemplate< Tabulated >::_computeEnergy (const Real3D & dist) const inline inherited
Definition at line 367 of file Potential.hpp.
_computeEnergy() [4/4]
real espressopp::interaction::PotentialTemplate< Tabulated >::_computeEnergy (real dist) const inline inherited
Definition at line 374 of file Potential.hpp.
_computeEnergyDeriv()
real espressopp::interaction::PotentialTemplate< Tabulated >::_computeEnergyDeriv (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 395 of file Potential.hpp.
_computeEnergySqr()
real espressopp::interaction::PotentialTemplate< Tabulated >::_computeEnergySqr (real distSqr) const inline inherited
Definition at line 381 of file Potential.hpp.
_computeEnergySqrRaw()
real espressopp::interaction::Tabulated::_computeEnergySqrRaw (real distSqr) const inline
Definition at line 89 of file Tabulated.hpp.
References interpolationType, and table.
_computeForce() [1/3]
bool espressopp::interaction::PotentialTemplate< Tabulated >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const inline inherited
Definition at line 423 of file Potential.hpp.
_computeForce() [2/3]
bool espressopp::interaction::PotentialTemplate< Tabulated >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 431 of file Potential.hpp.
_computeForce() [3/3]
bool espressopp::interaction::PotentialTemplate< Tabulated >::_computeForce (Real3D & force, const Real3D & dist) const inline inherited
Definition at line 438 of file Potential.hpp.
_computeForceRaw()
bool espressopp::interaction::Tabulated::_computeForceRaw (Real3D & force, const Real3D & dist, real distSqr) const inline
Definition at line 101 of file Tabulated.hpp.
References interpolationType, and table.
computeColVarWeights()
void espressopp::interaction::PotentialTemplate< Tabulated >::computeColVarWeights (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 315 of file Potential.hpp.
computeEnergy() [1/3]
real espressopp::interaction::PotentialTemplate< Tabulated >::computeEnergy (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 323 of file Potential.hpp.
computeEnergy() [2/3]
real espressopp::interaction::PotentialTemplate< Tabulated >::computeEnergy (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 331 of file Potential.hpp.
computeEnergy() [3/3]
real espressopp::interaction::PotentialTemplate< Tabulated >::computeEnergy (real dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 338 of file Potential.hpp.
computeEnergySqr()
real espressopp::interaction::PotentialTemplate< Tabulated >::computeEnergySqr (real distsqr) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 345 of file Potential.hpp.
computeForce() [1/2]
Real3D espressopp::interaction::PotentialTemplate< Tabulated >::computeForce (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 405 of file Potential.hpp.
computeForce() [2/2]
Real3D espressopp::interaction::PotentialTemplate< Tabulated >::computeForce (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 413 of file Potential.hpp.
derived_this() [1/2]
Tabulated * espressopp::interaction::PotentialTemplate< Tabulated >::derived_this inline protected inherited
Definition at line 161 of file Potential.hpp.
derived_this() [2/2]
const Tabulated * espressopp::interaction::PotentialTemplate< Tabulated >::derived_this inline protected inherited
Definition at line 165 of file Potential.hpp.
getColVar() [1/2]
RealND espressopp::interaction::PotentialTemplate< Tabulated >::getColVar inline virtual inherited
Definition at line 309 of file Potential.hpp.
getColVar() [2/2]
virtual RealND espressopp::interaction::Potential::getColVar () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getColVarAngleList() [1/2]
shared_ptr< FixedTripleList > espressopp::interaction::PotentialTemplate< Tabulated >::getColVarAngleList inline virtual inherited
Definition at line 273 of file Potential.hpp.
getColVarAngleList() [2/2]
virtual shared_ptr<FixedTripleList> espressopp::interaction::Potential::getColVarAngleList () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getColVarBondList() [1/2]
shared_ptr< FixedPairList > espressopp::interaction::PotentialTemplate< Tabulated >::getColVarBondList inline virtual inherited
Definition at line 259 of file Potential.hpp.
getColVarBondList() [2/2]
virtual shared_ptr<FixedPairList> espressopp::interaction::Potential::getColVarBondList () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getColVarDihedList() [1/2]
shared_ptr< FixedQuadrupleList > espressopp::interaction::PotentialTemplate< Tabulated >::getColVarDihedList inline virtual inherited
Definition at line 287 of file Potential.hpp.
getColVarDihedList() [2/2]
virtual shared_ptr<FixedQuadrupleList> espressopp::interaction::Potential::getColVarDihedList () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getCutoff() [1/2]
real espressopp::interaction::PotentialTemplate< Tabulated >::getCutoff inline virtual inherited
Definition at line 210 of file Potential.hpp.
getCutoff() [2/2]
virtual real espressopp::interaction::Potential::getCutoff () const pure virtual inherited
Implemented in espressopp::interaction::CoulombKSpaceP3M, and espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getFilename()
const char* espressopp::interaction::Tabulated::getFilename () const inline
Getter for the filename.
Definition at line 87 of file Tabulated.hpp.
References filename.
Referenced by espressopp::interaction::Tabulated_pickle::getinitargs(), and registerPython().
getInterpolationType()
int espressopp::interaction::Tabulated::getInterpolationType () const inline
Getter for the interpolation type.
Definition at line 81 of file Tabulated.hpp.
References interpolationType.
Referenced by espressopp::interaction::Tabulated_pickle::getinitargs().
getShift() [1/2]
real espressopp::interaction::PotentialTemplate< Tabulated >::getShift inline virtual inherited
Definition at line 225 of file Potential.hpp.
getShift() [2/2]
virtual real espressopp::interaction::Potential::getShift () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
registerPython()
void espressopp::interaction::Tabulated::registerPython () static
Definition at line 85 of file Tabulated.cpp.
References getFilename(), and setFilename().
Referenced by espressopp::interaction::registerPython().
setAutoShift()
real espressopp::interaction::PotentialTemplate< Tabulated >::setAutoShift inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 231 of file Potential.hpp.
setColVar() [1/2]
void espressopp::interaction::PotentialTemplate< Tabulated >::setColVar (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 301 of file Potential.hpp.
setColVar() [2/2]
void espressopp::interaction::PotentialTemplate< Tabulated >::setColVar (const RealND & cv) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 294 of file Potential.hpp.
setColVarAngleList()
void espressopp::interaction::PotentialTemplate< Tabulated >::setColVarAngleList (const shared_ptr< FixedTripleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 266 of file Potential.hpp.
setColVarBondList()
void espressopp::interaction::PotentialTemplate< Tabulated >::setColVarBondList (const shared_ptr< FixedPairList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 252 of file Potential.hpp.
setColVarDihedList()
void espressopp::interaction::PotentialTemplate< Tabulated >::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 280 of file Potential.hpp.
setCutoff()
void espressopp::interaction::PotentialTemplate< Tabulated >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 201 of file Potential.hpp.
setFilename()
void espressopp::interaction::Tabulated::setFilename (int itype, const char * _filename)
Setter for the filename will read in the table.
Definition at line 49 of file Tabulated.cpp.
References filename, and table.
Referenced by registerPython(), and Tabulated().
setInterpolationType()
void espressopp::interaction::Tabulated::setInterpolationType (int itype) inline
Setter for the interpolation type.
Definition at line 78 of file Tabulated.hpp.
References interpolationType.
Referenced by Tabulated().
setShift()
void espressopp::interaction::PotentialTemplate< Tabulated >::setShift (real _shift) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 216 of file Potential.hpp.
updateAutoShift()
void espressopp::interaction::PotentialTemplate< Tabulated >::updateAutoShift inline inherited
Definition at line 244 of file Potential.hpp.
Member Data Documentation
autoShift
bool espressopp::interaction::PotentialTemplate< Tabulated >::autoShift protected inherited
Definition at line 151 of file Potential.hpp.
colVar
RealND espressopp::interaction::PotentialTemplate< Tabulated >::colVar protected inherited
Definition at line 159 of file Potential.hpp.
colVarAngleList
shared_ptr<FixedTripleList> espressopp::interaction::PotentialTemplate< Tabulated >::colVarAngleList protected inherited
Definition at line 155 of file Potential.hpp.
colVarBondList
shared_ptr<FixedPairList> espressopp::interaction::PotentialTemplate< Tabulated >::colVarBondList protected inherited
Definition at line 153 of file Potential.hpp.
colVarDihedList
shared_ptr<FixedQuadrupleList> espressopp::interaction::PotentialTemplate< Tabulated >::colVarDihedList protected inherited
Definition at line 157 of file Potential.hpp.
cutoff
real espressopp::interaction::PotentialTemplate< Tabulated >::cutoff protected inherited
Definition at line 148 of file Potential.hpp.
cutoffSqr
real espressopp::interaction::PotentialTemplate< Tabulated >::cutoffSqr protected inherited
Definition at line 149 of file Potential.hpp.
filename
std::string espressopp::interaction::Tabulated::filename private
Definition at line 46 of file Tabulated.hpp.
Referenced by getFilename(), setFilename(), and Tabulated().
interpolationType
int espressopp::interaction::Tabulated::interpolationType private
Definition at line 48 of file Tabulated.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), getInterpolationType(), setInterpolationType(), and Tabulated().
shift
real espressopp::interaction::PotentialTemplate< Tabulated >::shift protected inherited
Definition at line 150 of file Potential.hpp.
table
shared_ptr<Interpolation> espressopp::interaction::Tabulated::table private
Definition at line 47 of file Tabulated.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), and setFilename().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/Tabulated.hpp
/home/espressopp/espressopp/src/interaction/Tabulated.cpp