ESPResSo++: espressopp::esutil::Array4D< T, outlier_mode > Class Template Reference
espressopp::esutil::Array4D< T, outlier_mode > Class Template Reference
A four-dimensional array (i.e.
#include <Array4D.hpp>
Public Types
typedef T value_type
The type of object, T, stored in the Array1D.
typedef T & reference
Reference to to a T object.
typedef Super::size_type size_type
An unsigned integer type.
typedef Super::iterator iterator
Iterator used to iterate through an Array1D.
typedef Super::const_iterator const_iterator
Const-iterator used to iterate through an Array1D.
Public Member Functions
Array4D ()
Default constructor.
Array4D (size_type n, size_type m, size_type l, size_type k, const T &t=T())
Creates a 4-dimensional n x m x l x k array, initialising the values with copies of t.
void clear ()
Erases all elements.
void init (size_type n, size_type m, size_type l, size_type k, const T &t=T())
Creates a 3-dimensional n x m x p x q array, initialising the values with copies of t.
void resize (size_type n, size_type m, size_type l, size_type k, const T &t=T())
Changes the size of the Array4D so that the size becomes n x m x p x q array.
size_type size_n () const
Returns the n -size of the array.
size_type size_m () const
Returns the m -size of the array.
size_type size_p () const
Returns the p -size of the array.
size_type size_q () const
Returns the q -size of the array.
bool empty () const
true if the Array4D's size is 0 x 0 x 0 x 0.
reference operator() (size_type i, size_type j, size_type k, size_type l)
Returns the element at position i x j x k.
const_reference operator() (size_type i, size_type j, size_type k, size_type l) const
Returns the element at position i x j x k.
template<class Vector >
reference operator() (const Vector &pos)
Returns the element at position pos.
template<class Vector >
const_reference operator() (const Vector &pos) const
Returns the element at position pos.
reference at (size_type i, size_type j, size_type k, size_type l)
Returns the element at position i x j x k.
const_reference at (size_type i, size_type j, size_type k, size_type l) const
Returns the element at position i x j x k.
template<class Vector >
reference at (const Vector &pos)
Returns the element at position pos.
template<class Vector >
const_reference at (const Vector &pos) const
Returns the element at position pos.
iterator begin ()
Returns an iterator pointing to the beginning of the Array4D.
const_iterator begin () const
Returns a const_iterator pointing to the beginning of the Array4D.
iterator end ()
Returns an iterator pointing to the end of the Array4D.
const_iterator end () const
Returns a const_iterator pointing to the end of the Array4D.
template<class T2 >
void operator= (const T2 &t2)
Assigns t2 to each of the elements.
template<class T2 >
void operator+= (const T2 &t2)
Adds t2 to each of the elements.
template<class T2 >
void operator-= (const T2 &t2)
Adds t2 to each of the elements.
template<class T2 >
void operator*= (const T2 &t2)
Multiplies each of the elements by t2.
template<class T2 >
void operator/= (const T2 &t2)
Divides each of the elements by t2.
void operator/= (const double &x)
bool operator== (const Array4D< T, exception > &a)
Equality operator.
bool operator!= (const Array4D< T, exception > &a)
Inequality operator.
Public Attributes
const typedef T & const_reference
Const reference to to a T object.
Private Types
typedef Array4D< T > Self
typedef std::vector< T > Super
The super class of the array (i.e.
Private Attributes
size_type n
The n size of the n x m x p x q array.
size_type m
The m size of the n x m x p x q array.
size_type p
The p size of the n x m x p x q array.
size_type q
The p size of the n x m x p x q array.
Detailed Description
template<class T, OutlierMode outlier_mode = exception>
class espressopp::esutil::Array4D< T, outlier_mode >
A four-dimensional array (i.e.
a matrix). Particulary we need it for 4-body potential tables
Parameters
T The type of the object stored in the array.
Example:
// create the 10x10 id matrix
Array4D< double > I(10, 10, ,10, 10.0, 0.0);
for (int i = 0; i < 10; i++) I(i, i, i, i) = 1.0;
Definition at line 42 of file Array4D.hpp.
Member Typedef Documentation
const_iterator
template<class T , OutlierMode outlier_mode = exception> typedef Super::const_iterator espressopp::esutil::Array4D< T, outlier_mode >::const_iterator
Const-iterator used to iterate through an Array1D.
Definition at line 59 of file Array4D.hpp.
iterator
template<class T , OutlierMode outlier_mode = exception> typedef Super::iterator espressopp::esutil::Array4D< T, outlier_mode >::iterator
Iterator used to iterate through an Array1D.
Definition at line 57 of file Array4D.hpp.
reference
template<class T , OutlierMode outlier_mode = exception> typedef T& espressopp::esutil::Array4D< T, outlier_mode >::reference
Reference to to a T object.
Definition at line 51 of file Array4D.hpp.
Self
template<class T , OutlierMode outlier_mode = exception> typedef Array4D<T> espressopp::esutil::Array4D< T, outlier_mode >::Self private
Definition at line 43 of file Array4D.hpp.
size_type
template<class T , OutlierMode outlier_mode = exception> typedef Super::size_type espressopp::esutil::Array4D< T, outlier_mode >::size_type
An unsigned integer type.
Definition at line 55 of file Array4D.hpp.
Super
template<class T , OutlierMode outlier_mode = exception> typedef std::vector<T> espressopp::esutil::Array4D< T, outlier_mode >::Super private
The super class of the array (i.e.
vector<T>).
Definition at line 45 of file Array4D.hpp.
value_type
template<class T , OutlierMode outlier_mode = exception> typedef T espressopp::esutil::Array4D< T, outlier_mode >::value_type
The type of object, T, stored in the Array1D.
Definition at line 49 of file Array4D.hpp.
Constructor & Destructor Documentation
Array4D() [1/2]
template<class T , OutlierMode outlier_mode = exception> espressopp::esutil::Array4D< T, outlier_mode >::Array4D () inline
Default constructor.
Definition at line 62 of file Array4D.hpp.
Array4D() [2/2]
template<class T , OutlierMode outlier_mode = exception> espressopp::esutil::Array4D< T, outlier_mode >::Array4D (size_type n, size_type m, size_type l, size_type k, const T & t = T()) inline
Creates a 4-dimensional n x m x l x k array, initialising the values with copies of t.
Definition at line 66 of file Array4D.hpp.
Member Function Documentation
at() [1/4]
template<class T , OutlierMode outlier_mode = exception> template<class Vector > reference espressopp::esutil::Array4D< T, outlier_mode >::at (const Vector & pos) inline
Returns the element at position pos.
pos must be a vector where the expressions pos[0], pos[1] and pos[2] return the first and second element.
Exceptions
out_of_range i is out of range of the Array4D
Definition at line 178 of file Array4D.hpp.
Referenced by espressopp::esutil::Array4D< Potential, esutil::enlarge >::at().
at() [2/4]
template<class T , OutlierMode outlier_mode = exception> template<class Vector > const_reference espressopp::esutil::Array4D< T, outlier_mode >::at (const Vector & pos) const inline
Returns the element at position pos.
pos must be a vector where the expressions pos[0], pos[1] and pos[2] return the first and second element.
Exceptions
out_of_range i is out of range of the Array4D
Definition at line 187 of file Array4D.hpp.
Referenced by espressopp::esutil::Array4D< Potential, esutil::enlarge >::at().
at() [3/4]
template<class T , OutlierMode outlier_mode = exception> reference espressopp::esutil::Array4D< T, outlier_mode >::at (size_type i, size_type j, size_type k, size_type l) inline
Returns the element at position i x j x k.
Exceptions
out_of_range i is out of range of the Array4D
Definition at line 153 of file Array4D.hpp.
Referenced by espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::getPotential(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::getPotentialPtr(), and espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::setPotential().
at() [4/4]
template<class T , OutlierMode outlier_mode = exception> const_reference espressopp::esutil::Array4D< T, outlier_mode >::at (size_type i, size_type j, size_type k, size_type l) const inline
Returns the element at position i x j x k.
Exceptions
out_of_range i is out of range of the Array4D
Definition at line 163 of file Array4D.hpp.
begin() [1/2]
template<class T , OutlierMode outlier_mode = exception> iterator espressopp::esutil::Array4D< T, outlier_mode >::begin () inline
Returns an iterator pointing to the beginning of the Array4D.
Definition at line 191 of file Array4D.hpp.
Referenced by espressopp::esutil::Array4D< Potential, esutil::enlarge >::operator*=(), espressopp::esutil::Array4D< Potential, esutil::enlarge >::operator+=(), espressopp::esutil::Array4D< Potential, esutil::enlarge >::operator-=(), espressopp::esutil::Array4D< Potential, esutil::enlarge >::operator/=(), and espressopp::esutil::Array4D< Potential, esutil::enlarge >::operator=().
begin() [2/2]
template<class T , OutlierMode outlier_mode = exception> const_iterator espressopp::esutil::Array4D< T, outlier_mode >::begin () const inline
Returns a const_iterator pointing to the beginning of the Array4D.
Definition at line 195 of file Array4D.hpp.
clear()
template<class T , OutlierMode outlier_mode = exception> void espressopp::esutil::Array4D< T, outlier_mode >::clear () inline
Erases all elements.
Definition at line 71 of file Array4D.hpp.
Referenced by espressopp::esutil::Array4D< Potential, esutil::enlarge >::Array4D().
empty()
template<class T , OutlierMode outlier_mode = exception> bool espressopp::esutil::Array4D< T, outlier_mode >::empty () const inline
true if the Array4D's size is 0 x 0 x 0 x 0.
Definition at line 117 of file Array4D.hpp.
end() [1/2]
template<class T , OutlierMode outlier_mode = exception> iterator espressopp::esutil::Array4D< T, outlier_mode >::end () inline
Returns an iterator pointing to the end of the Array4D.
Definition at line 199 of file Array4D.hpp.
Referenced by espressopp::esutil::Array4D< Potential, esutil::enlarge >::operator*=(), espressopp::esutil::Array4D< Potential, esutil::enlarge >::operator+=(), espressopp::esutil::Array4D< Potential, esutil::enlarge >::operator-=(), espressopp::esutil::Array4D< Potential, esutil::enlarge >::operator/=(), and espressopp::esutil::Array4D< Potential, esutil::enlarge >::operator=().
end() [2/2]
template<class T , OutlierMode outlier_mode = exception> const_iterator espressopp::esutil::Array4D< T, outlier_mode >::end () const inline
Returns a const_iterator pointing to the end of the Array4D.
Definition at line 203 of file Array4D.hpp.
init()
template<class T , OutlierMode outlier_mode = exception> void espressopp::esutil::Array4D< T, outlier_mode >::init (size_type n, size_type m, size_type l, size_type k, const T & t = T()) inline
Creates a 3-dimensional n x m x p x q array, initialising the values with copies of t.
Definition at line 81 of file Array4D.hpp.
Referenced by espressopp::esutil::Array4D< Potential, esutil::enlarge >::Array4D(), and espressopp::esutil::Array4D< T, enlarge >::Array4D().
operator!=()
template<class T , OutlierMode outlier_mode = exception> bool espressopp::esutil::Array4D< T, outlier_mode >::operator!= (const Array4D< T, exception > & a) inline
Inequality operator.
Definition at line 243 of file Array4D.hpp.
operator()() [1/4]
template<class T , OutlierMode outlier_mode = exception> template<class Vector > reference espressopp::esutil::Array4D< T, outlier_mode >::operator() (const Vector & pos) inline
Returns the element at position pos.
pos must be a vector where the expressions pos[0], pos[1] and pos[2] return the indices.
Attention
No range checking.
Definition at line 137 of file Array4D.hpp.
operator()() [2/4]
template<class T , OutlierMode outlier_mode = exception> template<class Vector > const_reference espressopp::esutil::Array4D< T, outlier_mode >::operator() (const Vector & pos) const inline
Returns the element at position pos.
pos must be a vector where the expressions pos[0], pos[1] and pos[2] return the indices.
Attention
No range checking.
Definition at line 147 of file Array4D.hpp.
operator()() [3/4]
template<class T , OutlierMode outlier_mode = exception> reference espressopp::esutil::Array4D< T, outlier_mode >::operator() (size_type i, size_type j, size_type k, size_type l) inline
Returns the element at position i x j x k.
Attention
No range checking.
Definition at line 121 of file Array4D.hpp.
Referenced by espressopp::esutil::Array4D< Potential, esutil::enlarge >::at(), and espressopp::esutil::Array4D< Potential, esutil::enlarge >::operator()().
operator()() [4/4]
template<class T , OutlierMode outlier_mode = exception> const_reference espressopp::esutil::Array4D< T, outlier_mode >::operator() (size_type i, size_type j, size_type k, size_type l) const inline
Returns the element at position i x j x k.
Attention
No range checking.
Definition at line 127 of file Array4D.hpp.
operator*=()
template<class T , OutlierMode outlier_mode = exception> template<class T2 > void espressopp::esutil::Array4D< T, outlier_mode >::operator*= (const T2 & t2) inline
Multiplies each of the elements by t2.
Definition at line 225 of file Array4D.hpp.
operator+=()
template<class T , OutlierMode outlier_mode = exception> template<class T2 > void espressopp::esutil::Array4D< T, outlier_mode >::operator+= (const T2 & t2) inline
Adds t2 to each of the elements.
Definition at line 213 of file Array4D.hpp.
operator-=()
template<class T , OutlierMode outlier_mode = exception> template<class T2 > void espressopp::esutil::Array4D< T, outlier_mode >::operator-= (const T2 & t2) inline
Adds t2 to each of the elements.
Definition at line 219 of file Array4D.hpp.
operator/=() [1/2]
template<class T , OutlierMode outlier_mode = exception> void espressopp::esutil::Array4D< T, outlier_mode >::operator/= (const double & x) inline
Definition at line 231 of file Array4D.hpp.
operator/=() [2/2]
template<class T , OutlierMode outlier_mode = exception> template<class T2 > void espressopp::esutil::Array4D< T, outlier_mode >::operator/= (const T2 & t2) inline
Divides each of the elements by t2.
Definition at line 229 of file Array4D.hpp.
operator=()
template<class T , OutlierMode outlier_mode = exception> template<class T2 > void espressopp::esutil::Array4D< T, outlier_mode >::operator= (const T2 & t2) inline
Assigns t2 to each of the elements.
Definition at line 207 of file Array4D.hpp.
operator==()
template<class T , OutlierMode outlier_mode = exception> bool espressopp::esutil::Array4D< T, outlier_mode >::operator== (const Array4D< T, exception > & a) inline
Equality operator.
Definition at line 237 of file Array4D.hpp.
resize()
template<class T , OutlierMode outlier_mode = exception> void espressopp::esutil::Array4D< T, outlier_mode >::resize (size_type n, size_type m, size_type l, size_type k, const T & t = T()) inline
Changes the size of the Array4D so that the size becomes n x m x p x q array.
Attention
The elements of the Array4D are not initialised consistently, so the values are undefined. The t parameter exists only for the purpose to provide a default T value when new elements are created and needs to be specified only when T has no default constructor.
Definition at line 96 of file Array4D.hpp.
Referenced by espressopp::esutil::Array4D< Potential, esutil::enlarge >::init().
size_m()
template<class T , OutlierMode outlier_mode = exception> size_type espressopp::esutil::Array4D< T, outlier_mode >::size_m () const inline
Returns the m -size of the array.
Definition at line 108 of file Array4D.hpp.
Referenced by espressopp::esutil::Array4D< T, enlarge >::at().
size_n()
template<class T , OutlierMode outlier_mode = exception> size_type espressopp::esutil::Array4D< T, outlier_mode >::size_n () const inline
Returns the n -size of the array.
Definition at line 105 of file Array4D.hpp.
Referenced by espressopp::esutil::Array4D< T, enlarge >::at().
size_p()
template<class T , OutlierMode outlier_mode = exception> size_type espressopp::esutil::Array4D< T, outlier_mode >::size_p () const inline
Returns the p -size of the array.
Definition at line 111 of file Array4D.hpp.
Referenced by espressopp::esutil::Array4D< T, enlarge >::at().
size_q()
template<class T , OutlierMode outlier_mode = exception> size_type espressopp::esutil::Array4D< T, outlier_mode >::size_q () const inline
Returns the q -size of the array.
Definition at line 114 of file Array4D.hpp.
Referenced by espressopp::esutil::Array4D< T, enlarge >::at().
Member Data Documentation
const_reference
template<class T , OutlierMode outlier_mode = exception> const typedef T& espressopp::esutil::Array4D< T, outlier_mode >::const_reference
Const reference to to a T object.
Definition at line 53 of file Array4D.hpp.
m
template<class T , OutlierMode outlier_mode = exception> size_type espressopp::esutil::Array4D< T, outlier_mode >::m private
The m size of the n x m x p x q array.
Definition at line 252 of file Array4D.hpp.
Referenced by espressopp::esutil::Array4D< Potential, esutil::enlarge >::Array4D(), espressopp::esutil::Array4D< T, enlarge >::Array4D(), espressopp::esutil::Array4D< Potential, esutil::enlarge >::at(), espressopp::esutil::Array4D< Potential, esutil::enlarge >::empty(), espressopp::esutil::Array4D< Potential, esutil::enlarge >::init(), espressopp::esutil::Array4D< T, enlarge >::init(), espressopp::esutil::Array4D< Potential, esutil::enlarge >::operator()(), espressopp::esutil::Array4D< Potential, esutil::enlarge >::resize(), and espressopp::esutil::Array4D< Potential, esutil::enlarge >::size_m().
n
template<class T , OutlierMode outlier_mode = exception> size_type espressopp::esutil::Array4D< T, outlier_mode >::n private
The n size of the n x m x p x q array.
Definition at line 250 of file Array4D.hpp.
Referenced by espressopp::esutil::Array4D< Potential, esutil::enlarge >::Array4D(), espressopp::esutil::Array4D< T, enlarge >::Array4D(), espressopp::esutil::Array4D< Potential, esutil::enlarge >::at(), espressopp::esutil::Array4D< Potential, esutil::enlarge >::empty(), espressopp::esutil::Array4D< Potential, esutil::enlarge >::init(), espressopp::esutil::Array4D< T, enlarge >::init(), espressopp::esutil::Array4D< Potential, esutil::enlarge >::operator()(), espressopp::esutil::Array4D< Potential, esutil::enlarge >::resize(), and espressopp::esutil::Array4D< Potential, esutil::enlarge >::size_n().
p
template<class T , OutlierMode outlier_mode = exception> size_type espressopp::esutil::Array4D< T, outlier_mode >::p private
The p size of the n x m x p x q array.
Definition at line 254 of file Array4D.hpp.
Referenced by espressopp::esutil::Array4D< T, enlarge >::Array4D(), espressopp::esutil::Array4D< Potential, esutil::enlarge >::at(), espressopp::esutil::Array4D< Potential, esutil::enlarge >::clear(), espressopp::esutil::Array4D< Potential, esutil::enlarge >::empty(), espressopp::esutil::Array4D< T, enlarge >::init(), espressopp::esutil::Array4D< Potential, esutil::enlarge >::operator()(), espressopp::esutil::Array4D< Potential, esutil::enlarge >::resize(), and espressopp::esutil::Array4D< Potential, esutil::enlarge >::size_p().
q
template<class T , OutlierMode outlier_mode = exception> size_type espressopp::esutil::Array4D< T, outlier_mode >::q private
The p size of the n x m x p x q array.
Definition at line 256 of file Array4D.hpp.
Referenced by espressopp::esutil::Array4D< T, enlarge >::Array4D(), espressopp::esutil::Array4D< Potential, esutil::enlarge >::at(), espressopp::esutil::Array4D< Potential, esutil::enlarge >::clear(), espressopp::esutil::Array4D< Potential, esutil::enlarge >::empty(), espressopp::esutil::Array4D< T, enlarge >::init(), espressopp::esutil::Array4D< Potential, esutil::enlarge >::resize(), and espressopp::esutil::Array4D< Potential, esutil::enlarge >::size_q().
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/esutil/Array4D.hpp