ESPResSo++: espressopp::interaction::DihedralHarmonicCos Class Reference
espressopp::interaction::DihedralHarmonicCos Class Reference
This class provides methods to compute forces and energies of the DihedralHarmonicCos dihedral potential.
#include <DihedralHarmonicCos.hpp>
Public Member Functions
DihedralHarmonicCos ()
DihedralHarmonicCos (real _K, real _phi0)
void setK (real _K)
real getK () const
void setPhi0 (real _phi0)
real getPhi0 () const
real d (int i, int j) const
Real3D prod (Real3D a, Real3D b) const
real _computeEnergyRaw (real _phi) const
void _computeForceRaw (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &r21, const Real3D &r32, const Real3D &r43) const
real _computeForceRaw (real phi) const
virtual real computeEnergy (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
virtual real computeEnergy (real phi) const
virtual void computeForce (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
virtual real computeForce (real phi) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)
virtual shared_ptr< FixedPairList > getColVarBondList () const
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &ftl)
virtual shared_ptr< FixedTripleList > getColVarAngleList () const
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fql)
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const
virtual void setColVar (const RealND &cv)
virtual void setColVar (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43, const bc::BC &bc)
virtual RealND getColVar () const
virtual void computeColVarWeights (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43, const bc::BC &bc)
real _computeEnergy (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
real _computeEnergy (real phi) const
void _computeForce (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
Static Public Member Functions
static void registerPython ()
static real computePhi (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43)
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
DihedralHarmonicCos * derived_this ()
const DihedralHarmonicCos * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
shared_ptr< FixedPairList > colVarBondList
shared_ptr< FixedTripleList > colVarAngleList
shared_ptr< FixedQuadrupleList > colVarDihedList
RealND colVar
Private Attributes
real K
real phi0
real cos_phi0
Detailed Description
This class provides methods to compute forces and energies of the DihedralHarmonicCos dihedral potential.
Definition at line 35 of file DihedralHarmonicCos.hpp.
Constructor & Destructor Documentation
DihedralHarmonicCos() [1/2]
espressopp::interaction::DihedralHarmonicCos::DihedralHarmonicCos () inline
Definition at line 44 of file DihedralHarmonicCos.hpp.
DihedralHarmonicCos() [2/2]
espressopp::interaction::DihedralHarmonicCos::DihedralHarmonicCos (real _K, real _phi0) inline
Definition at line 45 of file DihedralHarmonicCos.hpp.
Member Function Documentation
_computeEnergy() [1/2]
real espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >::_computeEnergy (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline inherited
Definition at line 285 of file DihedralPotential.hpp.
_computeEnergy() [2/2]
real espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >::_computeEnergy (real phi) const inline inherited
Definition at line 295 of file DihedralPotential.hpp.
_computeEnergyRaw()
real espressopp::interaction::DihedralHarmonicCos::_computeEnergyRaw (real _phi) const inline
Definition at line 80 of file DihedralHarmonicCos.hpp.
_computeForce()
void espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >::_computeForce (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline inherited
Definition at line 317 of file DihedralPotential.hpp.
_computeForceRaw() [1/2]
void espressopp::interaction::DihedralHarmonicCos::_computeForceRaw (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & r21, const Real3D & r32, const Real3D & r43) const inline
Definition at line 86 of file DihedralHarmonicCos.hpp.
References cos_phi0, espressopp::Real3D::cross(), d(), prod(), and espressopp::Real3D::sqr().
_computeForceRaw() [2/2]
real espressopp::interaction::DihedralHarmonicCos::_computeForceRaw (real phi) const inline
Definition at line 153 of file DihedralHarmonicCos.hpp.
References cos_phi0.
computeColVarWeights()
void espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >::computeColVarWeights (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 256 of file DihedralPotential.hpp.
computeEnergy() [1/2]
real espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >::computeEnergy (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 265 of file DihedralPotential.hpp.
computeEnergy() [2/2]
real espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >::computeEnergy (real phi) const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 278 of file DihedralPotential.hpp.
computeForce() [1/2]
void espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >::computeForce (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 303 of file DihedralPotential.hpp.
computeForce() [2/2]
real espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >::computeForce (real phi) const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 331 of file DihedralPotential.hpp.
computePhi()
real espressopp::interaction::DihedralPotential::computePhi (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) static inherited
Definition at line 31 of file DihedralPotential.cpp.
References espressopp::Real3D::abs(), espressopp::Real3D::cross(), and espressopp::interaction::LOG4ESPP_LOGGER().
Referenced by espressopp::interaction::DihedralPotential::registerPython(), espressopp::interaction::TabulatedSubEnsDihedral::setColVar(), espressopp::interaction::TabulatedSubEnsAngular::setColVar(), and espressopp::interaction::TabulatedSubEns::setColVar().
d()
real espressopp::interaction::DihedralHarmonicCos::d (int i, int j) const inline
Definition at line 63 of file DihedralHarmonicCos.hpp.
Referenced by _computeForceRaw(), and prod().
derived_this() [1/2]
DihedralHarmonicCos * espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >::derived_this () inline protected inherited
Definition at line 154 of file DihedralPotential.hpp.
derived_this() [2/2]
const DihedralHarmonicCos * espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >::derived_this () const inline protected inherited
Definition at line 158 of file DihedralPotential.hpp.
getColVar()
RealND espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >::getColVar () const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 250 of file DihedralPotential.hpp.
getColVarAngleList()
shared_ptr< FixedTripleList > espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >::getColVarAngleList () const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 213 of file DihedralPotential.hpp.
getColVarBondList()
shared_ptr< FixedPairList > espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >::getColVarBondList () const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 199 of file DihedralPotential.hpp.
getColVarDihedList()
shared_ptr< FixedQuadrupleList > espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >::getColVarDihedList () const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 227 of file DihedralPotential.hpp.
getCutoff()
real espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 185 of file DihedralPotential.hpp.
getK()
real espressopp::interaction::DihedralHarmonicCos::getK () const inline
Definition at line 52 of file DihedralHarmonicCos.hpp.
References K.
Referenced by registerPython().
getPhi0()
real espressopp::interaction::DihedralHarmonicCos::getPhi0 () const inline
Definition at line 60 of file DihedralHarmonicCos.hpp.
References phi0.
Referenced by registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::DihedralPotential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
prod()
Real3D espressopp::interaction::DihedralHarmonicCos::prod (Real3D a, Real3D b) const inline
Definition at line 70 of file DihedralHarmonicCos.hpp.
References d().
Referenced by _computeForceRaw().
registerPython()
void espressopp::interaction::DihedralHarmonicCos::registerPython () static
Definition at line 33 of file DihedralHarmonicCos.cpp.
References getK(), getPhi0(), setK(), and setPhi0().
Referenced by espressopp::interaction::registerPython().
setColVar() [1/2]
void espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >::setColVar (const RealND & cv) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 234 of file DihedralPotential.hpp.
setColVar() [2/2]
void espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >::setColVar (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 241 of file DihedralPotential.hpp.
setColVarAngleList()
void espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >::setColVarAngleList (const shared_ptr< FixedTripleList > & ftl) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 206 of file DihedralPotential.hpp.
setColVarBondList()
void espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >::setColVarBondList (const shared_ptr< FixedPairList > & fpl) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 192 of file DihedralPotential.hpp.
setColVarDihedList()
void espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fql) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 220 of file DihedralPotential.hpp.
setCutoff()
void espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 177 of file DihedralPotential.hpp.
setK()
void espressopp::interaction::DihedralHarmonicCos::setK (real _K) inline
Definition at line 51 of file DihedralHarmonicCos.hpp.
Referenced by registerPython().
setPhi0()
void espressopp::interaction::DihedralHarmonicCos::setPhi0 (real _phi0) inline
Definition at line 54 of file DihedralHarmonicCos.hpp.
Referenced by registerPython().
Member Data Documentation
colVar
RealND espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >::colVar protected inherited
Definition at line 152 of file DihedralPotential.hpp.
colVarAngleList
shared_ptr<FixedTripleList> espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >::colVarAngleList protected inherited
Definition at line 148 of file DihedralPotential.hpp.
colVarBondList
shared_ptr<FixedPairList> espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >::colVarBondList protected inherited
Definition at line 146 of file DihedralPotential.hpp.
colVarDihedList
shared_ptr<FixedQuadrupleList> espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >::colVarDihedList protected inherited
Definition at line 150 of file DihedralPotential.hpp.
cos_phi0
real espressopp::interaction::DihedralHarmonicCos::cos_phi0 private
Definition at line 40 of file DihedralHarmonicCos.hpp.
Referenced by _computeForceRaw().
cutoff
real espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >::cutoff protected inherited
Definition at line 143 of file DihedralPotential.hpp.
cutoffSqr
real espressopp::interaction::DihedralPotentialTemplate< DihedralHarmonicCos >::cutoffSqr protected inherited
Definition at line 144 of file DihedralPotential.hpp.
K
real espressopp::interaction::DihedralHarmonicCos::K private
Definition at line 37 of file DihedralHarmonicCos.hpp.
Referenced by getK().
phi0
real espressopp::interaction::DihedralHarmonicCos::phi0 private
Definition at line 38 of file DihedralHarmonicCos.hpp.
Referenced by getPhi0().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/DihedralHarmonicCos.hpp
/home/espressopp/espressopp/src/interaction/DihedralHarmonicCos.cpp