ESPResSo++: espressopp::interaction::CoulombTruncatedUniqueCharge Class Reference
espressopp::interaction::CoulombTruncatedUniqueCharge Class Reference
#include <CoulombTruncatedUniqueCharge.hpp>
Public Member Functions
CoulombTruncatedUniqueCharge ()
CoulombTruncatedUniqueCharge (real _qq, real _cutoff, real _shift)
CoulombTruncatedUniqueCharge (real _qq, real _cutoff)
void setQQ (real _qq)
real getQQ () const
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &dist, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
real _computeEnergyDeriv (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
CoulombTruncatedUniqueCharge * derived_this ()
const CoulombTruncatedUniqueCharge * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
Private Attributes
real qq
Detailed Description
Definition at line 35 of file CoulombTruncatedUniqueCharge.hpp.
Constructor & Destructor Documentation
CoulombTruncatedUniqueCharge() [1/3]
espressopp::interaction::CoulombTruncatedUniqueCharge::CoulombTruncatedUniqueCharge () inline
Definition at line 42 of file CoulombTruncatedUniqueCharge.hpp.
References espressopp::infinity, espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::setCutoff(), and espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::setShift().
CoulombTruncatedUniqueCharge() [2/3]
espressopp::interaction::CoulombTruncatedUniqueCharge::CoulombTruncatedUniqueCharge (real _qq, real _cutoff, real _shift) inline
Definition at line 48 of file CoulombTruncatedUniqueCharge.hpp.
References espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::setCutoff(), and espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::setShift().
CoulombTruncatedUniqueCharge() [3/3]
espressopp::interaction::CoulombTruncatedUniqueCharge::CoulombTruncatedUniqueCharge (real _qq, real _cutoff) inline
Definition at line 55 of file CoulombTruncatedUniqueCharge.hpp.
References espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::autoShift, espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::setAutoShift(), and espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::setCutoff().
Member Function Documentation
_computeEnergy() [1/4]
real espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::_computeEnergy (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 242 of file Potential.hpp.
_computeEnergy() [2/4]
real espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::_computeEnergy (const Real3D & dist) const inline inherited
Definition at line 257 of file Potential.hpp.
_computeEnergy() [3/4]
real espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::_computeEnergy (real dist) const inline inherited
Definition at line 264 of file Potential.hpp.
_computeEnergy() [4/4]
real espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 250 of file Potential.hpp.
_computeEnergyDeriv()
real espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::_computeEnergyDeriv (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 285 of file Potential.hpp.
_computeEnergySqr()
real espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::_computeEnergySqr (real distSqr) const inline inherited
Definition at line 271 of file Potential.hpp.
_computeEnergySqrRaw()
real espressopp::interaction::CoulombTruncatedUniqueCharge::_computeEnergySqrRaw (real distSqr) const inline
Definition at line 71 of file CoulombTruncatedUniqueCharge.hpp.
_computeForce() [1/3]
bool espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const inline inherited
Definition at line 313 of file Potential.hpp.
_computeForce() [2/3]
bool espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::_computeForce (Real3D & force, const Real3D & dist) const inline inherited
Definition at line 328 of file Potential.hpp.
_computeForce() [3/3]
bool espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 321 of file Potential.hpp.
_computeForceRaw()
bool espressopp::interaction::CoulombTruncatedUniqueCharge::_computeForceRaw (Real3D & force, const Real3D & dist, real distSqr) const inline
Definition at line 76 of file CoulombTruncatedUniqueCharge.hpp.
computeEnergy() [1/3]
real espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::computeEnergy (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 213 of file Potential.hpp.
computeEnergy() [2/3]
real espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::computeEnergy (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 221 of file Potential.hpp.
computeEnergy() [3/3]
real espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::computeEnergy (real dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 228 of file Potential.hpp.
computeEnergySqr()
real espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::computeEnergySqr (real distsqr) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 235 of file Potential.hpp.
computeForce() [1/2]
Real3D espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::computeForce (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 295 of file Potential.hpp.
computeForce() [2/2]
Real3D espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::computeForce (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 303 of file Potential.hpp.
derived_this() [1/2]
CoulombTruncatedUniqueCharge * espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::derived_this () inline protected inherited
Definition at line 123 of file Potential.hpp.
derived_this() [2/2]
const CoulombTruncatedUniqueCharge * espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::derived_this () const inline protected inherited
Definition at line 127 of file Potential.hpp.
getCutoff()
real espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 171 of file Potential.hpp.
getQQ()
real espressopp::interaction::CoulombTruncatedUniqueCharge::getQQ () const inline
Definition at line 69 of file CoulombTruncatedUniqueCharge.hpp.
References qq.
Referenced by espressopp::interaction::CoulombTruncatedUniqueCharge_pickle::getinitargs(), and registerPython().
getShift()
real espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::getShift () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 186 of file Potential.hpp.
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
Referenced by espressopp::interaction::Potential::~Potential().
registerPython()
void espressopp::interaction::CoulombTruncatedUniqueCharge::registerPython () static
Definition at line 42 of file CoulombTruncatedUniqueCharge.cpp.
References getQQ(), and setQQ().
Referenced by espressopp::interaction::registerPython().
setAutoShift()
real espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::setAutoShift () inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 192 of file Potential.hpp.
Referenced by CoulombTruncatedUniqueCharge().
setCutoff()
void espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 162 of file Potential.hpp.
Referenced by CoulombTruncatedUniqueCharge().
setQQ()
void espressopp::interaction::CoulombTruncatedUniqueCharge::setQQ (real _qq) inline
Definition at line 65 of file CoulombTruncatedUniqueCharge.hpp.
References espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::updateAutoShift().
Referenced by registerPython().
setShift()
void espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::setShift (real _shift) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 177 of file Potential.hpp.
Referenced by CoulombTruncatedUniqueCharge().
updateAutoShift()
void espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::updateAutoShift () inline inherited
Definition at line 205 of file Potential.hpp.
Referenced by setQQ().
Member Data Documentation
autoShift
bool espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::autoShift protected inherited
Definition at line 121 of file Potential.hpp.
Referenced by CoulombTruncatedUniqueCharge().
cutoff
real espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::cutoff protected inherited
Definition at line 118 of file Potential.hpp.
cutoffSqr
real espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::cutoffSqr protected inherited
Definition at line 119 of file Potential.hpp.
qq
real espressopp::interaction::CoulombTruncatedUniqueCharge::qq private
Definition at line 37 of file CoulombTruncatedUniqueCharge.hpp.
Referenced by getQQ().
shift
real espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >::shift protected inherited
Definition at line 120 of file Potential.hpp.
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/CoulombTruncatedUniqueCharge.hpp
/home/espressopp/espressopp/src/interaction/CoulombTruncatedUniqueCharge.cpp