ESPResSo++: espressopp::interaction::TabulatedSubEnsAngular Class Reference
espressopp::interaction::TabulatedSubEnsAngular Class Reference
#include <TabulatedSubEnsAngular.hpp>
Public Member Functions
TabulatedSubEnsAngular ()
void addInteraction (int itype, boost::python::str fname, const RealND &_cvref)
void setDimension (int _dim)
int getDimension () const
void setInterpolationType (int itype)
Setter for the interpolation type.
int getInterpolationType () const
Getter for the interpolation type.
RealND getTargetProb () const
void setTargetProb (int index, real _r)
RealND getColVarSds () const
void setColVarSd (int index, real _r)
RealND getColVarRef (int i) const
RealNDs getColVarRefs () const
void setColVarRef (const RealNDs &cvRefs)
void setColVarRefs (const RealNDs &c)
boost::python::list getFilenames () const
boost::python::list getFilename (int index) const
void setFilename (int index, boost::python::list _f)
void setFilenames (int dim, int itype, boost::python::list _filenames)
RealND getWeights () const
void setWeights (const RealND &r)
real getWeight (int index) const
void setWeight (int index, real _w)
real getAlpha () const
void setAlpha (real _r)
void computeColVarWeights (const Real3D &dist12, const Real3D &dist32, const bc::BC &bc)
void setColVar (const Real3D &dist12, const Real3D &dist32, const bc::BC &bc)
real _computeEnergyRaw (real theta) const
bool _computeForceRaw (Real3D &force12, Real3D &force32, const Real3D &dist12, const Real3D &dist32) const
real _computeForceRaw (real theta) const
virtual real computeEnergy (const Particle &p1, const Particle &p2, const Particle &p3) const
virtual real computeEnergy (const Real3D &dist12, const Real3D &dist32) const
virtual real computeEnergy (const real theta) const
virtual void computeForce (Real3D &force12, Real3D &force32, const Particle &p1, const Particle &p2, const Particle &p3) const
virtual void computeForce (Real3D &force12, Real3D &force32, const Real3D &dist12, const Real3D &dist32) const
virtual real computeForce (real theta) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)
virtual shared_ptr< FixedPairList > getColVarBondList () const
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &fpl)
virtual shared_ptr< FixedTripleList > getColVarAngleList () const
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fpl)
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const
virtual void setColVar (const RealND &cv)
virtual RealND getColVar () const
real _computeEnergy (const Particle &p1, const Particle &p2, const Particle &p3) const
real _computeEnergy (const Real3D &dist12, const Real3D &dist32) const
real _computeEnergy (real theta) const
void _computeForce (Real3D &force12, Real3D &force32, const Particle &p1, const Particle &p2, const Particle &p3) const
bool _computeForce (Real3D &force12, Real3D &force32, const Real3D &dist12, const Real3D &dist32) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
TabulatedSubEnsAngular * derived_this ()
const TabulatedSubEnsAngular * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
shared_ptr< FixedPairList > colVarBondList
shared_ptr< FixedTripleList > colVarAngleList
shared_ptr< FixedQuadrupleList > colVarDihedList
RealND colVar
Private Attributes
int numInteractions
std::vector< std::string > filenames
std::vector< shared_ptr< Interpolation > > tables
int interpolationType
RealNDs colVarRef
RealND weights
RealND targetProb
RealND weightSum
int weightCounts
RealND colVarSd
real alpha
int colVarBondListSize
int colVarAngleListSize
int colVarDihedListSize
Detailed Description
Definition at line 33 of file TabulatedSubEnsAngular.hpp.
Constructor & Destructor Documentation
TabulatedSubEnsAngular()
espressopp::interaction::TabulatedSubEnsAngular::TabulatedSubEnsAngular () inline
Definition at line 62 of file TabulatedSubEnsAngular.hpp.
References addInteraction(), espressopp::infinity, espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::setCutoff(), espressopp::RealND::setDimension(), and espressopp::RealNDs::setDimension().
Member Function Documentation
_computeEnergy() [1/3]
real espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::_computeEnergy (const Particle & p1, const Particle & p2, const Particle & p3) const inline inherited
Definition at line 290 of file AngularPotential.hpp.
_computeEnergy() [2/3]
real espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::_computeEnergy (const Real3D & dist12, const Real3D & dist32) const inline inherited
Definition at line 299 of file AngularPotential.hpp.
_computeEnergy() [3/3]
real espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::_computeEnergy (real theta) const inline inherited
Definition at line 314 of file AngularPotential.hpp.
_computeEnergyRaw()
real espressopp::interaction::TabulatedSubEnsAngular::_computeEnergyRaw (real theta) const inline
Definition at line 153 of file TabulatedSubEnsAngular.hpp.
References numInteractions.
_computeForce() [1/2]
void espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::_computeForce (Real3D & force12, Real3D & force32, const Particle & p1, const Particle & p2, const Particle & p3) const inline inherited
Definition at line 343 of file AngularPotential.hpp.
_computeForce() [2/2]
bool espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::_computeForce (Real3D & force12, Real3D & force32, const Real3D & dist12, const Real3D & dist32) const inline inherited
Definition at line 354 of file AngularPotential.hpp.
_computeForceRaw() [1/2]
bool espressopp::interaction::TabulatedSubEnsAngular::_computeForceRaw (Real3D & force12, Real3D & force32, const Real3D & dist12, const Real3D & dist32) const inline
Definition at line 160 of file TabulatedSubEnsAngular.hpp.
References numInteractions.
_computeForceRaw() [2/2]
real espressopp::interaction::TabulatedSubEnsAngular::_computeForceRaw (real theta) const inline
Definition at line 183 of file TabulatedSubEnsAngular.hpp.
References numInteractions.
addInteraction()
void espressopp::interaction::TabulatedSubEnsAngular::addInteraction (int itype, boost::python::str fname, const RealND & _cvref)
Definition at line 59 of file TabulatedSubEnsAngular.cpp.
References colVarRef, filenames, numInteractions, espressopp::RealND::push_back(), espressopp::RealNDs::setDimension(), tables, targetProb, weights, and weightSum.
Referenced by registerPython(), and TabulatedSubEnsAngular().
computeColVarWeights()
void espressopp::interaction::TabulatedSubEnsAngular::computeColVarWeights (const Real3D & dist12, const Real3D & dist32, const bc::BC & bc) virtual
Reimplemented from espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >.
Definition at line 95 of file TabulatedSubEnsAngular.cpp.
References alpha, espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::colVar, colVarAngleListSize, colVarBondListSize, colVarRef, colVarSd, espressopp::RealND::getDimension(), M_PI, numInteractions, setColVar(), targetProb, weightCounts, weights, and weightSum.
Referenced by setAlpha().
computeEnergy() [1/3]
real espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::computeEnergy (const Particle & p1, const Particle & p2, const Particle & p3) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 264 of file AngularPotential.hpp.
computeEnergy() [2/3]
real espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::computeEnergy (const Real3D & dist12, const Real3D & dist32) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 273 of file AngularPotential.hpp.
computeEnergy() [3/3]
real espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::computeEnergy (const real theta) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 283 of file AngularPotential.hpp.
computeForce() [1/3]
void espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::computeForce (Real3D & force12, Real3D & force32, const Particle & p1, const Particle & p2, const Particle & p3) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 322 of file AngularPotential.hpp.
computeForce() [2/3]
void espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::computeForce (Real3D & force12, Real3D & force32, const Real3D & dist12, const Real3D & dist32) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 333 of file AngularPotential.hpp.
computeForce() [3/3]
real espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::computeForce (real theta) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 366 of file AngularPotential.hpp.
derived_this() [1/2]
TabulatedSubEnsAngular * espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::derived_this () inline protected inherited
Definition at line 154 of file AngularPotential.hpp.
derived_this() [2/2]
const TabulatedSubEnsAngular * espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::derived_this () const inline protected inherited
Definition at line 158 of file AngularPotential.hpp.
getAlpha()
real espressopp::interaction::TabulatedSubEnsAngular::getAlpha () const inline
Definition at line 143 of file TabulatedSubEnsAngular.hpp.
References alpha.
Referenced by espressopp::interaction::TabulatedSubEnsAngular_pickle::getinitargs(), and registerPython().
getColVar()
RealND espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::getColVar () const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 249 of file AngularPotential.hpp.
getColVarAngleList()
shared_ptr< FixedTripleList > espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::getColVarAngleList () const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 212 of file AngularPotential.hpp.
getColVarBondList()
shared_ptr< FixedPairList > espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::getColVarBondList () const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 198 of file AngularPotential.hpp.
getColVarDihedList()
shared_ptr< FixedQuadrupleList > espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::getColVarDihedList () const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 226 of file AngularPotential.hpp.
getColVarRef()
RealND espressopp::interaction::TabulatedSubEnsAngular::getColVarRef (int i) const inline
Definition at line 110 of file TabulatedSubEnsAngular.hpp.
Referenced by registerPython().
getColVarRefs()
RealNDs espressopp::interaction::TabulatedSubEnsAngular::getColVarRefs () const inline
Definition at line 112 of file TabulatedSubEnsAngular.hpp.
References colVarRef, and setColVarRef().
Referenced by espressopp::interaction::TabulatedSubEnsAngular_pickle::getinitargs(), and registerPython().
getColVarSds()
RealND espressopp::interaction::TabulatedSubEnsAngular::getColVarSds () const inline
Definition at line 104 of file TabulatedSubEnsAngular.hpp.
References colVarSd.
Referenced by espressopp::interaction::TabulatedSubEnsAngular_pickle::getinitargs(), and registerPython().
getCutoff()
real espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 184 of file AngularPotential.hpp.
getDimension()
int espressopp::interaction::TabulatedSubEnsAngular::getDimension () const inline
Definition at line 90 of file TabulatedSubEnsAngular.hpp.
References numInteractions.
Referenced by espressopp::interaction::TabulatedSubEnsAngular_pickle::getinitargs(), and registerPython().
getFilename()
boost::python::list espressopp::interaction::TabulatedSubEnsAngular::getFilename (int index) const inline
Definition at line 121 of file TabulatedSubEnsAngular.hpp.
Referenced by registerPython().
getFilenames()
boost::python::list espressopp::interaction::TabulatedSubEnsAngular::getFilenames () const inline
Definition at line 118 of file TabulatedSubEnsAngular.hpp.
Referenced by espressopp::interaction::TabulatedSubEnsAngular_pickle::getinitargs(), and registerPython().
getInterpolationType()
int espressopp::interaction::TabulatedSubEnsAngular::getInterpolationType () const inline
Getter for the interpolation type.
Definition at line 96 of file TabulatedSubEnsAngular.hpp.
References interpolationType.
Referenced by espressopp::interaction::TabulatedSubEnsAngular_pickle::getinitargs().
getTargetProb()
RealND espressopp::interaction::TabulatedSubEnsAngular::getTargetProb () const inline
Definition at line 98 of file TabulatedSubEnsAngular.hpp.
References targetProb.
Referenced by registerPython().
getWeight()
real espressopp::interaction::TabulatedSubEnsAngular::getWeight (int index) const inline
Definition at line 135 of file TabulatedSubEnsAngular.hpp.
References espressopp::RealND::getItem().
getWeights()
RealND espressopp::interaction::TabulatedSubEnsAngular::getWeights () const inline
Definition at line 131 of file TabulatedSubEnsAngular.hpp.
References weights.
Referenced by registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::AngularPotential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
registerPython()
void espressopp::interaction::TabulatedSubEnsAngular::registerPython () static
Definition at line 240 of file TabulatedSubEnsAngular.cpp.
References addInteraction(), getAlpha(), getColVarRef(), getColVarRefs(), getColVarSds(), getDimension(), getFilename(), getFilenames(), getTargetProb(), getWeights(), setAlpha(), setColVarSd(), setFilename(), setTargetProb(), and setWeight().
Referenced by espressopp::interaction::registerPython().
setAlpha()
void espressopp::interaction::TabulatedSubEnsAngular::setAlpha (real _r) inline
Definition at line 145 of file TabulatedSubEnsAngular.hpp.
References computeColVarWeights(), and setColVar().
Referenced by registerPython().
setColVar() [1/2]
void espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::setColVar (const RealND & cv) inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 233 of file AngularPotential.hpp.
setColVar() [2/2]
void espressopp::interaction::TabulatedSubEnsAngular::setColVar (const Real3D & dist12, const Real3D & dist32, const bc::BC & bc) virtual
Reimplemented from espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >.
Definition at line 172 of file TabulatedSubEnsAngular.cpp.
References espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::colVar, espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::colVarAngleList, colVarAngleListSize, espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::colVarBondList, colVarBondListSize, espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::colVarDihedList, colVarDihedListSize, espressopp::interaction::DihedralPotential::computePhi(), espressopp::bc::BC::getMinimumImageVectorBox(), espressopp::Particle::position(), and espressopp::RealND::setDimension().
Referenced by computeColVarWeights(), and setAlpha().
setColVarAngleList()
void espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::setColVarAngleList (const shared_ptr< FixedTripleList > & fpl) inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 205 of file AngularPotential.hpp.
setColVarBondList()
void espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::setColVarBondList (const shared_ptr< FixedPairList > & fpl) inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 191 of file AngularPotential.hpp.
setColVarDihedList()
void espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fpl) inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 219 of file AngularPotential.hpp.
setColVarRef()
void espressopp::interaction::TabulatedSubEnsAngular::setColVarRef (const RealNDs & cvRefs)
Definition at line 87 of file TabulatedSubEnsAngular.cpp.
References colVarRef, and numInteractions.
Referenced by getColVarRefs().
setColVarRefs()
void espressopp::interaction::TabulatedSubEnsAngular::setColVarRefs (const RealNDs & c) inline
Definition at line 116 of file TabulatedSubEnsAngular.hpp.
setColVarSd()
void espressopp::interaction::TabulatedSubEnsAngular::setColVarSd (int index, real _r) inline
Definition at line 106 of file TabulatedSubEnsAngular.hpp.
References espressopp::RealND::setItem().
Referenced by registerPython().
setCutoff()
void espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 176 of file AngularPotential.hpp.
Referenced by TabulatedSubEnsAngular().
setDimension()
void espressopp::interaction::TabulatedSubEnsAngular::setDimension (int _dim) inline
Definition at line 80 of file TabulatedSubEnsAngular.hpp.
References espressopp::RealND::setDimension(), and espressopp::RealNDs::setDimension().
setFilename()
void espressopp::interaction::TabulatedSubEnsAngular::setFilename (int index, boost::python::list _f) inline
Definition at line 125 of file TabulatedSubEnsAngular.hpp.
References setFilenames().
Referenced by registerPython().
setFilenames()
void espressopp::interaction::TabulatedSubEnsAngular::setFilenames (int dim, int itype, boost::python::list _filenames)
Definition at line 33 of file TabulatedSubEnsAngular.cpp.
References colVarRef, filenames, numInteractions, espressopp::RealNDs::setDimension(), and tables.
Referenced by setFilename().
setInterpolationType()
void espressopp::interaction::TabulatedSubEnsAngular::setInterpolationType (int itype) inline
Setter for the interpolation type.
Definition at line 93 of file TabulatedSubEnsAngular.hpp.
setTargetProb()
void espressopp::interaction::TabulatedSubEnsAngular::setTargetProb (int index, real _r) inline
Definition at line 100 of file TabulatedSubEnsAngular.hpp.
References espressopp::RealND::setItem().
Referenced by registerPython().
setWeight()
void espressopp::interaction::TabulatedSubEnsAngular::setWeight (int index, real _w) inline
Definition at line 139 of file TabulatedSubEnsAngular.hpp.
References espressopp::RealND::setItem().
Referenced by registerPython().
setWeights()
void espressopp::interaction::TabulatedSubEnsAngular::setWeights (const RealND & r) inline
Definition at line 133 of file TabulatedSubEnsAngular.hpp.
Member Data Documentation
alpha
real espressopp::interaction::TabulatedSubEnsAngular::alpha private
Definition at line 52 of file TabulatedSubEnsAngular.hpp.
Referenced by computeColVarWeights(), and getAlpha().
colVar
RealND espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::colVar protected inherited
Definition at line 152 of file AngularPotential.hpp.
Referenced by computeColVarWeights(), and setColVar().
colVarAngleList
shared_ptr<FixedTripleList> espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::colVarAngleList protected inherited
Definition at line 148 of file AngularPotential.hpp.
Referenced by setColVar().
colVarAngleListSize
int espressopp::interaction::TabulatedSubEnsAngular::colVarAngleListSize private
Definition at line 55 of file TabulatedSubEnsAngular.hpp.
Referenced by computeColVarWeights(), and setColVar().
colVarBondList
shared_ptr<FixedPairList> espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::colVarBondList protected inherited
Definition at line 146 of file AngularPotential.hpp.
Referenced by setColVar().
colVarBondListSize
int espressopp::interaction::TabulatedSubEnsAngular::colVarBondListSize private
Definition at line 54 of file TabulatedSubEnsAngular.hpp.
Referenced by computeColVarWeights(), and setColVar().
colVarDihedList
shared_ptr<FixedQuadrupleList> espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::colVarDihedList protected inherited
Definition at line 150 of file AngularPotential.hpp.
Referenced by setColVar().
colVarDihedListSize
int espressopp::interaction::TabulatedSubEnsAngular::colVarDihedListSize private
Definition at line 56 of file TabulatedSubEnsAngular.hpp.
Referenced by setColVar().
colVarRef
RealNDs espressopp::interaction::TabulatedSubEnsAngular::colVarRef private
Definition at line 41 of file TabulatedSubEnsAngular.hpp.
Referenced by addInteraction(), computeColVarWeights(), getColVarRefs(), setColVarRef(), and setFilenames().
colVarSd
RealND espressopp::interaction::TabulatedSubEnsAngular::colVarSd private
Definition at line 50 of file TabulatedSubEnsAngular.hpp.
Referenced by computeColVarWeights(), and getColVarSds().
cutoff
real espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::cutoff protected inherited
Definition at line 143 of file AngularPotential.hpp.
cutoffSqr
real espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >::cutoffSqr protected inherited
Definition at line 144 of file AngularPotential.hpp.
filenames
std::vector<std::string> espressopp::interaction::TabulatedSubEnsAngular::filenames private
Definition at line 37 of file TabulatedSubEnsAngular.hpp.
Referenced by addInteraction(), and setFilenames().
interpolationType
int espressopp::interaction::TabulatedSubEnsAngular::interpolationType private
Definition at line 39 of file TabulatedSubEnsAngular.hpp.
Referenced by getInterpolationType().
numInteractions
int espressopp::interaction::TabulatedSubEnsAngular::numInteractions private
Definition at line 36 of file TabulatedSubEnsAngular.hpp.
Referenced by _computeEnergyRaw(), _computeForceRaw(), addInteraction(), computeColVarWeights(), getDimension(), setColVarRef(), and setFilenames().
tables
std::vector<shared_ptr <Interpolation> > espressopp::interaction::TabulatedSubEnsAngular::tables private
Definition at line 38 of file TabulatedSubEnsAngular.hpp.
Referenced by addInteraction(), and setFilenames().
targetProb
RealND espressopp::interaction::TabulatedSubEnsAngular::targetProb private
Definition at line 45 of file TabulatedSubEnsAngular.hpp.
Referenced by addInteraction(), computeColVarWeights(), and getTargetProb().
weightCounts
int espressopp::interaction::TabulatedSubEnsAngular::weightCounts private
Definition at line 48 of file TabulatedSubEnsAngular.hpp.
Referenced by computeColVarWeights().
weights
RealND espressopp::interaction::TabulatedSubEnsAngular::weights private
Definition at line 43 of file TabulatedSubEnsAngular.hpp.
Referenced by addInteraction(), computeColVarWeights(), and getWeights().
weightSum
RealND espressopp::interaction::TabulatedSubEnsAngular::weightSum private
Definition at line 47 of file TabulatedSubEnsAngular.hpp.
Referenced by addInteraction(), and computeColVarWeights().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/TabulatedSubEnsAngular.hpp
/home/espressopp/espressopp/src/interaction/TabulatedSubEnsAngular.cpp