ESPResSo++: espressopp::interaction::TersoffPairTerm Class Reference
espressopp::interaction::TersoffPairTerm Class Reference
This class provides methods to compute forces and energies of 2 body term of Tersoff potential.
#include <TersoffPairTerm.hpp>
Public Member Functions
TersoffPairTerm ()
TersoffPairTerm (real _A, real _lambda1, real _R, real _D, real _cutoff)
virtual ~TersoffPairTerm ()
void setA (real _A)
real getA () const
void setLambda1 (real _lambda1)
real getLambda1 () const
void setR (real _R)
real getR () const
void setD (real _D)
real getD () const
void preset ()
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &r12, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
real _computeEnergyDeriv (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
TersoffPairTerm * derived_this ()
const TersoffPairTerm * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
Private Attributes
real A
real lambda1
real R
real D
real Pi_2D
Detailed Description
This class provides methods to compute forces and energies of 2 body term of Tersoff potential.
Definition at line 45 of file TersoffPairTerm.hpp.
Constructor & Destructor Documentation
TersoffPairTerm() [1/2]
espressopp::interaction::TersoffPairTerm::TersoffPairTerm () inline
Definition at line 53 of file TersoffPairTerm.hpp.
References espressopp::infinity, preset(), espressopp::interaction::PotentialTemplate< TersoffPairTerm >::setCutoff(), and espressopp::interaction::PotentialTemplate< TersoffPairTerm >::setShift().
TersoffPairTerm() [2/2]
espressopp::interaction::TersoffPairTerm::TersoffPairTerm (real _A, real _lambda1, real _R, real _D, real _cutoff) inline
Definition at line 59 of file TersoffPairTerm.hpp.
References preset(), espressopp::interaction::PotentialTemplate< TersoffPairTerm >::setCutoff(), and espressopp::interaction::PotentialTemplate< TersoffPairTerm >::setShift().
~TersoffPairTerm()
virtual espressopp::interaction::TersoffPairTerm::~TersoffPairTerm () inline virtual
Definition at line 66 of file TersoffPairTerm.hpp.
Member Function Documentation
_computeEnergy() [1/4]
real espressopp::interaction::PotentialTemplate< TersoffPairTerm >::_computeEnergy (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 242 of file Potential.hpp.
_computeEnergy() [2/4]
real espressopp::interaction::PotentialTemplate< TersoffPairTerm >::_computeEnergy (const Real3D & dist) const inline inherited
Definition at line 257 of file Potential.hpp.
_computeEnergy() [3/4]
real espressopp::interaction::PotentialTemplate< TersoffPairTerm >::_computeEnergy (real dist) const inline inherited
Definition at line 264 of file Potential.hpp.
_computeEnergy() [4/4]
real espressopp::interaction::PotentialTemplate< TersoffPairTerm >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 250 of file Potential.hpp.
_computeEnergyDeriv()
real espressopp::interaction::PotentialTemplate< TersoffPairTerm >::_computeEnergyDeriv (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 285 of file Potential.hpp.
_computeEnergySqr()
real espressopp::interaction::PotentialTemplate< TersoffPairTerm >::_computeEnergySqr (real distSqr) const inline inherited
Definition at line 271 of file Potential.hpp.
_computeEnergySqrRaw()
real espressopp::interaction::TersoffPairTerm::_computeEnergySqrRaw (real distSqr) const inline
Definition at line 89 of file TersoffPairTerm.hpp.
References R.
_computeForce() [1/3]
bool espressopp::interaction::PotentialTemplate< TersoffPairTerm >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const inline inherited
Definition at line 313 of file Potential.hpp.
_computeForce() [2/3]
bool espressopp::interaction::PotentialTemplate< TersoffPairTerm >::_computeForce (Real3D & force, const Real3D & dist) const inline inherited
Definition at line 328 of file Potential.hpp.
_computeForce() [3/3]
bool espressopp::interaction::PotentialTemplate< TersoffPairTerm >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 321 of file Potential.hpp.
_computeForceRaw()
bool espressopp::interaction::TersoffPairTerm::_computeForceRaw (Real3D & force, const Real3D & r12, real distSqr) const inline
Definition at line 108 of file TersoffPairTerm.hpp.
References R.
computeEnergy() [1/3]
real espressopp::interaction::PotentialTemplate< TersoffPairTerm >::computeEnergy (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 213 of file Potential.hpp.
computeEnergy() [2/3]
real espressopp::interaction::PotentialTemplate< TersoffPairTerm >::computeEnergy (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 221 of file Potential.hpp.
computeEnergy() [3/3]
real espressopp::interaction::PotentialTemplate< TersoffPairTerm >::computeEnergy (real dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 228 of file Potential.hpp.
computeEnergySqr()
real espressopp::interaction::PotentialTemplate< TersoffPairTerm >::computeEnergySqr (real distsqr) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 235 of file Potential.hpp.
computeForce() [1/2]
Real3D espressopp::interaction::PotentialTemplate< TersoffPairTerm >::computeForce (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 295 of file Potential.hpp.
computeForce() [2/2]
Real3D espressopp::interaction::PotentialTemplate< TersoffPairTerm >::computeForce (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 303 of file Potential.hpp.
derived_this() [1/2]
TersoffPairTerm * espressopp::interaction::PotentialTemplate< TersoffPairTerm >::derived_this () inline protected inherited
Definition at line 123 of file Potential.hpp.
derived_this() [2/2]
const TersoffPairTerm * espressopp::interaction::PotentialTemplate< TersoffPairTerm >::derived_this () const inline protected inherited
Definition at line 127 of file Potential.hpp.
getA()
real espressopp::interaction::TersoffPairTerm::getA () const inline
Definition at line 69 of file TersoffPairTerm.hpp.
References A.
Referenced by registerPython().
getCutoff()
real espressopp::interaction::PotentialTemplate< TersoffPairTerm >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 171 of file Potential.hpp.
getD()
real espressopp::interaction::TersoffPairTerm::getD () const inline
Definition at line 81 of file TersoffPairTerm.hpp.
References D.
Referenced by registerPython().
getLambda1()
real espressopp::interaction::TersoffPairTerm::getLambda1 () const inline
Definition at line 72 of file TersoffPairTerm.hpp.
References lambda1.
Referenced by registerPython().
getR()
real espressopp::interaction::TersoffPairTerm::getR () const inline
Definition at line 75 of file TersoffPairTerm.hpp.
References R.
Referenced by registerPython().
getShift()
real espressopp::interaction::PotentialTemplate< TersoffPairTerm >::getShift () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 186 of file Potential.hpp.
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
Referenced by espressopp::interaction::Potential::~Potential().
preset()
void espressopp::interaction::TersoffPairTerm::preset () inline
Definition at line 85 of file TersoffPairTerm.hpp.
References D, and M_PIl.
Referenced by setD(), and TersoffPairTerm().
registerPython()
void espressopp::interaction::TersoffPairTerm::registerPython () static
Definition at line 43 of file TersoffPairTerm.cpp.
References getA(), getD(), getLambda1(), getR(), setA(), setD(), setLambda1(), and setR().
Referenced by espressopp::interaction::registerPython().
setA()
void espressopp::interaction::TersoffPairTerm::setA (real _A) inline
Definition at line 68 of file TersoffPairTerm.hpp.
Referenced by registerPython().
setAutoShift()
real espressopp::interaction::PotentialTemplate< TersoffPairTerm >::setAutoShift () inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 192 of file Potential.hpp.
setCutoff()
void espressopp::interaction::PotentialTemplate< TersoffPairTerm >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 162 of file Potential.hpp.
Referenced by TersoffPairTerm().
setD()
void espressopp::interaction::TersoffPairTerm::setD (real _D) inline
Definition at line 77 of file TersoffPairTerm.hpp.
References preset().
Referenced by registerPython().
setLambda1()
void espressopp::interaction::TersoffPairTerm::setLambda1 (real _lambda1) inline
Definition at line 71 of file TersoffPairTerm.hpp.
Referenced by registerPython().
setR()
void espressopp::interaction::TersoffPairTerm::setR (real _R) inline
Definition at line 74 of file TersoffPairTerm.hpp.
Referenced by registerPython().
setShift()
void espressopp::interaction::PotentialTemplate< TersoffPairTerm >::setShift (real _shift) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 177 of file Potential.hpp.
Referenced by TersoffPairTerm().
updateAutoShift()
void espressopp::interaction::PotentialTemplate< TersoffPairTerm >::updateAutoShift () inline inherited
Definition at line 205 of file Potential.hpp.
Member Data Documentation
A
real espressopp::interaction::TersoffPairTerm::A private
Definition at line 48 of file TersoffPairTerm.hpp.
Referenced by getA().
autoShift
bool espressopp::interaction::PotentialTemplate< TersoffPairTerm >::autoShift protected inherited
Definition at line 121 of file Potential.hpp.
cutoff
real espressopp::interaction::PotentialTemplate< TersoffPairTerm >::cutoff protected inherited
Definition at line 118 of file Potential.hpp.
cutoffSqr
real espressopp::interaction::PotentialTemplate< TersoffPairTerm >::cutoffSqr protected inherited
Definition at line 119 of file Potential.hpp.
D
real espressopp::interaction::TersoffPairTerm::D private
Definition at line 48 of file TersoffPairTerm.hpp.
Referenced by getD(), and preset().
lambda1
real espressopp::interaction::TersoffPairTerm::lambda1 private
Definition at line 48 of file TersoffPairTerm.hpp.
Referenced by getLambda1().
Pi_2D
real espressopp::interaction::TersoffPairTerm::Pi_2D private
Definition at line 49 of file TersoffPairTerm.hpp.
R
real espressopp::interaction::TersoffPairTerm::R private
Definition at line 48 of file TersoffPairTerm.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), and getR().
shift
real espressopp::interaction::PotentialTemplate< TersoffPairTerm >::shift protected inherited
Definition at line 120 of file Potential.hpp.
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/TersoffPairTerm.hpp
/home/espressopp/espressopp/src/interaction/TersoffPairTerm.cpp