ESPResSo++: espressopp::ParticleGroup Class Reference
espressopp::ParticleGroup Class Reference
group of particles
#include <ParticleGroup.hpp>
Classes
struct iterator
iterator for active particles
Public Member Functions
ParticleGroup (shared_ptr< storage::Storage > _storage)
~ParticleGroup ()
void add (longint pid)
add particle to group
void print ()
bool has (longint pid)
longint size ()
iterator begin ()
begin iterator for active particles
iterator end ()
end iterator for active particles
Static Public Member Functions
static void registerPython ()
Protected Member Functions
void beforeSendParticles (ParticleList &pl, class OutBuffer &buf)
void afterRecvParticles (ParticleList &pl, class InBuffer &buf)
void onParticlesChanged ()
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Attributes
std::map< longint, Particle * > active
std::set< longint > particles
shared_ptr< storage::Storage > storage
boost::signals2::connection con_send
boost::signals2::connection con_recv
boost::signals2::connection con_changed
Detailed Description
group of particles
This part contains a list of particles to e.g. organize the system into molecules. The particles are stored as ids, in addition a list of active particles on the processor (or will it be cell) is generated by connecting to the communicator signals.
This is a first try. Further extensions might be to put groups into groups.
Definition at line 47 of file ParticleGroup.hpp.
Constructor & Destructor Documentation
ParticleGroup()
espressopp::ParticleGroup::ParticleGroup (shared_ptr< storage::Storage > _storage)
Definition at line 30 of file ParticleGroup.cpp.
References afterRecvParticles(), beforeSendParticles(), con_changed, con_recv, con_send, onParticlesChanged(), and storage.
~ParticleGroup()
espressopp::ParticleGroup::~ParticleGroup ()
Definition at line 41 of file ParticleGroup.cpp.
References con_changed, con_recv, and con_send.
Member Function Documentation
add()
void espressopp::ParticleGroup::add (longint pid)
add particle to group
Parameters
pid particle id
Definition at line 48 of file ParticleGroup.cpp.
References active, particles, and storage.
Referenced by registerPython().
afterRecvParticles()
void espressopp::ParticleGroup::afterRecvParticles (ParticleList & pl, class InBuffer & buf) protected
Definition at line 91 of file ParticleGroup.cpp.
References active, espressopp::esutil::ESPPIterator< STLContainer >::isValid(), and particles.
Referenced by ParticleGroup().
beforeSendParticles()
void espressopp::ParticleGroup::beforeSendParticles (ParticleList & pl, class OutBuffer & buf) protected
Definition at line 78 of file ParticleGroup.cpp.
References active, and espressopp::esutil::ESPPIterator< STLContainer >::isValid().
Referenced by ParticleGroup().
begin()
iterator espressopp::ParticleGroup::begin () inline
begin iterator for active particles
Returns
begin iterator
Definition at line 92 of file ParticleGroup.hpp.
References active.
Referenced by print().
end()
iterator espressopp::ParticleGroup::end () inline
end iterator for active particles
Returns
end iterator
Definition at line 101 of file ParticleGroup.hpp.
References active.
Referenced by print().
has()
bool espressopp::ParticleGroup::has (longint pid)
Definition at line 57 of file ParticleGroup.cpp.
References particles.
Referenced by registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::ParticleGroup::LOG4ESPP_DECL_LOGGER (theLogger) static protected
onParticlesChanged()
void espressopp::ParticleGroup::onParticlesChanged () protected
Definition at line 106 of file ParticleGroup.cpp.
References active, and storage.
Referenced by ParticleGroup().
print()
void espressopp::ParticleGroup::print ()
Definition at line 62 of file ParticleGroup.cpp.
References active, begin(), end(), and particles.
Referenced by registerPython().
registerPython()
void espressopp::ParticleGroup::registerPython () static
Definition at line 126 of file ParticleGroup.cpp.
References add(), has(), print(), and size().
Referenced by espressopp::registerPython().
size()
longint espressopp::ParticleGroup::size () inline
Definition at line 64 of file ParticleGroup.hpp.
References particles.
Referenced by registerPython().
Member Data Documentation
active
std::map<longint, Particle*> espressopp::ParticleGroup::active protected
Definition at line 108 of file ParticleGroup.hpp.
Referenced by add(), afterRecvParticles(), beforeSendParticles(), begin(), end(), onParticlesChanged(), and print().
con_changed
boost::signals2::connection espressopp::ParticleGroup::con_changed protected
Definition at line 120 of file ParticleGroup.hpp.
Referenced by ParticleGroup(), and ~ParticleGroup().
con_recv
boost::signals2::connection espressopp::ParticleGroup::con_recv protected
Definition at line 120 of file ParticleGroup.hpp.
Referenced by ParticleGroup(), and ~ParticleGroup().
con_send
boost::signals2::connection espressopp::ParticleGroup::con_send protected
Definition at line 120 of file ParticleGroup.hpp.
Referenced by ParticleGroup(), and ~ParticleGroup().
particles
std::set<longint> espressopp::ParticleGroup::particles protected
Todo:
find better solution here
Definition at line 114 of file ParticleGroup.hpp.
Referenced by add(), afterRecvParticles(), has(), print(), and size().
storage
shared_ptr<storage::Storage> espressopp::ParticleGroup::storage protected
Definition at line 117 of file ParticleGroup.hpp.
Referenced by add(), onParticlesChanged(), and ParticleGroup().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/ParticleGroup.hpp
/home/espressopp/espressopp/src/ParticleGroup.cpp