ESPResSo++: espressopp::FixedQuadrupleAngleList Class Reference
espressopp::FixedQuadrupleAngleList Class Reference
#include <FixedQuadrupleAngleList.hpp>
Public Types
typedef ESPPIterator
< std::vector
< ParticleQuadruple > > Iterator
Public Member Functions
FixedQuadrupleAngleList (shared_ptr< storage::Storage > _storage)
~FixedQuadrupleAngleList ()
bool add (longint pid1, longint pid2, longint pid3, longint pid4)
Add the given particle quadruple to the list on this processor if the particle with the lower id belongs to this processor.
void beforeSendParticles (ParticleList &pl, class OutBuffer &buf)
void afterRecvParticles (ParticleList &pl, class InBuffer &buf)
void onParticlesChanged ()
python::list getQuadruples ()
python::list getQuadruplesAngles ()
real getAngle (int, int, int, int)
int size ()
Get the number of quadruples in the GlobalQuadruples list.
void add (Particle *p1, Particle *p2, Particle *p3, Particle *p4)
void add (Particle &p1, Particle &p2, Particle &p3, Particle &p4)
void add (std::vector< Particle * > particles)
Static Public Member Functions
static void registerPython ()
Protected Types
typedef std::multimap< longint,
std::pair< Triple< longint,
longint, longint >, real > > QuadruplesAngles
typedef std::vector
< ParticleQuadruple > Super
Protected Attributes
boost::signals2::connection con1
boost::signals2::connection con2
boost::signals2::connection con3
shared_ptr< storage::Storage > storage
QuadruplesAngles quadruplesAngles
Static Private Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Detailed Description
Definition at line 38 of file FixedQuadrupleAngleList.hpp.
Member Typedef Documentation
typedef ESPPIterator<std::vector< ParticleQuadruple > > espressopp::esutil::ESPPContainer< std::vector< ParticleQuadruple > >::Iterator inherited
Definition at line 66 of file ESPPIterator.hpp.
typedef std::multimap< longint, std::pair<Triple < longint, longint, longint >, real> > espressopp::FixedQuadrupleAngleList::QuadruplesAngles protected
Definition at line 42 of file FixedQuadrupleAngleList.hpp.
typedef std::vector< ParticleQuadruple > espressopp::esutil::ESPPContainer< std::vector< ParticleQuadruple > >::Super protected inherited
Definition at line 64 of file ESPPIterator.hpp.
Constructor & Destructor Documentation
espressopp::FixedQuadrupleAngleList::FixedQuadrupleAngleList (shared_ptr< storage::Storage > _storage)
Definition at line 47 of file FixedQuadrupleAngleList.cpp.
References afterRecvParticles(), beforeSendParticles(), con1, con2, con3, LOG4ESPP_INFO, onParticlesChanged(), and storage.
espressopp::FixedQuadrupleAngleList::~FixedQuadrupleAngleList ()
Definition at line 60 of file FixedQuadrupleAngleList.cpp.
References con1, con2, con3, and LOG4ESPP_INFO.
Member Function Documentation
bool espressopp::FixedQuadrupleAngleList::add (longint pid1, longint pid2, longint pid3, longint pid4)
Add the given particle quadruple to the list on this processor if the particle with the lower id belongs to this processor.
Note that this routine does not check whether the quadruple is inserted on another processor as well.
it contains the information about the initial angle for each quadruple.
This is probably temporary fast solution for the dihedral potential where all the quadruples have different phi0
Returns
whether the quadruple was inserted on this processor.
Definition at line 69 of file FixedQuadrupleAngleList.cpp.
References espressopp::System::bc, espressopp::esutil::Error::checkException(), espressopp::System::comm, espressopp::Real3D::cross(), LOG4ESPP_INFO, espressopp::Particle::position(), quadruplesAngles, espressopp::esutil::Error::setException(), espressopp::Real3D::sqr(), and storage.
Referenced by onParticlesChanged(), and registerPython().
void espressopp::QuadrupleList::add (Particle * p1, Particle * p2, Particle * p3, Particle * p4) inline inherited
Definition at line 455 of file Particle.hpp.
Referenced by espressopp::FixedListComm::add(), espressopp::QuadrupleList::add(), and espressopp::FixedListComm::onParticlesChanged().
void espressopp::QuadrupleList::add (Particle & p1, Particle & p2, Particle & p3, Particle & p4) inline inherited
Definition at line 459 of file Particle.hpp.
References espressopp::QuadrupleList::add().
Referenced by espressopp::QuadrupleList::add().
void espressopp::QuadrupleList::add (std::vector< Particle * > particles) inline inherited
Definition at line 462 of file Particle.hpp.
References espressopp::QuadrupleList::add().
void espressopp::FixedQuadrupleAngleList::afterRecvParticles (ParticleList & pl, class InBuffer & buf)
Definition at line 245 of file FixedQuadrupleAngleList.cpp.
References LOG4ESPP_INFO, quadruplesAngles, espressopp::InBuffer::read(), and size().
Referenced by FixedQuadrupleAngleList().
void espressopp::FixedQuadrupleAngleList::beforeSendParticles (ParticleList & pl, class OutBuffer & buf)
Definition at line 203 of file FixedQuadrupleAngleList.cpp.
References espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_INFO, quadruplesAngles, and espressopp::OutBuffer::write().
Referenced by FixedQuadrupleAngleList().
real espressopp::FixedQuadrupleAngleList::getAngle (int pid1, int pid2, int pid3, int pid4)
Definition at line 177 of file FixedQuadrupleAngleList.cpp.
References quadruplesAngles, and espressopp::Triple< T1, T2, T3 >::second.
Referenced by registerPython().
python::list espressopp::FixedQuadrupleAngleList::getQuadruples ()
Definition at line 148 of file FixedQuadrupleAngleList.cpp.
References quadruplesAngles.
Referenced by registerPython().
python::list espressopp::FixedQuadrupleAngleList::getQuadruplesAngles ()
Definition at line 163 of file FixedQuadrupleAngleList.cpp.
References quadruplesAngles.
Referenced by registerPython().
static espressopp::FixedQuadrupleAngleList::LOG4ESPP_DECL_LOGGER (theLogger) static private
void espressopp::FixedQuadrupleAngleList::onParticlesChanged ()
Definition at line 278 of file FixedQuadrupleAngleList.cpp.
References add(), espressopp::esutil::Error::checkException(), espressopp::System::comm, LOG4ESPP_INFO, quadruplesAngles, espressopp::esutil::Error::setException(), and storage.
Referenced by FixedQuadrupleAngleList().
void espressopp::FixedQuadrupleAngleList::registerPython () static
Definition at line 334 of file FixedQuadrupleAngleList.cpp.
References add(), getAngle(), getQuadruples(), getQuadruplesAngles(), and size().
Referenced by espressopp::registerPython().
int espressopp::FixedQuadrupleAngleList::size () inline
Get the number of quadruples in the GlobalQuadruples list.
Definition at line 76 of file FixedQuadrupleAngleList.hpp.
References quadruplesAngles.
Referenced by afterRecvParticles(), and registerPython().
Member Data Documentation
boost::signals2::connection espressopp::FixedQuadrupleAngleList::con1 protected
Definition at line 40 of file FixedQuadrupleAngleList.hpp.
Referenced by FixedQuadrupleAngleList(), and ~FixedQuadrupleAngleList().
boost::signals2::connection espressopp::FixedQuadrupleAngleList::con2 protected
Definition at line 40 of file FixedQuadrupleAngleList.hpp.
Referenced by FixedQuadrupleAngleList(), and ~FixedQuadrupleAngleList().
boost::signals2::connection espressopp::FixedQuadrupleAngleList::con3 protected
Definition at line 40 of file FixedQuadrupleAngleList.hpp.
Referenced by FixedQuadrupleAngleList(), and ~FixedQuadrupleAngleList().
QuadruplesAngles espressopp::FixedQuadrupleAngleList::quadruplesAngles protected
Definition at line 44 of file FixedQuadrupleAngleList.hpp.
Referenced by add(), afterRecvParticles(), beforeSendParticles(), getAngle(), getQuadruples(), getQuadruplesAngles(), onParticlesChanged(), and size().
shared_ptr<storage::Storage> espressopp::FixedQuadrupleAngleList::storage protected
Definition at line 43 of file FixedQuadrupleAngleList.hpp.
Referenced by add(), FixedQuadrupleAngleList(), and onParticlesChanged().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/FixedQuadrupleAngleList.hpp
/home/travis/build/espressopp/espressopp/src/FixedQuadrupleAngleList.cpp