ESPResSo++: espressopp::interaction::DihedralHarmonicUniqueCos Class Reference
espressopp::interaction::DihedralHarmonicUniqueCos Class Reference
This class provides methods to compute forces and energies of the DihedralHarmonicUniqueCos dihedral potential.
#include <DihedralHarmonicUniqueCos.hpp>
Public Member Functions
DihedralHarmonicUniqueCos ()
DihedralHarmonicUniqueCos (real _K)
void setK (real _K)
real getK () const
real d (int i, int j) const
Real3D prod (Real3D a, Real3D b) const
real _computeEnergyRaw (real _phi, real _phi0) const
void _computeForceRaw (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &r21, const Real3D &r32, const Real3D &r43, const real _phi0) const
real _computeForceRaw (real phi, real _phi0) const
virtual real computeEnergy (const Real3D &r21, const Real3D &r32, const Real3D &r43, const real phi0) const
virtual real computeEnergy (real phi, real phi0) const
virtual void computeForce (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &r21, const Real3D &r32, const Real3D &r43, const real phi0) const
virtual real computeForce (real phi, real phi0) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
real _computeEnergy (const Real3D &r21, const Real3D &r32, const Real3D &r43, const real phi0) const
real _computeEnergy (real phi, real phi0) const
void _computeForce (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &r21, const Real3D &r32, const Real3D &r43, const real phi0) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
DihedralHarmonicUniqueCos * derived_this ()
const DihedralHarmonicUniqueCos * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
Private Attributes
real K
Detailed Description
This class provides methods to compute forces and energies of the DihedralHarmonicUniqueCos dihedral potential.
Definition at line 35 of file DihedralHarmonicUniqueCos.hpp.
Constructor & Destructor Documentation
DihedralHarmonicUniqueCos() [1/2]
espressopp::interaction::DihedralHarmonicUniqueCos::DihedralHarmonicUniqueCos () inline
Definition at line 41 of file DihedralHarmonicUniqueCos.hpp.
DihedralHarmonicUniqueCos() [2/2]
espressopp::interaction::DihedralHarmonicUniqueCos::DihedralHarmonicUniqueCos (real _K) inline
Definition at line 42 of file DihedralHarmonicUniqueCos.hpp.
Member Function Documentation
_computeEnergy() [1/2]
real espressopp::interaction::DihedralUniquePotentialTemplate< DihedralHarmonicUniqueCos >::_computeEnergy (const Real3D & r21, const Real3D & r32, const Real3D & r43, const real phi0) const inline inherited
Definition at line 165 of file DihedralUniquePotential.hpp.
References espressopp::Real3D::cross(), and espressopp::Real3D::sqr().
_computeEnergy() [2/2]
real espressopp::interaction::DihedralUniquePotentialTemplate< DihedralHarmonicUniqueCos >::_computeEnergy (real phi, real phi0) const inline inherited
Definition at line 194 of file DihedralUniquePotential.hpp.
_computeEnergyRaw()
real espressopp::interaction::DihedralHarmonicUniqueCos::_computeEnergyRaw (real _phi, real _phi0) const inline
Definition at line 65 of file DihedralHarmonicUniqueCos.hpp.
_computeForce()
void espressopp::interaction::DihedralUniquePotentialTemplate< DihedralHarmonicUniqueCos >::_computeForce (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & r21, const Real3D & r32, const Real3D & r43, const real phi0) const inline inherited
Definition at line 216 of file DihedralUniquePotential.hpp.
_computeForceRaw() [1/2]
void espressopp::interaction::DihedralHarmonicUniqueCos::_computeForceRaw (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & r21, const Real3D & r32, const Real3D & r43, const real _phi0) const inline
Definition at line 71 of file DihedralHarmonicUniqueCos.hpp.
References espressopp::Real3D::cross(), d(), prod(), and espressopp::Real3D::sqr().
_computeForceRaw() [2/2]
real espressopp::interaction::DihedralHarmonicUniqueCos::_computeForceRaw (real phi, real _phi0) const inline
Definition at line 138 of file DihedralHarmonicUniqueCos.hpp.
computeEnergy() [1/2]
real espressopp::interaction::DihedralUniquePotentialTemplate< DihedralHarmonicUniqueCos >::computeEnergy (const Real3D & r21, const Real3D & r32, const Real3D & r43, const real phi0) const inline virtual inherited
Implements espressopp::interaction::DihedralUniquePotential.
Definition at line 145 of file DihedralUniquePotential.hpp.
computeEnergy() [2/2]
real espressopp::interaction::DihedralUniquePotentialTemplate< DihedralHarmonicUniqueCos >::computeEnergy (real phi, real phi0) const inline virtual inherited
Implements espressopp::interaction::DihedralUniquePotential.
Definition at line 158 of file DihedralUniquePotential.hpp.
computeForce() [1/2]
void espressopp::interaction::DihedralUniquePotentialTemplate< DihedralHarmonicUniqueCos >::computeForce (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & r21, const Real3D & r32, const Real3D & r43, const real phi0) const inline virtual inherited
Implements espressopp::interaction::DihedralUniquePotential.
Definition at line 202 of file DihedralUniquePotential.hpp.
computeForce() [2/2]
real espressopp::interaction::DihedralUniquePotentialTemplate< DihedralHarmonicUniqueCos >::computeForce (real phi, real phi0) const inline virtual inherited
Implements espressopp::interaction::DihedralUniquePotential.
Definition at line 230 of file DihedralUniquePotential.hpp.
d()
real espressopp::interaction::DihedralHarmonicUniqueCos::d (int i, int j) const inline
Definition at line 48 of file DihedralHarmonicUniqueCos.hpp.
Referenced by _computeForceRaw(), and prod().
derived_this() [1/2]
DihedralHarmonicUniqueCos * espressopp::interaction::DihedralUniquePotentialTemplate< DihedralHarmonicUniqueCos >::derived_this () inline protected inherited
Definition at line 107 of file DihedralUniquePotential.hpp.
derived_this() [2/2]
const DihedralHarmonicUniqueCos * espressopp::interaction::DihedralUniquePotentialTemplate< DihedralHarmonicUniqueCos >::derived_this () const inline protected inherited
Definition at line 111 of file DihedralUniquePotential.hpp.
References espressopp::interaction::DihedralUniquePotentialTemplate< Derived >::DihedralUniquePotentialTemplate().
getCutoff()
real espressopp::interaction::DihedralUniquePotentialTemplate< DihedralHarmonicUniqueCos >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::DihedralUniquePotential.
Definition at line 138 of file DihedralUniquePotential.hpp.
getK()
real espressopp::interaction::DihedralHarmonicUniqueCos::getK () const inline
Definition at line 45 of file DihedralHarmonicUniqueCos.hpp.
References K.
Referenced by registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::DihedralUniquePotential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
prod()
Real3D espressopp::interaction::DihedralHarmonicUniqueCos::prod (Real3D a, Real3D b) const inline
Definition at line 55 of file DihedralHarmonicUniqueCos.hpp.
References d().
Referenced by _computeForceRaw().
registerPython()
void espressopp::interaction::DihedralHarmonicUniqueCos::registerPython () static
Definition at line 33 of file DihedralHarmonicUniqueCos.cpp.
References getK(), and setK().
Referenced by espressopp::interaction::registerPython().
setCutoff()
void espressopp::interaction::DihedralUniquePotentialTemplate< DihedralHarmonicUniqueCos >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::DihedralUniquePotential.
Definition at line 130 of file DihedralUniquePotential.hpp.
setK()
void espressopp::interaction::DihedralHarmonicUniqueCos::setK (real _K) inline
Definition at line 44 of file DihedralHarmonicUniqueCos.hpp.
Referenced by registerPython().
Member Data Documentation
cutoff
real espressopp::interaction::DihedralUniquePotentialTemplate< DihedralHarmonicUniqueCos >::cutoff protected inherited
Definition at line 104 of file DihedralUniquePotential.hpp.
cutoffSqr
real espressopp::interaction::DihedralUniquePotentialTemplate< DihedralHarmonicUniqueCos >::cutoffSqr protected inherited
Definition at line 105 of file DihedralUniquePotential.hpp.
K
real espressopp::interaction::DihedralHarmonicUniqueCos::K private
Definition at line 37 of file DihedralHarmonicUniqueCos.hpp.
Referenced by getK().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/DihedralHarmonicUniqueCos.hpp
/home/espressopp/espressopp/src/interaction/DihedralHarmonicUniqueCos.cpp