ESPResSo++: espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential > Class Template Reference
espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential > Class Template Reference
#include <FixedLocalTupleRgListInteractionTemplate.hpp>
Public Member Functions
FixedLocalTupleRgListInteractionTemplate (shared_ptr< System > _system, shared_ptr< FixedLocalTupleList > _fixedtupleList, shared_ptr< Potential > _potential)
virtual ~FixedLocalTupleRgListInteractionTemplate ()
void setRG (longint id, const real rg)
void setFixedLocalTupleList (shared_ptr< FixedLocalTupleList > _fixedtupleList)
shared_ptr< FixedLocalTupleList > getFixedLocalTupleList ()
void setPotential (shared_ptr< Potential > _potential)
shared_ptr< Potential > getPotential ()
virtual void addForces ()
virtual real computeEnergy ()
virtual real computeEnergyDeriv ()
virtual real computeEnergyAA ()
virtual real computeEnergyCG ()
virtual real computeEnergyAA (int atomtype)
virtual real computeEnergyCG (int atomtype)
virtual void computeVirialX (std::vector< real > &p_xx_total, int bins)
virtual real computeVirial ()
virtual void computeVirialTensor (Tensor &w)
virtual void computeVirialTensor (Tensor &w, real z)
virtual void computeVirialTensor (Tensor *w, int n)
virtual real getMaxCutoff ()
This method returns the maximal cutoff defined for one type pair.
virtual int bondType ()
Static Public Member Functions
static void registerPython ()
Protected Types
typedef _Potential Potential
Protected Member Functions
boost::unordered_map< long unsigned int, Real3D > computeCenter ()
boost::unordered_map< long unsigned int, real > computeRG (boost::unordered_map< long unsigned int, Real3D > center)
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Protected Attributes
int ntypes
shared_ptr< FixedLocalTupleList > fixedtupleList
shared_ptr< Potential > potential
Private Member Functions
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Private Attributes
long unsigned int num_of_part
long unsigned int num_of_subchain
boost::unordered_map< long unsigned int, real > rg_origin
int N_Constrain
Detailed Description
template<typename _Potential>
class espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >
Definition at line 42 of file FixedLocalTupleRgListInteractionTemplate.hpp.
Member Typedef Documentation
Potential
template<typename _Potential > typedef _Potential espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::Potential protected
Definition at line 45 of file FixedLocalTupleRgListInteractionTemplate.hpp.
Constructor & Destructor Documentation
FixedLocalTupleRgListInteractionTemplate()
template<typename _Potential > espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate (shared_ptr< System > _system, shared_ptr< FixedLocalTupleList > _fixedtupleList, shared_ptr< Potential > _potential) inline
Definition at line 56 of file FixedLocalTupleRgListInteractionTemplate.hpp.
References espressopp::System::comm, espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::fixedtupleList, espressopp::SystemAccess::getSystemRef(), espressopp::Particle::id(), LOG4ESPP_ERROR, espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::N_Constrain, espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::num_of_subchain, espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::potential, espressopp::esutil::Error::setException(), and espressopp::System::storage.
~FixedLocalTupleRgListInteractionTemplate()
template<typename _Potential > virtual espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::~FixedLocalTupleRgListInteractionTemplate () inline virtual
Definition at line 163 of file FixedLocalTupleRgListInteractionTemplate.hpp.
Member Function Documentation
addForces()
template<typename _Potential > void espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::addForces () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 278 of file FixedLocalTupleRgListInteractionTemplate.hpp.
References espressopp::System::bc, espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::fixedtupleList, espressopp::Particle::force(), espressopp::bc::BC::getMinimumImageVectorBox(), espressopp::SystemAccess::getSystemRef(), espressopp::Particle::id(), LOG4ESPP_INFO, espressopp::Particle::mass(), espressopp::Particle::position(), and espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::potential.
Referenced by espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::getPotential().
bondType()
template<typename _Potential > virtual int espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::bondType () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 205 of file FixedLocalTupleRgListInteractionTemplate.hpp.
References espressopp::interaction::Nonbonded.
computeCenter()
template<typename _Potential > boost::unordered_map<long unsigned int, Real3D> espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter () inline protected
Definition at line 211 of file FixedLocalTupleRgListInteractionTemplate.hpp.
References espressopp::System::bc, espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::fixedtupleList, espressopp::bc::BC::getMinimumImageVectorBox(), espressopp::SystemAccess::getSystemRef(), espressopp::Particle::id(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::N_Constrain, and espressopp::Particle::position().
Referenced by espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor(), and espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate().
computeEnergy()
template<typename _Potential > real espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeEnergy () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 317 of file FixedLocalTupleRgListInteractionTemplate.hpp.
References espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeEnergyDeriv(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::fixedtupleList, espressopp::Particle::id(), LOG4ESPP_INFO, mpiWorld, and espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::potential.
Referenced by espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::addForces(), and espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::getPotential().
computeEnergyAA() [1/2]
template<typename _Potential > real espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeEnergyAA () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 351 of file FixedLocalTupleRgListInteractionTemplate.hpp.
Referenced by espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeEnergyDeriv(), and espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::getPotential().
computeEnergyAA() [2/2]
template<typename _Potential > real espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeEnergyAA (int atomtype) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 358 of file FixedLocalTupleRgListInteractionTemplate.hpp.
References espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeEnergyCG().
computeEnergyCG() [1/2]
template<typename _Potential > real espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeEnergyCG () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 365 of file FixedLocalTupleRgListInteractionTemplate.hpp.
Referenced by espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeEnergyAA(), and espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::getPotential().
computeEnergyCG() [2/2]
template<typename _Potential > real espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeEnergyCG (int atomtype) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 372 of file FixedLocalTupleRgListInteractionTemplate.hpp.
References espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialX().
computeEnergyDeriv()
template<typename _Potential > real espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeEnergyDeriv () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 344 of file FixedLocalTupleRgListInteractionTemplate.hpp.
References espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeEnergyAA().
Referenced by espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeEnergy(), and espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::getPotential().
computeRG()
template<typename _Potential > boost::unordered_map<long unsigned int, real> espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG (boost::unordered_map< long unsigned int, Real3D > center) inline protected
Definition at line 240 of file FixedLocalTupleRgListInteractionTemplate.hpp.
References espressopp::System::bc, espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::fixedtupleList, espressopp::bc::BC::getMinimumImageVectorBox(), espressopp::SystemAccess::getSystemRef(), espressopp::Particle::id(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::N_Constrain, espressopp::Particle::position(), and espressopp::Real3D::sqr().
Referenced by espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor(), and espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate().
computeVirial()
template<typename _Potential > real espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirial () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 387 of file FixedLocalTupleRgListInteractionTemplate.hpp.
References espressopp::System::bc, espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::fixedtupleList, espressopp::bc::BC::getMinimumImageVectorBox(), espressopp::SystemAccess::getSystemRef(), espressopp::Particle::id(), LOG4ESPP_INFO, espressopp::Particle::mass(), mpiWorld, espressopp::Particle::position(), and espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::potential.
Referenced by espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialX(), and espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::getPotential().
computeVirialTensor() [1/3]
template<typename _Potential > void espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor (Tensor & w) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 429 of file FixedLocalTupleRgListInteractionTemplate.hpp.
References espressopp::System::bc, espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::fixedtupleList, espressopp::bc::BC::getMinimumImageVectorBox(), espressopp::SystemAccess::getSystemRef(), espressopp::Particle::id(), LOG4ESPP_INFO, espressopp::Particle::mass(), mpiWorld, espressopp::Particle::position(), and espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::potential.
Referenced by espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor(), and espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::getPotential().
computeVirialTensor() [2/3]
template<typename _Potential > void espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor (Tensor & w, real z) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 473 of file FixedLocalTupleRgListInteractionTemplate.hpp.
References espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor().
computeVirialTensor() [3/3]
template<typename _Potential > void espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor (Tensor * w, int n) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 480 of file FixedLocalTupleRgListInteractionTemplate.hpp.
computeVirialX()
template<typename _Potential > void espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialX (std::vector< real > & p_xx_total, int bins) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 380 of file FixedLocalTupleRgListInteractionTemplate.hpp.
References espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirial().
Referenced by espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeEnergyCG(), and espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::getPotential().
getFixedLocalTupleList()
template<typename _Potential > shared_ptr< FixedLocalTupleList > espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::getFixedLocalTupleList () inline
Definition at line 175 of file FixedLocalTupleRgListInteractionTemplate.hpp.
References espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::fixedtupleList.
getMaxCutoff()
template<typename _Potential > virtual real espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::getMaxCutoff () inline virtual
This method returns the maximal cutoff defined for one type pair.
Implements espressopp::interaction::Interaction.
Definition at line 204 of file FixedLocalTupleRgListInteractionTemplate.hpp.
getPotential()
template<typename _Potential > shared_ptr< Potential > espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::getPotential () inline
Definition at line 188 of file FixedLocalTupleRgListInteractionTemplate.hpp.
References espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeEnergyAA(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeEnergyCG(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeEnergyDeriv(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialX(), and espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::potential.
getSystem()
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::LatticeBoltzmann::assignMyLattice(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::PIAdressIntegrator::computeKineticEnergy(), espressopp::integrator::PIAdressIntegrator::computeMomentumDrift(), espressopp::integrator::PIAdressIntegrator::computePositionDrift(), espressopp::integrator::PIAdressIntegrator::computeRingEnergy(), espressopp::integrator::PIAdressIntegrator::computeRingEnergyRaw(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpXTCAdress::dump(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::io::DumpXYZ::DumpXYZ(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::VerletListTriple::registerPython(), espressopp::VerletList::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
getSystem1()
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
getSystem2()
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
getSystemRef()
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::addForces(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::addForces(), espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerletRESPA::calcForces(), espressopp::integrator::VelocityVerlet::calcForces(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::PIAdressIntegrator::calcForcesF(), espressopp::integrator::PIAdressIntegrator::calcForcesM(), espressopp::integrator::PIAdressIntegrator::calcForcesS(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeCOM(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeEnergy(), espressopp::integrator::PIAdressIntegrator::computeKineticEnergy(), espressopp::integrator::PIAdressIntegrator::computeMomentumDrift(), espressopp::integrator::PIAdressIntegrator::computePositionDrift(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::integrator::PIAdressIntegrator::computeRingEnergy(), espressopp::integrator::PIAdressIntegrator::computeRingEnergyRaw(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::PIAdressIntegrator::distributeForces(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::FixedLocalTupleComListInteractionTemplate(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::VelocityVerletRESPA::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerlet::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::PIAdressIntegrator::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::PIAdressIntegrator::initializeSetup(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::VelocityVerletRESPA::integrate1(), espressopp::integrator::VelocityVerlet::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::VelocityVerletRESPA::integrate2(), espressopp::integrator::VelocityVerlet::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::PIAdressIntegrator::integrateModePos(), espressopp::integrator::Adress::integrateSlow(), espressopp::integrator::PIAdressIntegrator::integrateV1(), espressopp::integrator::PIAdressIntegrator::integrateV2(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::PIAdressIntegrator::OUintegrate(), espressopp::integrator::VelocityVerlet::printForces(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerlet::printPositions(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::PIAdressIntegrator::run(), espressopp::integrator::VelocityVerletRESPA::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::MinimizeEnergy::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::Rattle::saveOldPos(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::PIAdressIntegrator::setWeights(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostatOnGroup::thermalize(), espressopp::integrator::LangevinThermostatOnRadius::thermalize(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::integrator::PIAdressIntegrator::transForces(), espressopp::integrator::PIAdressIntegrator::transMom1(), espressopp::integrator::PIAdressIntegrator::transMom2(), espressopp::integrator::PIAdressIntegrator::transPos1(), espressopp::integrator::PIAdressIntegrator::transPos2(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::io::DumpH5MD::update(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::VelocityVerletRESPA::updateForces(), espressopp::integrator::VelocityVerlet::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::PIAdressIntegrator::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
getSystemRef1()
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
getSystemRef2()
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Interaction::LOG4ESPP_DECL_LOGGER (theLogger) static protected inherited
Logger.
Referenced by espressopp::interaction::Interaction::~Interaction().
registerPython()
void espressopp::interaction::Interaction::registerPython () static inherited
Definition at line 36 of file Interaction.cpp.
References espressopp::interaction::Interaction::bondType(), espressopp::interaction::Interaction::computeEnergy(), espressopp::interaction::Interaction::computeEnergyAA(), espressopp::interaction::Interaction::computeEnergyCG(), espressopp::interaction::Interaction::computeEnergyDeriv(), and espressopp::interaction::Interaction::computeVirial().
Referenced by espressopp::interaction::registerPython(), and espressopp::interaction::Interaction::~Interaction().
setFixedLocalTupleList()
template<typename _Potential > void espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::setFixedLocalTupleList (shared_ptr< FixedLocalTupleList > _fixedtupleList) inline
Definition at line 171 of file FixedLocalTupleRgListInteractionTemplate.hpp.
References espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::fixedtupleList.
setPotential()
template<typename _Potential > void espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::setPotential (shared_ptr< Potential > _potential) inline
Definition at line 180 of file FixedLocalTupleRgListInteractionTemplate.hpp.
References LOG4ESPP_ERROR, and espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::potential.
setRG()
template<typename _Potential > void espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::setRG (longint id, const real rg) inline
Definition at line 166 of file FixedLocalTupleRgListInteractionTemplate.hpp.
Member Data Documentation
fixedtupleList
template<typename _Potential > shared_ptr< FixedLocalTupleList > espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::fixedtupleList protected
Definition at line 270 of file FixedLocalTupleRgListInteractionTemplate.hpp.
Referenced by espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::getFixedLocalTupleList(), and espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::setFixedLocalTupleList().
N_Constrain
template<typename _Potential > int espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::N_Constrain private
Definition at line 52 of file FixedLocalTupleRgListInteractionTemplate.hpp.
Referenced by espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), and espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate().
ntypes
template<typename _Potential > int espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::ntypes protected
Definition at line 269 of file FixedLocalTupleRgListInteractionTemplate.hpp.
num_of_part
template<typename _Potential > long unsigned int espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::num_of_part private
Definition at line 48 of file FixedLocalTupleRgListInteractionTemplate.hpp.
num_of_subchain
template<typename _Potential > long unsigned int espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::num_of_subchain private
Definition at line 49 of file FixedLocalTupleRgListInteractionTemplate.hpp.
Referenced by espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate().
potential
template<typename _Potential > shared_ptr< Potential > espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::potential protected
Definition at line 271 of file FixedLocalTupleRgListInteractionTemplate.hpp.
Referenced by espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::getPotential(), and espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::setPotential().
rg_origin
template<typename _Potential > boost::unordered_map<long unsigned int, real> espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::rg_origin private
Definition at line 50 of file FixedLocalTupleRgListInteractionTemplate.hpp.
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/interaction/FixedLocalTupleRgListInteractionTemplate.hpp