ESPResSo++: espressopp::integrator::LBInitPeriodicForce Class Reference
espressopp::integrator::LBInitPeriodicForce Class Reference
#include <LBInitPeriodicForce.hpp>
Public Member Functions
LBInitPeriodicForce (shared_ptr< System > _system, shared_ptr< LatticeBoltzmann > _latticeboltzmann)
void createDenVel (real _rho0, Real3D _u0)
Destructor for output.
void setForce (Real3D _force)
void addForce (Real3D _force)
void printForce (Real3D _force, int _id)
Static Public Member Functions
static void registerPython ()
Protected Attributes
shared_ptr< LatticeBoltzmann > latticeboltzmann
real rho0
Real3D u0
Detailed Description
Definition at line 30 of file LBInitPeriodicForce.hpp.
Constructor & Destructor Documentation
espressopp::integrator::LBInitPeriodicForce::LBInitPeriodicForce (shared_ptr< System > _system, shared_ptr< LatticeBoltzmann > _latticeboltzmann)
Definition at line 30 of file LBInitPeriodicForce.cpp.
Member Function Documentation
void espressopp::integrator::LBInitPeriodicForce::addForce (Real3D _force) [virtual]
Implements espressopp::integrator::LBInit.
Definition at line 83 of file LBInitPeriodicForce.cpp.
References espressopp::Int3D::getItem(), espressopp::Real3D::getItem(), espressopp::integrator::LBInit::latticeboltzmann, M_PI, and printForce().
Referenced by registerPython().
void espressopp::integrator::LBInitPeriodicForce::createDenVel (real _rho0, Real3D _u0) [virtual]
Destructor for output.
Implements espressopp::integrator::LBInit.
Definition at line 36 of file LBInitPeriodicForce.cpp.
void espressopp::integrator::LBInitPeriodicForce::printForce (Real3D _force, int _id)
Definition at line 130 of file LBInitPeriodicForce.cpp.
References espressopp::Real3D::getItem(), and mpiWorld.
Referenced by addForce(), and setForce().
void espressopp::integrator::LBInitPeriodicForce::registerPython () [static]
Reimplemented from espressopp::integrator::LBInit.
Definition at line 161 of file LBInitPeriodicForce.cpp.
References addForce(), and setForce().
Referenced by espressopp::integrator::registerPython().
void espressopp::integrator::LBInitPeriodicForce::setForce (Real3D _force) [virtual]
Implements espressopp::integrator::LBInit.
Definition at line 38 of file LBInitPeriodicForce.cpp.
References espressopp::Int3D::getItem(), espressopp::Real3D::getItem(), espressopp::integrator::LBInit::latticeboltzmann, M_PI, and printForce().
Referenced by registerPython().
Member Data Documentation
shared_ptr<LatticeBoltzmann> espressopp::integrator::LBInit::latticeboltzmann [protected, inherited]
Definition at line 52 of file LBInit.hpp.
Referenced by espressopp::integrator::LBInitConstForce::addForce(), addForce(), espressopp::integrator::LBInitPopWave::createDenVel(), espressopp::integrator::LBInitPopUniform::createDenVel(), espressopp::integrator::LBInit::LBInit(), espressopp::integrator::LBInitConstForce::setForce(), and setForce().
real espressopp::integrator::LBInit::rho0 [protected, inherited]
Definition at line 53 of file LBInit.hpp.
Real3D espressopp::integrator::LBInit::u0 [protected, inherited]
Definition at line 54 of file LBInit.hpp.
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/integrator/LBInitPeriodicForce.hpp
/home/travis/build/espressopp/espressopp/src/integrator/LBInitPeriodicForce.cpp