ESPResSo++: espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential > Class Template Reference
espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential > Class Template Reference
#include <CellListAllParticlesInteractionTemplate.hpp>
Public Member Functions
CellListAllParticlesInteractionTemplate (shared_ptr< storage::Storage > _storage, shared_ptr< Potential > _potential)
shared_ptr< Potential > getPotential ()
virtual void addForces ()
virtual real computeEnergy ()
virtual real computeEnergyDeriv ()
virtual real computeEnergyAA ()
virtual real computeEnergyCG ()
virtual real computeEnergyAA (int atomtype)
virtual real computeEnergyCG (int atomtype)
virtual void computeVirialX (std::vector< real > &p_xx_total, int bins)
virtual real computeVirial ()
virtual void computeVirialTensor (Tensor &wij)
virtual void computeVirialTensor (Tensor &w, real z)
virtual void computeVirialTensor (Tensor *w, int n)
virtual real getMaxCutoff ()
This method returns the maximal cutoff defined for one type pair.
virtual int bondType ()
Static Public Member Functions
static void registerPython ()
Protected Types
typedef _Potential Potential
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Protected Attributes
int ntypes
shared_ptr< storage::Storage > storage
shared_ptr< Potential > potential
Detailed Description
template<typename _Potential>
class espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >
Definition at line 36 of file CellListAllParticlesInteractionTemplate.hpp.
Member Typedef Documentation
Potential
template<typename _Potential > typedef _Potential espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >::Potential protected
Definition at line 38 of file CellListAllParticlesInteractionTemplate.hpp.
Constructor & Destructor Documentation
CellListAllParticlesInteractionTemplate()
template<typename _Potential > espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >::CellListAllParticlesInteractionTemplate (shared_ptr< storage::Storage > _storage, shared_ptr< Potential > _potential) inline
Definition at line 41 of file CellListAllParticlesInteractionTemplate.hpp.
Member Function Documentation
addForces()
template<typename _Potential > void espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >::addForces inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 74 of file CellListAllParticlesInteractionTemplate.hpp.
References LOG4ESPP_INFO.
bondType()
template<typename _Potential > virtual int espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >::bondType () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 61 of file CellListAllParticlesInteractionTemplate.hpp.
References espressopp::interaction::Nonbonded.
computeEnergy()
template<typename _Potential > real espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >::computeEnergy inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 83 of file CellListAllParticlesInteractionTemplate.hpp.
References LOG4ESPP_INFO.
computeEnergyAA() [1/2]
template<typename _Potential > real espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >::computeEnergyAA inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 99 of file CellListAllParticlesInteractionTemplate.hpp.
computeEnergyAA() [2/2]
template<typename _Potential > real espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >::computeEnergyAA (int atomtype) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 106 of file CellListAllParticlesInteractionTemplate.hpp.
computeEnergyCG() [1/2]
template<typename _Potential > real espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >::computeEnergyCG inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 113 of file CellListAllParticlesInteractionTemplate.hpp.
computeEnergyCG() [2/2]
template<typename _Potential > real espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >::computeEnergyCG (int atomtype) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 120 of file CellListAllParticlesInteractionTemplate.hpp.
computeEnergyDeriv()
template<typename _Potential > real espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >::computeEnergyDeriv inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 92 of file CellListAllParticlesInteractionTemplate.hpp.
computeVirial()
template<typename _Potential > real espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >::computeVirial inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 134 of file CellListAllParticlesInteractionTemplate.hpp.
References LOG4ESPP_INFO.
computeVirialTensor() [1/3]
template<typename _Potential > void espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >::computeVirialTensor (Tensor & w, real z) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 153 of file CellListAllParticlesInteractionTemplate.hpp.
computeVirialTensor() [2/3]
template<typename _Potential > void espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >::computeVirialTensor (Tensor & wij) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 143 of file CellListAllParticlesInteractionTemplate.hpp.
References LOG4ESPP_INFO.
computeVirialTensor() [3/3]
template<typename _Potential > void espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >::computeVirialTensor (Tensor * w, int n) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 160 of file CellListAllParticlesInteractionTemplate.hpp.
computeVirialX()
template<typename _Potential > void espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >::computeVirialX (std::vector< real > & p_xx_total, int bins) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 128 of file CellListAllParticlesInteractionTemplate.hpp.
getMaxCutoff()
template<typename _Potential > virtual real espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >::getMaxCutoff () inline virtual
This method returns the maximal cutoff defined for one type pair.
Implements espressopp::interaction::Interaction.
Definition at line 60 of file CellListAllParticlesInteractionTemplate.hpp.
getPotential()
template<typename _Potential > shared_ptr< Potential > espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >::getPotential () inline
Definition at line 44 of file CellListAllParticlesInteractionTemplate.hpp.
References espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >::potential.
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Interaction::LOG4ESPP_DECL_LOGGER (theLogger) static protected inherited
Logger.
registerPython()
void espressopp::interaction::Interaction::registerPython () static inherited
Definition at line 36 of file Interaction.cpp.
References espressopp::interaction::Interaction::bondType(), espressopp::interaction::Interaction::computeEnergy(), espressopp::interaction::Interaction::computeEnergyAA(), espressopp::interaction::Interaction::computeEnergyCG(), espressopp::interaction::Interaction::computeEnergyDeriv(), and espressopp::interaction::Interaction::computeVirial().
Referenced by espressopp::interaction::registerPython().
Member Data Documentation
ntypes
template<typename _Potential > int espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >::ntypes protected
Definition at line 64 of file CellListAllParticlesInteractionTemplate.hpp.
potential
template<typename _Potential > shared_ptr< Potential > espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >::potential protected
Definition at line 66 of file CellListAllParticlesInteractionTemplate.hpp.
Referenced by espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >::getPotential().
storage
template<typename _Potential > shared_ptr< storage::Storage > espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >::storage protected
Definition at line 65 of file CellListAllParticlesInteractionTemplate.hpp.
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/interaction/CellListAllParticlesInteractionTemplate.hpp