ESPResSo++: espressopp::interaction::LennardJonesGromacs Class Reference
espressopp::interaction::LennardJonesGromacs Class Reference abstract
#include <LennardJonesGromacs.hpp>
Public Member Functions
LennardJonesGromacs ()
LennardJonesGromacs (real _epsilon, real _sigma, real _r1, real _cutoff, real _shift)
LennardJonesGromacs (real _epsilon, real _sigma, real _r1, real _cutoff)
void preset1 ()
void preset2 ()
void setEpsilon (real _epsilon)
real getEpsilon () const
void setSigma (real _sigma)
real getSigma () const
void setR1 (real _r1)
real getR1 () const
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &dist, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual real getCutoff () const =0
virtual void setShift (real _shift)
virtual real getShift () const
virtual real getShift () const =0
virtual real setAutoShift ()
void updateAutoShift ()
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)
virtual shared_ptr< FixedPairList > getColVarBondList () const
virtual shared_ptr< FixedPairList > getColVarBondList () const =0
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &fpl)
virtual shared_ptr< FixedTripleList > getColVarAngleList () const
virtual shared_ptr< FixedTripleList > getColVarAngleList () const =0
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fpl)
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const =0
virtual void setColVar (const RealND &cv)
virtual void setColVar (const Real3D &dist, const bc::BC &bc)
virtual RealND getColVar () const
virtual RealND getColVar () const =0
virtual void computeColVarWeights (const Real3D &dist, const bc::BC &bc)
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
real _computeEnergyDeriv (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
LennardJonesGromacs * derived_this ()
const LennardJonesGromacs * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
shared_ptr< FixedPairList > colVarBondList
shared_ptr< FixedTripleList > colVarAngleList
shared_ptr< FixedQuadrupleList > colVarDihedList
RealND colVar
Private Attributes
real epsilon
real sigma
real ff1
real ff2
real ef1
real ef2
real r1
real r1sq
real A12
real B12
real C12
real A6
real B6
real C6
real ljsw1
real ljsw2
real ljsw3
real ljsw4
real ljsw5
Detailed Description
Definition at line 32 of file LennardJonesGromacs.hpp.
Constructor & Destructor Documentation
LennardJonesGromacs() [1/3]
espressopp::interaction::LennardJonesGromacs::LennardJonesGromacs () inline
Definition at line 54 of file LennardJonesGromacs.hpp.
References A12, A6, B12, B6, C12, C6, espressopp::infinity, ljsw1, ljsw2, ljsw3, ljsw4, ljsw5, preset1(), r1sq, espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::setCutoff(), and espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::setShift().
LennardJonesGromacs() [2/3]
espressopp::interaction::LennardJonesGromacs::LennardJonesGromacs (real _epsilon, real _sigma, real _r1, real _cutoff, real _shift) inline
Definition at line 73 of file LennardJonesGromacs.hpp.
References preset1(), preset2(), espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::setCutoff(), and espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::setShift().
LennardJonesGromacs() [3/3]
espressopp::interaction::LennardJonesGromacs::LennardJonesGromacs (real _epsilon, real _sigma, real _r1, real _cutoff) inline
Definition at line 81 of file LennardJonesGromacs.hpp.
References espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::autoShift, preset1(), preset2(), espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::setAutoShift(), and espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::setCutoff().
Member Function Documentation
_computeEnergy() [1/4]
real espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::_computeEnergy (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 352 of file Potential.hpp.
_computeEnergy() [2/4]
real espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 360 of file Potential.hpp.
_computeEnergy() [3/4]
real espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::_computeEnergy (const Real3D & dist) const inline inherited
Definition at line 367 of file Potential.hpp.
_computeEnergy() [4/4]
real espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::_computeEnergy (real dist) const inline inherited
Definition at line 374 of file Potential.hpp.
_computeEnergyDeriv()
real espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::_computeEnergyDeriv (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 395 of file Potential.hpp.
_computeEnergySqr()
real espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::_computeEnergySqr (real distSqr) const inline inherited
Definition at line 381 of file Potential.hpp.
_computeEnergySqrRaw()
real espressopp::interaction::LennardJonesGromacs::_computeEnergySqrRaw (real distSqr) const inline
Definition at line 151 of file LennardJonesGromacs.hpp.
References epsilon, ljsw3, ljsw4, ljsw5, r1, r1sq, and sigma.
_computeForce() [1/3]
bool espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const inline inherited
Definition at line 423 of file Potential.hpp.
_computeForce() [2/3]
bool espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 431 of file Potential.hpp.
_computeForce() [3/3]
bool espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::_computeForce (Real3D & force, const Real3D & dist) const inline inherited
Definition at line 438 of file Potential.hpp.
_computeForceRaw()
bool espressopp::interaction::LennardJonesGromacs::_computeForceRaw (Real3D & force, const Real3D & dist, real distSqr) const inline
Definition at line 162 of file LennardJonesGromacs.hpp.
References ff1, ff2, ljsw1, ljsw2, r1, and r1sq.
computeColVarWeights()
void espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::computeColVarWeights (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 315 of file Potential.hpp.
computeEnergy() [1/3]
real espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::computeEnergy (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 323 of file Potential.hpp.
computeEnergy() [2/3]
real espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::computeEnergy (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 331 of file Potential.hpp.
computeEnergy() [3/3]
real espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::computeEnergy (real dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 338 of file Potential.hpp.
computeEnergySqr()
real espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::computeEnergySqr (real distsqr) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 345 of file Potential.hpp.
computeForce() [1/2]
Real3D espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::computeForce (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 405 of file Potential.hpp.
computeForce() [2/2]
Real3D espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::computeForce (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 413 of file Potential.hpp.
derived_this() [1/2]
LennardJonesGromacs * espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::derived_this inline protected inherited
Definition at line 161 of file Potential.hpp.
derived_this() [2/2]
const LennardJonesGromacs * espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::derived_this inline protected inherited
Definition at line 165 of file Potential.hpp.
getColVar() [1/2]
RealND espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::getColVar inline virtual inherited
Definition at line 309 of file Potential.hpp.
getColVar() [2/2]
virtual RealND espressopp::interaction::Potential::getColVar () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getColVarAngleList() [1/2]
shared_ptr< FixedTripleList > espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::getColVarAngleList inline virtual inherited
Definition at line 273 of file Potential.hpp.
getColVarAngleList() [2/2]
virtual shared_ptr<FixedTripleList> espressopp::interaction::Potential::getColVarAngleList () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getColVarBondList() [1/2]
shared_ptr< FixedPairList > espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::getColVarBondList inline virtual inherited
Definition at line 259 of file Potential.hpp.
getColVarBondList() [2/2]
virtual shared_ptr<FixedPairList> espressopp::interaction::Potential::getColVarBondList () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getColVarDihedList() [1/2]
shared_ptr< FixedQuadrupleList > espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::getColVarDihedList inline virtual inherited
Definition at line 287 of file Potential.hpp.
getColVarDihedList() [2/2]
virtual shared_ptr<FixedQuadrupleList> espressopp::interaction::Potential::getColVarDihedList () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getCutoff() [1/2]
real espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::getCutoff inline virtual inherited
Definition at line 210 of file Potential.hpp.
getCutoff() [2/2]
virtual real espressopp::interaction::Potential::getCutoff () const pure virtual inherited
Implemented in espressopp::interaction::CoulombKSpaceP3M, and espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getEpsilon()
real espressopp::interaction::LennardJonesGromacs::getEpsilon () const inline
Definition at line 133 of file LennardJonesGromacs.hpp.
References epsilon.
Referenced by espressopp::interaction::LennardJonesGromacs_pickle::getinitargs(), and registerPython().
getR1()
real espressopp::interaction::LennardJonesGromacs::getR1 () const inline
Definition at line 149 of file LennardJonesGromacs.hpp.
References r1.
Referenced by espressopp::interaction::LennardJonesGromacs_pickle::getinitargs(), and registerPython().
getShift() [1/2]
real espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::getShift inline virtual inherited
Definition at line 225 of file Potential.hpp.
getShift() [2/2]
virtual real espressopp::interaction::Potential::getShift () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getSigma()
real espressopp::interaction::LennardJonesGromacs::getSigma () const inline
Definition at line 141 of file LennardJonesGromacs.hpp.
References sigma.
Referenced by espressopp::interaction::LennardJonesGromacs_pickle::getinitargs(), and registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
preset1()
void espressopp::interaction::LennardJonesGromacs::preset1 () inline
Definition at line 90 of file LennardJonesGromacs.hpp.
References ef1, ef2, epsilon, ff1, ff2, r1, r1sq, and sigma.
Referenced by LennardJonesGromacs(), setEpsilon(), setR1(), and setSigma().
preset2()
void espressopp::interaction::LennardJonesGromacs::preset2 () inline
Definition at line 100 of file LennardJonesGromacs.hpp.
References espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::cutoff, ef1, ef2, ff1, ff2, ljsw1, ljsw2, ljsw3, ljsw4, ljsw5, and r1.
Referenced by LennardJonesGromacs(), setEpsilon(), setR1(), and setSigma().
registerPython()
void espressopp::interaction::LennardJonesGromacs::registerPython () static
Definition at line 42 of file LennardJonesGromacs.cpp.
References getEpsilon(), getR1(), getSigma(), setEpsilon(), setR1(), and setSigma().
Referenced by espressopp::interaction::registerPython().
setAutoShift()
real espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::setAutoShift inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 231 of file Potential.hpp.
setColVar() [1/2]
void espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::setColVar (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 301 of file Potential.hpp.
setColVar() [2/2]
void espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::setColVar (const RealND & cv) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 294 of file Potential.hpp.
setColVarAngleList()
void espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::setColVarAngleList (const shared_ptr< FixedTripleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 266 of file Potential.hpp.
setColVarBondList()
void espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::setColVarBondList (const shared_ptr< FixedPairList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 252 of file Potential.hpp.
setColVarDihedList()
void espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 280 of file Potential.hpp.
setCutoff()
void espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 201 of file Potential.hpp.
setEpsilon()
void espressopp::interaction::LennardJonesGromacs::setEpsilon (real _epsilon) inline
Definition at line 127 of file LennardJonesGromacs.hpp.
References epsilon, preset1(), preset2(), and espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::updateAutoShift().
Referenced by registerPython().
setR1()
void espressopp::interaction::LennardJonesGromacs::setR1 (real _r1) inline
Definition at line 143 of file LennardJonesGromacs.hpp.
References preset1(), preset2(), r1, and espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::updateAutoShift().
Referenced by registerPython().
setShift()
void espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::setShift (real _shift) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 216 of file Potential.hpp.
setSigma()
void espressopp::interaction::LennardJonesGromacs::setSigma (real _sigma) inline
Definition at line 135 of file LennardJonesGromacs.hpp.
References preset1(), preset2(), sigma, and espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::updateAutoShift().
Referenced by registerPython().
updateAutoShift()
void espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::updateAutoShift inline inherited
Definition at line 244 of file Potential.hpp.
Member Data Documentation
A12
real espressopp::interaction::LennardJonesGromacs::A12 private
Definition at line 39 of file LennardJonesGromacs.hpp.
Referenced by LennardJonesGromacs().
A6
real espressopp::interaction::LennardJonesGromacs::A6 private
Definition at line 42 of file LennardJonesGromacs.hpp.
Referenced by LennardJonesGromacs().
autoShift
bool espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::autoShift protected inherited
Definition at line 151 of file Potential.hpp.
B12
real espressopp::interaction::LennardJonesGromacs::B12 private
Definition at line 40 of file LennardJonesGromacs.hpp.
Referenced by LennardJonesGromacs().
B6
real espressopp::interaction::LennardJonesGromacs::B6 private
Definition at line 43 of file LennardJonesGromacs.hpp.
Referenced by LennardJonesGromacs().
C12
real espressopp::interaction::LennardJonesGromacs::C12 private
Definition at line 41 of file LennardJonesGromacs.hpp.
Referenced by LennardJonesGromacs().
C6
real espressopp::interaction::LennardJonesGromacs::C6 private
Definition at line 44 of file LennardJonesGromacs.hpp.
Referenced by LennardJonesGromacs().
colVar
RealND espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::colVar protected inherited
Definition at line 159 of file Potential.hpp.
colVarAngleList
shared_ptr<FixedTripleList> espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::colVarAngleList protected inherited
Definition at line 155 of file Potential.hpp.
colVarBondList
shared_ptr<FixedPairList> espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::colVarBondList protected inherited
Definition at line 153 of file Potential.hpp.
colVarDihedList
shared_ptr<FixedQuadrupleList> espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::colVarDihedList protected inherited
Definition at line 157 of file Potential.hpp.
cutoff
real espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::cutoff protected inherited
Definition at line 148 of file Potential.hpp.
cutoffSqr
real espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::cutoffSqr protected inherited
Definition at line 149 of file Potential.hpp.
ef1
real espressopp::interaction::LennardJonesGromacs::ef1 private
Definition at line 37 of file LennardJonesGromacs.hpp.
Referenced by preset1(), and preset2().
ef2
real espressopp::interaction::LennardJonesGromacs::ef2 private
Definition at line 37 of file LennardJonesGromacs.hpp.
Referenced by preset1(), and preset2().
epsilon
real espressopp::interaction::LennardJonesGromacs::epsilon private
Definition at line 34 of file LennardJonesGromacs.hpp.
Referenced by _computeEnergySqrRaw(), getEpsilon(), preset1(), and setEpsilon().
ff1
real espressopp::interaction::LennardJonesGromacs::ff1 private
Definition at line 36 of file LennardJonesGromacs.hpp.
Referenced by _computeForceRaw(), preset1(), and preset2().
ff2
real espressopp::interaction::LennardJonesGromacs::ff2 private
Definition at line 36 of file LennardJonesGromacs.hpp.
Referenced by _computeForceRaw(), preset1(), and preset2().
ljsw1
real espressopp::interaction::LennardJonesGromacs::ljsw1 private
Definition at line 45 of file LennardJonesGromacs.hpp.
Referenced by _computeForceRaw(), LennardJonesGromacs(), and preset2().
ljsw2
real espressopp::interaction::LennardJonesGromacs::ljsw2 private
Definition at line 46 of file LennardJonesGromacs.hpp.
Referenced by _computeForceRaw(), LennardJonesGromacs(), and preset2().
ljsw3
real espressopp::interaction::LennardJonesGromacs::ljsw3 private
Definition at line 47 of file LennardJonesGromacs.hpp.
Referenced by _computeEnergySqrRaw(), LennardJonesGromacs(), and preset2().
ljsw4
real espressopp::interaction::LennardJonesGromacs::ljsw4 private
Definition at line 48 of file LennardJonesGromacs.hpp.
Referenced by _computeEnergySqrRaw(), LennardJonesGromacs(), and preset2().
ljsw5
real espressopp::interaction::LennardJonesGromacs::ljsw5 private
Definition at line 49 of file LennardJonesGromacs.hpp.
Referenced by _computeEnergySqrRaw(), LennardJonesGromacs(), and preset2().
r1
real espressopp::interaction::LennardJonesGromacs::r1 private
Definition at line 38 of file LennardJonesGromacs.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), getR1(), preset1(), preset2(), and setR1().
r1sq
real espressopp::interaction::LennardJonesGromacs::r1sq private
Definition at line 38 of file LennardJonesGromacs.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), LennardJonesGromacs(), and preset1().
shift
real espressopp::interaction::PotentialTemplate< LennardJonesGromacs >::shift protected inherited
Definition at line 150 of file Potential.hpp.
sigma
real espressopp::interaction::LennardJonesGromacs::sigma private
Definition at line 35 of file LennardJonesGromacs.hpp.
Referenced by _computeEnergySqrRaw(), getSigma(), preset1(), and setSigma().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/LennardJonesGromacs.hpp
/home/espressopp/espressopp/src/interaction/LennardJonesGromacs.cpp