ESPResSo++: espressopp::interaction::HarmonicTrap Class Reference
espressopp::interaction::HarmonicTrap Class Reference
This class provides methods to compute forces and energies for an harmonic well potential.
#include <HarmonicTrap.hpp>
Public Member Functions
HarmonicTrap ()
~HarmonicTrap ()
int bondType ()
real getMaxCutoff ()
void setK (real _k)
real getK () const
Real3D getCenter () const
void setCenter (const Real3D &_center)
real _computeEnergyRaw (const Particle &p, const bc::BC &bc) const
bool _computeForceRaw (Real3D &force, const Particle &p, const bc::BC &bc) const
virtual real computeEnergy (const Particle &p, const bc::BC &bc) const
virtual Real3D computeForce (const Particle &p, const bc::BC &bc) const
real _computeEnergy (const Particle &p, const bc::BC &bc) const
bool _computeForce (Real3D &force, const Particle &p, const bc::BC &bc) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
HarmonicTrap * derived_this ()
const HarmonicTrap * derived_this () const
Private Attributes
real k
Real3D center
Detailed Description
This class provides methods to compute forces and energies for an harmonic well potential.
Definition at line 41 of file HarmonicTrap.hpp.
Constructor & Destructor Documentation
HarmonicTrap()
espressopp::interaction::HarmonicTrap::HarmonicTrap () inline
Definition at line 49 of file HarmonicTrap.hpp.
~HarmonicTrap()
espressopp::interaction::HarmonicTrap::~HarmonicTrap () inline
Definition at line 52 of file HarmonicTrap.hpp.
Member Function Documentation
_computeEnergy()
real espressopp::interaction::SingleParticlePotentialTemplate< HarmonicTrap >::_computeEnergy (const Particle & p, const bc::BC & bc) const inline inherited
Definition at line 101 of file SingleParticlePotential.hpp.
_computeEnergyRaw()
real espressopp::interaction::HarmonicTrap::_computeEnergyRaw (const Particle & p, const bc::BC & bc) const inline
Definition at line 65 of file HarmonicTrap.hpp.
References espressopp::bc::BC::getMinimumImageVectorBox(), espressopp::Particle::position(), and espressopp::Real3D::sqr().
_computeForce()
bool espressopp::interaction::SingleParticlePotentialTemplate< HarmonicTrap >::_computeForce (Real3D & force, const Particle & p, const bc::BC & bc) const inline inherited
Definition at line 120 of file SingleParticlePotential.hpp.
_computeForceRaw()
bool espressopp::interaction::HarmonicTrap::_computeForceRaw (Real3D & force, const Particle & p, const bc::BC & bc) const inline
Definition at line 74 of file HarmonicTrap.hpp.
References espressopp::bc::BC::getMinimumImageVectorBox(), and espressopp::Particle::position().
bondType()
int espressopp::interaction::HarmonicTrap::bondType () inline
Definition at line 54 of file HarmonicTrap.hpp.
References espressopp::interaction::Single.
computeEnergy()
real espressopp::interaction::SingleParticlePotentialTemplate< HarmonicTrap >::computeEnergy (const Particle & p, const bc::BC & bc) const inline virtual inherited
Implements espressopp::interaction::SingleParticlePotential.
Definition at line 94 of file SingleParticlePotential.hpp.
computeForce()
Real3D espressopp::interaction::SingleParticlePotentialTemplate< HarmonicTrap >::computeForce (const Particle & p, const bc::BC & bc) const inline virtual inherited
Implements espressopp::interaction::SingleParticlePotential.
Definition at line 109 of file SingleParticlePotential.hpp.
derived_this() [1/2]
HarmonicTrap * espressopp::interaction::SingleParticlePotentialTemplate< HarmonicTrap >::derived_this () inline protected inherited
Definition at line 73 of file SingleParticlePotential.hpp.
derived_this() [2/2]
const HarmonicTrap * espressopp::interaction::SingleParticlePotentialTemplate< HarmonicTrap >::derived_this () const inline protected inherited
Definition at line 77 of file SingleParticlePotential.hpp.
getCenter()
Real3D espressopp::interaction::HarmonicTrap::getCenter () const inline
Definition at line 62 of file HarmonicTrap.hpp.
References center.
Referenced by registerPython().
getK()
real espressopp::interaction::HarmonicTrap::getK () const inline
Definition at line 60 of file HarmonicTrap.hpp.
References k.
Referenced by registerPython().
getMaxCutoff()
real espressopp::interaction::HarmonicTrap::getMaxCutoff () inline virtual
Implements espressopp::interaction::SingleParticlePotential.
Definition at line 55 of file HarmonicTrap.hpp.
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::SingleParticlePotential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
registerPython()
void espressopp::interaction::HarmonicTrap::registerPython () static
Definition at line 39 of file HarmonicTrap.cpp.
References getCenter(), getK(), setCenter(), and setK().
Referenced by espressopp::interaction::registerPython().
setCenter()
void espressopp::interaction::HarmonicTrap::setCenter (const Real3D & _center) inline
Definition at line 63 of file HarmonicTrap.hpp.
Referenced by registerPython().
setK()
void espressopp::interaction::HarmonicTrap::setK (real _k) inline
Definition at line 57 of file HarmonicTrap.hpp.
Referenced by registerPython().
Member Data Documentation
center
Real3D espressopp::interaction::HarmonicTrap::center private
Definition at line 44 of file HarmonicTrap.hpp.
Referenced by getCenter().
k
real espressopp::interaction::HarmonicTrap::k private
Definition at line 43 of file HarmonicTrap.hpp.
Referenced by getK().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/HarmonicTrap.hpp
/home/espressopp/espressopp/src/interaction/HarmonicTrap.cpp