ESPResSo++: espressopp::interaction::PotentialUniqueDistTemplate< Derived > Class Template Reference
espressopp::interaction::PotentialUniqueDistTemplate< Derived > Class Template Reference
Provides a template for the simple implementation of a shifted, absolute distance dependent PotentialUniqueDist with cutoff.
#include <PotentialUniqueDist.hpp>
Public Member Functions
PotentialUniqueDistTemplate ()
virtual ~PotentialUniqueDistTemplate ()
virtual real computeEnergy (const Particle &p1, const Particle &p2, const real curDist) const
virtual real computeEnergy (const Real3D &r21, const real curDist) const
virtual real computeEnergy (real dist, real curDist) const
virtual real computeEnergySqr (real distsqr, real curDist) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2, const real curDist) const
virtual Real3D computeForce (const Real3D &r21, const real curDist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
real _computeEnergy (const Particle &p1, const Particle &p2, const real curDist) const
real _computeEnergy (const Real3D &r21, const real curDist) const
real _computeEnergy (real dist, real curDist) const
real _computeEnergySqr (real distSqr, real curDist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const real curDist) const
bool _computeForce (Real3D &force, const Real3D &dist, const real curDist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
Derived * derived_this ()
const Derived * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
Detailed Description
template<class Derived>
class espressopp::interaction::PotentialUniqueDistTemplate< Derived >
Provides a template for the simple implementation of a shifted, absolute distance dependent PotentialUniqueDist with cutoff.
Definition at line 68 of file PotentialUniqueDist.hpp.
Constructor & Destructor Documentation
PotentialUniqueDistTemplate()
template<class Derived > espressopp::interaction::PotentialUniqueDistTemplate< Derived >::PotentialUniqueDistTemplate () inline
Definition at line 121 of file PotentialUniqueDist.hpp.
~PotentialUniqueDistTemplate()
template<class Derived> virtual espressopp::interaction::PotentialUniqueDistTemplate< Derived >::~PotentialUniqueDistTemplate () inline virtual
Definition at line 71 of file PotentialUniqueDist.hpp.
Member Function Documentation
_computeEnergy() [1/3]
template<class Derived > real espressopp::interaction::PotentialUniqueDistTemplate< Derived >::_computeEnergy (const Particle & p1, const Particle & p2, const real curDist) const inline
Definition at line 208 of file PotentialUniqueDist.hpp.
_computeEnergy() [2/3]
template<class Derived > real espressopp::interaction::PotentialUniqueDistTemplate< Derived >::_computeEnergy (const Real3D & r21, const real curDist) const inline
Definition at line 216 of file PotentialUniqueDist.hpp.
_computeEnergy() [3/3]
template<class Derived > real espressopp::interaction::PotentialUniqueDistTemplate< Derived >::_computeEnergy (real dist, real curDist) const inline
Definition at line 223 of file PotentialUniqueDist.hpp.
_computeEnergySqr()
template<class Derived > real espressopp::interaction::PotentialUniqueDistTemplate< Derived >::_computeEnergySqr (real distSqr, real curDist) const inline
Definition at line 230 of file PotentialUniqueDist.hpp.
_computeForce() [1/2]
template<class Derived > bool espressopp::interaction::PotentialUniqueDistTemplate< Derived >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const real curDist) const inline
Definition at line 262 of file PotentialUniqueDist.hpp.
_computeForce() [2/2]
template<class Derived > bool espressopp::interaction::PotentialUniqueDistTemplate< Derived >::_computeForce (Real3D & force, const Real3D & dist, const real curDist) const inline
Definition at line 270 of file PotentialUniqueDist.hpp.
computeEnergy() [1/3]
template<class Derived > real espressopp::interaction::PotentialUniqueDistTemplate< Derived >::computeEnergy (const Particle & p1, const Particle & p2, const real curDist) const inline virtual
Implements espressopp::interaction::PotentialUniqueDist.
Definition at line 179 of file PotentialUniqueDist.hpp.
computeEnergy() [2/3]
template<class Derived > real espressopp::interaction::PotentialUniqueDistTemplate< Derived >::computeEnergy (const Real3D & r21, const real curDist) const inline virtual
Implements espressopp::interaction::PotentialUniqueDist.
Definition at line 187 of file PotentialUniqueDist.hpp.
computeEnergy() [3/3]
template<class Derived > real espressopp::interaction::PotentialUniqueDistTemplate< Derived >::computeEnergy (real dist, real curDist) const inline virtual
Implements espressopp::interaction::PotentialUniqueDist.
Definition at line 194 of file PotentialUniqueDist.hpp.
computeEnergySqr()
template<class Derived > real espressopp::interaction::PotentialUniqueDistTemplate< Derived >::computeEnergySqr (real distsqr, real curDist) const inline virtual
Implements espressopp::interaction::PotentialUniqueDist.
Definition at line 201 of file PotentialUniqueDist.hpp.
computeForce() [1/2]
template<class Derived > Real3D espressopp::interaction::PotentialUniqueDistTemplate< Derived >::computeForce (const Particle & p1, const Particle & p2, const real curDist) const inline virtual
Implements espressopp::interaction::PotentialUniqueDist.
Definition at line 244 of file PotentialUniqueDist.hpp.
computeForce() [2/2]
template<class Derived > Real3D espressopp::interaction::PotentialUniqueDistTemplate< Derived >::computeForce (const Real3D & r21, const real curDist) const inline virtual
Implements espressopp::interaction::PotentialUniqueDist.
Definition at line 252 of file PotentialUniqueDist.hpp.
derived_this() [1/2]
template<class Derived> Derived* espressopp::interaction::PotentialUniqueDistTemplate< Derived >::derived_this () inline protected
Definition at line 105 of file PotentialUniqueDist.hpp.
derived_this() [2/2]
template<class Derived> const Derived* espressopp::interaction::PotentialUniqueDistTemplate< Derived >::derived_this () const inline protected
Definition at line 109 of file PotentialUniqueDist.hpp.
getCutoff()
template<class Derived > real espressopp::interaction::PotentialUniqueDistTemplate< Derived >::getCutoff () const inline virtual
Implements espressopp::interaction::PotentialUniqueDist.
Definition at line 135 of file PotentialUniqueDist.hpp.
getShift()
template<class Derived > real espressopp::interaction::PotentialUniqueDistTemplate< Derived >::getShift () const inline virtual
Implements espressopp::interaction::PotentialUniqueDist.
Definition at line 149 of file PotentialUniqueDist.hpp.
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::PotentialUniqueDist::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
Referenced by espressopp::interaction::PotentialUniqueDist::~PotentialUniqueDist().
registerPython()
void espressopp::interaction::PotentialUniqueDist::registerPython () static inherited
Definition at line 35 of file PotentialUniqueDist.cpp.
References espressopp::interaction::PotentialUniqueDist::computeEnergy(), espressopp::interaction::PotentialUniqueDist::computeForce(), espressopp::interaction::PotentialUniqueDist::getCutoff(), espressopp::interaction::PotentialUniqueDist::getShift(), espressopp::interaction::PotentialUniqueDist::setAutoShift(), espressopp::interaction::PotentialUniqueDist::setCutoff(), and espressopp::interaction::PotentialUniqueDist::setShift().
Referenced by espressopp::interaction::registerPython(), and espressopp::interaction::PotentialUniqueDist::~PotentialUniqueDist().
setAutoShift()
template<class Derived > real espressopp::interaction::PotentialUniqueDistTemplate< Derived >::setAutoShift () inline virtual
Implements espressopp::interaction::PotentialUniqueDist.
Definition at line 155 of file PotentialUniqueDist.hpp.
setCutoff()
template<class Derived > void espressopp::interaction::PotentialUniqueDistTemplate< Derived >::setCutoff (real _cutoff) inline virtual
Implements espressopp::interaction::PotentialUniqueDist.
Definition at line 127 of file PotentialUniqueDist.hpp.
setShift()
template<class Derived > void espressopp::interaction::PotentialUniqueDistTemplate< Derived >::setShift (real _shift) inline virtual
Implements espressopp::interaction::PotentialUniqueDist.
Definition at line 141 of file PotentialUniqueDist.hpp.
updateAutoShift()
template<class Derived > void espressopp::interaction::PotentialUniqueDistTemplate< Derived >::updateAutoShift () inline
Definition at line 171 of file PotentialUniqueDist.hpp.
Member Data Documentation
autoShift
template<class Derived> bool espressopp::interaction::PotentialUniqueDistTemplate< Derived >::autoShift protected
Definition at line 103 of file PotentialUniqueDist.hpp.
cutoff
template<class Derived> real espressopp::interaction::PotentialUniqueDistTemplate< Derived >::cutoff protected
Definition at line 100 of file PotentialUniqueDist.hpp.
cutoffSqr
template<class Derived> real espressopp::interaction::PotentialUniqueDistTemplate< Derived >::cutoffSqr protected
Definition at line 101 of file PotentialUniqueDist.hpp.
shift
template<class Derived> real espressopp::interaction::PotentialUniqueDistTemplate< Derived >::shift protected
Definition at line 102 of file PotentialUniqueDist.hpp.
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/interaction/PotentialUniqueDist.hpp