ESPResSo++: espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential > Class Template Reference
espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential > Class Template Reference
#include <FixedTripleListPIadressInteractionTemplate.hpp>
Public Member Functions
FixedTripleListPIadressInteractionTemplate (shared_ptr< System > _system, shared_ptr< FixedTripleList > _fixedtripleList, shared_ptr< FixedTupleListAdress > _fixedtupleList, shared_ptr< Potential > _potential, int _ntrotter, bool _speedup)
virtual ~FixedTripleListPIadressInteractionTemplate ()
void setFixedTripleList (shared_ptr< FixedTripleList > _fixedtripleList)
shared_ptr< FixedTripleList > getFixedTripleList ()
void setFixedTupleList (shared_ptr< FixedTupleListAdress > _fixedtupleList)
shared_ptr< FixedTupleListAdress > getFixedTupleList ()
void setNTrotter (int _ntrotter)
int getNTrotter ()
void setSpeedup (bool _speedup)
bool getSpeedup ()
void setPotential (shared_ptr< Potential > _potential)
shared_ptr< Potential > getPotential ()
virtual void addForces ()
virtual real computeEnergy ()
virtual real computeEnergyDeriv ()
virtual real computeEnergyAA ()
virtual real computeEnergyCG ()
virtual real computeEnergyAA (int atomtype)
virtual real computeEnergyCG (int atomtype)
virtual void computeVirialX (std::vector< real > &p_xx_total, int bins)
virtual real computeVirial ()
virtual void computeVirialTensor (Tensor &w)
virtual void computeVirialTensor (Tensor &w, real z)
virtual void computeVirialTensor (Tensor *w, int n)
virtual real getMaxCutoff ()
This method returns the maximal cutoff defined for one type pair.
virtual int bondType ()
Static Public Member Functions
static void registerPython ()
Protected Types
typedef _AngularPotential Potential
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Protected Attributes
int ntypes
int ntrotter
bool speedup
shared_ptr< FixedTripleList > fixedtripleList
shared_ptr< FixedTupleListAdress > fixedtupleList
shared_ptr< Potential > potential
Private Member Functions
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Detailed Description
template<typename _AngularPotential>
class espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >
Definition at line 41 of file FixedTripleListPIadressInteractionTemplate.hpp.
Member Typedef Documentation
Potential
template<typename _AngularPotential > typedef _AngularPotential espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::Potential protected
Definition at line 44 of file FixedTripleListPIadressInteractionTemplate.hpp.
Constructor & Destructor Documentation
FixedTripleListPIadressInteractionTemplate()
template<typename _AngularPotential > espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::FixedTripleListPIadressInteractionTemplate (shared_ptr< System > _system, shared_ptr< FixedTripleList > _fixedtripleList, shared_ptr< FixedTupleListAdress > _fixedtupleList, shared_ptr< Potential > _potential, int _ntrotter, bool _speedup) inline
Definition at line 48 of file FixedTripleListPIadressInteractionTemplate.hpp.
References espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::potential.
~FixedTripleListPIadressInteractionTemplate()
template<typename _AngularPotential > virtual espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::~FixedTripleListPIadressInteractionTemplate () inline virtual
Definition at line 62 of file FixedTripleListPIadressInteractionTemplate.hpp.
Member Function Documentation
addForces()
template<typename _AngularPotential > void espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::addForces () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 144 of file FixedTripleListPIadressInteractionTemplate.hpp.
References espressopp::System::bc, espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::fixedtripleList, espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::fixedtupleList, espressopp::Particle::force(), espressopp::bc::BC::getMinimumImageVectorBox(), espressopp::SystemAccess::getSystemRef(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::Particle::lambda(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::ntrotter, espressopp::Particle::pib(), espressopp::Particle::position(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::potential, and espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::speedup.
Referenced by espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::getPotential().
bondType()
template<typename _AngularPotential > virtual int espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::bondType () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 126 of file FixedTripleListPIadressInteractionTemplate.hpp.
References espressopp::interaction::Angular.
computeEnergy()
template<typename _AngularPotential > real espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergy () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 307 of file FixedTripleListPIadressInteractionTemplate.hpp.
References espressopp::System::bc, espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergyDeriv(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::fixedtripleList, espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::fixedtupleList, espressopp::bc::BC::getMinimumImageVector(), espressopp::SystemAccess::getSystemRef(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::Particle::lambda(), mpiWorld, espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::ntrotter, espressopp::Particle::pib(), espressopp::Particle::position(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::potential, and espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::speedup.
Referenced by espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::addForces(), and espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::getPotential().
computeEnergyAA() [1/2]
template<typename _AngularPotential > real espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergyAA () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 458 of file FixedTripleListPIadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergyDeriv(), and espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::getPotential().
computeEnergyAA() [2/2]
template<typename _AngularPotential > real espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergyAA (int atomtype) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 465 of file FixedTripleListPIadressInteractionTemplate.hpp.
References espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergyCG().
computeEnergyCG() [1/2]
template<typename _AngularPotential > real espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergyCG () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 472 of file FixedTripleListPIadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergyAA(), and espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::getPotential().
computeEnergyCG() [2/2]
template<typename _AngularPotential > real espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergyCG (int atomtype) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 479 of file FixedTripleListPIadressInteractionTemplate.hpp.
References espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirialX().
computeEnergyDeriv()
template<typename _AngularPotential > real espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergyDeriv () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 451 of file FixedTripleListPIadressInteractionTemplate.hpp.
References espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergyAA().
Referenced by espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergy(), and espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::getPotential().
computeVirial()
template<typename _AngularPotential > real espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirial () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 494 of file FixedTripleListPIadressInteractionTemplate.hpp.
References espressopp::System::bc, espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::fixedtripleList, espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::fixedtupleList, espressopp::bc::BC::getMinimumImageVectorBox(), espressopp::SystemAccess::getSystemRef(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::Particle::lambda(), mpiWorld, espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::ntrotter, espressopp::Particle::pib(), espressopp::Particle::position(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::potential, and espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::speedup.
Referenced by espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirialX(), and espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::getPotential().
computeVirialTensor() [1/3]
template<typename _AngularPotential > void espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirialTensor (Tensor & w) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 655 of file FixedTripleListPIadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirialTensor(), and espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::getPotential().
computeVirialTensor() [2/3]
template<typename _AngularPotential > void espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirialTensor (Tensor & w, real z) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 662 of file FixedTripleListPIadressInteractionTemplate.hpp.
References espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirialTensor().
computeVirialTensor() [3/3]
template<typename _AngularPotential > void espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirialTensor (Tensor * w, int n) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 669 of file FixedTripleListPIadressInteractionTemplate.hpp.
References espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::getMaxCutoff().
computeVirialX()
template<typename _AngularPotential > void espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirialX (std::vector< real > & p_xx_total, int bins) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 487 of file FixedTripleListPIadressInteractionTemplate.hpp.
References espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirial().
Referenced by espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergyCG(), and espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::getPotential().
getFixedTripleList()
template<typename _AngularPotential > shared_ptr< FixedTripleList > espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::getFixedTripleList () inline
Definition at line 69 of file FixedTripleListPIadressInteractionTemplate.hpp.
References espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::fixedtripleList.
getFixedTupleList()
template<typename _AngularPotential > shared_ptr< FixedTupleListAdress > espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::getFixedTupleList () inline
Definition at line 78 of file FixedTripleListPIadressInteractionTemplate.hpp.
References espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::fixedtupleList.
getMaxCutoff()
template<typename _AngularPotential > real espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::getMaxCutoff () inline virtual
This method returns the maximal cutoff defined for one type pair.
Implements espressopp::interaction::Interaction.
Definition at line 677 of file FixedTripleListPIadressInteractionTemplate.hpp.
References espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::potential.
Referenced by espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirialTensor(), and espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::getPotential().
getNTrotter()
template<typename _AngularPotential > int espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::getNTrotter () inline
Definition at line 87 of file FixedTripleListPIadressInteractionTemplate.hpp.
References espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::ntrotter.
getPotential()
template<typename _AngularPotential > shared_ptr< Potential > espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::getPotential () inline
Definition at line 109 of file FixedTripleListPIadressInteractionTemplate.hpp.
References espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergyAA(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergyCG(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergyDeriv(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirialX(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::getMaxCutoff(), and espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::potential.
getSpeedup()
template<typename _AngularPotential > bool espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::getSpeedup () inline
Definition at line 96 of file FixedTripleListPIadressInteractionTemplate.hpp.
References espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::speedup.
getSystem()
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::VerletList::_rebuildUsingBuffers(), espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::LatticeBoltzmann::assignMyLattice(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::vectorization::Vectorization::befCalcForces(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::PIAdressIntegrator::computeKineticEnergy(), espressopp::integrator::PIAdressIntegrator::computeMomentumDrift(), espressopp::integrator::PIAdressIntegrator::computePositionDrift(), espressopp::integrator::PIAdressIntegrator::computeRingEnergy(), espressopp::integrator::PIAdressIntegrator::computeRingEnergyRaw(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::vectorization::Vectorization::connect(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::vectorization::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpXTCAdress::dump(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::io::DumpXYZ::DumpXYZ(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::vectorization::VerletList::rebuild(), espressopp::vectorization::VerletList::rebuild_p_nc_pack_stencil(), espressopp::vectorization::VerletList::rebuildPairs(), espressopp::VerletListTriple::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::VerletList::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::vectorization::VerletList::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::vectorization::Vectorization::resetCells(), espressopp::vectorization::Vectorization::resetParticles(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::vectorization::Vectorization::updateForces(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
getSystem1()
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
getSystem2()
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
getSystemRef()
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::addForces(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::addForces(), espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerletRESPA::calcForces(), espressopp::integrator::VelocityVerlet::calcForces(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::PIAdressIntegrator::calcForcesF(), espressopp::integrator::PIAdressIntegrator::calcForcesM(), espressopp::integrator::PIAdressIntegrator::calcForcesS(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeCOM(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeEnergy(), espressopp::integrator::PIAdressIntegrator::computeKineticEnergy(), espressopp::integrator::PIAdressIntegrator::computeMomentumDrift(), espressopp::integrator::PIAdressIntegrator::computePositionDrift(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::integrator::PIAdressIntegrator::computeRingEnergy(), espressopp::integrator::PIAdressIntegrator::computeRingEnergyRaw(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::PIAdressIntegrator::distributeForces(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::FixedLocalTupleComListInteractionTemplate(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::VelocityVerletRESPA::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerlet::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::PIAdressIntegrator::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::PIAdressIntegrator::initializeSetup(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::VelocityVerletRESPA::integrate1(), espressopp::integrator::VelocityVerlet::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::VelocityVerletRESPA::integrate2(), espressopp::integrator::VelocityVerlet::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::PIAdressIntegrator::integrateModePos(), espressopp::integrator::Adress::integrateSlow(), espressopp::integrator::PIAdressIntegrator::integrateV1(), espressopp::integrator::PIAdressIntegrator::integrateV2(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::vectorization::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::PIAdressIntegrator::OUintegrate(), espressopp::integrator::VelocityVerlet::printForces(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerlet::printPositions(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::VelocityVerletRESPA::run(), espressopp::integrator::PIAdressIntegrator::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::MinimizeEnergy::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::Rattle::saveOldPos(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::PIAdressIntegrator::setWeights(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostatOnGroup::thermalize(), espressopp::integrator::LangevinThermostatOnRadius::thermalize(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::vectorization::VerletList::totalSize(), espressopp::integrator::PIAdressIntegrator::transForces(), espressopp::integrator::PIAdressIntegrator::transMom1(), espressopp::integrator::PIAdressIntegrator::transMom2(), espressopp::integrator::PIAdressIntegrator::transPos1(), espressopp::integrator::PIAdressIntegrator::transPos2(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::io::DumpH5MD::update(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::VelocityVerletRESPA::updateForces(), espressopp::integrator::VelocityVerlet::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::PIAdressIntegrator::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
getSystemRef1()
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
getSystemRef2()
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Interaction::LOG4ESPP_DECL_LOGGER (theLogger) static protected inherited
Logger.
Referenced by espressopp::interaction::Interaction::~Interaction().
registerPython()
void espressopp::interaction::Interaction::registerPython () static inherited
Definition at line 36 of file Interaction.cpp.
References espressopp::interaction::Interaction::bondType(), espressopp::interaction::Interaction::computeEnergy(), espressopp::interaction::Interaction::computeEnergyAA(), espressopp::interaction::Interaction::computeEnergyCG(), espressopp::interaction::Interaction::computeEnergyDeriv(), and espressopp::interaction::Interaction::computeVirial().
Referenced by espressopp::interaction::registerPython(), and espressopp::interaction::Interaction::~Interaction().
setFixedTripleList()
template<typename _AngularPotential > void espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::setFixedTripleList (shared_ptr< FixedTripleList > _fixedtripleList) inline
Definition at line 65 of file FixedTripleListPIadressInteractionTemplate.hpp.
References espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::fixedtripleList.
setFixedTupleList()
template<typename _AngularPotential > void espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::setFixedTupleList (shared_ptr< FixedTupleListAdress > _fixedtupleList) inline
Definition at line 74 of file FixedTripleListPIadressInteractionTemplate.hpp.
References espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::fixedtupleList.
setNTrotter()
template<typename _AngularPotential > void espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::setNTrotter (int _ntrotter) inline
Definition at line 83 of file FixedTripleListPIadressInteractionTemplate.hpp.
References espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::ntrotter.
setPotential()
template<typename _AngularPotential > void espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::setPotential (shared_ptr< Potential > _potential) inline
Definition at line 101 of file FixedTripleListPIadressInteractionTemplate.hpp.
References espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::potential.
setSpeedup()
template<typename _AngularPotential > void espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::setSpeedup (bool _speedup) inline
Definition at line 92 of file FixedTripleListPIadressInteractionTemplate.hpp.
References espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::speedup.
Member Data Documentation
fixedtripleList
template<typename _AngularPotential > shared_ptr<FixedTripleList> espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::fixedtripleList protected
Definition at line 134 of file FixedTripleListPIadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::getFixedTripleList(), and espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::setFixedTripleList().
fixedtupleList
template<typename _AngularPotential > shared_ptr<FixedTupleListAdress> espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::fixedtupleList protected
Definition at line 135 of file FixedTripleListPIadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::getFixedTupleList(), and espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::setFixedTupleList().
ntrotter
template<typename _AngularPotential > int espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::ntrotter protected
Definition at line 132 of file FixedTripleListPIadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::getNTrotter(), and espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::setNTrotter().
ntypes
template<typename _AngularPotential > int espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::ntypes protected
Definition at line 131 of file FixedTripleListPIadressInteractionTemplate.hpp.
potential
template<typename _AngularPotential > shared_ptr< Potential > espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::potential protected
Definition at line 136 of file FixedTripleListPIadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::FixedTripleListPIadressInteractionTemplate(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::getMaxCutoff(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::getPotential(), and espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::setPotential().
speedup
template<typename _AngularPotential > bool espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::speedup protected
Definition at line 133 of file FixedTripleListPIadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::getSpeedup(), and espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::setSpeedup().
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/interaction/FixedTripleListPIadressInteractionTemplate.hpp