ESPResSo++: espressopp::integrator::LBInitPopWave Class Reference
espressopp::integrator::LBInitPopWave Class Reference
#include <LBInitPopWave.hpp>
Public Member Functions
LBInitPopWave (shared_ptr< System > _system, shared_ptr< LatticeBoltzmann > _latticeboltzmann)
void createDenVel (real _rho0, Real3D _u0)
void setForce (Real3D _force)
void addForce (Real3D _force)
Static Public Member Functions
static void registerPython ()
Protected Attributes
shared_ptr< LatticeBoltzmann > latticeboltzmann
real rho0
Real3D u0
Detailed Description
Definition at line 30 of file LBInitPopWave.hpp.
Constructor & Destructor Documentation
espressopp::integrator::LBInitPopWave::LBInitPopWave (shared_ptr< System > _system, shared_ptr< LatticeBoltzmann > _latticeboltzmann)
Definition at line 29 of file LBInitPopWave.cpp.
Member Function Documentation
void espressopp::integrator::LBInitPopWave::addForce (Real3D _force) virtual
Implements espressopp::integrator::LBInit.
Definition at line 89 of file LBInitPopWave.cpp.
void espressopp::integrator::LBInitPopWave::createDenVel (real _rho0, Real3D _u0) virtual
Implements espressopp::integrator::LBInit.
Definition at line 34 of file LBInitPopWave.cpp.
References espressopp::Int3D::getItem(), espressopp::Real3D::getItem(), espressopp::integrator::LBInit::latticeboltzmann, M_PI, and mpiWorld.
Referenced by registerPython().
void espressopp::integrator::LBInitPopWave::registerPython () static
Definition at line 91 of file LBInitPopWave.cpp.
References createDenVel().
Referenced by espressopp::integrator::registerPython().
void espressopp::integrator::LBInitPopWave::setForce (Real3D _force) virtual
Implements espressopp::integrator::LBInit.
Definition at line 88 of file LBInitPopWave.cpp.
Member Data Documentation
shared_ptr<LatticeBoltzmann> espressopp::integrator::LBInit::latticeboltzmann protected inherited
Definition at line 52 of file LBInit.hpp.
Referenced by espressopp::integrator::LBInitConstForce::addForce(), espressopp::integrator::LBInitPeriodicForce::addForce(), createDenVel(), espressopp::integrator::LBInitPopUniform::createDenVel(), espressopp::integrator::LBInit::LBInit(), espressopp::integrator::LBInitConstForce::setForce(), and espressopp::integrator::LBInitPeriodicForce::setForce().
real espressopp::integrator::LBInit::rho0 protected inherited
Definition at line 53 of file LBInit.hpp.
Real3D espressopp::integrator::LBInit::u0 protected inherited
Definition at line 54 of file LBInit.hpp.
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/integrator/LBInitPopWave.hpp
/home/travis/build/espressopp/espressopp/src/integrator/LBInitPopWave.cpp