ESPResSo++: espressopp::InBuffer Class Reference
espressopp::InBuffer Class Reference
#include <BufferArchive.hpp>
Public Types
enum ExtraDataElements {
DATA_PROPERTIES = 1, DATA_MOMENTUM = 2, DATA_LOCAL = 4, DATA_PROPERTIES = 1,
DATA_MOMENTUM = 2, DATA_LOCAL = 4, DATA_PROPERTIES = 1, DATA_MOMENTUM = 2,
DATA_LOCAL = 4
}
bitmask: which extra data elements to in- or exclude from ghost sending
enum ExtraDataElements {
DATA_PROPERTIES = 1, DATA_MOMENTUM = 2, DATA_LOCAL = 4, DATA_PROPERTIES = 1,
DATA_MOMENTUM = 2, DATA_LOCAL = 4, DATA_PROPERTIES = 1, DATA_MOMENTUM = 2,
DATA_LOCAL = 4
}
bitmask: which extra data elements to in- or exclude from ghost sending
enum ExtraDataElements {
DATA_PROPERTIES = 1, DATA_MOMENTUM = 2, DATA_LOCAL = 4, DATA_PROPERTIES = 1,
DATA_MOMENTUM = 2, DATA_LOCAL = 4, DATA_PROPERTIES = 1, DATA_MOMENTUM = 2,
DATA_LOCAL = 4
}
bitmask: which extra data elements to in- or exclude from ghost sending
Public Member Functions
InBuffer (const mpi::communicator &comm)
void read (int &val)
void read (Particle &p, int extradata)
void read (Particle &p)
void read (ParticleForce &f)
void read (std::vector< longint > &v)
void recv (longint sender, int tag)
InBuffer (const mpi::communicator &comm)
template<class T >
void readAll (T &val)
void read (int &val)
void read (real &val)
void read (Particle &p, int extradata)
void read (Particle &p)
void read (ParticleForce &f)
void read (std::vector< longint > &v)
void read (std::vector< real > &v)
void recv (longint sender, int tag)
mpi::request irecv (longint sender, int tag)
InBuffer (const mpi::communicator &comm)
template<class T >
void readAll (T &val)
void read (int &val)
void read (Particle &p, int extradata)
void read (Particle &p)
void read (ParticleForce &f)
void read (std::vector< longint > &v)
void recv (longint sender, int tag)
void reset ()
void reset ()
Protected Member Functions
void allocate (int size)
void extend (int size)
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (logger)
static LOG4ESPP_DECL_LOGGER (logger)
static LOG4ESPP_DECL_LOGGER (logger)
Protected Attributes
const mpi::communicator & comm
char * buf
char buf [BUFFER_SIZE]
char staticBuf [BUFFER_SIZE]
buffer with static size
boost::scoped_array< char > dynBuf
dynamic buffer, auto freed
int capacity
allocated size of the buffer
int usedSize
used size of the buffer
int pos
current buffer position
int size
Private Attributes
mpi::packed_iarchive ar
Detailed Description
Definition at line 58 of file BufferArchive.hpp.
Member Enumeration Documentation
enum espressopp::Buffer::ExtraDataElements [inherited]
bitmask: which extra data elements to in- or exclude from ghost sending
Enumerator:
DATA_PROPERTIES
DATA_MOMENTUM
DATA_LOCAL
DATA_PROPERTIES
DATA_MOMENTUM
DATA_LOCAL
DATA_PROPERTIES
DATA_MOMENTUM
DATA_LOCAL
Definition at line 42 of file BufferArchive.hpp.
enum espressopp::Buffer::ExtraDataElements [inherited]
bitmask: which extra data elements to in- or exclude from ghost sending
Enumerator:
DATA_PROPERTIES
DATA_MOMENTUM
DATA_LOCAL
DATA_PROPERTIES
DATA_MOMENTUM
DATA_LOCAL
DATA_PROPERTIES
DATA_MOMENTUM
DATA_LOCAL
Definition at line 46 of file BufferStatic.hpp.
enum espressopp::Buffer::ExtraDataElements [inherited]
bitmask: which extra data elements to in- or exclude from ghost sending
Enumerator:
DATA_PROPERTIES
DATA_MOMENTUM
DATA_LOCAL
DATA_PROPERTIES
DATA_MOMENTUM
DATA_LOCAL
DATA_PROPERTIES
DATA_MOMENTUM
DATA_LOCAL
Definition at line 52 of file BufferDynamic.hpp.
Constructor & Destructor Documentation
espressopp::InBuffer::InBuffer (const mpi::communicator & comm) [inline]
Definition at line 64 of file BufferArchive.hpp.
espressopp::InBuffer::InBuffer (const mpi::communicator & comm) [inline, explicit]
Definition at line 113 of file BufferDynamic.hpp.
espressopp::InBuffer::InBuffer (const mpi::communicator & comm) [inline]
Definition at line 82 of file BufferStatic.hpp.
Member Function Documentation
void espressopp::Buffer::allocate (int size) [inline, protected, inherited]
Definition at line 91 of file BufferDynamic.hpp.
References espressopp::Buffer::buf, espressopp::Buffer::capacity, espressopp::Buffer::dynBuf, espressopp::Buffer::size, and espressopp::Buffer::usedSize.
Referenced by espressopp::Buffer::extend(), irecv(), and recv().
void espressopp::Buffer::extend (int size) [inline, protected, inherited]
Definition at line 101 of file BufferDynamic.hpp.
References espressopp::Buffer::allocate(), and espressopp::Buffer::capacity.
Referenced by espressopp::OutBuffer::writeAll().
mpi::request espressopp::InBuffer::irecv (longint sender, int tag) [inline]
Definition at line 206 of file BufferDynamic.hpp.
References espressopp::Buffer::allocate(), espressopp::Buffer::buf, espressopp::Buffer::capacity, espressopp::Buffer::comm, espressopp::Buffer::pos, and espressopp::Buffer::usedSize.
Referenced by espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), and espressopp::storage::DomainDecompositionNonBlocking::irecvParticles_initiate().
static espressopp::Buffer::LOG4ESPP_DECL_LOGGER (logger) [static, protected, inherited]
static espressopp::Buffer::LOG4ESPP_DECL_LOGGER (logger) [static, protected, inherited]
static espressopp::Buffer::LOG4ESPP_DECL_LOGGER (logger) [static, protected, inherited]
void espressopp::InBuffer::read (int & val) [inline]
Definition at line 68 of file BufferArchive.hpp.
References ar.
Referenced by espressopp::FixedTupleList::afterRecvParticles(), espressopp::FixedTupleListAdress::afterRecvParticles(), espressopp::FixedListComm::afterRecvParticles(), espressopp::FixedTripleList::afterRecvParticles(), espressopp::FixedPairDistList::afterRecvParticles(), espressopp::FixedSingleList::afterRecvParticles(), espressopp::FixedQuadrupleList::afterRecvParticles(), espressopp::FixedPairList::afterRecvParticles(), espressopp::FixedTripleAngleList::afterRecvParticles(), espressopp::FixedQuadrupleAngleList::afterRecvParticles(), espressopp::storage::DomainDecompositionNonBlocking::irecvParticles_finish(), read(), espressopp::storage::Storage::recvParticles(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::storage::DomainDecompositionAdress::unpackAndAddForces(), espressopp::storage::Storage::unpackAndAddForces(), espressopp::storage::Storage::unpackForces(), espressopp::storage::DomainDecompositionAdress::unpackPositionsEtc(), and espressopp::storage::Storage::unpackPositionsEtc().
void espressopp::InBuffer::read (Particle & p, int extradata) [inline]
Definition at line 70 of file BufferArchive.hpp.
References ar, espressopp::Buffer::DATA_LOCAL, espressopp::Buffer::DATA_MOMENTUM, espressopp::Buffer::DATA_PROPERTIES, espressopp::Particle::l, espressopp::Particle::m, espressopp::Particle::p, and espressopp::Particle::r.
void espressopp::InBuffer::read (Particle & p) [inline]
Definition at line 85 of file BufferArchive.hpp.
References ar.
void espressopp::InBuffer::read (ParticleForce & f) [inline]
Definition at line 89 of file BufferArchive.hpp.
References ar.
void espressopp::InBuffer::read (std::vector< longint > & v) [inline]
Definition at line 93 of file BufferArchive.hpp.
References ar.
void espressopp::InBuffer::read (int & val) [inline]
Definition at line 96 of file BufferStatic.hpp.
void espressopp::InBuffer::read (Particle & p, int extradata) [inline]
Definition at line 98 of file BufferStatic.hpp.
References espressopp::Buffer::DATA_LOCAL, espressopp::Buffer::DATA_MOMENTUM, espressopp::Buffer::DATA_PROPERTIES, espressopp::Particle::l, espressopp::Particle::m, espressopp::Particle::p, and espressopp::Particle::r.
void espressopp::InBuffer::read (Particle & p) [inline]
Definition at line 113 of file BufferStatic.hpp.
void espressopp::InBuffer::read (ParticleForce & f) [inline]
Definition at line 117 of file BufferStatic.hpp.
void espressopp::InBuffer::read (std::vector< longint > & v) [inline]
Definition at line 121 of file BufferStatic.hpp.
References read().
void espressopp::InBuffer::read (int & val) [inline]
Definition at line 129 of file BufferDynamic.hpp.
void espressopp::InBuffer::read (real & val) [inline]
Definition at line 131 of file BufferDynamic.hpp.
void espressopp::InBuffer::read (Particle & p, int extradata) [inline]
Definition at line 133 of file BufferDynamic.hpp.
References espressopp::Buffer::DATA_LOCAL, espressopp::Buffer::DATA_MOMENTUM, espressopp::Buffer::DATA_PROPERTIES, espressopp::Particle::l, espressopp::Particle::m, espressopp::Particle::p, and espressopp::Particle::r.
void espressopp::InBuffer::read (Particle & p) [inline]
Definition at line 148 of file BufferDynamic.hpp.
void espressopp::InBuffer::read (ParticleForce & f) [inline]
Definition at line 152 of file BufferDynamic.hpp.
void espressopp::InBuffer::read (std::vector< longint > & v) [inline]
Definition at line 156 of file BufferDynamic.hpp.
References read().
void espressopp::InBuffer::read (std::vector< real > & v) [inline]
Definition at line 168 of file BufferDynamic.hpp.
References read().
template<class T > void espressopp::InBuffer::readAll (T & val) [inline]
Definition at line 86 of file BufferStatic.hpp.
References espressopp::Buffer::buf, espressopp::Buffer::pos, and espressopp::Buffer::size.
template<class T > void espressopp::InBuffer::readAll (T & val) [inline]
Definition at line 117 of file BufferDynamic.hpp.
References espressopp::Buffer::buf, espressopp::Buffer::comm, espressopp::Buffer::pos, and espressopp::Buffer::usedSize.
void espressopp::InBuffer::recv (longint sender, int tag) [inline]
Definition at line 97 of file BufferArchive.hpp.
References ar, and espressopp::Buffer::comm.
Referenced by espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::storage::Storage::recvParticles(), and espressopp::integrator::AssociationReaction::sendMultiMap().
void espressopp::InBuffer::recv (longint sender, int tag) [inline]
Definition at line 133 of file BufferStatic.hpp.
References espressopp::Buffer::buf, espressopp::Buffer::capacity, espressopp::Buffer::comm, espressopp::Buffer::pos, and espressopp::Buffer::size.
void espressopp::InBuffer::recv (longint sender, int tag) [inline]
Definition at line 180 of file BufferDynamic.hpp.
References espressopp::Buffer::allocate(), espressopp::Buffer::buf, espressopp::Buffer::capacity, espressopp::Buffer::comm, espressopp::Buffer::pos, and espressopp::Buffer::usedSize.
void espressopp::Buffer::reset () [inline, inherited]
Definition at line 59 of file BufferStatic.hpp.
References espressopp::Buffer::pos, and espressopp::Buffer::size.
void espressopp::Buffer::reset () [inline, inherited]
Definition at line 69 of file BufferDynamic.hpp.
References espressopp::Buffer::pos, and espressopp::Buffer::usedSize.
Referenced by espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::storage::DomainDecompositionNonBlocking::isendParticles(), espressopp::integrator::AssociationReaction::sendMultiMap(), and espressopp::storage::Storage::sendParticles().
Member Data Documentation
mpi::packed_iarchive espressopp::InBuffer::ar [private]
Definition at line 60 of file BufferArchive.hpp.
Referenced by read(), and recv().
char espressopp::Buffer::buf[BUFFER_SIZE] [protected, inherited]
Definition at line 71 of file BufferStatic.hpp.
char* espressopp::Buffer::buf [protected, inherited]
Definition at line 81 of file BufferDynamic.hpp.
Referenced by espressopp::Buffer::allocate(), espressopp::Buffer::Buffer(), irecv(), espressopp::OutBuffer::isend(), readAll(), recv(), espressopp::OutBuffer::send(), and espressopp::OutBuffer::writeAll().
int espressopp::Buffer::capacity [protected, inherited]
allocated size of the buffer
Definition at line 87 of file BufferDynamic.hpp.
Referenced by espressopp::Buffer::allocate(), espressopp::Buffer::Buffer(), espressopp::Buffer::extend(), irecv(), recv(), and espressopp::OutBuffer::writeAll().
const mpi::communicator & espressopp::Buffer::comm [protected, inherited]
Definition at line 54 of file BufferArchive.hpp.
Referenced by irecv(), espressopp::OutBuffer::isend(), readAll(), recv(), and espressopp::OutBuffer::send().
boost::scoped_array<char> espressopp::Buffer::dynBuf [protected, inherited]
dynamic buffer, auto freed
Definition at line 85 of file BufferDynamic.hpp.
Referenced by espressopp::Buffer::allocate().
int espressopp::Buffer::pos [protected, inherited]
current buffer position
Definition at line 89 of file BufferDynamic.hpp.
Referenced by espressopp::Buffer::Buffer(), irecv(), espressopp::OutBuffer::isend(), readAll(), recv(), espressopp::Buffer::reset(), espressopp::OutBuffer::send(), and espressopp::OutBuffer::writeAll().
int espressopp::Buffer::size [protected, inherited]
Definition at line 72 of file BufferStatic.hpp.
Referenced by espressopp::Buffer::allocate(), espressopp::Buffer::Buffer(), readAll(), recv(), espressopp::Buffer::reset(), espressopp::OutBuffer::write(), and espressopp::OutBuffer::writeAll().
char espressopp::Buffer::staticBuf[BUFFER_SIZE] [protected, inherited]
buffer with static size
Definition at line 83 of file BufferDynamic.hpp.
Referenced by espressopp::Buffer::Buffer().
int espressopp::Buffer::usedSize [protected, inherited]
used size of the buffer
Definition at line 88 of file BufferDynamic.hpp.
Referenced by espressopp::Buffer::allocate(), espressopp::Buffer::Buffer(), irecv(), readAll(), recv(), espressopp::Buffer::reset(), and espressopp::OutBuffer::writeAll().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/BufferArchive.hpp
/home/travis/build/espressopp/espressopp/src/BufferDynamic.hpp
/home/travis/build/espressopp/espressopp/src/BufferStatic.hpp