ESPResSo++: log4espp::GenLogger Class Reference
log4espp::GenLogger Class Reference
GenLogger is a very generic C++ implementation of the abstract Logger class.
#include <GenLogger.hpp>
Public Types
enum Level {
TRACE = 10, DEBUG = 20, INFO = 30, WARN = 40,
ERROR = 50, FATAL = 60
}
Public Member Functions
GenLogger (std::string name, class Logger *parent)
Constructor for o a generic logger.
~GenLogger ()
virtual void trace (Location loc, const std::string &msg)
Implementation of Logger::trace.
virtual void debug (Location loc, const std::string &msg)
Implementation of Logger::debug.
virtual void info (Location loc, const std::string &msg)
Implementation of Logger::info.
virtual void warn (Location loc, const std::string &msg)
Implementation of Logger::warn.
virtual void error (Location loc, const std::string &msg)
Implementation of Logger::error.
virtual void fatal (Location loc, const std::string &msg)
Implementation of Logger::fatal.
void traverse ()
Traversing this logger and all output loggers, can be used for DEBUG of Logger.
std::string getFullName ()
Asks for the full name of the logger, e.g.
bool isTraceEnabled ()
Check if logging statements of level TRACE are enabled.
bool isDebugEnabled ()
Check if logging statements of level DEBUG are enabled.
bool isInfoEnabled ()
Check if logging statements of level INFO are enabled.
bool isWarnEnabled ()
Check if logging statements of level WARN are enabled.
bool isErrorEnabled ()
Check if logging statements of level ERROR are enabled.
bool isFatalEnabled ()
Check if logging statements of level FATAL are enabled.
Level getLevel ()
Getter routine for the logging level of this object.
Level getEffectiveLevel ()
Getter routine for the effective logging level of this object.
void setLevel (Level level, bool force=true)
Setter routine for the logging level of this object.
Static Public Member Functions
static Logger & getRoot ()
Get reference to the root logger.
static Logger & getInstance (std::string name)
Get reference to a logger with a given name.
static void push (std::string item)
Add some content for the following log statements.
static void pop ()
Reverse to the last push.
static void configure ()
Configuration of the logging system.
static const char * getLevelString (int level)
Getter routine for the logging level of this object.
template<class DerivedLogger >
static Logger & createInstance (std::string name)
This routine creates a logger instance for a given name.
Protected Attributes
std::string name
name of the logger
bool setFlag
This flag indicates that level has been set explicitly.
Level myLevel
Current level of this logger.
class Logger * parent
points back to the parent logger, NULL for root
std::vector< class Logger * > sons
sub loggers of this logger
Static Protected Attributes
static std::vector< std::string > context
stack for different context
Private Member Functions
void log (const char *level, Location &loc, const std::string &msg)
Generic routine for logging output that can be used for all levels.
Detailed Description
GenLogger is a very generic C++ implementation of the abstract Logger class.
Definition at line 45 of file GenLogger.hpp.
Member Enumeration Documentation
enum log4espp::Logger::Level [inherited]
Enumerator:
TRACE
even more detailed than DEBUG
DEBUG
designates fine-grained informational events
INFO
informational messages highlighting progress
WARN
for potentially harmful situations
ERROR
for errors that might still allow the application to continue
FATAL
servere errors that will presumably lead to aborts
Definition at line 92 of file Logger.hpp.
Constructor & Destructor Documentation
GenLogger::GenLogger (std::string name, class Logger * parent)
Constructor for o a generic logger.
Parameters:
name is the name of the logger at this level
parent is a pointer to the ancestor logger (NULL for root)
See also:
Logger::Logger
Definition at line 60 of file GenLogger.cpp.
References log4espp::Logger::getFullName().
log4espp::GenLogger::~GenLogger () [inline]
Definition at line 70 of file GenLogger.hpp.
Member Function Documentation
void Logger::configure () [static, inherited]
Configuration of the logging system.
Definition at line 254 of file GenLogger.cpp.
References log4espp::Logger::getRoot(), LOG4ESPP_INFO, LOG4ESPP_WARN, read_config(), log4espp::Logger::setLevel(), traverse(), and log4espp::Logger::WARN.
template<class DerivedLogger > Logger & log4espp::Logger::createInstance (std::string name) [static, inherited]
This routine creates a logger instance for a given name.
The template argument specifies the class of the logger.
Definition at line 323 of file Logger.hpp.
References log4espp::Logger::getRoot(), log4espp::Logger::name, and log4espp::Logger::sons.
void GenLogger::debug (Location loc, const std::string & msg) [virtual]
Implementation of Logger::debug.
Implements log4espp::Logger.
Definition at line 310 of file GenLogger.cpp.
References log().
void GenLogger::error (Location loc, const std::string & msg) [virtual]
Implementation of Logger::error.
Implements log4espp::Logger.
Definition at line 325 of file GenLogger.cpp.
References log().
void GenLogger::fatal (Location loc, const std::string & msg) [virtual]
Implementation of Logger::fatal.
Implements log4espp::Logger.
Definition at line 330 of file GenLogger.cpp.
References log().
Level log4espp::Logger::getEffectiveLevel () [inline, inherited]
Getter routine for the effective logging level of this object.
If level has not been set explicitly it will ask the ancestors for the level
Definition at line 198 of file Logger.hpp.
References log4espp::Logger::getEffectiveLevel(), log4espp::Logger::myLevel, log4espp::Logger::parent, and log4espp::Logger::setFlag.
Referenced by log4espp::Logger::getEffectiveLevel(), and traverse().
std::string log4espp::Logger::getFullName () [inline, inherited]
Asks for the full name of the logger, e.g.
"X.Y.Z"
Definition at line 154 of file Logger.hpp.
References log4espp::Logger::getFullName(), log4espp::Logger::name, and log4espp::Logger::parent.
Referenced by GenLogger(), log4espp::Logger::getFullName(), log4espp::PyLogger::PyLogger(), log4espp::PyLogger::setPythonLevel(), log4espp::PyLogger::setPythonLogger(), and traverse().
Logger & Logger::getInstance (std::string name) [static, inherited]
Get reference to a logger with a given name.
Definition at line 90 of file GenLogger.cpp.
References log4espp::Logger::name.
Referenced by loggerUpdate(), and setLoggerLevel().
Level log4espp::Logger::getLevel () [inline, inherited]
Getter routine for the logging level of this object.
Definition at line 191 of file Logger.hpp.
References log4espp::Logger::myLevel.
Referenced by log4espp::Logger::Logger().
static const char* log4espp::Logger::getLevelString (int level) [inline, static, inherited]
Getter routine for the logging level of this object.
Returns:
the logging level as a string.
Definition at line 208 of file Logger.hpp.
References log4espp::Logger::DEBUG, log4espp::Logger::ERROR, log4espp::Logger::FATAL, log4espp::Logger::INFO, log4espp::Logger::TRACE, and log4espp::Logger::WARN.
Referenced by traverse().
Logger & Logger::getRoot () [static, inherited]
Get reference to the root logger.
Definition at line 72 of file GenLogger.cpp.
References rootLogger.
Referenced by log4espp::Logger::configure(), log4espp::Logger::createInstance(), and setLoggerLevel().
void GenLogger::info (Location loc, const std::string & msg) [virtual]
Implementation of Logger::info.
Implements log4espp::Logger.
Definition at line 315 of file GenLogger.cpp.
References log().
bool log4espp::Logger::isDebugEnabled () [inline, inherited]
Check if logging statements of level DEBUG are enabled.
Definition at line 171 of file Logger.hpp.
References log4espp::Logger::DEBUG, and log4espp::Logger::myLevel.
bool log4espp::Logger::isErrorEnabled () [inline, inherited]
Check if logging statements of level ERROR are enabled.
Definition at line 183 of file Logger.hpp.
References log4espp::Logger::ERROR, and log4espp::Logger::myLevel.
bool log4espp::Logger::isFatalEnabled () [inline, inherited]
Check if logging statements of level FATAL are enabled.
Definition at line 187 of file Logger.hpp.
References log4espp::Logger::FATAL, and log4espp::Logger::myLevel.
bool log4espp::Logger::isInfoEnabled () [inline, inherited]
Check if logging statements of level INFO are enabled.
Definition at line 175 of file Logger.hpp.
References log4espp::Logger::INFO, and log4espp::Logger::myLevel.
bool log4espp::Logger::isTraceEnabled () [inline, inherited]
Check if logging statements of level TRACE are enabled.
Definition at line 167 of file Logger.hpp.
References log4espp::Logger::myLevel, and log4espp::Logger::TRACE.
bool log4espp::Logger::isWarnEnabled () [inline, inherited]
Check if logging statements of level WARN are enabled.
Definition at line 179 of file Logger.hpp.
References log4espp::Logger::myLevel, and log4espp::Logger::WARN.
void GenLogger::log (const char * level, Location & loc, const std::string & msg) [private]
Generic routine for logging output that can be used for all levels.
Parameters:
level is the string representation of the level
loc is the file location of the logging statement
msg is the message output of the logging statement
Definition at line 288 of file GenLogger.cpp.
References log4espp::Location::filename, log4espp::Location::funcname, and log4espp::Location::line.
Referenced by debug(), error(), fatal(), info(), trace(), and warn().
static void log4espp::Logger::pop () [inline, static, inherited]
Reverse to the last push.
Definition at line 150 of file Logger.hpp.
References log4espp::Logger::context.
static void log4espp::Logger::push (std::string item) [inline, static, inherited]
Add some content for the following log statements.
Definition at line 146 of file Logger.hpp.
References log4espp::Logger::context.
void log4espp::Logger::setLevel (Level level, bool force = true) [inline, inherited]
Setter routine for the logging level of this object.
Parameters:
level is the new logging level for this object
force true specifies that this is an explicit set
This routine will set implicitly the levels recursively for the descendants whose level has not been set explicitly.
Definition at line 228 of file Logger.hpp.
References log4espp::Logger::myLevel, log4espp::Logger::setFlag, and log4espp::Logger::sons.
Referenced by log4espp::Logger::configure(), setLoggerLevel(), and log4espp::PyLogger::setPythonLevel().
void GenLogger::trace (Location loc, const std::string & msg) [virtual]
Implementation of Logger::trace.
Implements log4espp::Logger.
Definition at line 305 of file GenLogger.cpp.
References log().
void GenLogger::traverse ()
Traversing this logger and all output loggers, can be used for DEBUG of Logger.
Definition at line 133 of file GenLogger.cpp.
References log4espp::Logger::getEffectiveLevel(), log4espp::Logger::getFullName(), log4espp::Logger::getLevelString(), LOG4ESPP_DEBUG, log4espp::Logger::setFlag, log4espp::Logger::sons, and traverse().
Referenced by log4espp::Logger::configure(), and traverse().
void GenLogger::warn (Location loc, const std::string & msg) [virtual]
Implementation of Logger::warn.
Implements log4espp::Logger.
Definition at line 320 of file GenLogger.cpp.
References log().
Member Data Documentation
std::vector<std::string> log4espp::Logger::context [static, protected, inherited]
stack for different context
Definition at line 111 of file Logger.hpp.
Referenced by log4espp::Logger::pop(), and log4espp::Logger::push().
Level log4espp::Logger::myLevel [protected, inherited]
Current level of this logger.
Definition at line 105 of file Logger.hpp.
Referenced by log4espp::Logger::getEffectiveLevel(), log4espp::Logger::getLevel(), log4espp::Logger::isDebugEnabled(), log4espp::Logger::isErrorEnabled(), log4espp::Logger::isFatalEnabled(), log4espp::Logger::isInfoEnabled(), log4espp::Logger::isTraceEnabled(), log4espp::Logger::isWarnEnabled(), log4espp::Logger::Logger(), log4espp::Logger::setLevel(), and log4espp::PyLogger::setPythonLevel().
std::string log4espp::Logger::name [protected, inherited]
name of the logger
Definition at line 102 of file Logger.hpp.
Referenced by log4espp::Logger::createInstance(), log4espp::Logger::getFullName(), log4espp::Logger::getInstance(), log4espp::PyLogger::initLogging(), log4espp::PyLogger::log(), log4espp::Logger::Logger(), and log4espp::PyLogger::setPythonLoggers().
class Logger* log4espp::Logger::parent [protected, inherited]
points back to the parent logger, NULL for root
Definition at line 107 of file Logger.hpp.
Referenced by log4espp::Logger::getEffectiveLevel(), log4espp::Logger::getFullName(), and log4espp::Logger::Logger().
bool log4espp::Logger::setFlag [protected, inherited]
This flag indicates that level has been set explicitly.
Definition at line 103 of file Logger.hpp.
Referenced by log4espp::Logger::getEffectiveLevel(), log4espp::Logger::Logger(), log4espp::Logger::setLevel(), log4espp::PyLogger::setPythonLevel(), and traverse().
std::vector<class Logger*> log4espp::Logger::sons [protected, inherited]
sub loggers of this logger
Definition at line 109 of file Logger.hpp.
Referenced by log4espp::Logger::createInstance(), log4espp::Logger::Logger(), log4espp::Logger::setLevel(), log4espp::PyLogger::setPythonLoggers(), and traverse().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/esutil/GenLogger.hpp
/home/travis/build/espressopp/espressopp/src/esutil/GenLogger.cpp