ESPResSo++: espressopp::interaction::LennardJonesCapped Class Reference
espressopp::interaction::LennardJonesCapped Class Reference
This class provides methods to compute forces and energies of the Lennard Jones potential with capped forces.
#include <LennardJonesCapped.hpp>
Public Member Functions
LennardJonesCapped ()
LennardJonesCapped (real _epsilon, real _sigma, real _cutoff, real _caprad, real _shift)
LennardJonesCapped (real _epsilon, real _sigma, real _cutoff, real _caprad)
virtual ~LennardJonesCapped ()
void preset ()
void setEpsilon (real _epsilon)
real getEpsilon () const
void setCaprad (real _caprad)
real getCaprad () const
void setSigma (real _sigma)
real getSigma () const
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &dist, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
LennardJonesCapped * derived_this ()
const LennardJonesCapped * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
Private Attributes
real epsilon
real sigma
real caprad
real ff1
real ff2
real ef1
real ef2
Detailed Description
This class provides methods to compute forces and energies of the Lennard Jones potential with capped forces.
Definition at line 40 of file LennardJonesCapped.hpp.
Constructor & Destructor Documentation
espressopp::interaction::LennardJonesCapped::LennardJonesCapped () [inline]
Definition at line 51 of file LennardJonesCapped.hpp.
References espressopp::infinity, preset(), espressopp::interaction::PotentialTemplate< LennardJonesCapped >::setCutoff(), and espressopp::interaction::PotentialTemplate< LennardJonesCapped >::setShift().
espressopp::interaction::LennardJonesCapped::LennardJonesCapped (real _epsilon, real _sigma, real _cutoff, real _caprad, real _shift) [inline]
Definition at line 58 of file LennardJonesCapped.hpp.
References preset(), espressopp::interaction::PotentialTemplate< LennardJonesCapped >::setCutoff(), and espressopp::interaction::PotentialTemplate< LennardJonesCapped >::setShift().
espressopp::interaction::LennardJonesCapped::LennardJonesCapped (real _epsilon, real _sigma, real _cutoff, real _caprad) [inline]
Definition at line 66 of file LennardJonesCapped.hpp.
References espressopp::interaction::PotentialTemplate< LennardJonesCapped >::autoShift, preset(), espressopp::interaction::PotentialTemplate< LennardJonesCapped >::setAutoShift(), and espressopp::interaction::PotentialTemplate< LennardJonesCapped >::setCutoff().
virtual espressopp::interaction::LennardJonesCapped::~LennardJonesCapped () [inline, virtual]
Definition at line 75 of file LennardJonesCapped.hpp.
Member Function Documentation
real espressopp::interaction::PotentialTemplate< LennardJonesCapped >::_computeEnergy (const Particle & p1, const Particle & p2) const [inherited]
real espressopp::interaction::PotentialTemplate< LennardJonesCapped >::_computeEnergy (const Real3D & dist) const [inherited]
real espressopp::interaction::PotentialTemplate< LennardJonesCapped >::_computeEnergy (real dist) const [inherited]
real espressopp::interaction::PotentialTemplate< LennardJonesCapped >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const [inherited]
real espressopp::interaction::PotentialTemplate< LennardJonesCapped >::_computeEnergySqr (real distSqr) const [inherited]
real espressopp::interaction::LennardJonesCapped::_computeEnergySqrRaw (real distSqr) const [inline]
Definition at line 110 of file LennardJonesCapped.hpp.
References caprad, epsilon, and sigma.
bool espressopp::interaction::PotentialTemplate< LennardJonesCapped >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const [inherited]
bool espressopp::interaction::PotentialTemplate< LennardJonesCapped >::_computeForce (Real3D & force, const Real3D & dist) const [inherited]
bool espressopp::interaction::PotentialTemplate< LennardJonesCapped >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const [inherited]
bool espressopp::interaction::LennardJonesCapped::_computeForceRaw (Real3D & force, const Real3D & dist, real distSqr) const [inline]
Definition at line 128 of file LennardJonesCapped.hpp.
References caprad, epsilon, ff1, ff2, and sigma.
virtual real espressopp::interaction::PotentialTemplate< LennardJonesCapped >::computeEnergy (const Particle & p1, const Particle & p2) const [virtual, inherited]
Implements espressopp::interaction::Potential.
virtual real espressopp::interaction::PotentialTemplate< LennardJonesCapped >::computeEnergy (const Real3D & dist) const [virtual, inherited]
Implements espressopp::interaction::Potential.
virtual real espressopp::interaction::PotentialTemplate< LennardJonesCapped >::computeEnergy (real dist) const [virtual, inherited]
Implements espressopp::interaction::Potential.
virtual real espressopp::interaction::PotentialTemplate< LennardJonesCapped >::computeEnergySqr (real distsqr) const [virtual, inherited]
Implements espressopp::interaction::Potential.
virtual Real3D espressopp::interaction::PotentialTemplate< LennardJonesCapped >::computeForce (const Particle & p1, const Particle & p2) const [virtual, inherited]
Implements espressopp::interaction::Potential.
virtual Real3D espressopp::interaction::PotentialTemplate< LennardJonesCapped >::computeForce (const Real3D & dist) const [virtual, inherited]
Implements espressopp::interaction::Potential.
LennardJonesCapped * espressopp::interaction::PotentialTemplate< LennardJonesCapped >::derived_this () [inline, protected, inherited]
Definition at line 121 of file Potential.hpp.
const LennardJonesCapped * espressopp::interaction::PotentialTemplate< LennardJonesCapped >::derived_this () const [inline, protected, inherited]
Definition at line 125 of file Potential.hpp.
real espressopp::interaction::LennardJonesCapped::getCaprad () const [inline]
Definition at line 101 of file LennardJonesCapped.hpp.
References caprad.
Referenced by registerPython().
virtual real espressopp::interaction::PotentialTemplate< LennardJonesCapped >::getCutoff () const [virtual, inherited]
Implements espressopp::interaction::Potential.
real espressopp::interaction::LennardJonesCapped::getEpsilon () const [inline]
Definition at line 93 of file LennardJonesCapped.hpp.
References epsilon.
Referenced by espressopp::interaction::LennardJonesCapped_pickle::getinitargs(), and registerPython().
virtual real espressopp::interaction::PotentialTemplate< LennardJonesCapped >::getShift () const [virtual, inherited]
Implements espressopp::interaction::Potential.
real espressopp::interaction::LennardJonesCapped::getSigma () const [inline]
Definition at line 108 of file LennardJonesCapped.hpp.
References sigma.
Referenced by espressopp::interaction::LennardJonesCapped_pickle::getinitargs(), and registerPython().
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) [static, inherited]
Reimplemented in espressopp::interaction::LennardJones, espressopp::interaction::LennardJonesGeneric, and espressopp::interaction::FENE.
void espressopp::interaction::LennardJonesCapped::preset () [inline]
Definition at line 77 of file LennardJonesCapped.hpp.
References ef1, ef2, epsilon, ff1, ff2, and sigma.
Referenced by LennardJonesCapped(), setCaprad(), setEpsilon(), and setSigma().
void espressopp::interaction::LennardJonesCapped::registerPython () [static]
Reimplemented from espressopp::interaction::Potential.
Definition at line 50 of file LennardJonesCapped.cpp.
References getCaprad(), getEpsilon(), getSigma(), setCaprad(), setEpsilon(), and setSigma().
Referenced by espressopp::interaction::registerPython().
virtual real espressopp::interaction::PotentialTemplate< LennardJonesCapped >::setAutoShift () [virtual, inherited]
Implements espressopp::interaction::Potential.
Referenced by LennardJonesCapped().
void espressopp::interaction::LennardJonesCapped::setCaprad (real _caprad) [inline]
Definition at line 95 of file LennardJonesCapped.hpp.
References caprad, preset(), and espressopp::interaction::PotentialTemplate< LennardJonesCapped >::updateAutoShift().
Referenced by registerPython().
virtual void espressopp::interaction::PotentialTemplate< LennardJonesCapped >::setCutoff (real _cutoff) [virtual, inherited]
Implements espressopp::interaction::Potential.
Referenced by LennardJonesCapped().
void espressopp::interaction::LennardJonesCapped::setEpsilon (real _epsilon) [inline]
Definition at line 87 of file LennardJonesCapped.hpp.
References epsilon, preset(), and espressopp::interaction::PotentialTemplate< LennardJonesCapped >::updateAutoShift().
Referenced by registerPython().
virtual void espressopp::interaction::PotentialTemplate< LennardJonesCapped >::setShift (real _shift) [virtual, inherited]
Implements espressopp::interaction::Potential.
Referenced by LennardJonesCapped().
void espressopp::interaction::LennardJonesCapped::setSigma (real _sigma) [inline]
Definition at line 103 of file LennardJonesCapped.hpp.
References preset(), sigma, and espressopp::interaction::PotentialTemplate< LennardJonesCapped >::updateAutoShift().
Referenced by registerPython().
void espressopp::interaction::PotentialTemplate< LennardJonesCapped >::updateAutoShift () [inherited]
Referenced by setCaprad(), setEpsilon(), and setSigma().
Member Data Documentation
bool espressopp::interaction::PotentialTemplate< LennardJonesCapped >::autoShift [protected, inherited]
Definition at line 119 of file Potential.hpp.
Referenced by LennardJonesCapped().
real espressopp::interaction::LennardJonesCapped::caprad [private]
Definition at line 44 of file LennardJonesCapped.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), getCaprad(), and setCaprad().
real espressopp::interaction::PotentialTemplate< LennardJonesCapped >::cutoff [protected, inherited]
Definition at line 116 of file Potential.hpp.
real espressopp::interaction::PotentialTemplate< LennardJonesCapped >::cutoffSqr [protected, inherited]
Definition at line 117 of file Potential.hpp.
real espressopp::interaction::LennardJonesCapped::ef1 [private]
Definition at line 46 of file LennardJonesCapped.hpp.
Referenced by preset().
real espressopp::interaction::LennardJonesCapped::ef2 [private]
Definition at line 46 of file LennardJonesCapped.hpp.
Referenced by preset().
real espressopp::interaction::LennardJonesCapped::epsilon [private]
Definition at line 42 of file LennardJonesCapped.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), getEpsilon(), preset(), and setEpsilon().
real espressopp::interaction::LennardJonesCapped::ff1 [private]
Definition at line 45 of file LennardJonesCapped.hpp.
Referenced by _computeForceRaw(), and preset().
real espressopp::interaction::LennardJonesCapped::ff2 [private]
Definition at line 45 of file LennardJonesCapped.hpp.
Referenced by _computeForceRaw(), and preset().
real espressopp::interaction::PotentialTemplate< LennardJonesCapped >::shift [protected, inherited]
Definition at line 118 of file Potential.hpp.
real espressopp::interaction::LennardJonesCapped::sigma [private]
Definition at line 43 of file LennardJonesCapped.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), getSigma(), preset(), and setSigma().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/interaction/LennardJonesCapped.hpp
/home/travis/build/espressopp/espressopp/src/interaction/LennardJonesCapped.cpp