ESPResSo++: espressopp::interaction::StillingerWeberTripleTerm Class Reference
espressopp::interaction::StillingerWeberTripleTerm Class Reference abstract
#include <StillingerWeberTripleTerm.hpp>
Public Member Functions
StillingerWeberTripleTerm ()
StillingerWeberTripleTerm (real _gamma1, real _gamma2, real _theta0, real _lambda, real _epsilon, real _sigma1, real _sigma2, real _cutoff1, real _cutoff2)
virtual ~StillingerWeberTripleTerm ()
void setGamma1 (real _gamma)
real getGamma1 () const
void setGamma2 (real _gamma)
real getGamma2 () const
void setTheta0 (real _theta0)
real getTheta0 () const
void setLambda (real _lambda)
real getLambda () const
void setEpsilon (real _epsilon)
real getEpsilon () const
void setSigma1 (real _sigma)
real getSigma1 () const
void setSigma2 (real _sigma)
real getSigma2 () const
real getCutoff () const
void setCutoff1 (real _cutoff)
real getCutoff1 () const
void setCutoff2 (real _cutoff)
real getCutoff2 () const
void preset ()
real _computeEnergy (const Real3D &r12, const Real3D &r32) const
bool _computeForceRaw (Real3D &force12, Real3D &force32, const Real3D &r12, const Real3D &r32) const
real _computeEnergyRaw (real _theta) const
real _computeForceRaw (real theta) const
virtual real computeEnergy (const Particle &p1, const Particle &p2, const Particle &p3) const
virtual real computeEnergy (const Real3D &dist12, const Real3D &dist32) const
virtual real computeEnergy (const real theta) const
virtual void computeForce (Real3D &force12, Real3D &force32, const Particle &p1, const Particle &p2, const Particle &p3) const
virtual void computeForce (Real3D &force12, Real3D &force32, const Real3D &dist12, const Real3D &dist32) const
virtual real computeForce (real theta) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)
virtual shared_ptr< FixedPairList > getColVarBondList () const
virtual shared_ptr< FixedPairList > getColVarBondList () const =0
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &fpl)
virtual shared_ptr< FixedTripleList > getColVarAngleList () const
virtual shared_ptr< FixedTripleList > getColVarAngleList () const =0
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fpl)
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const =0
virtual void setColVar (const RealND &cv)
virtual void setColVar (const Real3D &dist12, const Real3D &dist32, const bc::BC &bc)
virtual RealND getColVar () const
virtual RealND getColVar () const =0
virtual void computeColVarWeights (const Real3D &dist12, const Real3D &dist32, const bc::BC &bc)
real _computeEnergy (const Particle &p1, const Particle &p2, const Particle &p3) const
real _computeEnergy (real theta) const
void _computeForce (Real3D &force12, Real3D &force32, const Particle &p1, const Particle &p2, const Particle &p3) const
bool _computeForce (Real3D &force12, Real3D &force32, const Real3D &dist12, const Real3D &dist32) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
StillingerWeberTripleTerm * derived_this ()
const StillingerWeberTripleTerm * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
shared_ptr< FixedPairList > colVarBondList
shared_ptr< FixedTripleList > colVarAngleList
shared_ptr< FixedQuadrupleList > colVarDihedList
RealND colVar
Private Attributes
real gamma1
real gamma2
real sigma1
real rc1
real sigma2
real rc2
real theta0
real lambda
real epsilon
real cosTeta0
real sigmaGamma1
real sigmaGamma2
real sigmarc1
real sigmarc2
real epsilonLambda
Detailed Description
Definition at line 39 of file StillingerWeberTripleTerm.hpp.
Constructor & Destructor Documentation
StillingerWeberTripleTerm() [1/2]
espressopp::interaction::StillingerWeberTripleTerm::StillingerWeberTripleTerm () inline
Definition at line 57 of file StillingerWeberTripleTerm.hpp.
References preset().
StillingerWeberTripleTerm() [2/2]
espressopp::interaction::StillingerWeberTripleTerm::StillingerWeberTripleTerm (real _gamma1, real _gamma2, real _theta0, real _lambda, real _epsilon, real _sigma1, real _sigma2, real _cutoff1, real _cutoff2) inline
Definition at line 61 of file StillingerWeberTripleTerm.hpp.
References preset().
~StillingerWeberTripleTerm()
virtual espressopp::interaction::StillingerWeberTripleTerm::~StillingerWeberTripleTerm () inline virtual
Definition at line 70 of file StillingerWeberTripleTerm.hpp.
Member Function Documentation
_computeEnergy() [1/3]
real espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::_computeEnergy (const Particle & p1, const Particle & p2, const Particle & p3) const inline inherited
Definition at line 290 of file AngularPotential.hpp.
_computeEnergy() [2/3]
real espressopp::interaction::StillingerWeberTripleTerm::_computeEnergy (const Real3D & r12, const Real3D & r32) const inline
Definition at line 143 of file StillingerWeberTripleTerm.hpp.
References espressopp::Real3D::abs(), cosTeta0, epsilonLambda, rc1, rc2, sigmaGamma1, sigmaGamma2, sigmarc1, and sigmarc2.
_computeEnergy() [3/3]
real espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::_computeEnergy (real theta) const inline inherited
Definition at line 314 of file AngularPotential.hpp.
_computeEnergyRaw()
real espressopp::interaction::StillingerWeberTripleTerm::_computeEnergyRaw (real _theta) const inline
Definition at line 216 of file StillingerWeberTripleTerm.hpp.
_computeForce() [1/2]
void espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::_computeForce (Real3D & force12, Real3D & force32, const Particle & p1, const Particle & p2, const Particle & p3) const inline inherited
Definition at line 343 of file AngularPotential.hpp.
_computeForce() [2/2]
bool espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::_computeForce (Real3D & force12, Real3D & force32, const Real3D & dist12, const Real3D & dist32) const inline inherited
Definition at line 354 of file AngularPotential.hpp.
_computeForceRaw() [1/2]
real espressopp::interaction::StillingerWeberTripleTerm::_computeForceRaw (real theta) const inline
Definition at line 222 of file StillingerWeberTripleTerm.hpp.
_computeForceRaw() [2/2]
bool espressopp::interaction::StillingerWeberTripleTerm::_computeForceRaw (Real3D & force12, Real3D & force32, const Real3D & r12, const Real3D & r32) const inline
Definition at line 168 of file StillingerWeberTripleTerm.hpp.
References espressopp::Real3D::abs(), cosTeta0, epsilonLambda, rc1, rc2, sigmaGamma1, sigmaGamma2, sigmarc1, and sigmarc2.
computeColVarWeights()
void espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::computeColVarWeights (const Real3D & dist12, const Real3D & dist32, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 255 of file AngularPotential.hpp.
computeEnergy() [1/3]
real espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::computeEnergy (const Particle & p1, const Particle & p2, const Particle & p3) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 264 of file AngularPotential.hpp.
computeEnergy() [2/3]
real espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::computeEnergy (const real theta) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 283 of file AngularPotential.hpp.
computeEnergy() [3/3]
real espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::computeEnergy (const Real3D & dist12, const Real3D & dist32) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 273 of file AngularPotential.hpp.
computeForce() [1/3]
real espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::computeForce (real theta) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 366 of file AngularPotential.hpp.
computeForce() [2/3]
void espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::computeForce (Real3D & force12, Real3D & force32, const Particle & p1, const Particle & p2, const Particle & p3) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 322 of file AngularPotential.hpp.
computeForce() [3/3]
void espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::computeForce (Real3D & force12, Real3D & force32, const Real3D & dist12, const Real3D & dist32) const inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 333 of file AngularPotential.hpp.
derived_this() [1/2]
StillingerWeberTripleTerm * espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::derived_this inline protected inherited
Definition at line 154 of file AngularPotential.hpp.
derived_this() [2/2]
const StillingerWeberTripleTerm * espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::derived_this inline protected inherited
Definition at line 158 of file AngularPotential.hpp.
getColVar() [1/2]
RealND espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::getColVar inline virtual inherited
Definition at line 249 of file AngularPotential.hpp.
getColVar() [2/2]
virtual RealND espressopp::interaction::AngularPotential::getColVar () const pure virtual inherited
Implemented in espressopp::interaction::AngularPotentialTemplate< Derived >.
Referenced by espressopp::interaction::AngularPotential::registerPython().
getColVarAngleList() [1/2]
shared_ptr< FixedTripleList > espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::getColVarAngleList inline virtual inherited
Definition at line 212 of file AngularPotential.hpp.
getColVarAngleList() [2/2]
virtual shared_ptr<FixedTripleList> espressopp::interaction::AngularPotential::getColVarAngleList () const pure virtual inherited
Implemented in espressopp::interaction::AngularPotentialTemplate< Derived >.
Referenced by espressopp::interaction::AngularPotential::registerPython().
getColVarBondList() [1/2]
shared_ptr< FixedPairList > espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::getColVarBondList inline virtual inherited
Definition at line 198 of file AngularPotential.hpp.
getColVarBondList() [2/2]
virtual shared_ptr<FixedPairList> espressopp::interaction::AngularPotential::getColVarBondList () const pure virtual inherited
Implemented in espressopp::interaction::AngularPotentialTemplate< Derived >.
Referenced by espressopp::interaction::AngularPotential::registerPython().
getColVarDihedList() [1/2]
shared_ptr< FixedQuadrupleList > espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::getColVarDihedList inline virtual inherited
Definition at line 226 of file AngularPotential.hpp.
getColVarDihedList() [2/2]
virtual shared_ptr<FixedQuadrupleList> espressopp::interaction::AngularPotential::getColVarDihedList () const pure virtual inherited
Implemented in espressopp::interaction::AngularPotentialTemplate< Derived >.
Referenced by espressopp::interaction::AngularPotential::registerPython().
getCutoff() [1/2]
real espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::getCutoff inline virtual inherited
Definition at line 184 of file AngularPotential.hpp.
getCutoff() [2/2]
real espressopp::interaction::StillingerWeberTripleTerm::getCutoff () const inline virtual
Implements espressopp::interaction::AngularPotential.
Definition at line 112 of file StillingerWeberTripleTerm.hpp.
References rc1, and rc2.
getCutoff1()
real espressopp::interaction::StillingerWeberTripleTerm::getCutoff1 () const inline
Definition at line 119 of file StillingerWeberTripleTerm.hpp.
References rc1.
Referenced by registerPython().
getCutoff2()
real espressopp::interaction::StillingerWeberTripleTerm::getCutoff2 () const inline
Definition at line 126 of file StillingerWeberTripleTerm.hpp.
References rc2.
Referenced by registerPython().
getEpsilon()
real espressopp::interaction::StillingerWeberTripleTerm::getEpsilon () const inline
Definition at line 99 of file StillingerWeberTripleTerm.hpp.
References epsilon.
Referenced by registerPython().
getGamma1()
real espressopp::interaction::StillingerWeberTripleTerm::getGamma1 () const inline
Definition at line 76 of file StillingerWeberTripleTerm.hpp.
References gamma1.
Referenced by registerPython().
getGamma2()
real espressopp::interaction::StillingerWeberTripleTerm::getGamma2 () const inline
Definition at line 81 of file StillingerWeberTripleTerm.hpp.
References gamma2.
Referenced by registerPython().
getLambda()
real espressopp::interaction::StillingerWeberTripleTerm::getLambda () const inline
Definition at line 93 of file StillingerWeberTripleTerm.hpp.
References lambda.
Referenced by registerPython().
getSigma1()
real espressopp::interaction::StillingerWeberTripleTerm::getSigma1 () const inline
Definition at line 105 of file StillingerWeberTripleTerm.hpp.
References sigma1.
Referenced by registerPython().
getSigma2()
real espressopp::interaction::StillingerWeberTripleTerm::getSigma2 () const inline
Definition at line 110 of file StillingerWeberTripleTerm.hpp.
References sigma2.
Referenced by registerPython().
getTheta0()
real espressopp::interaction::StillingerWeberTripleTerm::getTheta0 () const inline
Definition at line 87 of file StillingerWeberTripleTerm.hpp.
References theta0.
Referenced by registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::AngularPotential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
preset()
void espressopp::interaction::StillingerWeberTripleTerm::preset () inline
Definition at line 130 of file StillingerWeberTripleTerm.hpp.
References cosTeta0, epsilon, epsilonLambda, gamma1, gamma2, lambda, M_PIl, rc1, rc2, sigma1, sigma2, sigmaGamma1, sigmaGamma2, sigmarc1, sigmarc2, and theta0.
Referenced by setCutoff1(), setCutoff2(), setEpsilon(), setGamma1(), setGamma2(), setLambda(), setSigma1(), setSigma2(), setTheta0(), and StillingerWeberTripleTerm().
registerPython()
void espressopp::interaction::StillingerWeberTripleTerm::registerPython () static
Definition at line 40 of file StillingerWeberTripleTerm.cpp.
References getCutoff1(), getCutoff2(), getEpsilon(), getGamma1(), getGamma2(), getLambda(), getSigma1(), getSigma2(), getTheta0(), setCutoff1(), setCutoff2(), setEpsilon(), setGamma1(), setGamma2(), setLambda(), setSigma1(), setSigma2(), and setTheta0().
Referenced by espressopp::interaction::registerPython().
setColVar() [1/2]
void espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::setColVar (const Real3D & dist12, const Real3D & dist32, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 240 of file AngularPotential.hpp.
setColVar() [2/2]
void espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::setColVar (const RealND & cv) inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 233 of file AngularPotential.hpp.
setColVarAngleList()
void espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::setColVarAngleList (const shared_ptr< FixedTripleList > & fpl) inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 205 of file AngularPotential.hpp.
setColVarBondList()
void espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::setColVarBondList (const shared_ptr< FixedPairList > & fpl) inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 191 of file AngularPotential.hpp.
setColVarDihedList()
void espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fpl) inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 219 of file AngularPotential.hpp.
setCutoff()
void espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::AngularPotential.
Definition at line 176 of file AngularPotential.hpp.
setCutoff1()
void espressopp::interaction::StillingerWeberTripleTerm::setCutoff1 (real _cutoff) inline
Definition at line 115 of file StillingerWeberTripleTerm.hpp.
References preset(), and rc1.
Referenced by registerPython().
setCutoff2()
void espressopp::interaction::StillingerWeberTripleTerm::setCutoff2 (real _cutoff) inline
Definition at line 122 of file StillingerWeberTripleTerm.hpp.
References preset(), and rc2.
Referenced by registerPython().
setEpsilon()
void espressopp::interaction::StillingerWeberTripleTerm::setEpsilon (real _epsilon) inline
Definition at line 95 of file StillingerWeberTripleTerm.hpp.
References epsilon, and preset().
Referenced by registerPython().
setGamma1()
void espressopp::interaction::StillingerWeberTripleTerm::setGamma1 (real _gamma) inline
Definition at line 72 of file StillingerWeberTripleTerm.hpp.
References gamma1, and preset().
Referenced by registerPython().
setGamma2()
void espressopp::interaction::StillingerWeberTripleTerm::setGamma2 (real _gamma) inline
Definition at line 77 of file StillingerWeberTripleTerm.hpp.
References gamma2, and preset().
Referenced by registerPython().
setLambda()
void espressopp::interaction::StillingerWeberTripleTerm::setLambda (real _lambda) inline
Definition at line 89 of file StillingerWeberTripleTerm.hpp.
References lambda, and preset().
Referenced by registerPython().
setSigma1()
void espressopp::interaction::StillingerWeberTripleTerm::setSigma1 (real _sigma) inline
Definition at line 101 of file StillingerWeberTripleTerm.hpp.
References preset(), and sigma1.
Referenced by registerPython().
setSigma2()
void espressopp::interaction::StillingerWeberTripleTerm::setSigma2 (real _sigma) inline
Definition at line 106 of file StillingerWeberTripleTerm.hpp.
References preset(), and sigma2.
Referenced by registerPython().
setTheta0()
void espressopp::interaction::StillingerWeberTripleTerm::setTheta0 (real _theta0) inline
Definition at line 83 of file StillingerWeberTripleTerm.hpp.
References preset(), and theta0.
Referenced by registerPython().
Member Data Documentation
colVar
RealND espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::colVar protected inherited
Definition at line 152 of file AngularPotential.hpp.
colVarAngleList
shared_ptr<FixedTripleList> espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::colVarAngleList protected inherited
Definition at line 148 of file AngularPotential.hpp.
colVarBondList
shared_ptr<FixedPairList> espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::colVarBondList protected inherited
Definition at line 146 of file AngularPotential.hpp.
colVarDihedList
shared_ptr<FixedQuadrupleList> espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::colVarDihedList protected inherited
Definition at line 150 of file AngularPotential.hpp.
cosTeta0
real espressopp::interaction::StillingerWeberTripleTerm::cosTeta0 private
Definition at line 49 of file StillingerWeberTripleTerm.hpp.
Referenced by _computeEnergy(), _computeForceRaw(), and preset().
cutoff
real espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::cutoff protected inherited
Definition at line 143 of file AngularPotential.hpp.
cutoffSqr
real espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >::cutoffSqr protected inherited
Definition at line 144 of file AngularPotential.hpp.
epsilon
real espressopp::interaction::StillingerWeberTripleTerm::epsilon private
Definition at line 47 of file StillingerWeberTripleTerm.hpp.
Referenced by getEpsilon(), preset(), and setEpsilon().
epsilonLambda
real espressopp::interaction::StillingerWeberTripleTerm::epsilonLambda private
Definition at line 53 of file StillingerWeberTripleTerm.hpp.
Referenced by _computeEnergy(), _computeForceRaw(), and preset().
gamma1
real espressopp::interaction::StillingerWeberTripleTerm::gamma1 private
Definition at line 41 of file StillingerWeberTripleTerm.hpp.
Referenced by getGamma1(), preset(), and setGamma1().
gamma2
real espressopp::interaction::StillingerWeberTripleTerm::gamma2 private
Definition at line 41 of file StillingerWeberTripleTerm.hpp.
Referenced by getGamma2(), preset(), and setGamma2().
lambda
real espressopp::interaction::StillingerWeberTripleTerm::lambda private
Definition at line 45 of file StillingerWeberTripleTerm.hpp.
Referenced by getLambda(), preset(), and setLambda().
rc1
real espressopp::interaction::StillingerWeberTripleTerm::rc1 private
Definition at line 42 of file StillingerWeberTripleTerm.hpp.
Referenced by _computeEnergy(), _computeForceRaw(), getCutoff(), getCutoff1(), preset(), and setCutoff1().
rc2
real espressopp::interaction::StillingerWeberTripleTerm::rc2 private
Definition at line 42 of file StillingerWeberTripleTerm.hpp.
Referenced by _computeEnergy(), _computeForceRaw(), getCutoff(), getCutoff2(), preset(), and setCutoff2().
sigma1
real espressopp::interaction::StillingerWeberTripleTerm::sigma1 private
Definition at line 42 of file StillingerWeberTripleTerm.hpp.
Referenced by getSigma1(), preset(), and setSigma1().
sigma2
real espressopp::interaction::StillingerWeberTripleTerm::sigma2 private
Definition at line 42 of file StillingerWeberTripleTerm.hpp.
Referenced by getSigma2(), preset(), and setSigma2().
sigmaGamma1
real espressopp::interaction::StillingerWeberTripleTerm::sigmaGamma1 private
Definition at line 51 of file StillingerWeberTripleTerm.hpp.
Referenced by _computeEnergy(), _computeForceRaw(), and preset().
sigmaGamma2
real espressopp::interaction::StillingerWeberTripleTerm::sigmaGamma2 private
Definition at line 51 of file StillingerWeberTripleTerm.hpp.
Referenced by _computeEnergy(), _computeForceRaw(), and preset().
sigmarc1
real espressopp::interaction::StillingerWeberTripleTerm::sigmarc1 private
Definition at line 52 of file StillingerWeberTripleTerm.hpp.
Referenced by _computeEnergy(), _computeForceRaw(), and preset().
sigmarc2
real espressopp::interaction::StillingerWeberTripleTerm::sigmarc2 private
Definition at line 52 of file StillingerWeberTripleTerm.hpp.
Referenced by _computeEnergy(), _computeForceRaw(), and preset().
theta0
real espressopp::interaction::StillingerWeberTripleTerm::theta0 private
Definition at line 45 of file StillingerWeberTripleTerm.hpp.
Referenced by getTheta0(), preset(), and setTheta0().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/StillingerWeberTripleTerm.hpp
/home/espressopp/espressopp/src/interaction/StillingerWeberTripleTerm.cpp