ESPResSo++: espressopp::FixedListComm Class Reference
espressopp::FixedListComm Class Reference
#include <FixedListComm.hpp>
Public Types
typedef ESPPIterator< std::vector< ParticlePair > > Iterator
typedef ESPPIterator< std::vector< ParticleTriple > > Iterator
typedef ESPPIterator< std::vector< ParticleQuadruple > > Iterator
Public Member Functions
FixedListComm (shared_ptr< storage::Storage > _storage)
~FixedListComm ()
bool add (pvec pids)
void beforeSendParticles (ParticleList &pl, class OutBuffer &buf)
void afterRecvParticles (ParticleList &pl, class InBuffer &buf)
void onParticlesChanged ()
void add (Particle *p1, Particle *p2)
void add (Particle &p1, Particle &p2)
void add (std::vector< Particle *> particles)
void add (Particle *p1, Particle *p2, Particle *p3)
void add (Particle &p1, Particle &p2, Particle &p3)
void add (std::vector< Particle *> particles)
void add (Particle *p1, Particle *p2, Particle *p3, Particle *p4)
void add (Particle &p1, Particle &p2, Particle &p3, Particle &p4)
void add (std::vector< Particle *> particles)
Protected Types
typedef std::vector< longint > pvec
typedef boost::unordered_multimap< longint, pvec > GlobalList
typedef std::vector< ParticlePair > Super
typedef std::vector< ParticleTriple > Super
typedef std::vector< ParticleQuadruple > Super
Protected Attributes
boost::signals2::connection con1
boost::signals2::connection con2
boost::signals2::connection con3
shared_ptr< storage::Storage > storage
GlobalList globalLists
Static Private Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Detailed Description
Definition at line 36 of file FixedListComm.hpp.
Member Typedef Documentation
GlobalList
typedef boost::unordered_multimap<longint, pvec> espressopp::FixedListComm::GlobalList protected
Definition at line 41 of file FixedListComm.hpp.
Iterator [1/3]
typedef ESPPIterator<std::vector< ParticlePair > > espressopp::esutil::ESPPContainer< std::vector< ParticlePair > >::Iterator inherited
Definition at line 66 of file ESPPIterator.hpp.
Iterator [2/3]
typedef ESPPIterator<std::vector< ParticleQuadruple > > espressopp::esutil::ESPPContainer< std::vector< ParticleQuadruple > >::Iterator inherited
Definition at line 66 of file ESPPIterator.hpp.
Iterator [3/3]
typedef ESPPIterator<std::vector< ParticleTriple > > espressopp::esutil::ESPPContainer< std::vector< ParticleTriple > >::Iterator inherited
Definition at line 66 of file ESPPIterator.hpp.
pvec
typedef std::vector<longint> espressopp::FixedListComm::pvec protected
Definition at line 40 of file FixedListComm.hpp.
Super [1/3]
typedef std::vector< ParticleQuadruple > espressopp::esutil::ESPPContainer< std::vector< ParticleQuadruple > >::Super protected inherited
Definition at line 64 of file ESPPIterator.hpp.
Super [2/3]
typedef std::vector< ParticlePair > espressopp::esutil::ESPPContainer< std::vector< ParticlePair > >::Super protected inherited
Definition at line 64 of file ESPPIterator.hpp.
Super [3/3]
typedef std::vector< ParticleTriple > espressopp::esutil::ESPPContainer< std::vector< ParticleTriple > >::Super protected inherited
Definition at line 64 of file ESPPIterator.hpp.
Constructor & Destructor Documentation
FixedListComm()
espressopp::FixedListComm::FixedListComm (shared_ptr< storage::Storage > _storage)
Definition at line 34 of file FixedListComm.cpp.
References afterRecvParticles(), beforeSendParticles(), con1, con2, con3, LOG4ESPP_INFO, onParticlesChanged(), and storage.
~FixedListComm()
espressopp::FixedListComm::~FixedListComm ()
Definition at line 48 of file FixedListComm.cpp.
References con1, con2, con3, and LOG4ESPP_INFO.
Member Function Documentation
add() [1/10]
bool espressopp::FixedListComm::add (pvec pids)
Definition at line 59 of file FixedListComm.cpp.
References espressopp::PairList::add(), espressopp::TripleList::add(), espressopp::QuadrupleList::add(), beforeSendParticles(), globalLists, LOG4ESPP_INFO, and storage.
add() [2/10]
void espressopp::PairList::add (Particle * p1, Particle * p2) inline inherited
Definition at line 454 of file Particle.hpp.
Referenced by espressopp::VerletList::_rebuildUsingBuffers(), add(), espressopp::VerletListAdress::checkPair(), espressopp::VerletList::checkPair(), espressopp::vectorization::VerletList::checkPair(), and onParticlesChanged().
add() [3/10]
void espressopp::PairList::add (Particle & p1, Particle & p2) inline inherited
Definition at line 458 of file Particle.hpp.
add() [4/10]
void espressopp::PairList::add (std::vector< Particle *> particles) inline inherited
Definition at line 461 of file Particle.hpp.
add() [5/10]
void espressopp::TripleList::add (Particle * p1, Particle * p2, Particle * p3) inline inherited
Definition at line 483 of file Particle.hpp.
Referenced by add(), espressopp::VerletListTriple::checkTriple(), and onParticlesChanged().
add() [6/10]
void espressopp::TripleList::add (Particle & p1, Particle & p2, Particle & p3) inline inherited
Definition at line 487 of file Particle.hpp.
add() [7/10]
void espressopp::TripleList::add (std::vector< Particle *> particles) inline inherited
Definition at line 490 of file Particle.hpp.
add() [8/10]
void espressopp::QuadrupleList::add (Particle * p1, Particle * p2, Particle * p3, Particle * p4) inline inherited
Definition at line 514 of file Particle.hpp.
Referenced by add(), and onParticlesChanged().
add() [9/10]
void espressopp::QuadrupleList::add (Particle & p1, Particle & p2, Particle & p3, Particle & p4) inline inherited
Definition at line 518 of file Particle.hpp.
add() [10/10]
void espressopp::QuadrupleList::add (std::vector< Particle *> particles) inline inherited
Definition at line 521 of file Particle.hpp.
afterRecvParticles()
void espressopp::FixedListComm::afterRecvParticles (ParticleList & pl, class InBuffer & buf)
Definition at line 158 of file FixedListComm.cpp.
References globalLists, LOG4ESPP_DEBUG, LOG4ESPP_ERROR, LOG4ESPP_INFO, and espressopp::InBuffer::read().
Referenced by beforeSendParticles(), and FixedListComm().
beforeSendParticles()
void espressopp::FixedListComm::beforeSendParticles (ParticleList & pl, class OutBuffer & buf)
Definition at line 111 of file FixedListComm.cpp.
References afterRecvParticles(), globalLists, espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_DEBUG, LOG4ESPP_INFO, and espressopp::OutBuffer::write().
Referenced by add(), and FixedListComm().
LOG4ESPP_DECL_LOGGER()
static espressopp::FixedListComm::LOG4ESPP_DECL_LOGGER (theLogger) static private
onParticlesChanged()
void espressopp::FixedListComm::onParticlesChanged ()
Definition at line 195 of file FixedListComm.cpp.
References espressopp::PairList::add(), espressopp::TripleList::add(), espressopp::QuadrupleList::add(), globalLists, LOG4ESPP_INFO, and storage.
Referenced by FixedListComm().
Member Data Documentation
con1
boost::signals2::connection espressopp::FixedListComm::con1 protected
Definition at line 38 of file FixedListComm.hpp.
Referenced by FixedListComm(), and ~FixedListComm().
con2
boost::signals2::connection espressopp::FixedListComm::con2 protected
Definition at line 38 of file FixedListComm.hpp.
Referenced by FixedListComm(), and ~FixedListComm().
con3
boost::signals2::connection espressopp::FixedListComm::con3 protected
Definition at line 38 of file FixedListComm.hpp.
Referenced by FixedListComm(), and ~FixedListComm().
globalLists
GlobalList espressopp::FixedListComm::globalLists protected
Definition at line 42 of file FixedListComm.hpp.
Referenced by add(), afterRecvParticles(), beforeSendParticles(), and onParticlesChanged().
storage
shared_ptr<storage::Storage> espressopp::FixedListComm::storage protected
Definition at line 39 of file FixedListComm.hpp.
Referenced by add(), FixedListComm(), and onParticlesChanged().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/FixedListComm.hpp
/home/espressopp/espressopp/src/FixedListComm.cpp