ESPResSo++: espressopp::FixedPairListAdress Class Reference
espressopp::FixedPairListAdress Class Reference
This is a subclass of FixedPairList.
#include <FixedPairListAdress.hpp>
Public Types
typedef boost::unordered_multimap< longint, longint > GlobalPairs
typedef ESPPIterator< std::vector< ParticlePair > > Iterator
Public Member Functions
FixedPairListAdress (shared_ptr< storage::Storage > _storage, shared_ptr< FixedTupleListAdress > _fixedtupleList)
virtual ~FixedPairListAdress ()
bool add (longint pid1, longint pid2)
Add the given particle pair to the list on this processor if the particle with the lower id belongs to this processor.
void beforeSendParticles (ParticleList &pl, class OutBuffer &buf)
void beforeSendATParticles (std::vector< longint > &atpl, class OutBuffer &buf)
void onParticlesChanged ()
void remove ()
python::list getBonds ()
real getLongtimeMaxBondSqr ()
void setLongtimeMaxBondSqr (real d)
void resetLongtimeMaxBondSqr ()
void add (Particle *p1, Particle *p2)
void add (Particle &p1, Particle &p2)
void add (std::vector< Particle *> particles)
void afterRecvParticles (ParticleList &pl, class InBuffer &buf)
std::vector< longint > getPairList ()
python::list getAllBonds ()
GlobalPairs * getGlobalPairs ()
int size ()
Get the number of bonds in the GlobalPairs list.
int totalSize ()
Static Public Member Functions
static void registerPython ()
Protected Types
typedef std::vector< ParticlePair > Super
Protected Attributes
boost::signals2::connection sigBeforeSendAT
boost::signals2::connection sigAfterRecvAT
boost::signals2::connection sigBeforeSend
boost::signals2::connection sigOnParticlesChanged
boost::signals2::connection sigAfterRecv
shared_ptr< storage::Storage > storage
GlobalPairs globalPairs
real longtimeMaxBondSqr
Static Private Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Private Attributes
shared_ptr< FixedTupleListAdress > fixedtupleList
Detailed Description
This is a subclass of FixedPairList.
It should be used for AdResS fixed pairs. It overrides some parent functions, to use AT particles.
Definition at line 44 of file FixedPairListAdress.hpp.
Member Typedef Documentation
GlobalPairs
typedef boost::unordered_multimap<longint, longint> espressopp::FixedPairList::GlobalPairs inherited
Definition at line 42 of file FixedPairList.hpp.
Iterator
typedef ESPPIterator<std::vector< ParticlePair > > espressopp::esutil::ESPPContainer< std::vector< ParticlePair > >::Iterator inherited
Definition at line 66 of file ESPPIterator.hpp.
Super
typedef std::vector< ParticlePair > espressopp::esutil::ESPPContainer< std::vector< ParticlePair > >::Super protected inherited
Definition at line 64 of file ESPPIterator.hpp.
Constructor & Destructor Documentation
FixedPairListAdress()
espressopp::FixedPairListAdress::FixedPairListAdress (shared_ptr< storage::Storage > _storage, shared_ptr< FixedTupleListAdress > _fixedtupleList)
Definition at line 37 of file FixedPairListAdress.cpp.
References espressopp::FixedPairList::afterRecvParticles(), beforeSendATParticles(), fixedtupleList, LOG4ESPP_INFO, espressopp::FixedPairList::sigAfterRecv, sigAfterRecvAT, espressopp::FixedPairList::sigBeforeSend, and sigBeforeSendAT.
~FixedPairListAdress()
espressopp::FixedPairListAdress::~FixedPairListAdress () virtual
Definition at line 53 of file FixedPairListAdress.cpp.
References LOG4ESPP_INFO, sigAfterRecvAT, and sigBeforeSendAT.
Member Function Documentation
add() [1/4]
bool espressopp::FixedPairListAdress::add (longint pid1, longint pid2) virtual
Add the given particle pair to the list on this processor if the particle with the lower id belongs to this processor.
Note that this routine does not check whether the pair is inserted on another processor as well.
Returns
whether the particle was inserted on this processor.
Reimplemented from espressopp::FixedPairList.
Definition at line 63 of file FixedPairListAdress.cpp.
References espressopp::esutil::Error::checkException(), espressopp::System::comm, espressopp::FixedPairList::globalPairs, LOG4ESPP_INFO, espressopp::esutil::Error::setException(), and espressopp::FixedPairList::storage.
Referenced by onParticlesChanged(), and registerPython().
add() [2/4]
void espressopp::PairList::add (Particle * p1, Particle * p2) inline inherited
Definition at line 454 of file Particle.hpp.
Referenced by espressopp::FixedListComm::add(), espressopp::VerletList::checkPair(), espressopp::VerletListAdress::checkPair(), and espressopp::FixedListComm::onParticlesChanged().
add() [3/4]
void espressopp::PairList::add (Particle & p1, Particle & p2) inline inherited
Definition at line 458 of file Particle.hpp.
add() [4/4]
void espressopp::PairList::add (std::vector< Particle *> particles) inline inherited
Definition at line 461 of file Particle.hpp.
afterRecvParticles()
void espressopp::FixedPairList::afterRecvParticles (ParticleList & pl, class InBuffer & buf) inherited
Definition at line 237 of file FixedPairList.cpp.
References espressopp::FixedPairList::globalPairs, LOG4ESPP_DEBUG, LOG4ESPP_ERROR, LOG4ESPP_INFO, espressopp::InBuffer::read(), and espressopp::FixedPairList::size().
Referenced by espressopp::FixedPairList::FixedPairList(), and FixedPairListAdress().
beforeSendATParticles()
void espressopp::FixedPairListAdress::beforeSendATParticles (std::vector< longint > & atpl, class OutBuffer & buf)
Definition at line 119 of file FixedPairListAdress.cpp.
References espressopp::FixedPairList::globalPairs, LOG4ESPP_DEBUG, LOG4ESPP_INFO, and espressopp::OutBuffer::write().
Referenced by FixedPairListAdress().
beforeSendParticles()
void espressopp::FixedPairListAdress::beforeSendParticles (ParticleList & pl, class OutBuffer & buf) virtual
Reimplemented from espressopp::FixedPairList.
Definition at line 167 of file FixedPairListAdress.cpp.
getAllBonds()
python::list espressopp::FixedPairList::getAllBonds () inherited
Definition at line 169 of file FixedPairList.cpp.
References espressopp::System::comm, espressopp::FixedPairList::globalPairs, and espressopp::FixedPairList::storage.
Referenced by espressopp::FixedPairList::registerPython().
getBonds()
python::list espressopp::FixedPairListAdress::getBonds ()
Definition at line 214 of file FixedPairListAdress.cpp.
References espressopp::FixedPairList::globalPairs.
Referenced by registerPython().
getGlobalPairs()
GlobalPairs* espressopp::FixedPairList::getGlobalPairs () inline inherited
Definition at line 73 of file FixedPairList.hpp.
References espressopp::FixedPairList::globalPairs.
getLongtimeMaxBondSqr()
real espressopp::FixedPairList::getLongtimeMaxBondSqr () inherited
Definition at line 85 of file FixedPairList.cpp.
References espressopp::FixedPairList::longtimeMaxBondSqr.
Referenced by espressopp::FixedPairList::registerPython().
getPairList()
std::vector< longint > espressopp::FixedPairList::getPairList () inherited
Definition at line 160 of file FixedPairList.cpp.
References espressopp::FixedPairList::globalPairs.
LOG4ESPP_DECL_LOGGER()
static espressopp::FixedPairListAdress::LOG4ESPP_DECL_LOGGER (theLogger) static private
onParticlesChanged()
void espressopp::FixedPairListAdress::onParticlesChanged () virtual
Reimplemented from espressopp::FixedPairList.
Definition at line 172 of file FixedPairListAdress.cpp.
References add(), espressopp::esutil::Error::checkException(), espressopp::System::comm, espressopp::FixedPairList::globalPairs, LOG4ESPP_INFO, espressopp::esutil::Error::setException(), and espressopp::FixedPairList::storage.
registerPython()
void espressopp::FixedPairListAdress::registerPython () static
Definition at line 241 of file FixedPairListAdress.cpp.
References add(), getBonds(), and remove().
Referenced by espressopp::registerPython().
remove()
void espressopp::FixedPairListAdress::remove (void)
Definition at line 226 of file FixedPairListAdress.cpp.
References espressopp::FixedPairList::globalPairs, espressopp::FixedPairList::sigAfterRecv, sigAfterRecvAT, espressopp::FixedPairList::sigBeforeSend, sigBeforeSendAT, and espressopp::FixedPairList::sigOnParticlesChanged.
Referenced by registerPython().
resetLongtimeMaxBondSqr()
void espressopp::FixedPairList::resetLongtimeMaxBondSqr () inherited
Definition at line 93 of file FixedPairList.cpp.
References espressopp::FixedPairList::add(), and espressopp::FixedPairList::longtimeMaxBondSqr.
Referenced by espressopp::FixedPairList::registerPython().
setLongtimeMaxBondSqr()
void espressopp::FixedPairList::setLongtimeMaxBondSqr (real d) inherited
Definition at line 89 of file FixedPairList.cpp.
References espressopp::FixedPairList::longtimeMaxBondSqr.
size()
int espressopp::FixedPairList::size () inline inherited
Get the number of bonds in the GlobalPairs list.
Definition at line 77 of file FixedPairList.hpp.
References espressopp::FixedPairList::LOG4ESPP_DECL_LOGGER(), espressopp::FixedPairList::registerPython(), and espressopp::FixedPairList::totalSize().
Referenced by espressopp::FixedPairList::afterRecvParticles(), and espressopp::FixedPairList::registerPython().
totalSize()
int espressopp::FixedPairList::totalSize () inherited
Definition at line 308 of file FixedPairList.cpp.
References espressopp::System::comm, espressopp::FixedPairList::globalPairs, and espressopp::FixedPairList::storage.
Referenced by espressopp::FixedPairList::registerPython(), and espressopp::FixedPairList::size().
Member Data Documentation
fixedtupleList
shared_ptr<FixedTupleListAdress> espressopp::FixedPairListAdress::fixedtupleList private
Definition at line 69 of file FixedPairListAdress.hpp.
Referenced by FixedPairListAdress().
globalPairs
GlobalPairs espressopp::FixedPairList::globalPairs protected inherited
Definition at line 47 of file FixedPairList.hpp.
Referenced by add(), espressopp::FixedPairList::add(), espressopp::FixedPairList::afterRecvParticles(), beforeSendATParticles(), espressopp::FixedPairList::beforeSendParticles(), espressopp::FixedPairList::getAllBonds(), getBonds(), espressopp::FixedPairList::getBonds(), espressopp::FixedPairList::getGlobalPairs(), espressopp::FixedPairList::getPairList(), onParticlesChanged(), espressopp::FixedPairList::onParticlesChanged(), remove(), espressopp::FixedPairList::remove(), and espressopp::FixedPairList::totalSize().
longtimeMaxBondSqr
real espressopp::FixedPairList::longtimeMaxBondSqr protected inherited
Definition at line 49 of file FixedPairList.hpp.
Referenced by espressopp::FixedPairList::getLongtimeMaxBondSqr(), espressopp::FixedPairList::resetLongtimeMaxBondSqr(), and espressopp::FixedPairList::setLongtimeMaxBondSqr().
sigAfterRecv
boost::signals2::connection espressopp::FixedPairList::sigAfterRecv protected inherited
Definition at line 45 of file FixedPairList.hpp.
Referenced by espressopp::FixedPairList::FixedPairList(), FixedPairListAdress(), remove(), espressopp::FixedPairList::remove(), and espressopp::FixedPairList::~FixedPairList().
sigAfterRecvAT
boost::signals2::connection espressopp::FixedPairListAdress::sigAfterRecvAT protected
Definition at line 66 of file FixedPairListAdress.hpp.
Referenced by FixedPairListAdress(), remove(), and ~FixedPairListAdress().
sigBeforeSend
boost::signals2::connection espressopp::FixedPairList::sigBeforeSend protected inherited
Definition at line 45 of file FixedPairList.hpp.
Referenced by espressopp::FixedPairList::FixedPairList(), FixedPairListAdress(), remove(), espressopp::FixedPairList::remove(), and espressopp::FixedPairList::~FixedPairList().
sigBeforeSendAT
boost::signals2::connection espressopp::FixedPairListAdress::sigBeforeSendAT protected
Definition at line 66 of file FixedPairListAdress.hpp.
Referenced by FixedPairListAdress(), remove(), and ~FixedPairListAdress().
sigOnParticlesChanged
boost::signals2::connection espressopp::FixedPairList::sigOnParticlesChanged protected inherited
Definition at line 45 of file FixedPairList.hpp.
Referenced by espressopp::FixedPairList::FixedPairList(), remove(), espressopp::FixedPairList::remove(), and espressopp::FixedPairList::~FixedPairList().
storage
shared_ptr<storage::Storage> espressopp::FixedPairList::storage protected inherited
Definition at line 46 of file FixedPairList.hpp.
Referenced by add(), espressopp::FixedPairList::add(), espressopp::FixedPairList::FixedPairList(), espressopp::FixedPairList::getAllBonds(), onParticlesChanged(), espressopp::FixedPairList::onParticlesChanged(), and espressopp::FixedPairList::totalSize().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/FixedPairListAdress.hpp
/home/espressopp/espressopp/src/FixedPairListAdress.cpp