ESPResSo++: espressopp::analysis::IntraChainDistSq Class Reference
espressopp::analysis::IntraChainDistSq Class Reference
calculate mean squared intra-chain-distances
#include <IntraChainDistSq.hpp>
Public Member Functions
IntraChainDistSq (shared_ptr< System > system, shared_ptr< FixedPairList > _fpl)
~IntraChainDistSq ()
python::list compute ()
void gatherAllPositions ()
gather and broadcast all particle positions to all cpus
ConfMap getAllPositions ()
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
Public Attributes
shared_ptr< FixedPairList > fpl
ConfMap AllPositions
int numParticles
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (logger)
Private Attributes
weak_ptr< System > mySystem
Weak pointer to the system guarantees that system will be freed.
weak_ptr< System > mySystem1
weak_ptr< System > mySystem2
Detailed Description
calculate mean squared intra-chain-distances
Definition at line 39 of file IntraChainDistSq.hpp.
Constructor & Destructor Documentation
IntraChainDistSq()
espressopp::analysis::IntraChainDistSq::IntraChainDistSq (shared_ptr< System > system, shared_ptr< FixedPairList > _fpl) inline
Definition at line 42 of file IntraChainDistSq.hpp.
~IntraChainDistSq()
espressopp::analysis::IntraChainDistSq::~IntraChainDistSq () inline
Definition at line 43 of file IntraChainDistSq.hpp.
Member Function Documentation
compute()
python::list espressopp::analysis::IntraChainDistSq::compute ()
Definition at line 40 of file IntraChainDistSq.cpp.
Referenced by registerPython().
gatherAllPositions()
void espressopp::analysis::AllParticlePos::gatherAllPositions () inherited
gather and broadcast all particle positions to all cpus
Definition at line 41 of file AllParticlePos.cpp.
References espressopp::System::bc, espressopp::System::comm, espressopp::iterator::CellListIterator::isDone(), espressopp::analysis::sBuf::r, and espressopp::System::storage.
Referenced by espressopp::analysis::AllParticlePos::registerPython().
getAllPositions()
ConfMap espressopp::analysis::AllParticlePos::getAllPositions () inherited
Definition at line 77 of file AllParticlePos.cpp.
getSystem()
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::VerletList::_rebuildUsingBuffers(), espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::LatticeBoltzmann::assignMyLattice(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::vectorization::Vectorization::befCalcForces(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::vectorization::Vectorization::connect(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::vectorization::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpXTCAdress::dump(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::io::DumpXYZ::DumpXYZ(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::vectorization::VerletList::rebuild(), espressopp::vectorization::VerletList::rebuild_p_nc_pack_stencil(), espressopp::vectorization::VerletList::rebuildPairs(), espressopp::VerletListTriple::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::VerletList::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::vectorization::VerletList::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::vectorization::Vectorization::resetCells(), espressopp::vectorization::Vectorization::resetParticles(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::vectorization::Vectorization::updateForces(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
getSystem1()
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
getSystem2()
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
getSystemRef()
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerletRESPA::calcForces(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeCOM(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::FixedLocalTupleComListInteractionTemplate(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::VelocityVerletRESPA::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::VelocityVerletRESPA::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::VelocityVerletRESPA::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::Adress::integrateSlow(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::vectorization::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::VelocityVerletRESPA::run(), espressopp::integrator::PIAdressIntegrator::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::MinimizeEnergy::run(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::Rattle::saveOldPos(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostatOnGroup::thermalize(), espressopp::integrator::LangevinThermostatOnRadius::thermalize(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::vectorization::VerletList::totalSize(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::io::DumpH5MD::update(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::VelocityVerletRESPA::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
getSystemRef1()
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
getSystemRef2()
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
LOG4ESPP_DECL_LOGGER()
static espressopp::analysis::IntraChainDistSq::LOG4ESPP_DECL_LOGGER (logger) static protected
registerPython()
void espressopp::analysis::IntraChainDistSq::registerPython () static
Definition at line 59 of file IntraChainDistSq.cpp.
References compute().
Referenced by espressopp::analysis::registerPython().
Member Data Documentation
AllPositions
ConfMap espressopp::analysis::AllParticlePos::AllPositions inherited
Definition at line 59 of file AllParticlePos.hpp.
fpl
shared_ptr<FixedPairList> espressopp::analysis::IntraChainDistSq::fpl
Definition at line 41 of file IntraChainDistSq.hpp.
mySystem
weak_ptr< System > espressopp::SystemAccess::mySystem private inherited
Weak pointer to the system guarantees that system will be freed.
Definition at line 54 of file SystemAccess.hpp.
Referenced by espressopp::SystemAccess::getSystem(), and espressopp::SystemAccess::SystemAccess().
mySystem1
weak_ptr< System > espressopp::SystemAccess::mySystem1 private inherited
Definition at line 55 of file SystemAccess.hpp.
Referenced by espressopp::SystemAccess::getSystem1(), and espressopp::SystemAccess::SystemAccess().
mySystem2
weak_ptr< System > espressopp::SystemAccess::mySystem2 private inherited
Definition at line 56 of file SystemAccess.hpp.
Referenced by espressopp::SystemAccess::getSystem2(), and espressopp::SystemAccess::SystemAccess().
numParticles
int espressopp::analysis::AllParticlePos::numParticles inherited
Definition at line 60 of file AllParticlePos.hpp.
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/analysis/IntraChainDistSq.hpp
/home/espressopp/espressopp/src/analysis/IntraChainDistSq.cpp