ESPResSo++: espressopp::FixedQuadrupleList Class Reference
espressopp::FixedQuadrupleList Class Reference
#include <FixedQuadrupleList.hpp>
Public Types
typedef ESPPIterator< std::vector< ParticleQuadruple > > Iterator
Public Member Functions
FixedQuadrupleList (shared_ptr< storage::Storage > _storage)
~FixedQuadrupleList ()
bool add (longint pid1, longint pid2, longint pid3, longint pid4)
Add the given particle quadruple to the list on this processor if the particle with the lower id belongs to this processor.
void beforeSendParticles (ParticleList &pl, class OutBuffer &buf)
void afterRecvParticles (ParticleList &pl, class InBuffer &buf)
virtual void onParticlesChanged ()
virtual std::vector< longint > getQuadrupleList ()
python::list getQuadruples ()
int size ()
Get the number of quadruples in the GlobalQuadruples list.
void remove ()
void add (Particle *p1, Particle *p2, Particle *p3, Particle *p4)
void add (Particle &p1, Particle &p2, Particle &p3, Particle &p4)
void add (std::vector< Particle *> particles)
Static Public Member Functions
static void registerPython ()
Protected Types
typedef boost::unordered_multimap< longint, Triple< longint, longint, longint > > GlobalQuadruples
typedef std::vector< ParticleQuadruple > Super
Protected Attributes
boost::signals2::connection sigBeforeSend
boost::signals2::connection sigAfterRecv
boost::signals2::connection sigOnParticlesChanged
shared_ptr< storage::Storage > storage
GlobalQuadruples globalQuadruples
Static Private Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Detailed Description
Definition at line 39 of file FixedQuadrupleList.hpp.
Member Typedef Documentation
GlobalQuadruples
typedef boost::unordered_multimap< longint, Triple < longint, longint, longint > > espressopp::FixedQuadrupleList::GlobalQuadruples protected
Definition at line 44 of file FixedQuadrupleList.hpp.
Iterator
typedef ESPPIterator<std::vector< ParticleQuadruple > > espressopp::esutil::ESPPContainer< std::vector< ParticleQuadruple > >::Iterator inherited
Definition at line 66 of file ESPPIterator.hpp.
Super
typedef std::vector< ParticleQuadruple > espressopp::esutil::ESPPContainer< std::vector< ParticleQuadruple > >::Super protected inherited
Definition at line 64 of file ESPPIterator.hpp.
Constructor & Destructor Documentation
FixedQuadrupleList()
espressopp::FixedQuadrupleList::FixedQuadrupleList (shared_ptr< storage::Storage > _storage)
Definition at line 47 of file FixedQuadrupleList.cpp.
References afterRecvParticles(), beforeSendParticles(), LOG4ESPP_INFO, onParticlesChanged(), sigAfterRecv, sigBeforeSend, sigOnParticlesChanged, and storage.
~FixedQuadrupleList()
espressopp::FixedQuadrupleList::~FixedQuadrupleList ()
Definition at line 60 of file FixedQuadrupleList.cpp.
References add(), LOG4ESPP_INFO, sigAfterRecv, sigBeforeSend, and sigOnParticlesChanged.
Member Function Documentation
add() [1/4]
bool espressopp::FixedQuadrupleList::add (longint pid1, longint pid2, longint pid3, longint pid4)
Add the given particle quadruple to the list on this processor if the particle with the lower id belongs to this processor.
Note that this routine does not check whether the quadruple is inserted on another processor as well.
Returns
whether the quadruple was inserted on this processor.
Definition at line 83 of file FixedQuadrupleList.cpp.
References espressopp::esutil::Error::checkException(), espressopp::System::comm, globalQuadruples, LOG4ESPP_INFO, espressopp::esutil::Error::setException(), and storage.
Referenced by onParticlesChanged(), registerPython(), and ~FixedQuadrupleList().
add() [2/4]
void espressopp::QuadrupleList::add (Particle * p1, Particle * p2, Particle * p3, Particle * p4) inline inherited
Definition at line 514 of file Particle.hpp.
Referenced by espressopp::FixedListComm::add(), and espressopp::FixedListComm::onParticlesChanged().
add() [3/4]
void espressopp::QuadrupleList::add (Particle & p1, Particle & p2, Particle & p3, Particle & p4) inline inherited
Definition at line 518 of file Particle.hpp.
add() [4/4]
void espressopp::QuadrupleList::add (std::vector< Particle *> particles) inline inherited
Definition at line 521 of file Particle.hpp.
afterRecvParticles()
void espressopp::FixedQuadrupleList::afterRecvParticles (ParticleList & pl, class InBuffer & buf)
Definition at line 211 of file FixedQuadrupleList.cpp.
References globalQuadruples, LOG4ESPP_INFO, espressopp::InBuffer::read(), and size().
Referenced by beforeSendParticles(), FixedQuadrupleList(), and espressopp::FixedQuadrupleListAdress::FixedQuadrupleListAdress().
beforeSendParticles()
void espressopp::FixedQuadrupleList::beforeSendParticles (ParticleList & pl, class OutBuffer & buf)
Definition at line 170 of file FixedQuadrupleList.cpp.
References afterRecvParticles(), globalQuadruples, espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_INFO, and espressopp::OutBuffer::write().
Referenced by FixedQuadrupleList(), and getQuadrupleList().
getQuadrupleList()
std::vector< longint > espressopp::FixedQuadrupleList::getQuadrupleList () virtual
Definition at line 158 of file FixedQuadrupleList.cpp.
References beforeSendParticles(), and globalQuadruples.
getQuadruples()
python::list espressopp::FixedQuadrupleList::getQuadruples ()
Definition at line 146 of file FixedQuadrupleList.cpp.
References globalQuadruples.
Referenced by espressopp::FixedQuadrupleListAdress::registerPython(), and registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::FixedQuadrupleList::LOG4ESPP_DECL_LOGGER (theLogger) static private
Referenced by size().
onParticlesChanged()
void espressopp::FixedQuadrupleList::onParticlesChanged () virtual
Reimplemented in espressopp::FixedQuadrupleListAdress.
Definition at line 242 of file FixedQuadrupleList.cpp.
References add(), espressopp::System::comm, globalQuadruples, LOG4ESPP_INFO, espressopp::esutil::Error::setException(), and storage.
Referenced by FixedQuadrupleList().
registerPython()
void espressopp::FixedQuadrupleList::registerPython () static
Definition at line 300 of file FixedQuadrupleList.cpp.
References add(), getQuadruples(), remove(), and size().
Referenced by espressopp::registerPython(), and size().
remove()
void espressopp::FixedQuadrupleList::remove (void)
Definition at line 290 of file FixedQuadrupleList.cpp.
References globalQuadruples, sigAfterRecv, and sigBeforeSend.
Referenced by registerPython().
size()
int espressopp::FixedQuadrupleList::size () inline
Get the number of quadruples in the GlobalQuadruples list.
Definition at line 67 of file FixedQuadrupleList.hpp.
References LOG4ESPP_DECL_LOGGER(), and registerPython().
Referenced by afterRecvParticles(), espressopp::FixedQuadrupleListAdress::registerPython(), and registerPython().
Member Data Documentation
globalQuadruples
GlobalQuadruples espressopp::FixedQuadrupleList::globalQuadruples protected
Definition at line 45 of file FixedQuadrupleList.hpp.
Referenced by espressopp::FixedQuadrupleListAdress::add(), add(), afterRecvParticles(), espressopp::FixedQuadrupleListAdress::beforeSendATParticles(), beforeSendParticles(), getQuadrupleList(), getQuadruples(), espressopp::FixedQuadrupleListAdress::onParticlesChanged(), onParticlesChanged(), and remove().
sigAfterRecv
boost::signals2::connection espressopp::FixedQuadrupleList::sigAfterRecv protected
Definition at line 41 of file FixedQuadrupleList.hpp.
Referenced by FixedQuadrupleList(), espressopp::FixedQuadrupleListAdress::FixedQuadrupleListAdress(), remove(), and ~FixedQuadrupleList().
sigBeforeSend
boost::signals2::connection espressopp::FixedQuadrupleList::sigBeforeSend protected
Definition at line 41 of file FixedQuadrupleList.hpp.
Referenced by FixedQuadrupleList(), espressopp::FixedQuadrupleListAdress::FixedQuadrupleListAdress(), remove(), and ~FixedQuadrupleList().
sigOnParticlesChanged
boost::signals2::connection espressopp::FixedQuadrupleList::sigOnParticlesChanged protected
Definition at line 41 of file FixedQuadrupleList.hpp.
Referenced by FixedQuadrupleList(), and ~FixedQuadrupleList().
storage
shared_ptr< storage::Storage > espressopp::FixedQuadrupleList::storage protected
Definition at line 42 of file FixedQuadrupleList.hpp.
Referenced by espressopp::FixedQuadrupleListAdress::add(), add(), FixedQuadrupleList(), espressopp::FixedQuadrupleListAdress::onParticlesChanged(), and onParticlesChanged().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/FixedQuadrupleList.hpp
/home/espressopp/espressopp/src/FixedQuadrupleList.cpp