ESPResSo++: espressopp::FixedTupleListAdress Class Reference
espressopp::FixedTupleListAdress Class Reference
#include <FixedTupleListAdress.hpp>
Public Types
typedef ESPPIterator< std::map
< Particle *, std::vector
< Particle * > > > Iterator
Public Member Functions
FixedTupleListAdress (shared_ptr< storage::Storage > _storage)
~FixedTupleListAdress ()
void add (longint pid)
void addTs ()
void beforeSendParticles (ParticleList &pl, class OutBuffer &buf)
void afterRecvParticles (ParticleList &pl, class InBuffer &buf)
void onParticlesChanged ()
void add (Particle *p, std::vector< Particle * > particles)
Static Public Member Functions
static void registerPython ()
Public Attributes
boost::signals2::signal2< void,
std::vector< longint >
&, class OutBuffer & > beforeSendATParticles
boost::signals2::signal2< void,
ParticleList &, class InBuffer & > afterRecvATParticles
Protected Types
typedef std::vector< longint > tuple
typedef boost::unordered_map
< longint, tuple > GlobalTuples
typedef std::map< Particle
*, std::vector< Particle * > > Super
Protected Attributes
boost::signals2::connection sigOnTupleChanged
boost::signals2::connection sigAfterRecv
boost::signals2::connection sigBeforeSend
shared_ptr< storage::Storage > storage
GlobalTuples globalTuples
Private Member Functions
bool addT (tuple pids)
Static Private Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Private Attributes
tuple tmppids
Detailed Description
Definition at line 37 of file FixedTupleListAdress.hpp.
Member Typedef Documentation
typedef boost::unordered_map<longint, tuple> espressopp::FixedTupleListAdress::GlobalTuples protected
Definition at line 42 of file FixedTupleListAdress.hpp.
typedef ESPPIterator<std::map< Particle *, std::vector< Particle * > > > espressopp::esutil::ESPPContainer< std::map< Particle *, std::vector< Particle * > > >::Iterator inherited
Definition at line 66 of file ESPPIterator.hpp.
typedef std::map< Particle *, std::vector< Particle * > > espressopp::esutil::ESPPContainer< std::map< Particle *, std::vector< Particle * > > >::Super protected inherited
Definition at line 64 of file ESPPIterator.hpp.
typedef std::vector<longint> espressopp::FixedTupleListAdress::tuple protected
Definition at line 41 of file FixedTupleListAdress.hpp.
Constructor & Destructor Documentation
espressopp::FixedTupleListAdress::FixedTupleListAdress (shared_ptr< storage::Storage > _storage)
Definition at line 44 of file FixedTupleListAdress.cpp.
References afterRecvParticles(), beforeSendParticles(), LOG4ESPP_INFO, onParticlesChanged(), sigAfterRecv, sigBeforeSend, sigOnTupleChanged, and storage.
espressopp::FixedTupleListAdress::~FixedTupleListAdress ()
Definition at line 57 of file FixedTupleListAdress.cpp.
References LOG4ESPP_INFO, sigAfterRecv, sigBeforeSend, and sigOnTupleChanged.
Member Function Documentation
void espressopp::FixedTupleListAdress::add (longint pid) inline
Definition at line 50 of file FixedTupleListAdress.hpp.
References tmppids.
Referenced by addT(), onParticlesChanged(), and registerPython().
void espressopp::TupleList::add (Particle * p, std::vector< Particle * > particles) inline inherited
Definition at line 470 of file Particle.hpp.
Referenced by espressopp::FixedTupleList::addTuple(), and espressopp::FixedTupleList::onParticlesChanged().
bool espressopp::FixedTupleListAdress::addT (tuple pids) private
Definition at line 65 of file FixedTupleListAdress.cpp.
References add(), espressopp::esutil::Error::checkException(), espressopp::System::comm, globalTuples, LOG4ESPP_INFO, espressopp::esutil::Error::setException(), and storage.
Referenced by addTs().
void espressopp::FixedTupleListAdress::addTs () inline
Definition at line 51 of file FixedTupleListAdress.hpp.
References addT(), and tmppids.
Referenced by registerPython().
void espressopp::FixedTupleListAdress::afterRecvParticles (ParticleList & pl, class InBuffer & buf)
Definition at line 176 of file FixedTupleListAdress.cpp.
References espressopp::Particle::id(), LOG4ESPP_DEBUG, and espressopp::InBuffer::read().
Referenced by FixedTupleListAdress().
void espressopp::FixedTupleListAdress::beforeSendParticles (ParticleList & pl, class OutBuffer & buf)
Definition at line 122 of file FixedTupleListAdress.cpp.
References espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_DEBUG, and espressopp::OutBuffer::write().
Referenced by FixedTupleListAdress().
static espressopp::FixedTupleListAdress::LOG4ESPP_DECL_LOGGER (theLogger) static private
void espressopp::FixedTupleListAdress::onParticlesChanged ()
Definition at line 292 of file FixedTupleListAdress.cpp.
References add(), globalTuples, espressopp::Particle::image(), LOG4ESPP_INFO, espressopp::Particle::position(), and storage.
Referenced by FixedTupleListAdress().
void espressopp::FixedTupleListAdress::registerPython () static
Definition at line 365 of file FixedTupleListAdress.cpp.
References add(), and addTs().
Referenced by espressopp::registerPython().
Member Data Documentation
boost::signals2::signal2<void, ParticleList&, class InBuffer&> espressopp::FixedTupleListAdress::afterRecvATParticles
Definition at line 63 of file FixedTupleListAdress.hpp.
boost::signals2::signal2<void, std::vector<longint>&, class OutBuffer&> espressopp::FixedTupleListAdress::beforeSendATParticles
Definition at line 61 of file FixedTupleListAdress.hpp.
GlobalTuples espressopp::FixedTupleListAdress::globalTuples protected
Definition at line 43 of file FixedTupleListAdress.hpp.
Referenced by addT(), and onParticlesChanged().
boost::signals2::connection espressopp::FixedTupleListAdress::sigAfterRecv protected
Definition at line 39 of file FixedTupleListAdress.hpp.
Referenced by FixedTupleListAdress(), and ~FixedTupleListAdress().
boost::signals2::connection espressopp::FixedTupleListAdress::sigBeforeSend protected
Definition at line 39 of file FixedTupleListAdress.hpp.
Referenced by FixedTupleListAdress(), and ~FixedTupleListAdress().
boost::signals2::connection espressopp::FixedTupleListAdress::sigOnTupleChanged protected
Definition at line 39 of file FixedTupleListAdress.hpp.
Referenced by FixedTupleListAdress(), and ~FixedTupleListAdress().
shared_ptr<storage::Storage> espressopp::FixedTupleListAdress::storage protected
Definition at line 40 of file FixedTupleListAdress.hpp.
Referenced by addT(), FixedTupleListAdress(), and onParticlesChanged().
tuple espressopp::FixedTupleListAdress::tmppids private
Definition at line 68 of file FixedTupleListAdress.hpp.
Referenced by add(), and addTs().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/FixedTupleListAdress.hpp
/home/travis/build/espressopp/espressopp/src/FixedTupleListAdress.cpp