ESPResSo++: espressopp::interaction::CoulombKSpaceP3M Class Reference
espressopp::interaction::CoulombKSpaceP3M Class Reference
This class provides methods to compute forces and energies of the CoulombKSpaceP3M part.
#include <CoulombKSpaceP3M.hpp>
Public Member Functions
CoulombKSpaceP3M (shared_ptr< System > _system, real _coulomb_prefactor, real _alpha, Int3D _M, int _P, real _rcut, int _interpolation)
~CoulombKSpaceP3M ()
void preset ()
void setPrefactor (real _prefactor)
real getPrefactor () const
void setAlpha (real _alpha)
real getAlpha () const
void setMesh (Int3D _M)
Int3D getMesh () const
void setP (int _P)
int getP () const
void setCutoff (real _rc)
real getCutoff () const
void setInterpolation (int _interpolation)
int getInterpolation () const
void initialize ()
void getParticleNumber ()
void count_charges (CellList realCells)
void precalc_interpol_charge_assignment_f ()
void calc_differential_operator ()
void create_mesh (CellList realCells)
void gen_mesh (CellList realCells)
void assign_charge_for_single_particle (real q, Real3D particle_pos)
void calc_opt_influence_function ()
void calc_m_shift ()
void aliasing_sum (Int3D i, Real3D *nominator, real *denominator)
real sinc (real x)
taken from Deserno's code Calculates the sinc-function as sin(PI*x)/(PI*x).
real sinc (Real3D X)
real dround (real x)
Real3D dround (Real3D x)
void set_fftw_array ()
void set_plan_frw ()
void set_plan_bcw ()
void clean_fftw ()
real _computeEnergy (CellList realCells)
void common_part (CellList realCells, int iii)
bool _computeForce (CellList realCells)
dcomplex swap_complex (dcomplex C)
real _computeVirial (CellList realcells)
Tensor _computeVirialTensor (CellList realcells)
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &dist, real distSqr) const
real asignment_f1 (real x, int k, int P)
real asignment_f2 (int i, real x, int P)
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
real _computeEnergyDeriv (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
CoulombKSpaceP3M * derived_this ()
const CoulombKSpaceP3M * derived_this () const
Protected Attributes
boost::signals2::connection connectionRecalcKVec
boost::signals2::connection connectionGetParticleNumber
real cutoff
real cutoffSqr
real shift
bool autoShift
Private Attributes
shared_ptr< System > system
Real3D d_mesh
Real3D d_inv
real C_pref
real alpha
Int3D M
int P
real rc
int interpolation
int MMM
vector< vector< real > > precalc_interp_caf
vector< vector< real > > mesh_shift
vector< vector< real > > d_op
vector< real > gf
vector< dcomplex > QQQ
vector< vector< dcomplex > > phi
vector< Int3D > g_ca
vector< vector< real > > q_l
vector< vector< vector< int > > > map_indx
int nParticles
Real3D sysL
real sumq_2
real sum_q2
real af_coef [8][7][7]
fftw_complex * in_array
fftw_plan plan
int MM [3]
Static Private Attributes
static const int brillouin = 1
Detailed Description
This class provides methods to compute forces and energies of the CoulombKSpaceP3M part.
The code is based on M.Deserno's work. Reference in literature M. Deserno, C.Holm, J.Chem. Phys, 109[18] (1998) 7694
Definition at line 69 of file CoulombKSpaceP3M.hpp.
Constructor & Destructor Documentation
CoulombKSpaceP3M()
espressopp::interaction::CoulombKSpaceP3M::CoulombKSpaceP3M (shared_ptr< System > _system, real _coulomb_prefactor, real _alpha, Int3D _M, int _P, real _rcut, int _interpolation)
Definition at line 35 of file CoulombKSpaceP3M.cpp.
References af_coef, connectionGetParticleNumber, connectionRecalcKVec, count_charges(), getParticleNumber(), initialize(), preset(), and system.
~CoulombKSpaceP3M()
espressopp::interaction::CoulombKSpaceP3M::~CoulombKSpaceP3M ()
Definition at line 217 of file CoulombKSpaceP3M.cpp.
References clean_fftw().
Member Function Documentation
_computeEnergy() [1/5]
real espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >::_computeEnergy (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 242 of file Potential.hpp.
_computeEnergy() [2/5]
real espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >::_computeEnergy (const Real3D & dist) const inline inherited
Definition at line 257 of file Potential.hpp.
_computeEnergy() [3/5]
real espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >::_computeEnergy (real dist) const inline inherited
Definition at line 264 of file Potential.hpp.
_computeEnergy() [4/5]
real espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 250 of file Potential.hpp.
_computeEnergy() [5/5]
real espressopp::interaction::CoulombKSpaceP3M::_computeEnergy (CellList realCells) inline
Definition at line 429 of file CoulombKSpaceP3M.hpp.
References M_PIl.
_computeEnergyDeriv()
real espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >::_computeEnergyDeriv (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 285 of file Potential.hpp.
_computeEnergySqr()
real espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >::_computeEnergySqr (real distSqr) const inline inherited
Definition at line 271 of file Potential.hpp.
_computeEnergySqrRaw()
real espressopp::interaction::CoulombKSpaceP3M::_computeEnergySqrRaw (real distSqr) const inline
Definition at line 598 of file CoulombKSpaceP3M.hpp.
References espressopp::esutil::Error::setException().
_computeForce() [1/4]
bool espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const inline inherited
Definition at line 313 of file Potential.hpp.
_computeForce() [2/4]
bool espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >::_computeForce (Real3D & force, const Real3D & dist) const inline inherited
Definition at line 328 of file Potential.hpp.
_computeForce() [3/4]
bool espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 321 of file Potential.hpp.
_computeForce() [4/4]
bool espressopp::interaction::CoulombKSpaceP3M::_computeForce (CellList realCells) inline
Definition at line 516 of file CoulombKSpaceP3M.hpp.
References espressopp::Particle::force(), espressopp::Particle::id(), and espressopp::iterator::CellListIterator::isValid().
_computeForceRaw()
bool espressopp::interaction::CoulombKSpaceP3M::_computeForceRaw (Real3D & force, const Real3D & dist, real distSqr) const inline
Definition at line 605 of file CoulombKSpaceP3M.hpp.
References espressopp::esutil::Error::setException().
_computeVirial()
real espressopp::interaction::CoulombKSpaceP3M::_computeVirial (CellList realcells) inline
Definition at line 577 of file CoulombKSpaceP3M.hpp.
_computeVirialTensor()
Tensor espressopp::interaction::CoulombKSpaceP3M::_computeVirialTensor (CellList realcells) inline
Definition at line 586 of file CoulombKSpaceP3M.hpp.
aliasing_sum()
void espressopp::interaction::CoulombKSpaceP3M::aliasing_sum (Int3D i, Real3D * nominator, real * denominator) inline
Definition at line 319 of file CoulombKSpaceP3M.hpp.
References M_PIl, and espressopp::Real3D::sqr().
asignment_f1()
real espressopp::interaction::CoulombKSpaceP3M::asignment_f1 (real x, int k, int P) inline
Definition at line 614 of file CoulombKSpaceP3M.hpp.
References espressopp::esutil::Error::checkException(), and espressopp::esutil::Error::setException().
asignment_f2()
real espressopp::interaction::CoulombKSpaceP3M::asignment_f2 (int i, real x, int P) inline
Definition at line 632 of file CoulombKSpaceP3M.hpp.
assign_charge_for_single_particle()
void espressopp::interaction::CoulombKSpaceP3M::assign_charge_for_single_particle (real q, Real3D particle_pos) inline
Definition at line 280 of file CoulombKSpaceP3M.hpp.
calc_differential_operator()
void espressopp::interaction::CoulombKSpaceP3M::calc_differential_operator () inline
Definition at line 266 of file CoulombKSpaceP3M.hpp.
calc_m_shift()
void espressopp::interaction::CoulombKSpaceP3M::calc_m_shift () inline
Definition at line 309 of file CoulombKSpaceP3M.hpp.
calc_opt_influence_function()
void espressopp::interaction::CoulombKSpaceP3M::calc_opt_influence_function () inline
Definition at line 284 of file CoulombKSpaceP3M.hpp.
References espressopp::Real3D::sqr().
clean_fftw()
void espressopp::interaction::CoulombKSpaceP3M::clean_fftw () inline
Definition at line 422 of file CoulombKSpaceP3M.hpp.
Referenced by ~CoulombKSpaceP3M().
common_part()
void espressopp::interaction::CoulombKSpaceP3M::common_part (CellList realCells, int iii) inline
Definition at line 450 of file CoulombKSpaceP3M.hpp.
References espressopp::Particle::id(), espressopp::iterator::CellListIterator::isValid(), espressopp::Particle::position(), and espressopp::Particle::q().
computeEnergy() [1/3]
real espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >::computeEnergy (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 213 of file Potential.hpp.
computeEnergy() [2/3]
real espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >::computeEnergy (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 221 of file Potential.hpp.
computeEnergy() [3/3]
real espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >::computeEnergy (real dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 228 of file Potential.hpp.
computeEnergySqr()
real espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >::computeEnergySqr (real distsqr) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 235 of file Potential.hpp.
computeForce() [1/2]
Real3D espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >::computeForce (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 295 of file Potential.hpp.
computeForce() [2/2]
Real3D espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >::computeForce (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 303 of file Potential.hpp.
count_charges()
void espressopp::interaction::CoulombKSpaceP3M::count_charges (CellList realCells) inline
Definition at line 236 of file CoulombKSpaceP3M.hpp.
References espressopp::iterator::CellListIterator::isValid(), and espressopp::Particle::q().
Referenced by CoulombKSpaceP3M().
create_mesh()
void espressopp::interaction::CoulombKSpaceP3M::create_mesh (CellList realCells) inline
Definition at line 276 of file CoulombKSpaceP3M.hpp.
derived_this() [1/2]
CoulombKSpaceP3M * espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >::derived_this () inline protected inherited
Definition at line 123 of file Potential.hpp.
derived_this() [2/2]
const CoulombKSpaceP3M * espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >::derived_this () const inline protected inherited
Definition at line 127 of file Potential.hpp.
dround() [1/2]
real espressopp::interaction::CoulombKSpaceP3M::dround (real x) inline
Definition at line 406 of file CoulombKSpaceP3M.hpp.
dround() [2/2]
Real3D espressopp::interaction::CoulombKSpaceP3M::dround (Real3D x) inline
Definition at line 407 of file CoulombKSpaceP3M.hpp.
gen_mesh()
void espressopp::interaction::CoulombKSpaceP3M::gen_mesh (CellList realCells) inline
Definition at line 278 of file CoulombKSpaceP3M.hpp.
getAlpha()
real espressopp::interaction::CoulombKSpaceP3M::getAlpha () const inline
Definition at line 173 of file CoulombKSpaceP3M.hpp.
getCutoff()
real espressopp::interaction::CoulombKSpaceP3M::getCutoff () const inline virtual
Reimplemented from espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >.
Definition at line 188 of file CoulombKSpaceP3M.hpp.
getInterpolation()
int espressopp::interaction::CoulombKSpaceP3M::getInterpolation () const inline
Definition at line 193 of file CoulombKSpaceP3M.hpp.
getMesh()
Int3D espressopp::interaction::CoulombKSpaceP3M::getMesh () const inline
Definition at line 178 of file CoulombKSpaceP3M.hpp.
getP()
int espressopp::interaction::CoulombKSpaceP3M::getP () const inline
Definition at line 183 of file CoulombKSpaceP3M.hpp.
getParticleNumber()
void espressopp::interaction::CoulombKSpaceP3M::getParticleNumber () inline
Definition at line 231 of file CoulombKSpaceP3M.hpp.
Referenced by CoulombKSpaceP3M().
getPrefactor()
real espressopp::interaction::CoulombKSpaceP3M::getPrefactor () const inline
Definition at line 168 of file CoulombKSpaceP3M.hpp.
Referenced by registerPython().
getShift()
real espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >::getShift () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 186 of file Potential.hpp.
initialize()
void espressopp::interaction::CoulombKSpaceP3M::initialize () inline
Definition at line 196 of file CoulombKSpaceP3M.hpp.
Referenced by CoulombKSpaceP3M().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
Referenced by espressopp::interaction::Potential::~Potential().
precalc_interpol_charge_assignment_f()
void espressopp::interaction::CoulombKSpaceP3M::precalc_interpol_charge_assignment_f () inline
Definition at line 253 of file CoulombKSpaceP3M.hpp.
preset()
void espressopp::interaction::CoulombKSpaceP3M::preset () inline
Definition at line 138 of file CoulombKSpaceP3M.hpp.
Referenced by CoulombKSpaceP3M().
registerPython()
void espressopp::interaction::CoulombKSpaceP3M::registerPython () static
Definition at line 230 of file CoulombKSpaceP3M.cpp.
References getPrefactor(), and setPrefactor().
Referenced by espressopp::interaction::registerPython().
set_fftw_array()
void espressopp::interaction::CoulombKSpaceP3M::set_fftw_array () inline
Definition at line 413 of file CoulombKSpaceP3M.hpp.
set_plan_bcw()
void espressopp::interaction::CoulombKSpaceP3M::set_plan_bcw () inline
Definition at line 419 of file CoulombKSpaceP3M.hpp.
set_plan_frw()
void espressopp::interaction::CoulombKSpaceP3M::set_plan_frw () inline
Definition at line 416 of file CoulombKSpaceP3M.hpp.
setAlpha()
void espressopp::interaction::CoulombKSpaceP3M::setAlpha (real _alpha) inline
Definition at line 169 of file CoulombKSpaceP3M.hpp.
setAutoShift()
real espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >::setAutoShift () inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 192 of file Potential.hpp.
setCutoff()
void espressopp::interaction::CoulombKSpaceP3M::setCutoff (real _rc) inline virtual
Reimplemented from espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >.
Definition at line 184 of file CoulombKSpaceP3M.hpp.
setInterpolation()
void espressopp::interaction::CoulombKSpaceP3M::setInterpolation (int _interpolation) inline
Definition at line 189 of file CoulombKSpaceP3M.hpp.
setMesh()
void espressopp::interaction::CoulombKSpaceP3M::setMesh (Int3D _M) inline
Definition at line 174 of file CoulombKSpaceP3M.hpp.
setP()
void espressopp::interaction::CoulombKSpaceP3M::setP (int _P) inline
Definition at line 179 of file CoulombKSpaceP3M.hpp.
setPrefactor()
void espressopp::interaction::CoulombKSpaceP3M::setPrefactor (real _prefactor) inline
Definition at line 164 of file CoulombKSpaceP3M.hpp.
Referenced by registerPython().
setShift()
void espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >::setShift (real _shift) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 177 of file Potential.hpp.
sinc() [1/2]
real espressopp::interaction::CoulombKSpaceP3M::sinc (real x) inline
taken from Deserno's code Calculates the sinc-function as sin(PI*x)/(PI*x).
(same convention as in Hockney/Eastwood). In order to avoid divisions by 0, arguments, whose modulus is smaller than epsi, will be evaluated by an 8th order Taylor expansion of the sinc function. Note that the difference between sinc(x) and this expansion is smaller than 0.235e-12, if x is smaller than 0.1. (The next term in the expansion is the 10th order contribution PI^10/39916800 * x^10 = 0.2346...*x^12). This expansion should also save time, since it reduces the number of function calls to sin().
Definition at line 382 of file CoulombKSpaceP3M.hpp.
References M_PIl.
sinc() [2/2]
real espressopp::interaction::CoulombKSpaceP3M::sinc (Real3D X) inline
Definition at line 400 of file CoulombKSpaceP3M.hpp.
swap_complex()
dcomplex espressopp::interaction::CoulombKSpaceP3M::swap_complex (dcomplex C) inline
Definition at line 570 of file CoulombKSpaceP3M.hpp.
updateAutoShift()
void espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >::updateAutoShift () inline inherited
Definition at line 205 of file Potential.hpp.
Member Data Documentation
af_coef
real espressopp::interaction::CoulombKSpaceP3M::af_coef[8][7][7] private
Definition at line 115 of file CoulombKSpaceP3M.hpp.
Referenced by CoulombKSpaceP3M().
alpha
real espressopp::interaction::CoulombKSpaceP3M::alpha private
Definition at line 78 of file CoulombKSpaceP3M.hpp.
autoShift
bool espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >::autoShift protected inherited
Definition at line 121 of file Potential.hpp.
brillouin
const int espressopp::interaction::CoulombKSpaceP3M::brillouin = 1 static private
Definition at line 88 of file CoulombKSpaceP3M.hpp.
C_pref
real espressopp::interaction::CoulombKSpaceP3M::C_pref private
Definition at line 77 of file CoulombKSpaceP3M.hpp.
connectionGetParticleNumber
boost::signals2::connection espressopp::interaction::CoulombKSpaceP3M::connectionGetParticleNumber protected
Definition at line 724 of file CoulombKSpaceP3M.hpp.
Referenced by CoulombKSpaceP3M().
connectionRecalcKVec
boost::signals2::connection espressopp::interaction::CoulombKSpaceP3M::connectionRecalcKVec protected
Definition at line 722 of file CoulombKSpaceP3M.hpp.
Referenced by CoulombKSpaceP3M().
cutoff
real espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >::cutoff protected inherited
Definition at line 118 of file Potential.hpp.
cutoffSqr
real espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >::cutoffSqr protected inherited
Definition at line 119 of file Potential.hpp.
d_inv
Real3D espressopp::interaction::CoulombKSpaceP3M::d_inv private
Definition at line 75 of file CoulombKSpaceP3M.hpp.
d_mesh
Real3D espressopp::interaction::CoulombKSpaceP3M::d_mesh private
Definition at line 74 of file CoulombKSpaceP3M.hpp.
d_op
vector< vector<real> > espressopp::interaction::CoulombKSpaceP3M::d_op private
Definition at line 94 of file CoulombKSpaceP3M.hpp.
g_ca
vector<Int3D> espressopp::interaction::CoulombKSpaceP3M::g_ca private
Definition at line 105 of file CoulombKSpaceP3M.hpp.
gf
vector<real> espressopp::interaction::CoulombKSpaceP3M::gf private
Definition at line 97 of file CoulombKSpaceP3M.hpp.
in_array
fftw_complex* espressopp::interaction::CoulombKSpaceP3M::in_array private
Definition at line 118 of file CoulombKSpaceP3M.hpp.
interpolation
int espressopp::interaction::CoulombKSpaceP3M::interpolation private
Definition at line 82 of file CoulombKSpaceP3M.hpp.
M
Int3D espressopp::interaction::CoulombKSpaceP3M::M private
Definition at line 79 of file CoulombKSpaceP3M.hpp.
map_indx
vector< vector< vector< int > > > espressopp::interaction::CoulombKSpaceP3M::map_indx private
Definition at line 109 of file CoulombKSpaceP3M.hpp.
mesh_shift
vector< vector<real> > espressopp::interaction::CoulombKSpaceP3M::mesh_shift private
Definition at line 92 of file CoulombKSpaceP3M.hpp.
MM
int espressopp::interaction::CoulombKSpaceP3M::MM[3] private
Definition at line 120 of file CoulombKSpaceP3M.hpp.
MMM
int espressopp::interaction::CoulombKSpaceP3M::MMM private
Definition at line 85 of file CoulombKSpaceP3M.hpp.
nParticles
int espressopp::interaction::CoulombKSpaceP3M::nParticles private
Definition at line 111 of file CoulombKSpaceP3M.hpp.
P
int espressopp::interaction::CoulombKSpaceP3M::P private
Definition at line 80 of file CoulombKSpaceP3M.hpp.
phi
vector<vector<dcomplex> > espressopp::interaction::CoulombKSpaceP3M::phi private
Definition at line 102 of file CoulombKSpaceP3M.hpp.
plan
fftw_plan espressopp::interaction::CoulombKSpaceP3M::plan private
Definition at line 119 of file CoulombKSpaceP3M.hpp.
precalc_interp_caf
vector< vector<real> > espressopp::interaction::CoulombKSpaceP3M::precalc_interp_caf private
Definition at line 90 of file CoulombKSpaceP3M.hpp.
q_l
vector< vector< real > > espressopp::interaction::CoulombKSpaceP3M::q_l private
Definition at line 107 of file CoulombKSpaceP3M.hpp.
QQQ
vector< dcomplex > espressopp::interaction::CoulombKSpaceP3M::QQQ private
Definition at line 100 of file CoulombKSpaceP3M.hpp.
rc
real espressopp::interaction::CoulombKSpaceP3M::rc private
Definition at line 81 of file CoulombKSpaceP3M.hpp.
shift
real espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >::shift protected inherited
Definition at line 120 of file Potential.hpp.
sum_q2
real espressopp::interaction::CoulombKSpaceP3M::sum_q2 private
Definition at line 113 of file CoulombKSpaceP3M.hpp.
sumq_2
real espressopp::interaction::CoulombKSpaceP3M::sumq_2 private
Definition at line 113 of file CoulombKSpaceP3M.hpp.
sysL
Real3D espressopp::interaction::CoulombKSpaceP3M::sysL private
Definition at line 112 of file CoulombKSpaceP3M.hpp.
system
shared_ptr< System > espressopp::interaction::CoulombKSpaceP3M::system private
Definition at line 71 of file CoulombKSpaceP3M.hpp.
Referenced by CoulombKSpaceP3M().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/CoulombKSpaceP3M.hpp
/home/espressopp/espressopp/src/interaction/CoulombKSpaceP3M.cpp