ESPResSo++: espressopp::interaction::VSphereSelf Class Reference
espressopp::interaction::VSphereSelf Class Reference abstract
This class provides methods to compute forces and energies of the VSphereSelf potential.
#include <VSphereSelf.hpp>
Public Member Functions
VSphereSelf ()
VSphereSelf (real _e1, real _a1, real _a2, int _Nb, real _cutoff, real _shift)
VSphereSelf (real _e1, real _a1, real _a2, int _Nb, real _cutoff)
void preset ()
void sete1 (real _e1)
real gete1 () const
void seta1 (real _a1)
real geta1 () const
void seta2 (real _a2)
real geta2 () const
void setNb (int _Nb)
real getNb () const
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &dist, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual real getCutoff () const =0
virtual void setShift (real _shift)
virtual real getShift () const
virtual real getShift () const =0
virtual real setAutoShift ()
void updateAutoShift ()
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)
virtual shared_ptr< FixedPairList > getColVarBondList () const
virtual shared_ptr< FixedPairList > getColVarBondList () const =0
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &fpl)
virtual shared_ptr< FixedTripleList > getColVarAngleList () const
virtual shared_ptr< FixedTripleList > getColVarAngleList () const =0
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fpl)
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const =0
virtual void setColVar (const RealND &cv)
virtual void setColVar (const Real3D &dist, const bc::BC &bc)
virtual RealND getColVar () const
virtual RealND getColVar () const =0
virtual void computeColVarWeights (const Real3D &dist, const bc::BC &bc)
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
real _computeEnergyDeriv (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
VSphereSelf * derived_this ()
const VSphereSelf * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
shared_ptr< FixedPairList > colVarBondList
shared_ptr< FixedTripleList > colVarAngleList
shared_ptr< FixedQuadrupleList > colVarDihedList
RealND colVar
Private Attributes
real e1
real a1
real a16
real a16NbNbNb
real a2
real a22
real a2dNb
real a22dNb
real mth
real mfh
int Nb
int NbNbNb
Detailed Description
This class provides methods to compute forces and energies of the VSphereSelf potential.
Definition at line 44 of file VSphereSelf.hpp.
Constructor & Destructor Documentation
VSphereSelf() [1/3]
espressopp::interaction::VSphereSelf::VSphereSelf () inline
Definition at line 55 of file VSphereSelf.hpp.
References espressopp::infinity, preset(), espressopp::interaction::PotentialTemplate< VSphereSelf >::setCutoff(), and espressopp::interaction::PotentialTemplate< VSphereSelf >::setShift().
VSphereSelf() [2/3]
espressopp::interaction::VSphereSelf::VSphereSelf (real _e1, real _a1, real _a2, int _Nb, real _cutoff, real _shift) inline
Definition at line 62 of file VSphereSelf.hpp.
References preset(), espressopp::interaction::PotentialTemplate< VSphereSelf >::setCutoff(), and espressopp::interaction::PotentialTemplate< VSphereSelf >::setShift().
VSphereSelf() [3/3]
espressopp::interaction::VSphereSelf::VSphereSelf (real _e1, real _a1, real _a2, int _Nb, real _cutoff) inline
Definition at line 70 of file VSphereSelf.hpp.
References espressopp::interaction::PotentialTemplate< VSphereSelf >::autoShift, preset(), espressopp::interaction::PotentialTemplate< VSphereSelf >::setAutoShift(), and espressopp::interaction::PotentialTemplate< VSphereSelf >::setCutoff().
Member Function Documentation
_computeEnergy() [1/4]
real espressopp::interaction::PotentialTemplate< VSphereSelf >::_computeEnergy (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 352 of file Potential.hpp.
_computeEnergy() [2/4]
real espressopp::interaction::PotentialTemplate< VSphereSelf >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 360 of file Potential.hpp.
_computeEnergy() [3/4]
real espressopp::interaction::PotentialTemplate< VSphereSelf >::_computeEnergy (const Real3D & dist) const inline inherited
Definition at line 367 of file Potential.hpp.
_computeEnergy() [4/4]
real espressopp::interaction::PotentialTemplate< VSphereSelf >::_computeEnergy (real dist) const inline inherited
Definition at line 374 of file Potential.hpp.
_computeEnergyDeriv()
real espressopp::interaction::PotentialTemplate< VSphereSelf >::_computeEnergyDeriv (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 395 of file Potential.hpp.
_computeEnergySqr()
real espressopp::interaction::PotentialTemplate< VSphereSelf >::_computeEnergySqr (real distSqr) const inline inherited
Definition at line 381 of file Potential.hpp.
_computeEnergySqrRaw()
real espressopp::interaction::VSphereSelf::_computeEnergySqrRaw (real distSqr) const inline
Definition at line 119 of file VSphereSelf.hpp.
References a1, a2dNb, e1, M_4PI3, mth, and NbNbNb.
_computeForce() [1/3]
bool espressopp::interaction::PotentialTemplate< VSphereSelf >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const inline inherited
Definition at line 423 of file Potential.hpp.
_computeForce() [2/3]
bool espressopp::interaction::PotentialTemplate< VSphereSelf >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 431 of file Potential.hpp.
_computeForce() [3/3]
bool espressopp::interaction::PotentialTemplate< VSphereSelf >::_computeForce (Real3D & force, const Real3D & dist) const inline inherited
Definition at line 438 of file Potential.hpp.
_computeForceRaw()
bool espressopp::interaction::VSphereSelf::_computeForceRaw (Real3D & force, const Real3D & dist, real distSqr) const inline
Definition at line 128 of file VSphereSelf.hpp.
References a16NbNbNb, a22dNb, e1, M_4PI, M_4PI3, and mfh.
computeColVarWeights()
void espressopp::interaction::PotentialTemplate< VSphereSelf >::computeColVarWeights (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 315 of file Potential.hpp.
computeEnergy() [1/3]
real espressopp::interaction::PotentialTemplate< VSphereSelf >::computeEnergy (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 323 of file Potential.hpp.
computeEnergy() [2/3]
real espressopp::interaction::PotentialTemplate< VSphereSelf >::computeEnergy (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 331 of file Potential.hpp.
computeEnergy() [3/3]
real espressopp::interaction::PotentialTemplate< VSphereSelf >::computeEnergy (real dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 338 of file Potential.hpp.
computeEnergySqr()
real espressopp::interaction::PotentialTemplate< VSphereSelf >::computeEnergySqr (real distsqr) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 345 of file Potential.hpp.
computeForce() [1/2]
Real3D espressopp::interaction::PotentialTemplate< VSphereSelf >::computeForce (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 405 of file Potential.hpp.
computeForce() [2/2]
Real3D espressopp::interaction::PotentialTemplate< VSphereSelf >::computeForce (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 413 of file Potential.hpp.
derived_this() [1/2]
VSphereSelf * espressopp::interaction::PotentialTemplate< VSphereSelf >::derived_this inline protected inherited
Definition at line 161 of file Potential.hpp.
derived_this() [2/2]
const VSphereSelf * espressopp::interaction::PotentialTemplate< VSphereSelf >::derived_this inline protected inherited
Definition at line 165 of file Potential.hpp.
geta1()
real espressopp::interaction::VSphereSelf::geta1 () const inline
Definition at line 103 of file VSphereSelf.hpp.
References a1.
Referenced by registerPython().
geta2()
real espressopp::interaction::VSphereSelf::geta2 () const inline
Definition at line 110 of file VSphereSelf.hpp.
References a2.
Referenced by registerPython().
getColVar() [1/2]
RealND espressopp::interaction::PotentialTemplate< VSphereSelf >::getColVar inline virtual inherited
Definition at line 309 of file Potential.hpp.
getColVar() [2/2]
virtual RealND espressopp::interaction::Potential::getColVar () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getColVarAngleList() [1/2]
shared_ptr< FixedTripleList > espressopp::interaction::PotentialTemplate< VSphereSelf >::getColVarAngleList inline virtual inherited
Definition at line 273 of file Potential.hpp.
getColVarAngleList() [2/2]
virtual shared_ptr<FixedTripleList> espressopp::interaction::Potential::getColVarAngleList () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getColVarBondList() [1/2]
shared_ptr< FixedPairList > espressopp::interaction::PotentialTemplate< VSphereSelf >::getColVarBondList inline virtual inherited
Definition at line 259 of file Potential.hpp.
getColVarBondList() [2/2]
virtual shared_ptr<FixedPairList> espressopp::interaction::Potential::getColVarBondList () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getColVarDihedList() [1/2]
shared_ptr< FixedQuadrupleList > espressopp::interaction::PotentialTemplate< VSphereSelf >::getColVarDihedList inline virtual inherited
Definition at line 287 of file Potential.hpp.
getColVarDihedList() [2/2]
virtual shared_ptr<FixedQuadrupleList> espressopp::interaction::Potential::getColVarDihedList () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
getCutoff() [1/2]
real espressopp::interaction::PotentialTemplate< VSphereSelf >::getCutoff inline virtual inherited
Definition at line 210 of file Potential.hpp.
getCutoff() [2/2]
virtual real espressopp::interaction::Potential::getCutoff () const pure virtual inherited
Implemented in espressopp::interaction::CoulombKSpaceP3M, and espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
gete1()
real espressopp::interaction::VSphereSelf::gete1 () const inline
Definition at line 96 of file VSphereSelf.hpp.
References e1.
Referenced by registerPython().
getNb()
real espressopp::interaction::VSphereSelf::getNb () const inline
Definition at line 117 of file VSphereSelf.hpp.
References Nb.
Referenced by registerPython().
getShift() [1/2]
real espressopp::interaction::PotentialTemplate< VSphereSelf >::getShift inline virtual inherited
Definition at line 225 of file Potential.hpp.
getShift() [2/2]
virtual real espressopp::interaction::Potential::getShift () const pure virtual inherited
Implemented in espressopp::interaction::PotentialTemplate< Derived >.
Referenced by espressopp::interaction::Potential::registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
preset()
void espressopp::interaction::VSphereSelf::preset () inline
Definition at line 79 of file VSphereSelf.hpp.
References a1, a16, a16NbNbNb, a2, a22, a22dNb, a2dNb, mfh, mth, Nb, and NbNbNb.
Referenced by seta1(), seta2(), sete1(), setNb(), and VSphereSelf().
registerPython()
void espressopp::interaction::VSphereSelf::registerPython () static
Definition at line 36 of file VSphereSelf.cpp.
References geta1(), geta2(), gete1(), getNb(), seta1(), seta2(), sete1(), and setNb().
Referenced by espressopp::interaction::registerPython().
seta1()
void espressopp::interaction::VSphereSelf::seta1 (real _a1) inline
Definition at line 98 of file VSphereSelf.hpp.
References a1, preset(), and espressopp::interaction::PotentialTemplate< VSphereSelf >::updateAutoShift().
Referenced by registerPython().
seta2()
void espressopp::interaction::VSphereSelf::seta2 (real _a2) inline
Definition at line 105 of file VSphereSelf.hpp.
References a2, preset(), and espressopp::interaction::PotentialTemplate< VSphereSelf >::updateAutoShift().
Referenced by registerPython().
setAutoShift()
real espressopp::interaction::PotentialTemplate< VSphereSelf >::setAutoShift inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 231 of file Potential.hpp.
setColVar() [1/2]
void espressopp::interaction::PotentialTemplate< VSphereSelf >::setColVar (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 301 of file Potential.hpp.
setColVar() [2/2]
void espressopp::interaction::PotentialTemplate< VSphereSelf >::setColVar (const RealND & cv) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 294 of file Potential.hpp.
setColVarAngleList()
void espressopp::interaction::PotentialTemplate< VSphereSelf >::setColVarAngleList (const shared_ptr< FixedTripleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 266 of file Potential.hpp.
setColVarBondList()
void espressopp::interaction::PotentialTemplate< VSphereSelf >::setColVarBondList (const shared_ptr< FixedPairList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 252 of file Potential.hpp.
setColVarDihedList()
void espressopp::interaction::PotentialTemplate< VSphereSelf >::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 280 of file Potential.hpp.
setCutoff()
void espressopp::interaction::PotentialTemplate< VSphereSelf >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 201 of file Potential.hpp.
sete1()
void espressopp::interaction::VSphereSelf::sete1 (real _e1) inline
Definition at line 91 of file VSphereSelf.hpp.
References e1, preset(), and espressopp::interaction::PotentialTemplate< VSphereSelf >::updateAutoShift().
Referenced by registerPython().
setNb()
void espressopp::interaction::VSphereSelf::setNb (int _Nb) inline
Definition at line 112 of file VSphereSelf.hpp.
References Nb, preset(), and espressopp::interaction::PotentialTemplate< VSphereSelf >::updateAutoShift().
Referenced by registerPython().
setShift()
void espressopp::interaction::PotentialTemplate< VSphereSelf >::setShift (real _shift) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 216 of file Potential.hpp.
updateAutoShift()
void espressopp::interaction::PotentialTemplate< VSphereSelf >::updateAutoShift inline inherited
Definition at line 244 of file Potential.hpp.
Member Data Documentation
a1
real espressopp::interaction::VSphereSelf::a1 private
Definition at line 47 of file VSphereSelf.hpp.
Referenced by _computeEnergySqrRaw(), geta1(), preset(), and seta1().
a16
real espressopp::interaction::VSphereSelf::a16 private
Definition at line 47 of file VSphereSelf.hpp.
Referenced by preset().
a16NbNbNb
real espressopp::interaction::VSphereSelf::a16NbNbNb private
Definition at line 47 of file VSphereSelf.hpp.
Referenced by _computeForceRaw(), and preset().
a2
real espressopp::interaction::VSphereSelf::a2 private
Definition at line 48 of file VSphereSelf.hpp.
Referenced by geta2(), preset(), and seta2().
a22
real espressopp::interaction::VSphereSelf::a22 private
Definition at line 48 of file VSphereSelf.hpp.
Referenced by preset().
a22dNb
real espressopp::interaction::VSphereSelf::a22dNb private
Definition at line 48 of file VSphereSelf.hpp.
Referenced by _computeForceRaw(), and preset().
a2dNb
real espressopp::interaction::VSphereSelf::a2dNb private
Definition at line 48 of file VSphereSelf.hpp.
Referenced by _computeEnergySqrRaw(), and preset().
autoShift
bool espressopp::interaction::PotentialTemplate< VSphereSelf >::autoShift protected inherited
Definition at line 151 of file Potential.hpp.
colVar
RealND espressopp::interaction::PotentialTemplate< VSphereSelf >::colVar protected inherited
Definition at line 159 of file Potential.hpp.
colVarAngleList
shared_ptr<FixedTripleList> espressopp::interaction::PotentialTemplate< VSphereSelf >::colVarAngleList protected inherited
Definition at line 155 of file Potential.hpp.
colVarBondList
shared_ptr<FixedPairList> espressopp::interaction::PotentialTemplate< VSphereSelf >::colVarBondList protected inherited
Definition at line 153 of file Potential.hpp.
colVarDihedList
shared_ptr<FixedQuadrupleList> espressopp::interaction::PotentialTemplate< VSphereSelf >::colVarDihedList protected inherited
Definition at line 157 of file Potential.hpp.
cutoff
real espressopp::interaction::PotentialTemplate< VSphereSelf >::cutoff protected inherited
Definition at line 148 of file Potential.hpp.
cutoffSqr
real espressopp::interaction::PotentialTemplate< VSphereSelf >::cutoffSqr protected inherited
Definition at line 149 of file Potential.hpp.
e1
real espressopp::interaction::VSphereSelf::e1 private
Definition at line 46 of file VSphereSelf.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), gete1(), and sete1().
mfh
real espressopp::interaction::VSphereSelf::mfh private
Definition at line 49 of file VSphereSelf.hpp.
Referenced by _computeForceRaw(), and preset().
mth
real espressopp::interaction::VSphereSelf::mth private
Definition at line 49 of file VSphereSelf.hpp.
Referenced by _computeEnergySqrRaw(), and preset().
Nb
int espressopp::interaction::VSphereSelf::Nb private
Definition at line 50 of file VSphereSelf.hpp.
Referenced by getNb(), preset(), and setNb().
NbNbNb
int espressopp::interaction::VSphereSelf::NbNbNb private
Definition at line 50 of file VSphereSelf.hpp.
Referenced by _computeEnergySqrRaw(), and preset().
shift
real espressopp::interaction::PotentialTemplate< VSphereSelf >::shift protected inherited
Definition at line 150 of file Potential.hpp.
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/VSphereSelf.hpp
/home/espressopp/espressopp/src/interaction/VSphereSelf.cpp