ESPResSo++: espressopp::Int3D Class Reference
espressopp::Int3D Class Reference
#include <Int3D.hpp>
Public Member Functions
Int3D ()
Int3D (int v)
Int3D (int x, int y, int z)
Int3D (const int v[3])
Int3D (const Real3D v)
Int3D & operator= (const Int3D &v)
Int3D & operator= (const int v[3])
int & operator[] (int i)
const int & operator[] (int i) const
int & at (int i)
const int & at (int i) const
void setItem (int i, int v)
int getItem (int i) const
Int3D & operator+= (const Int3D &v)
Int3D & operator-= (const Int3D &v)
bool operator== (const Int3D &v) const
bool operator!= (const Int3D &v) const
Int3D operator+ (const Int3D &v) const
Int3D operator- (const Int3D &v) const
Static Public Member Functions
static void registerPython ()
Private Attributes
int data [3]
Detailed Description
Definition at line 37 of file Int3D.hpp.
Constructor & Destructor Documentation
espressopp::Int3D::Int3D () [inline]
Definition at line 85 of file Int3D.hpp.
References data.
Referenced by operator+(), and operator-().
espressopp::Int3D::Int3D (int v) [inline]
Definition at line 88 of file Int3D.hpp.
References data.
espressopp::Int3D::Int3D (int x, int y, int z) [inline]
Definition at line 91 of file Int3D.hpp.
References data.
espressopp::Int3D::Int3D (const int v[3]) [inline]
Definition at line 97 of file Int3D.hpp.
References data.
espressopp::Int3D::Int3D (const Real3D v) [inline]
Definition at line 101 of file Int3D.hpp.
References data.
Member Function Documentation
int & espressopp::Int3D::at (int i) [inline]
Definition at line 126 of file Int3D.hpp.
Referenced by getItem(), and setItem().
const int & espressopp::Int3D::at (int i) const [inline]
Definition at line 132 of file Int3D.hpp.
int espressopp::Int3D::getItem (int i) const [inline]
Definition at line 141 of file Int3D.hpp.
References at().
Referenced by espressopp::integrator::LatticeBoltzmann::addExtForceLoc(), espressopp::integrator::LBInitConstForce::addForce(), espressopp::integrator::LBInitPeriodicForce::addForce(), espressopp::integrator::LiquidGasLB::collideStream(), espressopp::integrator::LiquidGasLB::computeDensity(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::integrator::LBInitPopUniform::createDenVel(), espressopp::integrator::LBInitPopWave::createDenVel(), espressopp::integrator::LatticeBoltzmann::getExtForceLoc(), espressopp::integrator::LiquidGasLB::getForceLoc(), espressopp::integrator::LiquidGasLB::getLBFluid(), espressopp::integrator::LatticeBoltzmann::getLBFluid(), espressopp::integrator::LatticeBoltzmann::getLBMom(), espressopp::integrator::LiquidGasLB::initFluctuations(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::LiquidGasLB::initGammas(), espressopp::integrator::LatticeBoltzmann::initGammas(), espressopp::integrator::LiquidGasLB::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LiquidGasLB::LiquidGasLB(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), registerPython(), espressopp::integrator::LatticeBoltzmann::setExtForceLoc(), espressopp::integrator::LBInitPeriodicForce::setForce(), espressopp::integrator::LBInitConstForce::setForce(), espressopp::integrator::LiquidGasLB::setForceLoc(), espressopp::integrator::LiquidGasLB::setGhostFluid(), espressopp::integrator::LatticeBoltzmann::setGhostFluid(), espressopp::integrator::LiquidGasLB::setLBFluid(), espressopp::integrator::LatticeBoltzmann::setLBFluid(), espressopp::integrator::LatticeBoltzmann::setLBMom(), espressopp::integrator::LiquidGasLB::streaming(), espressopp::analysis::LBOutputVzOfX::writeOutput(), and espressopp::analysis::LBOutputVzInTime::writeOutput().
bool espressopp::Int3D::operator!= (const Int3D & v) const [inline]
Definition at line 159 of file Int3D.hpp.
Int3D espressopp::Int3D::operator+ (const Int3D & v) const [inline]
Definition at line 163 of file Int3D.hpp.
References Int3D().
Int3D & espressopp::Int3D::operator+= (const Int3D & v) [inline]
Definition at line 145 of file Int3D.hpp.
References data.
Int3D espressopp::Int3D::operator- (const Int3D & v) const [inline]
Definition at line 166 of file Int3D.hpp.
References Int3D().
Int3D & espressopp::Int3D::operator-= (const Int3D & v) [inline]
Definition at line 148 of file Int3D.hpp.
References data.
Int3D & espressopp::Int3D::operator= (const Int3D & v) [inline]
Definition at line 106 of file Int3D.hpp.
References data.
Int3D & espressopp::Int3D::operator= (const int v[3]) [inline]
Definition at line 113 of file Int3D.hpp.
References data.
bool espressopp::Int3D::operator== (const Int3D & v) const [inline]
Definition at line 152 of file Int3D.hpp.
References data.
int & espressopp::Int3D::operator[] (int i) [inline]
Definition at line 120 of file Int3D.hpp.
References data.
const int & espressopp::Int3D::operator[] (int i) const [inline]
Definition at line 123 of file Int3D.hpp.
References data.
void espressopp::Int3D::registerPython () [static]
Definition at line 37 of file Int3D.cpp.
References getItem(), and setItem().
Referenced by espressopp::registerPython().
void espressopp::Int3D::setItem (int i, int v) [inline]
Definition at line 138 of file Int3D.hpp.
References at().
Referenced by registerPython().
Member Data Documentation
int espressopp::Int3D::data[3] [private]
Definition at line 38 of file Int3D.hpp.
Referenced by Int3D(), operator+=(), operator-=(), operator=(), operator==(), and operator[]().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/Int3D.hpp
/home/travis/build/espressopp/espressopp/src/Int3D.cpp