ESPResSo++: espressopp::VerletListAdress Class Reference
espressopp::VerletListAdress Class Reference
Class that builds and stores verlet lists.
#include <VerletListAdress.hpp>
Public Member Functions
VerletListAdress (shared_ptr< System >, real cut, real adrcut, bool rebuildVL, real _dEx, real _dHy)
Build a verlet list of all particle pairs in the storage whose distance is less than a given cutoff.
~VerletListAdress ()
PairList & getPairs ()
PairList & getAdrPairs ()
std::set< longint > & getAdrList ()
std::set< Particle * > & getAdrZone ()
std::set< Particle * > & getCGZone ()
std::vector< Real3D * > & getAdrPositions ()
real getHy ()
real getEx ()
void addAdrParticle (longint pid)
Add an atomistic particle (used for AdResS) to atList.
void setAdrCenter (real x, real y, real z)
bool getAdrCenterSet ()
Real3D getAdrCenter ()
void setAdrRegionType (bool _sphereAdr)
bool getAdrRegionType ()
void rebuild ()
int totalSize () const
Get the total number of pairs for the Verlet list.
bool exclude (longint pid1, longint pid2)
Add pairs to exclusion list.
int getBuilds () const
Get the number of times the Verlet list has been rebuilt.
void setBuilds (int _builds)
Set the number of times the Verlet list has been rebuilt.
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
Register this class so it can be used from Python.
Public Attributes
std::vector< Real3D * > adrPositions
Define the lowest atomistic type number.
Private Member Functions
void checkPair (Particle &pt1, Particle &pt2)
Static Private Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Private Attributes
std::set< longint > adrList
std::set< Particle * > adrZone
std::set< Particle * > cgZone
PairList adrPairs
real dEx
real dHy
real adrsq
real adrcutsq
real adrCutverlet
real cutverlet
real skin
Real3D adrCenter
bool adrCenterSet
bool sphereAdr
PairList vlPairs
boost::unordered_set< std::pair< longint, longint > > exList
real cutsq
int builds
boost::signals2::connection connectionResort
Detailed Description
Class that builds and stores verlet lists.
ToDo: register at system for rebuild
Definition at line 43 of file VerletListAdress.hpp.
Constructor & Destructor Documentation
VerletListAdress()
espressopp::VerletListAdress::VerletListAdress (shared_ptr< System > system, real cut, real adrcut, bool rebuildVL, real _dEx, real _dHy)
Build a verlet list of all particle pairs in the storage whose distance is less than a given cutoff.
Parameters
system is the system for which the verlet list is built
cut is the cutoff value for the
Definition at line 42 of file VerletListAdress.cpp.
References adrCenterSet, adrcutsq, adrCutverlet, adrsq, builds, connectionResort, cutsq, cutverlet, dEx, dHy, LOG4ESPP_INFO, rebuild(), and skin.
~VerletListAdress()
espressopp::VerletListAdress::~VerletListAdress ()
Definition at line 219 of file VerletListAdress.cpp.
References connectionResort, and LOG4ESPP_INFO.
Member Function Documentation
addAdrParticle()
void espressopp::VerletListAdress::addAdrParticle (longint pid)
Add an atomistic particle (used for AdResS) to atList.
Definition at line 197 of file VerletListAdress.cpp.
References adrList.
Referenced by getEx(), and registerPython().
checkPair()
void espressopp::VerletListAdress::checkPair (Particle & pt1, Particle & pt2) private
Definition at line 154 of file VerletListAdress.cpp.
References espressopp::PairList::add(), adrcutsq, adrPairs, adrZone, cutsq, exList, espressopp::Particle::id(), LOG4ESPP_TRACE, espressopp::Particle::position(), espressopp::Real3D::sqr(), and vlPairs.
Referenced by rebuild().
exclude()
bool espressopp::VerletListAdress::exclude (longint pid1, longint pid2)
Add pairs to exclusion list.
Definition at line 192 of file VerletListAdress.cpp.
References exList.
Referenced by registerPython().
getAdrCenter()
Real3D espressopp::VerletListAdress::getAdrCenter ()
Definition at line 207 of file VerletListAdress.cpp.
References adrCenter.
Referenced by getAdrCenterSet().
getAdrCenterSet()
bool espressopp::VerletListAdress::getAdrCenterSet () inline
Definition at line 71 of file VerletListAdress.hpp.
References adrCenterSet, getAdrCenter(), getAdrRegionType(), and setAdrRegionType().
getAdrList()
std::set<longint>& espressopp::VerletListAdress::getAdrList () inline
Definition at line 61 of file VerletListAdress.hpp.
References adrList.
getAdrPairs()
PairList& espressopp::VerletListAdress::getAdrPairs () inline
Definition at line 60 of file VerletListAdress.hpp.
References adrPairs.
getAdrPositions()
std::vector<Real3D*>& espressopp::VerletListAdress::getAdrPositions () inline
Definition at line 64 of file VerletListAdress.hpp.
References adrPositions.
getAdrRegionType()
bool espressopp::VerletListAdress::getAdrRegionType ()
Definition at line 213 of file VerletListAdress.cpp.
References sphereAdr.
Referenced by getAdrCenterSet(), and rebuild().
getAdrZone()
std::set<Particle*>& espressopp::VerletListAdress::getAdrZone () inline
Definition at line 62 of file VerletListAdress.hpp.
References adrZone.
getBuilds()
int espressopp::VerletListAdress::getBuilds () const inline
Get the number of times the Verlet list has been rebuilt.
Definition at line 90 of file VerletListAdress.hpp.
References builds.
Referenced by registerPython().
getCGZone()
std::set<Particle*>& espressopp::VerletListAdress::getCGZone () inline
Definition at line 63 of file VerletListAdress.hpp.
References cgZone.
getEx()
real espressopp::VerletListAdress::getEx () inline
Definition at line 66 of file VerletListAdress.hpp.
References addAdrParticle(), dEx, and setAdrCenter().
getHy()
real espressopp::VerletListAdress::getHy () inline
Definition at line 65 of file VerletListAdress.hpp.
References dHy.
getPairs()
PairList& espressopp::VerletListAdress::getPairs () inline
Definition at line 59 of file VerletListAdress.hpp.
References vlPairs.
getSystem()
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::LatticeBoltzmann::assignMyLattice(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::PIAdressIntegrator::computeKineticEnergy(), espressopp::integrator::PIAdressIntegrator::computeMomentumDrift(), espressopp::integrator::PIAdressIntegrator::computePositionDrift(), espressopp::integrator::PIAdressIntegrator::computeRingEnergy(), espressopp::integrator::PIAdressIntegrator::computeRingEnergyRaw(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::io::DumpXYZ::DumpXYZ(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), rebuild(), espressopp::VerletListTriple::registerPython(), espressopp::VerletList::registerPython(), registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
getSystem1()
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
getSystem2()
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
getSystemRef()
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::addForces(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::addForces(), espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerlet::calcForces(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::PIAdressIntegrator::calcForcesF(), espressopp::integrator::PIAdressIntegrator::calcForcesM(), espressopp::integrator::PIAdressIntegrator::calcForcesS(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeCOM(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeEnergy(), espressopp::integrator::PIAdressIntegrator::computeKineticEnergy(), espressopp::integrator::PIAdressIntegrator::computeMomentumDrift(), espressopp::integrator::PIAdressIntegrator::computePositionDrift(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::integrator::PIAdressIntegrator::computeRingEnergy(), espressopp::integrator::PIAdressIntegrator::computeRingEnergyRaw(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::PIAdressIntegrator::distributeForces(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::FixedLocalTupleComListInteractionTemplate(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::VelocityVerlet::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::PIAdressIntegrator::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::PIAdressIntegrator::initializeSetup(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::VelocityVerlet::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::VelocityVerlet::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::PIAdressIntegrator::integrateModePos(), espressopp::integrator::PIAdressIntegrator::integrateV1(), espressopp::integrator::PIAdressIntegrator::integrateV2(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::PIAdressIntegrator::OUintegrate(), espressopp::integrator::VelocityVerlet::printForces(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerlet::printPositions(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readLBConf(), rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::PIAdressIntegrator::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::MinimizeEnergy::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::Rattle::saveOldPos(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::PIAdressIntegrator::setWeights(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostatOnGroup::thermalize(), espressopp::integrator::LangevinThermostatOnRadius::thermalize(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), totalSize(), espressopp::integrator::PIAdressIntegrator::transForces(), espressopp::integrator::PIAdressIntegrator::transMom1(), espressopp::integrator::PIAdressIntegrator::transMom2(), espressopp::integrator::PIAdressIntegrator::transPos1(), espressopp::integrator::PIAdressIntegrator::transPos2(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::VelocityVerlet::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::PIAdressIntegrator::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
getSystemRef1()
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
getSystemRef2()
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
LOG4ESPP_DECL_LOGGER()
static espressopp::VerletListAdress::LOG4ESPP_DECL_LOGGER (theLogger) static private
rebuild()
void espressopp::VerletListAdress::rebuild ()
Definition at line 73 of file VerletListAdress.cpp.
References adrCenter, adrCenterSet, adrPairs, adrPositions, adrsq, adrZone, espressopp::System::bc, builds, cgZone, checkPair(), cutsq, getAdrRegionType(), espressopp::bc::BC::getMinimumImageVectorBox(), espressopp::SystemAccess::getSystem(), espressopp::SystemAccess::getSystemRef(), espressopp::iterator::CellListAllPairsIterator::isValid(), espressopp::iterator::CellListIterator::isValid(), LOG4ESPP_INFO, espressopp::Real3D::sqr(), and vlPairs.
Referenced by registerPython(), and VerletListAdress().
registerPython()
void espressopp::VerletListAdress::registerPython () static
Register this class so it can be used from Python.
Definition at line 232 of file VerletListAdress.cpp.
References addAdrParticle(), exclude(), getBuilds(), espressopp::SystemAccess::getSystem(), rebuild(), setAdrCenter(), setAdrRegionType(), setBuilds(), and totalSize().
Referenced by espressopp::registerPython(), and setBuilds().
setAdrCenter()
void espressopp::VerletListAdress::setAdrCenter (real x, real y, real z)
Definition at line 201 of file VerletListAdress.cpp.
References adrCenter, adrCenterSet, and adrPositions.
Referenced by getEx(), and registerPython().
setAdrRegionType()
void espressopp::VerletListAdress::setAdrRegionType (bool _sphereAdr)
Definition at line 209 of file VerletListAdress.cpp.
References sphereAdr.
Referenced by getAdrCenterSet(), and registerPython().
setBuilds()
void espressopp::VerletListAdress::setBuilds (int _builds) inline
Set the number of times the Verlet list has been rebuilt.
Definition at line 93 of file VerletListAdress.hpp.
References builds, and registerPython().
Referenced by registerPython().
totalSize()
int espressopp::VerletListAdress::totalSize () const
Get the total number of pairs for the Verlet list.
Definition at line 181 of file VerletListAdress.cpp.
References espressopp::System::comm, espressopp::SystemAccess::getSystemRef(), and vlPairs.
Referenced by registerPython().
Member Data Documentation
adrCenter
Real3D espressopp::VerletListAdress::adrCenter private
Definition at line 107 of file VerletListAdress.hpp.
Referenced by getAdrCenter(), rebuild(), and setAdrCenter().
adrCenterSet
bool espressopp::VerletListAdress::adrCenterSet private
Definition at line 108 of file VerletListAdress.hpp.
Referenced by getAdrCenterSet(), rebuild(), setAdrCenter(), and VerletListAdress().
adrcutsq
real espressopp::VerletListAdress::adrcutsq private
Definition at line 105 of file VerletListAdress.hpp.
Referenced by checkPair(), and VerletListAdress().
adrCutverlet
real espressopp::VerletListAdress::adrCutverlet private
Definition at line 105 of file VerletListAdress.hpp.
Referenced by VerletListAdress().
adrList
std::set<longint> espressopp::VerletListAdress::adrList private
Definition at line 100 of file VerletListAdress.hpp.
Referenced by addAdrParticle(), and getAdrList().
adrPairs
PairList espressopp::VerletListAdress::adrPairs private
Definition at line 103 of file VerletListAdress.hpp.
Referenced by checkPair(), getAdrPairs(), and rebuild().
adrPositions
std::vector<Real3D*> espressopp::VerletListAdress::adrPositions
Define the lowest atomistic type number.
Definition at line 80 of file VerletListAdress.hpp.
Referenced by getAdrPositions(), rebuild(), and setAdrCenter().
adrsq
real espressopp::VerletListAdress::adrsq private
Definition at line 105 of file VerletListAdress.hpp.
Referenced by rebuild(), and VerletListAdress().
adrZone
std::set<Particle*> espressopp::VerletListAdress::adrZone private
Definition at line 101 of file VerletListAdress.hpp.
Referenced by checkPair(), getAdrZone(), and rebuild().
builds
int espressopp::VerletListAdress::builds private
Definition at line 119 of file VerletListAdress.hpp.
Referenced by getBuilds(), rebuild(), setBuilds(), and VerletListAdress().
cgZone
std::set<Particle*> espressopp::VerletListAdress::cgZone private
Definition at line 102 of file VerletListAdress.hpp.
Referenced by getCGZone(), and rebuild().
connectionResort
boost::signals2::connection espressopp::VerletListAdress::connectionResort private
Definition at line 120 of file VerletListAdress.hpp.
Referenced by VerletListAdress(), and ~VerletListAdress().
cutsq
real espressopp::VerletListAdress::cutsq private
Definition at line 118 of file VerletListAdress.hpp.
Referenced by checkPair(), rebuild(), and VerletListAdress().
cutverlet
real espressopp::VerletListAdress::cutverlet private
Definition at line 105 of file VerletListAdress.hpp.
Referenced by VerletListAdress().
dEx
real espressopp::VerletListAdress::dEx private
Definition at line 104 of file VerletListAdress.hpp.
Referenced by getEx(), and VerletListAdress().
dHy
real espressopp::VerletListAdress::dHy private
Definition at line 104 of file VerletListAdress.hpp.
Referenced by getHy(), and VerletListAdress().
exList
boost::unordered_set<std::pair<longint, longint> > espressopp::VerletListAdress::exList private
Definition at line 117 of file VerletListAdress.hpp.
Referenced by checkPair(), and exclude().
skin
real espressopp::VerletListAdress::skin private
Definition at line 106 of file VerletListAdress.hpp.
Referenced by VerletListAdress().
sphereAdr
bool espressopp::VerletListAdress::sphereAdr private
Definition at line 109 of file VerletListAdress.hpp.
Referenced by getAdrRegionType(), and setAdrRegionType().
vlPairs
PairList espressopp::VerletListAdress::vlPairs private
Definition at line 116 of file VerletListAdress.hpp.
Referenced by checkPair(), getPairs(), rebuild(), and totalSize().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/VerletListAdress.hpp
/home/espressopp/espressopp/src/VerletListAdress.cpp