ESPResSo++: espressopp::interaction::Potential Class Reference
espressopp::interaction::Potential Class Reference abstract
#include <Potential.hpp>
Public Member Functions
virtual ~Potential ()
virtual real computeEnergy (const Particle &p1, const Particle &p2) const =0
virtual real computeEnergy (const Real3D &dist) const =0
virtual real computeEnergy (real dist) const =0
virtual real computeEnergySqr (real distSqr) const =0
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const =0
virtual Real3D computeForce (const Real3D &dist) const =0
virtual void setCutoff (real _cutoff)=0
virtual real getCutoff () const =0
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)=0
virtual shared_ptr< FixedPairList > getColVarBondList () const =0
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &fpl)=0
virtual shared_ptr< FixedTripleList > getColVarAngleList () const =0
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fpl)=0
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const =0
virtual void setColVar (const RealND &cv)=0
virtual void setColVar (const Real3D &dist, const bc::BC &bc)=0
virtual RealND getColVar () const =0
virtual void computeColVarWeights (const Real3D &dist, const bc::BC &bc)=0
virtual void setShift (real _shift)=0
virtual real getShift () const =0
virtual real setAutoShift ()=0
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Detailed Description
Definition at line 38 of file Potential.hpp.
Constructor & Destructor Documentation
~Potential()
virtual espressopp::interaction::Potential::~Potential () inline virtual
Definition at line 40 of file Potential.hpp.
References computeColVarWeights(), computeEnergy(), computeEnergySqr(), computeForce(), getColVar(), getColVarAngleList(), getColVarBondList(), getColVarDihedList(), getCutoff(), getShift(), LOG4ESPP_DECL_LOGGER(), registerPython(), setAutoShift(), setColVar(), setColVarAngleList(), setColVarBondList(), setColVarDihedList(), setCutoff(), and setShift().
Member Function Documentation
computeColVarWeights()
virtual void espressopp::interaction::Potential::computeColVarWeights (const Real3D & dist, const bc::BC & bc) pure virtual
Implemented in espressopp::interaction::TabulatedSubEns, espressopp::interaction::PotentialTemplate< Derived >, espressopp::interaction::PotentialTemplate< LennardJonesGeneric >, espressopp::interaction::PotentialTemplate< CoulombTruncated >, espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >, espressopp::interaction::PotentialTemplate< SoftCosine >, espressopp::interaction::PotentialTemplate< SmoothSquareWell >, espressopp::interaction::PotentialTemplate< TabulatedSubEns >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >, espressopp::interaction::PotentialTemplate< LennardJones >, espressopp::interaction::PotentialTemplate< CoulombRSpace >, espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >, espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >, espressopp::interaction::PotentialTemplate< Harmonic >, espressopp::interaction::PotentialTemplate< ConstrainRG >, espressopp::interaction::PotentialTemplate< Tabulated >, espressopp::interaction::PotentialTemplate< FENECapped >, espressopp::interaction::PotentialTemplate< FENE >, espressopp::interaction::PotentialTemplate< VSphereSelf >, espressopp::interaction::PotentialTemplate< LJcos >, espressopp::interaction::PotentialTemplate< LennardJonesExpand >, espressopp::interaction::PotentialTemplate< TersoffPairTerm >, espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >, espressopp::interaction::PotentialTemplate< LennardJonesGromacs >, espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >, espressopp::interaction::PotentialTemplate< Quartic >, espressopp::interaction::PotentialTemplate< GravityTruncated >, espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >, espressopp::interaction::PotentialTemplate< LennardJonesCapped >, espressopp::interaction::PotentialTemplate< MirrorLennardJones >, espressopp::interaction::PotentialTemplate< Zero >, espressopp::interaction::PotentialTemplate< Morse >, espressopp::interaction::PotentialTemplate< ConstrainCOM >, espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >, and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >.
Referenced by ~Potential(), and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::~PotentialTemplate().
computeEnergy() [1/3]
virtual real espressopp::interaction::Potential::computeEnergy (const Particle & p1, const Particle & p2) const pure virtual
Implemented in espressopp::interaction::LennardJonesAutoBonds, espressopp::interaction::PotentialTemplate< Derived >, espressopp::interaction::PotentialTemplate< LennardJonesGeneric >, espressopp::interaction::PotentialTemplate< CoulombTruncated >, espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >, espressopp::interaction::PotentialTemplate< SoftCosine >, espressopp::interaction::PotentialTemplate< SmoothSquareWell >, espressopp::interaction::PotentialTemplate< TabulatedSubEns >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >, espressopp::interaction::PotentialTemplate< LennardJones >, espressopp::interaction::PotentialTemplate< CoulombRSpace >, espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >, espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >, espressopp::interaction::PotentialTemplate< Harmonic >, espressopp::interaction::PotentialTemplate< ConstrainRG >, espressopp::interaction::PotentialTemplate< Tabulated >, espressopp::interaction::PotentialTemplate< FENECapped >, espressopp::interaction::PotentialTemplate< FENE >, espressopp::interaction::PotentialTemplate< VSphereSelf >, espressopp::interaction::PotentialTemplate< LJcos >, espressopp::interaction::PotentialTemplate< LennardJonesExpand >, espressopp::interaction::PotentialTemplate< TersoffPairTerm >, espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >, espressopp::interaction::PotentialTemplate< LennardJonesGromacs >, espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >, espressopp::interaction::PotentialTemplate< Quartic >, espressopp::interaction::PotentialTemplate< GravityTruncated >, espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >, espressopp::interaction::PotentialTemplate< LennardJonesCapped >, espressopp::interaction::PotentialTemplate< MirrorLennardJones >, espressopp::interaction::PotentialTemplate< Zero >, espressopp::interaction::PotentialTemplate< Morse >, espressopp::interaction::PotentialTemplate< ConstrainCOM >, espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >, and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >.
Referenced by registerPython(), ~Potential(), and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::~PotentialTemplate().
computeEnergy() [2/3]
virtual real espressopp::interaction::Potential::computeEnergy (const Real3D & dist) const pure virtual
Implemented in espressopp::interaction::LennardJonesAutoBonds, espressopp::interaction::PotentialTemplate< Derived >, espressopp::interaction::PotentialTemplate< LennardJonesGeneric >, espressopp::interaction::PotentialTemplate< CoulombTruncated >, espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >, espressopp::interaction::PotentialTemplate< SoftCosine >, espressopp::interaction::PotentialTemplate< SmoothSquareWell >, espressopp::interaction::PotentialTemplate< TabulatedSubEns >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >, espressopp::interaction::PotentialTemplate< LennardJones >, espressopp::interaction::PotentialTemplate< CoulombRSpace >, espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >, espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >, espressopp::interaction::PotentialTemplate< Harmonic >, espressopp::interaction::PotentialTemplate< ConstrainRG >, espressopp::interaction::PotentialTemplate< Tabulated >, espressopp::interaction::PotentialTemplate< FENECapped >, espressopp::interaction::PotentialTemplate< FENE >, espressopp::interaction::PotentialTemplate< VSphereSelf >, espressopp::interaction::PotentialTemplate< LJcos >, espressopp::interaction::PotentialTemplate< LennardJonesExpand >, espressopp::interaction::PotentialTemplate< TersoffPairTerm >, espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >, espressopp::interaction::PotentialTemplate< LennardJonesGromacs >, espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >, espressopp::interaction::PotentialTemplate< Quartic >, espressopp::interaction::PotentialTemplate< GravityTruncated >, espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >, espressopp::interaction::PotentialTemplate< LennardJonesCapped >, espressopp::interaction::PotentialTemplate< MirrorLennardJones >, espressopp::interaction::PotentialTemplate< Zero >, espressopp::interaction::PotentialTemplate< Morse >, espressopp::interaction::PotentialTemplate< ConstrainCOM >, espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >, and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >.
computeEnergy() [3/3]
virtual real espressopp::interaction::Potential::computeEnergy (real dist) const pure virtual
Implemented in espressopp::interaction::LennardJonesAutoBonds, espressopp::interaction::PotentialTemplate< Derived >, espressopp::interaction::PotentialTemplate< LennardJonesGeneric >, espressopp::interaction::PotentialTemplate< CoulombTruncated >, espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >, espressopp::interaction::PotentialTemplate< SoftCosine >, espressopp::interaction::PotentialTemplate< SmoothSquareWell >, espressopp::interaction::PotentialTemplate< TabulatedSubEns >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >, espressopp::interaction::PotentialTemplate< LennardJones >, espressopp::interaction::PotentialTemplate< CoulombRSpace >, espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >, espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >, espressopp::interaction::PotentialTemplate< Harmonic >, espressopp::interaction::PotentialTemplate< ConstrainRG >, espressopp::interaction::PotentialTemplate< Tabulated >, espressopp::interaction::PotentialTemplate< FENECapped >, espressopp::interaction::PotentialTemplate< FENE >, espressopp::interaction::PotentialTemplate< VSphereSelf >, espressopp::interaction::PotentialTemplate< LJcos >, espressopp::interaction::PotentialTemplate< LennardJonesExpand >, espressopp::interaction::PotentialTemplate< TersoffPairTerm >, espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >, espressopp::interaction::PotentialTemplate< LennardJonesGromacs >, espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >, espressopp::interaction::PotentialTemplate< Quartic >, espressopp::interaction::PotentialTemplate< GravityTruncated >, espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >, espressopp::interaction::PotentialTemplate< LennardJonesCapped >, espressopp::interaction::PotentialTemplate< MirrorLennardJones >, espressopp::interaction::PotentialTemplate< Zero >, espressopp::interaction::PotentialTemplate< Morse >, espressopp::interaction::PotentialTemplate< ConstrainCOM >, espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >, and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >.
computeEnergySqr()
virtual real espressopp::interaction::Potential::computeEnergySqr (real distSqr) const pure virtual
Implemented in espressopp::interaction::LennardJonesAutoBonds, espressopp::interaction::PotentialTemplate< Derived >, espressopp::interaction::PotentialTemplate< LennardJonesGeneric >, espressopp::interaction::PotentialTemplate< CoulombTruncated >, espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >, espressopp::interaction::PotentialTemplate< SoftCosine >, espressopp::interaction::PotentialTemplate< SmoothSquareWell >, espressopp::interaction::PotentialTemplate< TabulatedSubEns >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >, espressopp::interaction::PotentialTemplate< LennardJones >, espressopp::interaction::PotentialTemplate< CoulombRSpace >, espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >, espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >, espressopp::interaction::PotentialTemplate< Harmonic >, espressopp::interaction::PotentialTemplate< ConstrainRG >, espressopp::interaction::PotentialTemplate< Tabulated >, espressopp::interaction::PotentialTemplate< FENECapped >, espressopp::interaction::PotentialTemplate< FENE >, espressopp::interaction::PotentialTemplate< VSphereSelf >, espressopp::interaction::PotentialTemplate< LJcos >, espressopp::interaction::PotentialTemplate< LennardJonesExpand >, espressopp::interaction::PotentialTemplate< TersoffPairTerm >, espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >, espressopp::interaction::PotentialTemplate< LennardJonesGromacs >, espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >, espressopp::interaction::PotentialTemplate< Quartic >, espressopp::interaction::PotentialTemplate< GravityTruncated >, espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >, espressopp::interaction::PotentialTemplate< LennardJonesCapped >, espressopp::interaction::PotentialTemplate< MirrorLennardJones >, espressopp::interaction::PotentialTemplate< Zero >, espressopp::interaction::PotentialTemplate< Morse >, espressopp::interaction::PotentialTemplate< ConstrainCOM >, espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >, and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >.
Referenced by ~Potential(), and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::~PotentialTemplate().
computeForce() [1/2]
virtual Real3D espressopp::interaction::Potential::computeForce (const Particle & p1, const Particle & p2) const pure virtual
Implemented in espressopp::interaction::LennardJonesAutoBonds, espressopp::interaction::PotentialTemplate< Derived >, espressopp::interaction::PotentialTemplate< LennardJonesGeneric >, espressopp::interaction::PotentialTemplate< CoulombTruncated >, espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >, espressopp::interaction::PotentialTemplate< SoftCosine >, espressopp::interaction::PotentialTemplate< SmoothSquareWell >, espressopp::interaction::PotentialTemplate< TabulatedSubEns >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >, espressopp::interaction::PotentialTemplate< LennardJones >, espressopp::interaction::PotentialTemplate< CoulombRSpace >, espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >, espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >, espressopp::interaction::PotentialTemplate< Harmonic >, espressopp::interaction::PotentialTemplate< ConstrainRG >, espressopp::interaction::PotentialTemplate< Tabulated >, espressopp::interaction::PotentialTemplate< FENECapped >, espressopp::interaction::PotentialTemplate< FENE >, espressopp::interaction::PotentialTemplate< VSphereSelf >, espressopp::interaction::PotentialTemplate< LJcos >, espressopp::interaction::PotentialTemplate< LennardJonesExpand >, espressopp::interaction::PotentialTemplate< TersoffPairTerm >, espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >, espressopp::interaction::PotentialTemplate< LennardJonesGromacs >, espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >, espressopp::interaction::PotentialTemplate< Quartic >, espressopp::interaction::PotentialTemplate< GravityTruncated >, espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >, espressopp::interaction::PotentialTemplate< LennardJonesCapped >, espressopp::interaction::PotentialTemplate< MirrorLennardJones >, espressopp::interaction::PotentialTemplate< Zero >, espressopp::interaction::PotentialTemplate< Morse >, espressopp::interaction::PotentialTemplate< ConstrainCOM >, espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >, and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >.
Referenced by registerPython(), ~Potential(), and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::~PotentialTemplate().
computeForce() [2/2]
virtual Real3D espressopp::interaction::Potential::computeForce (const Real3D & dist) const pure virtual
Implemented in espressopp::interaction::LennardJonesAutoBonds, espressopp::interaction::PotentialTemplate< Derived >, espressopp::interaction::PotentialTemplate< LennardJonesGeneric >, espressopp::interaction::PotentialTemplate< CoulombTruncated >, espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >, espressopp::interaction::PotentialTemplate< SoftCosine >, espressopp::interaction::PotentialTemplate< SmoothSquareWell >, espressopp::interaction::PotentialTemplate< TabulatedSubEns >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >, espressopp::interaction::PotentialTemplate< LennardJones >, espressopp::interaction::PotentialTemplate< CoulombRSpace >, espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >, espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >, espressopp::interaction::PotentialTemplate< Harmonic >, espressopp::interaction::PotentialTemplate< ConstrainRG >, espressopp::interaction::PotentialTemplate< Tabulated >, espressopp::interaction::PotentialTemplate< FENECapped >, espressopp::interaction::PotentialTemplate< FENE >, espressopp::interaction::PotentialTemplate< VSphereSelf >, espressopp::interaction::PotentialTemplate< LJcos >, espressopp::interaction::PotentialTemplate< LennardJonesExpand >, espressopp::interaction::PotentialTemplate< TersoffPairTerm >, espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >, espressopp::interaction::PotentialTemplate< LennardJonesGromacs >, espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >, espressopp::interaction::PotentialTemplate< Quartic >, espressopp::interaction::PotentialTemplate< GravityTruncated >, espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >, espressopp::interaction::PotentialTemplate< LennardJonesCapped >, espressopp::interaction::PotentialTemplate< MirrorLennardJones >, espressopp::interaction::PotentialTemplate< Zero >, espressopp::interaction::PotentialTemplate< Morse >, espressopp::interaction::PotentialTemplate< ConstrainCOM >, espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >, and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >.
getColVar()
virtual RealND espressopp::interaction::Potential::getColVar () const pure virtual
Implemented in espressopp::interaction::PotentialTemplate< Derived >, espressopp::interaction::PotentialTemplate< LennardJonesGeneric >, espressopp::interaction::PotentialTemplate< CoulombTruncated >, espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >, espressopp::interaction::PotentialTemplate< SoftCosine >, espressopp::interaction::PotentialTemplate< SmoothSquareWell >, espressopp::interaction::PotentialTemplate< TabulatedSubEns >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >, espressopp::interaction::PotentialTemplate< LennardJones >, espressopp::interaction::PotentialTemplate< CoulombRSpace >, espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >, espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >, espressopp::interaction::PotentialTemplate< Harmonic >, espressopp::interaction::PotentialTemplate< ConstrainRG >, espressopp::interaction::PotentialTemplate< Tabulated >, espressopp::interaction::PotentialTemplate< FENECapped >, espressopp::interaction::PotentialTemplate< FENE >, espressopp::interaction::PotentialTemplate< VSphereSelf >, espressopp::interaction::PotentialTemplate< LJcos >, espressopp::interaction::PotentialTemplate< LennardJonesExpand >, espressopp::interaction::PotentialTemplate< TersoffPairTerm >, espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >, espressopp::interaction::PotentialTemplate< LennardJonesGromacs >, espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >, espressopp::interaction::PotentialTemplate< Quartic >, espressopp::interaction::PotentialTemplate< GravityTruncated >, espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >, espressopp::interaction::PotentialTemplate< LennardJonesCapped >, espressopp::interaction::PotentialTemplate< MirrorLennardJones >, espressopp::interaction::PotentialTemplate< Zero >, espressopp::interaction::PotentialTemplate< Morse >, espressopp::interaction::PotentialTemplate< ConstrainCOM >, espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >, and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >.
Referenced by registerPython(), ~Potential(), and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::~PotentialTemplate().
getColVarAngleList()
virtual shared_ptr<FixedTripleList> espressopp::interaction::Potential::getColVarAngleList () const pure virtual
Implemented in espressopp::interaction::PotentialTemplate< Derived >, espressopp::interaction::PotentialTemplate< LennardJonesGeneric >, espressopp::interaction::PotentialTemplate< CoulombTruncated >, espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >, espressopp::interaction::PotentialTemplate< SoftCosine >, espressopp::interaction::PotentialTemplate< SmoothSquareWell >, espressopp::interaction::PotentialTemplate< TabulatedSubEns >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >, espressopp::interaction::PotentialTemplate< LennardJones >, espressopp::interaction::PotentialTemplate< CoulombRSpace >, espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >, espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >, espressopp::interaction::PotentialTemplate< Harmonic >, espressopp::interaction::PotentialTemplate< ConstrainRG >, espressopp::interaction::PotentialTemplate< Tabulated >, espressopp::interaction::PotentialTemplate< FENECapped >, espressopp::interaction::PotentialTemplate< FENE >, espressopp::interaction::PotentialTemplate< VSphereSelf >, espressopp::interaction::PotentialTemplate< LJcos >, espressopp::interaction::PotentialTemplate< LennardJonesExpand >, espressopp::interaction::PotentialTemplate< TersoffPairTerm >, espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >, espressopp::interaction::PotentialTemplate< LennardJonesGromacs >, espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >, espressopp::interaction::PotentialTemplate< Quartic >, espressopp::interaction::PotentialTemplate< GravityTruncated >, espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >, espressopp::interaction::PotentialTemplate< LennardJonesCapped >, espressopp::interaction::PotentialTemplate< MirrorLennardJones >, espressopp::interaction::PotentialTemplate< Zero >, espressopp::interaction::PotentialTemplate< Morse >, espressopp::interaction::PotentialTemplate< ConstrainCOM >, espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >, and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >.
Referenced by registerPython(), ~Potential(), and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::~PotentialTemplate().
getColVarBondList()
virtual shared_ptr<FixedPairList> espressopp::interaction::Potential::getColVarBondList () const pure virtual
Implemented in espressopp::interaction::PotentialTemplate< Derived >, espressopp::interaction::PotentialTemplate< LennardJonesGeneric >, espressopp::interaction::PotentialTemplate< CoulombTruncated >, espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >, espressopp::interaction::PotentialTemplate< SoftCosine >, espressopp::interaction::PotentialTemplate< SmoothSquareWell >, espressopp::interaction::PotentialTemplate< TabulatedSubEns >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >, espressopp::interaction::PotentialTemplate< LennardJones >, espressopp::interaction::PotentialTemplate< CoulombRSpace >, espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >, espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >, espressopp::interaction::PotentialTemplate< Harmonic >, espressopp::interaction::PotentialTemplate< ConstrainRG >, espressopp::interaction::PotentialTemplate< Tabulated >, espressopp::interaction::PotentialTemplate< FENECapped >, espressopp::interaction::PotentialTemplate< FENE >, espressopp::interaction::PotentialTemplate< VSphereSelf >, espressopp::interaction::PotentialTemplate< LJcos >, espressopp::interaction::PotentialTemplate< LennardJonesExpand >, espressopp::interaction::PotentialTemplate< TersoffPairTerm >, espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >, espressopp::interaction::PotentialTemplate< LennardJonesGromacs >, espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >, espressopp::interaction::PotentialTemplate< Quartic >, espressopp::interaction::PotentialTemplate< GravityTruncated >, espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >, espressopp::interaction::PotentialTemplate< LennardJonesCapped >, espressopp::interaction::PotentialTemplate< MirrorLennardJones >, espressopp::interaction::PotentialTemplate< Zero >, espressopp::interaction::PotentialTemplate< Morse >, espressopp::interaction::PotentialTemplate< ConstrainCOM >, espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >, and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >.
Referenced by registerPython(), ~Potential(), and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::~PotentialTemplate().
getColVarDihedList()
virtual shared_ptr<FixedQuadrupleList> espressopp::interaction::Potential::getColVarDihedList () const pure virtual
Implemented in espressopp::interaction::PotentialTemplate< Derived >, espressopp::interaction::PotentialTemplate< LennardJonesGeneric >, espressopp::interaction::PotentialTemplate< CoulombTruncated >, espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >, espressopp::interaction::PotentialTemplate< SoftCosine >, espressopp::interaction::PotentialTemplate< SmoothSquareWell >, espressopp::interaction::PotentialTemplate< TabulatedSubEns >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >, espressopp::interaction::PotentialTemplate< LennardJones >, espressopp::interaction::PotentialTemplate< CoulombRSpace >, espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >, espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >, espressopp::interaction::PotentialTemplate< Harmonic >, espressopp::interaction::PotentialTemplate< ConstrainRG >, espressopp::interaction::PotentialTemplate< Tabulated >, espressopp::interaction::PotentialTemplate< FENECapped >, espressopp::interaction::PotentialTemplate< FENE >, espressopp::interaction::PotentialTemplate< VSphereSelf >, espressopp::interaction::PotentialTemplate< LJcos >, espressopp::interaction::PotentialTemplate< LennardJonesExpand >, espressopp::interaction::PotentialTemplate< TersoffPairTerm >, espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >, espressopp::interaction::PotentialTemplate< LennardJonesGromacs >, espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >, espressopp::interaction::PotentialTemplate< Quartic >, espressopp::interaction::PotentialTemplate< GravityTruncated >, espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >, espressopp::interaction::PotentialTemplate< LennardJonesCapped >, espressopp::interaction::PotentialTemplate< MirrorLennardJones >, espressopp::interaction::PotentialTemplate< Zero >, espressopp::interaction::PotentialTemplate< Morse >, espressopp::interaction::PotentialTemplate< ConstrainCOM >, espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >, and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >.
Referenced by registerPython(), ~Potential(), and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::~PotentialTemplate().
getCutoff()
virtual real espressopp::interaction::Potential::getCutoff () const pure virtual
Implemented in espressopp::interaction::CoulombKSpaceP3M, espressopp::interaction::PotentialTemplate< Derived >, espressopp::interaction::PotentialTemplate< LennardJonesGeneric >, espressopp::interaction::PotentialTemplate< CoulombTruncated >, espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >, espressopp::interaction::PotentialTemplate< SoftCosine >, espressopp::interaction::PotentialTemplate< SmoothSquareWell >, espressopp::interaction::PotentialTemplate< TabulatedSubEns >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >, espressopp::interaction::PotentialTemplate< LennardJones >, espressopp::interaction::PotentialTemplate< CoulombRSpace >, espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >, espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >, espressopp::interaction::PotentialTemplate< Harmonic >, espressopp::interaction::PotentialTemplate< ConstrainRG >, espressopp::interaction::PotentialTemplate< Tabulated >, espressopp::interaction::PotentialTemplate< FENECapped >, espressopp::interaction::PotentialTemplate< FENE >, espressopp::interaction::PotentialTemplate< VSphereSelf >, espressopp::interaction::PotentialTemplate< LJcos >, espressopp::interaction::PotentialTemplate< LennardJonesExpand >, espressopp::interaction::PotentialTemplate< TersoffPairTerm >, espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >, espressopp::interaction::PotentialTemplate< LennardJonesGromacs >, espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >, espressopp::interaction::PotentialTemplate< Quartic >, espressopp::interaction::PotentialTemplate< GravityTruncated >, espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >, espressopp::interaction::PotentialTemplate< LennardJonesCapped >, espressopp::interaction::PotentialTemplate< MirrorLennardJones >, espressopp::interaction::PotentialTemplate< Zero >, espressopp::interaction::PotentialTemplate< Morse >, espressopp::interaction::PotentialTemplate< ConstrainCOM >, espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >, and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >.
Referenced by registerPython(), ~Potential(), and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::~PotentialTemplate().
getShift()
virtual real espressopp::interaction::Potential::getShift () const pure virtual
Implemented in espressopp::interaction::PotentialTemplate< Derived >, espressopp::interaction::PotentialTemplate< LennardJonesGeneric >, espressopp::interaction::PotentialTemplate< CoulombTruncated >, espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >, espressopp::interaction::PotentialTemplate< SoftCosine >, espressopp::interaction::PotentialTemplate< SmoothSquareWell >, espressopp::interaction::PotentialTemplate< TabulatedSubEns >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >, espressopp::interaction::PotentialTemplate< LennardJones >, espressopp::interaction::PotentialTemplate< CoulombRSpace >, espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >, espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >, espressopp::interaction::PotentialTemplate< Harmonic >, espressopp::interaction::PotentialTemplate< ConstrainRG >, espressopp::interaction::PotentialTemplate< Tabulated >, espressopp::interaction::PotentialTemplate< FENECapped >, espressopp::interaction::PotentialTemplate< FENE >, espressopp::interaction::PotentialTemplate< VSphereSelf >, espressopp::interaction::PotentialTemplate< LJcos >, espressopp::interaction::PotentialTemplate< LennardJonesExpand >, espressopp::interaction::PotentialTemplate< TersoffPairTerm >, espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >, espressopp::interaction::PotentialTemplate< LennardJonesGromacs >, espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >, espressopp::interaction::PotentialTemplate< Quartic >, espressopp::interaction::PotentialTemplate< GravityTruncated >, espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >, espressopp::interaction::PotentialTemplate< LennardJonesCapped >, espressopp::interaction::PotentialTemplate< MirrorLennardJones >, espressopp::interaction::PotentialTemplate< Zero >, espressopp::interaction::PotentialTemplate< Morse >, espressopp::interaction::PotentialTemplate< ConstrainCOM >, espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >, and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >.
Referenced by registerPython(), ~Potential(), and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::~PotentialTemplate().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) static
Referenced by ~Potential().
registerPython()
void espressopp::interaction::Potential::registerPython () static
Definition at line 35 of file Potential.cpp.
References computeEnergy(), computeForce(), getColVar(), getColVarAngleList(), getColVarBondList(), getColVarDihedList(), getCutoff(), getShift(), setAutoShift(), setColVarAngleList(), setColVarBondList(), setColVarDihedList(), setCutoff(), and setShift().
Referenced by espressopp::interaction::registerPython(), and ~Potential().
setAutoShift()
virtual real espressopp::interaction::Potential::setAutoShift () pure virtual
Implemented in espressopp::interaction::LennardJonesAutoBonds, espressopp::interaction::PotentialTemplate< Derived >, espressopp::interaction::PotentialTemplate< LennardJonesGeneric >, espressopp::interaction::PotentialTemplate< CoulombTruncated >, espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >, espressopp::interaction::PotentialTemplate< SoftCosine >, espressopp::interaction::PotentialTemplate< SmoothSquareWell >, espressopp::interaction::PotentialTemplate< TabulatedSubEns >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >, espressopp::interaction::PotentialTemplate< LennardJones >, espressopp::interaction::PotentialTemplate< CoulombRSpace >, espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >, espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >, espressopp::interaction::PotentialTemplate< Harmonic >, espressopp::interaction::PotentialTemplate< ConstrainRG >, espressopp::interaction::PotentialTemplate< Tabulated >, espressopp::interaction::PotentialTemplate< FENECapped >, espressopp::interaction::PotentialTemplate< FENE >, espressopp::interaction::PotentialTemplate< VSphereSelf >, espressopp::interaction::PotentialTemplate< LJcos >, espressopp::interaction::PotentialTemplate< LennardJonesExpand >, espressopp::interaction::PotentialTemplate< TersoffPairTerm >, espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >, espressopp::interaction::PotentialTemplate< LennardJonesGromacs >, espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >, espressopp::interaction::PotentialTemplate< Quartic >, espressopp::interaction::PotentialTemplate< GravityTruncated >, espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >, espressopp::interaction::PotentialTemplate< LennardJonesCapped >, espressopp::interaction::PotentialTemplate< MirrorLennardJones >, espressopp::interaction::PotentialTemplate< Zero >, espressopp::interaction::PotentialTemplate< Morse >, espressopp::interaction::PotentialTemplate< ConstrainCOM >, espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >, and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >.
Referenced by registerPython(), ~Potential(), and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::~PotentialTemplate().
setColVar() [1/2]
virtual void espressopp::interaction::Potential::setColVar (const RealND & cv) pure virtual
Implemented in espressopp::interaction::PotentialTemplate< Derived >, espressopp::interaction::PotentialTemplate< LennardJonesGeneric >, espressopp::interaction::PotentialTemplate< CoulombTruncated >, espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >, espressopp::interaction::PotentialTemplate< SoftCosine >, espressopp::interaction::PotentialTemplate< SmoothSquareWell >, espressopp::interaction::PotentialTemplate< TabulatedSubEns >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >, espressopp::interaction::PotentialTemplate< LennardJones >, espressopp::interaction::PotentialTemplate< CoulombRSpace >, espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >, espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >, espressopp::interaction::PotentialTemplate< Harmonic >, espressopp::interaction::PotentialTemplate< ConstrainRG >, espressopp::interaction::PotentialTemplate< Tabulated >, espressopp::interaction::PotentialTemplate< FENECapped >, espressopp::interaction::PotentialTemplate< FENE >, espressopp::interaction::PotentialTemplate< VSphereSelf >, espressopp::interaction::PotentialTemplate< LJcos >, espressopp::interaction::PotentialTemplate< LennardJonesExpand >, espressopp::interaction::PotentialTemplate< TersoffPairTerm >, espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >, espressopp::interaction::PotentialTemplate< LennardJonesGromacs >, espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >, espressopp::interaction::PotentialTemplate< Quartic >, espressopp::interaction::PotentialTemplate< GravityTruncated >, espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >, espressopp::interaction::PotentialTemplate< LennardJonesCapped >, espressopp::interaction::PotentialTemplate< MirrorLennardJones >, espressopp::interaction::PotentialTemplate< Zero >, espressopp::interaction::PotentialTemplate< Morse >, espressopp::interaction::PotentialTemplate< ConstrainCOM >, espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >, and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >.
Referenced by ~Potential(), and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::~PotentialTemplate().
setColVar() [2/2]
virtual void espressopp::interaction::Potential::setColVar (const Real3D & dist, const bc::BC & bc) pure virtual
Implemented in espressopp::interaction::TabulatedSubEns, espressopp::interaction::PotentialTemplate< Derived >, espressopp::interaction::PotentialTemplate< LennardJonesGeneric >, espressopp::interaction::PotentialTemplate< CoulombTruncated >, espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >, espressopp::interaction::PotentialTemplate< SoftCosine >, espressopp::interaction::PotentialTemplate< SmoothSquareWell >, espressopp::interaction::PotentialTemplate< TabulatedSubEns >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >, espressopp::interaction::PotentialTemplate< LennardJones >, espressopp::interaction::PotentialTemplate< CoulombRSpace >, espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >, espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >, espressopp::interaction::PotentialTemplate< Harmonic >, espressopp::interaction::PotentialTemplate< ConstrainRG >, espressopp::interaction::PotentialTemplate< Tabulated >, espressopp::interaction::PotentialTemplate< FENECapped >, espressopp::interaction::PotentialTemplate< FENE >, espressopp::interaction::PotentialTemplate< VSphereSelf >, espressopp::interaction::PotentialTemplate< LJcos >, espressopp::interaction::PotentialTemplate< LennardJonesExpand >, espressopp::interaction::PotentialTemplate< TersoffPairTerm >, espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >, espressopp::interaction::PotentialTemplate< LennardJonesGromacs >, espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >, espressopp::interaction::PotentialTemplate< Quartic >, espressopp::interaction::PotentialTemplate< GravityTruncated >, espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >, espressopp::interaction::PotentialTemplate< LennardJonesCapped >, espressopp::interaction::PotentialTemplate< MirrorLennardJones >, espressopp::interaction::PotentialTemplate< Zero >, espressopp::interaction::PotentialTemplate< Morse >, espressopp::interaction::PotentialTemplate< ConstrainCOM >, espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >, and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >.
setColVarAngleList()
virtual void espressopp::interaction::Potential::setColVarAngleList (const shared_ptr< FixedTripleList > & fpl) pure virtual
Implemented in espressopp::interaction::PotentialTemplate< Derived >, espressopp::interaction::PotentialTemplate< LennardJonesGeneric >, espressopp::interaction::PotentialTemplate< CoulombTruncated >, espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >, espressopp::interaction::PotentialTemplate< SoftCosine >, espressopp::interaction::PotentialTemplate< SmoothSquareWell >, espressopp::interaction::PotentialTemplate< TabulatedSubEns >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >, espressopp::interaction::PotentialTemplate< LennardJones >, espressopp::interaction::PotentialTemplate< CoulombRSpace >, espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >, espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >, espressopp::interaction::PotentialTemplate< Harmonic >, espressopp::interaction::PotentialTemplate< ConstrainRG >, espressopp::interaction::PotentialTemplate< Tabulated >, espressopp::interaction::PotentialTemplate< FENECapped >, espressopp::interaction::PotentialTemplate< FENE >, espressopp::interaction::PotentialTemplate< VSphereSelf >, espressopp::interaction::PotentialTemplate< LJcos >, espressopp::interaction::PotentialTemplate< LennardJonesExpand >, espressopp::interaction::PotentialTemplate< TersoffPairTerm >, espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >, espressopp::interaction::PotentialTemplate< LennardJonesGromacs >, espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >, espressopp::interaction::PotentialTemplate< Quartic >, espressopp::interaction::PotentialTemplate< GravityTruncated >, espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >, espressopp::interaction::PotentialTemplate< LennardJonesCapped >, espressopp::interaction::PotentialTemplate< MirrorLennardJones >, espressopp::interaction::PotentialTemplate< Zero >, espressopp::interaction::PotentialTemplate< Morse >, espressopp::interaction::PotentialTemplate< ConstrainCOM >, espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >, and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >.
Referenced by registerPython(), ~Potential(), and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::~PotentialTemplate().
setColVarBondList()
virtual void espressopp::interaction::Potential::setColVarBondList (const shared_ptr< FixedPairList > & fpl) pure virtual
Implemented in espressopp::interaction::PotentialTemplate< Derived >, espressopp::interaction::PotentialTemplate< LennardJonesGeneric >, espressopp::interaction::PotentialTemplate< CoulombTruncated >, espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >, espressopp::interaction::PotentialTemplate< SoftCosine >, espressopp::interaction::PotentialTemplate< SmoothSquareWell >, espressopp::interaction::PotentialTemplate< TabulatedSubEns >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >, espressopp::interaction::PotentialTemplate< LennardJones >, espressopp::interaction::PotentialTemplate< CoulombRSpace >, espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >, espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >, espressopp::interaction::PotentialTemplate< Harmonic >, espressopp::interaction::PotentialTemplate< ConstrainRG >, espressopp::interaction::PotentialTemplate< Tabulated >, espressopp::interaction::PotentialTemplate< FENECapped >, espressopp::interaction::PotentialTemplate< FENE >, espressopp::interaction::PotentialTemplate< VSphereSelf >, espressopp::interaction::PotentialTemplate< LJcos >, espressopp::interaction::PotentialTemplate< LennardJonesExpand >, espressopp::interaction::PotentialTemplate< TersoffPairTerm >, espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >, espressopp::interaction::PotentialTemplate< LennardJonesGromacs >, espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >, espressopp::interaction::PotentialTemplate< Quartic >, espressopp::interaction::PotentialTemplate< GravityTruncated >, espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >, espressopp::interaction::PotentialTemplate< LennardJonesCapped >, espressopp::interaction::PotentialTemplate< MirrorLennardJones >, espressopp::interaction::PotentialTemplate< Zero >, espressopp::interaction::PotentialTemplate< Morse >, espressopp::interaction::PotentialTemplate< ConstrainCOM >, espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >, and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >.
Referenced by registerPython(), ~Potential(), and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::~PotentialTemplate().
setColVarDihedList()
virtual void espressopp::interaction::Potential::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fpl) pure virtual
Implemented in espressopp::interaction::PotentialTemplate< Derived >, espressopp::interaction::PotentialTemplate< LennardJonesGeneric >, espressopp::interaction::PotentialTemplate< CoulombTruncated >, espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >, espressopp::interaction::PotentialTemplate< SoftCosine >, espressopp::interaction::PotentialTemplate< SmoothSquareWell >, espressopp::interaction::PotentialTemplate< TabulatedSubEns >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >, espressopp::interaction::PotentialTemplate< LennardJones >, espressopp::interaction::PotentialTemplate< CoulombRSpace >, espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >, espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >, espressopp::interaction::PotentialTemplate< Harmonic >, espressopp::interaction::PotentialTemplate< ConstrainRG >, espressopp::interaction::PotentialTemplate< Tabulated >, espressopp::interaction::PotentialTemplate< FENECapped >, espressopp::interaction::PotentialTemplate< FENE >, espressopp::interaction::PotentialTemplate< VSphereSelf >, espressopp::interaction::PotentialTemplate< LJcos >, espressopp::interaction::PotentialTemplate< LennardJonesExpand >, espressopp::interaction::PotentialTemplate< TersoffPairTerm >, espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >, espressopp::interaction::PotentialTemplate< LennardJonesGromacs >, espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >, espressopp::interaction::PotentialTemplate< Quartic >, espressopp::interaction::PotentialTemplate< GravityTruncated >, espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >, espressopp::interaction::PotentialTemplate< LennardJonesCapped >, espressopp::interaction::PotentialTemplate< MirrorLennardJones >, espressopp::interaction::PotentialTemplate< Zero >, espressopp::interaction::PotentialTemplate< Morse >, espressopp::interaction::PotentialTemplate< ConstrainCOM >, espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >, and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >.
Referenced by registerPython(), ~Potential(), and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::~PotentialTemplate().
setCutoff()
virtual void espressopp::interaction::Potential::setCutoff (real _cutoff) pure virtual
Implemented in espressopp::interaction::CoulombKSpaceP3M, espressopp::interaction::ReactionFieldGeneralized, espressopp::interaction::LennardJonesAutoBonds, espressopp::interaction::ReactionFieldGeneralizedTI, espressopp::interaction::PotentialTemplate< Derived >, espressopp::interaction::PotentialTemplate< LennardJonesGeneric >, espressopp::interaction::PotentialTemplate< CoulombTruncated >, espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >, espressopp::interaction::PotentialTemplate< SoftCosine >, espressopp::interaction::PotentialTemplate< SmoothSquareWell >, espressopp::interaction::PotentialTemplate< TabulatedSubEns >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >, espressopp::interaction::PotentialTemplate< LennardJones >, espressopp::interaction::PotentialTemplate< CoulombRSpace >, espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >, espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >, espressopp::interaction::PotentialTemplate< Harmonic >, espressopp::interaction::PotentialTemplate< ConstrainRG >, espressopp::interaction::PotentialTemplate< Tabulated >, espressopp::interaction::PotentialTemplate< FENECapped >, espressopp::interaction::PotentialTemplate< FENE >, espressopp::interaction::PotentialTemplate< VSphereSelf >, espressopp::interaction::PotentialTemplate< LJcos >, espressopp::interaction::PotentialTemplate< LennardJonesExpand >, espressopp::interaction::PotentialTemplate< TersoffPairTerm >, espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >, espressopp::interaction::PotentialTemplate< LennardJonesGromacs >, espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >, espressopp::interaction::PotentialTemplate< Quartic >, espressopp::interaction::PotentialTemplate< GravityTruncated >, espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >, espressopp::interaction::PotentialTemplate< LennardJonesCapped >, espressopp::interaction::PotentialTemplate< MirrorLennardJones >, espressopp::interaction::PotentialTemplate< Zero >, espressopp::interaction::PotentialTemplate< Morse >, espressopp::interaction::PotentialTemplate< ConstrainCOM >, espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >, and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >.
Referenced by registerPython(), ~Potential(), and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::~PotentialTemplate().
setShift()
virtual void espressopp::interaction::Potential::setShift (real _shift) pure virtual
Implemented in espressopp::interaction::PotentialTemplate< Derived >, espressopp::interaction::PotentialTemplate< LennardJonesGeneric >, espressopp::interaction::PotentialTemplate< CoulombTruncated >, espressopp::interaction::PotentialTemplate< StillingerWeberPairTermCapped >, espressopp::interaction::PotentialTemplate< SoftCosine >, espressopp::interaction::PotentialTemplate< SmoothSquareWell >, espressopp::interaction::PotentialTemplate< TabulatedSubEns >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralizedTI >, espressopp::interaction::PotentialTemplate< LennardJones >, espressopp::interaction::PotentialTemplate< CoulombRSpace >, espressopp::interaction::PotentialTemplate< CoulombTruncatedUniqueCharge >, espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >, espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >, espressopp::interaction::PotentialTemplate< Harmonic >, espressopp::interaction::PotentialTemplate< ConstrainRG >, espressopp::interaction::PotentialTemplate< Tabulated >, espressopp::interaction::PotentialTemplate< FENECapped >, espressopp::interaction::PotentialTemplate< FENE >, espressopp::interaction::PotentialTemplate< VSphereSelf >, espressopp::interaction::PotentialTemplate< LJcos >, espressopp::interaction::PotentialTemplate< LennardJonesExpand >, espressopp::interaction::PotentialTemplate< TersoffPairTerm >, espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >, espressopp::interaction::PotentialTemplate< LennardJonesGromacs >, espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >, espressopp::interaction::PotentialTemplate< Quartic >, espressopp::interaction::PotentialTemplate< GravityTruncated >, espressopp::interaction::PotentialTemplate< CoulombKSpaceP3M >, espressopp::interaction::PotentialTemplate< LennardJonesCapped >, espressopp::interaction::PotentialTemplate< MirrorLennardJones >, espressopp::interaction::PotentialTemplate< Zero >, espressopp::interaction::PotentialTemplate< Morse >, espressopp::interaction::PotentialTemplate< ConstrainCOM >, espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >, and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >.
Referenced by registerPython(), ~Potential(), and espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::~PotentialTemplate().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/Potential.hpp
/home/espressopp/espressopp/src/interaction/Potential.cpp