ESPResSo++: espressopp::interaction::VSpherePair Class Reference
espressopp::interaction::VSpherePair Class Reference
This class provides methods to compute forces and energies of the VSpherePair potential.
#include <VSpherePair.hpp>
Public Member Functions
VSpherePair ()
VSpherePair (real _epsilon, real _cutoff, real _shift)
VSpherePair (real _epsilon, real _cutoff)
virtual ~VSpherePair ()
void preset ()
void setEpsilon (real _epsilon)
real getEpsilon () const
real _computeEnergySqrRaw (real distSqr, real sigmaij) const
bool _computeForceRaw (Real3D &force, real &fsi, real &fsj, const Real3D &dist, real distSqr, real sigmai, real sigmaj) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist, real &sigmaij) const
virtual real computeEnergy (real dist, real sigmaij) const
virtual real computeEnergySqr (real distsqr, real sigmaij) const
virtual python::list computeForce (const Particle &p1, const Particle &p2) const
virtual python::list computeForce (const Real3D &dist, const real &sigmai, const real &sigmaj) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Real3D &dist, real &sigmaij) const
real _computeEnergy (real dist, real sigmaij) const
real _computeEnergySqr (real distSqr, real sigmaij) const
bool _computeForce (Real3D &force, real &sigiforce, real &sigjforce, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, real &sigiforce, real &sigjforce, const Real3D &dist, const real &sigmai, const real &sigmaj) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
VSpherePair * derived_this ()
const VSpherePair * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
Private Attributes
real epsilon
real ff1
real ef1
real mth
real mfh
Detailed Description
This class provides methods to compute forces and energies of the VSpherePair potential.
Definition at line 49 of file VSpherePair.hpp.
Constructor & Destructor Documentation
VSpherePair() [1/3]
espressopp::interaction::VSpherePair::VSpherePair () inline
Definition at line 59 of file VSpherePair.hpp.
References espressopp::infinity, preset(), espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::setCutoff(), and espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::setShift().
VSpherePair() [2/3]
espressopp::interaction::VSpherePair::VSpherePair (real _epsilon, real _cutoff, real _shift) inline
Definition at line 66 of file VSpherePair.hpp.
References preset(), espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::setCutoff(), and espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::setShift().
VSpherePair() [3/3]
espressopp::interaction::VSpherePair::VSpherePair (real _epsilon, real _cutoff) inline
Definition at line 73 of file VSpherePair.hpp.
References espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::autoShift, preset(), espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::setAutoShift(), and espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::setCutoff().
~VSpherePair()
virtual espressopp::interaction::VSpherePair::~VSpherePair () inline virtual
Definition at line 81 of file VSpherePair.hpp.
Member Function Documentation
_computeEnergy() [1/3]
real espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::_computeEnergy (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 240 of file PotentialVSpherePair.hpp.
References espressopp::Particle::position(), and espressopp::Particle::radius().
_computeEnergy() [2/3]
real espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::_computeEnergy (const Real3D & dist, real & sigmaij) const inline inherited
Definition at line 251 of file PotentialVSpherePair.hpp.
References espressopp::Real3D::sqr().
_computeEnergy() [3/3]
real espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::_computeEnergy (real dist, real sigmaij) const inline inherited
Definition at line 258 of file PotentialVSpherePair.hpp.
_computeEnergySqr()
real espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::_computeEnergySqr (real distSqr, real sigmaij) const inline inherited
Definition at line 265 of file PotentialVSpherePair.hpp.
References LOG4ESPP_TRACE.
_computeEnergySqrRaw()
real espressopp::interaction::VSpherePair::_computeEnergySqrRaw (real distSqr, real sigmaij) const inline
Definition at line 99 of file VSpherePair.hpp.
_computeForce() [1/2]
bool espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::_computeForce (Real3D & force, real & sigiforce, real & sigjforce, const Particle & p1, const Particle & p2) const inline inherited
Definition at line 317 of file PotentialVSpherePair.hpp.
References espressopp::Particle::position(), and espressopp::Particle::radius().
_computeForce() [2/2]
bool espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::_computeForce (Real3D & force, real & sigiforce, real & sigjforce, const Real3D & dist, const real & sigmai, const real & sigmaj) const inline inherited
Definition at line 328 of file PotentialVSpherePair.hpp.
References espressopp::Real3D::sqr().
_computeForceRaw()
bool espressopp::interaction::VSpherePair::_computeForceRaw (Real3D & force, real & fsi, real & fsj, const Real3D & dist, real distSqr, real sigmai, real sigmaj) const inline
Definition at line 104 of file VSpherePair.hpp.
computeEnergy() [1/3]
real espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::computeEnergy (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::PotentialVSpherePair.
Definition at line 208 of file PotentialVSpherePair.hpp.
References espressopp::Particle::position(), and espressopp::Particle::radius().
computeEnergy() [2/3]
real espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::computeEnergy (const Real3D & dist, real & sigmaij) const inline virtual inherited
Implements espressopp::interaction::PotentialVSpherePair.
Definition at line 219 of file PotentialVSpherePair.hpp.
References espressopp::Real3D::sqr().
computeEnergy() [3/3]
real espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::computeEnergy (real dist, real sigmaij) const inline virtual inherited
Implements espressopp::interaction::PotentialVSpherePair.
Definition at line 226 of file PotentialVSpherePair.hpp.
computeEnergySqr()
real espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::computeEnergySqr (real distsqr, real sigmaij) const inline virtual inherited
Implements espressopp::interaction::PotentialVSpherePair.
Definition at line 233 of file PotentialVSpherePair.hpp.
computeForce() [1/2]
python::list espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::computeForce (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::PotentialVSpherePair.
Definition at line 279 of file PotentialVSpherePair.hpp.
computeForce() [2/2]
python::list espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::computeForce (const Real3D & dist, const real & sigmai, const real & sigmaj) const inline virtual inherited
Implements espressopp::interaction::PotentialVSpherePair.
Definition at line 298 of file PotentialVSpherePair.hpp.
derived_this() [1/2]
VSpherePair * espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::derived_this () inline protected inherited
Definition at line 118 of file PotentialVSpherePair.hpp.
derived_this() [2/2]
const VSpherePair * espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::derived_this () const inline protected inherited
Definition at line 122 of file PotentialVSpherePair.hpp.
getCutoff()
real espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::PotentialVSpherePair.
Definition at line 165 of file PotentialVSpherePair.hpp.
getEpsilon()
real espressopp::interaction::VSpherePair::getEpsilon () const inline
Definition at line 97 of file VSpherePair.hpp.
References epsilon.
Referenced by espressopp::interaction::VSpherePair_pickle::getinitargs(), and registerPython().
getShift()
real espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::getShift () const inline virtual inherited
Implements espressopp::interaction::PotentialVSpherePair.
Definition at line 179 of file PotentialVSpherePair.hpp.
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::PotentialVSpherePair::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
Referenced by espressopp::interaction::PotentialVSpherePair::~PotentialVSpherePair().
preset()
void espressopp::interaction::VSpherePair::preset () inline
Definition at line 83 of file VSpherePair.hpp.
References ef1, and M_PIl.
Referenced by setEpsilon(), and VSpherePair().
registerPython()
void espressopp::interaction::VSpherePair::registerPython () static
Definition at line 38 of file VSpherePair.cpp.
References getEpsilon(), and setEpsilon().
Referenced by espressopp::interaction::registerPython().
setAutoShift()
real espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::setAutoShift () inline virtual inherited
Implements espressopp::interaction::PotentialVSpherePair.
Definition at line 185 of file PotentialVSpherePair.hpp.
References espressopp::infinity.
Referenced by VSpherePair().
setCutoff()
void espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::PotentialVSpherePair.
Definition at line 157 of file PotentialVSpherePair.hpp.
Referenced by VSpherePair().
setEpsilon()
void espressopp::interaction::VSpherePair::setEpsilon (real _epsilon) inline
Definition at line 91 of file VSpherePair.hpp.
References preset(), and espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::updateAutoShift().
Referenced by registerPython().
setShift()
void espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::setShift (real _shift) inline virtual inherited
Implements espressopp::interaction::PotentialVSpherePair.
Definition at line 171 of file PotentialVSpherePair.hpp.
Referenced by VSpherePair().
updateAutoShift()
void espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::updateAutoShift () inline inherited
Definition at line 200 of file PotentialVSpherePair.hpp.
Referenced by setEpsilon().
Member Data Documentation
autoShift
bool espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::autoShift protected inherited
Definition at line 116 of file PotentialVSpherePair.hpp.
Referenced by VSpherePair().
cutoff
real espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::cutoff protected inherited
Definition at line 113 of file PotentialVSpherePair.hpp.
cutoffSqr
real espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::cutoffSqr protected inherited
Definition at line 114 of file PotentialVSpherePair.hpp.
ef1
real espressopp::interaction::VSpherePair::ef1 private
Definition at line 53 of file VSpherePair.hpp.
Referenced by preset().
epsilon
real espressopp::interaction::VSpherePair::epsilon private
Definition at line 51 of file VSpherePair.hpp.
Referenced by getEpsilon().
ff1
real espressopp::interaction::VSpherePair::ff1 private
Definition at line 52 of file VSpherePair.hpp.
mfh
real espressopp::interaction::VSpherePair::mfh private
Definition at line 54 of file VSpherePair.hpp.
mth
real espressopp::interaction::VSpherePair::mth private
Definition at line 54 of file VSpherePair.hpp.
shift
real espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::shift protected inherited
Definition at line 115 of file PotentialVSpherePair.hpp.
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/VSpherePair.hpp
/home/espressopp/espressopp/src/interaction/VSpherePair.cpp