ESPResSo++: espressopp::interaction::LennardJonesEnergyCapped Class Reference
espressopp::interaction::LennardJonesEnergyCapped Class Reference
This class provides methods to compute forces and energies of the Lennard Jones potential with capped energy.
#include <LennardJonesEnergyCapped.hpp>
Public Member Functions
LennardJonesEnergyCapped ()
LennardJonesEnergyCapped (real _epsilon, real _sigma, real _cutoff, real _caprad, real _shift)
LennardJonesEnergyCapped (real _epsilon, real _sigma, real _cutoff, real _caprad)
void preset ()
void setEpsilon (real _epsilon)
real getEpsilon () const
void setCaprad (real _caprad)
real getCaprad () const
void setSigma (real _sigma)
real getSigma () const
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &dist, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
real _computeEnergyDeriv (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
LennardJonesEnergyCapped * derived_this ()
const LennardJonesEnergyCapped * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
Private Attributes
real epsilon
real sigma
real ff1
real ff2
real ef1
real ef2
real caprad
real capradSqr
Detailed Description
This class provides methods to compute forces and energies of the Lennard Jones potential with capped energy.
Definition at line 40 of file LennardJonesEnergyCapped.hpp.
Constructor & Destructor Documentation
LennardJonesEnergyCapped() [1/3]
espressopp::interaction::LennardJonesEnergyCapped::LennardJonesEnergyCapped () inline
Definition at line 52 of file LennardJonesEnergyCapped.hpp.
References espressopp::infinity, preset(), espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::setCutoff(), and espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::setShift().
LennardJonesEnergyCapped() [2/3]
espressopp::interaction::LennardJonesEnergyCapped::LennardJonesEnergyCapped (real _epsilon, real _sigma, real _cutoff, real _caprad, real _shift) inline
Definition at line 59 of file LennardJonesEnergyCapped.hpp.
References preset(), espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::setCutoff(), and espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::setShift().
LennardJonesEnergyCapped() [3/3]
espressopp::interaction::LennardJonesEnergyCapped::LennardJonesEnergyCapped (real _epsilon, real _sigma, real _cutoff, real _caprad) inline
Definition at line 67 of file LennardJonesEnergyCapped.hpp.
References espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::autoShift, preset(), espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::setAutoShift(), and espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::setCutoff().
Member Function Documentation
_computeEnergy() [1/4]
real espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::_computeEnergy (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 242 of file Potential.hpp.
_computeEnergy() [2/4]
real espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::_computeEnergy (const Real3D & dist) const inline inherited
Definition at line 257 of file Potential.hpp.
_computeEnergy() [3/4]
real espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::_computeEnergy (real dist) const inline inherited
Definition at line 264 of file Potential.hpp.
_computeEnergy() [4/4]
real espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 250 of file Potential.hpp.
_computeEnergyDeriv()
real espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::_computeEnergyDeriv (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 285 of file Potential.hpp.
_computeEnergySqr()
real espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::_computeEnergySqr (real distSqr) const inline inherited
Definition at line 271 of file Potential.hpp.
_computeEnergySqrRaw()
real espressopp::interaction::LennardJonesEnergyCapped::_computeEnergySqrRaw (real distSqr) const inline
Definition at line 110 of file LennardJonesEnergyCapped.hpp.
References capradSqr.
_computeForce() [1/3]
bool espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const inline inherited
Definition at line 313 of file Potential.hpp.
_computeForce() [2/3]
bool espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::_computeForce (Real3D & force, const Real3D & dist) const inline inherited
Definition at line 328 of file Potential.hpp.
_computeForce() [3/3]
bool espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 321 of file Potential.hpp.
_computeForceRaw()
bool espressopp::interaction::LennardJonesEnergyCapped::_computeForceRaw (Real3D & force, const Real3D & dist, real distSqr) const inline
Definition at line 126 of file LennardJonesEnergyCapped.hpp.
References ff2.
computeEnergy() [1/3]
real espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::computeEnergy (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 213 of file Potential.hpp.
computeEnergy() [2/3]
real espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::computeEnergy (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 221 of file Potential.hpp.
computeEnergy() [3/3]
real espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::computeEnergy (real dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 228 of file Potential.hpp.
computeEnergySqr()
real espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::computeEnergySqr (real distsqr) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 235 of file Potential.hpp.
computeForce() [1/2]
Real3D espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::computeForce (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 295 of file Potential.hpp.
computeForce() [2/2]
Real3D espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::computeForce (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 303 of file Potential.hpp.
derived_this() [1/2]
LennardJonesEnergyCapped * espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::derived_this () inline protected inherited
Definition at line 123 of file Potential.hpp.
derived_this() [2/2]
const LennardJonesEnergyCapped * espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::derived_this () const inline protected inherited
Definition at line 127 of file Potential.hpp.
getCaprad()
real espressopp::interaction::LennardJonesEnergyCapped::getCaprad () const inline
Definition at line 101 of file LennardJonesEnergyCapped.hpp.
References caprad.
Referenced by registerPython().
getCutoff()
real espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 171 of file Potential.hpp.
getEpsilon()
real espressopp::interaction::LennardJonesEnergyCapped::getEpsilon () const inline
Definition at line 93 of file LennardJonesEnergyCapped.hpp.
References epsilon.
Referenced by espressopp::interaction::LennardJonesEnergyCapped_pickle::getinitargs(), and registerPython().
getShift()
real espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::getShift () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 186 of file Potential.hpp.
getSigma()
real espressopp::interaction::LennardJonesEnergyCapped::getSigma () const inline
Definition at line 108 of file LennardJonesEnergyCapped.hpp.
References sigma.
Referenced by espressopp::interaction::LennardJonesEnergyCapped_pickle::getinitargs(), and registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
Referenced by espressopp::interaction::Potential::~Potential().
preset()
void espressopp::interaction::LennardJonesEnergyCapped::preset () inline
Definition at line 76 of file LennardJonesEnergyCapped.hpp.
References caprad, and sigma.
Referenced by LennardJonesEnergyCapped(), setCaprad(), setEpsilon(), and setSigma().
registerPython()
void espressopp::interaction::LennardJonesEnergyCapped::registerPython () static
Definition at line 50 of file LennardJonesEnergyCapped.cpp.
References getCaprad(), getEpsilon(), getSigma(), setCaprad(), setEpsilon(), and setSigma().
Referenced by espressopp::interaction::registerPython().
setAutoShift()
real espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::setAutoShift () inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 192 of file Potential.hpp.
Referenced by LennardJonesEnergyCapped().
setCaprad()
void espressopp::interaction::LennardJonesEnergyCapped::setCaprad (real _caprad) inline
Definition at line 95 of file LennardJonesEnergyCapped.hpp.
References preset(), and espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::updateAutoShift().
Referenced by registerPython().
setCutoff()
void espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 162 of file Potential.hpp.
Referenced by LennardJonesEnergyCapped().
setEpsilon()
void espressopp::interaction::LennardJonesEnergyCapped::setEpsilon (real _epsilon) inline
Definition at line 87 of file LennardJonesEnergyCapped.hpp.
References preset(), and espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::updateAutoShift().
Referenced by registerPython().
setShift()
void espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::setShift (real _shift) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 177 of file Potential.hpp.
Referenced by LennardJonesEnergyCapped().
setSigma()
void espressopp::interaction::LennardJonesEnergyCapped::setSigma (real _sigma) inline
Definition at line 103 of file LennardJonesEnergyCapped.hpp.
References preset(), and espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::updateAutoShift().
Referenced by registerPython().
updateAutoShift()
void espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::updateAutoShift () inline inherited
Definition at line 205 of file Potential.hpp.
Referenced by setCaprad(), setEpsilon(), and setSigma().
Member Data Documentation
autoShift
bool espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::autoShift protected inherited
Definition at line 121 of file Potential.hpp.
Referenced by LennardJonesEnergyCapped().
caprad
real espressopp::interaction::LennardJonesEnergyCapped::caprad private
Definition at line 46 of file LennardJonesEnergyCapped.hpp.
Referenced by getCaprad(), and preset().
capradSqr
real espressopp::interaction::LennardJonesEnergyCapped::capradSqr private
Definition at line 47 of file LennardJonesEnergyCapped.hpp.
Referenced by _computeEnergySqrRaw().
cutoff
real espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::cutoff protected inherited
Definition at line 118 of file Potential.hpp.
cutoffSqr
real espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::cutoffSqr protected inherited
Definition at line 119 of file Potential.hpp.
ef1
real espressopp::interaction::LennardJonesEnergyCapped::ef1 private
Definition at line 45 of file LennardJonesEnergyCapped.hpp.
ef2
real espressopp::interaction::LennardJonesEnergyCapped::ef2 private
Definition at line 45 of file LennardJonesEnergyCapped.hpp.
epsilon
real espressopp::interaction::LennardJonesEnergyCapped::epsilon private
Definition at line 42 of file LennardJonesEnergyCapped.hpp.
Referenced by getEpsilon().
ff1
real espressopp::interaction::LennardJonesEnergyCapped::ff1 private
Definition at line 44 of file LennardJonesEnergyCapped.hpp.
ff2
real espressopp::interaction::LennardJonesEnergyCapped::ff2 private
Definition at line 44 of file LennardJonesEnergyCapped.hpp.
Referenced by _computeForceRaw().
shift
real espressopp::interaction::PotentialTemplate< LennardJonesEnergyCapped >::shift protected inherited
Definition at line 120 of file Potential.hpp.
sigma
real espressopp::interaction::LennardJonesEnergyCapped::sigma private
Definition at line 43 of file LennardJonesEnergyCapped.hpp.
Referenced by getSigma(), and preset().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/LennardJonesEnergyCapped.hpp
/home/espressopp/espressopp/src/interaction/LennardJonesEnergyCapped.cpp