ESPResSo++: espressopp::integrator::LatticeBoltzmann Class Reference
espressopp::integrator::LatticeBoltzmann Class Reference
#include <LatticeBoltzmann.hpp>
Public Types
enum ExtensionType {
all =0, Thermostat =1, Barostat =2, Constraint =3,
Adress =4, FreeEnergyCompensation =5, ExtForce =6, ExtAnalysis =7,
Reaction =8
}
Public Member Functions
LatticeBoltzmann (shared_ptr< System > _system, Int3D _nodeGrid, real _a, real _tau, int _numDims, int _numVels)
~LatticeBoltzmann ()
void setMyNeigh (int _dir, int _rank)
int getMyNeigh (int _dir)
void setNodeGrid (Int3D _nodeGrid)
Int3D getNodeGrid ()
void setMyPos (Int3D _myPos)
Int3D getMyPos ()
void setHaloSkin (int _haloSkin)
int getHaloSkin ()
void setMyNi (Int3D _myNi)
Int3D getMyNi ()
void setMyLeft (Real3D _myLeft)
Real3D getMyLeft ()
void setNi (Int3D _Ni)
Int3D getNi ()
void setA (real _a)
real getA ()
void setTau (real _tau)
real getTau ()
void setNumDims (int _numDims)
int getNumDims ()
void setNumVels (int _numVels)
int getNumVels ()
void setEqWeight (int _l, real _value)
real getEqWeight (int _l)
void setCi (int _l, Real3D _vec)
Real3D getCi (int _l)
void setCs2 (real _cs2)
real getCs2 ()
void setInvB (int _l, real _value)
real getInvB (int _l)
void setGamma (int _i, real _gamma)
real getGamma (int _i)
void setGammaB (real _gamma_b)
real getGammaB ()
void setGammaS (real _gamma_s)
real getGammaS ()
void setGammaOdd (real _gamma_odd)
real getGammaOdd ()
void setGammaEven (real _gamma_even)
real getGammaEven ()
void setViscB (real _visc_b)
real getViscB ()
void setViscS (real _visc_s)
real getViscS ()
void setLBTemp (real _lbTemp)
real getLBTemp ()
void setDoFluct (bool _fluct)
bool doFluct ()
void setPhi (int _l, real _value)
real getPhi (int _l)
void setDoExtForce (bool _extForce)
bool doExtForce ()
void setDoCoupling (bool _coupling)
bool doCoupling ()
void setExtForceLoc (Int3D _Ni, Real3D _extForceLoc)
Real3D getExtForceLoc (Int3D _Ni)
void addExtForceLoc (Int3D _Ni, Real3D _extForceLoc)
void setFricCoeff (real _fricCoeff)
real getFricCoeff ()
void setNSteps (int _nSteps)
int getNSteps ()
void setPrevDumpStep (int saveStep)
int getPrevDumpStep ()
void setTotNPart (int _totNPart)
int getTotNPart ()
void setFOnPart (int _id, Real3D _fOnPart)
Real3D getFOnPart (int _id)
void addFOnPart (int _id, Real3D _fOnPart)
void keepLBDump ()
void setPops (Int3D _Ni, int _l, real _value)
real getPops (Int3D _Ni, int _l)
void setGhostFluid (Int3D _Ni, int _l, real _value)
void setLBMom (Int3D _Ni, int _l, real _value)
real getLBMom (Int3D _Ni, int _l)
void setJLoc (Real3D _value)
Real3D getJLoc ()
real convMassMDtoLB ()
real convTimeMDtoLB ()
real convLenMDtoLB ()
void setProfStep (int _profStep)
int getProfStep ()
void setStepNum (int _step)
int getStepNum ()
void setCopyTimestep (real _copyTimestep)
real getCopyTimestep ()
void setDoRestart (bool _restart)
bool doRestart ()
void readLBConf (int _mode)
void saveLBConf ()
void initLatticeSize ()
void initLatticeModel ()
void initFluctuations ()
void makeLBStep ()
Real3D findCMVelMD ()
void zeroMDCMVel ()
void galileanTransf (Real3D _specCmVel)
void coupleLBtoMD ()
void calcRandForce (class Particle &)
void calcViscForce (class Particle &)
void calcDenMom ()
real convMDtoLB (int _opCode)
void collideStream ()
void streaming (int _i, int _j, int _k)
void findMyNeighbours ()
void assignMyLattice ()
Int3D findGlobIdx ()
void commHalo ()
void copyForcesFromHalo ()
void copyDenMomToHalo ()
void makeDecompose ()
void computeDensity (int _i, int _j, int _k)
void computeMomentum (int _i, int _j, int _k)
ExtensionType getType ()
void setType (ExtensionType k)
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
Register this class so it can be used from Python.
Public Attributes
ExtensionType type
Protected Member Functions
void setIntegrator (shared_ptr< MDIntegrator > _integrator)
Protected Attributes
shared_ptr< MDIntegrator > integrator
Private Member Functions
void connect ()
void disconnect ()
Static Private Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Private Attributes
int numDims
int numVels
real a
real tau
real cs2
real invCs2
std::vector< Real3D > c_i
std::vector< real > eqWeight
std::vector< real > inv_b
Int3D Ni
real visc_b
real visc_s
std::vector< real > gamma
bool fluct
real lbTemp
std::vector< real > phi
int start
int stepNum
real copyTimestep
bool restart
shared_ptr< esutil::RNG > rng
random number generator used for fluctuations
bool extForce
lblattice * lbfluid
lblattice * ghostlat
lbmoments * lbmom
lbforces * lbfor
bool coupling
int nSteps
int totNPart
real fricCoeff
std::vector< Real3D > fOnPart
int saveStep
std::vector< int > myNeigh
Int3D myPos
int haloSkin
Int3D myNi
Int3D nodeGrid
Real3D myLeft
boost::signals2::connection _befIntV
boost::signals2::connection _recalc2
esutil::WallTimer swapping
esutil::WallTimer colstream
esutil::WallTimer comm
esutil::WallTimer timeReadLBConf
esutil::WallTimer timeSaveLBConf
real time_sw
real time_colstr
real time_comm
int profStep
Detailed Description
Definition at line 41 of file LatticeBoltzmann.hpp.
Member Enumeration Documentation
ExtensionType
enum espressopp::integrator::Extension::ExtensionType inherited
Enumerator
all
Thermostat
Barostat
Constraint
Adress
FreeEnergyCompensation
ExtForce
ExtAnalysis
Reaction
Definition at line 48 of file Extension.hpp.
Constructor & Destructor Documentation
LatticeBoltzmann()
espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann (shared_ptr< System > _system, Int3D _nodeGrid, real _a, real _tau, int _numDims, int _numVels)
Definition at line 51 of file LatticeBoltzmann.cpp.
References assignMyLattice(), c_i, colstream, comm, eqWeight, findMyNeighbours(), fOnPart, gamma, getA(), getNumVels(), espressopp::SystemAccess::getSystem(), getTau(), initLatticeModel(), initLatticeSize(), inv_b, myNeigh, phi, espressopp::esutil::Timer::reset(), rng, setDoCoupling(), setDoExtForce(), setDoFluct(), setDoRestart(), setFOnPart(), setFricCoeff(), setHaloSkin(), setNSteps(), setPrevDumpStep(), setProfStep(), setTotNPart(), swapping, time_colstr, time_comm, and time_sw.
~LatticeBoltzmann()
espressopp::integrator::LatticeBoltzmann::~LatticeBoltzmann ()
Definition at line 2093 of file LatticeBoltzmann.cpp.
References disconnect().
Member Function Documentation
addExtForceLoc()
void espressopp::integrator::LatticeBoltzmann::addExtForceLoc (Int3D _Ni, Real3D _extForceLoc)
Definition at line 244 of file LatticeBoltzmann.cpp.
References lbfor.
addFOnPart()
void espressopp::integrator::LatticeBoltzmann::addFOnPart (int _id, Real3D _fOnPart)
Definition at line 261 of file LatticeBoltzmann.cpp.
References fOnPart.
Referenced by calcViscForce().
assignMyLattice()
void espressopp::integrator::LatticeBoltzmann::assignMyLattice ()
Definition at line 1205 of file LatticeBoltzmann.cpp.
References getA(), getHaloSkin(), getMyPos(), getNodeGrid(), getNumDims(), espressopp::SystemAccess::getSystem(), setMyLeft(), setMyNi(), and setNi().
Referenced by LatticeBoltzmann().
calcDenMom()
void espressopp::integrator::LatticeBoltzmann::calcDenMom ()
Definition at line 727 of file LatticeBoltzmann.cpp.
References getCi(), getHaloSkin(), getMyNi(), and getNumVels().
Referenced by collideStream().
calcRandForce()
void espressopp::integrator::LatticeBoltzmann::calcRandForce (class Particle & p)
Definition at line 630 of file LatticeBoltzmann.cpp.
References getFricCoeff(), getLBTemp(), espressopp::Particle::id(), espressopp::integrator::Extension::integrator, rng, and setFOnPart().
Referenced by coupleLBtoMD().
calcViscForce()
void espressopp::integrator::LatticeBoltzmann::calcViscForce (class Particle & p)
Definition at line 646 of file LatticeBoltzmann.cpp.
References addFOnPart(), convLenMDtoLB(), convMassMDtoLB(), convTimeMDtoLB(), espressopp::Particle::force(), getA(), getFOnPart(), getFricCoeff(), getHaloSkin(), getMyLeft(), espressopp::SystemAccess::getSystem(), espressopp::Particle::id(), lbmom, espressopp::Particle::position(), and espressopp::Particle::velocity().
Referenced by coupleLBtoMD().
collideStream()
void espressopp::integrator::LatticeBoltzmann::collideStream ()
Definition at line 517 of file LatticeBoltzmann.cpp.
References calcDenMom(), colstream, comm, commHalo(), copyDenMomToHalo(), copyForcesFromHalo(), doCoupling(), doExtForce(), doFluct(), gamma, espressopp::esutil::Timer::getElapsedTime(), getHaloSkin(), getMyNi(), ghostlat, lbfluid, streaming(), swapping, time_colstr, time_comm, and time_sw.
Referenced by makeLBStep().
commHalo()
void espressopp::integrator::LatticeBoltzmann::commHalo ()
Definition at line 1245 of file LatticeBoltzmann.cpp.
References COMM_DIR_0, COMM_DIR_1, getHaloSkin(), getMyNeigh(), getMyNi(), getMyPos(), and getNodeGrid().
Referenced by collideStream().
computeDensity()
void espressopp::integrator::LatticeBoltzmann::computeDensity (int _i, int _j, int _k)
computeMomentum()
void espressopp::integrator::LatticeBoltzmann::computeMomentum (int _i, int _j, int _k)
connect()
void espressopp::integrator::LatticeBoltzmann::connect () private virtual
Implements espressopp::integrator::Extension.
Definition at line 137 of file LatticeBoltzmann.cpp.
References _befIntV, _recalc2, espressopp::integrator::Extension::integrator, makeLBStep(), and zeroMDCMVel().
Referenced by registerPython().
convLenMDtoLB()
real espressopp::integrator::LatticeBoltzmann::convLenMDtoLB ()
Definition at line 284 of file LatticeBoltzmann.cpp.
References getA(), espressopp::Int3D::getItem(), getNi(), and espressopp::SystemAccess::getSystem().
Referenced by calcViscForce(), initFluctuations(), setViscB(), and setViscS().
convMassMDtoLB()
real espressopp::integrator::LatticeBoltzmann::convMassMDtoLB ()
Definition at line 280 of file LatticeBoltzmann.cpp.
Referenced by calcViscForce(), initFluctuations(), setViscB(), and setViscS().
convMDtoLB()
real espressopp::integrator::LatticeBoltzmann::convMDtoLB (int _opCode)
convTimeMDtoLB()
real espressopp::integrator::LatticeBoltzmann::convTimeMDtoLB ()
Definition at line 283 of file LatticeBoltzmann.cpp.
References getTau(), and espressopp::integrator::Extension::integrator.
Referenced by calcViscForce(), initFluctuations(), setViscB(), and setViscS().
copyDenMomToHalo()
void espressopp::integrator::LatticeBoltzmann::copyDenMomToHalo ()
Definition at line 1819 of file LatticeBoltzmann.cpp.
References COMM_DEN_0, COMM_DEN_1, getHaloSkin(), getMyNeigh(), getMyNi(), getMyPos(), and getNodeGrid().
Referenced by collideStream(), and zeroMDCMVel().
copyForcesFromHalo()
void espressopp::integrator::LatticeBoltzmann::copyForcesFromHalo ()
Definition at line 1543 of file LatticeBoltzmann.cpp.
References COMM_FORCE_0, COMM_FORCE_1, getHaloSkin(), getMyNeigh(), getMyNi(), getMyPos(), and getNodeGrid().
Referenced by collideStream().
coupleLBtoMD()
void espressopp::integrator::LatticeBoltzmann::coupleLBtoMD ()
Definition at line 615 of file LatticeBoltzmann.cpp.
References calcRandForce(), calcViscForce(), espressopp::SystemAccess::getSystemRef(), espressopp::iterator::CellListIterator::isDone(), setDoExtForce(), and espressopp::System::storage.
Referenced by makeLBStep().
disconnect()
void espressopp::integrator::LatticeBoltzmann::disconnect () private virtual
Implements espressopp::integrator::Extension.
Definition at line 127 of file LatticeBoltzmann.cpp.
References _befIntV, _recalc2, ghostlat, lbfluid, lbfor, and lbmom.
Referenced by registerPython(), and ~LatticeBoltzmann().
doCoupling()
bool espressopp::integrator::LatticeBoltzmann::doCoupling ()
Definition at line 238 of file LatticeBoltzmann.cpp.
References coupling.
Referenced by collideStream(), makeLBStep(), and zeroMDCMVel().
doExtForce()
bool espressopp::integrator::LatticeBoltzmann::doExtForce ()
Definition at line 235 of file LatticeBoltzmann.cpp.
References extForce.
Referenced by collideStream().
doFluct()
bool espressopp::integrator::LatticeBoltzmann::doFluct ()
Definition at line 228 of file LatticeBoltzmann.cpp.
References fluct.
Referenced by collideStream().
doRestart()
bool espressopp::integrator::LatticeBoltzmann::doRestart ()
Definition at line 299 of file LatticeBoltzmann.cpp.
References restart.
Referenced by zeroMDCMVel().
findCMVelMD()
Real3D espressopp::integrator::LatticeBoltzmann::findCMVelMD ()
Definition at line 753 of file LatticeBoltzmann.cpp.
References espressopp::System::comm, espressopp::SystemAccess::getSystemRef(), getTotNPart(), espressopp::iterator::CellListIterator::isDone(), and espressopp::System::storage.
Referenced by zeroMDCMVel().
findGlobIdx()
Int3D espressopp::integrator::LatticeBoltzmann::findGlobIdx ()
Definition at line 1229 of file LatticeBoltzmann.cpp.
References getMyPos(), getNi(), and getNodeGrid().
findMyNeighbours()
void espressopp::integrator::LatticeBoltzmann::findMyNeighbours ()
Definition at line 1168 of file LatticeBoltzmann.cpp.
References getNodeGrid(), getNumDims(), espressopp::SystemAccess::getSystem(), espressopp::esutil::Grid::mapIndexToPosition(), espressopp::esutil::Grid::mapPositionToIndex(), mpiWorld, setMyNeigh(), and setMyPos().
Referenced by LatticeBoltzmann().
galileanTransf()
void espressopp::integrator::LatticeBoltzmann::galileanTransf (Real3D _specCmVel)
Definition at line 822 of file LatticeBoltzmann.cpp.
References espressopp::SystemAccess::getSystemRef(), espressopp::iterator::CellListIterator::isDone(), and espressopp::System::storage.
Referenced by zeroMDCMVel().
getA()
real espressopp::integrator::LatticeBoltzmann::getA ()
Definition at line 169 of file LatticeBoltzmann.cpp.
References a.
Referenced by assignMyLattice(), calcViscForce(), convLenMDtoLB(), initFluctuations(), initLatticeModel(), LatticeBoltzmann(), makeDecompose(), and registerPython().
getCi()
Real3D espressopp::integrator::LatticeBoltzmann::getCi (int _l)
Definition at line 187 of file LatticeBoltzmann.cpp.
References c_i.
Referenced by calcDenMom().
getCopyTimestep()
real espressopp::integrator::LatticeBoltzmann::getCopyTimestep ()
Definition at line 296 of file LatticeBoltzmann.cpp.
References copyTimestep.
getCs2()
real espressopp::integrator::LatticeBoltzmann::getCs2 ()
Definition at line 190 of file LatticeBoltzmann.cpp.
References cs2.
Referenced by initFluctuations(), setViscB(), and setViscS().
getEqWeight()
real espressopp::integrator::LatticeBoltzmann::getEqWeight (int _l)
Definition at line 184 of file LatticeBoltzmann.cpp.
References eqWeight.
getExtForceLoc()
Real3D espressopp::integrator::LatticeBoltzmann::getExtForceLoc (Int3D _Ni)
Definition at line 242 of file LatticeBoltzmann.cpp.
References lbfor.
getFOnPart()
Real3D espressopp::integrator::LatticeBoltzmann::getFOnPart (int _id)
Definition at line 260 of file LatticeBoltzmann.cpp.
References fOnPart.
Referenced by calcViscForce(), readLBConf(), and saveLBConf().
getFricCoeff()
real espressopp::integrator::LatticeBoltzmann::getFricCoeff ()
Definition at line 248 of file LatticeBoltzmann.cpp.
References fricCoeff.
Referenced by calcRandForce(), calcViscForce(), and registerPython().
getGamma()
real espressopp::integrator::LatticeBoltzmann::getGamma (int _i)
Definition at line 197 of file LatticeBoltzmann.cpp.
References gamma.
Referenced by getGammaB(), getGammaEven(), getGammaOdd(), getGammaS(), and initFluctuations().
getGammaB()
real espressopp::integrator::LatticeBoltzmann::getGammaB ()
Definition at line 200 of file LatticeBoltzmann.cpp.
References getGamma().
Referenced by registerPython().
getGammaEven()
real espressopp::integrator::LatticeBoltzmann::getGammaEven ()
Definition at line 209 of file LatticeBoltzmann.cpp.
References getGamma().
Referenced by registerPython().
getGammaOdd()
real espressopp::integrator::LatticeBoltzmann::getGammaOdd ()
Definition at line 206 of file LatticeBoltzmann.cpp.
References getGamma().
Referenced by registerPython().
getGammaS()
real espressopp::integrator::LatticeBoltzmann::getGammaS ()
Definition at line 203 of file LatticeBoltzmann.cpp.
References getGamma().
Referenced by registerPython().
getHaloSkin()
int espressopp::integrator::LatticeBoltzmann::getHaloSkin ()
Definition at line 155 of file LatticeBoltzmann.cpp.
References haloSkin.
Referenced by assignMyLattice(), calcDenMom(), calcViscForce(), collideStream(), commHalo(), copyDenMomToHalo(), copyForcesFromHalo(), makeDecompose(), readLBConf(), and saveLBConf().
getInvB()
real espressopp::integrator::LatticeBoltzmann::getInvB (int _l)
Definition at line 193 of file LatticeBoltzmann.cpp.
References inv_b.
Referenced by initFluctuations().
getJLoc()
Real3D espressopp::integrator::LatticeBoltzmann::getJLoc ()
getLBMom()
real espressopp::integrator::LatticeBoltzmann::getLBMom (Int3D _Ni, int _l)
Definition at line 276 of file LatticeBoltzmann.cpp.
References lbmom.
Referenced by registerPython().
getLBTemp()
real espressopp::integrator::LatticeBoltzmann::getLBTemp ()
Definition at line 225 of file LatticeBoltzmann.cpp.
References lbTemp.
Referenced by calcRandForce(), initFluctuations(), and registerPython().
getMyLeft()
Real3D espressopp::integrator::LatticeBoltzmann::getMyLeft ()
Definition at line 161 of file LatticeBoltzmann.cpp.
References myLeft.
Referenced by calcViscForce(), and makeDecompose().
getMyNeigh()
int espressopp::integrator::LatticeBoltzmann::getMyNeigh (int _dir)
Definition at line 146 of file LatticeBoltzmann.cpp.
References myNeigh.
Referenced by commHalo(), copyDenMomToHalo(), and copyForcesFromHalo().
getMyNi()
Int3D espressopp::integrator::LatticeBoltzmann::getMyNi ()
Definition at line 158 of file LatticeBoltzmann.cpp.
References myNi.
Referenced by calcDenMom(), collideStream(), commHalo(), copyDenMomToHalo(), copyForcesFromHalo(), initFluctuations(), initLatticeSize(), makeDecompose(), readLBConf(), registerPython(), and saveLBConf().
getMyPos()
Int3D espressopp::integrator::LatticeBoltzmann::getMyPos ()
Definition at line 152 of file LatticeBoltzmann.cpp.
References myPos.
Referenced by assignMyLattice(), commHalo(), copyDenMomToHalo(), copyForcesFromHalo(), findGlobIdx(), readLBConf(), and saveLBConf().
getNi()
Int3D espressopp::integrator::LatticeBoltzmann::getNi ()
Definition at line 165 of file LatticeBoltzmann.cpp.
References Ni.
Referenced by convLenMDtoLB(), findGlobIdx(), and initLatticeModel().
getNodeGrid()
Int3D espressopp::integrator::LatticeBoltzmann::getNodeGrid ()
Definition at line 149 of file LatticeBoltzmann.cpp.
References nodeGrid.
Referenced by assignMyLattice(), commHalo(), copyDenMomToHalo(), copyForcesFromHalo(), findGlobIdx(), findMyNeighbours(), and registerPython().
getNSteps()
int espressopp::integrator::LatticeBoltzmann::getNSteps ()
Definition at line 251 of file LatticeBoltzmann.cpp.
References nSteps.
Referenced by initFluctuations(), makeLBStep(), registerPython(), setViscB(), and setViscS().
getNumDims()
int espressopp::integrator::LatticeBoltzmann::getNumDims ()
Definition at line 177 of file LatticeBoltzmann.cpp.
References numDims.
Referenced by assignMyLattice(), findMyNeighbours(), registerPython(), and setViscB().
getNumVels()
int espressopp::integrator::LatticeBoltzmann::getNumVels ()
Definition at line 181 of file LatticeBoltzmann.cpp.
References numVels.
Referenced by calcDenMom(), initFluctuations(), initLatticeModel(), LatticeBoltzmann(), readLBConf(), registerPython(), and saveLBConf().
getPhi()
real espressopp::integrator::LatticeBoltzmann::getPhi (int _l)
Definition at line 231 of file LatticeBoltzmann.cpp.
References phi.
Referenced by initFluctuations().
getPops()
real espressopp::integrator::LatticeBoltzmann::getPops (Int3D _Ni, int _l)
Definition at line 268 of file LatticeBoltzmann.cpp.
References lbfluid.
Referenced by saveLBConf().
getPrevDumpStep()
int espressopp::integrator::LatticeBoltzmann::getPrevDumpStep ()
Definition at line 254 of file LatticeBoltzmann.cpp.
References saveStep.
Referenced by saveLBConf().
getProfStep()
int espressopp::integrator::LatticeBoltzmann::getProfStep ()
Definition at line 289 of file LatticeBoltzmann.cpp.
References profStep.
Referenced by makeLBStep(), and registerPython().
getStepNum()
int espressopp::integrator::LatticeBoltzmann::getStepNum ()
Definition at line 293 of file LatticeBoltzmann.cpp.
References stepNum.
Referenced by makeLBStep(), readLBConf(), saveLBConf(), and zeroMDCMVel().
getSystem()
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), assignMyLattice(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::io::DumpXYZ::DumpXYZ(), findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), initFluctuations(), espressopp::integrator::StochasticVelocityRescaling::initialize(), initLatticeModel(), LatticeBoltzmann(), makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), readLBConf(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::VerletListTriple::registerPython(), espressopp::VerletList::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::storage::Storage::restorePositions(), saveLBConf(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), and zeroMDCMVel().
getSystem1()
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
getSystem2()
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
getSystemRef()
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::addForces(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::addForces(), espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerlet::calcForces(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeCOM(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::integrator::Settle::correctVelocities(), coupleLBtoMD(), findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::FixedLocalTupleComListInteractionTemplate(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::VelocityVerlet::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::VelocityVerlet::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::VelocityVerlet::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), makeDecompose(), espressopp::integrator::VelocityVerlet::printForces(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerlet::printPositions(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), readLBConf(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::MinimizeEnergy::run(), saveLBConf(), espressopp::integrator::Rattle::saveOldPos(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostatOnGroup::thermalize(), espressopp::integrator::LangevinThermostatOnRadius::thermalize(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::VelocityVerlet::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
getSystemRef1()
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
getSystemRef2()
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
getTau()
real espressopp::integrator::LatticeBoltzmann::getTau ()
Definition at line 173 of file LatticeBoltzmann.cpp.
References tau.
Referenced by convTimeMDtoLB(), initLatticeModel(), LatticeBoltzmann(), registerPython(), setViscB(), and setViscS().
getTotNPart()
int espressopp::integrator::LatticeBoltzmann::getTotNPart ()
Definition at line 257 of file LatticeBoltzmann.cpp.
References totNPart.
Referenced by findCMVelMD(), and readLBConf().
getType()
ExtensionType espressopp::integrator::Extension::getType () inline inherited
Definition at line 67 of file Extension.hpp.
References espressopp::integrator::Extension::type.
Referenced by espressopp::integrator::Extension::registerPython().
getViscB()
real espressopp::integrator::LatticeBoltzmann::getViscB ()
Definition at line 215 of file LatticeBoltzmann.cpp.
References visc_b.
Referenced by registerPython().
getViscS()
real espressopp::integrator::LatticeBoltzmann::getViscS ()
Definition at line 221 of file LatticeBoltzmann.cpp.
References visc_s.
Referenced by registerPython().
initFluctuations()
void espressopp::integrator::LatticeBoltzmann::initFluctuations ()
Definition at line 376 of file LatticeBoltzmann.cpp.
References convLenMDtoLB(), convMassMDtoLB(), convTimeMDtoLB(), getA(), getCs2(), getGamma(), getInvB(), getLBTemp(), getMyNi(), getNSteps(), getNumVels(), getPhi(), espressopp::SystemAccess::getSystem(), espressopp::ROUND_ERROR_PREC, setDoFluct(), and setPhi().
Referenced by setGammaB(), setGammaS(), and setLBTemp().
initLatticeModel()
void espressopp::integrator::LatticeBoltzmann::initLatticeModel ()
Definition at line 335 of file LatticeBoltzmann.cpp.
References getA(), espressopp::integrator::LatticePar::getEqWeightLoc(), espressopp::integrator::LatticePar::getInvBLoc(), espressopp::Int3D::getItem(), getNi(), getNumVels(), espressopp::SystemAccess::getSystem(), getTau(), setCi(), setCs2(), setEqWeight(), and setInvB().
Referenced by LatticeBoltzmann().
initLatticeSize()
void espressopp::integrator::LatticeBoltzmann::initLatticeSize ()
Definition at line 304 of file LatticeBoltzmann.cpp.
References getMyNi(), ghostlat, lbfluid, lbfor, and lbmom.
Referenced by LatticeBoltzmann().
keepLBDump()
void espressopp::integrator::LatticeBoltzmann::keepLBDump ()
Definition at line 263 of file LatticeBoltzmann.cpp.
References setPrevDumpStep().
Referenced by registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::integrator::LatticeBoltzmann::LOG4ESPP_DECL_LOGGER (theLogger) static private
Logger.
makeDecompose()
*void espressopp::integrator::LatticeBoltzmann::makeDecompose ()
Definition at line 483 of file LatticeBoltzmann.cpp.
References espressopp::System::comm, getA(), getHaloSkin(), getMyLeft(), getMyNi(), espressopp::SystemAccess::getSystemRef(), espressopp::iterator::CellListIterator::isDone(), and espressopp::System::storage.
Referenced by makeLBStep().
makeLBStep()
void espressopp::integrator::LatticeBoltzmann::makeLBStep ()
Definition at line 448 of file LatticeBoltzmann.cpp.
References collideStream(), colstream, comm, coupleLBtoMD(), doCoupling(), getNSteps(), getProfStep(), getStepNum(), espressopp::SystemAccess::getSystem(), espressopp::integrator::Extension::integrator, makeDecompose(), espressopp::esutil::Timer::reset(), setStepNum(), swapping, time_colstr, time_comm, and time_sw.
Referenced by connect().
readLBConf()
void espressopp::integrator::LatticeBoltzmann::readLBConf (int _mode)
Definition at line 839 of file LatticeBoltzmann.cpp.
References espressopp::esutil::Timer::getElapsedTime(), getFOnPart(), getHaloSkin(), getMyNi(), getMyPos(), getNumVels(), getStepNum(), espressopp::SystemAccess::getSystem(), espressopp::SystemAccess::getSystemRef(), getTotNPart(), espressopp::integrator::Extension::integrator, espressopp::iterator::CellListIterator::isDone(), espressopp::esutil::Timer::reset(), setFOnPart(), setPops(), espressopp::System::storage, and timeReadLBConf.
Referenced by zeroMDCMVel().
registerPython()
void espressopp::integrator::LatticeBoltzmann::registerPython () static
Register this class so it can be used from Python.
Definition at line 2105 of file LatticeBoltzmann.cpp.
References connect(), disconnect(), getA(), getFricCoeff(), getGammaB(), getGammaEven(), getGammaOdd(), getGammaS(), getLBMom(), getLBTemp(), getMyNi(), getNodeGrid(), getNSteps(), getNumDims(), getNumVels(), getProfStep(), getTau(), getViscB(), getViscS(), keepLBDump(), saveLBConf(), setA(), setFricCoeff(), setGammaB(), setGammaEven(), setGammaOdd(), setGammaS(), setLBMom(), setLBTemp(), setNodeGrid(), setNSteps(), setNumDims(), setNumVels(), setProfStep(), setTau(), setViscB(), and setViscS().
Referenced by espressopp::integrator::registerPython().
saveLBConf()
void espressopp::integrator::LatticeBoltzmann::saveLBConf ()
Definition at line 1009 of file LatticeBoltzmann.cpp.
References espressopp::System::comm, espressopp::esutil::Timer::getElapsedTime(), getFOnPart(), getHaloSkin(), getMyNi(), getMyPos(), getNumVels(), getPops(), getPrevDumpStep(), getStepNum(), espressopp::SystemAccess::getSystem(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::Extension::integrator, espressopp::iterator::CellListIterator::isDone(), espressopp::esutil::Timer::reset(), espressopp::ROUND_ERROR_PREC, setPrevDumpStep(), espressopp::Real3D::sqr(), espressopp::System::storage, and timeSaveLBConf.
Referenced by registerPython(), and zeroMDCMVel().
setA()
void espressopp::integrator::LatticeBoltzmann::setA (real _a)
Definition at line 167 of file LatticeBoltzmann.cpp.
References a.
Referenced by registerPython().
setCi()
void espressopp::integrator::LatticeBoltzmann::setCi (int _l, Real3D _vec)
Definition at line 186 of file LatticeBoltzmann.cpp.
References c_i.
Referenced by initLatticeModel().
setCopyTimestep()
void espressopp::integrator::LatticeBoltzmann::setCopyTimestep (real _copyTimestep)
Definition at line 295 of file LatticeBoltzmann.cpp.
References copyTimestep.
Referenced by zeroMDCMVel().
setCs2()
void espressopp::integrator::LatticeBoltzmann::setCs2 (real _cs2)
Definition at line 189 of file LatticeBoltzmann.cpp.
References cs2.
Referenced by initLatticeModel().
setDoCoupling()
void espressopp::integrator::LatticeBoltzmann::setDoCoupling (bool _coupling)
Definition at line 237 of file LatticeBoltzmann.cpp.
References coupling.
Referenced by LatticeBoltzmann().
setDoExtForce()
void espressopp::integrator::LatticeBoltzmann::setDoExtForce (bool _extForce)
Definition at line 234 of file LatticeBoltzmann.cpp.
References extForce.
Referenced by coupleLBtoMD(), and LatticeBoltzmann().
setDoFluct()
void espressopp::integrator::LatticeBoltzmann::setDoFluct (bool _fluct)
Definition at line 227 of file LatticeBoltzmann.cpp.
References fluct.
Referenced by initFluctuations(), and LatticeBoltzmann().
setDoRestart()
void espressopp::integrator::LatticeBoltzmann::setDoRestart (bool _restart)
Definition at line 298 of file LatticeBoltzmann.cpp.
References restart.
Referenced by LatticeBoltzmann(), and zeroMDCMVel().
setEqWeight()
void espressopp::integrator::LatticeBoltzmann::setEqWeight (int _l, real _value)
Definition at line 183 of file LatticeBoltzmann.cpp.
References eqWeight.
Referenced by initLatticeModel().
setExtForceLoc()
void espressopp::integrator::LatticeBoltzmann::setExtForceLoc (Int3D _Ni, Real3D _extForceLoc)
Definition at line 240 of file LatticeBoltzmann.cpp.
References lbfor.
setFOnPart()
void espressopp::integrator::LatticeBoltzmann::setFOnPart (int _id, Real3D _fOnPart)
Definition at line 259 of file LatticeBoltzmann.cpp.
References fOnPart.
Referenced by calcRandForce(), LatticeBoltzmann(), and readLBConf().
setFricCoeff()
void espressopp::integrator::LatticeBoltzmann::setFricCoeff (real _fricCoeff)
Definition at line 247 of file LatticeBoltzmann.cpp.
References fricCoeff.
Referenced by LatticeBoltzmann(), and registerPython().
setGamma()
void espressopp::integrator::LatticeBoltzmann::setGamma (int _i, real _gamma)
Definition at line 196 of file LatticeBoltzmann.cpp.
References gamma.
Referenced by setGammaB(), setGammaEven(), setGammaOdd(), setGammaS(), setViscB(), and setViscS().
setGammaB()
void espressopp::integrator::LatticeBoltzmann::setGammaB (real _gamma_b)
Definition at line 199 of file LatticeBoltzmann.cpp.
References initFluctuations(), and setGamma().
Referenced by registerPython().
setGammaEven()
void espressopp::integrator::LatticeBoltzmann::setGammaEven (real _gamma_even)
Definition at line 208 of file LatticeBoltzmann.cpp.
References setGamma().
Referenced by registerPython().
setGammaOdd()
void espressopp::integrator::LatticeBoltzmann::setGammaOdd (real _gamma_odd)
Definition at line 205 of file LatticeBoltzmann.cpp.
References setGamma().
Referenced by registerPython().
setGammaS()
void espressopp::integrator::LatticeBoltzmann::setGammaS (real _gamma_s)
Definition at line 202 of file LatticeBoltzmann.cpp.
References initFluctuations(), and setGamma().
Referenced by registerPython().
setGhostFluid()
void espressopp::integrator::LatticeBoltzmann::setGhostFluid (Int3D _Ni, int _l, real _value)
Definition at line 271 of file LatticeBoltzmann.cpp.
setHaloSkin()
void espressopp::integrator::LatticeBoltzmann::setHaloSkin (int _haloSkin)
Definition at line 154 of file LatticeBoltzmann.cpp.
References haloSkin.
Referenced by LatticeBoltzmann().
setIntegrator()
void espressopp::integrator::Extension::setIntegrator (shared_ptr< MDIntegrator > _integrator) protected inherited
Definition at line 49 of file Extension.cpp.
References espressopp::integrator::Extension::integrator.
Referenced by espressopp::integrator::Extension::registerPython().
setInvB()
void espressopp::integrator::LatticeBoltzmann::setInvB (int _l, real _value)
Definition at line 192 of file LatticeBoltzmann.cpp.
References inv_b.
Referenced by initLatticeModel().
setJLoc()
void espressopp::integrator::LatticeBoltzmann::setJLoc (Real3D _value)
setLBMom()
void espressopp::integrator::LatticeBoltzmann::setLBMom (Int3D _Ni, int _l, real _value)
Definition at line 274 of file LatticeBoltzmann.cpp.
Referenced by registerPython().
setLBTemp()
void espressopp::integrator::LatticeBoltzmann::setLBTemp (real _lbTemp)
Definition at line 224 of file LatticeBoltzmann.cpp.
References initFluctuations(), and lbTemp.
Referenced by registerPython().
setMyLeft()
void espressopp::integrator::LatticeBoltzmann::setMyLeft (Real3D _myLeft)
Definition at line 160 of file LatticeBoltzmann.cpp.
References myLeft.
Referenced by assignMyLattice().
setMyNeigh()
void espressopp::integrator::LatticeBoltzmann::setMyNeigh (int _dir, int _rank)
Definition at line 145 of file LatticeBoltzmann.cpp.
References myNeigh.
Referenced by findMyNeighbours().
setMyNi()
void espressopp::integrator::LatticeBoltzmann::setMyNi (Int3D _myNi)
Definition at line 157 of file LatticeBoltzmann.cpp.
References myNi.
Referenced by assignMyLattice().
setMyPos()
void espressopp::integrator::LatticeBoltzmann::setMyPos (Int3D _myPos)
Definition at line 151 of file LatticeBoltzmann.cpp.
References myPos.
Referenced by findMyNeighbours().
setNi()
void espressopp::integrator::LatticeBoltzmann::setNi (Int3D _Ni)
Definition at line 164 of file LatticeBoltzmann.cpp.
References Ni.
Referenced by assignMyLattice().
setNodeGrid()
void espressopp::integrator::LatticeBoltzmann::setNodeGrid (Int3D _nodeGrid)
Definition at line 148 of file LatticeBoltzmann.cpp.
References nodeGrid.
Referenced by registerPython().
setNSteps()
void espressopp::integrator::LatticeBoltzmann::setNSteps (int _nSteps)
Definition at line 250 of file LatticeBoltzmann.cpp.
References nSteps.
Referenced by LatticeBoltzmann(), and registerPython().
setNumDims()
void espressopp::integrator::LatticeBoltzmann::setNumDims (int _numDims)
Definition at line 175 of file LatticeBoltzmann.cpp.
References numDims.
Referenced by registerPython().
setNumVels()
void espressopp::integrator::LatticeBoltzmann::setNumVels (int _numVels)
Definition at line 179 of file LatticeBoltzmann.cpp.
References numVels.
Referenced by registerPython().
setPhi()
void espressopp::integrator::LatticeBoltzmann::setPhi (int _l, real _value)
Definition at line 230 of file LatticeBoltzmann.cpp.
References phi.
Referenced by initFluctuations().
setPops()
void espressopp::integrator::LatticeBoltzmann::setPops (Int3D _Ni, int _l, real _value)
Definition at line 266 of file LatticeBoltzmann.cpp.
Referenced by readLBConf().
setPrevDumpStep()
void espressopp::integrator::LatticeBoltzmann::setPrevDumpStep (int saveStep)
Definition at line 253 of file LatticeBoltzmann.cpp.
References saveStep.
Referenced by keepLBDump(), LatticeBoltzmann(), and saveLBConf().
setProfStep()
void espressopp::integrator::LatticeBoltzmann::setProfStep (int _profStep)
Definition at line 288 of file LatticeBoltzmann.cpp.
References profStep.
Referenced by LatticeBoltzmann(), and registerPython().
setStepNum()
void espressopp::integrator::LatticeBoltzmann::setStepNum (int _step)
Definition at line 292 of file LatticeBoltzmann.cpp.
References stepNum.
Referenced by makeLBStep(), and zeroMDCMVel().
setTau()
void espressopp::integrator::LatticeBoltzmann::setTau (real _tau)
Definition at line 171 of file LatticeBoltzmann.cpp.
References tau.
Referenced by registerPython().
setTotNPart()
void espressopp::integrator::LatticeBoltzmann::setTotNPart (int _totNPart)
Definition at line 256 of file LatticeBoltzmann.cpp.
References totNPart.
Referenced by LatticeBoltzmann().
setType()
void espressopp::integrator::Extension::setType (ExtensionType k) inline inherited
Definition at line 68 of file Extension.hpp.
Referenced by espressopp::integrator::Extension::registerPython().
setViscB()
void espressopp::integrator::LatticeBoltzmann::setViscB (real _visc_b)
Definition at line 211 of file LatticeBoltzmann.cpp.
References convLenMDtoLB(), convMassMDtoLB(), convTimeMDtoLB(), getCs2(), getNSteps(), getNumDims(), getTau(), setGamma(), and visc_b.
Referenced by registerPython().
setViscS()
void espressopp::integrator::LatticeBoltzmann::setViscS (real _visc_s)
Definition at line 217 of file LatticeBoltzmann.cpp.
References convLenMDtoLB(), convMassMDtoLB(), convTimeMDtoLB(), getCs2(), getNSteps(), getTau(), setGamma(), and visc_s.
Referenced by registerPython().
streaming()
void espressopp::integrator::LatticeBoltzmann::streaming (int _i, int _j, int _k)
Definition at line 579 of file LatticeBoltzmann.cpp.
References lbfluid.
Referenced by collideStream().
zeroMDCMVel()
void espressopp::integrator::LatticeBoltzmann::zeroMDCMVel ()
Definition at line 775 of file LatticeBoltzmann.cpp.
References copyDenMomToHalo(), doCoupling(), doRestart(), findCMVelMD(), galileanTransf(), getStepNum(), espressopp::SystemAccess::getSystem(), espressopp::integrator::Extension::integrator, readLBConf(), saveLBConf(), setCopyTimestep(), setDoRestart(), and setStepNum().
Referenced by connect().
Member Data Documentation
_befIntV
boost::signals2::connection espressopp::integrator::LatticeBoltzmann::_befIntV private
Definition at line 300 of file LatticeBoltzmann.hpp.
Referenced by connect(), and disconnect().
_recalc2
boost::signals2::connection espressopp::integrator::LatticeBoltzmann::_recalc2 private
Definition at line 301 of file LatticeBoltzmann.hpp.
Referenced by connect(), and disconnect().
a
real espressopp::integrator::LatticeBoltzmann::a private
Definition at line 251 of file LatticeBoltzmann.hpp.
Referenced by getA(), and setA().
c_i
std::vector<Real3D> espressopp::integrator::LatticeBoltzmann::c_i private
Definition at line 253 of file LatticeBoltzmann.hpp.
Referenced by getCi(), LatticeBoltzmann(), and setCi().
colstream
esutil::WallTimer espressopp::integrator::LatticeBoltzmann::colstream private
Definition at line 304 of file LatticeBoltzmann.hpp.
Referenced by collideStream(), LatticeBoltzmann(), and makeLBStep().
comm
esutil::WallTimer espressopp::integrator::LatticeBoltzmann::comm private
Definition at line 304 of file LatticeBoltzmann.hpp.
Referenced by collideStream(), LatticeBoltzmann(), and makeLBStep().
copyTimestep
real espressopp::integrator::LatticeBoltzmann::copyTimestep private
Definition at line 270 of file LatticeBoltzmann.hpp.
Referenced by getCopyTimestep(), and setCopyTimestep().
coupling
bool espressopp::integrator::LatticeBoltzmann::coupling private
Definition at line 284 of file LatticeBoltzmann.hpp.
Referenced by doCoupling(), and setDoCoupling().
cs2
real espressopp::integrator::LatticeBoltzmann::cs2 private
Definition at line 252 of file LatticeBoltzmann.hpp.
Referenced by getCs2(), and setCs2().
eqWeight
std::vector<real> espressopp::integrator::LatticeBoltzmann::eqWeight private
Definition at line 254 of file LatticeBoltzmann.hpp.
Referenced by getEqWeight(), LatticeBoltzmann(), and setEqWeight().
extForce
bool espressopp::integrator::LatticeBoltzmann::extForce private
Definition at line 275 of file LatticeBoltzmann.hpp.
Referenced by doExtForce(), and setDoExtForce().
fluct
bool espressopp::integrator::LatticeBoltzmann::fluct private
Definition at line 263 of file LatticeBoltzmann.hpp.
Referenced by doFluct(), and setDoFluct().
fOnPart
std::vector<Real3D> espressopp::integrator::LatticeBoltzmann::fOnPart private
Definition at line 288 of file LatticeBoltzmann.hpp.
Referenced by addFOnPart(), getFOnPart(), LatticeBoltzmann(), and setFOnPart().
fricCoeff
real espressopp::integrator::LatticeBoltzmann::fricCoeff private
Definition at line 287 of file LatticeBoltzmann.hpp.
Referenced by getFricCoeff(), and setFricCoeff().
gamma
std::vector<real> espressopp::integrator::LatticeBoltzmann::gamma private
Definition at line 260 of file LatticeBoltzmann.hpp.
Referenced by collideStream(), getGamma(), LatticeBoltzmann(), and setGamma().
ghostlat
lblattice* espressopp::integrator::LatticeBoltzmann::ghostlat private
Definition at line 279 of file LatticeBoltzmann.hpp.
Referenced by collideStream(), disconnect(), and initLatticeSize().
haloSkin
int espressopp::integrator::LatticeBoltzmann::haloSkin private
Definition at line 294 of file LatticeBoltzmann.hpp.
Referenced by getHaloSkin(), and setHaloSkin().
integrator
shared_ptr<MDIntegrator> espressopp::integrator::Extension::integrator protected inherited
Definition at line 72 of file Extension.hpp.
Referenced by espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), calcRandForce(), espressopp::integrator::ExtAnalyze::connect(), espressopp::integrator::Rattle::connect(), espressopp::integrator::VelocityVerletOnRadius::connect(), espressopp::integrator::BerendsenBarostatAnisotropic::connect(), espressopp::integrator::BerendsenBarostat::connect(), espressopp::integrator::FixPositions::connect(), espressopp::integrator::FreeEnergyCompensation::connect(), espressopp::integrator::Isokinetic::connect(), espressopp::integrator::ExtForce::connect(), espressopp::integrator::TDforce::connect(), espressopp::integrator::BerendsenThermostat::connect(), espressopp::integrator::Settle::connect(), espressopp::integrator::LangevinThermostatOnGroup::connect(), espressopp::integrator::Adress::connect(), espressopp::integrator::CapForce::connect(), espressopp::integrator::LangevinThermostatOnRadius::connect(), espressopp::integrator::OnTheFlyFEC::connect(), espressopp::integrator::DPDThermostat::connect(), espressopp::integrator::GeneralizedLangevinThermostat::connect(), espressopp::integrator::LangevinThermostat1D::connect(), espressopp::integrator::LangevinThermostatHybrid::connect(), espressopp::integrator::LangevinBarostat::connect(), espressopp::integrator::LangevinThermostat::connect(), espressopp::integrator::AssociationReaction::connect(), espressopp::integrator::StochasticVelocityRescaling::connect(), connect(), convTimeMDtoLB(), espressopp::integrator::LangevinThermostatOnGroup::initialize(), espressopp::integrator::LangevinThermostatOnRadius::initialize(), espressopp::integrator::LangevinThermostat::initialize(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinThermostat1D::initialize(), espressopp::integrator::BerendsenThermostat::initialize(), espressopp::integrator::LangevinThermostatHybrid::initialize(), espressopp::integrator::BerendsenBarostatAnisotropic::initialize(), espressopp::integrator::BerendsenBarostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::Adress::integrate2(), makeLBStep(), espressopp::integrator::AssociationReaction::react(), readLBConf(), saveLBConf(), espressopp::integrator::Extension::setIntegrator(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and zeroMDCMVel().
inv_b
std::vector<real> espressopp::integrator::LatticeBoltzmann::inv_b private
Definition at line 255 of file LatticeBoltzmann.hpp.
Referenced by getInvB(), LatticeBoltzmann(), and setInvB().
invCs2
real espressopp::integrator::LatticeBoltzmann::invCs2 private
Definition at line 252 of file LatticeBoltzmann.hpp.
lbfluid
lblattice* espressopp::integrator::LatticeBoltzmann::lbfluid private
Definition at line 278 of file LatticeBoltzmann.hpp.
Referenced by collideStream(), disconnect(), getPops(), initLatticeSize(), and streaming().
lbfor
lbforces* espressopp::integrator::LatticeBoltzmann::lbfor private
Definition at line 281 of file LatticeBoltzmann.hpp.
Referenced by addExtForceLoc(), disconnect(), getExtForceLoc(), initLatticeSize(), and setExtForceLoc().
lbmom
lbmoments* espressopp::integrator::LatticeBoltzmann::lbmom private
Definition at line 280 of file LatticeBoltzmann.hpp.
Referenced by calcViscForce(), disconnect(), getLBMom(), and initLatticeSize().
lbTemp
real espressopp::integrator::LatticeBoltzmann::lbTemp private
Definition at line 264 of file LatticeBoltzmann.hpp.
Referenced by getLBTemp(), and setLBTemp().
myLeft
Real3D espressopp::integrator::LatticeBoltzmann::myLeft private
Definition at line 297 of file LatticeBoltzmann.hpp.
Referenced by getMyLeft(), and setMyLeft().
myNeigh
std::vector<int> espressopp::integrator::LatticeBoltzmann::myNeigh private
Definition at line 292 of file LatticeBoltzmann.hpp.
Referenced by getMyNeigh(), LatticeBoltzmann(), and setMyNeigh().
myNi
Int3D espressopp::integrator::LatticeBoltzmann::myNi private
Definition at line 295 of file LatticeBoltzmann.hpp.
Referenced by getMyNi(), and setMyNi().
myPos
Int3D espressopp::integrator::LatticeBoltzmann::myPos private
Definition at line 293 of file LatticeBoltzmann.hpp.
Referenced by getMyPos(), and setMyPos().
Ni
Int3D espressopp::integrator::LatticeBoltzmann::Ni private
Definition at line 256 of file LatticeBoltzmann.hpp.
Referenced by getNi(), and setNi().
nodeGrid
Int3D espressopp::integrator::LatticeBoltzmann::nodeGrid private
Definition at line 296 of file LatticeBoltzmann.hpp.
Referenced by getNodeGrid(), and setNodeGrid().
nSteps
int espressopp::integrator::LatticeBoltzmann::nSteps private
Definition at line 285 of file LatticeBoltzmann.hpp.
Referenced by getNSteps(), and setNSteps().
numDims
int espressopp::integrator::LatticeBoltzmann::numDims private
Definition at line 249 of file LatticeBoltzmann.hpp.
Referenced by getNumDims(), and setNumDims().
numVels
int espressopp::integrator::LatticeBoltzmann::numVels private
Definition at line 250 of file LatticeBoltzmann.hpp.
Referenced by getNumVels(), and setNumVels().
phi
std::vector<real> espressopp::integrator::LatticeBoltzmann::phi private
Definition at line 265 of file LatticeBoltzmann.hpp.
Referenced by getPhi(), LatticeBoltzmann(), and setPhi().
profStep
int espressopp::integrator::LatticeBoltzmann::profStep private
Definition at line 307 of file LatticeBoltzmann.hpp.
Referenced by getProfStep(), and setProfStep().
restart
bool espressopp::integrator::LatticeBoltzmann::restart private
Definition at line 271 of file LatticeBoltzmann.hpp.
Referenced by doRestart(), and setDoRestart().
rng
shared_ptr< esutil::RNG > espressopp::integrator::LatticeBoltzmann::rng private
random number generator used for fluctuations
Definition at line 272 of file LatticeBoltzmann.hpp.
Referenced by calcRandForce(), and LatticeBoltzmann().
saveStep
int espressopp::integrator::LatticeBoltzmann::saveStep private
Definition at line 289 of file LatticeBoltzmann.hpp.
Referenced by getPrevDumpStep(), and setPrevDumpStep().
start
int espressopp::integrator::LatticeBoltzmann::start private
Definition at line 268 of file LatticeBoltzmann.hpp.
stepNum
int espressopp::integrator::LatticeBoltzmann::stepNum private
Definition at line 269 of file LatticeBoltzmann.hpp.
Referenced by getStepNum(), and setStepNum().
swapping
esutil::WallTimer espressopp::integrator::LatticeBoltzmann::swapping private
Definition at line 304 of file LatticeBoltzmann.hpp.
Referenced by collideStream(), LatticeBoltzmann(), and makeLBStep().
tau
real espressopp::integrator::LatticeBoltzmann::tau private
Definition at line 251 of file LatticeBoltzmann.hpp.
Referenced by getTau(), and setTau().
time_colstr
real espressopp::integrator::LatticeBoltzmann::time_colstr private
Definition at line 306 of file LatticeBoltzmann.hpp.
Referenced by collideStream(), LatticeBoltzmann(), and makeLBStep().
time_comm
real espressopp::integrator::LatticeBoltzmann::time_comm private
Definition at line 306 of file LatticeBoltzmann.hpp.
Referenced by collideStream(), LatticeBoltzmann(), and makeLBStep().
time_sw
real espressopp::integrator::LatticeBoltzmann::time_sw private
Definition at line 306 of file LatticeBoltzmann.hpp.
Referenced by collideStream(), LatticeBoltzmann(), and makeLBStep().
timeReadLBConf
esutil::WallTimer espressopp::integrator::LatticeBoltzmann::timeReadLBConf private
Definition at line 305 of file LatticeBoltzmann.hpp.
Referenced by readLBConf().
timeSaveLBConf
esutil::WallTimer espressopp::integrator::LatticeBoltzmann::timeSaveLBConf private
Definition at line 305 of file LatticeBoltzmann.hpp.
Referenced by saveLBConf().
totNPart
int espressopp::integrator::LatticeBoltzmann::totNPart private
Definition at line 286 of file LatticeBoltzmann.hpp.
Referenced by getTotNPart(), and setTotNPart().
type
ExtensionType espressopp::integrator::Extension::type inherited
Definition at line 62 of file Extension.hpp.
Referenced by espressopp::integrator::TDforce::addForce(), espressopp::integrator::Adress::Adress(), espressopp::integrator::AssociationReaction::AssociationReaction(), espressopp::integrator::BerendsenBarostat::BerendsenBarostat(), espressopp::integrator::BerendsenBarostatAnisotropic::BerendsenBarostatAnisotropic(), espressopp::integrator::BerendsenThermostat::BerendsenThermostat(), espressopp::integrator::DPDThermostat::DPDThermostat(), espressopp::integrator::ExtAnalyze::ExtAnalyze(), espressopp::integrator::FreeEnergyCompensation::FreeEnergyCompensation(), espressopp::integrator::GeneralizedLangevinThermostat::GeneralizedLangevinThermostat(), espressopp::integrator::Extension::getType(), espressopp::integrator::LangevinBarostat::LangevinBarostat(), espressopp::integrator::LangevinThermostat::LangevinThermostat(), espressopp::integrator::LangevinThermostat1D::LangevinThermostat1D(), espressopp::integrator::LangevinThermostatHybrid::LangevinThermostatHybrid(), espressopp::integrator::LangevinThermostatOnGroup::LangevinThermostatOnGroup(), espressopp::integrator::LangevinThermostatOnRadius::LangevinThermostatOnRadius(), espressopp::integrator::OnTheFlyFEC::OnTheFlyFEC(), espressopp::integrator::TDforce::registerPython(), espressopp::integrator::StochasticVelocityRescaling::StochasticVelocityRescaling(), and espressopp::integrator::TDforce::TDforce().
visc_b
real espressopp::integrator::LatticeBoltzmann::visc_b private
Definition at line 259 of file LatticeBoltzmann.hpp.
Referenced by getViscB(), and setViscB().
visc_s
real espressopp::integrator::LatticeBoltzmann::visc_s private
Definition at line 259 of file LatticeBoltzmann.hpp.
Referenced by getViscS(), and setViscS().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/integrator/LatticeBoltzmann.hpp
/home/espressopp/espressopp/src/integrator/LatticeBoltzmann.cpp