ESPResSo++: espressopp::interaction::Quartic Class Reference
espressopp::interaction::Quartic Class Reference
#include <Quartic.hpp>
Public Member Functions
Quartic ()
Quartic (real _K, real _r0, real _cutoff, real _shift)
Quartic (real _K, real _r0, real _cutoff)
void setK (real _K)
real getK () const
void setR0 (real _r0)
real getR0 () const
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &dist, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
real _computeEnergyDeriv (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
Quartic * derived_this ()
const Quartic * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
Private Attributes
real K
real r0
Detailed Description
Definition at line 36 of file Quartic.hpp.
Constructor & Destructor Documentation
Quartic() [1/3]
espressopp::interaction::Quartic::Quartic () inline
Definition at line 44 of file Quartic.hpp.
References espressopp::infinity, espressopp::interaction::PotentialTemplate< Quartic >::setCutoff(), and espressopp::interaction::PotentialTemplate< Quartic >::setShift().
Quartic() [2/3]
espressopp::interaction::Quartic::Quartic (real _K, real _r0, real _cutoff, real _shift) inline
Definition at line 49 of file Quartic.hpp.
References espressopp::interaction::PotentialTemplate< Quartic >::setCutoff(), and espressopp::interaction::PotentialTemplate< Quartic >::setShift().
Quartic() [3/3]
espressopp::interaction::Quartic::Quartic (real _K, real _r0, real _cutoff) inline
Definition at line 54 of file Quartic.hpp.
References espressopp::interaction::PotentialTemplate< Quartic >::autoShift, espressopp::interaction::PotentialTemplate< Quartic >::setAutoShift(), and espressopp::interaction::PotentialTemplate< Quartic >::setCutoff().
Member Function Documentation
_computeEnergy() [1/4]
real espressopp::interaction::PotentialTemplate< Quartic >::_computeEnergy (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 242 of file Potential.hpp.
_computeEnergy() [2/4]
real espressopp::interaction::PotentialTemplate< Quartic >::_computeEnergy (const Real3D & dist) const inline inherited
Definition at line 257 of file Potential.hpp.
_computeEnergy() [3/4]
real espressopp::interaction::PotentialTemplate< Quartic >::_computeEnergy (real dist) const inline inherited
Definition at line 264 of file Potential.hpp.
_computeEnergy() [4/4]
real espressopp::interaction::PotentialTemplate< Quartic >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 250 of file Potential.hpp.
_computeEnergyDeriv()
real espressopp::interaction::PotentialTemplate< Quartic >::_computeEnergyDeriv (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 285 of file Potential.hpp.
_computeEnergySqr()
real espressopp::interaction::PotentialTemplate< Quartic >::_computeEnergySqr (real distSqr) const inline inherited
Definition at line 271 of file Potential.hpp.
_computeEnergySqrRaw()
real espressopp::interaction::Quartic::_computeEnergySqrRaw (real distSqr) const inline
Definition at line 75 of file Quartic.hpp.
_computeForce() [1/3]
bool espressopp::interaction::PotentialTemplate< Quartic >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const inline inherited
Definition at line 313 of file Potential.hpp.
_computeForce() [2/3]
bool espressopp::interaction::PotentialTemplate< Quartic >::_computeForce (Real3D & force, const Real3D & dist) const inline inherited
Definition at line 328 of file Potential.hpp.
_computeForce() [3/3]
bool espressopp::interaction::PotentialTemplate< Quartic >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 321 of file Potential.hpp.
_computeForceRaw()
bool espressopp::interaction::Quartic::_computeForceRaw (Real3D & force, const Real3D & dist, real distSqr) const inline
Definition at line 80 of file Quartic.hpp.
computeEnergy() [1/3]
real espressopp::interaction::PotentialTemplate< Quartic >::computeEnergy (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 213 of file Potential.hpp.
computeEnergy() [2/3]
real espressopp::interaction::PotentialTemplate< Quartic >::computeEnergy (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 221 of file Potential.hpp.
computeEnergy() [3/3]
real espressopp::interaction::PotentialTemplate< Quartic >::computeEnergy (real dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 228 of file Potential.hpp.
computeEnergySqr()
real espressopp::interaction::PotentialTemplate< Quartic >::computeEnergySqr (real distsqr) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 235 of file Potential.hpp.
computeForce() [1/2]
Real3D espressopp::interaction::PotentialTemplate< Quartic >::computeForce (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 295 of file Potential.hpp.
computeForce() [2/2]
Real3D espressopp::interaction::PotentialTemplate< Quartic >::computeForce (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 303 of file Potential.hpp.
derived_this() [1/2]
Quartic * espressopp::interaction::PotentialTemplate< Quartic >::derived_this () inline protected inherited
Definition at line 123 of file Potential.hpp.
derived_this() [2/2]
const Quartic * espressopp::interaction::PotentialTemplate< Quartic >::derived_this () const inline protected inherited
Definition at line 127 of file Potential.hpp.
getCutoff()
real espressopp::interaction::PotentialTemplate< Quartic >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 171 of file Potential.hpp.
getK()
real espressopp::interaction::Quartic::getK () const inline
Definition at line 66 of file Quartic.hpp.
References K.
Referenced by registerPython().
getR0()
real espressopp::interaction::Quartic::getR0 () const inline
Definition at line 73 of file Quartic.hpp.
References r0.
Referenced by registerPython().
getShift()
real espressopp::interaction::PotentialTemplate< Quartic >::getShift () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 186 of file Potential.hpp.
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
Referenced by espressopp::interaction::Potential::~Potential().
registerPython()
void espressopp::interaction::Quartic::registerPython () static
Definition at line 33 of file Quartic.cpp.
References getK(), getR0(), setK(), and setR0().
Referenced by espressopp::interaction::registerPython().
setAutoShift()
real espressopp::interaction::PotentialTemplate< Quartic >::setAutoShift () inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 192 of file Potential.hpp.
Referenced by Quartic().
setCutoff()
void espressopp::interaction::PotentialTemplate< Quartic >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 162 of file Potential.hpp.
Referenced by Quartic().
setK()
void espressopp::interaction::Quartic::setK (real _K) inline
Definition at line 61 of file Quartic.hpp.
References espressopp::interaction::PotentialTemplate< Quartic >::updateAutoShift().
Referenced by registerPython().
setR0()
void espressopp::interaction::Quartic::setR0 (real _r0) inline
Definition at line 68 of file Quartic.hpp.
References espressopp::interaction::PotentialTemplate< Quartic >::updateAutoShift().
Referenced by registerPython().
setShift()
void espressopp::interaction::PotentialTemplate< Quartic >::setShift (real _shift) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 177 of file Potential.hpp.
Referenced by Quartic().
updateAutoShift()
void espressopp::interaction::PotentialTemplate< Quartic >::updateAutoShift () inline inherited
Definition at line 205 of file Potential.hpp.
Referenced by setK(), and setR0().
Member Data Documentation
autoShift
bool espressopp::interaction::PotentialTemplate< Quartic >::autoShift protected inherited
Definition at line 121 of file Potential.hpp.
Referenced by Quartic().
cutoff
real espressopp::interaction::PotentialTemplate< Quartic >::cutoff protected inherited
Definition at line 118 of file Potential.hpp.
cutoffSqr
real espressopp::interaction::PotentialTemplate< Quartic >::cutoffSqr protected inherited
Definition at line 119 of file Potential.hpp.
K
real espressopp::interaction::Quartic::K private
Definition at line 38 of file Quartic.hpp.
Referenced by getK().
r0
real espressopp::interaction::Quartic::r0 private
Definition at line 39 of file Quartic.hpp.
Referenced by getR0().
shift
real espressopp::interaction::PotentialTemplate< Quartic >::shift protected inherited
Definition at line 120 of file Potential.hpp.
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/Quartic.hpp
/home/espressopp/espressopp/src/interaction/Quartic.cpp