ESPResSo++: espressopp::Real3D Class Reference
espressopp::Real3D Class Reference
#include <Real3D.hpp>
Public Types
typedef real * iterator
Public Member Functions
Real3D ()
Real3D (real v)
Real3D (real x, real y, real z)
Real3D (const Real3D &v)
Real3D (const real v[3])
Real3D & operator= (const Real3D &v)
real & operator[] (int i)
const real & operator[] (int i) const
real & at (int i)
const real & at (int i) const
void setItem (int i, real v)
real getItem (int i) const
Real3D & operator+= (const Real3D &v)
Real3D & operator-= (const Real3D &v)
Real3D & operator*= (const real v)
Real3D & operator/= (const real v)
bool operator== (const Real3D &v) const
bool operator!= (const Real3D &v) const
Real3D operator+ (const Real3D &v) const
Real3D operator- (const Real3D &v) const
Real3D operator* (real v) const
Real3D operator/ (real v) const
Real3D cross (const Real3D &v) const
Cross product of two Real3D.
real operator* (const Real3D &v) const
real sqr () const
real abs () const
iterator begin ()
iterator end ()
const real * get () const
real * get ()
Static Public Member Functions
static void registerPython ()
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
real data [3]
Friends
class boost::serialization::access
Detailed Description
Definition at line 33 of file Real3D.hpp.
Member Typedef Documentation
iterator
typedef real* espressopp::Real3D::iterator
Definition at line 45 of file Real3D.hpp.
Constructor & Destructor Documentation
Real3D() [1/5]
espressopp::Real3D::Real3D () inline
Definition at line 110 of file Real3D.hpp.
Referenced by cross(), operator*(), espressopp::operator*(), operator+(), operator-(), and operator/().
Real3D() [2/5]
espressopp::Real3D::Real3D (real v) inline
Definition at line 112 of file Real3D.hpp.
References data.
Real3D() [3/5]
espressopp::Real3D::Real3D (real x, real y, real z) inline
Definition at line 115 of file Real3D.hpp.
References data.
Real3D() [4/5]
espressopp::Real3D::Real3D (const Real3D & v) inline
Definition at line 121 of file Real3D.hpp.
References data.
Real3D() [5/5]
espressopp::Real3D::Real3D (const real v[3]) inline
Definition at line 126 of file Real3D.hpp.
References data.
Member Function Documentation
abs()
real espressopp::Real3D::abs () const inline
Definition at line 217 of file Real3D.hpp.
References sqr().
Referenced by espressopp::interaction::CoulombTruncated::_computeEnergy(), espressopp::interaction::GravityTruncated::_computeEnergy(), espressopp::interaction::CoulombRSpace::_computeEnergy(), espressopp::interaction::StillingerWeberTripleTerm::_computeEnergy(), espressopp::interaction::TersoffTripleTerm::_computeEnergy(), espressopp::interaction::GravityTruncated::_computeForce(), espressopp::interaction::CoulombTruncated::_computeForce(), espressopp::interaction::CoulombRSpace::_computeForce(), espressopp::interaction::StillingerWeberTripleTerm::_computeForceRaw(), espressopp::interaction::TersoffTripleTerm::_computeForceRaw(), espressopp::FixedPairDistList::add(), espressopp::FixedTripleAngleList::add(), espressopp::analysis::SubregionTracking::compute_int(), espressopp::analysis::NPartSubregion::compute_int(), espressopp::analysis::RDFatomistic::computeArray(), espressopp::analysis::RadialDistrF::computeArray(), espressopp::analysis::StaticStructF::computeArray(), espressopp::analysis::RDFatomistic::computeArrayPathIntegral(), espressopp::analysis::StaticStructF::computeArraySingleChain(), registerPython(), espressopp::integrator::Settle::settlep(), and espressopp::analysis::OrderParameter::SphHarm().
at() [1/2]
real & espressopp::Real3D::at (int i) inline
Definition at line 144 of file Real3D.hpp.
Referenced by espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialX(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialX(), getItem(), and setItem().
at() [2/2]
const real & espressopp::Real3D::at (int i) const inline
Definition at line 150 of file Real3D.hpp.
begin()
Real3D::iterator espressopp::Real3D::begin () inline
Definition at line 220 of file Real3D.hpp.
References data.
Referenced by espressopp::analysis::AdressDensity::computeArray().
cross()
Real3D espressopp::Real3D::cross (const Real3D & v) const inline
Cross product of two Real3D.
Definition at line 208 of file Real3D.hpp.
References data, and Real3D().
Referenced by espressopp::interaction::DihedralPotentialTemplate< OPLS >::_computeEnergy(), espressopp::interaction::DihedralUniquePotentialTemplate< DihedralHarmonicUniqueCos >::_computeEnergy(), espressopp::interaction::DihedralHarmonicUniqueCos::_computeForceRaw(), espressopp::interaction::DihedralRB::_computeForceRaw(), espressopp::interaction::OPLS::_computeForceRaw(), espressopp::interaction::TabulatedDihedral::_computeForceRaw(), espressopp::interaction::DihedralHarmonicCos::_computeForceRaw(), espressopp::interaction::DihedralHarmonic::_computeForceRaw(), espressopp::interaction::DihedralHarmonicNCos::_computeForceRaw(), espressopp::FixedQuadrupleAngleList::add(), espressopp::Quaternion::operator*(), registerPython(), and espressopp::integrator::Settle::settlep().
end()
Real3D::iterator espressopp::Real3D::end () inline
Definition at line 221 of file Real3D.hpp.
References data.
get() [1/2]
const real* espressopp::Real3D::get () const inline
Definition at line 93 of file Real3D.hpp.
References data.
get() [2/2]
real* espressopp::Real3D::get () inline
Definition at line 94 of file Real3D.hpp.
References data, operator*(), espressopp::operator<<(), and registerPython().
getItem()
real espressopp::Real3D::getItem (int i) const inline
Definition at line 159 of file Real3D.hpp.
References at().
Referenced by espressopp::integrator::LBInitPopUniform::createDenVel(), espressopp::integrator::LBInitPopWave::createDenVel(), espressopp::Quaternion::getImagItem(), espressopp::integrator::LBInitConstForce::printForce(), espressopp::analysis::MeanSquareDispl::printReal3D(), and registerPython().
operator!=()
bool espressopp::Real3D::operator!= (const Real3D & v) const inline
Definition at line 187 of file Real3D.hpp.
operator*() [1/2]
Real3D espressopp::Real3D::operator* (real v) const inline
Definition at line 197 of file Real3D.hpp.
References Real3D().
Referenced by get().
operator*() [2/2]
real espressopp::Real3D::operator* (const Real3D & v) const inline
Definition at line 204 of file Real3D.hpp.
References data.
operator*=()
Real3D & espressopp::Real3D::operator*= (const real v) inline
Definition at line 169 of file Real3D.hpp.
References data.
operator+()
Real3D espressopp::Real3D::operator+ (const Real3D & v) const inline
Definition at line 191 of file Real3D.hpp.
References Real3D().
operator+=()
Real3D & espressopp::Real3D::operator+= (const Real3D & v) inline
Definition at line 163 of file Real3D.hpp.
References data.
operator-()
Real3D espressopp::Real3D::operator- (const Real3D & v) const inline
Definition at line 194 of file Real3D.hpp.
References Real3D().
operator-=()
Real3D & espressopp::Real3D::operator-= (const Real3D & v) inline
Definition at line 166 of file Real3D.hpp.
References data.
operator/()
Real3D espressopp::Real3D::operator/ (real v) const inline
Definition at line 200 of file Real3D.hpp.
References Real3D().
operator/=()
Real3D & espressopp::Real3D::operator/= (const real v) inline
Definition at line 172 of file Real3D.hpp.
References data.
operator=()
Real3D & espressopp::Real3D::operator= (const Real3D & v) inline
Definition at line 131 of file Real3D.hpp.
References data.
operator==()
bool espressopp::Real3D::operator== (const Real3D & v) const inline
Definition at line 180 of file Real3D.hpp.
References data.
operator[]() [1/2]
real & espressopp::Real3D::operator[] (int i) inline
Definition at line 138 of file Real3D.hpp.
References data.
operator[]() [2/2]
const real & espressopp::Real3D::operator[] (int i) const inline
Definition at line 141 of file Real3D.hpp.
References data.
registerPython()
void espressopp::Real3D::registerPython () static
Definition at line 37 of file Real3D.cpp.
References abs(), cross(), getItem(), setItem(), and sqr().
Referenced by get(), espressopp::real3D_pickle_suite::getinitargs(), and espressopp::registerPython().
serialize()
template<class Archive > void espressopp::Real3D::serialize (Archive & ar, const unsigned int version) inline private
Definition at line 39 of file Real3D.hpp.
setItem()
void espressopp::Real3D::setItem (int i, real v) inline
Definition at line 156 of file Real3D.hpp.
References at().
Referenced by registerPython(), and espressopp::Quaternion::setImagItem().
sqr()
real espressopp::Real3D::sqr () const inline
Definition at line 214 of file Real3D.hpp.
References data.
Referenced by espressopp::interaction::ConstrainCOM::_computeEnergy(), espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueCosineSquared >::_computeEnergy(), espressopp::interaction::DihedralPotentialTemplate< OPLS >::_computeEnergy(), espressopp::interaction::DihedralUniquePotentialTemplate< DihedralHarmonicUniqueCos >::_computeEnergy(), espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::_computeEnergy(), espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::_computeEnergy(), espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::_computeEnergy(), espressopp::interaction::ReactionFieldGeneralized::_computeEnergy(), espressopp::interaction::LennardJonesSoftcoreTI::_computeEnergy(), espressopp::interaction::ReactionFieldGeneralizedTI::_computeEnergy(), espressopp::interaction::LennardJonesAutoBonds::_computeEnergy(), espressopp::interaction::ReactionFieldGeneralizedTI::_computeEnergyDeriv(), espressopp::interaction::LennardJonesSoftcoreTI::_computeEnergyDeriv(), espressopp::interaction::HarmonicTrap::_computeEnergyRaw(), espressopp::interaction::GravityTruncated::_computeForce(), espressopp::interaction::CoulombTruncated::_computeForce(), espressopp::interaction::CoulombRSpace::_computeForce(), espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::_computeForce(), espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::_computeForce(), espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::_computeForce(), espressopp::interaction::ReactionFieldGeneralizedTI::_computeForce(), espressopp::interaction::ReactionFieldGeneralized::_computeForce(), espressopp::interaction::LennardJonesSoftcoreTI::_computeForce(), espressopp::interaction::LennardJonesAutoBonds::_computeForce(), espressopp::interaction::AngularUniqueCosineSquared::_computeForceRaw(), espressopp::interaction::AngularUniqueHarmonic::_computeForceRaw(), espressopp::interaction::DihedralHarmonicUniqueCos::_computeForceRaw(), espressopp::interaction::DihedralRB::_computeForceRaw(), espressopp::interaction::DihedralHarmonicCos::_computeForceRaw(), espressopp::interaction::DihedralHarmonic::_computeForceRaw(), espressopp::interaction::DihedralHarmonicNCos::_computeForceRaw(), abs(), espressopp::FixedQuadrupleAngleList::add(), espressopp::integrator::LBInitPeriodicForce::addForce(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::addForces(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::addForces(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::addForces(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::addForces(), espressopp::interaction::CoulombKSpaceP3M::aliasing_sum(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::interaction::CoulombKSpaceP3M::calc_opt_influence_function(), espressopp::integrator::PIAdressIntegrator::calcForcesF(), espressopp::VerletList::checkPair(), espressopp::VerletListAdress::checkPair(), espressopp::VerletListTriple::checkTriple(), espressopp::analysis::MeanSquareDispl::compute(), espressopp::analysis::MeanSquareInternalDist::compute(), espressopp::analysis::AdressDensity::computeArray(), espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueCosineSquared >::computeEnergy(), espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::computeEnergy(), espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::computeEnergy(), espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::computeEnergy(), espressopp::interaction::VerletListAdressCGInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListAdressATATInteractionTemplate< _Potential1, _Potential2 >::computeEnergy(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeEnergy(), espressopp::interaction::VerletListAdressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeEnergy(), espressopp::interaction::LennardJonesAutoBonds::computeEnergy(), espressopp::analysis::MeanSquareDispl::computeG3(), espressopp::integrator::PIAdressIntegrator::computeKineticEnergy(), espressopp::integrator::PIAdressIntegrator::computeMomentumDrift(), espressopp::integrator::PIAdressIntegrator::computePositionDrift(), espressopp::analysis::OrderParameter::computeRaw(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::integrator::PIAdressIntegrator::computeRingEnergy(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::analysis::NeighborFluctuation::computeValues(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialX(), espressopp::integrator::DPDThermostat::frictionThermoDPD(), espressopp::integrator::DPDThermostat::frictionThermoTDPD(), espressopp::integrator::PIAdressIntegrator::initializeSetup(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::PIAdressIntegrator::integrateModePos(), espressopp::integrator::PIAdressIntegrator::integrateV2(), espressopp::integrator::AssociationReaction::reactPair(), espressopp::VerletListAdress::rebuild(), registerPython(), espressopp::integrator::LBSite::relaxMoments(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::LBInitPeriodicForce::setForce(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::Settle::settlev(), and espressopp::integrator::PIAdressIntegrator::setWeights().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Definition at line 37 of file Real3D.hpp.
Member Data Documentation
data
real espressopp::Real3D::data[3] private
Definition at line 34 of file Real3D.hpp.
Referenced by begin(), cross(), end(), get(), operator*(), operator*=(), operator+=(), operator-=(), operator/=(), operator=(), operator==(), operator[](), Real3D(), and sqr().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/Real3D.hpp
/home/espressopp/espressopp/src/Real3D.cpp