ESPResSo++: espressopp::integrator::MinimizeEnergy Class Reference
espressopp::integrator::MinimizeEnergy Class Reference
#include <MinimizeEnergy.hpp>
Public Member Functions
MinimizeEnergy (shared_ptr< class espressopp::System > system, real gamma, real ftol, real max_displacement, bool variable_step_flag)
virtual ~MinimizeEnergy ()
bool run (int max_steps, bool verbose)
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
Register this class so it can be used from Python.
Private Member Functions
void steepestDescentStep ()
void updateForces ()
real getFMax ()
real getDpMax ()
Static Private Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Private Attributes
real gamma_
real max_displacement_
real ftol_sqr_
real f_max_sqr_
real dp_sqr_max_
real dp_MAX
bool variable_step_flag_
true implies that gamma is adjusted to the force strength.
bool resort_flag_
true implies need for resort of particles
longint nstep_
Detailed Description
Definition at line 41 of file MinimizeEnergy.hpp.
Constructor & Destructor Documentation
espressopp::integrator::MinimizeEnergy::MinimizeEnergy (shared_ptr< class espressopp::System > system, real gamma, real ftol, real max_displacement, bool variable_step_flag)
Definition at line 35 of file MinimizeEnergy.cpp.
References dp_MAX, LOG4ESPP_INFO, nstep_, and resort_flag_.
espressopp::integrator::MinimizeEnergy::~MinimizeEnergy () virtual
Definition at line 49 of file MinimizeEnergy.cpp.
References LOG4ESPP_INFO.
Member Function Documentation
real espressopp::integrator::MinimizeEnergy::getDpMax () inline private
Definition at line 63 of file MinimizeEnergy.hpp.
References dp_sqr_max_.
Referenced by registerPython().
real espressopp::integrator::MinimizeEnergy::getFMax () inline private
Definition at line 59 of file MinimizeEnergy.hpp.
References f_max_sqr_.
Referenced by registerPython().
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::io::DumpXYZ::DumpXYZ(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::LatticeBoltzmann::initGammas(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readCouplForces(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::VerletListTriple::registerPython(), espressopp::VerletList::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveCouplForces(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::analysis::LBOutputScreen::writeOutput(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readCouplForces(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::LatticeBoltzmann::restoreLBForces(), run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::LatticeBoltzmann::saveCouplForces(), espressopp::integrator::Rattle::saveOldPos(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), steepestDescentStep(), espressopp::integrator::LangevinThermostatOnGroup::thermalize(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
static espressopp::integrator::MinimizeEnergy::LOG4ESPP_DECL_LOGGER (theLogger) static private
void espressopp::integrator::MinimizeEnergy::registerPython () static
Register this class so it can be used from Python.
Definition at line 203 of file MinimizeEnergy.cpp.
References getDpMax(), getFMax(), nstep_, and run().
Referenced by espressopp::integrator::registerPython().
bool espressopp::integrator::MinimizeEnergy::run (int max_steps, bool verbose)
Definition at line 53 of file MinimizeEnergy.cpp.
References espressopp::storage::Storage::decompose(), dp_MAX, dp_sqr_max_, f_max_sqr_, ftol_sqr_, espressopp::System::getSkin(), espressopp::SystemAccess::getSystemRef(), LOG4ESPP_DEBUG, LOG4ESPP_INFO, max_displacement_, nstep_, resort_flag_, steepestDescentStep(), espressopp::System::storage, and updateForces().
Referenced by registerPython().
void espressopp::integrator::MinimizeEnergy::steepestDescentStep () private
Definition at line 161 of file MinimizeEnergy.cpp.
References espressopp::System::comm, dp_sqr_max_, f_max_sqr_, gamma_, espressopp::SystemAccess::getSystemRef(), espressopp::iterator::CellListIterator::isDone(), LOG4ESPP_INFO, max_displacement_, espressopp::System::storage, and variable_step_flag_.
Referenced by run().
void espressopp::integrator::MinimizeEnergy::updateForces () private
Definition at line 123 of file MinimizeEnergy.cpp.
References espressopp::System::comm, f_max_sqr_, espressopp::SystemAccess::getSystemRef(), espressopp::iterator::CellListIterator::isDone(), LOG4ESPP_DEBUG, LOG4ESPP_INFO, espressopp::System::shortRangeInteractions, and espressopp::System::storage.
Referenced by run().
Member Data Documentation
real espressopp::integrator::MinimizeEnergy::dp_MAX private
Definition at line 74 of file MinimizeEnergy.hpp.
Referenced by MinimizeEnergy(), and run().
real espressopp::integrator::MinimizeEnergy::dp_sqr_max_ private
Definition at line 73 of file MinimizeEnergy.hpp.
Referenced by getDpMax(), run(), and steepestDescentStep().
real espressopp::integrator::MinimizeEnergy::f_max_sqr_ private
Definition at line 72 of file MinimizeEnergy.hpp.
Referenced by getFMax(), run(), steepestDescentStep(), and updateForces().
real espressopp::integrator::MinimizeEnergy::ftol_sqr_ private
Definition at line 70 of file MinimizeEnergy.hpp.
Referenced by run().
real espressopp::integrator::MinimizeEnergy::gamma_ private
Definition at line 68 of file MinimizeEnergy.hpp.
Referenced by steepestDescentStep().
real espressopp::integrator::MinimizeEnergy::max_displacement_ private
Definition at line 69 of file MinimizeEnergy.hpp.
Referenced by run(), and steepestDescentStep().
longint espressopp::integrator::MinimizeEnergy::nstep_ private
Definition at line 80 of file MinimizeEnergy.hpp.
Referenced by MinimizeEnergy(), registerPython(), and run().
bool espressopp::integrator::MinimizeEnergy::resort_flag_ private
true implies need for resort of particles
Definition at line 78 of file MinimizeEnergy.hpp.
Referenced by MinimizeEnergy(), and run().
bool espressopp::integrator::MinimizeEnergy::variable_step_flag_ private
true implies that gamma is adjusted to the force strength.
Definition at line 76 of file MinimizeEnergy.hpp.
Referenced by steepestDescentStep().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/integrator/MinimizeEnergy.hpp
/home/travis/build/espressopp/espressopp/src/integrator/MinimizeEnergy.cpp