ESPResSo++: espressopp::interaction::LJcos Class Reference
espressopp::interaction::LJcos Class Reference
This class provides methods to compute forces and energies of the modified Lennard Jones potential (WCA) combined with the cos-contribution that smoothly reaches zero.
#include <LJcos.hpp>
Public Member Functions
LJcos ()
LJcos (real _phi)
virtual ~LJcos ()
void setEpsilon (real _epsilon)
real getEpsilon ()
void preset ()
void setPhi (real _phi)
real getPhi () const
void setSigma (real _sigma)
real getSigma () const
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &dist, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)
virtual shared_ptr< FixedPairList > getColVarBondList () const
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &fpl)
virtual shared_ptr< FixedTripleList > getColVarAngleList () const
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fpl)
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const
virtual void setColVar (const RealND &cv)
virtual void setColVar (const Real3D &dist, const bc::BC &bc)
virtual RealND getColVar () const
virtual void computeColVarWeights (const Real3D &dist, const bc::BC &bc)
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
real _computeEnergyDeriv (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
LJcos * derived_this ()
const LJcos * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
shared_ptr< FixedPairList > colVarBondList
shared_ptr< FixedTripleList > colVarAngleList
shared_ptr< FixedQuadrupleList > colVarDihedList
RealND colVar
Private Attributes
real phi
real epsilon
real sigma
real r_min
real sqr_r_min
real alpha
real beta
real gamma
real one_phi
real half_phi
real alpha_phi
real gamma_phi
real sqr_cutoff
real ff1
real ff2
real auxCoef
Detailed Description
This class provides methods to compute forces and energies of the modified Lennard Jones potential (WCA) combined with the cos-contribution that smoothly reaches zero.
It has cutoff 1.5 LJ units. There are two main application possibilities:
Controlling the depth of the resulted potential mimic solvents of various qualities;
With some modification cos->cos^2 model biomembranes.
The approach 1. can be followes in detail in M. Steinhauser, JCP, 2005 (Eq. 8) The approach 2. is the paper of Markus Deserno in Nature from 2007
Definition at line 44 of file LJcos.hpp.
Constructor & Destructor Documentation
LJcos() [1/2]
espressopp::interaction::LJcos::LJcos () inline
Definition at line 49 of file LJcos.hpp.
References espressopp::interaction::PotentialTemplate< LJcos >::autoShift, auxCoef, preset(), espressopp::interaction::PotentialTemplate< LJcos >::setCutoff(), setEpsilon(), espressopp::interaction::PotentialTemplate< LJcos >::setShift(), and setSigma().
LJcos() [2/2]
espressopp::interaction::LJcos::LJcos (real _phi) inline
Definition at line 60 of file LJcos.hpp.
References espressopp::interaction::PotentialTemplate< LJcos >::autoShift, auxCoef, preset(), espressopp::interaction::PotentialTemplate< LJcos >::setCutoff(), setEpsilon(), espressopp::interaction::PotentialTemplate< LJcos >::setShift(), and setSigma().
~LJcos()
virtual espressopp::interaction::LJcos::~LJcos () inline virtual
Definition at line 70 of file LJcos.hpp.
Member Function Documentation
_computeEnergy() [1/4]
real espressopp::interaction::PotentialTemplate< LJcos >::_computeEnergy (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 352 of file Potential.hpp.
_computeEnergy() [2/4]
real espressopp::interaction::PotentialTemplate< LJcos >::_computeEnergy (const Real3D & dist) const inline inherited
Definition at line 367 of file Potential.hpp.
_computeEnergy() [3/4]
real espressopp::interaction::PotentialTemplate< LJcos >::_computeEnergy (real dist) const inline inherited
Definition at line 374 of file Potential.hpp.
_computeEnergy() [4/4]
real espressopp::interaction::PotentialTemplate< LJcos >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 360 of file Potential.hpp.
_computeEnergyDeriv()
real espressopp::interaction::PotentialTemplate< LJcos >::_computeEnergyDeriv (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 395 of file Potential.hpp.
_computeEnergySqr()
real espressopp::interaction::PotentialTemplate< LJcos >::_computeEnergySqr (real distSqr) const inline inherited
Definition at line 381 of file Potential.hpp.
_computeEnergySqrRaw()
real espressopp::interaction::LJcos::_computeEnergySqrRaw (real distSqr) const inline
Definition at line 112 of file LJcos.hpp.
References alpha, auxCoef, beta, epsilon, gamma_phi, half_phi, one_phi, sigma, and sqr_r_min.
_computeForce() [1/3]
bool espressopp::interaction::PotentialTemplate< LJcos >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const inline inherited
Definition at line 423 of file Potential.hpp.
_computeForce() [2/3]
bool espressopp::interaction::PotentialTemplate< LJcos >::_computeForce (Real3D & force, const Real3D & dist) const inline inherited
Definition at line 438 of file Potential.hpp.
_computeForce() [3/3]
bool espressopp::interaction::PotentialTemplate< LJcos >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 431 of file Potential.hpp.
_computeForceRaw()
bool espressopp::interaction::LJcos::_computeForceRaw (Real3D & force, const Real3D & dist, real distSqr) const inline
Definition at line 126 of file LJcos.hpp.
References alpha, alpha_phi, auxCoef, beta, ff1, ff2, and sqr_r_min.
computeColVarWeights()
void espressopp::interaction::PotentialTemplate< LJcos >::computeColVarWeights (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 315 of file Potential.hpp.
computeEnergy() [1/3]
real espressopp::interaction::PotentialTemplate< LJcos >::computeEnergy (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 323 of file Potential.hpp.
computeEnergy() [2/3]
real espressopp::interaction::PotentialTemplate< LJcos >::computeEnergy (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 331 of file Potential.hpp.
computeEnergy() [3/3]
real espressopp::interaction::PotentialTemplate< LJcos >::computeEnergy (real dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 338 of file Potential.hpp.
computeEnergySqr()
real espressopp::interaction::PotentialTemplate< LJcos >::computeEnergySqr (real distsqr) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 345 of file Potential.hpp.
computeForce() [1/2]
Real3D espressopp::interaction::PotentialTemplate< LJcos >::computeForce (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 405 of file Potential.hpp.
computeForce() [2/2]
Real3D espressopp::interaction::PotentialTemplate< LJcos >::computeForce (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 413 of file Potential.hpp.
derived_this() [1/2]
LJcos * espressopp::interaction::PotentialTemplate< LJcos >::derived_this () inline protected inherited
Definition at line 161 of file Potential.hpp.
derived_this() [2/2]
const LJcos * espressopp::interaction::PotentialTemplate< LJcos >::derived_this () const inline protected inherited
Definition at line 165 of file Potential.hpp.
getColVar()
RealND espressopp::interaction::PotentialTemplate< LJcos >::getColVar () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 309 of file Potential.hpp.
getColVarAngleList()
shared_ptr< FixedTripleList > espressopp::interaction::PotentialTemplate< LJcos >::getColVarAngleList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 273 of file Potential.hpp.
getColVarBondList()
shared_ptr< FixedPairList > espressopp::interaction::PotentialTemplate< LJcos >::getColVarBondList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 259 of file Potential.hpp.
getColVarDihedList()
shared_ptr< FixedQuadrupleList > espressopp::interaction::PotentialTemplate< LJcos >::getColVarDihedList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 287 of file Potential.hpp.
getCutoff()
real espressopp::interaction::PotentialTemplate< LJcos >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 210 of file Potential.hpp.
Referenced by preset().
getEpsilon()
real espressopp::interaction::LJcos::getEpsilon () inline
Definition at line 76 of file LJcos.hpp.
References epsilon.
getPhi()
real espressopp::interaction::LJcos::getPhi () const inline
Definition at line 102 of file LJcos.hpp.
References phi.
Referenced by espressopp::interaction::LJcos_pickle::getinitargs(), and registerPython().
getShift()
real espressopp::interaction::PotentialTemplate< LJcos >::getShift () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 225 of file Potential.hpp.
getSigma()
real espressopp::interaction::LJcos::getSigma () const inline
Definition at line 110 of file LJcos.hpp.
References sigma.
Referenced by espressopp::interaction::LJcos_pickle::getinitargs(), and registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
Referenced by espressopp::interaction::Potential::~Potential().
preset()
void espressopp::interaction::LJcos::preset () inline
Definition at line 78 of file LJcos.hpp.
References alpha, alpha_phi, beta, epsilon, ff1, ff2, gamma, gamma_phi, espressopp::interaction::PotentialTemplate< LJcos >::getCutoff(), half_phi, M_PIl, one_phi, phi, r_min, sigma, sqr_cutoff, and sqr_r_min.
Referenced by LJcos(), setPhi(), and setSigma().
registerPython()
void espressopp::interaction::LJcos::registerPython () static
Definition at line 47 of file LJcos.cpp.
References getPhi(), getSigma(), setPhi(), and setSigma().
Referenced by espressopp::interaction::registerPython().
setAutoShift()
real espressopp::interaction::PotentialTemplate< LJcos >::setAutoShift () inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 231 of file Potential.hpp.
setColVar() [1/2]
void espressopp::interaction::PotentialTemplate< LJcos >::setColVar (const RealND & cv) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 294 of file Potential.hpp.
setColVar() [2/2]
void espressopp::interaction::PotentialTemplate< LJcos >::setColVar (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 301 of file Potential.hpp.
setColVarAngleList()
void espressopp::interaction::PotentialTemplate< LJcos >::setColVarAngleList (const shared_ptr< FixedTripleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 266 of file Potential.hpp.
setColVarBondList()
void espressopp::interaction::PotentialTemplate< LJcos >::setColVarBondList (const shared_ptr< FixedPairList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 252 of file Potential.hpp.
setColVarDihedList()
void espressopp::interaction::PotentialTemplate< LJcos >::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 280 of file Potential.hpp.
setCutoff()
void espressopp::interaction::PotentialTemplate< LJcos >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 201 of file Potential.hpp.
Referenced by LJcos().
setEpsilon()
void espressopp::interaction::LJcos::setEpsilon (real _epsilon) inline
Definition at line 72 of file LJcos.hpp.
References epsilon.
Referenced by LJcos().
setPhi()
void espressopp::interaction::LJcos::setPhi (real _phi) inline
Definition at line 98 of file LJcos.hpp.
References phi, and preset().
Referenced by registerPython().
setShift()
void espressopp::interaction::PotentialTemplate< LJcos >::setShift (real _shift) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 216 of file Potential.hpp.
Referenced by LJcos().
setSigma()
void espressopp::interaction::LJcos::setSigma (real _sigma) inline
Definition at line 105 of file LJcos.hpp.
References LOG4ESPP_INFO, preset(), and sigma.
Referenced by LJcos(), and registerPython().
updateAutoShift()
void espressopp::interaction::PotentialTemplate< LJcos >::updateAutoShift () inline inherited
Definition at line 244 of file Potential.hpp.
Member Data Documentation
alpha
real espressopp::interaction::LJcos::alpha private
Definition at line 148 of file LJcos.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), and preset().
alpha_phi
real espressopp::interaction::LJcos::alpha_phi private
Definition at line 149 of file LJcos.hpp.
Referenced by _computeForceRaw(), and preset().
autoShift
bool espressopp::interaction::PotentialTemplate< LJcos >::autoShift protected inherited
Definition at line 151 of file Potential.hpp.
Referenced by LJcos().
auxCoef
real espressopp::interaction::LJcos::auxCoef private
Definition at line 153 of file LJcos.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), and LJcos().
beta
real espressopp::interaction::LJcos::beta private
Definition at line 148 of file LJcos.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), and preset().
colVar
RealND espressopp::interaction::PotentialTemplate< LJcos >::colVar protected inherited
Definition at line 159 of file Potential.hpp.
colVarAngleList
shared_ptr<FixedTripleList> espressopp::interaction::PotentialTemplate< LJcos >::colVarAngleList protected inherited
Definition at line 155 of file Potential.hpp.
colVarBondList
shared_ptr<FixedPairList> espressopp::interaction::PotentialTemplate< LJcos >::colVarBondList protected inherited
Definition at line 153 of file Potential.hpp.
colVarDihedList
shared_ptr<FixedQuadrupleList> espressopp::interaction::PotentialTemplate< LJcos >::colVarDihedList protected inherited
Definition at line 157 of file Potential.hpp.
cutoff
real espressopp::interaction::PotentialTemplate< LJcos >::cutoff protected inherited
Definition at line 148 of file Potential.hpp.
cutoffSqr
real espressopp::interaction::PotentialTemplate< LJcos >::cutoffSqr protected inherited
Definition at line 149 of file Potential.hpp.
epsilon
real espressopp::interaction::LJcos::epsilon private
Definition at line 144 of file LJcos.hpp.
Referenced by _computeEnergySqrRaw(), getEpsilon(), preset(), and setEpsilon().
ff1
real espressopp::interaction::LJcos::ff1 private
Definition at line 151 of file LJcos.hpp.
Referenced by _computeForceRaw(), and preset().
ff2
real espressopp::interaction::LJcos::ff2 private
Definition at line 151 of file LJcos.hpp.
Referenced by _computeForceRaw(), and preset().
gamma
real espressopp::interaction::LJcos::gamma private
Definition at line 148 of file LJcos.hpp.
Referenced by preset().
gamma_phi
real espressopp::interaction::LJcos::gamma_phi private
Definition at line 149 of file LJcos.hpp.
Referenced by _computeEnergySqrRaw(), and preset().
half_phi
real espressopp::interaction::LJcos::half_phi private
Definition at line 149 of file LJcos.hpp.
Referenced by _computeEnergySqrRaw(), and preset().
one_phi
real espressopp::interaction::LJcos::one_phi private
Definition at line 149 of file LJcos.hpp.
Referenced by _computeEnergySqrRaw(), and preset().
phi
real espressopp::interaction::LJcos::phi private
Definition at line 142 of file LJcos.hpp.
Referenced by getPhi(), preset(), and setPhi().
r_min
real espressopp::interaction::LJcos::r_min private
Definition at line 147 of file LJcos.hpp.
Referenced by preset().
shift
real espressopp::interaction::PotentialTemplate< LJcos >::shift protected inherited
Definition at line 150 of file Potential.hpp.
sigma
real espressopp::interaction::LJcos::sigma private
Definition at line 145 of file LJcos.hpp.
Referenced by _computeEnergySqrRaw(), getSigma(), preset(), and setSigma().
sqr_cutoff
real espressopp::interaction::LJcos::sqr_cutoff private
Definition at line 150 of file LJcos.hpp.
Referenced by preset().
sqr_r_min
real espressopp::interaction::LJcos::sqr_r_min private
Definition at line 147 of file LJcos.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), and preset().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/LJcos.hpp
/home/espressopp/espressopp/src/interaction/LJcos.cpp