ESPResSo++: espressopp::interaction::ConstrainRG Class Reference
espressopp::interaction::ConstrainRG Class Reference
This class provides methods to compute forces and energies of the ConstrainRG part.
#include <ConstrainRG.hpp>
Public Member Functions
ConstrainRG (real _k_rg)
~ConstrainRG ()
void setK_rg (real _k_rg)
real getK_rg () const
real _computeEnergy (real diff_rg)
Real3D _computeForce (Real3D diff, real diff_rg, long unsigned int N_Constrain)
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &dist, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)
virtual shared_ptr< FixedPairList > getColVarBondList () const
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &fpl)
virtual shared_ptr< FixedTripleList > getColVarAngleList () const
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fpl)
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const
virtual void setColVar (const RealND &cv)
virtual void setColVar (const Real3D &dist, const bc::BC &bc)
virtual RealND getColVar () const
virtual void computeColVarWeights (const Real3D &dist, const bc::BC &bc)
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
real _computeEnergyDeriv (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
ConstrainRG * derived_this ()
const ConstrainRG * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
shared_ptr< FixedPairList > colVarBondList
shared_ptr< FixedTripleList > colVarAngleList
shared_ptr< FixedQuadrupleList > colVarDihedList
RealND colVar
Private Attributes
real k_rg
Detailed Description
This class provides methods to compute forces and energies of the ConstrainRG part.
The code is based on G. Zhang's work. Reference in literature G. Zhang, L. A. Moreira, T. Stuehn, K. CH. Daoulas, K. Kremer, Macro Lett., 2014, 3, 198
Definition at line 45 of file ConstrainRG.hpp.
Constructor & Destructor Documentation
ConstrainRG()
espressopp::interaction::ConstrainRG::ConstrainRG (real _k_rg)
Definition at line 27 of file ConstrainRG.cpp.
~ConstrainRG()
espressopp::interaction::ConstrainRG::~ConstrainRG ()
Definition at line 29 of file ConstrainRG.cpp.
Member Function Documentation
_computeEnergy() [1/5]
real espressopp::interaction::ConstrainRG::_computeEnergy (real diff_rg) inline
Definition at line 68 of file ConstrainRG.hpp.
_computeEnergy() [2/5]
real espressopp::interaction::PotentialTemplate< ConstrainRG >::_computeEnergy (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 352 of file Potential.hpp.
_computeEnergy() [3/5]
real espressopp::interaction::PotentialTemplate< ConstrainRG >::_computeEnergy (const Real3D & dist) const inline inherited
Definition at line 367 of file Potential.hpp.
_computeEnergy() [4/5]
real espressopp::interaction::PotentialTemplate< ConstrainRG >::_computeEnergy (real dist) const inline inherited
Definition at line 374 of file Potential.hpp.
_computeEnergy() [5/5]
real espressopp::interaction::PotentialTemplate< ConstrainRG >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 360 of file Potential.hpp.
_computeEnergyDeriv()
real espressopp::interaction::PotentialTemplate< ConstrainRG >::_computeEnergyDeriv (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 395 of file Potential.hpp.
_computeEnergySqr()
real espressopp::interaction::PotentialTemplate< ConstrainRG >::_computeEnergySqr (real distSqr) const inline inherited
Definition at line 381 of file Potential.hpp.
_computeEnergySqrRaw()
real espressopp::interaction::ConstrainRG::_computeEnergySqrRaw (real distSqr) const inline
Definition at line 85 of file ConstrainRG.hpp.
References LOG4ESPP_INFO.
_computeForce() [1/4]
Real3D espressopp::interaction::ConstrainRG::_computeForce (Real3D diff, real diff_rg, long unsigned int N_Constrain) inline
Definition at line 78 of file ConstrainRG.hpp.
_computeForce() [2/4]
bool espressopp::interaction::PotentialTemplate< ConstrainRG >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const inline inherited
Definition at line 423 of file Potential.hpp.
_computeForce() [3/4]
bool espressopp::interaction::PotentialTemplate< ConstrainRG >::_computeForce (Real3D & force, const Real3D & dist) const inline inherited
Definition at line 438 of file Potential.hpp.
_computeForce() [4/4]
bool espressopp::interaction::PotentialTemplate< ConstrainRG >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 431 of file Potential.hpp.
_computeForceRaw()
bool espressopp::interaction::ConstrainRG::_computeForceRaw (Real3D & force, const Real3D & dist, real distSqr) const inline
Definition at line 90 of file ConstrainRG.hpp.
References LOG4ESPP_INFO.
computeColVarWeights()
void espressopp::interaction::PotentialTemplate< ConstrainRG >::computeColVarWeights (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 315 of file Potential.hpp.
computeEnergy() [1/3]
real espressopp::interaction::PotentialTemplate< ConstrainRG >::computeEnergy (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 323 of file Potential.hpp.
computeEnergy() [2/3]
real espressopp::interaction::PotentialTemplate< ConstrainRG >::computeEnergy (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 331 of file Potential.hpp.
computeEnergy() [3/3]
real espressopp::interaction::PotentialTemplate< ConstrainRG >::computeEnergy (real dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 338 of file Potential.hpp.
computeEnergySqr()
real espressopp::interaction::PotentialTemplate< ConstrainRG >::computeEnergySqr (real distsqr) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 345 of file Potential.hpp.
computeForce() [1/2]
Real3D espressopp::interaction::PotentialTemplate< ConstrainRG >::computeForce (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 405 of file Potential.hpp.
computeForce() [2/2]
Real3D espressopp::interaction::PotentialTemplate< ConstrainRG >::computeForce (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 413 of file Potential.hpp.
derived_this() [1/2]
ConstrainRG * espressopp::interaction::PotentialTemplate< ConstrainRG >::derived_this () inline protected inherited
Definition at line 161 of file Potential.hpp.
derived_this() [2/2]
const ConstrainRG * espressopp::interaction::PotentialTemplate< ConstrainRG >::derived_this () const inline protected inherited
Definition at line 165 of file Potential.hpp.
getColVar()
RealND espressopp::interaction::PotentialTemplate< ConstrainRG >::getColVar () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 309 of file Potential.hpp.
getColVarAngleList()
shared_ptr< FixedTripleList > espressopp::interaction::PotentialTemplate< ConstrainRG >::getColVarAngleList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 273 of file Potential.hpp.
getColVarBondList()
shared_ptr< FixedPairList > espressopp::interaction::PotentialTemplate< ConstrainRG >::getColVarBondList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 259 of file Potential.hpp.
getColVarDihedList()
shared_ptr< FixedQuadrupleList > espressopp::interaction::PotentialTemplate< ConstrainRG >::getColVarDihedList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 287 of file Potential.hpp.
getCutoff()
real espressopp::interaction::PotentialTemplate< ConstrainRG >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 210 of file Potential.hpp.
getK_rg()
real espressopp::interaction::ConstrainRG::getK_rg () const inline
Definition at line 62 of file ConstrainRG.hpp.
Referenced by registerPython().
getShift()
real espressopp::interaction::PotentialTemplate< ConstrainRG >::getShift () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 225 of file Potential.hpp.
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
Referenced by espressopp::interaction::Potential::~Potential().
registerPython()
void espressopp::interaction::ConstrainRG::registerPython () static
Definition at line 33 of file ConstrainRG.cpp.
References getK_rg(), and setK_rg().
Referenced by espressopp::interaction::registerPython().
setAutoShift()
real espressopp::interaction::PotentialTemplate< ConstrainRG >::setAutoShift () inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 231 of file Potential.hpp.
setColVar() [1/2]
void espressopp::interaction::PotentialTemplate< ConstrainRG >::setColVar (const RealND & cv) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 294 of file Potential.hpp.
setColVar() [2/2]
void espressopp::interaction::PotentialTemplate< ConstrainRG >::setColVar (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 301 of file Potential.hpp.
setColVarAngleList()
void espressopp::interaction::PotentialTemplate< ConstrainRG >::setColVarAngleList (const shared_ptr< FixedTripleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 266 of file Potential.hpp.
setColVarBondList()
void espressopp::interaction::PotentialTemplate< ConstrainRG >::setColVarBondList (const shared_ptr< FixedPairList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 252 of file Potential.hpp.
setColVarDihedList()
void espressopp::interaction::PotentialTemplate< ConstrainRG >::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 280 of file Potential.hpp.
setCutoff()
void espressopp::interaction::PotentialTemplate< ConstrainRG >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 201 of file Potential.hpp.
setK_rg()
void espressopp::interaction::ConstrainRG::setK_rg (real _k_rg) inline
Definition at line 59 of file ConstrainRG.hpp.
Referenced by registerPython().
setShift()
void espressopp::interaction::PotentialTemplate< ConstrainRG >::setShift (real _shift) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 216 of file Potential.hpp.
updateAutoShift()
void espressopp::interaction::PotentialTemplate< ConstrainRG >::updateAutoShift () inline inherited
Definition at line 244 of file Potential.hpp.
Member Data Documentation
autoShift
bool espressopp::interaction::PotentialTemplate< ConstrainRG >::autoShift protected inherited
Definition at line 151 of file Potential.hpp.
colVar
RealND espressopp::interaction::PotentialTemplate< ConstrainRG >::colVar protected inherited
Definition at line 159 of file Potential.hpp.
colVarAngleList
shared_ptr<FixedTripleList> espressopp::interaction::PotentialTemplate< ConstrainRG >::colVarAngleList protected inherited
Definition at line 155 of file Potential.hpp.
colVarBondList
shared_ptr<FixedPairList> espressopp::interaction::PotentialTemplate< ConstrainRG >::colVarBondList protected inherited
Definition at line 153 of file Potential.hpp.
colVarDihedList
shared_ptr<FixedQuadrupleList> espressopp::interaction::PotentialTemplate< ConstrainRG >::colVarDihedList protected inherited
Definition at line 157 of file Potential.hpp.
cutoff
real espressopp::interaction::PotentialTemplate< ConstrainRG >::cutoff protected inherited
Definition at line 148 of file Potential.hpp.
cutoffSqr
real espressopp::interaction::PotentialTemplate< ConstrainRG >::cutoffSqr protected inherited
Definition at line 149 of file Potential.hpp.
k_rg
real espressopp::interaction::ConstrainRG::k_rg private
Definition at line 47 of file ConstrainRG.hpp.
shift
real espressopp::interaction::PotentialTemplate< ConstrainRG >::shift protected inherited
Definition at line 150 of file Potential.hpp.
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/ConstrainRG.hpp
/home/espressopp/espressopp/src/interaction/ConstrainRG.cpp