ESPResSo++: espressopp::interaction::AngularPotential Class Reference
espressopp::interaction::AngularPotential Class Reference abstract
#include <AngularPotential.hpp>
Public Member Functions
virtual real computeEnergy (const Particle &p1, const Particle &p2, const Particle &p3) const =0
virtual real computeEnergy (const Real3D &dist12, const Real3D &dist32) const =0
virtual real computeEnergy (real theta) const =0
virtual void computeForce (Real3D &force12, Real3D &force32, const Particle &p1, const Particle &p2, const Particle &p3) const =0
virtual void computeForce (Real3D &force12, Real3D &force32, const Real3D &dist12, const Real3D &dist32) const =0
virtual real computeForce (real theta) const =0
virtual void setCutoff (real _cutoff)=0
virtual real getCutoff () const =0
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)=0
virtual shared_ptr< FixedPairList > getColVarBondList () const =0
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &fpl)=0
virtual shared_ptr< FixedTripleList > getColVarAngleList () const =0
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fpl)=0
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const =0
virtual void setColVar (const RealND &cv)=0
virtual void setColVar (const Real3D &dist12, const Real3D &dist32, const bc::BC &bc)=0
virtual RealND getColVar () const =0
virtual void computeColVarWeights (const Real3D &dist12, const Real3D &dist32, const bc::BC &bc)=0
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Detailed Description
Definition at line 40 of file AngularPotential.hpp.
Member Function Documentation
computeColVarWeights()
virtual void espressopp::interaction::AngularPotential::computeColVarWeights (const Real3D & dist12, const Real3D & dist32, const bc::BC & bc) pure virtual
Implemented in espressopp::interaction::TabulatedSubEnsAngular, espressopp::interaction::AngularPotentialTemplate< Derived >, espressopp::interaction::AngularPotentialTemplate< Cosine >, espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >, espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >, espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >, espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >, espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >, and espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >.
computeEnergy() [1/3]
virtual real espressopp::interaction::AngularPotential::computeEnergy (const Particle & p1, const Particle & p2, const Particle & p3) const pure virtual
Implemented in espressopp::interaction::AngularPotentialTemplate< Derived >, espressopp::interaction::AngularPotentialTemplate< Cosine >, espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >, espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >, espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >, espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >, espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >, and espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >.
Referenced by registerPython().
computeEnergy() [2/3]
virtual real espressopp::interaction::AngularPotential::computeEnergy (const Real3D & dist12, const Real3D & dist32) const pure virtual
Implemented in espressopp::interaction::AngularPotentialTemplate< Derived >, espressopp::interaction::AngularPotentialTemplate< Cosine >, espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >, espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >, espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >, espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >, espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >, and espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >.
computeEnergy() [3/3]
virtual real espressopp::interaction::AngularPotential::computeEnergy (real theta) const pure virtual
Implemented in espressopp::interaction::AngularPotentialTemplate< Derived >, espressopp::interaction::AngularPotentialTemplate< Cosine >, espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >, espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >, espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >, espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >, espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >, and espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >.
computeForce() [1/3]
virtual real espressopp::interaction::AngularPotential::computeForce (real theta) const pure virtual
Implemented in espressopp::interaction::AngularPotentialTemplate< Derived >, espressopp::interaction::AngularPotentialTemplate< Cosine >, espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >, espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >, espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >, espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >, espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >, and espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >.
computeForce() [2/3]
virtual void espressopp::interaction::AngularPotential::computeForce (Real3D & force12, Real3D & force32, const Particle & p1, const Particle & p2, const Particle & p3) const pure virtual
Implemented in espressopp::interaction::AngularPotentialTemplate< Derived >, espressopp::interaction::AngularPotentialTemplate< Cosine >, espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >, espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >, espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >, espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >, espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >, and espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >.
Referenced by registerPython().
computeForce() [3/3]
virtual void espressopp::interaction::AngularPotential::computeForce (Real3D & force12, Real3D & force32, const Real3D & dist12, const Real3D & dist32) const pure virtual
Implemented in espressopp::interaction::AngularPotentialTemplate< Derived >, espressopp::interaction::AngularPotentialTemplate< Cosine >, espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >, espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >, espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >, espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >, espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >, and espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >.
getColVar()
virtual RealND espressopp::interaction::AngularPotential::getColVar () const pure virtual
Implemented in espressopp::interaction::AngularPotentialTemplate< Derived >.
Referenced by registerPython().
getColVarAngleList()
virtual shared_ptr<FixedTripleList> espressopp::interaction::AngularPotential::getColVarAngleList () const pure virtual
Implemented in espressopp::interaction::AngularPotentialTemplate< Derived >.
Referenced by registerPython().
getColVarBondList()
virtual shared_ptr<FixedPairList> espressopp::interaction::AngularPotential::getColVarBondList () const pure virtual
Implemented in espressopp::interaction::AngularPotentialTemplate< Derived >.
Referenced by registerPython().
getColVarDihedList()
virtual shared_ptr<FixedQuadrupleList> espressopp::interaction::AngularPotential::getColVarDihedList () const pure virtual
Implemented in espressopp::interaction::AngularPotentialTemplate< Derived >.
Referenced by registerPython().
getCutoff()
virtual real espressopp::interaction::AngularPotential::getCutoff () const pure virtual
Implemented in espressopp::interaction::TersoffTripleTerm, espressopp::interaction::StillingerWeberTripleTerm, and espressopp::interaction::AngularPotentialTemplate< Derived >.
Referenced by registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::AngularPotential::LOG4ESPP_DECL_LOGGER (theLogger) static
registerPython()
void espressopp::interaction::AngularPotential::registerPython () static
Definition at line 35 of file AngularPotential.cpp.
References computeEnergy(), computeForce(), getColVar(), getColVarAngleList(), getColVarBondList(), getColVarDihedList(), getCutoff(), setColVarAngleList(), setColVarBondList(), setColVarDihedList(), and setCutoff().
Referenced by espressopp::interaction::registerPython().
setColVar() [1/2]
virtual void espressopp::interaction::AngularPotential::setColVar (const Real3D & dist12, const Real3D & dist32, const bc::BC & bc) pure virtual
Implemented in espressopp::interaction::TabulatedSubEnsAngular, espressopp::interaction::AngularPotentialTemplate< Derived >, espressopp::interaction::AngularPotentialTemplate< Cosine >, espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >, espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >, espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >, espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >, espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >, and espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >.
setColVar() [2/2]
virtual void espressopp::interaction::AngularPotential::setColVar (const RealND & cv) pure virtual
Implemented in espressopp::interaction::AngularPotentialTemplate< Derived >, espressopp::interaction::AngularPotentialTemplate< Cosine >, espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >, espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >, espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >, espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >, espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >, and espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >.
setColVarAngleList()
virtual void espressopp::interaction::AngularPotential::setColVarAngleList (const shared_ptr< FixedTripleList > & fpl) pure virtual
Implemented in espressopp::interaction::AngularPotentialTemplate< Derived >, espressopp::interaction::AngularPotentialTemplate< Cosine >, espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >, espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >, espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >, espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >, espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >, and espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >.
Referenced by registerPython().
setColVarBondList()
virtual void espressopp::interaction::AngularPotential::setColVarBondList (const shared_ptr< FixedPairList > & fpl) pure virtual
Implemented in espressopp::interaction::AngularPotentialTemplate< Derived >, espressopp::interaction::AngularPotentialTemplate< Cosine >, espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >, espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >, espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >, espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >, espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >, and espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >.
Referenced by registerPython().
setColVarDihedList()
virtual void espressopp::interaction::AngularPotential::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fpl) pure virtual
Implemented in espressopp::interaction::AngularPotentialTemplate< Derived >, espressopp::interaction::AngularPotentialTemplate< Cosine >, espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >, espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >, espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >, espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >, espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >, and espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >.
Referenced by registerPython().
setCutoff()
virtual void espressopp::interaction::AngularPotential::setCutoff (real _cutoff) pure virtual
Implemented in espressopp::interaction::AngularPotentialTemplate< Derived >, espressopp::interaction::AngularPotentialTemplate< Cosine >, espressopp::interaction::AngularPotentialTemplate< TabulatedSubEnsAngular >, espressopp::interaction::AngularPotentialTemplate< TabulatedAngular >, espressopp::interaction::AngularPotentialTemplate< StillingerWeberTripleTerm >, espressopp::interaction::AngularPotentialTemplate< AngularHarmonic >, espressopp::interaction::AngularPotentialTemplate< AngularCosineSquared >, and espressopp::interaction::AngularPotentialTemplate< TersoffTripleTerm >.
Referenced by registerPython().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/AngularPotential.hpp
/home/espressopp/espressopp/src/interaction/AngularPotential.cpp