ESPResSo++: espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG > Class Template Reference
espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG > Class Template Reference
#include <VerletListHadressInteractionTemplate.hpp>
Public Member Functions
VerletListHadressInteractionTemplate (shared_ptr< VerletListAdress > _verletList, shared_ptr< FixedTupleListAdress > _fixedtupleList)
void setVerletList (shared_ptr< VerletListAdress > _verletList)
shared_ptr< VerletListAdress > getVerletList ()
void setFixedTupleList (shared_ptr< FixedTupleListAdress > _fixedtupleList)
void setPotentialAT (int type1, int type2, const PotentialAT &potential)
void setPotentialCG (int type1, int type2, const PotentialCG &potential)
PotentialAT & getPotentialAT (int type1, int type2)
PotentialCG & getPotentialCG (int type1, int type2)
virtual void addForces ()
virtual real computeEnergy ()
virtual real computeEnergyDeriv ()
virtual real computeEnergyAA ()
virtual real computeEnergyCG ()
virtual void computeVirialX (std::vector< real > &p_xx_total, int bins)
virtual real computeVirial ()
virtual void computeVirialTensor (Tensor &w)
virtual void computeVirialTensor (Tensor &w, real z)
virtual void computeVirialTensor (Tensor *w, int n)
virtual real getMaxCutoff ()
This method returns the maximal cutoff defined for one type pair.
virtual int bondType ()
Static Public Member Functions
static void registerPython ()
Protected Types
typedef _PotentialAT PotentialAT
typedef _PotentialCG PotentialCG
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Protected Attributes
int ntypes
shared_ptr< VerletListAdress > verletList
shared_ptr< FixedTupleListAdress > fixedtupleList
esutil::Array2D< PotentialAT,
esutil::enlarge > potentialArrayAT
esutil::Array2D< PotentialCG,
esutil::enlarge > potentialArrayCG
real pidhy2
real dexdhy
real dexdhy2
real dex
real dhy
real dex2
std::map< Particle *, real > energydiff
std::set< Particle * > adrZone
std::set< Particle * > cgZone
Detailed Description
template<typename _PotentialAT, typename _PotentialCG>
class espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >
Definition at line 43 of file VerletListHadressInteractionTemplate.hpp.
Member Typedef Documentation
template<typename _PotentialAT , typename _PotentialCG > typedef _PotentialAT espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::PotentialAT protected
Definition at line 46 of file VerletListHadressInteractionTemplate.hpp.
template<typename _PotentialAT , typename _PotentialCG > typedef _PotentialCG espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::PotentialCG protected
Definition at line 47 of file VerletListHadressInteractionTemplate.hpp.
Constructor & Destructor Documentation
template<typename _PotentialAT , typename _PotentialCG > espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::VerletListHadressInteractionTemplate (shared_ptr< VerletListAdress > _verletList, shared_ptr< FixedTupleListAdress > _fixedtupleList) inline
Definition at line 51 of file VerletListHadressInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::dex, espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::dex2, espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::dexdhy, espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::dexdhy2, espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::dhy, M_PI, espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::ntypes, espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::pidhy2, espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::potentialArrayAT, espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::potentialArrayCG, and espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::verletList.
Member Function Documentation
template<typename _PotentialAT , typename _PotentialCG > void espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::addForces () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 150 of file VerletListHadressInteractionTemplate.hpp.
References espressopp::Particle::drift(), espressopp::Particle::force(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::Particle::lambda(), espressopp::Particle::lambdaDeriv(), LOG4ESPP_INFO, espressopp::Particle::position(), espressopp::Real3D::sqr(), and espressopp::Particle::type().
template<typename _PotentialAT , typename _PotentialCG > virtual int espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::bondType () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 123 of file VerletListHadressInteractionTemplate.hpp.
References espressopp::interaction::Nonbonded.
template<typename _PotentialAT , typename _PotentialCG > real espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeEnergy () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 350 of file VerletListHadressInteractionTemplate.hpp.
References espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::Particle::lambda(), LOG4ESPP_INFO, and espressopp::Particle::type().
template<typename _PotentialAT , typename _PotentialCG > real espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeEnergyAA () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 424 of file VerletListHadressInteractionTemplate.hpp.
References espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_INFO, and espressopp::Particle::type().
template<typename _PotentialAT , typename _PotentialCG > real espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeEnergyCG () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 501 of file VerletListHadressInteractionTemplate.hpp.
References espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_INFO, and espressopp::Particle::type().
template<typename _PotentialAT , typename _PotentialCG > real espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeEnergyDeriv () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 417 of file VerletListHadressInteractionTemplate.hpp.
template<typename _PotentialAT , typename _PotentialCG > real espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirial () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 800 of file VerletListHadressInteractionTemplate.hpp.
References espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::Particle::lambda(), LOG4ESPP_INFO, mpiWorld, espressopp::Particle::position(), and espressopp::Particle::type().
template<typename _PotentialAT , typename _PotentialCG > void espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialTensor (Tensor & w) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 905 of file VerletListHadressInteractionTemplate.hpp.
References espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_INFO, mpiWorld, espressopp::Particle::position(), and espressopp::Particle::type().
template<typename _PotentialAT , typename _PotentialCG > void espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialTensor (Tensor & w, real z) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 944 of file VerletListHadressInteractionTemplate.hpp.
References LOG4ESPP_INFO.
template<typename _PotentialAT , typename _PotentialCG > void espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialTensor (Tensor * w, int n) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 953 of file VerletListHadressInteractionTemplate.hpp.
template<typename _PotentialAT , typename _PotentialCG > void espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialX (std::vector< real > & p_xx_total, int bins) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 533 of file VerletListHadressInteractionTemplate.hpp.
References espressopp::Real3D::at(), espressopp::System::bc, espressopp::Particle::getMass(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::Particle::lambda(), LOG4ESPP_INFO, espressopp::Particle::mass(), mpiWorld, espressopp::Particle::position(), and espressopp::Particle::type().
template<typename _PotentialAT , typename _PotentialCG > real espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::getMaxCutoff () inline virtual
This method returns the maximal cutoff defined for one type pair.
Implements espressopp::interaction::Interaction.
Definition at line 960 of file VerletListHadressInteractionTemplate.hpp.
template<typename _PotentialAT , typename _PotentialCG > PotentialAT& espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::getPotentialAT (int type1, int type2) inline
Definition at line 104 of file VerletListHadressInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), and espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::potentialArrayAT.
template<typename _PotentialAT , typename _PotentialCG > PotentialCG& espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::getPotentialCG (int type1, int type2) inline
Definition at line 108 of file VerletListHadressInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), and espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::potentialArrayCG.
template<typename _PotentialAT , typename _PotentialCG > shared_ptr<VerletListAdress> espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::getVerletList () inline
Definition at line 73 of file VerletListHadressInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::verletList.
static espressopp::interaction::Interaction::LOG4ESPP_DECL_LOGGER (theLogger) static protected inherited
Logger.
void espressopp::interaction::Interaction::registerPython () static inherited
Definition at line 36 of file Interaction.cpp.
References espressopp::interaction::Interaction::bondType(), espressopp::interaction::Interaction::computeEnergy(), espressopp::interaction::Interaction::computeEnergyAA(), espressopp::interaction::Interaction::computeEnergyCG(), espressopp::interaction::Interaction::computeEnergyDeriv(), and espressopp::interaction::Interaction::computeVirial().
Referenced by espressopp::interaction::registerPython().
template<typename _PotentialAT , typename _PotentialCG > void espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::setFixedTupleList (shared_ptr< FixedTupleListAdress > _fixedtupleList) inline
Definition at line 78 of file VerletListHadressInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::fixedtupleList.
template<typename _PotentialAT , typename _PotentialCG > void espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::setPotentialAT (int type1, int type2, const PotentialAT & potential) inline
Definition at line 83 of file VerletListHadressInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::ntypes, and espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::potentialArrayAT.
template<typename _PotentialAT , typename _PotentialCG > void espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::setPotentialCG (int type1, int type2, const PotentialCG & potential) inline
Definition at line 94 of file VerletListHadressInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::ntypes, and espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::potentialArrayCG.
template<typename _PotentialAT , typename _PotentialCG > void espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::setVerletList (shared_ptr< VerletListAdress > _verletList) inline
Definition at line 69 of file VerletListHadressInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::verletList.
Member Data Documentation
template<typename _PotentialAT , typename _PotentialCG > std::set<Particle*> espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::adrZone protected
Definition at line 140 of file VerletListHadressInteractionTemplate.hpp.
template<typename _PotentialAT , typename _PotentialCG > std::set<Particle*> espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::cgZone protected
Definition at line 141 of file VerletListHadressInteractionTemplate.hpp.
template<typename _PotentialAT , typename _PotentialCG > real espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::dex protected
Definition at line 136 of file VerletListHadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::VerletListHadressInteractionTemplate().
template<typename _PotentialAT , typename _PotentialCG > real espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::dex2 protected
Definition at line 138 of file VerletListHadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::VerletListHadressInteractionTemplate().
template<typename _PotentialAT , typename _PotentialCG > real espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::dexdhy protected
Definition at line 134 of file VerletListHadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::VerletListHadressInteractionTemplate().
template<typename _PotentialAT , typename _PotentialCG > real espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::dexdhy2 protected
Definition at line 135 of file VerletListHadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::VerletListHadressInteractionTemplate().
template<typename _PotentialAT , typename _PotentialCG > real espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::dhy protected
Definition at line 137 of file VerletListHadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::VerletListHadressInteractionTemplate().
template<typename _PotentialAT , typename _PotentialCG > std::map<Particle*, real> espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::energydiff protected
Definition at line 139 of file VerletListHadressInteractionTemplate.hpp.
template<typename _PotentialAT , typename _PotentialCG > shared_ptr<FixedTupleListAdress> espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::fixedtupleList protected
Definition at line 128 of file VerletListHadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::setFixedTupleList().
template<typename _PotentialAT , typename _PotentialCG > int espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::ntypes protected
Definition at line 126 of file VerletListHadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::setPotentialAT(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::setPotentialCG(), and espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::VerletListHadressInteractionTemplate().
template<typename _PotentialAT , typename _PotentialCG > real espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::pidhy2 protected
Definition at line 133 of file VerletListHadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::VerletListHadressInteractionTemplate().
template<typename _PotentialAT , typename _PotentialCG > esutil::Array2D<PotentialAT, esutil::enlarge> espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::potentialArrayAT protected
Definition at line 129 of file VerletListHadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::getPotentialAT(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::setPotentialAT(), and espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::VerletListHadressInteractionTemplate().
template<typename _PotentialAT , typename _PotentialCG > esutil::Array2D<PotentialCG, esutil::enlarge> espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::potentialArrayCG protected
Definition at line 130 of file VerletListHadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::getPotentialCG(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::setPotentialCG(), and espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::VerletListHadressInteractionTemplate().
template<typename _PotentialAT , typename _PotentialCG > shared_ptr<VerletListAdress> espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::verletList protected
Definition at line 127 of file VerletListHadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::getVerletList(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::setVerletList(), and espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::VerletListHadressInteractionTemplate().
The documentation for this class was generated from the following file:
/home/travis/build/espressopp/espressopp/src/interaction/VerletListHadressInteractionTemplate.hpp