ESPResSo++: espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential > Class Template Reference
espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential > Class Template Reference
#include <FixedQuadrupleListTypesInteractionTemplate.hpp>
Public Member Functions
FixedQuadrupleListTypesInteractionTemplate (shared_ptr< System > _system, shared_ptr< FixedQuadrupleList > _fixedquadrupleList)
void setFixedQuadrupleList (shared_ptr< FixedQuadrupleList > _fixedquadrupleList)
virtual ~FixedQuadrupleListTypesInteractionTemplate ()
shared_ptr< FixedQuadrupleList > getFixedQuadrupleList ()
void setPotential (int type1, int type2, int type3, int type4, const Potential &potential)
Potential & getPotential (int type1, int type2, int type3, int type4)
shared_ptr< Potential > getPotentialPtr (int type1, int type2, int type3, int type4)
virtual void addForces ()
virtual real computeEnergy ()
virtual real computeEnergyDeriv ()
virtual real computeEnergyAA ()
virtual real computeEnergyCG ()
virtual real computeEnergyAA (int atomtype)
virtual real computeEnergyCG (int atomtype)
virtual void computeVirialX (std::vector< real > &p_xx_total, int bins)
virtual real computeVirial ()
virtual void computeVirialTensor (Tensor &w)
virtual void computeVirialTensor (Tensor &w, real z)
virtual void computeVirialTensor (Tensor *w, int n)
virtual real getMaxCutoff ()
This method returns the maximal cutoff defined for one type pair.
virtual int bondType ()
Static Public Member Functions
static void registerPython ()
Protected Types
typedef _DihedralPotential Potential
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Protected Attributes
int ntypes
shared_ptr< FixedQuadrupleList > fixedquadrupleList
esutil::Array4D< Potential, esutil::enlarge > potentialArray
Private Member Functions
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Detailed Description
template<typename _DihedralPotential>
class espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >
Definition at line 46 of file FixedQuadrupleListTypesInteractionTemplate.hpp.
Member Typedef Documentation
Potential
template<typename _DihedralPotential > typedef _DihedralPotential espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::Potential protected
Definition at line 48 of file FixedQuadrupleListTypesInteractionTemplate.hpp.
Constructor & Destructor Documentation
FixedQuadrupleListTypesInteractionTemplate()
template<typename _DihedralPotential > espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::FixedQuadrupleListTypesInteractionTemplate (shared_ptr< System > _system, shared_ptr< FixedQuadrupleList > _fixedquadrupleList) inline
Definition at line 52 of file FixedQuadrupleListTypesInteractionTemplate.hpp.
References espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::ntypes, and espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::potentialArray.
~FixedQuadrupleListTypesInteractionTemplate()
template<typename _DihedralPotential > virtual espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::~FixedQuadrupleListTypesInteractionTemplate () inline virtual
Definition at line 64 of file FixedQuadrupleListTypesInteractionTemplate.hpp.
Member Function Documentation
addForces()
template<typename _DihedralPotential > void espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::addForces () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 115 of file FixedQuadrupleListTypesInteractionTemplate.hpp.
References espressopp::System::bc, espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::fixedquadrupleList, espressopp::Particle::force(), espressopp::bc::BC::getMinimumImageVectorBox(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::getPotential(), espressopp::SystemAccess::getSystemRef(), LOG4ESPP_INFO, espressopp::Particle::position(), and espressopp::Particle::type().
Referenced by espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::getPotentialPtr().
bondType()
template<typename _DihedralPotential > virtual int espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::bondType () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 101 of file FixedQuadrupleListTypesInteractionTemplate.hpp.
References espressopp::interaction::Dihedral.
computeEnergy()
template<typename _DihedralPotential > real espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergy () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 154 of file FixedQuadrupleListTypesInteractionTemplate.hpp.
References espressopp::System::bc, espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergyDeriv(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::fixedquadrupleList, espressopp::bc::BC::getMinimumImageVectorBox(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::getPotential(), espressopp::SystemAccess::getSystemRef(), LOG4ESPP_INFO, mpiWorld, espressopp::Particle::position(), and espressopp::Particle::type().
Referenced by espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::addForces(), and espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::getPotentialPtr().
computeEnergyAA() [1/2]
template<typename _DihedralPotential > real espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergyAA () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 196 of file FixedQuadrupleListTypesInteractionTemplate.hpp.
Referenced by espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergyDeriv(), and espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::getPotentialPtr().
computeEnergyAA() [2/2]
template<typename _DihedralPotential > real espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergyAA (int atomtype) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 204 of file FixedQuadrupleListTypesInteractionTemplate.hpp.
References espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergyCG().
computeEnergyCG() [1/2]
template<typename _DihedralPotential > real espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergyCG () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 212 of file FixedQuadrupleListTypesInteractionTemplate.hpp.
Referenced by espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergyAA(), and espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::getPotentialPtr().
computeEnergyCG() [2/2]
template<typename _DihedralPotential > real espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergyCG (int atomtype) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 220 of file FixedQuadrupleListTypesInteractionTemplate.hpp.
References espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialX().
computeEnergyDeriv()
template<typename _DihedralPotential > real espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergyDeriv () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 188 of file FixedQuadrupleListTypesInteractionTemplate.hpp.
References espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergyAA().
Referenced by espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergy(), and espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::getPotentialPtr().
computeVirial()
template<typename _DihedralPotential > real espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirial () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 235 of file FixedQuadrupleListTypesInteractionTemplate.hpp.
References espressopp::System::bc, espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::fixedquadrupleList, espressopp::bc::BC::getMinimumImageVectorBox(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::getPotential(), espressopp::SystemAccess::getSystemRef(), LOG4ESPP_INFO, mpiWorld, espressopp::Particle::position(), and espressopp::Particle::type().
Referenced by espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialX(), and espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::getPotentialPtr().
computeVirialTensor() [1/3]
template<typename _DihedralPotential > void espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor (Tensor & w) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 278 of file FixedQuadrupleListTypesInteractionTemplate.hpp.
References espressopp::System::bc, espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::fixedquadrupleList, espressopp::bc::BC::getMinimumImageVectorBox(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::getPotential(), espressopp::SystemAccess::getSystemRef(), LOG4ESPP_INFO, mpiWorld, espressopp::Particle::position(), and espressopp::Particle::type().
Referenced by espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), and espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::getPotentialPtr().
computeVirialTensor() [2/3]
template<typename _DihedralPotential > void espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor (Tensor & w, real z) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 323 of file FixedQuadrupleListTypesInteractionTemplate.hpp.
References espressopp::System::bc, espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::fixedquadrupleList, espressopp::bc::BC::getMinimumImageVectorBox(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::getPotential(), espressopp::SystemAccess::getSystemRef(), LOG4ESPP_INFO, mpiWorld, espressopp::Particle::position(), and espressopp::Particle::type().
computeVirialTensor() [3/3]
template<typename _DihedralPotential > void espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor (Tensor * w, int n) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 370 of file FixedQuadrupleListTypesInteractionTemplate.hpp.
References espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::getMaxCutoff().
computeVirialX()
template<typename _DihedralPotential > void espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialX (std::vector< real > & p_xx_total, int bins) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 228 of file FixedQuadrupleListTypesInteractionTemplate.hpp.
References espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirial().
Referenced by espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergyCG(), and espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::getPotentialPtr().
getFixedQuadrupleList()
template<typename _DihedralPotential > shared_ptr<FixedQuadrupleList> espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::getFixedQuadrupleList () inline
Definition at line 66 of file FixedQuadrupleListTypesInteractionTemplate.hpp.
References espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::fixedquadrupleList.
getMaxCutoff()
template<typename _DihedralPotential > real espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::getMaxCutoff () inline virtual
This method returns the maximal cutoff defined for one type pair.
Implements espressopp::interaction::Interaction.
Definition at line 378 of file FixedQuadrupleListTypesInteractionTemplate.hpp.
References espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::getPotential(), and espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::ntypes.
Referenced by espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), and espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::getPotentialPtr().
getPotential()
template<typename _DihedralPotential > Potential& espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::getPotential (int type1, int type2, int type3, int type4) inline
Definition at line 80 of file FixedQuadrupleListTypesInteractionTemplate.hpp.
References espressopp::esutil::Array4D< T, outlier_mode >::at(), and espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::potentialArray.
Referenced by espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), and espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::getMaxCutoff().
getPotentialPtr()
template<typename _DihedralPotential > shared_ptr<Potential> espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::getPotentialPtr (int type1, int type2, int type3, int type4) inline
Definition at line 84 of file FixedQuadrupleListTypesInteractionTemplate.hpp.
References espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::addForces(), espressopp::esutil::Array4D< T, outlier_mode >::at(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergyAA(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergyCG(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergyDeriv(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialX(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::getMaxCutoff(), and espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::potentialArray.
getSystem()
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::LatticeBoltzmann::assignMyLattice(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::PIAdressIntegrator::computeKineticEnergy(), espressopp::integrator::PIAdressIntegrator::computeMomentumDrift(), espressopp::integrator::PIAdressIntegrator::computePositionDrift(), espressopp::integrator::PIAdressIntegrator::computeRingEnergy(), espressopp::integrator::PIAdressIntegrator::computeRingEnergyRaw(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpXTCAdress::dump(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::io::DumpXYZ::DumpXYZ(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::VerletListTriple::registerPython(), espressopp::VerletList::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
getSystem1()
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
getSystem2()
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
getSystemRef()
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::addForces(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::addForces(), espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerletRESPA::calcForces(), espressopp::integrator::VelocityVerlet::calcForces(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::PIAdressIntegrator::calcForcesF(), espressopp::integrator::PIAdressIntegrator::calcForcesM(), espressopp::integrator::PIAdressIntegrator::calcForcesS(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeCOM(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeEnergy(), espressopp::integrator::PIAdressIntegrator::computeKineticEnergy(), espressopp::integrator::PIAdressIntegrator::computeMomentumDrift(), espressopp::integrator::PIAdressIntegrator::computePositionDrift(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::integrator::PIAdressIntegrator::computeRingEnergy(), espressopp::integrator::PIAdressIntegrator::computeRingEnergyRaw(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::PIAdressIntegrator::distributeForces(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::FixedLocalTupleComListInteractionTemplate(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::VelocityVerletRESPA::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerlet::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::PIAdressIntegrator::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::PIAdressIntegrator::initializeSetup(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::VelocityVerletRESPA::integrate1(), espressopp::integrator::VelocityVerlet::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::VelocityVerletRESPA::integrate2(), espressopp::integrator::VelocityVerlet::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::PIAdressIntegrator::integrateModePos(), espressopp::integrator::Adress::integrateSlow(), espressopp::integrator::PIAdressIntegrator::integrateV1(), espressopp::integrator::PIAdressIntegrator::integrateV2(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::PIAdressIntegrator::OUintegrate(), espressopp::integrator::VelocityVerlet::printForces(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerlet::printPositions(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::VelocityVerletRESPA::run(), espressopp::integrator::PIAdressIntegrator::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::MinimizeEnergy::run(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::Rattle::saveOldPos(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::PIAdressIntegrator::setWeights(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostatOnGroup::thermalize(), espressopp::integrator::LangevinThermostatOnRadius::thermalize(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::integrator::PIAdressIntegrator::transForces(), espressopp::integrator::PIAdressIntegrator::transMom1(), espressopp::integrator::PIAdressIntegrator::transMom2(), espressopp::integrator::PIAdressIntegrator::transPos1(), espressopp::integrator::PIAdressIntegrator::transPos2(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::io::DumpH5MD::update(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::VelocityVerletRESPA::updateForces(), espressopp::integrator::VelocityVerlet::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::PIAdressIntegrator::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
getSystemRef1()
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
getSystemRef2()
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Interaction::LOG4ESPP_DECL_LOGGER (theLogger) static protected inherited
Logger.
Referenced by espressopp::interaction::Interaction::~Interaction().
registerPython()
void espressopp::interaction::Interaction::registerPython () static inherited
Definition at line 36 of file Interaction.cpp.
References espressopp::interaction::Interaction::bondType(), espressopp::interaction::Interaction::computeEnergy(), espressopp::interaction::Interaction::computeEnergyAA(), espressopp::interaction::Interaction::computeEnergyCG(), espressopp::interaction::Interaction::computeEnergyDeriv(), and espressopp::interaction::Interaction::computeVirial().
Referenced by espressopp::interaction::registerPython(), and espressopp::interaction::Interaction::~Interaction().
setFixedQuadrupleList()
template<typename _DihedralPotential > void espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::setFixedQuadrupleList (shared_ptr< FixedQuadrupleList > _fixedquadrupleList) inline
Definition at line 60 of file FixedQuadrupleListTypesInteractionTemplate.hpp.
References espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::fixedquadrupleList.
setPotential()
template<typename _DihedralPotential > void espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::setPotential (int type1, int type2, int type3, int type4, const Potential & potential) inline
Definition at line 70 of file FixedQuadrupleListTypesInteractionTemplate.hpp.
References espressopp::esutil::Array4D< T, outlier_mode >::at(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::ntypes, and espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::potentialArray.
Member Data Documentation
fixedquadrupleList
template<typename _DihedralPotential > shared_ptr<FixedQuadrupleList> espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::fixedquadrupleList protected
Definition at line 105 of file FixedQuadrupleListTypesInteractionTemplate.hpp.
Referenced by espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::getFixedQuadrupleList(), and espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::setFixedQuadrupleList().
ntypes
template<typename _DihedralPotential > int espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::ntypes protected
Definition at line 104 of file FixedQuadrupleListTypesInteractionTemplate.hpp.
Referenced by espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::FixedQuadrupleListTypesInteractionTemplate(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::getMaxCutoff(), and espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::setPotential().
potentialArray
template<typename _DihedralPotential > esutil::Array4D<Potential, esutil::enlarge> espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::potentialArray protected
Definition at line 106 of file FixedQuadrupleListTypesInteractionTemplate.hpp.
Referenced by espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::FixedQuadrupleListTypesInteractionTemplate(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::getPotential(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::getPotentialPtr(), and espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::setPotential().
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/interaction/FixedQuadrupleListTypesInteractionTemplate.hpp