ESPResSo++: espressopp::vectorization::interaction::LennardJones Class Reference
espressopp::vectorization::interaction::LennardJones Class Reference
This class provides methods to compute forces and energies of the Lennard Jones potential.
#include <LennardJones.hpp>
Public Member Functions
const real & getCutoffSqr () const
const real & getff1 () const
const real & getff2 () const
LennardJones ()
LennardJones (real _epsilon, real _sigma, real _cutoff, real _shift)
LennardJones (real _epsilon, real _sigma, real _cutoff)
virtual ~LennardJones ()
void preset ()
void setEpsilon (real _epsilon)
real getEpsilon () const
void setSigma (real _sigma)
real getSigma () const
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &dist, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)
virtual shared_ptr< FixedPairList > getColVarBondList () const
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &fpl)
virtual shared_ptr< FixedTripleList > getColVarAngleList () const
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fpl)
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const
virtual void setColVar (const RealND &cv)
virtual void setColVar (const Real3D &dist, const bc::BC &bc)
virtual RealND getColVar () const
virtual void computeColVarWeights (const Real3D &dist, const bc::BC &bc)
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
real _computeEnergyDeriv (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
Derived * derived_this ()
const Derived * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
shared_ptr< FixedPairList > colVarBondList
shared_ptr< FixedTripleList > colVarAngleList
shared_ptr< FixedQuadrupleList > colVarDihedList
RealND colVar
Private Attributes
real epsilon
real sigma
real ff1
real ff2
real ef1
real ef2
Detailed Description
This class provides methods to compute forces and energies of the Lennard Jones potential.
Definition at line 44 of file LennardJones.hpp.
Constructor & Destructor Documentation
LennardJones() [1/3]
espressopp::vectorization::interaction::LennardJones::LennardJones () inline
Definition at line 59 of file LennardJones.hpp.
References espressopp::infinity, preset(), espressopp::interaction::PotentialTemplate< Derived >::setCutoff(), and espressopp::interaction::PotentialTemplate< Derived >::setShift().
LennardJones() [2/3]
espressopp::vectorization::interaction::LennardJones::LennardJones (real _epsilon, real _sigma, real _cutoff, real _shift) inline
Definition at line 67 of file LennardJones.hpp.
References preset(), espressopp::interaction::PotentialTemplate< Derived >::setCutoff(), and espressopp::interaction::PotentialTemplate< Derived >::setShift().
LennardJones() [3/3]
espressopp::vectorization::interaction::LennardJones::LennardJones (real _epsilon, real _sigma, real _cutoff) inline
Definition at line 75 of file LennardJones.hpp.
References espressopp::interaction::PotentialTemplate< Derived >::autoShift, preset(), espressopp::interaction::PotentialTemplate< Derived >::setAutoShift(), and espressopp::interaction::PotentialTemplate< Derived >::setCutoff().
~LennardJones()
virtual espressopp::vectorization::interaction::LennardJones::~LennardJones () inline virtual
Definition at line 84 of file LennardJones.hpp.
Member Function Documentation
_computeEnergy() [1/4]
template<class Derived > real espressopp::interaction::PotentialTemplate< Derived >::_computeEnergy (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 352 of file Potential.hpp.
Referenced by espressopp::vectorization::interaction::VerletListLennardJones::computeEnergy().
_computeEnergy() [2/4]
template<class Derived > real espressopp::interaction::PotentialTemplate< Derived >::_computeEnergy (const Real3D & dist) const inline inherited
Definition at line 367 of file Potential.hpp.
_computeEnergy() [3/4]
template<class Derived > real espressopp::interaction::PotentialTemplate< Derived >::_computeEnergy (real dist) const inline inherited
Definition at line 374 of file Potential.hpp.
_computeEnergy() [4/4]
template<class Derived > real espressopp::interaction::PotentialTemplate< Derived >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 360 of file Potential.hpp.
_computeEnergyDeriv()
template<class Derived > real espressopp::interaction::PotentialTemplate< Derived >::_computeEnergyDeriv (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 395 of file Potential.hpp.
_computeEnergySqr()
template<class Derived > real espressopp::interaction::PotentialTemplate< Derived >::_computeEnergySqr (real distSqr) const inline inherited
Definition at line 381 of file Potential.hpp.
_computeEnergySqrRaw()
real espressopp::vectorization::interaction::LennardJones::_computeEnergySqrRaw (real distSqr) const inline
Definition at line 113 of file LennardJones.hpp.
_computeForce() [1/3]
template<class Derived > bool espressopp::interaction::PotentialTemplate< Derived >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const inline inherited
Definition at line 423 of file Potential.hpp.
Referenced by espressopp::vectorization::interaction::VerletListLennardJones::computeVirial(), and espressopp::vectorization::interaction::VerletListLennardJones::computeVirialTensor().
_computeForce() [2/3]
template<class Derived > bool espressopp::interaction::PotentialTemplate< Derived >::_computeForce (Real3D & force, const Real3D & dist) const inline inherited
Definition at line 438 of file Potential.hpp.
_computeForce() [3/3]
template<class Derived > bool espressopp::interaction::PotentialTemplate< Derived >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 431 of file Potential.hpp.
_computeForceRaw()
bool espressopp::vectorization::interaction::LennardJones::_computeForceRaw (Real3D & force, const Real3D & dist, real distSqr) const inline
Definition at line 120 of file LennardJones.hpp.
References ff2, and LOG4ESPP_DECL_LOGGER().
computeColVarWeights()
template<class Derived > void espressopp::interaction::PotentialTemplate< Derived >::computeColVarWeights (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Reimplemented in espressopp::interaction::TabulatedSubEns.
Definition at line 315 of file Potential.hpp.
computeEnergy() [1/3]
template<class Derived > real espressopp::interaction::PotentialTemplate< Derived >::computeEnergy (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Reimplemented in espressopp::interaction::LennardJonesAutoBonds.
Definition at line 323 of file Potential.hpp.
computeEnergy() [2/3]
template<class Derived > real espressopp::interaction::PotentialTemplate< Derived >::computeEnergy (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Reimplemented in espressopp::interaction::LennardJonesAutoBonds.
Definition at line 331 of file Potential.hpp.
computeEnergy() [3/3]
template<class Derived > real espressopp::interaction::PotentialTemplate< Derived >::computeEnergy (real dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Reimplemented in espressopp::interaction::LennardJonesAutoBonds.
Definition at line 338 of file Potential.hpp.
computeEnergySqr()
template<class Derived > real espressopp::interaction::PotentialTemplate< Derived >::computeEnergySqr (real distsqr) const inline virtual inherited
Implements espressopp::interaction::Potential.
Reimplemented in espressopp::interaction::LennardJonesAutoBonds.
Definition at line 345 of file Potential.hpp.
computeForce() [1/2]
template<class Derived > Real3D espressopp::interaction::PotentialTemplate< Derived >::computeForce (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Reimplemented in espressopp::interaction::LennardJonesAutoBonds.
Definition at line 405 of file Potential.hpp.
computeForce() [2/2]
template<class Derived > Real3D espressopp::interaction::PotentialTemplate< Derived >::computeForce (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Reimplemented in espressopp::interaction::LennardJonesAutoBonds.
Definition at line 413 of file Potential.hpp.
derived_this() [1/2]
template<class Derived> Derived* espressopp::interaction::PotentialTemplate< Derived >::derived_this () inline protected inherited
Definition at line 161 of file Potential.hpp.
derived_this() [2/2]
template<class Derived> const Derived* espressopp::interaction::PotentialTemplate< Derived >::derived_this () const inline protected inherited
Definition at line 165 of file Potential.hpp.
getColVar()
template<class Derived > RealND espressopp::interaction::PotentialTemplate< Derived >::getColVar () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 309 of file Potential.hpp.
getColVarAngleList()
template<class Derived > shared_ptr< FixedTripleList > espressopp::interaction::PotentialTemplate< Derived >::getColVarAngleList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 273 of file Potential.hpp.
getColVarBondList()
template<class Derived > shared_ptr< FixedPairList > espressopp::interaction::PotentialTemplate< Derived >::getColVarBondList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 259 of file Potential.hpp.
getColVarDihedList()
template<class Derived > shared_ptr< FixedQuadrupleList > espressopp::interaction::PotentialTemplate< Derived >::getColVarDihedList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 287 of file Potential.hpp.
getCutoff()
template<class Derived > real espressopp::interaction::PotentialTemplate< Derived >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::Potential.
Reimplemented in espressopp::interaction::CoulombKSpaceP3M.
Definition at line 210 of file Potential.hpp.
Referenced by espressopp::interaction::CoulombTruncatedUniqueCharge_pickle::getinitargs(), espressopp::interaction::SoftCosine_pickle::getinitargs(), espressopp::interaction::LennardJonesExpand_pickle::getinitargs(), espressopp::interaction::SmoothSquareWell_pickle::getinitargs(), espressopp::interaction::Tabulated_pickle::getinitargs(), espressopp::vectorization::interaction::LennardJones_pickle::getinitargs(), espressopp::interaction::LennardJonesGeneric_pickle::getinitargs(), espressopp::interaction::LennardJonesEnergyCapped_pickle::getinitargs(), espressopp::interaction::LennardJonesCapped_pickle::getinitargs(), espressopp::interaction::LennardJones_pickle::getinitargs(), espressopp::interaction::TabulatedSubEns_pickle::getinitargs(), espressopp::interaction::LennardJonesGromacs_pickle::getinitargs(), espressopp::interaction::ReactionFieldGeneralizedTI_pickle::getinitargs(), and espressopp::interaction::ReactionFieldGeneralized_pickle::getinitargs().
getCutoffSqr()
const real& espressopp::vectorization::interaction::LennardJones::getCutoffSqr () const inline
Definition at line 53 of file LennardJones.hpp.
References espressopp::interaction::PotentialTemplate< Derived >::cutoffSqr.
getEpsilon()
real espressopp::vectorization::interaction::LennardJones::getEpsilon () const inline
Definition at line 103 of file LennardJones.hpp.
References epsilon.
Referenced by espressopp::vectorization::interaction::LennardJones_pickle::getinitargs(), and registerPython().
getff1()
const real& espressopp::vectorization::interaction::LennardJones::getff1 () const inline
Definition at line 54 of file LennardJones.hpp.
References ff1.
getff2()
const real& espressopp::vectorization::interaction::LennardJones::getff2 () const inline
Definition at line 55 of file LennardJones.hpp.
References ff2, and registerPython().
getShift()
template<class Derived > real espressopp::interaction::PotentialTemplate< Derived >::getShift () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 225 of file Potential.hpp.
Referenced by espressopp::interaction::CoulombTruncatedUniqueCharge_pickle::getinitargs(), espressopp::interaction::SoftCosine_pickle::getinitargs(), espressopp::interaction::LennardJonesExpand_pickle::getinitargs(), espressopp::interaction::SmoothSquareWell_pickle::getinitargs(), espressopp::vectorization::interaction::LennardJones_pickle::getinitargs(), espressopp::interaction::LennardJonesGeneric_pickle::getinitargs(), espressopp::interaction::LennardJonesEnergyCapped_pickle::getinitargs(), espressopp::interaction::LennardJonesCapped_pickle::getinitargs(), espressopp::interaction::LennardJones_pickle::getinitargs(), espressopp::interaction::LennardJonesGromacs_pickle::getinitargs(), and espressopp::interaction::ReactionFieldGeneralized_pickle::getinitargs().
getSigma()
real espressopp::vectorization::interaction::LennardJones::getSigma () const inline
Definition at line 111 of file LennardJones.hpp.
References sigma.
Referenced by espressopp::vectorization::interaction::LennardJones_pickle::getinitargs(), and registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::vectorization::interaction::LennardJones::LOG4ESPP_DECL_LOGGER (theLogger) static
Referenced by _computeForceRaw().
preset()
void espressopp::vectorization::interaction::LennardJones::preset () inline
Definition at line 86 of file LennardJones.hpp.
References sigma.
Referenced by LennardJones(), setEpsilon(), and setSigma().
registerPython()
void espressopp::vectorization::interaction::LennardJones::registerPython () static
Definition at line 39 of file LennardJones.cpp.
References getEpsilon(), espressopp::vectorization::interaction::VerletListLennardJones::getPotentialPtr(), getSigma(), espressopp::vectorization::interaction::VerletListLennardJones::getVerletList(), setEpsilon(), espressopp::vectorization::interaction::VerletListLennardJones::setPotential(), and setSigma().
Referenced by getff2(), and espressopp::vectorization::interaction::registerPython().
setAutoShift()
template<class Derived > real espressopp::interaction::PotentialTemplate< Derived >::setAutoShift () inline virtual inherited
Implements espressopp::interaction::Potential.
Reimplemented in espressopp::interaction::LennardJonesAutoBonds.
Definition at line 231 of file Potential.hpp.
Referenced by LennardJones().
setColVar() [1/2]
template<class Derived > void espressopp::interaction::PotentialTemplate< Derived >::setColVar (const RealND & cv) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 294 of file Potential.hpp.
setColVar() [2/2]
template<class Derived > void espressopp::interaction::PotentialTemplate< Derived >::setColVar (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Reimplemented in espressopp::interaction::TabulatedSubEns.
Definition at line 301 of file Potential.hpp.
setColVarAngleList()
template<class Derived > void espressopp::interaction::PotentialTemplate< Derived >::setColVarAngleList (const shared_ptr< FixedTripleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 266 of file Potential.hpp.
setColVarBondList()
template<class Derived > void espressopp::interaction::PotentialTemplate< Derived >::setColVarBondList (const shared_ptr< FixedPairList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 252 of file Potential.hpp.
setColVarDihedList()
template<class Derived > void espressopp::interaction::PotentialTemplate< Derived >::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 280 of file Potential.hpp.
setCutoff()
template<class Derived > void espressopp::interaction::PotentialTemplate< Derived >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::Potential.
Reimplemented in espressopp::interaction::CoulombKSpaceP3M, espressopp::interaction::ReactionFieldGeneralized, espressopp::interaction::LennardJonesAutoBonds, and espressopp::interaction::ReactionFieldGeneralizedTI.
Definition at line 201 of file Potential.hpp.
Referenced by LennardJones().
setEpsilon()
void espressopp::vectorization::interaction::LennardJones::setEpsilon (real _epsilon) inline
Definition at line 96 of file LennardJones.hpp.
References LOG4ESPP_INFO, preset(), and espressopp::interaction::PotentialTemplate< Derived >::updateAutoShift().
Referenced by registerPython().
setShift()
template<class Derived > void espressopp::interaction::PotentialTemplate< Derived >::setShift (real _shift) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 216 of file Potential.hpp.
Referenced by LennardJones().
setSigma()
void espressopp::vectorization::interaction::LennardJones::setSigma (real _sigma) inline
Definition at line 105 of file LennardJones.hpp.
References LOG4ESPP_INFO, preset(), and espressopp::interaction::PotentialTemplate< Derived >::updateAutoShift().
Referenced by registerPython().
updateAutoShift()
template<class Derived > void espressopp::interaction::PotentialTemplate< Derived >::updateAutoShift () inline inherited
Definition at line 244 of file Potential.hpp.
Referenced by setEpsilon(), and setSigma().
Member Data Documentation
autoShift
template<class Derived> bool espressopp::interaction::PotentialTemplate< Derived >::autoShift protected inherited
Definition at line 151 of file Potential.hpp.
Referenced by LennardJones().
colVar
template<class Derived> RealND espressopp::interaction::PotentialTemplate< Derived >::colVar protected inherited
Definition at line 159 of file Potential.hpp.
colVarAngleList
template<class Derived> shared_ptr<FixedTripleList> espressopp::interaction::PotentialTemplate< Derived >::colVarAngleList protected inherited
Definition at line 155 of file Potential.hpp.
colVarBondList
template<class Derived> shared_ptr<FixedPairList> espressopp::interaction::PotentialTemplate< Derived >::colVarBondList protected inherited
Definition at line 153 of file Potential.hpp.
colVarDihedList
template<class Derived> shared_ptr<FixedQuadrupleList> espressopp::interaction::PotentialTemplate< Derived >::colVarDihedList protected inherited
Definition at line 157 of file Potential.hpp.
cutoff
template<class Derived> real espressopp::interaction::PotentialTemplate< Derived >::cutoff protected inherited
Definition at line 148 of file Potential.hpp.
cutoffSqr
template<class Derived> real espressopp::interaction::PotentialTemplate< Derived >::cutoffSqr protected inherited
Definition at line 149 of file Potential.hpp.
Referenced by getCutoffSqr().
ef1
real espressopp::vectorization::interaction::LennardJones::ef1 private
Definition at line 49 of file LennardJones.hpp.
ef2
real espressopp::vectorization::interaction::LennardJones::ef2 private
Definition at line 49 of file LennardJones.hpp.
epsilon
real espressopp::vectorization::interaction::LennardJones::epsilon private
Definition at line 46 of file LennardJones.hpp.
Referenced by getEpsilon().
ff1
real espressopp::vectorization::interaction::LennardJones::ff1 private
Definition at line 48 of file LennardJones.hpp.
Referenced by getff1().
ff2
real espressopp::vectorization::interaction::LennardJones::ff2 private
Definition at line 48 of file LennardJones.hpp.
Referenced by _computeForceRaw(), and getff2().
shift
template<class Derived> real espressopp::interaction::PotentialTemplate< Derived >::shift protected inherited
Definition at line 150 of file Potential.hpp.
sigma
real espressopp::vectorization::interaction::LennardJones::sigma private
Definition at line 47 of file LennardJones.hpp.
Referenced by getSigma(), and preset().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/vectorization/interaction/LennardJones.hpp
/home/espressopp/espressopp/src/vectorization/interaction/LennardJones.cpp