ESPResSo++: espressopp::integrator::LiquidGasLB Class Reference
espressopp::integrator::LiquidGasLB Class Reference
#include <LiquidGasLB.hpp>
Public Types
enum ExtensionType {
all = 0, Thermostat = 1, Barostat = 2, Constraint = 3,
Adress = 4, FreeEnergyCompensation = 5, ExtForce = 6, ExtAnalysis = 7,
Reaction = 8
}
Public Member Functions
LiquidGasLB (shared_ptr< System > _system, Int3D _Ni, real _a, real _tau, int _numDims, int _numVels)
~LiquidGasLB ()
void setNi (Int3D _Ni)
Int3D getNi ()
void setA (real _a)
real getA ()
void setTau (real _tau)
real getTau ()
void setGammaB (real _gamma_b)
real getGammaB ()
void setGammaS (real _gamma_s)
real getGammaS ()
void setGammaOdd (real _gamma_odd)
real getGammaOdd ()
void setGammaEven (real _gamma_even)
real getGammaEven ()
void setExtForceFlag (int _extForceFlag)
int getExtForceFlag ()
void setNumDims (int _numDims)
int getNumDims ()
void setNumVels (int _numVels)
int getNumVels ()
void setStepNum (int _step)
int getStepNum ()
void setNBins (int _nBins)
int getNBins ()
void setDistr (int _i, real _distr)
real getDistr (int _i)
void incDistr (int _i)
void setLBTemp (real _lbTemp)
real getLBTemp ()
void setLBTempFlag (int _lbTempFlag)
int getLBTempFlag ()
void setEqWeight (int _l, real _value)
real getEqWeight (int _l)
void setCi (int _l, Real3D _vec)
Real3D getCi (int _l)
void setCs2 (real _cs2)
real getCs2 ()
void setInvBi (int _l, real _value)
real getInvBi (int _l)
void setPhi (int _l, real _value)
real getPhi (int _l)
void setLBFluid (Int3D _Ni, int _l, real _value)
real getLBFluid (Int3D _Ni, int _l)
void setForceLoc (Int3D _Ni, Real3D _extForceLoc)
Real3D getForceLoc (Int3D _Ni)
void setGhostFluid (Int3D _Ni, int _l, real _value)
void initLatticeModel ()
void initGammas (int _idGamma)
void initFluctuations ()
void makeLBStep ()
void addPolyLBForces ()
void collideStream ()
void streaming (int _i, int _j, int _k)
void computeDensity (int _i, int _j, int _k, int _numVels, int _step)
void computeMomentum (int _i, int _j, int _k, int _numVels)
ExtensionType getType ()
void setType (ExtensionType k)
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
Register this class so it can be used from Python.
Public Attributes
ExtensionType type
Protected Member Functions
void setIntegrator (shared_ptr< MDIntegrator > _integrator)
Protected Attributes
shared_ptr< MDIntegrator > integrator
Private Member Functions
void connect ()
void disconnect ()
Static Private Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Private Attributes
int numDims
int numVels
real cs2
real invCs2
real a
real tau
real gamma_b
real gamma_s
real gamma_odd
real gamma_even
real lbTemp
int lbTempFlag
int stepNum
std::vector< real > eqWeight
std::vector< Real3D > c_i
std::vector< real > inv_b_i
std::vector< real > phi
int extForceFlag
Int3D Ni
int idX
int idY
int idZ
int index
std::vector< std::vector
< std::vector< LGSite > > > lbfluid
std::vector< std::vector
< std::vector< GhostLatticeLG > > > ghostlat
int nBins
std::vector< real > distr
shared_ptr< esutil::RNG > rng
random number generator used for fluctuations
boost::signals2::connection _befIntP
boost::signals2::connection _befIntV
Detailed Description
Definition at line 25 of file LiquidGasLB.hpp.
Member Enumeration Documentation
enum espressopp::integrator::Extension::ExtensionType [inherited]
Enumerator:
all
Thermostat
Barostat
Constraint
Adress
FreeEnergyCompensation
ExtForce
ExtAnalysis
Reaction
Definition at line 48 of file Extension.hpp.
Constructor & Destructor Documentation
espressopp::integrator::LiquidGasLB::LiquidGasLB (shared_ptr< System > _system, Int3D _Ni, real _a, real _tau, int _numDims, int _numVels)
Definition at line 27 of file LiquidGasLB.cpp.
References c_i, distr, eqWeight, getA(), espressopp::Int3D::getItem(), getNBins(), getNi(), getNumVels(), getTau(), ghostlat, initLatticeModel(), inv_b_i, lbfluid, phi, rng, setCs2(), setExtForceFlag(), setLBTempFlag(), and setNBins().
espressopp::integrator::LiquidGasLB::~LiquidGasLB ()
Definition at line 516 of file LiquidGasLB.cpp.
Member Function Documentation
void espressopp::integrator::LiquidGasLB::addPolyLBForces ()
Definition at line 512 of file LiquidGasLB.cpp.
Referenced by connect().
void espressopp::integrator::LiquidGasLB::collideStream ()
Definition at line 378 of file LiquidGasLB.cpp.
References computeDensity(), getExtForceFlag(), espressopp::Int3D::getItem(), getLBTempFlag(), getNi(), getNumVels(), getStepNum(), ghostlat, lbfluid, numVels, and streaming().
Referenced by makeLBStep().
void espressopp::integrator::LiquidGasLB::computeDensity (int _i, int _j, int _k, int _numVels, int _step)
Definition at line 475 of file LiquidGasLB.cpp.
References distr, getCi(), espressopp::Int3D::getItem(), espressopp::Real3D::getItem(), getNBins(), getNi(), getStepNum(), and lbfluid.
Referenced by collideStream().
void espressopp::integrator::LiquidGasLB::computeMomentum (int _i, int _j, int _k, int _numVels)
void espressopp::integrator::LiquidGasLB::connect () [private, virtual]
Implements espressopp::integrator::Extension.
Definition at line 109 of file LiquidGasLB.cpp.
References _befIntP, _befIntV, addPolyLBForces(), espressopp::integrator::Extension::integrator, and makeLBStep().
Referenced by registerPython().
void espressopp::integrator::LiquidGasLB::disconnect () [private, virtual]
Implements espressopp::integrator::Extension.
Definition at line 104 of file LiquidGasLB.cpp.
References _befIntP, and _befIntV.
Referenced by registerPython().
real espressopp::integrator::LiquidGasLB::getA ()
Definition at line 123 of file LiquidGasLB.cpp.
References a.
Referenced by initFluctuations(), LiquidGasLB(), and registerPython().
Real3D espressopp::integrator::LiquidGasLB::getCi (int _l)
Definition at line 157 of file LiquidGasLB.cpp.
References c_i.
Referenced by computeDensity(), and initLatticeModel().
real espressopp::integrator::LiquidGasLB::getCs2 ()
Definition at line 160 of file LiquidGasLB.cpp.
References cs2.
Referenced by initFluctuations(), and initLatticeModel().
real espressopp::integrator::LiquidGasLB::getDistr (int _i)
Definition at line 144 of file LiquidGasLB.cpp.
References distr.
real espressopp::integrator::LiquidGasLB::getEqWeight (int _l)
Definition at line 154 of file LiquidGasLB.cpp.
References eqWeight.
Referenced by initLatticeModel().
int espressopp::integrator::LiquidGasLB::getExtForceFlag ()
Definition at line 181 of file LiquidGasLB.cpp.
References extForceFlag.
Referenced by collideStream().
Real3D espressopp::integrator::LiquidGasLB::getForceLoc (Int3D _Ni)
Definition at line 194 of file LiquidGasLB.cpp.
References espressopp::Int3D::getItem(), and lbfluid.
real espressopp::integrator::LiquidGasLB::getGammaB ()
Definition at line 169 of file LiquidGasLB.cpp.
References gamma_b.
Referenced by initFluctuations(), initGammas(), and registerPython().
real espressopp::integrator::LiquidGasLB::getGammaEven ()
Definition at line 178 of file LiquidGasLB.cpp.
References gamma_even.
Referenced by initGammas(), and registerPython().
real espressopp::integrator::LiquidGasLB::getGammaOdd ()
Definition at line 175 of file LiquidGasLB.cpp.
References gamma_odd.
Referenced by initGammas(), and registerPython().
real espressopp::integrator::LiquidGasLB::getGammaS ()
Definition at line 172 of file LiquidGasLB.cpp.
References gamma_s.
Referenced by initFluctuations(), initGammas(), and registerPython().
real espressopp::integrator::LiquidGasLB::getInvBi (int _l)
Definition at line 163 of file LiquidGasLB.cpp.
References inv_b_i.
Referenced by initFluctuations(), and initLatticeModel().
real espressopp::integrator::LiquidGasLB::getLBFluid (Int3D _Ni, int _l)
Definition at line 186 of file LiquidGasLB.cpp.
References espressopp::Int3D::getItem(), and lbfluid.
real espressopp::integrator::LiquidGasLB::getLBTemp ()
Definition at line 148 of file LiquidGasLB.cpp.
References lbTemp.
Referenced by initFluctuations(), and registerPython().
int espressopp::integrator::LiquidGasLB::getLBTempFlag ()
Definition at line 151 of file LiquidGasLB.cpp.
References lbTempFlag.
Referenced by collideStream().
int espressopp::integrator::LiquidGasLB::getNBins ()
Definition at line 141 of file LiquidGasLB.cpp.
References nBins.
Referenced by computeDensity(), and LiquidGasLB().
Int3D espressopp::integrator::LiquidGasLB::getNi ()
Definition at line 119 of file LiquidGasLB.cpp.
References Ni.
Referenced by collideStream(), computeDensity(), initFluctuations(), initGammas(), initLatticeModel(), LiquidGasLB(), registerPython(), and streaming().
int espressopp::integrator::LiquidGasLB::getNumDims ()
Definition at line 135 of file LiquidGasLB.cpp.
References numDims.
Referenced by registerPython().
int espressopp::integrator::LiquidGasLB::getNumVels ()
Definition at line 131 of file LiquidGasLB.cpp.
References numVels.
Referenced by collideStream(), initFluctuations(), initGammas(), initLatticeModel(), LiquidGasLB(), registerPython(), and streaming().
real espressopp::integrator::LiquidGasLB::getPhi (int _l)
Definition at line 166 of file LiquidGasLB.cpp.
References phi.
Referenced by initFluctuations().
int espressopp::integrator::LiquidGasLB::getStepNum ()
Definition at line 138 of file LiquidGasLB.cpp.
References stepNum.
Referenced by collideStream(), and computeDensity().
shared_ptr< System > espressopp::SystemAccess::getSystem () const [inline, inherited]
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::LatticeBoltzmann::initGammas(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readCouplForces(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::VerletListTriple::registerPython(), espressopp::VerletList::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveCouplForces(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::analysis::LBOutputScreen::writeOutput(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const [inline, inherited]
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const [inline, inherited]
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
System& espressopp::SystemAccess::getSystemRef () const [inline, inherited]
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readCouplForces(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::LatticeBoltzmann::restoreLBForces(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::LatticeBoltzmann::saveCouplForces(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
System& espressopp::SystemAccess::getSystemRef1 () const [inline, inherited]
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
System& espressopp::SystemAccess::getSystemRef2 () const [inline, inherited]
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
real espressopp::integrator::LiquidGasLB::getTau ()
Definition at line 127 of file LiquidGasLB.cpp.
References tau.
Referenced by LiquidGasLB(), and registerPython().
ExtensionType espressopp::integrator::Extension::getType () [inline, inherited]
Definition at line 67 of file Extension.hpp.
References espressopp::integrator::Extension::type.
Referenced by espressopp::integrator::Extension::registerPython().
void espressopp::integrator::LiquidGasLB::incDistr (int _i)
Definition at line 145 of file LiquidGasLB.cpp.
References distr.
void espressopp::integrator::LiquidGasLB::initFluctuations ()
Definition at line 316 of file LiquidGasLB.cpp.
References getA(), getCs2(), getGammaB(), getGammaS(), getInvBi(), espressopp::Int3D::getItem(), getLBTemp(), getNi(), getNumVels(), getPhi(), lbfluid, setLBTempFlag(), and setPhi().
Referenced by setLBTemp().
void espressopp::integrator::LiquidGasLB::initGammas (int _idGamma)
Definition at line 288 of file LiquidGasLB.cpp.
References getGammaB(), getGammaEven(), getGammaOdd(), getGammaS(), espressopp::Int3D::getItem(), getNi(), getNumVels(), and lbfluid.
Referenced by setGammaB(), setGammaEven(), setGammaOdd(), and setGammaS().
void espressopp::integrator::LiquidGasLB::initLatticeModel ()
Definition at line 203 of file LiquidGasLB.cpp.
References getCi(), getCs2(), getEqWeight(), getInvBi(), espressopp::Int3D::getItem(), espressopp::Real3D::getItem(), getNi(), getNumVels(), ghostlat, lbfluid, setCi(), setEqWeight(), and setInvBi().
Referenced by LiquidGasLB().
static espressopp::integrator::LiquidGasLB::LOG4ESPP_DECL_LOGGER (theLogger) [static, private]
Logger.
Reimplemented from espressopp::integrator::Extension.
void espressopp::integrator::LiquidGasLB::makeLBStep ()
Definition at line 370 of file LiquidGasLB.cpp.
References collideStream(), espressopp::integrator::Extension::integrator, and setStepNum().
Referenced by connect().
void espressopp::integrator::LiquidGasLB::registerPython () [static]
Register this class so it can be used from Python.
Reimplemented from espressopp::integrator::Extension.
Definition at line 523 of file LiquidGasLB.cpp.
References connect(), disconnect(), getA(), getGammaB(), getGammaEven(), getGammaOdd(), getGammaS(), getLBTemp(), getNi(), getNumDims(), getNumVels(), getTau(), setA(), setGammaB(), setGammaEven(), setGammaOdd(), setGammaS(), setLBTemp(), setNi(), setNumDims(), setNumVels(), and setTau().
Referenced by espressopp::integrator::registerPython().
void espressopp::integrator::LiquidGasLB::setA (real _a)
Definition at line 121 of file LiquidGasLB.cpp.
References a.
Referenced by registerPython().
void espressopp::integrator::LiquidGasLB::setCi (int _l, Real3D _vec)
Definition at line 156 of file LiquidGasLB.cpp.
References c_i.
Referenced by initLatticeModel().
void espressopp::integrator::LiquidGasLB::setCs2 (real _cs2)
Definition at line 159 of file LiquidGasLB.cpp.
References cs2.
Referenced by LiquidGasLB().
void espressopp::integrator::LiquidGasLB::setDistr (int _i, real _distr)
Definition at line 143 of file LiquidGasLB.cpp.
References distr.
void espressopp::integrator::LiquidGasLB::setEqWeight (int _l, real _value)
Definition at line 153 of file LiquidGasLB.cpp.
References eqWeight.
Referenced by initLatticeModel().
void espressopp::integrator::LiquidGasLB::setExtForceFlag (int _extForceFlag)
Definition at line 180 of file LiquidGasLB.cpp.
References extForceFlag.
Referenced by LiquidGasLB().
void espressopp::integrator::LiquidGasLB::setForceLoc (Int3D _Ni, Real3D _extForceLoc)
Definition at line 190 of file LiquidGasLB.cpp.
References espressopp::Int3D::getItem(), and lbfluid.
void espressopp::integrator::LiquidGasLB::setGammaB (real _gamma_b)
Definition at line 168 of file LiquidGasLB.cpp.
References gamma_b, and initGammas().
Referenced by registerPython().
void espressopp::integrator::LiquidGasLB::setGammaEven (real _gamma_even)
Definition at line 177 of file LiquidGasLB.cpp.
References gamma_even, and initGammas().
Referenced by registerPython().
void espressopp::integrator::LiquidGasLB::setGammaOdd (real _gamma_odd)
Definition at line 174 of file LiquidGasLB.cpp.
References gamma_odd, and initGammas().
Referenced by registerPython().
void espressopp::integrator::LiquidGasLB::setGammaS (real _gamma_s)
Definition at line 171 of file LiquidGasLB.cpp.
References gamma_s, and initGammas().
Referenced by registerPython().
void espressopp::integrator::LiquidGasLB::setGhostFluid (Int3D _Ni, int _l, real _value)
Definition at line 198 of file LiquidGasLB.cpp.
References espressopp::Int3D::getItem(), and ghostlat.
void espressopp::integrator::Extension::setIntegrator (shared_ptr< MDIntegrator > _integrator) [protected, inherited]
Definition at line 49 of file Extension.cpp.
References espressopp::integrator::Extension::integrator.
Referenced by espressopp::integrator::Extension::registerPython().
void espressopp::integrator::LiquidGasLB::setInvBi (int _l, real _value)
Definition at line 162 of file LiquidGasLB.cpp.
References inv_b_i.
Referenced by initLatticeModel().
void espressopp::integrator::LiquidGasLB::setLBFluid (Int3D _Ni, int _l, real _value)
Definition at line 183 of file LiquidGasLB.cpp.
References espressopp::Int3D::getItem(), and lbfluid.
void espressopp::integrator::LiquidGasLB::setLBTemp (real _lbTemp)
Definition at line 147 of file LiquidGasLB.cpp.
References initFluctuations(), and lbTemp.
Referenced by registerPython().
void espressopp::integrator::LiquidGasLB::setLBTempFlag (int _lbTempFlag)
Definition at line 150 of file LiquidGasLB.cpp.
References lbTempFlag.
Referenced by initFluctuations(), and LiquidGasLB().
void espressopp::integrator::LiquidGasLB::setNBins (int _nBins)
Definition at line 140 of file LiquidGasLB.cpp.
References nBins.
Referenced by LiquidGasLB().
void espressopp::integrator::LiquidGasLB::setNi (Int3D _Ni)
Definition at line 118 of file LiquidGasLB.cpp.
References Ni.
Referenced by registerPython().
void espressopp::integrator::LiquidGasLB::setNumDims (int _numDims)
Definition at line 133 of file LiquidGasLB.cpp.
References numDims.
Referenced by registerPython().
void espressopp::integrator::LiquidGasLB::setNumVels (int _numVels)
Definition at line 129 of file LiquidGasLB.cpp.
References numVels.
Referenced by registerPython().
void espressopp::integrator::LiquidGasLB::setPhi (int _l, real _value)
Definition at line 165 of file LiquidGasLB.cpp.
References phi.
Referenced by initFluctuations().
void espressopp::integrator::LiquidGasLB::setStepNum (int _step)
Definition at line 137 of file LiquidGasLB.cpp.
References stepNum.
Referenced by makeLBStep().
void espressopp::integrator::LiquidGasLB::setTau (real _tau)
Definition at line 125 of file LiquidGasLB.cpp.
References tau.
Referenced by registerPython().
void espressopp::integrator::Extension::setType (ExtensionType k) [inline, inherited]
Definition at line 68 of file Extension.hpp.
References espressopp::integrator::Extension::type.
Referenced by espressopp::integrator::Extension::registerPython().
void espressopp::integrator::LiquidGasLB::streaming (int _i, int _j, int _k)
Definition at line 424 of file LiquidGasLB.cpp.
References espressopp::Int3D::getItem(), getNi(), getNumVels(), ghostlat, and lbfluid.
Referenced by collideStream().
Member Data Documentation
boost::signals2::connection espressopp::integrator::LiquidGasLB::_befIntP [private]
Definition at line 173 of file LiquidGasLB.hpp.
Referenced by connect(), and disconnect().
boost::signals2::connection espressopp::integrator::LiquidGasLB::_befIntV [private]
Definition at line 173 of file LiquidGasLB.hpp.
Referenced by connect(), and disconnect().
real espressopp::integrator::LiquidGasLB::a [private]
Definition at line 145 of file LiquidGasLB.hpp.
Referenced by getA(), and setA().
std::vector<Real3D> espressopp::integrator::LiquidGasLB::c_i [private]
Definition at line 155 of file LiquidGasLB.hpp.
Referenced by getCi(), LiquidGasLB(), and setCi().
real espressopp::integrator::LiquidGasLB::cs2 [private]
Definition at line 143 of file LiquidGasLB.hpp.
Referenced by getCs2(), and setCs2().
std::vector<real> espressopp::integrator::LiquidGasLB::distr [private]
Definition at line 169 of file LiquidGasLB.hpp.
Referenced by computeDensity(), getDistr(), incDistr(), LiquidGasLB(), and setDistr().
std::vector<real> espressopp::integrator::LiquidGasLB::eqWeight [private]
Definition at line 154 of file LiquidGasLB.hpp.
Referenced by getEqWeight(), LiquidGasLB(), and setEqWeight().
int espressopp::integrator::LiquidGasLB::extForceFlag [private]
Definition at line 158 of file LiquidGasLB.hpp.
Referenced by getExtForceFlag(), and setExtForceFlag().
real espressopp::integrator::LiquidGasLB::gamma_b [private]
Definition at line 147 of file LiquidGasLB.hpp.
Referenced by getGammaB(), and setGammaB().
real espressopp::integrator::LiquidGasLB::gamma_even [private]
Definition at line 150 of file LiquidGasLB.hpp.
Referenced by getGammaEven(), and setGammaEven().
real espressopp::integrator::LiquidGasLB::gamma_odd [private]
Definition at line 149 of file LiquidGasLB.hpp.
Referenced by getGammaOdd(), and setGammaOdd().
real espressopp::integrator::LiquidGasLB::gamma_s [private]
Definition at line 148 of file LiquidGasLB.hpp.
Referenced by getGammaS(), and setGammaS().
std::vector< std::vector< std::vector<GhostLatticeLG> > > espressopp::integrator::LiquidGasLB::ghostlat [private]
Definition at line 166 of file LiquidGasLB.hpp.
Referenced by collideStream(), initLatticeModel(), LiquidGasLB(), setGhostFluid(), and streaming().
int espressopp::integrator::LiquidGasLB::idX [private]
Definition at line 160 of file LiquidGasLB.hpp.
int espressopp::integrator::LiquidGasLB::idY [private]
Definition at line 160 of file LiquidGasLB.hpp.
int espressopp::integrator::LiquidGasLB::idZ [private]
Definition at line 160 of file LiquidGasLB.hpp.
int espressopp::integrator::LiquidGasLB::index [private]
Definition at line 160 of file LiquidGasLB.hpp.
shared_ptr<MDIntegrator> espressopp::integrator::Extension::integrator [protected, inherited]
Definition at line 72 of file Extension.hpp.
Referenced by espressopp::integrator::LatticeBoltzmann::calcRandForce(), espressopp::integrator::ExtAnalyze::connect(), espressopp::integrator::VelocityVerletOnRadius::connect(), espressopp::integrator::BerendsenBarostatAnisotropic::connect(), espressopp::integrator::BerendsenBarostat::connect(), espressopp::integrator::FreeEnergyCompensation::connect(), espressopp::integrator::FixPositions::connect(), espressopp::integrator::Isokinetic::connect(), espressopp::integrator::ExtForce::connect(), espressopp::integrator::BerendsenThermostat::connect(), espressopp::integrator::TDforce::connect(), espressopp::integrator::Settle::connect(), espressopp::integrator::Adress::connect(), espressopp::integrator::CapForce::connect(), espressopp::integrator::OnTheFlyFEC::connect(), espressopp::integrator::DPDThermostat::connect(), espressopp::integrator::LangevinThermostat::connect(), espressopp::integrator::GeneralizedLangevinThermostat::connect(), espressopp::integrator::LangevinThermostat1D::connect(), espressopp::integrator::LangevinThermostatHybrid::connect(), espressopp::integrator::LangevinBarostat::connect(), espressopp::integrator::AssociationReaction::connect(), espressopp::integrator::StochasticVelocityRescaling::connect(), connect(), espressopp::integrator::LatticeBoltzmann::connect(), espressopp::integrator::LatticeBoltzmann::convTimeMDtoLB(), espressopp::integrator::LangevinThermostat::initialize(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinThermostat1D::initialize(), espressopp::integrator::BerendsenThermostat::initialize(), espressopp::integrator::LangevinThermostatHybrid::initialize(), espressopp::integrator::BerendsenBarostatAnisotropic::initialize(), espressopp::integrator::BerendsenBarostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::Adress::integrate2(), makeLBStep(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::saveCouplForces(), espressopp::integrator::Extension::setIntegrator(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
std::vector<real> espressopp::integrator::LiquidGasLB::inv_b_i [private]
Definition at line 156 of file LiquidGasLB.hpp.
Referenced by getInvBi(), LiquidGasLB(), and setInvBi().
real espressopp::integrator::LiquidGasLB::invCs2 [private]
Definition at line 144 of file LiquidGasLB.hpp.
std::vector< std::vector< std::vector<LGSite> > > espressopp::integrator::LiquidGasLB::lbfluid [private]
Definition at line 165 of file LiquidGasLB.hpp.
Referenced by collideStream(), computeDensity(), getForceLoc(), getLBFluid(), initFluctuations(), initGammas(), initLatticeModel(), LiquidGasLB(), setForceLoc(), setLBFluid(), and streaming().
real espressopp::integrator::LiquidGasLB::lbTemp [private]
Definition at line 151 of file LiquidGasLB.hpp.
Referenced by getLBTemp(), and setLBTemp().
int espressopp::integrator::LiquidGasLB::lbTempFlag [private]
Definition at line 152 of file LiquidGasLB.hpp.
Referenced by getLBTempFlag(), and setLBTempFlag().
int espressopp::integrator::LiquidGasLB::nBins [private]
Definition at line 168 of file LiquidGasLB.hpp.
Referenced by getNBins(), and setNBins().
Int3D espressopp::integrator::LiquidGasLB::Ni [private]
Definition at line 159 of file LiquidGasLB.hpp.
Referenced by getNi(), and setNi().
int espressopp::integrator::LiquidGasLB::numDims [private]
Definition at line 141 of file LiquidGasLB.hpp.
Referenced by getNumDims(), and setNumDims().
int espressopp::integrator::LiquidGasLB::numVels [private]
Definition at line 142 of file LiquidGasLB.hpp.
Referenced by collideStream(), getNumVels(), and setNumVels().
std::vector<real> espressopp::integrator::LiquidGasLB::phi [private]
Definition at line 157 of file LiquidGasLB.hpp.
Referenced by getPhi(), LiquidGasLB(), and setPhi().
shared_ptr< esutil::RNG > espressopp::integrator::LiquidGasLB::rng [private]
random number generator used for fluctuations
Definition at line 171 of file LiquidGasLB.hpp.
Referenced by LiquidGasLB().
int espressopp::integrator::LiquidGasLB::stepNum [private]
Definition at line 153 of file LiquidGasLB.hpp.
Referenced by getStepNum(), and setStepNum().
real espressopp::integrator::LiquidGasLB::tau [private]
Definition at line 146 of file LiquidGasLB.hpp.
Referenced by getTau(), and setTau().
ExtensionType espressopp::integrator::Extension::type [inherited]
Definition at line 62 of file Extension.hpp.
Referenced by espressopp::integrator::Adress::Adress(), espressopp::integrator::AssociationReaction::AssociationReaction(), espressopp::integrator::BerendsenBarostat::BerendsenBarostat(), espressopp::integrator::BerendsenBarostatAnisotropic::BerendsenBarostatAnisotropic(), espressopp::integrator::BerendsenThermostat::BerendsenThermostat(), espressopp::integrator::DPDThermostat::DPDThermostat(), espressopp::integrator::ExtAnalyze::ExtAnalyze(), espressopp::integrator::FreeEnergyCompensation::FreeEnergyCompensation(), espressopp::integrator::GeneralizedLangevinThermostat::GeneralizedLangevinThermostat(), espressopp::integrator::Extension::getType(), espressopp::integrator::LangevinBarostat::LangevinBarostat(), espressopp::integrator::LangevinThermostat::LangevinThermostat(), espressopp::integrator::LangevinThermostat1D::LangevinThermostat1D(), espressopp::integrator::LangevinThermostatHybrid::LangevinThermostatHybrid(), espressopp::integrator::OnTheFlyFEC::OnTheFlyFEC(), espressopp::integrator::TDforce::registerPython(), espressopp::integrator::Extension::setType(), espressopp::integrator::StochasticVelocityRescaling::StochasticVelocityRescaling(), and espressopp::integrator::TDforce::TDforce().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/integrator/LiquidGasLB.hpp
/home/travis/build/espressopp/espressopp/src/integrator/LiquidGasLB.cpp