ESPResSo++: espressopp::integrator::VelocityVerletOnGroup Class Reference
espressopp::integrator::VelocityVerletOnGroup Class Reference
Velocity Verlet Integrator.
#include <VelocityVerletOnGroup.hpp>
Public Member Functions
VelocityVerletOnGroup (shared_ptr< class espressopp::System > system, shared_ptr< class espressopp::ParticleGroup > group_)
virtual ~VelocityVerletOnGroup ()
void setLangevin (shared_ptr< class LangevinThermostat > langevin)
shared_ptr< class LangevinThermostat > getLangevin ()
void run (int nsteps)
This method runs the integration for a certain number of steps.
void setTimeStep (real dt)
Setter routine for the timestep.
real getTimeStep ()
Getter routine for the timestep.
void setStep (long long step_)
Getter routine for integration step.
long long getStep ()
Getter routine for integration step.
void addExtension (shared_ptr< integrator::Extension > extension)
shared_ptr< integrator::Extension > getExtension (int k)
int getNumberOfExtensions ()
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
Register this class so it can be used from Python.
Public Attributes
boost::signals2::signal< void()> runInit
boost::signals2::signal< void()> recalc1
boost::signals2::signal< void()> aftCalcSlow
boost::signals2::signal< void()> recalc2
boost::signals2::signal< void()> befIntP
boost::signals2::signal< void(real &)> inIntP
boost::signals2::signal< void()> aftIntP
boost::signals2::signal< void()> aftInitF
boost::signals2::signal< void()> aftCalcF
boost::signals2::signal< void()> befIntV
boost::signals2::signal< void()> aftIntV
boost::signals2::signal< void()> aftIntSlow
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Protected Attributes
bool timeFlag
ExtensionList exList
long long step
Integration step.
real dt
Timestep used for integration.
Private Member Functions
real integrate1 ()
Method updates particle positions and velocities.
void integrate2 ()
void initForces ()
void updateForces ()
void calcForces ()
void printPositions (bool withGhost)
void printForces (bool withGhost)
void setUp ()
void resetTimers ()
void printTimers ()
Private Attributes
bool resortFlag
true implies need for resort of particles
real maxDist
real maxCut
shared_ptr< class LangevinThermostat > langevin
Langevin thermostat if available.
shared_ptr< class espressopp::ParticleGroup > group
esutil::WallTimer timeIntegrate
used for timing
real timeResort
real timeForce
real timeForceComp [100]
real timeComm1
real timeComm2
real timeInt1
real timeInt2
Detailed Description
Velocity Verlet Integrator.
Definition at line 38 of file VelocityVerletOnGroup.hpp.
Constructor & Destructor Documentation
VelocityVerletOnGroup()
espressopp::integrator::VelocityVerletOnGroup::VelocityVerletOnGroup (shared_ptr< class espressopp::System > system, shared_ptr< class espressopp::ParticleGroup > group_)
Definition at line 43 of file VelocityVerletOnGroup.cpp.
References LOG4ESPP_INFO, maxDist, and resortFlag.
~VelocityVerletOnGroup()
espressopp::integrator::VelocityVerletOnGroup::~VelocityVerletOnGroup () virtual
Definition at line 54 of file VelocityVerletOnGroup.cpp.
References LOG4ESPP_INFO.
Member Function Documentation
addExtension()
void espressopp::integrator::MDIntegrator::addExtension (shared_ptr< integrator::Extension > extension) inherited
Definition at line 68 of file MDIntegrator.cpp.
References espressopp::integrator::MDIntegrator::exList.
Referenced by espressopp::integrator::MDIntegrator::registerPython().
calcForces()
void espressopp::integrator::VelocityVerletOnGroup::calcForces () private
Definition at line 278 of file VelocityVerletOnGroup.cpp.
References espressopp::esutil::Timer::getElapsedTime(), espressopp::SystemAccess::getSystemRef(), initForces(), LOG4ESPP_INFO, espressopp::System::shortRangeInteractions, timeForceComp, and timeIntegrate.
Referenced by updateForces().
getExtension()
shared_ptr< integrator::Extension > espressopp::integrator::MDIntegrator::getExtension (int k) inherited
Definition at line 92 of file MDIntegrator.cpp.
References espressopp::integrator::MDIntegrator::exList.
Referenced by espressopp::integrator::MDIntegrator::registerPython().
getLangevin()
shared_ptr<class LangevinThermostat> espressopp::integrator::VelocityVerletOnGroup::getLangevin () inline
Definition at line 48 of file VelocityVerletOnGroup.hpp.
References langevin, registerPython(), and run().
Referenced by registerPython().
getNumberOfExtensions()
int espressopp::integrator::MDIntegrator::getNumberOfExtensions () inherited
Definition at line 88 of file MDIntegrator.cpp.
References espressopp::integrator::MDIntegrator::exList.
Referenced by espressopp::integrator::MDIntegrator::registerPython().
getStep()
long long espressopp::integrator::MDIntegrator::getStep () inline inherited
Getter routine for integration step.
Definition at line 73 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::MDIntegrator::registerPython().
getSystem()
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::LatticeBoltzmann::assignMyLattice(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::PIAdressIntegrator::computeKineticEnergy(), espressopp::integrator::PIAdressIntegrator::computeMomentumDrift(), espressopp::integrator::PIAdressIntegrator::computePositionDrift(), espressopp::integrator::PIAdressIntegrator::computeRingEnergy(), espressopp::integrator::PIAdressIntegrator::computeRingEnergyRaw(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpXTCAdress::dump(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::io::DumpXYZ::DumpXYZ(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::VerletListTriple::registerPython(), espressopp::VerletList::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
getSystem1()
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
getSystem2()
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
getSystemRef()
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::addForces(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::addForces(), espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerletRESPA::calcForces(), espressopp::integrator::VelocityVerlet::calcForces(), calcForces(), espressopp::integrator::PIAdressIntegrator::calcForcesF(), espressopp::integrator::PIAdressIntegrator::calcForcesM(), espressopp::integrator::PIAdressIntegrator::calcForcesS(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeCOM(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeEnergy(), espressopp::integrator::PIAdressIntegrator::computeKineticEnergy(), espressopp::integrator::PIAdressIntegrator::computeMomentumDrift(), espressopp::integrator::PIAdressIntegrator::computePositionDrift(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::integrator::PIAdressIntegrator::computeRingEnergy(), espressopp::integrator::PIAdressIntegrator::computeRingEnergyRaw(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::PIAdressIntegrator::distributeForces(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::FixedLocalTupleComListInteractionTemplate(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::VelocityVerletRESPA::initForces(), espressopp::integrator::VelocityVerlet::initForces(), espressopp::integrator::Adress::initForces(), initForces(), espressopp::integrator::PIAdressIntegrator::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::PIAdressIntegrator::initializeSetup(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::VelocityVerletRESPA::integrate1(), espressopp::integrator::VelocityVerlet::integrate1(), espressopp::integrator::Adress::integrate1(), integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::VelocityVerletRESPA::integrate2(), espressopp::integrator::VelocityVerlet::integrate2(), integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::PIAdressIntegrator::integrateModePos(), espressopp::integrator::Adress::integrateSlow(), espressopp::integrator::PIAdressIntegrator::integrateV1(), espressopp::integrator::PIAdressIntegrator::integrateV2(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::PIAdressIntegrator::OUintegrate(), espressopp::integrator::VelocityVerlet::printForces(), printForces(), espressopp::integrator::VelocityVerlet::printPositions(), printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::PIAdressIntegrator::run(), espressopp::integrator::VelocityVerletRESPA::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::MinimizeEnergy::run(), run(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::Rattle::saveOldPos(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), setUp(), espressopp::integrator::PIAdressIntegrator::setWeights(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostatOnGroup::thermalize(), espressopp::integrator::LangevinThermostatOnRadius::thermalize(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::integrator::PIAdressIntegrator::transForces(), espressopp::integrator::PIAdressIntegrator::transMom1(), espressopp::integrator::PIAdressIntegrator::transMom2(), espressopp::integrator::PIAdressIntegrator::transPos1(), espressopp::integrator::PIAdressIntegrator::transPos2(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::io::DumpH5MD::update(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::VelocityVerletRESPA::updateForces(), espressopp::integrator::VelocityVerlet::updateForces(), updateForces(), espressopp::integrator::PIAdressIntegrator::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
getSystemRef1()
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
getSystemRef2()
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
getTimeStep()
real espressopp::integrator::MDIntegrator::getTimeStep () inline inherited
Getter routine for the timestep.
Definition at line 67 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::MDIntegrator::registerPython().
initForces()
void espressopp::integrator::VelocityVerletOnGroup::initForces () private
Definition at line 322 of file VelocityVerletOnGroup.cpp.
References espressopp::SystemAccess::getSystemRef(), espressopp::iterator::CellListIterator::isDone(), LOG4ESPP_INFO, and espressopp::System::storage.
Referenced by calcForces().
integrate1()
real espressopp::integrator::VelocityVerletOnGroup::integrate1 () private
Method updates particle positions and velocities.
Returns
maximal square distance a particle has moved.
Definition at line 184 of file VelocityVerletOnGroup.cpp.
References espressopp::System::comm, espressopp::integrator::MDIntegrator::dt, espressopp::SystemAccess::getSystemRef(), group, LOG4ESPP_DEBUG, and LOG4ESPP_INFO.
Referenced by run().
integrate2()
void espressopp::integrator::VelocityVerletOnGroup::integrate2 () private
Definition at line 240 of file VelocityVerletOnGroup.cpp.
References espressopp::integrator::MDIntegrator::dt, espressopp::SystemAccess::getSystemRef(), and group.
Referenced by run().
LOG4ESPP_DECL_LOGGER()
static espressopp::integrator::MDIntegrator::LOG4ESPP_DECL_LOGGER (theLogger) static protected inherited
Logger.
printForces()
void espressopp::integrator::VelocityVerletOnGroup::printForces (bool withGhost) private
Definition at line 340 of file VelocityVerletOnGroup.cpp.
References espressopp::SystemAccess::getSystemRef(), espressopp::iterator::CellListIterator::isDone(), LOG4ESPP_DEBUG, and espressopp::System::storage.
printPositions()
void espressopp::integrator::VelocityVerletOnGroup::printPositions (bool withGhost) private
Definition at line 366 of file VelocityVerletOnGroup.cpp.
References espressopp::SystemAccess::getSystemRef(), group, LOG4ESPP_DEBUG, and espressopp::System::storage.
printTimers()
void espressopp::integrator::VelocityVerletOnGroup::printTimers () private
Definition at line 169 of file VelocityVerletOnGroup.cpp.
References timeComm1, timeComm2, timeForceComp, timeInt1, timeInt2, timeIntegrate, and timeResort.
Referenced by run().
registerPython()
void espressopp::integrator::VelocityVerletOnGroup::registerPython () static
Register this class so it can be used from Python.
Definition at line 394 of file VelocityVerletOnGroup.cpp.
References getLangevin(), and setLangevin().
Referenced by getLangevin(), and espressopp::integrator::registerPython().
resetTimers()
void espressopp::integrator::VelocityVerletOnGroup::resetTimers () private
Definition at line 157 of file VelocityVerletOnGroup.cpp.
References timeComm1, timeComm2, timeForce, timeForceComp, timeInt1, timeInt2, and timeResort.
Referenced by run().
run()
void espressopp::integrator::VelocityVerletOnGroup::run (int nsteps) virtual
This method runs the integration for a certain number of steps.
Implements espressopp::integrator::MDIntegrator.
Definition at line 69 of file VelocityVerletOnGroup.cpp.
References espressopp::storage::Storage::decompose(), espressopp::esutil::Timer::getElapsedTime(), espressopp::System::getSkin(), espressopp::SystemAccess::getSystemRef(), integrate1(), integrate2(), langevin, LOG4ESPP_DEBUG_ON, LOG4ESPP_INFO, maxDist, printTimers(), espressopp::esutil::Timer::reset(), resetTimers(), resortFlag, espressopp::System::storage, timeInt1, timeInt2, timeIntegrate, timeResort, and updateForces().
Referenced by getLangevin().
setLangevin()
void espressopp::integrator::VelocityVerletOnGroup::setLangevin (shared_ptr< class LangevinThermostat > langevin)
Definition at line 61 of file VelocityVerletOnGroup.cpp.
References langevin, and LOG4ESPP_INFO.
Referenced by registerPython().
setStep()
void espressopp::integrator::MDIntegrator::setStep (long long step_) inline inherited
Getter routine for integration step.
Definition at line 70 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::MDIntegrator::registerPython().
setTimeStep()
void espressopp::integrator::MDIntegrator::setTimeStep (real dt) inherited
Setter routine for the timestep.
Definition at line 54 of file MDIntegrator.cpp.
References espressopp::System::comm, espressopp::integrator::MDIntegrator::dt, espressopp::SystemAccess::getSystemRef(), and espressopp::esutil::Error::setException().
Referenced by espressopp::integrator::MDIntegrator::registerPython().
setUp()
void espressopp::integrator::VelocityVerletOnGroup::setUp () private
Definition at line 258 of file VelocityVerletOnGroup.cpp.
References espressopp::SystemAccess::getSystemRef(), LOG4ESPP_INFO, maxCut, and espressopp::System::shortRangeInteractions.
updateForces()
void espressopp::integrator::VelocityVerletOnGroup::updateForces () private
Definition at line 300 of file VelocityVerletOnGroup.cpp.
References calcForces(), espressopp::storage::Storage::collectGhostForces(), espressopp::esutil::Timer::getElapsedTime(), espressopp::SystemAccess::getSystemRef(), langevin, espressopp::System::storage, timeComm1, timeComm2, timeForce, timeIntegrate, and espressopp::storage::Storage::updateGhosts().
Referenced by run().
Member Data Documentation
aftCalcF
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::aftCalcF inherited
Definition at line 93 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::PIAdressIntegrator::calcForcesM(), espressopp::integrator::VelocityVerletRESPA::updateForces(), and espressopp::integrator::VelocityVerlet::updateForces().
aftCalcSlow
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::aftCalcSlow inherited
Definition at line 87 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerletRESPA::run().
aftInitF
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::aftInitF inherited
Definition at line 92 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerletRESPA::calcForces(), and espressopp::integrator::VelocityVerlet::calcForces().
aftIntP
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::aftIntP inherited
Definition at line 91 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerletRESPA::run(), and espressopp::integrator::VelocityVerlet::run().
aftIntSlow
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::aftIntSlow inherited
Definition at line 96 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerletRESPA::run().
aftIntV
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::aftIntV inherited
Definition at line 95 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerletRESPA::run(), and espressopp::integrator::VelocityVerlet::run().
befIntP
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::befIntP inherited
Definition at line 89 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerletRESPA::run(), and espressopp::integrator::VelocityVerlet::run().
befIntV
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::befIntV inherited
Definition at line 94 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerletRESPA::run(), and espressopp::integrator::VelocityVerlet::run().
dt
real espressopp::integrator::MDIntegrator::dt protected inherited
Timestep used for integration.
Definition at line 112 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::PIAdressIntegrator::getTimeStep(), espressopp::integrator::VelocityVerletRESPA::integrate1(), espressopp::integrator::VelocityVerlet::integrate1(), integrate1(), espressopp::integrator::VelocityVerletRESPA::integrate2(), espressopp::integrator::VelocityVerlet::integrate2(), integrate2(), espressopp::integrator::PIAdressIntegrator::integrateModePos(), espressopp::integrator::PIAdressIntegrator::integrateV2(), espressopp::integrator::MDIntegrator::MDIntegrator(), espressopp::integrator::PIAdressIntegrator::OUintegrate(), espressopp::integrator::PIAdressIntegrator::PIAdressIntegrator(), espressopp::integrator::VelocityVerletRESPA::run(), espressopp::integrator::PIAdressIntegrator::setmStep(), espressopp::integrator::VelocityVerletRESPA::setmultistep(), espressopp::integrator::PIAdressIntegrator::setsStep(), espressopp::integrator::PIAdressIntegrator::setTimeStep(), espressopp::integrator::VelocityVerletRESPA::setTimeStep(), espressopp::integrator::MDIntegrator::setTimeStep(), and espressopp::integrator::VelocityVerletRESPA::VelocityVerletRESPA().
exList
ExtensionList espressopp::integrator::MDIntegrator::exList protected inherited
Definition at line 106 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::MDIntegrator::addExtension(), espressopp::integrator::MDIntegrator::getExtension(), and espressopp::integrator::MDIntegrator::getNumberOfExtensions().
group
shared_ptr<class espressopp::ParticleGroup> espressopp::integrator::VelocityVerletOnGroup::group private
Definition at line 64 of file VelocityVerletOnGroup.hpp.
Referenced by integrate1(), integrate2(), and printPositions().
inIntP
boost::signals2::signal<void (real&)> espressopp::integrator::MDIntegrator::inIntP inherited
Definition at line 90 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerletRESPA::integrate1(), and espressopp::integrator::VelocityVerlet::integrate1().
langevin
shared_ptr< class LangevinThermostat > espressopp::integrator::VelocityVerletOnGroup::langevin private
Langevin thermostat if available.
Definition at line 63 of file VelocityVerletOnGroup.hpp.
Referenced by getLangevin(), run(), setLangevin(), and updateForces().
maxCut
real espressopp::integrator::VelocityVerletOnGroup::maxCut private
Definition at line 61 of file VelocityVerletOnGroup.hpp.
Referenced by setUp().
maxDist
real espressopp::integrator::VelocityVerletOnGroup::maxDist private
Definition at line 59 of file VelocityVerletOnGroup.hpp.
Referenced by run(), and VelocityVerletOnGroup().
recalc1
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::recalc1 inherited
Definition at line 86 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerletRESPA::run(), and espressopp::integrator::VelocityVerlet::run().
recalc2
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::recalc2 inherited
Definition at line 88 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerletRESPA::run(), and espressopp::integrator::VelocityVerlet::run().
resortFlag
bool espressopp::integrator::VelocityVerletOnGroup::resortFlag private
true implies need for resort of particles
Definition at line 58 of file VelocityVerletOnGroup.hpp.
Referenced by run(), and VelocityVerletOnGroup().
runInit
boost::signals2::signal<void ()> espressopp::integrator::MDIntegrator::runInit inherited
Definition at line 85 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerletRESPA::run(), and espressopp::integrator::VelocityVerlet::run().
step
long long espressopp::integrator::MDIntegrator::step protected inherited
Integration step.
Definition at line 109 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::VelocityVerletRESPA::integrate2(), espressopp::integrator::VelocityVerlet::integrate2(), espressopp::integrator::MDIntegrator::MDIntegrator(), and espressopp::integrator::PIAdressIntegrator::run().
timeComm1
real espressopp::integrator::VelocityVerletOnGroup::timeComm1 private
Definition at line 98 of file VelocityVerletOnGroup.hpp.
Referenced by printTimers(), resetTimers(), and updateForces().
timeComm2
real espressopp::integrator::VelocityVerletOnGroup::timeComm2 private
Definition at line 99 of file VelocityVerletOnGroup.hpp.
Referenced by printTimers(), resetTimers(), and updateForces().
timeFlag
bool espressopp::integrator::MDIntegrator::timeFlag protected inherited
Definition at line 104 of file MDIntegrator.hpp.
Referenced by espressopp::integrator::MDIntegrator::MDIntegrator().
timeForce
real espressopp::integrator::VelocityVerletOnGroup::timeForce private
Definition at line 96 of file VelocityVerletOnGroup.hpp.
Referenced by resetTimers(), and updateForces().
timeForceComp
real espressopp::integrator::VelocityVerletOnGroup::timeForceComp[100] private
Definition at line 97 of file VelocityVerletOnGroup.hpp.
Referenced by calcForces(), printTimers(), and resetTimers().
timeInt1
real espressopp::integrator::VelocityVerletOnGroup::timeInt1 private
Definition at line 100 of file VelocityVerletOnGroup.hpp.
Referenced by printTimers(), resetTimers(), and run().
timeInt2
real espressopp::integrator::VelocityVerletOnGroup::timeInt2 private
Definition at line 101 of file VelocityVerletOnGroup.hpp.
Referenced by printTimers(), resetTimers(), and run().
timeIntegrate
esutil::WallTimer espressopp::integrator::VelocityVerletOnGroup::timeIntegrate private
used for timing
Definition at line 91 of file VelocityVerletOnGroup.hpp.
Referenced by calcForces(), printTimers(), run(), and updateForces().
timeResort
real espressopp::integrator::VelocityVerletOnGroup::timeResort private
Definition at line 95 of file VelocityVerletOnGroup.hpp.
Referenced by printTimers(), resetTimers(), and run().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/integrator/VelocityVerletOnGroup.hpp
/home/espressopp/espressopp/src/integrator/VelocityVerletOnGroup.cpp