ESPResSo++: espressopp::analysis::ConfigurationExtIterator Class Reference
espressopp::analysis::ConfigurationExtIterator Class Reference
Iterator class for configuration to be used in Python.
#include <ConfigurationExt.hpp>
Public Member Functions
ConfigurationExtIterator (std::map< size_t, RealND > &coordinates)
size_t currentId ()
RealND currentProperties ()
void incrementIterator ()
size_t nextId ()
Get next particle id for which properties are available.
const RealND nextProperties ()
Private Attributes
std::map< size_t, RealND >
::iterator it
std::map< size_t, RealND >
::iterator end
Detailed Description
Iterator class for configuration to be used in Python.
Definition at line 40 of file ConfigurationExt.hpp.
Constructor & Destructor Documentation
espressopp::analysis::ConfigurationExtIterator::ConfigurationExtIterator (std::map< size_t, RealND > & coordinates)
Definition at line 88 of file ConfigurationExt.cpp.
Member Function Documentation
size_t espressopp::analysis::ConfigurationExtIterator::currentId ()
Definition at line 96 of file ConfigurationExt.cpp.
Referenced by espressopp::io::DumpXYZ::dump().
RealND espressopp::analysis::ConfigurationExtIterator::currentProperties ()
Definition at line 107 of file ConfigurationExt.cpp.
Referenced by espressopp::io::DumpXYZ::dump().
void espressopp::analysis::ConfigurationExtIterator::incrementIterator ()
Definition at line 118 of file ConfigurationExt.cpp.
Referenced by espressopp::io::DumpXYZ::dump().
size_t espressopp::analysis::ConfigurationExtIterator::nextId ()
Get next particle id for which properties are available.
Definition at line 123 of file ConfigurationExt.cpp.
Referenced by espressopp::analysis::ConfigurationExt::registerPython().
const RealND espressopp::analysis::ConfigurationExtIterator::nextProperties ()
Definition at line 136 of file ConfigurationExt.cpp.
Referenced by espressopp::io::DumpGRO::dump(), and espressopp::io::DumpGROAdress::dump().
Member Data Documentation
std::map<size_t, RealND >::iterator espressopp::analysis::ConfigurationExtIterator::end private
Definition at line 62 of file ConfigurationExt.hpp.
std::map<size_t, RealND >::iterator espressopp::analysis::ConfigurationExtIterator::it private
Definition at line 61 of file ConfigurationExt.hpp.
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/analysis/ConfigurationExt.hpp
/home/travis/build/espressopp/espressopp/src/analysis/ConfigurationExt.cpp