ESPResSo++: espressopp::vectorization::Vectorization Class Reference
espressopp::vectorization::Vectorization Class Reference
facilitates offloading of particle data to vectorization-friendly form
#include <Vectorization.hpp>
Public Member Functions
Vectorization (shared_ptr< System > system, shared_ptr< integrator::MDIntegrator > mdintegrator, Mode mode=ESPP_VEC_MODE_DEFAULT)
constructor
~Vectorization ()
destructor
void connect ()
connect to boost signals in integrator and storage
void disconnect ()
disconnect boost signals made with connect()
ParticleArray & getParticleArray ()
CellNeighborList const & getNeighborList () const
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
registration with python
Private Member Functions
void resetParticles ()
reset and update particleArray from current storage
void befCalcForces ()
set force array/s to zero
void updatePositions ()
void updateForces ()
add forces back to storage
void resetCells ()
reset and update cell mapping and neighbor lists from current storage
Static Private Member Functions
static LOG4ESPP_DECL_LOGGER (logger)
Private Attributes
ParticleArray particleArray
Mode mode
CellNeighborList neighborList
shared_ptr< integrator::MDIntegrator > mdintegrator
boost::signals2::connection sigBefCalcForces
boost::signals2::connection sigUpdateForces
boost::signals2::connection sigResetParticles
boost::signals2::connection sigResetCells
shared_ptr< storage::DomainDecomposition > decomp
weak_ptr< System > mySystem
Weak pointer to the system guarantees that system will be freed.
weak_ptr< System > mySystem1
weak_ptr< System > mySystem2
Detailed Description
facilitates offloading of particle data to vectorization-friendly form
Definition at line 39 of file Vectorization.hpp.
Constructor & Destructor Documentation
Vectorization()
espressopp::vectorization::Vectorization::Vectorization (shared_ptr< System > system, shared_ptr< integrator::MDIntegrator > mdintegrator, Mode mode = ESPP_VEC_MODE_DEFAULT)
constructor
Definition at line 34 of file Vectorization.cpp.
References connect(), espressopp::vectorization::ESPP_VEC_AOS, LOG4ESPP_INFO, mode, and resetCells().
~Vectorization()
espressopp::vectorization::Vectorization::~Vectorization ()
destructor
Definition at line 48 of file Vectorization.cpp.
References disconnect().
Member Function Documentation
befCalcForces()
void espressopp::vectorization::Vectorization::befCalcForces () private
set force array/s to zero
Definition at line 98 of file Vectorization.cpp.
References espressopp::vectorization::ESPP_VEC_AOS, espressopp::vectorization::ParticleArray::f_x, espressopp::vectorization::ParticleArray::f_y, espressopp::vectorization::ParticleArray::f_z, espressopp::vectorization::ParticleArray::force, espressopp::SystemAccess::getSystem(), mode, particleArray, and espressopp::vectorization::ParticleArray::updateFromPositionOnly().
Referenced by connect().
connect()
void espressopp::vectorization::Vectorization::connect ()
connect to boost signals in integrator and storage
Definition at line 55 of file Vectorization.cpp.
References befCalcForces(), espressopp::SystemAccess::getSystem(), mdintegrator, resetCells(), resetParticles(), sigBefCalcForces, sigResetCells, sigResetParticles, sigUpdateForces, and updateForces().
Referenced by Vectorization().
disconnect()
void espressopp::vectorization::Vectorization::disconnect ()
disconnect boost signals made with connect()
Definition at line 73 of file Vectorization.cpp.
References sigBefCalcForces, sigResetCells, sigResetParticles, and sigUpdateForces.
Referenced by ~Vectorization().
getNeighborList()
CellNeighborList const& espressopp::vectorization::Vectorization::getNeighborList () const inline
Definition at line 50 of file Vectorization.hpp.
References neighborList.
getParticleArray()
ParticleArray& espressopp::vectorization::Vectorization::getParticleArray () inline
Definition at line 49 of file Vectorization.hpp.
References particleArray.
getSystem()
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::VerletList::_rebuildUsingBuffers(), espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::LatticeBoltzmann::assignMyLattice(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), befCalcForces(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::TDforce::computeTDEnergy(), connect(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::vectorization::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpXTCAdress::dump(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::io::DumpXYZ::DumpXYZ(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::vectorization::VerletList::rebuild(), espressopp::vectorization::VerletList::rebuild_p_nc_pack_stencil(), espressopp::vectorization::VerletList::rebuildPairs(), espressopp::VerletListTriple::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::VerletList::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::vectorization::VerletList::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), resetCells(), resetParticles(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), updateForces(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
getSystem1()
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
getSystem2()
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
getSystemRef()
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerletRESPA::calcForces(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeCOM(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::FixedLocalTupleComListInteractionTemplate(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::VelocityVerletRESPA::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::VelocityVerletRESPA::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::VelocityVerletRESPA::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::Adress::integrateSlow(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::vectorization::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::VelocityVerletRESPA::run(), espressopp::integrator::PIAdressIntegrator::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::MinimizeEnergy::run(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::Rattle::saveOldPos(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostatOnGroup::thermalize(), espressopp::integrator::LangevinThermostatOnRadius::thermalize(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::vectorization::VerletList::totalSize(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::io::DumpH5MD::update(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::VelocityVerletRESPA::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
getSystemRef1()
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
getSystemRef2()
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
LOG4ESPP_DECL_LOGGER()
static espressopp::vectorization::Vectorization::LOG4ESPP_DECL_LOGGER (logger) static private
registerPython()
void espressopp::vectorization::Vectorization::registerPython () static
registration with python
Definition at line 135 of file Vectorization.cpp.
References espressopp::vectorization::ESPP_VEC_AOS, and espressopp::vectorization::ESPP_VEC_SOA.
Referenced by espressopp::vectorization::registerPython().
resetCells()
void espressopp::vectorization::Vectorization::resetCells () private
reset and update cell mapping and neighbor lists from current storage
Definition at line 90 of file Vectorization.cpp.
References espressopp::SystemAccess::getSystem(), LOG4ESPP_TRACE, espressopp::vectorization::CellNeighborList::maxNumNeighbors(), neighborList, and espressopp::vectorization::CellNeighborList::numCells().
Referenced by connect(), and Vectorization().
resetParticles()
void espressopp::vectorization::Vectorization::resetParticles () private
reset and update particleArray from current storage
Definition at line 83 of file Vectorization.cpp.
References espressopp::vectorization::ParticleArray::copyFrom(), espressopp::SystemAccess::getSystem(), mode, and particleArray.
Referenced by connect().
updateForces()
void espressopp::vectorization::Vectorization::updateForces () private
add forces back to storage
Definition at line 127 of file Vectorization.cpp.
References espressopp::vectorization::ParticleArray::addToForceOnly(), espressopp::SystemAccess::getSystem(), and particleArray.
Referenced by connect().
updatePositions()
void espressopp::vectorization::Vectorization::updatePositions () private
Member Data Documentation
decomp
shared_ptr<storage::DomainDecomposition> espressopp::vectorization::Vectorization::decomp private
Definition at line 75 of file Vectorization.hpp.
mdintegrator
shared_ptr<integrator::MDIntegrator> espressopp::vectorization::Vectorization::mdintegrator private
Definition at line 65 of file Vectorization.hpp.
Referenced by connect().
mode
Mode espressopp::vectorization::Vectorization::mode private
Definition at line 56 of file Vectorization.hpp.
Referenced by befCalcForces(), resetParticles(), and Vectorization().
mySystem
weak_ptr< System > espressopp::SystemAccess::mySystem private inherited
Weak pointer to the system guarantees that system will be freed.
Definition at line 54 of file SystemAccess.hpp.
Referenced by espressopp::SystemAccess::getSystem(), and espressopp::SystemAccess::SystemAccess().
mySystem1
weak_ptr< System > espressopp::SystemAccess::mySystem1 private inherited
Definition at line 55 of file SystemAccess.hpp.
Referenced by espressopp::SystemAccess::getSystem1(), and espressopp::SystemAccess::SystemAccess().
mySystem2
weak_ptr< System > espressopp::SystemAccess::mySystem2 private inherited
Definition at line 56 of file SystemAccess.hpp.
Referenced by espressopp::SystemAccess::getSystem2(), and espressopp::SystemAccess::SystemAccess().
neighborList
CellNeighborList espressopp::vectorization::Vectorization::neighborList private
Definition at line 62 of file Vectorization.hpp.
Referenced by getNeighborList(), and resetCells().
particleArray
ParticleArray espressopp::vectorization::Vectorization::particleArray private
Definition at line 55 of file Vectorization.hpp.
Referenced by befCalcForces(), getParticleArray(), resetParticles(), and updateForces().
sigBefCalcForces
boost::signals2::connection espressopp::vectorization::Vectorization::sigBefCalcForces private
Definition at line 68 of file Vectorization.hpp.
Referenced by connect(), and disconnect().
sigResetCells
boost::signals2::connection espressopp::vectorization::Vectorization::sigResetCells private
Definition at line 73 of file Vectorization.hpp.
Referenced by connect(), and disconnect().
sigResetParticles
boost::signals2::connection espressopp::vectorization::Vectorization::sigResetParticles private
Definition at line 72 of file Vectorization.hpp.
Referenced by connect(), and disconnect().
sigUpdateForces
boost::signals2::connection espressopp::vectorization::Vectorization::sigUpdateForces private
Definition at line 69 of file Vectorization.hpp.
Referenced by connect(), and disconnect().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/vectorization/Vectorization.hpp
/home/espressopp/espressopp/src/vectorization/Vectorization.cpp