ESPResSo++: espressopp::storage::NodeGrid Class Reference
espressopp::storage::NodeGrid Class Reference
Node grid point.
#include <NodeGrid.hpp>
Public Types
enum Directions {
Left = 0, Right, Bottom, Top,
Front, Back
}
order of node neighbors
enum FoldDirections { ToLeft = -1, ToRight = 1 }
order coordinates
Public Member Functions
NodeGrid ()
NodeGrid (const Int3D &grid, const longint nodeId, const Real3D &domainSize)
longint mapPositionToNodeClipped (const Real3D &pos) const
map coordinate to a node. Positions outside are clipped back
longint getNodePosition (int axis) const
get this node's coordinates
real getLocalBoxSize (int axis) const
size of the local box
real getInverseLocalBoxSize (int axis) const
inverse of the size of a cell
real getMyLeft (int axis) const
calculate start of local box
Real3D getMyLeft () const
real getMyRight (int axis) const
calculate end of local box
Real3D getMyRight () const
Real3D getMyCenter () const
longint getNodeNeighborIndex (int dir) const
longint getNodeNeighborIndex (Directions dir) const
int getBoundary (int dir) const
where to fold particles that leave the box in direction i (ToRight, 0, ToLeft)
int getBoundary (FoldDirections dir) const
void scaleVolume (real s)
void scaleVolume (Real3D s)
longint getGridSize (int i) const
const Int3D & getGridSize () const
longint getNumberOfCells () const
longint mapPositionToIndex (int p1, int p2, int p3) const
convert a grid position to a unique sequence index
longint mapPositionToIndex (const Int3D &pos) const
void mapIndexToPosition (int &p1, int &p2, int &p3, longint index) const
convert a sequence index back to a grid position
void mapIndexToPosition (Int3D &pos, longint index) const
Static Public Member Functions
static int convertDirToCoord (int dir)
get the coordinate of a direction
static int convertDirToCoord (Directions dir)
static void registerPython ()
Static Public Attributes
static const int numNodeNeighbors = Back + 1
Private Member Functions
void calcNodeNeighbors (longint node)
Static Private Member Functions
static LOG4ESPP_DECL_LOGGER (logger)
Private Attributes
Int3D nodePos
position of this node in node grid
longint nodeNeighbors [6]
the six nearest neighbors of a node in the node grid
int boundaries [6]
where to fold particles that leave local box in direction i
Real3D localBoxSize
cell size
Real3D invLocalBoxSize
inverse domain size
real smallestLocalBoxDiameter
smallest diameter of the local box
Detailed Description
Node grid point.
This represents the node grid of the domain decomposition, as well as the location of this processor in the grid.
Definition at line 49 of file NodeGrid.hpp.
Member Enumeration Documentation
enum espressopp::storage::NodeGrid::Directions
order of node neighbors
Enumerator:
Left
Right
Bottom
Top
Front
Back
Definition at line 55 of file NodeGrid.hpp.
enum espressopp::storage::NodeGrid::FoldDirections
order coordinates
Enumerator:
ToLeft
ToRight
Definition at line 62 of file NodeGrid.hpp.
Constructor & Destructor Documentation
espressopp::storage::NodeGrid::NodeGrid () [inline]
Definition at line 52 of file NodeGrid.hpp.
espressopp::storage::NodeGrid::NodeGrid (const Int3D & grid, const longint nodeId, const Real3D & domainSize)
Definition at line 37 of file NodeGrid.cpp.
References calcNodeNeighbors(), espressopp::esutil::Grid::getGridSize(), invLocalBoxSize, localBoxSize, and smallestLocalBoxDiameter.
Member Function Documentation
void espressopp::storage::NodeGrid::calcNodeNeighbors (longint node) [private]
Definition at line 72 of file NodeGrid.cpp.
References boundaries, getBoundary(), espressopp::esutil::Grid::getGridSize(), getNodeNeighborIndex(), LOG4ESPP_DEBUG, espressopp::esutil::Grid::mapIndexToPosition(), espressopp::esutil::Grid::mapPositionToIndex(), nodeNeighbors, nodePos, ToLeft, and ToRight.
Referenced by NodeGrid().
static int espressopp::storage::NodeGrid::convertDirToCoord (int dir) [inline, static]
get the coordinate of a direction
Definition at line 113 of file NodeGrid.hpp.
Referenced by espressopp::storage::DomainDecomposition::appendParticles(), and espressopp::storage::DomainDecompositionAdress::appendParticles().
static int espressopp::storage::NodeGrid::convertDirToCoord (Directions dir) [inline, static]
Definition at line 115 of file NodeGrid.hpp.
int espressopp::storage::NodeGrid::getBoundary (int dir) const [inline]
where to fold particles that leave the box in direction i (ToRight, 0, ToLeft)
Definition at line 106 of file NodeGrid.hpp.
References boundaries.
Referenced by espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), calcNodeNeighbors(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), and espressopp::storage::DomainDecompositionAdress::doGhostCommunication().
int espressopp::storage::NodeGrid::getBoundary (FoldDirections dir) const [inline]
Definition at line 108 of file NodeGrid.hpp.
References getBoundary().
Referenced by getBoundary().
longint espressopp::esutil::Grid::getGridSize (int i) const [inline, inherited]
Reimplemented in espressopp::CellGrid.
Definition at line 49 of file Grid.hpp.
References espressopp::esutil::Grid::size.
Referenced by espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::storage::DomainDecomposition::getInt3DNodeGrid(), and espressopp::integrator::AssociationReaction::sendMultiMap().
const Int3D& espressopp::esutil::Grid::getGridSize () const [inline, inherited]
Definition at line 50 of file Grid.hpp.
References espressopp::esutil::Grid::size.
Referenced by calcNodeNeighbors(), espressopp::CellGrid::getFrameGridSize(), espressopp::CellGrid::getGridSize(), espressopp::CellGrid::getInnerCellsEnd(), espressopp::CellGrid::getNumberOfInnerCells(), mapPositionToNodeClipped(), and NodeGrid().
real espressopp::storage::NodeGrid::getInverseLocalBoxSize (int axis) const [inline]
inverse of the size of a cell
Definition at line 79 of file NodeGrid.hpp.
References invLocalBoxSize.
real espressopp::storage::NodeGrid::getLocalBoxSize (int axis) const [inline]
size of the local box
Definition at line 77 of file NodeGrid.hpp.
References localBoxSize.
Real3D espressopp::storage::NodeGrid::getMyCenter () const [inline]
Definition at line 93 of file NodeGrid.hpp.
References getMyLeft(), and getMyRight().
real espressopp::storage::NodeGrid::getMyLeft (int axis) const [inline]
calculate start of local box
Definition at line 82 of file NodeGrid.hpp.
References localBoxSize, and nodePos.
Referenced by espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionAdress::getLocalBoxXMin(), espressopp::storage::DomainDecomposition::getLocalBoxXMin(), espressopp::storage::DomainDecompositionAdress::getLocalBoxYMin(), espressopp::storage::DomainDecomposition::getLocalBoxYMin(), espressopp::storage::DomainDecompositionAdress::getLocalBoxZMin(), and espressopp::storage::DomainDecomposition::getLocalBoxZMin().
Real3D espressopp::storage::NodeGrid::getMyLeft () const [inline]
Definition at line 83 of file NodeGrid.hpp.
Referenced by getMyCenter().
real espressopp::storage::NodeGrid::getMyRight (int axis) const [inline]
calculate end of local box
Definition at line 88 of file NodeGrid.hpp.
References localBoxSize, and nodePos.
Referenced by espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionAdress::getLocalBoxXMax(), espressopp::storage::DomainDecomposition::getLocalBoxXMax(), espressopp::storage::DomainDecompositionAdress::getLocalBoxYMax(), espressopp::storage::DomainDecomposition::getLocalBoxYMax(), espressopp::storage::DomainDecompositionAdress::getLocalBoxZMax(), and espressopp::storage::DomainDecomposition::getLocalBoxZMax().
Real3D espressopp::storage::NodeGrid::getMyRight () const [inline]
Definition at line 89 of file NodeGrid.hpp.
Referenced by getMyCenter().
longint espressopp::storage::NodeGrid::getNodeNeighborIndex (int dir) const [inline]
Definition at line 100 of file NodeGrid.hpp.
References nodeNeighbors.
Referenced by calcNodeNeighbors(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), and espressopp::integrator::AssociationReaction::sendMultiMap().
longint espressopp::storage::NodeGrid::getNodeNeighborIndex (Directions dir) const [inline]
Definition at line 102 of file NodeGrid.hpp.
References getNodeNeighborIndex().
Referenced by getNodeNeighborIndex().
longint espressopp::storage::NodeGrid::getNodePosition (int axis) const [inline]
get this node's coordinates
Definition at line 75 of file NodeGrid.hpp.
References nodePos.
Referenced by espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), and espressopp::integrator::AssociationReaction::sendMultiMap().
longint espressopp::esutil::Grid::getNumberOfCells () const [inline, inherited]
Definition at line 52 of file Grid.hpp.
References espressopp::esutil::Grid::size.
Referenced by espressopp::storage::DomainDecomposition::createCellGrid(), and espressopp::storage::DomainDecompositionAdress::createCellGrid().
static espressopp::storage::NodeGrid::LOG4ESPP_DECL_LOGGER (logger) [static, private]
void espressopp::esutil::Grid::mapIndexToPosition (int & p1, int & p2, int & p3, longint index) const [inline, inherited]
convert a sequence index back to a grid position
Definition at line 67 of file Grid.hpp.
References espressopp::esutil::Grid::size.
Referenced by calcNodeNeighbors(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), and espressopp::esutil::Grid::mapIndexToPosition().
void espressopp::esutil::Grid::mapIndexToPosition (Int3D & pos, longint index) const [inline, inherited]
Definition at line 75 of file Grid.hpp.
References espressopp::esutil::Grid::mapIndexToPosition().
longint espressopp::esutil::Grid::mapPositionToIndex (int p1, int p2, int p3) const [inline, inherited]
convert a grid position to a unique sequence index
Definition at line 61 of file Grid.hpp.
References espressopp::esutil::Grid::size.
Referenced by calcNodeNeighbors(), espressopp::storage::DomainDecomposition::fillCells(), espressopp::storage::DomainDecompositionAdress::fillCells(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::storage::DomainDecomposition::initCellInteractions(), espressopp::storage::DomainDecompositionAdress::initCellInteractions(), espressopp::CellGrid::mapPositionToCell(), espressopp::CellGrid::mapPositionToCellChecked(), espressopp::CellGrid::mapPositionToCellCheckedAndClipped(), espressopp::CellGrid::mapPositionToCellClipped(), mapPositionToNodeClipped(), espressopp::storage::DomainDecomposition::markCells(), and espressopp::storage::DomainDecompositionAdress::markCells().
longint espressopp::esutil::Grid::mapPositionToIndex (const Int3D & pos) const [inline, inherited]
Definition at line 63 of file Grid.hpp.
References espressopp::esutil::Grid::mapPositionToIndex().
Referenced by espressopp::esutil::Grid::mapPositionToIndex().
longint espressopp::storage::NodeGrid::mapPositionToNodeClipped (const Real3D & pos) const
map coordinate to a node. Positions outside are clipped back
Definition at line 56 of file NodeGrid.cpp.
References espressopp::esutil::Grid::getGridSize(), invLocalBoxSize, and espressopp::esutil::Grid::mapPositionToIndex().
Referenced by espressopp::storage::DomainDecompositionAdress::mapPositionToNodeClipped(), and espressopp::storage::DomainDecomposition::mapPositionToNodeClipped().
void espressopp::esutil::Grid::registerPython () [static, inherited]
Definition at line 38 of file Grid.cpp.
References espressopp::esutil::mapIndexToPositionInt3D.
Referenced by espressopp::esutil::registerPython().
void espressopp::storage::NodeGrid::scaleVolume (real s) [inline]
Definition at line 119 of file NodeGrid.hpp.
References invLocalBoxSize, localBoxSize, and smallestLocalBoxDiameter.
Referenced by espressopp::storage::DomainDecomposition::scaleVolume().
void espressopp::storage::NodeGrid::scaleVolume (Real3D s) [inline]
Definition at line 132 of file NodeGrid.hpp.
References invLocalBoxSize, localBoxSize, and smallestLocalBoxDiameter.
Member Data Documentation
int espressopp::storage::NodeGrid::boundaries[6] [private]
where to fold particles that leave local box in direction i
Definition at line 154 of file NodeGrid.hpp.
Referenced by calcNodeNeighbors(), and getBoundary().
Real3D espressopp::storage::NodeGrid::invLocalBoxSize [private]
inverse domain size
Definition at line 159 of file NodeGrid.hpp.
Referenced by getInverseLocalBoxSize(), mapPositionToNodeClipped(), NodeGrid(), and scaleVolume().
Real3D espressopp::storage::NodeGrid::localBoxSize [private]
cell size
Definition at line 157 of file NodeGrid.hpp.
Referenced by getLocalBoxSize(), getMyLeft(), getMyRight(), NodeGrid(), and scaleVolume().
longint espressopp::storage::NodeGrid::nodeNeighbors[6] [private]
the six nearest neighbors of a node in the node grid
Definition at line 152 of file NodeGrid.hpp.
Referenced by calcNodeNeighbors(), and getNodeNeighborIndex().
Int3D espressopp::storage::NodeGrid::nodePos [private]
position of this node in node grid
Definition at line 150 of file NodeGrid.hpp.
Referenced by calcNodeNeighbors(), getMyLeft(), getMyRight(), and getNodePosition().
const int espressopp::storage::NodeGrid::numNodeNeighbors = Back + 1 [static]
Definition at line 117 of file NodeGrid.hpp.
real espressopp::storage::NodeGrid::smallestLocalBoxDiameter [private]
smallest diameter of the local box
Definition at line 162 of file NodeGrid.hpp.
Referenced by NodeGrid(), and scaleVolume().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/storage/NodeGrid.hpp
/home/travis/build/espressopp/espressopp/src/storage/NodeGrid.cpp