ESPResSo++: espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential > Class Template Reference
espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential > Class Template Reference
#include <VerletListVSphereInteractionTemplate.hpp>
Public Member Functions
VerletListVSphereInteractionTemplate (shared_ptr< VerletList > _verletList)
virtual ~VerletListVSphereInteractionTemplate ()
void setVerletList (shared_ptr< VerletList > _verletList)
shared_ptr< VerletList > getVerletList ()
void setPotential (int type1, int type2, const Potential &potential)
Potential & getPotential (int type1, int type2)
shared_ptr< Potential > getPotentialPtr (int type1, int type2)
virtual void addForces ()
virtual real computeEnergy ()
virtual real computeEnergyDeriv ()
virtual real computeEnergyAA ()
virtual real computeEnergyCG ()
virtual void computeVirialX (std::vector< real > &p_xx_total, int bins)
virtual real computeVirial ()
virtual void computeVirialTensor (Tensor &w)
virtual void computeVirialTensor (Tensor &w, real z)
virtual void computeVirialTensor (Tensor *w, int n)
virtual real getMaxCutoff ()
This method returns the maximal cutoff defined for one type pair.
virtual int bondType ()
Static Public Member Functions
static void registerPython ()
Protected Types
typedef _Potential Potential
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Protected Attributes
int ntypes
shared_ptr< VerletList > verletList
esutil::Array2D< Potential,
esutil::enlarge > potentialArray
esutil::Array2D< shared_ptr
< Potential >, esutil::enlarge > potentialArrayPtr
Detailed Description
template<typename _Potential>
class espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >
Definition at line 44 of file VerletListVSphereInteractionTemplate.hpp.
Member Typedef Documentation
template<typename _Potential > typedef _Potential espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::Potential protected
Definition at line 47 of file VerletListVSphereInteractionTemplate.hpp.
Constructor & Destructor Documentation
template<typename _Potential > espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::VerletListVSphereInteractionTemplate (shared_ptr< VerletList > _verletList) inline
Definition at line 51 of file VerletListVSphereInteractionTemplate.hpp.
References espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::ntypes, and espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::potentialArray.
template<typename _Potential > virtual espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::~VerletListVSphereInteractionTemplate () inline virtual
Definition at line 57 of file VerletListVSphereInteractionTemplate.hpp.
Member Function Documentation
template<typename _Potential > void espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::addForces () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 114 of file VerletListVSphereInteractionTemplate.hpp.
References espressopp::Particle::force(), espressopp::Particle::fradius(), espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_INFO, LOG4ESPP_TRACE, and espressopp::Particle::type().
template<typename _Potential > virtual int espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::bondType () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 100 of file VerletListVSphereInteractionTemplate.hpp.
References espressopp::interaction::Nonbonded.
template<typename _Potential > real espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::computeEnergy () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 141 of file VerletListVSphereInteractionTemplate.hpp.
References espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_INFO, LOG4ESPP_TRACE, and espressopp::Particle::type().
template<typename _Potential > real espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::computeEnergyAA () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 174 of file VerletListVSphereInteractionTemplate.hpp.
template<typename _Potential > real espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::computeEnergyCG () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 181 of file VerletListVSphereInteractionTemplate.hpp.
template<typename _Potential > real espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::computeEnergyDeriv () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 167 of file VerletListVSphereInteractionTemplate.hpp.
template<typename _Potential > real espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::computeVirial () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 195 of file VerletListVSphereInteractionTemplate.hpp.
References espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_INFO, mpiWorld, espressopp::Particle::position(), and espressopp::Particle::type().
template<typename _Potential > void espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::computeVirialTensor (Tensor & w) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 226 of file VerletListVSphereInteractionTemplate.hpp.
References espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_INFO, mpiWorld, espressopp::Particle::position(), and espressopp::Particle::type().
template<typename _Potential > void espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::computeVirialTensor (Tensor & w, real z) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 258 of file VerletListVSphereInteractionTemplate.hpp.
References espressopp::System::bc, espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_INFO, mpiWorld, espressopp::Particle::position(), and espressopp::Particle::type().
template<typename _Potential > void espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::computeVirialTensor (Tensor * w, int n) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 317 of file VerletListVSphereInteractionTemplate.hpp.
References espressopp::System::bc, espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_INFO, mpiWorld, espressopp::Particle::position(), and espressopp::Particle::type().
template<typename _Potential > void espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::computeVirialX (std::vector< real > & p_xx_total, int bins) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 189 of file VerletListVSphereInteractionTemplate.hpp.
template<typename _Potential > real espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::getMaxCutoff () inline virtual
This method returns the maximal cutoff defined for one type pair.
Implements espressopp::interaction::Interaction.
Definition at line 393 of file VerletListVSphereInteractionTemplate.hpp.
template<typename _Potential > Potential& espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::getPotential (int type1, int type2) inline
Definition at line 79 of file VerletListVSphereInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), and espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::potentialArray.
template<typename _Potential > shared_ptr<Potential> espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::getPotentialPtr (int type1, int type2) inline
Definition at line 84 of file VerletListVSphereInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), and espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::potentialArray.
template<typename _Potential > shared_ptr<VerletList> espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::getVerletList () inline
Definition at line 64 of file VerletListVSphereInteractionTemplate.hpp.
References espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::verletList.
static espressopp::interaction::Interaction::LOG4ESPP_DECL_LOGGER (theLogger) static protected inherited
Logger.
void espressopp::interaction::Interaction::registerPython () static inherited
Definition at line 36 of file Interaction.cpp.
References espressopp::interaction::Interaction::bondType(), espressopp::interaction::Interaction::computeEnergy(), espressopp::interaction::Interaction::computeEnergyAA(), espressopp::interaction::Interaction::computeEnergyCG(), espressopp::interaction::Interaction::computeEnergyDeriv(), and espressopp::interaction::Interaction::computeVirial().
Referenced by espressopp::interaction::registerPython().
template<typename _Potential > void espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::setPotential (int type1, int type2, const Potential & potential) inline
Definition at line 69 of file VerletListVSphereInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::ntypes, and espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::potentialArray.
template<typename _Potential > void espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::setVerletList (shared_ptr< VerletList > _verletList) inline
Definition at line 60 of file VerletListVSphereInteractionTemplate.hpp.
References espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::verletList.
Member Data Documentation
template<typename _Potential > int espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::ntypes protected
Definition at line 103 of file VerletListVSphereInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::setPotential(), and espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::VerletListVSphereInteractionTemplate().
template<typename _Potential > esutil::Array2D<Potential, esutil::enlarge> espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::potentialArray protected
Definition at line 105 of file VerletListVSphereInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::getPotential(), espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::getPotentialPtr(), espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::setPotential(), and espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::VerletListVSphereInteractionTemplate().
template<typename _Potential > esutil::Array2D<shared_ptr<Potential>, esutil::enlarge> espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::potentialArrayPtr protected
Definition at line 106 of file VerletListVSphereInteractionTemplate.hpp.
template<typename _Potential > shared_ptr<VerletList> espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::verletList protected
Definition at line 104 of file VerletListVSphereInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::getVerletList(), and espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::setVerletList().
The documentation for this class was generated from the following file:
/home/travis/build/espressopp/espressopp/src/interaction/VerletListVSphereInteractionTemplate.hpp