ESPResSo++: espressopp::interaction::Interaction Class Reference
espressopp::interaction::Interaction Class Reference abstract
Interaction base class.
#include <Interaction.hpp>
Public Member Functions
virtual ~Interaction ()
virtual void addForces ()=0
virtual real computeEnergy ()=0
virtual real computeEnergyDeriv ()=0
virtual real computeEnergyAA ()=0
virtual real computeEnergyCG ()=0
virtual real computeEnergyAA (int atomtype)=0
virtual real computeEnergyCG (int atomtype)=0
virtual real computeVirial ()=0
virtual void computeVirialTensor (Tensor &w)=0
virtual void computeVirialX (std::vector< real > &p_xx_total, int bins)=0
virtual void computeVirialTensor (Tensor &w, real z)=0
virtual void computeVirialTensor (Tensor *w, int n)=0
virtual real getMaxCutoff ()=0
This method returns the maximal cutoff defined for one type pair.
virtual int bondType ()=0
Static Public Member Functions
static void registerPython ()
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Detailed Description
Interaction base class.
Definition at line 38 of file Interaction.hpp.
Constructor & Destructor Documentation
~Interaction()
virtual espressopp::interaction::Interaction::~Interaction () inline virtual
Definition at line 41 of file Interaction.hpp.
Member Function Documentation
addForces()
virtual void espressopp::interaction::Interaction::addForces () pure virtual
Implemented in espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >, espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >, espressopp::interaction::VerletListAdressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >, espressopp::vectorization::interaction::VerletListLennardJones, espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >, espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >, espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >, espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >, espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >, espressopp::interaction::VerletListAdressATATInteractionTemplate< _Potential1, _Potential2 >, espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >, espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >, espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >, espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >, espressopp::interaction::VerletListAdressCGInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >, espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >, espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >, espressopp::interaction::VerletListInteractionTemplate< _Potential >, espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >, espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >, espressopp::interaction::FixedPairListInteractionTemplate< _Potential >, espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >, espressopp::interaction::SingleParticleInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >, espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >, espressopp::interaction::VSphereSelfInteractionTemplate< _Potential >, espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >, and espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >.
bondType()
virtual int espressopp::interaction::Interaction::bondType () pure virtual
Implemented in espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >, espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >, espressopp::interaction::VerletListAdressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >, espressopp::vectorization::interaction::VerletListLennardJones, espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >, espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >, espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >, espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >, espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >, espressopp::interaction::VerletListAdressATATInteractionTemplate< _Potential1, _Potential2 >, espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >, espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >, espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >, espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >, espressopp::interaction::VerletListAdressCGInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >, espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >, espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >, espressopp::interaction::VerletListInteractionTemplate< _Potential >, espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >, espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >, espressopp::interaction::FixedPairListInteractionTemplate< _Potential >, espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >, espressopp::interaction::SingleParticleInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >, espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >, espressopp::interaction::VSphereSelfInteractionTemplate< _Potential >, espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >, and espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >.
Referenced by registerPython().
computeEnergy()
virtual real espressopp::interaction::Interaction::computeEnergy () pure virtual
Implemented in espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >, espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >, espressopp::interaction::VerletListAdressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >, espressopp::vectorization::interaction::VerletListLennardJones, espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >, espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >, espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >, espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >, espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >, espressopp::interaction::VerletListAdressATATInteractionTemplate< _Potential1, _Potential2 >, espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >, espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >, espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >, espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >, espressopp::interaction::VerletListAdressCGInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >, espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >, espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >, espressopp::interaction::VerletListInteractionTemplate< _Potential >, espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >, espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >, espressopp::interaction::FixedPairListInteractionTemplate< _Potential >, espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >, espressopp::interaction::SingleParticleInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >, espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >, espressopp::interaction::VSphereSelfInteractionTemplate< _Potential >, espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >, and espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >.
Referenced by registerPython().
computeEnergyAA() [1/2]
virtual real espressopp::interaction::Interaction::computeEnergyAA () pure virtual
Implemented in espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >, espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >, espressopp::interaction::VerletListAdressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >, espressopp::vectorization::interaction::VerletListLennardJones, espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >, espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >, espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >, espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >, espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >, espressopp::interaction::VerletListAdressATATInteractionTemplate< _Potential1, _Potential2 >, espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >, espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >, espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >, espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >, espressopp::interaction::VerletListAdressCGInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >, espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >, espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >, espressopp::interaction::VerletListInteractionTemplate< _Potential >, espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >, espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >, espressopp::interaction::FixedPairListInteractionTemplate< _Potential >, espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >, espressopp::interaction::SingleParticleInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >, espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >, espressopp::interaction::VSphereSelfInteractionTemplate< _Potential >, espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >, and espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >.
Referenced by registerPython().
computeEnergyAA() [2/2]
virtual real espressopp::interaction::Interaction::computeEnergyAA (int atomtype) pure virtual
Implemented in espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >, espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >, espressopp::interaction::VerletListAdressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >, espressopp::vectorization::interaction::VerletListLennardJones, espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >, espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >, espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >, espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >, espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >, espressopp::interaction::VerletListAdressATATInteractionTemplate< _Potential1, _Potential2 >, espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >, espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >, espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >, espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >, espressopp::interaction::VerletListAdressCGInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >, espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >, espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >, espressopp::interaction::VerletListInteractionTemplate< _Potential >, espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >, espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >, espressopp::interaction::FixedPairListInteractionTemplate< _Potential >, espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >, espressopp::interaction::SingleParticleInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >, espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >, espressopp::interaction::VSphereSelfInteractionTemplate< _Potential >, espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >, and espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >.
computeEnergyCG() [1/2]
virtual real espressopp::interaction::Interaction::computeEnergyCG () pure virtual
Implemented in espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >, espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >, espressopp::interaction::VerletListAdressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >, espressopp::vectorization::interaction::VerletListLennardJones, espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >, espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >, espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >, espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >, espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >, espressopp::interaction::VerletListAdressATATInteractionTemplate< _Potential1, _Potential2 >, espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >, espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >, espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >, espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >, espressopp::interaction::VerletListAdressCGInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >, espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >, espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >, espressopp::interaction::VerletListInteractionTemplate< _Potential >, espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >, espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >, espressopp::interaction::FixedPairListInteractionTemplate< _Potential >, espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >, espressopp::interaction::SingleParticleInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >, espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >, espressopp::interaction::VSphereSelfInteractionTemplate< _Potential >, espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >, and espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >.
Referenced by registerPython().
computeEnergyCG() [2/2]
virtual real espressopp::interaction::Interaction::computeEnergyCG (int atomtype) pure virtual
Implemented in espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >, espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >, espressopp::interaction::VerletListAdressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >, espressopp::vectorization::interaction::VerletListLennardJones, espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >, espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >, espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >, espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >, espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >, espressopp::interaction::VerletListAdressATATInteractionTemplate< _Potential1, _Potential2 >, espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >, espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >, espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >, espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >, espressopp::interaction::VerletListAdressCGInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >, espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >, espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >, espressopp::interaction::VerletListInteractionTemplate< _Potential >, espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >, espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >, espressopp::interaction::FixedPairListInteractionTemplate< _Potential >, espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >, espressopp::interaction::SingleParticleInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >, espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >, espressopp::interaction::VSphereSelfInteractionTemplate< _Potential >, espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >, and espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >.
computeEnergyDeriv()
virtual real espressopp::interaction::Interaction::computeEnergyDeriv () pure virtual
Implemented in espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >, espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >, espressopp::interaction::VerletListAdressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >, espressopp::vectorization::interaction::VerletListLennardJones, espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >, espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >, espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >, espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >, espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >, espressopp::interaction::VerletListAdressATATInteractionTemplate< _Potential1, _Potential2 >, espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >, espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >, espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >, espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >, espressopp::interaction::VerletListAdressCGInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >, espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >, espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >, espressopp::interaction::VerletListInteractionTemplate< _Potential >, espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >, espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >, espressopp::interaction::FixedPairListInteractionTemplate< _Potential >, espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >, espressopp::interaction::SingleParticleInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >, espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >, espressopp::interaction::VSphereSelfInteractionTemplate< _Potential >, espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >, and espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >.
Referenced by registerPython().
computeVirial()
virtual real espressopp::interaction::Interaction::computeVirial () pure virtual
Implemented in espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >, espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >, espressopp::interaction::VerletListAdressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >, espressopp::vectorization::interaction::VerletListLennardJones, espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >, espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >, espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >, espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >, espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >, espressopp::interaction::VerletListAdressATATInteractionTemplate< _Potential1, _Potential2 >, espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >, espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >, espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >, espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >, espressopp::interaction::VerletListAdressCGInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >, espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >, espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >, espressopp::interaction::VerletListInteractionTemplate< _Potential >, espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >, espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >, espressopp::interaction::FixedPairListInteractionTemplate< _Potential >, espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >, espressopp::interaction::SingleParticleInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >, espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >, espressopp::interaction::VSphereSelfInteractionTemplate< _Potential >, espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >, and espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >.
Referenced by registerPython().
computeVirialTensor() [1/3]
virtual void espressopp::interaction::Interaction::computeVirialTensor (Tensor & w) pure virtual
Implemented in espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >, espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >, espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >, espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >, espressopp::interaction::VerletListAdressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >, espressopp::vectorization::interaction::VerletListLennardJones, espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >, espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >, espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >, espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >, espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >, espressopp::interaction::VerletListAdressATATInteractionTemplate< _Potential1, _Potential2 >, espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >, espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >, espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >, espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >, espressopp::interaction::VerletListAdressCGInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >, espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >, espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >, espressopp::interaction::VerletListInteractionTemplate< _Potential >, espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >, espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >, espressopp::interaction::FixedPairListInteractionTemplate< _Potential >, espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >, espressopp::interaction::SingleParticleInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >, espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >, and espressopp::interaction::VSphereSelfInteractionTemplate< _Potential >.
computeVirialTensor() [2/3]
virtual void espressopp::interaction::Interaction::computeVirialTensor (Tensor & w, real z) pure virtual
Implemented in espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >, espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >, espressopp::interaction::VerletListAdressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >, espressopp::vectorization::interaction::VerletListLennardJones, espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >, espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >, espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >, espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >, espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >, espressopp::interaction::VerletListAdressATATInteractionTemplate< _Potential1, _Potential2 >, espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >, espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >, espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >, espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >, espressopp::interaction::VerletListAdressCGInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >, espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >, espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >, espressopp::interaction::VerletListInteractionTemplate< _Potential >, espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >, espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >, espressopp::interaction::FixedPairListInteractionTemplate< _Potential >, espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >, espressopp::interaction::SingleParticleInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >, espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >, espressopp::interaction::VSphereSelfInteractionTemplate< _Potential >, espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >, and espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >.
computeVirialTensor() [3/3]
virtual void espressopp::interaction::Interaction::computeVirialTensor (Tensor * w, int n) pure virtual
Implemented in espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >, espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >, espressopp::interaction::VerletListAdressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >, espressopp::vectorization::interaction::VerletListLennardJones, espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >, espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >, espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >, espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >, espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >, espressopp::interaction::VerletListAdressATATInteractionTemplate< _Potential1, _Potential2 >, espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >, espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >, espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >, espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >, espressopp::interaction::VerletListAdressCGInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >, espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >, espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >, espressopp::interaction::VerletListInteractionTemplate< _Potential >, espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >, espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >, espressopp::interaction::FixedPairListInteractionTemplate< _Potential >, espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >, espressopp::interaction::SingleParticleInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >, espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >, espressopp::interaction::VSphereSelfInteractionTemplate< _Potential >, espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >, and espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >.
computeVirialX()
virtual void espressopp::interaction::Interaction::computeVirialX (std::vector< real > & p_xx_total, int bins) pure virtual
Implemented in espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >, espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >, espressopp::interaction::VerletListAdressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >, espressopp::vectorization::interaction::VerletListLennardJones, espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >, espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >, espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >, espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >, espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >, espressopp::interaction::VerletListAdressATATInteractionTemplate< _Potential1, _Potential2 >, espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >, espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >, espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >, espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >, espressopp::interaction::VerletListAdressCGInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >, espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >, espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >, espressopp::interaction::VerletListInteractionTemplate< _Potential >, espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >, espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >, espressopp::interaction::FixedPairListInteractionTemplate< _Potential >, espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >, espressopp::interaction::SingleParticleInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >, espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >, espressopp::interaction::VSphereSelfInteractionTemplate< _Potential >, espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >, and espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >.
getMaxCutoff()
virtual real espressopp::interaction::Interaction::getMaxCutoff () pure virtual
This method returns the maximal cutoff defined for one type pair.
Implemented in espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >, espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >, espressopp::interaction::VerletListAdressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >, espressopp::vectorization::interaction::VerletListLennardJones, espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >, espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >, espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >, espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >, espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >, espressopp::interaction::VerletListAdressATATInteractionTemplate< _Potential1, _Potential2 >, espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >, espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >, espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >, espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >, espressopp::interaction::VerletListAdressCGInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >, espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >, espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >, espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >, espressopp::interaction::VerletListInteractionTemplate< _Potential >, espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >, espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >, espressopp::interaction::FixedPairListInteractionTemplate< _Potential >, espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >, espressopp::interaction::SingleParticleInteractionTemplate< _Potential >, espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >, espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >, espressopp::interaction::VSphereSelfInteractionTemplate< _Potential >, espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >, and espressopp::interaction::CellListAllParticlesInteractionTemplate< _Potential >.
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Interaction::LOG4ESPP_DECL_LOGGER (theLogger) static protected
Logger.
registerPython()
void espressopp::interaction::Interaction::registerPython () static
Definition at line 36 of file Interaction.cpp.
References bondType(), computeEnergy(), computeEnergyAA(), computeEnergyCG(), computeEnergyDeriv(), and computeVirial().
Referenced by espressopp::interaction::registerPython().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/Interaction.hpp
/home/espressopp/espressopp/src/interaction/Interaction.cpp