ESPResSo++: espressopp::interaction::SingleParticlePotential Class Reference
espressopp::interaction::SingleParticlePotential Class Reference abstract
This class is used to define single-particle interactions, typically used for external forces on the system.
#include <SingleParticlePotential.hpp>
Public Member Functions
virtual real computeEnergy (const Particle &p, const bc::BC &bc) const =0
virtual Real3D computeForce (const Particle &p, const bc::BC &bc) const =0
virtual real getMaxCutoff ()=0
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Detailed Description
This class is used to define single-particle interactions, typically used for external forces on the system.
The potential may depend on any of the particle properties (type, mass, etc.).
Definition at line 43 of file SingleParticlePotential.hpp.
Member Function Documentation
computeEnergy()
virtual real espressopp::interaction::SingleParticlePotential::computeEnergy (const Particle & p, const bc::BC & bc) const pure virtual
Implemented in espressopp::interaction::SingleParticlePotentialTemplate< Derived >, espressopp::interaction::SingleParticlePotentialTemplate< HarmonicTrap >, and espressopp::interaction::SingleParticlePotentialTemplate< LennardJones93Wall >.
Referenced by registerPython(), and espressopp::interaction::SingleParticlePotentialTemplate< LennardJones93Wall >::~SingleParticlePotentialTemplate().
computeForce()
virtual Real3D espressopp::interaction::SingleParticlePotential::computeForce (const Particle & p, const bc::BC & bc) const pure virtual
Implemented in espressopp::interaction::SingleParticlePotentialTemplate< Derived >, espressopp::interaction::SingleParticlePotentialTemplate< HarmonicTrap >, and espressopp::interaction::SingleParticlePotentialTemplate< LennardJones93Wall >.
Referenced by registerPython(), and espressopp::interaction::SingleParticlePotentialTemplate< LennardJones93Wall >::~SingleParticlePotentialTemplate().
getMaxCutoff()
virtual real espressopp::interaction::SingleParticlePotential::getMaxCutoff () pure virtual
Implemented in espressopp::interaction::LennardJones93Wall, and espressopp::interaction::HarmonicTrap.
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::SingleParticlePotential::LOG4ESPP_DECL_LOGGER (theLogger) static
registerPython()
void espressopp::interaction::SingleParticlePotential::registerPython () static
Definition at line 38 of file SingleParticlePotential.cpp.
References computeEnergy(), and computeForce().
Referenced by espressopp::interaction::registerPython().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/SingleParticlePotential.hpp
/home/espressopp/espressopp/src/interaction/SingleParticlePotential.cpp