ESPResSo++: espressopp::FixedLocalTupleList Class Reference
espressopp::FixedLocalTupleList Class Reference
#include <FixedLocalTupleList.hpp>
Public Types
typedef ESPPIterator< std::map< Particle *, std::vector< Particle * > > > Iterator
Public Member Functions
FixedLocalTupleList (shared_ptr< storage::Storage > _storage)
virtual ~FixedLocalTupleList ()
virtual bool addTuple (boost::python::list &tuple)
virtual void beforeSendParticles (ParticleList &pl, class OutBuffer &buf)
void afterRecvParticles (ParticleList &pl, class InBuffer &buf)
virtual void onParticlesChanged ()
python::list getTuples ()
int size ()
Get the number of triples in the GlobalTriples list.
void add (Particle *p, std::vector< Particle *> particles)
Static Public Member Functions
static void registerPython ()
Protected Types
typedef std::vector< longint > tuple
typedef std::multimap< longint, tuple > GlobalTuples
typedef std::map< Particle *, std::vector< Particle * > > Super
Protected Attributes
boost::signals2::connection con1
boost::signals2::connection con2
boost::signals2::connection con3
shared_ptr< storage::Storage > storage
GlobalTuples globalTuples
Static Private Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Detailed Description
Definition at line 34 of file FixedLocalTupleList.hpp.
Member Typedef Documentation
GlobalTuples
typedef std::multimap<longint,tuple > espressopp::FixedLocalTupleList::GlobalTuples protected
Definition at line 39 of file FixedLocalTupleList.hpp.
Iterator
typedef ESPPIterator<std::map< Particle *, std::vector< Particle *> > > espressopp::esutil::ESPPContainer< std::map< Particle *, std::vector< Particle *> > >::Iterator inherited
Definition at line 66 of file ESPPIterator.hpp.
Super
typedef std::map< Particle *, std::vector< Particle *> > espressopp::esutil::ESPPContainer< std::map< Particle *, std::vector< Particle *> > >::Super protected inherited
Definition at line 64 of file ESPPIterator.hpp.
tuple
typedef std::vector<longint> espressopp::FixedLocalTupleList::tuple protected
Definition at line 38 of file FixedLocalTupleList.hpp.
Constructor & Destructor Documentation
FixedLocalTupleList()
espressopp::FixedLocalTupleList::FixedLocalTupleList (shared_ptr< storage::Storage > _storage)
Definition at line 36 of file FixedLocalTupleList.cpp.
References afterRecvParticles(), beforeSendParticles(), con1, con2, con3, LOG4ESPP_INFO, onParticlesChanged(), and storage.
~FixedLocalTupleList()
espressopp::FixedLocalTupleList::~FixedLocalTupleList () virtual
Definition at line 49 of file FixedLocalTupleList.cpp.
References addTuple(), con1, con2, con3, and LOG4ESPP_INFO.
Member Function Documentation
add()
void espressopp::TupleList::add (Particle * p, std::vector< Particle *> particles) inline inherited
Definition at line 472 of file Particle.hpp.
Referenced by addTuple(), espressopp::FixedTupleList::addTuple(), onParticlesChanged(), and espressopp::FixedTupleList::onParticlesChanged().
addTuple()
bool espressopp::FixedLocalTupleList::addTuple (boost::python::list & tuple) virtual
Definition at line 59 of file FixedLocalTupleList.cpp.
References espressopp::TupleList::add(), espressopp::esutil::Error::checkException(), espressopp::System::comm, globalTuples, LOG4ESPP_INFO, espressopp::esutil::Error::setException(), and storage.
Referenced by registerPython(), and ~FixedLocalTupleList().
afterRecvParticles()
void espressopp::FixedLocalTupleList::afterRecvParticles (ParticleList & pl, class InBuffer & buf)
Definition at line 157 of file FixedLocalTupleList.cpp.
References globalTuples, LOG4ESPP_DEBUG, espressopp::InBuffer::read(), and size().
Referenced by beforeSendParticles(), and FixedLocalTupleList().
beforeSendParticles()
void espressopp::FixedLocalTupleList::beforeSendParticles (ParticleList & pl, class OutBuffer & buf) virtual
Definition at line 126 of file FixedLocalTupleList.cpp.
References afterRecvParticles(), globalTuples, espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_DEBUG, and espressopp::OutBuffer::write().
Referenced by FixedLocalTupleList(), and getTuples().
getTuples()
python::list espressopp::FixedLocalTupleList::getTuples ()
Definition at line 109 of file FixedLocalTupleList.cpp.
References beforeSendParticles(), and globalTuples.
Referenced by registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::FixedLocalTupleList::LOG4ESPP_DECL_LOGGER (theLogger) static private
Referenced by size().
onParticlesChanged()
void espressopp::FixedLocalTupleList::onParticlesChanged () virtual
Definition at line 186 of file FixedLocalTupleList.cpp.
References espressopp::TupleList::add(), espressopp::System::comm, globalTuples, LOG4ESPP_INFO, espressopp::esutil::Error::setException(), and storage.
Referenced by FixedLocalTupleList().
registerPython()
void espressopp::FixedLocalTupleList::registerPython () static
Definition at line 231 of file FixedLocalTupleList.cpp.
References addTuple(), getTuples(), and size().
Referenced by espressopp::registerPython(), and size().
size()
int espressopp::FixedLocalTupleList::size () inline
Get the number of triples in the GlobalTriples list.
Definition at line 54 of file FixedLocalTupleList.hpp.
References LOG4ESPP_DECL_LOGGER(), and registerPython().
Referenced by afterRecvParticles(), and registerPython().
Member Data Documentation
con1
boost::signals2::connection espressopp::FixedLocalTupleList::con1 protected
Definition at line 36 of file FixedLocalTupleList.hpp.
Referenced by FixedLocalTupleList(), and ~FixedLocalTupleList().
con2
boost::signals2::connection espressopp::FixedLocalTupleList::con2 protected
Definition at line 36 of file FixedLocalTupleList.hpp.
Referenced by FixedLocalTupleList(), and ~FixedLocalTupleList().
con3
boost::signals2::connection espressopp::FixedLocalTupleList::con3 protected
Definition at line 36 of file FixedLocalTupleList.hpp.
Referenced by FixedLocalTupleList(), and ~FixedLocalTupleList().
globalTuples
GlobalTuples espressopp::FixedLocalTupleList::globalTuples protected
Definition at line 40 of file FixedLocalTupleList.hpp.
Referenced by addTuple(), afterRecvParticles(), beforeSendParticles(), getTuples(), and onParticlesChanged().
storage
shared_ptr<storage::Storage> espressopp::FixedLocalTupleList::storage protected
Definition at line 37 of file FixedLocalTupleList.hpp.
Referenced by addTuple(), FixedLocalTupleList(), and onParticlesChanged().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/FixedLocalTupleList.hpp
/home/espressopp/espressopp/src/FixedLocalTupleList.cpp