ESPResSo++: espressopp::FixedPairDistList Class Reference
espressopp::FixedPairDistList Class Reference
#include <FixedPairDistList.hpp>
Public Types
typedef ESPPIterator
< std::vector< ParticlePair > > Iterator
Public Member Functions
FixedPairDistList (shared_ptr< storage::Storage > _storage)
virtual ~FixedPairDistList ()
virtual bool add (longint pid1, longint pid2)
Add the given particle pair to the list on this processor if the
particle with the lower id belongs to this processor.
virtual void beforeSendParticles (ParticleList &pl, class OutBuffer &buf)
void afterRecvParticles (ParticleList &pl, class InBuffer &buf)
virtual void onParticlesChanged ()
python::list getPairs ()
python::list getPairsDist ()
real getDist (int, int)
int size ()
Get the number of bonds in the GlobalPairs list.
void add (Particle *p1, Particle *p2)
void add (Particle &p1, Particle &p2)
void add (std::vector< Particle * > particles)
Static Public Member Functions
static void registerPython ()
Protected Types
typedef std::multimap< longint,
std::pair< longint, real > > PairsDist
typedef std::vector< ParticlePair > Super
Protected Attributes
boost::signals2::connection con1
boost::signals2::connection con2
boost::signals2::connection con3
shared_ptr< storage::Storage > storage
PairsDist pairsDist
Static Private Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Detailed Description
Definition at line 39 of file FixedPairDistList.hpp.
Member Typedef Documentation
typedef ESPPIterator<std::vector< ParticlePair > > espressopp::esutil::ESPPContainer< std::vector< ParticlePair > >::Iterator inherited
Definition at line 66 of file ESPPIterator.hpp.
typedef std::multimap<longint, std::pair<longint, real> > espressopp::FixedPairDistList::PairsDist protected
Definition at line 41 of file FixedPairDistList.hpp.
typedef std::vector< ParticlePair > espressopp::esutil::ESPPContainer< std::vector< ParticlePair > >::Super protected inherited
Definition at line 64 of file ESPPIterator.hpp.
Constructor & Destructor Documentation
espressopp::FixedPairDistList::FixedPairDistList (shared_ptr< storage::Storage > _storage)
Definition at line 36 of file FixedPairDistList.cpp.
References afterRecvParticles(), beforeSendParticles(), con1, con2, con3, LOG4ESPP_INFO, onParticlesChanged(), and storage.
espressopp::FixedPairDistList::~FixedPairDistList () virtual
Definition at line 49 of file FixedPairDistList.cpp.
References con1, con2, con3, and LOG4ESPP_INFO.
Member Function Documentation
bool espressopp::FixedPairDistList::add (longint pid1, longint pid2) virtual
Add the given particle pair to the list on this processor if the
particle with the lower id belongs to this processor.
Note that this routine does not check whether the pair is inserted on another processor as well.
Returns
whether the particle was inserted on this processor.
Definition at line 59 of file FixedPairDistList.cpp.
References espressopp::Real3D::abs(), espressopp::System::bc, espressopp::esutil::Error::checkException(), espressopp::System::comm, LOG4ESPP_INFO, pairsDist, espressopp::Particle::position(), espressopp::esutil::Error::setException(), and storage.
Referenced by onParticlesChanged(), and registerPython().
void espressopp::PairList::add (Particle * p1, Particle * p2) inline inherited
Definition at line 395 of file Particle.hpp.
Referenced by espressopp::FixedListComm::add(), espressopp::PairList::add(), espressopp::VerletList::checkPair(), espressopp::VerletListAdress::checkPair(), and espressopp::FixedListComm::onParticlesChanged().
void espressopp::PairList::add (Particle & p1, Particle & p2) inline inherited
Definition at line 399 of file Particle.hpp.
References espressopp::PairList::add().
Referenced by espressopp::PairList::add().
void espressopp::PairList::add (std::vector< Particle * > particles) inline inherited
Definition at line 402 of file Particle.hpp.
References espressopp::PairList::add().
void espressopp::FixedPairDistList::afterRecvParticles (ParticleList & pl, class InBuffer & buf)
Definition at line 194 of file FixedPairDistList.cpp.
References LOG4ESPP_ERROR, LOG4ESPP_INFO, pairsDist, espressopp::InBuffer::read(), and size().
Referenced by FixedPairDistList().
void espressopp::FixedPairDistList::beforeSendParticles (ParticleList & pl, class OutBuffer & buf) virtual
Definition at line 149 of file FixedPairDistList.cpp.
References espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_DEBUG, LOG4ESPP_INFO, pairsDist, and espressopp::OutBuffer::write().
Referenced by FixedPairDistList().
real espressopp::FixedPairDistList::getDist (int pid1, int pid2)
Definition at line 124 of file FixedPairDistList.cpp.
References pairsDist.
Referenced by registerPython().
python::list espressopp::FixedPairDistList::getPairs ()
Definition at line 102 of file FixedPairDistList.cpp.
References pairsDist.
Referenced by registerPython().
python::list espressopp::FixedPairDistList::getPairsDist ()
Definition at line 113 of file FixedPairDistList.cpp.
References pairsDist.
Referenced by registerPython().
static espressopp::FixedPairDistList::LOG4ESPP_DECL_LOGGER (theLogger) static private
void espressopp::FixedPairDistList::onParticlesChanged () virtual
Definition at line 224 of file FixedPairDistList.cpp.
References add(), espressopp::esutil::Error::checkException(), espressopp::System::comm, LOG4ESPP_INFO, pairsDist, espressopp::esutil::Error::setException(), and storage.
Referenced by FixedPairDistList().
void espressopp::FixedPairDistList::registerPython () static
Definition at line 263 of file FixedPairDistList.cpp.
References add(), getDist(), getPairs(), getPairsDist(), and size().
Referenced by espressopp::registerPython().
int espressopp::FixedPairDistList::size () inline
Get the number of bonds in the GlobalPairs list.
Definition at line 68 of file FixedPairDistList.hpp.
References pairsDist.
Referenced by afterRecvParticles(), and registerPython().
Member Data Documentation
boost::signals2::connection espressopp::FixedPairDistList::con1 protected
Definition at line 42 of file FixedPairDistList.hpp.
Referenced by FixedPairDistList(), and ~FixedPairDistList().
boost::signals2::connection espressopp::FixedPairDistList::con2 protected
Definition at line 42 of file FixedPairDistList.hpp.
Referenced by FixedPairDistList(), and ~FixedPairDistList().
boost::signals2::connection espressopp::FixedPairDistList::con3 protected
Definition at line 42 of file FixedPairDistList.hpp.
Referenced by FixedPairDistList(), and ~FixedPairDistList().
PairsDist espressopp::FixedPairDistList::pairsDist protected
Definition at line 44 of file FixedPairDistList.hpp.
Referenced by add(), afterRecvParticles(), beforeSendParticles(), getDist(), getPairs(), getPairsDist(), onParticlesChanged(), and size().
shared_ptr<storage::Storage> espressopp::FixedPairDistList::storage protected
Definition at line 43 of file FixedPairDistList.hpp.
Referenced by add(), FixedPairDistList(), and onParticlesChanged().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/FixedPairDistList.hpp
/home/travis/build/espressopp/espressopp/src/FixedPairDistList.cpp