ESPResSo++: espressopp::esutil::Grid Class Reference
espressopp::esutil::Grid Class Reference
regular grid decomposition of a box, outside view.
#include <Grid.hpp>
Public Member Functions
Grid ()
Grid (int x, int y, int z)
Grid (const Int3D &_size)
longint getGridSize (int i) const
const Int3D & getGridSize () const
longint getNumberOfCells () const
longint mapPositionToIndex (int p1, int p2, int p3) const
convert a grid position to a unique sequence index
longint mapPositionToIndex (const Int3D &pos) const
void mapIndexToPosition (int &p1, int &p2, int &p3, longint index) const
convert a sequence index back to a grid position
void mapIndexToPosition (Int3D &pos, longint index) const
Static Public Member Functions
static void registerPython ()
Private Attributes
Int3D size
number of grid points
Detailed Description
regular grid decomposition of a box, outside view.
Definition at line 33 of file Grid.hpp.
Constructor & Destructor Documentation
Grid() [1/3]
espressopp::esutil::Grid::Grid () inline
Definition at line 35 of file Grid.hpp.
Grid() [2/3]
espressopp::esutil::Grid::Grid (int x, int y, int z) inline
Definition at line 37 of file Grid.hpp.
References size.
Grid() [3/3]
espressopp::esutil::Grid::Grid (const Int3D & _size) inline
Definition at line 43 of file Grid.hpp.
References size.
Member Function Documentation
getGridSize() [1/2]
longint espressopp::esutil::Grid::getGridSize (int i) const inline
Definition at line 49 of file Grid.hpp.
References size.
Referenced by espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::storage::DomainDecomposition::getInt3DNodeGrid(), and espressopp::integrator::AssociationReaction::sendMultiMap().
getGridSize() [2/2]
const Int3D& espressopp::esutil::Grid::getGridSize () const inline
Definition at line 50 of file Grid.hpp.
References size.
Referenced by espressopp::storage::NodeGrid::calcNodeNeighbors(), espressopp::CellGrid::getFrameGridSize(), espressopp::CellGrid::getGridSize(), espressopp::CellGrid::getInnerCellsEnd(), espressopp::CellGrid::getNumberOfInnerCells(), espressopp::storage::NodeGrid::mapPositionToNodeClipped(), and espressopp::storage::NodeGrid::NodeGrid().
getNumberOfCells()
longint espressopp::esutil::Grid::getNumberOfCells () const inline
Definition at line 52 of file Grid.hpp.
References size.
Referenced by espressopp::storage::DomainDecomposition::createCellGrid(), and espressopp::storage::DomainDecompositionAdress::createCellGrid().
mapIndexToPosition() [1/2]
void espressopp::esutil::Grid::mapIndexToPosition (int & p1, int & p2, int & p3, longint index) const inline
convert a sequence index back to a grid position
Definition at line 67 of file Grid.hpp.
References size.
Referenced by espressopp::storage::NodeGrid::calcNodeNeighbors(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), and mapIndexToPosition().
mapIndexToPosition() [2/2]
void espressopp::esutil::Grid::mapIndexToPosition (Int3D & pos, longint index) const inline
Definition at line 75 of file Grid.hpp.
References mapIndexToPosition(), and registerPython().
mapPositionToIndex() [1/2]
longint espressopp::esutil::Grid::mapPositionToIndex (int p1, int p2, int p3) const inline
convert a grid position to a unique sequence index
Definition at line 61 of file Grid.hpp.
References size.
Referenced by espressopp::storage::NodeGrid::calcNodeNeighbors(), espressopp::storage::DomainDecomposition::fillCells(), espressopp::storage::DomainDecompositionAdress::fillCells(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::storage::DomainDecomposition::initCellInteractions(), espressopp::storage::DomainDecompositionAdress::initCellInteractions(), espressopp::CellGrid::mapPositionToCell(), espressopp::CellGrid::mapPositionToCellChecked(), espressopp::CellGrid::mapPositionToCellCheckedAndClipped(), espressopp::CellGrid::mapPositionToCellClipped(), mapPositionToIndex(), espressopp::storage::NodeGrid::mapPositionToNodeClipped(), espressopp::storage::DomainDecomposition::markCells(), and espressopp::storage::DomainDecompositionAdress::markCells().
mapPositionToIndex() [2/2]
longint espressopp::esutil::Grid::mapPositionToIndex (const Int3D & pos) const inline
Definition at line 63 of file Grid.hpp.
References mapPositionToIndex().
registerPython()
void espressopp::esutil::Grid::registerPython () static
Definition at line 38 of file Grid.cpp.
References espressopp::esutil::mapIndexToPositionInt3D.
Referenced by mapIndexToPosition(), and espressopp::esutil::registerPython().
Member Data Documentation
size
Int3D espressopp::esutil::Grid::size private
number of grid points
Definition at line 83 of file Grid.hpp.
Referenced by getGridSize(), getNumberOfCells(), Grid(), mapIndexToPosition(), and mapPositionToIndex().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/esutil/Grid.hpp
/home/espressopp/espressopp/src/esutil/Grid.cpp