ESPResSo++: espressopp::FixedQuadrupleListAdress Class Reference
espressopp::FixedQuadrupleListAdress Class Reference
#include <FixedQuadrupleListAdress.hpp>
Public Types
typedef ESPPIterator
< std::vector
< ParticleQuadruple > > Iterator
Public Member Functions
FixedQuadrupleListAdress (shared_ptr< storage::Storage > _storage, shared_ptr< FixedTupleListAdress > _fixedtupleList)
~FixedQuadrupleListAdress ()
bool add (longint pid1, longint pid2, longint pid3, longint pid4)
Add the given particle quadruple to the list on this processor if the particle with the lower id belongs to this processor.
void beforeSendParticles (ParticleList &pl, class OutBuffer &buf)
void beforeSendATParticles (std::vector< longint > &atpl, class OutBuffer &buf)
void onParticlesChanged ()
void add (Particle *p1, Particle *p2, Particle *p3, Particle *p4)
void add (Particle &p1, Particle &p2, Particle &p3, Particle &p4)
void add (std::vector< Particle * > particles)
void afterRecvParticles (ParticleList &pl, class InBuffer &buf)
python::list getQuadruples ()
int size ()
Get the number of quadruples in the GlobalQuadruples list.
Static Public Member Functions
static void registerPython ()
Protected Types
typedef
boost::unordered_multimap
< longint, Triple< longint,
longint, longint > > GlobalQuadruples
typedef std::vector
< ParticleQuadruple > Super
Protected Attributes
boost::signals2::connection sigBeforeSendAT
boost::signals2::connection sigAfterRecvAT
boost::signals2::connection sigBeforeSend
boost::signals2::connection sigAfterRecv
boost::signals2::connection sigOnParticlesChanged
shared_ptr< storage::Storage > storage
GlobalQuadruples globalQuadruples
Static Private Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Private Attributes
shared_ptr< FixedTupleListAdress > fixedtupleList
Detailed Description
Definition at line 40 of file FixedQuadrupleListAdress.hpp.
Member Typedef Documentation
typedef boost::unordered_multimap< longint, Triple < longint, longint, longint > > espressopp::FixedQuadrupleList::GlobalQuadruples protected inherited
Definition at line 43 of file FixedQuadrupleList.hpp.
typedef ESPPIterator<std::vector< ParticleQuadruple > > espressopp::esutil::ESPPContainer< std::vector< ParticleQuadruple > >::Iterator inherited
Definition at line 66 of file ESPPIterator.hpp.
typedef std::vector< ParticleQuadruple > espressopp::esutil::ESPPContainer< std::vector< ParticleQuadruple > >::Super protected inherited
Definition at line 64 of file ESPPIterator.hpp.
Constructor & Destructor Documentation
espressopp::FixedQuadrupleListAdress::FixedQuadrupleListAdress (shared_ptr< storage::Storage > _storage, shared_ptr< FixedTupleListAdress > _fixedtupleList)
Definition at line 39 of file FixedQuadrupleListAdress.cpp.
References espressopp::FixedQuadrupleList::afterRecvParticles(), beforeSendATParticles(), fixedtupleList, LOG4ESPP_INFO, espressopp::FixedQuadrupleList::sigAfterRecv, sigAfterRecvAT, espressopp::FixedQuadrupleList::sigBeforeSend, and sigBeforeSendAT.
espressopp::FixedQuadrupleListAdress::~FixedQuadrupleListAdress ()
Definition at line 55 of file FixedQuadrupleListAdress.cpp.
References LOG4ESPP_INFO, sigAfterRecvAT, and sigBeforeSendAT.
Member Function Documentation
bool espressopp::FixedQuadrupleListAdress::add (longint pid1, longint pid2, longint pid3, longint pid4)
Add the given particle quadruple to the list on this processor if the particle with the lower id belongs to this processor.
Note that this routine does not check whether the quadruple is inserted on another processor as well.
Returns
whether the quadruple was inserted on this processor.
Definition at line 61 of file FixedQuadrupleListAdress.cpp.
References espressopp::esutil::Error::checkException(), espressopp::System::comm, espressopp::FixedQuadrupleList::globalQuadruples, LOG4ESPP_INFO, espressopp::esutil::Error::setException(), and espressopp::FixedQuadrupleList::storage.
Referenced by onParticlesChanged(), and registerPython().
void espressopp::QuadrupleList::add (Particle * p1, Particle * p2, Particle * p3, Particle * p4) inline inherited
Definition at line 455 of file Particle.hpp.
Referenced by espressopp::FixedListComm::add(), espressopp::QuadrupleList::add(), and espressopp::FixedListComm::onParticlesChanged().
void espressopp::QuadrupleList::add (Particle & p1, Particle & p2, Particle & p3, Particle & p4) inline inherited
Definition at line 459 of file Particle.hpp.
References espressopp::QuadrupleList::add().
Referenced by espressopp::QuadrupleList::add().
void espressopp::QuadrupleList::add (std::vector< Particle * > particles) inline inherited
Definition at line 462 of file Particle.hpp.
References espressopp::QuadrupleList::add().
void espressopp::FixedQuadrupleList::afterRecvParticles (ParticleList & pl, class InBuffer & buf) inherited
Definition at line 201 of file FixedQuadrupleList.cpp.
References espressopp::FixedQuadrupleList::globalQuadruples, LOG4ESPP_INFO, espressopp::InBuffer::read(), and espressopp::FixedQuadrupleList::size().
Referenced by espressopp::FixedQuadrupleList::FixedQuadrupleList(), and FixedQuadrupleListAdress().
void espressopp::FixedQuadrupleListAdress::beforeSendATParticles (std::vector< longint > & atpl, class OutBuffer & buf)
Definition at line 122 of file FixedQuadrupleListAdress.cpp.
References espressopp::FixedQuadrupleList::globalQuadruples, LOG4ESPP_DEBUG, LOG4ESPP_INFO, and espressopp::OutBuffer::write().
Referenced by FixedQuadrupleListAdress().
void espressopp::FixedQuadrupleListAdress::beforeSendParticles (ParticleList & pl, class OutBuffer & buf)
Definition at line 161 of file FixedQuadrupleListAdress.cpp.
python::list espressopp::FixedQuadrupleList::getQuadruples () inherited
Definition at line 147 of file FixedQuadrupleList.cpp.
References espressopp::FixedQuadrupleList::globalQuadruples.
Referenced by registerPython(), and espressopp::FixedQuadrupleList::registerPython().
static espressopp::FixedQuadrupleListAdress::LOG4ESPP_DECL_LOGGER (theLogger) static private
void espressopp::FixedQuadrupleListAdress::onParticlesChanged () virtual
Reimplemented from espressopp::FixedQuadrupleList.
Definition at line 165 of file FixedQuadrupleListAdress.cpp.
References add(), espressopp::esutil::Error::checkException(), espressopp::System::comm, espressopp::FixedQuadrupleList::globalQuadruples, LOG4ESPP_INFO, espressopp::esutil::Error::setException(), and espressopp::FixedQuadrupleList::storage.
void espressopp::FixedQuadrupleListAdress::registerPython () static
Definition at line 216 of file FixedQuadrupleListAdress.cpp.
References add(), espressopp::FixedQuadrupleList::getQuadruples(), and espressopp::FixedQuadrupleList::size().
Referenced by espressopp::registerPython().
int espressopp::FixedQuadrupleList::size () inline inherited
Get the number of quadruples in the GlobalQuadruples list.
Definition at line 66 of file FixedQuadrupleList.hpp.
References espressopp::FixedQuadrupleList::globalQuadruples.
Referenced by espressopp::FixedQuadrupleList::afterRecvParticles(), registerPython(), and espressopp::FixedQuadrupleList::registerPython().
Member Data Documentation
shared_ptr<FixedTupleListAdress> espressopp::FixedQuadrupleListAdress::fixedtupleList private
Definition at line 65 of file FixedQuadrupleListAdress.hpp.
Referenced by FixedQuadrupleListAdress().
GlobalQuadruples espressopp::FixedQuadrupleList::globalQuadruples protected inherited
Definition at line 44 of file FixedQuadrupleList.hpp.
Referenced by add(), espressopp::FixedQuadrupleList::add(), espressopp::FixedQuadrupleList::afterRecvParticles(), beforeSendATParticles(), espressopp::FixedQuadrupleList::beforeSendParticles(), espressopp::FixedQuadrupleList::getQuadruples(), onParticlesChanged(), espressopp::FixedQuadrupleList::onParticlesChanged(), and espressopp::FixedQuadrupleList::size().
boost::signals2::connection espressopp::FixedQuadrupleList::sigAfterRecv protected inherited
Definition at line 40 of file FixedQuadrupleList.hpp.
Referenced by espressopp::FixedQuadrupleList::FixedQuadrupleList(), FixedQuadrupleListAdress(), and espressopp::FixedQuadrupleList::~FixedQuadrupleList().
boost::signals2::connection espressopp::FixedQuadrupleListAdress::sigAfterRecvAT protected
Definition at line 62 of file FixedQuadrupleListAdress.hpp.
Referenced by FixedQuadrupleListAdress(), and ~FixedQuadrupleListAdress().
boost::signals2::connection espressopp::FixedQuadrupleList::sigBeforeSend protected inherited
Definition at line 40 of file FixedQuadrupleList.hpp.
Referenced by espressopp::FixedQuadrupleList::FixedQuadrupleList(), FixedQuadrupleListAdress(), and espressopp::FixedQuadrupleList::~FixedQuadrupleList().
boost::signals2::connection espressopp::FixedQuadrupleListAdress::sigBeforeSendAT protected
Definition at line 62 of file FixedQuadrupleListAdress.hpp.
Referenced by FixedQuadrupleListAdress(), and ~FixedQuadrupleListAdress().
boost::signals2::connection espressopp::FixedQuadrupleList::sigOnParticlesChanged protected inherited
Definition at line 40 of file FixedQuadrupleList.hpp.
Referenced by espressopp::FixedQuadrupleList::FixedQuadrupleList(), and espressopp::FixedQuadrupleList::~FixedQuadrupleList().
shared_ptr< storage::Storage > espressopp::FixedQuadrupleList::storage protected inherited
Definition at line 41 of file FixedQuadrupleList.hpp.
Referenced by add(), espressopp::FixedQuadrupleList::add(), espressopp::FixedQuadrupleList::FixedQuadrupleList(), onParticlesChanged(), and espressopp::FixedQuadrupleList::onParticlesChanged().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/FixedQuadrupleListAdress.hpp
/home/travis/build/espressopp/espressopp/src/FixedQuadrupleListAdress.cpp