ESPResSo++: espressopp::integrator::AssociationReaction Class Reference
espressopp::integrator::AssociationReaction Class Reference
Reaction scheme for polymer growth and curing/crosslinking.
#include <AssociationReaction.hpp>
Public Types
enum ExtensionType {
all =0, Thermostat =1, Barostat =2, Constraint =3,
Adress =4, FreeEnergyCompensation =5, ExtForce =6, ExtAnalysis =7,
Reaction =8
}
Public Member Functions
AssociationReaction (shared_ptr< System > system, shared_ptr< VerletList > _verletList, shared_ptr< FixedPairList > _fixedPairList, shared_ptr< DomainDecomposition > _domdec)
~AssociationReaction ()
void setRate (real rate)
real getRate ()
void setCutoff (real cutoff)
real getCutoff ()
void setTypeA (size_t typeA)
size_t getTypeA ()
void setTypeB (size_t typeB)
size_t getTypeB ()
void setDeltaA (int deltaA)
int getDeltaA ()
void setDeltaB (int deltaB)
int getDeltaB ()
void setStateAMin (int stateAMin)
int getStateAMin ()
void setInterval (int interval)
int getInterval ()
void initialize ()
void react ()
Actual reaction step.
void sendMultiMap (boost::unordered_multimap< longint, longint > &mm)
Performs two-way parallel communication to consolidate mm between neighbours.
void uniqueA (boost::unordered_multimap< longint, longint > &mm)
Given a multimap mm with several pairs (id1,id2), keep only one pair for each id1 and return it in place.
void uniqueB (boost::unordered_multimap< longint, longint > &mm, boost::unordered_multimap< longint, longint > &nn)
Given a multimap mm with several pairs (id1,id2), keep only one pair for each id2 and return it in place.
void applyAR ()
Use the (A,B) list "partners" to add bonds and change the state of the particles accordingly.
ExtensionType getType ()
void setType (ExtensionType k)
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
Register this class so it can be used from Python.
Public Attributes
ExtensionType type
Protected Member Functions
void setIntegrator (shared_ptr< MDIntegrator > _integrator)
Protected Attributes
shared_ptr< MDIntegrator > integrator
Private Member Functions
void reactPair (Particle &p1, Particle &p2)
For a given pair of particles, check if they meet the condition the reactive scheme.
void connect ()
void disconnect ()
Static Private Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Private Attributes
boost::signals2::connection _initialize
boost::signals2::connection _react
real rate
reaction rate
real cutoff
reaction cutoff
real cutoff_sqr
reaction cutoff squared
size_t typeA
type of reactant A
size_t typeB
type of reactant B
int deltaA
state change for reactant A
int deltaB
state change for reactant B
int stateAMin
minimum state of reactant A
int interval
number of steps between reaction loops
real dt
timestep from the integrator
shared_ptr< espressopp::interaction::Potential > potential
real current_cutoff
real current_cutoff_sqr
shared_ptr< VerletList > verletList
shared_ptr< esutil::RNG > rng
random number generator used for friction term
shared_ptr< FixedPairList > fpl
shared_ptr< DomainDecomposition > domdec
boost::unordered_multimap< longint, longint > Alist
container for (A,B) potential partners
boost::unordered_multimap< longint, longint > Blist
container for (A,B) effective partners
Detailed Description
Reaction scheme for polymer growth and curing/crosslinking.
This extension enables the rate-controlled stochastic curing of polymer systems, either for chain growth of step growth, depending on the parameters.
The variables typeA, typeB, stateAMin control the particles that enter the curing reaction
where A and B may possess additional bonds not shown. An extra bond is added between A and B upon reaction.
The reaction proceeds by testing for all possible (A,B) pairs and selects them only at a given rate. It works in parallel, by gathering first the successful pairs between neigboring CPUs and ensuring that each particle enters only in one new bond per reaction step.
Definition at line 68 of file AssociationReaction.hpp.
Member Enumeration Documentation
ExtensionType
enum espressopp::integrator::Extension::ExtensionType inherited
Enumerator
all
Thermostat
Barostat
Constraint
Adress
FreeEnergyCompensation
ExtForce
ExtAnalysis
Reaction
Definition at line 48 of file Extension.hpp.
Constructor & Destructor Documentation
AssociationReaction()
espressopp::integrator::AssociationReaction::AssociationReaction (shared_ptr< System > system, shared_ptr< VerletList > _verletList, shared_ptr< FixedPairList > _fixedPairList, shared_ptr< DomainDecomposition > _domdec)
Definition at line 46 of file AssociationReaction.cpp.
References current_cutoff, current_cutoff_sqr, cutoff, deltaA, deltaB, LOG4ESPP_INFO, rate, espressopp::integrator::Extension::Reaction, rng, stateAMin, espressopp::integrator::Extension::type, typeA, typeB, and verletList.
~AssociationReaction()
espressopp::integrator::AssociationReaction::~AssociationReaction ()
Definition at line 156 of file AssociationReaction.cpp.
References disconnect().
Member Function Documentation
applyAR()
void espressopp::integrator::AssociationReaction::applyAR ()
Use the (A,B) list "partners" to add bonds and change the state of the particles accordingly.
Definition at line 449 of file AssociationReaction.cpp.
References Blist, deltaA, deltaB, fpl, espressopp::Particle::getState(), espressopp::SystemAccess::getSystemRef(), LOG4ESPP_INFO, espressopp::Particle::setState(), and espressopp::System::storage.
Referenced by react().
connect()
void espressopp::integrator::AssociationReaction::connect () private virtual
Implements espressopp::integrator::Extension.
Definition at line 166 of file AssociationReaction.cpp.
References _initialize, _react, initialize(), espressopp::integrator::Extension::integrator, and react().
Referenced by registerPython().
disconnect()
void espressopp::integrator::AssociationReaction::disconnect () private virtual
Implements espressopp::integrator::Extension.
Definition at line 160 of file AssociationReaction.cpp.
References _initialize, and _react.
Referenced by registerPython(), and ~AssociationReaction().
getCutoff()
real espressopp::integrator::AssociationReaction::getCutoff ()
Definition at line 91 of file AssociationReaction.cpp.
References cutoff.
Referenced by registerPython().
getDeltaA()
int espressopp::integrator::AssociationReaction::getDeltaA ()
Definition at line 121 of file AssociationReaction.cpp.
References deltaA.
Referenced by registerPython().
getDeltaB()
int espressopp::integrator::AssociationReaction::getDeltaB ()
Definition at line 131 of file AssociationReaction.cpp.
References deltaB.
Referenced by registerPython().
getInterval()
int espressopp::integrator::AssociationReaction::getInterval ()
Definition at line 151 of file AssociationReaction.cpp.
References interval.
Referenced by registerPython().
getRate()
real espressopp::integrator::AssociationReaction::getRate ()
Definition at line 80 of file AssociationReaction.cpp.
References rate.
Referenced by registerPython().
getStateAMin()
int espressopp::integrator::AssociationReaction::getStateAMin ()
Definition at line 141 of file AssociationReaction.cpp.
References stateAMin.
Referenced by registerPython().
getSystem()
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::LatticeBoltzmann::assignMyLattice(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::PIAdressIntegrator::computeKineticEnergy(), espressopp::integrator::PIAdressIntegrator::computeMomentumDrift(), espressopp::integrator::PIAdressIntegrator::computePositionDrift(), espressopp::integrator::PIAdressIntegrator::computeRingEnergy(), espressopp::integrator::PIAdressIntegrator::computeRingEnergyRaw(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpXTCAdress::dump(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::io::DumpXYZ::DumpXYZ(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::VerletListTriple::registerPython(), espressopp::VerletList::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), sendMultiMap(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
getSystem1()
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
getSystem2()
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
getSystemRef()
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::addForces(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::addForces(), espressopp::integrator::Adress::aftCalcF(), applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerletRESPA::calcForces(), espressopp::integrator::VelocityVerlet::calcForces(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::PIAdressIntegrator::calcForcesF(), espressopp::integrator::PIAdressIntegrator::calcForcesM(), espressopp::integrator::PIAdressIntegrator::calcForcesS(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeCOM(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeEnergy(), espressopp::integrator::PIAdressIntegrator::computeKineticEnergy(), espressopp::integrator::PIAdressIntegrator::computeMomentumDrift(), espressopp::integrator::PIAdressIntegrator::computePositionDrift(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::integrator::PIAdressIntegrator::computeRingEnergy(), espressopp::integrator::PIAdressIntegrator::computeRingEnergyRaw(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::PIAdressIntegrator::distributeForces(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::FixedLocalTupleComListInteractionTemplate(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::VelocityVerletRESPA::initForces(), espressopp::integrator::VelocityVerlet::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::PIAdressIntegrator::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::PIAdressIntegrator::initializeSetup(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::VelocityVerletRESPA::integrate1(), espressopp::integrator::VelocityVerlet::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::VelocityVerletRESPA::integrate2(), espressopp::integrator::VelocityVerlet::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::PIAdressIntegrator::integrateModePos(), espressopp::integrator::Adress::integrateSlow(), espressopp::integrator::PIAdressIntegrator::integrateV1(), espressopp::integrator::PIAdressIntegrator::integrateV2(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::PIAdressIntegrator::OUintegrate(), espressopp::integrator::VelocityVerlet::printForces(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerlet::printPositions(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), react(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::PIAdressIntegrator::run(), espressopp::integrator::VelocityVerletRESPA::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::MinimizeEnergy::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::Rattle::saveOldPos(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::PIAdressIntegrator::setWeights(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostatOnGroup::thermalize(), espressopp::integrator::LangevinThermostatOnRadius::thermalize(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::integrator::PIAdressIntegrator::transForces(), espressopp::integrator::PIAdressIntegrator::transMom1(), espressopp::integrator::PIAdressIntegrator::transMom2(), espressopp::integrator::PIAdressIntegrator::transPos1(), espressopp::integrator::PIAdressIntegrator::transPos2(), uniqueA(), uniqueB(), espressopp::io::DumpH5MD::update(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::VelocityVerletRESPA::updateForces(), espressopp::integrator::VelocityVerlet::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::PIAdressIntegrator::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
getSystemRef1()
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
getSystemRef2()
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
getType()
ExtensionType espressopp::integrator::Extension::getType () inline inherited
Definition at line 67 of file Extension.hpp.
References espressopp::integrator::Extension::type.
Referenced by espressopp::integrator::Extension::registerPython().
getTypeA()
size_t espressopp::integrator::AssociationReaction::getTypeA ()
Definition at line 101 of file AssociationReaction.cpp.
References typeA.
Referenced by registerPython().
getTypeB()
size_t espressopp::integrator::AssociationReaction::getTypeB ()
Definition at line 111 of file AssociationReaction.cpp.
References typeB.
Referenced by registerPython().
initialize()
void espressopp::integrator::AssociationReaction::initialize ()
Definition at line 226 of file AssociationReaction.cpp.
References LOG4ESPP_INFO.
Referenced by connect().
LOG4ESPP_DECL_LOGGER()
static espressopp::integrator::AssociationReaction::LOG4ESPP_DECL_LOGGER (theLogger) static private
react()
void espressopp::integrator::AssociationReaction::react ()
Actual reaction step.
Performs all steps of the reactive scheme.
Definition at line 178 of file AssociationReaction.cpp.
References Alist, applyAR(), Blist, dt, espressopp::SystemAccess::getSystemRef(), espressopp::integrator::Extension::integrator, interval, espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_INFO, reactPair(), sendMultiMap(), uniqueA(), uniqueB(), and verletList.
Referenced by connect().
reactPair()
void espressopp::integrator::AssociationReaction::reactPair (Particle & p1, Particle & p2) private
For a given pair of particles, check if they meet the condition the reactive scheme.
If it is so, the (A,B) pair is added to Alist.
Definition at line 211 of file AssociationReaction.cpp.
References Alist, cutoff_sqr, dt, espressopp::Particle::id(), interval, espressopp::Particle::position(), rate, rng, espressopp::Real3D::sqr(), espressopp::Particle::state(), stateAMin, espressopp::Particle::type(), typeA, and typeB.
Referenced by react().
registerPython()
void espressopp::integrator::AssociationReaction::registerPython () static
Register this class so it can be used from Python.
Definition at line 481 of file AssociationReaction.cpp.
References connect(), disconnect(), getCutoff(), getDeltaA(), getDeltaB(), getInterval(), getRate(), getStateAMin(), getTypeA(), getTypeB(), setCutoff(), setDeltaA(), setDeltaB(), setInterval(), setRate(), setStateAMin(), setTypeA(), and setTypeB().
Referenced by espressopp::integrator::registerPython().
sendMultiMap()
void espressopp::integrator::AssociationReaction::sendMultiMap (boost::unordered_multimap< longint, longint > & mm)
Performs two-way parallel communication to consolidate mm between neighbours.
The parallel scheme is taken from DomainDecomposition::doGhostCommunication
Definition at line 236 of file AssociationReaction.cpp.
References espressopp::integrator::AR_COMM_TAG, espressopp::System::bc, domdec, espressopp::esutil::Grid::getGridSize(), espressopp::storage::NodeGrid::getNodeNeighborIndex(), espressopp::storage::NodeGrid::getNodePosition(), espressopp::SystemAccess::getSystem(), espressopp::SystemAccess::getSystemRef(), LOG4ESPP_DEBUG, LOG4ESPP_INFO, espressopp::InBuffer::read(), espressopp::InBuffer::recv(), espressopp::Buffer::reset(), espressopp::OutBuffer::send(), and espressopp::OutBuffer::write().
Referenced by react().
setCutoff()
void espressopp::integrator::AssociationReaction::setCutoff (real cutoff)
Definition at line 85 of file AssociationReaction.cpp.
References cutoff, and cutoff_sqr.
Referenced by registerPython().
setDeltaA()
void espressopp::integrator::AssociationReaction::setDeltaA (int deltaA)
Definition at line 116 of file AssociationReaction.cpp.
References deltaA.
Referenced by registerPython().
setDeltaB()
void espressopp::integrator::AssociationReaction::setDeltaB (int deltaB)
Definition at line 126 of file AssociationReaction.cpp.
References deltaB.
Referenced by registerPython().
setIntegrator()
void espressopp::integrator::Extension::setIntegrator (shared_ptr< MDIntegrator > _integrator) protected inherited
Definition at line 49 of file Extension.cpp.
References espressopp::integrator::Extension::integrator.
Referenced by espressopp::integrator::Extension::registerPython().
setInterval()
void espressopp::integrator::AssociationReaction::setInterval (int interval)
Definition at line 146 of file AssociationReaction.cpp.
References interval.
Referenced by registerPython().
setRate()
void espressopp::integrator::AssociationReaction::setRate (real rate)
Definition at line 75 of file AssociationReaction.cpp.
References rate.
Referenced by registerPython().
setStateAMin()
void espressopp::integrator::AssociationReaction::setStateAMin (int stateAMin)
Definition at line 136 of file AssociationReaction.cpp.
References stateAMin.
Referenced by registerPython().
setType()
void espressopp::integrator::Extension::setType (ExtensionType k) inline inherited
Definition at line 68 of file Extension.hpp.
Referenced by espressopp::integrator::Extension::registerPython().
setTypeA()
void espressopp::integrator::AssociationReaction::setTypeA (size_t typeA)
Definition at line 96 of file AssociationReaction.cpp.
References typeA.
Referenced by registerPython().
setTypeB()
void espressopp::integrator::AssociationReaction::setTypeB (size_t typeB)
Definition at line 106 of file AssociationReaction.cpp.
References typeB.
Referenced by registerPython().
uniqueA()
void espressopp::integrator::AssociationReaction::uniqueA (boost::unordered_multimap< longint, longint > & mm)
Given a multimap mm with several pairs (id1,id2), keep only one pair for each id1 and return it in place.
In addition, only pairs for which id1 is local are kept.
Definition at line 346 of file AssociationReaction.cpp.
References espressopp::SystemAccess::getSystemRef(), espressopp::Particle::ghost(), and espressopp::System::storage.
Referenced by react().
uniqueB()
void espressopp::integrator::AssociationReaction::uniqueB (boost::unordered_multimap< longint, longint > & mm, boost::unordered_multimap< longint, longint > & nn)
Given a multimap mm with several pairs (id1,id2), keep only one pair for each id2 and return it in place.
In addition, only pairs for which id2 is local are kept.
Definition at line 398 of file AssociationReaction.cpp.
References espressopp::SystemAccess::getSystemRef(), espressopp::Particle::ghost(), and espressopp::System::storage.
Referenced by react().
Member Data Documentation
_initialize
boost::signals2::connection espressopp::integrator::AssociationReaction::_initialize private
Definition at line 107 of file AssociationReaction.hpp.
Referenced by connect(), and disconnect().
_react
boost::signals2::connection espressopp::integrator::AssociationReaction::_react private
Definition at line 107 of file AssociationReaction.hpp.
Referenced by connect(), and disconnect().
Alist
boost::unordered_multimap<longint, longint> espressopp::integrator::AssociationReaction::Alist private
container for (A,B) potential partners
Definition at line 134 of file AssociationReaction.hpp.
Referenced by react(), and reactPair().
Blist
boost::unordered_multimap<longint, longint> espressopp::integrator::AssociationReaction::Blist private
container for (A,B) effective partners
Definition at line 136 of file AssociationReaction.hpp.
Referenced by applyAR(), and react().
current_cutoff
real espressopp::integrator::AssociationReaction::current_cutoff private
Definition at line 126 of file AssociationReaction.hpp.
Referenced by AssociationReaction().
current_cutoff_sqr
real espressopp::integrator::AssociationReaction::current_cutoff_sqr private
Definition at line 127 of file AssociationReaction.hpp.
Referenced by AssociationReaction().
cutoff
real espressopp::integrator::AssociationReaction::cutoff private
reaction cutoff
Definition at line 115 of file AssociationReaction.hpp.
Referenced by AssociationReaction(), getCutoff(), and setCutoff().
cutoff_sqr
real espressopp::integrator::AssociationReaction::cutoff_sqr private
reaction cutoff squared
Definition at line 116 of file AssociationReaction.hpp.
Referenced by reactPair(), and setCutoff().
deltaA
int espressopp::integrator::AssociationReaction::deltaA private
state change for reactant A
Definition at line 119 of file AssociationReaction.hpp.
Referenced by applyAR(), AssociationReaction(), getDeltaA(), and setDeltaA().
deltaB
int espressopp::integrator::AssociationReaction::deltaB private
state change for reactant B
Definition at line 120 of file AssociationReaction.hpp.
Referenced by applyAR(), AssociationReaction(), getDeltaB(), and setDeltaB().
domdec
shared_ptr<DomainDecomposition> espressopp::integrator::AssociationReaction::domdec private
Definition at line 131 of file AssociationReaction.hpp.
Referenced by sendMultiMap().
dt
real espressopp::integrator::AssociationReaction::dt private
timestep from the integrator
Definition at line 123 of file AssociationReaction.hpp.
Referenced by react(), and reactPair().
fpl
shared_ptr<FixedPairList> espressopp::integrator::AssociationReaction::fpl private
Definition at line 130 of file AssociationReaction.hpp.
Referenced by applyAR().
integrator
shared_ptr<MDIntegrator> espressopp::integrator::Extension::integrator protected inherited
Definition at line 72 of file Extension.hpp.
Referenced by espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::LatticeBoltzmann::calcRandForce(), espressopp::integrator::ExtAnalyze::connect(), espressopp::integrator::Rattle::connect(), espressopp::integrator::VelocityVerletOnRadius::connect(), espressopp::integrator::BerendsenBarostatAnisotropic::connect(), espressopp::integrator::BerendsenBarostat::connect(), espressopp::integrator::FixPositions::connect(), espressopp::integrator::Isokinetic::connect(), espressopp::integrator::ExtForce::connect(), espressopp::integrator::FreeEnergyCompensation::connect(), espressopp::integrator::BerendsenThermostat::connect(), espressopp::integrator::TDforce::connect(), espressopp::integrator::Settle::connect(), espressopp::integrator::LangevinThermostatOnGroup::connect(), espressopp::integrator::Adress::connect(), espressopp::integrator::CapForce::connect(), espressopp::integrator::LangevinThermostatOnRadius::connect(), espressopp::integrator::OnTheFlyFEC::connect(), espressopp::integrator::DPDThermostat::connect(), espressopp::integrator::GeneralizedLangevinThermostat::connect(), espressopp::integrator::LangevinThermostat1D::connect(), espressopp::integrator::LangevinThermostatHybrid::connect(), espressopp::integrator::LangevinBarostat::connect(), espressopp::integrator::LangevinThermostat::connect(), connect(), espressopp::integrator::StochasticVelocityRescaling::connect(), espressopp::integrator::LatticeBoltzmann::connect(), espressopp::integrator::LatticeBoltzmann::convTimeMDtoLB(), espressopp::integrator::LangevinThermostatOnGroup::initialize(), espressopp::integrator::LangevinThermostatOnRadius::initialize(), espressopp::integrator::LangevinThermostat::initialize(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinThermostat1D::initialize(), espressopp::integrator::BerendsenThermostat::initialize(), espressopp::integrator::LangevinThermostatHybrid::initialize(), espressopp::integrator::BerendsenBarostatAnisotropic::initialize(), espressopp::integrator::BerendsenBarostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::Adress::integrateSlow(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), react(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::Extension::setIntegrator(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
interval
int espressopp::integrator::AssociationReaction::interval private
number of steps between reaction loops
Definition at line 122 of file AssociationReaction.hpp.
Referenced by getInterval(), react(), reactPair(), and setInterval().
potential
shared_ptr<espressopp::interaction::Potential> espressopp::integrator::AssociationReaction::potential private
Definition at line 124 of file AssociationReaction.hpp.
rate
real espressopp::integrator::AssociationReaction::rate private
reaction rate
Definition at line 114 of file AssociationReaction.hpp.
Referenced by AssociationReaction(), getRate(), reactPair(), and setRate().
rng
shared_ptr< esutil::RNG > espressopp::integrator::AssociationReaction::rng private
random number generator used for friction term
Definition at line 129 of file AssociationReaction.hpp.
Referenced by AssociationReaction(), and reactPair().
stateAMin
int espressopp::integrator::AssociationReaction::stateAMin private
minimum state of reactant A
Definition at line 121 of file AssociationReaction.hpp.
Referenced by AssociationReaction(), getStateAMin(), reactPair(), and setStateAMin().
type
ExtensionType espressopp::integrator::Extension::type inherited
Definition at line 62 of file Extension.hpp.
Referenced by espressopp::integrator::TDforce::addForce(), espressopp::integrator::Adress::Adress(), AssociationReaction(), espressopp::integrator::BerendsenBarostat::BerendsenBarostat(), espressopp::integrator::BerendsenBarostatAnisotropic::BerendsenBarostatAnisotropic(), espressopp::integrator::BerendsenThermostat::BerendsenThermostat(), espressopp::integrator::DPDThermostat::DPDThermostat(), espressopp::integrator::ExtAnalyze::ExtAnalyze(), espressopp::integrator::FreeEnergyCompensation::FreeEnergyCompensation(), espressopp::integrator::GeneralizedLangevinThermostat::GeneralizedLangevinThermostat(), espressopp::integrator::Extension::getType(), espressopp::integrator::LangevinBarostat::LangevinBarostat(), espressopp::integrator::LangevinThermostat::LangevinThermostat(), espressopp::integrator::LangevinThermostat1D::LangevinThermostat1D(), espressopp::integrator::LangevinThermostatHybrid::LangevinThermostatHybrid(), espressopp::integrator::LangevinThermostatOnGroup::LangevinThermostatOnGroup(), espressopp::integrator::LangevinThermostatOnRadius::LangevinThermostatOnRadius(), espressopp::integrator::OnTheFlyFEC::OnTheFlyFEC(), espressopp::integrator::TDforce::registerPython(), espressopp::integrator::StochasticVelocityRescaling::StochasticVelocityRescaling(), and espressopp::integrator::TDforce::TDforce().
typeA
size_t espressopp::integrator::AssociationReaction::typeA private
type of reactant A
Definition at line 117 of file AssociationReaction.hpp.
Referenced by AssociationReaction(), getTypeA(), reactPair(), and setTypeA().
typeB
size_t espressopp::integrator::AssociationReaction::typeB private
type of reactant B
Definition at line 118 of file AssociationReaction.hpp.
Referenced by AssociationReaction(), getTypeB(), reactPair(), and setTypeB().
verletList
shared_ptr<VerletList> espressopp::integrator::AssociationReaction::verletList private
Definition at line 128 of file AssociationReaction.hpp.
Referenced by AssociationReaction(), and react().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/integrator/AssociationReaction.hpp
/home/espressopp/espressopp/src/integrator/AssociationReaction.cpp