ESPResSo++: espressopp::interaction::MirrorLennardJones Class Reference
espressopp::interaction::MirrorLennardJones Class Reference
This class provides methods to compute forces and energies of the Mirror Lennard-Jones potential.
#include <MirrorLennardJones.hpp>
Public Member Functions
MirrorLennardJones ()
MirrorLennardJones (real _epsilon, real _sigma)
void preset ()
void setEpsilon (real _epsilon)
real getEpsilon () const
void setSigma (real _sigma)
real getSigma () const
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &dist, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
MirrorLennardJones * derived_this ()
const MirrorLennardJones * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
Private Attributes
real epsilon
real sigma
real ff1
real ff2
real ef1
real ef2
Detailed Description
This class provides methods to compute forces and energies of the Mirror Lennard-Jones potential.
where
is the 6-12 purely repulsive Lennard-Jones potential. This potential is introduced in R.L.C. Akkermans, S. Toxvaerd and & W. J. Briels. Molecular dynamics of polymer growth. The Journal of Chemical Physics, 1998, 109, 2929-2940.
Definition at line 46 of file MirrorLennardJones.hpp.
Constructor & Destructor Documentation
espressopp::interaction::MirrorLennardJones::MirrorLennardJones () [inline]
Definition at line 56 of file MirrorLennardJones.hpp.
References espressopp::infinity, preset(), espressopp::interaction::PotentialTemplate< MirrorLennardJones >::setCutoff(), and espressopp::interaction::PotentialTemplate< MirrorLennardJones >::setShift().
espressopp::interaction::MirrorLennardJones::MirrorLennardJones (real _epsilon, real _sigma) [inline]
Definition at line 63 of file MirrorLennardJones.hpp.
References epsilon, preset(), espressopp::interaction::PotentialTemplate< MirrorLennardJones >::setCutoff(), espressopp::interaction::PotentialTemplate< MirrorLennardJones >::setShift(), and sigma.
Member Function Documentation
real espressopp::interaction::PotentialTemplate< MirrorLennardJones >::_computeEnergy (const Particle & p1, const Particle & p2) const [inherited]
real espressopp::interaction::PotentialTemplate< MirrorLennardJones >::_computeEnergy (const Real3D & dist) const [inherited]
real espressopp::interaction::PotentialTemplate< MirrorLennardJones >::_computeEnergy (real dist) const [inherited]
real espressopp::interaction::PotentialTemplate< MirrorLennardJones >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const [inherited]
real espressopp::interaction::PotentialTemplate< MirrorLennardJones >::_computeEnergySqr (real distSqr) const [inherited]
real espressopp::interaction::MirrorLennardJones::_computeEnergySqrRaw (real distSqr) const [inline]
Definition at line 96 of file MirrorLennardJones.hpp.
References espressopp::interaction::PotentialTemplate< MirrorLennardJones >::cutoff, espressopp::interaction::PotentialTemplate< MirrorLennardJones >::cutoffSqr, epsilon, espressopp::interaction::PotentialTemplate< MirrorLennardJones >::shift, and sigma.
bool espressopp::interaction::PotentialTemplate< MirrorLennardJones >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const [inherited]
bool espressopp::interaction::PotentialTemplate< MirrorLennardJones >::_computeForce (Real3D & force, const Real3D & dist) const [inherited]
bool espressopp::interaction::PotentialTemplate< MirrorLennardJones >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const [inherited]
bool espressopp::interaction::MirrorLennardJones::_computeForceRaw (Real3D & force, const Real3D & dist, real distSqr) const [inline]
Definition at line 106 of file MirrorLennardJones.hpp.
References espressopp::interaction::PotentialTemplate< MirrorLennardJones >::cutoff, espressopp::interaction::PotentialTemplate< MirrorLennardJones >::cutoffSqr, ff1, and ff2.
virtual real espressopp::interaction::PotentialTemplate< MirrorLennardJones >::computeEnergy (const Particle & p1, const Particle & p2) const [virtual, inherited]
Implements espressopp::interaction::Potential.
virtual real espressopp::interaction::PotentialTemplate< MirrorLennardJones >::computeEnergy (const Real3D & dist) const [virtual, inherited]
Implements espressopp::interaction::Potential.
virtual real espressopp::interaction::PotentialTemplate< MirrorLennardJones >::computeEnergy (real dist) const [virtual, inherited]
Implements espressopp::interaction::Potential.
virtual real espressopp::interaction::PotentialTemplate< MirrorLennardJones >::computeEnergySqr (real distsqr) const [virtual, inherited]
Implements espressopp::interaction::Potential.
virtual Real3D espressopp::interaction::PotentialTemplate< MirrorLennardJones >::computeForce (const Particle & p1, const Particle & p2) const [virtual, inherited]
Implements espressopp::interaction::Potential.
virtual Real3D espressopp::interaction::PotentialTemplate< MirrorLennardJones >::computeForce (const Real3D & dist) const [virtual, inherited]
Implements espressopp::interaction::Potential.
MirrorLennardJones * espressopp::interaction::PotentialTemplate< MirrorLennardJones >::derived_this () [inline, protected, inherited]
Definition at line 121 of file Potential.hpp.
const MirrorLennardJones * espressopp::interaction::PotentialTemplate< MirrorLennardJones >::derived_this () const [inline, protected, inherited]
Definition at line 125 of file Potential.hpp.
virtual real espressopp::interaction::PotentialTemplate< MirrorLennardJones >::getCutoff () const [virtual, inherited]
Implements espressopp::interaction::Potential.
real espressopp::interaction::MirrorLennardJones::getEpsilon () const [inline]
Definition at line 86 of file MirrorLennardJones.hpp.
References epsilon.
Referenced by registerPython().
virtual real espressopp::interaction::PotentialTemplate< MirrorLennardJones >::getShift () const [virtual, inherited]
Implements espressopp::interaction::Potential.
real espressopp::interaction::MirrorLennardJones::getSigma () const [inline]
Definition at line 93 of file MirrorLennardJones.hpp.
References sigma.
Referenced by registerPython().
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) [static, inherited]
Reimplemented in espressopp::interaction::LennardJones, espressopp::interaction::LennardJonesGeneric, and espressopp::interaction::FENE.
void espressopp::interaction::MirrorLennardJones::preset () [inline]
Definition at line 70 of file MirrorLennardJones.hpp.
References ef1, ef2, epsilon, ff1, ff2, and sigma.
Referenced by MirrorLennardJones(), setEpsilon(), and setSigma().
void espressopp::interaction::MirrorLennardJones::registerPython () [static]
Reimplemented from espressopp::interaction::Potential.
Definition at line 38 of file MirrorLennardJones.cpp.
References getEpsilon(), getSigma(), setEpsilon(), and setSigma().
Referenced by espressopp::interaction::registerPython().
virtual real espressopp::interaction::PotentialTemplate< MirrorLennardJones >::setAutoShift () [virtual, inherited]
Implements espressopp::interaction::Potential.
virtual void espressopp::interaction::PotentialTemplate< MirrorLennardJones >::setCutoff (real _cutoff) [virtual, inherited]
Implements espressopp::interaction::Potential.
Referenced by MirrorLennardJones(), and setSigma().
void espressopp::interaction::MirrorLennardJones::setEpsilon (real _epsilon) [inline]
Definition at line 80 of file MirrorLennardJones.hpp.
References epsilon, preset(), and espressopp::interaction::PotentialTemplate< MirrorLennardJones >::setShift().
Referenced by registerPython().
virtual void espressopp::interaction::PotentialTemplate< MirrorLennardJones >::setShift (real _shift) [virtual, inherited]
Implements espressopp::interaction::Potential.
Referenced by MirrorLennardJones(), and setEpsilon().
void espressopp::interaction::MirrorLennardJones::setSigma (real _sigma) [inline]
Definition at line 88 of file MirrorLennardJones.hpp.
References preset(), espressopp::interaction::PotentialTemplate< MirrorLennardJones >::setCutoff(), and sigma.
Referenced by registerPython().
void espressopp::interaction::PotentialTemplate< MirrorLennardJones >::updateAutoShift () [inherited]
Member Data Documentation
bool espressopp::interaction::PotentialTemplate< MirrorLennardJones >::autoShift [protected, inherited]
Definition at line 119 of file Potential.hpp.
real espressopp::interaction::PotentialTemplate< MirrorLennardJones >::cutoff [protected, inherited]
Definition at line 116 of file Potential.hpp.
Referenced by _computeEnergySqrRaw(), and _computeForceRaw().
real espressopp::interaction::PotentialTemplate< MirrorLennardJones >::cutoffSqr [protected, inherited]
Definition at line 117 of file Potential.hpp.
Referenced by _computeEnergySqrRaw(), and _computeForceRaw().
real espressopp::interaction::MirrorLennardJones::ef1 [private]
Definition at line 51 of file MirrorLennardJones.hpp.
Referenced by preset().
real espressopp::interaction::MirrorLennardJones::ef2 [private]
Definition at line 51 of file MirrorLennardJones.hpp.
Referenced by preset().
real espressopp::interaction::MirrorLennardJones::epsilon [private]
Definition at line 48 of file MirrorLennardJones.hpp.
Referenced by _computeEnergySqrRaw(), getEpsilon(), MirrorLennardJones(), preset(), and setEpsilon().
real espressopp::interaction::MirrorLennardJones::ff1 [private]
Definition at line 50 of file MirrorLennardJones.hpp.
Referenced by _computeForceRaw(), and preset().
real espressopp::interaction::MirrorLennardJones::ff2 [private]
Definition at line 50 of file MirrorLennardJones.hpp.
Referenced by _computeForceRaw(), and preset().
real espressopp::interaction::PotentialTemplate< MirrorLennardJones >::shift [protected, inherited]
Definition at line 118 of file Potential.hpp.
Referenced by _computeEnergySqrRaw().
real espressopp::interaction::MirrorLennardJones::sigma [private]
Definition at line 49 of file MirrorLennardJones.hpp.
Referenced by _computeEnergySqrRaw(), getSigma(), MirrorLennardJones(), preset(), and setSigma().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/interaction/MirrorLennardJones.hpp
/home/travis/build/espressopp/espressopp/src/interaction/MirrorLennardJones.cpp