ESPResSo++: espressopp::iterator::CellListAllPairsIterator Class Reference
espressopp::iterator::CellListAllPairsIterator Class Reference
#include <CellListAllPairsIterator.hpp>
Public Member Functions
CellListAllPairsIterator ()
CellListAllPairsIterator (CellList &cl)
CellListAllPairsIterator & operator++ ()
bool isValid () const
bool isDone () const
const ParticlePair & operator* () const
const ParticlePair * operator-> () const
Static Private Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Private Attributes
ParticlePair current
bool inSelfLoop
CellList::Iterator cit
ParticleList::Iterator pit
NeighborCellList::Iterator ncit
ParticleList::Iterator npit
Detailed Description
Definition at line 34 of file CellListAllPairsIterator.hpp.
Constructor & Destructor Documentation
CellListAllPairsIterator() [1/2]
espressopp::iterator::CellListAllPairsIterator::CellListAllPairsIterator () inline
Definition at line 69 of file CellListAllPairsIterator.hpp.
CellListAllPairsIterator() [2/2]
espressopp::iterator::CellListAllPairsIterator::CellListAllPairsIterator (CellList & cl) inline
Definition at line 74 of file CellListAllPairsIterator.hpp.
References cit, inSelfLoop, espressopp::esutil::ESPPIterator< STLContainer >::isDone(), npit, operator++(), and pit.
Member Function Documentation
isDone()
bool espressopp::iterator::CellListAllPairsIterator::isDone () const inline
Definition at line 147 of file CellListAllPairsIterator.hpp.
References isValid(), and operator*().
Referenced by isValid().
isValid()
bool espressopp::iterator::CellListAllPairsIterator::isValid () const inline
Definition at line 142 of file CellListAllPairsIterator.hpp.
References cit, isDone(), and espressopp::esutil::ESPPIterator< STLContainer >::isValid().
Referenced by espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::addForces(), espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::computeEnergy(), espressopp::analysis::OrderParameter::computeRaw(), espressopp::analysis::NeighborFluctuation::computeValues(), espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::computeVirialTensor(), isDone(), operator++(), espressopp::VerletList::rebuild(), and espressopp::VerletListAdress::rebuild().
LOG4ESPP_DECL_LOGGER()
static espressopp::iterator::CellListAllPairsIterator::LOG4ESPP_DECL_LOGGER (theLogger) static private
operator*()
const ParticlePair & espressopp::iterator::CellListAllPairsIterator::operator* () const inline
Definition at line 152 of file CellListAllPairsIterator.hpp.
References current, and operator->().
Referenced by isDone().
operator++()
CellListAllPairsIterator & espressopp::iterator::CellListAllPairsIterator::operator++ () inline
Definition at line 91 of file CellListAllPairsIterator.hpp.
References cit, current, inSelfLoop, espressopp::esutil::ESPPIterator< STLContainer >::isDone(), isValid(), LOG4ESPP_TRACE, ncit, npit, and pit.
Referenced by CellListAllPairsIterator().
operator->()
const ParticlePair * espressopp::iterator::CellListAllPairsIterator::operator-> () const inline
Definition at line 157 of file CellListAllPairsIterator.hpp.
Referenced by operator*().
Member Data Documentation
cit
CellList::Iterator espressopp::iterator::CellListAllPairsIterator::cit private
Definition at line 55 of file CellListAllPairsIterator.hpp.
Referenced by CellListAllPairsIterator(), isValid(), and operator++().
current
ParticlePair espressopp::iterator::CellListAllPairsIterator::current private
Definition at line 50 of file CellListAllPairsIterator.hpp.
Referenced by operator*(), and operator++().
inSelfLoop
bool espressopp::iterator::CellListAllPairsIterator::inSelfLoop private
Definition at line 52 of file CellListAllPairsIterator.hpp.
Referenced by CellListAllPairsIterator(), and operator++().
ncit
NeighborCellList::Iterator espressopp::iterator::CellListAllPairsIterator::ncit private
Definition at line 60 of file CellListAllPairsIterator.hpp.
Referenced by operator++().
npit
ParticleList::Iterator espressopp::iterator::CellListAllPairsIterator::npit private
Definition at line 62 of file CellListAllPairsIterator.hpp.
Referenced by CellListAllPairsIterator(), and operator++().
pit
ParticleList::Iterator espressopp::iterator::CellListAllPairsIterator::pit private
Definition at line 57 of file CellListAllPairsIterator.hpp.
Referenced by CellListAllPairsIterator(), and operator++().
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/iterator/CellListAllPairsIterator.hpp