ESPResSo++: espressopp::interaction::DihedralUniquePotential Class Reference
espressopp::interaction::DihedralUniquePotential Class Reference abstract
#include <DihedralUniquePotential.hpp>
Public Member Functions
virtual real computeEnergy (const Real3D &r21, const Real3D &r32, const Real3D &r43, const real phi0) const =0
virtual real computeEnergy (real phi, real phi0) const =0
virtual void computeForce (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &r21, const Real3D &r32, const Real3D &r43, const real phi0) const =0
virtual real computeForce (real phi, real phi0) const =0
virtual void setCutoff (real _cutoff)=0
virtual real getCutoff () const =0
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Detailed Description
Definition at line 35 of file DihedralUniquePotential.hpp.
Member Function Documentation
computeEnergy() [1/2]
virtual real espressopp::interaction::DihedralUniquePotential::computeEnergy (const Real3D & r21, const Real3D & r32, const Real3D & r43, const real phi0) const pure virtual
Implemented in espressopp::interaction::DihedralUniquePotentialTemplate< Derived >, and espressopp::interaction::DihedralUniquePotentialTemplate< DihedralHarmonicUniqueCos >.
Referenced by registerPython().
computeEnergy() [2/2]
virtual real espressopp::interaction::DihedralUniquePotential::computeEnergy (real phi, real phi0) const pure virtual
Implemented in espressopp::interaction::DihedralUniquePotentialTemplate< Derived >, and espressopp::interaction::DihedralUniquePotentialTemplate< DihedralHarmonicUniqueCos >.
computeForce() [1/2]
virtual void espressopp::interaction::DihedralUniquePotential::computeForce (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & r21, const Real3D & r32, const Real3D & r43, const real phi0) const pure virtual
Implemented in espressopp::interaction::DihedralUniquePotentialTemplate< Derived >, and espressopp::interaction::DihedralUniquePotentialTemplate< DihedralHarmonicUniqueCos >.
Referenced by registerPython().
computeForce() [2/2]
virtual real espressopp::interaction::DihedralUniquePotential::computeForce (real phi, real phi0) const pure virtual
Implemented in espressopp::interaction::DihedralUniquePotentialTemplate< Derived >, and espressopp::interaction::DihedralUniquePotentialTemplate< DihedralHarmonicUniqueCos >.
getCutoff()
virtual real espressopp::interaction::DihedralUniquePotential::getCutoff () const pure virtual
Implemented in espressopp::interaction::DihedralUniquePotentialTemplate< Derived >, and espressopp::interaction::DihedralUniquePotentialTemplate< DihedralHarmonicUniqueCos >.
Referenced by registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::DihedralUniquePotential::LOG4ESPP_DECL_LOGGER (theLogger) static
registerPython()
void espressopp::interaction::DihedralUniquePotential::registerPython () static
Definition at line 36 of file DihedralUniquePotential.cpp.
References computeEnergy(), computeForce(), getCutoff(), and setCutoff().
Referenced by espressopp::interaction::registerPython().
setCutoff()
virtual void espressopp::interaction::DihedralUniquePotential::setCutoff (real _cutoff) pure virtual
Implemented in espressopp::interaction::DihedralUniquePotentialTemplate< Derived >, and espressopp::interaction::DihedralUniquePotentialTemplate< DihedralHarmonicUniqueCos >.
Referenced by registerPython().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/DihedralUniquePotential.hpp
/home/espressopp/espressopp/src/interaction/DihedralUniquePotential.cpp