ESPResSo++: log4espp::Logger Class Reference
log4espp::Logger Class Reference abstract
Logger is a an abstract class for hierarchical organization of logging objects.
#include <Logger.hpp>
Public Types
enum Level {
TRACE = 10, DEBUG = 20, INFO = 30, WARN = 40,
ERROR = 50, FATAL = 60
}
Public Member Functions
Logger (std::string _name, class Logger *_parent)
General constructor for a logger.
virtual ~Logger ()
Virtual estructor needed due to virtual functions.
std::string getFullName ()
Asks for the full name of the logger, e.g.
bool isTraceEnabled ()
Check if logging statements of level TRACE are enabled.
bool isDebugEnabled ()
Check if logging statements of level DEBUG are enabled.
bool isInfoEnabled ()
Check if logging statements of level INFO are enabled.
bool isWarnEnabled ()
Check if logging statements of level WARN are enabled.
bool isErrorEnabled ()
Check if logging statements of level ERROR are enabled.
bool isFatalEnabled ()
Check if logging statements of level FATAL are enabled.
Level getLevel ()
Getter routine for the logging level of this object.
Level getEffectiveLevel ()
Getter routine for the effective logging level of this object.
void setLevel (Level level, bool force=true)
Setter routine for the logging level of this object.
virtual void trace (Location loc, const std::string &msg)=0
Logging output for level TRACE.
virtual void debug (Location loc, const std::string &msg)=0
Logging output for level DEBUG.
virtual void info (Location loc, const std::string &msg)=0
Logging output for level INFO.
virtual void warn (Location loc, const std::string &msg)=0
Logging output for level WARN.
virtual void error (Location loc, const std::string &msg)=0
Logging output for level ERROR.
virtual void fatal (Location loc, const std::string &msg)=0
Logging output for level FATAL.
template<class DerivedLogger >
Logger & createInstance (std::string name)
This routine creates a logger instance for a given name.
Static Public Member Functions
static Logger & getRoot ()
Get reference to the root logger.
static Logger & getInstance (std::string name)
Get reference to a logger with a given name.
static void push (std::string item)
Add some content for the following log statements.
static void pop ()
Reverse to the last push.
static void configure ()
Configuration of the logging system.
static const char * getLevelString (int level)
Getter routine for the logging level of this object.
template<class DerivedLogger >
static Logger & createInstance (std::string name)
Protected Attributes
std::string name
name of the logger
bool setFlag
This flag indicates that level has been set explicitly.
Level myLevel
Current level of this logger.
class Logger * parent
points back to the parent logger, NULL for root
std::vector< class Logger * > sons
sub loggers of this logger
Static Protected Attributes
static std::vector< std::string > context
stack for different context
Detailed Description
Logger is a an abstract class for hierarchical organization of logging objects.
Definition at line 88 of file Logger.hpp.
Member Enumeration Documentation
enum log4espp::Logger::Level
Enumerator
TRACE
even more detailed than DEBUG
DEBUG
designates fine-grained informational events
INFO
informational messages highlighting progress
WARN
for potentially harmful situations
ERROR
for errors that might still allow the application to continue
FATAL
servere errors that will presumably lead to aborts
Definition at line 92 of file Logger.hpp.
Constructor & Destructor Documentation
log4espp::Logger::Logger (std::string _name, class Logger * _parent) inline
General constructor for a logger.
Parameters
_name is the name of this logger (not full name)
_parent is pointer to the parent logger
Definition at line 121 of file Logger.hpp.
References getLevel(), myLevel, name, parent, setFlag, sons, and WARN.
virtual log4espp::Logger::~Logger () inline virtual
Virtual estructor needed due to virtual functions.
Definition at line 134 of file Logger.hpp.
Member Function Documentation
void Logger::configure () static
Configuration of the logging system.
Definition at line 254 of file GenLogger.cpp.
References getRoot(), LOG4ESPP_INFO, LOG4ESPP_WARN, read_config(), setLevel(), log4espp::GenLogger::traverse(), and WARN.
template<class DerivedLogger > static Logger& log4espp::Logger::createInstance (std::string name) static
template<class DerivedLogger > Logger& log4espp::Logger::createInstance (std::string name)
This routine creates a logger instance for a given name.
The template argument specifies the class of the logger.
Definition at line 323 of file Logger.hpp.
References getRoot(), name, and sons.
virtual void log4espp::Logger::debug (Location loc, const std::string & msg) pure virtual
Logging output for level DEBUG.
This routine should only be called if isDebugEnabled() returns true.
Parameters
loc is the file location of the logging statement
is the message to be printed
Each derived class has to implement this routine. This abstract class does not handle output of logging at all.
Implemented in log4espp::PyLogger, and log4espp::GenLogger.
virtual void log4espp::Logger::error (Location loc, const std::string & msg) pure virtual
Logging output for level ERROR.
This routine should only be called if isErrorEnabled() returns true.
Parameters
loc is the file location of the logging statement
is the message to be printed
Each derived class has to implement this routine. This abstract class does not handle output of logging at all.
Implemented in log4espp::PyLogger, and log4espp::GenLogger.
virtual void log4espp::Logger::fatal (Location loc, const std::string & msg) pure virtual
Logging output for level FATAL.
This routine should only be called if isFatalEnabled() returns true.
Parameters
loc is the file location of the logging statement
is the message to be printed
Each derived class has to implement this routine. This abstract class does not handle output of logging at all.
Implemented in log4espp::PyLogger, and log4espp::GenLogger.
Level log4espp::Logger::getEffectiveLevel () inline
Getter routine for the effective logging level of this object.
If level has not been set explicitly it will ask the ancestors for the level
Definition at line 198 of file Logger.hpp.
References getEffectiveLevel(), myLevel, parent, and setFlag.
Referenced by getEffectiveLevel(), and log4espp::GenLogger::traverse().
std::string log4espp::Logger::getFullName () inline
Asks for the full name of the logger, e.g.
"X.Y.Z"
Definition at line 154 of file Logger.hpp.
References getFullName(), name, and parent.
Referenced by log4espp::GenLogger::GenLogger(), getFullName(), log4espp::PyLogger::PyLogger(), log4espp::PyLogger::setPythonLevel(), log4espp::PyLogger::setPythonLogger(), and log4espp::GenLogger::traverse().
Logger & Logger::getInstance (std::string name) static
Get reference to a logger with a given name.
Definition at line 90 of file GenLogger.cpp.
References name.
Referenced by loggerUpdate(), and setLoggerLevel().
Level log4espp::Logger::getLevel () inline
Getter routine for the logging level of this object.
Definition at line 191 of file Logger.hpp.
References myLevel.
Referenced by Logger().
static const char* log4espp::Logger::getLevelString (int level) inline static
Getter routine for the logging level of this object.
Returns
the logging level as a string.
Definition at line 208 of file Logger.hpp.
References DEBUG, ERROR, FATAL, INFO, TRACE, and WARN.
Referenced by log4espp::GenLogger::traverse().
Logger & Logger::getRoot () static
Get reference to the root logger.
Definition at line 72 of file GenLogger.cpp.
References rootLogger.
Referenced by configure(), createInstance(), and setLoggerLevel().
virtual void log4espp::Logger::info (Location loc, const std::string & msg) pure virtual
Logging output for level INFO.
This routine should only be called if isInfoEnabled() returns true.
Parameters
loc is the file location of the logging statement
is the message to be printed
Each derived class has to implement this routine. This abstract class does not handle output of logging at all.
Implemented in log4espp::PyLogger, and log4espp::GenLogger.
bool log4espp::Logger::isDebugEnabled () inline
Check if logging statements of level DEBUG are enabled.
Definition at line 171 of file Logger.hpp.
References DEBUG, and myLevel.
bool log4espp::Logger::isErrorEnabled () inline
Check if logging statements of level ERROR are enabled.
Definition at line 183 of file Logger.hpp.
References ERROR, and myLevel.
bool log4espp::Logger::isFatalEnabled () inline
Check if logging statements of level FATAL are enabled.
Definition at line 187 of file Logger.hpp.
References FATAL, and myLevel.
bool log4espp::Logger::isInfoEnabled () inline
Check if logging statements of level INFO are enabled.
Definition at line 175 of file Logger.hpp.
References INFO, and myLevel.
bool log4espp::Logger::isTraceEnabled () inline
Check if logging statements of level TRACE are enabled.
Definition at line 167 of file Logger.hpp.
References myLevel, and TRACE.
bool log4espp::Logger::isWarnEnabled () inline
Check if logging statements of level WARN are enabled.
Definition at line 179 of file Logger.hpp.
References myLevel, and WARN.
static void log4espp::Logger::pop () inline static
Reverse to the last push.
Definition at line 150 of file Logger.hpp.
References context.
static void log4espp::Logger::push (std::string item) inline static
Add some content for the following log statements.
Definition at line 146 of file Logger.hpp.
References context.
void log4espp::Logger::setLevel (Level level, bool force = true) inline
Setter routine for the logging level of this object.
Parameters
level is the new logging level for this object
force true specifies that this is an explicit set
This routine will set implicitly the levels recursively for the descendants whose level has not been set explicitly.
Definition at line 228 of file Logger.hpp.
References myLevel, setFlag, and sons.
Referenced by configure(), setLoggerLevel(), and log4espp::PyLogger::setPythonLevel().
virtual void log4espp::Logger::trace (Location loc, const std::string & msg) pure virtual
Logging output for level TRACE.
This routine should only be called if TraceEnabled() returns true.
Parameters
loc is the file location of the logging statement
is the message to be printed
Each derived class has to implement this routine. This abstract class does not handle output of logging at all.
Implemented in log4espp::PyLogger, and log4espp::GenLogger.
virtual void log4espp::Logger::warn (Location loc, const std::string & msg) pure virtual
Logging output for level WARN.
This routine should only be called if isWarnEnabled() returns true.
Parameters
loc is the file location of the logging statement
is the message to be printed
Each derived class has to implement this routine. This abstract class does not handle output of logging at all.
Implemented in log4espp::PyLogger, and log4espp::GenLogger.
Member Data Documentation
std::vector<std::string> log4espp::Logger::context static protected
stack for different context
Definition at line 111 of file Logger.hpp.
Referenced by pop(), and push().
Level log4espp::Logger::myLevel protected
Current level of this logger.
Definition at line 105 of file Logger.hpp.
Referenced by getEffectiveLevel(), getLevel(), isDebugEnabled(), isErrorEnabled(), isFatalEnabled(), isInfoEnabled(), isTraceEnabled(), isWarnEnabled(), Logger(), setLevel(), and log4espp::PyLogger::setPythonLevel().
std::string log4espp::Logger::name protected
name of the logger
Definition at line 102 of file Logger.hpp.
Referenced by createInstance(), getFullName(), getInstance(), log4espp::PyLogger::initLogging(), log4espp::PyLogger::log(), Logger(), and log4espp::PyLogger::setPythonLoggers().
class Logger* log4espp::Logger::parent protected
points back to the parent logger, NULL for root
Definition at line 107 of file Logger.hpp.
Referenced by getEffectiveLevel(), getFullName(), and Logger().
bool log4espp::Logger::setFlag protected
This flag indicates that level has been set explicitly.
Definition at line 103 of file Logger.hpp.
Referenced by getEffectiveLevel(), Logger(), setLevel(), log4espp::PyLogger::setPythonLevel(), and log4espp::GenLogger::traverse().
std::vector<class Logger*> log4espp::Logger::sons protected
sub loggers of this logger
Definition at line 109 of file Logger.hpp.
Referenced by createInstance(), Logger(), setLevel(), log4espp::PyLogger::setPythonLoggers(), and log4espp::GenLogger::traverse().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/esutil/Logger.hpp
/home/travis/build/espressopp/espressopp/src/esutil/GenLogger.cpp
/home/travis/build/espressopp/espressopp/src/esutil/PyLogger.cpp