ESPResSo++: espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL > Class Template Reference
espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL > Class Template Reference
#include <VerletListPIadressInteractionTemplate.hpp>
Public Member Functions
VerletListPIadressInteractionTemplate (shared_ptr< VerletListAdress > _verletList, shared_ptr< FixedTupleListAdress > _fixedtupleList, int _ntrotter, bool _speedup)
void setVerletList (shared_ptr< VerletListAdress > _verletList)
shared_ptr< VerletListAdress > getVerletList ()
void setFixedTupleList (shared_ptr< FixedTupleListAdress > _fixedtupleList)
shared_ptr< FixedTupleListAdress > getFixedTupleList ()
void setNTrotter (int _ntrotter)
int getNTrotter ()
void setSpeedup (bool _speedup)
bool getSpeedup ()
void setPotentialQM (int type1, int type2, const PotentialQM &potential)
void setPotentialCL (int type1, int type2, const PotentialCL &potential)
PotentialQM & getPotentialQM (int type1, int type2)
PotentialCL & getPotentialCL (int type1, int type2)
virtual void addForces ()
virtual real computeEnergy ()
virtual real computeEnergyDeriv ()
virtual real computeEnergyAA ()
virtual real computeEnergyCG ()
virtual real computeEnergyAA (int atomtype)
virtual real computeEnergyCG (int atomtype)
virtual void computeVirialX (std::vector< real > &p_xx_total, int bins)
virtual real computeVirial ()
virtual void computeVirialTensor (Tensor &w)
virtual void computeVirialTensor (Tensor &w, real z)
virtual void computeVirialTensor (Tensor *w, int n)
virtual real getMaxCutoff ()
This method returns the maximal cutoff defined for one type pair.
virtual int bondType ()
Static Public Member Functions
static void registerPython ()
Protected Types
typedef _PotentialQM PotentialQM
typedef _PotentialCL PotentialCL
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Protected Attributes
int ntypes
shared_ptr< VerletListAdress > verletList
shared_ptr< FixedTupleListAdress > fixedtupleList
esutil::Array2D< PotentialQM, esutil::enlarge > potentialArrayQM
esutil::Array2D< PotentialCL, esutil::enlarge > potentialArrayCL
int ntrotter
bool speedup
boost::unordered_map< Particle *, real > energydiff
std::set< Particle * > adrZone
Detailed Description
template<typename _PotentialQM, typename _PotentialCL>
class espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >
Definition at line 41 of file VerletListPIadressInteractionTemplate.hpp.
Member Typedef Documentation
PotentialCL
template<typename _PotentialQM , typename _PotentialCL > typedef _PotentialCL espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::PotentialCL protected
Definition at line 45 of file VerletListPIadressInteractionTemplate.hpp.
PotentialQM
template<typename _PotentialQM , typename _PotentialCL > typedef _PotentialQM espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::PotentialQM protected
Definition at line 44 of file VerletListPIadressInteractionTemplate.hpp.
Constructor & Destructor Documentation
VerletListPIadressInteractionTemplate()
template<typename _PotentialQM , typename _PotentialCL > espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::VerletListPIadressInteractionTemplate (shared_ptr< VerletListAdress > _verletList, shared_ptr< FixedTupleListAdress > _fixedtupleList, int _ntrotter, bool _speedup) inline
Definition at line 49 of file VerletListPIadressInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::ntypes, espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::potentialArrayCL, and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::potentialArrayQM.
Member Function Documentation
addForces()
template<typename _PotentialQM , typename _PotentialCL > void espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::addForces () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 158 of file VerletListPIadressInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::adrZone, espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergy(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::energydiff, espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::fixedtupleList, espressopp::Particle::force(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getPotentialCL(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getPotentialQM(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::Particle::lambda(), espressopp::Particle::lambdaDeriv(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::ntrotter, espressopp::Particle::pib(), espressopp::Particle::position(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::speedup, espressopp::Real3D::sqr(), espressopp::Particle::type(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::verletList.
Referenced by espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getPotentialCL().
bondType()
template<typename _PotentialQM , typename _PotentialCL > virtual int espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::bondType () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 136 of file VerletListPIadressInteractionTemplate.hpp.
References espressopp::interaction::Nonbonded.
computeEnergy()
template<typename _PotentialQM , typename _PotentialCL > real espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergy () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 413 of file VerletListPIadressInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergyDeriv(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::fixedtupleList, espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getPotentialCL(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getPotentialQM(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getVerletList(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::Particle::lambda(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::ntrotter, espressopp::Particle::pib(), espressopp::Particle::position(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::speedup, espressopp::Particle::type(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::verletList.
Referenced by espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::addForces(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getPotentialCL().
computeEnergyAA() [1/2]
template<typename _PotentialQM , typename _PotentialCL > real espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergyAA () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 574 of file VerletListPIadressInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::fixedtupleList, espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getPotentialQM(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getVerletList(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::ntrotter, espressopp::Particle::pib(), espressopp::Particle::position(), espressopp::Particle::type(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::verletList.
Referenced by espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergyDeriv(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getPotentialCL().
computeEnergyAA() [2/2]
template<typename _PotentialQM , typename _PotentialCL > real espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergyAA (int atomtype) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 700 of file VerletListPIadressInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergyCG(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::fixedtupleList, espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getPotentialQM(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getVerletList(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::ntrotter, espressopp::Particle::pib(), espressopp::Particle::position(), espressopp::Particle::type(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::verletList.
computeEnergyCG() [1/2]
template<typename _PotentialQM , typename _PotentialCL > real espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergyCG () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 846 of file VerletListPIadressInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::fixedtupleList, espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getPotentialCL(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getVerletList(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::ntrotter, espressopp::Particle::pib(), espressopp::Particle::position(), espressopp::Particle::type(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::verletList.
Referenced by espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergyAA(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getPotentialCL().
computeEnergyCG() [2/2]
template<typename _PotentialQM , typename _PotentialCL > real espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergyCG (int atomtype) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 972 of file VerletListPIadressInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeVirialX(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::fixedtupleList, espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getPotentialCL(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getVerletList(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::ntrotter, espressopp::Particle::pib(), espressopp::Particle::position(), espressopp::Particle::type(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::verletList.
computeEnergyDeriv()
template<typename _PotentialQM , typename _PotentialCL > real espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergyDeriv () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 565 of file VerletListPIadressInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergyAA().
Referenced by espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergy(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getPotentialCL().
computeVirial()
template<typename _PotentialQM , typename _PotentialCL > real espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeVirial () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 1125 of file VerletListPIadressInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeVirialTensor(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::fixedtupleList, espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getPotentialCL(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getPotentialQM(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::Particle::lambda(), mpiWorld, espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::ntrotter, espressopp::Particle::pib(), espressopp::Particle::position(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::speedup, espressopp::Particle::type(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::verletList.
Referenced by espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeVirialX(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getPotentialCL().
computeVirialTensor() [1/3]
template<typename _PotentialQM , typename _PotentialCL > void espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeVirialTensor (Tensor & w) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 1310 of file VerletListPIadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeVirial(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeVirialTensor(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getPotentialCL().
computeVirialTensor() [2/3]
template<typename _PotentialQM , typename _PotentialCL > void espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeVirialTensor (Tensor & w, real z) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 1317 of file VerletListPIadressInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeVirialTensor().
computeVirialTensor() [3/3]
template<typename _PotentialQM , typename _PotentialCL > void espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeVirialTensor (Tensor * w, int n) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 1325 of file VerletListPIadressInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getMaxCutoff().
computeVirialX()
template<typename _PotentialQM , typename _PotentialCL > void espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeVirialX (std::vector< real > & p_xx_total, int bins) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 1117 of file VerletListPIadressInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeVirial().
Referenced by espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergyCG(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getPotentialCL().
getFixedTupleList()
template<typename _PotentialQM , typename _PotentialCL > shared_ptr< FixedTupleListAdress > espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getFixedTupleList () inline
Definition at line 71 of file VerletListPIadressInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::fixedtupleList.
getMaxCutoff()
template<typename _PotentialQM , typename _PotentialCL > real espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getMaxCutoff () inline virtual
This method returns the maximal cutoff defined for one type pair.
Implements espressopp::interaction::Interaction.
Definition at line 1333 of file VerletListPIadressInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getPotentialCL(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::ntypes.
Referenced by espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeVirialTensor(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getPotentialCL().
getNTrotter()
template<typename _PotentialQM , typename _PotentialCL > int espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getNTrotter () inline
Definition at line 80 of file VerletListPIadressInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::ntrotter.
getPotentialCL()
template<typename _PotentialQM , typename _PotentialCL > PotentialCL& espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getPotentialCL (int type1, int type2) inline
Definition at line 119 of file VerletListPIadressInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::addForces(), espressopp::esutil::Array2D< T, outlier_mode >::at(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergy(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergyAA(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergyCG(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergyDeriv(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeVirial(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeVirialTensor(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeVirialX(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getMaxCutoff(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::potentialArrayCL.
Referenced by espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::addForces(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergy(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergyCG(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeVirial(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getMaxCutoff().
getPotentialQM()
template<typename _PotentialQM , typename _PotentialCL > PotentialQM& espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getPotentialQM (int type1, int type2) inline
Definition at line 115 of file VerletListPIadressInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::potentialArrayQM.
Referenced by espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::addForces(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergy(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergyAA(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeVirial().
getSpeedup()
template<typename _PotentialQM , typename _PotentialCL > bool espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getSpeedup () inline
Definition at line 89 of file VerletListPIadressInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::speedup.
getVerletList()
template<typename _PotentialQM , typename _PotentialCL > shared_ptr<VerletListAdress> espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getVerletList () inline
Definition at line 62 of file VerletListPIadressInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::verletList.
Referenced by espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergy(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergyAA(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergyCG().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Interaction::LOG4ESPP_DECL_LOGGER (theLogger) static protected inherited
Logger.
Referenced by espressopp::interaction::Interaction::~Interaction().
registerPython()
void espressopp::interaction::Interaction::registerPython () static inherited
Definition at line 36 of file Interaction.cpp.
References espressopp::interaction::Interaction::bondType(), espressopp::interaction::Interaction::computeEnergy(), espressopp::interaction::Interaction::computeEnergyAA(), espressopp::interaction::Interaction::computeEnergyCG(), espressopp::interaction::Interaction::computeEnergyDeriv(), and espressopp::interaction::Interaction::computeVirial().
Referenced by espressopp::interaction::registerPython(), and espressopp::interaction::Interaction::~Interaction().
setFixedTupleList()
template<typename _PotentialQM , typename _PotentialCL > void espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::setFixedTupleList (shared_ptr< FixedTupleListAdress > _fixedtupleList) inline
Definition at line 67 of file VerletListPIadressInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::fixedtupleList.
setNTrotter()
template<typename _PotentialQM , typename _PotentialCL > void espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::setNTrotter (int _ntrotter) inline
Definition at line 76 of file VerletListPIadressInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::ntrotter.
setPotentialCL()
template<typename _PotentialQM , typename _PotentialCL > void espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::setPotentialCL (int type1, int type2, const PotentialCL & potential) inline
Definition at line 105 of file VerletListPIadressInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::ntypes, and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::potentialArrayCL.
setPotentialQM()
template<typename _PotentialQM , typename _PotentialCL > void espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::setPotentialQM (int type1, int type2, const PotentialQM & potential) inline
Definition at line 94 of file VerletListPIadressInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::ntypes, and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::potentialArrayQM.
setSpeedup()
template<typename _PotentialQM , typename _PotentialCL > void espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::setSpeedup (bool _speedup) inline
Definition at line 85 of file VerletListPIadressInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::speedup.
setVerletList()
template<typename _PotentialQM , typename _PotentialCL > void espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::setVerletList (shared_ptr< VerletListAdress > _verletList) inline
Definition at line 58 of file VerletListPIadressInteractionTemplate.hpp.
References espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::verletList.
Member Data Documentation
adrZone
template<typename _PotentialQM , typename _PotentialCL > std::set<Particle*> espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::adrZone protected
Definition at line 150 of file VerletListPIadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::addForces().
energydiff
template<typename _PotentialQM , typename _PotentialCL > boost::unordered_map<Particle*, real> espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::energydiff protected
Definition at line 149 of file VerletListPIadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::addForces().
fixedtupleList
template<typename _PotentialQM , typename _PotentialCL > shared_ptr<FixedTupleListAdress> espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::fixedtupleList protected
Definition at line 143 of file VerletListPIadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::addForces(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergy(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergyAA(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergyCG(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeVirial(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getFixedTupleList(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::setFixedTupleList().
ntrotter
template<typename _PotentialQM , typename _PotentialCL > int espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::ntrotter protected
Definition at line 147 of file VerletListPIadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::addForces(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergy(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergyAA(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergyCG(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeVirial(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getNTrotter(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::setNTrotter().
ntypes
template<typename _PotentialQM , typename _PotentialCL > int espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::ntypes protected
Definition at line 141 of file VerletListPIadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getMaxCutoff(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::setPotentialCL(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::setPotentialQM(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::VerletListPIadressInteractionTemplate().
potentialArrayCL
template<typename _PotentialQM , typename _PotentialCL > esutil::Array2D<PotentialCL, esutil::enlarge> espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::potentialArrayCL protected
Definition at line 145 of file VerletListPIadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getPotentialCL(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::setPotentialCL(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::VerletListPIadressInteractionTemplate().
potentialArrayQM
template<typename _PotentialQM , typename _PotentialCL > esutil::Array2D<PotentialQM, esutil::enlarge> espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::potentialArrayQM protected
Definition at line 144 of file VerletListPIadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getPotentialQM(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::setPotentialQM(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::VerletListPIadressInteractionTemplate().
speedup
template<typename _PotentialQM , typename _PotentialCL > bool espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::speedup protected
Definition at line 148 of file VerletListPIadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::addForces(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergy(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeVirial(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getSpeedup(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::setSpeedup().
verletList
template<typename _PotentialQM , typename _PotentialCL > shared_ptr<VerletListAdress> espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::verletList protected
Definition at line 142 of file VerletListPIadressInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::addForces(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergy(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergyAA(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergyCG(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeVirial(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getVerletList(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::setVerletList().
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/interaction/VerletListPIadressInteractionTemplate.hpp