ESPResSo++: espressopp::interaction::TabulatedDihedral Class Reference
espressopp::interaction::TabulatedDihedral Class Reference
#include <TabulatedDihedral.hpp>
Public Member Functions
TabulatedDihedral ()
TabulatedDihedral (int itype, const char *filename)
TabulatedDihedral (int itype, const char *filename, real cutoff)
void setInterpolationType (int itype)
Setter for the interpolation type.
int getInterpolationType () const
Getter for the interpolation type.
void setFilename (int itype, const char *_filename)
const char * getFilename () const
real _computeEnergyRaw (real phi) const
real d (int i, int j) const
Real3D prod (Real3D a, Real3D b) const
Compute dot product of two vectors.
void _computeForceRaw (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &r21, const Real3D &r32, const Real3D &r43) const
real _computeForceRaw (real phi) const
virtual real computeEnergy (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
virtual real computeEnergy (real phi) const
virtual void computeForce (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
virtual real computeForce (real phi) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)
virtual shared_ptr< FixedPairList > getColVarBondList () const
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &ftl)
virtual shared_ptr< FixedTripleList > getColVarAngleList () const
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fql)
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const
virtual void setColVar (const RealND &cv)
virtual void setColVar (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43, const bc::BC &bc)
virtual RealND getColVar () const
virtual void computeColVarWeights (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43, const bc::BC &bc)
real _computeEnergy (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
real _computeEnergy (real phi) const
void _computeForce (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
Static Public Member Functions
static void registerPython ()
static real computePhi (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43)
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
TabulatedDihedral * derived_this ()
const TabulatedDihedral * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
shared_ptr< FixedPairList > colVarBondList
shared_ptr< FixedTripleList > colVarAngleList
shared_ptr< FixedQuadrupleList > colVarDihedList
RealND colVar
Private Attributes
std::string filename
shared_ptr< Interpolation > table
int interpolationType
Detailed Description
Definition at line 37 of file TabulatedDihedral.hpp.
Constructor & Destructor Documentation
TabulatedDihedral() [1/3]
espressopp::interaction::TabulatedDihedral::TabulatedDihedral () inline
Definition at line 47 of file TabulatedDihedral.hpp.
TabulatedDihedral() [2/3]
espressopp::interaction::TabulatedDihedral::TabulatedDihedral (int itype, const char * filename) inline
Definition at line 51 of file TabulatedDihedral.hpp.
References setFilename(), and setInterpolationType().
TabulatedDihedral() [3/3]
espressopp::interaction::TabulatedDihedral::TabulatedDihedral (int itype, const char * filename, real cutoff) inline
Definition at line 56 of file TabulatedDihedral.hpp.
References espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >::setCutoff(), setFilename(), and setInterpolationType().
Member Function Documentation
_computeEnergy() [1/2]
real espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >::_computeEnergy (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline inherited
Definition at line 285 of file DihedralPotential.hpp.
_computeEnergy() [2/2]
real espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >::_computeEnergy (real phi) const inline inherited
Definition at line 295 of file DihedralPotential.hpp.
_computeEnergyRaw()
real espressopp::interaction::TabulatedDihedral::_computeEnergyRaw (real phi) const inline
Definition at line 74 of file TabulatedDihedral.hpp.
_computeForce()
void espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >::_computeForce (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline inherited
Definition at line 317 of file DihedralPotential.hpp.
_computeForceRaw() [1/2]
void espressopp::interaction::TabulatedDihedral::_computeForceRaw (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & r21, const Real3D & r32, const Real3D & r43) const inline
Definition at line 100 of file TabulatedDihedral.hpp.
References espressopp::Real3D::cross(), d(), M_PI, prod(), and espressopp::Real3D::sqr().
_computeForceRaw() [2/2]
real espressopp::interaction::TabulatedDihedral::_computeForceRaw (real phi) const inline
Definition at line 187 of file TabulatedDihedral.hpp.
computeColVarWeights()
void espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >::computeColVarWeights (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 256 of file DihedralPotential.hpp.
computeEnergy() [1/2]
real espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >::computeEnergy (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 265 of file DihedralPotential.hpp.
computeEnergy() [2/2]
real espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >::computeEnergy (real phi) const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 278 of file DihedralPotential.hpp.
computeForce() [1/2]
void espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >::computeForce (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 303 of file DihedralPotential.hpp.
computeForce() [2/2]
real espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >::computeForce (real phi) const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 331 of file DihedralPotential.hpp.
computePhi()
real espressopp::interaction::DihedralPotential::computePhi (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) static inherited
Definition at line 31 of file DihedralPotential.cpp.
References espressopp::Real3D::abs(), espressopp::Real3D::cross(), and espressopp::interaction::LOG4ESPP_LOGGER().
Referenced by espressopp::interaction::DihedralPotential::registerPython(), espressopp::interaction::TabulatedSubEnsDihedral::setColVar(), espressopp::interaction::TabulatedSubEnsAngular::setColVar(), and espressopp::interaction::TabulatedSubEns::setColVar().
d()
real espressopp::interaction::TabulatedDihedral::d (int i, int j) const inline
Definition at line 82 of file TabulatedDihedral.hpp.
Referenced by _computeForceRaw(), and prod().
derived_this() [1/2]
TabulatedDihedral * espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >::derived_this () inline protected inherited
Definition at line 154 of file DihedralPotential.hpp.
derived_this() [2/2]
const TabulatedDihedral * espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >::derived_this () const inline protected inherited
Definition at line 158 of file DihedralPotential.hpp.
getColVar()
RealND espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >::getColVar () const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 250 of file DihedralPotential.hpp.
getColVarAngleList()
shared_ptr< FixedTripleList > espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >::getColVarAngleList () const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 213 of file DihedralPotential.hpp.
getColVarBondList()
shared_ptr< FixedPairList > espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >::getColVarBondList () const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 199 of file DihedralPotential.hpp.
getColVarDihedList()
shared_ptr< FixedQuadrupleList > espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >::getColVarDihedList () const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 227 of file DihedralPotential.hpp.
getCutoff()
real espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 185 of file DihedralPotential.hpp.
getFilename()
const char* espressopp::interaction::TabulatedDihedral::getFilename () const inline
Definition at line 70 of file TabulatedDihedral.hpp.
Referenced by espressopp::interaction::TabulatedDihedral_pickle::getinitargs(), and registerPython().
getInterpolationType()
int espressopp::interaction::TabulatedDihedral::getInterpolationType () const inline
Getter for the interpolation type.
Definition at line 66 of file TabulatedDihedral.hpp.
References interpolationType, and setFilename().
Referenced by espressopp::interaction::TabulatedDihedral_pickle::getinitargs().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::DihedralPotential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
prod()
Real3D espressopp::interaction::TabulatedDihedral::prod (Real3D a, Real3D b) const inline
Compute dot product of two vectors.
Definition at line 90 of file TabulatedDihedral.hpp.
References d().
Referenced by _computeForceRaw().
registerPython()
void espressopp::interaction::TabulatedDihedral::registerPython () static
Definition at line 69 of file TabulatedDihedral.cpp.
References getFilename(), and setFilename().
Referenced by espressopp::interaction::registerPython().
setColVar() [1/2]
void espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >::setColVar (const RealND & cv) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 234 of file DihedralPotential.hpp.
setColVar() [2/2]
void espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >::setColVar (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 241 of file DihedralPotential.hpp.
setColVarAngleList()
void espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >::setColVarAngleList (const shared_ptr< FixedTripleList > & ftl) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 206 of file DihedralPotential.hpp.
setColVarBondList()
void espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >::setColVarBondList (const shared_ptr< FixedPairList > & fpl) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 192 of file DihedralPotential.hpp.
setColVarDihedList()
void espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fql) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 220 of file DihedralPotential.hpp.
setCutoff()
void espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 177 of file DihedralPotential.hpp.
Referenced by TabulatedDihedral().
setFilename()
void espressopp::interaction::TabulatedDihedral::setFilename (int itype, const char * _filename)
Definition at line 39 of file TabulatedDihedral.cpp.
References filename, and table.
Referenced by getInterpolationType(), registerPython(), and TabulatedDihedral().
setInterpolationType()
void espressopp::interaction::TabulatedDihedral::setInterpolationType (int itype) inline
Setter for the interpolation type.
Definition at line 63 of file TabulatedDihedral.hpp.
Referenced by TabulatedDihedral().
Member Data Documentation
colVar
RealND espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >::colVar protected inherited
Definition at line 152 of file DihedralPotential.hpp.
colVarAngleList
shared_ptr<FixedTripleList> espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >::colVarAngleList protected inherited
Definition at line 148 of file DihedralPotential.hpp.
colVarBondList
shared_ptr<FixedPairList> espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >::colVarBondList protected inherited
Definition at line 146 of file DihedralPotential.hpp.
colVarDihedList
shared_ptr<FixedQuadrupleList> espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >::colVarDihedList protected inherited
Definition at line 150 of file DihedralPotential.hpp.
cutoff
real espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >::cutoff protected inherited
Definition at line 143 of file DihedralPotential.hpp.
cutoffSqr
real espressopp::interaction::DihedralPotentialTemplate< TabulatedDihedral >::cutoffSqr protected inherited
Definition at line 144 of file DihedralPotential.hpp.
filename
std::string espressopp::interaction::TabulatedDihedral::filename private
Definition at line 40 of file TabulatedDihedral.hpp.
Referenced by setFilename().
interpolationType
int espressopp::interaction::TabulatedDihedral::interpolationType private
Definition at line 42 of file TabulatedDihedral.hpp.
Referenced by getInterpolationType().
table
shared_ptr<Interpolation> espressopp::interaction::TabulatedDihedral::table private
Definition at line 41 of file TabulatedDihedral.hpp.
Referenced by setFilename().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/TabulatedDihedral.hpp
/home/espressopp/espressopp/src/interaction/TabulatedDihedral.cpp