ESPResSo++: espressopp::Tensor Class Reference
espressopp::Tensor Class Reference
The class Tensor stands for a symmetric 3x3 matrix.
#include <Tensor.hpp>
Public Member Functions
Tensor ()
Tensor (real v)
Tensor (real xx, real yy, real zz, real xy, real xz, real yz)
Tensor (const Real3D &v1, const Real3D &v2)
Tensor & operator= (const Tensor &v)
real & operator[] (int i)
const real & operator[] (int i) const
real & at (int i)
const real & at (int i) const
void setItem (int i, real v)
real getItem (int i) const
Tensor & operator+= (const Tensor &v)
Tensor & operator-= (const Tensor &v)
Tensor & operator*= (const real v)
Tensor & operator/= (const real v)
bool operator== (const Tensor &v) const
bool operator!= (const Tensor &v) const
Tensor operator+ (const Tensor &v) const
Tensor operator- (const Tensor &v) const
Tensor operator* (real v) const
Tensor operator/ (real v) const
real sqr () const
real abs () const
const real * get () const
real * get ()
Static Public Member Functions
static void registerPython ()
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
real data [6]
Friends
class boost::serialization::access
Detailed Description
The class Tensor stands for a symmetric 3x3 matrix.
Definition at line 34 of file Tensor.hpp.
Constructor & Destructor Documentation
Tensor() [1/4]
espressopp::Tensor::Tensor () inline
Definition at line 102 of file Tensor.hpp.
Referenced by operator*(), operator+(), operator-(), and operator/().
Tensor() [2/4]
espressopp::Tensor::Tensor (real v) inline
Definition at line 104 of file Tensor.hpp.
References data.
Tensor() [3/4]
espressopp::Tensor::Tensor (real xx, real yy, real zz, real xy, real xz, real yz) inline
Definition at line 113 of file Tensor.hpp.
References data.
Tensor() [4/4]
espressopp::Tensor::Tensor (const Real3D & v1, const Real3D & v2) inline
Definition at line 122 of file Tensor.hpp.
References data.
Member Function Documentation
abs()
real espressopp::Tensor::abs () const
at() [1/2]
real & espressopp::Tensor::at (int i) inline
Definition at line 144 of file Tensor.hpp.
Referenced by getItem(), and setItem().
at() [2/2]
const real & espressopp::Tensor::at (int i) const inline
Definition at line 150 of file Tensor.hpp.
get() [1/2]
real* espressopp::Tensor::get () inline
Definition at line 86 of file Tensor.hpp.
References data.
get() [2/2]
const real* espressopp::Tensor::get () const inline
Definition at line 85 of file Tensor.hpp.
References data.
getItem()
real espressopp::Tensor::getItem (int i) const inline
Definition at line 159 of file Tensor.hpp.
References at().
Referenced by registerPython().
operator!=()
bool espressopp::Tensor::operator!= (const Tensor & v) const inline
Definition at line 190 of file Tensor.hpp.
operator*()
Tensor espressopp::Tensor::operator* (real v) const inline
Definition at line 200 of file Tensor.hpp.
References Tensor().
operator*=()
Tensor & espressopp::Tensor::operator*= (const real v) inline
Definition at line 169 of file Tensor.hpp.
References data.
operator+()
Tensor espressopp::Tensor::operator+ (const Tensor & v) const inline
Definition at line 194 of file Tensor.hpp.
References Tensor().
operator+=()
Tensor & espressopp::Tensor::operator+= (const Tensor & v) inline
Definition at line 163 of file Tensor.hpp.
References data.
operator-()
Tensor espressopp::Tensor::operator- (const Tensor & v) const inline
Definition at line 197 of file Tensor.hpp.
References Tensor().
operator-=()
Tensor & espressopp::Tensor::operator-= (const Tensor & v) inline
Definition at line 166 of file Tensor.hpp.
References data.
operator/()
Tensor espressopp::Tensor::operator/ (real v) const inline
Definition at line 203 of file Tensor.hpp.
References Tensor().
operator/=()
Tensor & espressopp::Tensor::operator/= (const real v) inline
Definition at line 172 of file Tensor.hpp.
References data.
operator=()
Tensor & espressopp::Tensor::operator= (const Tensor & v) inline
Definition at line 131 of file Tensor.hpp.
References data.
operator==()
bool espressopp::Tensor::operator== (const Tensor & v) const inline
Definition at line 180 of file Tensor.hpp.
References data.
operator[]() [1/2]
real & espressopp::Tensor::operator[] (int i) inline
Definition at line 138 of file Tensor.hpp.
References data.
operator[]() [2/2]
const real & espressopp::Tensor::operator[] (int i) const inline
Definition at line 141 of file Tensor.hpp.
References data.
registerPython()
void espressopp::Tensor::registerPython () static
Definition at line 37 of file Tensor.cpp.
References getItem(), and setItem().
Referenced by espressopp::registerPython().
serialize()
template<class Archive > void espressopp::Tensor::serialize (Archive & ar, const unsigned int version) inline private
Definition at line 40 of file Tensor.hpp.
References data.
setItem()
void espressopp::Tensor::setItem (int i, real v) inline
Definition at line 156 of file Tensor.hpp.
References at().
Referenced by registerPython().
sqr()
real espressopp::Tensor::sqr () const
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Definition at line 38 of file Tensor.hpp.
Member Data Documentation
data
real espressopp::Tensor::data[6] private
Definition at line 35 of file Tensor.hpp.
Referenced by get(), operator*=(), operator+=(), operator-=(), operator/=(), operator=(), operator==(), operator[](), serialize(), and Tensor().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/Tensor.hpp
/home/espressopp/espressopp/src/Tensor.cpp