ESPResSo++: espressopp::esutil::Array4D< T, enlarge > Class Template Reference
espressopp::esutil::Array4D< T, enlarge > Class Template Reference
#include <Array4D.hpp>
Public Types
typedef T value_type
The type of object, T, stored in the Array1D.
typedef T & reference
Reference to to a T object.
typedef const T & const_reference
Const reference to to a T object.
typedef Super::size_type size_type
An unsigned integer type.
typedef Super::iterator iterator
Iterator used to iterate through an Array1D.
typedef Super::const_iterator const_iterator
Const-iterator used to iterate through an Array1D.
Public Member Functions
Array4D (const T &prototype=T())
Default constructor.
Array4D (size_type n, size_type m, size_type p, size_type q, const T &prototype=T())
Creates a one-dimensional array of size n with n copies of prototype.
void init (size_type n, size_type m, size_type p, size_type q, const T &prototype=T())
Creates a one-dimensional array of size n with n copies of prototype.
void set_prototype (const T &prototype=T())
Sets the prototype used when the Array4D<T,enlarge> is automatically resized.
reference at (size_type i, size_type j, size_type k, size_type l)
Returns the element at position i x j x p x q.
template<class Vector >
reference at (const Vector &pos)
Returns the element at position pos.
void clear ()
Erases all elements.
void resize (size_type n, size_type m, size_type l, size_type k, const T &t=T())
Changes the size of the Array4D so that the size becomes n x m x p x q array.
size_type size_n () const
Returns the n -size of the array.
size_type size_m () const
Returns the m -size of the array.
size_type size_p () const
Returns the p -size of the array.
size_type size_q () const
Returns the q -size of the array.
bool empty () const
true if the Array4D's size is 0 x 0 x 0 x 0.
reference operator() (size_type i, size_type j, size_type k, size_type l)
Returns the element at position i x j x k.
const_reference operator() (size_type i, size_type j, size_type k, size_type l) const
Returns the element at position i x j x k.
reference operator() (const Vector &pos)
Returns the element at position pos.
const_reference operator() (const Vector &pos) const
Returns the element at position pos.
const_reference at (size_type i, size_type j, size_type k, size_type l) const
Returns the element at position i x j x k.
const_reference at (const Vector &pos) const
Returns the element at position pos.
iterator begin ()
Returns an iterator pointing to the beginning of the Array4D.
const_iterator begin () const
Returns a const_iterator pointing to the beginning of the Array4D.
iterator end ()
Returns an iterator pointing to the end of the Array4D.
const_iterator end () const
Returns a const_iterator pointing to the end of the Array4D.
void operator+= (const T2 &t2)
Adds t2 to each of the elements.
void operator-= (const T2 &t2)
Adds t2 to each of the elements.
void operator*= (const T2 &t2)
Multiplies each of the elements by t2.
void operator/= (const T2 &t2)
Divides each of the elements by t2.
void operator/= (const double &x)
bool operator== (const Array4D< T, exception > &a)
Equality operator.
bool operator!= (const Array4D< T, exception > &a)
Inequality operator.
Private Types
typedef Array4D< T, exception > Super
The super class of the array (i.e.
Private Attributes
value_type prototype
Detailed Description
template<class T>
class espressopp::esutil::Array4D< T, enlarge >
Definition at line 260 of file Array4D.hpp.
Member Typedef Documentation
template<class T > typedef Super::const_iterator espressopp::esutil::Array4D< T, enlarge >::const_iterator
Const-iterator used to iterate through an Array1D.
Definition at line 276 of file Array4D.hpp.
template<class T > typedef const T& espressopp::esutil::Array4D< T, enlarge >::const_reference
Const reference to to a T object.
Definition at line 270 of file Array4D.hpp.
template<class T > typedef Super::iterator espressopp::esutil::Array4D< T, enlarge >::iterator
Iterator used to iterate through an Array1D.
Definition at line 274 of file Array4D.hpp.
template<class T > typedef T& espressopp::esutil::Array4D< T, enlarge >::reference
Reference to to a T object.
Definition at line 268 of file Array4D.hpp.
template<class T > typedef Super::size_type espressopp::esutil::Array4D< T, enlarge >::size_type
An unsigned integer type.
Definition at line 272 of file Array4D.hpp.
template<class T > typedef Array4D<T, exception> espressopp::esutil::Array4D< T, enlarge >::Super private
The super class of the array (i.e.
vector<T>).
Definition at line 262 of file Array4D.hpp.
template<class T > typedef T espressopp::esutil::Array4D< T, enlarge >::value_type
The type of object, T, stored in the Array1D.
Definition at line 266 of file Array4D.hpp.
Constructor & Destructor Documentation
template<class T > espressopp::esutil::Array4D< T, enlarge >::Array4D (const T & prototype = T()) inline explicit
Default constructor.
Definition at line 284 of file Array4D.hpp.
References espressopp::esutil::Array4D< T, outlier_mode >::init().
template<class T > espressopp::esutil::Array4D< T, enlarge >::Array4D (size_type n, size_type m, size_type p, size_type q, const T & prototype = T()) inline
Creates a one-dimensional array of size n with n copies of prototype.
Also sets the prototype.
Definition at line 291 of file Array4D.hpp.
References espressopp::esutil::Array4D< T, outlier_mode >::init().
Member Function Documentation
const_reference espressopp::esutil::Array4D< T, outlier_mode >::at (size_type i, size_type j, size_type k, size_type l) const inline inherited
Returns the element at position i x j x k.
Exceptions
out_of_range i is out of range of the Array4D
Definition at line 163 of file Array4D.hpp.
const_reference espressopp::esutil::Array4D< T, outlier_mode >::at (const Vector & pos) const inline inherited
Returns the element at position pos.
pos must be a vector where the expressions pos[0], pos[1] and pos[2] return the first and second element.
Exceptions
out_of_range i is out of range of the Array4D
Definition at line 187 of file Array4D.hpp.
template<class T > reference espressopp::esutil::Array4D< T, enlarge >::at (size_type i, size_type j, size_type k, size_type l) inline
Returns the element at position i x j x p x q.
When the element doesn't exist, the Array4D is automatically extended so that the element exists. The new elements are initialised with copies of the prototype.
Definition at line 317 of file Array4D.hpp.
References espressopp::esutil::Array4D< T, outlier_mode >::size_m(), espressopp::esutil::Array4D< T, outlier_mode >::size_n(), espressopp::esutil::Array4D< T, outlier_mode >::size_p(), and espressopp::esutil::Array4D< T, outlier_mode >::size_q().
template<class T > template<class Vector > reference espressopp::esutil::Array4D< T, enlarge >::at (const Vector & pos) inline
Returns the element at position pos.
pos must be a vector where the expressions pos[0], pos[1] and pos[2] return the first and second element.
When the element doesn't exist, the Array4D is automatically extended so that the element exists. The new elements are initialised with copies of the prototype.
Definition at line 376 of file Array4D.hpp.
References at().
Referenced by at().
iterator espressopp::esutil::Array4D< T, outlier_mode >::begin () inline inherited
Returns an iterator pointing to the beginning of the Array4D.
Definition at line 191 of file Array4D.hpp.
const_iterator espressopp::esutil::Array4D< T, outlier_mode >::begin () const inline inherited
Returns a const_iterator pointing to the beginning of the Array4D.
Definition at line 195 of file Array4D.hpp.
void espressopp::esutil::Array4D< T, outlier_mode >::clear () inline inherited
Erases all elements.
Definition at line 71 of file Array4D.hpp.
bool espressopp::esutil::Array4D< T, outlier_mode >::empty () const inline inherited
true if the Array4D's size is 0 x 0 x 0 x 0.
Definition at line 117 of file Array4D.hpp.
iterator espressopp::esutil::Array4D< T, outlier_mode >::end () inline inherited
Returns an iterator pointing to the end of the Array4D.
Definition at line 199 of file Array4D.hpp.
const_iterator espressopp::esutil::Array4D< T, outlier_mode >::end () const inline inherited
Returns a const_iterator pointing to the end of the Array4D.
Definition at line 203 of file Array4D.hpp.
template<class T > void espressopp::esutil::Array4D< T, enlarge >::init (size_type n, size_type m, size_type p, size_type q, const T & prototype = T()) inline
Creates a one-dimensional array of size n with n copies of prototype.
Also sets the prototype.
Definition at line 298 of file Array4D.hpp.
bool espressopp::esutil::Array4D< T, outlier_mode >::operator!= (const Array4D< T, exception > & a) inline inherited
Inequality operator.
Definition at line 243 of file Array4D.hpp.
reference espressopp::esutil::Array4D< T, outlier_mode >::operator() (size_type i, size_type j, size_type k, size_type l) inline inherited
Returns the element at position i x j x k.
Attention
No range checking.
Definition at line 121 of file Array4D.hpp.
const_reference espressopp::esutil::Array4D< T, outlier_mode >::operator() (size_type i, size_type j, size_type k, size_type l) const inline inherited
Returns the element at position i x j x k.
Attention
No range checking.
Definition at line 127 of file Array4D.hpp.
reference espressopp::esutil::Array4D< T, outlier_mode >::operator() (const Vector & pos) inline inherited
Returns the element at position pos.
pos must be a vector where the expressions pos[0], pos[1] and pos[2] return the indices.
Attention
No range checking.
Definition at line 137 of file Array4D.hpp.
const_reference espressopp::esutil::Array4D< T, outlier_mode >::operator() (const Vector & pos) const inline inherited
Returns the element at position pos.
pos must be a vector where the expressions pos[0], pos[1] and pos[2] return the indices.
Attention
No range checking.
Definition at line 147 of file Array4D.hpp.
void espressopp::esutil::Array4D< T, outlier_mode >::operator*= (const T2 & t2) inline inherited
Multiplies each of the elements by t2.
Definition at line 225 of file Array4D.hpp.
void espressopp::esutil::Array4D< T, outlier_mode >::operator+= (const T2 & t2) inline inherited
Adds t2 to each of the elements.
Definition at line 213 of file Array4D.hpp.
void espressopp::esutil::Array4D< T, outlier_mode >::operator-= (const T2 & t2) inline inherited
Adds t2 to each of the elements.
Definition at line 219 of file Array4D.hpp.
void espressopp::esutil::Array4D< T, outlier_mode >::operator/= (const T2 & t2) inline inherited
Divides each of the elements by t2.
Definition at line 229 of file Array4D.hpp.
void espressopp::esutil::Array4D< T, outlier_mode >::operator/= (const double & x) inline inherited
Definition at line 231 of file Array4D.hpp.
bool espressopp::esutil::Array4D< T, outlier_mode >::operator== (const Array4D< T, exception > & a) inline inherited
Equality operator.
Definition at line 237 of file Array4D.hpp.
void espressopp::esutil::Array4D< T, outlier_mode >::resize (size_type n, size_type m, size_type l, size_type k, const T & t = T()) inline inherited
Changes the size of the Array4D so that the size becomes n x m x p x q array.
Attention
The elements of the Array4D are not initialised consistently, so the values are undefined. The t parameter exists only for the purpose to provide a default T value when new elements are created and needs to be specified only when T has no default constructor.
Definition at line 96 of file Array4D.hpp.
template<class T > void espressopp::esutil::Array4D< T, enlarge >::set_prototype (const T & prototype = T()) inline
Sets the prototype used when the Array4D<T,enlarge> is automatically resized.
Definition at line 305 of file Array4D.hpp.
size_type espressopp::esutil::Array4D< T, outlier_mode >::size_m () const inline inherited
Returns the m -size of the array.
Definition at line 108 of file Array4D.hpp.
size_type espressopp::esutil::Array4D< T, outlier_mode >::size_n () const inline inherited
Returns the n -size of the array.
Definition at line 105 of file Array4D.hpp.
size_type espressopp::esutil::Array4D< T, outlier_mode >::size_p () const inline inherited
Returns the p -size of the array.
Definition at line 111 of file Array4D.hpp.
size_type espressopp::esutil::Array4D< T, outlier_mode >::size_q () const inline inherited
Returns the q -size of the array.
Definition at line 114 of file Array4D.hpp.
Member Data Documentation
template<class T > value_type espressopp::esutil::Array4D< T, enlarge >::prototype private
Definition at line 379 of file Array4D.hpp.
The documentation for this class was generated from the following file:
/home/travis/build/espressopp/espressopp/src/esutil/Array4D.hpp