ESPResSo++: espressopp::interaction::SingleParticlePotentialTemplate< Derived > Class Template Reference
espressopp::interaction::SingleParticlePotentialTemplate< Derived > Class Template Reference abstract
Provides a template for the simple implementation of a position-dependent potential.
#include <SingleParticlePotential.hpp>
Public Member Functions
SingleParticlePotentialTemplate ()
virtual ~SingleParticlePotentialTemplate ()
virtual real computeEnergy (const Particle &p, const bc::BC &bc) const
virtual Real3D computeForce (const Particle &p, const bc::BC &bc) const
real _computeEnergy (const Particle &p, const bc::BC &bc) const
bool _computeForce (Real3D &force, const Particle &p, const bc::BC &bc) const
virtual real getMaxCutoff ()=0
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
Derived * derived_this ()
const Derived * derived_this () const
Detailed Description
template<class Derived>
class espressopp::interaction::SingleParticlePotentialTemplate< Derived >
Provides a template for the simple implementation of a position-dependent potential.
Definition at line 58 of file SingleParticlePotential.hpp.
Constructor & Destructor Documentation
template<class Derived > espressopp::interaction::SingleParticlePotentialTemplate< Derived >::SingleParticlePotentialTemplate () inline
Definition at line 88 of file SingleParticlePotential.hpp.
References espressopp::interaction::SingleParticlePotentialTemplate< Derived >::computeEnergy().
template<class Derived> virtual espressopp::interaction::SingleParticlePotentialTemplate< Derived >::~SingleParticlePotentialTemplate () inline virtual
Definition at line 61 of file SingleParticlePotential.hpp.
Member Function Documentation
template<class Derived > real espressopp::interaction::SingleParticlePotentialTemplate< Derived >::_computeEnergy (const Particle & p, const bc::BC & bc) const inline
Definition at line 101 of file SingleParticlePotential.hpp.
References espressopp::interaction::SingleParticlePotentialTemplate< Derived >::computeForce().
Referenced by espressopp::interaction::SingleParticlePotentialTemplate< Derived >::computeEnergy().
template<class Derived > bool espressopp::interaction::SingleParticlePotentialTemplate< Derived >::_computeForce (Real3D & force, const Particle & p, const bc::BC & bc) const inline
Definition at line 120 of file SingleParticlePotential.hpp.
Referenced by espressopp::interaction::SingleParticlePotentialTemplate< Derived >::computeForce().
template<class Derived > real espressopp::interaction::SingleParticlePotentialTemplate< Derived >::computeEnergy (const Particle & p, const bc::BC & bc) const inline virtual
Implements espressopp::interaction::SingleParticlePotential.
Definition at line 94 of file SingleParticlePotential.hpp.
References espressopp::interaction::SingleParticlePotentialTemplate< Derived >::_computeEnergy().
Referenced by espressopp::interaction::SingleParticlePotentialTemplate< Derived >::SingleParticlePotentialTemplate().
template<class Derived > Real3D espressopp::interaction::SingleParticlePotentialTemplate< Derived >::computeForce (const Particle & p, const bc::BC & bc) const inline virtual
Implements espressopp::interaction::SingleParticlePotential.
Definition at line 109 of file SingleParticlePotential.hpp.
References espressopp::interaction::SingleParticlePotentialTemplate< Derived >::_computeForce().
Referenced by espressopp::interaction::SingleParticlePotentialTemplate< Derived >::_computeEnergy().
template<class Derived> Derived* espressopp::interaction::SingleParticlePotentialTemplate< Derived >::derived_this () inline protected
Definition at line 73 of file SingleParticlePotential.hpp.
template<class Derived> const Derived* espressopp::interaction::SingleParticlePotentialTemplate< Derived >::derived_this () const inline protected
Definition at line 77 of file SingleParticlePotential.hpp.
virtual real espressopp::interaction::SingleParticlePotential::getMaxCutoff () pure virtual inherited
Implemented in espressopp::interaction::LennardJones93Wall, and espressopp::interaction::HarmonicTrap.
static espressopp::interaction::SingleParticlePotential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
void espressopp::interaction::SingleParticlePotential::registerPython () static inherited
Definition at line 38 of file SingleParticlePotential.cpp.
References espressopp::interaction::SingleParticlePotential::computeEnergy(), and espressopp::interaction::SingleParticlePotential::computeForce().
Referenced by espressopp::interaction::registerPython().
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/interaction/SingleParticlePotential.hpp