ESPResSo++: espressopp::integrator::LBInit Class Reference
espressopp::integrator::LBInit Class Reference
Abstract base class for arbitrary Init for LB simulations.
#include <LBInit.hpp>
Public Member Functions
LBInit (shared_ptr< System > _system, shared_ptr< LatticeBoltzmann > _latticeboltzmann)
virtual ~LBInit ()
virtual void createDenVel (real _rho0, Real3D _u0)=0
virtual void setForce (Real3D _force)=0
virtual void addForce (Real3D _force)=0
Static Public Member Functions
static void registerPython ()
Protected Attributes
shared_ptr< LatticeBoltzmann > latticeboltzmann
real rho0
Real3D u0
Detailed Description
Abstract base class for arbitrary Init for LB simulations.
Definition at line 32 of file LBInit.hpp.
Constructor & Destructor Documentation
espressopp::integrator::LBInit::LBInit (shared_ptr< System > _system, shared_ptr< LatticeBoltzmann > _latticeboltzmann) [inline]
Definition at line 35 of file LBInit.hpp.
References latticeboltzmann.
virtual espressopp::integrator::LBInit::~LBInit () [inline, virtual]
Definition at line 40 of file LBInit.hpp.
Member Function Documentation
virtual void espressopp::integrator::LBInit::addForce (Real3D _force) [pure virtual]
Implemented in espressopp::integrator::LBInitConstForce, espressopp::integrator::LBInitPeriodicForce, espressopp::integrator::LBInitPopUniform, and espressopp::integrator::LBInitPopWave.
Referenced by registerPython().
virtual void espressopp::integrator::LBInit::createDenVel (real _rho0, Real3D _u0) [pure virtual]
Implemented in espressopp::integrator::LBInitConstForce, espressopp::integrator::LBInitPeriodicForce, espressopp::integrator::LBInitPopUniform, and espressopp::integrator::LBInitPopWave.
Referenced by registerPython().
void espressopp::integrator::LBInit::registerPython () [static]
Reimplemented in espressopp::integrator::LBInitConstForce, espressopp::integrator::LBInitPeriodicForce, espressopp::integrator::LBInitPopUniform, and espressopp::integrator::LBInitPopWave.
Definition at line 32 of file LBInit.cpp.
References addForce(), createDenVel(), and setForce().
Referenced by espressopp::integrator::registerPython().
virtual void espressopp::integrator::LBInit::setForce (Real3D _force) [pure virtual]
Implemented in espressopp::integrator::LBInitConstForce, espressopp::integrator::LBInitPeriodicForce, espressopp::integrator::LBInitPopUniform, and espressopp::integrator::LBInitPopWave.
Referenced by registerPython().
Member Data Documentation
shared_ptr<LatticeBoltzmann> espressopp::integrator::LBInit::latticeboltzmann [protected]
Definition at line 52 of file LBInit.hpp.
Referenced by espressopp::integrator::LBInitConstForce::addForce(), espressopp::integrator::LBInitPeriodicForce::addForce(), espressopp::integrator::LBInitPopWave::createDenVel(), espressopp::integrator::LBInitPopUniform::createDenVel(), LBInit(), espressopp::integrator::LBInitConstForce::setForce(), and espressopp::integrator::LBInitPeriodicForce::setForce().
real espressopp::integrator::LBInit::rho0 [protected]
Definition at line 53 of file LBInit.hpp.
Real3D espressopp::integrator::LBInit::u0 [protected]
Definition at line 54 of file LBInit.hpp.
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/integrator/LBInit.hpp
/home/travis/build/espressopp/espressopp/src/integrator/LBInit.cpp