ESPResSo++: espressopp::interaction::AngularUniqueCosineSquared Class Reference
espressopp::interaction::AngularUniqueCosineSquared Class Reference
This class provides methods to compute forces and energies of the AngularUniqueCosineSquared angular potential.
#include <AngularUniqueCosineSquared.hpp>
Public Member Functions
AngularUniqueCosineSquared ()
AngularUniqueCosineSquared (real _K)
void setK (real _K)
real getK () const
real _computeEnergyRaw (real _theta, real _theta0) const
bool _computeForceRaw (Real3D &force12, Real3D &force32, const Real3D &r12, const Real3D &r32, real _theta0) const
real _computeForceRaw (real theta, real _theta0) const
virtual real computeEnergy (const Particle &p1, const Particle &p2, const Particle &p3, real theta0) const
virtual real computeEnergy (const Real3D &r12, const Real3D &r32, real theta0) const
virtual real computeEnergy (const real theta, real theta0) const
virtual void computeForce (Real3D &force12, Real3D &force32, const Particle &p1, const Particle &p2, const Particle &p3, real theta0) const
virtual void computeForce (Real3D &force12, Real3D &force32, const Real3D &r12, const Real3D &r32, real cos0) const
virtual real computeForce (real theta, real cos0) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
real _computeEnergy (const Particle &p1, const Particle &p2, const Particle &p3, real theta0) const
real _computeEnergy (const Real3D &r12, const Real3D &r32, real theta0) const
real _computeEnergy (real theta, real theta0) const
void _computeForce (Real3D &force12, Real3D &force32, const Particle &p1, const Particle &p2, const Particle &p3, real theta0) const
bool _computeForce (Real3D &force12, Real3D &force32, const Real3D &r12, const Real3D &r32, real theta0) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
AngularUniqueCosineSquared * derived_this ()
const AngularUniqueCosineSquared * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
Private Attributes
real K
Detailed Description
This class provides methods to compute forces and energies of the AngularUniqueCosineSquared angular potential.
To create a new angular potential one only needs to write the setter/getters and the variable dU_dtheta.
Definition at line 37 of file AngularUniqueCosineSquared.hpp.
Constructor & Destructor Documentation
AngularUniqueCosineSquared() [1/2]
espressopp::interaction::AngularUniqueCosineSquared::AngularUniqueCosineSquared () inline
Definition at line 44 of file AngularUniqueCosineSquared.hpp.
AngularUniqueCosineSquared() [2/2]
espressopp::interaction::AngularUniqueCosineSquared::AngularUniqueCosineSquared (real _K) inline
Definition at line 45 of file AngularUniqueCosineSquared.hpp.
Member Function Documentation
_computeEnergy() [1/3]
real espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueCosineSquared >::_computeEnergy (const Particle & p1, const Particle & p2, const Particle & p3, real theta0) const inline inherited
Definition at line 160 of file AngularUniquePotential.hpp.
References espressopp::Particle::position().
_computeEnergy() [2/3]
real espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueCosineSquared >::_computeEnergy (const Real3D & r12, const Real3D & r32, real theta0) const inline inherited
Definition at line 169 of file AngularUniquePotential.hpp.
References espressopp::Real3D::sqr().
_computeEnergy() [3/3]
real espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueCosineSquared >::_computeEnergy (real theta, real theta0) const inline inherited
Definition at line 183 of file AngularUniquePotential.hpp.
_computeEnergyRaw()
real espressopp::interaction::AngularUniqueCosineSquared::_computeEnergyRaw (real _theta, real _theta0) const inline
Definition at line 51 of file AngularUniqueCosineSquared.hpp.
_computeForce() [1/2]
void espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueCosineSquared >::_computeForce (Real3D & force12, Real3D & force32, const Particle & p1, const Particle & p2, const Particle & p3, real theta0) const inline inherited
Definition at line 213 of file AngularUniquePotential.hpp.
References espressopp::Particle::position().
_computeForce() [2/2]
bool espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueCosineSquared >::_computeForce (Real3D & force12, Real3D & force32, const Real3D & r12, const Real3D & r32, real theta0) const inline inherited
Definition at line 225 of file AngularUniquePotential.hpp.
_computeForceRaw() [1/2]
bool espressopp::interaction::AngularUniqueCosineSquared::_computeForceRaw (Real3D & force12, Real3D & force32, const Real3D & r12, const Real3D & r32, real _theta0) const inline
Definition at line 57 of file AngularUniqueCosineSquared.hpp.
References espressopp::Real3D::sqr().
_computeForceRaw() [2/2]
real espressopp::interaction::AngularUniqueCosineSquared::_computeForceRaw (real theta, real _theta0) const inline
Definition at line 81 of file AngularUniqueCosineSquared.hpp.
computeEnergy() [1/3]
real espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueCosineSquared >::computeEnergy (const Particle & p1, const Particle & p2, const Particle & p3, real theta0) const inline virtual inherited
Implements espressopp::interaction::AngularUniquePotential.
Definition at line 134 of file AngularUniquePotential.hpp.
References espressopp::Particle::position().
computeEnergy() [2/3]
real espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueCosineSquared >::computeEnergy (const Real3D & r12, const Real3D & r32, real theta0) const inline virtual inherited
Implements espressopp::interaction::AngularUniquePotential.
Definition at line 143 of file AngularUniquePotential.hpp.
References espressopp::Real3D::sqr().
computeEnergy() [3/3]
real espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueCosineSquared >::computeEnergy (const real theta, real theta0) const inline virtual inherited
Implements espressopp::interaction::AngularUniquePotential.
Definition at line 153 of file AngularUniquePotential.hpp.
computeForce() [1/3]
void espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueCosineSquared >::computeForce (Real3D & force12, Real3D & force32, const Particle & p1, const Particle & p2, const Particle & p3, real theta0) const inline virtual inherited
Implements espressopp::interaction::AngularUniquePotential.
Definition at line 191 of file AngularUniquePotential.hpp.
References espressopp::Particle::position().
computeForce() [2/3]
void espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueCosineSquared >::computeForce (Real3D & force12, Real3D & force32, const Real3D & r12, const Real3D & r32, real cos0) const inline virtual inherited
Implements espressopp::interaction::AngularUniquePotential.
Definition at line 203 of file AngularUniquePotential.hpp.
computeForce() [3/3]
real espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueCosineSquared >::computeForce (real theta, real cos0) const inline virtual inherited
Implements espressopp::interaction::AngularUniquePotential.
Definition at line 237 of file AngularUniquePotential.hpp.
derived_this() [1/2]
AngularUniqueCosineSquared * espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueCosineSquared >::derived_this () inline protected inherited
Definition at line 96 of file AngularUniquePotential.hpp.
derived_this() [2/2]
const AngularUniqueCosineSquared * espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueCosineSquared >::derived_this () const inline protected inherited
Definition at line 100 of file AngularUniquePotential.hpp.
References espressopp::interaction::AngularUniquePotentialTemplate< Derived >::AngularUniquePotentialTemplate().
getCutoff()
real espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueCosineSquared >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::AngularUniquePotential.
Definition at line 127 of file AngularUniquePotential.hpp.
getK()
real espressopp::interaction::AngularUniqueCosineSquared::getK () const inline
Definition at line 49 of file AngularUniqueCosineSquared.hpp.
References K.
Referenced by registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::AngularUniquePotential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
registerPython()
void espressopp::interaction::AngularUniqueCosineSquared::registerPython () static
Definition at line 33 of file AngularUniqueCosineSquared.cpp.
References getK(), and setK().
Referenced by espressopp::interaction::registerPython().
setCutoff()
void espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueCosineSquared >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::AngularUniquePotential.
Definition at line 119 of file AngularUniquePotential.hpp.
setK()
void espressopp::interaction::AngularUniqueCosineSquared::setK (real _K) inline
Definition at line 48 of file AngularUniqueCosineSquared.hpp.
Referenced by registerPython().
Member Data Documentation
cutoff
real espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueCosineSquared >::cutoff protected inherited
Definition at line 93 of file AngularUniquePotential.hpp.
cutoffSqr
real espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueCosineSquared >::cutoffSqr protected inherited
Definition at line 94 of file AngularUniquePotential.hpp.
K
real espressopp::interaction::AngularUniqueCosineSquared::K private
Definition at line 39 of file AngularUniqueCosineSquared.hpp.
Referenced by getK().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/AngularUniqueCosineSquared.hpp
/home/espressopp/espressopp/src/interaction/AngularUniqueCosineSquared.cpp