ESPResSo++: log4espp::PyLogger Class Reference
log4espp::PyLogger Class Reference
PyLogger is an implementaton of the abstract class Logger that uses corresponding Python Logger objects for the output of the logging statements.
#include <PyLogger.hpp>
Public Types
typedef boost::python::object object
enum Level {
TRACE = 10, DEBUG = 20, INFO = 30, WARN = 40,
ERROR = 50, FATAL = 60
}
Public Member Functions
PyLogger (std::string, class Logger *parent)
Constructor for a Logger that will use a corresponding Python instance for the configuration and for the output of the logging messages.
~PyLogger ()
void setPythonLogger (boost::python::object pyLogger)
This routine sets the Python instance of the logger and/or updates the logging level of the C++ class.
void setPythonLoggers (std::string &parentName)
This routine sets the Python loggers for this logger and the descendants.
virtual void trace (Location loc, const std::string &msg)
Implementation of Logger::trace.
virtual void debug (Location loc, const std::string &msg)
Implementation of Logger::debug.
virtual void info (Location loc, const std::string &msg)
Implementation of Logger::info.
virtual void warn (Location loc, const std::string &msg)
Implementation of Logger::warn.
virtual void error (Location loc, const std::string &msg)
Implementation of Logger::error.
virtual void fatal (Location loc, const std::string &msg)
Implementation of Logger::fatal.
std::string getFullName ()
Asks for the full name of the logger, e.g.
bool isTraceEnabled ()
Check if logging statements of level TRACE are enabled.
bool isDebugEnabled ()
Check if logging statements of level DEBUG are enabled.
bool isInfoEnabled ()
Check if logging statements of level INFO are enabled.
bool isWarnEnabled ()
Check if logging statements of level WARN are enabled.
bool isErrorEnabled ()
Check if logging statements of level ERROR are enabled.
bool isFatalEnabled ()
Check if logging statements of level FATAL are enabled.
Level getLevel ()
Getter routine for the logging level of this object.
Level getEffectiveLevel ()
Getter routine for the effective logging level of this object.
void setLevel (Level level, bool force=true)
Setter routine for the logging level of this object.
template<class DerivedLogger >
Logger & createInstance (std::string name)
This routine creates a logger instance for a given name.
Static Public Member Functions
static void initLogging ()
Initialization routine to be called with initialization.
static void registerPython ()
This routine exports the bindings for python.
static Logger & getRoot ()
Get reference to the root logger.
static Logger & getInstance (std::string name)
Get reference to a logger with a given name.
static void push (std::string item)
Add some content for the following log statements.
static void pop ()
Reverse to the last push.
static void configure ()
Configuration of the logging system.
static const char * getLevelString (int level)
Getter routine for the logging level of this object.
template<class DerivedLogger >
static Logger & createInstance (std::string name)
Protected Attributes
std::string name
name of the logger
bool setFlag
This flag indicates that level has been set explicitly.
Level myLevel
Current level of this logger.
class Logger * parent
points back to the parent logger, NULL for root
std::vector< class Logger * > sons
sub loggers of this logger
Static Protected Attributes
static std::vector< std::string > context
stack for different context
Private Member Functions
void setPythonLevel (int pyLevel)
This routine updates the logging level by the given level of the Python logger.
void log (int level, Location &loc, const std::string &msg)
Commonly used routine for logging output that can be used for all levels.
Private Attributes
boost::python::object pyLogger
Pointer to the Python instance of this logger.
Detailed Description
PyLogger is an implementaton of the abstract class Logger that uses corresponding Python Logger objects for the output of the logging statements.
One major efficiency aspect is that an object of this class will not ask for the logging level of its Python equivalent; therefore it has to be ensured that changing the logging level of a Python logger will notity an object of this C++ class.
Definition at line 51 of file PyLogger.hpp.
Member Typedef Documentation
typedef boost::python::object log4espp::PyLogger::object
Definition at line 79 of file PyLogger.hpp.
Member Enumeration Documentation
enum log4espp::Logger::Level inherited
Enumerator
TRACE
even more detailed than DEBUG
DEBUG
designates fine-grained informational events
INFO
informational messages highlighting progress
WARN
for potentially harmful situations
ERROR
for errors that might still allow the application to continue
FATAL
servere errors that will presumably lead to aborts
Definition at line 92 of file Logger.hpp.
Constructor & Destructor Documentation
PyLogger::PyLogger (std::string , class Logger * parent)
Constructor for a Logger that will use a corresponding Python instance for the configuration and for the output of the logging messages.
Definition at line 86 of file PyLogger.cpp.
References log4espp::Logger::getFullName(), pyInit, pyLogger, pyLogging, and setPythonLogger().
Referenced by initLogging().
log4espp::PyLogger::~PyLogger () inline
Definition at line 93 of file PyLogger.hpp.
Member Function Documentation
void Logger::configure () static inherited
Configuration of the logging system.
Definition at line 254 of file GenLogger.cpp.
References log4espp::Logger::getRoot(), LOG4ESPP_INFO, LOG4ESPP_WARN, read_config(), log4espp::Logger::setLevel(), log4espp::GenLogger::traverse(), and log4espp::Logger::WARN.
template<class DerivedLogger > static Logger& log4espp::Logger::createInstance (std::string name) static inherited
template<class DerivedLogger > Logger& log4espp::Logger::createInstance (std::string name) inherited
This routine creates a logger instance for a given name.
The template argument specifies the class of the logger.
Definition at line 323 of file Logger.hpp.
References log4espp::Logger::getRoot(), log4espp::Logger::name, and log4espp::Logger::sons.
void PyLogger::debug (Location loc, const std::string & msg) virtual
Implementation of Logger::debug.
Implements log4espp::Logger.
Definition at line 185 of file PyLogger.cpp.
References log(), and pyDEBUG.
void PyLogger::error (Location loc, const std::string & msg) virtual
Implementation of Logger::error.
Implements log4espp::Logger.
Definition at line 200 of file PyLogger.cpp.
References log(), and pyERROR.
void PyLogger::fatal (Location loc, const std::string & msg) virtual
Implementation of Logger::fatal.
Implements log4espp::Logger.
Definition at line 205 of file PyLogger.cpp.
References log(), and pyFATAL.
Level log4espp::Logger::getEffectiveLevel () inline inherited
Getter routine for the effective logging level of this object.
If level has not been set explicitly it will ask the ancestors for the level
Definition at line 198 of file Logger.hpp.
References log4espp::Logger::getEffectiveLevel(), log4espp::Logger::myLevel, log4espp::Logger::parent, and log4espp::Logger::setFlag.
Referenced by log4espp::Logger::getEffectiveLevel(), and log4espp::GenLogger::traverse().
std::string log4espp::Logger::getFullName () inline inherited
Asks for the full name of the logger, e.g.
"X.Y.Z"
Definition at line 154 of file Logger.hpp.
References log4espp::Logger::getFullName(), log4espp::Logger::name, and log4espp::Logger::parent.
Referenced by log4espp::GenLogger::GenLogger(), log4espp::Logger::getFullName(), PyLogger(), setPythonLevel(), setPythonLogger(), and log4espp::GenLogger::traverse().
Logger & Logger::getInstance (std::string name) static inherited
Get reference to a logger with a given name.
Definition at line 90 of file GenLogger.cpp.
References log4espp::Logger::name.
Referenced by loggerUpdate(), and setLoggerLevel().
Level log4espp::Logger::getLevel () inline inherited
Getter routine for the logging level of this object.
Definition at line 191 of file Logger.hpp.
References log4espp::Logger::myLevel.
Referenced by log4espp::Logger::Logger().
static const char* log4espp::Logger::getLevelString (int level) inline static inherited
Getter routine for the logging level of this object.
Returns
the logging level as a string.
Definition at line 208 of file Logger.hpp.
References log4espp::Logger::DEBUG, log4espp::Logger::ERROR, log4espp::Logger::FATAL, log4espp::Logger::INFO, log4espp::Logger::TRACE, and log4espp::Logger::WARN.
Referenced by log4espp::GenLogger::traverse().
Logger & Logger::getRoot () static inherited
Get reference to the root logger.
Definition at line 72 of file GenLogger.cpp.
References rootLogger.
Referenced by log4espp::Logger::configure(), log4espp::Logger::createInstance(), and setLoggerLevel().
void PyLogger::info (Location loc, const std::string & msg) virtual
Implementation of Logger::info.
Implements log4espp::Logger.
Definition at line 190 of file PyLogger.cpp.
References log(), and pyINFO.
void PyLogger::initLogging () static
Initialization routine to be called with initialization.
Initialization routine called from Python.
Parameters
loggerClass is the name of the class to which all loggers of will belong; this class guarantees that log level changes will be availabe here.
Definition at line 360 of file PyLogger.cpp.
References log4espp::Logger::name, pyInitialize(), PyLogger(), rootLogger, and setPythonLoggers().
Referenced by registerPython().
bool log4espp::Logger::isDebugEnabled () inline inherited
Check if logging statements of level DEBUG are enabled.
Definition at line 171 of file Logger.hpp.
References log4espp::Logger::DEBUG, and log4espp::Logger::myLevel.
bool log4espp::Logger::isErrorEnabled () inline inherited
Check if logging statements of level ERROR are enabled.
Definition at line 183 of file Logger.hpp.
References log4espp::Logger::ERROR, and log4espp::Logger::myLevel.
bool log4espp::Logger::isFatalEnabled () inline inherited
Check if logging statements of level FATAL are enabled.
Definition at line 187 of file Logger.hpp.
References log4espp::Logger::FATAL, and log4espp::Logger::myLevel.
bool log4espp::Logger::isInfoEnabled () inline inherited
Check if logging statements of level INFO are enabled.
Definition at line 175 of file Logger.hpp.
References log4espp::Logger::INFO, and log4espp::Logger::myLevel.
bool log4espp::Logger::isTraceEnabled () inline inherited
Check if logging statements of level TRACE are enabled.
Definition at line 167 of file Logger.hpp.
References log4espp::Logger::myLevel, and log4espp::Logger::TRACE.
bool log4espp::Logger::isWarnEnabled () inline inherited
Check if logging statements of level WARN are enabled.
Definition at line 179 of file Logger.hpp.
References log4espp::Logger::myLevel, and log4espp::Logger::WARN.
void PyLogger::log (int level, Location & loc, const std::string & msg) private
Commonly used routine for logging output that can be used for all levels.
Parameters
level is the string representation of the level
loc is the file location of the logging statement
msg is the message output of the logging statement
The logging output will be printed via the Python Logger object.
Definition at line 137 of file PyLogger.cpp.
References log4espp::Location::filename, log4espp::Location::funcname, log4espp::Location::line, log4espp::Logger::name, pyLogger, and pyNone.
Referenced by debug(), error(), fatal(), info(), trace(), and warn().
static void log4espp::Logger::pop () inline static inherited
Reverse to the last push.
Definition at line 150 of file Logger.hpp.
References log4espp::Logger::context.
static void log4espp::Logger::push (std::string item) inline static inherited
Add some content for the following log statements.
Definition at line 146 of file Logger.hpp.
References log4espp::Logger::context.
void PyLogger::registerPython () static
This routine exports the bindings for python.
Definition at line 387 of file PyLogger.cpp.
References initLogging(), and loggerUpdate().
Referenced by espressopp::registerPython().
void log4espp::Logger::setLevel (Level level, bool force = true) inline inherited
Setter routine for the logging level of this object.
Parameters
level is the new logging level for this object
force true specifies that this is an explicit set
This routine will set implicitly the levels recursively for the descendants whose level has not been set explicitly.
Definition at line 228 of file Logger.hpp.
References log4espp::Logger::myLevel, log4espp::Logger::setFlag, and log4espp::Logger::sons.
Referenced by log4espp::Logger::configure(), setLoggerLevel(), and setPythonLevel().
void PyLogger::setPythonLevel (int pyLevel) private
This routine updates the logging level by the given level of the Python logger.
Parameters
pyLevel is the Python coding of the level
The Python coding of the level will be translated to Logger::Level.
Definition at line 210 of file PyLogger.cpp.
References log4espp::Logger::DEBUG, log4espp::Logger::ERROR, log4espp::Logger::FATAL, log4espp::Logger::getFullName(), log4espp::Logger::INFO, log4espp::Logger::myLevel, pyDEBUG, pyERROR, pyFATAL, pyINFO, pyNOTSET, pyTRACE, pyWARN, log4espp::Logger::setFlag, log4espp::Logger::setLevel(), log4espp::Logger::TRACE, and log4espp::Logger::WARN.
Referenced by setPythonLogger().
void PyLogger::setPythonLogger (boost::python::object pyLogger)
This routine sets the Python instance of the logger and/or updates the logging level of the C++ class.
Parameters
pyLogger is the Python Logger object.
This routine must also be called to update the logging level of this object.
Definition at line 243 of file PyLogger.cpp.
References log4espp::Logger::getFullName(), pyLogger, and setPythonLevel().
Referenced by loggerUpdate(), PyLogger(), and setPythonLoggers().
void PyLogger::setPythonLoggers (std::string & parentName)
This routine sets the Python loggers for this logger and the descendants.
Parameters
ParentName is the name of the parent of this logger.
Definition at line 263 of file PyLogger.cpp.
References log4espp::Logger::name, pyLogger, pyLogging, setPythonLogger(), setPythonLoggers(), and log4espp::Logger::sons.
Referenced by initLogging(), and setPythonLoggers().
void PyLogger::trace (Location loc, const std::string & msg) virtual
Implementation of Logger::trace.
Implements log4espp::Logger.
Definition at line 180 of file PyLogger.cpp.
References log(), and pyTRACE.
void PyLogger::warn (Location loc, const std::string & msg) virtual
Implementation of Logger::warn.
Implements log4espp::Logger.
Definition at line 195 of file PyLogger.cpp.
References log(), and pyWARN.
Member Data Documentation
std::vector<std::string> log4espp::Logger::context static protected inherited
stack for different context
Definition at line 111 of file Logger.hpp.
Referenced by log4espp::Logger::pop(), and log4espp::Logger::push().
Level log4espp::Logger::myLevel protected inherited
Current level of this logger.
Definition at line 105 of file Logger.hpp.
Referenced by log4espp::Logger::getEffectiveLevel(), log4espp::Logger::getLevel(), log4espp::Logger::isDebugEnabled(), log4espp::Logger::isErrorEnabled(), log4espp::Logger::isFatalEnabled(), log4espp::Logger::isInfoEnabled(), log4espp::Logger::isTraceEnabled(), log4espp::Logger::isWarnEnabled(), log4espp::Logger::Logger(), log4espp::Logger::setLevel(), and setPythonLevel().
std::string log4espp::Logger::name protected inherited
name of the logger
Definition at line 102 of file Logger.hpp.
Referenced by log4espp::Logger::createInstance(), log4espp::Logger::getFullName(), log4espp::Logger::getInstance(), initLogging(), log(), log4espp::Logger::Logger(), and setPythonLoggers().
class Logger* log4espp::Logger::parent protected inherited
points back to the parent logger, NULL for root
Definition at line 107 of file Logger.hpp.
Referenced by log4espp::Logger::getEffectiveLevel(), log4espp::Logger::getFullName(), and log4espp::Logger::Logger().
boost::python::object log4espp::PyLogger::pyLogger private
Pointer to the Python instance of this logger.
Definition at line 55 of file PyLogger.hpp.
Referenced by log(), PyLogger(), setPythonLogger(), and setPythonLoggers().
bool log4espp::Logger::setFlag protected inherited
This flag indicates that level has been set explicitly.
Definition at line 103 of file Logger.hpp.
Referenced by log4espp::Logger::getEffectiveLevel(), log4espp::Logger::Logger(), log4espp::Logger::setLevel(), setPythonLevel(), and log4espp::GenLogger::traverse().
std::vector<class Logger*> log4espp::Logger::sons protected inherited
sub loggers of this logger
Definition at line 109 of file Logger.hpp.
Referenced by log4espp::Logger::createInstance(), log4espp::Logger::Logger(), log4espp::Logger::setLevel(), setPythonLoggers(), and log4espp::GenLogger::traverse().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/esutil/PyLogger.hpp
/home/travis/build/espressopp/espressopp/src/esutil/PyLogger.cpp