ESPResSo++: espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential > Class Template Reference
espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential > Class Template Reference
#include <FixedPairDistListInteractionTemplate.hpp>
Public Member Functions
FixedPairDistListInteractionTemplate (shared_ptr< System > system, shared_ptr< FixedPairDistList > _fixedPairDistList, shared_ptr< Potential > _potential)
virtual ~FixedPairDistListInteractionTemplate ()
void setFixedPairList (shared_ptr< FixedPairDistList > _fixedPairDistList)
shared_ptr< FixedPairDistList > getFixedPairList ()
void setPotential (shared_ptr< Potential > _potential)
shared_ptr< Potential > getPotential ()
virtual void addForces ()
virtual real computeEnergy ()
virtual real computeEnergyDeriv ()
virtual real computeEnergyAA ()
virtual real computeEnergyCG ()
virtual real computeEnergyAA (int atomtype)
virtual real computeEnergyCG (int atomtype)
virtual void computeVirialX (std::vector< real > &p_xx_total, int bins)
virtual real computeVirial ()
virtual void computeVirialTensor (Tensor &w)
virtual void computeVirialTensor (Tensor &w, real z)
virtual void computeVirialTensor (Tensor *w, int n)
virtual real getMaxCutoff ()
This method returns the maximal cutoff defined for one type pair.
virtual int bondType ()
Static Public Member Functions
static void registerPython ()
Protected Types
typedef _Potential Potential
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Protected Attributes
int ntypes
shared_ptr< FixedPairDistList > fixedPairDistList
shared_ptr< Potential > potential
Private Member Functions
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Detailed Description
template<typename _Potential>
class espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >
Definition at line 42 of file FixedPairDistListInteractionTemplate.hpp.
Member Typedef Documentation
Potential
template<typename _Potential > typedef _Potential espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::Potential protected
Definition at line 45 of file FixedPairDistListInteractionTemplate.hpp.
Constructor & Destructor Documentation
FixedPairDistListInteractionTemplate()
template<typename _Potential > espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::FixedPairDistListInteractionTemplate (shared_ptr< System > system, shared_ptr< FixedPairDistList > _fixedPairDistList, shared_ptr< Potential > _potential) inline
Definition at line 49 of file FixedPairDistListInteractionTemplate.hpp.
References LOG4ESPP_ERROR, and espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::potential.
~FixedPairDistListInteractionTemplate()
template<typename _Potential > virtual espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::~FixedPairDistListInteractionTemplate () inline virtual
Definition at line 60 of file FixedPairDistListInteractionTemplate.hpp.
Member Function Documentation
addForces()
template<typename _Potential > void espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::addForces () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 109 of file FixedPairDistListInteractionTemplate.hpp.
References espressopp::System::bc, espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::fixedPairDistList, espressopp::Particle::force(), espressopp::Particle::getId(), espressopp::bc::BC::getMinimumImageVectorBox(), espressopp::SystemAccess::getSystemRef(), LOG4ESPP_INFO, espressopp::Particle::position(), and espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::potential.
Referenced by espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::getPotential().
bondType()
template<typename _Potential > virtual int espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::bondType () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 97 of file FixedPairDistListInteractionTemplate.hpp.
References espressopp::interaction::Pair.
computeEnergy()
template<typename _Potential > real espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergy () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 130 of file FixedPairDistListInteractionTemplate.hpp.
References espressopp::System::bc, espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergyDeriv(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::fixedPairDistList, espressopp::Particle::getId(), espressopp::bc::BC::getMinimumImageVectorBox(), espressopp::SystemAccess::getSystemRef(), LOG4ESPP_INFO, mpiWorld, espressopp::Particle::position(), and espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::potential.
Referenced by espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::addForces(), and espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::getPotential().
computeEnergyAA() [1/2]
template<typename _Potential > real espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergyAA () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 160 of file FixedPairDistListInteractionTemplate.hpp.
Referenced by espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergyDeriv(), and espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::getPotential().
computeEnergyAA() [2/2]
template<typename _Potential > real espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergyAA (int atomtype) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 167 of file FixedPairDistListInteractionTemplate.hpp.
References espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergyCG().
computeEnergyCG() [1/2]
template<typename _Potential > real espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergyCG () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 174 of file FixedPairDistListInteractionTemplate.hpp.
Referenced by espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergyAA(), and espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::getPotential().
computeEnergyCG() [2/2]
template<typename _Potential > real espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergyCG (int atomtype) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 181 of file FixedPairDistListInteractionTemplate.hpp.
References espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialX().
computeEnergyDeriv()
template<typename _Potential > real espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergyDeriv () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 153 of file FixedPairDistListInteractionTemplate.hpp.
References espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergyAA().
Referenced by espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergy(), and espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::getPotential().
computeVirial()
template<typename _Potential > real espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirial () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 195 of file FixedPairDistListInteractionTemplate.hpp.
References espressopp::System::bc, espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::fixedPairDistList, espressopp::Particle::getId(), espressopp::bc::BC::getMinimumImageVectorBox(), espressopp::SystemAccess::getSystemRef(), LOG4ESPP_INFO, mpiWorld, espressopp::Particle::position(), and espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::potential.
Referenced by espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialX(), and espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::getPotential().
computeVirialTensor() [1/3]
template<typename _Potential > void espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor (Tensor & w) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 221 of file FixedPairDistListInteractionTemplate.hpp.
References espressopp::System::bc, espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::fixedPairDistList, espressopp::Particle::getId(), espressopp::bc::BC::getMinimumImageVectorBox(), espressopp::SystemAccess::getSystemRef(), LOG4ESPP_INFO, mpiWorld, espressopp::Particle::position(), and espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::potential.
Referenced by espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), and espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::getPotential().
computeVirialTensor() [2/3]
template<typename _Potential > void espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor (Tensor & w, real z) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 248 of file FixedPairDistListInteractionTemplate.hpp.
References espressopp::System::bc, espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::fixedPairDistList, espressopp::Particle::getId(), espressopp::bc::BC::getMinimumImageVectorBox(), espressopp::SystemAccess::getSystemRef(), LOG4ESPP_INFO, mpiWorld, espressopp::Particle::position(), and espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::potential.
computeVirialTensor() [3/3]
template<typename _Potential > void espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor (Tensor * w, int n) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 281 of file FixedPairDistListInteractionTemplate.hpp.
References espressopp::System::bc, espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::fixedPairDistList, espressopp::bc::BC::getBoxL(), espressopp::Particle::getId(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::getMaxCutoff(), espressopp::bc::BC::getMinimumImageVectorBox(), espressopp::SystemAccess::getSystemRef(), LOG4ESPP_INFO, mpiWorld, espressopp::Particle::position(), and espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::potential.
computeVirialX()
template<typename _Potential > void espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialX (std::vector< real > & p_xx_total, int bins) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 189 of file FixedPairDistListInteractionTemplate.hpp.
References espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirial().
Referenced by espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergyCG(), and espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::getPotential().
getFixedPairList()
template<typename _Potential > shared_ptr< FixedPairDistList > espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::getFixedPairList () inline
Definition at line 67 of file FixedPairDistListInteractionTemplate.hpp.
References espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::fixedPairDistList.
getMaxCutoff()
template<typename _Potential > real espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::getMaxCutoff () inline virtual
This method returns the maximal cutoff defined for one type pair.
Implements espressopp::interaction::Interaction.
Definition at line 333 of file FixedPairDistListInteractionTemplate.hpp.
References espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::potential.
Referenced by espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), and espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::getPotential().
getPotential()
template<typename _Potential > shared_ptr< Potential > espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::getPotential () inline
Definition at line 80 of file FixedPairDistListInteractionTemplate.hpp.
References espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergyAA(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergyCG(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergyDeriv(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialX(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::getMaxCutoff(), and espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::potential.
getSystem()
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::LatticeBoltzmann::assignMyLattice(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::PIAdressIntegrator::computeKineticEnergy(), espressopp::integrator::PIAdressIntegrator::computeMomentumDrift(), espressopp::integrator::PIAdressIntegrator::computePositionDrift(), espressopp::integrator::PIAdressIntegrator::computeRingEnergy(), espressopp::integrator::PIAdressIntegrator::computeRingEnergyRaw(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpXTCAdress::dump(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::io::DumpXYZ::DumpXYZ(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::VerletListTriple::registerPython(), espressopp::VerletList::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
getSystem1()
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
getSystem2()
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
getSystemRef()
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::addForces(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::addForces(), espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerletRESPA::calcForces(), espressopp::integrator::VelocityVerlet::calcForces(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::PIAdressIntegrator::calcForcesF(), espressopp::integrator::PIAdressIntegrator::calcForcesM(), espressopp::integrator::PIAdressIntegrator::calcForcesS(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeCOM(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeEnergy(), espressopp::integrator::PIAdressIntegrator::computeKineticEnergy(), espressopp::integrator::PIAdressIntegrator::computeMomentumDrift(), espressopp::integrator::PIAdressIntegrator::computePositionDrift(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::integrator::PIAdressIntegrator::computeRingEnergy(), espressopp::integrator::PIAdressIntegrator::computeRingEnergyRaw(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::PIAdressIntegrator::distributeForces(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::FixedLocalTupleComListInteractionTemplate(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::VelocityVerletRESPA::initForces(), espressopp::integrator::VelocityVerlet::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::PIAdressIntegrator::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::PIAdressIntegrator::initializeSetup(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::VelocityVerletRESPA::integrate1(), espressopp::integrator::VelocityVerlet::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::VelocityVerletRESPA::integrate2(), espressopp::integrator::VelocityVerlet::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::PIAdressIntegrator::integrateModePos(), espressopp::integrator::Adress::integrateSlow(), espressopp::integrator::PIAdressIntegrator::integrateV1(), espressopp::integrator::PIAdressIntegrator::integrateV2(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::PIAdressIntegrator::OUintegrate(), espressopp::integrator::VelocityVerlet::printForces(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerlet::printPositions(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::VelocityVerletRESPA::run(), espressopp::integrator::PIAdressIntegrator::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::MinimizeEnergy::run(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::Rattle::saveOldPos(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::PIAdressIntegrator::setWeights(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostatOnGroup::thermalize(), espressopp::integrator::LangevinThermostatOnRadius::thermalize(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::integrator::PIAdressIntegrator::transForces(), espressopp::integrator::PIAdressIntegrator::transMom1(), espressopp::integrator::PIAdressIntegrator::transMom2(), espressopp::integrator::PIAdressIntegrator::transPos1(), espressopp::integrator::PIAdressIntegrator::transPos2(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::io::DumpH5MD::update(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::VelocityVerletRESPA::updateForces(), espressopp::integrator::VelocityVerlet::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::PIAdressIntegrator::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
getSystemRef1()
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
getSystemRef2()
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Interaction::LOG4ESPP_DECL_LOGGER (theLogger) static protected inherited
Logger.
Referenced by espressopp::interaction::Interaction::~Interaction().
registerPython()
void espressopp::interaction::Interaction::registerPython () static inherited
Definition at line 36 of file Interaction.cpp.
References espressopp::interaction::Interaction::bondType(), espressopp::interaction::Interaction::computeEnergy(), espressopp::interaction::Interaction::computeEnergyAA(), espressopp::interaction::Interaction::computeEnergyCG(), espressopp::interaction::Interaction::computeEnergyDeriv(), and espressopp::interaction::Interaction::computeVirial().
Referenced by espressopp::interaction::registerPython(), and espressopp::interaction::Interaction::~Interaction().
setFixedPairList()
template<typename _Potential > void espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::setFixedPairList (shared_ptr< FixedPairDistList > _fixedPairDistList) inline
Definition at line 63 of file FixedPairDistListInteractionTemplate.hpp.
References espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::fixedPairDistList.
setPotential()
template<typename _Potential > void espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::setPotential (shared_ptr< Potential > _potential) inline
Definition at line 72 of file FixedPairDistListInteractionTemplate.hpp.
References LOG4ESPP_ERROR, and espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::potential.
Member Data Documentation
fixedPairDistList
template<typename _Potential > shared_ptr< FixedPairDistList > espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::fixedPairDistList protected
Definition at line 101 of file FixedPairDistListInteractionTemplate.hpp.
Referenced by espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::getFixedPairList(), and espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::setFixedPairList().
ntypes
template<typename _Potential > int espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::ntypes protected
Definition at line 100 of file FixedPairDistListInteractionTemplate.hpp.
potential
template<typename _Potential > shared_ptr< Potential > espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::potential protected
Definition at line 102 of file FixedPairDistListInteractionTemplate.hpp.
Referenced by espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::FixedPairDistListInteractionTemplate(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::getMaxCutoff(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::getPotential(), and espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::setPotential().
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/interaction/FixedPairDistListInteractionTemplate.hpp