ESPResSo++: espressopp::Quaternion Class Reference
espressopp::Quaternion Class Reference
#include <Quaternion.hpp>
Public Types
typedef real * iterator
Public Member Functions
Quaternion ()
Quaternion (real v)
Quaternion (Real3D v)
Quaternion (real r, Real3D v)
Quaternion (real alpha, real beta, real gamma, real delta)
Quaternion (const Quaternion &v)
Quaternion (const real v[4])
real & operator[] (int i)
const real & operator[] (int i) const
Quaternion & operator= (const Quaternion &v)
Quaternion & operator+= (const Quaternion &v)
Quaternion & operator-= (const Quaternion &v)
Quaternion & operator*= (const real v)
Quaternion & operator/= (const real v)
bool operator== (const Quaternion &v) const
bool operator!= (const Quaternion &v) const
Quaternion operator+ (const Quaternion &v) const
Quaternion operator- (const Quaternion &v) const
Quaternion operator* (real v) const
Quaternion operator/ (real v) const
Quaternion operator* (const Quaternion &v) const
real sqr () const
real abs () const
void normalize ()
void transpose ()
real getReal () const
Real3D getImag () const
real getImagItem (int i) const
real getItem (int i) const
real & at (int i)
const real & at (int i) const
void setReal (real v)
void setImag (Real3D &v)
void setImagItem (int i, real v)
void setItem (int i, real r)
Static Public Member Functions
static void registerPython ()
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
real real_part
Real3D unreal_part
Friends
class boost::serialization::access
Detailed Description
Definition at line 34 of file Quaternion.hpp.
Member Typedef Documentation
iterator
typedef real* espressopp::Quaternion::iterator
Definition at line 48 of file Quaternion.hpp.
Constructor & Destructor Documentation
Quaternion() [1/7]
espressopp::Quaternion::Quaternion () inline
Definition at line 136 of file Quaternion.hpp.
Referenced by operator*(), espressopp::operator*(), operator+(), operator-(), operator/(), and espressopp::transpose().
Quaternion() [2/7]
espressopp::Quaternion::Quaternion (real v) inline
Definition at line 138 of file Quaternion.hpp.
Quaternion() [3/7]
espressopp::Quaternion::Quaternion (Real3D v) inline
Definition at line 141 of file Quaternion.hpp.
Quaternion() [4/7]
espressopp::Quaternion::Quaternion (real r, Real3D v) inline
Definition at line 144 of file Quaternion.hpp.
Quaternion() [5/7]
espressopp::Quaternion::Quaternion (real alpha, real beta, real gamma, real delta) inline
Definition at line 147 of file Quaternion.hpp.
Quaternion() [6/7]
espressopp::Quaternion::Quaternion (const Quaternion & v) inline
Definition at line 151 of file Quaternion.hpp.
Quaternion() [7/7]
espressopp::Quaternion::Quaternion (const real v[4]) inline
Definition at line 154 of file Quaternion.hpp.
Member Function Documentation
abs()
real espressopp::Quaternion::abs () const inline
Definition at line 210 of file Quaternion.hpp.
Referenced by normalize(), and registerPython().
at() [1/2]
real & espressopp::Quaternion::at (int i) inline
Definition at line 235 of file Quaternion.hpp.
References real_part, and unreal_part.
Referenced by getImagItem(), getItem(), and setItem().
at() [2/2]
const real & espressopp::Quaternion::at (int i) const inline
Definition at line 245 of file Quaternion.hpp.
References real_part, and unreal_part.
getImag()
Real3D espressopp::Quaternion::getImag () const inline
Definition at line 104 of file Quaternion.hpp.
References unreal_part.
Referenced by espressopp::quaternion_pickle_suite::getinitargs(), registerPython(), and espressopp::transpose().
getImagItem()
real espressopp::Quaternion::getImagItem (int i) const inline
Definition at line 105 of file Quaternion.hpp.
References at(), espressopp::Real3D::getItem(), and getItem().
Referenced by espressopp::operator<<(), and registerPython().
getItem()
real espressopp::Quaternion::getItem (int i) const inline
Definition at line 266 of file Quaternion.hpp.
References at().
Referenced by getImagItem(), and registerPython().
getReal()
real espressopp::Quaternion::getReal () const inline
Definition at line 103 of file Quaternion.hpp.
References real_part.
Referenced by espressopp::quaternion_pickle_suite::getinitargs(), espressopp::operator<<(), registerPython(), and espressopp::transpose().
normalize()
void espressopp::Quaternion::normalize () inline
Definition at line 91 of file Quaternion.hpp.
References abs().
Referenced by registerPython().
operator!=()
bool espressopp::Quaternion::operator!= (const Quaternion & v) const inline
Definition at line 185 of file Quaternion.hpp.
operator*() [1/2]
Quaternion espressopp::Quaternion::operator* (real v) const inline
Definition at line 196 of file Quaternion.hpp.
References Quaternion(), real_part, and unreal_part.
Referenced by setImagItem().
operator*() [2/2]
Quaternion espressopp::Quaternion::operator* (const Quaternion & v) const inline
Definition at line 203 of file Quaternion.hpp.
References espressopp::Real3D::cross(), Quaternion(), real_part, and unreal_part.
operator*=()
Quaternion & espressopp::Quaternion::operator*= (const real v) inline
Definition at line 171 of file Quaternion.hpp.
References real_part, and unreal_part.
operator+()
Quaternion espressopp::Quaternion::operator+ (const Quaternion & v) const inline
Definition at line 189 of file Quaternion.hpp.
References Quaternion().
operator+=()
Quaternion & espressopp::Quaternion::operator+= (const Quaternion & v) inline
Definition at line 165 of file Quaternion.hpp.
References real_part, and unreal_part.
operator-()
Quaternion espressopp::Quaternion::operator- (const Quaternion & v) const inline
Definition at line 192 of file Quaternion.hpp.
References Quaternion().
operator-=()
Quaternion & espressopp::Quaternion::operator-= (const Quaternion & v) inline
Definition at line 168 of file Quaternion.hpp.
References real_part, and unreal_part.
operator/()
Quaternion espressopp::Quaternion::operator/ (real v) const inline
Definition at line 199 of file Quaternion.hpp.
References Quaternion(), real_part, and unreal_part.
operator/=()
Quaternion & espressopp::Quaternion::operator/= (const real v) inline
Definition at line 174 of file Quaternion.hpp.
References real_part, and unreal_part.
operator=()
Quaternion & espressopp::Quaternion::operator= (const Quaternion & v) inline
Definition at line 157 of file Quaternion.hpp.
References real_part, and unreal_part.
operator==()
bool espressopp::Quaternion::operator== (const Quaternion & v) const inline
Definition at line 179 of file Quaternion.hpp.
References real_part, and unreal_part.
operator[]() [1/2]
real & espressopp::Quaternion::operator[] (int i) inline
Definition at line 215 of file Quaternion.hpp.
References real_part, and unreal_part.
operator[]() [2/2]
const real & espressopp::Quaternion::operator[] (int i) const inline
Definition at line 225 of file Quaternion.hpp.
References real_part, and unreal_part.
registerPython()
void espressopp::Quaternion::registerPython () static
Definition at line 39 of file Quaternion.cpp.
References abs(), getImag(), getImagItem(), getItem(), getReal(), normalize(), setImag(), setImagItem(), setItem(), setReal(), sqr(), and transpose().
Referenced by espressopp::quaternion_pickle_suite::getinitargs(), espressopp::registerPython(), and setImagItem().
serialize()
template<class Archive > void espressopp::Quaternion::serialize (Archive & ar, const unsigned int version) inline private
Definition at line 41 of file Quaternion.hpp.
References real_part.
setImag()
void espressopp::Quaternion::setImag (Real3D & v) inline
Definition at line 115 of file Quaternion.hpp.
Referenced by registerPython().
setImagItem()
void espressopp::Quaternion::setImagItem (int i, real v) inline
Definition at line 116 of file Quaternion.hpp.
References operator*(), espressopp::operator<<(), registerPython(), espressopp::Real3D::setItem(), setItem(), and transpose().
Referenced by registerPython().
setItem()
void espressopp::Quaternion::setItem (int i, real r) inline
Definition at line 255 of file Quaternion.hpp.
References at().
Referenced by registerPython(), and setImagItem().
setReal()
void espressopp::Quaternion::setReal (real v) inline
Definition at line 114 of file Quaternion.hpp.
Referenced by registerPython().
sqr()
real espressopp::Quaternion::sqr () const inline
Definition at line 207 of file Quaternion.hpp.
References real_part, and unreal_part.
Referenced by registerPython().
transpose()
void espressopp::Quaternion::transpose () inline
Definition at line 98 of file Quaternion.hpp.
References unreal_part.
Referenced by registerPython(), and setImagItem().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Definition at line 39 of file Quaternion.hpp.
Member Data Documentation
real_part
real espressopp::Quaternion::real_part private
Definition at line 35 of file Quaternion.hpp.
Referenced by at(), getReal(), operator*(), operator*=(), operator+=(), operator-=(), operator/(), operator/=(), operator=(), operator==(), operator[](), serialize(), and sqr().
unreal_part
Real3D espressopp::Quaternion::unreal_part private
Definition at line 36 of file Quaternion.hpp.
Referenced by at(), getImag(), operator*(), operator*=(), operator+=(), operator-=(), operator/(), operator/=(), operator=(), operator==(), operator[](), sqr(), and transpose().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/Quaternion.hpp
/home/espressopp/espressopp/src/Quaternion.cpp