ESPResSo++: espressopp::interaction::FENE Class Reference
espressopp::interaction::FENE Class Reference
This class provides methods to compute forces and energies of the FENE potential.
#include <FENE.hpp>
Public Member Functions
FENE ()
FENE (real _K, real _r0, real _rMax, real _cutoff, real _shift)
FENE (real _K, real _r0, real _rMax, real _cutoff)
void setK (real _K)
real getK () const
void setR0 (real _r0)
real getR0 () const
void setRMax (real _rMax)
real getRMax () const
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &dist, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
FENE * derived_this ()
const FENE * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
Private Attributes
real K
real r0
real rMax
Detailed Description
This class provides methods to compute forces and energies of the FENE potential.
Definition at line 40 of file FENE.hpp.
Constructor & Destructor Documentation
espressopp::interaction::FENE::FENE () [inline]
Definition at line 48 of file FENE.hpp.
References espressopp::infinity, espressopp::interaction::PotentialTemplate< FENE >::setCutoff(), and espressopp::interaction::PotentialTemplate< FENE >::setShift().
espressopp::interaction::FENE::FENE (real _K, real _r0, real _rMax, real _cutoff, real _shift) [inline]
Definition at line 54 of file FENE.hpp.
References espressopp::interaction::PotentialTemplate< FENE >::setCutoff(), and espressopp::interaction::PotentialTemplate< FENE >::setShift().
espressopp::interaction::FENE::FENE (real _K, real _r0, real _rMax, real _cutoff) [inline]
Definition at line 61 of file FENE.hpp.
References espressopp::interaction::PotentialTemplate< FENE >::autoShift, espressopp::interaction::PotentialTemplate< FENE >::setAutoShift(), and espressopp::interaction::PotentialTemplate< FENE >::setCutoff().
Member Function Documentation
real espressopp::interaction::PotentialTemplate< FENE >::_computeEnergy (const Particle & p1, const Particle & p2) const [inherited]
real espressopp::interaction::PotentialTemplate< FENE >::_computeEnergy (const Real3D & dist) const [inherited]
real espressopp::interaction::PotentialTemplate< FENE >::_computeEnergy (real dist) const [inherited]
real espressopp::interaction::PotentialTemplate< FENE >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const [inherited]
real espressopp::interaction::PotentialTemplate< FENE >::_computeEnergySqr (real distSqr) const [inherited]
real espressopp::interaction::FENE::_computeEnergySqrRaw (real distSqr) const [inline]
Definition at line 88 of file FENE.hpp.
References K, r0, and rMax.
bool espressopp::interaction::PotentialTemplate< FENE >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const [inherited]
bool espressopp::interaction::PotentialTemplate< FENE >::_computeForce (Real3D & force, const Real3D & dist) const [inherited]
bool espressopp::interaction::PotentialTemplate< FENE >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const [inherited]
bool espressopp::interaction::FENE::_computeForceRaw (Real3D & force, const Real3D & dist, real distSqr) const [inline]
Definition at line 94 of file FENE.hpp.
References K, r0, and rMax.
virtual real espressopp::interaction::PotentialTemplate< FENE >::computeEnergy (const Particle & p1, const Particle & p2) const [virtual, inherited]
Implements espressopp::interaction::Potential.
virtual real espressopp::interaction::PotentialTemplate< FENE >::computeEnergy (const Real3D & dist) const [virtual, inherited]
Implements espressopp::interaction::Potential.
virtual real espressopp::interaction::PotentialTemplate< FENE >::computeEnergy (real dist) const [virtual, inherited]
Implements espressopp::interaction::Potential.
virtual real espressopp::interaction::PotentialTemplate< FENE >::computeEnergySqr (real distsqr) const [virtual, inherited]
Implements espressopp::interaction::Potential.
virtual Real3D espressopp::interaction::PotentialTemplate< FENE >::computeForce (const Particle & p1, const Particle & p2) const [virtual, inherited]
Implements espressopp::interaction::Potential.
virtual Real3D espressopp::interaction::PotentialTemplate< FENE >::computeForce (const Real3D & dist) const [virtual, inherited]
Implements espressopp::interaction::Potential.
FENE * espressopp::interaction::PotentialTemplate< FENE >::derived_this () [inline, protected, inherited]
Definition at line 121 of file Potential.hpp.
const FENE * espressopp::interaction::PotentialTemplate< FENE >::derived_this () const [inline, protected, inherited]
Definition at line 125 of file Potential.hpp.
virtual real espressopp::interaction::PotentialTemplate< FENE >::getCutoff () const [virtual, inherited]
Implements espressopp::interaction::Potential.
real espressopp::interaction::FENE::getK () const [inline]
Definition at line 74 of file FENE.hpp.
References K.
Referenced by registerPython().
real espressopp::interaction::FENE::getR0 () const [inline]
Definition at line 80 of file FENE.hpp.
References r0.
Referenced by registerPython().
real espressopp::interaction::FENE::getRMax () const [inline]
Definition at line 86 of file FENE.hpp.
References rMax.
Referenced by registerPython().
virtual real espressopp::interaction::PotentialTemplate< FENE >::getShift () const [virtual, inherited]
Implements espressopp::interaction::Potential.
static espressopp::interaction::FENE::LOG4ESPP_DECL_LOGGER (theLogger) [static]
Reimplemented from espressopp::interaction::Potential.
void espressopp::interaction::FENE::registerPython () [static]
Reimplemented from espressopp::interaction::Potential.
Definition at line 35 of file FENE.cpp.
References getK(), getR0(), getRMax(), setK(), setR0(), and setRMax().
Referenced by espressopp::interaction::registerPython().
virtual real espressopp::interaction::PotentialTemplate< FENE >::setAutoShift () [virtual, inherited]
Implements espressopp::interaction::Potential.
Referenced by FENE().
virtual void espressopp::interaction::PotentialTemplate< FENE >::setCutoff (real _cutoff) [virtual, inherited]
Implements espressopp::interaction::Potential.
Referenced by FENE().
void espressopp::interaction::FENE::setK (real _K) [inline]
Definition at line 70 of file FENE.hpp.
References K, and espressopp::interaction::PotentialTemplate< FENE >::updateAutoShift().
Referenced by registerPython().
void espressopp::interaction::FENE::setR0 (real _r0) [inline]
Definition at line 76 of file FENE.hpp.
References r0, and espressopp::interaction::PotentialTemplate< FENE >::updateAutoShift().
Referenced by registerPython().
void espressopp::interaction::FENE::setRMax (real _rMax) [inline]
Definition at line 82 of file FENE.hpp.
References rMax, and espressopp::interaction::PotentialTemplate< FENE >::updateAutoShift().
Referenced by registerPython().
virtual void espressopp::interaction::PotentialTemplate< FENE >::setShift (real _shift) [virtual, inherited]
Implements espressopp::interaction::Potential.
Referenced by FENE().
void espressopp::interaction::PotentialTemplate< FENE >::updateAutoShift () [inherited]
Referenced by setK(), setR0(), and setRMax().
Member Data Documentation
bool espressopp::interaction::PotentialTemplate< FENE >::autoShift [protected, inherited]
Definition at line 119 of file Potential.hpp.
Referenced by FENE().
real espressopp::interaction::PotentialTemplate< FENE >::cutoff [protected, inherited]
Definition at line 116 of file Potential.hpp.
real espressopp::interaction::PotentialTemplate< FENE >::cutoffSqr [protected, inherited]
Definition at line 117 of file Potential.hpp.
real espressopp::interaction::FENE::K [private]
Definition at line 42 of file FENE.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), getK(), and setK().
real espressopp::interaction::FENE::r0 [private]
Definition at line 43 of file FENE.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), getR0(), and setR0().
real espressopp::interaction::FENE::rMax [private]
Definition at line 44 of file FENE.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), getRMax(), and setRMax().
real espressopp::interaction::PotentialTemplate< FENE >::shift [protected, inherited]
Definition at line 118 of file Potential.hpp.
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/interaction/FENE.hpp
/home/travis/build/espressopp/espressopp/src/interaction/FENE.cpp