ESPResSo++: espressopp::interaction::CoulombTruncated Class Reference
espressopp::interaction::CoulombTruncated Class Reference
#include <CoulombTruncated.hpp>
Public Member Functions
CoulombTruncated ()
CoulombTruncated (real _prefactor, real _cutoff)
void setPrefactor (real _prefactor)
real getPrefactor () const
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Particle &p1, const Particle &p2, Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, Real3D &dist) const
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &dist, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
real _computeEnergyDeriv (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
CoulombTruncated * derived_this ()
const CoulombTruncated * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
Private Attributes
real prefactor
Detailed Description
Definition at line 37 of file CoulombTruncated.hpp.
Constructor & Destructor Documentation
espressopp::interaction::CoulombTruncated::CoulombTruncated () inline
Definition at line 44 of file CoulombTruncated.hpp.
References espressopp::infinity.
espressopp::interaction::CoulombTruncated::CoulombTruncated (real _prefactor, real _cutoff) inline
Definition at line 50 of file CoulombTruncated.hpp.
Member Function Documentation
real espressopp::interaction::CoulombTruncated::_computeEnergy (const Particle & p1, const Particle & p2) const inline
Definition at line 67 of file CoulombTruncated.hpp.
References espressopp::Real3D::abs(), espressopp::Particle::position(), and espressopp::Particle::q().
real espressopp::interaction::CoulombTruncated::_computeEnergy (const Particle & p1, const Particle & p2, Real3D & dist) const inline
Definition at line 73 of file CoulombTruncated.hpp.
References espressopp::Real3D::abs(), and espressopp::Particle::q().
real espressopp::interaction::PotentialTemplate< CoulombTruncated >::_computeEnergy (const Real3D & dist) const inherited
real espressopp::interaction::PotentialTemplate< CoulombTruncated >::_computeEnergy (real dist) const inherited
real espressopp::interaction::PotentialTemplate< CoulombTruncated >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const inherited
real espressopp::interaction::PotentialTemplate< CoulombTruncated >::_computeEnergyDeriv (const Particle & p1, const Particle & p2) const inherited
real espressopp::interaction::PotentialTemplate< CoulombTruncated >::_computeEnergySqr (real distSqr) const inherited
real espressopp::interaction::CoulombTruncated::_computeEnergySqrRaw (real distSqr) const inline
Definition at line 97 of file CoulombTruncated.hpp.
bool espressopp::interaction::CoulombTruncated::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const inline
Definition at line 78 of file CoulombTruncated.hpp.
References espressopp::Real3D::abs(), espressopp::Particle::position(), espressopp::Particle::q(), and espressopp::Real3D::sqr().
bool espressopp::interaction::CoulombTruncated::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, Real3D & dist) const inline
Definition at line 88 of file CoulombTruncated.hpp.
References espressopp::Real3D::abs(), espressopp::Particle::q(), and espressopp::Real3D::sqr().
bool espressopp::interaction::PotentialTemplate< CoulombTruncated >::_computeForce (Real3D & force, const Real3D & dist) const inherited
bool espressopp::interaction::PotentialTemplate< CoulombTruncated >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const inherited
bool espressopp::interaction::CoulombTruncated::_computeForceRaw (Real3D & force, const Real3D & dist, real distSqr) const inline
Definition at line 101 of file CoulombTruncated.hpp.
virtual real espressopp::interaction::PotentialTemplate< CoulombTruncated >::computeEnergy (const Particle & p1, const Particle & p2) const virtual inherited
Implements espressopp::interaction::Potential.
virtual real espressopp::interaction::PotentialTemplate< CoulombTruncated >::computeEnergy (const Real3D & dist) const virtual inherited
Implements espressopp::interaction::Potential.
virtual real espressopp::interaction::PotentialTemplate< CoulombTruncated >::computeEnergy (real dist) const virtual inherited
Implements espressopp::interaction::Potential.
virtual real espressopp::interaction::PotentialTemplate< CoulombTruncated >::computeEnergySqr (real distsqr) const virtual inherited
Implements espressopp::interaction::Potential.
virtual Real3D espressopp::interaction::PotentialTemplate< CoulombTruncated >::computeForce (const Particle & p1, const Particle & p2) const virtual inherited
Implements espressopp::interaction::Potential.
virtual Real3D espressopp::interaction::PotentialTemplate< CoulombTruncated >::computeForce (const Real3D & dist) const virtual inherited
Implements espressopp::interaction::Potential.
CoulombTruncated * espressopp::interaction::PotentialTemplate< CoulombTruncated >::derived_this () inline protected inherited
Definition at line 123 of file Potential.hpp.
const CoulombTruncated * espressopp::interaction::PotentialTemplate< CoulombTruncated >::derived_this () const inline protected inherited
Definition at line 127 of file Potential.hpp.
virtual real espressopp::interaction::PotentialTemplate< CoulombTruncated >::getCutoff () const virtual inherited
Implements espressopp::interaction::Potential.
real espressopp::interaction::CoulombTruncated::getPrefactor () const inline
Definition at line 63 of file CoulombTruncated.hpp.
Referenced by registerPython().
virtual real espressopp::interaction::PotentialTemplate< CoulombTruncated >::getShift () const virtual inherited
Implements espressopp::interaction::Potential.
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
void espressopp::interaction::CoulombTruncated::registerPython () static
Definition at line 43 of file CoulombTruncated.cpp.
References getPrefactor(), and setPrefactor().
Referenced by espressopp::interaction::registerPython().
virtual real espressopp::interaction::PotentialTemplate< CoulombTruncated >::setAutoShift () virtual inherited
Implements espressopp::interaction::Potential.
virtual void espressopp::interaction::PotentialTemplate< CoulombTruncated >::setCutoff (real _cutoff) virtual inherited
Implements espressopp::interaction::Potential.
void espressopp::interaction::CoulombTruncated::setPrefactor (real _prefactor) inline
Definition at line 59 of file CoulombTruncated.hpp.
Referenced by registerPython().
virtual void espressopp::interaction::PotentialTemplate< CoulombTruncated >::setShift (real _shift) virtual inherited
Implements espressopp::interaction::Potential.
void espressopp::interaction::PotentialTemplate< CoulombTruncated >::updateAutoShift () inherited
Member Data Documentation
bool espressopp::interaction::PotentialTemplate< CoulombTruncated >::autoShift protected inherited
Definition at line 121 of file Potential.hpp.
real espressopp::interaction::PotentialTemplate< CoulombTruncated >::cutoff protected inherited
Definition at line 118 of file Potential.hpp.
real espressopp::interaction::PotentialTemplate< CoulombTruncated >::cutoffSqr protected inherited
Definition at line 119 of file Potential.hpp.
real espressopp::interaction::CoulombTruncated::prefactor private
Definition at line 39 of file CoulombTruncated.hpp.
real espressopp::interaction::PotentialTemplate< CoulombTruncated >::shift protected inherited
Definition at line 120 of file Potential.hpp.
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/interaction/CoulombTruncated.hpp
/home/travis/build/espressopp/espressopp/src/interaction/CoulombTruncated.cpp