ESPResSo++: espressopp::interaction::OPLS Class Reference
espressopp::interaction::OPLS Class Reference abstract
This class provides methods to compute forces and energies of the OPLS dihedral potential.
#include <OPLS.hpp>
Public Member Functions
OPLS ()
OPLS (real _K1, real _K2, real _K3, real _K4)
void setK1 (real _K1)
real getK1 () const
void setK2 (real _K2)
real getK2 () const
void setK3 (real _K3)
real getK3 () const
void setK4 (real _K4)
real getK4 () const
void setK (real _K1, real _K2, real _K3, real _K4)
real _computeEnergyRaw (real _phi) const
void _computeForceRaw (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
real _computeForceRaw (real phi) const
virtual real computeEnergy (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
virtual real computeEnergy (real phi) const
virtual void computeForce (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
virtual real computeForce (real phi) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual real getCutoff () const =0
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)
virtual shared_ptr< FixedPairList > getColVarBondList () const
virtual shared_ptr< FixedPairList > getColVarBondList () const =0
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &ftl)
virtual shared_ptr< FixedTripleList > getColVarAngleList () const
virtual shared_ptr< FixedTripleList > getColVarAngleList () const =0
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fql)
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const =0
virtual void setColVar (const RealND &cv)
virtual void setColVar (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43, const bc::BC &bc)
virtual RealND getColVar () const
virtual RealND getColVar () const =0
virtual void computeColVarWeights (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43, const bc::BC &bc)
real _computeEnergy (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
real _computeEnergy (real phi) const
void _computeForce (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
Static Public Member Functions
static void registerPython ()
static real computePhi (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43)
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
OPLS * derived_this ()
const OPLS * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
shared_ptr< FixedPairList > colVarBondList
shared_ptr< FixedTripleList > colVarAngleList
shared_ptr< FixedQuadrupleList > colVarDihedList
RealND colVar
Private Attributes
real K1
real K2
real K3
real K4
Detailed Description
This class provides methods to compute forces and energies of the OPLS dihedral potential.
To create a new dihedral potential one only needs to write the setter/getters and the variable dU_dphi.
Definition at line 36 of file OPLS.hpp.
Constructor & Destructor Documentation
OPLS() [1/2]
espressopp::interaction::OPLS::OPLS () inline
Definition at line 46 of file OPLS.hpp.
OPLS() [2/2]
espressopp::interaction::OPLS::OPLS (real _K1, real _K2, real _K3, real _K4) inline
Definition at line 47 of file OPLS.hpp.
Member Function Documentation
_computeEnergy() [1/2]
real espressopp::interaction::DihedralPotentialTemplate< OPLS >::_computeEnergy (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline inherited
Definition at line 285 of file DihedralPotential.hpp.
_computeEnergy() [2/2]
real espressopp::interaction::DihedralPotentialTemplate< OPLS >::_computeEnergy (real phi) const inline inherited
Definition at line 295 of file DihedralPotential.hpp.
_computeEnergyRaw()
real espressopp::interaction::OPLS::_computeEnergyRaw (real _phi) const inline
Definition at line 68 of file OPLS.hpp.
References K1, K2, K3, and K4.
_computeForce()
void espressopp::interaction::DihedralPotentialTemplate< OPLS >::_computeForce (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline inherited
Definition at line 317 of file DihedralPotential.hpp.
_computeForceRaw() [1/2]
real espressopp::interaction::OPLS::_computeForceRaw (real phi) const inline
Definition at line 370 of file OPLS.hpp.
References K1, K2, K3, and K4.
_computeForceRaw() [2/2]
void espressopp::interaction::OPLS::_computeForceRaw (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline
Definition at line 77 of file OPLS.hpp.
References espressopp::Real3D::cross(), K1, K2, K3, and K4.
computeColVarWeights()
void espressopp::interaction::DihedralPotentialTemplate< OPLS >::computeColVarWeights (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 256 of file DihedralPotential.hpp.
computeEnergy() [1/2]
real espressopp::interaction::DihedralPotentialTemplate< OPLS >::computeEnergy (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 265 of file DihedralPotential.hpp.
computeEnergy() [2/2]
real espressopp::interaction::DihedralPotentialTemplate< OPLS >::computeEnergy (real phi) const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 278 of file DihedralPotential.hpp.
computeForce() [1/2]
real espressopp::interaction::DihedralPotentialTemplate< OPLS >::computeForce (real phi) const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 331 of file DihedralPotential.hpp.
computeForce() [2/2]
void espressopp::interaction::DihedralPotentialTemplate< OPLS >::computeForce (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 303 of file DihedralPotential.hpp.
computePhi()
real espressopp::interaction::DihedralPotential::computePhi (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) static inherited
Definition at line 31 of file DihedralPotential.cpp.
References espressopp::Real3D::abs(), and espressopp::Real3D::cross().
Referenced by espressopp::interaction::DihedralPotential::registerPython(), espressopp::interaction::TabulatedSubEnsDihedral::setColVar(), espressopp::interaction::TabulatedSubEnsAngular::setColVar(), and espressopp::interaction::TabulatedSubEns::setColVar().
derived_this() [1/2]
OPLS * espressopp::interaction::DihedralPotentialTemplate< OPLS >::derived_this inline protected inherited
Definition at line 154 of file DihedralPotential.hpp.
derived_this() [2/2]
const OPLS * espressopp::interaction::DihedralPotentialTemplate< OPLS >::derived_this inline protected inherited
Definition at line 158 of file DihedralPotential.hpp.
getColVar() [1/2]
RealND espressopp::interaction::DihedralPotentialTemplate< OPLS >::getColVar inline virtual inherited
Definition at line 250 of file DihedralPotential.hpp.
getColVar() [2/2]
virtual RealND espressopp::interaction::DihedralPotential::getColVar () const pure virtual inherited
Implemented in espressopp::interaction::DihedralPotentialTemplate< Derived >.
Referenced by espressopp::interaction::DihedralPotential::registerPython().
getColVarAngleList() [1/2]
shared_ptr< FixedTripleList > espressopp::interaction::DihedralPotentialTemplate< OPLS >::getColVarAngleList inline virtual inherited
Definition at line 213 of file DihedralPotential.hpp.
getColVarAngleList() [2/2]
virtual shared_ptr<FixedTripleList> espressopp::interaction::DihedralPotential::getColVarAngleList () const pure virtual inherited
Implemented in espressopp::interaction::DihedralPotentialTemplate< Derived >.
Referenced by espressopp::interaction::DihedralPotential::registerPython().
getColVarBondList() [1/2]
shared_ptr< FixedPairList > espressopp::interaction::DihedralPotentialTemplate< OPLS >::getColVarBondList inline virtual inherited
Definition at line 199 of file DihedralPotential.hpp.
getColVarBondList() [2/2]
virtual shared_ptr<FixedPairList> espressopp::interaction::DihedralPotential::getColVarBondList () const pure virtual inherited
Implemented in espressopp::interaction::DihedralPotentialTemplate< Derived >.
Referenced by espressopp::interaction::DihedralPotential::registerPython().
getColVarDihedList() [1/2]
shared_ptr< FixedQuadrupleList > espressopp::interaction::DihedralPotentialTemplate< OPLS >::getColVarDihedList inline virtual inherited
Definition at line 227 of file DihedralPotential.hpp.
getColVarDihedList() [2/2]
virtual shared_ptr<FixedQuadrupleList> espressopp::interaction::DihedralPotential::getColVarDihedList () const pure virtual inherited
Implemented in espressopp::interaction::DihedralPotentialTemplate< Derived >.
getCutoff() [1/2]
real espressopp::interaction::DihedralPotentialTemplate< OPLS >::getCutoff inline virtual inherited
Definition at line 185 of file DihedralPotential.hpp.
getCutoff() [2/2]
virtual real espressopp::interaction::DihedralPotential::getCutoff () const pure virtual inherited
Implemented in espressopp::interaction::DihedralPotentialTemplate< Derived >.
Referenced by espressopp::interaction::DihedralPotential::registerPython().
getK1()
real espressopp::interaction::OPLS::getK1 () const inline
Definition at line 50 of file OPLS.hpp.
References K1.
Referenced by registerPython().
getK2()
real espressopp::interaction::OPLS::getK2 () const inline
Definition at line 53 of file OPLS.hpp.
References K2.
Referenced by registerPython().
getK3()
real espressopp::interaction::OPLS::getK3 () const inline
Definition at line 56 of file OPLS.hpp.
References K3.
Referenced by registerPython().
getK4()
real espressopp::interaction::OPLS::getK4 () const inline
Definition at line 59 of file OPLS.hpp.
References K4.
Referenced by registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::DihedralPotential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
registerPython()
void espressopp::interaction::OPLS::registerPython () static
Definition at line 34 of file OPLS.cpp.
References getK1(), getK2(), getK3(), getK4(), setK1(), setK2(), setK3(), and setK4().
Referenced by espressopp::interaction::registerPython().
setColVar() [1/2]
void espressopp::interaction::DihedralPotentialTemplate< OPLS >::setColVar (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 241 of file DihedralPotential.hpp.
setColVar() [2/2]
void espressopp::interaction::DihedralPotentialTemplate< OPLS >::setColVar (const RealND & cv) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 234 of file DihedralPotential.hpp.
setColVarAngleList()
void espressopp::interaction::DihedralPotentialTemplate< OPLS >::setColVarAngleList (const shared_ptr< FixedTripleList > & ftl) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 206 of file DihedralPotential.hpp.
setColVarBondList()
void espressopp::interaction::DihedralPotentialTemplate< OPLS >::setColVarBondList (const shared_ptr< FixedPairList > & fpl) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 192 of file DihedralPotential.hpp.
setColVarDihedList()
void espressopp::interaction::DihedralPotentialTemplate< OPLS >::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fql) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 220 of file DihedralPotential.hpp.
setCutoff()
void espressopp::interaction::DihedralPotentialTemplate< OPLS >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 177 of file DihedralPotential.hpp.
setK()
void espressopp::interaction::OPLS::setK (real _K1, real _K2, real _K3, real _K4) inline
Definition at line 61 of file OPLS.hpp.
References K1, K2, K3, and K4.
setK1()
void espressopp::interaction::OPLS::setK1 (real _K1) inline
Definition at line 49 of file OPLS.hpp.
References K1.
Referenced by registerPython().
setK2()
void espressopp::interaction::OPLS::setK2 (real _K2) inline
Definition at line 52 of file OPLS.hpp.
References K2.
Referenced by registerPython().
setK3()
void espressopp::interaction::OPLS::setK3 (real _K3) inline
Definition at line 55 of file OPLS.hpp.
References K3.
Referenced by registerPython().
setK4()
void espressopp::interaction::OPLS::setK4 (real _K4) inline
Definition at line 58 of file OPLS.hpp.
References K4.
Referenced by registerPython().
Member Data Documentation
colVar
RealND espressopp::interaction::DihedralPotentialTemplate< OPLS >::colVar protected inherited
Definition at line 152 of file DihedralPotential.hpp.
colVarAngleList
shared_ptr<FixedTripleList> espressopp::interaction::DihedralPotentialTemplate< OPLS >::colVarAngleList protected inherited
Definition at line 148 of file DihedralPotential.hpp.
colVarBondList
shared_ptr<FixedPairList> espressopp::interaction::DihedralPotentialTemplate< OPLS >::colVarBondList protected inherited
Definition at line 146 of file DihedralPotential.hpp.
colVarDihedList
shared_ptr<FixedQuadrupleList> espressopp::interaction::DihedralPotentialTemplate< OPLS >::colVarDihedList protected inherited
Definition at line 150 of file DihedralPotential.hpp.
cutoff
real espressopp::interaction::DihedralPotentialTemplate< OPLS >::cutoff protected inherited
Definition at line 143 of file DihedralPotential.hpp.
cutoffSqr
real espressopp::interaction::DihedralPotentialTemplate< OPLS >::cutoffSqr protected inherited
Definition at line 144 of file DihedralPotential.hpp.
K1
real espressopp::interaction::OPLS::K1 private
Definition at line 38 of file OPLS.hpp.
Referenced by _computeEnergyRaw(), _computeForceRaw(), getK1(), setK(), and setK1().
K2
real espressopp::interaction::OPLS::K2 private
Definition at line 39 of file OPLS.hpp.
Referenced by _computeEnergyRaw(), _computeForceRaw(), getK2(), setK(), and setK2().
K3
real espressopp::interaction::OPLS::K3 private
Definition at line 40 of file OPLS.hpp.
Referenced by _computeEnergyRaw(), _computeForceRaw(), getK3(), setK(), and setK3().
K4
real espressopp::interaction::OPLS::K4 private
Definition at line 41 of file OPLS.hpp.
Referenced by _computeEnergyRaw(), _computeForceRaw(), getK4(), setK(), and setK4().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/OPLS.hpp
/home/espressopp/espressopp/src/interaction/OPLS.cpp