ESPResSo++: espressopp::analysis::PotentialEnergy Class Reference
espressopp::analysis::PotentialEnergy Class Reference
#include <PotentialEnergy.hpp>
Public Types
enum result_types {
old_format = -1, none = 0, real_scalar = 1, int_scalar = 2,
real_vector = 3, int_vector = 4
}
Observable can be int, real, scalar or vector.
Public Member Functions
PotentialEnergy (shared_ptr< System > system, shared_ptr< interaction::Interaction > interaction, bool compute_at)
PotentialEnergy (shared_ptr< System > system, shared_ptr< interaction::Interaction > interaction)
~PotentialEnergy ()
real compute_real () const
returns observable of type real, used for Python and on C++ level
virtual real compute () const
for compatibilty with old compute function only, will be deleted soon
virtual int compute_int () const
returns observable of type int, used for Python and on C++ level
virtual void compute_real_vector ()
computes vector of real values (e.g.
virtual void compute_int_vector ()
computes vector of integer values, used on C++ level only
virtual python::list compute_real_vector_python ()
returns python list of real values (e.g.
virtual python::list compute_int_vector_python ()
returns python list of integer values, used on Python level
int getResultType ()
returns the result type of the observable
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (logger)
Protected Attributes
result_types result_type
std::vector< real > result_real_vector
std::vector< int > result_int_vector
Private Attributes
shared_ptr
< interaction::Interaction > interaction_
bool compute_at_
bool compute_global_
Detailed Description
Definition at line 32 of file PotentialEnergy.hpp.
Member Enumeration Documentation
enum espressopp::analysis::Observable::result_types [inherited]
Observable can be int, real, scalar or vector.
Enumerator:
old_format
none
real_scalar
int_scalar
real_vector
int_vector
Definition at line 37 of file Observable.hpp.
Constructor & Destructor Documentation
espressopp::analysis::PotentialEnergy::PotentialEnergy (shared_ptr< System > system, shared_ptr< interaction::Interaction > interaction, bool compute_at) [inline]
Definition at line 34 of file PotentialEnergy.hpp.
References compute_global_, espressopp::analysis::Observable::real_scalar, and espressopp::analysis::Observable::result_type.
espressopp::analysis::PotentialEnergy::PotentialEnergy (shared_ptr< System > system, shared_ptr< interaction::Interaction > interaction) [inline]
Definition at line 40 of file PotentialEnergy.hpp.
References compute_global_, espressopp::analysis::Observable::real_scalar, and espressopp::analysis::Observable::result_type.
espressopp::analysis::PotentialEnergy::~PotentialEnergy () [inline]
Definition at line 45 of file PotentialEnergy.hpp.
Member Function Documentation
virtual real espressopp::analysis::Observable::compute () const [inline, virtual, inherited]
for compatibilty with old compute function only, will be deleted soon
Reimplemented in espressopp::analysis::NeighborFluctuation, espressopp::analysis::StaticStructF, espressopp::analysis::RadialDistrF, espressopp::analysis::RDFatomistic, espressopp::analysis::XDensity, espressopp::analysis::XPressure, espressopp::analysis::XTemperature, espressopp::analysis::CenterOfMass, espressopp::analysis::MaxPID, and espressopp::analysis::Pressure.
Definition at line 43 of file Observable.hpp.
Referenced by espressopp::analysis::Observable::registerPython().
virtual int espressopp::analysis::Observable::compute_int () const [inline, virtual, inherited]
returns observable of type int, used for Python and on C++ level
Definition at line 47 of file Observable.hpp.
Referenced by espressopp::analysis::Observable::registerPython().
virtual void espressopp::analysis::Observable::compute_int_vector () [inline, virtual, inherited]
computes vector of integer values, used on C++ level only
Definition at line 51 of file Observable.hpp.
Referenced by espressopp::analysis::Observable::compute_int_vector_python().
python::list espressopp::analysis::Observable::compute_int_vector_python () [virtual, inherited]
returns python list of integer values, used on Python level
Definition at line 39 of file Observable.cpp.
References espressopp::analysis::Observable::compute_int_vector(), and espressopp::analysis::Observable::result_int_vector.
Referenced by espressopp::analysis::Observable::registerPython().
real espressopp::analysis::PotentialEnergy::compute_real () const [virtual]
returns observable of type real, used for Python and on C++ level
Reimplemented from espressopp::analysis::Observable.
Definition at line 30 of file PotentialEnergy.cpp.
Referenced by registerPython().
virtual void espressopp::analysis::Observable::compute_real_vector () [inline, virtual, inherited]
computes vector of real values (e.g.
pressure tensor, ...), used on C++ level only
Definition at line 49 of file Observable.hpp.
Referenced by espressopp::analysis::Observable::compute_real_vector_python().
python::list espressopp::analysis::Observable::compute_real_vector_python () [virtual, inherited]
returns python list of real values (e.g.
pressure tensor, ...), used on Python level
Definition at line 32 of file Observable.cpp.
References espressopp::analysis::Observable::compute_real_vector(), and espressopp::analysis::Observable::result_real_vector.
Referenced by espressopp::analysis::Observable::registerPython().
int espressopp::analysis::Observable::getResultType () [inline, inherited]
returns the result type of the observable
Definition at line 62 of file Observable.hpp.
References espressopp::analysis::Observable::result_type.
Referenced by espressopp::analysis::Observable::registerPython().
shared_ptr< System > espressopp::SystemAccess::getSystem () const [inline, inherited]
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::LatticeBoltzmann::initGammas(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readCouplForces(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::VerletListTriple::registerPython(), espressopp::VerletList::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveCouplForces(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::analysis::LBOutputScreen::writeOutput(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const [inline, inherited]
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const [inline, inherited]
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
System& espressopp::SystemAccess::getSystemRef () const [inline, inherited]
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readCouplForces(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::LatticeBoltzmann::restoreLBForces(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::LatticeBoltzmann::saveCouplForces(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
System& espressopp::SystemAccess::getSystemRef1 () const [inline, inherited]
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
System& espressopp::SystemAccess::getSystemRef2 () const [inline, inherited]
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
static espressopp::analysis::Observable::LOG4ESPP_DECL_LOGGER (logger) [static, protected, inherited]
void espressopp::analysis::PotentialEnergy::registerPython () [static]
Reimplemented from espressopp::analysis::Observable.
Definition at line 40 of file PotentialEnergy.cpp.
References compute_real().
Referenced by espressopp::analysis::registerPython().
Member Data Documentation
bool espressopp::analysis::PotentialEnergy::compute_at_ [private]
Definition at line 51 of file PotentialEnergy.hpp.
bool espressopp::analysis::PotentialEnergy::compute_global_ [private]
Definition at line 52 of file PotentialEnergy.hpp.
Referenced by PotentialEnergy().
shared_ptr<interaction::Interaction> espressopp::analysis::PotentialEnergy::interaction_ [private]
Definition at line 50 of file PotentialEnergy.hpp.
std::vector< int > espressopp::analysis::Observable::result_int_vector [protected, inherited]
Definition at line 69 of file Observable.hpp.
Referenced by espressopp::analysis::Observable::compute_int_vector_python().
std::vector< real > espressopp::analysis::Observable::result_real_vector [protected, inherited]
Definition at line 68 of file Observable.hpp.
Referenced by espressopp::analysis::Observable::compute_real_vector_python().
result_types espressopp::analysis::Observable::result_type [protected, inherited]
Definition at line 67 of file Observable.hpp.
Referenced by espressopp::analysis::Observable::getResultType(), espressopp::analysis::NPart::NPart(), espressopp::analysis::Observable::Observable(), and PotentialEnergy().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/analysis/PotentialEnergy.hpp
/home/travis/build/espressopp/espressopp/src/analysis/PotentialEnergy.cpp