ESPResSo++: espressopp::CellGrid Class Reference
espressopp::CellGrid Class Reference
Grid with a ghost frame.
#include <CellGrid.hpp>
Public Member Functions
CellGrid ()
CellGrid (const Int3D &grid, const real _myLeft[3], const real _myRight[3], int frame)
int getFrameWidth () const
longint mapPositionToCell (const Real3D &pos) const
map coordinate to cell (ghost or non-ghost). This is used for AdResS
longint mapPositionToCellClipped (const Real3D &pos) const
map coordinate to a non-ghost cell. Positions outside the inner grid are clipped back
longint mapPositionToCellChecked (const Real3D &pos) const
map coordinate to a non-ghost cell. Returns noCell if the position is outside the inner grid
bool mapPositionToCellCheckedAndClipped (longint &, const Real3D &pos) const
map coordinate to a non-ghost cell.
bool isInnerPosition (real pos[3])
check wether a position is in the inner domain
bool isInnerCell (int m, int n, int o) const
check whether a cell is in the inner grid
longint getInnerCellsBegin (int i) const
get start of inner grid
longint getInnerCellsEnd (int i) const
get first element after inner elements
int getGridSize (int i) const
inner size without the ghost frame
int getFrameGridSize (int i) const
full size including the ghost frame
real getMyLeft (int i) const
start coordinates of the domain
const real * getMyLeft () const
start coordinates of the domain
real getMyRight (int i) const
end coordinates of the domain
const real * getMyRight () const
end coordinates of the domain
real getCellSize (int i) const
size of a cell
const real * getCellSize () const
size of a cell
real getInverseCellSize (int i) const
inverse of the size of a cell
const real * getInverseCellSize () const
inverse of the size of a cell
longint getNumberOfInnerCells () const
real getSmallestCellDiameter () const
void scaleVolume (real s)
void scaleVolume (Real3D s)
const Int3D & getGridSize () const
longint getNumberOfCells () const
longint mapPositionToIndex (int p1, int p2, int p3) const
convert a grid position to a unique sequence index
longint mapPositionToIndex (const Int3D &pos) const
void mapIndexToPosition (int &p1, int &p2, int &p3, longint index) const
convert a sequence index back to a grid position
void mapIndexToPosition (Int3D &pos, longint index) const
Static Public Member Functions
static void registerPython ()
Static Public Attributes
static const longint noCell = static_cast<longint>(-1)
Static Private Member Functions
static LOG4ESPP_DECL_LOGGER (logger)
Private Attributes
int frame
size of frame around
int extraSize
twice the size of frame around
real myLeft [3]
Left (bottom, front) corner of the inner domain.
real myRight [3]
Right (top, back) corner of the inner domain.
real cellSize [3]
cell size
real invCellSize [3]
inverse cell size
real smallestCellDiameter
smallest diameter of the cell
Detailed Description
Grid with a ghost frame.
This represents the cell grid of the domain decomposition.
Definition at line 45 of file CellGrid.hpp.
Constructor & Destructor Documentation
espressopp::CellGrid::CellGrid () [inline]
Definition at line 48 of file CellGrid.hpp.
CellGrid::CellGrid (const Int3D & grid, const real _myLeft[3], const real _myRight[3], int frame)
Definition at line 39 of file CellGrid.cpp.
References cellSize, invCellSize, myLeft, myRight, and smallestCellDiameter.
Member Function Documentation
real espressopp::CellGrid::getCellSize (int i) const [inline]
size of a cell
Definition at line 100 of file CellGrid.hpp.
References cellSize.
const real* espressopp::CellGrid::getCellSize () const [inline]
size of a cell
Definition at line 102 of file CellGrid.hpp.
References cellSize.
int espressopp::CellGrid::getFrameGridSize (int i) const [inline]
full size including the ghost frame
Definition at line 88 of file CellGrid.hpp.
References espressopp::esutil::Grid::getGridSize().
Referenced by espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecomposition::fillCells(), espressopp::storage::DomainDecompositionAdress::fillCells(), mapPositionToCellChecked(), mapPositionToCellCheckedAndClipped(), mapPositionToCellClipped(), espressopp::storage::DomainDecomposition::markCells(), espressopp::storage::DomainDecompositionAdress::markCells(), espressopp::storage::DomainDecomposition::prepareGhostCommunication(), and espressopp::storage::DomainDecompositionAdress::prepareGhostCommunication().
int espressopp::CellGrid::getFrameWidth () const [inline]
Definition at line 55 of file CellGrid.hpp.
References frame.
Referenced by espressopp::storage::DomainDecomposition::prepareGhostCommunication(), and espressopp::storage::DomainDecompositionAdress::prepareGhostCommunication().
const Int3D& espressopp::esutil::Grid::getGridSize () const [inline, inherited]
Definition at line 50 of file Grid.hpp.
References espressopp::esutil::Grid::size.
Referenced by espressopp::storage::NodeGrid::calcNodeNeighbors(), getFrameGridSize(), getGridSize(), getInnerCellsEnd(), getNumberOfInnerCells(), espressopp::storage::NodeGrid::mapPositionToNodeClipped(), and espressopp::storage::NodeGrid::NodeGrid().
int espressopp::CellGrid::getGridSize (int i) const [inline]
inner size without the ghost frame
Reimplemented from espressopp::esutil::Grid.
Definition at line 86 of file CellGrid.hpp.
References extraSize, and espressopp::esutil::Grid::getGridSize().
Referenced by espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionAdress::getInt3DCellGrid(), and espressopp::storage::DomainDecomposition::getInt3DCellGrid().
longint espressopp::CellGrid::getInnerCellsBegin (int i) const [inline]
get start of inner grid
Definition at line 81 of file CellGrid.hpp.
References frame.
Referenced by espressopp::storage::DomainDecomposition::initCellInteractions(), espressopp::storage::DomainDecompositionAdress::initCellInteractions(), isInnerCell(), espressopp::storage::DomainDecomposition::prepareGhostCommunication(), and espressopp::storage::DomainDecompositionAdress::prepareGhostCommunication().
longint espressopp::CellGrid::getInnerCellsEnd (int i) const [inline]
get first element after inner elements
Definition at line 83 of file CellGrid.hpp.
References frame, and espressopp::esutil::Grid::getGridSize().
Referenced by espressopp::storage::DomainDecomposition::initCellInteractions(), espressopp::storage::DomainDecompositionAdress::initCellInteractions(), isInnerCell(), espressopp::storage::DomainDecomposition::prepareGhostCommunication(), and espressopp::storage::DomainDecompositionAdress::prepareGhostCommunication().
real espressopp::CellGrid::getInverseCellSize (int i) const [inline]
inverse of the size of a cell
Definition at line 105 of file CellGrid.hpp.
References invCellSize.
const real* espressopp::CellGrid::getInverseCellSize () const [inline]
inverse of the size of a cell
Definition at line 107 of file CellGrid.hpp.
References invCellSize.
real espressopp::CellGrid::getMyLeft (int i) const [inline]
start coordinates of the domain
Definition at line 91 of file CellGrid.hpp.
References myLeft.
Referenced by espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), and espressopp::storage::DomainDecompositionAdress::decomposeRealParticles().
const real* espressopp::CellGrid::getMyLeft () const [inline]
start coordinates of the domain
Definition at line 93 of file CellGrid.hpp.
References myLeft.
Referenced by isInnerPosition().
real espressopp::CellGrid::getMyRight (int i) const [inline]
end coordinates of the domain
Definition at line 95 of file CellGrid.hpp.
References myRight.
Referenced by espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), and espressopp::storage::DomainDecompositionAdress::decomposeRealParticles().
const real* espressopp::CellGrid::getMyRight () const [inline]
end coordinates of the domain
Definition at line 97 of file CellGrid.hpp.
References myRight.
Referenced by isInnerPosition().
longint espressopp::esutil::Grid::getNumberOfCells () const [inline, inherited]
Definition at line 52 of file Grid.hpp.
References espressopp::esutil::Grid::size.
Referenced by espressopp::storage::DomainDecomposition::createCellGrid(), and espressopp::storage::DomainDecompositionAdress::createCellGrid().
longint CellGrid::getNumberOfInnerCells () const
Definition at line 58 of file CellGrid.cpp.
References espressopp::esutil::Grid::getGridSize().
real espressopp::CellGrid::getSmallestCellDiameter () const [inline]
Definition at line 111 of file CellGrid.hpp.
References smallestCellDiameter.
Referenced by espressopp::storage::DomainDecomposition::scaleVolume().
bool espressopp::CellGrid::isInnerCell (int m, int n, int o) const [inline]
check whether a cell is in the inner grid
Definition at line 74 of file CellGrid.hpp.
References getInnerCellsBegin(), and getInnerCellsEnd().
Referenced by espressopp::storage::DomainDecomposition::markCells(), and espressopp::storage::DomainDecompositionAdress::markCells().
bool espressopp::CellGrid::isInnerPosition (real pos[3]) [inline]
check wether a position is in the inner domain
Definition at line 68 of file CellGrid.hpp.
References getMyLeft(), and getMyRight().
static espressopp::CellGrid::LOG4ESPP_DECL_LOGGER (logger) [static, private]
void espressopp::esutil::Grid::mapIndexToPosition (int & p1, int & p2, int & p3, longint index) const [inline, inherited]
convert a sequence index back to a grid position
Definition at line 67 of file Grid.hpp.
References espressopp::esutil::Grid::size.
Referenced by espressopp::storage::NodeGrid::calcNodeNeighbors(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), and espressopp::esutil::Grid::mapIndexToPosition().
void espressopp::esutil::Grid::mapIndexToPosition (Int3D & pos, longint index) const [inline, inherited]
Definition at line 75 of file Grid.hpp.
References espressopp::esutil::Grid::mapIndexToPosition().
longint CellGrid::mapPositionToCell (const Real3D & pos) const
map coordinate to cell (ghost or non-ghost). This is used for AdResS
Definition at line 68 of file CellGrid.cpp.
References frame, invCellSize, espressopp::esutil::Grid::mapPositionToIndex(), and myLeft.
Referenced by espressopp::storage::DomainDecompositionAdress::mapPositionToCell(), and espressopp::storage::DomainDecomposition::mapPositionToCell().
longint CellGrid::mapPositionToCellChecked (const Real3D & pos) const
map coordinate to a non-ghost cell. Returns noCell if the position is outside the inner grid
Definition at line 99 of file CellGrid.cpp.
References frame, getFrameGridSize(), invCellSize, espressopp::esutil::Grid::mapPositionToIndex(), myLeft, myRight, noCell, and espressopp::ROUND_ERROR_PREC.
Referenced by espressopp::storage::DomainDecompositionAdress::mapPositionToCellChecked(), and espressopp::storage::DomainDecomposition::mapPositionToCellChecked().
bool CellGrid::mapPositionToCellCheckedAndClipped (longint & cell, const Real3D & pos) const
map coordinate to a non-ghost cell.
Returns true if the returned cell is clipped, i.e. the position is outside the inner grid
Definition at line 130 of file CellGrid.cpp.
References frame, getFrameGridSize(), invCellSize, LOG4ESPP_TRACE, espressopp::esutil::Grid::mapPositionToIndex(), myLeft, myRight, and espressopp::ROUND_ERROR_PREC.
Referenced by espressopp::storage::DomainDecomposition::appendParticles(), and espressopp::storage::DomainDecompositionAdress::appendParticles().
longint CellGrid::mapPositionToCellClipped (const Real3D & pos) const
map coordinate to a non-ghost cell. Positions outside the inner grid are clipped back
Definition at line 80 of file CellGrid.cpp.
References frame, getFrameGridSize(), invCellSize, espressopp::esutil::Grid::mapPositionToIndex(), and myLeft.
Referenced by espressopp::storage::DomainDecompositionAdress::mapPositionToCellClipped(), and espressopp::storage::DomainDecomposition::mapPositionToCellClipped().
longint espressopp::esutil::Grid::mapPositionToIndex (int p1, int p2, int p3) const [inline, inherited]
convert a grid position to a unique sequence index
Definition at line 61 of file Grid.hpp.
References espressopp::esutil::Grid::size.
Referenced by espressopp::storage::NodeGrid::calcNodeNeighbors(), espressopp::storage::DomainDecomposition::fillCells(), espressopp::storage::DomainDecompositionAdress::fillCells(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::storage::DomainDecomposition::initCellInteractions(), espressopp::storage::DomainDecompositionAdress::initCellInteractions(), mapPositionToCell(), mapPositionToCellChecked(), mapPositionToCellCheckedAndClipped(), mapPositionToCellClipped(), espressopp::storage::NodeGrid::mapPositionToNodeClipped(), espressopp::storage::DomainDecomposition::markCells(), and espressopp::storage::DomainDecompositionAdress::markCells().
longint espressopp::esutil::Grid::mapPositionToIndex (const Int3D & pos) const [inline, inherited]
Definition at line 63 of file Grid.hpp.
References espressopp::esutil::Grid::mapPositionToIndex().
Referenced by espressopp::esutil::Grid::mapPositionToIndex().
void espressopp::esutil::Grid::registerPython () [static, inherited]
Definition at line 38 of file Grid.cpp.
References espressopp::esutil::mapIndexToPositionInt3D.
Referenced by espressopp::esutil::registerPython().
void espressopp::CellGrid::scaleVolume (real s) [inline]
Definition at line 115 of file CellGrid.hpp.
References cellSize, invCellSize, myLeft, myRight, and smallestCellDiameter.
Referenced by espressopp::storage::DomainDecomposition::scaleVolume().
void espressopp::CellGrid::scaleVolume (Real3D s) [inline]
Definition at line 130 of file CellGrid.hpp.
References cellSize, invCellSize, myLeft, myRight, and smallestCellDiameter.
Member Data Documentation
real espressopp::CellGrid::cellSize[3] [private]
cell size
Definition at line 159 of file CellGrid.hpp.
Referenced by CellGrid(), getCellSize(), and scaleVolume().
int espressopp::CellGrid::extraSize [private]
twice the size of frame around
Definition at line 151 of file CellGrid.hpp.
Referenced by getGridSize().
int espressopp::CellGrid::frame [private]
size of frame around
Definition at line 149 of file CellGrid.hpp.
Referenced by getFrameWidth(), getInnerCellsBegin(), getInnerCellsEnd(), mapPositionToCell(), mapPositionToCellChecked(), mapPositionToCellCheckedAndClipped(), and mapPositionToCellClipped().
real espressopp::CellGrid::invCellSize[3] [private]
inverse cell size
Definition at line 161 of file CellGrid.hpp.
Referenced by CellGrid(), getInverseCellSize(), mapPositionToCell(), mapPositionToCellChecked(), mapPositionToCellCheckedAndClipped(), mapPositionToCellClipped(), and scaleVolume().
real espressopp::CellGrid::myLeft[3] [private]
Left (bottom, front) corner of the inner domain.
Definition at line 154 of file CellGrid.hpp.
Referenced by CellGrid(), getMyLeft(), mapPositionToCell(), mapPositionToCellChecked(), mapPositionToCellCheckedAndClipped(), mapPositionToCellClipped(), and scaleVolume().
real espressopp::CellGrid::myRight[3] [private]
Right (top, back) corner of the inner domain.
Definition at line 156 of file CellGrid.hpp.
Referenced by CellGrid(), getMyRight(), mapPositionToCellChecked(), mapPositionToCellCheckedAndClipped(), and scaleVolume().
const longint espressopp::CellGrid::noCell = static_cast<longint>(-1) [static]
Definition at line 113 of file CellGrid.hpp.
Referenced by espressopp::storage::DomainDecompositionAdress::mapPositionToCellChecked(), mapPositionToCellChecked(), and espressopp::storage::DomainDecomposition::mapPositionToCellChecked().
real espressopp::CellGrid::smallestCellDiameter [private]
smallest diameter of the cell
Definition at line 164 of file CellGrid.hpp.
Referenced by CellGrid(), getSmallestCellDiameter(), and scaleVolume().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/storage/CellGrid.hpp
/home/travis/build/espressopp/espressopp/src/storage/CellGrid.cpp