ESPResSo++: espressopp::OutBuffer Class Reference
espressopp::OutBuffer Class Reference
#include <BufferArchive.hpp>
Public Types
enum ExtraDataElements {
DATA_PROPERTIES = 1, DATA_MOMENTUM = 2, DATA_LOCAL = 4, DATA_PROPERTIES = 1,
DATA_MOMENTUM = 2, DATA_LOCAL = 4, DATA_PROPERTIES = 1, DATA_MOMENTUM = 2,
DATA_LOCAL = 4
}
bitmask: which extra data elements to in- or exclude from ghost sending
enum ExtraDataElements {
DATA_PROPERTIES = 1, DATA_MOMENTUM = 2, DATA_LOCAL = 4, DATA_PROPERTIES = 1,
DATA_MOMENTUM = 2, DATA_LOCAL = 4, DATA_PROPERTIES = 1, DATA_MOMENTUM = 2,
DATA_LOCAL = 4
}
bitmask: which extra data elements to in- or exclude from ghost sending
enum ExtraDataElements {
DATA_PROPERTIES = 1, DATA_MOMENTUM = 2, DATA_LOCAL = 4, DATA_PROPERTIES = 1,
DATA_MOMENTUM = 2, DATA_LOCAL = 4, DATA_PROPERTIES = 1, DATA_MOMENTUM = 2,
DATA_LOCAL = 4
}
bitmask: which extra data elements to in- or exclude from ghost sending
Public Member Functions
OutBuffer (const mpi::communicator &comm)
void write (int &val)
void write (Particle &p, int extradata, const Real3D &shift)
void write (ParticleForce &f)
void write (Particle &p)
void write (std::vector< longint > &v)
void send (longint receiver, int tag)
OutBuffer (const mpi::communicator &comm)
template<class T >
void writeAll (T &val)
void write (int &val)
void write (real &val)
void write (Particle &p, int extradata, const Real3D &shift)
void write (ParticleForce &f)
void write (Particle &p)
void write (std::vector< longint > &v)
void write (std::vector< real > &v)
void send (longint receiver, int tag)
mpi::request isend (longint receiver, int tag)
OutBuffer (const mpi::communicator &comm)
template<class T >
void writeAll (T &val)
void write (int &val)
void write (Particle &p, int extradata, const Real3D &shift)
void write (ParticleForce &f)
void write (Particle &p)
void write (std::vector< longint > &v)
void send (longint receiver, int tag)
void reset ()
void reset ()
Protected Member Functions
void allocate (int size)
void extend (int size)
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (logger)
static LOG4ESPP_DECL_LOGGER (logger)
static LOG4ESPP_DECL_LOGGER (logger)
Protected Attributes
const mpi::communicator & comm
char * buf
char buf [BUFFER_SIZE]
char staticBuf [BUFFER_SIZE]
buffer with static size
boost::scoped_array< char > dynBuf
dynamic buffer, auto freed
int capacity
allocated size of the buffer
int usedSize
used size of the buffer
int pos
current buffer position
int size
Private Attributes
mpi::packed_oarchive ar
Detailed Description
Definition at line 103 of file BufferArchive.hpp.
Member Enumeration Documentation
enum espressopp::Buffer::ExtraDataElements [inherited]
bitmask: which extra data elements to in- or exclude from ghost sending
Enumerator:
DATA_PROPERTIES
DATA_MOMENTUM
DATA_LOCAL
DATA_PROPERTIES
DATA_MOMENTUM
DATA_LOCAL
DATA_PROPERTIES
DATA_MOMENTUM
DATA_LOCAL
Definition at line 42 of file BufferArchive.hpp.
enum espressopp::Buffer::ExtraDataElements [inherited]
bitmask: which extra data elements to in- or exclude from ghost sending
Enumerator:
DATA_PROPERTIES
DATA_MOMENTUM
DATA_LOCAL
DATA_PROPERTIES
DATA_MOMENTUM
DATA_LOCAL
DATA_PROPERTIES
DATA_MOMENTUM
DATA_LOCAL
Definition at line 46 of file BufferStatic.hpp.
enum espressopp::Buffer::ExtraDataElements [inherited]
bitmask: which extra data elements to in- or exclude from ghost sending
Enumerator:
DATA_PROPERTIES
DATA_MOMENTUM
DATA_LOCAL
DATA_PROPERTIES
DATA_MOMENTUM
DATA_LOCAL
DATA_PROPERTIES
DATA_MOMENTUM
DATA_LOCAL
Definition at line 52 of file BufferDynamic.hpp.
Constructor & Destructor Documentation
espressopp::OutBuffer::OutBuffer (const mpi::communicator & comm) [inline]
Definition at line 109 of file BufferArchive.hpp.
espressopp::OutBuffer::OutBuffer (const mpi::communicator & comm) [inline]
Definition at line 231 of file BufferDynamic.hpp.
espressopp::OutBuffer::OutBuffer (const mpi::communicator & comm) [inline]
Definition at line 146 of file BufferStatic.hpp.
Member Function Documentation
void espressopp::Buffer::allocate (int size) [inline, protected, inherited]
Definition at line 91 of file BufferDynamic.hpp.
References espressopp::Buffer::buf, espressopp::Buffer::capacity, espressopp::Buffer::dynBuf, espressopp::Buffer::size, and espressopp::Buffer::usedSize.
Referenced by espressopp::Buffer::extend(), espressopp::InBuffer::irecv(), and espressopp::InBuffer::recv().
void espressopp::Buffer::extend (int size) [inline, protected, inherited]
Definition at line 101 of file BufferDynamic.hpp.
References espressopp::Buffer::allocate(), and espressopp::Buffer::capacity.
Referenced by writeAll().
mpi::request espressopp::OutBuffer::isend (longint receiver, int tag) [inline]
Definition at line 301 of file BufferDynamic.hpp.
References espressopp::Buffer::buf, espressopp::Buffer::comm, and espressopp::Buffer::pos.
Referenced by espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), and espressopp::storage::DomainDecompositionNonBlocking::isendParticles().
static espressopp::Buffer::LOG4ESPP_DECL_LOGGER (logger) [static, protected, inherited]
static espressopp::Buffer::LOG4ESPP_DECL_LOGGER (logger) [static, protected, inherited]
static espressopp::Buffer::LOG4ESPP_DECL_LOGGER (logger) [static, protected, inherited]
void espressopp::Buffer::reset () [inline, inherited]
Definition at line 59 of file BufferStatic.hpp.
References espressopp::Buffer::pos, and espressopp::Buffer::size.
void espressopp::Buffer::reset () [inline, inherited]
Definition at line 69 of file BufferDynamic.hpp.
References espressopp::Buffer::pos, and espressopp::Buffer::usedSize.
Referenced by espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::storage::DomainDecompositionNonBlocking::isendParticles(), espressopp::integrator::AssociationReaction::sendMultiMap(), and espressopp::storage::Storage::sendParticles().
void espressopp::OutBuffer::send (longint receiver, int tag) [inline]
Definition at line 146 of file BufferArchive.hpp.
References ar, and espressopp::Buffer::comm.
Referenced by espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), and espressopp::integrator::AssociationReaction::sendMultiMap().
void espressopp::OutBuffer::send (longint receiver, int tag) [inline]
Definition at line 201 of file BufferStatic.hpp.
References espressopp::Buffer::buf, espressopp::Buffer::comm, and espressopp::Buffer::pos.
void espressopp::OutBuffer::send (longint receiver, int tag) [inline]
Definition at line 296 of file BufferDynamic.hpp.
References espressopp::Buffer::buf, espressopp::Buffer::comm, and espressopp::Buffer::pos.
void espressopp::OutBuffer::write (int & val) [inline]
Definition at line 113 of file BufferArchive.hpp.
References ar.
Referenced by espressopp::FixedQuadrupleListAdress::beforeSendATParticles(), espressopp::FixedPairListAdress::beforeSendATParticles(), espressopp::FixedTripleListAdress::beforeSendATParticles(), espressopp::FixedTupleList::beforeSendParticles(), espressopp::FixedTupleListAdress::beforeSendParticles(), espressopp::FixedListComm::beforeSendParticles(), espressopp::FixedSingleList::beforeSendParticles(), espressopp::FixedTripleList::beforeSendParticles(), espressopp::FixedPairDistList::beforeSendParticles(), espressopp::FixedQuadrupleList::beforeSendParticles(), espressopp::FixedPairList::beforeSendParticles(), espressopp::FixedTripleAngleList::beforeSendParticles(), espressopp::FixedQuadrupleAngleList::beforeSendParticles(), espressopp::storage::DomainDecompositionNonBlocking::isendParticles(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::Storage::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::storage::Storage::packPositionsEtc(), espressopp::integrator::AssociationReaction::sendMultiMap(), and write().
void espressopp::OutBuffer::write (Particle & p, int extradata, const Real3D & shift) [inline]
Definition at line 115 of file BufferArchive.hpp.
References ar, espressopp::ParticlePosition::copyShifted(), espressopp::Buffer::DATA_LOCAL, espressopp::Buffer::DATA_MOMENTUM, espressopp::Buffer::DATA_PROPERTIES, espressopp::Particle::l, espressopp::Particle::m, espressopp::Particle::p, and espressopp::Particle::r.
void espressopp::OutBuffer::write (ParticleForce & f) [inline]
Definition at line 134 of file BufferArchive.hpp.
References ar.
void espressopp::OutBuffer::write (Particle & p) [inline]
Definition at line 138 of file BufferArchive.hpp.
References ar.
void espressopp::OutBuffer::write (std::vector< longint > & v) [inline]
Definition at line 142 of file BufferArchive.hpp.
References ar.
void espressopp::OutBuffer::write (int & val) [inline]
Definition at line 163 of file BufferStatic.hpp.
void espressopp::OutBuffer::write (Particle & p, int extradata, const Real3D & shift) [inline]
Definition at line 165 of file BufferStatic.hpp.
References espressopp::ParticlePosition::copyShifted(), espressopp::Buffer::DATA_LOCAL, espressopp::Buffer::DATA_MOMENTUM, espressopp::Buffer::DATA_PROPERTIES, espressopp::Particle::l, espressopp::Particle::m, espressopp::Particle::p, and espressopp::Particle::r.
void espressopp::OutBuffer::write (ParticleForce & f) [inline]
Definition at line 184 of file BufferStatic.hpp.
void espressopp::OutBuffer::write (Particle & p) [inline]
Definition at line 188 of file BufferStatic.hpp.
void espressopp::OutBuffer::write (std::vector< longint > & v) [inline]
Definition at line 192 of file BufferStatic.hpp.
References espressopp::Buffer::size, and write().
void espressopp::OutBuffer::write (int & val) [inline]
Definition at line 247 of file BufferDynamic.hpp.
void espressopp::OutBuffer::write (real & val) [inline]
Definition at line 249 of file BufferDynamic.hpp.
void espressopp::OutBuffer::write (Particle & p, int extradata, const Real3D & shift) [inline]
Definition at line 251 of file BufferDynamic.hpp.
References espressopp::ParticlePosition::copyShifted(), espressopp::Buffer::DATA_LOCAL, espressopp::Buffer::DATA_MOMENTUM, espressopp::Buffer::DATA_PROPERTIES, espressopp::Particle::l, espressopp::Particle::m, espressopp::Particle::p, and espressopp::Particle::r.
void espressopp::OutBuffer::write (ParticleForce & f) [inline]
Definition at line 270 of file BufferDynamic.hpp.
void espressopp::OutBuffer::write (Particle & p) [inline]
Definition at line 274 of file BufferDynamic.hpp.
void espressopp::OutBuffer::write (std::vector< longint > & v) [inline]
Definition at line 278 of file BufferDynamic.hpp.
References espressopp::Buffer::size, and write().
void espressopp::OutBuffer::write (std::vector< real > & v) [inline]
Definition at line 287 of file BufferDynamic.hpp.
References espressopp::Buffer::size, and write().
template<class T > void espressopp::OutBuffer::writeAll (T & val) [inline]
Definition at line 151 of file BufferStatic.hpp.
References espressopp::Buffer::buf, espressopp::Buffer::capacity, espressopp::Buffer::pos, and espressopp::Buffer::size.
template<class T > void espressopp::OutBuffer::writeAll (T & val) [inline]
Definition at line 236 of file BufferDynamic.hpp.
References espressopp::Buffer::buf, espressopp::Buffer::extend(), espressopp::Buffer::pos, espressopp::Buffer::size, and espressopp::Buffer::usedSize.
Member Data Documentation
mpi::packed_oarchive espressopp::OutBuffer::ar [private]
Definition at line 105 of file BufferArchive.hpp.
Referenced by send(), and write().
char espressopp::Buffer::buf[BUFFER_SIZE] [protected, inherited]
Definition at line 71 of file BufferStatic.hpp.
char* espressopp::Buffer::buf [protected, inherited]
Definition at line 81 of file BufferDynamic.hpp.
Referenced by espressopp::Buffer::allocate(), espressopp::Buffer::Buffer(), espressopp::InBuffer::irecv(), isend(), espressopp::InBuffer::readAll(), espressopp::InBuffer::recv(), send(), and writeAll().
int espressopp::Buffer::capacity [protected, inherited]
allocated size of the buffer
Definition at line 87 of file BufferDynamic.hpp.
Referenced by espressopp::Buffer::allocate(), espressopp::Buffer::Buffer(), espressopp::Buffer::extend(), espressopp::InBuffer::irecv(), espressopp::InBuffer::recv(), and writeAll().
const mpi::communicator & espressopp::Buffer::comm [protected, inherited]
Definition at line 54 of file BufferArchive.hpp.
Referenced by espressopp::InBuffer::irecv(), isend(), espressopp::InBuffer::readAll(), espressopp::InBuffer::recv(), and send().
boost::scoped_array<char> espressopp::Buffer::dynBuf [protected, inherited]
dynamic buffer, auto freed
Definition at line 85 of file BufferDynamic.hpp.
Referenced by espressopp::Buffer::allocate().
int espressopp::Buffer::pos [protected, inherited]
current buffer position
Definition at line 89 of file BufferDynamic.hpp.
Referenced by espressopp::Buffer::Buffer(), espressopp::InBuffer::irecv(), isend(), espressopp::InBuffer::readAll(), espressopp::InBuffer::recv(), espressopp::Buffer::reset(), send(), and writeAll().
int espressopp::Buffer::size [protected, inherited]
Definition at line 72 of file BufferStatic.hpp.
Referenced by espressopp::Buffer::allocate(), espressopp::Buffer::Buffer(), espressopp::InBuffer::readAll(), espressopp::InBuffer::recv(), espressopp::Buffer::reset(), write(), and writeAll().
char espressopp::Buffer::staticBuf[BUFFER_SIZE] [protected, inherited]
buffer with static size
Definition at line 83 of file BufferDynamic.hpp.
Referenced by espressopp::Buffer::Buffer().
int espressopp::Buffer::usedSize [protected, inherited]
used size of the buffer
Definition at line 88 of file BufferDynamic.hpp.
Referenced by espressopp::Buffer::allocate(), espressopp::Buffer::Buffer(), espressopp::InBuffer::irecv(), espressopp::InBuffer::readAll(), espressopp::InBuffer::recv(), espressopp::Buffer::reset(), and writeAll().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/BufferArchive.hpp
/home/travis/build/espressopp/espressopp/src/BufferDynamic.hpp
/home/travis/build/espressopp/espressopp/src/BufferStatic.hpp