ESPResSo++: espressopp::storage::Storage Class Reference
espressopp::storage::Storage Class Reference abstract
represents the particle storage of one system.
#include <Storage.hpp>
Public Types
typedef boost::unordered_map< longint, Particle * > IdParticleMap
typedef std::list< Particle > ParticleListAdr
Public Member Functions
Storage (shared_ptr< class System > system)
virtual ~Storage ()
void scaleVolume (real s)
Scale Volume, only for Storage.
void scaleVolume (Real3D s)
Scale Volume, only for Storage.
virtual void scaleVolume (real s, bool pS)=0
Scale Volume for derived classes, pS define the particle coordinates scaling.
virtual void scaleVolume (Real3D s, bool pS)=0
Scale Volume for derived classes, pS define the particle coordinates scaling.
virtual void cellAdjust ()=0
It should be used at the place where is the possibility of cell size<cutoff+skin.
virtual Int3D getInt3DCellGrid ()=0
It should return cell grid as an integer vector.
virtual real getLocalBoxXMin ()=0
virtual real getLocalBoxYMin ()=0
virtual real getLocalBoxZMin ()=0
virtual real getLocalBoxXMax ()=0
virtual real getLocalBoxYMax ()=0
virtual real getLocalBoxZMax ()=0
Particle * addParticle (longint id, const Real3D &pos)
add a particle with given id and position.
int removeParticle (longint id)
void removeAllParticles ()
Particle * addAdrATParticle (longint id, const Real3D &pos, const Real3D &VPpos)
Particle * addAdrATParticleFTPL (Particle n)
void removeAdrATParticle (longint id)
Particle * lookupLocalParticle (longint id)
lookup whether data for a given particle is available on this node, either as real or as ghost particle.
Particle * lookupGhostParticle (longint id)
Particle * lookupRealParticle (longint id)
Lookup whether data for a given particle is available on this node.
Particle * lookupAdrATParticle (longint id)
Lookup whether data for a given adress real AT particle is available on this node.
longint getNRealParticles () const
get number of real particles on this node
longint getNLocalParticles () const
longint getNGhostParticles () const
longint getNAdressParticles () const
void fetchParticles (Storage &)
insert the particles in the given storage into the current one.
CellList & getLocalCells ()
CellList & getRealCells ()
CellList & getGhostCells ()
python::list getRealParticleIDs ()
const Cell * getFirstCell () const
virtual Cell * mapPositionToCell (const Real3D &pos)=0
map a position to a valid cell on this node.
virtual Cell * mapPositionToCellClipped (const Real3D &pos)=0
map a position to a valid cell on this node.
virtual Cell * mapPositionToCellChecked (const Real3D &pos)=0
map a position to a cell on this node.
virtual void decompose ()
(Re-)Decompose the system, i.e.
virtual void updateGhosts ()=0
copy minimal information from the real to the ghost particles.
virtual void updateGhostsV ()=0
Copies just velocites of real particles to their ghosts.
virtual void collectGhostForces ()=0
read back forces from ghost particles by two-sided communication.
void setFixedTuplesAdress (shared_ptr< FixedTupleListAdress > _fixedtupleList)
shared_ptr< FixedTupleListAdress > getFixedTuples ()
ParticleList & getAdrATParticles ()
std::list< ParticleList > & getAdrATParticlesG ()
bool pyAddParticle (longint id, const Real3D &pos)
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
Public Attributes
boost::signals2::signal< void()> onParticlesChanged
Ths signal will be called whenever the storage was modified such that particle pointers have become invalid, e.g.
boost::signals2::signal< void(ParticleList &, class OutBuffer &)> beforeSendParticles
boost::signals2::signal< void(ParticleList &, class InBuffer &)> afterRecvParticles
boost::signals2::signal< void()> onTuplesChanged
Protected Types
enum ExtraDataElements { DATA_PROPERTIES =1, DATA_MOMENTUM =2, DATA_LOCAL =4 }
bitmask: which extra data elements to in- or exclude from ghost sending
Protected Member Functions
virtual bool checkIsRealParticle (longint id, const Real3D &pos)=0
Check whether a particle belongs to this node.
virtual void decomposeRealParticles ()=0
Decompose the real particles such that they are at the correct processor.
virtual void exchangeGhosts ()=0
used by the Storage to initiate the exchange of the full ghost information after decomposition.
virtual void invalidateGhosts ()
remove ghost particles from the localParticles index
virtual void packPositionsEtc (class OutBuffer &buf, Cell &reals, int extradata, const Real3D &shift)
pack real particle data for sending.
virtual void unpackPositionsEtc (Cell &ghosts, class InBuffer &buf, int extradata)
unpack received data for ghosts.
virtual void copyRealsToGhosts (Cell &reals, Cell &ghosts, int extradata, const Real3D &shift)
copy specified data elements between a real cell and one of its ghosts
virtual void packForces (OutBuffer &buf, Cell &ghosts)
pack ghost forces for sending.
virtual void unpackAndAddForces (Cell &reals, class InBuffer &buf)
unpack received ghost forces.
void unpackForces (Cell &reals, class InBuffer &buf)
unpack received ghost forces.
virtual void addGhostForcesToReals (Cell &ghosts, Cell &reals)
void sendParticles (ParticleList &, longint node)
send particles of a cell to another node, and empty the cell locally.
void recvParticles (ParticleList &, longint node)
receive particles from another node.
void updateLocalParticles (ParticleList &, bool adress=false)
void removeFromLocalParticles (Particle *, bool weak=false)
void updateInLocalParticles (Particle *, bool weak=false)
void updateInLocalAdrATParticles (Particle *)
void resizeCells (longint nCells)
Particle * appendUnindexedParticle (ParticleList &, Particle &)
Particle * appendUnindexedAdrParticle (ParticleList &, Particle &)
void appendParticleListToGhosts (ParticleList &l)
Particle * appendIndexedParticle (ParticleList &, Particle &)
Particle * moveIndexedParticle (ParticleList &dst, ParticleList &src, int srcpos)
void clearAdrATParticlesG ()
void savePosition (size_t id)
void restorePositions ()
void clearSavedPositions ()
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (logger)
Protected Attributes
LocalCellList cells
here the local particles are actually stored
CellList realCells
list of real cells
CellList ghostCells
list of ghost cells
CellList localCells
all cells on this CPU.
InBuffer inBuffer
OutBuffer outBuffer
shared_ptr< FixedTupleListAdress > fixedtupleList
Static Protected Attributes
static const int dataOfUpdateGhosts = 0
for the moment, these are constants, defining what to transfer during ghost communications.
static const int dataOfExchangeGhosts = DATA_PROPERTIES
Private Attributes
boost::unordered_map< longint, Particle * > localParticles
ParticleList AdrATParticles
std::list< ParticleList > AdrATParticlesG
boost::unordered_map< longint, Particle * > localAdrATParticles
std::map< size_t, Real3D > savedRealPositions
std::map< size_t, Int3D > savedImages
Detailed Description
represents the particle storage of one system.
Definition at line 45 of file Storage.hpp.
Member Typedef Documentation
IdParticleMap
typedef boost::unordered_map<longint, Particle*> espressopp::storage::Storage::IdParticleMap
Definition at line 47 of file Storage.hpp.
ParticleListAdr
typedef std::list<Particle> espressopp::storage::Storage::ParticleListAdr
Definition at line 48 of file Storage.hpp.
Member Enumeration Documentation
ExtraDataElements
enum espressopp::storage::Storage::ExtraDataElements protected
bitmask: which extra data elements to in- or exclude from ghost sending
Enumerator
DATA_PROPERTIES
DATA_MOMENTUM
DATA_LOCAL
Definition at line 286 of file Storage.hpp.
Constructor & Destructor Documentation
Storage()
espressopp::storage::Storage::Storage (shared_ptr< class System > system)
Definition at line 56 of file Storage.cpp.
References LOG4ESPP_INFO.
~Storage()
espressopp::storage::Storage::~Storage () virtual
Definition at line 65 of file Storage.cpp.
Member Function Documentation
addAdrATParticle()
Particle * espressopp::storage::Storage::addAdrATParticle (longint id, const Real3D & pos, const Real3D & VPpos)
Definition at line 324 of file Storage.cpp.
References AdrATParticles, checkIsRealParticle(), espressopp::SystemAccess::getSystem(), espressopp::Particle::id(), espressopp::Particle::image(), espressopp::Particle::init(), espressopp::Particle::position(), updateInLocalAdrATParticles(), and updateLocalParticles().
Referenced by registerPython().
addAdrATParticleFTPL()
Particle * espressopp::storage::Storage::addAdrATParticleFTPL (Particle n)
Definition at line 372 of file Storage.cpp.
References AdrATParticles, updateInLocalAdrATParticles(), and updateLocalParticles().
addGhostForcesToReals()
void espressopp::storage::Storage::addGhostForcesToReals (Cell & ghosts, Cell & reals) protected virtual
Reimplemented in espressopp::storage::DomainDecompositionAdress.
Definition at line 675 of file Storage.cpp.
References getFirstCell(), LOG4ESPP_DEBUG, LOG4ESPP_TRACE, and espressopp::Cell::particles.
Referenced by espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), and espressopp::storage::DomainDecomposition::doGhostCommunication().
addParticle()
Particle * espressopp::storage::Storage::addParticle (longint id, const Real3D & pos)
add a particle with given id and position.
Note that this is a local operation, and therefore cannot check whether a particle with the given id already exists. This is left to the parallel front end.
Definition at line 256 of file Storage.cpp.
References appendIndexedParticle(), checkIsRealParticle(), getFirstCell(), espressopp::SystemAccess::getSystem(), espressopp::Particle::id(), espressopp::Particle::image(), espressopp::Particle::init(), LOG4ESPP_TRACE, mapPositionToCellClipped(), espressopp::Cell::particles, and espressopp::Particle::position().
Referenced by registerPython().
appendIndexedParticle()
Particle * espressopp::storage::Storage::appendIndexedParticle (ParticleList & l, Particle & part) protected
Definition at line 416 of file Storage.cpp.
References updateInLocalParticles(), and updateLocalParticles().
Referenced by addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), and espressopp::storage::DomainDecompositionAdress::appendParticles().
appendParticleListToGhosts()
void espressopp::storage::Storage::appendParticleListToGhosts (ParticleList & l) protected
Definition at line 409 of file Storage.cpp.
References AdrATParticlesG.
Referenced by espressopp::storage::DomainDecompositionAdress::copyGhostTuples(), and espressopp::storage::DomainDecompositionAdress::unpackPositionsEtc().
appendUnindexedAdrParticle()
Particle * espressopp::storage::Storage::appendUnindexedAdrParticle (ParticleList & l, Particle & part) protected
Definition at line 404 of file Storage.cpp.
appendUnindexedParticle()
Particle * espressopp::storage::Storage::appendUnindexedParticle (ParticleList & l, Particle & part) protected
Definition at line 397 of file Storage.cpp.
Referenced by espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), and fetchParticles().
cellAdjust()
virtual void espressopp::storage::Storage::cellAdjust () pure virtual
It should be used at the place where is the possibility of cell size<cutoff+skin.
Implemented in espressopp::storage::DomainDecomposition, and espressopp::storage::DomainDecompositionAdress.
checkIsRealParticle()
virtual bool espressopp::storage::Storage::checkIsRealParticle (longint id, const Real3D & pos) protected pure virtual
Check whether a particle belongs to this node.
Implemented in espressopp::storage::DomainDecompositionAdress, and espressopp::storage::DomainDecomposition.
Referenced by addAdrATParticle(), addParticle(), and getAdrATParticlesG().
clearAdrATParticlesG()
void espressopp::storage::Storage::clearAdrATParticlesG () inline protected
Definition at line 408 of file Storage.hpp.
References AdrATParticlesG, clearSavedPositions(), restorePositions(), and savePosition().
Referenced by espressopp::storage::DomainDecompositionAdress::invalidateGhosts().
clearSavedPositions()
void espressopp::storage::Storage::clearSavedPositions () protected
Definition at line 694 of file Storage.cpp.
References savedImages, and savedRealPositions.
Referenced by clearAdrATParticlesG(), and registerPython().
collectGhostForces()
virtual void espressopp::storage::Storage::collectGhostForces () pure virtual
read back forces from ghost particles by two-sided communication.
Storage implementations should only gather forces here. Note that forces are not stored back, but are additive!
Implemented in espressopp::storage::DomainDecompositionAdress, and espressopp::storage::DomainDecomposition.
Referenced by getFirstCell(), espressopp::integrator::VelocityVerletRESPA::updateForces(), espressopp::integrator::VelocityVerlet::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), and espressopp::integrator::PIAdressIntegrator::updateForces().
copyRealsToGhosts()
void espressopp::storage::Storage::copyRealsToGhosts (Cell & reals, Cell & ghosts, int extradata, const Real3D & shift) protected virtual
copy specified data elements between a real cell and one of its ghosts
Parameters
shift how to adjust the positions of the particles when sending
Reimplemented in espressopp::storage::DomainDecompositionAdress.
Definition at line 603 of file Storage.cpp.
References DATA_LOCAL, DATA_MOMENTUM, DATA_PROPERTIES, getFirstCell(), LOG4ESPP_DEBUG, and espressopp::Cell::particles.
Referenced by espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), and espressopp::storage::DomainDecomposition::doGhostCommunication().
decompose()
void espressopp::storage::Storage::decompose () virtual
(Re-)Decompose the system, i.e.
redistribute the particles to the correct processors.
This should be called by any parallel algorithm that works with the particle data at the beggining of the algorithm. Otherwise, it is not guaranteed that the particles are at the correct processor.
This should be called by the integrator instead of updateGhosts() whenever a particle might have moved more than a given skin. The skin is not an issue of the storage, but all algorithms using the particle data need to be aware that particles might be located up to skin away from their current cell.
Reimplemented in espressopp::storage::DomainDecompositionAdress.
Definition at line 555 of file Storage.cpp.
References decomposeRealParticles(), exchangeGhosts(), invalidateGhosts(), and onParticlesChanged.
Referenced by getFirstCell(), registerPython(), espressopp::integrator::VelocityVerletRESPA::run(), espressopp::integrator::PIAdressIntegrator::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::MinimizeEnergy::run(), and espressopp::integrator::VelocityVerletOnGroup::run().
decomposeRealParticles()
virtual void espressopp::storage::Storage::decomposeRealParticles () protected pure virtual
Decompose the real particles such that they are at the correct processor.
This should not touch the ghosts. Called by decompose.
Implemented in espressopp::storage::DomainDecompositionAdress, espressopp::storage::DomainDecomposition, and espressopp::storage::DomainDecompositionNonBlocking.
Referenced by decompose(), and getAdrATParticlesG().
exchangeGhosts()
virtual void espressopp::storage::Storage::exchangeGhosts () protected pure virtual
used by the Storage to initiate the exchange of the full ghost information after decomposition.
Storage implementations should exchange particle positions, plus data fields as indicated by dataOfExchangeGhosts.
Implemented in espressopp::storage::DomainDecompositionAdress, and espressopp::storage::DomainDecomposition.
Referenced by decompose(), and getAdrATParticlesG().
fetchParticles()
void espressopp::storage::Storage::fetchParticles (Storage & old)
insert the particles in the given storage into the current one.
This is mainly used to switch from one storage to another.
Definition at line 472 of file Storage.cpp.
References appendUnindexedParticle(), getRealCells(), espressopp::iterator::CellListIterator::isValid(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_DEBUG, mapPositionToCellClipped(), espressopp::Cell::particles, espressopp::Particle::position(), realCells, and updateLocalParticles().
getAdrATParticles()
ParticleList& espressopp::storage::Storage::getAdrATParticles () inline
Definition at line 254 of file Storage.hpp.
References AdrATParticles.
getAdrATParticlesG()
std::list<ParticleList>& espressopp::storage::Storage::getAdrATParticlesG () inline
Definition at line 256 of file Storage.hpp.
References AdrATParticlesG, checkIsRealParticle(), decomposeRealParticles(), exchangeGhosts(), pyAddParticle(), and registerPython().
Referenced by espressopp::storage::DomainDecompositionAdress::copyGhostTuples(), and espressopp::storage::DomainDecompositionAdress::unpackPositionsEtc().
getFirstCell()
const Cell* espressopp::storage::Storage::getFirstCell () const inline
Definition at line 175 of file Storage.hpp.
References cells, collectGhostForces(), decompose(), mapPositionToCell(), mapPositionToCellChecked(), mapPositionToCellClipped(), updateGhosts(), and updateGhostsV().
Referenced by addGhostForcesToReals(), addParticle(), copyRealsToGhosts(), getNGhostParticles(), getNLocalParticles(), getNRealParticles(), espressopp::storage::DomainDecomposition::initCellInteractions(), espressopp::storage::DomainDecompositionAdress::initCellInteractions(), packForces(), packPositionsEtc(), espressopp::storage::DomainDecompositionAdress::unpackAndAddForces(), unpackAndAddForces(), unpackForces(), and unpackPositionsEtc().
getFixedTuples()
shared_ptr<FixedTupleListAdress> espressopp::storage::Storage::getFixedTuples () inline
Definition at line 253 of file Storage.hpp.
References fixedtupleList.
getGhostCells()
CellList& espressopp::storage::Storage::getGhostCells () inline
Definition at line 171 of file Storage.hpp.
References getRealParticleIDs(), and ghostCells.
Referenced by espressopp::storage::DomainDecompositionAdress::invalidateGhosts(), and invalidateGhosts().
getInt3DCellGrid()
virtual Int3D espressopp::storage::Storage::getInt3DCellGrid () pure virtual
It should return cell grid as an integer vector.
Implemented in espressopp::storage::DomainDecomposition, and espressopp::storage::DomainDecompositionAdress.
getLocalBoxXMax()
virtual real espressopp::storage::Storage::getLocalBoxXMax () pure virtual
Implemented in espressopp::storage::DomainDecomposition, and espressopp::storage::DomainDecompositionAdress.
getLocalBoxXMin()
virtual real espressopp::storage::Storage::getLocalBoxXMin () pure virtual
Implemented in espressopp::storage::DomainDecomposition, and espressopp::storage::DomainDecompositionAdress.
getLocalBoxYMax()
virtual real espressopp::storage::Storage::getLocalBoxYMax () pure virtual
Implemented in espressopp::storage::DomainDecomposition, and espressopp::storage::DomainDecompositionAdress.
getLocalBoxYMin()
virtual real espressopp::storage::Storage::getLocalBoxYMin () pure virtual
Implemented in espressopp::storage::DomainDecomposition, and espressopp::storage::DomainDecompositionAdress.
getLocalBoxZMax()
virtual real espressopp::storage::Storage::getLocalBoxZMax () pure virtual
Implemented in espressopp::storage::DomainDecomposition, and espressopp::storage::DomainDecompositionAdress.
getLocalBoxZMin()
virtual real espressopp::storage::Storage::getLocalBoxZMin () pure virtual
Implemented in espressopp::storage::DomainDecomposition, and espressopp::storage::DomainDecompositionAdress.
getLocalCells()
CellList& espressopp::storage::Storage::getLocalCells () inline
Definition at line 169 of file Storage.hpp.
References localCells.
getNAdressParticles()
longint espressopp::storage::Storage::getNAdressParticles () const
Definition at line 101 of file Storage.cpp.
References localAdrATParticles.
getNGhostParticles()
longint espressopp::storage::Storage::getNGhostParticles () const
Definition at line 90 of file Storage.cpp.
References getFirstCell(), ghostCells, and LOG4ESPP_TRACE.
getNLocalParticles()
longint espressopp::storage::Storage::getNLocalParticles () const
Definition at line 79 of file Storage.cpp.
References getFirstCell(), localCells, and LOG4ESPP_TRACE.
getNRealParticles()
longint espressopp::storage::Storage::getNRealParticles () const
get number of real particles on this node
Definition at line 67 of file Storage.cpp.
References getFirstCell(), LOG4ESPP_TRACE, and realCells.
getRealCells()
CellList& espressopp::storage::Storage::getRealCells () inline
Definition at line 170 of file Storage.hpp.
References realCells.
Referenced by fetchParticles().
getRealParticleIDs()
python::list espressopp::storage::Storage::getRealParticleIDs ()
Definition at line 106 of file Storage.cpp.
References espressopp::iterator::CellListIterator::isDone(), and realCells.
Referenced by getGhostCells(), and registerPython().
getSystem()
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by addAdrATParticle(), addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::LatticeBoltzmann::assignMyLattice(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::PIAdressIntegrator::computeKineticEnergy(), espressopp::integrator::PIAdressIntegrator::computeMomentumDrift(), espressopp::integrator::PIAdressIntegrator::computePositionDrift(), espressopp::integrator::PIAdressIntegrator::computeRingEnergy(), espressopp::integrator::PIAdressIntegrator::computeRingEnergyRaw(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpXTCAdress::dump(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::io::DumpXYZ::DumpXYZ(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::VerletListTriple::registerPython(), espressopp::VerletList::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), restorePositions(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
getSystem1()
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
getSystem2()
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
getSystemRef()
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::addForces(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::addForces(), espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerletRESPA::calcForces(), espressopp::integrator::VelocityVerlet::calcForces(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::PIAdressIntegrator::calcForcesF(), espressopp::integrator::PIAdressIntegrator::calcForcesM(), espressopp::integrator::PIAdressIntegrator::calcForcesS(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeCOM(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeEnergy(), espressopp::integrator::PIAdressIntegrator::computeKineticEnergy(), espressopp::integrator::PIAdressIntegrator::computeMomentumDrift(), espressopp::integrator::PIAdressIntegrator::computePositionDrift(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::integrator::PIAdressIntegrator::computeRingEnergy(), espressopp::integrator::PIAdressIntegrator::computeRingEnergyRaw(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::PIAdressIntegrator::distributeForces(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::FixedLocalTupleComListInteractionTemplate(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::VelocityVerletRESPA::initForces(), espressopp::integrator::VelocityVerlet::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::PIAdressIntegrator::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::PIAdressIntegrator::initializeSetup(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::VelocityVerletRESPA::integrate1(), espressopp::integrator::VelocityVerlet::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::VelocityVerletRESPA::integrate2(), espressopp::integrator::VelocityVerlet::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::PIAdressIntegrator::integrateModePos(), espressopp::integrator::Adress::integrateSlow(), espressopp::integrator::PIAdressIntegrator::integrateV1(), espressopp::integrator::PIAdressIntegrator::integrateV2(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::PIAdressIntegrator::OUintegrate(), espressopp::integrator::VelocityVerlet::printForces(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerlet::printPositions(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::PIAdressIntegrator::run(), espressopp::integrator::VelocityVerletRESPA::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::MinimizeEnergy::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::Rattle::saveOldPos(), espressopp::integrator::Settle::saveOldPos(), savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::PIAdressIntegrator::setWeights(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostatOnGroup::thermalize(), espressopp::integrator::LangevinThermostatOnRadius::thermalize(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::integrator::PIAdressIntegrator::transForces(), espressopp::integrator::PIAdressIntegrator::transMom1(), espressopp::integrator::PIAdressIntegrator::transMom2(), espressopp::integrator::PIAdressIntegrator::transPos1(), espressopp::integrator::PIAdressIntegrator::transPos2(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::io::DumpH5MD::update(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::VelocityVerletRESPA::updateForces(), espressopp::integrator::VelocityVerlet::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::PIAdressIntegrator::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
getSystemRef1()
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
getSystemRef2()
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
invalidateGhosts()
void espressopp::storage::Storage::invalidateGhosts () protected virtual
remove ghost particles from the localParticles index
Reimplemented in espressopp::storage::DomainDecompositionAdress.
Definition at line 544 of file Storage.cpp.
References getGhostCells(), espressopp::iterator::CellListIterator::isValid(), and removeFromLocalParticles().
Referenced by espressopp::storage::DomainDecomposition::cellAdjust(), and decompose().
LOG4ESPP_DECL_LOGGER()
static espressopp::storage::Storage::LOG4ESPP_DECL_LOGGER (logger) static protected
lookupAdrATParticle()
Particle* espressopp::storage::Storage::lookupAdrATParticle (longint id) inline
Lookup whether data for a given adress real AT particle is available on this node.
Returns
0 if the particle wasn't available, the pointer to the Particle, if it was.
Definition at line 147 of file Storage.hpp.
References localAdrATParticles.
Referenced by lookupRealParticle(), and removeAdrATParticle().
lookupGhostParticle()
Particle* espressopp::storage::Storage::lookupGhostParticle (longint id) inline
Definition at line 114 of file Storage.hpp.
References localParticles.
lookupLocalParticle()
Particle* espressopp::storage::Storage::lookupLocalParticle (longint id) inline
lookup whether data for a given particle is available on this node, either as real or as ghost particle.
Definition at line 109 of file Storage.hpp.
References localParticles.
Referenced by registerPython().
lookupRealParticle()
Particle* espressopp::storage::Storage::lookupRealParticle (longint id) inline
Lookup whether data for a given particle is available on this node.
Returns
0 if the particle wasn't available, the pointer to the Particle, if it was. Lookup whether data for a given particle is available on this node.
0 if the particle wasn't available, the pointer to the Particle, if it was.
Definition at line 132 of file Storage.hpp.
References localParticles, and lookupAdrATParticle().
Referenced by registerPython(), removeParticle(), restorePositions(), and savePosition().
mapPositionToCell()
virtual Cell* espressopp::storage::Storage::mapPositionToCell (const Real3D & pos) pure virtual
map a position to a valid cell on this node.
Used for AdResS
Implemented in espressopp::storage::DomainDecomposition, and espressopp::storage::DomainDecompositionAdress.
Referenced by getFirstCell().
mapPositionToCellChecked()
virtual Cell* espressopp::storage::Storage::mapPositionToCellChecked (const Real3D & pos) pure virtual
map a position to a cell on this node.
If the position is outside the domain of this node, return 0.
Implemented in espressopp::storage::DomainDecomposition, and espressopp::storage::DomainDecompositionAdress.
Referenced by getFirstCell(), and removeParticle().
mapPositionToCellClipped()
virtual Cell* espressopp::storage::Storage::mapPositionToCellClipped (const Real3D & pos) pure virtual
map a position to a valid cell on this node.
If the position is outside the domain of this node, return the cell inside the domain that is closest to the position.
Implemented in espressopp::storage::DomainDecomposition, and espressopp::storage::DomainDecompositionAdress.
Referenced by addParticle(), fetchParticles(), and getFirstCell().
moveIndexedParticle()
Particle * espressopp::storage::Storage::moveIndexedParticle (ParticleList & dst, ParticleList & src, int srcpos) protected
Definition at line 434 of file Storage.cpp.
References updateInLocalParticles(), and updateLocalParticles().
Referenced by espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), and espressopp::storage::DomainDecompositionAdress::decomposeRealParticles().
packForces()
void espressopp::storage::Storage::packForces (OutBuffer & buf, Cell & ghosts) protected virtual
pack ghost forces for sending.
Reimplemented in espressopp::storage::DomainDecompositionAdress.
Definition at line 628 of file Storage.cpp.
References getFirstCell(), LOG4ESPP_DEBUG, LOG4ESPP_TRACE, espressopp::Cell::particles, and espressopp::OutBuffer::write().
Referenced by espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), and espressopp::storage::DomainDecomposition::doGhostCommunication().
packPositionsEtc()
void espressopp::storage::Storage::packPositionsEtc (class OutBuffer & buf, Cell & reals, int extradata, const Real3D & shift) protected virtual
pack real particle data for sending.
At least positions, maybe shifted, and possibly additional data according to extradata.
Parameters
shift how to adjust the positions of the particles when sending
Reimplemented in espressopp::storage::DomainDecompositionAdress.
Definition at line 562 of file Storage.cpp.
References DATA_LOCAL, DATA_MOMENTUM, DATA_PROPERTIES, getFirstCell(), LOG4ESPP_DEBUG, espressopp::Cell::particles, and espressopp::OutBuffer::write().
Referenced by espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), and espressopp::storage::DomainDecomposition::doGhostCommunication().
pyAddParticle()
bool espressopp::storage::Storage::pyAddParticle (longint id, const Real3D & pos)
Referenced by getAdrATParticlesG().
recvParticles()
void espressopp::storage::Storage::recvParticles (ParticleList & list, longint node) protected
receive particles from another node.
The particles are added to the given cell. The operation is blocking: the operation will wait until the particles have been received.
The particles are not added to localParticles! Moreover, the cell might be resized, invalidating all particles localParticles entries. Therefore, if the receiving cell is the final destination of the particles, call updateLocalParticles after recvParticles.
Definition at line 515 of file Storage.cpp.
References afterRecvParticles, inBuffer, LOG4ESPP_DEBUG, espressopp::InBuffer::read(), espressopp::InBuffer::recv(), and updateInLocalParticles().
Referenced by espressopp::storage::DomainDecomposition::decomposeRealParticles(), and espressopp::storage::DomainDecompositionAdress::decomposeRealParticles().
registerPython()
void espressopp::storage::Storage::registerPython () static
Definition at line 751 of file Storage.cpp.
References addAdrATParticle(), addParticle(), clearSavedPositions(), decompose(), getRealParticleIDs(), espressopp::SystemAccess::getSystem(), lookupLocalParticle(), lookupRealParticle(), removeAllParticles(), removeParticle(), restorePositions(), savePosition(), and setFixedTuplesAdress().
Referenced by getAdrATParticlesG(), and espressopp::storage::registerPython().
removeAdrATParticle()
void espressopp::storage::Storage::removeAdrATParticle (longint id)
Definition at line 154 of file Storage.cpp.
References AdrATParticles, localAdrATParticles, lookupAdrATParticle(), updateInLocalAdrATParticles(), and updateLocalParticles().
removeAllParticles()
void espressopp::storage::Storage::removeAllParticles ()
Definition at line 315 of file Storage.cpp.
References localCells, localParticles, and onParticlesChanged.
Referenced by registerPython().
removeFromLocalParticles()
void espressopp::storage::Storage::removeFromLocalParticles (Particle * p, bool weak = false) protected
Definition at line 116 of file Storage.cpp.
References espressopp::Particle::id(), localParticles, and LOG4ESPP_TRACE.
Referenced by espressopp::storage::DomainDecompositionAdress::invalidateGhosts(), invalidateGhosts(), espressopp::storage::DomainDecompositionNonBlocking::isendParticles(), removeParticle(), and sendParticles().
removeParticle()
int espressopp::storage::Storage::removeParticle (longint id)
Definition at line 284 of file Storage.cpp.
References espressopp::Particle::id(), lookupRealParticle(), mapPositionToCellChecked(), onParticlesChanged, espressopp::Cell::particles, espressopp::Particle::position(), removeFromLocalParticles(), and updateLocalParticles().
Referenced by registerPython().
resizeCells()
void espressopp::storage::Storage::resizeCells (longint nCells) protected
Definition at line 248 of file Storage.cpp.
References cells, and localCells.
Referenced by espressopp::storage::DomainDecomposition::createCellGrid(), and espressopp::storage::DomainDecompositionAdress::createCellGrid().
restorePositions()
void espressopp::storage::Storage::restorePositions () protected
Definition at line 715 of file Storage.cpp.
References espressopp::SystemAccess::getSystem(), espressopp::Particle::image(), lookupRealParticle(), espressopp::Particle::position(), savedImages, savedRealPositions, and espressopp::esutil::Error::setException().
Referenced by clearAdrATParticlesG(), and registerPython().
savePosition()
void espressopp::storage::Storage::savePosition (size_t id) protected
Definition at line 698 of file Storage.cpp.
References espressopp::SystemAccess::getSystem(), espressopp::SystemAccess::getSystemRef(), espressopp::Particle::image(), lookupRealParticle(), espressopp::Particle::position(), savedImages, savedRealPositions, and espressopp::esutil::Error::setException().
Referenced by clearAdrATParticlesG(), and registerPython().
scaleVolume() [1/4]
void espressopp::storage::Storage::scaleVolume (real s)
Scale Volume, only for Storage.
Scale coordinates of all real particles by factor s.
It scales only the particle coord.
Definition at line 136 of file Storage.cpp.
References espressopp::iterator::CellListIterator::isDone(), and realCells.
Referenced by espressopp::storage::DomainDecomposition::scaleVolume().
scaleVolume() [2/4]
void espressopp::storage::Storage::scaleVolume (Real3D s)
Scale Volume, only for Storage.
Scale coordinates of all real particles by factor s.
It scales only the particle coord. Anisotropic case
Anisotropic case
Definition at line 144 of file Storage.cpp.
References espressopp::iterator::CellListIterator::isDone(), and realCells.
scaleVolume() [3/4]
virtual void espressopp::storage::Storage::scaleVolume (real s, bool pS) pure virtual
Scale Volume for derived classes, pS define the particle coordinates scaling.
Implemented in espressopp::storage::DomainDecompositionAdress, and espressopp::storage::DomainDecomposition.
scaleVolume() [4/4]
virtual void espressopp::storage::Storage::scaleVolume (Real3D s, bool pS) pure virtual
Scale Volume for derived classes, pS define the particle coordinates scaling.
Anisotropic case
Implemented in espressopp::storage::DomainDecompositionAdress, and espressopp::storage::DomainDecomposition.
sendParticles()
void espressopp::storage::Storage::sendParticles (ParticleList & list, longint node) protected
send particles of a cell to another node, and empty the cell locally.
The operation is blocking: the operation will wait until the particles really have been received.
The particles are not removed from localParticles!
Definition at line 489 of file Storage.cpp.
References beforeSendParticles, espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_DEBUG, outBuffer, removeFromLocalParticles(), and espressopp::Buffer::reset().
Referenced by espressopp::storage::DomainDecomposition::decomposeRealParticles(), and espressopp::storage::DomainDecompositionAdress::decomposeRealParticles().
setFixedTuplesAdress()
void espressopp::storage::Storage::setFixedTuplesAdress (shared_ptr< FixedTupleListAdress > _fixedtupleList) inline
Definition at line 250 of file Storage.hpp.
References fixedtupleList.
Referenced by registerPython().
unpackAndAddForces()
void espressopp::storage::Storage::unpackAndAddForces (Cell & reals, class InBuffer & buf) protected virtual
unpack received ghost forces.
This one ADDS, and is most likely, what you need.
Reimplemented in espressopp::storage::DomainDecompositionAdress.
Definition at line 659 of file Storage.cpp.
References espressopp::ParticleForce::f, getFirstCell(), LOG4ESPP_DEBUG, LOG4ESPP_TRACE, espressopp::Cell::particles, and espressopp::InBuffer::read().
Referenced by espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), and espressopp::storage::DomainDecomposition::doGhostCommunication().
unpackForces()
void espressopp::storage::Storage::unpackForces (Cell & reals, class InBuffer & buf) protected
unpack received ghost forces.
This one OVERWRITES, and is probably what you don't need.
Definition at line 643 of file Storage.cpp.
References espressopp::ParticleForce::f, getFirstCell(), LOG4ESPP_DEBUG, LOG4ESPP_TRACE, espressopp::Cell::particles, and espressopp::InBuffer::read().
unpackPositionsEtc()
void espressopp::storage::Storage::unpackPositionsEtc (Cell & ghosts, class InBuffer & buf, int extradata) protected virtual
unpack received data for ghosts.
Reimplemented in espressopp::storage::DomainDecompositionAdress.
Definition at line 581 of file Storage.cpp.
References DATA_LOCAL, DATA_MOMENTUM, DATA_PROPERTIES, getFirstCell(), LOG4ESPP_DEBUG, espressopp::Cell::particles, espressopp::InBuffer::read(), and updateInLocalParticles().
Referenced by espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), and espressopp::storage::DomainDecomposition::doGhostCommunication().
updateGhosts()
virtual void espressopp::storage::Storage::updateGhosts () pure virtual
copy minimal information from the real to the ghost particles.
Typically this copies the positions and maybe the velocities from real to ghost particles. Particle order is unaffected by this method.
Storage implementations should exchange particle positions, plus data fields as indicated by dataOfUpdateGhosts.
Implemented in espressopp::storage::DomainDecompositionAdress, and espressopp::storage::DomainDecomposition.
Referenced by getFirstCell(), espressopp::integrator::VelocityVerletRESPA::updateForces(), espressopp::integrator::VelocityVerlet::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), and espressopp::integrator::PIAdressIntegrator::updateForces().
updateGhostsV()
virtual void espressopp::storage::Storage::updateGhostsV () pure virtual
Copies just velocites of real particles to their ghosts.
Needed for DPD thermostat for example.
Implemented in espressopp::storage::DomainDecompositionAdress, and espressopp::storage::DomainDecomposition.
Referenced by getFirstCell().
updateInLocalAdrATParticles()
void espressopp::storage::Storage::updateInLocalAdrATParticles (Particle * p) inline protected
Definition at line 231 of file Storage.cpp.
References espressopp::Particle::id(), and localAdrATParticles.
Referenced by addAdrATParticle(), addAdrATParticleFTPL(), removeAdrATParticle(), and updateLocalParticles().
updateInLocalParticles()
void espressopp::storage::Storage::updateInLocalParticles (Particle * p, bool weak = false) protected
Definition at line 189 of file Storage.cpp.
References espressopp::Particle::id(), localParticles, and LOG4ESPP_TRACE.
Referenced by appendIndexedParticle(), espressopp::storage::DomainDecompositionNonBlocking::irecvParticles_finish(), moveIndexedParticle(), recvParticles(), espressopp::storage::DomainDecompositionAdress::unpackPositionsEtc(), unpackPositionsEtc(), and updateLocalParticles().
updateLocalParticles()
void espressopp::storage::Storage::updateLocalParticles (ParticleList & list, bool adress = false) protected
Definition at line 235 of file Storage.cpp.
References espressopp::esutil::ESPPIterator< STLContainer >::isValid(), updateInLocalAdrATParticles(), and updateInLocalParticles().
Referenced by addAdrATParticle(), addAdrATParticleFTPL(), appendIndexedParticle(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), fetchParticles(), moveIndexedParticle(), removeAdrATParticle(), and removeParticle().
Member Data Documentation
AdrATParticles
ParticleList espressopp::storage::Storage::AdrATParticles private
Definition at line 425 of file Storage.hpp.
Referenced by addAdrATParticle(), addAdrATParticleFTPL(), getAdrATParticles(), and removeAdrATParticle().
AdrATParticlesG
std::list<ParticleList> espressopp::storage::Storage::AdrATParticlesG private
Definition at line 427 of file Storage.hpp.
Referenced by appendParticleListToGhosts(), clearAdrATParticlesG(), and getAdrATParticlesG().
afterRecvParticles
boost::signals2::signal<void (ParticleList&, class InBuffer&)> espressopp::storage::Storage::afterRecvParticles
Definition at line 241 of file Storage.hpp.
Referenced by espressopp::storage::DomainDecompositionNonBlocking::irecvParticles_finish(), and recvParticles().
beforeSendParticles
boost::signals2::signal<void (ParticleList&, class OutBuffer&)> espressopp::storage::Storage::beforeSendParticles
Definition at line 239 of file Storage.hpp.
Referenced by espressopp::storage::DomainDecompositionNonBlocking::isendParticles(), and sendParticles().
cells
LocalCellList espressopp::storage::Storage::cells protected
here the local particles are actually stored
Definition at line 391 of file Storage.hpp.
Referenced by espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::fillCells(), espressopp::storage::DomainDecompositionAdress::fillCells(), getFirstCell(), espressopp::storage::DomainDecomposition::initCellInteractions(), espressopp::storage::DomainDecompositionAdress::initCellInteractions(), espressopp::storage::DomainDecompositionAdress::mapPositionToCell(), espressopp::storage::DomainDecomposition::mapPositionToCell(), espressopp::storage::DomainDecompositionAdress::mapPositionToCellChecked(), espressopp::storage::DomainDecomposition::mapPositionToCellChecked(), espressopp::storage::DomainDecompositionAdress::mapPositionToCellClipped(), espressopp::storage::DomainDecomposition::mapPositionToCellClipped(), espressopp::storage::DomainDecomposition::markCells(), espressopp::storage::DomainDecompositionAdress::markCells(), and resizeCells().
dataOfExchangeGhosts
const int espressopp::storage::Storage::dataOfExchangeGhosts = DATA_PROPERTIES static protected
Definition at line 296 of file Storage.hpp.
Referenced by espressopp::storage::DomainDecomposition::exchangeGhosts(), and espressopp::storage::DomainDecompositionAdress::exchangeGhosts().
dataOfUpdateGhosts
const int espressopp::storage::Storage::dataOfUpdateGhosts = 0 static protected
for the moment, these are constants, defining what to transfer during ghost communications.
Definition at line 295 of file Storage.hpp.
Referenced by espressopp::storage::DomainDecomposition::updateGhosts(), and espressopp::storage::DomainDecompositionAdress::updateGhosts().
fixedtupleList
shared_ptr<FixedTupleListAdress> espressopp::storage::Storage::fixedtupleList protected
Definition at line 407 of file Storage.hpp.
Referenced by espressopp::storage::DomainDecompositionAdress::addAdrGhostForcesToReals(), espressopp::storage::DomainDecompositionAdress::copyGhostTuples(), getFixedTuples(), espressopp::storage::DomainDecompositionAdress::invalidateGhosts(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), setFixedTuplesAdress(), espressopp::storage::DomainDecompositionAdress::unpackAndAddForces(), and espressopp::storage::DomainDecompositionAdress::unpackPositionsEtc().
ghostCells
CellList espressopp::storage::Storage::ghostCells protected
list of ghost cells
Definition at line 396 of file Storage.hpp.
Referenced by espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), getGhostCells(), getNGhostParticles(), espressopp::storage::DomainDecomposition::markCells(), and espressopp::storage::DomainDecompositionAdress::markCells().
inBuffer
InBuffer espressopp::storage::Storage::inBuffer protected
Definition at line 402 of file Storage.hpp.
Referenced by espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), and recvParticles().
localAdrATParticles
boost::unordered_map<longint, Particle*> espressopp::storage::Storage::localAdrATParticles private
Definition at line 431 of file Storage.hpp.
Referenced by getNAdressParticles(), lookupAdrATParticle(), removeAdrATParticle(), and updateInLocalAdrATParticles().
localCells
CellList espressopp::storage::Storage::localCells protected
all cells on this CPU.
Just an index of the cells
Definition at line 398 of file Storage.hpp.
Referenced by espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), getLocalCells(), getNLocalParticles(), removeAllParticles(), and resizeCells().
localParticles
boost::unordered_map<longint, Particle*> espressopp::storage::Storage::localParticles private
Definition at line 421 of file Storage.hpp.
Referenced by lookupGhostParticle(), lookupLocalParticle(), lookupRealParticle(), removeAllParticles(), removeFromLocalParticles(), and updateInLocalParticles().
onParticlesChanged
boost::signals2::signal<void ()> espressopp::storage::Storage::onParticlesChanged
Ths signal will be called whenever the storage was modified such that particle pointers have become invalid, e.g.
at the end of decompose(). Classes that connect to this signal can update pointers to the particles in the call via lookupLocalParticle() and lookupRealParticle().
Definition at line 237 of file Storage.hpp.
Referenced by espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecompositionAdress::decompose(), decompose(), removeAllParticles(), and removeParticle().
onTuplesChanged
boost::signals2::signal<void ()> espressopp::storage::Storage::onTuplesChanged
Definition at line 246 of file Storage.hpp.
Referenced by espressopp::storage::DomainDecompositionAdress::decompose().
outBuffer
OutBuffer espressopp::storage::Storage::outBuffer protected
Definition at line 403 of file Storage.hpp.
Referenced by espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), and sendParticles().
realCells
CellList espressopp::storage::Storage::realCells protected
list of real cells
Definition at line 394 of file Storage.hpp.
Referenced by espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), fetchParticles(), getNRealParticles(), getRealCells(), getRealParticleIDs(), espressopp::storage::DomainDecomposition::markCells(), espressopp::storage::DomainDecompositionAdress::markCells(), and scaleVolume().
savedImages
std::map< size_t, Int3D > espressopp::storage::Storage::savedImages private
Definition at line 435 of file Storage.hpp.
Referenced by clearSavedPositions(), restorePositions(), and savePosition().
savedRealPositions
std::map< size_t, Real3D > espressopp::storage::Storage::savedRealPositions private
Definition at line 434 of file Storage.hpp.
Referenced by clearSavedPositions(), restorePositions(), and savePosition().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/storage/Storage.hpp
/home/espressopp/espressopp/src/storage/Storage.cpp