ESPResSo++: espressopp::esutil::ESPPIterator< STLContainer > Class Template Reference
espressopp::esutil::ESPPIterator< STLContainer > Class Template Reference
#include <ESPPIterator.hpp>
Public Member Functions
ESPPIterator ()
ESPPIterator (STLContainer &container)
ESPPIterator (typename STLContainer::iterator begin, typename STLContainer::iterator end)
ESPPIterator & operator++ ()
bool isValid () const
bool isDone () const
value_type & operator* () const
value_type * operator-> () const
STLContainer::iterator getSTLIterator ()
Private Types
typedef STLContainer::value_type value_type
Private Attributes
STLContainer::iterator stlIt
STLContainer::iterator stlEnd
Detailed Description
template<class STLContainer>
class espressopp::esutil::ESPPIterator< STLContainer >
Definition at line 30 of file ESPPIterator.hpp.
Member Typedef Documentation
value_type
template<class STLContainer > typedef STLContainer::value_type espressopp::esutil::ESPPIterator< STLContainer >::value_type private
Definition at line 31 of file ESPPIterator.hpp.
Constructor & Destructor Documentation
ESPPIterator() [1/3]
template<class STLContainer > espressopp::esutil::ESPPIterator< STLContainer >::ESPPIterator () inline
Definition at line 33 of file ESPPIterator.hpp.
ESPPIterator() [2/3]
template<class STLContainer > espressopp::esutil::ESPPIterator< STLContainer >::ESPPIterator (STLContainer & container) inline
Definition at line 37 of file ESPPIterator.hpp.
ESPPIterator() [3/3]
template<class STLContainer > espressopp::esutil::ESPPIterator< STLContainer >::ESPPIterator (typename STLContainer::iterator begin, typename STLContainer::iterator end) inline
Definition at line 41 of file ESPPIterator.hpp.
Member Function Documentation
getSTLIterator()
template<class STLContainer > STLContainer::iterator espressopp::esutil::ESPPIterator< STLContainer >::getSTLIterator () inline
Definition at line 54 of file ESPPIterator.hpp.
References espressopp::esutil::ESPPIterator< STLContainer >::stlIt.
isDone()
template<class STLContainer > bool espressopp::esutil::ESPPIterator< STLContainer >::isDone () const inline
Definition at line 48 of file ESPPIterator.hpp.
References espressopp::esutil::ESPPIterator< STLContainer >::isValid().
Referenced by espressopp::iterator::CellListAllPairsIterator::CellListAllPairsIterator(), espressopp::iterator::CellListIterator::findNonemptyCell(), espressopp::iterator::NeighborCellListIterator::NeighborCellListIterator(), espressopp::iterator::CellListAllPairsIterator::operator++(), and espressopp::iterator::NeighborCellListIterator::operator++().
isValid()
template<class STLContainer > bool espressopp::esutil::ESPPIterator< STLContainer >::isValid () const inline
Definition at line 47 of file ESPPIterator.hpp.
References espressopp::esutil::ESPPIterator< STLContainer >::stlEnd, and espressopp::esutil::ESPPIterator< STLContainer >::stlIt.
Referenced by espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::addForces(), espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListAdressCGInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListAdressATATInteractionTemplate< _Potential1, _Potential2 >::addForces(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::addForces(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::addForces(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::addForces(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::addForces(), espressopp::interaction::VerletListAdressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::addForces(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::addForces(), espressopp::ParticleGroup::afterRecvParticles(), espressopp::FixedLocalTupleList::beforeSendParticles(), espressopp::FixedTupleList::beforeSendParticles(), espressopp::FixedListComm::beforeSendParticles(), espressopp::FixedTupleListAdress::beforeSendParticles(), espressopp::FixedSingleList::beforeSendParticles(), espressopp::FixedPairDistList::beforeSendParticles(), espressopp::FixedTripleList::beforeSendParticles(), espressopp::FixedQuadrupleList::beforeSendParticles(), espressopp::FixedTripleAngleList::beforeSendParticles(), espressopp::FixedQuadrupleAngleList::beforeSendParticles(), espressopp::FixedPairList::beforeSendParticles(), espressopp::ParticleGroup::beforeSendParticles(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeEnergy(), espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListAdressCGInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeEnergy(), espressopp::interaction::VerletListAdressATATInteractionTemplate< _Potential1, _Potential2 >::computeEnergy(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeEnergy(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeEnergy(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergy(), espressopp::interaction::VerletListAdressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeEnergy(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeEnergy(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergyAA(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeEnergyAA(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergyAA(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeEnergyCG(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeEnergyCG(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeEnergyCG(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeEnergyDeriv(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirial(), espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirial(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirial(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeVirial(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirialTensor(), espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::VerletListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialTensor(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialTensor(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialX(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialX(), espressopp::storage::Storage::fetchParticles(), espressopp::esutil::ESPPIterator< STLContainer >::isDone(), espressopp::storage::DomainDecompositionNonBlocking::isendParticles(), espressopp::iterator::CellListAllPairsIterator::isValid(), espressopp::integrator::AssociationReaction::react(), espressopp::storage::Storage::sendParticles(), espressopp::integrator::DPDThermostat::thermalize(), and espressopp::storage::Storage::updateLocalParticles().
operator*()
template<class STLContainer > value_type& espressopp::esutil::ESPPIterator< STLContainer >::operator* () const inline
Definition at line 50 of file ESPPIterator.hpp.
References espressopp::esutil::ESPPIterator< STLContainer >::stlIt.
operator++()
template<class STLContainer > ESPPIterator& espressopp::esutil::ESPPIterator< STLContainer >::operator++ () inline
Definition at line 46 of file ESPPIterator.hpp.
References espressopp::esutil::ESPPIterator< STLContainer >::stlIt.
operator->()
template<class STLContainer > value_type* espressopp::esutil::ESPPIterator< STLContainer >::operator-> () const inline
Definition at line 51 of file ESPPIterator.hpp.
Member Data Documentation
stlEnd
template<class STLContainer > STLContainer::iterator espressopp::esutil::ESPPIterator< STLContainer >::stlEnd private
Definition at line 58 of file ESPPIterator.hpp.
Referenced by espressopp::esutil::ESPPIterator< STLContainer >::isValid().
stlIt
template<class STLContainer > STLContainer::iterator espressopp::esutil::ESPPIterator< STLContainer >::stlIt private
Definition at line 57 of file ESPPIterator.hpp.
Referenced by espressopp::esutil::ESPPIterator< STLContainer >::getSTLIterator(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::esutil::ESPPIterator< STLContainer >::operator*(), and espressopp::esutil::ESPPIterator< STLContainer >::operator++().
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/esutil/ESPPIterator.hpp