ESPResSo++: espressopp::esutil::Array2D< T, outlier_mode > Class Template Reference
espressopp::esutil::Array2D< T, outlier_mode > Class Template Reference
A two-dimensional array (i.e.
#include <Array2D.hpp>
Public Types
typedef T value_type
The type of object, T, stored in the Array1D.
typedef T & reference
Reference to to a T object.
typedef const T & const_reference
Const reference to to a T object.
typedef Super::size_type size_type
An unsigned integer type.
typedef Super::iterator iterator
Iterator used to iterate through an Array1D.
typedef Super::const_iterator const_iterator
Const-iterator used to iterate through an Array1D.
Public Member Functions
Array2D ()
Default constructor.
Array2D (size_type n, size_type m, const T &t=T())
Creates a two-dimensional n x m array, initialising the values with copies of t.
void clear ()
Erases all elements.
void init (size_type n, size_type m, const T &t=T())
Creates a two-dimensional n x m array, initialising the values with copies of t.
void resize (size_type n, size_type m, const T &t=T())
Changes the size of the Array2D so that the size becomes n x m.
size_type size_n () const
Returns the n -size of the array.
size_type size_x () const
Returns the n -size of the array.
size_type size_m () const
Returns the m -size of the array.
size_type size_y () const
Returns the m -size of the array.
bool empty () const
true if the Array2D's size is 0 x 0.
reference operator() (size_type i, size_type j)
Returns the element at position i x j.
const_reference operator() (size_type i, size_type j) const
Returns the element at position i x j.
template<class Vector >
reference operator() (const Vector &pos)
Returns the element at position pos.
template<class Vector >
const_reference operator() (const Vector &pos) const
Returns the element at position pos.
reference at (size_type i, size_type j)
Returns the element at position i x j.
const_reference at (size_type i, size_type j) const
Returns the element at position i x j.
template<class Vector >
reference at (const Vector &pos)
Returns the element at position pos.
template<class Vector >
const_reference at (const Vector &pos) const
Returns the element at position pos.
iterator begin ()
Returns an iterator pointing to the beginning of the Array2D.
const_iterator begin () const
Returns a const_iterator pointing to the beginning of the Array2D.
iterator end ()
Returns an iterator pointing to the end of the Array2D.
const_iterator end () const
Returns a const_iterator pointing to the end of the Array2D.
template<class T2 >
void operator= (const T2 &t2)
Assigns t2 to each of the elements.
template<class T2 >
void operator+= (const T2 &t2)
Adds t2 to each of the elements.
template<class T2 >
void operator-= (const T2 &t2)
Adds t2 to each of the elements.
template<class T2 >
void operator*= (const T2 &t2)
Multiplies each of the elements by t2.
template<class T2 >
void operator/= (const T2 &t2)
Divides each of the elements by t2.
void operator/= (const double &x)
bool operator== (const Array2D< T, exception > &a)
Equality operator.
bool operator!= (const Array2D< T, exception > &a)
Inequality operator.
Private Types
typedef Array2D< T > Self
typedef std::vector< T > Super
The super class of the array (i.e.
Private Attributes
size_type n
The n size of the n x m array.
size_type m
The m size of the n x m array.
Detailed Description
template<class T, OutlierMode outlier_mode = exception>
class espressopp::esutil::Array2D< T, outlier_mode >
A two-dimensional array (i.e.
a matrix).
Parameters
T The type of the object stored in the array.
Example:
// create the 10x10 id matrix
Array2D< double > I(10, 10, 0.0);
for (int i = 0; i < 10; i++) I(i, i) = 1.0;
Definition at line 44 of file Array2D.hpp.
Member Typedef Documentation
const_iterator
template<class T, OutlierMode outlier_mode = exception> typedef Super::const_iterator espressopp::esutil::Array2D< T, outlier_mode >::const_iterator
Const-iterator used to iterate through an Array1D.
Definition at line 61 of file Array2D.hpp.
const_reference
template<class T, OutlierMode outlier_mode = exception> typedef const T& espressopp::esutil::Array2D< T, outlier_mode >::const_reference
Const reference to to a T object.
Definition at line 55 of file Array2D.hpp.
iterator
template<class T, OutlierMode outlier_mode = exception> typedef Super::iterator espressopp::esutil::Array2D< T, outlier_mode >::iterator
Iterator used to iterate through an Array1D.
Definition at line 59 of file Array2D.hpp.
reference
template<class T, OutlierMode outlier_mode = exception> typedef T& espressopp::esutil::Array2D< T, outlier_mode >::reference
Reference to to a T object.
Definition at line 53 of file Array2D.hpp.
Self
template<class T, OutlierMode outlier_mode = exception> typedef Array2D< T > espressopp::esutil::Array2D< T, outlier_mode >::Self private
Definition at line 45 of file Array2D.hpp.
size_type
template<class T, OutlierMode outlier_mode = exception> typedef Super::size_type espressopp::esutil::Array2D< T, outlier_mode >::size_type
An unsigned integer type.
Definition at line 57 of file Array2D.hpp.
Super
template<class T, OutlierMode outlier_mode = exception> typedef std::vector< T > espressopp::esutil::Array2D< T, outlier_mode >::Super private
The super class of the array (i.e.
vector<T>).
Definition at line 47 of file Array2D.hpp.
value_type
template<class T, OutlierMode outlier_mode = exception> typedef T espressopp::esutil::Array2D< T, outlier_mode >::value_type
The type of object, T, stored in the Array1D.
Definition at line 51 of file Array2D.hpp.
Constructor & Destructor Documentation
Array2D() [1/2]
template<class T, OutlierMode outlier_mode = exception> espressopp::esutil::Array2D< T, outlier_mode >::Array2D () inline
Default constructor.
Definition at line 64 of file Array2D.hpp.
Array2D() [2/2]
template<class T, OutlierMode outlier_mode = exception> espressopp::esutil::Array2D< T, outlier_mode >::Array2D (size_type n, size_type m, const T & t = T()) inline
Creates a two-dimensional n x m array, initialising the values with copies of t.
Definition at line 68 of file Array2D.hpp.
Member Function Documentation
at() [1/4]
template<class T, OutlierMode outlier_mode = exception> reference espressopp::esutil::Array2D< T, outlier_mode >::at (size_type i, size_type j) inline
Returns the element at position i x j.
Exceptions
out_of_range i is out of range of the Array2D
Definition at line 144 of file Array2D.hpp.
Referenced by espressopp::interaction::VerletListInteractionTemplate< _Potential >::addForces(), espressopp::esutil::Array2D< PotentialCG, esutil::enlarge >::at(), espressopp::esutil::Array2D< T, enlarge >::at(), espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::getPotential(), espressopp::interaction::VerletListInteractionTemplate< _Potential >::getPotential(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::getPotential(), espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::getPotential(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::getPotential(), espressopp::interaction::VerletListAdressCGInteractionTemplate< _Potential >::getPotential(), espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::getPotential(), espressopp::vectorization::interaction::VerletListLennardJones::getPotential(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::getPotential(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getPotential1(), espressopp::interaction::VerletListAdressATATInteractionTemplate< _Potential1, _Potential2 >::getPotential1(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getPotential2(), espressopp::interaction::VerletListAdressATATInteractionTemplate< _Potential1, _Potential2 >::getPotential2(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::getPotentialAT(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::getPotentialAT(), espressopp::interaction::VerletListAdressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialAT1(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialAT1(), espressopp::interaction::VerletListAdressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialAT2(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialAT2(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::getPotentialCG(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::getPotentialCG(), espressopp::interaction::VerletListAdressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialCG(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialCG(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getPotentialCL(), espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::getPotentialPtr(), espressopp::interaction::VerletListInteractionTemplate< _Potential >::getPotentialPtr(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::getPotentialPtr(), espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::getPotentialPtr(), espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::getPotentialPtr(), espressopp::interaction::VerletListAdressCGInteractionTemplate< _Potential >::getPotentialPtr(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::getPotentialPtr(), espressopp::vectorization::interaction::VerletListLennardJones::getPotentialPtr(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::getPotentialQM(), espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::setPotential(), espressopp::interaction::VerletListInteractionTemplate< _Potential >::setPotential(), espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::setPotential(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::setPotential(), espressopp::interaction::VerletListAdressATInteractionTemplate< _Potential >::setPotential(), espressopp::interaction::VerletListHadressATInteractionTemplate< _Potential >::setPotential(), espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::setPotential(), espressopp::interaction::VerletListAdressCGInteractionTemplate< _Potential >::setPotential(), espressopp::vectorization::interaction::VerletListLennardJones::setPotential(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::setPotential(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::setPotential1(), espressopp::interaction::VerletListAdressATATInteractionTemplate< _Potential1, _Potential2 >::setPotential1(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::setPotential2(), espressopp::interaction::VerletListAdressATATInteractionTemplate< _Potential1, _Potential2 >::setPotential2(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::setPotentialAT(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::setPotentialAT(), espressopp::interaction::VerletListAdressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::setPotentialAT1(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::setPotentialAT1(), espressopp::interaction::VerletListAdressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::setPotentialAT2(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::setPotentialAT2(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::setPotentialCG(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::setPotentialCG(), espressopp::interaction::VerletListAdressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::setPotentialCG(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::setPotentialCG(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::setPotentialCL(), and espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::setPotentialQM().
at() [2/4]
template<class T, OutlierMode outlier_mode = exception> const_reference espressopp::esutil::Array2D< T, outlier_mode >::at (size_type i, size_type j) const inline
Returns the element at position i x j.
Exceptions
out_of_range i is out of range of the Array2D
Definition at line 152 of file Array2D.hpp.
at() [3/4]
template<class T, OutlierMode outlier_mode = exception> template<class Vector > reference espressopp::esutil::Array2D< T, outlier_mode >::at (const Vector & pos) inline
Returns the element at position pos.
pos must be a vector where the expressions pos[0] and pos[1] return the first and second element.
Exceptions
out_of_range i is out of range of the Array2D
Definition at line 165 of file Array2D.hpp.
at() [4/4]
template<class T, OutlierMode outlier_mode = exception> template<class Vector > const_reference espressopp::esutil::Array2D< T, outlier_mode >::at (const Vector & pos) const inline
Returns the element at position pos.
pos must be a vector where the expressions pos[0] and pos[1] return the first and second element.
Exceptions
out_of_range i is out of range of the Array2D
Definition at line 175 of file Array2D.hpp.
begin() [1/2]
template<class T, OutlierMode outlier_mode = exception> iterator espressopp::esutil::Array2D< T, outlier_mode >::begin () inline
Returns an iterator pointing to the beginning of the Array2D.
Definition at line 180 of file Array2D.hpp.
Referenced by espressopp::esutil::Array2D< PotentialCG, esutil::enlarge >::operator*=(), espressopp::esutil::Array2D< PotentialCG, esutil::enlarge >::operator+=(), espressopp::esutil::Array2D< PotentialCG, esutil::enlarge >::operator-=(), espressopp::esutil::Array2D< PotentialCG, esutil::enlarge >::operator/=(), and espressopp::esutil::Array2D< PotentialCG, esutil::enlarge >::operator=().
begin() [2/2]
template<class T, OutlierMode outlier_mode = exception> const_iterator espressopp::esutil::Array2D< T, outlier_mode >::begin () const inline
Returns a const_iterator pointing to the beginning of the Array2D.
Definition at line 184 of file Array2D.hpp.
clear()
template<class T, OutlierMode outlier_mode = exception> void espressopp::esutil::Array2D< T, outlier_mode >::clear () inline
Erases all elements.
Definition at line 72 of file Array2D.hpp.
Referenced by espressopp::esutil::Array2D< PotentialCG, esutil::enlarge >::Array2D().
empty()
template<class T, OutlierMode outlier_mode = exception> bool espressopp::esutil::Array2D< T, outlier_mode >::empty () const inline
true if the Array2D's size is 0 x 0.
Definition at line 112 of file Array2D.hpp.
end() [1/2]
template<class T, OutlierMode outlier_mode = exception> iterator espressopp::esutil::Array2D< T, outlier_mode >::end () inline
Returns an iterator pointing to the end of the Array2D.
Definition at line 188 of file Array2D.hpp.
Referenced by espressopp::esutil::Array2D< PotentialCG, esutil::enlarge >::operator*=(), espressopp::esutil::Array2D< PotentialCG, esutil::enlarge >::operator+=(), espressopp::esutil::Array2D< PotentialCG, esutil::enlarge >::operator-=(), espressopp::esutil::Array2D< PotentialCG, esutil::enlarge >::operator/=(), and espressopp::esutil::Array2D< PotentialCG, esutil::enlarge >::operator=().
end() [2/2]
template<class T, OutlierMode outlier_mode = exception> const_iterator espressopp::esutil::Array2D< T, outlier_mode >::end () const inline
Returns a const_iterator pointing to the end of the Array2D.
Definition at line 192 of file Array2D.hpp.
init()
template<class T, OutlierMode outlier_mode = exception> void espressopp::esutil::Array2D< T, outlier_mode >::init (size_type n, size_type m, const T & t = T()) inline
Creates a two-dimensional n x m array, initialising the values with copies of t.
Definition at line 80 of file Array2D.hpp.
Referenced by espressopp::esutil::Array2D< PotentialCG, esutil::enlarge >::Array2D(), and espressopp::esutil::Array2D< T, enlarge >::Array2D().
operator!=()
template<class T, OutlierMode outlier_mode = exception> bool espressopp::esutil::Array2D< T, outlier_mode >::operator!= (const Array2D< T, exception > & a) inline
Inequality operator.
Definition at line 234 of file Array2D.hpp.
operator()() [1/4]
template<class T, OutlierMode outlier_mode = exception> reference espressopp::esutil::Array2D< T, outlier_mode >::operator() (size_type i, size_type j) inline
Returns the element at position i x j.
Attention
No range checking.
Definition at line 116 of file Array2D.hpp.
Referenced by espressopp::esutil::Array2D< PotentialCG, esutil::enlarge >::at(), and espressopp::esutil::Array2D< PotentialCG, esutil::enlarge >::operator()().
operator()() [2/4]
template<class T, OutlierMode outlier_mode = exception> const_reference espressopp::esutil::Array2D< T, outlier_mode >::operator() (size_type i, size_type j) const inline
Returns the element at position i x j.
Attention
No range checking.
Definition at line 121 of file Array2D.hpp.
operator()() [3/4]
template<class T, OutlierMode outlier_mode = exception> template<class Vector > reference espressopp::esutil::Array2D< T, outlier_mode >::operator() (const Vector & pos) inline
Returns the element at position pos.
pos must be a vector where the expressions pos[0] and pos[1] return the indices.
Attention
No range checking.
Definition at line 130 of file Array2D.hpp.
operator()() [4/4]
template<class T, OutlierMode outlier_mode = exception> template<class Vector > const_reference espressopp::esutil::Array2D< T, outlier_mode >::operator() (const Vector & pos) const inline
Returns the element at position pos.
pos must be a vector where the expressions pos[0] and pos[1] return the indices.
Attention
No range checking.
Definition at line 139 of file Array2D.hpp.
operator*=()
template<class T, OutlierMode outlier_mode = exception> template<class T2 > void espressopp::esutil::Array2D< T, outlier_mode >::operator*= (const T2 & t2) inline
Multiplies each of the elements by t2.
Definition at line 214 of file Array2D.hpp.
operator+=()
template<class T, OutlierMode outlier_mode = exception> template<class T2 > void espressopp::esutil::Array2D< T, outlier_mode >::operator+= (const T2 & t2) inline
Adds t2 to each of the elements.
Definition at line 202 of file Array2D.hpp.
operator-=()
template<class T, OutlierMode outlier_mode = exception> template<class T2 > void espressopp::esutil::Array2D< T, outlier_mode >::operator-= (const T2 & t2) inline
Adds t2 to each of the elements.
Definition at line 208 of file Array2D.hpp.
operator/=() [1/2]
template<class T, OutlierMode outlier_mode = exception> template<class T2 > void espressopp::esutil::Array2D< T, outlier_mode >::operator/= (const T2 & t2) inline
Divides each of the elements by t2.
Definition at line 219 of file Array2D.hpp.
operator/=() [2/2]
template<class T, OutlierMode outlier_mode = exception> void espressopp::esutil::Array2D< T, outlier_mode >::operator/= (const double & x) inline
Definition at line 222 of file Array2D.hpp.
operator=()
template<class T, OutlierMode outlier_mode = exception> template<class T2 > void espressopp::esutil::Array2D< T, outlier_mode >::operator= (const T2 & t2) inline
Assigns t2 to each of the elements.
Definition at line 196 of file Array2D.hpp.
operator==()
template<class T, OutlierMode outlier_mode = exception> bool espressopp::esutil::Array2D< T, outlier_mode >::operator== (const Array2D< T, exception > & a) inline
Equality operator.
Definition at line 228 of file Array2D.hpp.
resize()
template<class T, OutlierMode outlier_mode = exception> void espressopp::esutil::Array2D< T, outlier_mode >::resize (size_type n, size_type m, const T & t = T()) inline
Changes the size of the Array2D so that the size becomes n x m.
Attention
The elements of the Array2D are not initialised consistently, so the values are undefined. The t parameter exists only for the purpose to provide a default T value when new elements are created and needs to be specified only when T has no default constructor.
Definition at line 95 of file Array2D.hpp.
Referenced by espressopp::esutil::Array2D< PotentialCG, esutil::enlarge >::init().
size_m()
template<class T, OutlierMode outlier_mode = exception> size_type espressopp::esutil::Array2D< T, outlier_mode >::size_m () const inline
Returns the m -size of the array.
Definition at line 107 of file Array2D.hpp.
Referenced by espressopp::esutil::Array2D< T, enlarge >::at(), espressopp::vectorization::interaction::VerletListLennardJones::getPotential(), and espressopp::vectorization::interaction::VerletListLennardJones::rebuildPotential().
size_n()
template<class T, OutlierMode outlier_mode = exception> size_type espressopp::esutil::Array2D< T, outlier_mode >::size_n () const inline
Returns the n -size of the array.
Definition at line 102 of file Array2D.hpp.
Referenced by espressopp::esutil::Array2D< T, enlarge >::at(), espressopp::vectorization::interaction::VerletListLennardJones::getPotential(), and espressopp::vectorization::interaction::VerletListLennardJones::rebuildPotential().
size_x()
template<class T, OutlierMode outlier_mode = exception> size_type espressopp::esutil::Array2D< T, outlier_mode >::size_x () const inline
Returns the n -size of the array.
Definition at line 104 of file Array2D.hpp.
size_y()
template<class T, OutlierMode outlier_mode = exception> size_type espressopp::esutil::Array2D< T, outlier_mode >::size_y () const inline
Returns the m -size of the array.
Definition at line 109 of file Array2D.hpp.
Member Data Documentation
m
template<class T, OutlierMode outlier_mode = exception> size_type espressopp::esutil::Array2D< T, outlier_mode >::m private
The m size of the n x m array.
Definition at line 243 of file Array2D.hpp.
Referenced by espressopp::esutil::Array2D< PotentialCG, esutil::enlarge >::resize(), espressopp::esutil::Array2D< PotentialCG, esutil::enlarge >::size_m(), and espressopp::esutil::Array2D< PotentialCG, esutil::enlarge >::size_y().
n
template<class T, OutlierMode outlier_mode = exception> size_type espressopp::esutil::Array2D< T, outlier_mode >::n private
The n size of the n x m array.
Definition at line 241 of file Array2D.hpp.
Referenced by espressopp::esutil::Array2D< PotentialCG, esutil::enlarge >::resize(), espressopp::esutil::Array2D< PotentialCG, esutil::enlarge >::size_n(), and espressopp::esutil::Array2D< PotentialCG, esutil::enlarge >::size_x().
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/esutil/Array2D.hpp