ESPResSo++: espressopp::interaction::VerletListInteractionTemplate< _Potential > Class Template Reference
espressopp::interaction::VerletListInteractionTemplate< _Potential > Class Template Reference
#include <VerletListInteractionTemplate.hpp>
Public Member Functions
VerletListInteractionTemplate (shared_ptr< VerletList > _verletList)
virtual ~VerletListInteractionTemplate ()
void setVerletList (shared_ptr< VerletList > _verletList)
shared_ptr< VerletList > getVerletList ()
void setPotential (int type1, int type2, const Potential &potential)
Potential & getPotential (int type1, int type2)
shared_ptr< Potential > getPotentialPtr (int type1, int type2)
virtual void addForces ()
virtual real computeEnergy ()
virtual real computeEnergyDeriv ()
virtual real computeEnergyAA ()
virtual real computeEnergyCG ()
virtual void computeVirialX (std::vector< real > &p_xx_total, int bins)
virtual real computeVirial ()
virtual void computeVirialTensor (Tensor &w)
virtual void computeVirialTensor (Tensor &w, real z)
virtual void computeVirialTensor (Tensor *w, int n)
virtual real getMaxCutoff ()
This method returns the maximal cutoff defined for one type pair.
virtual int bondType ()
Static Public Member Functions
static void registerPython ()
Protected Types
typedef _Potential Potential
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Protected Attributes
int ntypes
shared_ptr< VerletList > verletList
esutil::Array2D< Potential,
esutil::enlarge > potentialArray
Detailed Description
template<typename _Potential>
class espressopp::interaction::VerletListInteractionTemplate< _Potential >
Definition at line 44 of file VerletListInteractionTemplate.hpp.
Member Typedef Documentation
template<typename _Potential > typedef _Potential espressopp::interaction::VerletListInteractionTemplate< _Potential >::Potential protected
Definition at line 47 of file VerletListInteractionTemplate.hpp.
Constructor & Destructor Documentation
template<typename _Potential > espressopp::interaction::VerletListInteractionTemplate< _Potential >::VerletListInteractionTemplate (shared_ptr< VerletList > _verletList) inline
Definition at line 51 of file VerletListInteractionTemplate.hpp.
References espressopp::interaction::VerletListInteractionTemplate< _Potential >::ntypes, and espressopp::interaction::VerletListInteractionTemplate< _Potential >::potentialArray.
template<typename _Potential > virtual espressopp::interaction::VerletListInteractionTemplate< _Potential >::~VerletListInteractionTemplate () inline virtual
Definition at line 57 of file VerletListInteractionTemplate.hpp.
Member Function Documentation
template<typename _Potential > void espressopp::interaction::VerletListInteractionTemplate< _Potential >::addForces () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 116 of file VerletListInteractionTemplate.hpp.
References espressopp::Particle::force(), espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_DEBUG, LOG4ESPP_TRACE, and espressopp::Particle::type().
template<typename _Potential > virtual int espressopp::interaction::VerletListInteractionTemplate< _Potential >::bondType () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 102 of file VerletListInteractionTemplate.hpp.
References espressopp::interaction::Nonbonded.
template<typename _Potential > real espressopp::interaction::VerletListInteractionTemplate< _Potential >::computeEnergy () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 140 of file VerletListInteractionTemplate.hpp.
References espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_DEBUG, LOG4ESPP_TRACE, and espressopp::Particle::type().
template<typename _Potential > real espressopp::interaction::VerletListInteractionTemplate< _Potential >::computeEnergyAA () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 173 of file VerletListInteractionTemplate.hpp.
References LOG4ESPP_WARN.
template<typename _Potential > real espressopp::interaction::VerletListInteractionTemplate< _Potential >::computeEnergyCG () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 180 of file VerletListInteractionTemplate.hpp.
References LOG4ESPP_WARN.
template<typename _Potential > real espressopp::interaction::VerletListInteractionTemplate< _Potential >::computeEnergyDeriv () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 166 of file VerletListInteractionTemplate.hpp.
References LOG4ESPP_WARN.
template<typename _Potential > real espressopp::interaction::VerletListInteractionTemplate< _Potential >::computeVirial () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 194 of file VerletListInteractionTemplate.hpp.
References espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_DEBUG, mpiWorld, espressopp::Particle::position(), and espressopp::Particle::type().
template<typename _Potential > void espressopp::interaction::VerletListInteractionTemplate< _Potential >::computeVirialTensor (Tensor & w) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 223 of file VerletListInteractionTemplate.hpp.
References espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_DEBUG, mpiWorld, espressopp::Particle::position(), and espressopp::Particle::type().
template<typename _Potential > void espressopp::interaction::VerletListInteractionTemplate< _Potential >::computeVirialTensor (Tensor & w, real z) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 253 of file VerletListInteractionTemplate.hpp.
References espressopp::System::bc, espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_DEBUG, mpiWorld, espressopp::Particle::position(), and espressopp::Particle::type().
template<typename _Potential > void espressopp::interaction::VerletListInteractionTemplate< _Potential >::computeVirialTensor (Tensor * w, int n) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 310 of file VerletListInteractionTemplate.hpp.
References espressopp::System::bc, espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_DEBUG, mpiWorld, espressopp::Particle::position(), and espressopp::Particle::type().
template<typename _Potential > void espressopp::interaction::VerletListInteractionTemplate< _Potential >::computeVirialX (std::vector< real > & p_xx_total, int bins) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 188 of file VerletListInteractionTemplate.hpp.
References LOG4ESPP_WARN.
template<typename _Potential > real espressopp::interaction::VerletListInteractionTemplate< _Potential >::getMaxCutoff () inline virtual
This method returns the maximal cutoff defined for one type pair.
Implements espressopp::interaction::Interaction.
Definition at line 384 of file VerletListInteractionTemplate.hpp.
template<typename _Potential > Potential& espressopp::interaction::VerletListInteractionTemplate< _Potential >::getPotential (int type1, int type2) inline
Definition at line 81 of file VerletListInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), and espressopp::interaction::VerletListInteractionTemplate< _Potential >::potentialArray.
template<typename _Potential > shared_ptr<Potential> espressopp::interaction::VerletListInteractionTemplate< _Potential >::getPotentialPtr (int type1, int type2) inline
Definition at line 86 of file VerletListInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), and espressopp::interaction::VerletListInteractionTemplate< _Potential >::potentialArray.
template<typename _Potential > shared_ptr<VerletList> espressopp::interaction::VerletListInteractionTemplate< _Potential >::getVerletList () inline
Definition at line 64 of file VerletListInteractionTemplate.hpp.
References espressopp::interaction::VerletListInteractionTemplate< _Potential >::verletList.
static espressopp::interaction::Interaction::LOG4ESPP_DECL_LOGGER (theLogger) static protected inherited
Logger.
void espressopp::interaction::Interaction::registerPython () static inherited
Definition at line 36 of file Interaction.cpp.
References espressopp::interaction::Interaction::bondType(), espressopp::interaction::Interaction::computeEnergy(), espressopp::interaction::Interaction::computeEnergyAA(), espressopp::interaction::Interaction::computeEnergyCG(), espressopp::interaction::Interaction::computeEnergyDeriv(), and espressopp::interaction::Interaction::computeVirial().
Referenced by espressopp::interaction::registerPython().
template<typename _Potential > void espressopp::interaction::VerletListInteractionTemplate< _Potential >::setPotential (int type1, int type2, const Potential & potential) inline
Definition at line 69 of file VerletListInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), LOG4ESPP_INFO, espressopp::interaction::VerletListInteractionTemplate< _Potential >::ntypes, and espressopp::interaction::VerletListInteractionTemplate< _Potential >::potentialArray.
template<typename _Potential > void espressopp::interaction::VerletListInteractionTemplate< _Potential >::setVerletList (shared_ptr< VerletList > _verletList) inline
Definition at line 60 of file VerletListInteractionTemplate.hpp.
References espressopp::interaction::VerletListInteractionTemplate< _Potential >::verletList.
Member Data Documentation
template<typename _Potential > int espressopp::interaction::VerletListInteractionTemplate< _Potential >::ntypes protected
Definition at line 105 of file VerletListInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListInteractionTemplate< _Potential >::setPotential(), and espressopp::interaction::VerletListInteractionTemplate< _Potential >::VerletListInteractionTemplate().
template<typename _Potential > esutil::Array2D<Potential, esutil::enlarge> espressopp::interaction::VerletListInteractionTemplate< _Potential >::potentialArray protected
Definition at line 107 of file VerletListInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListInteractionTemplate< _Potential >::getPotential(), espressopp::interaction::VerletListInteractionTemplate< _Potential >::getPotentialPtr(), espressopp::interaction::VerletListInteractionTemplate< _Potential >::setPotential(), and espressopp::interaction::VerletListInteractionTemplate< _Potential >::VerletListInteractionTemplate().
template<typename _Potential > shared_ptr<VerletList> espressopp::interaction::VerletListInteractionTemplate< _Potential >::verletList protected
Definition at line 106 of file VerletListInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListInteractionTemplate< _Potential >::getVerletList(), and espressopp::interaction::VerletListInteractionTemplate< _Potential >::setVerletList().
The documentation for this class was generated from the following file:
/home/travis/build/espressopp/espressopp/src/interaction/VerletListInteractionTemplate.hpp