ESPResSo++: espressopp::vectorization::VerletList Class Reference
espressopp::vectorization::VerletList Class Reference
Class that builds and stores verlet lists.
#include <VerletList.hpp>
Classes
struct NeighborList
Hierarchical storage of chunk indices.
Public Member Functions
VerletList (shared_ptr< System >, shared_ptr< Vectorization >, real cut, bool rebuildVL)
Build a verlet list of all particle pairs stored in Vectorization whose distance is less than a given cutoff.
~VerletList ()
PairList & getPairs ()
NeighborList & getNeighborList ()
ParticleArray & getParticleArray ()
python::tuple getPair (int i)
std::uint64_t getMaxType ()
real getVerletCutoff ()
void connect ()
void disconnect ()
void rebuildPairs ()
Rebuilds the non-vectorized Verlet list vlPairs for back-compatibility with analysis.
void rebuild ()
int totalSize () const
Get the total number of pairs for the Verlet list.
int localSize () const
bool exclude (longint pid1, longint pid2)
Add pairs to exclusion list.
int getBuilds () const
Get the number of times the Verlet list has been rebuilt.
void setBuilds (int _builds)
Set the number of times the Verlet list has been rebuilt.
void resetTimers ()
void loadTimers (real *t)
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
Register this class so it can be used from Python.
Protected Member Functions
void checkPair (Particle &pt1, Particle &pt2)
template<bool VEC_MODE_AOS, bool PACK_NEIGHBORS>
void rebuild_p_nc_pack_stencil ()
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Attributes
shared_ptr< Vectorization > vec
int num_pairs = 0
AlignedVector< int > c_j
AlignedVector< real > c_x
AlignedVector< real > c_y
AlignedVector< real > c_z
PairList vlPairs
NeighborList neighborList
boost::unordered_set< std::pair< longint, longint > > exList
std::uint64_t max_type
real cutsq
real cut
real cutVerlet
int builds
boost::signals2::connection connectionResort
esutil::WallTimer timer
real timeRebuild
Private Attributes
weak_ptr< System > mySystem
Weak pointer to the system guarantees that system will be freed.
weak_ptr< System > mySystem1
weak_ptr< System > mySystem2
Detailed Description
Class that builds and stores verlet lists.
ToDo: register at system for rebuild
Definition at line 47 of file VerletList.hpp.
Constructor & Destructor Documentation
VerletList()
espressopp::vectorization::VerletList::VerletList (shared_ptr< System > system, shared_ptr< Vectorization > vec, real cut, bool rebuildVL)
Build a verlet list of all particle pairs stored in Vectorization whose distance is less than a given cutoff.
Parameters
system is the system for which the verlet list is built
cut is the cutoff value for the
Definition at line 45 of file VerletList.cpp.
References builds, connectionResort, cut, cutsq, cutVerlet, LOG4ESPP_INFO, max_type, rebuild(), and resetTimers().
~VerletList()
espressopp::vectorization::VerletList::~VerletList ()
Definition at line 549 of file VerletList.cpp.
References connectionResort, and LOG4ESPP_INFO.
Member Function Documentation
checkPair()
void espressopp::vectorization::VerletList::checkPair (Particle & pt1, Particle & pt2) protected
Definition at line 487 of file VerletList.cpp.
References espressopp::PairList::add(), cutsq, exList, espressopp::Particle::id(), LOG4ESPP_TRACE, max_type, espressopp::Particle::position(), espressopp::Real3D::sqr(), espressopp::Particle::type(), and vlPairs.
Referenced by rebuildPairs().
connect()
void espressopp::vectorization::VerletList::connect ()
Definition at line 73 of file VerletList.cpp.
References connectionResort, espressopp::SystemAccess::getSystem(), and rebuild().
Referenced by registerPython().
disconnect()
void espressopp::vectorization::VerletList::disconnect ()
Definition at line 81 of file VerletList.cpp.
References connectionResort.
Referenced by registerPython().
exclude()
bool espressopp::vectorization::VerletList::exclude (longint pid1, longint pid2)
Add pairs to exclusion list.
Definition at line 537 of file VerletList.cpp.
References exList.
Referenced by registerPython().
getBuilds()
int espressopp::vectorization::VerletList::getBuilds () const inline
Get the number of times the Verlet list has been rebuilt.
Definition at line 119 of file VerletList.hpp.
References builds.
Referenced by registerPython().
getMaxType()
std::uint64_t espressopp::vectorization::VerletList::getMaxType () inline
Definition at line 96 of file VerletList.hpp.
References max_type.
getNeighborList()
NeighborList& espressopp::vectorization::VerletList::getNeighborList () inline
Definition at line 90 of file VerletList.hpp.
References neighborList.
getPair()
python::tuple espressopp::vectorization::VerletList::getPair (int i)
Definition at line 527 of file VerletList.cpp.
References vlPairs.
Referenced by registerPython().
getPairs()
PairList& espressopp::vectorization::VerletList::getPairs () inline
Definition at line 88 of file VerletList.hpp.
References vlPairs.
getParticleArray()
ParticleArray & espressopp::vectorization::VerletList::getParticleArray ()
Definition at line 90 of file VerletList.cpp.
References vec.
Referenced by rebuild().
getSystem()
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::VerletList::_rebuildUsingBuffers(), espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::LatticeBoltzmann::assignMyLattice(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::vectorization::Vectorization::befCalcForces(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::vectorization::Vectorization::connect(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpXTCAdress::dump(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::io::DumpXYZ::DumpXYZ(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), rebuild(), rebuild_p_nc_pack_stencil(), rebuildPairs(), espressopp::VerletListTriple::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::VerletList::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::vectorization::Vectorization::resetCells(), espressopp::vectorization::Vectorization::resetParticles(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::vectorization::Vectorization::updateForces(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
getSystem1()
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
getSystem2()
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
getSystemRef()
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerletRESPA::calcForces(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeCOM(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::FixedLocalTupleComListInteractionTemplate(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::VelocityVerletRESPA::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::VelocityVerletRESPA::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::VelocityVerletRESPA::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::Adress::integrateSlow(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::VelocityVerletRESPA::run(), espressopp::integrator::PIAdressIntegrator::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::MinimizeEnergy::run(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::Rattle::saveOldPos(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostatOnGroup::thermalize(), espressopp::integrator::LangevinThermostatOnRadius::thermalize(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), totalSize(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::io::DumpH5MD::update(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::VelocityVerletRESPA::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
getSystemRef1()
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
getSystemRef2()
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
getVerletCutoff()
real espressopp::vectorization::VerletList::getVerletCutoff ()
Definition at line 69 of file VerletList.cpp.
References cutVerlet.
Referenced by registerPython().
loadTimers()
void espressopp::vectorization::VerletList::loadTimers (real * t)
Definition at line 565 of file VerletList.cpp.
References timeRebuild.
Referenced by espressopp::vectorization::wrapGetTimers().
localSize()
int espressopp::vectorization::VerletList::localSize () const
Definition at line 520 of file VerletList.cpp.
References espressopp::SystemAccess::getSystemRef(), and num_pairs.
Referenced by registerPython(), and totalSize().
LOG4ESPP_DECL_LOGGER()
static espressopp::vectorization::VerletList::LOG4ESPP_DECL_LOGGER (theLogger) static protected
rebuild()
void espressopp::vectorization::VerletList::rebuild ()
Definition at line 112 of file VerletList.cpp.
References builds, cut, cutsq, cutVerlet, espressopp::esutil::Timer::getElapsedTime(), getParticleArray(), espressopp::SystemAccess::getSystem(), espressopp::vectorization::ParticleArray::mode_aos(), neighborList, num_pairs, espressopp::esutil::Timer::reset(), espressopp::vectorization::VerletList::NeighborList::reset(), timer, timeRebuild, and vlPairs.
Referenced by connect(), registerPython(), and VerletList().
rebuild_p_nc_pack_stencil()
template<bool VEC_MODE_AOS, bool PACK_NEIGHBORS> void espressopp::vectorization::VerletList::rebuild_p_nc_pack_stencil protected
fill values
Check whether there is enough space for next cells
Definition at line 153 of file VerletList.cpp.
References builds, c_j, c_x, c_y, c_z, espressopp::vectorization::VerletList::NeighborList::clist, espressopp::vectorization::VerletList::NeighborList::crange, cutsq, ESPP_FIT_TO_VECTOR_WIDTH, ESPP_VECTOR_WIDTH, espressopp::SystemAccess::getSystem(), LOG4ESPP_DEBUG, LOG4ESPP_INFO, LOG4ESPP_WARN, max_type, neighborList, espressopp::vectorization::VerletList::NeighborList::nplist, num_pairs, espressopp::vectorization::VerletList::NeighborList::plist, espressopp::vectorization::VerletList::NeighborList::prange, vec, and vlPairs.
rebuildPairs()
void espressopp::vectorization::VerletList::rebuildPairs ()
Rebuilds the non-vectorized Verlet list vlPairs for back-compatibility with analysis.
Definition at line 96 of file VerletList.cpp.
References checkPair(), cut, cutsq, cutVerlet, espressopp::SystemAccess::getSystem(), espressopp::iterator::CellListAllPairsIterator::isValid(), LOG4ESPP_DEBUG, and vlPairs.
Referenced by registerPython().
registerPython()
void espressopp::vectorization::VerletList::registerPython () static
Register this class so it can be used from Python.
Definition at line 581 of file VerletList.cpp.
References connect(), disconnect(), exclude(), getBuilds(), getPair(), espressopp::SystemAccess::getSystem(), getVerletCutoff(), localSize(), rebuild(), rebuildPairs(), resetTimers(), setBuilds(), totalSize(), and espressopp::vectorization::wrapGetTimers().
Referenced by espressopp::vectorization::registerPython().
resetTimers()
void espressopp::vectorization::VerletList::resetTimers ()
Definition at line 560 of file VerletList.cpp.
References timeRebuild.
Referenced by registerPython(), and VerletList().
setBuilds()
void espressopp::vectorization::VerletList::setBuilds (int _builds) inline
Set the number of times the Verlet list has been rebuilt.
Definition at line 122 of file VerletList.hpp.
References builds.
Referenced by registerPython().
totalSize()
int espressopp::vectorization::VerletList::totalSize () const
Get the total number of pairs for the Verlet list.
Definition at line 510 of file VerletList.cpp.
References espressopp::System::comm, espressopp::SystemAccess::getSystemRef(), and localSize().
Referenced by registerPython().
Member Data Documentation
builds
int espressopp::vectorization::VerletList::builds protected
Definition at line 151 of file VerletList.hpp.
Referenced by getBuilds(), rebuild(), rebuild_p_nc_pack_stencil(), setBuilds(), and VerletList().
c_j
AlignedVector<int> espressopp::vectorization::VerletList::c_j protected
Definition at line 137 of file VerletList.hpp.
Referenced by rebuild_p_nc_pack_stencil().
c_x
AlignedVector<real> espressopp::vectorization::VerletList::c_x protected
Definition at line 138 of file VerletList.hpp.
Referenced by rebuild_p_nc_pack_stencil().
c_y
AlignedVector<real> espressopp::vectorization::VerletList::c_y protected
Definition at line 138 of file VerletList.hpp.
Referenced by rebuild_p_nc_pack_stencil().
c_z
AlignedVector<real> espressopp::vectorization::VerletList::c_z protected
Definition at line 138 of file VerletList.hpp.
Referenced by rebuild_p_nc_pack_stencil().
connectionResort
boost::signals2::connection espressopp::vectorization::VerletList::connectionResort protected
Definition at line 152 of file VerletList.hpp.
Referenced by connect(), disconnect(), VerletList(), and ~VerletList().
cut
real espressopp::vectorization::VerletList::cut protected
Definition at line 148 of file VerletList.hpp.
Referenced by rebuild(), rebuildPairs(), and VerletList().
cutsq
real espressopp::vectorization::VerletList::cutsq protected
Definition at line 147 of file VerletList.hpp.
Referenced by checkPair(), rebuild(), rebuild_p_nc_pack_stencil(), rebuildPairs(), and VerletList().
cutVerlet
real espressopp::vectorization::VerletList::cutVerlet protected
Definition at line 149 of file VerletList.hpp.
Referenced by getVerletCutoff(), rebuild(), rebuildPairs(), and VerletList().
exList
boost::unordered_set<std::pair<longint, longint> > espressopp::vectorization::VerletList::exList protected
Definition at line 144 of file VerletList.hpp.
Referenced by checkPair(), and exclude().
max_type
std::uint64_t espressopp::vectorization::VerletList::max_type protected
Definition at line 146 of file VerletList.hpp.
Referenced by checkPair(), getMaxType(), rebuild_p_nc_pack_stencil(), and VerletList().
mySystem
weak_ptr< System > espressopp::SystemAccess::mySystem private inherited
Weak pointer to the system guarantees that system will be freed.
Definition at line 54 of file SystemAccess.hpp.
Referenced by espressopp::SystemAccess::getSystem(), and espressopp::SystemAccess::SystemAccess().
mySystem1
weak_ptr< System > espressopp::SystemAccess::mySystem1 private inherited
Definition at line 55 of file SystemAccess.hpp.
Referenced by espressopp::SystemAccess::getSystem1(), and espressopp::SystemAccess::SystemAccess().
mySystem2
weak_ptr< System > espressopp::SystemAccess::mySystem2 private inherited
Definition at line 56 of file SystemAccess.hpp.
Referenced by espressopp::SystemAccess::getSystem2(), and espressopp::SystemAccess::SystemAccess().
neighborList
NeighborList espressopp::vectorization::VerletList::neighborList protected
Definition at line 143 of file VerletList.hpp.
Referenced by getNeighborList(), rebuild(), and rebuild_p_nc_pack_stencil().
num_pairs
int espressopp::vectorization::VerletList::num_pairs = 0 protected
Definition at line 134 of file VerletList.hpp.
Referenced by localSize(), rebuild(), and rebuild_p_nc_pack_stencil().
timer
esutil::WallTimer espressopp::vectorization::VerletList::timer protected
Definition at line 154 of file VerletList.hpp.
Referenced by rebuild().
timeRebuild
real espressopp::vectorization::VerletList::timeRebuild protected
Definition at line 155 of file VerletList.hpp.
Referenced by loadTimers(), rebuild(), and resetTimers().
vec
shared_ptr<Vectorization> espressopp::vectorization::VerletList::vec protected
Definition at line 132 of file VerletList.hpp.
Referenced by getParticleArray(), and rebuild_p_nc_pack_stencil().
vlPairs
PairList espressopp::vectorization::VerletList::vlPairs protected
Definition at line 142 of file VerletList.hpp.
Referenced by checkPair(), getPair(), getPairs(), rebuild(), rebuild_p_nc_pack_stencil(), and rebuildPairs().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/vectorization/VerletList.hpp
/home/espressopp/espressopp/src/vectorization/VerletList.cpp