ESPResSo++: espressopp::interaction::AngularUniquePotentialTemplate< Derived > Class Template Reference
espressopp::interaction::AngularUniquePotentialTemplate< Derived > Class Template Reference
#include <AngularUniquePotential.hpp>
Public Member Functions
AngularUniquePotentialTemplate ()
virtual real computeEnergy (const Particle &p1, const Particle &p2, const Particle &p3, real theta0) const
virtual real computeEnergy (const Real3D &r12, const Real3D &r32, real theta0) const
virtual real computeEnergy (const real theta, real theta0) const
virtual void computeForce (Real3D &force12, Real3D &force32, const Particle &p1, const Particle &p2, const Particle &p3, real theta0) const
virtual void computeForce (Real3D &force12, Real3D &force32, const Real3D &r12, const Real3D &r32, real cos0) const
virtual real computeForce (real theta, real cos0) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
real _computeEnergy (const Particle &p1, const Particle &p2, const Particle &p3, real theta0) const
real _computeEnergy (const Real3D &r12, const Real3D &r32, real theta0) const
real _computeEnergy (real theta, real theta0) const
void _computeForce (Real3D &force12, Real3D &force32, const Particle &p1, const Particle &p2, const Particle &p3, real theta0) const
bool _computeForce (Real3D &force12, Real3D &force32, const Real3D &r12, const Real3D &r32, real theta0) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
Derived * derived_this ()
const Derived * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
Detailed Description
template<class Derived>
class espressopp::interaction::AngularUniquePotentialTemplate< Derived >
Definition at line 59 of file AngularUniquePotential.hpp.
Constructor & Destructor Documentation
AngularUniquePotentialTemplate()
template<class Derived > espressopp::interaction::AngularUniquePotentialTemplate< Derived >::AngularUniquePotentialTemplate () inline
Definition at line 111 of file AngularUniquePotential.hpp.
Referenced by espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueCosineSquared >::derived_this().
Member Function Documentation
_computeEnergy() [1/3]
template<class Derived > real espressopp::interaction::AngularUniquePotentialTemplate< Derived >::_computeEnergy (const Particle & p1, const Particle & p2, const Particle & p3, real theta0) const inline
Definition at line 160 of file AngularUniquePotential.hpp.
_computeEnergy() [2/3]
template<class Derived > real espressopp::interaction::AngularUniquePotentialTemplate< Derived >::_computeEnergy (const Real3D & r12, const Real3D & r32, real theta0) const inline
Definition at line 169 of file AngularUniquePotential.hpp.
_computeEnergy() [3/3]
template<class Derived > real espressopp::interaction::AngularUniquePotentialTemplate< Derived >::_computeEnergy (real theta, real theta0) const inline
Definition at line 183 of file AngularUniquePotential.hpp.
_computeForce() [1/2]
template<class Derived > void espressopp::interaction::AngularUniquePotentialTemplate< Derived >::_computeForce (Real3D & force12, Real3D & force32, const Particle & p1, const Particle & p2, const Particle & p3, real theta0) const inline
Definition at line 213 of file AngularUniquePotential.hpp.
_computeForce() [2/2]
template<class Derived > bool espressopp::interaction::AngularUniquePotentialTemplate< Derived >::_computeForce (Real3D & force12, Real3D & force32, const Real3D & r12, const Real3D & r32, real theta0) const inline
Definition at line 225 of file AngularUniquePotential.hpp.
computeEnergy() [1/3]
template<class Derived > real espressopp::interaction::AngularUniquePotentialTemplate< Derived >::computeEnergy (const Particle & p1, const Particle & p2, const Particle & p3, real theta0) const inline virtual
Implements espressopp::interaction::AngularUniquePotential.
Definition at line 134 of file AngularUniquePotential.hpp.
computeEnergy() [2/3]
template<class Derived > real espressopp::interaction::AngularUniquePotentialTemplate< Derived >::computeEnergy (const Real3D & r12, const Real3D & r32, real theta0) const inline virtual
Implements espressopp::interaction::AngularUniquePotential.
Definition at line 143 of file AngularUniquePotential.hpp.
computeEnergy() [3/3]
template<class Derived > real espressopp::interaction::AngularUniquePotentialTemplate< Derived >::computeEnergy (const real theta, real theta0) const inline virtual
Implements espressopp::interaction::AngularUniquePotential.
Definition at line 153 of file AngularUniquePotential.hpp.
computeForce() [1/3]
template<class Derived > void espressopp::interaction::AngularUniquePotentialTemplate< Derived >::computeForce (Real3D & force12, Real3D & force32, const Particle & p1, const Particle & p2, const Particle & p3, real theta0) const inline virtual
Implements espressopp::interaction::AngularUniquePotential.
Definition at line 191 of file AngularUniquePotential.hpp.
computeForce() [2/3]
template<class Derived > void espressopp::interaction::AngularUniquePotentialTemplate< Derived >::computeForce (Real3D & force12, Real3D & force32, const Real3D & r12, const Real3D & r32, real cos0) const inline virtual
Implements espressopp::interaction::AngularUniquePotential.
Definition at line 203 of file AngularUniquePotential.hpp.
computeForce() [3/3]
template<class Derived > real espressopp::interaction::AngularUniquePotentialTemplate< Derived >::computeForce (real theta, real cos0) const inline virtual
Implements espressopp::interaction::AngularUniquePotential.
Definition at line 237 of file AngularUniquePotential.hpp.
derived_this() [1/2]
template<class Derived> Derived* espressopp::interaction::AngularUniquePotentialTemplate< Derived >::derived_this () inline protected
Definition at line 96 of file AngularUniquePotential.hpp.
derived_this() [2/2]
template<class Derived> const Derived* espressopp::interaction::AngularUniquePotentialTemplate< Derived >::derived_this () const inline protected
Definition at line 100 of file AngularUniquePotential.hpp.
getCutoff()
template<class Derived > real espressopp::interaction::AngularUniquePotentialTemplate< Derived >::getCutoff () const inline virtual
Implements espressopp::interaction::AngularUniquePotential.
Definition at line 127 of file AngularUniquePotential.hpp.
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::AngularUniquePotential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
registerPython()
void espressopp::interaction::AngularUniquePotential::registerPython () static inherited
Definition at line 35 of file AngularUniquePotential.cpp.
References espressopp::interaction::AngularUniquePotential::computeEnergy(), espressopp::interaction::AngularUniquePotential::computeForce(), espressopp::interaction::AngularUniquePotential::getCutoff(), and espressopp::interaction::AngularUniquePotential::setCutoff().
Referenced by espressopp::interaction::registerPython().
setCutoff()
template<class Derived > void espressopp::interaction::AngularUniquePotentialTemplate< Derived >::setCutoff (real _cutoff) inline virtual
Implements espressopp::interaction::AngularUniquePotential.
Definition at line 119 of file AngularUniquePotential.hpp.
Member Data Documentation
cutoff
template<class Derived> real espressopp::interaction::AngularUniquePotentialTemplate< Derived >::cutoff protected
Definition at line 93 of file AngularUniquePotential.hpp.
cutoffSqr
template<class Derived> real espressopp::interaction::AngularUniquePotentialTemplate< Derived >::cutoffSqr protected
Definition at line 94 of file AngularUniquePotential.hpp.
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/interaction/AngularUniquePotential.hpp