ESPResSo++: espressopp::integrator::LangevinThermostat1D Class Reference
espressopp::integrator::LangevinThermostat1D Class Reference
Langevin thermostat.
#include <LangevinThermostat1D.hpp>
Public Types
enum ExtensionType {
all =0, Thermostat =1, Barostat =2, Constraint =3,
Adress =4, FreeEnergyCompensation =5, ExtForce =6, ExtAnalysis =7,
Reaction =8
}
Public Member Functions
LangevinThermostat1D (shared_ptr< System > system)
virtual ~LangevinThermostat1D ()
void setGamma (real gamma)
real getGamma ()
void setTemperature (real temperature)
real getTemperature ()
void setDirection (int _direction)
int getDirection ()
void setAdress (bool _adress)
bool getAdress ()
void initialize ()
void thermalize ()
update of forces to thermalize the system
void thermalizeAdr ()
void heatUp ()
very nasty: if we recalculate force when leaving/reentering the integrator, a(t) and a((t-dt)+dt) are NOT equal in the vv algorithm.
void coolDown ()
Opposite to heatUp.
ExtensionType getType ()
void setType (ExtensionType k)
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
Register this class so it can be used from Python.
Public Attributes
ExtensionType type
Protected Member Functions
void setIntegrator (shared_ptr< MDIntegrator > _integrator)
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Protected Attributes
shared_ptr< MDIntegrator > integrator
Private Member Functions
void frictionThermo (class Particle &)
void enableAdress ()
void connect ()
void disconnect ()
Private Attributes
boost::signals2::connection _initialize
boost::signals2::connection _heatUp
boost::signals2::connection _coolDown
boost::signals2::connection _thermalize
boost::signals2::connection _thermalizeAdr
bool adress
int direction
real gamma
friction coefficient
real temperature
desired user temperature
real pref1
prefactor, reduces complexity of thermalize
real pref2
prefactor, reduces complexity of thermalize
real pref2buffer
temporary to save value between heatUp/coolDown
shared_ptr< esutil::RNG > rng
random number generator used for friction term
Detailed Description
Langevin thermostat.
Definition at line 44 of file LangevinThermostat1D.hpp.
Member Enumeration Documentation
enum espressopp::integrator::Extension::ExtensionType inherited
Enumerator
all
Thermostat
Barostat
Constraint
Adress
FreeEnergyCompensation
ExtForce
ExtAnalysis
Reaction
Definition at line 48 of file Extension.hpp.
Constructor & Destructor Documentation
espressopp::integrator::LangevinThermostat1D::LangevinThermostat1D (shared_ptr< System > system)
Definition at line 39 of file LangevinThermostat1D.cpp.
References direction, gamma, LOG4ESPP_INFO, rng, temperature, espressopp::integrator::Extension::Thermostat, and espressopp::integrator::Extension::type.
espressopp::integrator::LangevinThermostat1D::~LangevinThermostat1D () virtual
Definition at line 97 of file LangevinThermostat1D.cpp.
References disconnect().
Member Function Documentation
void espressopp::integrator::LangevinThermostat1D::connect () private virtual
Implements espressopp::integrator::Extension.
Definition at line 112 of file LangevinThermostat1D.cpp.
References _coolDown, _heatUp, _initialize, _thermalize, _thermalizeAdr, adress, coolDown(), heatUp(), initialize(), espressopp::integrator::Extension::integrator, thermalize(), and thermalizeAdr().
Referenced by registerPython().
void espressopp::integrator::LangevinThermostat1D::coolDown ()
Opposite to heatUp.
Definition at line 215 of file LangevinThermostat1D.cpp.
References LOG4ESPP_INFO, pref2, and pref2buffer.
Referenced by connect().
void espressopp::integrator::LangevinThermostat1D::disconnect () private virtual
Implements espressopp::integrator::Extension.
Definition at line 102 of file LangevinThermostat1D.cpp.
References _coolDown, _heatUp, _initialize, _thermalize, and _thermalizeAdr.
Referenced by registerPython(), and ~LangevinThermostat1D().
void espressopp::integrator::LangevinThermostat1D::enableAdress () private
void espressopp::integrator::LangevinThermostat1D::frictionThermo (class Particle & p) private
Definition at line 172 of file LangevinThermostat1D.cpp.
References direction, espressopp::Particle::force(), LOG4ESPP_TRACE, espressopp::Particle::mass(), pref1, pref2, and espressopp::Particle::velocity().
Referenced by thermalize(), and thermalizeAdr().
bool espressopp::integrator::LangevinThermostat1D::getAdress ()
Definition at line 73 of file LangevinThermostat1D.cpp.
References adress.
Referenced by registerPython().
int espressopp::integrator::LangevinThermostat1D::getDirection ()
Definition at line 92 of file LangevinThermostat1D.cpp.
References direction.
Referenced by registerPython().
real espressopp::integrator::LangevinThermostat1D::getGamma ()
Definition at line 64 of file LangevinThermostat1D.cpp.
References gamma.
Referenced by registerPython().
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::LatticeBoltzmann::initGammas(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readCouplForces(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::VerletListTriple::registerPython(), espressopp::VerletList::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveCouplForces(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::analysis::LBOutputScreen::writeOutput(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readCouplForces(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::LatticeBoltzmann::restoreLBForces(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::LatticeBoltzmann::saveCouplForces(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
real espressopp::integrator::LangevinThermostat1D::getTemperature ()
Definition at line 82 of file LangevinThermostat1D.cpp.
References temperature.
Referenced by registerPython().
ExtensionType espressopp::integrator::Extension::getType () inline inherited
Definition at line 67 of file Extension.hpp.
References espressopp::integrator::Extension::type.
Referenced by espressopp::integrator::Extension::registerPython().
void espressopp::integrator::LangevinThermostat1D::heatUp ()
very nasty: if we recalculate force when leaving/reentering the integrator, a(t) and a((t-dt)+dt) are NOT equal in the vv algorithm.
The random numbers are drawn twice, resulting in a different variance of the random force. This is corrected by additional heat when restarting the integrator here. Currently only works for the Langevin thermostat, although probably also others are affected.
Definition at line 205 of file LangevinThermostat1D.cpp.
References LOG4ESPP_INFO, pref2, and pref2buffer.
Referenced by connect().
void espressopp::integrator::LangevinThermostat1D::initialize ()
Definition at line 183 of file LangevinThermostat1D.cpp.
References gamma, espressopp::integrator::Extension::integrator, LOG4ESPP_INFO, pref1, pref2, and temperature.
Referenced by connect().
static espressopp::integrator::Extension::LOG4ESPP_DECL_LOGGER (theLogger) static protected inherited
Logger.
void espressopp::integrator::LangevinThermostat1D::registerPython () static
Register this class so it can be used from Python.
Definition at line 226 of file LangevinThermostat1D.cpp.
References connect(), disconnect(), getAdress(), getDirection(), getGamma(), getTemperature(), setAdress(), setDirection(), setGamma(), and setTemperature().
Referenced by espressopp::integrator::registerPython().
void espressopp::integrator::LangevinThermostat1D::setAdress (bool _adress)
Definition at line 69 of file LangevinThermostat1D.cpp.
References adress.
Referenced by registerPython().
void espressopp::integrator::LangevinThermostat1D::setDirection (int _direction)
Definition at line 87 of file LangevinThermostat1D.cpp.
References direction.
Referenced by registerPython().
void espressopp::integrator::LangevinThermostat1D::setGamma (real gamma)
Definition at line 59 of file LangevinThermostat1D.cpp.
References gamma.
Referenced by registerPython().
void espressopp::integrator::Extension::setIntegrator (shared_ptr< MDIntegrator > _integrator) protected inherited
Definition at line 49 of file Extension.cpp.
References espressopp::integrator::Extension::integrator.
Referenced by espressopp::integrator::Extension::registerPython().
void espressopp::integrator::LangevinThermostat1D::setTemperature (real temperature)
Definition at line 77 of file LangevinThermostat1D.cpp.
References temperature.
Referenced by registerPython().
void espressopp::integrator::Extension::setType (ExtensionType k) inline inherited
Definition at line 68 of file Extension.hpp.
References espressopp::integrator::Extension::type.
Referenced by espressopp::integrator::Extension::registerPython().
void espressopp::integrator::LangevinThermostat1D::thermalize ()
update of forces to thermalize the system
Definition at line 135 of file LangevinThermostat1D.cpp.
References frictionThermo(), espressopp::SystemAccess::getSystemRef(), espressopp::iterator::CellListIterator::isDone(), LOG4ESPP_DEBUG, and espressopp::System::storage.
Referenced by connect().
void espressopp::integrator::LangevinThermostat1D::thermalizeAdr ()
Definition at line 149 of file LangevinThermostat1D.cpp.
References frictionThermo(), espressopp::SystemAccess::getSystemRef(), espressopp::iterator::CellListIterator::isDone(), LOG4ESPP_DEBUG, and espressopp::System::storage.
Referenced by connect().
Member Data Documentation
boost::signals2::connection espressopp::integrator::LangevinThermostat1D::_coolDown private
Definition at line 86 of file LangevinThermostat1D.hpp.
Referenced by connect(), and disconnect().
boost::signals2::connection espressopp::integrator::LangevinThermostat1D::_heatUp private
Definition at line 86 of file LangevinThermostat1D.hpp.
Referenced by connect(), and disconnect().
boost::signals2::connection espressopp::integrator::LangevinThermostat1D::_initialize private
Definition at line 86 of file LangevinThermostat1D.hpp.
Referenced by connect(), and disconnect().
boost::signals2::connection espressopp::integrator::LangevinThermostat1D::_thermalize private
Definition at line 86 of file LangevinThermostat1D.hpp.
Referenced by connect(), and disconnect().
boost::signals2::connection espressopp::integrator::LangevinThermostat1D::_thermalizeAdr private
Definition at line 86 of file LangevinThermostat1D.hpp.
Referenced by connect(), and disconnect().
bool espressopp::integrator::LangevinThermostat1D::adress private
Definition at line 93 of file LangevinThermostat1D.hpp.
Referenced by connect(), getAdress(), and setAdress().
int espressopp::integrator::LangevinThermostat1D::direction private
Definition at line 98 of file LangevinThermostat1D.hpp.
Referenced by frictionThermo(), getDirection(), LangevinThermostat1D(), and setDirection().
real espressopp::integrator::LangevinThermostat1D::gamma private
friction coefficient
Definition at line 100 of file LangevinThermostat1D.hpp.
Referenced by getGamma(), initialize(), LangevinThermostat1D(), and setGamma().
shared_ptr<MDIntegrator> espressopp::integrator::Extension::integrator protected inherited
Definition at line 72 of file Extension.hpp.
Referenced by espressopp::integrator::LatticeBoltzmann::calcRandForce(), espressopp::integrator::ExtAnalyze::connect(), espressopp::integrator::VelocityVerletOnRadius::connect(), espressopp::integrator::BerendsenBarostatAnisotropic::connect(), espressopp::integrator::BerendsenBarostat::connect(), espressopp::integrator::FreeEnergyCompensation::connect(), espressopp::integrator::Isokinetic::connect(), espressopp::integrator::FixPositions::connect(), espressopp::integrator::ExtForce::connect(), espressopp::integrator::BerendsenThermostat::connect(), espressopp::integrator::TDforce::connect(), espressopp::integrator::Settle::connect(), espressopp::integrator::Adress::connect(), espressopp::integrator::CapForce::connect(), espressopp::integrator::OnTheFlyFEC::connect(), espressopp::integrator::DPDThermostat::connect(), espressopp::integrator::LangevinThermostat::connect(), espressopp::integrator::GeneralizedLangevinThermostat::connect(), connect(), espressopp::integrator::LangevinThermostatHybrid::connect(), espressopp::integrator::LangevinBarostat::connect(), espressopp::integrator::AssociationReaction::connect(), espressopp::integrator::StochasticVelocityRescaling::connect(), espressopp::integrator::LiquidGasLB::connect(), espressopp::integrator::LatticeBoltzmann::connect(), espressopp::integrator::LatticeBoltzmann::convTimeMDtoLB(), espressopp::integrator::LangevinThermostat::initialize(), espressopp::integrator::DPDThermostat::initialize(), initialize(), espressopp::integrator::BerendsenThermostat::initialize(), espressopp::integrator::LangevinThermostatHybrid::initialize(), espressopp::integrator::BerendsenBarostatAnisotropic::initialize(), espressopp::integrator::BerendsenBarostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::LiquidGasLB::makeLBStep(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::saveCouplForces(), espressopp::integrator::Extension::setIntegrator(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
real espressopp::integrator::LangevinThermostat1D::pref1 private
prefactor, reduces complexity of thermalize
Definition at line 103 of file LangevinThermostat1D.hpp.
Referenced by frictionThermo(), and initialize().
real espressopp::integrator::LangevinThermostat1D::pref2 private
prefactor, reduces complexity of thermalize
Definition at line 104 of file LangevinThermostat1D.hpp.
Referenced by coolDown(), frictionThermo(), heatUp(), and initialize().
real espressopp::integrator::LangevinThermostat1D::pref2buffer private
temporary to save value between heatUp/coolDown
Definition at line 106 of file LangevinThermostat1D.hpp.
Referenced by coolDown(), and heatUp().
shared_ptr< esutil::RNG > espressopp::integrator::LangevinThermostat1D::rng private
random number generator used for friction term
Definition at line 108 of file LangevinThermostat1D.hpp.
Referenced by LangevinThermostat1D().
real espressopp::integrator::LangevinThermostat1D::temperature private
desired user temperature
Definition at line 101 of file LangevinThermostat1D.hpp.
Referenced by getTemperature(), initialize(), LangevinThermostat1D(), and setTemperature().
ExtensionType espressopp::integrator::Extension::type inherited
Definition at line 62 of file Extension.hpp.
Referenced by espressopp::integrator::Adress::Adress(), espressopp::integrator::AssociationReaction::AssociationReaction(), espressopp::integrator::BerendsenBarostat::BerendsenBarostat(), espressopp::integrator::BerendsenBarostatAnisotropic::BerendsenBarostatAnisotropic(), espressopp::integrator::BerendsenThermostat::BerendsenThermostat(), espressopp::integrator::DPDThermostat::DPDThermostat(), espressopp::integrator::ExtAnalyze::ExtAnalyze(), espressopp::integrator::FreeEnergyCompensation::FreeEnergyCompensation(), espressopp::integrator::GeneralizedLangevinThermostat::GeneralizedLangevinThermostat(), espressopp::integrator::Extension::getType(), espressopp::integrator::LangevinBarostat::LangevinBarostat(), espressopp::integrator::LangevinThermostat::LangevinThermostat(), LangevinThermostat1D(), espressopp::integrator::LangevinThermostatHybrid::LangevinThermostatHybrid(), espressopp::integrator::OnTheFlyFEC::OnTheFlyFEC(), espressopp::integrator::TDforce::registerPython(), espressopp::integrator::Extension::setType(), espressopp::integrator::StochasticVelocityRescaling::StochasticVelocityRescaling(), and espressopp::integrator::TDforce::TDforce().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/integrator/LangevinThermostat1D.hpp
/home/travis/build/espressopp/espressopp/src/integrator/LangevinThermostat1D.cpp