ESPResSo++: espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG > Class Template Reference
espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG > Class Template Reference
#include <VerletListHadressATATCGInteractionTemplate.hpp>
Public Member Functions
VerletListHadressATATCGInteractionTemplate (shared_ptr< VerletListAdress > _verletList, shared_ptr< FixedTupleListAdress > _fixedtupleList)
void setVerletList (shared_ptr< VerletListAdress > _verletList)
shared_ptr< VerletListAdress > getVerletList ()
void setFixedTupleList (shared_ptr< FixedTupleListAdress > _fixedtupleList)
void setPotentialAT1 (int type1, int type2, const PotentialAT1 &potential)
void setPotentialAT2 (int type1, int type2, const PotentialAT2 &potential)
void setPotentialCG (int type1, int type2, const PotentialCG &potential)
PotentialAT1 & getPotentialAT1 (int type1, int type2)
PotentialAT2 & getPotentialAT2 (int type1, int type2)
PotentialCG & getPotentialCG (int type1, int type2)
virtual void addForces ()
virtual real computeEnergy ()
virtual real computeEnergyDeriv ()
virtual real computeEnergyAA ()
virtual real computeEnergyCG ()
virtual real computeEnergyAA (int atomtype)
virtual real computeEnergyCG (int atomtype)
virtual void computeVirialX (std::vector< real > &p_xx_total, int bins)
virtual real computeVirial ()
virtual void computeVirialTensor (Tensor &w)
virtual void computeVirialTensor (Tensor &w, real z)
virtual void computeVirialTensor (Tensor *w, int n)
virtual real getMaxCutoff ()
This method returns the maximal cutoff defined for one type pair.
virtual int bondType ()
Static Public Member Functions
static void registerPython ()
Protected Types
typedef _PotentialAT1 PotentialAT1
typedef _PotentialAT2 PotentialAT2
typedef _PotentialCG PotentialCG
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Protected Attributes
int ntypes
shared_ptr< VerletListAdress > verletList
shared_ptr< FixedTupleListAdress > fixedtupleList
esutil::Array2D< PotentialAT1, esutil::enlarge > potentialArrayAT1
esutil::Array2D< PotentialAT2, esutil::enlarge > potentialArrayAT2
esutil::Array2D< PotentialCG, esutil::enlarge > potentialArrayCG
real pidhy2
real dexdhy
real dexdhy2
real dex
real dhy
real dex2
boost::unordered_map< Particle *, real > energydiff
std::set< Particle * > adrZone
std::set< Particle * > cgZone
Detailed Description
template<typename _PotentialAT1, typename _PotentialAT2, typename _PotentialCG>
class espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >
Definition at line 42 of file VerletListHadressATATCGInteractionTemplate.hpp.
Member Typedef Documentation
PotentialAT1
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > typedef _PotentialAT1 espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::PotentialAT1 protected
Definition at line 45 of file VerletListHadressATATCGInteractionTemplate.hpp.
PotentialAT2
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > typedef _PotentialAT2 espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::PotentialAT2 protected
Definition at line 46 of file VerletListHadressATATCGInteractionTemplate.hpp.
PotentialCG
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > typedef _PotentialCG espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::PotentialCG protected
Definition at line 47 of file VerletListHadressATATCGInteractionTemplate.hpp.
Constructor & Destructor Documentation
VerletListHadressATATCGInteractionTemplate()
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::VerletListHadressATATCGInteractionTemplate (shared_ptr< VerletListAdress > _verletList, shared_ptr< FixedTupleListAdress > _fixedtupleList) inline
Definition at line 51 of file VerletListHadressATATCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::dex, espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::dex2, espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::dexdhy, espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::dexdhy2, espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::dhy, M_PI, espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::ntypes, espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::pidhy2, espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::potentialArrayAT1, espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::potentialArrayAT2, espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::potentialArrayCG, and espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::verletList.
Member Function Documentation
addForces()
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > void espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::addForces () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 171 of file VerletListHadressATATCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::adrZone, espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::cgZone, espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeEnergy(), espressopp::Particle::drift(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::energydiff, espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::fixedtupleList, espressopp::Particle::force(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialAT1(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialAT2(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialCG(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::Particle::lambda(), espressopp::Particle::lambdaDeriv(), LOG4ESPP_INFO, espressopp::Particle::position(), espressopp::Real3D::sqr(), espressopp::Particle::type(), and espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::verletList.
Referenced by espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialCG().
bondType()
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > virtual int espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::bondType () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 141 of file VerletListHadressATATCGInteractionTemplate.hpp.
References espressopp::interaction::Nonbonded.
computeEnergy()
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > real espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeEnergy () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 390 of file VerletListHadressATATCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeEnergyDeriv(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::fixedtupleList, espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialAT1(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialAT2(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialCG(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getVerletList(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::Particle::lambda(), LOG4ESPP_INFO, espressopp::Particle::type(), and espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::verletList.
Referenced by espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::addForces(), and espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialCG().
computeEnergyAA() [1/2]
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > real espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeEnergyAA () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 466 of file VerletListHadressATATCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeEnergyDeriv(), and espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialCG().
computeEnergyAA() [2/2]
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > real espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeEnergyAA (int atomtype) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 474 of file VerletListHadressATATCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeEnergyCG().
computeEnergyCG() [1/2]
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > real espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeEnergyCG () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 482 of file VerletListHadressATATCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeEnergyAA(), and espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialCG().
computeEnergyCG() [2/2]
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > real espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeEnergyCG (int atomtype) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 490 of file VerletListHadressATATCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeVirialX().
computeEnergyDeriv()
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > real espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeEnergyDeriv () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 458 of file VerletListHadressATATCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeEnergyAA().
Referenced by espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeEnergy(), and espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialCG().
computeVirial()
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > real espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeVirial () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 503 of file VerletListHadressATATCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeVirialTensor().
Referenced by espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeVirialX(), and espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialCG().
computeVirialTensor() [1/3]
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > void espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeVirialTensor (Tensor & w) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 510 of file VerletListHadressATATCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeVirial(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeVirialTensor(), and espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialCG().
computeVirialTensor() [2/3]
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > void espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeVirialTensor (Tensor & w, real z) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 516 of file VerletListHadressATATCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeVirialTensor().
computeVirialTensor() [3/3]
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > void espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeVirialTensor (Tensor * w, int n) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 523 of file VerletListHadressATATCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getMaxCutoff().
computeVirialX()
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > void espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeVirialX (std::vector< real > & p_xx_total, int bins) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 497 of file VerletListHadressATATCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeVirial().
Referenced by espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeEnergyCG(), and espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialCG().
getMaxCutoff()
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > real espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getMaxCutoff () inline virtual
This method returns the maximal cutoff defined for one type pair.
Implements espressopp::interaction::Interaction.
Definition at line 530 of file VerletListHadressATATCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialAT1(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialAT2(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialCG(), and espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::ntypes.
Referenced by espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeVirialTensor(), and espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialCG().
getPotentialAT1()
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > PotentialAT1& espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialAT1 (int type1, int type2) inline
Definition at line 116 of file VerletListHadressATATCGInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), and espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::potentialArrayAT1.
Referenced by espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::addForces(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeEnergy(), and espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getMaxCutoff().
getPotentialAT2()
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > PotentialAT2& espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialAT2 (int type1, int type2) inline
Definition at line 120 of file VerletListHadressATATCGInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), and espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::potentialArrayAT2.
Referenced by espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::addForces(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeEnergy(), and espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getMaxCutoff().
getPotentialCG()
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > PotentialCG& espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialCG (int type1, int type2) inline
Definition at line 124 of file VerletListHadressATATCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::addForces(), espressopp::esutil::Array2D< T, outlier_mode >::at(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeEnergy(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeEnergyAA(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeEnergyCG(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeEnergyDeriv(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeVirial(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeVirialTensor(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeVirialX(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getMaxCutoff(), and espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::potentialArrayCG.
Referenced by espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::addForces(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeEnergy(), and espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getMaxCutoff().
getVerletList()
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > shared_ptr<VerletListAdress> espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getVerletList () inline
Definition at line 74 of file VerletListHadressATATCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::verletList.
Referenced by espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeEnergy().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Interaction::LOG4ESPP_DECL_LOGGER (theLogger) static protected inherited
Logger.
Referenced by espressopp::interaction::Interaction::~Interaction().
registerPython()
void espressopp::interaction::Interaction::registerPython () static inherited
Definition at line 36 of file Interaction.cpp.
References espressopp::interaction::Interaction::bondType(), espressopp::interaction::Interaction::computeEnergy(), espressopp::interaction::Interaction::computeEnergyAA(), espressopp::interaction::Interaction::computeEnergyCG(), espressopp::interaction::Interaction::computeEnergyDeriv(), and espressopp::interaction::Interaction::computeVirial().
Referenced by espressopp::interaction::registerPython(), and espressopp::interaction::Interaction::~Interaction().
setFixedTupleList()
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > void espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::setFixedTupleList (shared_ptr< FixedTupleListAdress > _fixedtupleList) inline
Definition at line 79 of file VerletListHadressATATCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::fixedtupleList.
setPotentialAT1()
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > void espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::setPotentialAT1 (int type1, int type2, const PotentialAT1 & potential) inline
Definition at line 84 of file VerletListHadressATATCGInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::ntypes, and espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::potentialArrayAT1.
setPotentialAT2()
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > void espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::setPotentialAT2 (int type1, int type2, const PotentialAT2 & potential) inline
Definition at line 95 of file VerletListHadressATATCGInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::ntypes, and espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::potentialArrayAT2.
setPotentialCG()
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > void espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::setPotentialCG (int type1, int type2, const PotentialCG & potential) inline
Definition at line 106 of file VerletListHadressATATCGInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::ntypes, and espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::potentialArrayCG.
setVerletList()
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > void espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::setVerletList (shared_ptr< VerletListAdress > _verletList) inline
Definition at line 70 of file VerletListHadressATATCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::verletList.
Member Data Documentation
adrZone
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > std::set<Particle*> espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::adrZone protected
Definition at line 161 of file VerletListHadressATATCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::addForces().
cgZone
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > std::set<Particle*> espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::cgZone protected
Definition at line 162 of file VerletListHadressATATCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::addForces().
dex
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > real espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::dex protected
Definition at line 157 of file VerletListHadressATATCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::VerletListHadressATATCGInteractionTemplate().
dex2
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > real espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::dex2 protected
Definition at line 159 of file VerletListHadressATATCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::VerletListHadressATATCGInteractionTemplate().
dexdhy
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > real espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::dexdhy protected
Definition at line 155 of file VerletListHadressATATCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::VerletListHadressATATCGInteractionTemplate().
dexdhy2
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > real espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::dexdhy2 protected
Definition at line 156 of file VerletListHadressATATCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::VerletListHadressATATCGInteractionTemplate().
dhy
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > real espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::dhy protected
Definition at line 158 of file VerletListHadressATATCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::VerletListHadressATATCGInteractionTemplate().
energydiff
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > boost::unordered_map<Particle*, real> espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::energydiff protected
Definition at line 160 of file VerletListHadressATATCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::addForces().
fixedtupleList
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > shared_ptr<FixedTupleListAdress> espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::fixedtupleList protected
Definition at line 148 of file VerletListHadressATATCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::addForces(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeEnergy(), and espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::setFixedTupleList().
ntypes
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > int espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::ntypes protected
Definition at line 146 of file VerletListHadressATATCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getMaxCutoff(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::setPotentialAT1(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::setPotentialAT2(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::setPotentialCG(), and espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::VerletListHadressATATCGInteractionTemplate().
pidhy2
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > real espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::pidhy2 protected
Definition at line 154 of file VerletListHadressATATCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::VerletListHadressATATCGInteractionTemplate().
potentialArrayAT1
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > esutil::Array2D<PotentialAT1, esutil::enlarge> espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::potentialArrayAT1 protected
Definition at line 149 of file VerletListHadressATATCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialAT1(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::setPotentialAT1(), and espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::VerletListHadressATATCGInteractionTemplate().
potentialArrayAT2
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > esutil::Array2D<PotentialAT2, esutil::enlarge> espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::potentialArrayAT2 protected
Definition at line 150 of file VerletListHadressATATCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialAT2(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::setPotentialAT2(), and espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::VerletListHadressATATCGInteractionTemplate().
potentialArrayCG
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > esutil::Array2D<PotentialCG, esutil::enlarge> espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::potentialArrayCG protected
Definition at line 151 of file VerletListHadressATATCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getPotentialCG(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::setPotentialCG(), and espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::VerletListHadressATATCGInteractionTemplate().
verletList
template<typename _PotentialAT1 , typename _PotentialAT2 , typename _PotentialCG > shared_ptr<VerletListAdress> espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::verletList protected
Definition at line 147 of file VerletListHadressATATCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::addForces(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::computeEnergy(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::getVerletList(), espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::setVerletList(), and espressopp::interaction::VerletListHadressATATCGInteractionTemplate< _PotentialAT1, _PotentialAT2, _PotentialCG >::VerletListHadressATATCGInteractionTemplate().
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/interaction/VerletListHadressATATCGInteractionTemplate.hpp