ESPResSo++: espressopp::interaction::LennardJonesAutoBonds Class Reference
espressopp::interaction::LennardJonesAutoBonds Class Reference
This class provides methods to compute forces and energies of the Lennard Jones potential.
#include <LennardJonesAutoBonds.hpp>
Public Member Functions
LennardJonesAutoBonds ()
LennardJonesAutoBonds (real _epsilon, real _sigma, real _cutoff, real _shift, shared_ptr< FixedPairList > _fpl, int _max_crosslinks)
LennardJonesAutoBonds (real _epsilon, real _sigma, real _cutoff, shared_ptr< FixedPairList > _fpl, int _max_crosslinks)
void preset ()
void setEpsilon (real _epsilon)
real getEpsilon () const
void setSigma (real _sigma)
real getSigma () const
real getMaxCrosslinks () const
void setMaxCrosslinks (int _max_crosslinks)
real computeEnergy (const Particle &p1, const Particle &p2) const
void setCutoff (real _cutoff)
real setAutoShift ()
void updateAutoShift ()
real computeEnergy (const Real3D &dist) const
real computeEnergy (real dist) const
real computeEnergySqr (real distsqr) const
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergySqr (real distSqr) const
Real3D computeForce (const Particle &p1, const Particle &p2) const
Real3D computeForce (const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &dist, real distSqr) const
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)
virtual shared_ptr< FixedPairList > getColVarBondList () const
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &fpl)
virtual shared_ptr< FixedTripleList > getColVarAngleList () const
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fpl)
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const
virtual void setColVar (const RealND &cv)
virtual void setColVar (const Real3D &dist, const bc::BC &bc)
virtual RealND getColVar () const
virtual void computeColVarWeights (const Real3D &dist, const bc::BC &bc)
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergyDeriv (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
LennardJonesAutoBonds * derived_this ()
const LennardJonesAutoBonds * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
shared_ptr< FixedPairList > colVarBondList
shared_ptr< FixedTripleList > colVarAngleList
shared_ptr< FixedQuadrupleList > colVarDihedList
RealND colVar
Private Attributes
real epsilon
real sigma
real ff1
real ff2
real ef1
real ef2
shared_ptr< FixedPairList > bondlist
int max_crosslinks
Detailed Description
This class provides methods to compute forces and energies of the Lennard Jones potential.
Definition at line 41 of file LennardJonesAutoBonds.hpp.
Constructor & Destructor Documentation
LennardJonesAutoBonds() [1/3]
espressopp::interaction::LennardJonesAutoBonds::LennardJonesAutoBonds () inline
Definition at line 53 of file LennardJonesAutoBonds.hpp.
References setCutoff(), and espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::setShift().
LennardJonesAutoBonds() [2/3]
espressopp::interaction::LennardJonesAutoBonds::LennardJonesAutoBonds (real _epsilon, real _sigma, real _cutoff, real _shift, shared_ptr< FixedPairList > _fpl, int _max_crosslinks) inline
Definition at line 60 of file LennardJonesAutoBonds.hpp.
References preset(), setCutoff(), and espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::setShift().
LennardJonesAutoBonds() [3/3]
espressopp::interaction::LennardJonesAutoBonds::LennardJonesAutoBonds (real _epsilon, real _sigma, real _cutoff, shared_ptr< FixedPairList > _fpl, int _max_crosslinks) inline
Definition at line 68 of file LennardJonesAutoBonds.hpp.
References espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::autoShift, preset(), setAutoShift(), and setCutoff().
Member Function Documentation
_computeEnergy() [1/4]
real espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 360 of file Potential.hpp.
_computeEnergy() [2/4]
real espressopp::interaction::LennardJonesAutoBonds::_computeEnergy (const Particle & p1, const Particle & p2) const inline
Definition at line 144 of file LennardJonesAutoBonds.hpp.
References espressopp::Particle::position().
_computeEnergy() [3/4]
real espressopp::interaction::LennardJonesAutoBonds::_computeEnergy (const Real3D & dist) const inline
Definition at line 149 of file LennardJonesAutoBonds.hpp.
References _computeEnergySqr(), and espressopp::Real3D::sqr().
_computeEnergy() [4/4]
real espressopp::interaction::LennardJonesAutoBonds::_computeEnergy (real dist) const inline
Definition at line 153 of file LennardJonesAutoBonds.hpp.
References _computeEnergySqr().
_computeEnergyDeriv()
real espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::_computeEnergyDeriv (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 395 of file Potential.hpp.
_computeEnergySqr()
real espressopp::interaction::LennardJonesAutoBonds::_computeEnergySqr (real distSqr) const inline
Definition at line 157 of file LennardJonesAutoBonds.hpp.
References _computeEnergySqrRaw(), espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::cutoffSqr, espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::derived_this(), LOG4ESPP_TRACE, and espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::shift.
Referenced by _computeEnergy(), and computeEnergySqr().
_computeEnergySqrRaw()
real espressopp::interaction::LennardJonesAutoBonds::_computeEnergySqrRaw (real distSqr) const inline
Definition at line 204 of file LennardJonesAutoBonds.hpp.
Referenced by _computeEnergySqr(), and setAutoShift().
_computeForce() [1/3]
bool espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 431 of file Potential.hpp.
_computeForce() [2/3]
bool espressopp::interaction::LennardJonesAutoBonds::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const inline
Definition at line 179 of file LennardJonesAutoBonds.hpp.
References espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::cutoffSqr, espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::Particle::position(), and espressopp::Real3D::sqr().
Referenced by computeForce().
_computeForce() [3/3]
bool espressopp::interaction::LennardJonesAutoBonds::_computeForce (Real3D & force, const Real3D & dist) const inline
Definition at line 195 of file LennardJonesAutoBonds.hpp.
References _computeForceRaw(), espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::cutoffSqr, espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::derived_this(), and espressopp::Real3D::sqr().
_computeForceRaw()
bool espressopp::interaction::LennardJonesAutoBonds::_computeForceRaw (Real3D & force, const Real3D & dist, real distSqr) const inline
Definition at line 211 of file LennardJonesAutoBonds.hpp.
References ff2.
Referenced by _computeForce().
computeColVarWeights()
void espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::computeColVarWeights (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 315 of file Potential.hpp.
computeEnergy() [1/3]
real espressopp::interaction::LennardJonesAutoBonds::computeEnergy (const Particle & p1, const Particle & p2) const inline virtual
Reimplemented from espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >.
Definition at line 108 of file LennardJonesAutoBonds.hpp.
References espressopp::Particle::position().
computeEnergy() [2/3]
real espressopp::interaction::LennardJonesAutoBonds::computeEnergy (const Real3D & dist) const inline virtual
Reimplemented from espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >.
Definition at line 132 of file LennardJonesAutoBonds.hpp.
References computeEnergySqr(), and espressopp::Real3D::sqr().
computeEnergy() [3/3]
real espressopp::interaction::LennardJonesAutoBonds::computeEnergy (real dist) const inline virtual
Reimplemented from espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >.
Definition at line 136 of file LennardJonesAutoBonds.hpp.
References computeEnergySqr().
computeEnergySqr()
real espressopp::interaction::LennardJonesAutoBonds::computeEnergySqr (real distsqr) const inline virtual
Reimplemented from espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >.
Definition at line 140 of file LennardJonesAutoBonds.hpp.
References _computeEnergySqr().
Referenced by computeEnergy().
computeForce() [1/2]
Real3D espressopp::interaction::LennardJonesAutoBonds::computeForce (const Particle & p1, const Particle & p2) const inline virtual
Reimplemented from espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >.
Definition at line 167 of file LennardJonesAutoBonds.hpp.
References espressopp::Particle::position().
computeForce() [2/2]
Real3D espressopp::interaction::LennardJonesAutoBonds::computeForce (const Real3D & dist) const inline virtual
Reimplemented from espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >.
Definition at line 172 of file LennardJonesAutoBonds.hpp.
References _computeForce().
derived_this() [1/2]
LennardJonesAutoBonds * espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::derived_this () inline protected inherited
Definition at line 161 of file Potential.hpp.
Referenced by _computeEnergySqr(), _computeForce(), and setAutoShift().
derived_this() [2/2]
const LennardJonesAutoBonds * espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::derived_this () const inline protected inherited
Definition at line 165 of file Potential.hpp.
getColVar()
RealND espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::getColVar () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 309 of file Potential.hpp.
getColVarAngleList()
shared_ptr< FixedTripleList > espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::getColVarAngleList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 273 of file Potential.hpp.
getColVarBondList()
shared_ptr< FixedPairList > espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::getColVarBondList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 259 of file Potential.hpp.
getColVarDihedList()
shared_ptr< FixedQuadrupleList > espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::getColVarDihedList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 287 of file Potential.hpp.
getCutoff()
real espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 210 of file Potential.hpp.
getEpsilon()
real espressopp::interaction::LennardJonesAutoBonds::getEpsilon () const inline
Definition at line 93 of file LennardJonesAutoBonds.hpp.
References epsilon.
Referenced by registerPython().
getMaxCrosslinks()
real espressopp::interaction::LennardJonesAutoBonds::getMaxCrosslinks () const inline
Definition at line 102 of file LennardJonesAutoBonds.hpp.
References max_crosslinks.
Referenced by registerPython().
getShift()
real espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::getShift () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 225 of file Potential.hpp.
getSigma()
real espressopp::interaction::LennardJonesAutoBonds::getSigma () const inline
Definition at line 100 of file LennardJonesAutoBonds.hpp.
References sigma.
Referenced by registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
Referenced by espressopp::interaction::Potential::~Potential().
preset()
void espressopp::interaction::LennardJonesAutoBonds::preset () inline
Definition at line 77 of file LennardJonesAutoBonds.hpp.
References sigma.
Referenced by LennardJonesAutoBonds(), setEpsilon(), and setSigma().
registerPython()
void espressopp::interaction::LennardJonesAutoBonds::registerPython () static
Definition at line 50 of file LennardJonesAutoBonds.cpp.
References getEpsilon(), getMaxCrosslinks(), getSigma(), setEpsilon(), setMaxCrosslinks(), and setSigma().
Referenced by espressopp::interaction::registerPython().
setAutoShift()
real espressopp::interaction::LennardJonesAutoBonds::setAutoShift () inline virtual
Reimplemented from espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >.
Definition at line 119 of file LennardJonesAutoBonds.hpp.
References _computeEnergySqrRaw(), espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::autoShift, espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::cutoffSqr, espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::derived_this(), espressopp::infinity, and espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::shift.
Referenced by LennardJonesAutoBonds(), and updateAutoShift().
setColVar() [1/2]
void espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::setColVar (const RealND & cv) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 294 of file Potential.hpp.
setColVar() [2/2]
void espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::setColVar (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 301 of file Potential.hpp.
setColVarAngleList()
void espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::setColVarAngleList (const shared_ptr< FixedTripleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 266 of file Potential.hpp.
setColVarBondList()
void espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::setColVarBondList (const shared_ptr< FixedPairList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 252 of file Potential.hpp.
setColVarDihedList()
void espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 280 of file Potential.hpp.
setCutoff()
void espressopp::interaction::LennardJonesAutoBonds::setCutoff (real _cutoff) inline virtual
Reimplemented from espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >.
Definition at line 113 of file LennardJonesAutoBonds.hpp.
References espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::cutoff, espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::cutoffSqr, and updateAutoShift().
Referenced by LennardJonesAutoBonds().
setEpsilon()
void espressopp::interaction::LennardJonesAutoBonds::setEpsilon (real _epsilon) inline
Definition at line 87 of file LennardJonesAutoBonds.hpp.
References preset(), and updateAutoShift().
Referenced by registerPython().
setMaxCrosslinks()
void espressopp::interaction::LennardJonesAutoBonds::setMaxCrosslinks (int _max_crosslinks) inline
Definition at line 104 of file LennardJonesAutoBonds.hpp.
Referenced by registerPython().
setShift()
void espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::setShift (real _shift) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 216 of file Potential.hpp.
Referenced by LennardJonesAutoBonds().
setSigma()
void espressopp::interaction::LennardJonesAutoBonds::setSigma (real _sigma) inline
Definition at line 95 of file LennardJonesAutoBonds.hpp.
References preset(), and updateAutoShift().
Referenced by registerPython().
updateAutoShift()
void espressopp::interaction::LennardJonesAutoBonds::updateAutoShift () inline
Definition at line 128 of file LennardJonesAutoBonds.hpp.
References espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::autoShift, and setAutoShift().
Referenced by setCutoff(), setEpsilon(), and setSigma().
Member Data Documentation
autoShift
bool espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::autoShift protected inherited
Definition at line 151 of file Potential.hpp.
Referenced by LennardJonesAutoBonds(), setAutoShift(), and updateAutoShift().
bondlist
shared_ptr< FixedPairList > espressopp::interaction::LennardJonesAutoBonds::bondlist private
Definition at line 47 of file LennardJonesAutoBonds.hpp.
colVar
RealND espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::colVar protected inherited
Definition at line 159 of file Potential.hpp.
colVarAngleList
shared_ptr<FixedTripleList> espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::colVarAngleList protected inherited
Definition at line 155 of file Potential.hpp.
colVarBondList
shared_ptr<FixedPairList> espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::colVarBondList protected inherited
Definition at line 153 of file Potential.hpp.
colVarDihedList
shared_ptr<FixedQuadrupleList> espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::colVarDihedList protected inherited
Definition at line 157 of file Potential.hpp.
cutoff
real espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::cutoff protected inherited
Definition at line 148 of file Potential.hpp.
Referenced by setCutoff().
cutoffSqr
real espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::cutoffSqr protected inherited
Definition at line 149 of file Potential.hpp.
Referenced by _computeEnergySqr(), _computeForce(), setAutoShift(), and setCutoff().
ef1
real espressopp::interaction::LennardJonesAutoBonds::ef1 private
Definition at line 46 of file LennardJonesAutoBonds.hpp.
ef2
real espressopp::interaction::LennardJonesAutoBonds::ef2 private
Definition at line 46 of file LennardJonesAutoBonds.hpp.
epsilon
real espressopp::interaction::LennardJonesAutoBonds::epsilon private
Definition at line 43 of file LennardJonesAutoBonds.hpp.
Referenced by getEpsilon().
ff1
real espressopp::interaction::LennardJonesAutoBonds::ff1 private
Definition at line 45 of file LennardJonesAutoBonds.hpp.
ff2
real espressopp::interaction::LennardJonesAutoBonds::ff2 private
Definition at line 45 of file LennardJonesAutoBonds.hpp.
Referenced by _computeForceRaw().
max_crosslinks
int espressopp::interaction::LennardJonesAutoBonds::max_crosslinks private
Definition at line 48 of file LennardJonesAutoBonds.hpp.
Referenced by getMaxCrosslinks().
shift
real espressopp::interaction::PotentialTemplate< LennardJonesAutoBonds >::shift protected inherited
Definition at line 150 of file Potential.hpp.
Referenced by _computeEnergySqr(), and setAutoShift().
sigma
real espressopp::interaction::LennardJonesAutoBonds::sigma private
Definition at line 44 of file LennardJonesAutoBonds.hpp.
Referenced by getSigma(), and preset().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/LennardJonesAutoBonds.hpp
/home/espressopp/espressopp/src/interaction/LennardJonesAutoBonds.cpp