ESPResSo++: espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 > Class Template Reference
espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 > Class Template Reference
#include <VerletListHadressATATInteractionTemplate.hpp>
Public Member Functions
VerletListHadressATATInteractionTemplate (shared_ptr< VerletListAdress > _verletList, shared_ptr< FixedTupleListAdress > _fixedtupleList)
void setVerletList (shared_ptr< VerletListAdress > _verletList)
shared_ptr< VerletListAdress > getVerletList ()
void setFixedTupleList (shared_ptr< FixedTupleListAdress > _fixedtupleList)
void setPotential1 (int type1, int type2, const Potential1 &potential)
void setPotential2 (int type1, int type2, const Potential2 &potential)
Potential1 & getPotential1 (int type1, int type2)
Potential2 & getPotential2 (int type1, int type2)
virtual void addForces ()
virtual real computeEnergy ()
virtual real computeEnergyDeriv ()
virtual real computeEnergyAA ()
virtual real computeEnergyCG ()
virtual real computeEnergyAA (int atomtype)
virtual real computeEnergyCG (int atomtype)
virtual void computeVirialX (std::vector< real > &p_xx_total, int bins)
virtual real computeVirial ()
virtual void computeVirialTensor (Tensor &w)
virtual void computeVirialTensor (Tensor &w, real z)
virtual void computeVirialTensor (Tensor *w, int n)
virtual real getMaxCutoff ()
This method returns the maximal cutoff defined for one type pair.
virtual int bondType ()
Static Public Member Functions
static void registerPython ()
Protected Types
typedef _Potential1 Potential1
typedef _Potential2 Potential2
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Protected Attributes
int ntypes
shared_ptr< VerletListAdress > verletList
shared_ptr< FixedTupleListAdress > fixedtupleList
esutil::Array2D< Potential1, esutil::enlarge > potentialArray1
esutil::Array2D< Potential2, esutil::enlarge > potentialArray2
real pidhy2
real dexdhy
real dexdhy2
real dex
real dhy
real dex2
boost::unordered_map< Particle *, real > energydiff
std::set< Particle * > adrZone
std::set< Particle * > cgZone
Detailed Description
template<typename _Potential1, typename _Potential2>
class espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >
Definition at line 42 of file VerletListHadressATATInteractionTemplate.hpp.
Member Typedef Documentation
Potential1
template<typename _Potential1 , typename _Potential2 > typedef _Potential1 espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::Potential1 protected
Definition at line 45 of file VerletListHadressATATInteractionTemplate.hpp.
Potential2
template<typename _Potential1 , typename _Potential2 > typedef _Potential2 espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::Potential2 protected
Definition at line 46 of file VerletListHadressATATInteractionTemplate.hpp.
Constructor & Destructor Documentation
VerletListHadressATATInteractionTemplate()
template<typename _Potential1 , typename _Potential2 > espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::VerletListHadressATATInteractionTemplate (shared_ptr< VerletListAdress > _verletList, shared_ptr< FixedTupleListAdress > _fixedtupleList) inline
Definition at line 50 of file VerletListHadressATATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::dex, espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::dex2, espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::dexdhy, espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::dexdhy2, espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::dhy, M_PI, espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::ntypes, espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::pidhy2, espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::potentialArray1, espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::potentialArray2, and espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::verletList.
Member Function Documentation
addForces()
template<typename _Potential1 , typename _Potential2 > void espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::addForces () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 153 of file VerletListHadressATATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::adrZone, espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::cgZone, espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeEnergy(), espressopp::Particle::drift(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::energydiff, espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::fixedtupleList, espressopp::Particle::force(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getPotential1(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getPotential2(), espressopp::Particle::ghost(), espressopp::Particle::id(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::Particle::lambda(), espressopp::Particle::lambdaDeriv(), LOG4ESPP_INFO, espressopp::Particle::position(), espressopp::Real3D::sqr(), espressopp::Particle::type(), and espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::verletList.
Referenced by espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getPotential2().
bondType()
template<typename _Potential1 , typename _Potential2 > virtual int espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::bondType () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 124 of file VerletListHadressATATInteractionTemplate.hpp.
References espressopp::interaction::Nonbonded.
computeEnergy()
template<typename _Potential1 , typename _Potential2 > real espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeEnergy () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 321 of file VerletListHadressATATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeEnergyDeriv(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::fixedtupleList, espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getPotential1(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getPotential2(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getVerletList(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::Particle::lambda(), LOG4ESPP_INFO, espressopp::Particle::type(), and espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::verletList.
Referenced by espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::addForces(), and espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getPotential2().
computeEnergyAA() [1/2]
template<typename _Potential1 , typename _Potential2 > real espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeEnergyAA () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 376 of file VerletListHadressATATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeEnergyDeriv(), and espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getPotential2().
computeEnergyAA() [2/2]
template<typename _Potential1 , typename _Potential2 > real espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeEnergyAA (int atomtype) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 383 of file VerletListHadressATATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeEnergyCG().
computeEnergyCG() [1/2]
template<typename _Potential1 , typename _Potential2 > real espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeEnergyCG () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 390 of file VerletListHadressATATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeEnergyAA(), and espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getPotential2().
computeEnergyCG() [2/2]
template<typename _Potential1 , typename _Potential2 > real espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeEnergyCG (int atomtype) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 397 of file VerletListHadressATATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeVirialX().
computeEnergyDeriv()
template<typename _Potential1 , typename _Potential2 > real espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeEnergyDeriv () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 369 of file VerletListHadressATATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeEnergyAA().
Referenced by espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeEnergy(), and espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getPotential2().
computeVirial()
template<typename _Potential1 , typename _Potential2 > real espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeVirial () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 410 of file VerletListHadressATATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeVirialTensor().
Referenced by espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeVirialX(), and espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getPotential2().
computeVirialTensor() [1/3]
template<typename _Potential1 , typename _Potential2 > void espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeVirialTensor (Tensor & w) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 417 of file VerletListHadressATATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeVirial(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeVirialTensor(), and espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getPotential2().
computeVirialTensor() [2/3]
template<typename _Potential1 , typename _Potential2 > void espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeVirialTensor (Tensor & w, real z) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 423 of file VerletListHadressATATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeVirialTensor().
computeVirialTensor() [3/3]
template<typename _Potential1 , typename _Potential2 > void espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeVirialTensor (Tensor * w, int n) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 429 of file VerletListHadressATATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getMaxCutoff().
computeVirialX()
template<typename _Potential1 , typename _Potential2 > void espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeVirialX (std::vector< real > & p_xx_total, int bins) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 404 of file VerletListHadressATATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeVirial().
Referenced by espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeEnergyCG(), and espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getPotential2().
getMaxCutoff()
template<typename _Potential1 , typename _Potential2 > real espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getMaxCutoff () inline virtual
This method returns the maximal cutoff defined for one type pair.
Implements espressopp::interaction::Interaction.
Definition at line 436 of file VerletListHadressATATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getPotential1(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getPotential2(), and espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::ntypes.
Referenced by espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeVirialTensor(), and espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getPotential2().
getPotential1()
template<typename _Potential1 , typename _Potential2 > Potential1& espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getPotential1 (int type1, int type2) inline
Definition at line 103 of file VerletListHadressATATInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), and espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::potentialArray1.
Referenced by espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::addForces(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeEnergy(), and espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getMaxCutoff().
getPotential2()
template<typename _Potential1 , typename _Potential2 > Potential2& espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getPotential2 (int type1, int type2) inline
Definition at line 107 of file VerletListHadressATATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::addForces(), espressopp::esutil::Array2D< T, outlier_mode >::at(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeEnergy(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeEnergyAA(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeEnergyCG(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeEnergyDeriv(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeVirial(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeVirialTensor(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeVirialX(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getMaxCutoff(), and espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::potentialArray2.
Referenced by espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::addForces(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeEnergy(), and espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getMaxCutoff().
getVerletList()
template<typename _Potential1 , typename _Potential2 > shared_ptr<VerletListAdress> espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getVerletList () inline
Definition at line 72 of file VerletListHadressATATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::verletList.
Referenced by espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeEnergy().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Interaction::LOG4ESPP_DECL_LOGGER (theLogger) static protected inherited
Logger.
Referenced by espressopp::interaction::Interaction::~Interaction().
registerPython()
void espressopp::interaction::Interaction::registerPython () static inherited
Definition at line 36 of file Interaction.cpp.
References espressopp::interaction::Interaction::bondType(), espressopp::interaction::Interaction::computeEnergy(), espressopp::interaction::Interaction::computeEnergyAA(), espressopp::interaction::Interaction::computeEnergyCG(), espressopp::interaction::Interaction::computeEnergyDeriv(), and espressopp::interaction::Interaction::computeVirial().
Referenced by espressopp::interaction::registerPython(), and espressopp::interaction::Interaction::~Interaction().
setFixedTupleList()
template<typename _Potential1 , typename _Potential2 > void espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::setFixedTupleList (shared_ptr< FixedTupleListAdress > _fixedtupleList) inline
Definition at line 77 of file VerletListHadressATATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::fixedtupleList.
setPotential1()
template<typename _Potential1 , typename _Potential2 > void espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::setPotential1 (int type1, int type2, const Potential1 & potential) inline
Definition at line 82 of file VerletListHadressATATInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::ntypes, and espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::potentialArray1.
setPotential2()
template<typename _Potential1 , typename _Potential2 > void espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::setPotential2 (int type1, int type2, const Potential2 & potential) inline
Definition at line 93 of file VerletListHadressATATInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::ntypes, and espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::potentialArray2.
setVerletList()
template<typename _Potential1 , typename _Potential2 > void espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::setVerletList (shared_ptr< VerletListAdress > _verletList) inline
Definition at line 68 of file VerletListHadressATATInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::verletList.
Member Data Documentation
adrZone
template<typename _Potential1 , typename _Potential2 > std::set<Particle*> espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::adrZone protected
Definition at line 143 of file VerletListHadressATATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::addForces().
cgZone
template<typename _Potential1 , typename _Potential2 > std::set<Particle*> espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::cgZone protected
Definition at line 144 of file VerletListHadressATATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::addForces().
dex
template<typename _Potential1 , typename _Potential2 > real espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::dex protected
Definition at line 139 of file VerletListHadressATATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::VerletListHadressATATInteractionTemplate().
dex2
template<typename _Potential1 , typename _Potential2 > real espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::dex2 protected
Definition at line 141 of file VerletListHadressATATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::VerletListHadressATATInteractionTemplate().
dexdhy
template<typename _Potential1 , typename _Potential2 > real espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::dexdhy protected
Definition at line 137 of file VerletListHadressATATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::VerletListHadressATATInteractionTemplate().
dexdhy2
template<typename _Potential1 , typename _Potential2 > real espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::dexdhy2 protected
Definition at line 138 of file VerletListHadressATATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::VerletListHadressATATInteractionTemplate().
dhy
template<typename _Potential1 , typename _Potential2 > real espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::dhy protected
Definition at line 140 of file VerletListHadressATATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::VerletListHadressATATInteractionTemplate().
energydiff
template<typename _Potential1 , typename _Potential2 > boost::unordered_map<Particle*, real> espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::energydiff protected
Definition at line 142 of file VerletListHadressATATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::addForces().
fixedtupleList
template<typename _Potential1 , typename _Potential2 > shared_ptr<FixedTupleListAdress> espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::fixedtupleList protected
Definition at line 131 of file VerletListHadressATATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::addForces(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeEnergy(), and espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::setFixedTupleList().
ntypes
template<typename _Potential1 , typename _Potential2 > int espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::ntypes protected
Definition at line 129 of file VerletListHadressATATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getMaxCutoff(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::setPotential1(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::setPotential2(), and espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::VerletListHadressATATInteractionTemplate().
pidhy2
template<typename _Potential1 , typename _Potential2 > real espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::pidhy2 protected
Definition at line 136 of file VerletListHadressATATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::VerletListHadressATATInteractionTemplate().
potentialArray1
template<typename _Potential1 , typename _Potential2 > esutil::Array2D<Potential1, esutil::enlarge> espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::potentialArray1 protected
Definition at line 132 of file VerletListHadressATATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getPotential1(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::setPotential1(), and espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::VerletListHadressATATInteractionTemplate().
potentialArray2
template<typename _Potential1 , typename _Potential2 > esutil::Array2D<Potential2, esutil::enlarge> espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::potentialArray2 protected
Definition at line 133 of file VerletListHadressATATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getPotential2(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::setPotential2(), and espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::VerletListHadressATATInteractionTemplate().
verletList
template<typename _Potential1 , typename _Potential2 > shared_ptr<VerletListAdress> espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::verletList protected
Definition at line 130 of file VerletListHadressATATInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::addForces(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::computeEnergy(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::getVerletList(), espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::setVerletList(), and espressopp::interaction::VerletListHadressATATInteractionTemplate< _Potential1, _Potential2 >::VerletListHadressATATInteractionTemplate().
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/interaction/VerletListHadressATATInteractionTemplate.hpp