ESPResSo++: espressopp::analysis::OrderParticleProps Class Reference
espressopp::analysis::OrderParticleProps Class Reference
#include <OrderParameter.hpp>
Public Member Functions
OrderParticleProps ()
OrderParticleProps (int am)
OrderParticleProps (int am, int pid)
~OrderParticleProps ()
void insertNN (int i)
int getNN (int i)
int getNumNN ()
void setQlm (int indx, dcomplex v)
dcomplex getQlm (int indx)
vector< dcomplex > getQlmVector ()
void addQlmVector (vector< dcomplex > v)
void setQlm (vector< dcomplex > v)
void calculateSumQlm ()
real getSumQlm ()
void setD (real v)
real getD ()
void setPID (int v)
int getPID ()
void setSolid (bool v)
bool getSolid ()
void setSurface (bool v)
bool getSurface ()
void setLabel (int v)
int getLabel ()
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
real d
real qlmSumSqrt
int nnns
int ang_m
int particle_id
bool is_solid
bool is_surface
vector< int > nns
vector< dcomplex > qlm
int label
Friends
class boost::serialization::access
Detailed Description
Definition at line 69 of file OrderParameter.hpp.
Constructor & Destructor Documentation
OrderParticleProps() [1/3]
espressopp::analysis::OrderParticleProps::OrderParticleProps () inline
Definition at line 102 of file OrderParameter.hpp.
OrderParticleProps() [2/3]
espressopp::analysis::OrderParticleProps::OrderParticleProps (int am) inline
Definition at line 112 of file OrderParameter.hpp.
OrderParticleProps() [3/3]
espressopp::analysis::OrderParticleProps::OrderParticleProps (int am, int pid) inline
Definition at line 122 of file OrderParameter.hpp.
~OrderParticleProps()
espressopp::analysis::OrderParticleProps::~OrderParticleProps () inline
Definition at line 132 of file OrderParameter.hpp.
Member Function Documentation
addQlmVector()
void espressopp::analysis::OrderParticleProps::addQlmVector (vector< dcomplex > v) inline
Definition at line 154 of file OrderParameter.hpp.
Referenced by espressopp::analysis::OrderParameter::computeRaw().
calculateSumQlm()
void espressopp::analysis::OrderParticleProps::calculateSumQlm () inline
Definition at line 169 of file OrderParameter.hpp.
Referenced by espressopp::analysis::OrderParameter::computeRaw().
getD()
real espressopp::analysis::OrderParticleProps::getD () inline
Definition at line 179 of file OrderParameter.hpp.
Referenced by espressopp::analysis::OrderParameter::computeRaw(), and espressopp::analysis::OrderParameter::define_solid().
getLabel()
int espressopp::analysis::OrderParticleProps::getLabel () inline
Definition at line 190 of file OrderParameter.hpp.
Referenced by espressopp::analysis::OrderParameter::biggest_cluster(), espressopp::analysis::OrderParameter::cluster_walk(), espressopp::analysis::OrderParameter::global_cluster_analysis(), espressopp::analysis::OrderParameter::local_cluster_search(), espressopp::analysis::OrderParameter::relab(), and espressopp::analysis::OrderParameter::relabel_particles().
getNN()
int espressopp::analysis::OrderParticleProps::getNN (int i) inline
Definition at line 138 of file OrderParameter.hpp.
Referenced by espressopp::analysis::OrderParameter::cluster_walk(), espressopp::analysis::OrderParameter::computeRaw(), and espressopp::analysis::OrderParameter::define_solid().
getNumNN()
int espressopp::analysis::OrderParticleProps::getNumNN () inline
Definition at line 140 of file OrderParameter.hpp.
Referenced by espressopp::analysis::OrderParameter::cluster_walk(), espressopp::analysis::OrderParameter::computeRaw(), and espressopp::analysis::OrderParameter::define_solid().
getPID()
int espressopp::analysis::OrderParticleProps::getPID () inline
Definition at line 182 of file OrderParameter.hpp.
Referenced by espressopp::analysis::OrderParameter::biggest_cluster(), espressopp::analysis::OrderParameter::computeRaw(), espressopp::analysis::OrderParameter::define_solid(), and espressopp::analysis::OrderParameter::relabel_particles().
getQlm()
dcomplex espressopp::analysis::OrderParticleProps::getQlm (int indx) inline
Definition at line 148 of file OrderParameter.hpp.
Referenced by espressopp::analysis::OrderParameter::computeRaw().
getQlmVector()
vector<dcomplex> espressopp::analysis::OrderParticleProps::getQlmVector () inline
Definition at line 153 of file OrderParameter.hpp.
Referenced by espressopp::analysis::OrderParameter::computeRaw().
getSolid()
bool espressopp::analysis::OrderParticleProps::getSolid () inline
Definition at line 185 of file OrderParameter.hpp.
Referenced by espressopp::analysis::OrderParameter::cluster_walk(), espressopp::analysis::OrderParameter::define_solid(), espressopp::analysis::OrderParameter::global_cluster_analysis(), espressopp::analysis::OrderParameter::local_cluster_search(), and espressopp::analysis::OrderParameter::relabel_particles().
getSumQlm()
real espressopp::analysis::OrderParticleProps::getSumQlm () inline
Definition at line 176 of file OrderParameter.hpp.
Referenced by espressopp::analysis::OrderParameter::computeRaw().
getSurface()
bool espressopp::analysis::OrderParticleProps::getSurface () inline
Definition at line 187 of file OrderParameter.hpp.
Referenced by espressopp::analysis::OrderParameter::cluster_walk(), espressopp::analysis::OrderParameter::define_solid(), espressopp::analysis::OrderParameter::global_cluster_analysis(), espressopp::analysis::OrderParameter::local_cluster_search(), and espressopp::analysis::OrderParameter::relabel_particles().
insertNN()
void espressopp::analysis::OrderParticleProps::insertNN (int i) inline
Definition at line 134 of file OrderParameter.hpp.
Referenced by espressopp::analysis::OrderParameter::computeRaw().
serialize()
template<class Archive > void espressopp::analysis::OrderParticleProps::serialize (Archive & ar, const unsigned int version) inline private
Definition at line 88 of file OrderParameter.hpp.
setD()
void espressopp::analysis::OrderParticleProps::setD (real v) inline
Definition at line 178 of file OrderParameter.hpp.
Referenced by espressopp::analysis::OrderParameter::computeRaw().
setLabel()
void espressopp::analysis::OrderParticleProps::setLabel (int v) inline
Definition at line 189 of file OrderParameter.hpp.
Referenced by espressopp::analysis::OrderParameter::cluster_walk(), espressopp::analysis::OrderParameter::global_cluster_analysis(), espressopp::analysis::OrderParameter::relab(), and espressopp::analysis::OrderParameter::relabel_particles().
setPID()
void espressopp::analysis::OrderParticleProps::setPID (int v) inline
Definition at line 181 of file OrderParameter.hpp.
setQlm() [1/2]
void espressopp::analysis::OrderParticleProps::setQlm (int indx, dcomplex v) inline
Definition at line 143 of file OrderParameter.hpp.
Referenced by espressopp::analysis::OrderParameter::computeRaw().
setQlm() [2/2]
void espressopp::analysis::OrderParticleProps::setQlm (vector< dcomplex > v) inline
Definition at line 161 of file OrderParameter.hpp.
setSolid()
void espressopp::analysis::OrderParticleProps::setSolid (bool v) inline
Definition at line 184 of file OrderParameter.hpp.
Referenced by espressopp::analysis::OrderParameter::define_solid().
setSurface()
void espressopp::analysis::OrderParticleProps::setSurface (bool v) inline
Definition at line 186 of file OrderParameter.hpp.
Referenced by espressopp::analysis::OrderParameter::define_solid().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Definition at line 86 of file OrderParameter.hpp.
Member Data Documentation
ang_m
int espressopp::analysis::OrderParticleProps::ang_m private
Definition at line 75 of file OrderParameter.hpp.
d
real espressopp::analysis::OrderParticleProps::d private
Definition at line 71 of file OrderParameter.hpp.
is_solid
bool espressopp::analysis::OrderParticleProps::is_solid private
Definition at line 78 of file OrderParameter.hpp.
is_surface
bool espressopp::analysis::OrderParticleProps::is_surface private
Definition at line 79 of file OrderParameter.hpp.
label
int espressopp::analysis::OrderParticleProps::label private
Definition at line 84 of file OrderParameter.hpp.
nnns
int espressopp::analysis::OrderParticleProps::nnns private
Definition at line 73 of file OrderParameter.hpp.
nns
vector<int> espressopp::analysis::OrderParticleProps::nns private
Definition at line 81 of file OrderParameter.hpp.
particle_id
int espressopp::analysis::OrderParticleProps::particle_id private
Definition at line 76 of file OrderParameter.hpp.
qlm
vector<dcomplex> espressopp::analysis::OrderParticleProps::qlm private
Definition at line 82 of file OrderParameter.hpp.
qlmSumSqrt
real espressopp::analysis::OrderParticleProps::qlmSumSqrt private
Definition at line 72 of file OrderParameter.hpp.
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/analysis/OrderParameter.hpp