ESPResSo++: espressopp::interaction::AngularUniquePotential Class Reference
espressopp::interaction::AngularUniquePotential Class Reference abstract
#include <AngularUniquePotential.hpp>
Public Member Functions
virtual real computeEnergy (const Particle &p1, const Particle &p2, const Particle &p3, real theta0) const =0
virtual real computeEnergy (const Real3D &r12, const Real3D &r32, real theta0) const =0
virtual real computeEnergy (real theta, real theta0) const =0
virtual void computeForce (Real3D &force12, Real3D &force32, const Particle &p1, const Particle &p2, const Particle &p3, real theta0) const =0
virtual void computeForce (Real3D &force12, Real3D &force32, const Real3D &r12, const Real3D &r32, real theta0) const =0
virtual real computeForce (real theta, real theta0) const =0
virtual void setCutoff (real _cutoff)=0
virtual real getCutoff () const =0
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Detailed Description
Definition at line 35 of file AngularUniquePotential.hpp.
Member Function Documentation
computeEnergy() [1/3]
virtual real espressopp::interaction::AngularUniquePotential::computeEnergy (const Particle & p1, const Particle & p2, const Particle & p3, real theta0) const pure virtual
Implemented in espressopp::interaction::AngularUniquePotentialTemplate< Derived >, espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueHarmonic >, and espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueCosineSquared >.
Referenced by registerPython().
computeEnergy() [2/3]
virtual real espressopp::interaction::AngularUniquePotential::computeEnergy (const Real3D & r12, const Real3D & r32, real theta0) const pure virtual
Implemented in espressopp::interaction::AngularUniquePotentialTemplate< Derived >, espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueHarmonic >, and espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueCosineSquared >.
computeEnergy() [3/3]
virtual real espressopp::interaction::AngularUniquePotential::computeEnergy (real theta, real theta0) const pure virtual
Implemented in espressopp::interaction::AngularUniquePotentialTemplate< Derived >, espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueHarmonic >, and espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueCosineSquared >.
computeForce() [1/3]
virtual void espressopp::interaction::AngularUniquePotential::computeForce (Real3D & force12, Real3D & force32, const Particle & p1, const Particle & p2, const Particle & p3, real theta0) const pure virtual
Implemented in espressopp::interaction::AngularUniquePotentialTemplate< Derived >, espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueHarmonic >, and espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueCosineSquared >.
Referenced by registerPython().
computeForce() [2/3]
virtual void espressopp::interaction::AngularUniquePotential::computeForce (Real3D & force12, Real3D & force32, const Real3D & r12, const Real3D & r32, real theta0) const pure virtual
Implemented in espressopp::interaction::AngularUniquePotentialTemplate< Derived >, espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueHarmonic >, and espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueCosineSquared >.
computeForce() [3/3]
virtual real espressopp::interaction::AngularUniquePotential::computeForce (real theta, real theta0) const pure virtual
Implemented in espressopp::interaction::AngularUniquePotentialTemplate< Derived >, espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueHarmonic >, and espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueCosineSquared >.
getCutoff()
virtual real espressopp::interaction::AngularUniquePotential::getCutoff () const pure virtual
Implemented in espressopp::interaction::AngularUniquePotentialTemplate< Derived >, espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueHarmonic >, and espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueCosineSquared >.
Referenced by registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::AngularUniquePotential::LOG4ESPP_DECL_LOGGER (theLogger) static
registerPython()
void espressopp::interaction::AngularUniquePotential::registerPython () static
Definition at line 35 of file AngularUniquePotential.cpp.
References computeEnergy(), computeForce(), getCutoff(), and setCutoff().
Referenced by espressopp::interaction::registerPython().
setCutoff()
virtual void espressopp::interaction::AngularUniquePotential::setCutoff (real _cutoff) pure virtual
Implemented in espressopp::interaction::AngularUniquePotentialTemplate< Derived >, espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueHarmonic >, and espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueCosineSquared >.
Referenced by registerPython().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/AngularUniquePotential.hpp
/home/espressopp/espressopp/src/interaction/AngularUniquePotential.cpp