ESPResSo++: espressopp::esutil::Array2D< T, enlarge > Class Template Reference
espressopp::esutil::Array2D< T, enlarge > Class Template Reference
#include <Array2D.hpp>
Public Types
typedef T value_type
The type of object, T, stored in the Array1D.
typedef T & reference
Reference to to a T object.
typedef const T & const_reference
Const reference to to a T object.
typedef Super::size_type size_type
An unsigned integer type.
typedef Super::iterator iterator
Iterator used to iterate through an Array1D.
typedef Super::const_iterator const_iterator
Const-iterator used to iterate through an Array1D.
Public Member Functions
Array2D (const T &prototype=T())
Default constructor.
Array2D (size_type n, size_type m, const T &prototype=T())
Creates a one-dimensional array of size n with n copies of prototype.
void init (size_type n, size_type m, const T &prototype=T())
Creates a one-dimensional array of size n with n copies of prototype.
void set_prototype (const T &prototype=T())
Sets the prototype used when the Array2D<T,enlarge> is automatically resized.
reference at (size_type i, size_type j)
Returns the element at position i x j.
template<class Vector >
reference at (const Vector &pos)
Returns the element at position pos.
void clear ()
Erases all elements.
void resize (size_type n, size_type m, const T &t=T())
Changes the size of the Array2D so that the size becomes n x m.
size_type size_n () const
Returns the n -size of the array.
size_type size_x () const
Returns the n -size of the array.
size_type size_m () const
Returns the m -size of the array.
size_type size_y () const
Returns the m -size of the array.
bool empty () const
true if the Array2D's size is 0 x 0.
reference operator() (size_type i, size_type j)
Returns the element at position i x j.
const_reference operator() (size_type i, size_type j) const
Returns the element at position i x j.
reference operator() (const Vector &pos)
Returns the element at position pos.
const_reference operator() (const Vector &pos) const
Returns the element at position pos.
const_reference at (size_type i, size_type j) const
Returns the element at position i x j.
const_reference at (const Vector &pos) const
Returns the element at position pos.
iterator begin ()
Returns an iterator pointing to the beginning of the Array2D.
const_iterator begin () const
Returns a const_iterator pointing to the beginning of the Array2D.
iterator end ()
Returns an iterator pointing to the end of the Array2D.
const_iterator end () const
Returns a const_iterator pointing to the end of the Array2D.
void operator+= (const T2 &t2)
Adds t2 to each of the elements.
void operator-= (const T2 &t2)
Adds t2 to each of the elements.
void operator*= (const T2 &t2)
Multiplies each of the elements by t2.
void operator/= (const T2 &t2)
Divides each of the elements by t2.
void operator/= (const double &x)
bool operator== (const Array2D< T, exception > &a)
Equality operator.
bool operator!= (const Array2D< T, exception > &a)
Inequality operator.
Private Types
typedef Array2D< T, exception > Super
The super class of the array (i.e.
Private Attributes
value_type prototype
Detailed Description
template<class T>
class espressopp::esutil::Array2D< T, enlarge >
Definition at line 247 of file Array2D.hpp.
Member Typedef Documentation
template<class T > typedef Super::const_iterator espressopp::esutil::Array2D< T, enlarge >::const_iterator
Const-iterator used to iterate through an Array1D.
Reimplemented from espressopp::esutil::Array2D< T, exception >.
Definition at line 263 of file Array2D.hpp.
template<class T > typedef const T& espressopp::esutil::Array2D< T, enlarge >::const_reference
Const reference to to a T object.
Reimplemented from espressopp::esutil::Array2D< T, exception >.
Definition at line 257 of file Array2D.hpp.
template<class T > typedef Super::iterator espressopp::esutil::Array2D< T, enlarge >::iterator
Iterator used to iterate through an Array1D.
Reimplemented from espressopp::esutil::Array2D< T, exception >.
Definition at line 261 of file Array2D.hpp.
template<class T > typedef T& espressopp::esutil::Array2D< T, enlarge >::reference
Reference to to a T object.
Reimplemented from espressopp::esutil::Array2D< T, exception >.
Definition at line 255 of file Array2D.hpp.
template<class T > typedef Super::size_type espressopp::esutil::Array2D< T, enlarge >::size_type
An unsigned integer type.
Reimplemented from espressopp::esutil::Array2D< T, exception >.
Definition at line 259 of file Array2D.hpp.
template<class T > typedef Array2D< T, exception > espressopp::esutil::Array2D< T, enlarge >::Super [private]
The super class of the array (i.e.
vector<T>).
Reimplemented from espressopp::esutil::Array2D< T, exception >.
Definition at line 249 of file Array2D.hpp.
template<class T > typedef T espressopp::esutil::Array2D< T, enlarge >::value_type
The type of object, T, stored in the Array1D.
Reimplemented from espressopp::esutil::Array2D< T, exception >.
Definition at line 253 of file Array2D.hpp.
Constructor & Destructor Documentation
template<class T > espressopp::esutil::Array2D< T, enlarge >::Array2D (const T & prototype = T()) [inline]
Default constructor.
Definition at line 269 of file Array2D.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::init().
template<class T > espressopp::esutil::Array2D< T, enlarge >::Array2D (size_type n, size_type m, const T & prototype = T()) [inline]
Creates a one-dimensional array of size n with n copies of prototype.
Also sets the prototype.
Reimplemented from espressopp::esutil::Array2D< T, exception >.
Definition at line 274 of file Array2D.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::init().
Member Function Documentation
const_reference espressopp::esutil::Array2D< T, outlier_mode >::at (size_type i, size_type j) const [inline, inherited]
Returns the element at position i x j.
Exceptions:
out_of_range i is out of range of the Array2D
Definition at line 152 of file Array2D.hpp.
const_reference espressopp::esutil::Array2D< T, outlier_mode >::at (const Vector & pos) const [inline, inherited]
Returns the element at position pos.
pos must be a vector where the expressions pos[0] and pos[1] return the first and second element.
Exceptions:
out_of_range i is out of range of the Array2D
Definition at line 175 of file Array2D.hpp.
template<class T > reference espressopp::esutil::Array2D< T, enlarge >::at (size_type i, size_type j) [inline]
Returns the element at position i x j.
When the element doesn't exist, the Array2D is automatically extended so that the element exists. The new elements are initialised with copies of the prototype.
Reimplemented from espressopp::esutil::Array2D< T, exception >.
Definition at line 294 of file Array2D.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), espressopp::esutil::Array2D< T, outlier_mode >::init(), espressopp::esutil::Array2D< T, outlier_mode >::size_m(), and espressopp::esutil::Array2D< T, outlier_mode >::size_n().
template<class T > template<class Vector > reference espressopp::esutil::Array2D< T, enlarge >::at (const Vector & pos) [inline]
Returns the element at position pos.
pos must be a vector where the expressions pos[0] and pos[1] return the first and second element.
When the element doesn't exist, the Array2D is automatically extended so that the element exists. The new elements are initialised with copies of the prototype.
Reimplemented from espressopp::esutil::Array2D< T, exception >.
Definition at line 330 of file Array2D.hpp.
References at().
Referenced by at().
iterator espressopp::esutil::Array2D< T, outlier_mode >::begin () [inline, inherited]
Returns an iterator pointing to the beginning of the Array2D.
Definition at line 180 of file Array2D.hpp.
const_iterator espressopp::esutil::Array2D< T, outlier_mode >::begin () const [inline, inherited]
Returns a const_iterator pointing to the beginning of the Array2D.
Definition at line 184 of file Array2D.hpp.
void espressopp::esutil::Array2D< T, outlier_mode >::clear () [inline, inherited]
Erases all elements.
Definition at line 72 of file Array2D.hpp.
bool espressopp::esutil::Array2D< T, outlier_mode >::empty () const [inline, inherited]
true if the Array2D's size is 0 x 0.
Definition at line 112 of file Array2D.hpp.
iterator espressopp::esutil::Array2D< T, outlier_mode >::end () [inline, inherited]
Returns an iterator pointing to the end of the Array2D.
Definition at line 188 of file Array2D.hpp.
const_iterator espressopp::esutil::Array2D< T, outlier_mode >::end () const [inline, inherited]
Returns a const_iterator pointing to the end of the Array2D.
Definition at line 192 of file Array2D.hpp.
template<class T > void espressopp::esutil::Array2D< T, enlarge >::init (size_type n, size_type m, const T & prototype = T()) [inline]
Creates a one-dimensional array of size n with n copies of prototype.
Also sets the prototype.
Reimplemented from espressopp::esutil::Array2D< T, exception >.
Definition at line 280 of file Array2D.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::init().
bool espressopp::esutil::Array2D< T, outlier_mode >::operator!= (const Array2D< T, exception > & a) [inline, inherited]
Inequality operator.
Definition at line 234 of file Array2D.hpp.
reference espressopp::esutil::Array2D< T, outlier_mode >::operator() (size_type i, size_type j) [inline, inherited]
Returns the element at position i x j.
Attention:
No range checking.
Definition at line 116 of file Array2D.hpp.
const_reference espressopp::esutil::Array2D< T, outlier_mode >::operator() (size_type i, size_type j) const [inline, inherited]
Returns the element at position i x j.
Attention:
No range checking.
Definition at line 121 of file Array2D.hpp.
reference espressopp::esutil::Array2D< T, outlier_mode >::operator() (const Vector & pos) [inline, inherited]
Returns the element at position pos.
pos must be a vector where the expressions pos[0] and pos[1] return the indices.
Attention:
No range checking.
Definition at line 130 of file Array2D.hpp.
const_reference espressopp::esutil::Array2D< T, outlier_mode >::operator() (const Vector & pos) const [inline, inherited]
Returns the element at position pos.
pos must be a vector where the expressions pos[0] and pos[1] return the indices.
Attention:
No range checking.
Definition at line 139 of file Array2D.hpp.
void espressopp::esutil::Array2D< T, outlier_mode >::operator*= (const T2 & t2) [inline, inherited]
Multiplies each of the elements by t2.
Definition at line 214 of file Array2D.hpp.
void espressopp::esutil::Array2D< T, outlier_mode >::operator+= (const T2 & t2) [inline, inherited]
Adds t2 to each of the elements.
Definition at line 202 of file Array2D.hpp.
void espressopp::esutil::Array2D< T, outlier_mode >::operator-= (const T2 & t2) [inline, inherited]
Adds t2 to each of the elements.
Definition at line 208 of file Array2D.hpp.
void espressopp::esutil::Array2D< T, outlier_mode >::operator/= (const T2 & t2) [inline, inherited]
Divides each of the elements by t2.
Definition at line 219 of file Array2D.hpp.
void espressopp::esutil::Array2D< T, outlier_mode >::operator/= (const double & x) [inline, inherited]
Definition at line 222 of file Array2D.hpp.
bool espressopp::esutil::Array2D< T, outlier_mode >::operator== (const Array2D< T, exception > & a) [inline, inherited]
Equality operator.
Definition at line 228 of file Array2D.hpp.
void espressopp::esutil::Array2D< T, outlier_mode >::resize (size_type n, size_type m, const T & t = T()) [inline, inherited]
Changes the size of the Array2D so that the size becomes n x m.
Attention:
The elements of the Array2D are not initialised consistently, so the values are undefined. The t parameter exists only for the purpose to provide a default T value when new elements are created and needs to be specified only when T has no default constructor.
Definition at line 95 of file Array2D.hpp.
template<class T > void espressopp::esutil::Array2D< T, enlarge >::set_prototype (const T & prototype = T()) [inline]
Sets the prototype used when the Array2D<T,enlarge> is automatically resized.
Definition at line 285 of file Array2D.hpp.
size_type espressopp::esutil::Array2D< T, outlier_mode >::size_m () const [inline, inherited]
Returns the m -size of the array.
Definition at line 107 of file Array2D.hpp.
size_type espressopp::esutil::Array2D< T, outlier_mode >::size_n () const [inline, inherited]
Returns the n -size of the array.
Definition at line 102 of file Array2D.hpp.
size_type espressopp::esutil::Array2D< T, outlier_mode >::size_x () const [inline, inherited]
Returns the n -size of the array.
Definition at line 104 of file Array2D.hpp.
size_type espressopp::esutil::Array2D< T, outlier_mode >::size_y () const [inline, inherited]
Returns the m -size of the array.
Definition at line 109 of file Array2D.hpp.
Member Data Documentation
template<class T > value_type espressopp::esutil::Array2D< T, enlarge >::prototype [private]
Definition at line 334 of file Array2D.hpp.
The documentation for this class was generated from the following file:
/home/travis/build/espressopp/espressopp/src/esutil/Array2D.hpp