ESPResSo++: espressopp::interaction::CoulombKSpaceEwald Class Reference
espressopp::interaction::CoulombKSpaceEwald Class Reference
This class provides methods to compute forces and energies of the CoulombKSpaceEwald part.
#include <CoulombKSpaceEwald.hpp>
Public Member Functions
CoulombKSpaceEwald (shared_ptr< System > _system, real _prefactor, real _alpha, int _kmax)
~CoulombKSpaceEwald ()
void preset ()
void getParticleNumber ()
void count_charges (CellList realcells)
void setPrefactor (real _prefactor)
real getPrefactor () const
void setAlpha (real _alpha)
real getAlpha () const
void setKMax (int _kmax)
int getKMax () const
void exponentPrecalculation (CellList realcells)
real _computeEnergy (CellList realcells)
bool _computeForce (CellList realcells)
real _computeVirial (CellList realcells)
Tensor _computeVirialTensor (CellList realcells)
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &dist, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)
virtual shared_ptr< FixedPairList > getColVarBondList () const
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &fpl)
virtual shared_ptr< FixedTripleList > getColVarAngleList () const
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fpl)
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const
virtual void setColVar (const RealND &cv)
virtual void setColVar (const Real3D &dist, const bc::BC &bc)
virtual RealND getColVar () const
virtual void computeColVarWeights (const Real3D &dist, const bc::BC &bc)
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
real _computeEnergyDeriv (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
CoulombKSpaceEwald * derived_this ()
const CoulombKSpaceEwald * derived_this () const
Protected Attributes
boost::signals2::connection connectionRecalcKVec
boost::signals2::connection connectionGetParticleNumber
real cutoff
real cutoffSqr
real shift
bool autoShift
shared_ptr< FixedPairList > colVarBondList
shared_ptr< FixedTripleList > colVarAngleList
shared_ptr< FixedQuadrupleList > colVarDihedList
RealND colVar
Private Attributes
real prefactor
real alpha
int kmax
shared_ptr< System > system
real Lx
real Ly
real Lz
int nParticles
real rclx
real rcly
real rclz
real force_prefac [3]
vector< real > kvector
int kVectorLength
vector< int > kxfield
vector< int > kyfield
vector< int > kzfield
vector< int > kx_ind
vector< int > ky_ind
vector< int > kz_ind
vector< real > virialPref
vector< Tensor > virialTensorPref
Tensor I
vector< vector< dcomplex > > eikx
vector< vector< dcomplex > > eiky
vector< vector< dcomplex > > eikz
vector< vector< dcomplex > > eik
real sum_q2
dcomplex * sum
dcomplex * totsum
Detailed Description
This class provides methods to compute forces and energies of the CoulombKSpaceEwald part.
Currently it works with cubes and rectangular cuboids. Does not work for triclinic box, slab geometry.
Definition at line 71 of file CoulombKSpaceEwald.hpp.
Constructor & Destructor Documentation
CoulombKSpaceEwald()
espressopp::interaction::CoulombKSpaceEwald::CoulombKSpaceEwald (shared_ptr< System > _system, real _prefactor, real _alpha, int _kmax)
Definition at line 33 of file CoulombKSpaceEwald.cpp.
References alpha, connectionGetParticleNumber, connectionRecalcKVec, count_charges(), getParticleNumber(), I, kmax, prefactor, preset(), sum, system, and totsum.
~CoulombKSpaceEwald()
espressopp::interaction::CoulombKSpaceEwald::~CoulombKSpaceEwald ()
Definition at line 56 of file CoulombKSpaceEwald.cpp.
References sum, and totsum.
Member Function Documentation
_computeEnergy() [1/5]
real espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::_computeEnergy (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 352 of file Potential.hpp.
_computeEnergy() [2/5]
real espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::_computeEnergy (const Real3D & dist) const inline inherited
Definition at line 367 of file Potential.hpp.
_computeEnergy() [3/5]
real espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::_computeEnergy (real dist) const inline inherited
Definition at line 374 of file Potential.hpp.
_computeEnergy() [4/5]
real espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 360 of file Potential.hpp.
_computeEnergy() [5/5]
real espressopp::interaction::CoulombKSpaceEwald::_computeEnergy (CellList realcells) inline
Definition at line 319 of file CoulombKSpaceEwald.hpp.
References M_1_SQRTPI.
_computeEnergyDeriv()
real espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::_computeEnergyDeriv (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 395 of file Potential.hpp.
_computeEnergySqr()
real espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::_computeEnergySqr (real distSqr) const inline inherited
Definition at line 381 of file Potential.hpp.
_computeEnergySqrRaw()
real espressopp::interaction::CoulombKSpaceEwald::_computeEnergySqrRaw (real distSqr) const inline
Definition at line 457 of file CoulombKSpaceEwald.hpp.
References espressopp::esutil::Error::setException().
_computeForce() [1/4]
bool espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const inline inherited
Definition at line 423 of file Potential.hpp.
_computeForce() [2/4]
bool espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::_computeForce (Real3D & force, const Real3D & dist) const inline inherited
Definition at line 438 of file Potential.hpp.
_computeForce() [3/4]
bool espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 431 of file Potential.hpp.
_computeForce() [4/4]
bool espressopp::interaction::CoulombKSpaceEwald::_computeForce (CellList realcells) inline
Definition at line 356 of file CoulombKSpaceEwald.hpp.
References espressopp::Particle::force(), espressopp::iterator::CellListIterator::isDone(), and espressopp::Particle::q().
_computeForceRaw()
bool espressopp::interaction::CoulombKSpaceEwald::_computeForceRaw (Real3D & force, const Real3D & dist, real distSqr) const inline
Definition at line 464 of file CoulombKSpaceEwald.hpp.
References espressopp::esutil::Error::setException().
_computeVirial()
real espressopp::interaction::CoulombKSpaceEwald::_computeVirial (CellList realcells) inline
Definition at line 390 of file CoulombKSpaceEwald.hpp.
_computeVirialTensor()
Tensor espressopp::interaction::CoulombKSpaceEwald::_computeVirialTensor (CellList realcells) inline
Definition at line 422 of file CoulombKSpaceEwald.hpp.
computeColVarWeights()
void espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::computeColVarWeights (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 315 of file Potential.hpp.
computeEnergy() [1/3]
real espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::computeEnergy (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 323 of file Potential.hpp.
computeEnergy() [2/3]
real espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::computeEnergy (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 331 of file Potential.hpp.
computeEnergy() [3/3]
real espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::computeEnergy (real dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 338 of file Potential.hpp.
computeEnergySqr()
real espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::computeEnergySqr (real distsqr) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 345 of file Potential.hpp.
computeForce() [1/2]
Real3D espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::computeForce (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 405 of file Potential.hpp.
computeForce() [2/2]
Real3D espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::computeForce (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 413 of file Potential.hpp.
count_charges()
void espressopp::interaction::CoulombKSpaceEwald::count_charges (CellList realcells) inline
Definition at line 234 of file CoulombKSpaceEwald.hpp.
References espressopp::iterator::CellListIterator::isDone(), and espressopp::Particle::q().
Referenced by CoulombKSpaceEwald().
derived_this() [1/2]
CoulombKSpaceEwald * espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::derived_this () inline protected inherited
Definition at line 161 of file Potential.hpp.
derived_this() [2/2]
const CoulombKSpaceEwald * espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::derived_this () const inline protected inherited
Definition at line 165 of file Potential.hpp.
exponentPrecalculation()
void espressopp::interaction::CoulombKSpaceEwald::exponentPrecalculation (CellList realcells) inline
Definition at line 262 of file CoulombKSpaceEwald.hpp.
References espressopp::iterator::CellListIterator::isDone(), espressopp::Particle::position(), and espressopp::Particle::q().
getAlpha()
real espressopp::interaction::CoulombKSpaceEwald::getAlpha () const inline
Definition at line 254 of file CoulombKSpaceEwald.hpp.
Referenced by registerPython().
getColVar()
RealND espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::getColVar () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 309 of file Potential.hpp.
getColVarAngleList()
shared_ptr< FixedTripleList > espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::getColVarAngleList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 273 of file Potential.hpp.
getColVarBondList()
shared_ptr< FixedPairList > espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::getColVarBondList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 259 of file Potential.hpp.
getColVarDihedList()
shared_ptr< FixedQuadrupleList > espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::getColVarDihedList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 287 of file Potential.hpp.
getCutoff()
real espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 210 of file Potential.hpp.
getKMax()
int espressopp::interaction::CoulombKSpaceEwald::getKMax () const inline
Definition at line 259 of file CoulombKSpaceEwald.hpp.
Referenced by registerPython().
getParticleNumber()
void espressopp::interaction::CoulombKSpaceEwald::getParticleNumber () inline
Definition at line 223 of file CoulombKSpaceEwald.hpp.
Referenced by CoulombKSpaceEwald().
getPrefactor()
real espressopp::interaction::CoulombKSpaceEwald::getPrefactor () const inline
Definition at line 249 of file CoulombKSpaceEwald.hpp.
Referenced by registerPython().
getShift()
real espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::getShift () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 225 of file Potential.hpp.
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
Referenced by espressopp::interaction::Potential::~Potential().
preset()
void espressopp::interaction::CoulombKSpaceEwald::preset () inline
Definition at line 121 of file CoulombKSpaceEwald.hpp.
References M_2PI, and M_PI2.
Referenced by CoulombKSpaceEwald().
registerPython()
void espressopp::interaction::CoulombKSpaceEwald::registerPython () static
Definition at line 66 of file CoulombKSpaceEwald.cpp.
References getAlpha(), getKMax(), getPrefactor(), setAlpha(), setKMax(), and setPrefactor().
Referenced by espressopp::interaction::registerPython().
setAlpha()
void espressopp::interaction::CoulombKSpaceEwald::setAlpha (real _alpha) inline
Definition at line 250 of file CoulombKSpaceEwald.hpp.
Referenced by registerPython().
setAutoShift()
real espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::setAutoShift () inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 231 of file Potential.hpp.
setColVar() [1/2]
void espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::setColVar (const RealND & cv) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 294 of file Potential.hpp.
setColVar() [2/2]
void espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::setColVar (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 301 of file Potential.hpp.
setColVarAngleList()
void espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::setColVarAngleList (const shared_ptr< FixedTripleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 266 of file Potential.hpp.
setColVarBondList()
void espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::setColVarBondList (const shared_ptr< FixedPairList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 252 of file Potential.hpp.
setColVarDihedList()
void espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 280 of file Potential.hpp.
setCutoff()
void espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 201 of file Potential.hpp.
setKMax()
void espressopp::interaction::CoulombKSpaceEwald::setKMax (int _kmax) inline
Definition at line 255 of file CoulombKSpaceEwald.hpp.
Referenced by registerPython().
setPrefactor()
void espressopp::interaction::CoulombKSpaceEwald::setPrefactor (real _prefactor) inline
Definition at line 245 of file CoulombKSpaceEwald.hpp.
Referenced by registerPython().
setShift()
void espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::setShift (real _shift) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 216 of file Potential.hpp.
updateAutoShift()
void espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::updateAutoShift () inline inherited
Definition at line 244 of file Potential.hpp.
Member Data Documentation
alpha
real espressopp::interaction::CoulombKSpaceEwald::alpha private
Definition at line 74 of file CoulombKSpaceEwald.hpp.
Referenced by CoulombKSpaceEwald().
autoShift
bool espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::autoShift protected inherited
Definition at line 151 of file Potential.hpp.
colVar
RealND espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::colVar protected inherited
Definition at line 159 of file Potential.hpp.
colVarAngleList
shared_ptr<FixedTripleList> espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::colVarAngleList protected inherited
Definition at line 155 of file Potential.hpp.
colVarBondList
shared_ptr<FixedPairList> espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::colVarBondList protected inherited
Definition at line 153 of file Potential.hpp.
colVarDihedList
shared_ptr<FixedQuadrupleList> espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::colVarDihedList protected inherited
Definition at line 157 of file Potential.hpp.
connectionGetParticleNumber
boost::signals2::connection espressopp::interaction::CoulombKSpaceEwald::connectionGetParticleNumber protected
Definition at line 476 of file CoulombKSpaceEwald.hpp.
Referenced by CoulombKSpaceEwald().
connectionRecalcKVec
boost::signals2::connection espressopp::interaction::CoulombKSpaceEwald::connectionRecalcKVec protected
Definition at line 474 of file CoulombKSpaceEwald.hpp.
Referenced by CoulombKSpaceEwald().
cutoff
real espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::cutoff protected inherited
Definition at line 148 of file Potential.hpp.
cutoffSqr
real espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::cutoffSqr protected inherited
Definition at line 149 of file Potential.hpp.
eik
vector< vector<dcomplex> > espressopp::interaction::CoulombKSpaceEwald::eik private
Definition at line 107 of file CoulombKSpaceEwald.hpp.
eikx
vector< vector<dcomplex> > espressopp::interaction::CoulombKSpaceEwald::eikx private
Definition at line 103 of file CoulombKSpaceEwald.hpp.
eiky
vector< vector<dcomplex> > espressopp::interaction::CoulombKSpaceEwald::eiky private
Definition at line 104 of file CoulombKSpaceEwald.hpp.
eikz
vector< vector<dcomplex> > espressopp::interaction::CoulombKSpaceEwald::eikz private
Definition at line 105 of file CoulombKSpaceEwald.hpp.
force_prefac
real espressopp::interaction::CoulombKSpaceEwald::force_prefac[3] private
Definition at line 83 of file CoulombKSpaceEwald.hpp.
I
Tensor espressopp::interaction::CoulombKSpaceEwald::I private
Definition at line 100 of file CoulombKSpaceEwald.hpp.
Referenced by CoulombKSpaceEwald().
kmax
int espressopp::interaction::CoulombKSpaceEwald::kmax private
Definition at line 75 of file CoulombKSpaceEwald.hpp.
Referenced by CoulombKSpaceEwald().
kvector
vector<real> espressopp::interaction::CoulombKSpaceEwald::kvector private
Definition at line 85 of file CoulombKSpaceEwald.hpp.
kVectorLength
int espressopp::interaction::CoulombKSpaceEwald::kVectorLength private
Definition at line 86 of file CoulombKSpaceEwald.hpp.
kx_ind
vector<int> espressopp::interaction::CoulombKSpaceEwald::kx_ind private
Definition at line 93 of file CoulombKSpaceEwald.hpp.
kxfield
vector<int> espressopp::interaction::CoulombKSpaceEwald::kxfield private
Definition at line 89 of file CoulombKSpaceEwald.hpp.
ky_ind
vector<int> espressopp::interaction::CoulombKSpaceEwald::ky_ind private
Definition at line 94 of file CoulombKSpaceEwald.hpp.
kyfield
vector<int> espressopp::interaction::CoulombKSpaceEwald::kyfield private
Definition at line 90 of file CoulombKSpaceEwald.hpp.
kz_ind
vector<int> espressopp::interaction::CoulombKSpaceEwald::kz_ind private
Definition at line 95 of file CoulombKSpaceEwald.hpp.
kzfield
vector<int> espressopp::interaction::CoulombKSpaceEwald::kzfield private
Definition at line 91 of file CoulombKSpaceEwald.hpp.
Lx
real espressopp::interaction::CoulombKSpaceEwald::Lx private
Definition at line 80 of file CoulombKSpaceEwald.hpp.
Ly
real espressopp::interaction::CoulombKSpaceEwald::Ly private
Definition at line 80 of file CoulombKSpaceEwald.hpp.
Lz
real espressopp::interaction::CoulombKSpaceEwald::Lz private
Definition at line 80 of file CoulombKSpaceEwald.hpp.
nParticles
int espressopp::interaction::CoulombKSpaceEwald::nParticles private
Definition at line 81 of file CoulombKSpaceEwald.hpp.
prefactor
real espressopp::interaction::CoulombKSpaceEwald::prefactor private
Definition at line 73 of file CoulombKSpaceEwald.hpp.
Referenced by CoulombKSpaceEwald().
rclx
real espressopp::interaction::CoulombKSpaceEwald::rclx private
Definition at line 82 of file CoulombKSpaceEwald.hpp.
rcly
real espressopp::interaction::CoulombKSpaceEwald::rcly private
Definition at line 82 of file CoulombKSpaceEwald.hpp.
rclz
real espressopp::interaction::CoulombKSpaceEwald::rclz private
Definition at line 82 of file CoulombKSpaceEwald.hpp.
shift
real espressopp::interaction::PotentialTemplate< CoulombKSpaceEwald >::shift protected inherited
Definition at line 150 of file Potential.hpp.
sum
dcomplex* espressopp::interaction::CoulombKSpaceEwald::sum private
Definition at line 111 of file CoulombKSpaceEwald.hpp.
Referenced by CoulombKSpaceEwald(), and ~CoulombKSpaceEwald().
sum_q2
real espressopp::interaction::CoulombKSpaceEwald::sum_q2 private
Definition at line 109 of file CoulombKSpaceEwald.hpp.
system
shared_ptr< System > espressopp::interaction::CoulombKSpaceEwald::system private
Definition at line 77 of file CoulombKSpaceEwald.hpp.
Referenced by CoulombKSpaceEwald().
totsum
dcomplex* espressopp::interaction::CoulombKSpaceEwald::totsum private
Definition at line 112 of file CoulombKSpaceEwald.hpp.
Referenced by CoulombKSpaceEwald(), and ~CoulombKSpaceEwald().
virialPref
vector<real> espressopp::interaction::CoulombKSpaceEwald::virialPref private
Definition at line 98 of file CoulombKSpaceEwald.hpp.
virialTensorPref
vector<Tensor> espressopp::interaction::CoulombKSpaceEwald::virialTensorPref private
Definition at line 99 of file CoulombKSpaceEwald.hpp.
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/CoulombKSpaceEwald.hpp
/home/espressopp/espressopp/src/interaction/CoulombKSpaceEwald.cpp