ESPResSo++: espressopp::interaction::DihedralRB Class Reference
espressopp::interaction::DihedralRB Class Reference
This class provides methods to compute forces and energies of the Ryckaert-Bellemans dihedral potential.
#include <DihedralRB.hpp>
Public Member Functions
DihedralRB ()
DihedralRB (real _K0, real _K1, real _K2, real _K3, real _K4, real _K5)
real _computeEnergyRaw (real _phi) const
real d (int i, int j) const
Real3D prod (Real3D a, Real3D b) const
void _computeForceRaw (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &r21, const Real3D &r32, const Real3D &r43) const
real _computeForceRaw (real phi) const
virtual real computeEnergy (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
virtual real computeEnergy (real phi) const
virtual void computeForce (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
virtual real computeForce (real phi) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)
virtual shared_ptr< FixedPairList > getColVarBondList () const
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &ftl)
virtual shared_ptr< FixedTripleList > getColVarAngleList () const
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fql)
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const
virtual void setColVar (const RealND &cv)
virtual void setColVar (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43, const bc::BC &bc)
virtual RealND getColVar () const
virtual void computeColVarWeights (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43, const bc::BC &bc)
real _computeEnergy (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
real _computeEnergy (real phi) const
void _computeForce (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
Static Public Member Functions
static void registerPython ()
static real computePhi (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43)
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
DihedralRB * derived_this ()
const DihedralRB * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
shared_ptr< FixedPairList > colVarBondList
shared_ptr< FixedTripleList > colVarAngleList
shared_ptr< FixedQuadrupleList > colVarDihedList
RealND colVar
Private Attributes
real K0
real K1
real K2
real K3
real K4
real K5
Detailed Description
This class provides methods to compute forces and energies of the Ryckaert-Bellemans dihedral potential.
Definition at line 33 of file DihedralRB.hpp.
Constructor & Destructor Documentation
DihedralRB() [1/2]
espressopp::interaction::DihedralRB::DihedralRB () inline
Definition at line 45 of file DihedralRB.hpp.
DihedralRB() [2/2]
espressopp::interaction::DihedralRB::DihedralRB (real _K0, real _K1, real _K2, real _K3, real _K4, real _K5) inline
Definition at line 46 of file DihedralRB.hpp.
Member Function Documentation
_computeEnergy() [1/2]
real espressopp::interaction::DihedralPotentialTemplate< DihedralRB >::_computeEnergy (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline inherited
Definition at line 285 of file DihedralPotential.hpp.
_computeEnergy() [2/2]
real espressopp::interaction::DihedralPotentialTemplate< DihedralRB >::_computeEnergy (real phi) const inline inherited
Definition at line 295 of file DihedralPotential.hpp.
_computeEnergyRaw()
real espressopp::interaction::DihedralRB::_computeEnergyRaw (real _phi) const inline
Definition at line 49 of file DihedralRB.hpp.
_computeForce()
void espressopp::interaction::DihedralPotentialTemplate< DihedralRB >::_computeForce (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline inherited
Definition at line 317 of file DihedralPotential.hpp.
_computeForceRaw() [1/2]
void espressopp::interaction::DihedralRB::_computeForceRaw (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & r21, const Real3D & r32, const Real3D & r43) const inline
Derivative of the potential.
Calculates force in Cartesian coordinates. base on: http://www.ccp5.ac.uk/DL_POLY_CLASSIC/MANUALS/USRMAN.pdf
Definition at line 77 of file DihedralRB.hpp.
References espressopp::Real3D::cross(), d(), prod(), and espressopp::Real3D::sqr().
_computeForceRaw() [2/2]
real espressopp::interaction::DihedralRB::_computeForceRaw (real phi) const inline
Definition at line 156 of file DihedralRB.hpp.
computeColVarWeights()
void espressopp::interaction::DihedralPotentialTemplate< DihedralRB >::computeColVarWeights (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 256 of file DihedralPotential.hpp.
computeEnergy() [1/2]
real espressopp::interaction::DihedralPotentialTemplate< DihedralRB >::computeEnergy (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 265 of file DihedralPotential.hpp.
computeEnergy() [2/2]
real espressopp::interaction::DihedralPotentialTemplate< DihedralRB >::computeEnergy (real phi) const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 278 of file DihedralPotential.hpp.
computeForce() [1/2]
void espressopp::interaction::DihedralPotentialTemplate< DihedralRB >::computeForce (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 303 of file DihedralPotential.hpp.
computeForce() [2/2]
real espressopp::interaction::DihedralPotentialTemplate< DihedralRB >::computeForce (real phi) const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 331 of file DihedralPotential.hpp.
computePhi()
real espressopp::interaction::DihedralPotential::computePhi (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) static inherited
Definition at line 31 of file DihedralPotential.cpp.
References espressopp::Real3D::abs(), espressopp::Real3D::cross(), and espressopp::interaction::LOG4ESPP_LOGGER().
Referenced by espressopp::interaction::DihedralPotential::registerPython(), espressopp::interaction::TabulatedSubEnsDihedral::setColVar(), espressopp::interaction::TabulatedSubEnsAngular::setColVar(), and espressopp::interaction::TabulatedSubEns::setColVar().
d()
real espressopp::interaction::DihedralRB::d (int i, int j) const inline
Definition at line 62 of file DihedralRB.hpp.
Referenced by _computeForceRaw(), and prod().
derived_this() [1/2]
DihedralRB * espressopp::interaction::DihedralPotentialTemplate< DihedralRB >::derived_this () inline protected inherited
Definition at line 154 of file DihedralPotential.hpp.
derived_this() [2/2]
const DihedralRB * espressopp::interaction::DihedralPotentialTemplate< DihedralRB >::derived_this () const inline protected inherited
Definition at line 158 of file DihedralPotential.hpp.
getColVar()
RealND espressopp::interaction::DihedralPotentialTemplate< DihedralRB >::getColVar () const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 250 of file DihedralPotential.hpp.
getColVarAngleList()
shared_ptr< FixedTripleList > espressopp::interaction::DihedralPotentialTemplate< DihedralRB >::getColVarAngleList () const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 213 of file DihedralPotential.hpp.
getColVarBondList()
shared_ptr< FixedPairList > espressopp::interaction::DihedralPotentialTemplate< DihedralRB >::getColVarBondList () const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 199 of file DihedralPotential.hpp.
getColVarDihedList()
shared_ptr< FixedQuadrupleList > espressopp::interaction::DihedralPotentialTemplate< DihedralRB >::getColVarDihedList () const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 227 of file DihedralPotential.hpp.
getCutoff()
real espressopp::interaction::DihedralPotentialTemplate< DihedralRB >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 185 of file DihedralPotential.hpp.
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::DihedralPotential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
prod()
Real3D espressopp::interaction::DihedralRB::prod (Real3D a, Real3D b) const inline
Definition at line 69 of file DihedralRB.hpp.
References d().
Referenced by _computeForceRaw().
registerPython()
void espressopp::interaction::DihedralRB::registerPython () static
Definition at line 29 of file DihedralRB.cpp.
Referenced by espressopp::interaction::registerPython().
setColVar() [1/2]
void espressopp::interaction::DihedralPotentialTemplate< DihedralRB >::setColVar (const RealND & cv) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 234 of file DihedralPotential.hpp.
setColVar() [2/2]
void espressopp::interaction::DihedralPotentialTemplate< DihedralRB >::setColVar (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 241 of file DihedralPotential.hpp.
setColVarAngleList()
void espressopp::interaction::DihedralPotentialTemplate< DihedralRB >::setColVarAngleList (const shared_ptr< FixedTripleList > & ftl) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 206 of file DihedralPotential.hpp.
setColVarBondList()
void espressopp::interaction::DihedralPotentialTemplate< DihedralRB >::setColVarBondList (const shared_ptr< FixedPairList > & fpl) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 192 of file DihedralPotential.hpp.
setColVarDihedList()
void espressopp::interaction::DihedralPotentialTemplate< DihedralRB >::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fql) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 220 of file DihedralPotential.hpp.
setCutoff()
void espressopp::interaction::DihedralPotentialTemplate< DihedralRB >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::DihedralPotential.
Definition at line 177 of file DihedralPotential.hpp.
Member Data Documentation
colVar
RealND espressopp::interaction::DihedralPotentialTemplate< DihedralRB >::colVar protected inherited
Definition at line 152 of file DihedralPotential.hpp.
colVarAngleList
shared_ptr<FixedTripleList> espressopp::interaction::DihedralPotentialTemplate< DihedralRB >::colVarAngleList protected inherited
Definition at line 148 of file DihedralPotential.hpp.
colVarBondList
shared_ptr<FixedPairList> espressopp::interaction::DihedralPotentialTemplate< DihedralRB >::colVarBondList protected inherited
Definition at line 146 of file DihedralPotential.hpp.
colVarDihedList
shared_ptr<FixedQuadrupleList> espressopp::interaction::DihedralPotentialTemplate< DihedralRB >::colVarDihedList protected inherited
Definition at line 150 of file DihedralPotential.hpp.
cutoff
real espressopp::interaction::DihedralPotentialTemplate< DihedralRB >::cutoff protected inherited
Definition at line 143 of file DihedralPotential.hpp.
cutoffSqr
real espressopp::interaction::DihedralPotentialTemplate< DihedralRB >::cutoffSqr protected inherited
Definition at line 144 of file DihedralPotential.hpp.
K0
real espressopp::interaction::DihedralRB::K0 private
Definition at line 35 of file DihedralRB.hpp.
K1
real espressopp::interaction::DihedralRB::K1 private
Definition at line 36 of file DihedralRB.hpp.
K2
real espressopp::interaction::DihedralRB::K2 private
Definition at line 37 of file DihedralRB.hpp.
K3
real espressopp::interaction::DihedralRB::K3 private
Definition at line 38 of file DihedralRB.hpp.
K4
real espressopp::interaction::DihedralRB::K4 private
Definition at line 39 of file DihedralRB.hpp.
K5
real espressopp::interaction::DihedralRB::K5 private
Definition at line 40 of file DihedralRB.hpp.
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/DihedralRB.hpp
/home/espressopp/espressopp/src/interaction/DihedralRB.cpp