ESPResSo++: espressopp::interaction::PotentialUniqueDist Class Reference
espressopp::interaction::PotentialUniqueDist Class Reference abstract
#include <PotentialUniqueDist.hpp>
Public Member Functions
virtual ~PotentialUniqueDist ()
virtual real computeEnergy (const Particle &p1, const Particle &p2, const real curDist) const =0
virtual real computeEnergy (const Real3D &r21, const real curDist) const =0
virtual real computeEnergy (real dist, real curDist) const =0
virtual real computeEnergySqr (real distSqr, real curDist) const =0
virtual Real3D computeForce (const Particle &p1, const Particle &p2, const real curDist) const =0
virtual Real3D computeForce (const Real3D &dist, const real curDist) const =0
virtual void setCutoff (real _cutoff)=0
virtual real getCutoff () const =0
virtual void setShift (real _shift)=0
virtual real getShift () const =0
virtual real setAutoShift ()=0
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Detailed Description
Definition at line 34 of file PotentialUniqueDist.hpp.
Constructor & Destructor Documentation
~PotentialUniqueDist()
virtual espressopp::interaction::PotentialUniqueDist::~PotentialUniqueDist () inline virtual
Definition at line 36 of file PotentialUniqueDist.hpp.
References computeEnergy(), computeEnergySqr(), computeForce(), getCutoff(), getShift(), LOG4ESPP_DECL_LOGGER(), registerPython(), setAutoShift(), setCutoff(), and setShift().
Member Function Documentation
computeEnergy() [1/3]
virtual real espressopp::interaction::PotentialUniqueDist::computeEnergy (const Particle & p1, const Particle & p2, const real curDist) const pure virtual
Implemented in espressopp::interaction::PotentialUniqueDistTemplate< Derived >, and espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >.
Referenced by registerPython(), ~PotentialUniqueDist(), and espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::~PotentialUniqueDistTemplate().
computeEnergy() [2/3]
virtual real espressopp::interaction::PotentialUniqueDist::computeEnergy (const Real3D & r21, const real curDist) const pure virtual
Implemented in espressopp::interaction::PotentialUniqueDistTemplate< Derived >, and espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >.
computeEnergy() [3/3]
virtual real espressopp::interaction::PotentialUniqueDist::computeEnergy (real dist, real curDist) const pure virtual
Implemented in espressopp::interaction::PotentialUniqueDistTemplate< Derived >, and espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >.
computeEnergySqr()
virtual real espressopp::interaction::PotentialUniqueDist::computeEnergySqr (real distSqr, real curDist) const pure virtual
Implemented in espressopp::interaction::PotentialUniqueDistTemplate< Derived >, and espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >.
Referenced by ~PotentialUniqueDist(), and espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::~PotentialUniqueDistTemplate().
computeForce() [1/2]
virtual Real3D espressopp::interaction::PotentialUniqueDist::computeForce (const Particle & p1, const Particle & p2, const real curDist) const pure virtual
Implemented in espressopp::interaction::PotentialUniqueDistTemplate< Derived >, and espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >.
Referenced by registerPython(), ~PotentialUniqueDist(), and espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::~PotentialUniqueDistTemplate().
computeForce() [2/2]
virtual Real3D espressopp::interaction::PotentialUniqueDist::computeForce (const Real3D & dist, const real curDist) const pure virtual
Implemented in espressopp::interaction::PotentialUniqueDistTemplate< Derived >, and espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >.
getCutoff()
virtual real espressopp::interaction::PotentialUniqueDist::getCutoff () const pure virtual
Implemented in espressopp::interaction::PotentialUniqueDistTemplate< Derived >, and espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >.
Referenced by registerPython(), ~PotentialUniqueDist(), and espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::~PotentialUniqueDistTemplate().
getShift()
virtual real espressopp::interaction::PotentialUniqueDist::getShift () const pure virtual
Implemented in espressopp::interaction::PotentialUniqueDistTemplate< Derived >, and espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >.
Referenced by registerPython(), ~PotentialUniqueDist(), and espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::~PotentialUniqueDistTemplate().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::PotentialUniqueDist::LOG4ESPP_DECL_LOGGER (theLogger) static
Referenced by ~PotentialUniqueDist().
registerPython()
void espressopp::interaction::PotentialUniqueDist::registerPython () static
Definition at line 35 of file PotentialUniqueDist.cpp.
References computeEnergy(), computeForce(), getCutoff(), getShift(), setAutoShift(), setCutoff(), and setShift().
Referenced by espressopp::interaction::registerPython(), and ~PotentialUniqueDist().
setAutoShift()
virtual real espressopp::interaction::PotentialUniqueDist::setAutoShift () pure virtual
Implemented in espressopp::interaction::PotentialUniqueDistTemplate< Derived >, and espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >.
Referenced by registerPython(), ~PotentialUniqueDist(), and espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::~PotentialUniqueDistTemplate().
setCutoff()
virtual void espressopp::interaction::PotentialUniqueDist::setCutoff (real _cutoff) pure virtual
Implemented in espressopp::interaction::PotentialUniqueDistTemplate< Derived >, and espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >.
Referenced by registerPython(), ~PotentialUniqueDist(), and espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::~PotentialUniqueDistTemplate().
setShift()
virtual void espressopp::interaction::PotentialUniqueDist::setShift (real _shift) pure virtual
Implemented in espressopp::interaction::PotentialUniqueDistTemplate< Derived >, and espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >.
Referenced by registerPython(), ~PotentialUniqueDist(), and espressopp::interaction::PotentialUniqueDistTemplate< HarmonicUnique >::~PotentialUniqueDistTemplate().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/PotentialUniqueDist.hpp
/home/espressopp/espressopp/src/interaction/PotentialUniqueDist.cpp