ESPResSo++: espressopp::interaction::FENECapped Class Reference
espressopp::interaction::FENECapped Class Reference
This class provides methods to compute forces and energies of the FENECapped potential.
#include <FENECapped.hpp>
Public Member Functions
FENECapped ()
FENECapped (real _K, real _r0, real _rMax, real _cutoff, real _caprad, real _shift)
FENECapped (real _K, real _r0, real _rMax, real _cutoff, real _caprad)
void setK (real _K)
real getK () const
void setcaprad (real _caprad)
real getcaprad () const
void setR0 (real _r0)
real getR0 () const
void setRMax (real _rMax)
real getRMax () const
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &dist, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
real _computeEnergyDeriv (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
FENECapped * derived_this ()
const FENECapped * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
Private Attributes
real K
real r0
real rMax
real caprad
Detailed Description
This class provides methods to compute forces and energies of the FENECapped potential.
Definition at line 40 of file FENECapped.hpp.
Constructor & Destructor Documentation
FENECapped() [1/3]
espressopp::interaction::FENECapped::FENECapped () inline
Definition at line 50 of file FENECapped.hpp.
References espressopp::infinity, espressopp::interaction::PotentialTemplate< FENECapped >::setCutoff(), and espressopp::interaction::PotentialTemplate< FENECapped >::setShift().
FENECapped() [2/3]
espressopp::interaction::FENECapped::FENECapped (real _K, real _r0, real _rMax, real _cutoff, real _caprad, real _shift) inline
Definition at line 56 of file FENECapped.hpp.
References espressopp::interaction::PotentialTemplate< FENECapped >::setCutoff(), and espressopp::interaction::PotentialTemplate< FENECapped >::setShift().
FENECapped() [3/3]
espressopp::interaction::FENECapped::FENECapped (real _K, real _r0, real _rMax, real _cutoff, real _caprad) inline
Definition at line 63 of file FENECapped.hpp.
References espressopp::interaction::PotentialTemplate< FENECapped >::autoShift, espressopp::interaction::PotentialTemplate< FENECapped >::setAutoShift(), and espressopp::interaction::PotentialTemplate< FENECapped >::setCutoff().
Member Function Documentation
_computeEnergy() [1/4]
real espressopp::interaction::PotentialTemplate< FENECapped >::_computeEnergy (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 242 of file Potential.hpp.
_computeEnergy() [2/4]
real espressopp::interaction::PotentialTemplate< FENECapped >::_computeEnergy (const Real3D & dist) const inline inherited
Definition at line 257 of file Potential.hpp.
_computeEnergy() [3/4]
real espressopp::interaction::PotentialTemplate< FENECapped >::_computeEnergy (real dist) const inline inherited
Definition at line 264 of file Potential.hpp.
_computeEnergy() [4/4]
real espressopp::interaction::PotentialTemplate< FENECapped >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 250 of file Potential.hpp.
_computeEnergyDeriv()
real espressopp::interaction::PotentialTemplate< FENECapped >::_computeEnergyDeriv (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 285 of file Potential.hpp.
_computeEnergySqr()
real espressopp::interaction::PotentialTemplate< FENECapped >::_computeEnergySqr (real distSqr) const inline inherited
Definition at line 271 of file Potential.hpp.
_computeEnergySqrRaw()
real espressopp::interaction::FENECapped::_computeEnergySqrRaw (real distSqr) const inline
Definition at line 96 of file FENECapped.hpp.
References caprad.
_computeForce() [1/3]
bool espressopp::interaction::PotentialTemplate< FENECapped >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const inline inherited
Definition at line 313 of file Potential.hpp.
_computeForce() [2/3]
bool espressopp::interaction::PotentialTemplate< FENECapped >::_computeForce (Real3D & force, const Real3D & dist) const inline inherited
Definition at line 328 of file Potential.hpp.
_computeForce() [3/3]
bool espressopp::interaction::PotentialTemplate< FENECapped >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 321 of file Potential.hpp.
_computeForceRaw()
bool espressopp::interaction::FENECapped::_computeForceRaw (Real3D & force, const Real3D & dist, real distSqr) const inline
Definition at line 107 of file FENECapped.hpp.
References caprad, r0, and rMax.
computeEnergy() [1/3]
real espressopp::interaction::PotentialTemplate< FENECapped >::computeEnergy (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 213 of file Potential.hpp.
computeEnergy() [2/3]
real espressopp::interaction::PotentialTemplate< FENECapped >::computeEnergy (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 221 of file Potential.hpp.
computeEnergy() [3/3]
real espressopp::interaction::PotentialTemplate< FENECapped >::computeEnergy (real dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 228 of file Potential.hpp.
computeEnergySqr()
real espressopp::interaction::PotentialTemplate< FENECapped >::computeEnergySqr (real distsqr) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 235 of file Potential.hpp.
computeForce() [1/2]
Real3D espressopp::interaction::PotentialTemplate< FENECapped >::computeForce (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 295 of file Potential.hpp.
computeForce() [2/2]
Real3D espressopp::interaction::PotentialTemplate< FENECapped >::computeForce (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 303 of file Potential.hpp.
derived_this() [1/2]
FENECapped * espressopp::interaction::PotentialTemplate< FENECapped >::derived_this () inline protected inherited
Definition at line 123 of file Potential.hpp.
derived_this() [2/2]
const FENECapped * espressopp::interaction::PotentialTemplate< FENECapped >::derived_this () const inline protected inherited
Definition at line 127 of file Potential.hpp.
getcaprad()
real espressopp::interaction::FENECapped::getcaprad () const inline
Definition at line 82 of file FENECapped.hpp.
References caprad.
Referenced by registerPython().
getCutoff()
real espressopp::interaction::PotentialTemplate< FENECapped >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 171 of file Potential.hpp.
getK()
real espressopp::interaction::FENECapped::getK () const inline
Definition at line 76 of file FENECapped.hpp.
References K.
Referenced by registerPython().
getR0()
real espressopp::interaction::FENECapped::getR0 () const inline
Definition at line 88 of file FENECapped.hpp.
References r0.
Referenced by registerPython().
getRMax()
real espressopp::interaction::FENECapped::getRMax () const inline
Definition at line 94 of file FENECapped.hpp.
References rMax.
Referenced by registerPython().
getShift()
real espressopp::interaction::PotentialTemplate< FENECapped >::getShift () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 186 of file Potential.hpp.
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
Referenced by espressopp::interaction::Potential::~Potential().
registerPython()
void espressopp::interaction::FENECapped::registerPython () static
Definition at line 36 of file FENECapped.cpp.
References getcaprad(), getK(), getR0(), getRMax(), setcaprad(), setK(), setR0(), and setRMax().
Referenced by espressopp::interaction::registerPython().
setAutoShift()
real espressopp::interaction::PotentialTemplate< FENECapped >::setAutoShift () inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 192 of file Potential.hpp.
Referenced by FENECapped().
setcaprad()
void espressopp::interaction::FENECapped::setcaprad (real _caprad) inline
Definition at line 78 of file FENECapped.hpp.
References espressopp::interaction::PotentialTemplate< FENECapped >::updateAutoShift().
Referenced by registerPython().
setCutoff()
void espressopp::interaction::PotentialTemplate< FENECapped >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 162 of file Potential.hpp.
Referenced by FENECapped().
setK()
void espressopp::interaction::FENECapped::setK (real _K) inline
Definition at line 72 of file FENECapped.hpp.
References espressopp::interaction::PotentialTemplate< FENECapped >::updateAutoShift().
Referenced by registerPython().
setR0()
void espressopp::interaction::FENECapped::setR0 (real _r0) inline
Definition at line 84 of file FENECapped.hpp.
References espressopp::interaction::PotentialTemplate< FENECapped >::updateAutoShift().
Referenced by registerPython().
setRMax()
void espressopp::interaction::FENECapped::setRMax (real _rMax) inline
Definition at line 90 of file FENECapped.hpp.
References espressopp::interaction::PotentialTemplate< FENECapped >::updateAutoShift().
Referenced by registerPython().
setShift()
void espressopp::interaction::PotentialTemplate< FENECapped >::setShift (real _shift) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 177 of file Potential.hpp.
Referenced by FENECapped().
updateAutoShift()
void espressopp::interaction::PotentialTemplate< FENECapped >::updateAutoShift () inline inherited
Definition at line 205 of file Potential.hpp.
Referenced by setcaprad(), setK(), setR0(), and setRMax().
Member Data Documentation
autoShift
bool espressopp::interaction::PotentialTemplate< FENECapped >::autoShift protected inherited
Definition at line 121 of file Potential.hpp.
Referenced by FENECapped().
caprad
real espressopp::interaction::FENECapped::caprad private
Definition at line 45 of file FENECapped.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), and getcaprad().
cutoff
real espressopp::interaction::PotentialTemplate< FENECapped >::cutoff protected inherited
Definition at line 118 of file Potential.hpp.
cutoffSqr
real espressopp::interaction::PotentialTemplate< FENECapped >::cutoffSqr protected inherited
Definition at line 119 of file Potential.hpp.
K
real espressopp::interaction::FENECapped::K private
Definition at line 42 of file FENECapped.hpp.
Referenced by getK().
r0
real espressopp::interaction::FENECapped::r0 private
Definition at line 43 of file FENECapped.hpp.
Referenced by _computeForceRaw(), and getR0().
rMax
real espressopp::interaction::FENECapped::rMax private
Definition at line 44 of file FENECapped.hpp.
Referenced by _computeForceRaw(), and getRMax().
shift
real espressopp::interaction::PotentialTemplate< FENECapped >::shift protected inherited
Definition at line 120 of file Potential.hpp.
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/FENECapped.hpp
/home/espressopp/espressopp/src/interaction/FENECapped.cpp