ESPResSo++: espressopp::integrator::LangevinBarostat Class Reference
espressopp::integrator::LangevinBarostat Class Reference
Barostat.
#include <LangevinBarostat.hpp>
Public Types
enum ExtensionType {
all =0, Thermostat =1, Barostat =2, Constraint =3,
Adress =4, FreeEnergyCompensation =5, ExtForce =6, ExtAnalysis =7,
Reaction =8
}
Public Member Functions
LangevinBarostat (shared_ptr< System >, shared_ptr< esutil::RNG >, real)
void setGammaP (real)
real getGammaP ()
void setPressure (real)
real getPressure ()
void setMass (real)
real getMass ()
void setMassByFrequency (real)
virtual ~LangevinBarostat ()
ExtensionType getType ()
void setType (ExtensionType k)
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
Register this class so it can be used from Python.
Public Attributes
ExtensionType type
Protected Member Functions
void setIntegrator (shared_ptr< MDIntegrator > _integrator)
Protected Attributes
shared_ptr< MDIntegrator > integrator
Private Member Functions
void frictionBarostat (class Particle &, real)
void initialize ()
void upd_Vp ()
void upd_pV ()
void updVolume ()
void updVolumeMomentum ()
void updForces ()
void updDisplacement (real &)
void connect ()
void disconnect ()
Static Private Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Private Attributes
boost::signals2::connection _runInit
boost::signals2::connection _befIntP
boost::signals2::connection _inIntP
boost::signals2::connection _aftIntV
boost::signals2::connection _aftCalcF
real gammaP
real mass
real externalPressure
real desiredTemperature
real momentum
real momentum_mass
real pref3
real pref4
real pref5
real pref6
shared_ptr< esutil::RNG > rng
random number generator used for friction term
Detailed Description
Barostat.
In a couple with Langevin thermostat it performs Langevin dynamics in a Hoover-style extended system. See D. Quigley, M.I.J. Probert, J. Chem. Phys., 120, 2004, p. 11432
Definition at line 41 of file LangevinBarostat.hpp.
Member Enumeration Documentation
ExtensionType
enum espressopp::integrator::Extension::ExtensionType inherited
Enumerator
all
Thermostat
Barostat
Constraint
Adress
FreeEnergyCompensation
ExtForce
ExtAnalysis
Reaction
Definition at line 48 of file Extension.hpp.
Constructor & Destructor Documentation
LangevinBarostat()
espressopp::integrator::LangevinBarostat::LangevinBarostat (shared_ptr< System > _system, shared_ptr< esutil::RNG > _rng, real _temperature)
Definition at line 52 of file LangevinBarostat.cpp.
References espressopp::integrator::Extension::Barostat, externalPressure, gammaP, LOG4ESPP_INFO, mass, momentum, momentum_mass, and espressopp::integrator::Extension::type.
~LangevinBarostat()
espressopp::integrator::LangevinBarostat::~LangevinBarostat () virtual
Definition at line 71 of file LangevinBarostat.cpp.
References disconnect(), and LOG4ESPP_INFO.
Member Function Documentation
connect()
void espressopp::integrator::LangevinBarostat::connect () private virtual
Implements espressopp::integrator::Extension.
Definition at line 84 of file LangevinBarostat.cpp.
References _aftCalcF, _aftIntV, _befIntP, _inIntP, _runInit, initialize(), espressopp::integrator::Extension::integrator, upd_pV(), upd_Vp(), updDisplacement(), and updForces().
Referenced by registerPython().
disconnect()
void espressopp::integrator::LangevinBarostat::disconnect () private virtual
Implements espressopp::integrator::Extension.
Definition at line 76 of file LangevinBarostat.cpp.
References _aftCalcF, _aftIntV, _befIntP, _inIntP, and _runInit.
Referenced by registerPython(), and ~LangevinBarostat().
frictionBarostat()
void espressopp::integrator::LangevinBarostat::frictionBarostat (class Particle & p, real factor) private
Definition at line 248 of file LangevinBarostat.cpp.
References espressopp::Particle::force(), LOG4ESPP_TRACE, espressopp::Particle::mass(), and espressopp::Particle::velocity().
Referenced by updForces().
getGammaP()
real espressopp::integrator::LangevinBarostat::getGammaP ()
Definition at line 100 of file LangevinBarostat.cpp.
References gammaP.
Referenced by registerPython().
getMass()
real espressopp::integrator::LangevinBarostat::getMass ()
Definition at line 114 of file LangevinBarostat.cpp.
References mass.
Referenced by registerPython().
getPressure()
real espressopp::integrator::LangevinBarostat::getPressure ()
Definition at line 107 of file LangevinBarostat.cpp.
References externalPressure.
Referenced by registerPython().
getSystem()
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::LatticeBoltzmann::assignMyLattice(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::PIAdressIntegrator::computeKineticEnergy(), espressopp::integrator::PIAdressIntegrator::computeMomentumDrift(), espressopp::integrator::PIAdressIntegrator::computePositionDrift(), espressopp::integrator::PIAdressIntegrator::computeRingEnergy(), espressopp::integrator::PIAdressIntegrator::computeRingEnergyRaw(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::io::DumpXYZ::DumpXYZ(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::VerletListTriple::registerPython(), espressopp::VerletList::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
getSystem1()
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
getSystem2()
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
getSystemRef()
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::addForces(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::addForces(), espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerlet::calcForces(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::PIAdressIntegrator::calcForcesF(), espressopp::integrator::PIAdressIntegrator::calcForcesM(), espressopp::integrator::PIAdressIntegrator::calcForcesS(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeCOM(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeEnergy(), espressopp::integrator::PIAdressIntegrator::computeKineticEnergy(), espressopp::integrator::PIAdressIntegrator::computeMomentumDrift(), espressopp::integrator::PIAdressIntegrator::computePositionDrift(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::integrator::PIAdressIntegrator::computeRingEnergy(), espressopp::integrator::PIAdressIntegrator::computeRingEnergyRaw(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::PIAdressIntegrator::distributeForces(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::FixedLocalTupleComListInteractionTemplate(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::VelocityVerlet::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::PIAdressIntegrator::initForces(), espressopp::integrator::DPDThermostat::initialize(), initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::PIAdressIntegrator::initializeSetup(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::VelocityVerlet::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::VelocityVerlet::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::PIAdressIntegrator::integrateModePos(), espressopp::integrator::PIAdressIntegrator::integrateV1(), espressopp::integrator::PIAdressIntegrator::integrateV2(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::PIAdressIntegrator::OUintegrate(), espressopp::integrator::VelocityVerlet::printForces(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerlet::printPositions(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::PIAdressIntegrator::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::MinimizeEnergy::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::Rattle::saveOldPos(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::PIAdressIntegrator::setWeights(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostatOnGroup::thermalize(), espressopp::integrator::LangevinThermostatOnRadius::thermalize(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::integrator::PIAdressIntegrator::transForces(), espressopp::integrator::PIAdressIntegrator::transMom1(), espressopp::integrator::PIAdressIntegrator::transMom2(), espressopp::integrator::PIAdressIntegrator::transPos1(), espressopp::integrator::PIAdressIntegrator::transPos2(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::VelocityVerlet::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::PIAdressIntegrator::updateForces(), updDisplacement(), updForces(), updVolume(), updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
getSystemRef1()
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
getSystemRef2()
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
getType()
ExtensionType espressopp::integrator::Extension::getType () inline inherited
Definition at line 67 of file Extension.hpp.
References espressopp::integrator::Extension::type.
Referenced by espressopp::integrator::Extension::registerPython().
initialize()
void espressopp::integrator::LangevinBarostat::initialize () private
Definition at line 254 of file LangevinBarostat.cpp.
References desiredTemperature, externalPressure, gammaP, espressopp::SystemAccess::getSystemRef(), espressopp::integrator::Extension::integrator, LOG4ESPP_INFO, mass, mpiWorld, pref3, pref4, pref5, pref6, and espressopp::System::storage.
Referenced by connect().
LOG4ESPP_DECL_LOGGER()
static espressopp::integrator::LangevinBarostat::LOG4ESPP_DECL_LOGGER (theLogger) static private
Logger.
registerPython()
void espressopp::integrator::LangevinBarostat::registerPython () static
Register this class so it can be used from Python.
Definition at line 288 of file LangevinBarostat.cpp.
References connect(), disconnect(), getGammaP(), getMass(), getPressure(), setGammaP(), setMass(), setMassByFrequency(), and setPressure().
Referenced by espressopp::integrator::registerPython().
setGammaP()
void espressopp::integrator::LangevinBarostat::setGammaP (real _gammaP)
Definition at line 97 of file LangevinBarostat.cpp.
References gammaP.
Referenced by registerPython().
setIntegrator()
void espressopp::integrator::Extension::setIntegrator (shared_ptr< MDIntegrator > _integrator) protected inherited
Definition at line 49 of file Extension.cpp.
References espressopp::integrator::Extension::integrator.
Referenced by espressopp::integrator::Extension::registerPython().
setMass()
void espressopp::integrator::LangevinBarostat::setMass (real _mass)
Definition at line 111 of file LangevinBarostat.cpp.
References mass.
Referenced by registerPython().
setMassByFrequency()
void espressopp::integrator::LangevinBarostat::setMassByFrequency (real freq)
Definition at line 119 of file LangevinBarostat.cpp.
References desiredTemperature, espressopp::SystemAccess::getSystemRef(), mass, mpiWorld, and espressopp::System::storage.
Referenced by registerPython().
setPressure()
void espressopp::integrator::LangevinBarostat::setPressure (real _press)
Definition at line 104 of file LangevinBarostat.cpp.
References externalPressure.
Referenced by registerPython().
setType()
void espressopp::integrator::Extension::setType (ExtensionType k) inline inherited
Definition at line 68 of file Extension.hpp.
Referenced by espressopp::integrator::Extension::registerPython().
upd_pV()
void espressopp::integrator::LangevinBarostat::upd_pV () private
Definition at line 138 of file LangevinBarostat.cpp.
References updVolume(), and updVolumeMomentum().
Referenced by connect().
upd_Vp()
void espressopp::integrator::LangevinBarostat::upd_Vp () private
Definition at line 133 of file LangevinBarostat.cpp.
References updVolume(), and updVolumeMomentum().
Referenced by connect().
updDisplacement()
void espressopp::integrator::LangevinBarostat::updDisplacement (real & maxSqDist) private
Definition at line 233 of file LangevinBarostat.cpp.
References espressopp::SystemAccess::getSystemRef(), espressopp::integrator::Extension::integrator, espressopp::iterator::CellListIterator::isDone(), momentum_mass, espressopp::Particle::position(), and espressopp::System::storage.
Referenced by connect().
updForces()
void espressopp::integrator::LangevinBarostat::updForces () private
Definition at line 221 of file LangevinBarostat.cpp.
References frictionBarostat(), espressopp::SystemAccess::getSystemRef(), espressopp::iterator::CellListIterator::isDone(), LOG4ESPP_DEBUG, momentum_mass, pref3, and espressopp::System::storage.
Referenced by connect().
updVolume()
void espressopp::integrator::LangevinBarostat::updVolume () private
Definition at line 143 of file LangevinBarostat.cpp.
References espressopp::esutil::Error::checkException(), espressopp::System::comm, espressopp::SystemAccess::getSystemRef(), espressopp::integrator::Extension::integrator, momentum_mass, espressopp::System::scaleVolume(), and espressopp::esutil::Error::setException().
Referenced by upd_pV(), and upd_Vp().
updVolumeMomentum()
void espressopp::integrator::LangevinBarostat::updVolumeMomentum () private
Definition at line 172 of file LangevinBarostat.cpp.
References espressopp::System::bc, espressopp::System::comm, externalPressure, espressopp::SystemAccess::getSystemRef(), espressopp::integrator::Extension::integrator, espressopp::iterator::CellListIterator::isDone(), mass, espressopp::Particle::mass(), momentum, momentum_mass, pref4, pref5, pref6, rng, espressopp::System::shortRangeInteractions, espressopp::System::storage, and espressopp::Particle::velocity().
Referenced by upd_pV(), and upd_Vp().
Member Data Documentation
_aftCalcF
boost::signals2::connection espressopp::integrator::LangevinBarostat::_aftCalcF private
Definition at line 63 of file LangevinBarostat.hpp.
Referenced by connect(), and disconnect().
_aftIntV
boost::signals2::connection espressopp::integrator::LangevinBarostat::_aftIntV private
Definition at line 63 of file LangevinBarostat.hpp.
Referenced by connect(), and disconnect().
_befIntP
boost::signals2::connection espressopp::integrator::LangevinBarostat::_befIntP private
Definition at line 63 of file LangevinBarostat.hpp.
Referenced by connect(), and disconnect().
_inIntP
boost::signals2::connection espressopp::integrator::LangevinBarostat::_inIntP private
Definition at line 63 of file LangevinBarostat.hpp.
Referenced by connect(), and disconnect().
_runInit
boost::signals2::connection espressopp::integrator::LangevinBarostat::_runInit private
Definition at line 63 of file LangevinBarostat.hpp.
Referenced by connect(), and disconnect().
desiredTemperature
real espressopp::integrator::LangevinBarostat::desiredTemperature private
Definition at line 72 of file LangevinBarostat.hpp.
Referenced by initialize(), and setMassByFrequency().
externalPressure
real espressopp::integrator::LangevinBarostat::externalPressure private
Definition at line 70 of file LangevinBarostat.hpp.
Referenced by getPressure(), initialize(), LangevinBarostat(), setPressure(), and updVolumeMomentum().
gammaP
real espressopp::integrator::LangevinBarostat::gammaP private
Definition at line 68 of file LangevinBarostat.hpp.
Referenced by getGammaP(), initialize(), LangevinBarostat(), and setGammaP().
integrator
shared_ptr<MDIntegrator> espressopp::integrator::Extension::integrator protected inherited
Definition at line 72 of file Extension.hpp.
Referenced by espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::LatticeBoltzmann::calcRandForce(), espressopp::integrator::ExtAnalyze::connect(), espressopp::integrator::Rattle::connect(), espressopp::integrator::VelocityVerletOnRadius::connect(), espressopp::integrator::BerendsenBarostatAnisotropic::connect(), espressopp::integrator::BerendsenBarostat::connect(), espressopp::integrator::FixPositions::connect(), espressopp::integrator::Isokinetic::connect(), espressopp::integrator::FreeEnergyCompensation::connect(), espressopp::integrator::ExtForce::connect(), espressopp::integrator::TDforce::connect(), espressopp::integrator::BerendsenThermostat::connect(), espressopp::integrator::Settle::connect(), espressopp::integrator::LangevinThermostatOnGroup::connect(), espressopp::integrator::Adress::connect(), espressopp::integrator::CapForce::connect(), espressopp::integrator::LangevinThermostatOnRadius::connect(), espressopp::integrator::OnTheFlyFEC::connect(), espressopp::integrator::DPDThermostat::connect(), espressopp::integrator::GeneralizedLangevinThermostat::connect(), espressopp::integrator::LangevinThermostat1D::connect(), espressopp::integrator::LangevinThermostatHybrid::connect(), connect(), espressopp::integrator::LangevinThermostat::connect(), espressopp::integrator::AssociationReaction::connect(), espressopp::integrator::StochasticVelocityRescaling::connect(), espressopp::integrator::LatticeBoltzmann::connect(), espressopp::integrator::LatticeBoltzmann::convTimeMDtoLB(), espressopp::integrator::LangevinThermostatOnGroup::initialize(), espressopp::integrator::LangevinThermostatOnRadius::initialize(), espressopp::integrator::LangevinThermostat::initialize(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinThermostat1D::initialize(), espressopp::integrator::BerendsenThermostat::initialize(), espressopp::integrator::LangevinThermostatHybrid::initialize(), espressopp::integrator::BerendsenBarostatAnisotropic::initialize(), espressopp::integrator::BerendsenBarostat::initialize(), initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::Extension::setIntegrator(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), updDisplacement(), updVolume(), updVolumeMomentum(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
mass
real espressopp::integrator::LangevinBarostat::mass private
Definition at line 69 of file LangevinBarostat.hpp.
Referenced by getMass(), initialize(), LangevinBarostat(), setMass(), setMassByFrequency(), and updVolumeMomentum().
momentum
real espressopp::integrator::LangevinBarostat::momentum private
Definition at line 75 of file LangevinBarostat.hpp.
Referenced by LangevinBarostat(), and updVolumeMomentum().
momentum_mass
real espressopp::integrator::LangevinBarostat::momentum_mass private
Definition at line 76 of file LangevinBarostat.hpp.
Referenced by LangevinBarostat(), updDisplacement(), updForces(), updVolume(), and updVolumeMomentum().
pref3
real espressopp::integrator::LangevinBarostat::pref3 private
Definition at line 79 of file LangevinBarostat.hpp.
Referenced by initialize(), and updForces().
pref4
real espressopp::integrator::LangevinBarostat::pref4 private
Definition at line 80 of file LangevinBarostat.hpp.
Referenced by initialize(), and updVolumeMomentum().
pref5
real espressopp::integrator::LangevinBarostat::pref5 private
Definition at line 81 of file LangevinBarostat.hpp.
Referenced by initialize(), and updVolumeMomentum().
pref6
real espressopp::integrator::LangevinBarostat::pref6 private
Definition at line 82 of file LangevinBarostat.hpp.
Referenced by initialize(), and updVolumeMomentum().
rng
shared_ptr< esutil::RNG > espressopp::integrator::LangevinBarostat::rng private
random number generator used for friction term
Definition at line 84 of file LangevinBarostat.hpp.
Referenced by updVolumeMomentum().
type
ExtensionType espressopp::integrator::Extension::type inherited
Definition at line 62 of file Extension.hpp.
Referenced by espressopp::integrator::TDforce::addForce(), espressopp::integrator::Adress::Adress(), espressopp::integrator::AssociationReaction::AssociationReaction(), espressopp::integrator::BerendsenBarostat::BerendsenBarostat(), espressopp::integrator::BerendsenBarostatAnisotropic::BerendsenBarostatAnisotropic(), espressopp::integrator::BerendsenThermostat::BerendsenThermostat(), espressopp::integrator::DPDThermostat::DPDThermostat(), espressopp::integrator::ExtAnalyze::ExtAnalyze(), espressopp::integrator::FreeEnergyCompensation::FreeEnergyCompensation(), espressopp::integrator::GeneralizedLangevinThermostat::GeneralizedLangevinThermostat(), espressopp::integrator::Extension::getType(), LangevinBarostat(), espressopp::integrator::LangevinThermostat::LangevinThermostat(), espressopp::integrator::LangevinThermostat1D::LangevinThermostat1D(), espressopp::integrator::LangevinThermostatHybrid::LangevinThermostatHybrid(), espressopp::integrator::LangevinThermostatOnGroup::LangevinThermostatOnGroup(), espressopp::integrator::LangevinThermostatOnRadius::LangevinThermostatOnRadius(), espressopp::integrator::OnTheFlyFEC::OnTheFlyFEC(), espressopp::integrator::TDforce::registerPython(), espressopp::integrator::StochasticVelocityRescaling::StochasticVelocityRescaling(), and espressopp::integrator::TDforce::TDforce().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/integrator/LangevinBarostat.hpp
/home/espressopp/espressopp/src/integrator/LangevinBarostat.cpp