ESPResSo++: espressopp::esutil::Error Class Reference
espressopp::esutil::Error Class Reference
This class supports exception handling for MPI processors.
#include <Error.hpp>
Public Member Functions
Error (boost::shared_ptr< boost::mpi::communicator > comm)
Constructor of the error handler object.
~Error ()
Destructor; will also test for pending exceptions.
template<typename T >
void setException (const T msg, bool add=true)
Set an exception.
void checkException ()
Checks whether any processor has set an exception and if yes will throw a C++ exception.
Private Attributes
boost::shared_ptr
< boost::mpi::communicator > comm
std::string exceptionMessage
int noExceptions
counts exceptions on this proc
Detailed Description
This class supports exception handling for MPI processors.
The problem of MPI is that it is not possible to throw an exception on individual processors because it might seriously damage running communication patterns, e.g. they will not participate anymore in a global communication and the other processors will hang.
So it is only safe to throw an exception if this is done on all processors.
This class allows processors to throw individual exceptions and a global exception will be thrown later.
Be careful about the drawbacks:
A processor continues execution if it has set an exception
check for exceptions must be invoked explicitly.
Definition at line 72 of file Error.hpp.
Constructor & Destructor Documentation
espressopp::esutil::Error::Error (boost::shared_ptr< boost::mpi::communicator > comm)
Constructor of the error handler object.
Parameters:
comm is the communicator
All processor of the communicator must call this constrcutor.
Definition at line 35 of file Error.cpp.
espressopp::esutil::Error::~Error ()
Destructor; will also test for pending exceptions.
Definition at line 43 of file Error.cpp.
Member Function Documentation
void espressopp::esutil::Error::checkException ()
Checks whether any processor has set an exception and if yes will throw a C++ exception.
The string of the exception will be the concatenation of all messages set so far.
Definition at line 51 of file Error.cpp.
Referenced by espressopp::FixedQuadrupleListAdress::add(), espressopp::FixedPairListAdress::add(), espressopp::FixedTripleListAdress::add(), espressopp::FixedPairDistList::add(), espressopp::FixedTripleList::add(), espressopp::FixedQuadrupleList::add(), espressopp::FixedTripleAngleList::add(), espressopp::FixedQuadrupleAngleList::add(), espressopp::FixedTupleListAdress::addT(), espressopp::FixedTupleList::addTuple(), espressopp::interaction::CoulombKSpaceP3M::asignment_f1(), espressopp::analysis::ConfigsParticleDecomp::ConfigsParticleDecomp(), espressopp::FixedQuadrupleListAdress::onParticlesChanged(), espressopp::FixedPairListAdress::onParticlesChanged(), espressopp::FixedTripleList::onParticlesChanged(), espressopp::FixedTripleListAdress::onParticlesChanged(), espressopp::FixedSingleList::onParticlesChanged(), espressopp::FixedPairDistList::onParticlesChanged(), espressopp::FixedPairList::onParticlesChanged(), espressopp::FixedQuadrupleAngleList::onParticlesChanged(), espressopp::FixedTripleAngleList::onParticlesChanged(), espressopp::System::removeInteraction(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), and espressopp::integrator::LangevinBarostat::updVolume().
template<typename T > void espressopp::esutil::Error::setException (const T msg, bool add = true) [inline]
Set an exception.
This routine might be called individually by one or more processors.
The error message will only be added if no exceptions has been set so far or if add is set to true.
Definition at line 99 of file Error.hpp.
References exceptionMessage, and noExceptions.
Referenced by espressopp::interaction::CoulombKSpaceEwald::_computeEnergySqrRaw(), espressopp::interaction::CoulombKSpaceP3M::_computeEnergySqrRaw(), espressopp::interaction::CoulombKSpaceEwald::_computeForceRaw(), espressopp::interaction::CoulombKSpaceP3M::_computeForceRaw(), espressopp::FixedQuadrupleListAdress::add(), espressopp::FixedPairListAdress::add(), espressopp::FixedPairDistList::add(), espressopp::FixedTripleList::add(), espressopp::FixedTripleListAdress::add(), espressopp::FixedQuadrupleList::add(), espressopp::FixedTripleAngleList::add(), espressopp::FixedQuadrupleAngleList::add(), espressopp::FixedTupleListAdress::addT(), espressopp::FixedTupleList::addTuple(), espressopp::interaction::CoulombKSpaceP3M::asignment_f1(), espressopp::analysis::ConfigsParticleDecomp::ConfigsParticleDecomp(), espressopp::analysis::ConfigsParticleDecomp::gather(), espressopp::analysis::ConfigsParticleDecomp::gatherFromFile(), espressopp::analysis::ConfigsParticleDecomp::getConf(), espressopp::analysis::Autocorrelation::getValue(), espressopp::analysis::NeighborFluctuation::NeighborFluctuation(), espressopp::FixedTupleList::onParticlesChanged(), espressopp::FixedQuadrupleListAdress::onParticlesChanged(), espressopp::FixedPairListAdress::onParticlesChanged(), espressopp::FixedPairDistList::onParticlesChanged(), espressopp::FixedSingleList::onParticlesChanged(), espressopp::FixedTripleList::onParticlesChanged(), espressopp::FixedTripleListAdress::onParticlesChanged(), espressopp::FixedQuadrupleList::onParticlesChanged(), espressopp::FixedPairList::onParticlesChanged(), espressopp::FixedQuadrupleAngleList::onParticlesChanged(), espressopp::FixedTripleAngleList::onParticlesChanged(), espressopp::System::removeInteraction(), espressopp::storage::Storage::restorePositions(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::BerendsenThermostat::thermostat(), and espressopp::integrator::LangevinBarostat::updVolume().
Member Data Documentation
boost::shared_ptr< boost::mpi::communicator > espressopp::esutil::Error::comm [private]
Definition at line 122 of file Error.hpp.
std::string espressopp::esutil::Error::exceptionMessage [private]
Definition at line 124 of file Error.hpp.
Referenced by setException().
int espressopp::esutil::Error::noExceptions [private]
counts exceptions on this proc
Definition at line 126 of file Error.hpp.
Referenced by setException().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/esutil/Error.hpp
/home/travis/build/espressopp/espressopp/src/esutil/Error.cpp