ESPResSo++: espressopp::esutil::Timer Class Reference
espressopp::esutil::Timer Class Reference abstract
simple timer for obtaining typically microsecond precision timings.
#include <Timer.hpp>
Public Member Functions
virtual ~Timer ()
void reset ()
reset the starting time
float getElapsedTime () const
get the time that elapsed since the last reset
Protected Member Functions
virtual float getCurrentTime () const =0
Protected Attributes
float currentTime
Detailed Description
simple timer for obtaining typically microsecond precision timings.
The time is measured in seconds from the point of construction or whenever reset() is called. The precision depends on the available time measuring functions.
Definition at line 39 of file Timer.hpp.
Constructor & Destructor Documentation
~Timer()
virtual espressopp::esutil::Timer::~Timer () inline virtual
Definition at line 44 of file Timer.hpp.
Member Function Documentation
getCurrentTime()
virtual float espressopp::esutil::Timer::getCurrentTime () const protected pure virtual
Implemented in espressopp::esutil::WallTimer, and espressopp::esutil::UserTimer.
Referenced by getElapsedTime(), and reset().
getElapsedTime()
float espressopp::esutil::Timer::getElapsedTime () const inline
get the time that elapsed since the last reset
Definition at line 48 of file Timer.hpp.
References currentTime, and getCurrentTime().
Referenced by espressopp::integrator::VelocityVerlet::calcForces(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::LatticeBoltzmann::collideStream(), espressopp::esutil::operator<<(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletList::rebuild(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::VelocityVerlet::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), and espressopp::analysis::LBOutputScreen::writeOutput().
reset()
void espressopp::esutil::Timer::reset () inline
reset the starting time
Definition at line 46 of file Timer.hpp.
References getCurrentTime().
Referenced by espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletList::rebuild(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::esutil::UserTimer::UserTimer(), and espressopp::analysis::LBOutputScreen::writeOutput().
Member Data Documentation
currentTime
float espressopp::esutil::Timer::currentTime protected
Definition at line 41 of file Timer.hpp.
Referenced by getElapsedTime().
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/esutil/Timer.hpp