ESPResSo++: espressopp::storage::DomainDecomposition Class Reference
espressopp::storage::DomainDecomposition Class Reference
#include <DomainDecomposition.hpp>
Classes
struct CommCells
which cells to send and receive during one communication step.
Public Types
typedef boost::unordered_map< longint, Particle * > IdParticleMap
typedef std::list< Particle > ParticleListAdr
Public Member Functions
DomainDecomposition (shared_ptr< System > system, const Int3D &_nodeGrid, const Int3D &_cellGrid)
virtual ~DomainDecomposition ()
virtual void scaleVolume (real s, bool particleCoordinates)
scale position coordinates of all real particles by factor s
virtual void scaleVolume (Real3D s, bool particleCoordinates)
Scale Volume for derived classes, pS define the particle coordinates scaling.
virtual Int3D getInt3DCellGrid ()
It should return cell grid as an integer vector.
Int3D getInt3DNodeGrid ()
virtual void cellAdjust ()
It should be used at the place where is the possibility of cell size<cutoff+skin.
virtual Cell * mapPositionToCell (const Real3D &pos)
map a position to a valid cell on this node.
virtual Cell * mapPositionToCellClipped (const Real3D &pos)
map a position to a valid cell on this node.
virtual Cell * mapPositionToCellChecked (const Real3D &pos)
map a position to a cell on this node.
longint mapPositionToNodeClipped (const Real3D &pos)
const NodeGrid & getNodeGrid () const
const CellGrid & getCellGrid () const
virtual real getLocalBoxXMin ()
virtual real getLocalBoxYMin ()
virtual real getLocalBoxZMin ()
virtual real getLocalBoxXMax ()
virtual real getLocalBoxYMax ()
virtual real getLocalBoxZMax ()
virtual void updateGhosts ()
copy minimal information from the real to the ghost particles.
virtual void updateGhostsV ()
Copies just velocites of real particles to their ghosts.
virtual void collectGhostForces ()
read back forces from ghost particles by two-sided communication.
void scaleVolume (real s)
Scale Volume, only for Storage.
void scaleVolume (Real3D s)
Scale Volume, only for Storage.
Particle * addParticle (longint id, const Real3D &pos)
add a particle with given id and position.
int removeParticle (longint id)
void removeAllParticles ()
Particle * addAdrATParticle (longint id, const Real3D &pos, const Real3D &VPpos)
Particle * addAdrATParticleFTPL (Particle n)
void removeAdrATParticle (longint id)
Particle * lookupLocalParticle (longint id)
lookup whether data for a given particle is available on this node, either as real or as ghost particle.
Particle * lookupGhostParticle (longint id)
Particle * lookupRealParticle (longint id)
Lookup whether data for a given particle is available on this node.
Particle * lookupAdrATParticle (longint id)
Lookup whether data for a given adress real AT particle is available on this node.
longint getNRealParticles () const
get number of real particles on this node
longint getNLocalParticles () const
longint getNGhostParticles () const
longint getNAdressParticles () const
void fetchParticles (Storage &)
insert the particles in the given storage into the current one.
CellList & getLocalCells ()
CellList & getRealCells ()
CellList & getGhostCells ()
python::list getRealParticleIDs ()
const Cell * getFirstCell () const
virtual void decompose ()
(Re-)Decompose the system, i.e.
void setFixedTuplesAdress (shared_ptr< FixedTupleListAdress > _fixedtupleList)
shared_ptr< FixedTupleListAdress > getFixedTuples ()
ParticleList & getAdrATParticles ()
std::list< ParticleList > & getAdrATParticlesG ()
bool pyAddParticle (longint id, const Real3D &pos)
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
Public Attributes
boost::signals2::signal< void()> onParticlesChanged
Ths signal will be called whenever the storage was modified such that particle pointers have become invalid, e.g.
boost::signals2::signal< void(ParticleList &, class OutBuffer &)> beforeSendParticles
boost::signals2::signal< void(ParticleList &, class InBuffer &)> afterRecvParticles
boost::signals2::signal< void()> onTuplesChanged
Protected Types
enum ExtraDataElements { DATA_PROPERTIES =1, DATA_MOMENTUM =2, DATA_LOCAL =4 }
bitmask: which extra data elements to in- or exclude from ghost sending
Protected Member Functions
virtual bool checkIsRealParticle (longint id, const Real3D &pos)
Check whether a particle belongs to this node.
virtual void decomposeRealParticles ()
Decompose the real particles such that they are at the correct processor.
virtual void exchangeGhosts ()
used by the Storage to initiate the exchange of the full ghost information after decomposition.
virtual void doGhostCommunication (bool sizesFirst, bool realToGhosts, const int dataElements=0)
void prepareGhostCommunication ()
void initCellInteractions ()
init global Verlet list
void createCellGrid (const Int3D &nodeGrid, const Int3D &cellGrid)
set the grids and allocate space accordingly
void markCells ()
sort cells into local/ghost cell arrays
void fillCells (std::vector< Cell *> &, const int leftBoundary[3], const int rightBoundary[3])
fill a list of cells with the cells from a certain region of the domain grid
bool appendParticles (ParticleList &, int dir)
read particles from a temporary buffer into the local cell structure.
virtual void invalidateGhosts ()
remove ghost particles from the localParticles index
virtual void packPositionsEtc (class OutBuffer &buf, Cell &reals, int extradata, const Real3D &shift)
pack real particle data for sending.
virtual void unpackPositionsEtc (Cell &ghosts, class InBuffer &buf, int extradata)
unpack received data for ghosts.
virtual void copyRealsToGhosts (Cell &reals, Cell &ghosts, int extradata, const Real3D &shift)
copy specified data elements between a real cell and one of its ghosts
virtual void packForces (OutBuffer &buf, Cell &ghosts)
pack ghost forces for sending.
virtual void unpackAndAddForces (Cell &reals, class InBuffer &buf)
unpack received ghost forces.
void unpackForces (Cell &reals, class InBuffer &buf)
unpack received ghost forces.
virtual void addGhostForcesToReals (Cell &ghosts, Cell &reals)
void sendParticles (ParticleList &, longint node)
send particles of a cell to another node, and empty the cell locally.
void recvParticles (ParticleList &, longint node)
receive particles from another node.
void updateLocalParticles (ParticleList &, bool adress=false)
void removeFromLocalParticles (Particle *, bool weak=false)
void updateInLocalParticles (Particle *, bool weak=false)
void updateInLocalAdrATParticles (Particle *)
void resizeCells (longint nCells)
Particle * appendUnindexedParticle (ParticleList &, Particle &)
Particle * appendUnindexedAdrParticle (ParticleList &, Particle &)
void appendParticleListToGhosts (ParticleList &l)
Particle * appendIndexedParticle (ParticleList &, Particle &)
Particle * moveIndexedParticle (ParticleList &dst, ParticleList &src, int srcpos)
void clearAdrATParticlesG ()
void savePosition (size_t id)
void restorePositions ()
void clearSavedPositions ()
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (logger)
Protected Attributes
NodeGrid nodeGrid
spatial domain decomposition of nodes
CellGrid cellGrid
spatial domain decomposition on node in cells
size_t exchangeBufferSize
expected capacity of send/recv buffers for neighbor communication
CommCells commCells [6]
which cells to send left, right, up, down, ...
LocalCellList cells
here the local particles are actually stored
CellList realCells
list of real cells
CellList ghostCells
list of ghost cells
CellList localCells
all cells on this CPU.
InBuffer inBuffer
OutBuffer outBuffer
shared_ptr< FixedTupleListAdress > fixedtupleList
Static Protected Attributes
static const int dataOfUpdateGhosts = 0
for the moment, these are constants, defining what to transfer during ghost communications.
static const int dataOfExchangeGhosts = DATA_PROPERTIES
Detailed Description
Definition at line 40 of file DomainDecomposition.hpp.
Member Typedef Documentation
IdParticleMap
typedef boost::unordered_map<longint, Particle*> espressopp::storage::Storage::IdParticleMap inherited
Definition at line 47 of file Storage.hpp.
ParticleListAdr
typedef std::list<Particle> espressopp::storage::Storage::ParticleListAdr inherited
Definition at line 48 of file Storage.hpp.
Member Enumeration Documentation
ExtraDataElements
enum espressopp::storage::Storage::ExtraDataElements protected inherited
bitmask: which extra data elements to in- or exclude from ghost sending
Enumerator
DATA_PROPERTIES
DATA_MOMENTUM
DATA_LOCAL
Definition at line 286 of file Storage.hpp.
Constructor & Destructor Documentation
DomainDecomposition()
espressopp::storage::DomainDecomposition::DomainDecomposition (shared_ptr< System > system, const Int3D & _nodeGrid, const Int3D & _cellGrid)
Definition at line 69 of file DomainDecomposition.cpp.
References createCellGrid(), initCellInteractions(), LOG4ESPP_DEBUG, LOG4ESPP_INFO, and prepareGhostCommunication().
Referenced by espressopp::storage::NodeGridMismatch::NodeGridMismatch().
~DomainDecomposition()
virtual espressopp::storage::DomainDecomposition::~DomainDecomposition () inline virtual
Definition at line 46 of file DomainDecomposition.hpp.
Member Function Documentation
addAdrATParticle()
Particle * espressopp::storage::Storage::addAdrATParticle (longint id, const Real3D & pos, const Real3D & VPpos) inherited
Definition at line 324 of file Storage.cpp.
References espressopp::storage::Storage::AdrATParticles, espressopp::storage::Storage::checkIsRealParticle(), espressopp::SystemAccess::getSystem(), espressopp::Particle::id(), espressopp::Particle::image(), espressopp::Particle::init(), espressopp::Particle::position(), espressopp::storage::Storage::updateInLocalAdrATParticles(), and espressopp::storage::Storage::updateLocalParticles().
Referenced by espressopp::storage::Storage::registerPython().
addAdrATParticleFTPL()
Particle * espressopp::storage::Storage::addAdrATParticleFTPL (Particle n) inherited
Definition at line 372 of file Storage.cpp.
References espressopp::storage::Storage::AdrATParticles, espressopp::storage::Storage::updateInLocalAdrATParticles(), and espressopp::storage::Storage::updateLocalParticles().
addGhostForcesToReals()
void espressopp::storage::Storage::addGhostForcesToReals (Cell & ghosts, Cell & reals) protected virtual inherited
Reimplemented in espressopp::storage::DomainDecompositionAdress.
Definition at line 675 of file Storage.cpp.
References espressopp::storage::Storage::getFirstCell(), LOG4ESPP_DEBUG, LOG4ESPP_TRACE, and espressopp::Cell::particles.
Referenced by espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), and doGhostCommunication().
addParticle()
Particle * espressopp::storage::Storage::addParticle (longint id, const Real3D & pos) inherited
add a particle with given id and position.
Note that this is a local operation, and therefore cannot check whether a particle with the given id already exists. This is left to the parallel front end.
Definition at line 256 of file Storage.cpp.
References espressopp::storage::Storage::appendIndexedParticle(), espressopp::storage::Storage::checkIsRealParticle(), espressopp::storage::Storage::getFirstCell(), espressopp::SystemAccess::getSystem(), espressopp::Particle::id(), espressopp::Particle::image(), espressopp::Particle::init(), LOG4ESPP_TRACE, espressopp::storage::Storage::mapPositionToCellClipped(), espressopp::ParticlePosition::p, espressopp::Cell::particles, espressopp::Particle::position(), and espressopp::Particle::r.
Referenced by espressopp::storage::Storage::registerPython().
appendIndexedParticle()
Particle * espressopp::storage::Storage::appendIndexedParticle (ParticleList & l, Particle & part) protected inherited
Definition at line 416 of file Storage.cpp.
References espressopp::storage::Storage::updateInLocalParticles(), and espressopp::storage::Storage::updateLocalParticles().
Referenced by espressopp::storage::Storage::addParticle(), appendParticles(), and espressopp::storage::DomainDecompositionAdress::appendParticles().
appendParticleListToGhosts()
void espressopp::storage::Storage::appendParticleListToGhosts (ParticleList & l) protected inherited
Definition at line 409 of file Storage.cpp.
References espressopp::storage::Storage::AdrATParticlesG.
Referenced by espressopp::storage::DomainDecompositionAdress::copyGhostTuples(), and espressopp::storage::DomainDecompositionAdress::unpackPositionsEtc().
appendParticles()
bool espressopp::storage::DomainDecomposition::appendParticles (ParticleList & l, int dir) protected
read particles from a temporary buffer into the local cell structure.
The direction determines in which direction to fold the particles position. Returns true if one of the given particles did not belong to this processors domain.
Definition at line 352 of file DomainDecomposition.cpp.
References espressopp::storage::Storage::appendIndexedParticle(), cellGrid, espressopp::storage::Storage::cells, espressopp::storage::NodeGrid::convertDirToCoord(), espressopp::storage::NodeGrid::getBoundary(), espressopp::SystemAccess::getSystem(), LOG4ESPP_DEBUG, LOG4ESPP_TRACE, espressopp::CellGrid::mapPositionToCellCheckedAndClipped(), and nodeGrid.
Referenced by espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), and decomposeRealParticles().
appendUnindexedAdrParticle()
Particle * espressopp::storage::Storage::appendUnindexedAdrParticle (ParticleList & l, Particle & part) protected inherited
Definition at line 404 of file Storage.cpp.
appendUnindexedParticle()
Particle * espressopp::storage::Storage::appendUnindexedParticle (ParticleList & l, Particle & part) protected inherited
Definition at line 397 of file Storage.cpp.
Referenced by espressopp::storage::DomainDecompositionAdress::cellAdjust(), cellAdjust(), and espressopp::storage::Storage::fetchParticles().
cellAdjust()
void espressopp::storage::DomainDecomposition::cellAdjust () virtual
It should be used at the place where is the possibility of cell size<cutoff+skin.
Implements espressopp::storage::Storage.
Definition at line 232 of file DomainDecomposition.cpp.
References espressopp::storage::Storage::appendUnindexedParticle(), espressopp::storage::Storage::cells, commCells, createCellGrid(), exchangeGhosts(), espressopp::esutil::Grid::getGridSize(), espressopp::SystemAccess::getSystem(), espressopp::storage::Storage::ghostCells, espressopp::storage::DomainDecomposition::CommCells::ghosts, initCellInteractions(), espressopp::storage::Storage::invalidateGhosts(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::storage::Storage::localCells, mapPositionToCellClipped(), nodeGrid, espressopp::storage::Storage::onParticlesChanged, espressopp::Cell::particles, espressopp::Particle::position(), prepareGhostCommunication(), espressopp::storage::Storage::realCells, espressopp::storage::DomainDecomposition::CommCells::reals, and espressopp::storage::Storage::updateLocalParticles().
Referenced by registerPython(), and scaleVolume().
checkIsRealParticle()
bool espressopp::storage::DomainDecomposition::checkIsRealParticle (longint id, const Real3D & pos) protected virtual
Check whether a particle belongs to this node.
Implements espressopp::storage::Storage.
Definition at line 348 of file DomainDecomposition.cpp.
References espressopp::SystemAccess::getSystem(), and mapPositionToNodeClipped().
clearAdrATParticlesG()
void espressopp::storage::Storage::clearAdrATParticlesG () inline protected inherited
Definition at line 408 of file Storage.hpp.
References espressopp::storage::Storage::AdrATParticlesG, espressopp::storage::Storage::clearSavedPositions(), espressopp::storage::Storage::restorePositions(), and espressopp::storage::Storage::savePosition().
Referenced by espressopp::storage::DomainDecompositionAdress::invalidateGhosts().
clearSavedPositions()
void espressopp::storage::Storage::clearSavedPositions () protected inherited
Definition at line 694 of file Storage.cpp.
References espressopp::storage::Storage::savedImages, and espressopp::storage::Storage::savedRealPositions.
Referenced by espressopp::storage::Storage::clearAdrATParticlesG(), and espressopp::storage::Storage::registerPython().
collectGhostForces()
void espressopp::storage::DomainDecomposition::collectGhostForces () virtual
read back forces from ghost particles by two-sided communication.
Storage implementations should only gather forces here. Note that forces are not stored back, but are additive!
Implements espressopp::storage::Storage.
Definition at line 556 of file DomainDecomposition.cpp.
References doGhostCommunication(), and LOG4ESPP_DEBUG.
copyRealsToGhosts()
void espressopp::storage::Storage::copyRealsToGhosts (Cell & reals, Cell & ghosts, int extradata, const Real3D & shift) protected virtual inherited
copy specified data elements between a real cell and one of its ghosts
Parameters
shift how to adjust the positions of the particles when sending
Reimplemented in espressopp::storage::DomainDecompositionAdress.
Definition at line 603 of file Storage.cpp.
References espressopp::storage::Storage::DATA_LOCAL, espressopp::storage::Storage::DATA_MOMENTUM, espressopp::storage::Storage::DATA_PROPERTIES, espressopp::storage::Storage::getFirstCell(), LOG4ESPP_DEBUG, and espressopp::Cell::particles.
Referenced by espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), and doGhostCommunication().
createCellGrid()
void espressopp::storage::DomainDecomposition::createCellGrid (const Int3D & nodeGrid, const Int3D & cellGrid) protected
set the grids and allocate space accordingly
Definition at line 84 of file DomainDecomposition.cpp.
References cellGrid, espressopp::CellGrid::getFrameGridSize(), espressopp::CellGrid::getGridSize(), espressopp::storage::NodeGrid::getMyLeft(), espressopp::storage::NodeGrid::getMyRight(), espressopp::storage::NodeGrid::getNodeNeighborIndex(), espressopp::storage::NodeGrid::getNodePosition(), espressopp::esutil::Grid::getNumberOfCells(), espressopp::SystemAccess::getSystem(), espressopp::storage::Storage::ghostCells, LOG4ESPP_DEBUG, LOG4ESPP_INFO, markCells(), nodeGrid, espressopp::storage::Storage::realCells, and espressopp::storage::Storage::resizeCells().
Referenced by cellAdjust(), and DomainDecomposition().
decompose()
void espressopp::storage::Storage::decompose () virtual inherited
(Re-)Decompose the system, i.e.
redistribute the particles to the correct processors.
This should be called by any parallel algorithm that works with the particle data at the beggining of the algorithm. Otherwise, it is not guaranteed that the particles are at the correct processor.
This should be called by the integrator instead of updateGhosts() whenever a particle might have moved more than a given skin. The skin is not an issue of the storage, but all algorithms using the particle data need to be aware that particles might be located up to skin away from their current cell.
Reimplemented in espressopp::storage::DomainDecompositionAdress.
Definition at line 555 of file Storage.cpp.
References espressopp::storage::Storage::decomposeRealParticles(), espressopp::storage::Storage::exchangeGhosts(), espressopp::storage::Storage::invalidateGhosts(), and espressopp::storage::Storage::onParticlesChanged.
Referenced by espressopp::storage::Storage::getFirstCell(), espressopp::storage::Storage::registerPython(), espressopp::integrator::VelocityVerletRESPA::run(), espressopp::integrator::PIAdressIntegrator::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::MinimizeEnergy::run(), and espressopp::integrator::VelocityVerletOnGroup::run().
decomposeRealParticles()
void espressopp::storage::DomainDecomposition::decomposeRealParticles () protected virtual
Decompose the real particles such that they are at the correct processor.
This should not touch the ghosts. Called by decompose.
Implements espressopp::storage::Storage.
Reimplemented in espressopp::storage::DomainDecompositionNonBlocking.
Definition at line 381 of file DomainDecomposition.cpp.
References appendParticles(), cellGrid, exchangeBufferSize, espressopp::esutil::Grid::getGridSize(), espressopp::CellGrid::getMyLeft(), espressopp::CellGrid::getMyRight(), espressopp::storage::NodeGrid::getNodeNeighborIndex(), espressopp::storage::NodeGrid::getNodePosition(), espressopp::SystemAccess::getSystem(), espressopp::Particle::id(), espressopp::Particle::image(), LOG4ESPP_DEBUG, LOG4ESPP_ERROR, LOG4ESPP_TRACE, mapPositionToCellChecked(), espressopp::storage::Storage::moveIndexedParticle(), nodeGrid, espressopp::Cell::particles, espressopp::Particle::position(), espressopp::storage::Storage::realCells, espressopp::storage::Storage::recvParticles(), espressopp::ROUND_ERROR_PREC, and espressopp::storage::Storage::sendParticles().
doGhostCommunication()
void espressopp::storage::DomainDecomposition::doGhostCommunication (bool sizesFirst, bool realToGhosts, const int dataElements = 0) protected virtual
Reimplemented in espressopp::storage::DomainDecompositionNonBlocking.
Definition at line 647 of file DomainDecomposition.cpp.
References espressopp::storage::Storage::addGhostForcesToReals(), commCells, espressopp::storage::Storage::copyRealsToGhosts(), espressopp::storage::DD_COMM_TAG, espressopp::storage::NodeGrid::getBoundary(), espressopp::esutil::Grid::getGridSize(), espressopp::storage::NodeGrid::getNodeNeighborIndex(), espressopp::storage::NodeGrid::getNodePosition(), espressopp::SystemAccess::getSystem(), espressopp::storage::DomainDecomposition::CommCells::ghosts, espressopp::storage::Storage::inBuffer, LOG4ESPP_DEBUG, nodeGrid, espressopp::storage::Storage::outBuffer, espressopp::storage::Storage::packForces(), espressopp::storage::Storage::packPositionsEtc(), espressopp::storage::DomainDecomposition::CommCells::reals, espressopp::InBuffer::recv(), espressopp::Buffer::reset(), espressopp::OutBuffer::send(), espressopp::storage::Storage::unpackAndAddForces(), and espressopp::storage::Storage::unpackPositionsEtc().
Referenced by collectGhostForces(), exchangeGhosts(), prepareGhostCommunication(), updateGhosts(), and updateGhostsV().
exchangeGhosts()
void espressopp::storage::DomainDecomposition::exchangeGhosts () protected virtual
used by the Storage to initiate the exchange of the full ghost information after decomposition.
Storage implementations should exchange particle positions, plus data fields as indicated by dataOfExchangeGhosts.
Implements espressopp::storage::Storage.
Definition at line 540 of file DomainDecomposition.cpp.
References espressopp::storage::Storage::dataOfExchangeGhosts, doGhostCommunication(), and LOG4ESPP_DEBUG.
Referenced by cellAdjust().
fetchParticles()
void espressopp::storage::Storage::fetchParticles (Storage & old) inherited
insert the particles in the given storage into the current one.
This is mainly used to switch from one storage to another.
Definition at line 472 of file Storage.cpp.
References espressopp::storage::Storage::appendUnindexedParticle(), espressopp::storage::Storage::getRealCells(), espressopp::iterator::CellListIterator::isValid(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_DEBUG, espressopp::storage::Storage::mapPositionToCellClipped(), espressopp::Cell::particles, espressopp::Particle::position(), espressopp::storage::Storage::realCells, and espressopp::storage::Storage::updateLocalParticles().
fillCells()
void espressopp::storage::DomainDecomposition::fillCells (std::vector< Cell *> & cv, const int leftBoundary[3], const int rightBoundary[3]) protected
fill a list of cells with the cells from a certain region of the domain grid
Definition at line 561 of file DomainDecomposition.cpp.
References cellGrid, espressopp::storage::Storage::cells, espressopp::CellGrid::getFrameGridSize(), LOG4ESPP_DEBUG, LOG4ESPP_TRACE, and espressopp::esutil::Grid::mapPositionToIndex().
Referenced by prepareGhostCommunication().
getAdrATParticles()
ParticleList& espressopp::storage::Storage::getAdrATParticles () inline inherited
Definition at line 254 of file Storage.hpp.
References espressopp::storage::Storage::AdrATParticles.
getAdrATParticlesG()
std::list<ParticleList>& espressopp::storage::Storage::getAdrATParticlesG () inline inherited
Definition at line 256 of file Storage.hpp.
References espressopp::storage::Storage::AdrATParticlesG, espressopp::storage::Storage::checkIsRealParticle(), espressopp::storage::Storage::decomposeRealParticles(), espressopp::storage::Storage::exchangeGhosts(), espressopp::storage::Storage::pyAddParticle(), and espressopp::storage::Storage::registerPython().
Referenced by espressopp::storage::DomainDecompositionAdress::copyGhostTuples(), and espressopp::storage::DomainDecompositionAdress::unpackPositionsEtc().
getCellGrid()
const CellGrid& espressopp::storage::DomainDecomposition::getCellGrid () const inline
Definition at line 67 of file DomainDecomposition.hpp.
getFirstCell()
const Cell* espressopp::storage::Storage::getFirstCell () const inline inherited
Definition at line 175 of file Storage.hpp.
References espressopp::storage::Storage::cells, espressopp::storage::Storage::collectGhostForces(), espressopp::storage::Storage::decompose(), espressopp::storage::Storage::mapPositionToCell(), espressopp::storage::Storage::mapPositionToCellChecked(), espressopp::storage::Storage::mapPositionToCellClipped(), espressopp::storage::Storage::updateGhosts(), and espressopp::storage::Storage::updateGhostsV().
Referenced by espressopp::storage::Storage::addGhostForcesToReals(), espressopp::storage::Storage::addParticle(), espressopp::storage::Storage::copyRealsToGhosts(), espressopp::storage::Storage::getNGhostParticles(), espressopp::storage::Storage::getNLocalParticles(), espressopp::storage::Storage::getNRealParticles(), initCellInteractions(), espressopp::storage::DomainDecompositionAdress::initCellInteractions(), espressopp::storage::Storage::packForces(), espressopp::storage::Storage::packPositionsEtc(), espressopp::storage::DomainDecompositionAdress::unpackAndAddForces(), espressopp::storage::Storage::unpackAndAddForces(), espressopp::storage::Storage::unpackForces(), and espressopp::storage::Storage::unpackPositionsEtc().
getFixedTuples()
shared_ptr<FixedTupleListAdress> espressopp::storage::Storage::getFixedTuples () inline inherited
Definition at line 253 of file Storage.hpp.
References espressopp::storage::Storage::fixedtupleList.
getGhostCells()
CellList& espressopp::storage::Storage::getGhostCells () inline inherited
Definition at line 171 of file Storage.hpp.
References espressopp::storage::Storage::getRealParticleIDs(), and espressopp::storage::Storage::ghostCells.
Referenced by espressopp::storage::DomainDecompositionAdress::invalidateGhosts(), and espressopp::storage::Storage::invalidateGhosts().
getInt3DCellGrid()
Int3D espressopp::storage::DomainDecomposition::getInt3DCellGrid () virtual
It should return cell grid as an integer vector.
Implements espressopp::storage::Storage.
Definition at line 219 of file DomainDecomposition.cpp.
References cellGrid, and espressopp::CellGrid::getGridSize().
Referenced by registerPython().
getInt3DNodeGrid()
Int3D espressopp::storage::DomainDecomposition::getInt3DNodeGrid ()
Definition at line 225 of file DomainDecomposition.cpp.
References espressopp::esutil::Grid::getGridSize(), and nodeGrid.
Referenced by registerPython().
getLocalBoxXMax()
virtual real espressopp::storage::DomainDecomposition::getLocalBoxXMax () inline virtual
Implements espressopp::storage::Storage.
Definition at line 72 of file DomainDecomposition.hpp.
getLocalBoxXMin()
virtual real espressopp::storage::DomainDecomposition::getLocalBoxXMin () inline virtual
Implements espressopp::storage::Storage.
Definition at line 69 of file DomainDecomposition.hpp.
getLocalBoxYMax()
virtual real espressopp::storage::DomainDecomposition::getLocalBoxYMax () inline virtual
Implements espressopp::storage::Storage.
Definition at line 73 of file DomainDecomposition.hpp.
getLocalBoxYMin()
virtual real espressopp::storage::DomainDecomposition::getLocalBoxYMin () inline virtual
Implements espressopp::storage::Storage.
Definition at line 70 of file DomainDecomposition.hpp.
getLocalBoxZMax()
virtual real espressopp::storage::DomainDecomposition::getLocalBoxZMax () inline virtual
Implements espressopp::storage::Storage.
Definition at line 74 of file DomainDecomposition.hpp.
References espressopp::storage::registerPython().
getLocalBoxZMin()
virtual real espressopp::storage::DomainDecomposition::getLocalBoxZMin () inline virtual
Implements espressopp::storage::Storage.
Definition at line 71 of file DomainDecomposition.hpp.
getLocalCells()
CellList& espressopp::storage::Storage::getLocalCells () inline inherited
Definition at line 169 of file Storage.hpp.
References espressopp::storage::Storage::localCells.
getNAdressParticles()
longint espressopp::storage::Storage::getNAdressParticles () const inherited
Definition at line 101 of file Storage.cpp.
References espressopp::storage::Storage::localAdrATParticles.
getNGhostParticles()
longint espressopp::storage::Storage::getNGhostParticles () const inherited
Definition at line 90 of file Storage.cpp.
References espressopp::storage::Storage::getFirstCell(), espressopp::storage::Storage::ghostCells, and LOG4ESPP_TRACE.
getNLocalParticles()
longint espressopp::storage::Storage::getNLocalParticles () const inherited
Definition at line 79 of file Storage.cpp.
References espressopp::storage::Storage::getFirstCell(), espressopp::storage::Storage::localCells, and LOG4ESPP_TRACE.
getNodeGrid()
const NodeGrid& espressopp::storage::DomainDecomposition::getNodeGrid () const inline
Definition at line 66 of file DomainDecomposition.hpp.
getNRealParticles()
longint espressopp::storage::Storage::getNRealParticles () const inherited
get number of real particles on this node
Definition at line 67 of file Storage.cpp.
References espressopp::storage::Storage::getFirstCell(), LOG4ESPP_TRACE, and espressopp::storage::Storage::realCells.
getRealCells()
CellList& espressopp::storage::Storage::getRealCells () inline inherited
Definition at line 170 of file Storage.hpp.
References espressopp::storage::Storage::realCells.
Referenced by espressopp::storage::Storage::fetchParticles().
getRealParticleIDs()
python::list espressopp::storage::Storage::getRealParticleIDs () inherited
Definition at line 106 of file Storage.cpp.
References espressopp::iterator::CellListIterator::isDone(), and espressopp::storage::Storage::realCells.
Referenced by espressopp::storage::Storage::getGhostCells(), and espressopp::storage::Storage::registerPython().
getSystem()
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::LatticeBoltzmann::assignMyLattice(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), cellAdjust(), checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::PIAdressIntegrator::computeKineticEnergy(), espressopp::integrator::PIAdressIntegrator::computeMomentumDrift(), espressopp::integrator::PIAdressIntegrator::computePositionDrift(), espressopp::integrator::PIAdressIntegrator::computeRingEnergy(), espressopp::integrator::PIAdressIntegrator::computeRingEnergyRaw(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpXTCAdress::dump(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::io::DumpXYZ::DumpXYZ(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::VerletListTriple::registerPython(), espressopp::VerletList::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::storage::Storage::savePosition(), scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
getSystem1()
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
getSystem2()
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
getSystemRef()
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::addForces(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::addForces(), espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerletRESPA::calcForces(), espressopp::integrator::VelocityVerlet::calcForces(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::PIAdressIntegrator::calcForcesF(), espressopp::integrator::PIAdressIntegrator::calcForcesM(), espressopp::integrator::PIAdressIntegrator::calcForcesS(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::analysis::NPart::compute_real(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeCenter(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeCOM(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeEnergy(), espressopp::integrator::PIAdressIntegrator::computeKineticEnergy(), espressopp::integrator::PIAdressIntegrator::computeMomentumDrift(), espressopp::integrator::PIAdressIntegrator::computePositionDrift(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeRG(), espressopp::integrator::PIAdressIntegrator::computeRingEnergy(), espressopp::integrator::PIAdressIntegrator::computeRingEnergyRaw(), espressopp::integrator::TDforce::computeTDEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::PIAdressIntegrator::distributeForces(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::FixedLocalTupleComListInteractionTemplate(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::FixedLocalTupleRgListInteractionTemplate(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::VelocityVerletRESPA::initForces(), espressopp::integrator::VelocityVerlet::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::PIAdressIntegrator::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::PIAdressIntegrator::initializeSetup(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::VelocityVerletRESPA::integrate1(), espressopp::integrator::VelocityVerlet::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::VelocityVerletRESPA::integrate2(), espressopp::integrator::VelocityVerlet::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::PIAdressIntegrator::integrateModePos(), espressopp::integrator::Adress::integrateSlow(), espressopp::integrator::PIAdressIntegrator::integrateV1(), espressopp::integrator::PIAdressIntegrator::integrateV2(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::PIAdressIntegrator::OUintegrate(), espressopp::integrator::VelocityVerlet::printForces(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerlet::printPositions(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readLBConf(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::VelocityVerletRESPA::run(), espressopp::integrator::PIAdressIntegrator::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::MinimizeEnergy::run(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), espressopp::integrator::Rattle::saveOldPos(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::PIAdressIntegrator::setWeights(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostatOnGroup::thermalize(), espressopp::integrator::LangevinThermostatOnRadius::thermalize(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::integrator::PIAdressIntegrator::transForces(), espressopp::integrator::PIAdressIntegrator::transMom1(), espressopp::integrator::PIAdressIntegrator::transMom2(), espressopp::integrator::PIAdressIntegrator::transPos1(), espressopp::integrator::PIAdressIntegrator::transPos2(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::VelocityVerletRESPA::updateForces(), espressopp::integrator::VelocityVerlet::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::PIAdressIntegrator::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
getSystemRef1()
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
getSystemRef2()
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
initCellInteractions()
void espressopp::storage::DomainDecomposition::initCellInteractions () protected
init global Verlet list
Definition at line 289 of file DomainDecomposition.cpp.
References cellGrid, espressopp::storage::Storage::cells, espressopp::storage::Storage::getFirstCell(), espressopp::CellGrid::getInnerCellsBegin(), espressopp::CellGrid::getInnerCellsEnd(), LOG4ESPP_DEBUG, LOG4ESPP_TRACE, espressopp::esutil::Grid::mapPositionToIndex(), and espressopp::Cell::neighborCells.
Referenced by cellAdjust(), and DomainDecomposition().
invalidateGhosts()
void espressopp::storage::Storage::invalidateGhosts () protected virtual inherited
remove ghost particles from the localParticles index
Reimplemented in espressopp::storage::DomainDecompositionAdress.
Definition at line 544 of file Storage.cpp.
References espressopp::storage::Storage::getGhostCells(), espressopp::iterator::CellListIterator::isValid(), and espressopp::storage::Storage::removeFromLocalParticles().
Referenced by cellAdjust(), and espressopp::storage::Storage::decompose().
LOG4ESPP_DECL_LOGGER()
static espressopp::storage::DomainDecomposition::LOG4ESPP_DECL_LOGGER (logger) static protected
lookupAdrATParticle()
Particle* espressopp::storage::Storage::lookupAdrATParticle (longint id) inline inherited
Lookup whether data for a given adress real AT particle is available on this node.
Returns
0 if the particle wasn't available, the pointer to the Particle, if it was.
Definition at line 147 of file Storage.hpp.
References espressopp::storage::Storage::localAdrATParticles.
Referenced by espressopp::storage::Storage::lookupRealParticle(), and espressopp::storage::Storage::removeAdrATParticle().
lookupGhostParticle()
Particle* espressopp::storage::Storage::lookupGhostParticle (longint id) inline inherited
Definition at line 114 of file Storage.hpp.
References espressopp::storage::Storage::localParticles.
lookupLocalParticle()
Particle* espressopp::storage::Storage::lookupLocalParticle (longint id) inline inherited
lookup whether data for a given particle is available on this node, either as real or as ghost particle.
Definition at line 109 of file Storage.hpp.
References espressopp::storage::Storage::localParticles.
Referenced by espressopp::storage::Storage::registerPython().
lookupRealParticle()
Particle* espressopp::storage::Storage::lookupRealParticle (longint id) inline inherited
Lookup whether data for a given particle is available on this node.
Returns
0 if the particle wasn't available, the pointer to the Particle, if it was. Lookup whether data for a given particle is available on this node.
0 if the particle wasn't available, the pointer to the Particle, if it was.
Definition at line 132 of file Storage.hpp.
References espressopp::storage::Storage::localParticles, and espressopp::storage::Storage::lookupAdrATParticle().
Referenced by espressopp::storage::Storage::registerPython(), espressopp::storage::Storage::removeParticle(), espressopp::storage::Storage::restorePositions(), and espressopp::storage::Storage::savePosition().
mapPositionToCell()
Cell * espressopp::storage::DomainDecomposition::mapPositionToCell (const Real3D & pos) virtual
map a position to a valid cell on this node.
Used for AdResS
Implements espressopp::storage::Storage.
Definition at line 326 of file DomainDecomposition.cpp.
References cellGrid, espressopp::storage::Storage::cells, and espressopp::CellGrid::mapPositionToCell().
mapPositionToCellChecked()
Cell * espressopp::storage::DomainDecomposition::mapPositionToCellChecked (const Real3D & pos) virtual
map a position to a cell on this node.
If the position is outside the domain of this node, return 0.
Implements espressopp::storage::Storage.
Definition at line 334 of file DomainDecomposition.cpp.
References cellGrid, espressopp::storage::Storage::cells, espressopp::CellGrid::mapPositionToCellChecked(), and espressopp::CellGrid::noCell.
Referenced by espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), and decomposeRealParticles().
mapPositionToCellClipped()
Cell * espressopp::storage::DomainDecomposition::mapPositionToCellClipped (const Real3D & pos) virtual
map a position to a valid cell on this node.
If the position is outside the domain of this node, return the cell inside the domain that is closest to the position.
Implements espressopp::storage::Storage.
Definition at line 330 of file DomainDecomposition.cpp.
References cellGrid, espressopp::storage::Storage::cells, and espressopp::CellGrid::mapPositionToCellClipped().
Referenced by cellAdjust().
mapPositionToNodeClipped()
longint espressopp::storage::DomainDecomposition::mapPositionToNodeClipped (const Real3D & pos)
Definition at line 344 of file DomainDecomposition.cpp.
References espressopp::storage::NodeGrid::mapPositionToNodeClipped(), and nodeGrid.
Referenced by checkIsRealParticle(), and registerPython().
markCells()
void espressopp::storage::DomainDecomposition::markCells () protected
sort cells into local/ghost cell arrays
Definition at line 142 of file DomainDecomposition.cpp.
References cellGrid, espressopp::storage::Storage::cells, espressopp::CellGrid::getFrameGridSize(), espressopp::storage::Storage::ghostCells, espressopp::CellGrid::isInnerCell(), LOG4ESPP_TRACE, espressopp::esutil::Grid::mapPositionToIndex(), and espressopp::storage::Storage::realCells.
Referenced by createCellGrid().
moveIndexedParticle()
Particle * espressopp::storage::Storage::moveIndexedParticle (ParticleList & dst, ParticleList & src, int srcpos) protected inherited
Definition at line 434 of file Storage.cpp.
References espressopp::storage::Storage::updateInLocalParticles(), and espressopp::storage::Storage::updateLocalParticles().
Referenced by espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), decomposeRealParticles(), and espressopp::storage::DomainDecompositionAdress::decomposeRealParticles().
packForces()
void espressopp::storage::Storage::packForces (OutBuffer & buf, Cell & ghosts) protected virtual inherited
pack ghost forces for sending.
Reimplemented in espressopp::storage::DomainDecompositionAdress.
Definition at line 628 of file Storage.cpp.
References espressopp::storage::Storage::getFirstCell(), LOG4ESPP_DEBUG, LOG4ESPP_TRACE, espressopp::Cell::particles, and espressopp::OutBuffer::write().
Referenced by espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), and doGhostCommunication().
packPositionsEtc()
void espressopp::storage::Storage::packPositionsEtc (class OutBuffer & buf, Cell & reals, int extradata, const Real3D & shift) protected virtual inherited
pack real particle data for sending.
At least positions, maybe shifted, and possibly additional data according to extradata.
Parameters
shift how to adjust the positions of the particles when sending
Reimplemented in espressopp::storage::DomainDecompositionAdress.
Definition at line 562 of file Storage.cpp.
References espressopp::storage::Storage::DATA_LOCAL, espressopp::storage::Storage::DATA_MOMENTUM, espressopp::storage::Storage::DATA_PROPERTIES, espressopp::storage::Storage::getFirstCell(), LOG4ESPP_DEBUG, espressopp::Cell::particles, and espressopp::OutBuffer::write().
Referenced by espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), and doGhostCommunication().
prepareGhostCommunication()
void espressopp::storage::DomainDecomposition::prepareGhostCommunication () protected
Definition at line 593 of file DomainDecomposition.cpp.
References cellGrid, commCells, doGhostCommunication(), fillCells(), espressopp::CellGrid::getFrameGridSize(), espressopp::CellGrid::getFrameWidth(), espressopp::CellGrid::getInnerCellsBegin(), espressopp::CellGrid::getInnerCellsEnd(), and LOG4ESPP_DEBUG.
Referenced by cellAdjust(), and DomainDecomposition().
pyAddParticle()
bool espressopp::storage::Storage::pyAddParticle (longint id, const Real3D & pos) inherited
Referenced by espressopp::storage::Storage::getAdrATParticlesG().
recvParticles()
void espressopp::storage::Storage::recvParticles (ParticleList & list, longint node) protected inherited
receive particles from another node.
The particles are added to the given cell. The operation is blocking: the operation will wait until the particles have been received.
The particles are not added to localParticles! Moreover, the cell might be resized, invalidating all particles localParticles entries. Therefore, if the receiving cell is the final destination of the particles, call updateLocalParticles after recvParticles.
Definition at line 515 of file Storage.cpp.
References espressopp::storage::Storage::afterRecvParticles, espressopp::storage::Storage::inBuffer, LOG4ESPP_DEBUG, espressopp::InBuffer::read(), espressopp::InBuffer::recv(), and espressopp::storage::Storage::updateInLocalParticles().
Referenced by decomposeRealParticles(), and espressopp::storage::DomainDecompositionAdress::decomposeRealParticles().
registerPython()
void espressopp::storage::DomainDecomposition::registerPython () static
Definition at line 773 of file DomainDecomposition.cpp.
References cellAdjust(), getInt3DCellGrid(), getInt3DNodeGrid(), and mapPositionToNodeClipped().
Referenced by espressopp::storage::registerPython().
removeAdrATParticle()
void espressopp::storage::Storage::removeAdrATParticle (longint id) inherited
Definition at line 154 of file Storage.cpp.
References espressopp::storage::Storage::AdrATParticles, espressopp::storage::Storage::localAdrATParticles, espressopp::storage::Storage::lookupAdrATParticle(), espressopp::storage::Storage::updateInLocalAdrATParticles(), and espressopp::storage::Storage::updateLocalParticles().
removeAllParticles()
void espressopp::storage::Storage::removeAllParticles () inherited
Definition at line 315 of file Storage.cpp.
References espressopp::storage::Storage::localCells, espressopp::storage::Storage::localParticles, and espressopp::storage::Storage::onParticlesChanged.
Referenced by espressopp::storage::Storage::registerPython().
removeFromLocalParticles()
void espressopp::storage::Storage::removeFromLocalParticles (Particle * p, bool weak = false) protected inherited
Definition at line 116 of file Storage.cpp.
References espressopp::Particle::id(), espressopp::storage::Storage::localParticles, and LOG4ESPP_TRACE.
Referenced by espressopp::storage::DomainDecompositionAdress::invalidateGhosts(), espressopp::storage::Storage::invalidateGhosts(), espressopp::storage::DomainDecompositionNonBlocking::isendParticles(), espressopp::storage::Storage::removeParticle(), and espressopp::storage::Storage::sendParticles().
removeParticle()
int espressopp::storage::Storage::removeParticle (longint id) inherited
Definition at line 284 of file Storage.cpp.
References espressopp::Particle::id(), espressopp::storage::Storage::lookupRealParticle(), espressopp::storage::Storage::mapPositionToCellChecked(), espressopp::storage::Storage::onParticlesChanged, espressopp::Cell::particles, espressopp::Particle::position(), espressopp::storage::Storage::removeFromLocalParticles(), and espressopp::storage::Storage::updateLocalParticles().
Referenced by espressopp::storage::Storage::registerPython().
resizeCells()
void espressopp::storage::Storage::resizeCells (longint nCells) protected inherited
Definition at line 248 of file Storage.cpp.
References espressopp::storage::Storage::cells, and espressopp::storage::Storage::localCells.
Referenced by createCellGrid(), and espressopp::storage::DomainDecompositionAdress::createCellGrid().
restorePositions()
void espressopp::storage::Storage::restorePositions () protected inherited
Definition at line 715 of file Storage.cpp.
References espressopp::SystemAccess::getSystem(), espressopp::Particle::image(), espressopp::storage::Storage::lookupRealParticle(), espressopp::Particle::position(), espressopp::storage::Storage::savedImages, espressopp::storage::Storage::savedRealPositions, and espressopp::esutil::Error::setException().
Referenced by espressopp::storage::Storage::clearAdrATParticlesG(), and espressopp::storage::Storage::registerPython().
savePosition()
void espressopp::storage::Storage::savePosition (size_t id) protected inherited
Definition at line 698 of file Storage.cpp.
References espressopp::SystemAccess::getSystem(), espressopp::SystemAccess::getSystemRef(), espressopp::Particle::image(), espressopp::storage::Storage::lookupRealParticle(), espressopp::Particle::position(), espressopp::storage::Storage::savedImages, espressopp::storage::Storage::savedRealPositions, and espressopp::esutil::Error::setException().
Referenced by espressopp::storage::Storage::clearAdrATParticlesG(), and espressopp::storage::Storage::registerPython().
scaleVolume() [1/4]
void espressopp::storage::DomainDecomposition::scaleVolume (real s, bool particleCoordinates) virtual
scale position coordinates of all real particles by factor s
Implements espressopp::storage::Storage.
Definition at line 164 of file DomainDecomposition.cpp.
References cellAdjust(), cellGrid, espressopp::CellGrid::getSmallestCellDiameter(), espressopp::SystemAccess::getSystem(), espressopp::SystemAccess::getSystemRef(), nodeGrid, espressopp::storage::Storage::scaleVolume(), espressopp::CellGrid::scaleVolume(), espressopp::storage::NodeGrid::scaleVolume(), and espressopp::esutil::Error::setException().
scaleVolume() [2/4]
void espressopp::storage::DomainDecomposition::scaleVolume (Real3D s, bool pS) virtual
Scale Volume for derived classes, pS define the particle coordinates scaling.
Anisotropic case
Implements espressopp::storage::Storage.
Definition at line 189 of file DomainDecomposition.cpp.
References cellAdjust(), cellGrid, espressopp::CellGrid::getSmallestCellDiameter(), espressopp::SystemAccess::getSystem(), espressopp::SystemAccess::getSystemRef(), nodeGrid, espressopp::storage::Storage::scaleVolume(), espressopp::CellGrid::scaleVolume(), espressopp::storage::NodeGrid::scaleVolume(), and espressopp::esutil::Error::setException().
scaleVolume() [3/4]
void espressopp::storage::Storage::scaleVolume (real s) inherited
Scale Volume, only for Storage.
Scale coordinates of all real particles by factor s.
It scales only the particle coord.
Definition at line 136 of file Storage.cpp.
References espressopp::iterator::CellListIterator::isDone(), and espressopp::storage::Storage::realCells.
Referenced by scaleVolume().
scaleVolume() [4/4]
void espressopp::storage::Storage::scaleVolume (Real3D s) inherited
Scale Volume, only for Storage.
Scale coordinates of all real particles by factor s.
It scales only the particle coord. Anisotropic case
Anisotropic case
Definition at line 144 of file Storage.cpp.
References espressopp::iterator::CellListIterator::isDone(), and espressopp::storage::Storage::realCells.
sendParticles()
void espressopp::storage::Storage::sendParticles (ParticleList & list, longint node) protected inherited
send particles of a cell to another node, and empty the cell locally.
The operation is blocking: the operation will wait until the particles really have been received.
The particles are not removed from localParticles!
Definition at line 489 of file Storage.cpp.
References espressopp::storage::Storage::beforeSendParticles, espressopp::esutil::ESPPIterator< STLContainer >::isValid(), LOG4ESPP_DEBUG, espressopp::storage::Storage::outBuffer, espressopp::storage::Storage::removeFromLocalParticles(), and espressopp::Buffer::reset().
Referenced by decomposeRealParticles(), and espressopp::storage::DomainDecompositionAdress::decomposeRealParticles().
setFixedTuplesAdress()
void espressopp::storage::Storage::setFixedTuplesAdress (shared_ptr< FixedTupleListAdress > _fixedtupleList) inline inherited
Definition at line 250 of file Storage.hpp.
References espressopp::storage::Storage::fixedtupleList.
Referenced by espressopp::storage::Storage::registerPython().
unpackAndAddForces()
void espressopp::storage::Storage::unpackAndAddForces (Cell & reals, class InBuffer & buf) protected virtual inherited
unpack received ghost forces.
This one ADDS, and is most likely, what you need.
Reimplemented in espressopp::storage::DomainDecompositionAdress.
Definition at line 659 of file Storage.cpp.
References espressopp::ParticleForce::f, espressopp::storage::Storage::getFirstCell(), LOG4ESPP_DEBUG, LOG4ESPP_TRACE, espressopp::Cell::particles, and espressopp::InBuffer::read().
Referenced by espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), and doGhostCommunication().
unpackForces()
void espressopp::storage::Storage::unpackForces (Cell & reals, class InBuffer & buf) protected inherited
unpack received ghost forces.
This one OVERWRITES, and is probably what you don't need.
Definition at line 643 of file Storage.cpp.
References espressopp::storage::Storage::getFirstCell(), LOG4ESPP_DEBUG, LOG4ESPP_TRACE, espressopp::Cell::particles, and espressopp::InBuffer::read().
unpackPositionsEtc()
void espressopp::storage::Storage::unpackPositionsEtc (Cell & ghosts, class InBuffer & buf, int extradata) protected virtual inherited
unpack received data for ghosts.
Reimplemented in espressopp::storage::DomainDecompositionAdress.
Definition at line 581 of file Storage.cpp.
References espressopp::storage::Storage::DATA_LOCAL, espressopp::storage::Storage::DATA_MOMENTUM, espressopp::storage::Storage::DATA_PROPERTIES, espressopp::storage::Storage::getFirstCell(), LOG4ESPP_DEBUG, espressopp::Cell::particles, espressopp::InBuffer::read(), and espressopp::storage::Storage::updateInLocalParticles().
Referenced by espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), and doGhostCommunication().
updateGhosts()
void espressopp::storage::DomainDecomposition::updateGhosts () virtual
copy minimal information from the real to the ghost particles.
Typically this copies the positions and maybe the velocities from real to ghost particles. Particle order is unaffected by this method.
Storage implementations should exchange particle positions, plus data fields as indicated by dataOfUpdateGhosts.
Implements espressopp::storage::Storage.
Definition at line 546 of file DomainDecomposition.cpp.
References espressopp::storage::Storage::dataOfUpdateGhosts, doGhostCommunication(), and LOG4ESPP_DEBUG.
updateGhostsV()
void espressopp::storage::DomainDecomposition::updateGhostsV () virtual
Copies just velocites of real particles to their ghosts.
Needed for DPD thermostat for example.
Implements espressopp::storage::Storage.
Definition at line 551 of file DomainDecomposition.cpp.
References doGhostCommunication(), and LOG4ESPP_DEBUG.
updateInLocalAdrATParticles()
void espressopp::storage::Storage::updateInLocalAdrATParticles (Particle * p) inline protected inherited
Definition at line 231 of file Storage.cpp.
References espressopp::Particle::id(), and espressopp::storage::Storage::localAdrATParticles.
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addAdrATParticleFTPL(), espressopp::storage::Storage::removeAdrATParticle(), and espressopp::storage::Storage::updateLocalParticles().
updateInLocalParticles()
void espressopp::storage::Storage::updateInLocalParticles (Particle * p, bool weak = false) protected inherited
Definition at line 189 of file Storage.cpp.
References espressopp::Particle::id(), espressopp::storage::Storage::localParticles, and LOG4ESPP_TRACE.
Referenced by espressopp::storage::Storage::appendIndexedParticle(), espressopp::storage::DomainDecompositionNonBlocking::irecvParticles_finish(), espressopp::storage::Storage::moveIndexedParticle(), espressopp::storage::Storage::recvParticles(), espressopp::storage::DomainDecompositionAdress::unpackPositionsEtc(), espressopp::storage::Storage::unpackPositionsEtc(), and espressopp::storage::Storage::updateLocalParticles().
updateLocalParticles()
void espressopp::storage::Storage::updateLocalParticles (ParticleList & list, bool adress = false) protected inherited
Definition at line 235 of file Storage.cpp.
References espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::storage::Storage::updateInLocalAdrATParticles(), and espressopp::storage::Storage::updateInLocalParticles().
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addAdrATParticleFTPL(), espressopp::storage::Storage::appendIndexedParticle(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), cellAdjust(), espressopp::storage::Storage::fetchParticles(), espressopp::storage::Storage::moveIndexedParticle(), espressopp::storage::Storage::removeAdrATParticle(), and espressopp::storage::Storage::removeParticle().
Member Data Documentation
afterRecvParticles
boost::signals2::signal<void (ParticleList&, class InBuffer&)> espressopp::storage::Storage::afterRecvParticles inherited
Definition at line 241 of file Storage.hpp.
Referenced by espressopp::storage::DomainDecompositionNonBlocking::irecvParticles_finish(), and espressopp::storage::Storage::recvParticles().
beforeSendParticles
boost::signals2::signal<void (ParticleList&, class OutBuffer&)> espressopp::storage::Storage::beforeSendParticles inherited
Definition at line 239 of file Storage.hpp.
Referenced by espressopp::storage::DomainDecompositionNonBlocking::isendParticles(), and espressopp::storage::Storage::sendParticles().
cellGrid
CellGrid espressopp::storage::DomainDecomposition::cellGrid protected
spatial domain decomposition on node in cells
Definition at line 115 of file DomainDecomposition.hpp.
Referenced by appendParticles(), createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), decomposeRealParticles(), fillCells(), getInt3DCellGrid(), initCellInteractions(), mapPositionToCell(), mapPositionToCellChecked(), mapPositionToCellClipped(), markCells(), prepareGhostCommunication(), and scaleVolume().
cells
LocalCellList espressopp::storage::Storage::cells protected inherited
here the local particles are actually stored
Definition at line 391 of file Storage.hpp.
Referenced by appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), cellAdjust(), fillCells(), espressopp::storage::DomainDecompositionAdress::fillCells(), espressopp::storage::Storage::getFirstCell(), initCellInteractions(), espressopp::storage::DomainDecompositionAdress::initCellInteractions(), espressopp::storage::DomainDecompositionAdress::mapPositionToCell(), mapPositionToCell(), espressopp::storage::DomainDecompositionAdress::mapPositionToCellChecked(), mapPositionToCellChecked(), espressopp::storage::DomainDecompositionAdress::mapPositionToCellClipped(), mapPositionToCellClipped(), markCells(), espressopp::storage::DomainDecompositionAdress::markCells(), and espressopp::storage::Storage::resizeCells().
commCells
CommCells espressopp::storage::DomainDecomposition::commCells[6] protected
which cells to send left, right, up, down, ...
For the order, see NodeGrid.
Definition at line 130 of file DomainDecomposition.hpp.
Referenced by cellAdjust(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), doGhostCommunication(), and prepareGhostCommunication().
dataOfExchangeGhosts
const int espressopp::storage::Storage::dataOfExchangeGhosts = DATA_PROPERTIES static protected inherited
Definition at line 296 of file Storage.hpp.
Referenced by exchangeGhosts(), and espressopp::storage::DomainDecompositionAdress::exchangeGhosts().
dataOfUpdateGhosts
const int espressopp::storage::Storage::dataOfUpdateGhosts = 0 static protected inherited
for the moment, these are constants, defining what to transfer during ghost communications.
Definition at line 295 of file Storage.hpp.
Referenced by updateGhosts(), and espressopp::storage::DomainDecompositionAdress::updateGhosts().
exchangeBufferSize
size_t espressopp::storage::DomainDecomposition::exchangeBufferSize protected
expected capacity of send/recv buffers for neighbor communication
Definition at line 118 of file DomainDecomposition.hpp.
Referenced by espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), and decomposeRealParticles().
fixedtupleList
shared_ptr<FixedTupleListAdress> espressopp::storage::Storage::fixedtupleList protected inherited
Definition at line 407 of file Storage.hpp.
Referenced by espressopp::storage::DomainDecompositionAdress::addAdrGhostForcesToReals(), espressopp::storage::DomainDecompositionAdress::copyGhostTuples(), espressopp::storage::Storage::getFixedTuples(), espressopp::storage::DomainDecompositionAdress::invalidateGhosts(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::storage::Storage::setFixedTuplesAdress(), espressopp::storage::DomainDecompositionAdress::unpackAndAddForces(), and espressopp::storage::DomainDecompositionAdress::unpackPositionsEtc().
ghostCells
CellList espressopp::storage::Storage::ghostCells protected inherited
list of ghost cells
Definition at line 396 of file Storage.hpp.
Referenced by espressopp::storage::DomainDecompositionAdress::cellAdjust(), cellAdjust(), createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::Storage::getGhostCells(), espressopp::storage::Storage::getNGhostParticles(), markCells(), and espressopp::storage::DomainDecompositionAdress::markCells().
inBuffer
InBuffer espressopp::storage::Storage::inBuffer protected inherited
Definition at line 402 of file Storage.hpp.
Referenced by doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), and espressopp::storage::Storage::recvParticles().
localCells
CellList espressopp::storage::Storage::localCells protected inherited
all cells on this CPU.
Just an index of the cells
Definition at line 398 of file Storage.hpp.
Referenced by espressopp::storage::DomainDecompositionAdress::cellAdjust(), cellAdjust(), espressopp::storage::Storage::getLocalCells(), espressopp::storage::Storage::getNLocalParticles(), espressopp::storage::Storage::removeAllParticles(), and espressopp::storage::Storage::resizeCells().
nodeGrid
NodeGrid espressopp::storage::DomainDecomposition::nodeGrid protected
spatial domain decomposition of nodes
Definition at line 112 of file DomainDecomposition.hpp.
Referenced by appendParticles(), cellAdjust(), createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), doGhostCommunication(), getInt3DNodeGrid(), mapPositionToNodeClipped(), and scaleVolume().
onParticlesChanged
boost::signals2::signal<void ()> espressopp::storage::Storage::onParticlesChanged inherited
Ths signal will be called whenever the storage was modified such that particle pointers have become invalid, e.g.
at the end of decompose(). Classes that connect to this signal can update pointers to the particles in the call via lookupLocalParticle() and lookupRealParticle().
Definition at line 237 of file Storage.hpp.
Referenced by espressopp::storage::DomainDecompositionAdress::cellAdjust(), cellAdjust(), espressopp::storage::DomainDecompositionAdress::decompose(), espressopp::storage::Storage::decompose(), espressopp::storage::Storage::removeAllParticles(), and espressopp::storage::Storage::removeParticle().
onTuplesChanged
boost::signals2::signal<void ()> espressopp::storage::Storage::onTuplesChanged inherited
Definition at line 246 of file Storage.hpp.
Referenced by espressopp::storage::DomainDecompositionAdress::decompose().
outBuffer
OutBuffer espressopp::storage::Storage::outBuffer protected inherited
Definition at line 403 of file Storage.hpp.
Referenced by doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), and espressopp::storage::Storage::sendParticles().
realCells
CellList espressopp::storage::Storage::realCells protected inherited
list of real cells
Definition at line 394 of file Storage.hpp.
Referenced by espressopp::storage::DomainDecompositionAdress::cellAdjust(), cellAdjust(), createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::Storage::fetchParticles(), espressopp::storage::Storage::getNRealParticles(), espressopp::storage::Storage::getRealCells(), espressopp::storage::Storage::getRealParticleIDs(), markCells(), espressopp::storage::DomainDecompositionAdress::markCells(), and espressopp::storage::Storage::scaleVolume().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/storage/DomainDecomposition.hpp
/home/espressopp/espressopp/src/storage/DomainDecomposition.cpp