ESPResSo++: espressopp::analysis::ConfigurationExt Class Reference
espressopp::analysis::ConfigurationExt Class Reference
Class that stores particle positions for later analysis.
#include <ConfigurationExt.hpp>
Public Member Functions
ConfigurationExt ()
~ConfigurationExt ()
RealND getProperties (size_t id)
size_t getSize ()
void set (size_t id, RealND vec)
class ConfigurationExtIterator getIterator ()
Static Public Member Functions
static void registerPython ()
Private Attributes
std::map< size_t, RealND > particleProperties
Detailed Description
Class that stores particle positions for later analysis.
Definition at line 69 of file ConfigurationExt.hpp.
Constructor & Destructor Documentation
ConfigurationExt()
espressopp::analysis::ConfigurationExt::ConfigurationExt ()
Definition at line 39 of file ConfigurationExt.cpp.
~ConfigurationExt()
espressopp::analysis::ConfigurationExt::~ConfigurationExt ()
Definition at line 44 of file ConfigurationExt.cpp.
Member Function Documentation
getIterator()
ConfigurationExtIterator espressopp::analysis::ConfigurationExt::getIterator ()
Definition at line 81 of file ConfigurationExt.cpp.
Referenced by registerPython().
getProperties()
RealND espressopp::analysis::ConfigurationExt::getProperties (size_t id)
Definition at line 60 of file ConfigurationExt.cpp.
Referenced by registerPython().
getSize()
size_t espressopp::analysis::ConfigurationExt::getSize () inline
Definition at line 81 of file ConfigurationExt.hpp.
References particleProperties.
Referenced by registerPython().
registerPython()
void espressopp::analysis::ConfigurationExt::registerPython () static
Definition at line 163 of file ConfigurationExt.cpp.
References getIterator(), getProperties(), getSize(), espressopp::analysis::ConfigurationExtIterator::nextId(), and espressopp::analysis::pass_through().
Referenced by espressopp::analysis::registerPython().
set()
void espressopp::analysis::ConfigurationExt::set (size_t id, RealND vec)
Definition at line 52 of file ConfigurationExt.cpp.
References espressopp::RealND::getDimension().
Member Data Documentation
particleProperties
std::map<size_t, RealND > espressopp::analysis::ConfigurationExt::particleProperties private
Definition at line 95 of file ConfigurationExt.hpp.
Referenced by getSize().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/analysis/ConfigurationExt.hpp
/home/espressopp/espressopp/src/analysis/ConfigurationExt.cpp