ESPResSo++: espressopp::interaction::AngularUniqueHarmonic Class Reference
espressopp::interaction::AngularUniqueHarmonic Class Reference
This class provides methods to compute forces and energies of the AngularUniqueHarmonic angular potential.
#include <AngularUniqueHarmonic.hpp>
Public Member Functions
AngularUniqueHarmonic ()
AngularUniqueHarmonic (real _K)
void setK (real _K)
real getK () const
void preset ()
real _computeEnergyRaw (real _theta, real _theta0) const
bool _computeForceRaw (Real3D &force12, Real3D &force32, const Real3D &r12, const Real3D &r32, real _theta0) const
real _computeForceRaw (const real theta, const real theta0) const
virtual real computeEnergy (const Particle &p1, const Particle &p2, const Particle &p3, real theta0) const
virtual real computeEnergy (const Real3D &r12, const Real3D &r32, real theta0) const
virtual real computeEnergy (const real theta, real theta0) const
virtual void computeForce (Real3D &force12, Real3D &force32, const Particle &p1, const Particle &p2, const Particle &p3, real theta0) const
virtual void computeForce (Real3D &force12, Real3D &force32, const Real3D &r12, const Real3D &r32, real cos0) const
virtual real computeForce (real theta, real cos0) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
real _computeEnergy (const Particle &p1, const Particle &p2, const Particle &p3, real theta0) const
real _computeEnergy (const Real3D &r12, const Real3D &r32, real theta0) const
real _computeEnergy (real theta, real theta0) const
void _computeForce (Real3D &force12, Real3D &force32, const Particle &p1, const Particle &p2, const Particle &p3, real theta0) const
bool _computeForce (Real3D &force12, Real3D &force32, const Real3D &r12, const Real3D &r32, real theta0) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
AngularUniqueHarmonic * derived_this ()
const AngularUniqueHarmonic * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
Private Attributes
real K
real KpK
Detailed Description
This class provides methods to compute forces and energies of the AngularUniqueHarmonic angular potential.
To create a new angular potential one only needs to write the setter/getters and the variable dU_dtheta.
Definition at line 37 of file AngularUniqueHarmonic.hpp.
Constructor & Destructor Documentation
AngularUniqueHarmonic() [1/2]
espressopp::interaction::AngularUniqueHarmonic::AngularUniqueHarmonic () inline
Definition at line 46 of file AngularUniqueHarmonic.hpp.
AngularUniqueHarmonic() [2/2]
espressopp::interaction::AngularUniqueHarmonic::AngularUniqueHarmonic (real _K) inline
Definition at line 47 of file AngularUniqueHarmonic.hpp.
References preset().
Member Function Documentation
_computeEnergy() [1/3]
real espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueHarmonic >::_computeEnergy (const Particle & p1, const Particle & p2, const Particle & p3, real theta0) const inline inherited
Definition at line 160 of file AngularUniquePotential.hpp.
_computeEnergy() [2/3]
real espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueHarmonic >::_computeEnergy (const Real3D & r12, const Real3D & r32, real theta0) const inline inherited
Definition at line 169 of file AngularUniquePotential.hpp.
_computeEnergy() [3/3]
real espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueHarmonic >::_computeEnergy (real theta, real theta0) const inline inherited
Definition at line 183 of file AngularUniquePotential.hpp.
_computeEnergyRaw()
real espressopp::interaction::AngularUniqueHarmonic::_computeEnergyRaw (real _theta, real _theta0) const inline
Definition at line 61 of file AngularUniqueHarmonic.hpp.
_computeForce() [1/2]
void espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueHarmonic >::_computeForce (Real3D & force12, Real3D & force32, const Particle & p1, const Particle & p2, const Particle & p3, real theta0) const inline inherited
Definition at line 213 of file AngularUniquePotential.hpp.
_computeForce() [2/2]
bool espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueHarmonic >::_computeForce (Real3D & force12, Real3D & force32, const Real3D & r12, const Real3D & r32, real theta0) const inline inherited
Definition at line 225 of file AngularUniquePotential.hpp.
_computeForceRaw() [1/2]
bool espressopp::interaction::AngularUniqueHarmonic::_computeForceRaw (Real3D & force12, Real3D & force32, const Real3D & r12, const Real3D & r32, real _theta0) const inline
Definition at line 67 of file AngularUniqueHarmonic.hpp.
References espressopp::Real3D::sqr().
_computeForceRaw() [2/2]
real espressopp::interaction::AngularUniqueHarmonic::_computeForceRaw (const real theta, const real theta0) const inline
Definition at line 98 of file AngularUniqueHarmonic.hpp.
computeEnergy() [1/3]
real espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueHarmonic >::computeEnergy (const Particle & p1, const Particle & p2, const Particle & p3, real theta0) const inline virtual inherited
Implements espressopp::interaction::AngularUniquePotential.
Definition at line 134 of file AngularUniquePotential.hpp.
computeEnergy() [2/3]
real espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueHarmonic >::computeEnergy (const Real3D & r12, const Real3D & r32, real theta0) const inline virtual inherited
Implements espressopp::interaction::AngularUniquePotential.
Definition at line 143 of file AngularUniquePotential.hpp.
computeEnergy() [3/3]
real espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueHarmonic >::computeEnergy (const real theta, real theta0) const inline virtual inherited
Implements espressopp::interaction::AngularUniquePotential.
Definition at line 153 of file AngularUniquePotential.hpp.
computeForce() [1/3]
void espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueHarmonic >::computeForce (Real3D & force12, Real3D & force32, const Particle & p1, const Particle & p2, const Particle & p3, real theta0) const inline virtual inherited
Implements espressopp::interaction::AngularUniquePotential.
Definition at line 191 of file AngularUniquePotential.hpp.
computeForce() [2/3]
void espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueHarmonic >::computeForce (Real3D & force12, Real3D & force32, const Real3D & r12, const Real3D & r32, real cos0) const inline virtual inherited
Implements espressopp::interaction::AngularUniquePotential.
Definition at line 203 of file AngularUniquePotential.hpp.
computeForce() [3/3]
real espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueHarmonic >::computeForce (real theta, real cos0) const inline virtual inherited
Implements espressopp::interaction::AngularUniquePotential.
Definition at line 237 of file AngularUniquePotential.hpp.
derived_this() [1/2]
AngularUniqueHarmonic * espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueHarmonic >::derived_this () inline protected inherited
Definition at line 96 of file AngularUniquePotential.hpp.
derived_this() [2/2]
const AngularUniqueHarmonic * espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueHarmonic >::derived_this () const inline protected inherited
Definition at line 100 of file AngularUniquePotential.hpp.
getCutoff()
real espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueHarmonic >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::AngularUniquePotential.
Definition at line 127 of file AngularUniquePotential.hpp.
getK()
real espressopp::interaction::AngularUniqueHarmonic::getK () const inline
Definition at line 55 of file AngularUniqueHarmonic.hpp.
References K.
Referenced by registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::AngularUniquePotential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
preset()
void espressopp::interaction::AngularUniqueHarmonic::preset () inline
Definition at line 57 of file AngularUniqueHarmonic.hpp.
References K.
Referenced by AngularUniqueHarmonic(), and setK().
registerPython()
void espressopp::interaction::AngularUniqueHarmonic::registerPython () static
Definition at line 33 of file AngularUniqueHarmonic.cpp.
References getK(), and setK().
Referenced by espressopp::interaction::registerPython().
setCutoff()
void espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueHarmonic >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::AngularUniquePotential.
Definition at line 119 of file AngularUniquePotential.hpp.
setK()
void espressopp::interaction::AngularUniqueHarmonic::setK (real _K) inline
Definition at line 51 of file AngularUniqueHarmonic.hpp.
References preset().
Referenced by registerPython().
Member Data Documentation
cutoff
real espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueHarmonic >::cutoff protected inherited
Definition at line 93 of file AngularUniquePotential.hpp.
cutoffSqr
real espressopp::interaction::AngularUniquePotentialTemplate< AngularUniqueHarmonic >::cutoffSqr protected inherited
Definition at line 94 of file AngularUniquePotential.hpp.
K
real espressopp::interaction::AngularUniqueHarmonic::K private
Definition at line 39 of file AngularUniqueHarmonic.hpp.
Referenced by getK(), and preset().
KpK
real espressopp::interaction::AngularUniqueHarmonic::KpK private
Definition at line 41 of file AngularUniqueHarmonic.hpp.
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/AngularUniqueHarmonic.hpp
/home/espressopp/espressopp/src/interaction/AngularUniqueHarmonic.cpp