ESPResSo++: espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential > Class Template Reference
espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential > Class Template Reference
#include <VerletListHadressCGInteractionTemplate.hpp>
Public Member Functions
VerletListHadressCGInteractionTemplate (shared_ptr< VerletListAdress > _verletList, shared_ptr< FixedTupleListAdress > _fixedtupleList)
void setVerletList (shared_ptr< VerletListAdress > _verletList)
shared_ptr< VerletListAdress > getVerletList ()
void setFixedTupleList (shared_ptr< FixedTupleListAdress > _fixedtupleList)
void setPotential (int type1, int type2, const Potential &potential)
Potential & getPotential (int type1, int type2)
shared_ptr< Potential > getPotentialPtr (int type1, int type2)
virtual void addForces ()
virtual real computeEnergy ()
virtual real computeEnergyDeriv ()
virtual real computeEnergyAA ()
virtual real computeEnergyCG ()
virtual real computeEnergyAA (int atomtype)
virtual real computeEnergyCG (int atomtype)
virtual void computeVirialX (std::vector< real > &p_xx_total, int bins)
virtual real computeVirial ()
virtual void computeVirialTensor (Tensor &w)
virtual void computeVirialTensor (Tensor &w, real z)
virtual void computeVirialTensor (Tensor *w, int n)
virtual real getMaxCutoff ()
This method returns the maximal cutoff defined for one type pair.
virtual int bondType ()
Static Public Member Functions
static void registerPython ()
Protected Types
typedef _Potential Potential
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (theLogger)
Logger.
Protected Attributes
int ntypes
shared_ptr< VerletListAdress > verletList
shared_ptr< FixedTupleListAdress > fixedtupleList
esutil::Array2D< Potential, esutil::enlarge > potentialArray
real pidhy2
real dexdhy
real dexdhy2
real dex
real dhy
real dex2
boost::unordered_map< Particle *, real > energydiff
std::set< Particle * > adrZone
std::set< Particle * > cgZone
Detailed Description
template<typename _Potential>
class espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >
Definition at line 42 of file VerletListHadressCGInteractionTemplate.hpp.
Member Typedef Documentation
Potential
template<typename _Potential > typedef _Potential espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::Potential protected
Definition at line 45 of file VerletListHadressCGInteractionTemplate.hpp.
Constructor & Destructor Documentation
VerletListHadressCGInteractionTemplate()
template<typename _Potential > espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::VerletListHadressCGInteractionTemplate (shared_ptr< VerletListAdress > _verletList, shared_ptr< FixedTupleListAdress > _fixedtupleList) inline
Definition at line 49 of file VerletListHadressCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::dex, espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::dex2, espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::dexdhy, espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::dexdhy2, espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::dhy, M_PI, espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::ntypes, espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::pidhy2, espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::potentialArray, and espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::verletList.
Member Function Documentation
addForces()
template<typename _Potential > void espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::addForces () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 139 of file VerletListHadressCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::adrZone, espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::cgZone, espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeEnergy(), espressopp::Particle::drift(), espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::energydiff, espressopp::Particle::force(), espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::getPotential(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::Particle::lambda(), espressopp::Particle::lambdaDeriv(), LOG4ESPP_INFO, espressopp::Particle::position(), espressopp::Real3D::sqr(), espressopp::Particle::type(), and espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::verletList.
Referenced by espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::getPotentialPtr().
bondType()
template<typename _Potential > virtual int espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::bondType () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 111 of file VerletListHadressCGInteractionTemplate.hpp.
References espressopp::interaction::NonbondedSlow.
computeEnergy()
template<typename _Potential > real espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeEnergy () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 275 of file VerletListHadressCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeEnergyDeriv(), espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::getPotential(), espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::getVerletList(), espressopp::esutil::ESPPIterator< STLContainer >::isValid(), espressopp::Particle::lambda(), LOG4ESPP_INFO, espressopp::Particle::type(), and espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::verletList.
Referenced by espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::addForces(), and espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::getPotentialPtr().
computeEnergyAA() [1/2]
template<typename _Potential > real espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeEnergyAA () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 317 of file VerletListHadressCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeEnergyDeriv(), and espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::getPotentialPtr().
computeEnergyAA() [2/2]
template<typename _Potential > real espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeEnergyAA (int atomtype) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 324 of file VerletListHadressCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeEnergyCG().
computeEnergyCG() [1/2]
template<typename _Potential > real espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeEnergyCG () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 331 of file VerletListHadressCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeEnergyAA(), and espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::getPotentialPtr().
computeEnergyCG() [2/2]
template<typename _Potential > real espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeEnergyCG (int atomtype) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 338 of file VerletListHadressCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeVirialX().
computeEnergyDeriv()
template<typename _Potential > real espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeEnergyDeriv () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 310 of file VerletListHadressCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeEnergyAA().
Referenced by espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeEnergy(), and espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::getPotentialPtr().
computeVirial()
template<typename _Potential > real espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeVirial () inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 351 of file VerletListHadressCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeVirialTensor(), and LOG4ESPP_INFO.
Referenced by espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeVirialX(), and espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::getPotentialPtr().
computeVirialTensor() [1/3]
template<typename _Potential > void espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeVirialTensor (Tensor & w) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 359 of file VerletListHadressCGInteractionTemplate.hpp.
References LOG4ESPP_INFO.
Referenced by espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeVirialTensor(), and espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::getPotentialPtr().
computeVirialTensor() [2/3]
template<typename _Potential > void espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeVirialTensor (Tensor & w, real z) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 366 of file VerletListHadressCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeVirialTensor(), and LOG4ESPP_INFO.
computeVirialTensor() [3/3]
template<typename _Potential > void espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeVirialTensor (Tensor * w, int n) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 373 of file VerletListHadressCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::getMaxCutoff().
computeVirialX()
template<typename _Potential > void espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeVirialX (std::vector< real > & p_xx_total, int bins) inline virtual
Implements espressopp::interaction::Interaction.
Definition at line 345 of file VerletListHadressCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeVirial().
Referenced by espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeEnergyCG(), and espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::getPotentialPtr().
getMaxCutoff()
template<typename _Potential > real espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::getMaxCutoff () inline virtual
This method returns the maximal cutoff defined for one type pair.
Implements espressopp::interaction::Interaction.
Definition at line 380 of file VerletListHadressCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::getPotential(), and espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::ntypes.
Referenced by espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeVirialTensor(), and espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::getPotentialPtr().
getPotential()
template<typename _Potential > Potential& espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::getPotential (int type1, int type2) inline
Definition at line 90 of file VerletListHadressCGInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), and espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::potentialArray.
Referenced by espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeEnergy(), and espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::getMaxCutoff().
getPotentialPtr()
template<typename _Potential > shared_ptr<Potential> espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::getPotentialPtr (int type1, int type2) inline
Definition at line 94 of file VerletListHadressCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::addForces(), espressopp::esutil::Array2D< T, outlier_mode >::at(), espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeEnergyAA(), espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeEnergyCG(), espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeEnergyDeriv(), espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeVirialX(), espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::getMaxCutoff(), and espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::potentialArray.
getVerletList()
template<typename _Potential > shared_ptr<VerletListAdress> espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::getVerletList () inline
Definition at line 70 of file VerletListHadressCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::verletList.
Referenced by espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeEnergy().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Interaction::LOG4ESPP_DECL_LOGGER (theLogger) static protected inherited
Logger.
Referenced by espressopp::interaction::Interaction::~Interaction().
registerPython()
void espressopp::interaction::Interaction::registerPython () static inherited
Definition at line 36 of file Interaction.cpp.
References espressopp::interaction::Interaction::bondType(), espressopp::interaction::Interaction::computeEnergy(), espressopp::interaction::Interaction::computeEnergyAA(), espressopp::interaction::Interaction::computeEnergyCG(), espressopp::interaction::Interaction::computeEnergyDeriv(), and espressopp::interaction::Interaction::computeVirial().
Referenced by espressopp::interaction::registerPython(), and espressopp::interaction::Interaction::~Interaction().
setFixedTupleList()
template<typename _Potential > void espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::setFixedTupleList (shared_ptr< FixedTupleListAdress > _fixedtupleList) inline
Definition at line 75 of file VerletListHadressCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::fixedtupleList.
setPotential()
template<typename _Potential > void espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::setPotential (int type1, int type2, const Potential & potential) inline
Definition at line 80 of file VerletListHadressCGInteractionTemplate.hpp.
References espressopp::esutil::Array2D< T, outlier_mode >::at(), espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::ntypes, and espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::potentialArray.
setVerletList()
template<typename _Potential > void espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::setVerletList (shared_ptr< VerletListAdress > _verletList) inline
Definition at line 66 of file VerletListHadressCGInteractionTemplate.hpp.
References espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::verletList.
Member Data Documentation
adrZone
template<typename _Potential > std::set<Particle*> espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::adrZone protected
Definition at line 129 of file VerletListHadressCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::addForces().
cgZone
template<typename _Potential > std::set<Particle*> espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::cgZone protected
Definition at line 130 of file VerletListHadressCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::addForces().
dex
template<typename _Potential > real espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::dex protected
Definition at line 125 of file VerletListHadressCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::VerletListHadressCGInteractionTemplate().
dex2
template<typename _Potential > real espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::dex2 protected
Definition at line 127 of file VerletListHadressCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::VerletListHadressCGInteractionTemplate().
dexdhy
template<typename _Potential > real espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::dexdhy protected
Definition at line 123 of file VerletListHadressCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::VerletListHadressCGInteractionTemplate().
dexdhy2
template<typename _Potential > real espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::dexdhy2 protected
Definition at line 124 of file VerletListHadressCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::VerletListHadressCGInteractionTemplate().
dhy
template<typename _Potential > real espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::dhy protected
Definition at line 126 of file VerletListHadressCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::VerletListHadressCGInteractionTemplate().
energydiff
template<typename _Potential > boost::unordered_map<Particle*, real> espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::energydiff protected
Definition at line 128 of file VerletListHadressCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::addForces().
fixedtupleList
template<typename _Potential > shared_ptr<FixedTupleListAdress> espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::fixedtupleList protected
Definition at line 118 of file VerletListHadressCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::setFixedTupleList().
ntypes
template<typename _Potential > int espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::ntypes protected
Definition at line 116 of file VerletListHadressCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::getMaxCutoff(), espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::setPotential(), and espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::VerletListHadressCGInteractionTemplate().
pidhy2
template<typename _Potential > real espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::pidhy2 protected
Definition at line 122 of file VerletListHadressCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::VerletListHadressCGInteractionTemplate().
potentialArray
template<typename _Potential > esutil::Array2D<Potential, esutil::enlarge> espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::potentialArray protected
Definition at line 119 of file VerletListHadressCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::getPotential(), espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::getPotentialPtr(), espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::setPotential(), and espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::VerletListHadressCGInteractionTemplate().
verletList
template<typename _Potential > shared_ptr<VerletListAdress> espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::verletList protected
Definition at line 117 of file VerletListHadressCGInteractionTemplate.hpp.
Referenced by espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::getVerletList(), espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::setVerletList(), and espressopp::interaction::VerletListHadressCGInteractionTemplate< _Potential >::VerletListHadressCGInteractionTemplate().
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/interaction/VerletListHadressCGInteractionTemplate.hpp