ESPResSo++: espressopp::analysis::MeanSquareDispl Class Reference
espressopp::analysis::MeanSquareDispl Class Reference
#include <MeanSquareDispl.hpp>
Public Member Functions
MeanSquareDispl (shared_ptr< System > system)
MeanSquareDispl (shared_ptr< System > system, int chainlength)
~MeanSquareDispl ()
virtual python::list compute () const
python::list computeG2 () const
python::list computeG3 () const
void setPrint_progress (bool _print_progress)
bool getPrint_progress ()
int getListSize () const
void gather ()
void gatherFromFile (string filename)
ConfigurationPtr getConf (int position) const
ConfigurationList all () const
void clear ()
shared_ptr< System > getSystem () const
Get shared pointer to the system.
shared_ptr< System > getSystem1 () const
shared_ptr< System > getSystem2 () const
System & getSystemRef () const
Get a system reference.
System & getSystemRef1 () const
System & getSystemRef2 () const
Static Public Member Functions
static void registerPython ()
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (logger)
Protected Attributes
int num_of_part
int chainlength
map< size_t, int > idToCpu
map< size_t, int > cidToCpu
map< size_t, int > idToCid
string key
Private Member Functions
void printReal3D (Real3D v) const
Private Attributes
bool print_progress
Detailed Description
Definition at line 40 of file MeanSquareDispl.hpp.
Constructor & Destructor Documentation
espressopp::analysis::MeanSquareDispl::MeanSquareDispl (shared_ptr< System > system) inline
Definition at line 43 of file MeanSquareDispl.hpp.
References espressopp::analysis::ConfigsParticleDecomp::key, and setPrint_progress().
espressopp::analysis::MeanSquareDispl::MeanSquareDispl (shared_ptr< System > system, int chainlength) inline
Definition at line 49 of file MeanSquareDispl.hpp.
References espressopp::analysis::ConfigsParticleDecomp::key, and setPrint_progress().
espressopp::analysis::MeanSquareDispl::~MeanSquareDispl () inline
Definition at line 56 of file MeanSquareDispl.hpp.
Member Function Documentation
ConfigurationList espressopp::analysis::ConfigsParticleDecomp::all () const inherited
Definition at line 46 of file ConfigsParticleDecomp.cpp.
void espressopp::analysis::ConfigsParticleDecomp::clear () inline inherited
Definition at line 271 of file ConfigsParticleDecomp.hpp.
python::list espressopp::analysis::MeanSquareDispl::compute () const virtual
Implements espressopp::analysis::ConfigsParticleDecomp.
Definition at line 41 of file MeanSquareDispl.cpp.
References espressopp::System::comm, mpiWorld, and espressopp::Real3D::sqr().
python::list espressopp::analysis::MeanSquareDispl::computeG2 () const
Definition at line 142 of file MeanSquareDispl.cpp.
python::list espressopp::analysis::MeanSquareDispl::computeG3 () const
stores particleIDs of local particles calculated by CPU
total number of chains
stores COM of conf m and chain cid as local_chainCOMlist[m][cid]
stores COM of the whole system for each snapshot, called 'centerOfMassList in compute()
< position of COM of chain
< mass of chain
< counts number of particles of one chain
< counts chains of one CPU
< COM of particles on one CPU
< local chains' COM of one conf/snapshot
< pid
< COM of system
Definition at line 254 of file MeanSquareDispl.cpp.
References espressopp::System::comm, mpiWorld, and espressopp::Real3D::sqr().
void espressopp::analysis::ConfigsParticleDecomp::gather () inherited
Definition at line 69 of file ConfigsParticleDecomp.cpp.
References espressopp::System::bc, espressopp::System::comm, espressopp::iterator::CellListIterator::isDone(), espressopp::esutil::Error::setException(), and espressopp::System::storage.
void espressopp::analysis::ConfigsParticleDecomp::gatherFromFile (string filename) inherited
Definition at line 133 of file ConfigsParticleDecomp.cpp.
References espressopp::System::comm, espressopp::esutil::Error::setException(), and espressopp::System::storage.
ConfigurationPtr espressopp::analysis::ConfigsParticleDecomp::getConf (int position) const inherited
Definition at line 50 of file ConfigsParticleDecomp.cpp.
References espressopp::System::comm, and espressopp::esutil::Error::setException().
int espressopp::analysis::ConfigsParticleDecomp::getListSize () const inherited
Definition at line 42 of file ConfigsParticleDecomp.cpp.
bool espressopp::analysis::MeanSquareDispl::getPrint_progress () inline
Definition at line 67 of file MeanSquareDispl.hpp.
References print_progress.
shared_ptr< System > espressopp::SystemAccess::getSystem () const inline inherited
Get shared pointer to the system.
Definition at line 96 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem.
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecomposition::appendParticles(), espressopp::storage::DomainDecompositionAdress::appendParticles(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::storage::DomainDecomposition::checkIsRealParticle(), espressopp::storage::DomainDecompositionAdress::checkIsRealParticle(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::VerletListTriple::connect(), espressopp::VerletList::connect(), espressopp::integrator::LatticeBoltzmann::convLenMDtoLB(), espressopp::storage::DomainDecomposition::createCellGrid(), espressopp::storage::DomainDecompositionAdress::createCellGrid(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::io::DumpGRO::DumpGRO(), espressopp::io::DumpGROAdress::DumpGROAdress(), espressopp::io::DumpXYZ::DumpXYZ(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::analysis::LBOutputScreen::findLBMom(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::SystemAccess::getSystemRef(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::integrator::LatticeBoltzmann::initGammas(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::LatticeBoltzmann::initLatticeModel(), espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::storage::DomainDecompositionAdress::packForces(), espressopp::storage::DomainDecompositionAdress::packPositionsEtc(), espressopp::integrator::LatticeBoltzmann::readCouplForces(), espressopp::VerletListTriple::rebuild(), espressopp::VerletList::rebuild(), espressopp::VerletListAdress::rebuild(), espressopp::VerletListTriple::registerPython(), espressopp::VerletList::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::storage::Storage::registerPython(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::storage::Storage::restorePositions(), espressopp::integrator::LatticeBoltzmann::saveCouplForces(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::io::DumpGRO::setLengthUnit(), espressopp::io::DumpGROAdress::setLengthUnit(), espressopp::io::DumpXYZ::setLengthUnit(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::analysis::LBOutputScreen::writeOutput(), and espressopp::integrator::LatticeBoltzmann::zeroMDCMVel().
shared_ptr< System > espressopp::SystemAccess::getSystem1 () const inline inherited
Definition at line 105 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem1.
Referenced by espressopp::SystemAccess::getSystemRef1().
shared_ptr< System > espressopp::SystemAccess::getSystem2 () const inline inherited
Definition at line 114 of file SystemAccess.hpp.
References espressopp::SystemAccess::mySystem2.
Referenced by espressopp::SystemAccess::getSystemRef2().
System& espressopp::SystemAccess::getSystemRef () const inline inherited
Get a system reference.
Definition at line 49 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem().
Referenced by espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::AssociationReaction::applyAR(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::TDforce::applyForce(), espressopp::integrator::CapForce::applyForceCappingToAll(), espressopp::integrator::ExtForce::applyForceToAll(), espressopp::integrator::BerendsenBarostatAnisotropic::barostat(), espressopp::integrator::BerendsenBarostat::barostat(), espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::Adress::communicateAdrPositions(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::integrator::Settle::correctVelocities(), espressopp::integrator::LatticeBoltzmann::coupleLBtoMD(), espressopp::integrator::LatticeBoltzmann::findCMVelMD(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LatticeBoltzmann::galileanTransf(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::VelocityVerletOnRadius::initForces(), espressopp::integrator::Adress::initForces(), espressopp::integrator::VelocityVerletOnGroup::initForces(), espressopp::integrator::DPDThermostat::initialize(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::integrator::StochasticVelocityRescaling::initialize(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::VelocityVerletOnRadius::integrate1(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::VelocityVerletOnGroup::integrate1(), espressopp::integrator::VelocityVerletOnRadius::integrate2(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::VelocityVerletOnGroup::integrate2(), espressopp::VerletListTriple::localSize(), espressopp::VerletList::localSize(), espressopp::integrator::LatticeBoltzmann::makeDecompose(), espressopp::integrator::VelocityVerletOnGroup::printForces(), espressopp::integrator::VelocityVerletOnGroup::printPositions(), espressopp::integrator::AssociationReaction::react(), espressopp::integrator::LatticeBoltzmann::readCouplForces(), espressopp::VerletListAdress::rebuild(), espressopp::integrator::Isokinetic::rescaleVelocities(), espressopp::integrator::StochasticVelocityRescaling::rescaleVelocities(), espressopp::integrator::LatticeBoltzmann::restoreLBForces(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::MinimizeEnergy::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::LatticeBoltzmann::saveCouplForces(), espressopp::integrator::Settle::saveOldPos(), espressopp::storage::Storage::savePosition(), espressopp::storage::DomainDecomposition::scaleVolume(), espressopp::integrator::AssociationReaction::sendMultiMap(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::MDIntegrator::setTimeStep(), espressopp::integrator::Settle::settlep(), espressopp::integrator::Settle::settlev(), espressopp::integrator::VelocityVerletOnGroup::setUp(), espressopp::integrator::MinimizeEnergy::steepestDescentStep(), espressopp::integrator::LangevinThermostat::thermalize(), espressopp::integrator::DPDThermostat::thermalize(), espressopp::integrator::LangevinThermostat1D::thermalize(), espressopp::integrator::LangevinThermostat::thermalizeAdr(), espressopp::integrator::LangevinThermostat1D::thermalizeAdr(), espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr(), espressopp::integrator::BerendsenThermostat::thermostat(), espressopp::VerletListTriple::totalSize(), espressopp::VerletList::totalSize(), espressopp::VerletListAdress::totalSize(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), espressopp::integrator::MinimizeEnergy::updateForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), espressopp::integrator::LangevinBarostat::updDisplacement(), espressopp::integrator::LangevinBarostat::updForces(), espressopp::integrator::LangevinBarostat::updVolume(), espressopp::integrator::LangevinBarostat::updVolumeMomentum(), and espressopp::analysis::LBOutputScreen::writeOutput().
System& espressopp::SystemAccess::getSystemRef1 () const inline inherited
Definition at line 50 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem1().
System& espressopp::SystemAccess::getSystemRef2 () const inline inherited
Definition at line 51 of file SystemAccess.hpp.
References espressopp::SystemAccess::getSystem2().
static espressopp::analysis::ConfigsParticleDecomp::LOG4ESPP_DECL_LOGGER (logger) static protected inherited
void espressopp::analysis::MeanSquareDispl::printReal3D (Real3D v) const inline private
Definition at line 74 of file MeanSquareDispl.hpp.
References espressopp::Real3D::getItem().
void espressopp::analysis::MeanSquareDispl::registerPython () static
Definition at line 436 of file MeanSquareDispl.cpp.
Referenced by espressopp::analysis::registerPython().
void espressopp::analysis::MeanSquareDispl::setPrint_progress (bool _print_progress) inline
Definition at line 63 of file MeanSquareDispl.hpp.
References print_progress.
Referenced by MeanSquareDispl().
Member Data Documentation
int espressopp::analysis::ConfigsParticleDecomp::chainlength protected inherited
Definition at line 285 of file ConfigsParticleDecomp.hpp.
map< size_t, int > espressopp::analysis::ConfigsParticleDecomp::cidToCpu protected inherited
Definition at line 287 of file ConfigsParticleDecomp.hpp.
map< size_t, int > espressopp::analysis::ConfigsParticleDecomp::idToCid protected inherited
Definition at line 288 of file ConfigsParticleDecomp.hpp.
map< size_t, int > espressopp::analysis::ConfigsParticleDecomp::idToCpu protected inherited
Definition at line 286 of file ConfigsParticleDecomp.hpp.
string espressopp::analysis::ConfigsParticleDecomp::key protected inherited
Definition at line 290 of file ConfigsParticleDecomp.hpp.
Referenced by MeanSquareDispl(), espressopp::analysis::MeanSquareInternalDist::MeanSquareInternalDist(), and espressopp::analysis::VelocityAutocorrelation::VelocityAutocorrelation().
int espressopp::analysis::ConfigsParticleDecomp::num_of_part protected inherited
Definition at line 284 of file ConfigsParticleDecomp.hpp.
bool espressopp::analysis::MeanSquareDispl::print_progress private
Definition at line 73 of file MeanSquareDispl.hpp.
Referenced by getPrint_progress(), and setPrint_progress().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/analysis/MeanSquareDispl.hpp
/home/travis/build/espressopp/espressopp/src/analysis/MeanSquareDispl.cpp