ESPResSo++: espressopp::esutil::UserTimer Class Reference
espressopp::esutil::UserTimer Class Reference
timer measuring the user time.
#include <Timer.hpp>
Public Member Functions
UserTimer ()
void reset ()
reset the starting time
float getElapsedTime () const
get the time that elapsed since the last reset
Protected Attributes
float currentTime
Private Member Functions
virtual float getCurrentTime () const
Detailed Description
timer measuring the user time.
Definition at line 58 of file Timer.hpp.
Constructor & Destructor Documentation
espressopp::esutil::UserTimer::UserTimer () [inline]
Definition at line 61 of file Timer.hpp.
References espressopp::esutil::Timer::reset().
Member Function Documentation
float UserTimer::getCurrentTime () const [private, virtual]
Implements espressopp::esutil::Timer.
Definition at line 40 of file Timer.cpp.
float espressopp::esutil::Timer::getElapsedTime () const [inline, inherited]
get the time that elapsed since the last reset
Definition at line 48 of file Timer.hpp.
References espressopp::esutil::Timer::currentTime, and espressopp::esutil::Timer::getCurrentTime().
Referenced by espressopp::integrator::VelocityVerletOnGroup::calcForces(), espressopp::integrator::LatticeBoltzmann::collideStream(), espressopp::esutil::operator<<(), espressopp::integrator::LatticeBoltzmann::readCouplForces(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::LatticeBoltzmann::saveCouplForces(), espressopp::integrator::VelocityVerletOnGroup::updateForces(), and espressopp::analysis::LBOutputScreen::writeOutput().
void espressopp::esutil::Timer::reset () [inline, inherited]
reset the starting time
Definition at line 46 of file Timer.hpp.
References espressopp::esutil::Timer::currentTime, and espressopp::esutil::Timer::getCurrentTime().
Referenced by espressopp::integrator::LatticeBoltzmann::LatticeBoltzmann(), espressopp::integrator::LatticeBoltzmann::makeLBStep(), espressopp::integrator::LatticeBoltzmann::readCouplForces(), espressopp::integrator::VelocityVerletOnGroup::run(), espressopp::integrator::VelocityVerlet::run(), espressopp::integrator::LatticeBoltzmann::saveCouplForces(), UserTimer(), and espressopp::analysis::LBOutputScreen::writeOutput().
Member Data Documentation
float espressopp::esutil::Timer::currentTime [protected, inherited]
Definition at line 41 of file Timer.hpp.
Referenced by espressopp::esutil::Timer::getElapsedTime(), and espressopp::esutil::Timer::reset().
The documentation for this class was generated from the following files:
/home/travis/build/espressopp/espressopp/src/esutil/Timer.hpp
/home/travis/build/espressopp/espressopp/src/esutil/Timer.cpp