ESPResSo++: espressopp::vectorization::CellNeighborList Class Reference
espressopp::vectorization::CellNeighborList Class Reference
stores neighbor cells used for all-pair loops (following Newton's 3rd law) as 2d array second index corresponds to one cell in particleArray first index corresponds to neighbor cells zeroth column contains the index in localcells first column (first index) contains size N, so columns [1,N+1) represent the neighbors
#include <CellNeighborList.hpp>
Public Types
typedef size_t T
typedef T value_type
typedef T & reference
typedef const T & const_reference
typedef Super::size_type size_type
Public Member Functions
CellNeighborList ()
CellNeighborList (shared_ptr< storage::Storage > &storage)
void clear ()
reference at (size_type row, size_type nbr)
const_reference at (size_type row, size_type nbr) const
size_type numCells () const
size_type maxNumNeighbors () const
reference & cellId (size_type row)
const_reference & cellId (size_type row) const
reference & numNeighbors (size_type row)
const_reference & numNeighbors (size_type row) const
void print ()
Private Types
typedef esutil::Array2D< size_t, esutil::enlarge > Super
typedef Super::iterator iterator
Iterator used to iterate through an Array1D.
typedef Super::const_iterator const_iterator
Const-iterator used to iterate through an Array1D.
Private Member Functions
void init (size_type n, size_type m, const size_t &t=size_t())
Creates a two-dimensional n x m array, initialising the values with copies of t.
void resize (size_type n, size_type m, const size_t &t=size_t())
Changes the size of the Array2D so that the size becomes n x m.
size_type size_n () const
Returns the n -size of the array.
size_type size_x () const
Returns the n -size of the array.
size_type size_m () const
Returns the m -size of the array.
size_type size_y () const
Returns the m -size of the array.
bool empty () const
true if the Array2D's size is 0 x 0.
reference operator() (size_type i, size_type j)
Returns the element at position i x j.
const_reference operator() (size_type i, size_type j) const
Returns the element at position i x j.
reference operator() (const Vector &pos)
Returns the element at position pos.
const_reference operator() (const Vector &pos) const
Returns the element at position pos.
reference at (const Vector &pos)
Returns the element at position pos.
const_reference at (const Vector &pos) const
Returns the element at position pos.
iterator begin ()
Returns an iterator pointing to the beginning of the Array2D.
const_iterator begin () const
Returns a const_iterator pointing to the beginning of the Array2D.
iterator end ()
Returns an iterator pointing to the end of the Array2D.
const_iterator end () const
Returns a const_iterator pointing to the end of the Array2D.
void operator+= (const T2 &t2)
Adds t2 to each of the elements.
void operator-= (const T2 &t2)
Adds t2 to each of the elements.
void operator*= (const T2 &t2)
Multiplies each of the elements by t2.
void operator/= (const T2 &t2)
Divides each of the elements by t2.
void operator/= (const double &x)
bool operator== (const Array2D< size_t, exception > &a)
Equality operator.
bool operator!= (const Array2D< size_t, exception > &a)
Inequality operator.
Private Attributes
size_t startCell = 0
Detailed Description
stores neighbor cells used for all-pair loops (following Newton's 3rd law) as 2d array second index corresponds to one cell in particleArray first index corresponds to neighbor cells zeroth column contains the index in localcells first column (first index) contains size N, so columns [1,N+1) represent the neighbors
Definition at line 36 of file CellNeighborList.hpp.
Member Typedef Documentation
const_iterator
typedef Super::const_iterator espressopp::esutil::Array2D< size_t , outlier_mode >::const_iterator inherited
Const-iterator used to iterate through an Array1D.
Definition at line 61 of file Array2D.hpp.
const_reference
typedef const T& espressopp::vectorization::CellNeighborList::const_reference
Definition at line 44 of file CellNeighborList.hpp.
iterator
typedef Super::iterator espressopp::esutil::Array2D< size_t , outlier_mode >::iterator inherited
Iterator used to iterate through an Array1D.
Definition at line 59 of file Array2D.hpp.
reference
typedef T& espressopp::vectorization::CellNeighborList::reference
Definition at line 43 of file CellNeighborList.hpp.
size_type
typedef Super::size_type espressopp::vectorization::CellNeighborList::size_type
Definition at line 45 of file CellNeighborList.hpp.
Super
typedef esutil::Array2D<size_t, esutil::enlarge> espressopp::vectorization::CellNeighborList::Super private
Definition at line 38 of file CellNeighborList.hpp.
T
typedef size_t espressopp::vectorization::CellNeighborList::T
Definition at line 41 of file CellNeighborList.hpp.
value_type
typedef T espressopp::vectorization::CellNeighborList::value_type
Definition at line 42 of file CellNeighborList.hpp.
Constructor & Destructor Documentation
CellNeighborList() [1/2]
espressopp::vectorization::CellNeighborList::CellNeighborList () inline
Definition at line 47 of file CellNeighborList.hpp.
CellNeighborList() [2/2]
espressopp::vectorization::CellNeighborList::CellNeighborList (shared_ptr< storage::Storage > & storage) inline
Definition at line 48 of file CellNeighborList.hpp.
References at(), cellId(), numCells(), numNeighbors(), espressopp::esutil::Array2D< size_t, esutil::enlarge >::resize(), and espressopp::esutil::Array2D< size_t, esutil::enlarge >::size_n().
Member Function Documentation
at() [1/4]
reference espressopp::vectorization::CellNeighborList::at (size_type row, size_type nbr) inline
Definition at line 81 of file CellNeighborList.hpp.
References espressopp::esutil::Array2D< size_t, esutil::enlarge >::at().
Referenced by CellNeighborList().
at() [2/4]
const_reference espressopp::vectorization::CellNeighborList::at (size_type row, size_type nbr) const inline
Definition at line 82 of file CellNeighborList.hpp.
References espressopp::esutil::Array2D< size_t, esutil::enlarge >::operator()().
at() [3/4]
reference espressopp::esutil::Array2D< size_t , outlier_mode >::at (const Vector & pos) inline inherited
Returns the element at position pos.
pos must be a vector where the expressions pos[0] and pos[1] return the first and second element.
Exceptions
out_of_range i is out of range of the Array2D
Definition at line 165 of file Array2D.hpp.
at() [4/4]
const_reference espressopp::esutil::Array2D< size_t , outlier_mode >::at (const Vector & pos) const inline inherited
Returns the element at position pos.
pos must be a vector where the expressions pos[0] and pos[1] return the first and second element.
Exceptions
out_of_range i is out of range of the Array2D
Definition at line 175 of file Array2D.hpp.
begin() [1/2]
iterator espressopp::esutil::Array2D< size_t , outlier_mode >::begin () inline inherited
Returns an iterator pointing to the beginning of the Array2D.
Definition at line 180 of file Array2D.hpp.
begin() [2/2]
const_iterator espressopp::esutil::Array2D< size_t , outlier_mode >::begin () const inline inherited
Returns a const_iterator pointing to the beginning of the Array2D.
Definition at line 184 of file Array2D.hpp.
cellId() [1/2]
reference& espressopp::vectorization::CellNeighborList::cellId (size_type row) inline
Definition at line 85 of file CellNeighborList.hpp.
References espressopp::esutil::Array2D< size_t, esutil::enlarge >::at().
Referenced by CellNeighborList().
cellId() [2/2]
const_reference& espressopp::vectorization::CellNeighborList::cellId (size_type row) const inline
Definition at line 86 of file CellNeighborList.hpp.
References espressopp::esutil::Array2D< size_t, esutil::enlarge >::operator()().
clear()
void espressopp::vectorization::CellNeighborList::clear () inline
Definition at line 80 of file CellNeighborList.hpp.
References espressopp::esutil::Array2D< size_t, esutil::enlarge >::clear().
empty()
bool espressopp::esutil::Array2D< size_t , outlier_mode >::empty () const inline inherited
true if the Array2D's size is 0 x 0.
Definition at line 112 of file Array2D.hpp.
end() [1/2]
iterator espressopp::esutil::Array2D< size_t , outlier_mode >::end () inline inherited
Returns an iterator pointing to the end of the Array2D.
Definition at line 188 of file Array2D.hpp.
end() [2/2]
const_iterator espressopp::esutil::Array2D< size_t , outlier_mode >::end () const inline inherited
Returns a const_iterator pointing to the end of the Array2D.
Definition at line 192 of file Array2D.hpp.
init()
void espressopp::esutil::Array2D< size_t , outlier_mode >::init (size_type n, size_type m, const size_t & t = T()) inline inherited
Creates a two-dimensional n x m array, initialising the values with copies of t.
Definition at line 80 of file Array2D.hpp.
maxNumNeighbors()
size_type espressopp::vectorization::CellNeighborList::maxNumNeighbors () const inline
Definition at line 84 of file CellNeighborList.hpp.
References espressopp::esutil::Array2D< size_t, esutil::enlarge >::size_n().
Referenced by espressopp::vectorization::Vectorization::resetCells().
numCells()
size_type espressopp::vectorization::CellNeighborList::numCells () const inline
Definition at line 83 of file CellNeighborList.hpp.
References espressopp::esutil::Array2D< size_t, esutil::enlarge >::size_m().
Referenced by CellNeighborList(), and espressopp::vectorization::Vectorization::resetCells().
numNeighbors() [1/2]
reference& espressopp::vectorization::CellNeighborList::numNeighbors (size_type row) inline
Definition at line 87 of file CellNeighborList.hpp.
References espressopp::esutil::Array2D< size_t, esutil::enlarge >::at().
Referenced by CellNeighborList().
numNeighbors() [2/2]
const_reference& espressopp::vectorization::CellNeighborList::numNeighbors (size_type row) const inline
Definition at line 88 of file CellNeighborList.hpp.
References espressopp::esutil::Array2D< size_t, esutil::enlarge >::operator()().
operator!=()
bool espressopp::esutil::Array2D< size_t , outlier_mode >::operator!= (const Array2D< size_t , exception > & a) inline inherited
Inequality operator.
Definition at line 234 of file Array2D.hpp.
operator()() [1/4]
reference espressopp::esutil::Array2D< size_t , outlier_mode >::operator() (size_type i, size_type j) inline inherited
Returns the element at position i x j.
Attention
No range checking.
Definition at line 116 of file Array2D.hpp.
Referenced by at(), cellId(), and numNeighbors().
operator()() [2/4]
const_reference espressopp::esutil::Array2D< size_t , outlier_mode >::operator() (size_type i, size_type j) const inline inherited
Returns the element at position i x j.
Attention
No range checking.
Definition at line 121 of file Array2D.hpp.
operator()() [3/4]
reference espressopp::esutil::Array2D< size_t , outlier_mode >::operator() (const Vector & pos) inline inherited
Returns the element at position pos.
pos must be a vector where the expressions pos[0] and pos[1] return the indices.
Attention
No range checking.
Definition at line 130 of file Array2D.hpp.
operator()() [4/4]
const_reference espressopp::esutil::Array2D< size_t , outlier_mode >::operator() (const Vector & pos) const inline inherited
Returns the element at position pos.
pos must be a vector where the expressions pos[0] and pos[1] return the indices.
Attention
No range checking.
Definition at line 139 of file Array2D.hpp.
operator*=()
void espressopp::esutil::Array2D< size_t , outlier_mode >::operator*= (const T2 & t2) inline inherited
Multiplies each of the elements by t2.
Definition at line 214 of file Array2D.hpp.
operator+=()
void espressopp::esutil::Array2D< size_t , outlier_mode >::operator+= (const T2 & t2) inline inherited
Adds t2 to each of the elements.
Definition at line 202 of file Array2D.hpp.
operator-=()
void espressopp::esutil::Array2D< size_t , outlier_mode >::operator-= (const T2 & t2) inline inherited
Adds t2 to each of the elements.
Definition at line 208 of file Array2D.hpp.
operator/=() [1/2]
void espressopp::esutil::Array2D< size_t , outlier_mode >::operator/= (const T2 & t2) inline inherited
Divides each of the elements by t2.
Definition at line 219 of file Array2D.hpp.
operator/=() [2/2]
void espressopp::esutil::Array2D< size_t , outlier_mode >::operator/= (const double & x) inline inherited
Definition at line 222 of file Array2D.hpp.
operator==()
bool espressopp::esutil::Array2D< size_t , outlier_mode >::operator== (const Array2D< size_t , exception > & a) inline inherited
Equality operator.
Definition at line 228 of file Array2D.hpp.
print()
void espressopp::vectorization::CellNeighborList::print () inline
Definition at line 90 of file CellNeighborList.hpp.
References espressopp::esutil::Array2D< size_t, esutil::enlarge >::size_m(), and espressopp::esutil::Array2D< size_t, esutil::enlarge >::size_n().
resize()
void espressopp::esutil::Array2D< size_t , outlier_mode >::resize (size_type n, size_type m, const size_t & t = T()) inline inherited
Changes the size of the Array2D so that the size becomes n x m.
Attention
The elements of the Array2D are not initialised consistently, so the values are undefined. The t parameter exists only for the purpose to provide a default T value when new elements are created and needs to be specified only when T has no default constructor.
Definition at line 95 of file Array2D.hpp.
Referenced by CellNeighborList().
size_m()
size_type espressopp::esutil::Array2D< size_t , outlier_mode >::size_m () const inline inherited
Returns the m -size of the array.
Definition at line 107 of file Array2D.hpp.
Referenced by numCells(), and print().
size_n()
size_type espressopp::esutil::Array2D< size_t , outlier_mode >::size_n () const inline inherited
Returns the n -size of the array.
Definition at line 102 of file Array2D.hpp.
Referenced by CellNeighborList(), maxNumNeighbors(), and print().
size_x()
size_type espressopp::esutil::Array2D< size_t , outlier_mode >::size_x () const inline inherited
Returns the n -size of the array.
Definition at line 104 of file Array2D.hpp.
size_y()
size_type espressopp::esutil::Array2D< size_t , outlier_mode >::size_y () const inline inherited
Returns the m -size of the array.
Definition at line 109 of file Array2D.hpp.
Member Data Documentation
startCell
size_t espressopp::vectorization::CellNeighborList::startCell = 0 private
Definition at line 39 of file CellNeighborList.hpp.
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/vectorization/CellNeighborList.hpp