ESPResSo++: espressopp::interaction::LennardJones93Wall Class Reference
espressopp::interaction::LennardJones93Wall Class Reference
This class provides methods to compute forces and energies for an Lennard-Jones 9-3 wall, in the direction dir.
#include <LennardJones93Wall.hpp>
Public Member Functions
LennardJones93Wall ()
~LennardJones93Wall ()
int bondType ()
real getMaxCutoff ()
void setParams (int type, real _epsilon, real _sigma, real _sigmaCutoff, real _r0)
python::tuple getParams (int type)
real setAutoShift (int type)
real _computeEnergyRaw (const Particle &p, const bc::BC &bc) const
bool _computeForceRaw (Real3D &force, const Particle &p, const bc::BC &bc) const
virtual real computeEnergy (const Particle &p, const bc::BC &bc) const
virtual Real3D computeForce (const Particle &p, const bc::BC &bc) const
real _computeEnergy (const Particle &p, const bc::BC &bc) const
bool _computeForce (Real3D &force, const Particle &p, const bc::BC &bc) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
LennardJones93Wall * derived_this ()
const LennardJones93Wall * derived_this () const
Private Attributes
std::vector< LJ93WParams > params_list
int dir
Detailed Description
This class provides methods to compute forces and energies for an Lennard-Jones 9-3 wall, in the direction dir.
Definition at line 53 of file LennardJones93Wall.hpp.
Constructor & Destructor Documentation
LennardJones93Wall()
espressopp::interaction::LennardJones93Wall::LennardJones93Wall () inline
Definition at line 61 of file LennardJones93Wall.hpp.
References espressopp::interaction::LJ93WParams::epsilon, espressopp::interaction::LJ93WParams::r0, espressopp::interaction::LJ93WParams::sigma, and espressopp::interaction::LJ93WParams::sigma3.
~LennardJones93Wall()
espressopp::interaction::LennardJones93Wall::~LennardJones93Wall () inline
Definition at line 70 of file LennardJones93Wall.hpp.
Member Function Documentation
_computeEnergy()
real espressopp::interaction::SingleParticlePotentialTemplate< LennardJones93Wall >::_computeEnergy (const Particle & p, const bc::BC & bc) const inline inherited
Definition at line 101 of file SingleParticlePotential.hpp.
References espressopp::interaction::SingleParticlePotentialTemplate< Derived >::computeForce().
_computeEnergyRaw()
real espressopp::interaction::LennardJones93Wall::_computeEnergyRaw (const Particle & p, const bc::BC & bc) const inline
Definition at line 101 of file LennardJones93Wall.hpp.
References espressopp::interaction::LJ93WParams::epsilon, espressopp::bc::BC::getBoxL(), espressopp::Particle::position(), espressopp::interaction::LJ93WParams::r0, espressopp::interaction::LJ93WParams::shift, espressopp::interaction::LJ93WParams::sigma3, espressopp::interaction::LJ93WParams::sigmaCutoff, and espressopp::Particle::type().
_computeForce()
bool espressopp::interaction::SingleParticlePotentialTemplate< LennardJones93Wall >::_computeForce (Real3D & force, const Particle & p, const bc::BC & bc) const inline inherited
Definition at line 120 of file SingleParticlePotential.hpp.
_computeForceRaw()
bool espressopp::interaction::LennardJones93Wall::_computeForceRaw (Real3D & force, const Particle & p, const bc::BC & bc) const inline
Definition at line 124 of file LennardJones93Wall.hpp.
References espressopp::interaction::LJ93WParams::epsilon, espressopp::bc::BC::getBoxL(), espressopp::Particle::position(), espressopp::interaction::LJ93WParams::r0, espressopp::interaction::LJ93WParams::sigma3, espressopp::interaction::LJ93WParams::sigmaCutoff, and espressopp::Particle::type().
bondType()
int espressopp::interaction::LennardJones93Wall::bondType () inline
Definition at line 72 of file LennardJones93Wall.hpp.
References espressopp::interaction::Single.
computeEnergy()
real espressopp::interaction::SingleParticlePotentialTemplate< LennardJones93Wall >::computeEnergy (const Particle & p, const bc::BC & bc) const inline virtual inherited
Implements espressopp::interaction::SingleParticlePotential.
Definition at line 94 of file SingleParticlePotential.hpp.
References espressopp::interaction::SingleParticlePotentialTemplate< Derived >::_computeEnergy().
computeForce()
Real3D espressopp::interaction::SingleParticlePotentialTemplate< LennardJones93Wall >::computeForce (const Particle & p, const bc::BC & bc) const inline virtual inherited
Implements espressopp::interaction::SingleParticlePotential.
Definition at line 109 of file SingleParticlePotential.hpp.
References espressopp::interaction::SingleParticlePotentialTemplate< Derived >::_computeForce().
derived_this() [1/2]
LennardJones93Wall * espressopp::interaction::SingleParticlePotentialTemplate< LennardJones93Wall >::derived_this () inline protected inherited
Definition at line 73 of file SingleParticlePotential.hpp.
derived_this() [2/2]
const LennardJones93Wall * espressopp::interaction::SingleParticlePotentialTemplate< LennardJones93Wall >::derived_this () const inline protected inherited
Definition at line 77 of file SingleParticlePotential.hpp.
getMaxCutoff()
real espressopp::interaction::LennardJones93Wall::getMaxCutoff () inline virtual
Implements espressopp::interaction::SingleParticlePotential.
Definition at line 73 of file LennardJones93Wall.hpp.
getParams()
python::tuple espressopp::interaction::LennardJones93Wall::getParams (int type) inline
Definition at line 87 of file LennardJones93Wall.hpp.
References espressopp::interaction::LJ93WParams::epsilon, espressopp::interaction::LJ93WParams::r0, espressopp::interaction::LJ93WParams::sigma, and espressopp::interaction::LJ93WParams::sigmaCutoff.
Referenced by registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::SingleParticlePotential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
registerPython()
void espressopp::interaction::LennardJones93Wall::registerPython () static
Definition at line 39 of file LennardJones93Wall.cpp.
References getParams(), and setParams().
Referenced by espressopp::interaction::registerPython().
setAutoShift()
real espressopp::interaction::LennardJones93Wall::setAutoShift (int type) inline
Definition at line 92 of file LennardJones93Wall.hpp.
References espressopp::interaction::LJ93WParams::epsilon, espressopp::interaction::LJ93WParams::shift, espressopp::interaction::LJ93WParams::sigma3, and espressopp::interaction::LJ93WParams::sigmaCutoff.
setParams()
void espressopp::interaction::LennardJones93Wall::setParams (int type, real _epsilon, real _sigma, real _sigmaCutoff, real _r0) inline
Definition at line 75 of file LennardJones93Wall.hpp.
Referenced by registerPython().
Member Data Documentation
dir
int espressopp::interaction::LennardJones93Wall::dir private
Definition at line 56 of file LennardJones93Wall.hpp.
params_list
std::vector<LJ93WParams> espressopp::interaction::LennardJones93Wall::params_list private
Definition at line 55 of file LennardJones93Wall.hpp.
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/LennardJones93Wall.hpp
/home/espressopp/espressopp/src/interaction/LennardJones93Wall.cpp