ESPResSo++: espressopp::interaction::LennardJonesSoftcoreTI Class Reference
espressopp::interaction::LennardJonesSoftcoreTI Class Reference
This class provides methods to compute forces and energies of the softcore Lennard Jones potential in a Thermodynamic Integration simulation.
#include <LennardJonesSoftcoreTI.hpp>
Public Member Functions
LennardJonesSoftcoreTI ()
LennardJonesSoftcoreTI (real _epsilonA, real _sigmaA, real _epsilonB, real _sigmaB, real _alpha, real _p, real _cutoff, real _lambda, bool _annihilate)
virtual ~LennardJonesSoftcoreTI ()
real getLambdaTI () const
real getAlphaSC () const
real getPowerSC () const
void addPid (longint pid)
bool checkTIpair (size_t pid1, size_t pid2) const
real _computeEnergy (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
real _computeEnergyDeriv (const Particle &p1, const Particle &p2) const
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &dist, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)
virtual shared_ptr< FixedPairList > getColVarBondList () const
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &fpl)
virtual shared_ptr< FixedTripleList > getColVarAngleList () const
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fpl)
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const
virtual void setColVar (const RealND &cv)
virtual void setColVar (const Real3D &dist, const bc::BC &bc)
virtual RealND getColVar () const
virtual void computeColVarWeights (const Real3D &dist, const bc::BC &bc)
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
LennardJonesSoftcoreTI * derived_this ()
const LennardJonesSoftcoreTI * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
shared_ptr< FixedPairList > colVarBondList
shared_ptr< FixedTripleList > colVarAngleList
shared_ptr< FixedQuadrupleList > colVarDihedList
RealND colVar
Private Member Functions
void preset ()
Private Attributes
real epsilonA
real epsilonB
real ff1A
real ff2A
real ff1B
real ff2B
bool annihilate
std::set< longint > pidsTI
real lambdaTI
real complLambdaTI
real alphaSC
real sigmaSC_A
real sigmaSC_B
real powerSC
real sigmaSC_A6
real sigmaSC_B6
real lambdaTI_powerSC
real lambdaTI_powerSCm1
real compllambdaTI_powerSC
real compllambdaTI_powerSCm1
real alpha_sigmaA6_lambdaP
real alpha_sigmaB6_compllambdaP
real powerSC_alphaSC_inv6
Detailed Description
This class provides methods to compute forces and energies of the softcore Lennard Jones potential in a Thermodynamic Integration simulation.
Definition at line 38 of file LennardJonesSoftcoreTI.hpp.
Constructor & Destructor Documentation
LennardJonesSoftcoreTI() [1/2]
espressopp::interaction::LennardJonesSoftcoreTI::LennardJonesSoftcoreTI () inline
Definition at line 87 of file LennardJonesSoftcoreTI.hpp.
References espressopp::infinity, preset(), espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::setCutoff(), and espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::setShift().
LennardJonesSoftcoreTI() [2/2]
espressopp::interaction::LennardJonesSoftcoreTI::LennardJonesSoftcoreTI (real _epsilonA, real _sigmaA, real _epsilonB, real _sigmaB, real _alpha, real _p, real _cutoff, real _lambda, bool _annihilate) inline
Definition at line 95 of file LennardJonesSoftcoreTI.hpp.
References espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::autoShift, preset(), and espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::setCutoff().
~LennardJonesSoftcoreTI()
virtual espressopp::interaction::LennardJonesSoftcoreTI::~LennardJonesSoftcoreTI () inline virtual
Definition at line 108 of file LennardJonesSoftcoreTI.hpp.
Member Function Documentation
_computeEnergy() [1/4]
real espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::_computeEnergy (const Real3D & dist) const inline inherited
Definition at line 367 of file Potential.hpp.
_computeEnergy() [2/4]
real espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::_computeEnergy (real dist) const inline inherited
Definition at line 374 of file Potential.hpp.
_computeEnergy() [3/4]
real espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 360 of file Potential.hpp.
_computeEnergy() [4/4]
real espressopp::interaction::LennardJonesSoftcoreTI::_computeEnergy (const Particle & p1, const Particle & p2) const inline
Definition at line 136 of file LennardJonesSoftcoreTI.hpp.
References checkTIpair(), espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::cutoffSqr, espressopp::Particle::id(), espressopp::Particle::position(), and espressopp::Real3D::sqr().
_computeEnergyDeriv()
real espressopp::interaction::LennardJonesSoftcoreTI::_computeEnergyDeriv (const Particle & p1, const Particle & p2) const inline
Definition at line 217 of file LennardJonesSoftcoreTI.hpp.
References checkTIpair(), espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::cutoffSqr, ff2A, ff2B, espressopp::Particle::id(), lambdaTI_powerSCm1, espressopp::Particle::position(), and espressopp::Real3D::sqr().
_computeEnergySqr()
real espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::_computeEnergySqr (real distSqr) const inline inherited
Definition at line 381 of file Potential.hpp.
_computeEnergySqrRaw()
real espressopp::interaction::LennardJonesSoftcoreTI::_computeEnergySqrRaw (real distSqr) const inline
Definition at line 267 of file LennardJonesSoftcoreTI.hpp.
_computeForce() [1/3]
bool espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::_computeForce (Real3D & force, const Real3D & dist) const inline inherited
Definition at line 438 of file Potential.hpp.
_computeForce() [2/3]
bool espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 431 of file Potential.hpp.
_computeForce() [3/3]
bool espressopp::interaction::LennardJonesSoftcoreTI::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const inline
Definition at line 172 of file LennardJonesSoftcoreTI.hpp.
References checkTIpair(), espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::cutoffSqr, ff2A, ff2B, espressopp::Particle::id(), espressopp::Particle::position(), and espressopp::Real3D::sqr().
_computeForceRaw()
bool espressopp::interaction::LennardJonesSoftcoreTI::_computeForceRaw (Real3D & force, const Real3D & dist, real distSqr) const inline
Definition at line 272 of file LennardJonesSoftcoreTI.hpp.
addPid()
void espressopp::interaction::LennardJonesSoftcoreTI::addPid (longint pid) inline
Definition at line 114 of file LennardJonesSoftcoreTI.hpp.
Referenced by registerPython().
checkTIpair()
bool espressopp::interaction::LennardJonesSoftcoreTI::checkTIpair (size_t pid1, size_t pid2) const inline
Definition at line 118 of file LennardJonesSoftcoreTI.hpp.
Referenced by _computeEnergy(), _computeEnergyDeriv(), and _computeForce().
computeColVarWeights()
void espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::computeColVarWeights (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 315 of file Potential.hpp.
computeEnergy() [1/3]
real espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::computeEnergy (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 323 of file Potential.hpp.
computeEnergy() [2/3]
real espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::computeEnergy (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 331 of file Potential.hpp.
computeEnergy() [3/3]
real espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::computeEnergy (real dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 338 of file Potential.hpp.
computeEnergySqr()
real espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::computeEnergySqr (real distsqr) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 345 of file Potential.hpp.
computeForce() [1/2]
Real3D espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::computeForce (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 405 of file Potential.hpp.
computeForce() [2/2]
Real3D espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::computeForce (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 413 of file Potential.hpp.
derived_this() [1/2]
LennardJonesSoftcoreTI * espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::derived_this () inline protected inherited
Definition at line 161 of file Potential.hpp.
derived_this() [2/2]
const LennardJonesSoftcoreTI * espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::derived_this () const inline protected inherited
Definition at line 165 of file Potential.hpp.
getAlphaSC()
real espressopp::interaction::LennardJonesSoftcoreTI::getAlphaSC () const inline
Definition at line 111 of file LennardJonesSoftcoreTI.hpp.
References alphaSC.
getColVar()
RealND espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::getColVar () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 309 of file Potential.hpp.
getColVarAngleList()
shared_ptr< FixedTripleList > espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::getColVarAngleList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 273 of file Potential.hpp.
getColVarBondList()
shared_ptr< FixedPairList > espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::getColVarBondList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 259 of file Potential.hpp.
getColVarDihedList()
shared_ptr< FixedQuadrupleList > espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::getColVarDihedList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 287 of file Potential.hpp.
getCutoff()
real espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 210 of file Potential.hpp.
getLambdaTI()
real espressopp::interaction::LennardJonesSoftcoreTI::getLambdaTI () const inline
Definition at line 110 of file LennardJonesSoftcoreTI.hpp.
References lambdaTI.
getPowerSC()
real espressopp::interaction::LennardJonesSoftcoreTI::getPowerSC () const inline
Definition at line 112 of file LennardJonesSoftcoreTI.hpp.
References powerSC.
getShift()
real espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::getShift () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 225 of file Potential.hpp.
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
Referenced by espressopp::interaction::Potential::~Potential().
preset()
void espressopp::interaction::LennardJonesSoftcoreTI::preset () inline private
Definition at line 60 of file LennardJonesSoftcoreTI.hpp.
References compllambdaTI_powerSC, lambdaTI, lambdaTI_powerSC, registerPython(), sigmaSC_A, and sigmaSC_B.
Referenced by LennardJonesSoftcoreTI().
registerPython()
void espressopp::interaction::LennardJonesSoftcoreTI::registerPython () static
Definition at line 50 of file LennardJonesSoftcoreTI.cpp.
References addPid().
Referenced by preset(), and espressopp::interaction::registerPython().
setAutoShift()
real espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::setAutoShift () inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 231 of file Potential.hpp.
setColVar() [1/2]
void espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::setColVar (const RealND & cv) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 294 of file Potential.hpp.
setColVar() [2/2]
void espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::setColVar (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 301 of file Potential.hpp.
setColVarAngleList()
void espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::setColVarAngleList (const shared_ptr< FixedTripleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 266 of file Potential.hpp.
setColVarBondList()
void espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::setColVarBondList (const shared_ptr< FixedPairList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 252 of file Potential.hpp.
setColVarDihedList()
void espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 280 of file Potential.hpp.
setCutoff()
void espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 201 of file Potential.hpp.
Referenced by LennardJonesSoftcoreTI().
setShift()
void espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::setShift (real _shift) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 216 of file Potential.hpp.
Referenced by LennardJonesSoftcoreTI().
updateAutoShift()
void espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::updateAutoShift () inline inherited
Definition at line 244 of file Potential.hpp.
Member Data Documentation
alpha_sigmaA6_lambdaP
real espressopp::interaction::LennardJonesSoftcoreTI::alpha_sigmaA6_lambdaP private
Definition at line 56 of file LennardJonesSoftcoreTI.hpp.
alpha_sigmaB6_compllambdaP
real espressopp::interaction::LennardJonesSoftcoreTI::alpha_sigmaB6_compllambdaP private
Definition at line 57 of file LennardJonesSoftcoreTI.hpp.
alphaSC
real espressopp::interaction::LennardJonesSoftcoreTI::alphaSC private
Definition at line 47 of file LennardJonesSoftcoreTI.hpp.
Referenced by getAlphaSC().
annihilate
bool espressopp::interaction::LennardJonesSoftcoreTI::annihilate private
Definition at line 43 of file LennardJonesSoftcoreTI.hpp.
autoShift
bool espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::autoShift protected inherited
Definition at line 151 of file Potential.hpp.
Referenced by LennardJonesSoftcoreTI().
colVar
RealND espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::colVar protected inherited
Definition at line 159 of file Potential.hpp.
colVarAngleList
shared_ptr<FixedTripleList> espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::colVarAngleList protected inherited
Definition at line 155 of file Potential.hpp.
colVarBondList
shared_ptr<FixedPairList> espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::colVarBondList protected inherited
Definition at line 153 of file Potential.hpp.
colVarDihedList
shared_ptr<FixedQuadrupleList> espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::colVarDihedList protected inherited
Definition at line 157 of file Potential.hpp.
complLambdaTI
real espressopp::interaction::LennardJonesSoftcoreTI::complLambdaTI private
Definition at line 46 of file LennardJonesSoftcoreTI.hpp.
compllambdaTI_powerSC
real espressopp::interaction::LennardJonesSoftcoreTI::compllambdaTI_powerSC private
Definition at line 54 of file LennardJonesSoftcoreTI.hpp.
Referenced by preset().
compllambdaTI_powerSCm1
real espressopp::interaction::LennardJonesSoftcoreTI::compllambdaTI_powerSCm1 private
Definition at line 55 of file LennardJonesSoftcoreTI.hpp.
cutoff
real espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::cutoff protected inherited
Definition at line 148 of file Potential.hpp.
cutoffSqr
real espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::cutoffSqr protected inherited
Definition at line 149 of file Potential.hpp.
Referenced by _computeEnergy(), _computeEnergyDeriv(), and _computeForce().
epsilonA
real espressopp::interaction::LennardJonesSoftcoreTI::epsilonA private
Definition at line 40 of file LennardJonesSoftcoreTI.hpp.
epsilonB
real espressopp::interaction::LennardJonesSoftcoreTI::epsilonB private
Definition at line 40 of file LennardJonesSoftcoreTI.hpp.
ff1A
real espressopp::interaction::LennardJonesSoftcoreTI::ff1A private
Definition at line 41 of file LennardJonesSoftcoreTI.hpp.
ff1B
real espressopp::interaction::LennardJonesSoftcoreTI::ff1B private
Definition at line 42 of file LennardJonesSoftcoreTI.hpp.
ff2A
real espressopp::interaction::LennardJonesSoftcoreTI::ff2A private
Definition at line 41 of file LennardJonesSoftcoreTI.hpp.
Referenced by _computeEnergyDeriv(), and _computeForce().
ff2B
real espressopp::interaction::LennardJonesSoftcoreTI::ff2B private
Definition at line 42 of file LennardJonesSoftcoreTI.hpp.
Referenced by _computeEnergyDeriv(), and _computeForce().
lambdaTI
real espressopp::interaction::LennardJonesSoftcoreTI::lambdaTI private
Definition at line 45 of file LennardJonesSoftcoreTI.hpp.
Referenced by getLambdaTI(), and preset().
lambdaTI_powerSC
real espressopp::interaction::LennardJonesSoftcoreTI::lambdaTI_powerSC private
Definition at line 52 of file LennardJonesSoftcoreTI.hpp.
Referenced by preset().
lambdaTI_powerSCm1
real espressopp::interaction::LennardJonesSoftcoreTI::lambdaTI_powerSCm1 private
Definition at line 53 of file LennardJonesSoftcoreTI.hpp.
Referenced by _computeEnergyDeriv().
pidsTI
std::set<longint> espressopp::interaction::LennardJonesSoftcoreTI::pidsTI private
Definition at line 44 of file LennardJonesSoftcoreTI.hpp.
powerSC
real espressopp::interaction::LennardJonesSoftcoreTI::powerSC private
Definition at line 49 of file LennardJonesSoftcoreTI.hpp.
Referenced by getPowerSC().
powerSC_alphaSC_inv6
real espressopp::interaction::LennardJonesSoftcoreTI::powerSC_alphaSC_inv6 private
Definition at line 58 of file LennardJonesSoftcoreTI.hpp.
shift
real espressopp::interaction::PotentialTemplate< LennardJonesSoftcoreTI >::shift protected inherited
Definition at line 150 of file Potential.hpp.
sigmaSC_A
real espressopp::interaction::LennardJonesSoftcoreTI::sigmaSC_A private
Definition at line 48 of file LennardJonesSoftcoreTI.hpp.
Referenced by preset().
sigmaSC_A6
real espressopp::interaction::LennardJonesSoftcoreTI::sigmaSC_A6 private
Definition at line 50 of file LennardJonesSoftcoreTI.hpp.
sigmaSC_B
real espressopp::interaction::LennardJonesSoftcoreTI::sigmaSC_B private
Definition at line 48 of file LennardJonesSoftcoreTI.hpp.
Referenced by preset().
sigmaSC_B6
real espressopp::interaction::LennardJonesSoftcoreTI::sigmaSC_B6 private
Definition at line 51 of file LennardJonesSoftcoreTI.hpp.
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/LennardJonesSoftcoreTI.hpp
/home/espressopp/espressopp/src/interaction/LennardJonesSoftcoreTI.cpp