ESPResSo++: /home/espressopp/espressopp/src/main/espressopp_common.cpp File Reference
espressopp_common.cpp File Reference
#include "espressopp_common.hpp"
#include "mpi.hpp"
#include "types.hpp"
Functions
void initMPIEnv (int &argc, char **&argv)
Initialize MPI.
void initMPIEnv ()
void finalizeMPIEnv ()
Variables
static boost::mpi::environment * theEnvironment = 0
the one and only instance of the MPI environment
boost::shared_ptr< boost::mpi::communicator > mpiWorld = boost::make_shared< boost::mpi::communicator >()
Function Documentation
finalizeMPIEnv()
void finalizeMPIEnv ()
Definition at line 51 of file espressopp_common.cpp.
References theEnvironment.
Referenced by finalize().
initMPIEnv() [1/2]
void initMPIEnv (int & argc, char **& argv)
Initialize MPI.
Definition at line 35 of file espressopp_common.cpp.
References theEnvironment.
Referenced by BOOST_PYTHON_MODULE().
initMPIEnv() [2/2]
void initMPIEnv ()
Definition at line 41 of file espressopp_common.cpp.
References theEnvironment.
Variable Documentation
mpiWorld
boost::shared_ptr< boost::mpi::communicator > mpiWorld = boost::make_shared< boost::mpi::communicator >()
Definition at line 32 of file espressopp_common.cpp.
Referenced by espressopp::analysis::MeanSquareDispl::compute(), espressopp::analysis::RadGyrXProfilePI::computeArray(), espressopp::analysis::AdressDensity::computeArray(), espressopp::analysis::XDensity::computeArray(), espressopp::analysis::XPressure::computeArray(), espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VSphereSelfInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::SingleParticleInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeEnergy(), espressopp::analysis::MeanSquareDispl::computeG3(), espressopp::analysis::PressureTensor::computeRaw(), espressopp::analysis::PressureTensorLayer::computeRaw(), espressopp::analysis::PressureTensorMultiLayer::computeRaw(), espressopp::analysis::CenterOfMass::computeVector(), espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListPIadressNoDriftInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirial(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirial(), espressopp::interaction::FixedTripleListPIadressInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListPIadressInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListPIadressInteractionTemplate< _PotentialQM, _PotentialCL >::computeVirial(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::VerletListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialTensor(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleRgListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedLocalTupleComListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialX(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialX(), espressopp::integrator::LBInitPopUniform::createDenVel(), espressopp::integrator::LBInitPopWave::createDenVel(), espressopp::integrator::LatticeBoltzmann::findMyNeighbours(), espressopp::integrator::LangevinBarostat::initialize(), espressopp::esutil::RNG::loadState(), espressopp::integrator::LBInitPeriodicForce::printForce(), espressopp::integrator::LBInitConstForce::printForce(), pyLocateItem(), espressopp::esutil::RNG::saveState(), espressopp::esutil::RNG::seed(), espressopp::integrator::LangevinBarostat::setMassByFrequency(), espressopp::System::System(), espressopp::integrator::OnTheFlyFEC::writeFEC(), and espressopp::analysis::LBOutputVzOfX::writeOutput().
theEnvironment
boost::mpi::environment* theEnvironment = 0 static
the one and only instance of the MPI environment
Definition at line 29 of file espressopp_common.cpp.
Referenced by finalizeMPIEnv(), and initMPIEnv().