ESPResSo++: /home/espressopp/espressopp/src/esutil/GenLogger.cpp File Reference
GenLogger.cpp File Reference
Implementation of a genereric Logging facility.
#include <iostream>
#include <logging.hpp>
#include <cstdlib>
#include <cstdio>
#include "GenLogger.hpp"
Functions
static LOG4ESPP_LOGGER (myLogger,"Logger")
static void setLoggerLevel (string &name, string &value)
static int eval_entry (char *line, int length, char *filename)
static int read_config (char *fname)
Variables
static GenLogger * rootLogger = NULL
Detailed Description
Implementation of a genereric Logging facility.
Definition in file GenLogger.cpp.
Function Documentation
static int eval_entry (char * line, int length, char * filename) static
Definition at line 150 of file GenLogger.cpp.
References log4espp::Logger::name, and setLoggerLevel().
Referenced by read_config().
static LOG4ESPP_LOGGER (myLogger , "Logger") static
static int read_config (char * fname) static
Definition at line 208 of file GenLogger.cpp.
References eval_entry(), and LOG4ESPP_ERROR.
Referenced by log4espp::Logger::configure().
static void setLoggerLevel (string & name, string & value) static
Definition at line 98 of file GenLogger.cpp.
References log4espp::Logger::DEBUG, log4espp::Logger::ERROR, log4espp::Logger::FATAL, log4espp::Logger::getInstance(), log4espp::Logger::getRoot(), log4espp::Logger::INFO, LOG4ESPP_ERROR, LOG4ESPP_INFO, log4espp::Logger::setLevel(), log4espp::Logger::TRACE, and log4espp::Logger::WARN.
Referenced by eval_entry().
Variable Documentation
GenLogger* rootLogger = NULL static
Definition at line 44 of file GenLogger.cpp.
Referenced by log4espp::Logger::getRoot().