ESPResSo++: espressopp::analysis Namespace Reference
espressopp::analysis Namespace Reference
Classes
class AdressDensity
struct sBuf
Class provides pid and position information of all particles on all cpus (used e.g.
class AllParticlePos
class AnalysisBase
All quantities to be measured derive from this abstract base class and the corresponding template.
class AnalysisBaseTemplate
class Autocorrelation
class CenterOfMass
Class to compute the center-of-mass of the system.
class ConfigsParticleDecomp
class Configuration
    Iterator class for configuration to be used in Python
class ConfigurationIterator {
public:
  ConfigurationIterator(std::map<size_t, Real3D>& coordinates);
Get next particle id for which coordinates are available int nextId(); Real3D nextCoordinates(); Real3D nextVelocities(); Real3D nextForces(); Real3D nextRadius(); private: std::map<size_t, Real3D>::iterator it; std::map<size_t, Real3D>::iterator end; };
class ConfigurationExtIterator
Iterator class for configuration to be used in Python.
class ConfigurationExt
Class that stores particle positions for later analysis.
class Configurations
class ConfigurationsExt
class ConfigurationsExtAdress
class IntraChainDistSq
calculate mean squared intra-chain-distances
class LBOutput
Abstract base class for arbitrary output from LB simulations.
class LBOutputScreen
class LBOutputVzInTime
class LBOutputVzOfX
class MaxPID
Class to get the number of particles in the system.
class MeanSquareDispl
class MeanSquareInternalDist
class NeighborFluctuation
Class to get the number of particles in the system.
class NPart
Class to get the number of particles in the system.
class Observable
All quantities to be measured derive from this abstract base class.
class OrderParticleProps
class OrderParameter
compute order parameter.
class ParticleRadiusDistribution
class PotentialEnergy
class Pressure
Class to compute the pressure.
class PressureTensor
Class to compute the pressure tensor.
class PressureTensorLayer
Class to compute the pressure tensor.
class PressureTensorMultiLayer
Class to compute the pressure tensor.
class RadialDistrF
Class to compute the radial distribution function of the system.
class RDFatomistic
Class to compute the radial distribution function of the system.
class StaticStructF
Class to compute the static structure function of the system.
class SystemMonitorOutputCSV
class SystemMonitor
class Temperature
Class to compute the temperature.
class Test
Class to test AnalysisBase.
class TotalVelocity
Class to compute the total velocity of a system.
class Velocities
class VelocityAutocorrelation
class Viscosity
class XDensity
class XPressure
class XTemperature
Typedefs
typedef std::map< size_t, sBuf > ConfMap
typedef vector< ConfigurationPtr > ConfigurationList
Class that stores particle positions for later analysis.
typedef shared_ptr< class
Configuration > ConfigurationPtr
typedef shared_ptr< class
ConfigurationExt > ConfigurationExtPtr
typedef std::vector
< ConfigurationExtPtr > ConfigurationExtList
Class that stores particle positions for later analysis.
typedef std::vector< real > result
Class to compute the particle radius distribution.
Functions
LOG4ESPP_LOGGER (AllParticlePos::logger,"AllParticlePos")
LOG4ESPP_LOGGER (AnalysisBase::logger,"AnalysisBase")
void registerPython ()
object pass_through (object const &o)
LOG4ESPP_LOGGER (Configurations::logger,"Configurations")
LOG4ESPP_LOGGER (ConfigurationsExt::logger,"ConfigurationsExt")
LOG4ESPP_LOGGER (ConfigurationsExtAdress::logger,"ConfigurationsExtAdress")
LOG4ESPP_LOGGER (IntraChainDistSq::logger,"IntraChainDistSq")
LOG4ESPP_LOGGER (Observable::logger,"Observable")
LOG4ESPP_LOGGER (TotalVelocity::logger,"TotalVelocity")
LOG4ESPP_LOGGER (Velocities::logger,"Velocities")
Typedef Documentation
typedef std::vector< ConfigurationExtPtr > espressopp::analysis::ConfigurationExtList
Class that stores particle positions for later analysis.
Class that stores atomistic particle positions for later analysis.
Important: this class can also be used if the number of particles changes between different snapshots.
Definition at line 42 of file ConfigurationsExt.hpp.
typedef shared_ptr<class ConfigurationExt> espressopp::analysis::ConfigurationExtPtr
Definition at line 36 of file ConfigurationExt.hpp.
typedef std::vector< ConfigurationPtr > espressopp::analysis::ConfigurationList
Class that stores particle positions for later analysis.
Important: this class can also be used if the number of particles changes between different snapshots.
Definition at line 59 of file ConfigsParticleDecomp.hpp.
typedef shared_ptr<class Configuration> espressopp::analysis::ConfigurationPtr
Definition at line 34 of file Configuration.hpp.
typedef std::map< size_t, sBuf > espressopp::analysis::ConfMap
Definition at line 46 of file AllParticlePos.hpp.
typedef std::vector< real > espressopp::analysis::result
Class to compute the particle radius distribution.
Definition at line 38 of file ParticleRadiusDistribution.hpp.
Function Documentation
espressopp::analysis::LOG4ESPP_LOGGER (Observable::logger , "Observable")
espressopp::analysis::LOG4ESPP_LOGGER (AnalysisBase::logger , "AnalysisBase")
espressopp::analysis::LOG4ESPP_LOGGER (IntraChainDistSq::logger , "IntraChainDistSq")
espressopp::analysis::LOG4ESPP_LOGGER (AllParticlePos::logger , "AllParticlePos")
espressopp::analysis::LOG4ESPP_LOGGER (Velocities::logger , "Velocities")
espressopp::analysis::LOG4ESPP_LOGGER (TotalVelocity::logger , "TotalVelocity")
espressopp::analysis::LOG4ESPP_LOGGER (Configurations::logger , "Configurations")
espressopp::analysis::LOG4ESPP_LOGGER (ConfigurationsExtAdress::logger , "ConfigurationsExtAdress")
espressopp::analysis::LOG4ESPP_LOGGER (ConfigurationsExt::logger , "ConfigurationsExt")
object espressopp::analysis::pass_through (object const & o) inline
Definition at line 161 of file ConfigurationExt.cpp.
Referenced by espressopp::analysis::ConfigurationExt::registerPython().
void espressopp::analysis::registerPython ()
Definition at line 74 of file bindings.cpp.
References espressopp::analysis::Test::registerPython(), espressopp::analysis::Temperature::registerPython(), espressopp::analysis::Pressure::registerPython(), espressopp::analysis::MaxPID::registerPython(), espressopp::analysis::NPart::registerPython(), espressopp::analysis::LBOutputVzInTime::registerPython(), espressopp::analysis::LBOutputVzOfX::registerPython(), espressopp::analysis::CenterOfMass::registerPython(), espressopp::analysis::ParticleRadiusDistribution::registerPython(), espressopp::analysis::RDFatomistic::registerPython(), espressopp::analysis::XDensity::registerPython(), espressopp::analysis::XTemperature::registerPython(), espressopp::analysis::XPressure::registerPython(), espressopp::analysis::AdressDensity::registerPython(), espressopp::analysis::PressureTensor::registerPython(), espressopp::analysis::IntraChainDistSq::registerPython(), espressopp::analysis::PotentialEnergy::registerPython(), espressopp::analysis::StaticStructF::registerPython(), espressopp::analysis::PressureTensorLayer::registerPython(), espressopp::analysis::RadialDistrF::registerPython(), espressopp::analysis::PressureTensorMultiLayer::registerPython(), espressopp::analysis::VelocityAutocorrelation::registerPython(), espressopp::analysis::SystemMonitorOutputCSV::registerPython(), espressopp::analysis::TotalVelocity::registerPython(), espressopp::analysis::AllParticlePos::registerPython(), espressopp::analysis::LBOutputScreen::registerPython(), espressopp::analysis::AnalysisBase::registerPython(), espressopp::analysis::Viscosity::registerPython(), espressopp::analysis::MeanSquareInternalDist::registerPython(), espressopp::analysis::Observable::registerPython(), espressopp::analysis::NeighborFluctuation::registerPython(), espressopp::analysis::Configuration::registerPython(), espressopp::analysis::MeanSquareDispl::registerPython(), espressopp::analysis::Velocities::registerPython(), espressopp::analysis::LBOutput::registerPython(), espressopp::analysis::Autocorrelation::registerPython(), espressopp::analysis::ConfigurationsExt::registerPython(), espressopp::analysis::Configurations::registerPython(), espressopp::analysis::ConfigurationsExtAdress::registerPython(), espressopp::analysis::ConfigurationExt::registerPython(), espressopp::analysis::SystemMonitor::registerPython(), espressopp::analysis::OrderParameter::registerPython(), and espressopp::analysis::ConfigsParticleDecomp::registerPython().
Referenced by espressopp::registerPython().