ESPResSo++: espressopp::esutil::Collectives Namespace Reference
espressopp::esutil::Collectives Namespace Reference
Classes
class DuplicateError
Error thrown by locateItem if an item in a distributed storage was found on more than one node.
Functions
int locateItem (bool here, int controller, boost::mpi::communicator world=*mpiWorld)
Find the processor providing a certain information.
void registerPython ()
Variables
const int None = -1
Function Documentation
int espressopp::esutil::Collectives::locateItem (bool here, int controller, boost::mpi::communicator world = *mpiWorld)
Find the processor providing a certain information.
This function is SPMD, i.e. needs to be called on all nodes simultaneously.
Parameters
here - should be true iff the item is on the local node
Returns
on the controller the node number or None, if the item does not exist; on the workers: None.
Exceptions
DuplicateError if the particle is found on more than one node.
Referenced by pyLocateItem().
void espressopp::esutil::Collectives::registerPython ()
Definition at line 84 of file Collectives.cpp.
References None, pyLocateItem(), espressopp::analysis::Test::registerPython(), espressopp::interaction::Zero::registerPython(), espressopp::storage::DomainDecompositionNonBlocking::registerPython(), espressopp::analysis::MaxPID::registerPython(), espressopp::interaction::DihedralHarmonicUniqueCos::registerPython(), espressopp::analysis::Pressure::registerPython(), espressopp::analysis::Temperature::registerPython(), espressopp::analysis::NPart::registerPython(), espressopp::interaction::LennardJonesExpand::registerPython(), espressopp::analysis::LBOutputVzInTime::registerPython(), espressopp::integrator::LBInitPopUniform::registerPython(), espressopp::integrator::LBInitPopWave::registerPython(), espressopp::analysis::LBOutputVzOfX::registerPython(), espressopp::interaction::CoulombTruncatedUniqueCharge::registerPython(), espressopp::interaction::FENE::registerPython(), espressopp::analysis::CenterOfMass::registerPython(), espressopp::interaction::HarmonicUnique::registerPython(), espressopp::interaction::AngularUniqueCosineSquared::registerPython(), espressopp::interaction::DihedralHarmonicCos::registerPython(), espressopp::analysis::ParticleRadiusDistribution::registerPython(), espressopp::interaction::CoulombTruncated::registerPython(), espressopp::interaction::GravityTruncated::registerPython(), espressopp::analysis::RDFatomistic::registerPython(), espressopp::interaction::Quartic::registerPython(), espressopp::analysis::XDensity::registerPython(), espressopp::analysis::XTemperature::registerPython(), espressopp::analysis::XPressure::registerPython(), espressopp::interaction::TabulatedDihedral::registerPython(), espressopp::interaction::DihedralRB::registerPython(), espressopp::interaction::Harmonic::registerPython(), espressopp::interaction::TabulatedAngular::registerPython(), espressopp::interaction::AngularHarmonic::registerPython(), espressopp::analysis::AdressDensity::registerPython(), espressopp::interaction::OPLS::registerPython(), espressopp::analysis::PressureTensor::registerPython(), espressopp::interaction::Morse::registerPython(), espressopp::interaction::SoftCosine::registerPython(), espressopp::interaction::AngularCosineSquared::registerPython(), espressopp::interaction::AngularUniqueHarmonic::registerPython(), espressopp::analysis::IntraChainDistSq::registerPython(), espressopp::integrator::LBInitPeriodicForce::registerPython(), espressopp::integrator::ExtAnalyze::registerPython(), espressopp::interaction::Cosine::registerPython(), espressopp::integrator::LBInitConstForce::registerPython(), espressopp::esutil::UniformOnSphere::registerPython(), espressopp::interaction::HarmonicTrap::registerPython(), espressopp::analysis::PotentialEnergy::registerPython(), espressopp::analysis::StaticStructF::registerPython(), espressopp::interaction::LennardJonesGeneric::registerPython(), espressopp::interaction::FENECapped::registerPython(), espressopp::integrator::LBInit::registerPython(), espressopp::interaction::SingleParticlePotential::registerPython(), espressopp::interaction::LennardJones::registerPython(), espressopp::interaction::LennardJonesCapped::registerPython(), espressopp::analysis::PressureTensorLayer::registerPython(), espressopp::interaction::CoulombRSpace::registerPython(), espressopp::interaction::LennardJonesEnergyCapped::registerPython(), espressopp::esutil::GammaVariate::registerPython(), espressopp::esutil::NormalVariate::registerPython(), espressopp::analysis::RadialDistrF::registerPython(), espressopp::analysis::PressureTensorMultiLayer::registerPython(), espressopp::interaction::TersoffPairTerm::registerPython(), espressopp::interaction::StillingerWeberPairTerm::registerPython(), espressopp::interaction::StillingerWeberPairTermCapped::registerPython(), espressopp::integrator::VelocityVerletOnRadius::registerPython(), espressopp::integrator::EmptyExtension::registerPython(), espressopp::interaction::LennardJonesAutoBonds::registerPython(), espressopp::interaction::Tabulated::registerPython(), espressopp::interaction::AngularPotential::registerPython(), espressopp::interaction::DihedralHarmonic::registerPython(), espressopp::interaction::PotentialVSpherePair::registerPython(), espressopp::interaction::PotentialUniqueDist::registerPython(), espressopp::interaction::Potential::registerPython(), espressopp::interaction::LennardJonesGromacs::registerPython(), espressopp::integrator::MinimizeEnergy::registerPython(), espressopp::interaction::VSphereSelf::registerPython(), espressopp::interaction::AngularUniquePotential::registerPython(), espressopp::integrator::Isokinetic::registerPython(), espressopp::interaction::MirrorLennardJones::registerPython(), espressopp::analysis::VelocityAutocorrelation::registerPython(), espressopp::integrator::VelocityVerletOnGroup::registerPython(), espressopp::interaction::StillingerWeberTripleTerm::registerPython(), espressopp::integrator::Settle::registerPython(), registerPython(), espressopp::interaction::LJcos::registerPython(), espressopp::interaction::DihedralPotential::registerPython(), espressopp::interaction::DihedralUniquePotential::registerPython(), espressopp::analysis::SystemMonitorOutputCSV::registerPython(), espressopp::integrator::BerendsenThermostat::registerPython(), espressopp::interaction::VSpherePair::registerPython(), espressopp::analysis::AllParticlePos::registerPython(), espressopp::analysis::LBOutputScreen::registerPython(), espressopp::analysis::TotalVelocity::registerPython(), espressopp::interaction::DihedralHarmonicNCos::registerPython(), espressopp::analysis::AnalysisBase::registerPython(), espressopp::interaction::LennardJones93Wall::registerPython(), espressopp::integrator::BerendsenBarostatAnisotropic::registerPython(), espressopp::integrator::FixPositions::registerPython(), espressopp::interaction::Interaction::registerPython(), espressopp::integrator::LangevinBarostat::registerPython(), espressopp::analysis::Viscosity::registerPython(), espressopp::integrator::BerendsenBarostat::registerPython(), espressopp::integrator::FreeEnergyCompensation::registerPython(), espressopp::integrator::TDforce::registerPython(), espressopp::integrator::ExtForce::registerPython(), espressopp::interaction::TersoffTripleTerm::registerPython(), espressopp::analysis::MeanSquareInternalDist::registerPython(), espressopp::analysis::Observable::registerPython(), espressopp::integrator::Adress::registerPython(), espressopp::analysis::NeighborFluctuation::registerPython(), espressopp::integrator::Extension::registerPython(), espressopp::analysis::Configuration::registerPython(), espressopp::integrator::OnTheFlyFEC::registerPython(), espressopp::interaction::ReactionFieldGeneralized::registerPython(), espressopp::analysis::MeanSquareDispl::registerPython(), espressopp::integrator::CapForce::registerPython(), espressopp::analysis::Velocities::registerPython(), espressopp::analysis::LBOutput::registerPython(), espressopp::interaction::ReactionFieldGeneralizedTI::registerPython(), espressopp::analysis::Autocorrelation::registerPython(), espressopp::esutil::RNG::registerPython(), espressopp::esutil::Grid::registerPython(), espressopp::storage::DomainDecomposition::registerPython(), espressopp::integrator::DPDThermostat::registerPython(), espressopp::integrator::LangevinThermostat1D::registerPython(), espressopp::analysis::ConfigurationsExt::registerPython(), espressopp::integrator::GeneralizedLangevinThermostat::registerPython(), espressopp::storage::DomainDecompositionAdress::registerPython(), espressopp::integrator::LangevinThermostat::registerPython(), espressopp::analysis::Configurations::registerPython(), espressopp::interaction::LennardJonesSoftcoreTI::registerPython(), espressopp::integrator::LangevinThermostatHybrid::registerPython(), espressopp::analysis::ConfigurationsExtAdress::registerPython(), espressopp::analysis::ConfigurationExt::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::analysis::SystemMonitor::registerPython(), espressopp::io::DumpXYZ::registerPython(), espressopp::integrator::VelocityVerlet::registerPython(), espressopp::integrator::AssociationReaction::registerPython(), espressopp::integrator::StochasticVelocityRescaling::registerPython(), espressopp::interaction::CoulombKSpaceEwald::registerPython(), espressopp::bc::OrthorhombicBC::registerPython(), espressopp::bc::SlabBC::registerPython(), espressopp::interaction::CoulombKSpaceP3M::registerPython(), espressopp::io::DumpGROAdress::registerPython(), espressopp::io::DumpGRO::registerPython(), espressopp::integrator::LiquidGasLB::registerPython(), espressopp::bc::BC::registerPython(), espressopp::analysis::OrderParameter::registerPython(), espressopp::integrator::LatticeBoltzmann::registerPython(), espressopp::storage::Storage::registerPython(), and espressopp::analysis::ConfigsParticleDecomp::registerPython().
Referenced by espressopp::registerPython(), and espressopp::esutil::registerPython().
Variable Documentation
const int espressopp::esutil::Collectives::None = -1
Definition at line 32 of file Collectives.hpp.
Referenced by registerPython().