ESPResSo++: espressopp::integrator Namespace Reference
espressopp::integrator Namespace Reference
Classes
class Adress
class AssociationReaction
Reaction scheme for polymer growth and curing/crosslinking.
class BerendsenBarostat
class BerendsenBarostatAnisotropic
class BerendsenThermostat
class CapForce
CapForce.
class DPDThermostat
DPD thermostat.
class EmptyExtension
EmptyExtension.
class ExtAnalyze
ExtAnalyze.
class Extension
struct ExtensionList
class ExtForce
ExtForce.
class FixPositions
Langevin.
class FreeEnergyCompensation
class GammaDistribution
class GammaDistributionBoost
Gamma distribution, from Boost.
class GammaDistributionNR2nd
Gamma distribution, from Numerical Recipes, 2nd edition, pages 292 & 293.
class GammaDistributionNR3rd
Gamma distribution, from Numerical Recipes, 3rd edition, pages 370 & 371.
class GeneralizedLangevinThermostat
Langevin thermostat.
class Isokinetic
Langevin.
class LangevinBarostat
Barostat.
class LangevinThermostat
Langevin thermostat.
class LangevinThermostat1D
Langevin thermostat.
class LangevinThermostatHybrid
For use in AdResS simulations.
class LangevinThermostatOnGroup
Langevin thermostat on ParticleGroup.
class LangevinThermostatOnRadius
Langevin thermostat.
class LatticeBoltzmann
class LatticePar
class LBForce
class LBInit
Abstract base class for arbitrary Init for LB simulations.
class LBInitConstForce
class LBInitPeriodicForce
class LBInitPopUniform
class LBInitPopWave
class LBMom
class LBSite
class MDIntegrator
class MinimizeEnergy
class OnTheFlyFEC
class PIAdressIntegrator
class Rattle
class Settle
class StochasticVelocityRescaling
class TDforce
class VelocityVerlet
Velocity Verlet Integrator.
class VelocityVerletOnGroup
Velocity Verlet Integrator.
class VelocityVerletOnRadius
class VelocityVerletRESPA
Velocity Verlet Integrator.
Functions
LOG4ESPP_LOGGER (AssociationReaction::theLogger, "AssociationReaction")
LOG4ESPP_LOGGER (BerendsenBarostat::theLogger, "BerendsenBarostat")
LOG4ESPP_LOGGER (BerendsenBarostatAnisotropic::theLogger, "BerendsenBarostatAnisotropic")
LOG4ESPP_LOGGER (BerendsenThermostat::theLogger, "BerendsenThermostat")
void registerPython ()
LOG4ESPP_LOGGER (CapForce::theLogger, "CapForce")
LOG4ESPP_LOGGER (EmptyExtension::theLogger, "EmptyExtension")
LOG4ESPP_LOGGER (ExtAnalyze::theLogger, "ExtAnalyze")
LOG4ESPP_LOGGER (Extension::theLogger, "Extension")
LOG4ESPP_LOGGER (ExtForce::theLogger, "ExtForce")
LOG4ESPP_LOGGER (FixPositions::theLogger, "FixPositions")
LOG4ESPP_LOGGER (FreeEnergyCompensation::theLogger, "FreeEnergyCompensation")
LOG4ESPP_LOGGER (Isokinetic::theLogger, "Isokinetic")
LOG4ESPP_LOGGER (LangevinBarostat::theLogger, "LangevinBarostat")
LOG4ESPP_LOGGER (LatticeBoltzmann::theLogger, "LatticeBoltzmann")
LOG4ESPP_LOGGER (MDIntegrator::theLogger, "MDIntegrator")
LOG4ESPP_LOGGER (MinimizeEnergy::theLogger, "MinimizeEnergy")
template<typename T >
int sgn (T val)
LOG4ESPP_LOGGER (OnTheFlyFEC::theLogger, "OnTheFlyFEC")
LOG4ESPP_LOGGER (Rattle::theLogger, "Rattle")
LOG4ESPP_LOGGER (Settle::theLogger, "Settle")
LOG4ESPP_LOGGER (StochasticVelocityRescaling::theLogger, "StochasticVelocityRescaling")
LOG4ESPP_LOGGER (TDforce::theLogger, "TDforce")
LOG4ESPP_LOGGER (VelocityVerlet::theLogger, "VelocityVerlet")
static object wrapGetTimers (class VelocityVerlet *obj)
LOG4ESPP_LOGGER (VelocityVerletOnRadius::theLogger, "VelocityVerletOnRadius")
Variables
const int AR_COMM_TAG = 0xac
Function Documentation
LOG4ESPP_LOGGER() [1/23]
espressopp::integrator::LOG4ESPP_LOGGER (Extension::theLogger , "Extension")
LOG4ESPP_LOGGER() [2/23]
espressopp::integrator::LOG4ESPP_LOGGER (MDIntegrator::theLogger , "MDIntegrator")
LOG4ESPP_LOGGER() [3/23]
espressopp::integrator::LOG4ESPP_LOGGER (MinimizeEnergy::theLogger , "MinimizeEnergy")
LOG4ESPP_LOGGER() [4/23]
espressopp::integrator::LOG4ESPP_LOGGER (ExtAnalyze::theLogger , "ExtAnalyze")
LOG4ESPP_LOGGER() [5/23]
espressopp::integrator::LOG4ESPP_LOGGER (BerendsenBarostat::theLogger , "BerendsenBarostat")
LOG4ESPP_LOGGER() [6/23]
espressopp::integrator::LOG4ESPP_LOGGER (BerendsenBarostatAnisotropic::theLogger , "BerendsenBarostatAnisotropic")
LOG4ESPP_LOGGER() [7/23]
espressopp::integrator::LOG4ESPP_LOGGER (VelocityVerletOnRadius::theLogger , "VelocityVerletOnRadius")
LOG4ESPP_LOGGER() [8/23]
espressopp::integrator::LOG4ESPP_LOGGER (ExtForce::theLogger , "ExtForce")
LOG4ESPP_LOGGER() [9/23]
espressopp::integrator::LOG4ESPP_LOGGER (FixPositions::theLogger , "FixPositions")
LOG4ESPP_LOGGER() [10/23]
espressopp::integrator::LOG4ESPP_LOGGER (CapForce::theLogger , "CapForce")
LOG4ESPP_LOGGER() [11/23]
espressopp::integrator::LOG4ESPP_LOGGER (Isokinetic::theLogger , "Isokinetic")
LOG4ESPP_LOGGER() [12/23]
espressopp::integrator::LOG4ESPP_LOGGER (EmptyExtension::theLogger , "EmptyExtension")
LOG4ESPP_LOGGER() [13/23]
espressopp::integrator::LOG4ESPP_LOGGER (BerendsenThermostat::theLogger , "BerendsenThermostat")
LOG4ESPP_LOGGER() [14/23]
espressopp::integrator::LOG4ESPP_LOGGER (Settle::theLogger , "Settle")
LOG4ESPP_LOGGER() [15/23]
espressopp::integrator::LOG4ESPP_LOGGER (OnTheFlyFEC::theLogger , "OnTheFlyFEC")
LOG4ESPP_LOGGER() [16/23]
espressopp::integrator::LOG4ESPP_LOGGER (FreeEnergyCompensation::theLogger , "FreeEnergyCompensation")
LOG4ESPP_LOGGER() [17/23]
espressopp::integrator::LOG4ESPP_LOGGER (Rattle::theLogger , "Rattle")
LOG4ESPP_LOGGER() [18/23]
espressopp::integrator::LOG4ESPP_LOGGER (StochasticVelocityRescaling::theLogger , "StochasticVelocityRescaling")
LOG4ESPP_LOGGER() [19/23]
espressopp::integrator::LOG4ESPP_LOGGER (TDforce::theLogger , "TDforce")
LOG4ESPP_LOGGER() [20/23]
espressopp::integrator::LOG4ESPP_LOGGER (AssociationReaction::theLogger , "AssociationReaction")
LOG4ESPP_LOGGER() [21/23]
espressopp::integrator::LOG4ESPP_LOGGER (LatticeBoltzmann::theLogger , "LatticeBoltzmann")
LOG4ESPP_LOGGER() [22/23]
espressopp::integrator::LOG4ESPP_LOGGER (LangevinBarostat::theLogger , "LangevinBarostat")
LOG4ESPP_LOGGER() [23/23]
espressopp::integrator::LOG4ESPP_LOGGER (VelocityVerlet::theLogger , "VelocityVerlet")
registerPython()
void espressopp::integrator::registerPython ()
Definition at line 69 of file bindings.cpp.
References espressopp::integrator::LBInitPopUniform::registerPython(), espressopp::integrator::LBInitPopWave::registerPython(), espressopp::integrator::LBInitPeriodicForce::registerPython(), espressopp::integrator::ExtAnalyze::registerPython(), espressopp::integrator::Rattle::registerPython(), espressopp::integrator::LBInitConstForce::registerPython(), espressopp::integrator::LBInit::registerPython(), espressopp::integrator::VelocityVerletOnRadius::registerPython(), espressopp::integrator::EmptyExtension::registerPython(), espressopp::integrator::Isokinetic::registerPython(), espressopp::integrator::MinimizeEnergy::registerPython(), espressopp::integrator::VelocityVerletOnGroup::registerPython(), espressopp::integrator::VelocityVerletRESPA::registerPython(), espressopp::integrator::VelocityVerlet::registerPython(), espressopp::integrator::Settle::registerPython(), espressopp::integrator::BerendsenThermostat::registerPython(), espressopp::integrator::BerendsenBarostatAnisotropic::registerPython(), espressopp::integrator::LangevinBarostat::registerPython(), espressopp::integrator::FixPositions::registerPython(), espressopp::integrator::BerendsenBarostat::registerPython(), espressopp::integrator::ExtForce::registerPython(), espressopp::integrator::FreeEnergyCompensation::registerPython(), espressopp::integrator::Extension::registerPython(), espressopp::integrator::Adress::registerPython(), espressopp::integrator::TDforce::registerPython(), espressopp::integrator::OnTheFlyFEC::registerPython(), espressopp::integrator::LangevinThermostatOnGroup::registerPython(), espressopp::integrator::CapForce::registerPython(), espressopp::integrator::LangevinThermostatOnRadius::registerPython(), espressopp::integrator::DPDThermostat::registerPython(), espressopp::integrator::LangevinThermostat1D::registerPython(), espressopp::integrator::GeneralizedLangevinThermostat::registerPython(), espressopp::integrator::LangevinThermostat::registerPython(), espressopp::integrator::LangevinThermostatHybrid::registerPython(), espressopp::integrator::MDIntegrator::registerPython(), espressopp::integrator::AssociationReaction::registerPython(), espressopp::integrator::PIAdressIntegrator::registerPython(), espressopp::integrator::StochasticVelocityRescaling::registerPython(), and espressopp::integrator::LatticeBoltzmann::registerPython().
Referenced by espressopp::registerPython().
sgn()
template<typename T > int espressopp::integrator::sgn (T val)
Definition at line 157 of file MinimizeEnergy.cpp.
wrapGetTimers()
static object espressopp::integrator::wrapGetTimers (class VelocityVerlet * obj) static
Definition at line 179 of file VelocityVerlet.cpp.
References espressopp::integrator::VelocityVerlet::loadTimers().
Referenced by espressopp::integrator::VelocityVerlet::registerPython().
Variable Documentation
AR_COMM_TAG
const int espressopp::integrator::AR_COMM_TAG = 0xac
Definition at line 46 of file AssociationReaction.hpp.
Referenced by espressopp::integrator::AssociationReaction::sendMultiMap().