ESPResSo++: espressopp::storage Namespace Reference
espressopp::storage Namespace Reference
Classes
class NodeGridMismatch
class DomainDecomposition
class PyDomainDecompositionAdress
class NodeGridMismatch2
class DomainDecompositionAdress
class DomainDecompositionNonBlocking
class NodeGridIllegal
class NodeGrid
Node grid point.
class Storage
represents the particle storage of one system.
Functions
void registerPython ()
LOG4ESPP_LOGGER (DomainDecomposition::logger,"DomainDecomposition")
std::string formatMismatchMessage (const Int3D &gridRequested, int nodesAvailable)
LOG4ESPP_LOGGER (DomainDecompositionAdress::logger,"DomainDecompositionAdress")
std::string formatMismatchMessage2 (const Int3D &gridRequested, int nodesAvailable)
LOG4ESPP_LOGGER (NodeGrid::logger,"DomainDecomposition.NodeGrid")
LOG4ESPP_LOGGER (Storage::logger,"Storage")
Variables
const int DD_COMM_TAG = 0xab
const int STORAGE_COMM_TAG = 0xaa
Function Documentation
std::string espressopp::storage::formatMismatchMessage (const Int3D & gridRequested, int nodesAvailable)
Definition at line 54 of file DomainDecomposition.cpp.
std::string espressopp::storage::formatMismatchMessage2 (const Int3D & gridRequested, int nodesAvailable)
Definition at line 49 of file DomainDecompositionAdress.cpp.
espressopp::storage::LOG4ESPP_LOGGER (NodeGrid::logger , "DomainDecomposition.NodeGrid")
espressopp::storage::LOG4ESPP_LOGGER (DomainDecompositionAdress::logger , "DomainDecompositionAdress")
espressopp::storage::LOG4ESPP_LOGGER (Storage::logger , "Storage")
espressopp::storage::LOG4ESPP_LOGGER (DomainDecomposition::logger , "DomainDecomposition")
void espressopp::storage::registerPython ()
Definition at line 31 of file bindings.cpp.
References espressopp::esutil::Collectives::None, pyLocateItem(), espressopp::bc::registerPython(), espressopp::io::registerPython(), registerPython(), espressopp::esutil::registerPython(), espressopp::ParticleAccess::registerPython(), espressopp::storage::DomainDecompositionNonBlocking::registerPython(), espressopp::Version::registerPython(), espressopp::FixedQuadrupleListAdress::registerPython(), espressopp::FixedTupleList::registerPython(), espressopp::FixedPairListAdress::registerPython(), espressopp::FixedTripleListAdress::registerPython(), espressopp::FixedTupleListAdress::registerPython(), espressopp::integrator::registerPython(), espressopp::ParticleGroup::registerPython(), espressopp::FixedTripleList::registerPython(), espressopp::FixedPairDistList::registerPython(), espressopp::FixedSingleList::registerPython(), espressopp::FixedQuadrupleList::registerPython(), espressopp::Int3D::registerPython(), espressopp::analysis::registerPython(), espressopp::FixedPairList::registerPython(), espressopp::System::registerPython(), espressopp::FixedQuadrupleAngleList::registerPython(), espressopp::storage::DomainDecomposition::registerPython(), espressopp::FixedTripleAngleList::registerPython(), espressopp::storage::DomainDecompositionAdress::registerPython(), log4espp::PyLogger::registerPython(), espressopp::VerletListTriple::registerPython(), espressopp::interaction::registerPython(), espressopp::VerletList::registerPython(), espressopp::Tensor::registerPython(), espressopp::Real3D::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::RealND::registerPython(), espressopp::Quaternion::registerPython(), espressopp::storage::Storage::registerPython(), and espressopp::Particle::registerPython().
Referenced by BOOST_PYTHON_MODULE(), espressopp::registerPython(), and espressopp::esutil::registerPython().
Variable Documentation
const int espressopp::storage::DD_COMM_TAG = 0xab
Definition at line 50 of file DomainDecomposition.cpp.
Referenced by espressopp::storage::DomainDecompositionNonBlocking::doGhostCommunication(), espressopp::storage::DomainDecomposition::doGhostCommunication(), espressopp::storage::DomainDecompositionAdress::doGhostCommunication(), espressopp::storage::DomainDecompositionNonBlocking::irecvParticles_initiate(), and espressopp::storage::DomainDecompositionNonBlocking::isendParticles().
const int espressopp::storage::STORAGE_COMM_TAG = 0xaa
Definition at line 51 of file Storage.cpp.
Referenced by espressopp::storage::Storage::recvParticles(), and espressopp::storage::Storage::sendParticles().