ESPResSo++: espressopp::vectorization Namespace Reference
espressopp::vectorization Namespace Reference
Namespaces
interaction
Classes
class CellNeighborList
stores neighbor cells used for all-pair loops (following Newton's 3rd law) as 2d array second index corresponds to one cell in particleArray first index corresponds to neighbor cells zeroth column contains the index in localcells first column (first index) contains size N, so columns [1,N+1) represent the neighbors
class ParticleArray
struct Real3DInt
struct Real4D
class Vectorization
facilitates offloading of particle data to vectorization-friendly form
class VerletList
Class that builds and stores verlet lists.
Typedefs
typedef std::uint64_t ulongint
template<typename T , std::size_t Alignment = ESPP_VECTOR_ALIGNMENT>
using AlignedVector = std::vector< T, boost::alignment::aligned_allocator< T, Alignment > >
Enumerations
enum ParticleElements {
PARTICLE_PROPERTIES =1, PARTICLE_POSITION =2, PARTICLE_MOMENTUM =4, PARTICLE_LOCAL =8,
PARTICLE_FORCE =16, PARTICLE_ALL =31, PARTICLE_POSITION_ONLY =32, PARTICLE_VELOCITY_ONLY =64,
PARTICLE_FORCE_ONLY =128
}
enum Mode { ESPP_VEC_SOA =0, ESPP_VEC_AOS =1 }
Functions
void registerPython ()
LOG4ESPP_LOGGER (Vectorization::logger, "Vectorization")
LOG4ESPP_LOGGER (VerletList::theLogger, "VerletList")
static boost::python::object wrapGetTimers (class VerletList *obj)
Variables
static const real large_pos = 7.74099e150
Typedef Documentation
AlignedVector
template<typename T , std::size_t Alignment = ESPP_VECTOR_ALIGNMENT> using espressopp::vectorization::AlignedVector = typedef std::vector<T, boost::alignment::aligned_allocator<T,Alignment> >
Definition at line 51 of file simdconfig.hpp.
ulongint
typedef std::uint64_t espressopp::vectorization::ulongint
Definition at line 42 of file ParticleArray.hpp.
Enumeration Type Documentation
Mode
enum espressopp::vectorization::Mode
Enumerator
ESPP_VEC_SOA
ESPP_VEC_AOS
Definition at line 56 of file ParticleArray.hpp.
ParticleElements
enum espressopp::vectorization::ParticleElements
Enumerator
PARTICLE_PROPERTIES
PARTICLE_POSITION
PARTICLE_MOMENTUM
PARTICLE_LOCAL
PARTICLE_FORCE
PARTICLE_ALL
PARTICLE_POSITION_ONLY
PARTICLE_VELOCITY_ONLY
PARTICLE_FORCE_ONLY
Definition at line 44 of file ParticleArray.hpp.
Function Documentation
LOG4ESPP_LOGGER() [1/2]
espressopp::vectorization::LOG4ESPP_LOGGER (Vectorization::logger , "Vectorization")
LOG4ESPP_LOGGER() [2/2]
espressopp::vectorization::LOG4ESPP_LOGGER (VerletList::theLogger , "VerletList")
registerPython()
void espressopp::vectorization::registerPython ()
Definition at line 30 of file bindings.cpp.
References espressopp::vectorization::interaction::registerPython(), espressopp::vectorization::Vectorization::registerPython(), and espressopp::vectorization::VerletList::registerPython().
Referenced by espressopp::registerPython().
wrapGetTimers()
static boost::python::object espressopp::vectorization::wrapGetTimers (class VerletList * obj) static
Definition at line 570 of file VerletList.cpp.
References espressopp::vectorization::VerletList::loadTimers().
Referenced by espressopp::vectorization::VerletList::registerPython().
Variable Documentation
large_pos
const real espressopp::vectorization::large_pos = 7.74099e150 static
Definition at line 55 of file simdconfig.hpp.
Referenced by espressopp::vectorization::ParticleArray::copyFrom().