ESPResSo++: espressopp Namespace Reference
espressopp Namespace Reference
Namespaces
analysis
bc
esutil
integrator
interaction
io
iterator
mpi
python
storage
Classes
class Buffer
Communication buffer.
struct Cell
class CellGrid
Grid with a ghost frame.
class CellGridIllegal
struct CellList
class FixedListComm
class FixedLocalTupleList
class FixedPairDistList
class FixedPairList
class FixedPairListAdress
This is a subclass of FixedPairList.
class FixedQuadrupleAngleList
class FixedQuadrupleList
class FixedQuadrupleListAdress
class FixedSingleList
class FixedTripleAngleList
class FixedTripleList
class FixedTripleListAdress
This is a subclass of FixedTripleList.
class FixedTupleList
class FixedTupleListAdress
class InBuffer
class Int3D
struct int3D_pickle_suite
struct LocalCellList
class MultiSystemAccess
Common base class for all classes that need access to multiple systems.
struct NeighborCellInfo
A NeighborCellInfo manages the information about a cell in a neighborhood cell list.
struct NeighborCellList
class NoDefault
class OutBuffer
struct PairList
struct Particle
class ParticleAccess
struct ParticleForce
force-like properties
class ParticleGroup
group of particles
struct ParticleList
struct ParticleLocal
struct ParticleMomentum
momentum-like properties
class ParticlePair
struct ParticlePosition
position-like properties
struct ParticleProperties
class ParticleQuadruple
class ParticleSingle
class ParticleTriple
struct Quadruple
struct QuadrupleList
class Quaternion
struct quaternion_pickle_suite
class Real3D
struct real3D_pickle_suite
class RealND
struct Single
struct SingleList
class System
class SystemAccess
Common base class for all classes that need access to the system.
class Tensor
The class Tensor stands for a symmetric 3x3 matrix.
struct tensor_pickle_suite
struct Triple
struct TripleList
struct TupleList
class VerletList
Class that builds and stores verlet lists.
class VerletListAdress
Class that builds and stores verlet lists.
class VerletListTriple
Class that builds and stores verlet lists for 3-body interactions.
class Version
Typedefs
typedef double real
typedef int longint
typedef boost::lagged_fibonacci607 RNGType
Functions
void registerPython ()
LOG4ESPP_LOGGER (FixedListComm::theLogger, "FixedListComm")
LOG4ESPP_LOGGER (FixedLocalTupleList::theLogger, "FixedLocalTupleList")
LOG4ESPP_LOGGER (FixedPairDistList::theLogger, "FixedPairDistList")
LOG4ESPP_LOGGER (FixedPairList::theLogger, "FixedPairList")
LOG4ESPP_LOGGER (FixedPairListAdress::theLogger, "FixedPairListAdress")
LOG4ESPP_LOGGER (FixedQuadrupleAngleList::theLogger, "FixedQuadrupleAngleList")
LOG4ESPP_LOGGER (FixedQuadrupleList::theLogger, "FixedQuadrupleList")
LOG4ESPP_LOGGER (FixedQuadrupleListAdress::theLogger, "FixedQuadrupleListAdress")
LOG4ESPP_LOGGER (FixedSingleList::theLogger, "FixedSingleList")
LOG4ESPP_LOGGER (FixedTripleAngleList::theLogger, "FixedTripleAngleList")
LOG4ESPP_LOGGER (FixedTripleList::theLogger, "FixedTripleList")
LOG4ESPP_LOGGER (FixedTripleListAdress::theLogger, "FixedTripleListAdress")
LOG4ESPP_LOGGER (FixedTupleList::theLogger, "FixedTupleList")
LOG4ESPP_LOGGER (FixedTupleListAdress::theLogger, "FixedTupleListAdress")
std::ostream & operator<< (std::ostream &out, const Int3D &v)
Quaternion operator* (real s, const Quaternion &v)
std::ostream & operator<< (std::ostream &out, const Quaternion &v)
Quaternion transpose (const Quaternion &v)
Real3D operator* (real s, const Real3D &v)
std::ostream & operator<< (std::ostream &out, const Real3D &v)
RealND operator* (real s, const RealND &v)
std::ostream & operator<< (std::ostream &out, const RealND &v)
Tensor operator* (real s, const Tensor &v)
std::ostream & operator<< (std::ostream &out, const Tensor &v)
LOG4ESPP_LOGGER (VerletList::theLogger, "VerletList")
LOG4ESPP_LOGGER (VerletListAdress::theLogger, "VerletList")
LOG4ESPP_LOGGER (VerletListTriple::theLogger, "VerletListTriple")
Variables
static const real infinity = std::numeric_limits< real >::infinity()
static const real ROUND_ERROR_PREC = std::numeric_limits< real >::epsilon()
Typedef Documentation
longint
typedef int espressopp::longint
Definition at line 43 of file esconfig.hpp.
real
typedef double espressopp::real
Definition at line 37 of file esconfig.hpp.
RNGType
typedef boost::lagged_fibonacci607 espressopp::RNGType
Definition at line 46 of file esconfig.hpp.
Function Documentation
LOG4ESPP_LOGGER() [1/17]
espressopp::LOG4ESPP_LOGGER (FixedListComm::theLogger , "FixedListComm")
LOG4ESPP_LOGGER() [2/17]
espressopp::LOG4ESPP_LOGGER (FixedPairDistList::theLogger , "FixedPairDistList")
LOG4ESPP_LOGGER() [3/17]
espressopp::LOG4ESPP_LOGGER (FixedPairListAdress::theLogger , "FixedPairListAdress")
LOG4ESPP_LOGGER() [4/17]
espressopp::LOG4ESPP_LOGGER (FixedLocalTupleList::theLogger , "FixedLocalTupleList")
LOG4ESPP_LOGGER() [5/17]
espressopp::LOG4ESPP_LOGGER (VerletListTriple::theLogger , "VerletListTriple")
LOG4ESPP_LOGGER() [6/17]
espressopp::LOG4ESPP_LOGGER (FixedSingleList::theLogger , "FixedSingleList")
LOG4ESPP_LOGGER() [7/17]
espressopp::LOG4ESPP_LOGGER (FixedTripleAngleList::theLogger , "FixedTripleAngleList")
LOG4ESPP_LOGGER() [8/17]
espressopp::LOG4ESPP_LOGGER (FixedQuadrupleListAdress::theLogger , "FixedQuadrupleListAdress")
LOG4ESPP_LOGGER() [9/17]
espressopp::LOG4ESPP_LOGGER (VerletList::theLogger , "VerletList")
LOG4ESPP_LOGGER() [10/17]
espressopp::LOG4ESPP_LOGGER (VerletListAdress::theLogger , "VerletList")
LOG4ESPP_LOGGER() [11/17]
espressopp::LOG4ESPP_LOGGER (FixedTupleList::theLogger , "FixedTupleList")
LOG4ESPP_LOGGER() [12/17]
espressopp::LOG4ESPP_LOGGER (FixedTripleListAdress::theLogger , "FixedTripleListAdress")
LOG4ESPP_LOGGER() [13/17]
espressopp::LOG4ESPP_LOGGER (FixedTupleListAdress::theLogger , "FixedTupleListAdress")
LOG4ESPP_LOGGER() [14/17]
espressopp::LOG4ESPP_LOGGER (FixedQuadrupleAngleList::theLogger , "FixedQuadrupleAngleList")
LOG4ESPP_LOGGER() [15/17]
espressopp::LOG4ESPP_LOGGER (FixedTripleList::theLogger , "FixedTripleList")
LOG4ESPP_LOGGER() [16/17]
espressopp::LOG4ESPP_LOGGER (FixedQuadrupleList::theLogger , "FixedQuadrupleList")
LOG4ESPP_LOGGER() [17/17]
espressopp::LOG4ESPP_LOGGER (FixedPairList::theLogger , "FixedPairList")
operator*() [1/4]
Tensor espressopp::operator* (real s, const Tensor & v) inline
Definition at line 208 of file Tensor.hpp.
References espressopp::Tensor::Tensor().
operator*() [2/4]
Real3D espressopp::operator* (real s, const Real3D & v) inline
Definition at line 225 of file Real3D.hpp.
References espressopp::Real3D::Real3D().
operator*() [3/4]
RealND espressopp::operator* (real s, const RealND & v) inline
Definition at line 291 of file RealND.hpp.
References espressopp::RealND::RealND().
operator*() [4/4]
Quaternion espressopp::operator* (real s, const Quaternion & v) inline
Definition at line 280 of file Quaternion.hpp.
References espressopp::Quaternion::Quaternion().
Referenced by espressopp::iterator::CellListAllTriplesIterator::isDone().
operator<<() [1/5]
std::ostream & espressopp::operator<< (std::ostream & out, const Int3D & v) inline
Definition at line 171 of file Int3D.hpp.
Referenced by espressopp::Tensor::get(), espressopp::Real3D::get(), espressopp::RealND::get(), and espressopp::Quaternion::setImagItem().
operator<<() [2/5]
std::ostream & espressopp::operator<< (std::ostream & out, const Tensor & v) inline
Definition at line 211 of file Tensor.hpp.
operator<<() [3/5]
std::ostream & espressopp::operator<< (std::ostream & out, const Real3D & v) inline
Definition at line 228 of file Real3D.hpp.
operator<<() [4/5]
std::ostream & espressopp::operator<< (std::ostream & out, const RealND & v) inline
Definition at line 294 of file RealND.hpp.
References espressopp::RealND::getDimension().
operator<<() [5/5]
std::ostream & espressopp::operator<< (std::ostream & out, const Quaternion & v) inline
Definition at line 286 of file Quaternion.hpp.
References espressopp::Quaternion::getImagItem(), and espressopp::Quaternion::getReal().
registerPython()
void espressopp::registerPython ()
Definition at line 64 of file bindings.cpp.
References espressopp::bc::registerPython(), espressopp::storage::registerPython(), espressopp::esutil::registerPython(), espressopp::ParticleAccess::registerPython(), espressopp::io::registerPython(), espressopp::Version::registerPython(), espressopp::FixedLocalTupleList::registerPython(), espressopp::FixedQuadrupleListAdress::registerPython(), espressopp::FixedTupleList::registerPython(), espressopp::FixedPairListAdress::registerPython(), espressopp::FixedTripleListAdress::registerPython(), espressopp::ParticleGroup::registerPython(), espressopp::FixedTupleListAdress::registerPython(), espressopp::integrator::registerPython(), espressopp::FixedPairDistList::registerPython(), espressopp::FixedTripleList::registerPython(), espressopp::FixedSingleList::registerPython(), espressopp::FixedQuadrupleList::registerPython(), espressopp::Int3D::registerPython(), espressopp::System::registerPython(), espressopp::FixedPairList::registerPython(), espressopp::FixedQuadrupleAngleList::registerPython(), espressopp::analysis::registerPython(), espressopp::FixedTripleAngleList::registerPython(), espressopp::VerletListTriple::registerPython(), log4espp::PyLogger::registerPython(), espressopp::VerletList::registerPython(), espressopp::Tensor::registerPython(), espressopp::interaction::registerPython(), espressopp::VerletListAdress::registerPython(), espressopp::Real3D::registerPython(), espressopp::RealND::registerPython(), espressopp::Quaternion::registerPython(), and espressopp::Particle::registerPython().
Referenced by BOOST_PYTHON_MODULE(), and espressopp::Particle::setState().
transpose()
Quaternion espressopp::transpose (const Quaternion & v) inline
Definition at line 283 of file Quaternion.hpp.
References espressopp::Quaternion::getImag(), espressopp::Quaternion::getReal(), and espressopp::Quaternion::Quaternion().
Variable Documentation
infinity
const real espressopp::infinity = std::numeric_limits< real >::infinity() static
Definition at line 39 of file esconfig.hpp.
Referenced by espressopp::System::addInteraction(), espressopp::interaction::CoulombRSpace::CoulombRSpace(), espressopp::interaction::CoulombTruncated::CoulombTruncated(), espressopp::interaction::CoulombTruncatedUniqueCharge::CoulombTruncatedUniqueCharge(), espressopp::interaction::FENE::FENE(), espressopp::interaction::FENECapped::FENECapped(), espressopp::interaction::GravityTruncated::GravityTruncated(), espressopp::interaction::Harmonic::Harmonic(), espressopp::interaction::LennardJones::LennardJones(), espressopp::interaction::LennardJonesCapped::LennardJonesCapped(), espressopp::interaction::LennardJonesEnergyCapped::LennardJonesEnergyCapped(), espressopp::interaction::LennardJonesExpand::LennardJonesExpand(), espressopp::interaction::LennardJonesGeneric::LennardJonesGeneric(), espressopp::interaction::LennardJonesGromacs::LennardJonesGromacs(), espressopp::interaction::LennardJonesSoftcoreTI::LennardJonesSoftcoreTI(), espressopp::interaction::MirrorLennardJones::MirrorLennardJones(), espressopp::interaction::Morse::Morse(), espressopp::interaction::Quartic::Quartic(), espressopp::interaction::ReactionFieldGeneralized::ReactionFieldGeneralized(), espressopp::interaction::ReactionFieldGeneralizedTI::ReactionFieldGeneralizedTI(), espressopp::interaction::PotentialTemplate< StillingerWeberPairTerm >::setAutoShift(), espressopp::interaction::PotentialVSpherePairTemplate< VSpherePair >::setAutoShift(), espressopp::interaction::LennardJonesAutoBonds::setAutoShift(), espressopp::interaction::SoftCosine::SoftCosine(), espressopp::interaction::StillingerWeberPairTerm::StillingerWeberPairTerm(), espressopp::interaction::StillingerWeberPairTermCapped::StillingerWeberPairTermCapped(), espressopp::interaction::Tabulated::Tabulated(), espressopp::interaction::TersoffPairTerm::TersoffPairTerm(), espressopp::interaction::VSpherePair::VSpherePair(), and espressopp::interaction::VSphereSelf::VSphereSelf().
ROUND_ERROR_PREC
const real espressopp::ROUND_ERROR_PREC = std::numeric_limits< real >::epsilon() static
Definition at line 40 of file esconfig.hpp.
Referenced by espressopp::interaction::FENE::_computeForceRaw(), espressopp::integrator::LBInitPeriodicForce::addForce(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::integrator::LatticeBoltzmann::initFluctuations(), espressopp::CellGrid::mapPositionToCellChecked(), espressopp::CellGrid::mapPositionToCellCheckedAndClipped(), espressopp::integrator::LatticeBoltzmann::saveLBConf(), and espressopp::integrator::LBInitPeriodicForce::setForce().