ESPResSo++: espressopp::io Namespace Reference
espressopp::io Namespace Reference
Classes
class DumpGRO
class DumpGROAdress
class DumpH5MD
Store particle data in Python buffers.
class DumpTopology
class DumpXTC
class DumpXTCAdress
class DumpXYZ
Functions
void registerPython ()
template<class T >
void init_pb (Py_buffer *pb, int ndim, int *shape)
Initialize a Py_buffer object.
void free_pb (Py_buffer *pb)
Function Documentation
free_pb()
void espressopp::io::free_pb (Py_buffer * pb)
Definition at line 65 of file DumpH5MD.cpp.
Referenced by espressopp::io::DumpH5MD::clear_buffers().
init_pb()
template<class T > void espressopp::io::init_pb (Py_buffer * pb, int ndim, int * shape)
Initialize a Py_buffer object.
Definition at line 40 of file DumpH5MD.cpp.
References get_format().
registerPython()
void espressopp::io::registerPython ()
Definition at line 42 of file bindings.cpp.
References espressopp::io::DumpTopology::registerPython(), espressopp::io::DumpH5MD::registerPython(), espressopp::io::DumpXTCAdress::registerPython(), espressopp::io::DumpXTC::registerPython(), espressopp::io::DumpGROAdress::registerPython(), espressopp::io::DumpXYZ::registerPython(), and espressopp::io::DumpGRO::registerPython().
Referenced by espressopp::registerPython().