ESPResSo++: espressopp::interaction Namespace Reference
espressopp::interaction Namespace Reference
Classes
class AngularCosineSquared
This class provides methods to compute forces and energies of the AngularCosineSquared angular potential.
class AngularHarmonic
This class provides methods to compute forces and energies of the AngularHarmonic angular potential.
class AngularPotential
class AngularPotentialTemplate
Provides a template for the simple implementation of a shifted, absolute distance dependent potential with cutoff.
class CellListAllPairsInteractionTemplate
class CellListAllParticlesInteractionTemplate
class ConstrainCOM
This class provides methods to compute forces and energies of the ConstrainCOM part.
class ConstrainRG
This class provides methods to compute forces and energies of the ConstrainRG part.
class Cosine
This class provides methods to compute forces and energies of the Cosine angular potential.
class CoulombKSpaceEwald
This class provides methods to compute forces and energies of the CoulombKSpaceEwald part.
class CoulombKSpaceP3M
This class provides methods to compute forces and energies of the CoulombKSpaceP3M part.
class CoulombRSpace
class CoulombTruncated
class CoulombTruncatedUniqueCharge
struct CoulombTruncatedUniqueCharge_pickle
class DihedralHarmonic
This class provides methods to compute forces and energies of the DihedralHarmonic dihedral potential.
class DihedralHarmonicCos
This class provides methods to compute forces and energies of the DihedralHarmonicCos dihedral potential.
class DihedralHarmonicNCos
This class provides methods to compute forces and energies of the DihedralHarmonicNCos dihedral potential.
class DihedralPotential
class DihedralPotentialTemplate
class DihedralRB
This class provides methods to compute forces and energies of the Ryckaert-Bellemans dihedral potential.
class FENE
class FENECapped
This class provides methods to compute forces and energies of the FENECapped potential.
class FixedLocalTupleComListInteractionTemplate
class FixedLocalTupleRgListInteractionTemplate
class FixedPairDistListInteractionTemplate
class FixedPairListInteractionTemplate
class FixedPairListPIadressInteractionTemplate
class FixedPairListTypesInteractionTemplate
class FixedQuadrupleAngleListInteractionTemplate
class FixedQuadrupleListInteractionTemplate
class FixedQuadrupleListTypesInteractionTemplate
class FixedTripleAngleListInteractionTemplate
class FixedTripleListInteractionTemplate
class FixedTripleListPIadressInteractionTemplate
class FixedTripleListTypesInteractionTemplate
class GravityTruncated
class Harmonic
class HarmonicTrap
This class provides methods to compute forces and energies for an harmonic well potential.
class Interaction
Interaction base class.
struct InteractionList
class Interpolation
class InterpolationAkima
class InterpolationCubic
class InterpolationLinear
class InterpolationTable
This class defines an interpolation table that can be used for tabbed potentials (pair, bond, angle).
class InterpolationTemplate
class LennardJones
This class provides methods to compute forces and energies of the Lennard Jones potential.
class LennardJones93Wall
This class provides methods to compute forces and energies for an Lennard-Jones 9-3 wall, in the direction dir.
struct LennardJones_pickle
class LennardJonesAutoBonds
This class provides methods to compute forces and energies of the Lennard Jones potential.
class LennardJonesCapped
This class provides methods to compute forces and energies of the Lennard Jones potential with capped forces.
struct LennardJonesCapped_pickle
class LennardJonesEnergyCapped
This class provides methods to compute forces and energies of the Lennard Jones potential with capped energy.
struct LennardJonesEnergyCapped_pickle
class LennardJonesExpand
struct LennardJonesExpand_pickle
class LennardJonesGeneric
This class provides methods to compute forces and energies of the a generic Lennard Jones potential with arbitrary integers a and b.
struct LennardJonesGeneric_pickle
class LennardJonesGromacs
struct LennardJonesGromacs_pickle
class LennardJonesSoftcoreTI
This class provides methods to compute forces and energies of the softcore Lennard Jones potential in a Thermodynamic Integration simulation.
struct LJ93WParams
class LJcos
This class provides methods to compute forces and energies of the modified Lennard Jones potential (WCA) combined with the cos-contribution that smoothly reaches zero.
struct LJcos_pickle
class MirrorLennardJones
This class provides methods to compute forces and energies of the Mirror Lennard-Jones potential.
class Morse
This class provides methods to compute forces and energies of the Morse potential.
struct Morse_pickle
class OPLS
This class provides methods to compute forces and energies of the OPLS dihedral potential.
class Potential
class PotentialTemplate
Provides a template for the simple implementation of a shifted, absolute distance dependent potential with cutoff.
class PotentialVSpherePair
class PotentialVSpherePairTemplate
Provides a template for the simple implementation of a shifted, absolute distance dependent potential with cutoff.
class Quartic
class ReactionFieldGeneralized
struct ReactionFieldGeneralized_pickle
class ReactionFieldGeneralizedTI
struct ReactionFieldGeneralizedTI_pickle
class SingleParticleInteractionTemplate
This class provides a template for a single-particle interaction, typically used for external forces on the system.
class SingleParticlePotential
This class is used to define single-particle interactions, typically used for external forces on the system.
class SingleParticlePotentialTemplate
Provides a template for the simple implementation of a position-dependent potential.
class SmoothSquareWell
This class provides methods to compute forces and energies of a squarewell potential based on Leitold and Dellago J.
struct SmoothSquareWell_pickle
class SoftCosine
This class provides methods to compute forces and energies of the SoftCosine potential.
struct SoftCosine_pickle
class StillingerWeberPairTerm
This class provides methods to compute forces and energies of 2 body term of Stillinger-Weber potential.
class StillingerWeberPairTermCapped
This class provides methods to compute forces and energies of 2 body term of Stillinger-Weber potential.
class StillingerWeberTripleTerm
class Tabulated
This class provides methods to compute forces and energies of a tabulated potential.
struct Tabulated_pickle
class TabulatedAngular
struct TabulatedAngular_pickle
class TabulatedDihedral
struct TabulatedDihedral_pickle
class TabulatedSubEns
This class provides methods to compute forces and energies of a tabulated potential.
struct TabulatedSubEns_pickle
class TabulatedSubEnsAngular
struct TabulatedSubEnsAngular_pickle
class TabulatedSubEnsDihedral
struct TabulatedSubEnsDihedral_pickle
class TersoffPairTerm
This class provides methods to compute forces and energies of 2 body term of Tersoff potential.
class TersoffTripleTerm
class VerletListAdressATATCGInteractionTemplate
class VerletListAdressATATInteractionTemplate
class VerletListAdressATInteractionTemplate
class VerletListAdressCGInteractionTemplate
class VerletListAdressInteractionTemplate
class VerletListHadressATATCGInteractionTemplate
class VerletListHadressATATInteractionTemplate
class VerletListHadressATInteractionTemplate
class VerletListHadressCGInteractionTemplate
class VerletListHadressInteractionTemplate
class VerletListInteractionTemplate
class VerletListPIadressInteractionTemplate
class VerletListPIadressNoDriftInteractionTemplate
class VerletListTripleInteractionTemplate
class VerletListVSphereInteractionTemplate
class VSpherePair
This class provides methods to compute forces and energies of the VSpherePair potential.
struct VSpherePair_pickle
class VSphereSelf
This class provides methods to compute forces and energies of the VSphereSelf potential.
class VSphereSelfInteractionTemplate
class Zero
This class provides methods for a zero potential no interactions between particles, mainly used for debugging and testing.
struct Zero_pickle
Typedefs
typedef class CellListAllParticlesInteractionTemplate< CoulombKSpaceEwald > CellListCoulombKSpaceEwald
typedef class CellListAllParticlesInteractionTemplate< CoulombKSpaceP3M > CellListCoulombKSpaceP3M
typedef class VerletListInteractionTemplate< CoulombRSpace > VerletListCoulombRSpace
typedef class VerletListInteractionTemplate< CoulombTruncated > VerletListCoulombTruncated
typedef class FixedPairListTypesInteractionTemplate< CoulombTruncated > FixedPairListTypesCoulombTruncated
typedef class VerletListInteractionTemplate< CoulombTruncatedUniqueCharge > VerletListCoulombTruncatedUniqueCharge
typedef class CellListAllPairsInteractionTemplate< CoulombTruncatedUniqueCharge > CellListCoulombTruncatedUniqueCharge
typedef class FixedPairListInteractionTemplate< CoulombTruncatedUniqueCharge > FixedPairListCoulombTruncatedUniqueCharge
typedef class FixedPairListInteractionTemplate< FENE > FixedPairListFENE
typedef class FixedPairListInteractionTemplate< FENECapped > FixedPairListFENECapped
typedef class VerletListInteractionTemplate< GravityTruncated > VerletListGravityTruncated
typedef class SingleParticleInteractionTemplate< HarmonicTrap > SingleParticleHarmonicTrap
typedef class VerletListInteractionTemplate< LennardJones > VerletListLennardJones
typedef class VerletListAdressInteractionTemplate< LennardJones, Tabulated > VerletListAdressLennardJones
typedef class VerletListAdressATInteractionTemplate< LennardJones > VerletListAdressATLennardJones
typedef class VerletListAdressATATInteractionTemplate< LennardJones, ReactionFieldGeneralized > VerletListAdressATLenJonesReacFieldGen
typedef class VerletListAdressATATCGInteractionTemplate< LennardJones, ReactionFieldGeneralized, Tabulated > VerletListAdressATLJReacFieldGenTab
typedef class VerletListAdressATATCGInteractionTemplate< LennardJones, ReactionFieldGeneralized, Harmonic > VerletListAdressATLJReacFieldGenHarmonic
typedef class VerletListAdressCGInteractionTemplate< LennardJones > VerletListAdressCGLennardJones
typedef class VerletListAdressInteractionTemplate< LennardJones, LennardJones > VerletListAdressLennardJones2
typedef class VerletListAdressInteractionTemplate< LennardJones, Harmonic > VerletListAdressLennardJonesHarmonic
typedef class VerletListHadressInteractionTemplate< LennardJones, Tabulated > VerletListHadressLennardJones
typedef class VerletListHadressATInteractionTemplate< LennardJones > VerletListHadressATLennardJones
typedef class VerletListHadressATATInteractionTemplate< LennardJones, ReactionFieldGeneralized > VerletListHadressATLenJonesReacFieldGen
typedef class VerletListHadressATATCGInteractionTemplate< LennardJones, ReactionFieldGeneralized, Tabulated > VerletListHadressATLJReacFieldGenTab
typedef class VerletListHadressATATCGInteractionTemplate< LennardJones, ReactionFieldGeneralized, Harmonic > VerletListHadressATLJReacFieldGenHarmonic
typedef class VerletListHadressCGInteractionTemplate< LennardJones > VerletListHadressCGLennardJones
typedef class VerletListHadressInteractionTemplate< LennardJones, LennardJones > VerletListHadressLennardJones2
typedef class VerletListHadressInteractionTemplate< LennardJones, Harmonic > VerletListHadressLennardJonesHarmonic
typedef class CellListAllPairsInteractionTemplate< LennardJones > CellListLennardJones
typedef class FixedPairListInteractionTemplate< LennardJones > FixedPairListLennardJones
typedef class FixedPairListTypesInteractionTemplate< LennardJones > FixedPairListTypesLennardJones
typedef class SingleParticleInteractionTemplate< LennardJones93Wall > SingleParticleLennardJones93Wall
typedef class VerletListInteractionTemplate< LennardJonesAutoBonds > VerletListLennardJonesAutoBonds
typedef class VerletListAdressInteractionTemplate< LennardJonesAutoBonds, Tabulated > VerletListAdressLennardJonesAutoBonds
typedef class VerletListHadressInteractionTemplate< LennardJonesAutoBonds, Tabulated > VerletListHadressLennardJonesAutoBonds
typedef class CellListAllPairsInteractionTemplate< LennardJonesAutoBonds > CellListLennardJonesAutoBonds
typedef class FixedPairListInteractionTemplate< LennardJonesAutoBonds > FixedPairListLennardJonesAutoBonds
typedef class VerletListInteractionTemplate< LennardJonesCapped > VerletListLennardJonesCapped
typedef class VerletListAdressInteractionTemplate< LennardJonesCapped, Tabulated > VerletListAdressLennardJonesCapped
typedef class VerletListHadressInteractionTemplate< LennardJonesCapped, Tabulated > VerletListHadressLennardJonesCapped
typedef class CellListAllPairsInteractionTemplate< LennardJonesCapped > CellListLennardJonesCapped
typedef class FixedPairListInteractionTemplate< LennardJonesCapped > FixedPairListLennardJonesCapped
typedef class VerletListInteractionTemplate< LennardJonesEnergyCapped > VerletListLennardJonesEnergyCapped
typedef class VerletListAdressInteractionTemplate< LennardJonesEnergyCapped, Tabulated > VerletListAdressLennardJonesEnergyCapped
typedef class VerletListHadressInteractionTemplate< LennardJonesEnergyCapped, Tabulated > VerletListHadressLennardJonesEnergyCapped
typedef class CellListAllPairsInteractionTemplate< LennardJonesEnergyCapped > CellListLennardJonesEnergyCapped
typedef class FixedPairListInteractionTemplate< LennardJonesEnergyCapped > FixedPairListLennardJonesEnergyCapped
typedef class VerletListInteractionTemplate< LennardJonesExpand > VerletListLennardJonesExpand
typedef class CellListAllPairsInteractionTemplate< LennardJonesExpand > CellListLennardJonesExpand
typedef class FixedPairListInteractionTemplate< LennardJonesExpand > FixedPairListLennardJonesExpand
typedef class VerletListInteractionTemplate< LennardJonesGeneric > VerletListLennardJonesGeneric
typedef class VerletListAdressInteractionTemplate< LennardJonesGeneric, Tabulated > VerletListAdressLennardJonesGeneric
typedef class VerletListAdressInteractionTemplate< LennardJonesGeneric, LennardJonesGeneric > VerletListAdressLennardJonesGeneric2
typedef class VerletListHadressInteractionTemplate< LennardJonesGeneric, Tabulated > VerletListHadressLennardJonesGeneric
typedef class VerletListHadressInteractionTemplate< LennardJonesGeneric, LennardJonesGeneric > VerletListHadressLennardJonesGeneric2
typedef class CellListAllPairsInteractionTemplate< LennardJonesGeneric > CellListLennardJonesGeneric
typedef class FixedPairListInteractionTemplate< LennardJonesGeneric > FixedPairListLennardJonesGeneric
typedef class VerletListInteractionTemplate< LennardJonesGromacs > VerletListLennardJonesGromacs
typedef class CellListAllPairsInteractionTemplate< LennardJonesGromacs > CellListLennardJonesGromacs
typedef class FixedPairListInteractionTemplate< LennardJonesGromacs > FixedPairListLennardJonesGromacs
typedef class VerletListInteractionTemplate< LennardJonesSoftcoreTI > VerletListLennardJonesSoftcoreTI
typedef class VerletListAdressInteractionTemplate< LennardJonesSoftcoreTI, Tabulated > VerletListAdressLennardJonesSoftcoreTI
typedef class VerletListHadressInteractionTemplate< LennardJonesSoftcoreTI, Tabulated > VerletListHadressLennardJonesSoftcoreTI
typedef class FixedPairListInteractionTemplate< LennardJonesSoftcoreTI > FixedPairListLennardJonesSoftcoreTI
typedef class FixedPairListTypesInteractionTemplate< LennardJonesSoftcoreTI > FixedPairListTypesLennardJonesSoftcoreTI
typedef class VerletListInteractionTemplate< LJcos > VerletListLJcos
typedef class VerletListAdressInteractionTemplate< LJcos, Tabulated > VerletListAdressLJcos
typedef class VerletListHadressInteractionTemplate< LJcos, Tabulated > VerletListHadressLJcos
typedef class CellListAllPairsInteractionTemplate< LJcos > CellListLJcos
typedef class FixedPairListInteractionTemplate< LJcos > FixedPairListLJcos
typedef class FixedPairListInteractionTemplate< MirrorLennardJones > FixedPairListMirrorLennardJones
typedef class VerletListInteractionTemplate< Morse > VerletListMorse
typedef class VerletListAdressInteractionTemplate< Morse, Tabulated > VerletListAdressMorse
typedef class VerletListHadressInteractionTemplate< Morse, Tabulated > VerletListHadressMorse
typedef class CellListAllPairsInteractionTemplate< Morse > CellListMorse
typedef class FixedPairListInteractionTemplate< Morse > FixedPairListMorse
typedef class VerletListInteractionTemplate< ReactionFieldGeneralized > VerletListReactionFieldGeneralized
typedef class VerletListAdressInteractionTemplate< ReactionFieldGeneralized, Tabulated > VerletListAdressReactionFieldGeneralized
typedef class VerletListAdressATInteractionTemplate< ReactionFieldGeneralized > VerletListAdressATReactionFieldGeneralized
typedef class VerletListHadressInteractionTemplate< ReactionFieldGeneralized, Tabulated > VerletListHadressReactionFieldGeneralized
typedef class VerletListHadressATInteractionTemplate< ReactionFieldGeneralized > VerletListHadressATReactionFieldGeneralized
typedef class CellListAllPairsInteractionTemplate< ReactionFieldGeneralized > CellListReactionFieldGeneralized
typedef class VerletListAdressInteractionTemplate< ReactionFieldGeneralizedTI, Tabulated > VerletListAdressReactionFieldGeneralizedTI
typedef class VerletListInteractionTemplate< SmoothSquareWell > VerletListSmoothSquareWell
typedef class FixedPairListInteractionTemplate< SmoothSquareWell > FixedPairListSmoothSquareWell
typedef class FixedPairListTypesInteractionTemplate< SmoothSquareWell > FixedPairListTypesSmoothSquareWell
typedef class VerletListInteractionTemplate< SoftCosine > VerletListSoftCosine
typedef class CellListAllPairsInteractionTemplate< SoftCosine > CellListSoftCosine
typedef class FixedPairListInteractionTemplate< SoftCosine > FixedPairListSoftCosine
typedef class VerletListInteractionTemplate< StillingerWeberPairTerm > VerletListStillingerWeberPairTerm
typedef class VerletListAdressInteractionTemplate< StillingerWeberPairTerm, Tabulated > VerletListAdressStillingerWeberPairTerm
typedef class VerletListHadressInteractionTemplate< StillingerWeberPairTerm, Tabulated > VerletListHadressStillingerWeberPairTerm
typedef class CellListAllPairsInteractionTemplate< StillingerWeberPairTerm > CellListStillingerWeberPairTerm
typedef class FixedPairListInteractionTemplate< StillingerWeberPairTerm > FixedPairListStillingerWeberPairTerm
typedef class VerletListInteractionTemplate< StillingerWeberPairTermCapped > VerletListStillingerWeberPairTermCapped
typedef class VerletListAdressInteractionTemplate< StillingerWeberPairTermCapped, Tabulated > VerletListAdressStillingerWeberPairTermCapped
typedef class VerletListHadressInteractionTemplate< StillingerWeberPairTermCapped, Tabulated > VerletListHadressStillingerWeberPairTermCapped
typedef class CellListAllPairsInteractionTemplate< StillingerWeberPairTermCapped > CellListStillingerWeberPairTermCapped
typedef class FixedPairListInteractionTemplate< StillingerWeberPairTermCapped > FixedPairListStillingerWeberPairTermCapped
typedef class VerletListTripleInteractionTemplate< StillingerWeberTripleTerm > VerletListStillingerWeberTripleTerm
typedef class FixedTripleListInteractionTemplate< StillingerWeberTripleTerm > FixedListStillingerWeberTripleTerm
typedef class VerletListInteractionTemplate< Tabulated > VerletListTabulated
typedef class VerletListAdressInteractionTemplate< Tabulated, Tabulated > VerletListAdressTabulated
typedef class VerletListAdressCGInteractionTemplate< Tabulated > VerletListAdressCGTabulated
typedef class VerletListHadressInteractionTemplate< Tabulated, Tabulated > VerletListHadressTabulated
typedef class VerletListHadressCGInteractionTemplate< Tabulated > VerletListHadressCGTabulated
typedef class VerletListPIadressInteractionTemplate< Tabulated, Tabulated > VerletListPIadressTabulated
typedef class VerletListPIadressInteractionTemplate< Tabulated, LennardJones > VerletListPIadressTabulatedLJ
typedef class VerletListPIadressNoDriftInteractionTemplate< Tabulated > VerletListPIadressNoDriftTabulated
typedef class CellListAllPairsInteractionTemplate< Tabulated > CellListTabulated
typedef class FixedPairListInteractionTemplate< Tabulated > FixedPairListTabulated
typedef class FixedPairListTypesInteractionTemplate< Tabulated > FixedPairListTypesTabulated
typedef class FixedPairListPIadressInteractionTemplate< Tabulated > FixedPairListPIadressTabulated
typedef class FixedTripleListInteractionTemplate< TabulatedAngular > FixedTripleListTabulatedAngular
typedef class FixedTripleListTypesInteractionTemplate< TabulatedAngular > FixedTripleListTypesTabulatedAngular
typedef class FixedTripleListPIadressInteractionTemplate< TabulatedAngular > FixedTripleListPIadressTabulatedAngular
typedef class FixedQuadrupleListInteractionTemplate< TabulatedDihedral > FixedQuadrupleListTabulatedDihedral
typedef class FixedQuadrupleListTypesInteractionTemplate< TabulatedDihedral > FixedQuadrupleListTypesTabulatedDihedral
typedef class VerletListInteractionTemplate< TabulatedSubEns > VerletListTabulatedSubEns
typedef class VerletListAdressInteractionTemplate< TabulatedSubEns, TabulatedSubEns > VerletListAdressTabulatedSubEns
typedef class VerletListHadressInteractionTemplate< TabulatedSubEns, TabulatedSubEns > VerletListHadressTabulatedSubEns
typedef class CellListAllPairsInteractionTemplate< TabulatedSubEns > CellListTabulatedSubEns
typedef class FixedPairListInteractionTemplate< TabulatedSubEns > FixedPairListTabulatedSubEns
typedef class FixedPairListTypesInteractionTemplate< TabulatedSubEns > FixedPairListTypesTabulatedSubEns
typedef class FixedTripleListInteractionTemplate< TabulatedSubEnsAngular > FixedTripleListTabulatedSubEnsAngular
typedef class FixedTripleListTypesInteractionTemplate< TabulatedSubEnsAngular > FixedTripleListTypesTabulatedSubEnsAngular
typedef class FixedQuadrupleListInteractionTemplate< TabulatedSubEnsDihedral > FixedQuadrupleListTabulatedSubEnsDihedral
typedef class FixedQuadrupleListTypesInteractionTemplate< TabulatedSubEnsDihedral > FixedQuadrupleListTypesTabulatedSubEnsDihedral
typedef class VerletListInteractionTemplate< TersoffPairTerm > VerletListTersoffPairTerm
typedef class VerletListAdressInteractionTemplate< TersoffPairTerm, Tabulated > VerletListAdressTersoffPairTerm
typedef class CellListAllPairsInteractionTemplate< TersoffPairTerm > CellListTersoffPairTerm
typedef class FixedPairListInteractionTemplate< TersoffPairTerm > FixedPairListTersoffPairTerm
typedef class VerletListTripleInteractionTemplate< TersoffTripleTerm > VerletListTersoffTripleTerm
typedef class FixedTripleListInteractionTemplate< TersoffTripleTerm > FixedListTersoffTripleTerm
typedef class VerletListVSphereInteractionTemplate< VSpherePair > VerletListVSpherePair
typedef class VSphereSelfInteractionTemplate< VSphereSelf > SelfVSphere
typedef class VerletListInteractionTemplate< Zero > VerletListZero
typedef class VerletListAdressInteractionTemplate< Zero, Tabulated > VerletListAdressZero
typedef class VerletListHadressInteractionTemplate< Zero, Tabulated > VerletListHadressZero
typedef class CellListAllPairsInteractionTemplate< Zero > CellListZero
typedef class FixedPairListInteractionTemplate< Zero > FixedPairListZero
Enumerations
enum bondTypes {
unused, Nonbonded, Single, Pair,
Angular, Dihedral, NonbondedSlow
}
Functions
LOG4ESPP_LOGGER (AngularPotential::theLogger, "AngularPotential")
void registerPython ()
LOG4ESPP_LOGGER (DihedralPotential::theLogger, "DihedralPotential")
LOG4ESPP_LOGGER (FENE::theLogger, "FENE")
LOG4ESPP_LOGGER (Interaction::theLogger, "Interaction")
LOG4ESPP_LOGGER (InterpolationAkima::theLogger, "InterpolationAkima")
LOG4ESPP_LOGGER (InterpolationCubic::theLogger, "InterpolationCubic")
LOG4ESPP_LOGGER (InterpolationLinear::theLogger, "InterpolationLinear")
LOG4ESPP_LOGGER (InterpolationTable::theLogger, "InterpolationTable")
LOG4ESPP_LOGGER (LennardJones::theLogger, "LennardJones")
LOG4ESPP_LOGGER (LennardJonesGeneric::theLogger, "LennardJonesGeneric")
LOG4ESPP_LOGGER (Potential::theLogger, "Potential")
LOG4ESPP_LOGGER (PotentialVSpherePair::theLogger, "PotentialVSpherePair")
LOG4ESPP_LOGGER (SingleParticlePotential::theLogger, "SingleParticlePotential")
Typedef Documentation
CellListCoulombKSpaceEwald
typedef class CellListAllParticlesInteractionTemplate< CoulombKSpaceEwald > espressopp::interaction::CellListCoulombKSpaceEwald
Definition at line 31 of file CoulombKSpaceEwald.cpp.
CellListCoulombKSpaceP3M
typedef class CellListAllParticlesInteractionTemplate< CoulombKSpaceP3M > espressopp::interaction::CellListCoulombKSpaceP3M
Definition at line 31 of file CoulombKSpaceP3M.cpp.
CellListCoulombTruncatedUniqueCharge
typedef class CellListAllPairsInteractionTemplate< CoulombTruncatedUniqueCharge > espressopp::interaction::CellListCoulombTruncatedUniqueCharge
Definition at line 33 of file CoulombTruncatedUniqueCharge.cpp.
CellListLennardJones
typedef class CellListAllPairsInteractionTemplate< LennardJones > espressopp::interaction::CellListLennardJones
Definition at line 80 of file LennardJones.cpp.
CellListLennardJonesAutoBonds
typedef class CellListAllPairsInteractionTemplate< LennardJonesAutoBonds > espressopp::interaction::CellListLennardJonesAutoBonds
Definition at line 41 of file LennardJonesAutoBonds.cpp.
CellListLennardJonesCapped
typedef class CellListAllPairsInteractionTemplate< LennardJonesCapped > espressopp::interaction::CellListLennardJonesCapped
Definition at line 41 of file LennardJonesCapped.cpp.
CellListLennardJonesEnergyCapped
typedef class CellListAllPairsInteractionTemplate< LennardJonesEnergyCapped > espressopp::interaction::CellListLennardJonesEnergyCapped
Definition at line 41 of file LennardJonesEnergyCapped.cpp.
CellListLennardJonesExpand
typedef class CellListAllPairsInteractionTemplate< LennardJonesExpand > espressopp::interaction::CellListLennardJonesExpand
Definition at line 33 of file LennardJonesExpand.cpp.
CellListLennardJonesGeneric
typedef class CellListAllPairsInteractionTemplate< LennardJonesGeneric > espressopp::interaction::CellListLennardJonesGeneric
Definition at line 45 of file LennardJonesGeneric.cpp.
CellListLennardJonesGromacs
typedef class CellListAllPairsInteractionTemplate< LennardJonesGromacs > espressopp::interaction::CellListLennardJonesGromacs
Definition at line 33 of file LennardJonesGromacs.cpp.
CellListLJcos
typedef class CellListAllPairsInteractionTemplate< LJcos > espressopp::interaction::CellListLJcos
Definition at line 39 of file LJcos.cpp.
CellListMorse
typedef class CellListAllPairsInteractionTemplate< Morse > espressopp::interaction::CellListMorse
Definition at line 40 of file Morse.cpp.
CellListReactionFieldGeneralized
typedef class CellListAllPairsInteractionTemplate< ReactionFieldGeneralized > espressopp::interaction::CellListReactionFieldGeneralized
Definition at line 52 of file ReactionFieldGeneralized.cpp.
CellListSoftCosine
typedef class CellListAllPairsInteractionTemplate< SoftCosine > espressopp::interaction::CellListSoftCosine
Definition at line 33 of file SoftCosine.cpp.
CellListStillingerWeberPairTerm
typedef class CellListAllPairsInteractionTemplate< StillingerWeberPairTerm > espressopp::interaction::CellListStillingerWeberPairTerm
Definition at line 36 of file StillingerWeberPairTerm.cpp.
CellListStillingerWeberPairTermCapped
typedef class CellListAllPairsInteractionTemplate< StillingerWeberPairTermCapped > espressopp::interaction::CellListStillingerWeberPairTermCapped
Definition at line 36 of file StillingerWeberPairTermCapped.cpp.
CellListTabulated
typedef class CellListAllPairsInteractionTemplate< Tabulated > espressopp::interaction::CellListTabulated
Definition at line 77 of file Tabulated.cpp.
CellListTabulatedSubEns
typedef class CellListAllPairsInteractionTemplate< TabulatedSubEns > espressopp::interaction::CellListTabulatedSubEns
Definition at line 234 of file TabulatedSubEns.cpp.
CellListTersoffPairTerm
typedef class CellListAllPairsInteractionTemplate< TersoffPairTerm > espressopp::interaction::CellListTersoffPairTerm
Definition at line 34 of file TersoffPairTerm.cpp.
CellListZero
typedef class CellListAllPairsInteractionTemplate< Zero > espressopp::interaction::CellListZero
Definition at line 41 of file Zero.cpp.
FixedListStillingerWeberTripleTerm
typedef class FixedTripleListInteractionTemplate< StillingerWeberTripleTerm > espressopp::interaction::FixedListStillingerWeberTripleTerm
Definition at line 36 of file StillingerWeberTripleTerm.cpp.
FixedListTersoffTripleTerm
typedef class FixedTripleListInteractionTemplate< TersoffTripleTerm > espressopp::interaction::FixedListTersoffTripleTerm
Definition at line 36 of file TersoffTripleTerm.cpp.
FixedPairListCoulombTruncatedUniqueCharge
typedef class FixedPairListInteractionTemplate< CoulombTruncatedUniqueCharge > espressopp::interaction::FixedPairListCoulombTruncatedUniqueCharge
Definition at line 35 of file CoulombTruncatedUniqueCharge.cpp.
FixedPairListFENE
typedef class FixedPairListInteractionTemplate< FENE > espressopp::interaction::FixedPairListFENE
Definition at line 29 of file FENE.cpp.
FixedPairListFENECapped
typedef class FixedPairListInteractionTemplate< FENECapped > espressopp::interaction::FixedPairListFENECapped
Definition at line 29 of file FENECapped.cpp.
FixedPairListLennardJones
typedef class FixedPairListInteractionTemplate< LennardJones > espressopp::interaction::FixedPairListLennardJones
Definition at line 82 of file LennardJones.cpp.
FixedPairListLennardJonesAutoBonds
typedef class FixedPairListInteractionTemplate< LennardJonesAutoBonds > espressopp::interaction::FixedPairListLennardJonesAutoBonds
Definition at line 43 of file LennardJonesAutoBonds.cpp.
FixedPairListLennardJonesCapped
typedef class FixedPairListInteractionTemplate< LennardJonesCapped > espressopp::interaction::FixedPairListLennardJonesCapped
Definition at line 43 of file LennardJonesCapped.cpp.
FixedPairListLennardJonesEnergyCapped
typedef class FixedPairListInteractionTemplate< LennardJonesEnergyCapped > espressopp::interaction::FixedPairListLennardJonesEnergyCapped
Definition at line 43 of file LennardJonesEnergyCapped.cpp.
FixedPairListLennardJonesExpand
typedef class FixedPairListInteractionTemplate< LennardJonesExpand > espressopp::interaction::FixedPairListLennardJonesExpand
Definition at line 35 of file LennardJonesExpand.cpp.
FixedPairListLennardJonesGeneric
typedef class FixedPairListInteractionTemplate< LennardJonesGeneric > espressopp::interaction::FixedPairListLennardJonesGeneric
Definition at line 47 of file LennardJonesGeneric.cpp.
FixedPairListLennardJonesGromacs
typedef class FixedPairListInteractionTemplate< LennardJonesGromacs > espressopp::interaction::FixedPairListLennardJonesGromacs
Definition at line 35 of file LennardJonesGromacs.cpp.
FixedPairListLennardJonesSoftcoreTI
typedef class FixedPairListInteractionTemplate< LennardJonesSoftcoreTI > espressopp::interaction::FixedPairListLennardJonesSoftcoreTI
Definition at line 41 of file LennardJonesSoftcoreTI.cpp.
FixedPairListLJcos
typedef class FixedPairListInteractionTemplate< LJcos > espressopp::interaction::FixedPairListLJcos
Definition at line 41 of file LJcos.cpp.
FixedPairListMirrorLennardJones
typedef class FixedPairListInteractionTemplate< MirrorLennardJones > espressopp::interaction::FixedPairListMirrorLennardJones
Definition at line 31 of file MirrorLennardJones.cpp.
FixedPairListMorse
typedef class FixedPairListInteractionTemplate< Morse > espressopp::interaction::FixedPairListMorse
Definition at line 42 of file Morse.cpp.
FixedPairListPIadressTabulated
typedef class FixedPairListPIadressInteractionTemplate< Tabulated > espressopp::interaction::FixedPairListPIadressTabulated
Definition at line 80 of file Tabulated.cpp.
FixedPairListSmoothSquareWell
typedef class FixedPairListInteractionTemplate< SmoothSquareWell > espressopp::interaction::FixedPairListSmoothSquareWell
Definition at line 31 of file SmoothSquareWell.cpp.
FixedPairListSoftCosine
typedef class FixedPairListInteractionTemplate< SoftCosine > espressopp::interaction::FixedPairListSoftCosine
Definition at line 35 of file SoftCosine.cpp.
FixedPairListStillingerWeberPairTerm
typedef class FixedPairListInteractionTemplate< StillingerWeberPairTerm > espressopp::interaction::FixedPairListStillingerWeberPairTerm
Definition at line 38 of file StillingerWeberPairTerm.cpp.
FixedPairListStillingerWeberPairTermCapped
typedef class FixedPairListInteractionTemplate< StillingerWeberPairTermCapped > espressopp::interaction::FixedPairListStillingerWeberPairTermCapped
Definition at line 38 of file StillingerWeberPairTermCapped.cpp.
FixedPairListTabulated
typedef class FixedPairListInteractionTemplate< Tabulated > espressopp::interaction::FixedPairListTabulated
Definition at line 78 of file Tabulated.cpp.
FixedPairListTabulatedSubEns
typedef class FixedPairListInteractionTemplate< TabulatedSubEns > espressopp::interaction::FixedPairListTabulatedSubEns
Definition at line 235 of file TabulatedSubEns.cpp.
FixedPairListTersoffPairTerm
typedef class FixedPairListInteractionTemplate< TersoffPairTerm > espressopp::interaction::FixedPairListTersoffPairTerm
Definition at line 36 of file TersoffPairTerm.cpp.
FixedPairListTypesCoulombTruncated
typedef class FixedPairListTypesInteractionTemplate< CoulombTruncated > espressopp::interaction::FixedPairListTypesCoulombTruncated
Definition at line 36 of file CoulombTruncated.cpp.
FixedPairListTypesLennardJones
typedef class FixedPairListTypesInteractionTemplate< LennardJones > espressopp::interaction::FixedPairListTypesLennardJones
Definition at line 84 of file LennardJones.cpp.
FixedPairListTypesLennardJonesSoftcoreTI
typedef class FixedPairListTypesInteractionTemplate< LennardJonesSoftcoreTI > espressopp::interaction::FixedPairListTypesLennardJonesSoftcoreTI
Definition at line 43 of file LennardJonesSoftcoreTI.cpp.
FixedPairListTypesSmoothSquareWell
typedef class FixedPairListTypesInteractionTemplate< SmoothSquareWell > espressopp::interaction::FixedPairListTypesSmoothSquareWell
Definition at line 32 of file SmoothSquareWell.cpp.
FixedPairListTypesTabulated
typedef class FixedPairListTypesInteractionTemplate< Tabulated > espressopp::interaction::FixedPairListTypesTabulated
Definition at line 79 of file Tabulated.cpp.
FixedPairListTypesTabulatedSubEns
typedef class FixedPairListTypesInteractionTemplate< TabulatedSubEns > espressopp::interaction::FixedPairListTypesTabulatedSubEns
Definition at line 236 of file TabulatedSubEns.cpp.
FixedPairListZero
typedef class FixedPairListInteractionTemplate< Zero > espressopp::interaction::FixedPairListZero
Definition at line 43 of file Zero.cpp.
FixedQuadrupleListTabulatedDihedral
typedef class FixedQuadrupleListInteractionTemplate< TabulatedDihedral > espressopp::interaction::FixedQuadrupleListTabulatedDihedral
Definition at line 60 of file TabulatedDihedral.cpp.
FixedQuadrupleListTabulatedSubEnsDihedral
typedef class FixedQuadrupleListInteractionTemplate< TabulatedSubEnsDihedral > espressopp::interaction::FixedQuadrupleListTabulatedSubEnsDihedral
Definition at line 231 of file TabulatedSubEnsDihedral.cpp.
FixedQuadrupleListTypesTabulatedDihedral
typedef class FixedQuadrupleListTypesInteractionTemplate< TabulatedDihedral > espressopp::interaction::FixedQuadrupleListTypesTabulatedDihedral
Definition at line 63 of file TabulatedDihedral.cpp.
FixedQuadrupleListTypesTabulatedSubEnsDihedral
typedef class FixedQuadrupleListTypesInteractionTemplate< TabulatedSubEnsDihedral > espressopp::interaction::FixedQuadrupleListTypesTabulatedSubEnsDihedral
Definition at line 234 of file TabulatedSubEnsDihedral.cpp.
FixedTripleListPIadressTabulatedAngular
typedef class FixedTripleListPIadressInteractionTemplate< TabulatedAngular > espressopp::interaction::FixedTripleListPIadressTabulatedAngular
Definition at line 63 of file TabulatedAngular.cpp.
FixedTripleListTabulatedAngular
typedef class FixedTripleListInteractionTemplate< TabulatedAngular > espressopp::interaction::FixedTripleListTabulatedAngular
Definition at line 59 of file TabulatedAngular.cpp.
FixedTripleListTabulatedSubEnsAngular
typedef class FixedTripleListInteractionTemplate< TabulatedSubEnsAngular > espressopp::interaction::FixedTripleListTabulatedSubEnsAngular
Definition at line 232 of file TabulatedSubEnsAngular.cpp.
FixedTripleListTypesTabulatedAngular
typedef class FixedTripleListTypesInteractionTemplate< TabulatedAngular > espressopp::interaction::FixedTripleListTypesTabulatedAngular
Definition at line 61 of file TabulatedAngular.cpp.
FixedTripleListTypesTabulatedSubEnsAngular
typedef class FixedTripleListTypesInteractionTemplate< TabulatedSubEnsAngular > espressopp::interaction::FixedTripleListTypesTabulatedSubEnsAngular
Definition at line 234 of file TabulatedSubEnsAngular.cpp.
SelfVSphere
typedef class VSphereSelfInteractionTemplate< VSphereSelf > espressopp::interaction::SelfVSphere
Definition at line 29 of file VSphereSelf.cpp.
SingleParticleHarmonicTrap
typedef class SingleParticleInteractionTemplate< HarmonicTrap > espressopp::interaction::SingleParticleHarmonicTrap
Definition at line 32 of file HarmonicTrap.cpp.
SingleParticleLennardJones93Wall
typedef class SingleParticleInteractionTemplate< LennardJones93Wall > espressopp::interaction::SingleParticleLennardJones93Wall
Definition at line 32 of file LennardJones93Wall.cpp.
VerletListAdressATLenJonesReacFieldGen
typedef class VerletListAdressATATInteractionTemplate< LennardJones, ReactionFieldGeneralized > espressopp::interaction::VerletListAdressATLenJonesReacFieldGen
Definition at line 52 of file LennardJones.cpp.
VerletListAdressATLennardJones
typedef class VerletListAdressATInteractionTemplate< LennardJones > espressopp::interaction::VerletListAdressATLennardJones
Definition at line 50 of file LennardJones.cpp.
VerletListAdressATLJReacFieldGenHarmonic
typedef class VerletListAdressATATCGInteractionTemplate< LennardJones, ReactionFieldGeneralized, Harmonic > espressopp::interaction::VerletListAdressATLJReacFieldGenHarmonic
Definition at line 56 of file LennardJones.cpp.
VerletListAdressATLJReacFieldGenTab
typedef class VerletListAdressATATCGInteractionTemplate< LennardJones, ReactionFieldGeneralized, Tabulated > espressopp::interaction::VerletListAdressATLJReacFieldGenTab
Definition at line 54 of file LennardJones.cpp.
VerletListAdressATReactionFieldGeneralized
typedef class VerletListAdressATInteractionTemplate< ReactionFieldGeneralized > espressopp::interaction::VerletListAdressATReactionFieldGeneralized
Definition at line 43 of file ReactionFieldGeneralized.cpp.
VerletListAdressCGLennardJones
typedef class VerletListAdressCGInteractionTemplate< LennardJones > espressopp::interaction::VerletListAdressCGLennardJones
Definition at line 58 of file LennardJones.cpp.
VerletListAdressCGTabulated
typedef class VerletListAdressCGInteractionTemplate< Tabulated > espressopp::interaction::VerletListAdressCGTabulated
Definition at line 71 of file Tabulated.cpp.
VerletListAdressLennardJones
typedef class VerletListAdressInteractionTemplate< LennardJones, Tabulated > espressopp::interaction::VerletListAdressLennardJones
Definition at line 48 of file LennardJones.cpp.
VerletListAdressLennardJones2
typedef class VerletListAdressInteractionTemplate< LennardJones, LennardJones > espressopp::interaction::VerletListAdressLennardJones2
Definition at line 60 of file LennardJones.cpp.
VerletListAdressLennardJonesAutoBonds
typedef class VerletListAdressInteractionTemplate< LennardJonesAutoBonds, Tabulated > espressopp::interaction::VerletListAdressLennardJonesAutoBonds
Definition at line 37 of file LennardJonesAutoBonds.cpp.
VerletListAdressLennardJonesCapped
typedef class VerletListAdressInteractionTemplate< LennardJonesCapped, Tabulated > espressopp::interaction::VerletListAdressLennardJonesCapped
Definition at line 37 of file LennardJonesCapped.cpp.
VerletListAdressLennardJonesEnergyCapped
typedef class VerletListAdressInteractionTemplate< LennardJonesEnergyCapped, Tabulated > espressopp::interaction::VerletListAdressLennardJonesEnergyCapped
Definition at line 37 of file LennardJonesEnergyCapped.cpp.
VerletListAdressLennardJonesGeneric
typedef class VerletListAdressInteractionTemplate< LennardJonesGeneric, Tabulated > espressopp::interaction::VerletListAdressLennardJonesGeneric
Definition at line 37 of file LennardJonesGeneric.cpp.
VerletListAdressLennardJonesGeneric2
typedef class VerletListAdressInteractionTemplate< LennardJonesGeneric, LennardJonesGeneric > espressopp::interaction::VerletListAdressLennardJonesGeneric2
Definition at line 39 of file LennardJonesGeneric.cpp.
VerletListAdressLennardJonesHarmonic
typedef class VerletListAdressInteractionTemplate< LennardJones, Harmonic > espressopp::interaction::VerletListAdressLennardJonesHarmonic
Definition at line 62 of file LennardJones.cpp.
VerletListAdressLennardJonesSoftcoreTI
typedef class VerletListAdressInteractionTemplate< LennardJonesSoftcoreTI, Tabulated > espressopp::interaction::VerletListAdressLennardJonesSoftcoreTI
Definition at line 37 of file LennardJonesSoftcoreTI.cpp.
VerletListAdressLJcos
typedef class VerletListAdressInteractionTemplate< LJcos, Tabulated > espressopp::interaction::VerletListAdressLJcos
Definition at line 35 of file LJcos.cpp.
VerletListAdressMorse
typedef class VerletListAdressInteractionTemplate< Morse, Tabulated > espressopp::interaction::VerletListAdressMorse
Definition at line 36 of file Morse.cpp.
VerletListAdressReactionFieldGeneralized
typedef class VerletListAdressInteractionTemplate< ReactionFieldGeneralized, Tabulated > espressopp::interaction::VerletListAdressReactionFieldGeneralized
Definition at line 40 of file ReactionFieldGeneralized.cpp.
VerletListAdressReactionFieldGeneralizedTI
typedef class VerletListAdressInteractionTemplate< ReactionFieldGeneralizedTI, Tabulated > espressopp::interaction::VerletListAdressReactionFieldGeneralizedTI
Definition at line 36 of file ReactionFieldGeneralizedTI.cpp.
VerletListAdressStillingerWeberPairTerm
typedef class VerletListAdressInteractionTemplate< StillingerWeberPairTerm, Tabulated > espressopp::interaction::VerletListAdressStillingerWeberPairTerm
Definition at line 32 of file StillingerWeberPairTerm.cpp.
VerletListAdressStillingerWeberPairTermCapped
typedef class VerletListAdressInteractionTemplate< StillingerWeberPairTermCapped, Tabulated > espressopp::interaction::VerletListAdressStillingerWeberPairTermCapped
Definition at line 32 of file StillingerWeberPairTermCapped.cpp.
VerletListAdressTabulated
typedef class VerletListAdressInteractionTemplate< Tabulated, Tabulated > espressopp::interaction::VerletListAdressTabulated
Definition at line 70 of file Tabulated.cpp.
VerletListAdressTabulatedSubEns
typedef class VerletListAdressInteractionTemplate< TabulatedSubEns, TabulatedSubEns > espressopp::interaction::VerletListAdressTabulatedSubEns
Definition at line 232 of file TabulatedSubEns.cpp.
VerletListAdressTersoffPairTerm
typedef class VerletListAdressInteractionTemplate< TersoffPairTerm, Tabulated > espressopp::interaction::VerletListAdressTersoffPairTerm
Definition at line 32 of file TersoffPairTerm.cpp.
VerletListAdressZero
typedef class VerletListAdressInteractionTemplate< Zero, Tabulated > espressopp::interaction::VerletListAdressZero
Definition at line 37 of file Zero.cpp.
VerletListCoulombRSpace
typedef class VerletListInteractionTemplate< CoulombRSpace > espressopp::interaction::VerletListCoulombRSpace
Definition at line 33 of file CoulombRSpace.cpp.
VerletListCoulombTruncated
typedef class VerletListInteractionTemplate< CoulombTruncated > espressopp::interaction::VerletListCoulombTruncated
Definition at line 34 of file CoulombTruncated.cpp.
VerletListCoulombTruncatedUniqueCharge
typedef class VerletListInteractionTemplate< CoulombTruncatedUniqueCharge > espressopp::interaction::VerletListCoulombTruncatedUniqueCharge
Definition at line 31 of file CoulombTruncatedUniqueCharge.cpp.
VerletListGravityTruncated
typedef class VerletListInteractionTemplate< GravityTruncated > espressopp::interaction::VerletListGravityTruncated
Definition at line 30 of file GravityTruncated.cpp.
VerletListHadressATLenJonesReacFieldGen
typedef class VerletListHadressATATInteractionTemplate< LennardJones, ReactionFieldGeneralized > espressopp::interaction::VerletListHadressATLenJonesReacFieldGen
Definition at line 68 of file LennardJones.cpp.
VerletListHadressATLennardJones
typedef class VerletListHadressATInteractionTemplate< LennardJones > espressopp::interaction::VerletListHadressATLennardJones
Definition at line 66 of file LennardJones.cpp.
VerletListHadressATLJReacFieldGenHarmonic
typedef class VerletListHadressATATCGInteractionTemplate< LennardJones, ReactionFieldGeneralized, Harmonic > espressopp::interaction::VerletListHadressATLJReacFieldGenHarmonic
Definition at line 72 of file LennardJones.cpp.
VerletListHadressATLJReacFieldGenTab
typedef class VerletListHadressATATCGInteractionTemplate< LennardJones, ReactionFieldGeneralized, Tabulated > espressopp::interaction::VerletListHadressATLJReacFieldGenTab
Definition at line 70 of file LennardJones.cpp.
VerletListHadressATReactionFieldGeneralized
typedef class VerletListHadressATInteractionTemplate< ReactionFieldGeneralized > espressopp::interaction::VerletListHadressATReactionFieldGeneralized
Definition at line 49 of file ReactionFieldGeneralized.cpp.
VerletListHadressCGLennardJones
typedef class VerletListHadressCGInteractionTemplate< LennardJones > espressopp::interaction::VerletListHadressCGLennardJones
Definition at line 74 of file LennardJones.cpp.
VerletListHadressCGTabulated
typedef class VerletListHadressCGInteractionTemplate< Tabulated > espressopp::interaction::VerletListHadressCGTabulated
Definition at line 73 of file Tabulated.cpp.
VerletListHadressLennardJones
typedef class VerletListHadressInteractionTemplate< LennardJones, Tabulated > espressopp::interaction::VerletListHadressLennardJones
Definition at line 64 of file LennardJones.cpp.
VerletListHadressLennardJones2
typedef class VerletListHadressInteractionTemplate< LennardJones, LennardJones > espressopp::interaction::VerletListHadressLennardJones2
Definition at line 76 of file LennardJones.cpp.
VerletListHadressLennardJonesAutoBonds
typedef class VerletListHadressInteractionTemplate< LennardJonesAutoBonds, Tabulated > espressopp::interaction::VerletListHadressLennardJonesAutoBonds
Definition at line 39 of file LennardJonesAutoBonds.cpp.
VerletListHadressLennardJonesCapped
typedef class VerletListHadressInteractionTemplate< LennardJonesCapped, Tabulated > espressopp::interaction::VerletListHadressLennardJonesCapped
Definition at line 39 of file LennardJonesCapped.cpp.
VerletListHadressLennardJonesEnergyCapped
typedef class VerletListHadressInteractionTemplate< LennardJonesEnergyCapped, Tabulated > espressopp::interaction::VerletListHadressLennardJonesEnergyCapped
Definition at line 39 of file LennardJonesEnergyCapped.cpp.
VerletListHadressLennardJonesGeneric
typedef class VerletListHadressInteractionTemplate< LennardJonesGeneric, Tabulated > espressopp::interaction::VerletListHadressLennardJonesGeneric
Definition at line 41 of file LennardJonesGeneric.cpp.
VerletListHadressLennardJonesGeneric2
typedef class VerletListHadressInteractionTemplate< LennardJonesGeneric, LennardJonesGeneric > espressopp::interaction::VerletListHadressLennardJonesGeneric2
Definition at line 43 of file LennardJonesGeneric.cpp.
VerletListHadressLennardJonesHarmonic
typedef class VerletListHadressInteractionTemplate< LennardJones, Harmonic > espressopp::interaction::VerletListHadressLennardJonesHarmonic
Definition at line 78 of file LennardJones.cpp.
VerletListHadressLennardJonesSoftcoreTI
typedef class VerletListHadressInteractionTemplate< LennardJonesSoftcoreTI, Tabulated > espressopp::interaction::VerletListHadressLennardJonesSoftcoreTI
Definition at line 39 of file LennardJonesSoftcoreTI.cpp.
VerletListHadressLJcos
typedef class VerletListHadressInteractionTemplate< LJcos, Tabulated > espressopp::interaction::VerletListHadressLJcos
Definition at line 37 of file LJcos.cpp.
VerletListHadressMorse
typedef class VerletListHadressInteractionTemplate< Morse, Tabulated > espressopp::interaction::VerletListHadressMorse
Definition at line 38 of file Morse.cpp.
VerletListHadressReactionFieldGeneralized
typedef class VerletListHadressInteractionTemplate< ReactionFieldGeneralized, Tabulated > espressopp::interaction::VerletListHadressReactionFieldGeneralized
Definition at line 46 of file ReactionFieldGeneralized.cpp.
VerletListHadressStillingerWeberPairTerm
typedef class VerletListHadressInteractionTemplate< StillingerWeberPairTerm, Tabulated > espressopp::interaction::VerletListHadressStillingerWeberPairTerm
Definition at line 34 of file StillingerWeberPairTerm.cpp.
VerletListHadressStillingerWeberPairTermCapped
typedef class VerletListHadressInteractionTemplate< StillingerWeberPairTermCapped, Tabulated > espressopp::interaction::VerletListHadressStillingerWeberPairTermCapped
Definition at line 34 of file StillingerWeberPairTermCapped.cpp.
VerletListHadressTabulated
typedef class VerletListHadressInteractionTemplate< Tabulated, Tabulated > espressopp::interaction::VerletListHadressTabulated
Definition at line 72 of file Tabulated.cpp.
VerletListHadressTabulatedSubEns
typedef class VerletListHadressInteractionTemplate< TabulatedSubEns, TabulatedSubEns > espressopp::interaction::VerletListHadressTabulatedSubEns
Definition at line 233 of file TabulatedSubEns.cpp.
VerletListHadressZero
typedef class VerletListHadressInteractionTemplate< Zero, Tabulated > espressopp::interaction::VerletListHadressZero
Definition at line 39 of file Zero.cpp.
VerletListLennardJones
typedef class VerletListInteractionTemplate< LennardJones > espressopp::interaction::VerletListLennardJones
Definition at line 46 of file LennardJones.cpp.
VerletListLennardJonesAutoBonds
typedef class VerletListInteractionTemplate< LennardJonesAutoBonds > espressopp::interaction::VerletListLennardJonesAutoBonds
Definition at line 35 of file LennardJonesAutoBonds.cpp.
VerletListLennardJonesCapped
typedef class VerletListInteractionTemplate< LennardJonesCapped > espressopp::interaction::VerletListLennardJonesCapped
Definition at line 35 of file LennardJonesCapped.cpp.
VerletListLennardJonesEnergyCapped
typedef class VerletListInteractionTemplate< LennardJonesEnergyCapped > espressopp::interaction::VerletListLennardJonesEnergyCapped
Definition at line 35 of file LennardJonesEnergyCapped.cpp.
VerletListLennardJonesExpand
typedef class VerletListInteractionTemplate< LennardJonesExpand > espressopp::interaction::VerletListLennardJonesExpand
Definition at line 31 of file LennardJonesExpand.cpp.
VerletListLennardJonesGeneric
typedef class VerletListInteractionTemplate< LennardJonesGeneric > espressopp::interaction::VerletListLennardJonesGeneric
Definition at line 35 of file LennardJonesGeneric.cpp.
VerletListLennardJonesGromacs
typedef class VerletListInteractionTemplate< LennardJonesGromacs > espressopp::interaction::VerletListLennardJonesGromacs
Definition at line 31 of file LennardJonesGromacs.cpp.
VerletListLennardJonesSoftcoreTI
typedef class VerletListInteractionTemplate< LennardJonesSoftcoreTI > espressopp::interaction::VerletListLennardJonesSoftcoreTI
Definition at line 35 of file LennardJonesSoftcoreTI.cpp.
VerletListLJcos
typedef class VerletListInteractionTemplate< LJcos > espressopp::interaction::VerletListLJcos
Definition at line 33 of file LJcos.cpp.
VerletListMorse
typedef class VerletListInteractionTemplate< Morse > espressopp::interaction::VerletListMorse
Definition at line 34 of file Morse.cpp.
VerletListPIadressNoDriftTabulated
typedef class VerletListPIadressNoDriftInteractionTemplate< Tabulated > espressopp::interaction::VerletListPIadressNoDriftTabulated
Definition at line 76 of file Tabulated.cpp.
VerletListPIadressTabulated
typedef class VerletListPIadressInteractionTemplate< Tabulated, Tabulated > espressopp::interaction::VerletListPIadressTabulated
Definition at line 74 of file Tabulated.cpp.
VerletListPIadressTabulatedLJ
typedef class VerletListPIadressInteractionTemplate< Tabulated, LennardJones > espressopp::interaction::VerletListPIadressTabulatedLJ
Definition at line 75 of file Tabulated.cpp.
VerletListReactionFieldGeneralized
typedef class VerletListInteractionTemplate< ReactionFieldGeneralized > espressopp::interaction::VerletListReactionFieldGeneralized
Definition at line 37 of file ReactionFieldGeneralized.cpp.
VerletListSmoothSquareWell
typedef class VerletListInteractionTemplate< SmoothSquareWell > espressopp::interaction::VerletListSmoothSquareWell
Definition at line 30 of file SmoothSquareWell.cpp.
VerletListSoftCosine
typedef class VerletListInteractionTemplate< SoftCosine > espressopp::interaction::VerletListSoftCosine
Definition at line 31 of file SoftCosine.cpp.
VerletListStillingerWeberPairTerm
typedef class VerletListInteractionTemplate< StillingerWeberPairTerm > espressopp::interaction::VerletListStillingerWeberPairTerm
Definition at line 30 of file StillingerWeberPairTerm.cpp.
VerletListStillingerWeberPairTermCapped
typedef class VerletListInteractionTemplate< StillingerWeberPairTermCapped > espressopp::interaction::VerletListStillingerWeberPairTermCapped
Definition at line 30 of file StillingerWeberPairTermCapped.cpp.
VerletListStillingerWeberTripleTerm
typedef class VerletListTripleInteractionTemplate< StillingerWeberTripleTerm > espressopp::interaction::VerletListStillingerWeberTripleTerm
Definition at line 34 of file StillingerWeberTripleTerm.cpp.
VerletListTabulated
typedef class VerletListInteractionTemplate< Tabulated > espressopp::interaction::VerletListTabulated
Definition at line 69 of file Tabulated.cpp.
VerletListTabulatedSubEns
typedef class VerletListInteractionTemplate< TabulatedSubEns > espressopp::interaction::VerletListTabulatedSubEns
Definition at line 231 of file TabulatedSubEns.cpp.
VerletListTersoffPairTerm
typedef class VerletListInteractionTemplate< TersoffPairTerm > espressopp::interaction::VerletListTersoffPairTerm
Definition at line 30 of file TersoffPairTerm.cpp.
VerletListTersoffTripleTerm
typedef class VerletListTripleInteractionTemplate< TersoffTripleTerm > espressopp::interaction::VerletListTersoffTripleTerm
Definition at line 34 of file TersoffTripleTerm.cpp.
VerletListVSpherePair
typedef class VerletListVSphereInteractionTemplate< VSpherePair > espressopp::interaction::VerletListVSpherePair
Definition at line 31 of file VSpherePair.cpp.
VerletListZero
typedef class VerletListInteractionTemplate< Zero > espressopp::interaction::VerletListZero
Definition at line 35 of file Zero.cpp.
Enumeration Type Documentation
bondTypes
enum espressopp::interaction::bondTypes
Enumerator
unused
Nonbonded
Single
Pair
Angular
Dihedral
NonbondedSlow
Definition at line 34 of file Interaction.hpp.
Function Documentation
LOG4ESPP_LOGGER() [1/13]
espressopp::interaction::LOG4ESPP_LOGGER (Interaction::theLogger , "Interaction")
LOG4ESPP_LOGGER() [2/13]
espressopp::interaction::LOG4ESPP_LOGGER (AngularPotential::theLogger , "AngularPotential")
Referenced by espressopp::interaction::DihedralPotential::computePhi().
LOG4ESPP_LOGGER() [3/13]
espressopp::interaction::LOG4ESPP_LOGGER (PotentialVSpherePair::theLogger , "PotentialVSpherePair")
LOG4ESPP_LOGGER() [4/13]
espressopp::interaction::LOG4ESPP_LOGGER (InterpolationLinear::theLogger , "InterpolationLinear")
LOG4ESPP_LOGGER() [5/13]
espressopp::interaction::LOG4ESPP_LOGGER (InterpolationTable::theLogger , "InterpolationTable")
LOG4ESPP_LOGGER() [6/13]
espressopp::interaction::LOG4ESPP_LOGGER (FENE::theLogger , "FENE")
LOG4ESPP_LOGGER() [7/13]
espressopp::interaction::LOG4ESPP_LOGGER (InterpolationAkima::theLogger , "InterpolationAkima")
LOG4ESPP_LOGGER() [8/13]
espressopp::interaction::LOG4ESPP_LOGGER (Potential::theLogger , "Potential")
LOG4ESPP_LOGGER() [9/13]
espressopp::interaction::LOG4ESPP_LOGGER (InterpolationCubic::theLogger , "InterpolationCubic")
LOG4ESPP_LOGGER() [10/13]
espressopp::interaction::LOG4ESPP_LOGGER (SingleParticlePotential::theLogger , "SingleParticlePotential")
LOG4ESPP_LOGGER() [11/13]
espressopp::interaction::LOG4ESPP_LOGGER (LennardJonesGeneric::theLogger , "LennardJonesGeneric")
LOG4ESPP_LOGGER() [12/13]
espressopp::interaction::LOG4ESPP_LOGGER (DihedralPotential::theLogger , "DihedralPotential")
LOG4ESPP_LOGGER() [13/13]
espressopp::interaction::LOG4ESPP_LOGGER (LennardJones::theLogger , "LennardJones")
registerPython()
void espressopp::interaction::registerPython ()
Definition at line 88 of file bindings.cpp.
References espressopp::interaction::Zero::registerPython(), espressopp::interaction::LennardJonesExpand::registerPython(), espressopp::interaction::CoulombTruncatedUniqueCharge::registerPython(), espressopp::interaction::FENE::registerPython(), espressopp::interaction::CoulombTruncated::registerPython(), espressopp::interaction::GravityTruncated::registerPython(), espressopp::interaction::DihedralHarmonicCos::registerPython(), espressopp::interaction::Quartic::registerPython(), espressopp::interaction::TabulatedAngular::registerPython(), espressopp::interaction::AngularHarmonic::registerPython(), espressopp::interaction::DihedralRB::registerPython(), espressopp::interaction::Harmonic::registerPython(), espressopp::interaction::AngularCosineSquared::registerPython(), espressopp::interaction::SoftCosine::registerPython(), espressopp::interaction::OPLS::registerPython(), espressopp::interaction::Morse::registerPython(), espressopp::interaction::Cosine::registerPython(), espressopp::interaction::TabulatedDihedral::registerPython(), espressopp::interaction::LJcos::registerPython(), espressopp::interaction::SmoothSquareWell::registerPython(), espressopp::interaction::HarmonicTrap::registerPython(), espressopp::interaction::FENECapped::registerPython(), espressopp::interaction::LennardJonesGeneric::registerPython(), espressopp::interaction::LennardJonesCapped::registerPython(), espressopp::interaction::SingleParticlePotential::registerPython(), espressopp::interaction::LennardJones::registerPython(), espressopp::interaction::ConstrainRG::registerPython(), espressopp::interaction::LennardJonesEnergyCapped::registerPython(), espressopp::interaction::CoulombRSpace::registerPython(), espressopp::interaction::ConstrainCOM::registerPython(), espressopp::interaction::LennardJonesAutoBonds::registerPython(), espressopp::interaction::StillingerWeberPairTerm::registerPython(), espressopp::interaction::Tabulated::registerPython(), espressopp::interaction::StillingerWeberPairTermCapped::registerPython(), espressopp::interaction::TersoffPairTerm::registerPython(), espressopp::interaction::PotentialVSpherePair::registerPython(), espressopp::interaction::DihedralHarmonic::registerPython(), espressopp::interaction::LennardJonesGromacs::registerPython(), espressopp::interaction::VSphereSelf::registerPython(), espressopp::interaction::MirrorLennardJones::registerPython(), espressopp::interaction::StillingerWeberTripleTerm::registerPython(), espressopp::interaction::VSpherePair::registerPython(), espressopp::interaction::DihedralHarmonicNCos::registerPython(), espressopp::interaction::TabulatedSubEnsDihedral::registerPython(), espressopp::interaction::LennardJones93Wall::registerPython(), espressopp::interaction::TabulatedSubEnsAngular::registerPython(), espressopp::interaction::Interaction::registerPython(), espressopp::interaction::TersoffTripleTerm::registerPython(), espressopp::interaction::TabulatedSubEns::registerPython(), espressopp::interaction::ReactionFieldGeneralized::registerPython(), espressopp::interaction::Potential::registerPython(), espressopp::interaction::AngularPotential::registerPython(), espressopp::interaction::ReactionFieldGeneralizedTI::registerPython(), espressopp::interaction::DihedralPotential::registerPython(), espressopp::interaction::LennardJonesSoftcoreTI::registerPython(), espressopp::interaction::CoulombKSpaceEwald::registerPython(), and espressopp::interaction::CoulombKSpaceP3M::registerPython().
Referenced by espressopp::registerPython().