ESPResSo++: espressopp::esutil Namespace Reference
espressopp::esutil Namespace Reference
Namespaces
Collectives
Classes
class Array2D
A two-dimensional array (i.e.
class Array2D< T, enlarge >
class Array3D
A three-dimensional array (i.e.
class Array3D< T, enlarge >
class Array4D
A four-dimensional array (i.e.
class Array4D< T, enlarge >
class Error
This class supports exception handling for MPI processors.
class ESPPContainer
class ESPPIterator
class GammaVariate
This class generates gamma distributed random variates.
class Grid
regular grid decomposition of a box, outside view.
class NormalVariate
This class generates normal distributed random variates.
class RNG
class Timer
simple timer for obtaining typically microsecond precision timings.
class UniformOnSphere
This class generates random vectors that are uniformly distributed on a sphere.
class UserTimer
timer measuring the user time.
class WallTimer
timer measuring the wall time.
Enumerations
enum OutlierMode { exception, enlarge }
Functions
void registerPython ()
static void printStackTrace (std::stringstream &msg, unsigned int max_frames)
Print Stack.
real getDist (real dist[3], const real p[3], const real q[3])
std::ostream & operator<< (std::ostream &os, const Timer &timer)
when printing give the current elapsed time
real distance2vec (real pos1[3], real pos2[3], real vec[3])
Returns the distance between two positions squared and stores the distance vector pos1-pos2 in vec.
Variables
void(Grid::* mapIndexToPositionInt3D)(Int3D &, longint) const = &Grid::mapIndexToPosition
Enumeration Type Documentation
OutlierMode
enum espressopp::esutil::OutlierMode
Enumerator
exception
enlarge
Definition at line 30 of file Array2D.hpp.
Function Documentation
distance2vec()
real espressopp::esutil::distance2vec (real pos1[3], real pos2[3], real vec[3]) inline
Returns the distance between two positions squared and stores the distance vector pos1-pos2 in vec.
Parameters
pos1 Position one.
pos2 Position two.
vec vecotr pos1-pos2.
Returns
distance squared
Definition at line 39 of file Utils.hpp.
getDist()
real espressopp::esutil::getDist (real dist[3], const real p[3], const real q[3])
Definition at line 28 of file Math.hpp.
operator<<()
std::ostream& espressopp::esutil::operator<< (std::ostream & os, const Timer & timer) inline
when printing give the current elapsed time
Definition at line 52 of file Timer.hpp.
References espressopp::esutil::Timer::getElapsedTime().
printStackTrace()
static void espressopp::esutil::printStackTrace (std::stringstream & msg, unsigned int max_frames) inline static
Print Stack.
Definition at line 35 of file Error.hpp.
registerPython()
void espressopp::esutil::registerPython ()
Definition at line 34 of file bindings.cpp.
References espressopp::esutil::UniformOnSphere::registerPython(), espressopp::esutil::NormalVariate::registerPython(), espressopp::esutil::GammaVariate::registerPython(), espressopp::esutil::Collectives::registerPython(), espressopp::esutil::Grid::registerPython(), and espressopp::esutil::RNG::registerPython().
Referenced by espressopp::esutil::RNG::gammaOf1(), espressopp::System::getShared(), and espressopp::registerPython().
Variable Documentation
mapIndexToPositionInt3D
void(Grid::* espressopp::esutil::mapIndexToPositionInt3D) (Int3D &, longint) const = &Grid::mapIndexToPosition
Definition at line 33 of file Grid.cpp.
Referenced by espressopp::esutil::Grid::registerPython().