ESPResSo++: espressopp::interaction::ReactionFieldGeneralized_pickle Struct Reference
espressopp::interaction::ReactionFieldGeneralized_pickle Struct Reference
#include <ReactionFieldGeneralized.hpp>
Static Public Member Functions
static boost::python::tuple getinitargs (ReactionFieldGeneralized const &pot)
Detailed Description
Definition at line 228 of file ReactionFieldGeneralized.hpp.
Member Function Documentation
getinitargs()
static boost::python::tuple espressopp::interaction::ReactionFieldGeneralized_pickle::getinitargs (ReactionFieldGeneralized const & pot) inline static
Definition at line 232 of file ReactionFieldGeneralized.hpp.
References espressopp::interaction::PotentialTemplate< Derived >::getCutoff(), espressopp::interaction::ReactionFieldGeneralized::getEpsilon1(), espressopp::interaction::ReactionFieldGeneralized::getEpsilon2(), espressopp::interaction::ReactionFieldGeneralized::getKappa(), espressopp::interaction::ReactionFieldGeneralized::getPrefactor(), and espressopp::interaction::PotentialTemplate< Derived >::getShift().
The documentation for this struct was generated from the following file:
/home/espressopp/espressopp/src/interaction/ReactionFieldGeneralized.hpp