ESPResSo++: espressopp::interaction::LennardJonesCapped_pickle Struct Reference
espressopp::interaction::LennardJonesCapped_pickle Struct Reference
#include <LennardJonesCapped.hpp>
Static Public Member Functions
static boost::python::tuple getinitargs (LennardJonesCapped const &pot)
Detailed Description
Definition at line 159 of file LennardJonesCapped.hpp.
Member Function Documentation
getinitargs()
static boost::python::tuple espressopp::interaction::LennardJonesCapped_pickle::getinitargs (LennardJonesCapped const & pot) inline static
Definition at line 163 of file LennardJonesCapped.hpp.
References espressopp::interaction::PotentialTemplate< Derived >::getCutoff(), espressopp::interaction::LennardJonesCapped::getEpsilon(), espressopp::interaction::PotentialTemplate< Derived >::getShift(), and espressopp::interaction::LennardJonesCapped::getSigma().
The documentation for this struct was generated from the following file:
/home/espressopp/espressopp/src/interaction/LennardJonesCapped.hpp