ESPResSo++: espressopp::Particle Struct Reference
espressopp::Particle Struct Reference
#include <Particle.hpp>
Public Types
enum ExtraDataElements { DATA_PROPERTIES =1, DATA_MOMENTUM =2, DATA_LOCAL =4 }
bitmask: which extra data elements to in- or exclude from ghost sending
Public Member Functions
Particle ()
void init ()
size_t & id ()
const size_t & id () const
longint getId () const
size_t & type ()
const size_t & type () const
int getType () const
void setType (int type)
real & mass ()
const real & mass () const
real getMass () const
void setMass (real mass)
real & q ()
const real & q () const
real getQ () const
void setQ (real q)
real & radius ()
const real & radius () const
real getRadius () const
void setRadius (real q)
real & extVar ()
const real & extVar () const
real getExtVar () const
void setExtVar (real q)
Real3D & position ()
const Real3D & position () const
Real3D getPos () const
void setPos (const Real3D &pos)
ParticleForce & particleForce ()
const ParticleForce & particleForce () const
Real3D & force ()
const Real3D & force () const
Real3D getF () const
void setF (const Real3D &force)
real & fradius ()
const real & fradius () const
real getFRadius () const
void setFRadius (const real &fr)
Real3D & velocity ()
const Real3D & velocity () const
Real3D getV () const
void setV (const Real3D &velocity)
real & vradius ()
const real & vradius () const
real getVRadius () const
void setVRadius (const real &vr)
Int3D & image ()
const Int3D & image () const
Int3D getImageBox () const
void setImageBox (const Int3D &img)
bool & ghost ()
const bool & ghost () const
bool getGhostStatus () const
void setGhostStatus (const bool &gs)
real & lambda ()
const real & lambda () const
real getLambda () const
void setLambda (const real &_lambda)
real & drift ()
const real & drift () const
real getDrift () const
void setDrift (const real &_drift)
real & lambdaDeriv ()
const real & lambdaDeriv () const
real getLambdaDeriv () const
void setLambdaDeriv (const real &_lambdaDeriv)
int & state ()
const int & state () const
int getState () const
void setState (const int &_state)
void copyAsGhost (const Particle &src, int extradata, const Real3D &shift)
Static Public Member Functions
static void registerPython ()
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
ParticleProperties p
ParticlePosition r
ParticleMomentum m
ParticleLocal l
ParticleForce f
Friends
class InBuffer
class OutBuffer
class boost::serialization::access
Detailed Description
Definition at line 171 of file Particle.hpp.
Member Enumeration Documentation
enum espressopp::Particle::ExtraDataElements
bitmask: which extra data elements to in- or exclude from ghost sending
Enumerator
DATA_PROPERTIES
DATA_MOMENTUM
DATA_LOCAL
Definition at line 180 of file Particle.hpp.
Constructor & Destructor Documentation
espressopp::Particle::Particle () inline
Definition at line 186 of file Particle.hpp.
References init().
Member Function Documentation
void espressopp::Particle::copyAsGhost (const Particle & src, int extradata, const Real3D & shift) inline
Definition at line 316 of file Particle.hpp.
References espressopp::ParticlePosition::copyShifted(), DATA_LOCAL, DATA_MOMENTUM, DATA_PROPERTIES, ghost(), l, m, p, and r.
Referenced by espressopp::storage::DomainDecompositionAdress::copyGhostTuples().
real& espressopp::Particle::drift () inline
Definition at line 297 of file Particle.hpp.
References espressopp::ParticleProperties::drift, and p.
Referenced by espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::addForces(), and espressopp::integrator::OnTheFlyFEC::gatherStats().
const real& espressopp::Particle::drift () const inline
Definition at line 298 of file Particle.hpp.
References espressopp::ParticleProperties::drift, and p.
real& espressopp::Particle::extVar () inline
Definition at line 234 of file Particle.hpp.
References espressopp::ParticlePosition::extVar, and r.
Referenced by espressopp::integrator::GeneralizedLangevinThermostat::friction(), and espressopp::integrator::GeneralizedLangevinThermostat::integrate().
const real& espressopp::Particle::extVar () const inline
Definition at line 235 of file Particle.hpp.
References espressopp::ParticlePosition::extVar, and r.
Real3D& espressopp::Particle::force () inline
Definition at line 253 of file Particle.hpp.
References espressopp::ParticleForce::f, and f.
Referenced by espressopp::interaction::CoulombKSpaceEwald::_computeForce(), espressopp::interaction::CoulombKSpaceP3M::_computeForce(), espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::addForces(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::VerletListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::addForces(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::addForces(), espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LangevinBarostat::frictionBarostat(), espressopp::integrator::LangevinThermostatOnGroup::frictionThermo(), espressopp::integrator::LangevinThermostat1D::frictionThermo(), espressopp::integrator::LangevinThermostat::frictionThermo(), espressopp::integrator::LangevinThermostatHybrid::frictionThermo(), espressopp::integrator::DPDThermostat::frictionThermoDPD(), espressopp::integrator::DPDThermostat::frictionThermoTDPD(), and setF().
const Real3D& espressopp::Particle::force () const inline
Definition at line 254 of file Particle.hpp.
References espressopp::ParticleForce::f, and f.
real& espressopp::Particle::fradius () inline
Definition at line 259 of file Particle.hpp.
References f, and espressopp::ParticleForce::fradius.
Referenced by espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::addForces().
const real& espressopp::Particle::fradius () const inline
Definition at line 260 of file Particle.hpp.
References f, and espressopp::ParticleForce::fradius.
real espressopp::Particle::getDrift () const inline
Definition at line 299 of file Particle.hpp.
References espressopp::ParticleProperties::drift, and p.
Referenced by registerPython().
real espressopp::Particle::getExtVar () const inline
Definition at line 236 of file Particle.hpp.
References espressopp::ParticlePosition::extVar, and r.
Referenced by registerPython().
Real3D espressopp::Particle::getF () const inline
Definition at line 256 of file Particle.hpp.
References espressopp::ParticleForce::f, and f.
Referenced by registerPython().
real espressopp::Particle::getFRadius () const inline
Definition at line 262 of file Particle.hpp.
References f, and espressopp::ParticleForce::fradius.
Referenced by registerPython().
bool espressopp::Particle::getGhostStatus () const inline
Definition at line 287 of file Particle.hpp.
References espressopp::ParticleLocal::ghost, and l.
Referenced by registerPython().
longint espressopp::Particle::getId () const inline
Definition at line 210 of file Particle.hpp.
References espressopp::ParticleProperties::id, and p.
Referenced by espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), and registerPython().
Int3D espressopp::Particle::getImageBox () const inline
Definition at line 282 of file Particle.hpp.
References espressopp::ParticleLocal::i, and l.
Referenced by registerPython().
real espressopp::Particle::getLambda () const inline
Definition at line 293 of file Particle.hpp.
References espressopp::ParticleProperties::lambda, and p.
Referenced by registerPython().
real espressopp::Particle::getLambdaDeriv () const inline
Definition at line 305 of file Particle.hpp.
References espressopp::ParticleProperties::lambdaDeriv, and p.
Referenced by registerPython().
real espressopp::Particle::getMass () const inline
Definition at line 219 of file Particle.hpp.
References espressopp::ParticleProperties::mass, and p.
Referenced by espressopp::integrator::Adress::aftCalcF(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeEnergy(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialX(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialX(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::Adress::integrate2(), registerPython(), and espressopp::integrator::Adress::SetPosVel().
Real3D espressopp::Particle::getPos () const inline
Definition at line 243 of file Particle.hpp.
References espressopp::ParticlePosition::p, and r.
Referenced by registerPython(), espressopp::integrator::Rattle::saveOldPos(), espressopp::integrator::Settle::settlep(), and espressopp::integrator::Settle::settlev().
real espressopp::Particle::getQ () const inline
Definition at line 224 of file Particle.hpp.
References p, and espressopp::ParticleProperties::q.
Referenced by registerPython().
real espressopp::Particle::getRadius () const inline
Definition at line 230 of file Particle.hpp.
References r, and espressopp::ParticlePosition::radius.
Referenced by registerPython().
int espressopp::Particle::getState () const inline
Definition at line 311 of file Particle.hpp.
References p, and espressopp::ParticleProperties::state.
Referenced by espressopp::integrator::AssociationReaction::applyAR(), and registerPython().
int espressopp::Particle::getType () const inline
Definition at line 214 of file Particle.hpp.
References p, and espressopp::ParticleProperties::type.
Referenced by registerPython().
Real3D espressopp::Particle::getV () const inline
Definition at line 269 of file Particle.hpp.
References m, and espressopp::ParticleMomentum::v.
Referenced by registerPython(), and espressopp::integrator::Settle::settlev().
real espressopp::Particle::getVRadius () const inline
Definition at line 275 of file Particle.hpp.
References m, and espressopp::ParticleMomentum::vradius.
Referenced by registerPython().
bool& espressopp::Particle::ghost () inline
Definition at line 285 of file Particle.hpp.
References espressopp::ParticleLocal::ghost, and l.
Referenced by espressopp::interaction::LennardJonesAutoBonds::_computeForce(), espressopp::storage::DomainDecompositionAdress::addAdrGhostForcesToReals(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::addForces(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::addForces(), espressopp::integrator::Adress::aftCalcF(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeEnergy(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirial(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialX(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialX(), copyAsGhost(), espressopp::storage::DomainDecompositionAdress::copyGhostTuples(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::Adress::integrate2(), espressopp::storage::DomainDecompositionAdress::invalidateGhosts(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::AssociationReaction::uniqueA(), espressopp::integrator::AssociationReaction::uniqueB(), and espressopp::storage::DomainDecompositionAdress::unpackPositionsEtc().
const bool& espressopp::Particle::ghost () const inline
Definition at line 286 of file Particle.hpp.
References espressopp::ParticleLocal::ghost, and l.
size_t& espressopp::Particle::id () inline
Definition at line 208 of file Particle.hpp.
References espressopp::ParticleProperties::id, and p.
Referenced by espressopp::interaction::LennardJonesSoftcoreTI::_computeEnergy(), espressopp::interaction::ReactionFieldGeneralizedTI::_computeEnergy(), espressopp::interaction::ReactionFieldGeneralizedTI::_computeEnergyDeriv(), espressopp::interaction::LennardJonesSoftcoreTI::_computeEnergyDeriv(), espressopp::interaction::ReactionFieldGeneralizedTI::_computeForce(), espressopp::interaction::LennardJonesSoftcoreTI::_computeForce(), espressopp::interaction::LennardJonesAutoBonds::_computeForce(), espressopp::interaction::CoulombKSpaceP3M::_computeForce(), espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::DomainDecompositionAdress::addAdrGhostForcesToReals(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::addForces(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::addForces(), espressopp::storage::Storage::addParticle(), espressopp::integrator::Adress::aftCalcF(), espressopp::FixedTupleList::afterRecvParticles(), espressopp::FixedTupleListAdress::afterRecvParticles(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::analysis::OrderParameter::biggest_cluster(), espressopp::integrator::LatticeBoltzmann::calcRandForce(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::VerletList::checkPair(), espressopp::VerletListAdress::checkPair(), espressopp::VerletListTriple::checkTriple(), espressopp::interaction::CoulombKSpaceP3M::common_part(), espressopp::analysis::AdressDensity::computeArray(), espressopp::analysis::RDFatomistic::computeArray(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeEnergy(), espressopp::analysis::OrderParameter::computeRaw(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirial(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialX(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialX(), espressopp::storage::DomainDecompositionAdress::copyGhostTuples(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::analysis::OrderParameter::define_solid(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::analysis::ConfigurationsExtAdress::gather(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::Adress::integrate2(), espressopp::analysis::OrderParameter::local_cluster_search(), espressopp::integrator::AssociationReaction::reactPair(), espressopp::storage::Storage::removeFromLocalParticles(), espressopp::storage::Storage::removeParticle(), espressopp::integrator::Adress::SetPosVel(), espressopp::storage::Storage::updateInLocalAdrATParticles(), and espressopp::storage::Storage::updateInLocalParticles().
const size_t& espressopp::Particle::id () const inline
Definition at line 209 of file Particle.hpp.
References espressopp::ParticleProperties::id, and p.
Int3D& espressopp::Particle::image () inline
Definition at line 280 of file Particle.hpp.
References espressopp::ParticleLocal::i, and l.
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::analysis::ConfigurationsExtAdress::gather(), espressopp::FixedTupleListAdress::onParticlesChanged(), espressopp::storage::Storage::restorePositions(), and espressopp::storage::Storage::savePosition().
const Int3D& espressopp::Particle::image () const inline
Definition at line 281 of file Particle.hpp.
References espressopp::ParticleLocal::i, and l.
void espressopp::Particle::init () inline
Definition at line 188 of file Particle.hpp.
References espressopp::ParticleProperties::drift, espressopp::ParticlePosition::extVar, f, espressopp::ParticleForce::fradius, espressopp::ParticleLocal::ghost, l, espressopp::ParticleProperties::lambda, espressopp::ParticleProperties::lambdaDeriv, m, espressopp::ParticleProperties::mass, p, espressopp::ParticleProperties::q, r, espressopp::ParticlePosition::radius, espressopp::ParticleProperties::state, espressopp::ParticleProperties::type, espressopp::ParticleMomentum::v, and espressopp::ParticleMomentum::vradius.
Referenced by espressopp::storage::Storage::addAdrATParticle(), espressopp::storage::Storage::addParticle(), and Particle().
real& espressopp::Particle::lambda () inline
Definition at line 291 of file Particle.hpp.
References espressopp::ParticleProperties::lambda, and p.
Referenced by espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::addForces(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::addForces(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::analysis::RDFatomistic::computeArray(), espressopp::integrator::FreeEnergyCompensation::computeCompEnergy(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeEnergy(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeEnergy(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeEnergyDeriv(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirial(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialX(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialX(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::Adress::SetPosVel(), and espressopp::integrator::LangevinThermostatHybrid::thermalizeAdr().
const real& espressopp::Particle::lambda () const inline
Definition at line 292 of file Particle.hpp.
References espressopp::ParticleProperties::lambda, and p.
real& espressopp::Particle::lambdaDeriv () inline
Definition at line 303 of file Particle.hpp.
References espressopp::ParticleProperties::lambdaDeriv, and p.
Referenced by espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::addForces(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::Adress::integrate1(), and espressopp::integrator::Adress::SetPosVel().
const real& espressopp::Particle::lambdaDeriv () const inline
Definition at line 304 of file Particle.hpp.
References espressopp::ParticleProperties::lambdaDeriv, and p.
real& espressopp::Particle::mass () inline
Definition at line 217 of file Particle.hpp.
References espressopp::ParticleProperties::mass, and p.
Referenced by espressopp::interaction::GravityTruncated::_computeEnergy(), espressopp::interaction::GravityTruncated::_computeForce(), espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::analysis::Pressure::compute(), espressopp::analysis::XPressure::computeArray(), espressopp::analysis::XTemperature::computeArray(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeEnergy(), espressopp::analysis::Temperature::computeRaw(), espressopp::analysis::CenterOfMass::computeVector(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialX(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialX(), espressopp::integrator::GeneralizedLangevinThermostat::friction(), espressopp::integrator::LangevinBarostat::frictionBarostat(), espressopp::integrator::LangevinThermostatOnGroup::frictionThermo(), espressopp::integrator::LangevinThermostat1D::frictionThermo(), espressopp::integrator::LangevinThermostat::frictionThermo(), espressopp::integrator::LangevinThermostatHybrid::frictionThermo(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::Adress::integrate2(), setMass(), espressopp::integrator::Adress::SetPosVel(), and espressopp::integrator::LangevinBarostat::updVolumeMomentum().
const real& espressopp::Particle::mass () const inline
Definition at line 218 of file Particle.hpp.
References espressopp::ParticleProperties::mass, and p.
ParticleForce& espressopp::Particle::particleForce () inline
Definition at line 248 of file Particle.hpp.
References f.
Referenced by espressopp::storage::DomainDecompositionAdress::addAdrGhostForcesToReals(), espressopp::storage::DomainDecompositionAdress::packForces(), and espressopp::storage::DomainDecompositionAdress::unpackAndAddForces().
const ParticleForce& espressopp::Particle::particleForce () const inline
Definition at line 249 of file Particle.hpp.
References f.
Real3D& espressopp::Particle::position () inline
Definition at line 241 of file Particle.hpp.
References espressopp::ParticlePosition::p, and r.
Referenced by espressopp::interaction::CoulombTruncated::_computeEnergy(), espressopp::interaction::GravityTruncated::_computeEnergy(), espressopp::interaction::AngularUniquePotentialTemplate< Derived >::_computeEnergy(), espressopp::interaction::CoulombRSpace::_computeEnergy(), espressopp::interaction::AngularPotentialTemplate< Derived >::_computeEnergy(), espressopp::interaction::PotentialTemplate< Derived >::_computeEnergy(), espressopp::interaction::PotentialUniqueDistTemplate< Derived >::_computeEnergy(), espressopp::interaction::PotentialVSpherePairTemplate< Derived >::_computeEnergy(), espressopp::interaction::ReactionFieldGeneralized::_computeEnergy(), espressopp::interaction::LennardJonesSoftcoreTI::_computeEnergy(), espressopp::interaction::LennardJonesAutoBonds::_computeEnergy(), espressopp::interaction::ReactionFieldGeneralizedTI::_computeEnergy(), espressopp::interaction::ReactionFieldGeneralizedTI::_computeEnergyDeriv(), espressopp::interaction::LennardJonesSoftcoreTI::_computeEnergyDeriv(), espressopp::interaction::HarmonicTrap::_computeEnergyRaw(), espressopp::interaction::LennardJones93Wall::_computeEnergyRaw(), espressopp::interaction::GravityTruncated::_computeForce(), espressopp::interaction::CoulombTruncated::_computeForce(), espressopp::interaction::AngularUniquePotentialTemplate< Derived >::_computeForce(), espressopp::interaction::CoulombRSpace::_computeForce(), espressopp::interaction::AngularPotentialTemplate< Derived >::_computeForce(), espressopp::interaction::PotentialUniqueDistTemplate< Derived >::_computeForce(), espressopp::interaction::PotentialVSpherePairTemplate< Derived >::_computeForce(), espressopp::interaction::PotentialTemplate< Derived >::_computeForce(), espressopp::interaction::ReactionFieldGeneralizedTI::_computeForce(), espressopp::interaction::LennardJonesSoftcoreTI::_computeForce(), espressopp::interaction::ReactionFieldGeneralized::_computeForce(), espressopp::interaction::LennardJonesAutoBonds::_computeForce(), espressopp::interaction::HarmonicTrap::_computeForceRaw(), espressopp::interaction::LennardJones93Wall::_computeForceRaw(), espressopp::FixedPairDistList::add(), espressopp::FixedTripleAngleList::add(), espressopp::FixedQuadrupleAngleList::add(), espressopp::storage::Storage::addAdrATParticle(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::addForces(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::addForces(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::addForces(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::addForces(), espressopp::storage::Storage::addParticle(), espressopp::integrator::Adress::aftCalcF(), espressopp::integrator::FreeEnergyCompensation::applyForce(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::storage::DomainDecompositionAdress::cellAdjust(), espressopp::storage::DomainDecomposition::cellAdjust(), espressopp::VerletList::checkPair(), espressopp::VerletListAdress::checkPair(), espressopp::VerletListTriple::checkTriple(), espressopp::interaction::CoulombKSpaceP3M::common_part(), espressopp::analysis::AdressDensity::computeArray(), espressopp::analysis::RDFatomistic::computeArray(), espressopp::analysis::XDensity::computeArray(), espressopp::analysis::XTemperature::computeArray(), espressopp::interaction::AngularUniquePotentialTemplate< Derived >::computeEnergy(), espressopp::interaction::AngularPotentialTemplate< Derived >::computeEnergy(), espressopp::interaction::PotentialTemplate< Derived >::computeEnergy(), espressopp::interaction::PotentialUniqueDistTemplate< Derived >::computeEnergy(), espressopp::interaction::PotentialVSpherePairTemplate< Derived >::computeEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeEnergy(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::LennardJonesAutoBonds::computeEnergy(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeEnergy(), espressopp::interaction::AngularUniquePotentialTemplate< Derived >::computeForce(), espressopp::interaction::AngularPotentialTemplate< Derived >::computeForce(), espressopp::interaction::PotentialUniqueDistTemplate< Derived >::computeForce(), espressopp::interaction::PotentialTemplate< Derived >::computeForce(), espressopp::interaction::LennardJonesAutoBonds::computeForce(), espressopp::analysis::CenterOfMass::computeVector(), espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::VerletListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirial(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirial(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirial(), espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleAngleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::FixedPairDistListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedPairListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::VerletListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedTripleAngleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleListInteractionTemplate< _AngularPotential >::computeVirialTensor(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialTensor(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialTensor(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialX(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialX(), espressopp::storage::DomainDecompositionAdress::copyGhostTuples(), espressopp::storage::DomainDecompositionNonBlocking::decomposeRealParticles(), espressopp::storage::DomainDecomposition::decomposeRealParticles(), espressopp::storage::DomainDecompositionAdress::decomposeRealParticles(), espressopp::interaction::CoulombKSpaceEwald::exponentPrecalculation(), espressopp::storage::Storage::fetchParticles(), espressopp::integrator::DPDThermostat::frictionThermoDPD(), espressopp::integrator::DPDThermostat::frictionThermoTDPD(), espressopp::analysis::ConfigurationsExtAdress::gather(), espressopp::integrator::OnTheFlyFEC::gatherStats(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::Adress::integrate2(), espressopp::FixedTupleListAdress::onParticlesChanged(), espressopp::integrator::AssociationReaction::reactPair(), espressopp::storage::Storage::removeParticle(), espressopp::storage::Storage::restorePositions(), espressopp::storage::Storage::savePosition(), espressopp::integrator::Adress::SetPosVel(), espressopp::integrator::Settle::settlep(), and espressopp::integrator::LangevinBarostat::updDisplacement().
const Real3D& espressopp::Particle::position () const inline
Definition at line 242 of file Particle.hpp.
References espressopp::ParticlePosition::p, and r.
real& espressopp::Particle::q () inline
Definition at line 222 of file Particle.hpp.
References p, and espressopp::ParticleProperties::q.
Referenced by espressopp::interaction::CoulombTruncated::_computeEnergy(), espressopp::interaction::CoulombRSpace::_computeEnergy(), espressopp::interaction::ReactionFieldGeneralized::_computeEnergy(), espressopp::interaction::ReactionFieldGeneralizedTI::_computeEnergy(), espressopp::interaction::ReactionFieldGeneralizedTI::_computeEnergyDeriv(), espressopp::interaction::CoulombTruncated::_computeForce(), espressopp::interaction::CoulombRSpace::_computeForce(), espressopp::interaction::ReactionFieldGeneralizedTI::_computeForce(), espressopp::interaction::ReactionFieldGeneralized::_computeForce(), espressopp::interaction::CoulombKSpaceEwald::_computeForce(), espressopp::interaction::CoulombKSpaceP3M::common_part(), espressopp::interaction::CoulombKSpaceEwald::count_charges(), espressopp::interaction::CoulombKSpaceP3M::count_charges(), espressopp::interaction::CoulombKSpaceEwald::exponentPrecalculation(), setExtVar(), setQ(), and setRadius().
const real& espressopp::Particle::q () const inline
Definition at line 223 of file Particle.hpp.
References p, and espressopp::ParticleProperties::q.
real& espressopp::Particle::radius () inline
Definition at line 228 of file Particle.hpp.
References r, and espressopp::ParticlePosition::radius.
Referenced by espressopp::interaction::PotentialVSpherePairTemplate< Derived >::_computeEnergy(), espressopp::interaction::PotentialVSpherePairTemplate< Derived >::_computeForce(), and espressopp::interaction::PotentialVSpherePairTemplate< Derived >::computeEnergy().
const real& espressopp::Particle::radius () const inline
Definition at line 229 of file Particle.hpp.
References r, and espressopp::ParticlePosition::radius.
void espressopp::Particle::registerPython () static
Definition at line 29 of file Particle.cpp.
References getDrift(), getExtVar(), getF(), getFRadius(), getGhostStatus(), getId(), getImageBox(), getLambda(), getLambdaDeriv(), getMass(), getPos(), getQ(), getRadius(), getState(), getType(), getV(), getVRadius(), setDrift(), setExtVar(), setF(), setFRadius(), setGhostStatus(), setImageBox(), setLambda(), setLambdaDeriv(), setMass(), setPos(), setQ(), setRadius(), setState(), setType(), setV(), and setVRadius().
Referenced by espressopp::registerPython().
template<class Archive > void espressopp::Particle::serialize (Archive & ar, const unsigned int version) inline private
Definition at line 340 of file Particle.hpp.
References f, l, m, p, and r.
void espressopp::Particle::setDrift (const real & _drift) inline
Definition at line 300 of file Particle.hpp.
References espressopp::ParticleProperties::drift, and p.
Referenced by registerPython().
void espressopp::Particle::setExtVar (real q) inline
Definition at line 237 of file Particle.hpp.
References espressopp::ParticlePosition::extVar, q(), and r.
Referenced by registerPython().
void espressopp::Particle::setF (const Real3D & force) inline
Definition at line 257 of file Particle.hpp.
References espressopp::ParticleForce::f, f, and force().
Referenced by registerPython().
void espressopp::Particle::setFRadius (const real & fr) inline
Definition at line 263 of file Particle.hpp.
References f, and espressopp::ParticleForce::fradius.
Referenced by registerPython().
void espressopp::Particle::setGhostStatus (const bool & gs) inline
Definition at line 288 of file Particle.hpp.
References espressopp::ParticleLocal::ghost, and l.
Referenced by registerPython().
void espressopp::Particle::setImageBox (const Int3D & img) inline
Definition at line 283 of file Particle.hpp.
References espressopp::ParticleLocal::i, and l.
Referenced by registerPython().
void espressopp::Particle::setLambda (const real & _lambda) inline
Definition at line 294 of file Particle.hpp.
References espressopp::ParticleProperties::lambda, and p.
Referenced by registerPython().
void espressopp::Particle::setLambdaDeriv (const real & _lambdaDeriv) inline
Definition at line 306 of file Particle.hpp.
References espressopp::ParticleProperties::lambdaDeriv, and p.
Referenced by registerPython().
void espressopp::Particle::setMass (real mass) inline
Definition at line 220 of file Particle.hpp.
References espressopp::ParticleProperties::mass, mass(), and p.
Referenced by registerPython().
void espressopp::Particle::setPos (const Real3D & pos) inline
Definition at line 244 of file Particle.hpp.
References espressopp::ParticlePosition::p, and r.
Referenced by registerPython().
void espressopp::Particle::setQ (real q) inline
Definition at line 225 of file Particle.hpp.
References p, espressopp::ParticleProperties::q, and q().
Referenced by registerPython().
void espressopp::Particle::setRadius (real q) inline
Definition at line 231 of file Particle.hpp.
References q(), r, and espressopp::ParticlePosition::radius.
Referenced by registerPython().
void espressopp::Particle::setState (const int & _state) inline
Definition at line 312 of file Particle.hpp.
References p, and espressopp::ParticleProperties::state.
Referenced by espressopp::integrator::AssociationReaction::applyAR(), and registerPython().
void espressopp::Particle::setType (int type) inline
Definition at line 215 of file Particle.hpp.
References p, espressopp::ParticleProperties::type, and type().
Referenced by registerPython().
void espressopp::Particle::setV (const Real3D & velocity) inline
Definition at line 270 of file Particle.hpp.
References m, espressopp::ParticleMomentum::v, and velocity().
Referenced by registerPython(), espressopp::integrator::Settle::settlep(), and espressopp::integrator::Settle::settlev().
void espressopp::Particle::setVRadius (const real & vr) inline
Definition at line 276 of file Particle.hpp.
References m, and espressopp::ParticleMomentum::vradius.
Referenced by registerPython().
int& espressopp::Particle::state () inline
Definition at line 309 of file Particle.hpp.
References p, and espressopp::ParticleProperties::state.
Referenced by espressopp::integrator::AssociationReaction::reactPair().
const int& espressopp::Particle::state () const inline
Definition at line 310 of file Particle.hpp.
References p, and espressopp::ParticleProperties::state.
size_t& espressopp::Particle::type () inline
Definition at line 212 of file Particle.hpp.
References p, and espressopp::ParticleProperties::type.
Referenced by espressopp::interaction::LennardJones93Wall::_computeEnergyRaw(), espressopp::interaction::LennardJones93Wall::_computeForceRaw(), espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::addForces(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::addForces(), espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListInteractionTemplate< _Potential >::addForces(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::addForces(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::addForces(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::addForces(), espressopp::analysis::RDFatomistic::computeArray(), espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeEnergy(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeEnergy(), espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeEnergy(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeEnergy(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeEnergy(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeEnergyAA(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeEnergyCG(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeEnergyDeriv(), espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirial(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirial(), espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::FixedPairListTypesInteractionTemplate< _Potential >::computeVirial(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirial(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirial(), espressopp::interaction::CellListAllPairsInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::VerletListTripleInteractionTemplate< _ThreeBodyPotential >::computeVirialTensor(), espressopp::interaction::FixedTripleListTypesInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::FixedQuadrupleListTypesInteractionTemplate< _DihedralPotential >::computeVirialTensor(), espressopp::interaction::VerletListVSphereInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::VerletListInteractionTemplate< _Potential >::computeVirialTensor(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialTensor(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialTensor(), espressopp::interaction::VerletListHadressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialX(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialX(), espressopp::integrator::AssociationReaction::reactPair(), and setType().
const size_t& espressopp::Particle::type () const inline
Definition at line 213 of file Particle.hpp.
References p, and espressopp::ParticleProperties::type.
Real3D& espressopp::Particle::velocity () inline
Definition at line 267 of file Particle.hpp.
References m, and espressopp::ParticleMomentum::v.
Referenced by espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::addForces(), espressopp::integrator::Rattle::applyPositionConstraints(), espressopp::integrator::Rattle::applyVelocityConstraints(), espressopp::integrator::LatticeBoltzmann::calcViscForce(), espressopp::analysis::Pressure::compute(), espressopp::analysis::XPressure::computeArray(), espressopp::analysis::XTemperature::computeArray(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeEnergy(), espressopp::analysis::Temperature::computeRaw(), espressopp::interaction::VerletListAdressInteractionTemplate< _PotentialAT, _PotentialCG >::computeVirialX(), espressopp::integrator::LangevinBarostat::frictionBarostat(), espressopp::integrator::LangevinThermostatOnGroup::frictionThermo(), espressopp::integrator::LangevinThermostat1D::frictionThermo(), espressopp::integrator::LangevinThermostat::frictionThermo(), espressopp::integrator::LangevinThermostatHybrid::frictionThermo(), espressopp::integrator::DPDThermostat::frictionThermoDPD(), espressopp::integrator::DPDThermostat::frictionThermoTDPD(), espressopp::analysis::ConfigurationsExtAdress::gather(), espressopp::integrator::GeneralizedLangevinThermostat::integrate(), espressopp::integrator::Adress::integrate1(), espressopp::integrator::Adress::integrate2(), espressopp::integrator::BerendsenThermostat::scaleVelocity(), espressopp::integrator::Adress::SetPosVel(), setV(), and espressopp::integrator::LangevinBarostat::updVolumeMomentum().
const Real3D& espressopp::Particle::velocity () const inline
Definition at line 268 of file Particle.hpp.
References m, and espressopp::ParticleMomentum::v.
real& espressopp::Particle::vradius () inline
Definition at line 272 of file Particle.hpp.
References m, and espressopp::ParticleMomentum::vradius.
const real& espressopp::Particle::vradius () const inline
Definition at line 273 of file Particle.hpp.
References m, and espressopp::ParticleMomentum::vradius.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Definition at line 338 of file Particle.hpp.
friend class InBuffer friend
Definition at line 173 of file Particle.hpp.
friend class OutBuffer friend
Definition at line 174 of file Particle.hpp.
Member Data Documentation
ParticleForce espressopp::Particle::f private
Definition at line 336 of file Particle.hpp.
Referenced by force(), fradius(), getF(), getFRadius(), init(), particleForce(), serialize(), setF(), and setFRadius().
ParticleLocal espressopp::Particle::l private
Definition at line 335 of file Particle.hpp.
Referenced by copyAsGhost(), getGhostStatus(), getImageBox(), ghost(), image(), init(), espressopp::InBuffer::read(), serialize(), setGhostStatus(), setImageBox(), and espressopp::OutBuffer::write().
ParticleMomentum espressopp::Particle::m private
Definition at line 334 of file Particle.hpp.
Referenced by copyAsGhost(), getV(), getVRadius(), init(), espressopp::InBuffer::read(), serialize(), setV(), setVRadius(), velocity(), vradius(), and espressopp::OutBuffer::write().
ParticleProperties espressopp::Particle::p private
Definition at line 332 of file Particle.hpp.
Referenced by copyAsGhost(), drift(), getDrift(), getId(), getLambda(), getLambdaDeriv(), getMass(), getQ(), getState(), getType(), id(), init(), lambda(), lambdaDeriv(), mass(), q(), espressopp::InBuffer::read(), serialize(), setDrift(), setLambda(), setLambdaDeriv(), setMass(), setQ(), setState(), setType(), state(), type(), and espressopp::OutBuffer::write().
ParticlePosition espressopp::Particle::r private
Definition at line 333 of file Particle.hpp.
Referenced by espressopp::storage::Storage::addParticle(), copyAsGhost(), extVar(), getExtVar(), getPos(), getRadius(), init(), position(), radius(), espressopp::InBuffer::read(), serialize(), setExtVar(), setPos(), setRadius(), and espressopp::OutBuffer::write().
The documentation for this struct was generated from the following files:
/home/travis/build/espressopp/espressopp/src/Particle.hpp
/home/travis/build/espressopp/espressopp/src/Particle.cpp