ESPResSo++: espressopp::interaction::TabulatedDihedral_pickle Struct Reference
espressopp::interaction::TabulatedDihedral_pickle Struct Reference
#include <TabulatedDihedral.hpp>
Static Public Member Functions
static boost::python::tuple getinitargs (TabulatedDihedral const &pot)
Detailed Description
Definition at line 196 of file TabulatedDihedral.hpp.
Member Function Documentation
getinitargs()
static boost::python::tuple espressopp::interaction::TabulatedDihedral_pickle::getinitargs (TabulatedDihedral const & pot) inline static
Definition at line 200 of file TabulatedDihedral.hpp.
References espressopp::interaction::DihedralPotentialTemplate< Derived >::getCutoff(), espressopp::interaction::TabulatedDihedral::getFilename(), and espressopp::interaction::TabulatedDihedral::getInterpolationType().
The documentation for this struct was generated from the following file:
/home/espressopp/espressopp/src/interaction/TabulatedDihedral.hpp