ESPResSo++: espressopp::TupleList Struct Reference
espressopp::TupleList Struct Reference
#include <Particle.hpp>
Public Types
typedef ESPPIterator< std::map< Particle *, std::vector< Particle * > > > Iterator
Public Member Functions
void add (Particle *p, std::vector< Particle * > particles)
Protected Types
typedef std::map< Particle *, std::vector< Particle * > > Super
Detailed Description
Definition at line 527 of file Particle.hpp.
Member Typedef Documentation
Iterator
typedef ESPPIterator<std::map< Particle *, std::vector< Particle * > > > espressopp::esutil::ESPPContainer< std::map< Particle *, std::vector< Particle * > > >::Iterator inherited
Definition at line 66 of file ESPPIterator.hpp.
Super
typedef std::map< Particle *, std::vector< Particle * > > espressopp::esutil::ESPPContainer< std::map< Particle *, std::vector< Particle * > > >::Super protected inherited
Definition at line 64 of file ESPPIterator.hpp.
Member Function Documentation
add()
void espressopp::TupleList::add (Particle * p, std::vector< Particle * > particles) inline
Definition at line 529 of file Particle.hpp.
Referenced by espressopp::FixedLocalTupleList::addTuple(), espressopp::FixedTupleList::addTuple(), espressopp::FixedLocalTupleList::onParticlesChanged(), and espressopp::FixedTupleList::onParticlesChanged().
The documentation for this struct was generated from the following file:
/home/espressopp/espressopp/src/Particle.hpp