ESPResSo++: espressopp::interaction::CoulombTruncatedUniqueCharge_pickle Struct Reference
espressopp::interaction::CoulombTruncatedUniqueCharge_pickle Struct Reference
#include <CoulombTruncatedUniqueCharge.hpp>
Static Public Member Functions
static boost::python::tuple getinitargs (CoulombTruncatedUniqueCharge const &pot)
Detailed Description
Definition at line 88 of file CoulombTruncatedUniqueCharge.hpp.
Member Function Documentation
static boost::python::tuple espressopp::interaction::CoulombTruncatedUniqueCharge_pickle::getinitargs (CoulombTruncatedUniqueCharge const & pot) [inline, static]
Definition at line 92 of file CoulombTruncatedUniqueCharge.hpp.
References espressopp::interaction::PotentialTemplate< Derived >::getCutoff(), espressopp::interaction::CoulombTruncatedUniqueCharge::getQQ(), and espressopp::interaction::PotentialTemplate< Derived >::getShift().
The documentation for this struct was generated from the following file:
/home/travis/build/espressopp/espressopp/src/interaction/CoulombTruncatedUniqueCharge.hpp