ESPResSo++: espressopp::TripleList Struct Reference
espressopp::TripleList Struct Reference
#include <Particle.hpp>
Public Types
typedef ESPPIterator< std::vector< ParticleTriple > > Iterator
Public Member Functions
void add (Particle *p1, Particle *p2, Particle *p3)
void add (Particle &p1, Particle &p2, Particle &p3)
void add (std::vector< Particle * > particles)
Protected Types
typedef std::vector< ParticleTriple > Super
Detailed Description
Definition at line 480 of file Particle.hpp.
Member Typedef Documentation
Iterator
typedef ESPPIterator<std::vector< ParticleTriple > > espressopp::esutil::ESPPContainer< std::vector< ParticleTriple > >::Iterator inherited
Definition at line 66 of file ESPPIterator.hpp.
Super
typedef std::vector< ParticleTriple > espressopp::esutil::ESPPContainer< std::vector< ParticleTriple > >::Super protected inherited
Definition at line 64 of file ESPPIterator.hpp.
Member Function Documentation
add() [1/3]
void espressopp::TripleList::add (Particle & p1, Particle & p2, Particle & p3) inline
Definition at line 487 of file Particle.hpp.
References add().
add() [2/3]
void espressopp::TripleList::add (Particle * p1, Particle * p2, Particle * p3) inline
Definition at line 483 of file Particle.hpp.
Referenced by espressopp::FixedListComm::add(), add(), espressopp::VerletListTriple::checkTriple(), and espressopp::FixedListComm::onParticlesChanged().
add() [3/3]
void espressopp::TripleList::add (std::vector< Particle * > particles) inline
Definition at line 490 of file Particle.hpp.
References add().
The documentation for this struct was generated from the following file:
/home/espressopp/espressopp/src/Particle.hpp