ESPResSo++: espressopp::vectorization::VerletList::NeighborList Struct Reference
espressopp::vectorization::VerletList::NeighborList Struct Reference
Hierarchical storage of chunk indices.
#include <VerletList.hpp>
Public Member Functions
void reset ()
void clear ()
Public Attributes
std::vector< longint > clist
std::vector< int > crange
std::vector< int > plist
std::vector< int > prange
AlignedVector< int > nplist
Detailed Description
Hierarchical storage of chunk indices.
Definition at line 53 of file VerletList.hpp.
Member Function Documentation
clear()
void espressopp::vectorization::VerletList::NeighborList::clear () inline
Definition at line 69 of file VerletList.hpp.
References espressopp::vectorization::VerletList::cut, reset(), espressopp::vectorization::VerletList::VerletList(), and espressopp::vectorization::VerletList::~VerletList().
reset()
void espressopp::vectorization::VerletList::NeighborList::reset () inline
Definition at line 61 of file VerletList.hpp.
Referenced by clear(), and espressopp::vectorization::VerletList::rebuild().
Member Data Documentation
clist
std::vector< longint > espressopp::vectorization::VerletList::NeighborList::clist
Definition at line 55 of file VerletList.hpp.
Referenced by espressopp::vectorization::VerletList::rebuild_p_nc_pack_stencil().
crange
std::vector< int > espressopp::vectorization::VerletList::NeighborList::crange
Definition at line 56 of file VerletList.hpp.
Referenced by espressopp::vectorization::VerletList::rebuild_p_nc_pack_stencil().
nplist
AlignedVector< int > espressopp::vectorization::VerletList::NeighborList::nplist
Definition at line 59 of file VerletList.hpp.
Referenced by espressopp::vectorization::VerletList::rebuild_p_nc_pack_stencil().
plist
std::vector< int > espressopp::vectorization::VerletList::NeighborList::plist
Definition at line 57 of file VerletList.hpp.
Referenced by espressopp::vectorization::VerletList::rebuild_p_nc_pack_stencil().
prange
std::vector< int > espressopp::vectorization::VerletList::NeighborList::prange
Definition at line 58 of file VerletList.hpp.
Referenced by espressopp::vectorization::VerletList::rebuild_p_nc_pack_stencil().
The documentation for this struct was generated from the following file:
/home/espressopp/espressopp/src/vectorization/VerletList.hpp