ESPResSo++: espressopp::PairList Struct Reference
espressopp::PairList Struct Reference
#include <Particle.hpp>
Public Types
typedef ESPPIterator< std::vector< ParticlePair > > Iterator
Public Member Functions
void add (Particle *p1, Particle *p2)
void add (Particle &p1, Particle &p2)
void add (std::vector< Particle *> particles)
Protected Types
typedef std::vector< ParticlePair > Super
Detailed Description
Definition at line 451 of file Particle.hpp.
Member Typedef Documentation
Iterator
typedef ESPPIterator<std::vector< ParticlePair > > espressopp::esutil::ESPPContainer< std::vector< ParticlePair > >::Iterator inherited
Definition at line 66 of file ESPPIterator.hpp.
Super
typedef std::vector< ParticlePair > espressopp::esutil::ESPPContainer< std::vector< ParticlePair > >::Super protected inherited
Definition at line 64 of file ESPPIterator.hpp.
Member Function Documentation
add() [1/3]
void espressopp::PairList::add (Particle * p1, Particle * p2) inline
Definition at line 454 of file Particle.hpp.
Referenced by espressopp::VerletList::_rebuildUsingBuffers(), espressopp::FixedListComm::add(), espressopp::VerletListAdress::checkPair(), espressopp::VerletList::checkPair(), espressopp::vectorization::VerletList::checkPair(), and espressopp::FixedListComm::onParticlesChanged().
add() [2/3]
void espressopp::PairList::add (Particle & p1, Particle & p2) inline
Definition at line 458 of file Particle.hpp.
add() [3/3]
void espressopp::PairList::add (std::vector< Particle *> particles) inline
Definition at line 461 of file Particle.hpp.
The documentation for this struct was generated from the following file:
/home/espressopp/espressopp/src/Particle.hpp