ESPResSo++: espressopp::QuadrupleList Struct Reference
espressopp::QuadrupleList Struct Reference
#include <Particle.hpp>
Public Types
typedef ESPPIterator
< std::vector
< ParticleQuadruple > > Iterator
Public Member Functions
void add (Particle *p1, Particle *p2, Particle *p3, Particle *p4)
void add (Particle &p1, Particle &p2, Particle &p3, Particle &p4)
void add (std::vector< Particle * > particles)
Protected Types
typedef std::vector
< ParticleQuadruple > Super
Detailed Description
Definition at line 452 of file Particle.hpp.
Member Typedef Documentation
typedef ESPPIterator<std::vector< ParticleQuadruple > > espressopp::esutil::ESPPContainer< std::vector< ParticleQuadruple > >::Iterator inherited
Definition at line 66 of file ESPPIterator.hpp.
typedef std::vector< ParticleQuadruple > espressopp::esutil::ESPPContainer< std::vector< ParticleQuadruple > >::Super protected inherited
Definition at line 64 of file ESPPIterator.hpp.
Member Function Documentation
void espressopp::QuadrupleList::add (Particle * p1, Particle * p2, Particle * p3, Particle * p4) inline
Definition at line 455 of file Particle.hpp.
Referenced by espressopp::FixedListComm::add(), add(), and espressopp::FixedListComm::onParticlesChanged().
void espressopp::QuadrupleList::add (Particle & p1, Particle & p2, Particle & p3, Particle & p4) inline
Definition at line 459 of file Particle.hpp.
References add().
Referenced by add().
void espressopp::QuadrupleList::add (std::vector< Particle * > particles) inline
Definition at line 462 of file Particle.hpp.
References add().
The documentation for this struct was generated from the following file:
/home/travis/build/espressopp/espressopp/src/Particle.hpp