ESPResSo++: espressopp::interaction::TabulatedSubEns_pickle Struct Reference
espressopp::interaction::TabulatedSubEns_pickle Struct Reference
#include <TabulatedSubEns.hpp>
Static Public Member Functions
static boost::python::tuple getinitargs (TabulatedSubEns const &pot)
Detailed Description
Definition at line 179 of file TabulatedSubEns.hpp.
Member Function Documentation
getinitargs()
static boost::python::tuple espressopp::interaction::TabulatedSubEns_pickle::getinitargs (TabulatedSubEns const & pot) inline static
Definition at line 183 of file TabulatedSubEns.hpp.
References espressopp::interaction::TabulatedSubEns::getAlpha(), espressopp::interaction::TabulatedSubEns::getColVarRefs(), espressopp::interaction::TabulatedSubEns::getColVarSds(), espressopp::interaction::PotentialTemplate< Derived >::getCutoff(), espressopp::interaction::TabulatedSubEns::getDimension(), espressopp::interaction::TabulatedSubEns::getFilenames(), and espressopp::interaction::TabulatedSubEns::getInterpolationType().
The documentation for this struct was generated from the following file:
/home/espressopp/espressopp/src/interaction/TabulatedSubEns.hpp