ESPResSo++: espressopp::bc::OrthorhombicBC Class Reference
espressopp::bc::OrthorhombicBC Class Reference
#include <OrthorhombicBC.hpp>
Public Member Functions
virtual ~OrthorhombicBC ()
Virtual destructor for boundary conditions.
OrthorhombicBC (shared_ptr< esutil::RNG > _rng, const Real3D &_boxL)
Constructor.
virtual void setBoxL (const Real3D &_boxL)
Method to set the length of the side of the cubic simulation cell.
virtual Real3D getBoxL () const
Getters for box dimensions.
virtual void scaleVolume (real s)
Scale the Volume of the box by s^(1/3) ??? (Box-Length is scaled by s)
virtual void scaleVolume (Real3D s)
Scale the Volume of the box anisotropic case.
virtual void getMinimumImageVector (Real3D &dist, const Real3D &pos1, const Real3D &pos2) const
Computes the minimum image distance vector between two positions.
virtual void getMinimumImageVectorBox (Real3D &dist, const Real3D &pos1, const Real3D &pos2) const
Computes the minimum image distance vector between two positions where both positions are in the box.
virtual void getMinimumImageVectorX (real dist[3], const real pos1[3], const real pos2[3]) const
virtual void getMinimumDistance (Real3D &dist) const
Compute the minimum image distance where the distance is given by two positions in the box.
virtual void foldCoordinate (Real3D &pos, Int3D &imageBox, int dir) const
fold a coordinate to the primary simulation box.
virtual void unfoldCoordinate (Real3D &pos, Int3D &imageBox, int dir) const
unfold a coordinate to physical position.
virtual void getRandomPos (Real3D &res) const
Get a random position within the central simulation box.
virtual shared_ptr< esutil::RNG > getRng ()
Getter for the RNG.
virtual void setRng (shared_ptr< esutil::RNG > _rng)
Setter for RNG.
virtual Real3D getMinimumImageVector (const Real3D &pos1, const Real3D &pos2) const
virtual void foldPosition (Real3D &pos, Int3D &imageBox) const
Fold the coordinates to the primary simulation box.
virtual void foldPosition (Real3D &pos) const
virtual boost::python::tuple getFoldedPosition (const Real3D &pos, const Int3D &imageBox) const
Get the folded position as a Python tuple.
virtual boost::python::tuple getFoldedPosition (const Real3D &pos) const
virtual void unfoldPosition (Real3D &pos, Int3D &imageBox) const
unfold coordinates to physical position.
virtual Real3D getUnfoldedPosition (const Real3D &pos, const Int3D &imageBox) const
virtual Real3D getRandomPos () const
Static Public Member Functions
static void registerPython ()
Public Attributes
boost::signals2::signal< void()> onBoxDimensionsChanged
Static Protected Member Functions
static LOG4ESPP_DECL_LOGGER (logger)
Protected Attributes
shared_ptr< esutil::RNG > rng
Private Attributes
Real3D boxL
Real3D boxL2
Real3D invBoxL
Detailed Description
Definition at line 32 of file OrthorhombicBC.hpp.
Constructor & Destructor Documentation
~OrthorhombicBC()
virtual espressopp::bc::OrthorhombicBC::~OrthorhombicBC () inline virtual
Virtual destructor for boundary conditions.
Definition at line 41 of file OrthorhombicBC.hpp.
References OrthorhombicBC(), and setBoxL().
OrthorhombicBC()
espressopp::bc::OrthorhombicBC::OrthorhombicBC (shared_ptr< esutil::RNG > _rng, const Real3D & _boxL)
Constructor.
Definition at line 34 of file OrthorhombicBC.cpp.
References setBoxL().
Referenced by ~OrthorhombicBC().
Member Function Documentation
foldCoordinate()
void espressopp::bc::OrthorhombicBC::foldCoordinate (Real3D & pos, Int3D & imageBox, int dir) const virtual
fold a coordinate to the primary simulation box.
Parameters
pos the position...
imageBox and the box
dir the coordinate to fold: dir = 0,1,2 for x, y and z coordinate.
Both pos and image_box are I/O, i. e. a previously folded position will be folded correctly.
Implements espressopp::bc::BC.
Definition at line 134 of file OrthorhombicBC.cpp.
References boxL, invBoxL, and unfoldCoordinate().
Referenced by getBoxL(), and getMinimumImageVectorX().
foldPosition() [1/2]
void espressopp::bc::BC::foldPosition (Real3D & pos, Int3D & imageBox) const virtual inherited
Fold the coordinates to the primary simulation box.
Parameters
pos the position...
imageBox and the box
Both pos and image_box are I/O, i. e. a previously folded position will be folded correctly.
Definition at line 52 of file BC.cpp.
References espressopp::bc::BC::foldCoordinate().
Referenced by espressopp::bc::BC::foldPosition(), espressopp::bc::BC::getFoldedPosition(), and espressopp::bc::BC::setRng().
foldPosition() [2/2]
void espressopp::bc::BC::foldPosition (Real3D & pos) const virtual inherited
Definition at line 58 of file BC.cpp.
References espressopp::bc::BC::foldPosition().
getBoxL()
virtual Real3D espressopp::bc::OrthorhombicBC::getBoxL () const inline virtual
Getters for box dimensions.
Implements espressopp::bc::BC.
Definition at line 52 of file OrthorhombicBC.hpp.
References boxL, foldCoordinate(), getMinimumDistance(), getMinimumImageVector(), getMinimumImageVectorBox(), getMinimumImageVectorX(), espressopp::bc::BC::getRandomPos(), registerPython(), scaleVolume(), and unfoldCoordinate().
Referenced by registerPython().
getFoldedPosition() [1/2]
boost::python::tuple espressopp::bc::BC::getFoldedPosition (const Real3D & pos, const Int3D & imageBox) const virtual inherited
Get the folded position as a Python tuple.
Definition at line 70 of file BC.cpp.
References espressopp::bc::BC::foldPosition().
Referenced by espressopp::bc::BC::registerPython(), and espressopp::bc::BC::setRng().
getFoldedPosition() [2/2]
boost::python::tuple espressopp::bc::BC::getFoldedPosition (const Real3D & pos) const virtual inherited
Definition at line 79 of file BC.cpp.
References espressopp::bc::BC::foldPosition().
getMinimumDistance()
void espressopp::bc::OrthorhombicBC::getMinimumDistance (Real3D & dist) const virtual
Compute the minimum image distance where the distance is given by two positions in the box.
Implements espressopp::bc::BC.
Definition at line 101 of file OrthorhombicBC.cpp.
References boxL, and getMinimumImageVectorX().
Referenced by getBoxL().
getMinimumImageVector() [1/2]
void espressopp::bc::OrthorhombicBC::getMinimumImageVector (Real3D & dist, const Real3D & pos1, const Real3D & pos2) const virtual
Computes the minimum image distance vector between two positions.
This routine must be implemented by derived classes (once the code stabilizes).
Parameters
dist is the distance vector (pos2 - pos1)
pos1,pos2 are the particle positions
Implements espressopp::bc::BC.
Definition at line 70 of file OrthorhombicBC.cpp.
References boxL, getMinimumImageVectorBox(), and invBoxL.
Referenced by getBoxL(), and scaleVolume().
getMinimumImageVector() [2/2]
Real3D espressopp::bc::BC::getMinimumImageVector (const Real3D & pos1, const Real3D & pos2) const virtual inherited
Definition at line 37 of file BC.cpp.
References espressopp::bc::BC::getMinimumImageVector().
getMinimumImageVectorBox()
void espressopp::bc::OrthorhombicBC::getMinimumImageVectorBox (Real3D & dist, const Real3D & pos1, const Real3D & pos2) const virtual
Computes the minimum image distance vector between two positions where both positions are in the box.
Parameters
dist is the distance vector (pos2 - pos1)
pos1,pos2 are the particle positions
Be careful: this routine is faster than getMinimumImageVector but will only deliver corrrect result if the absolute distance in each dimension is less than the box size.
Implements espressopp::bc::BC.
Definition at line 84 of file OrthorhombicBC.cpp.
References boxL, and boxL2.
Referenced by getBoxL(), and getMinimumImageVector().
getMinimumImageVectorX()
void espressopp::bc::OrthorhombicBC::getMinimumImageVectorX (real dist[3], const real pos1[3], const real pos2[3]) const virtual
Implements espressopp::bc::BC.
Definition at line 114 of file OrthorhombicBC.cpp.
References boxL, foldCoordinate(), and invBoxL.
Referenced by getBoxL(), and getMinimumDistance().
getRandomPos() [1/2]
void espressopp::bc::OrthorhombicBC::getRandomPos (Real3D & res) const virtual
Get a random position within the central simulation box.
The positions are assigned with each coordinate on [0, boxL].
Implements espressopp::bc::BC.
Definition at line 165 of file OrthorhombicBC.cpp.
References boxL, and registerPython().
getRandomPos() [2/2]
Real3D espressopp::bc::BC::getRandomPos () const virtual inherited
Definition at line 45 of file BC.cpp.
Referenced by getBoxL(), espressopp::bc::SlabBC::getBoxL(), espressopp::bc::BC::registerPython(), espressopp::bc::BC::setRng(), unfoldCoordinate(), and espressopp::bc::SlabBC::unfoldCoordinate().
getRng()
virtual shared_ptr< esutil::RNG > espressopp::bc::BC::getRng () inline virtual inherited
Getter for the RNG.
Definition at line 50 of file BC.hpp.
References espressopp::bc::BC::rng.
Referenced by espressopp::bc::BC::registerPython().
getUnfoldedPosition()
Real3D espressopp::bc::BC::getUnfoldedPosition (const Real3D & pos, const Int3D & imageBox) const virtual inherited
Definition at line 87 of file BC.cpp.
References espressopp::bc::BC::unfoldPosition().
Referenced by espressopp::bc::BC::registerPython(), and espressopp::bc::BC::setRng().
LOG4ESPP_DECL_LOGGER()
static espressopp::bc::BC::LOG4ESPP_DECL_LOGGER (logger) static protected inherited
registerPython()
void espressopp::bc::OrthorhombicBC::registerPython () static
Definition at line 176 of file OrthorhombicBC.cpp.
References getBoxL(), and setBoxL().
Referenced by getBoxL(), getRandomPos(), and espressopp::bc::registerPython().
scaleVolume() [1/2]
void espressopp::bc::OrthorhombicBC::scaleVolume (real s) virtual
Scale the Volume of the box by s^(1/3) ??? (Box-Length is scaled by s)
Implements espressopp::bc::BC.
Definition at line 48 of file OrthorhombicBC.cpp.
References boxL, boxL2, invBoxL, and espressopp::bc::BC::onBoxDimensionsChanged.
Referenced by getBoxL().
scaleVolume() [2/2]
void espressopp::bc::OrthorhombicBC::scaleVolume (Real3D s) virtual
Scale the Volume of the box anisotropic case.
Implements espressopp::bc::BC.
Definition at line 54 of file OrthorhombicBC.cpp.
References boxL, boxL2, getMinimumImageVector(), invBoxL, and espressopp::bc::BC::onBoxDimensionsChanged.
setBoxL()
void espressopp::bc::OrthorhombicBC::setBoxL (const Real3D & _boxL) virtual
Method to set the length of the side of the cubic simulation cell.
Definition at line 40 of file OrthorhombicBC.cpp.
References boxL, boxL2, invBoxL, and espressopp::bc::BC::onBoxDimensionsChanged.
Referenced by OrthorhombicBC(), registerPython(), and ~OrthorhombicBC().
setRng()
virtual void espressopp::bc::BC::setRng (shared_ptr< esutil::RNG > _rng) inline virtual inherited
Setter for RNG.
Definition at line 52 of file BC.hpp.
References espressopp::bc::BC::foldCoordinate(), espressopp::bc::BC::foldPosition(), espressopp::bc::BC::getFoldedPosition(), espressopp::bc::BC::getMinimumDistance(), espressopp::bc::BC::getMinimumImageVector(), espressopp::bc::BC::getMinimumImageVectorBox(), espressopp::bc::BC::getMinimumImageVectorX(), espressopp::bc::BC::getRandomPos(), espressopp::bc::BC::getUnfoldedPosition(), espressopp::bc::BC::rng, espressopp::bc::BC::unfoldCoordinate(), and espressopp::bc::BC::unfoldPosition().
Referenced by espressopp::bc::BC::registerPython().
unfoldCoordinate()
void espressopp::bc::OrthorhombicBC::unfoldCoordinate (Real3D & pos, Int3D & imageBox, int dir) const virtual
unfold a coordinate to physical position.
Parameters
pos the position...
imageBox and the box
Both pos and image_box are I/O, i.e. image_box will be (0,0,0) afterwards.
Implements espressopp::bc::BC.
Definition at line 157 of file OrthorhombicBC.cpp.
References boxL, and espressopp::bc::BC::getRandomPos().
Referenced by foldCoordinate(), and getBoxL().
unfoldPosition()
void espressopp::bc::BC::unfoldPosition (Real3D & pos, Int3D & imageBox) const virtual inherited
unfold coordinates to physical position.
Parameters
pos the position...
imageBox and the box
Both pos and image_box are I/O, i.e. image_box will be (0,0,0) afterwards.
Definition at line 64 of file BC.cpp.
References espressopp::bc::BC::unfoldCoordinate().
Referenced by espressopp::bc::BC::getUnfoldedPosition(), and espressopp::bc::BC::setRng().
Member Data Documentation
boxL
Real3D espressopp::bc::OrthorhombicBC::boxL private
Definition at line 34 of file OrthorhombicBC.hpp.
Referenced by foldCoordinate(), getBoxL(), getMinimumDistance(), getMinimumImageVector(), getMinimumImageVectorBox(), getMinimumImageVectorX(), getRandomPos(), scaleVolume(), setBoxL(), and unfoldCoordinate().
boxL2
Real3D espressopp::bc::OrthorhombicBC::boxL2 private
Definition at line 35 of file OrthorhombicBC.hpp.
Referenced by getMinimumImageVectorBox(), scaleVolume(), and setBoxL().
invBoxL
Real3D espressopp::bc::OrthorhombicBC::invBoxL private
Definition at line 36 of file OrthorhombicBC.hpp.
Referenced by foldCoordinate(), getMinimumImageVector(), getMinimumImageVectorX(), scaleVolume(), and setBoxL().
onBoxDimensionsChanged
boost::signals2::signal<void ()> espressopp::bc::BC::onBoxDimensionsChanged inherited
Definition at line 152 of file BC.hpp.
Referenced by scaleVolume(), espressopp::bc::SlabBC::scaleVolume(), setBoxL(), and espressopp::bc::SlabBC::setBoxL().
rng
shared_ptr< esutil::RNG > espressopp::bc::BC::rng protected inherited
Definition at line 157 of file BC.hpp.
Referenced by espressopp::bc::BC::getRng(), and espressopp::bc::BC::setRng().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/bc/OrthorhombicBC.hpp
/home/espressopp/espressopp/src/bc/OrthorhombicBC.cpp