ESPResSo++: espressopp::interaction::DihedralPotentialTemplate< Derived > Class Template Reference
espressopp::interaction::DihedralPotentialTemplate< Derived > Class Template Reference
#include <DihedralPotential.hpp>
Public Member Functions
DihedralPotentialTemplate ()
virtual real computeEnergy (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
virtual real computeEnergy (real phi) const
virtual void computeForce (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
virtual real computeForce (real phi) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)
virtual shared_ptr< FixedPairList > getColVarBondList () const
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &ftl)
virtual shared_ptr< FixedTripleList > getColVarAngleList () const
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fql)
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const
virtual void setColVar (const RealND &cv)
virtual void setColVar (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43, const bc::BC &bc)
virtual RealND getColVar () const
virtual void computeColVarWeights (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43, const bc::BC &bc)
real _computeEnergy (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
real _computeEnergy (real phi) const
void _computeForce (Real3D &force1, Real3D &force2, Real3D &force3, Real3D &force4, const Real3D &dist21, const Real3D &dist32, const Real3D &dist43) const
Static Public Member Functions
static real computePhi (const Real3D &dist21, const Real3D &dist32, const Real3D &dist43)
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
Derived * derived_this ()
const Derived * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
shared_ptr< FixedPairList > colVarBondList
shared_ptr< FixedTripleList > colVarAngleList
shared_ptr< FixedQuadrupleList > colVarDihedList
RealND colVar
Detailed Description
template<class Derived>
class espressopp::interaction::DihedralPotentialTemplate< Derived >
Definition at line 84 of file DihedralPotential.hpp.
Constructor & Destructor Documentation
DihedralPotentialTemplate()
template<class Derived > espressopp::interaction::DihedralPotentialTemplate< Derived >::DihedralPotentialTemplate () inline
Definition at line 169 of file DihedralPotential.hpp.
Referenced by espressopp::interaction::DihedralPotentialTemplate< OPLS >::derived_this().
Member Function Documentation
_computeEnergy() [1/2]
template<class Derived > real espressopp::interaction::DihedralPotentialTemplate< Derived >::_computeEnergy (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline
Definition at line 285 of file DihedralPotential.hpp.
_computeEnergy() [2/2]
template<class Derived > real espressopp::interaction::DihedralPotentialTemplate< Derived >::_computeEnergy (real phi) const inline
Definition at line 295 of file DihedralPotential.hpp.
_computeForce()
template<class Derived > void espressopp::interaction::DihedralPotentialTemplate< Derived >::_computeForce (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline
Definition at line 317 of file DihedralPotential.hpp.
computeColVarWeights()
template<class Derived > void espressopp::interaction::DihedralPotentialTemplate< Derived >::computeColVarWeights (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43, const bc::BC & bc) inline virtual
Implements espressopp::interaction::DihedralPotential.
Reimplemented in espressopp::interaction::TabulatedSubEnsDihedral.
Definition at line 256 of file DihedralPotential.hpp.
computeEnergy() [1/2]
template<class Derived > real espressopp::interaction::DihedralPotentialTemplate< Derived >::computeEnergy (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline virtual
Implements espressopp::interaction::DihedralPotential.
Definition at line 265 of file DihedralPotential.hpp.
computeEnergy() [2/2]
template<class Derived > real espressopp::interaction::DihedralPotentialTemplate< Derived >::computeEnergy (real phi) const inline virtual
Implements espressopp::interaction::DihedralPotential.
Definition at line 278 of file DihedralPotential.hpp.
computeForce() [1/2]
template<class Derived > void espressopp::interaction::DihedralPotentialTemplate< Derived >::computeForce (Real3D & force1, Real3D & force2, Real3D & force3, Real3D & force4, const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) const inline virtual
Implements espressopp::interaction::DihedralPotential.
Definition at line 303 of file DihedralPotential.hpp.
computeForce() [2/2]
template<class Derived > real espressopp::interaction::DihedralPotentialTemplate< Derived >::computeForce (real phi) const inline virtual
Implements espressopp::interaction::DihedralPotential.
Definition at line 331 of file DihedralPotential.hpp.
computePhi()
real espressopp::interaction::DihedralPotential::computePhi (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43) static inherited
Definition at line 31 of file DihedralPotential.cpp.
References espressopp::Real3D::abs(), espressopp::Real3D::cross(), and espressopp::interaction::LOG4ESPP_LOGGER().
Referenced by espressopp::interaction::DihedralPotential::registerPython(), espressopp::interaction::TabulatedSubEnsDihedral::setColVar(), espressopp::interaction::TabulatedSubEnsAngular::setColVar(), and espressopp::interaction::TabulatedSubEns::setColVar().
derived_this() [1/2]
template<class Derived> Derived* espressopp::interaction::DihedralPotentialTemplate< Derived >::derived_this () inline protected
Definition at line 154 of file DihedralPotential.hpp.
derived_this() [2/2]
template<class Derived> const Derived* espressopp::interaction::DihedralPotentialTemplate< Derived >::derived_this () const inline protected
Definition at line 158 of file DihedralPotential.hpp.
getColVar()
template<class Derived > RealND espressopp::interaction::DihedralPotentialTemplate< Derived >::getColVar () const inline virtual
Implements espressopp::interaction::DihedralPotential.
Definition at line 250 of file DihedralPotential.hpp.
getColVarAngleList()
template<class Derived > shared_ptr< FixedTripleList > espressopp::interaction::DihedralPotentialTemplate< Derived >::getColVarAngleList () const inline virtual
Implements espressopp::interaction::DihedralPotential.
Definition at line 213 of file DihedralPotential.hpp.
getColVarBondList()
template<class Derived > shared_ptr< FixedPairList > espressopp::interaction::DihedralPotentialTemplate< Derived >::getColVarBondList () const inline virtual
Implements espressopp::interaction::DihedralPotential.
Definition at line 199 of file DihedralPotential.hpp.
getColVarDihedList()
template<class Derived > shared_ptr< FixedQuadrupleList > espressopp::interaction::DihedralPotentialTemplate< Derived >::getColVarDihedList () const inline virtual
Implements espressopp::interaction::DihedralPotential.
Definition at line 227 of file DihedralPotential.hpp.
getCutoff()
template<class Derived > real espressopp::interaction::DihedralPotentialTemplate< Derived >::getCutoff () const inline virtual
Implements espressopp::interaction::DihedralPotential.
Definition at line 185 of file DihedralPotential.hpp.
Referenced by espressopp::interaction::TabulatedDihedral_pickle::getinitargs(), and espressopp::interaction::TabulatedSubEnsDihedral_pickle::getinitargs().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::DihedralPotential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
registerPython()
void espressopp::interaction::DihedralPotential::registerPython () static inherited
Definition at line 64 of file DihedralPotential.cpp.
References espressopp::interaction::DihedralPotential::computeEnergy(), espressopp::interaction::DihedralPotential::computeForce(), espressopp::interaction::DihedralPotential::computePhi(), espressopp::interaction::DihedralPotential::getColVar(), espressopp::interaction::DihedralPotential::getColVarAngleList(), espressopp::interaction::DihedralPotential::getColVarBondList(), espressopp::interaction::DihedralPotential::getCutoff(), espressopp::interaction::DihedralPotential::setColVarAngleList(), espressopp::interaction::DihedralPotential::setColVarBondList(), and espressopp::interaction::DihedralPotential::setCutoff().
Referenced by espressopp::interaction::registerPython().
setColVar() [1/2]
template<class Derived > void espressopp::interaction::DihedralPotentialTemplate< Derived >::setColVar (const RealND & cv) inline virtual
Implements espressopp::interaction::DihedralPotential.
Definition at line 234 of file DihedralPotential.hpp.
setColVar() [2/2]
template<class Derived > void espressopp::interaction::DihedralPotentialTemplate< Derived >::setColVar (const Real3D & dist21, const Real3D & dist32, const Real3D & dist43, const bc::BC & bc) inline virtual
Implements espressopp::interaction::DihedralPotential.
Reimplemented in espressopp::interaction::TabulatedSubEnsDihedral.
Definition at line 241 of file DihedralPotential.hpp.
setColVarAngleList()
template<class Derived > void espressopp::interaction::DihedralPotentialTemplate< Derived >::setColVarAngleList (const shared_ptr< FixedTripleList > & ftl) inline virtual
Implements espressopp::interaction::DihedralPotential.
Definition at line 206 of file DihedralPotential.hpp.
setColVarBondList()
template<class Derived > void espressopp::interaction::DihedralPotentialTemplate< Derived >::setColVarBondList (const shared_ptr< FixedPairList > & fpl) inline virtual
Implements espressopp::interaction::DihedralPotential.
Definition at line 192 of file DihedralPotential.hpp.
setColVarDihedList()
template<class Derived > void espressopp::interaction::DihedralPotentialTemplate< Derived >::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fql) inline virtual
Implements espressopp::interaction::DihedralPotential.
Definition at line 220 of file DihedralPotential.hpp.
setCutoff()
template<class Derived > void espressopp::interaction::DihedralPotentialTemplate< Derived >::setCutoff (real _cutoff) inline virtual
Implements espressopp::interaction::DihedralPotential.
Definition at line 177 of file DihedralPotential.hpp.
Member Data Documentation
colVar
template<class Derived> RealND espressopp::interaction::DihedralPotentialTemplate< Derived >::colVar protected
Definition at line 152 of file DihedralPotential.hpp.
colVarAngleList
template<class Derived> shared_ptr<FixedTripleList> espressopp::interaction::DihedralPotentialTemplate< Derived >::colVarAngleList protected
Definition at line 148 of file DihedralPotential.hpp.
colVarBondList
template<class Derived> shared_ptr<FixedPairList> espressopp::interaction::DihedralPotentialTemplate< Derived >::colVarBondList protected
Definition at line 146 of file DihedralPotential.hpp.
colVarDihedList
template<class Derived> shared_ptr<FixedQuadrupleList> espressopp::interaction::DihedralPotentialTemplate< Derived >::colVarDihedList protected
Definition at line 150 of file DihedralPotential.hpp.
cutoff
template<class Derived> real espressopp::interaction::DihedralPotentialTemplate< Derived >::cutoff protected
Definition at line 143 of file DihedralPotential.hpp.
cutoffSqr
template<class Derived> real espressopp::interaction::DihedralPotentialTemplate< Derived >::cutoffSqr protected
Definition at line 144 of file DihedralPotential.hpp.
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/interaction/DihedralPotential.hpp