ESPResSo++: espressopp::interaction::TabulatedSubEns Class Reference
espressopp::interaction::TabulatedSubEns Class Reference
This class provides methods to compute forces and energies of a tabulated potential.
#include <TabulatedSubEns.hpp>
Public Member Functions
TabulatedSubEns ()
void addInteraction (int itype, boost::python::str fname, const RealND &_cvref)
void setDimension (int _dim)
int getDimension () const
void setInterpolationType (int itype)
Setter for the interpolation type.
int getInterpolationType () const
Getter for the interpolation type.
RealND getTargetProb () const
void setTargetProb (int index, real _r)
RealND getColVarSds () const
void setColVarSd (int index, real _r)
RealND getColVarRef (int i) const
RealNDs getColVarRefs () const
void setColVarRef (const RealNDs &cvRefs)
void setColVarRefs (const RealNDs &c)
boost::python::list getFilenames () const
boost::python::list getFilename (int index) const
void setFilename (int index, boost::python::list _f)
void setFilenames (int dim, int itype, boost::python::list _filenames)
RealND getWeights () const
void setWeights (const RealND &r)
real getWeight (int index) const
void setWeight (int index, real _w)
real getAlpha () const
void setAlpha (real _r)
void computeColVarWeights (const Real3D &dist, const bc::BC &bc)
void setColVar (const Real3D &dist, const bc::BC &bc)
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &dist, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)
virtual shared_ptr< FixedPairList > getColVarBondList () const
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &fpl)
virtual shared_ptr< FixedTripleList > getColVarAngleList () const
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fpl)
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const
virtual void setColVar (const RealND &cv)
virtual RealND getColVar () const
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
real _computeEnergyDeriv (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
TabulatedSubEns * derived_this ()
const TabulatedSubEns * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
shared_ptr< FixedPairList > colVarBondList
shared_ptr< FixedTripleList > colVarAngleList
shared_ptr< FixedQuadrupleList > colVarDihedList
RealND colVar
Private Attributes
int numInteractions
std::vector< std::string > filenames
std::vector< shared_ptr< Interpolation > > tables
int interpolationType
RealNDs colVarRef
RealND weights
RealND targetProb
RealND weightSum
int weightCounts
RealND colVarSd
real alpha
int colVarBondListSize
int colVarAngleListSize
int colVarDihedListSize
Detailed Description
This class provides methods to compute forces and energies of a tabulated potential.
The potential and forces must be provided in a file.
Be careful: default and copy constructor of this class are used.
Definition at line 43 of file TabulatedSubEns.hpp.
Constructor & Destructor Documentation
TabulatedSubEns()
espressopp::interaction::TabulatedSubEns::TabulatedSubEns () inline
Definition at line 71 of file TabulatedSubEns.hpp.
References addInteraction(), espressopp::infinity, espressopp::interaction::PotentialTemplate< TabulatedSubEns >::setCutoff(), espressopp::RealND::setDimension(), and espressopp::RealNDs::setDimension().
Member Function Documentation
_computeEnergy() [1/4]
real espressopp::interaction::PotentialTemplate< TabulatedSubEns >::_computeEnergy (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 352 of file Potential.hpp.
_computeEnergy() [2/4]
real espressopp::interaction::PotentialTemplate< TabulatedSubEns >::_computeEnergy (const Real3D & dist) const inline inherited
Definition at line 367 of file Potential.hpp.
_computeEnergy() [3/4]
real espressopp::interaction::PotentialTemplate< TabulatedSubEns >::_computeEnergy (real dist) const inline inherited
Definition at line 374 of file Potential.hpp.
_computeEnergy() [4/4]
real espressopp::interaction::PotentialTemplate< TabulatedSubEns >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 360 of file Potential.hpp.
_computeEnergyDeriv()
real espressopp::interaction::PotentialTemplate< TabulatedSubEns >::_computeEnergyDeriv (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 395 of file Potential.hpp.
_computeEnergySqr()
real espressopp::interaction::PotentialTemplate< TabulatedSubEns >::_computeEnergySqr (real distSqr) const inline inherited
Definition at line 381 of file Potential.hpp.
_computeEnergySqrRaw()
real espressopp::interaction::TabulatedSubEns::_computeEnergySqrRaw (real distSqr) const inline
Definition at line 160 of file TabulatedSubEns.hpp.
References numInteractions.
_computeForce() [1/3]
bool espressopp::interaction::PotentialTemplate< TabulatedSubEns >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const inline inherited
Definition at line 423 of file Potential.hpp.
_computeForce() [2/3]
bool espressopp::interaction::PotentialTemplate< TabulatedSubEns >::_computeForce (Real3D & force, const Real3D & dist) const inline inherited
Definition at line 438 of file Potential.hpp.
_computeForce() [3/3]
bool espressopp::interaction::PotentialTemplate< TabulatedSubEns >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 431 of file Potential.hpp.
_computeForceRaw()
bool espressopp::interaction::TabulatedSubEns::_computeForceRaw (Real3D & force, const Real3D & dist, real distSqr) const inline
Definition at line 167 of file TabulatedSubEns.hpp.
References numInteractions.
addInteraction()
void espressopp::interaction::TabulatedSubEns::addInteraction (int itype, boost::python::str fname, const RealND & _cvref)
Definition at line 64 of file TabulatedSubEns.cpp.
References colVarRef, filenames, numInteractions, espressopp::RealND::push_back(), espressopp::RealNDs::setDimension(), tables, targetProb, weights, and weightSum.
Referenced by registerPython(), and TabulatedSubEns().
computeColVarWeights()
void espressopp::interaction::TabulatedSubEns::computeColVarWeights (const Real3D & dist, const bc::BC & bc) virtual
Reimplemented from espressopp::interaction::PotentialTemplate< TabulatedSubEns >.
Definition at line 99 of file TabulatedSubEns.cpp.
References alpha, espressopp::interaction::PotentialTemplate< TabulatedSubEns >::colVar, colVarAngleListSize, colVarBondListSize, colVarRef, colVarSd, espressopp::RealND::getDimension(), M_PI, numInteractions, setColVar(), targetProb, weightCounts, weights, and weightSum.
Referenced by setAlpha().
computeEnergy() [1/3]
real espressopp::interaction::PotentialTemplate< TabulatedSubEns >::computeEnergy (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 323 of file Potential.hpp.
computeEnergy() [2/3]
real espressopp::interaction::PotentialTemplate< TabulatedSubEns >::computeEnergy (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 331 of file Potential.hpp.
computeEnergy() [3/3]
real espressopp::interaction::PotentialTemplate< TabulatedSubEns >::computeEnergy (real dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 338 of file Potential.hpp.
computeEnergySqr()
real espressopp::interaction::PotentialTemplate< TabulatedSubEns >::computeEnergySqr (real distsqr) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 345 of file Potential.hpp.
computeForce() [1/2]
Real3D espressopp::interaction::PotentialTemplate< TabulatedSubEns >::computeForce (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 405 of file Potential.hpp.
computeForce() [2/2]
Real3D espressopp::interaction::PotentialTemplate< TabulatedSubEns >::computeForce (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 413 of file Potential.hpp.
derived_this() [1/2]
TabulatedSubEns * espressopp::interaction::PotentialTemplate< TabulatedSubEns >::derived_this () inline protected inherited
Definition at line 161 of file Potential.hpp.
derived_this() [2/2]
const TabulatedSubEns * espressopp::interaction::PotentialTemplate< TabulatedSubEns >::derived_this () const inline protected inherited
Definition at line 165 of file Potential.hpp.
getAlpha()
real espressopp::interaction::TabulatedSubEns::getAlpha () const inline
Definition at line 152 of file TabulatedSubEns.hpp.
References alpha.
Referenced by espressopp::interaction::TabulatedSubEns_pickle::getinitargs(), and registerPython().
getColVar()
RealND espressopp::interaction::PotentialTemplate< TabulatedSubEns >::getColVar () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 309 of file Potential.hpp.
getColVarAngleList()
shared_ptr< FixedTripleList > espressopp::interaction::PotentialTemplate< TabulatedSubEns >::getColVarAngleList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 273 of file Potential.hpp.
getColVarBondList()
shared_ptr< FixedPairList > espressopp::interaction::PotentialTemplate< TabulatedSubEns >::getColVarBondList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 259 of file Potential.hpp.
getColVarDihedList()
shared_ptr< FixedQuadrupleList > espressopp::interaction::PotentialTemplate< TabulatedSubEns >::getColVarDihedList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 287 of file Potential.hpp.
getColVarRef()
RealND espressopp::interaction::TabulatedSubEns::getColVarRef (int i) const inline
Definition at line 119 of file TabulatedSubEns.hpp.
Referenced by registerPython().
getColVarRefs()
RealNDs espressopp::interaction::TabulatedSubEns::getColVarRefs () const inline
Definition at line 121 of file TabulatedSubEns.hpp.
References colVarRef, and setColVarRef().
Referenced by espressopp::interaction::TabulatedSubEns_pickle::getinitargs(), and registerPython().
getColVarSds()
RealND espressopp::interaction::TabulatedSubEns::getColVarSds () const inline
Definition at line 113 of file TabulatedSubEns.hpp.
References colVarSd.
Referenced by espressopp::interaction::TabulatedSubEns_pickle::getinitargs(), and registerPython().
getCutoff()
real espressopp::interaction::PotentialTemplate< TabulatedSubEns >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 210 of file Potential.hpp.
getDimension()
int espressopp::interaction::TabulatedSubEns::getDimension () const inline
Definition at line 99 of file TabulatedSubEns.hpp.
References numInteractions.
Referenced by espressopp::interaction::TabulatedSubEns_pickle::getinitargs(), and registerPython().
getFilename()
boost::python::list espressopp::interaction::TabulatedSubEns::getFilename (int index) const inline
Definition at line 130 of file TabulatedSubEns.hpp.
Referenced by registerPython().
getFilenames()
boost::python::list espressopp::interaction::TabulatedSubEns::getFilenames () const inline
Definition at line 127 of file TabulatedSubEns.hpp.
Referenced by espressopp::interaction::TabulatedSubEns_pickle::getinitargs(), and registerPython().
getInterpolationType()
int espressopp::interaction::TabulatedSubEns::getInterpolationType () const inline
Getter for the interpolation type.
Definition at line 105 of file TabulatedSubEns.hpp.
References interpolationType.
Referenced by espressopp::interaction::TabulatedSubEns_pickle::getinitargs().
getShift()
real espressopp::interaction::PotentialTemplate< TabulatedSubEns >::getShift () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 225 of file Potential.hpp.
getTargetProb()
RealND espressopp::interaction::TabulatedSubEns::getTargetProb () const inline
Definition at line 107 of file TabulatedSubEns.hpp.
References targetProb.
Referenced by registerPython().
getWeight()
real espressopp::interaction::TabulatedSubEns::getWeight (int index) const inline
Definition at line 144 of file TabulatedSubEns.hpp.
References espressopp::RealND::getItem().
getWeights()
RealND espressopp::interaction::TabulatedSubEns::getWeights () const inline
Definition at line 140 of file TabulatedSubEns.hpp.
References weights.
Referenced by registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
Referenced by espressopp::interaction::Potential::~Potential().
registerPython()
void espressopp::interaction::TabulatedSubEns::registerPython () static
Definition at line 241 of file TabulatedSubEns.cpp.
References addInteraction(), getAlpha(), getColVarRef(), getColVarRefs(), getColVarSds(), getDimension(), getFilename(), getFilenames(), getTargetProb(), getWeights(), setAlpha(), setColVarSd(), setFilename(), setTargetProb(), and setWeight().
Referenced by espressopp::interaction::registerPython().
setAlpha()
void espressopp::interaction::TabulatedSubEns::setAlpha (real _r) inline
Definition at line 154 of file TabulatedSubEns.hpp.
References computeColVarWeights(), and setColVar().
Referenced by registerPython().
setAutoShift()
real espressopp::interaction::PotentialTemplate< TabulatedSubEns >::setAutoShift () inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 231 of file Potential.hpp.
setColVar() [1/2]
void espressopp::interaction::PotentialTemplate< TabulatedSubEns >::setColVar (const RealND & cv) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 294 of file Potential.hpp.
setColVar() [2/2]
void espressopp::interaction::TabulatedSubEns::setColVar (const Real3D & dist, const bc::BC & bc) virtual
Reimplemented from espressopp::interaction::PotentialTemplate< TabulatedSubEns >.
Definition at line 176 of file TabulatedSubEns.cpp.
References espressopp::interaction::PotentialTemplate< TabulatedSubEns >::colVar, espressopp::interaction::PotentialTemplate< TabulatedSubEns >::colVarAngleList, colVarAngleListSize, espressopp::interaction::PotentialTemplate< TabulatedSubEns >::colVarBondList, colVarBondListSize, espressopp::interaction::PotentialTemplate< TabulatedSubEns >::colVarDihedList, colVarDihedListSize, espressopp::interaction::DihedralPotential::computePhi(), espressopp::bc::BC::getMinimumImageVectorBox(), espressopp::Particle::position(), and espressopp::RealND::setDimension().
Referenced by computeColVarWeights(), and setAlpha().
setColVarAngleList()
void espressopp::interaction::PotentialTemplate< TabulatedSubEns >::setColVarAngleList (const shared_ptr< FixedTripleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 266 of file Potential.hpp.
setColVarBondList()
void espressopp::interaction::PotentialTemplate< TabulatedSubEns >::setColVarBondList (const shared_ptr< FixedPairList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 252 of file Potential.hpp.
setColVarDihedList()
void espressopp::interaction::PotentialTemplate< TabulatedSubEns >::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 280 of file Potential.hpp.
setColVarRef()
void espressopp::interaction::TabulatedSubEns::setColVarRef (const RealNDs & cvRefs)
Definition at line 91 of file TabulatedSubEns.cpp.
References colVarRef, and numInteractions.
Referenced by getColVarRefs().
setColVarRefs()
void espressopp::interaction::TabulatedSubEns::setColVarRefs (const RealNDs & c) inline
Definition at line 125 of file TabulatedSubEns.hpp.
setColVarSd()
void espressopp::interaction::TabulatedSubEns::setColVarSd (int index, real _r) inline
Definition at line 115 of file TabulatedSubEns.hpp.
References espressopp::RealND::setItem().
Referenced by registerPython().
setCutoff()
void espressopp::interaction::PotentialTemplate< TabulatedSubEns >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 201 of file Potential.hpp.
Referenced by TabulatedSubEns().
setDimension()
void espressopp::interaction::TabulatedSubEns::setDimension (int _dim) inline
Definition at line 89 of file TabulatedSubEns.hpp.
References espressopp::RealND::setDimension(), and espressopp::RealNDs::setDimension().
setFilename()
void espressopp::interaction::TabulatedSubEns::setFilename (int index, boost::python::list _f) inline
Definition at line 134 of file TabulatedSubEns.hpp.
References setFilenames().
Referenced by registerPython().
setFilenames()
void espressopp::interaction::TabulatedSubEns::setFilenames (int dim, int itype, boost::python::list _filenames)
Definition at line 38 of file TabulatedSubEns.cpp.
References colVarRef, filenames, numInteractions, espressopp::RealNDs::setDimension(), and tables.
Referenced by setFilename().
setInterpolationType()
void espressopp::interaction::TabulatedSubEns::setInterpolationType (int itype) inline
Setter for the interpolation type.
Definition at line 102 of file TabulatedSubEns.hpp.
setShift()
void espressopp::interaction::PotentialTemplate< TabulatedSubEns >::setShift (real _shift) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 216 of file Potential.hpp.
setTargetProb()
void espressopp::interaction::TabulatedSubEns::setTargetProb (int index, real _r) inline
Definition at line 109 of file TabulatedSubEns.hpp.
References espressopp::RealND::setItem().
Referenced by registerPython().
setWeight()
void espressopp::interaction::TabulatedSubEns::setWeight (int index, real _w) inline
Definition at line 148 of file TabulatedSubEns.hpp.
References espressopp::RealND::setItem().
Referenced by registerPython().
setWeights()
void espressopp::interaction::TabulatedSubEns::setWeights (const RealND & r) inline
Definition at line 142 of file TabulatedSubEns.hpp.
updateAutoShift()
void espressopp::interaction::PotentialTemplate< TabulatedSubEns >::updateAutoShift () inline inherited
Definition at line 244 of file Potential.hpp.
Member Data Documentation
alpha
real espressopp::interaction::TabulatedSubEns::alpha private
Definition at line 62 of file TabulatedSubEns.hpp.
Referenced by computeColVarWeights(), and getAlpha().
autoShift
bool espressopp::interaction::PotentialTemplate< TabulatedSubEns >::autoShift protected inherited
Definition at line 151 of file Potential.hpp.
colVar
RealND espressopp::interaction::PotentialTemplate< TabulatedSubEns >::colVar protected inherited
Definition at line 159 of file Potential.hpp.
Referenced by computeColVarWeights(), and setColVar().
colVarAngleList
shared_ptr<FixedTripleList> espressopp::interaction::PotentialTemplate< TabulatedSubEns >::colVarAngleList protected inherited
Definition at line 155 of file Potential.hpp.
Referenced by setColVar().
colVarAngleListSize
int espressopp::interaction::TabulatedSubEns::colVarAngleListSize private
Definition at line 65 of file TabulatedSubEns.hpp.
Referenced by computeColVarWeights(), and setColVar().
colVarBondList
shared_ptr<FixedPairList> espressopp::interaction::PotentialTemplate< TabulatedSubEns >::colVarBondList protected inherited
Definition at line 153 of file Potential.hpp.
Referenced by setColVar().
colVarBondListSize
int espressopp::interaction::TabulatedSubEns::colVarBondListSize private
Definition at line 64 of file TabulatedSubEns.hpp.
Referenced by computeColVarWeights(), and setColVar().
colVarDihedList
shared_ptr<FixedQuadrupleList> espressopp::interaction::PotentialTemplate< TabulatedSubEns >::colVarDihedList protected inherited
Definition at line 157 of file Potential.hpp.
Referenced by setColVar().
colVarDihedListSize
int espressopp::interaction::TabulatedSubEns::colVarDihedListSize private
Definition at line 66 of file TabulatedSubEns.hpp.
Referenced by setColVar().
colVarRef
RealNDs espressopp::interaction::TabulatedSubEns::colVarRef private
Definition at line 51 of file TabulatedSubEns.hpp.
Referenced by addInteraction(), computeColVarWeights(), getColVarRefs(), setColVarRef(), and setFilenames().
colVarSd
RealND espressopp::interaction::TabulatedSubEns::colVarSd private
Definition at line 60 of file TabulatedSubEns.hpp.
Referenced by computeColVarWeights(), and getColVarSds().
cutoff
real espressopp::interaction::PotentialTemplate< TabulatedSubEns >::cutoff protected inherited
Definition at line 148 of file Potential.hpp.
cutoffSqr
real espressopp::interaction::PotentialTemplate< TabulatedSubEns >::cutoffSqr protected inherited
Definition at line 149 of file Potential.hpp.
filenames
std::vector<std::string> espressopp::interaction::TabulatedSubEns::filenames private
Definition at line 47 of file TabulatedSubEns.hpp.
Referenced by addInteraction(), and setFilenames().
interpolationType
int espressopp::interaction::TabulatedSubEns::interpolationType private
Definition at line 49 of file TabulatedSubEns.hpp.
Referenced by getInterpolationType().
numInteractions
int espressopp::interaction::TabulatedSubEns::numInteractions private
Definition at line 46 of file TabulatedSubEns.hpp.
Referenced by _computeEnergySqrRaw(), _computeForceRaw(), addInteraction(), computeColVarWeights(), getDimension(), setColVarRef(), and setFilenames().
shift
real espressopp::interaction::PotentialTemplate< TabulatedSubEns >::shift protected inherited
Definition at line 150 of file Potential.hpp.
tables
std::vector<shared_ptr <Interpolation> > espressopp::interaction::TabulatedSubEns::tables private
Definition at line 48 of file TabulatedSubEns.hpp.
Referenced by addInteraction(), and setFilenames().
targetProb
RealND espressopp::interaction::TabulatedSubEns::targetProb private
Definition at line 55 of file TabulatedSubEns.hpp.
Referenced by addInteraction(), computeColVarWeights(), and getTargetProb().
weightCounts
int espressopp::interaction::TabulatedSubEns::weightCounts private
Definition at line 58 of file TabulatedSubEns.hpp.
Referenced by computeColVarWeights().
weights
RealND espressopp::interaction::TabulatedSubEns::weights private
Definition at line 53 of file TabulatedSubEns.hpp.
Referenced by addInteraction(), computeColVarWeights(), and getWeights().
weightSum
RealND espressopp::interaction::TabulatedSubEns::weightSum private
Definition at line 57 of file TabulatedSubEns.hpp.
Referenced by addInteraction(), and computeColVarWeights().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/TabulatedSubEns.hpp
/home/espressopp/espressopp/src/interaction/TabulatedSubEns.cpp