ESPResSo++: espressopp::interaction::CoulombRSpace Class Reference
espressopp::interaction::CoulombRSpace Class Reference
#include <CoulombRSpace.hpp>
Public Member Functions
CoulombRSpace ()
CoulombRSpace (real _prefactor, real _alpha, real _rspacecutoff)
void preset ()
void setAlpha (real _alpha)
real getAlpha () const
void setPrefactor (real _prefactor)
real getPrefactor () const
real _computeEnergy (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &dist, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)
virtual shared_ptr< FixedPairList > getColVarBondList () const
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &fpl)
virtual shared_ptr< FixedTripleList > getColVarAngleList () const
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fpl)
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const
virtual void setColVar (const RealND &cv)
virtual void setColVar (const Real3D &dist, const bc::BC &bc)
virtual RealND getColVar () const
virtual void computeColVarWeights (const Real3D &dist, const bc::BC &bc)
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
real _computeEnergyDeriv (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
CoulombRSpace * derived_this ()
const CoulombRSpace * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
shared_ptr< FixedPairList > colVarBondList
shared_ptr< FixedTripleList > colVarAngleList
shared_ptr< FixedQuadrupleList > colVarDihedList
RealND colVar
Private Attributes
real alpha
real prefactor
real factor
real alpha2
Detailed Description
Definition at line 41 of file CoulombRSpace.hpp.
Constructor & Destructor Documentation
CoulombRSpace() [1/2]
espressopp::interaction::CoulombRSpace::CoulombRSpace () inline
Definition at line 53 of file CoulombRSpace.hpp.
References espressopp::infinity.
CoulombRSpace() [2/2]
espressopp::interaction::CoulombRSpace::CoulombRSpace (real _prefactor, real _alpha, real _rspacecutoff) inline
Definition at line 60 of file CoulombRSpace.hpp.
Member Function Documentation
_computeEnergy() [1/4]
real espressopp::interaction::CoulombRSpace::_computeEnergy (const Particle & p1, const Particle & p2) const inline
Definition at line 85 of file CoulombRSpace.hpp.
References espressopp::Real3D::abs(), espressopp::Particle::position(), and espressopp::Particle::q().
_computeEnergy() [2/4]
real espressopp::interaction::PotentialTemplate< CoulombRSpace >::_computeEnergy (const Real3D & dist) const inline inherited
Definition at line 367 of file Potential.hpp.
_computeEnergy() [3/4]
real espressopp::interaction::PotentialTemplate< CoulombRSpace >::_computeEnergy (real dist) const inline inherited
Definition at line 374 of file Potential.hpp.
_computeEnergy() [4/4]
real espressopp::interaction::PotentialTemplate< CoulombRSpace >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 360 of file Potential.hpp.
_computeEnergyDeriv()
real espressopp::interaction::PotentialTemplate< CoulombRSpace >::_computeEnergyDeriv (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 395 of file Potential.hpp.
_computeEnergySqr()
real espressopp::interaction::PotentialTemplate< CoulombRSpace >::_computeEnergySqr (real distSqr) const inline inherited
Definition at line 381 of file Potential.hpp.
_computeEnergySqrRaw()
real espressopp::interaction::CoulombRSpace::_computeEnergySqrRaw (real distSqr) const inline
Definition at line 102 of file CoulombRSpace.hpp.
_computeForce() [1/3]
bool espressopp::interaction::CoulombRSpace::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const inline
Definition at line 91 of file CoulombRSpace.hpp.
References espressopp::Real3D::abs(), espressopp::Particle::position(), espressopp::Particle::q(), and espressopp::Real3D::sqr().
_computeForce() [2/3]
bool espressopp::interaction::PotentialTemplate< CoulombRSpace >::_computeForce (Real3D & force, const Real3D & dist) const inline inherited
Definition at line 438 of file Potential.hpp.
_computeForce() [3/3]
bool espressopp::interaction::PotentialTemplate< CoulombRSpace >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 431 of file Potential.hpp.
_computeForceRaw()
bool espressopp::interaction::CoulombRSpace::_computeForceRaw (Real3D & force, const Real3D & dist, real distSqr) const inline
Definition at line 106 of file CoulombRSpace.hpp.
computeColVarWeights()
void espressopp::interaction::PotentialTemplate< CoulombRSpace >::computeColVarWeights (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 315 of file Potential.hpp.
computeEnergy() [1/3]
real espressopp::interaction::PotentialTemplate< CoulombRSpace >::computeEnergy (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 323 of file Potential.hpp.
computeEnergy() [2/3]
real espressopp::interaction::PotentialTemplate< CoulombRSpace >::computeEnergy (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 331 of file Potential.hpp.
computeEnergy() [3/3]
real espressopp::interaction::PotentialTemplate< CoulombRSpace >::computeEnergy (real dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 338 of file Potential.hpp.
computeEnergySqr()
real espressopp::interaction::PotentialTemplate< CoulombRSpace >::computeEnergySqr (real distsqr) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 345 of file Potential.hpp.
computeForce() [1/2]
Real3D espressopp::interaction::PotentialTemplate< CoulombRSpace >::computeForce (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 405 of file Potential.hpp.
computeForce() [2/2]
Real3D espressopp::interaction::PotentialTemplate< CoulombRSpace >::computeForce (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 413 of file Potential.hpp.
derived_this() [1/2]
CoulombRSpace * espressopp::interaction::PotentialTemplate< CoulombRSpace >::derived_this () inline protected inherited
Definition at line 161 of file Potential.hpp.
derived_this() [2/2]
const CoulombRSpace * espressopp::interaction::PotentialTemplate< CoulombRSpace >::derived_this () const inline protected inherited
Definition at line 165 of file Potential.hpp.
getAlpha()
real espressopp::interaction::CoulombRSpace::getAlpha () const inline
Definition at line 76 of file CoulombRSpace.hpp.
Referenced by registerPython().
getColVar()
RealND espressopp::interaction::PotentialTemplate< CoulombRSpace >::getColVar () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 309 of file Potential.hpp.
getColVarAngleList()
shared_ptr< FixedTripleList > espressopp::interaction::PotentialTemplate< CoulombRSpace >::getColVarAngleList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 273 of file Potential.hpp.
getColVarBondList()
shared_ptr< FixedPairList > espressopp::interaction::PotentialTemplate< CoulombRSpace >::getColVarBondList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 259 of file Potential.hpp.
getColVarDihedList()
shared_ptr< FixedQuadrupleList > espressopp::interaction::PotentialTemplate< CoulombRSpace >::getColVarDihedList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 287 of file Potential.hpp.
getCutoff()
real espressopp::interaction::PotentialTemplate< CoulombRSpace >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 210 of file Potential.hpp.
getPrefactor()
real espressopp::interaction::CoulombRSpace::getPrefactor () const inline
Definition at line 81 of file CoulombRSpace.hpp.
Referenced by registerPython().
getShift()
real espressopp::interaction::PotentialTemplate< CoulombRSpace >::getShift () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 225 of file Potential.hpp.
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
Referenced by espressopp::interaction::Potential::~Potential().
preset()
void espressopp::interaction::CoulombRSpace::preset () inline
Definition at line 66 of file CoulombRSpace.hpp.
References M_2_SQRTPIl.
registerPython()
void espressopp::interaction::CoulombRSpace::registerPython () static
Definition at line 38 of file CoulombRSpace.cpp.
References getAlpha(), getPrefactor(), setAlpha(), and setPrefactor().
Referenced by espressopp::interaction::registerPython().
setAlpha()
void espressopp::interaction::CoulombRSpace::setAlpha (real _alpha) inline
Definition at line 72 of file CoulombRSpace.hpp.
Referenced by registerPython().
setAutoShift()
real espressopp::interaction::PotentialTemplate< CoulombRSpace >::setAutoShift () inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 231 of file Potential.hpp.
setColVar() [1/2]
void espressopp::interaction::PotentialTemplate< CoulombRSpace >::setColVar (const RealND & cv) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 294 of file Potential.hpp.
setColVar() [2/2]
void espressopp::interaction::PotentialTemplate< CoulombRSpace >::setColVar (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 301 of file Potential.hpp.
setColVarAngleList()
void espressopp::interaction::PotentialTemplate< CoulombRSpace >::setColVarAngleList (const shared_ptr< FixedTripleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 266 of file Potential.hpp.
setColVarBondList()
void espressopp::interaction::PotentialTemplate< CoulombRSpace >::setColVarBondList (const shared_ptr< FixedPairList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 252 of file Potential.hpp.
setColVarDihedList()
void espressopp::interaction::PotentialTemplate< CoulombRSpace >::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 280 of file Potential.hpp.
setCutoff()
void espressopp::interaction::PotentialTemplate< CoulombRSpace >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 201 of file Potential.hpp.
setPrefactor()
void espressopp::interaction::CoulombRSpace::setPrefactor (real _prefactor) inline
Definition at line 77 of file CoulombRSpace.hpp.
Referenced by registerPython().
setShift()
void espressopp::interaction::PotentialTemplate< CoulombRSpace >::setShift (real _shift) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 216 of file Potential.hpp.
updateAutoShift()
void espressopp::interaction::PotentialTemplate< CoulombRSpace >::updateAutoShift () inline inherited
Definition at line 244 of file Potential.hpp.
Member Data Documentation
alpha
real espressopp::interaction::CoulombRSpace::alpha private
Definition at line 43 of file CoulombRSpace.hpp.
alpha2
real espressopp::interaction::CoulombRSpace::alpha2 private
Definition at line 47 of file CoulombRSpace.hpp.
autoShift
bool espressopp::interaction::PotentialTemplate< CoulombRSpace >::autoShift protected inherited
Definition at line 151 of file Potential.hpp.
colVar
RealND espressopp::interaction::PotentialTemplate< CoulombRSpace >::colVar protected inherited
Definition at line 159 of file Potential.hpp.
colVarAngleList
shared_ptr<FixedTripleList> espressopp::interaction::PotentialTemplate< CoulombRSpace >::colVarAngleList protected inherited
Definition at line 155 of file Potential.hpp.
colVarBondList
shared_ptr<FixedPairList> espressopp::interaction::PotentialTemplate< CoulombRSpace >::colVarBondList protected inherited
Definition at line 153 of file Potential.hpp.
colVarDihedList
shared_ptr<FixedQuadrupleList> espressopp::interaction::PotentialTemplate< CoulombRSpace >::colVarDihedList protected inherited
Definition at line 157 of file Potential.hpp.
cutoff
real espressopp::interaction::PotentialTemplate< CoulombRSpace >::cutoff protected inherited
Definition at line 148 of file Potential.hpp.
cutoffSqr
real espressopp::interaction::PotentialTemplate< CoulombRSpace >::cutoffSqr protected inherited
Definition at line 149 of file Potential.hpp.
factor
real espressopp::interaction::CoulombRSpace::factor private
Definition at line 47 of file CoulombRSpace.hpp.
prefactor
real espressopp::interaction::CoulombRSpace::prefactor private
Definition at line 44 of file CoulombRSpace.hpp.
shift
real espressopp::interaction::PotentialTemplate< CoulombRSpace >::shift protected inherited
Definition at line 150 of file Potential.hpp.
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/CoulombRSpace.hpp
/home/espressopp/espressopp/src/interaction/CoulombRSpace.cpp