ESPResSo++: espressopp::interaction::ReactionFieldGeneralized Class Reference
espressopp::interaction::ReactionFieldGeneralized Class Reference
#include <ReactionFieldGeneralized.hpp>
Public Member Functions
ReactionFieldGeneralized ()
ReactionFieldGeneralized (real _prefactor, real _kappa, real _eps1, real _eps2, real _cutoff, real _shift)
ReactionFieldGeneralized (real _prefactor, real _kappa, real _eps1, real _eps2, real _cutoff)
real getKappa () const
real getEpsilon1 () const
real getEpsilon2 () const
void setCutoff (real _cutoff)
void setPrefactor (real _prefactor)
real getPrefactor () const
real _computeEnergy (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &dist, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)
virtual shared_ptr< FixedPairList > getColVarBondList () const
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &fpl)
virtual shared_ptr< FixedTripleList > getColVarAngleList () const
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fpl)
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const
virtual void setColVar (const RealND &cv)
virtual void setColVar (const Real3D &dist, const bc::BC &bc)
virtual RealND getColVar () const
virtual void computeColVarWeights (const Real3D &dist, const bc::BC &bc)
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
real _computeEnergyDeriv (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
ReactionFieldGeneralized * derived_this ()
const ReactionFieldGeneralized * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
shared_ptr< FixedPairList > colVarBondList
shared_ptr< FixedTripleList > colVarAngleList
shared_ptr< FixedQuadrupleList > colVarDihedList
RealND colVar
Private Member Functions
void initialize ()
Private Attributes
real kappa
real epsilon1
real epsilon2
real rc
real rc3
real rc2
real B1
real B0
real B1_half
real prefactor
real crf
Detailed Description
Definition at line 38 of file ReactionFieldGeneralized.hpp.
Constructor & Destructor Documentation
ReactionFieldGeneralized() [1/3]
espressopp::interaction::ReactionFieldGeneralized::ReactionFieldGeneralized () inline
Definition at line 71 of file ReactionFieldGeneralized.hpp.
References espressopp::infinity.
ReactionFieldGeneralized() [2/3]
espressopp::interaction::ReactionFieldGeneralized::ReactionFieldGeneralized (real _prefactor, real _kappa, real _eps1, real _eps2, real _cutoff, real _shift) inline
Definition at line 80 of file ReactionFieldGeneralized.hpp.
ReactionFieldGeneralized() [3/3]
espressopp::interaction::ReactionFieldGeneralized::ReactionFieldGeneralized (real _prefactor, real _kappa, real _eps1, real _eps2, real _cutoff) inline
Definition at line 96 of file ReactionFieldGeneralized.hpp.
Member Function Documentation
_computeEnergy() [1/4]
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::_computeEnergy (const Real3D & dist) const inline inherited
Definition at line 367 of file Potential.hpp.
_computeEnergy() [2/4]
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::_computeEnergy (real dist) const inline inherited
Definition at line 374 of file Potential.hpp.
_computeEnergy() [3/4]
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 360 of file Potential.hpp.
_computeEnergy() [4/4]
real espressopp::interaction::ReactionFieldGeneralized::_computeEnergy (const Particle & p1, const Particle & p2) const inline
Definition at line 132 of file ReactionFieldGeneralized.hpp.
References espressopp::Particle::position(), espressopp::Particle::q(), and espressopp::Real3D::sqr().
_computeEnergyDeriv()
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::_computeEnergyDeriv (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 395 of file Potential.hpp.
_computeEnergySqr()
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::_computeEnergySqr (real distSqr) const inline inherited
Definition at line 381 of file Potential.hpp.
_computeEnergySqrRaw()
real espressopp::interaction::ReactionFieldGeneralized::_computeEnergySqrRaw (real distSqr) const inline
Definition at line 206 of file ReactionFieldGeneralized.hpp.
_computeForce() [1/3]
bool espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::_computeForce (Real3D & force, const Real3D & dist) const inline inherited
Definition at line 438 of file Potential.hpp.
_computeForce() [2/3]
bool espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 431 of file Potential.hpp.
_computeForce() [3/3]
bool espressopp::interaction::ReactionFieldGeneralized::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const inline
Definition at line 172 of file ReactionFieldGeneralized.hpp.
References espressopp::Particle::position(), espressopp::Particle::q(), and espressopp::Real3D::sqr().
_computeForceRaw()
bool espressopp::interaction::ReactionFieldGeneralized::_computeForceRaw (Real3D & force, const Real3D & dist, real distSqr) const inline
Definition at line 211 of file ReactionFieldGeneralized.hpp.
computeColVarWeights()
void espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::computeColVarWeights (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 315 of file Potential.hpp.
computeEnergy() [1/3]
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::computeEnergy (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 323 of file Potential.hpp.
computeEnergy() [2/3]
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::computeEnergy (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 331 of file Potential.hpp.
computeEnergy() [3/3]
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::computeEnergy (real dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 338 of file Potential.hpp.
computeEnergySqr()
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::computeEnergySqr (real distsqr) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 345 of file Potential.hpp.
computeForce() [1/2]
Real3D espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::computeForce (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 405 of file Potential.hpp.
computeForce() [2/2]
Real3D espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::computeForce (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 413 of file Potential.hpp.
derived_this() [1/2]
ReactionFieldGeneralized * espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::derived_this () inline protected inherited
Definition at line 161 of file Potential.hpp.
derived_this() [2/2]
const ReactionFieldGeneralized * espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::derived_this () const inline protected inherited
Definition at line 165 of file Potential.hpp.
getColVar()
RealND espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::getColVar () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 309 of file Potential.hpp.
getColVarAngleList()
shared_ptr< FixedTripleList > espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::getColVarAngleList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 273 of file Potential.hpp.
getColVarBondList()
shared_ptr< FixedPairList > espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::getColVarBondList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 259 of file Potential.hpp.
getColVarDihedList()
shared_ptr< FixedQuadrupleList > espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::getColVarDihedList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 287 of file Potential.hpp.
getCutoff()
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 210 of file Potential.hpp.
getEpsilon1()
real espressopp::interaction::ReactionFieldGeneralized::getEpsilon1 () const inline
Definition at line 114 of file ReactionFieldGeneralized.hpp.
Referenced by espressopp::interaction::ReactionFieldGeneralized_pickle::getinitargs().
getEpsilon2()
real espressopp::interaction::ReactionFieldGeneralized::getEpsilon2 () const inline
Definition at line 115 of file ReactionFieldGeneralized.hpp.
Referenced by espressopp::interaction::ReactionFieldGeneralized_pickle::getinitargs().
getKappa()
real espressopp::interaction::ReactionFieldGeneralized::getKappa () const inline
Definition at line 113 of file ReactionFieldGeneralized.hpp.
Referenced by espressopp::interaction::ReactionFieldGeneralized_pickle::getinitargs().
getPrefactor()
real espressopp::interaction::ReactionFieldGeneralized::getPrefactor () const inline
Definition at line 128 of file ReactionFieldGeneralized.hpp.
Referenced by espressopp::interaction::ReactionFieldGeneralized_pickle::getinitargs(), and registerPython().
getShift()
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::getShift () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 225 of file Potential.hpp.
initialize()
void espressopp::interaction::ReactionFieldGeneralized::initialize () inline private
Definition at line 51 of file ReactionFieldGeneralized.hpp.
References espressopp::analysis::registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
Referenced by espressopp::interaction::Potential::~Potential().
registerPython()
void espressopp::interaction::ReactionFieldGeneralized::registerPython () static
Definition at line 61 of file ReactionFieldGeneralized.cpp.
References getPrefactor(), and setPrefactor().
Referenced by espressopp::interaction::registerPython().
setAutoShift()
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::setAutoShift () inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 231 of file Potential.hpp.
setColVar() [1/2]
void espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::setColVar (const RealND & cv) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 294 of file Potential.hpp.
setColVar() [2/2]
void espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::setColVar (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 301 of file Potential.hpp.
setColVarAngleList()
void espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::setColVarAngleList (const shared_ptr< FixedTripleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 266 of file Potential.hpp.
setColVarBondList()
void espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::setColVarBondList (const shared_ptr< FixedPairList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 252 of file Potential.hpp.
setColVarDihedList()
void espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 280 of file Potential.hpp.
setCutoff()
void espressopp::interaction::ReactionFieldGeneralized::setCutoff (real _cutoff) inline virtual
Reimplemented from espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >.
Definition at line 117 of file ReactionFieldGeneralized.hpp.
setPrefactor()
void espressopp::interaction::ReactionFieldGeneralized::setPrefactor (real _prefactor) inline
Definition at line 124 of file ReactionFieldGeneralized.hpp.
Referenced by registerPython().
setShift()
void espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::setShift (real _shift) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 216 of file Potential.hpp.
updateAutoShift()
void espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::updateAutoShift () inline inherited
Definition at line 244 of file Potential.hpp.
Member Data Documentation
autoShift
bool espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::autoShift protected inherited
Definition at line 151 of file Potential.hpp.
B0
real espressopp::interaction::ReactionFieldGeneralized::B0 private
Definition at line 46 of file ReactionFieldGeneralized.hpp.
B1
real espressopp::interaction::ReactionFieldGeneralized::B1 private
Definition at line 46 of file ReactionFieldGeneralized.hpp.
B1_half
real espressopp::interaction::ReactionFieldGeneralized::B1_half private
Definition at line 46 of file ReactionFieldGeneralized.hpp.
colVar
RealND espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::colVar protected inherited
Definition at line 159 of file Potential.hpp.
colVarAngleList
shared_ptr<FixedTripleList> espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::colVarAngleList protected inherited
Definition at line 155 of file Potential.hpp.
colVarBondList
shared_ptr<FixedPairList> espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::colVarBondList protected inherited
Definition at line 153 of file Potential.hpp.
colVarDihedList
shared_ptr<FixedQuadrupleList> espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::colVarDihedList protected inherited
Definition at line 157 of file Potential.hpp.
crf
real espressopp::interaction::ReactionFieldGeneralized::crf private
Definition at line 48 of file ReactionFieldGeneralized.hpp.
cutoff
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::cutoff protected inherited
Definition at line 148 of file Potential.hpp.
cutoffSqr
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::cutoffSqr protected inherited
Definition at line 149 of file Potential.hpp.
epsilon1
real espressopp::interaction::ReactionFieldGeneralized::epsilon1 private
Definition at line 43 of file ReactionFieldGeneralized.hpp.
epsilon2
real espressopp::interaction::ReactionFieldGeneralized::epsilon2 private
Definition at line 43 of file ReactionFieldGeneralized.hpp.
kappa
real espressopp::interaction::ReactionFieldGeneralized::kappa private
Definition at line 42 of file ReactionFieldGeneralized.hpp.
prefactor
real espressopp::interaction::ReactionFieldGeneralized::prefactor private
Definition at line 47 of file ReactionFieldGeneralized.hpp.
rc
real espressopp::interaction::ReactionFieldGeneralized::rc private
Definition at line 44 of file ReactionFieldGeneralized.hpp.
rc2
real espressopp::interaction::ReactionFieldGeneralized::rc2 private
Definition at line 45 of file ReactionFieldGeneralized.hpp.
rc3
real espressopp::interaction::ReactionFieldGeneralized::rc3 private
Definition at line 44 of file ReactionFieldGeneralized.hpp.
shift
real espressopp::interaction::PotentialTemplate< ReactionFieldGeneralized >::shift protected inherited
Definition at line 150 of file Potential.hpp.
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/ReactionFieldGeneralized.hpp
/home/espressopp/espressopp/src/interaction/ReactionFieldGeneralized.cpp