ESPResSo++: espressopp::interaction::Interpolation Class Reference
espressopp::interaction::Interpolation Class Reference abstract
#include <Interpolation.hpp>
Public Member Functions
virtual real getEnergy (real r) const =0
virtual real getForce (real r) const =0
virtual void read (mpi::communicator comm, const char *file)=0
Detailed Description
Definition at line 35 of file Interpolation.hpp.
Member Function Documentation
getEnergy()
virtual real espressopp::interaction::Interpolation::getEnergy (real r) const pure virtual
Implemented in espressopp::interaction::InterpolationTemplate< Derived >, espressopp::interaction::InterpolationTemplate< InterpolationAkima >, espressopp::interaction::InterpolationTemplate< InterpolationCubic >, and espressopp::interaction::InterpolationTemplate< InterpolationLinear >.
Referenced by espressopp::interaction::InterpolationTemplate< InterpolationLinear >::InterpolationTemplate().
getForce()
virtual real espressopp::interaction::Interpolation::getForce (real r) const pure virtual
Implemented in espressopp::interaction::InterpolationTemplate< Derived >, espressopp::interaction::InterpolationTemplate< InterpolationAkima >, espressopp::interaction::InterpolationTemplate< InterpolationCubic >, and espressopp::interaction::InterpolationTemplate< InterpolationLinear >.
Referenced by espressopp::interaction::InterpolationTemplate< InterpolationLinear >::getEnergy().
read()
virtual void espressopp::interaction::Interpolation::read (mpi::communicator comm, const char * file) pure virtual
Implemented in espressopp::interaction::InterpolationTemplate< Derived >, espressopp::interaction::InterpolationTemplate< InterpolationAkima >, espressopp::interaction::InterpolationTemplate< InterpolationCubic >, and espressopp::interaction::InterpolationTemplate< InterpolationLinear >.
Referenced by espressopp::interaction::InterpolationTemplate< InterpolationLinear >::getForce().
The documentation for this class was generated from the following file:
/home/espressopp/espressopp/src/interaction/Interpolation.hpp