ESPResSo++: espressopp::interaction::LennardJonesExpand Class Reference
espressopp::interaction::LennardJonesExpand Class Reference
#include <LennardJonesExpand.hpp>
Public Member Functions
LennardJonesExpand ()
LennardJonesExpand (real _epsilon, real _sigma, real _delta, real _cutoff, real _shift)
LennardJonesExpand (real _epsilon, real _sigma, real _delta, real _cutoff)
void setEpsilon (real _epsilon)
real getEpsilon () const
void setSigma (real _sigma)
real getSigma () const
void setDelta (real _delta)
real getDelta () const
real _computeEnergySqrRaw (real distSqr) const
bool _computeForceRaw (Real3D &force, const Real3D &dist, real distSqr) const
virtual real computeEnergy (const Particle &p1, const Particle &p2) const
virtual real computeEnergy (const Real3D &dist) const
virtual real computeEnergy (real dist) const
virtual real computeEnergySqr (real distsqr) const
virtual Real3D computeForce (const Particle &p1, const Particle &p2) const
virtual Real3D computeForce (const Real3D &dist) const
virtual void setCutoff (real _cutoff)
virtual real getCutoff () const
virtual void setShift (real _shift)
virtual real getShift () const
virtual real setAutoShift ()
void updateAutoShift ()
virtual void setColVarBondList (const shared_ptr< FixedPairList > &fpl)
virtual shared_ptr< FixedPairList > getColVarBondList () const
virtual void setColVarAngleList (const shared_ptr< FixedTripleList > &fpl)
virtual shared_ptr< FixedTripleList > getColVarAngleList () const
virtual void setColVarDihedList (const shared_ptr< FixedQuadrupleList > &fpl)
virtual shared_ptr< FixedQuadrupleList > getColVarDihedList () const
virtual void setColVar (const RealND &cv)
virtual void setColVar (const Real3D &dist, const bc::BC &bc)
virtual RealND getColVar () const
virtual void computeColVarWeights (const Real3D &dist, const bc::BC &bc)
real _computeEnergy (const Particle &p1, const Particle &p2) const
real _computeEnergy (const Real3D &dist) const
real _computeEnergy (real dist) const
real _computeEnergy (const Particle &p1, const Particle &p2, const Real3D &dist) const
real _computeEnergySqr (real distSqr) const
real _computeEnergyDeriv (const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2) const
bool _computeForce (Real3D &force, const Real3D &dist) const
bool _computeForce (Real3D &force, const Particle &p1, const Particle &p2, const Real3D &dist) const
Static Public Member Functions
static void registerPython ()
static LOG4ESPP_DECL_LOGGER (theLogger)
Protected Member Functions
LennardJonesExpand * derived_this ()
const LennardJonesExpand * derived_this () const
Protected Attributes
real cutoff
real cutoffSqr
real shift
bool autoShift
shared_ptr< FixedPairList > colVarBondList
shared_ptr< FixedTripleList > colVarAngleList
shared_ptr< FixedQuadrupleList > colVarDihedList
RealND colVar
Private Attributes
real epsilon
real sigma
real delta
Detailed Description
Definition at line 32 of file LennardJonesExpand.hpp.
Constructor & Destructor Documentation
LennardJonesExpand() [1/3]
espressopp::interaction::LennardJonesExpand::LennardJonesExpand () inline
Definition at line 41 of file LennardJonesExpand.hpp.
References espressopp::infinity, espressopp::interaction::PotentialTemplate< LennardJonesExpand >::setCutoff(), and espressopp::interaction::PotentialTemplate< LennardJonesExpand >::setShift().
LennardJonesExpand() [2/3]
espressopp::interaction::LennardJonesExpand::LennardJonesExpand (real _epsilon, real _sigma, real _delta, real _cutoff, real _shift) inline
Definition at line 47 of file LennardJonesExpand.hpp.
References espressopp::interaction::PotentialTemplate< LennardJonesExpand >::setCutoff(), and espressopp::interaction::PotentialTemplate< LennardJonesExpand >::setShift().
LennardJonesExpand() [3/3]
espressopp::interaction::LennardJonesExpand::LennardJonesExpand (real _epsilon, real _sigma, real _delta, real _cutoff) inline
Definition at line 53 of file LennardJonesExpand.hpp.
References espressopp::interaction::PotentialTemplate< LennardJonesExpand >::autoShift, espressopp::interaction::PotentialTemplate< LennardJonesExpand >::setAutoShift(), and espressopp::interaction::PotentialTemplate< LennardJonesExpand >::setCutoff().
Member Function Documentation
_computeEnergy() [1/4]
real espressopp::interaction::PotentialTemplate< LennardJonesExpand >::_computeEnergy (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 352 of file Potential.hpp.
_computeEnergy() [2/4]
real espressopp::interaction::PotentialTemplate< LennardJonesExpand >::_computeEnergy (const Real3D & dist) const inline inherited
Definition at line 367 of file Potential.hpp.
_computeEnergy() [3/4]
real espressopp::interaction::PotentialTemplate< LennardJonesExpand >::_computeEnergy (real dist) const inline inherited
Definition at line 374 of file Potential.hpp.
_computeEnergy() [4/4]
real espressopp::interaction::PotentialTemplate< LennardJonesExpand >::_computeEnergy (const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 360 of file Potential.hpp.
_computeEnergyDeriv()
real espressopp::interaction::PotentialTemplate< LennardJonesExpand >::_computeEnergyDeriv (const Particle & p1, const Particle & p2) const inline inherited
Definition at line 395 of file Potential.hpp.
_computeEnergySqr()
real espressopp::interaction::PotentialTemplate< LennardJonesExpand >::_computeEnergySqr (real distSqr) const inline inherited
Definition at line 381 of file Potential.hpp.
_computeEnergySqrRaw()
real espressopp::interaction::LennardJonesExpand::_computeEnergySqrRaw (real distSqr) const inline
Definition at line 79 of file LennardJonesExpand.hpp.
_computeForce() [1/3]
bool espressopp::interaction::PotentialTemplate< LennardJonesExpand >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2) const inline inherited
Definition at line 423 of file Potential.hpp.
_computeForce() [2/3]
bool espressopp::interaction::PotentialTemplate< LennardJonesExpand >::_computeForce (Real3D & force, const Real3D & dist) const inline inherited
Definition at line 438 of file Potential.hpp.
_computeForce() [3/3]
bool espressopp::interaction::PotentialTemplate< LennardJonesExpand >::_computeForce (Real3D & force, const Particle & p1, const Particle & p2, const Real3D & dist) const inline inherited
Definition at line 431 of file Potential.hpp.
_computeForceRaw()
bool espressopp::interaction::LennardJonesExpand::_computeForceRaw (Real3D & force, const Real3D & dist, real distSqr) const inline
Definition at line 86 of file LennardJonesExpand.hpp.
References delta.
computeColVarWeights()
void espressopp::interaction::PotentialTemplate< LennardJonesExpand >::computeColVarWeights (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 315 of file Potential.hpp.
computeEnergy() [1/3]
real espressopp::interaction::PotentialTemplate< LennardJonesExpand >::computeEnergy (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 323 of file Potential.hpp.
computeEnergy() [2/3]
real espressopp::interaction::PotentialTemplate< LennardJonesExpand >::computeEnergy (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 331 of file Potential.hpp.
computeEnergy() [3/3]
real espressopp::interaction::PotentialTemplate< LennardJonesExpand >::computeEnergy (real dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 338 of file Potential.hpp.
computeEnergySqr()
real espressopp::interaction::PotentialTemplate< LennardJonesExpand >::computeEnergySqr (real distsqr) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 345 of file Potential.hpp.
computeForce() [1/2]
Real3D espressopp::interaction::PotentialTemplate< LennardJonesExpand >::computeForce (const Particle & p1, const Particle & p2) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 405 of file Potential.hpp.
computeForce() [2/2]
Real3D espressopp::interaction::PotentialTemplate< LennardJonesExpand >::computeForce (const Real3D & dist) const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 413 of file Potential.hpp.
derived_this() [1/2]
LennardJonesExpand * espressopp::interaction::PotentialTemplate< LennardJonesExpand >::derived_this () inline protected inherited
Definition at line 161 of file Potential.hpp.
derived_this() [2/2]
const LennardJonesExpand * espressopp::interaction::PotentialTemplate< LennardJonesExpand >::derived_this () const inline protected inherited
Definition at line 165 of file Potential.hpp.
getColVar()
RealND espressopp::interaction::PotentialTemplate< LennardJonesExpand >::getColVar () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 309 of file Potential.hpp.
getColVarAngleList()
shared_ptr< FixedTripleList > espressopp::interaction::PotentialTemplate< LennardJonesExpand >::getColVarAngleList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 273 of file Potential.hpp.
getColVarBondList()
shared_ptr< FixedPairList > espressopp::interaction::PotentialTemplate< LennardJonesExpand >::getColVarBondList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 259 of file Potential.hpp.
getColVarDihedList()
shared_ptr< FixedQuadrupleList > espressopp::interaction::PotentialTemplate< LennardJonesExpand >::getColVarDihedList () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 287 of file Potential.hpp.
getCutoff()
real espressopp::interaction::PotentialTemplate< LennardJonesExpand >::getCutoff () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 210 of file Potential.hpp.
getDelta()
real espressopp::interaction::LennardJonesExpand::getDelta () const inline
Definition at line 77 of file LennardJonesExpand.hpp.
References delta.
Referenced by espressopp::interaction::LennardJonesExpand_pickle::getinitargs(), and registerPython().
getEpsilon()
real espressopp::interaction::LennardJonesExpand::getEpsilon () const inline
Definition at line 65 of file LennardJonesExpand.hpp.
References epsilon.
Referenced by espressopp::interaction::LennardJonesExpand_pickle::getinitargs(), and registerPython().
getShift()
real espressopp::interaction::PotentialTemplate< LennardJonesExpand >::getShift () const inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 225 of file Potential.hpp.
getSigma()
real espressopp::interaction::LennardJonesExpand::getSigma () const inline
Definition at line 71 of file LennardJonesExpand.hpp.
References sigma.
Referenced by espressopp::interaction::LennardJonesExpand_pickle::getinitargs(), and registerPython().
LOG4ESPP_DECL_LOGGER()
static espressopp::interaction::Potential::LOG4ESPP_DECL_LOGGER (theLogger) static inherited
Referenced by espressopp::interaction::Potential::~Potential().
registerPython()
void espressopp::interaction::LennardJonesExpand::registerPython () static
Definition at line 42 of file LennardJonesExpand.cpp.
References getDelta(), getEpsilon(), getSigma(), setDelta(), setEpsilon(), and setSigma().
Referenced by espressopp::interaction::registerPython().
setAutoShift()
real espressopp::interaction::PotentialTemplate< LennardJonesExpand >::setAutoShift () inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 231 of file Potential.hpp.
Referenced by LennardJonesExpand().
setColVar() [1/2]
void espressopp::interaction::PotentialTemplate< LennardJonesExpand >::setColVar (const RealND & cv) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 294 of file Potential.hpp.
setColVar() [2/2]
void espressopp::interaction::PotentialTemplate< LennardJonesExpand >::setColVar (const Real3D & dist, const bc::BC & bc) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 301 of file Potential.hpp.
setColVarAngleList()
void espressopp::interaction::PotentialTemplate< LennardJonesExpand >::setColVarAngleList (const shared_ptr< FixedTripleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 266 of file Potential.hpp.
setColVarBondList()
void espressopp::interaction::PotentialTemplate< LennardJonesExpand >::setColVarBondList (const shared_ptr< FixedPairList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 252 of file Potential.hpp.
setColVarDihedList()
void espressopp::interaction::PotentialTemplate< LennardJonesExpand >::setColVarDihedList (const shared_ptr< FixedQuadrupleList > & fpl) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 280 of file Potential.hpp.
setCutoff()
void espressopp::interaction::PotentialTemplate< LennardJonesExpand >::setCutoff (real _cutoff) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 201 of file Potential.hpp.
Referenced by LennardJonesExpand().
setDelta()
void espressopp::interaction::LennardJonesExpand::setDelta (real _delta) inline
Definition at line 73 of file LennardJonesExpand.hpp.
References espressopp::interaction::PotentialTemplate< LennardJonesExpand >::updateAutoShift().
Referenced by registerPython().
setEpsilon()
void espressopp::interaction::LennardJonesExpand::setEpsilon (real _epsilon) inline
Definition at line 61 of file LennardJonesExpand.hpp.
References espressopp::interaction::PotentialTemplate< LennardJonesExpand >::updateAutoShift().
Referenced by registerPython().
setShift()
void espressopp::interaction::PotentialTemplate< LennardJonesExpand >::setShift (real _shift) inline virtual inherited
Implements espressopp::interaction::Potential.
Definition at line 216 of file Potential.hpp.
Referenced by LennardJonesExpand().
setSigma()
void espressopp::interaction::LennardJonesExpand::setSigma (real _sigma) inline
Definition at line 67 of file LennardJonesExpand.hpp.
References espressopp::interaction::PotentialTemplate< LennardJonesExpand >::updateAutoShift().
Referenced by registerPython().
updateAutoShift()
void espressopp::interaction::PotentialTemplate< LennardJonesExpand >::updateAutoShift () inline inherited
Definition at line 244 of file Potential.hpp.
Referenced by setDelta(), setEpsilon(), and setSigma().
Member Data Documentation
autoShift
bool espressopp::interaction::PotentialTemplate< LennardJonesExpand >::autoShift protected inherited
Definition at line 151 of file Potential.hpp.
Referenced by LennardJonesExpand().
colVar
RealND espressopp::interaction::PotentialTemplate< LennardJonesExpand >::colVar protected inherited
Definition at line 159 of file Potential.hpp.
colVarAngleList
shared_ptr<FixedTripleList> espressopp::interaction::PotentialTemplate< LennardJonesExpand >::colVarAngleList protected inherited
Definition at line 155 of file Potential.hpp.
colVarBondList
shared_ptr<FixedPairList> espressopp::interaction::PotentialTemplate< LennardJonesExpand >::colVarBondList protected inherited
Definition at line 153 of file Potential.hpp.
colVarDihedList
shared_ptr<FixedQuadrupleList> espressopp::interaction::PotentialTemplate< LennardJonesExpand >::colVarDihedList protected inherited
Definition at line 157 of file Potential.hpp.
cutoff
real espressopp::interaction::PotentialTemplate< LennardJonesExpand >::cutoff protected inherited
Definition at line 148 of file Potential.hpp.
cutoffSqr
real espressopp::interaction::PotentialTemplate< LennardJonesExpand >::cutoffSqr protected inherited
Definition at line 149 of file Potential.hpp.
delta
real espressopp::interaction::LennardJonesExpand::delta private
Definition at line 36 of file LennardJonesExpand.hpp.
Referenced by _computeForceRaw(), and getDelta().
epsilon
real espressopp::interaction::LennardJonesExpand::epsilon private
Definition at line 34 of file LennardJonesExpand.hpp.
Referenced by getEpsilon().
shift
real espressopp::interaction::PotentialTemplate< LennardJonesExpand >::shift protected inherited
Definition at line 150 of file Potential.hpp.
sigma
real espressopp::interaction::LennardJonesExpand::sigma private
Definition at line 35 of file LennardJonesExpand.hpp.
Referenced by getSigma().
The documentation for this class was generated from the following files:
/home/espressopp/espressopp/src/interaction/LennardJonesExpand.hpp
/home/espressopp/espressopp/src/interaction/LennardJonesExpand.cpp